 NOTICE:  table "noded3" does not exist, skipping
 NOTICE:  CREATE TABLE will create implicit sequence "noded3_gid_seq" for serial column "noded3.gid"
 NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "noded3_pkey" for table "noded3"
public.noded3.the_geom SRID:0 TYPE:MULTILINESTRING DIMS:2 
---------------------------------
 NOTICE:  Cheking noded3 exists
 NOTICE:    -----> OK
 NOTICE:  checking the_geom and gid columns in  public.noded3 
 NOTICE:    ------>OK
 NOTICE:  checking that  gid is completely populated i.e. do not have NULL values
 NOTICE:    ------>OK
 NOTICE:  checking "source" and "target" columns in  public.noded3 
 NOTICE:    ------>OK
 NOTICE:  Checking the SRID of the geometry the_geom
 NOTICE:    -----> SRID found 0
 NOTICE:  initializing public.noded3_vertices_pgr
 NOTICE:  CREATE TABLE will create implicit sequence "noded3_vertices_pgr_id_seq" for serial column "noded3_vertices_pgr.id"
CONTEXT:  SQL statement "CREATE TABLE public.noded3_vertices_pgr (id bigserial PRIMARY KEY,cnt integer,chk integer,ein integer,eout integer)"
PL/pgSQL function "pgr_createtopology" line 127 at EXECUTE statement
 NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "noded3_vertices_pgr_pkey" for table "noded3_vertices_pgr"
CONTEXT:  SQL statement "CREATE TABLE public.noded3_vertices_pgr (id bigserial PRIMARY KEY,cnt integer,chk integer,ein integer,eout integer)"
PL/pgSQL function "pgr_createtopology" line 127 at EXECUTE statement
 NOTICE:  Creating Topology
 NOTICE:  0 out of aprox 0 edges processed
 NOTICE:    -----> DONE: 40 edges processed
OK
---------------------------------
 ERROR:  relation "vertices_tmp" does not exist
LINE 1: select * from vertices_tmp order by id;
                      ^
