psql:src/common/test/common-any-03.test:6: NOTICE:  Adding "ein" and "eout" columns to vertices_tmp
psql:src/common/test/common-any-03.test:6: NOTICE:  Zeroing columns "ein" and "eout" on "vertices_tmp".
psql:src/common/test/common-any-03.test:6: NOTICE:  Analyzing graph for one way street errors.
psql:src/common/test/common-any-03.test:6: NOTICE:  Analysis 25% complete ...
psql:src/common/test/common-any-03.test:6: NOTICE:  Analysis 50% complete ...
psql:src/common/test/common-any-03.test:6: NOTICE:  Analysis 75% complete ...
psql:src/common/test/common-any-03.test:6: NOTICE:  Analysis 100% complete ...
psql:src/common/test/common-any-03.test:6: NOTICE:  Found 3 potential problems at 'SELECT * FROM vertices_tmp WHERE ein=0 or eout=0'
OK
15|2||2|0|POINT(2 0.5)
17|2||2|0|POINT(1 1.5)
14|2||0|2|POINT(1 0.5)
