 NOTICE:  Cheking edges2 exists
 NOTICE:    -----> OK
 NOTICE:  Cheking for "source","target" and "dir" columns in edges2
 NOTICE:    ------>OK
 NOTICE:  Checking table public.edges2_vertices_pgr exists 
 NOTICE:    ------>OK
 NOTICE:  Cheking "id" column in public.edges2_vertices_pgr is indexed
 NOTICE:    ------>OK
 NOTICE:  Cheking for "ein" column in public.edges2_vertices_pgr
 NOTICE:    ------>OK
 NOTICE:  Cheking for "eout" column in public.edges2_vertices_pgr
 NOTICE:    ------>OK
 NOTICE:  Zeroing columns "ein" and "eout" on "public.edges2_vertices_pgr".
 NOTICE:  Analyzing graph for one way street errors.
 NOTICE:  Analysis 25% complete ...
 NOTICE:  Analysis 50% complete ...
 NOTICE:  Analysis 75% complete ...
 NOTICE:  Analysis 100% complete ...
 NOTICE:  Found 3 potential problems at 'SELECT * FROM public.edges2_vertices_pgr WHERE ein=0 or eout=0'
OK
17|2|0|2|0|POINT(1 1.5)
15|2|0|2|0|POINT(2 0.5)
14|2|0|0|2|POINT(1 0.5)
