public|streets
public|Streets
public|streets
public|
s1|streets
s1|Streets
s1|streets
s1|
s2|
s2|Streets
S2|streets
s3|Streets
s3|sTreets
s3|StrEets
s3|
s3|
s3|
s1|streets
s1|Streets
s1|streets
s1|
s1|streets
s1|Streets
s1|streets
s1|
s2|
s2|Streets
S2|streets
s3|Streets
s3|sTreets
s3|StrEets
s3|
s3|
s3|
|
-----TRUE----------------------------
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
t
-----FALSE----------------------------
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
-----TRUE----------------------------
t
t
t
t
t
t
t
t
t
t
t
t
t
t
-----FALSE----------------------------
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
