 NOTICE:  pgr_getTableName: This function will no longer be soported
public|edges2
 NOTICE:  pgr_getTableName: This function will no longer be soported
public|
 NOTICE:  pgr_getColumnName: This function will no longer be soported
source
 NOTICE:  pgr_getColumnName: This function will no longer be soported

 NOTICE:  pgr_getColumnName: This function will no longer be soported

 NOTICE:  pgr_getColumnName: This function will no longer be soported

 NOTICE:  pgr_isColumnInTable: This function will no longer be soported
t
 NOTICE:  pgr_isColumnInTable: This function will no longer be soported
f
 NOTICE:  pgr_isColumnInTable: This function will no longer be soported
f
 NOTICE:  pgr_isColumnInTable: This function will no longer be soported
f
 NOTICE:  pgr_isColumnIndexed: This function will no longer be soported
t
 NOTICE:  pgr_isColumnIndexed: This function will no longer be soported
f
 NOTICE:  pgr_versionless: This function will no longer be soported
t
 NOTICE:  pgr_versionless: This function will no longer be soported
t
 NOTICE:  pgr_versionless: This function will no longer be soported
t
 NOTICE:  pgr_isColumnInTable: This function will no longer be soported
idname.text
 NOTICE:  pgr_startPoint: This function will no longer be soported
010100000000000000000000400000000000000000
 NOTICE:  pgr_endPoint: This function will no longer be soported
01010000000000000000000040000000000000F03F
