all: BDATester

BDATester: BDATester.cpp BiDirAStar.cpp MinHeap.cpp BiDirAStar.h  MinHeap.h  utils.h
	g++ BDATester.cpp BiDirAStar.cpp MinHeap.cpp -o BDATester

clean:
	rm -f BDATester bdd?.txt output.txt
