PGROUTING: pgrouting::algorithms::Pgr_astar< G > Class Template Reference
pgrouting::algorithms::Pgr_astar< G > Class Template Reference
#include "pgr_astar.hpp"
Classes
class astar_many_goals_visitor
class for stopping when all targets are found
class astar_one_goal_visitor
visitor that terminates when we find the goal
class distance_heuristic
struct found_goals
exception for termination
Public Types
typedef G::B_G B_G
typedef G::V V
Public Member Functions
void clear ()
Astar
Path astar (G &graph, int64_t start_vertex, int64_t end_vertex, int heuristic, double factor, double epsilon, bool only_cost)
one to one astar 1 to 1
std::deque< Path > astar (G &graph, int64_t start_vertex, std::vector< int64_t > end_vertex, int heuristic, double factor, double epsilon, bool only_cost)
astar 1 to many
std::deque< Path > astar (G &graph, std::vector< int64_t > start_vertex, std::vector< int64_t > end_vertex, int heuristic, double factor, double epsilon, bool only_cost)
Private Member Functions
bool astar_1_to_1 (G &graph, V source, V target, int heuristic, double factor, double epsilon)
Call to Astar 1 source to 1 target.
bool astar_1_to_many (G &graph, V source, const std::vector< V > &targets, int heuristic, double factor, double epsilon)
Call to astar 1 source to many targets.
std::deque< Path > get_paths (const G &graph, V source, const std::vector< V > &targets, bool only_cost) const
Private Attributes
members;
std::vector< V > predecessors
std::vector< double > distances
std::deque< V > nodesInDistance
Detailed Description
template<class G>
class pgrouting::algorithms::Pgr_astar< G >
Definition at line 52 of file pgr_astar.hpp.
Member Typedef Documentation
B_G
template<class G> typedef G::B_G pgrouting::algorithms::Pgr_astar< G >::B_G
Definition at line 55 of file pgr_astar.hpp.
V
template<class G> typedef G::V pgrouting::algorithms::Pgr_astar< G >::V
Definition at line 54 of file pgr_astar.hpp.
Member Function Documentation
astar() [1/3]
template<class G> Path pgrouting::algorithms::Pgr_astar< G >::astar (G & graph, int64_t start_vertex, int64_t end_vertex, int heuristic, double factor, double epsilon, bool only_cost) inline
one to one astar 1 to 1
Definition at line 67 of file pgr_astar.hpp.
Referenced by pgrouting::algorithms::Pgr_astar< G >::astar(), pgrouting::algorithms::Pgr_astar< G >::clear(), and pgr_astar().
{
          clear();
          predecessors.resize(graph.num_vertices());
          distances.resize(graph.num_vertices());
          if (!graph.has_vertex(start_vertex)
                  || !graph.has_vertex(end_vertex)) {
              return Path(start_vertex, end_vertex);
          }
          auto v_source(graph.get_V(start_vertex));
          auto v_target(graph.get_V(end_vertex));
          // perform the algorithm
          astar_1_to_1(graph, v_source, v_target, heuristic, factor, epsilon);
          auto solution = Path(graph, Path(graph,
                  v_source, v_target,
                  predecessors, distances,
                  false), only_cost);
          return solution;
      }
astar() [2/3]
template<class G> std::deque<Path> pgrouting::algorithms::Pgr_astar< G >::astar (G & graph, int64_t start_vertex, std::vector< int64_t > end_vertex, int heuristic, double factor, double epsilon, bool only_cost) inline
astar 1 to many
Definition at line 100 of file pgr_astar.hpp.
References pgrouting::algorithms::Pgr_astar< G >::astar_1_to_many(), pgrouting::algorithms::Pgr_astar< G >::clear(), pgrouting::algorithms::Pgr_astar< G >::distances, Path::end_id(), pgrouting::algorithms::Pgr_astar< G >::get_paths(), and pgrouting::algorithms::Pgr_astar< G >::predecessors.
{
          clear();
          predecessors.resize(graph.num_vertices());
          distances.resize(graph.num_vertices());
          if (!graph.has_vertex(start_vertex)) return std::deque<Path>();
          auto v_source(graph.get_V(start_vertex));
          std::vector<V> v_targets;
          for (const auto &vertex : end_vertex) {
              if (graph.has_vertex(vertex)) {
                  v_targets.push_back(graph.get_V(vertex));
              }
          }
          astar_1_to_many(graph,
                  v_source,
                  v_targets,
                  heuristic,
                  factor,
                  epsilon);
          auto paths = get_paths(graph, v_source, v_targets, only_cost);
          std::stable_sort(paths.begin(), paths.end(),
                  [](const Path &e1, const Path &e2)->bool {
                  return e1.end_id() < e2.end_id();
                  });
          return paths;
      }
astar() [3/3]
template<class G> std::deque<Path> pgrouting::algorithms::Pgr_astar< G >::astar (G & graph, std::vector< int64_t > start_vertex, std::vector< int64_t > end_vertex, int heuristic, double factor, double epsilon, bool only_cost) inline
Definition at line 141 of file pgr_astar.hpp.
References pgrouting::algorithms::Pgr_astar< G >::astar(), Path::end_id(), and Path::start_id().
{
          std::deque<Path> paths;
          for (const auto &start : start_vertex) {
              auto r_paths = astar(graph, start, end_vertex,
                      heuristic, factor, epsilon, only_cost);
               paths.insert(paths.begin(), r_paths.begin(), r_paths.end());
          }
          std::sort(paths.begin(), paths.end(),
                  [](const Path &e1, const Path &e2)->bool {
                  return e1.end_id() < e2.end_id();
                  });
          std::stable_sort(paths.begin(), paths.end(),
                  [](const Path &e1, const Path &e2)->bool {
                  return e1.start_id() < e2.start_id();
                  });
          return paths;
      }
astar_1_to_1()
template<class G> bool pgrouting::algorithms::Pgr_astar< G >::astar_1_to_1 (G & graph, V source, V target, int heuristic, double factor, double epsilon) inline private
Call to Astar 1 source to 1 target.
Definition at line 288 of file pgr_astar.hpp.
References pgrouting::Basic_edge::cost.
Referenced by pgrouting::algorithms::Pgr_astar< G >::clear().
{
          bool found = false;
          try {
              // Call A* named parameter interface
              boost::astar_search(
                      graph.graph, source,
                      distance_heuristic(graph.graph, target,
                          heuristic, factor * epsilon),
                      boost::predecessor_map(&predecessors[0])
                      .weight_map(get(&pgrouting::Basic_edge::cost, graph.graph))
                      .distance_map(&distances[0])
                      .visitor(astar_one_goal_visitor(target)));
          }
          catch(found_goals &) {
              found = true;  // Target vertex found
          }
          return found;
      }
astar_1_to_many()
template<class G> bool pgrouting::algorithms::Pgr_astar< G >::astar_1_to_many (G & graph, V source, const std::vector< V > & targets, int heuristic, double factor, double epsilon) inline private
Call to astar 1 source to many targets.
Definition at line 315 of file pgr_astar.hpp.
References pgrouting::Basic_edge::cost.
Referenced by pgrouting::algorithms::Pgr_astar< G >::astar().
{
          bool found = false;
          try {
              boost::astar_search(
                      graph.graph, source,
                      distance_heuristic(
                          graph.graph, targets,
                          heuristic, factor * epsilon),
                      boost::predecessor_map(&predecessors[0])
                      .weight_map(get(&pgrouting::Basic_edge::cost, graph.graph))
                      .distance_map(&distances[0])
                      .visitor(astar_many_goals_visitor(targets)));
          }
          catch(found_goals &) {
              found = true;  // Target vertex found
          }
          return found;
      }
clear()
template<class G> void pgrouting::algorithms::Pgr_astar< G >::clear () inline
Definition at line 58 of file pgr_astar.hpp.
References pgrouting::algorithms::Pgr_astar< G >::astar(), pgrouting::algorithms::Pgr_astar< G >::astar_1_to_1(), pgrouting::algorithms::Pgr_astar< G >::distances, and pgrouting::algorithms::Pgr_astar< G >::predecessors.
Referenced by pgrouting::algorithms::Pgr_astar< G >::astar().
                   {
          predecessors.clear();
          distances.clear();
      }
get_paths()
template<class G> std::deque<Path> pgrouting::algorithms::Pgr_astar< G >::get_paths (const G & graph, V source, const std::vector< V > & targets, bool only_cost) const inline private
Definition at line 346 of file pgr_astar.hpp.
Referenced by pgrouting::algorithms::Pgr_astar< G >::astar().
{
          std::deque<Path> paths;
          for (const auto &target : targets) {
              auto p = Path(graph,
                          source, target,
                          predecessors, distances,
                          false);
              paths.push_back(Path(graph, p, only_cost));
          }
          return paths;
      }
Member Data Documentation
distances
template<class G> std::vector< double > pgrouting::algorithms::Pgr_astar< G >::distances private
Definition at line 175 of file pgr_astar.hpp.
Referenced by pgrouting::algorithms::Pgr_astar< G >::astar(), and pgrouting::algorithms::Pgr_astar< G >::clear().
nodesInDistance
template<class G> std::deque< V > pgrouting::algorithms::Pgr_astar< G >::nodesInDistance private
Definition at line 176 of file pgr_astar.hpp.
predecessors
template<class G> std::vector< V > pgrouting::algorithms::Pgr_astar< G >::predecessors private
Definition at line 174 of file pgr_astar.hpp.
Referenced by pgrouting::algorithms::Pgr_astar< G >::astar(), and pgrouting::algorithms::Pgr_astar< G >::clear().
The documentation for this class was generated from the following file:
pgr_astar.hpp