PGROUTING: pgrouting::vrp::Fleet Class Reference
pgrouting::vrp::Fleet Class Reference
#include "fleet.h"
Public Types
typedef std::vector< Vehicle_pickDeliver >::iterator iterator
Public Member Functions
Vehicle_pickDeliver get_truck ()
Vehicle_pickDeliver get_truck (size_t order)
Vehicle_pickDeliver get_truck (const Order order)
bool is_fleet_ok () const
bool is_order_ok (const Order &order) const
Given an order, Cycle trhugh all the trucks to verify if the order can be served by at least one truck.
Fleet & operator= (const Fleet &fleet)
void release_truck (size_t id)
void set_compatibles (const PD_Orders &orders)
constructor
Fleet ()=default
Fleet (const std::vector< Vehicle_t > &vehicles, double factor)
Fleet (const Fleet &fleet)
vector like functions
size_t size () const
Vehicle_pickDeliver & operator[] (size_t i)
iterator begin ()
iterator end ()
Public Attributes
std::vector< Vehicle_pickDeliver > m_trucks
Static Public Attributes
static Pgr_messages msg
Static Protected Attributes
static Pgr_pickDeliver * problem
Private Member Functions
void add_vehicle (Vehicle_t, double factor, std::unique_ptr< Base_node >, const Vehicle_node &, std::unique_ptr< Base_node >, const Vehicle_node &)
bool build_fleet (std::vector< Vehicle_t > vehicles, double factor)
build the fleet
template<typename T >
std::unique_ptr< Base_node > create_b_end (const Vehicle_t &vehicle, size_t node_id)
template<typename T >
std::unique_ptr< Base_node > create_b_start (const Vehicle_t &vehicle, size_t node_id)
Private Attributes
Identifiers< size_t > un_used
Identifiers< size_t > used
Friends
std::ostream & operator<< (std::ostream &log, const Fleet &v)
Detailed Description
Definition at line 47 of file fleet.h.
Member Typedef Documentation
iterator
typedef std::vector<Vehicle_pickDeliver>::iterator pgrouting::vrp::Fleet::iterator
Definition at line 49 of file fleet.h.
Constructor & Destructor Documentation
Fleet() [1/3]
pgrouting::vrp::Fleet::Fleet () default
Fleet() [2/3]
pgrouting::vrp::Fleet::Fleet (const std::vector< Vehicle_t > & vehicles, double factor)
Definition at line 47 of file fleet.cpp.
References build_fleet(), m_trucks, and un_used.
                                                              :
     PD_problem(),
     used(),
     un_used() {
         build_fleet(vehicles, factor);
         Identifiers<size_t> unused(m_trucks.size());
         un_used = unused;
     }
Fleet() [3/3]
pgrouting::vrp::Fleet::Fleet (const Fleet & fleet)
Definition at line 40 of file fleet.cpp.
                                :
     PD_problem(),
     m_trucks(fleet.m_trucks),
     used(fleet.used),
     un_used(fleet.un_used)
     {}
Member Function Documentation
add_vehicle()
void pgrouting::vrp::Fleet::add_vehicle (Vehicle_t vehicle, double factor, std::unique_ptr< Base_node > b_start, const Vehicle_node & starting_site, std::unique_ptr< Base_node > b_end, const Vehicle_node & ending_site) private
Definition at line 135 of file fleet.cpp.
References pgrouting::vrp::Pgr_pickDeliver::add_base_node(), pgrouting::vrp::Pgr_pickDeliver::add_node(), Vehicle_t::cant_v, Vehicle_t::capacity, pgrouting::vrp::Tw_node::closes(), Vehicle_t::id, pgrouting::vrp::Tw_node::is_end(), pgrouting::vrp::Tw_node::is_start(), pgrouting::Pgr_messages::log, m_trucks, pgrouting::vrp::PD_problem::msg, pgrouting::vrp::Tw_node::opens(), pgassert, pgrouting::vrp::PD_problem::problem, and Vehicle_t::speed.
Referenced by build_fleet().
{
     pgassert(starting_site.is_start() && ending_site.is_end());
     pgassert(starting_site.opens() <= starting_site.closes());
     pgassert(ending_site.opens() <= ending_site.closes());
     problem->add_base_node(std::move(b_start));
     problem->add_base_node(std::move(b_end));
     problem->add_node(starting_site);
     problem->add_node(ending_site);
     for (int i = 0; i < vehicle.cant_v; ++i) {
         m_trucks.push_back(Vehicle_pickDeliver(
                     m_trucks.size(),
                     vehicle.id,
                     starting_site,
                     ending_site,
                     vehicle.capacity,
                     vehicle.speed,
                     factor));
 #if 0
         msg.log << "inserting vehicle: " << m_trucks.back().tau() << "\n";
 #endif
         pgassert((m_trucks.back().idx() + 1)  == m_trucks.size());
         pgassert(m_trucks.back().is_ok());
     }
 }
begin()
iterator pgrouting::vrp::Fleet::begin () inline
Definition at line 87 of file fleet.h.
 {return m_trucks.begin();}
build_fleet()
bool pgrouting::vrp::Fleet::build_fleet (std::vector< Vehicle_t > vehicles, double factor) private
build the fleet
builds a fleet from a vector of Vehicle_t
Parameters
[in] vehicles of type Vehicle_t
creates a phoney truck with unlimited capacity and unlimited closing times
checks that the number of vehicles is a legal value
creates the requested vehicles
Parameters
[in] vehicles the list of vehicles
[in] factor the multiplier to speed up or slow down
Definition at line 179 of file fleet.cpp.
References add_vehicle(), pgrouting::Pgr_messages::clear(), pgrouting::tsp::Dmatrix::empty(), pgrouting::Pgr_messages::error, pgrouting::Pgr_messages::get_error(), pgrouting::Pgr_messages::log, pgrouting::vrp::Pgr_pickDeliver::m_cost_matrix, m_trucks, pgrouting::vrp::PD_problem::msg, pgrouting::vrp::Pgr_pickDeliver::node_id(), pgassert, pgassertwm, pgrouting::vrp::PD_problem::problem, and un_used.
Referenced by Fleet().
{
     /*
      *  creating a phoney truck with max capacity and max window
      *  with the start & end points of the first vehicle given
      */
     vehicles.push_back({
             /*
              * id, capacity
              */
             -1,
             std::numeric_limits<double>::infinity(),
             vehicles[0].speed,
             vehicles[0].start_x,
             vehicles[0].start_y,
             vehicles[0].start_node_id,
             /*
              * cant_v, start_open_t, start_close_t, start_service_t
              */
             1,
             0,
             std::numeric_limits<double>::infinity(),
             0,
             vehicles[0].end_x,
             vehicles[0].end_y,
             vehicles[0].end_node_id,
             /*
              * end_open_t, end_close_t, end_service_t
              */
             0,
             std::numeric_limits<double>::infinity(),
             0});
     for (auto vehicle : vehicles) {
         if (vehicle.cant_v < 0) {
             msg.error << "Illegal number of vehicles found vehicle";
             msg.log << vehicle.cant_v << "< 0 on vehicle " << vehicle.id;
             return false;
         }
         if  (problem->m_cost_matrix.empty()) {
             /*
              * Euclidean version
              */
             auto b_start = create_b_start<Node>(vehicle, problem->node_id());
             auto starting_site = Vehicle_node(
                     {problem->node_id()++, vehicle, Tw_node::NodeType::kStart});
             auto b_end = create_b_end<Node>(vehicle, problem->node_id());
             auto ending_site = Vehicle_node(
                     {problem->node_id()++, vehicle, Tw_node::NodeType::kEnd});
             if (!(starting_site.is_start() && ending_site.is_end()
                     && starting_site.opens() <= starting_site.closes()
                     && ending_site.opens() <= ending_site.closes())) {
                 msg.clear();
                 msg.error << "Illegal values found on vehicle";
                 msg.log << "On vehicle " << vehicle.id
                     << " a condition is not met:\n"
                     << "starting_site.is_start: "
                     << (starting_site.is_start()? "YES" : "NO") << "\n"
                     << "ending_site.is_end: "
                     << (ending_site.is_end()? "YES" : "NO") << "\n"
                     << "verify that:\n"
                     << "-  start_open <= start_close: "
                     << starting_site.opens()
                     << "<"  << starting_site.closes() << "\n"
                     << "-  end_open <= end_close: "
                     << ending_site.opens()
                     << "<"  << ending_site.closes() << "\n"
                     << "-  capacity > 0\n";
                 pgassert(!msg.get_error().empty());
                 return false;
             }
             pgassert(starting_site.is_start());
             pgassert(ending_site.is_end());
             pgassert(starting_site.opens() <= starting_site.closes());
             pgassert(ending_site.opens() <= ending_site.closes());
             pgassertwm(
                     starting_site.is_start() && ending_site.is_end(),
                     msg.get_error().c_str());
             add_vehicle(vehicle, factor,
                     std::move(b_start), starting_site,
                     std::move(b_end), ending_site);
         } else {
             /*
              * Matrix version
              */
             auto b_start = create_b_start<Dnode>(vehicle, problem->node_id());
             auto starting_site = Vehicle_node(
                     {problem->node_id()++, vehicle, Tw_node::NodeType::kStart});
             auto b_end = create_b_end<Dnode>(vehicle, problem->node_id());
             auto ending_site = Vehicle_node(
                     {problem->node_id()++, vehicle, Tw_node::NodeType::kEnd});
             if (!(starting_site.is_start() && ending_site.is_end()
                     && starting_site.opens() <= starting_site.closes()
                     && ending_site.opens() <= ending_site.closes())) {
                 msg.clear();
                 msg.error << "Illegal values found on vehicle";
                 msg.log << "On vehicle " << vehicle.id
                     << " a condition is not met, verify that:\n"
                     << "starting_site.is_start()"
                     << starting_site.is_start() << "\n"
                     << "ending_site.is_start()"
                     << ending_site.is_end() << "\n"
                     << "-  start_open <= start_close\n"
                     << starting_site.opens() << "<"
                     << starting_site.closes() << "\n"
                     << "-  end_open <= end_close\n"
                     << ending_site.opens() << "<"
                     << ending_site.closes() << "\n"
                     << "-  capacity > 0\n";
                 pgassert(!msg.get_error().empty());
                 return false;
             }
             pgassert(starting_site.is_start());
             pgassert(ending_site.is_end());
             pgassert(starting_site.opens() <= starting_site.closes());
             pgassert(ending_site.opens() <= ending_site.closes());
             pgassert(starting_site.is_start() && ending_site.is_end());
             add_vehicle(vehicle, factor,
                     std::move(b_start), starting_site,
                     std::move(b_end), ending_site);
         }
     }
     Identifiers<size_t> unused(m_trucks.size());
     un_used = unused;
     return true;
 }
create_b_end()
template<typename T > std::unique_ptr<Base_node> pgrouting::vrp::Fleet::create_b_end (const Vehicle_t & vehicle, size_t node_id) inline private
Definition at line 125 of file fleet.h.
References Vehicle_t::end_node_id, Vehicle_t::end_x, and Vehicle_t::end_y.
{
          std::unique_ptr<Base_node> b_end(new T(
                      node_id,
                      vehicle.end_node_id,
                      vehicle.end_x,
                      vehicle.end_y));
          return std::move(b_end);
      }
create_b_start()
template<typename T > std::unique_ptr<Base_node> pgrouting::vrp::Fleet::create_b_start (const Vehicle_t & vehicle, size_t node_id) inline private
Definition at line 114 of file fleet.h.
References Vehicle_t::start_node_id, Vehicle_t::start_x, and Vehicle_t::start_y.
{
          std::unique_ptr<Base_node> b_start(new T(
                      node_id,
                      vehicle.start_node_id,
                      vehicle.start_x,
                      vehicle.start_y));
          return std::move(b_start);
      }
end()
iterator pgrouting::vrp::Fleet::end () inline
Definition at line 88 of file fleet.h.
References operator<<.
 {return m_trucks.end();}
get_truck() [1/3]
Vehicle_pickDeliver pgrouting::vrp::Fleet::get_truck ()
Definition at line 59 of file fleet.cpp.
References ENTERING, EXITING, Identifiers< T >::front(), pgrouting::Pgr_messages::log, m_trucks, pgrouting::vrp::PD_problem::msg, pgassertwm, Identifiers< T >::size(), un_used, and used.
Referenced by pgrouting::vrp::Initial_solution::do_while_foo(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), and operator=().
                  {
     ENTERING();
     auto idx = un_used.front();
     msg.log << "Available vehicles: " << un_used << "\n";
     msg.log << "NOT Available vehicles: " << used << "\n";
     msg.log << "getting idx" << idx << "\n";
     pgassertwm(idx < m_trucks.size(), msg.log.str());
     used += idx;
     if (un_used.size() > 1) un_used -= idx;
     EXITING();
     return m_trucks[idx];
 }
get_truck() [2/3]
Vehicle_pickDeliver pgrouting::vrp::Fleet::get_truck (size_t order)
Definition at line 79 of file fleet.cpp.
References Identifiers< T >::front(), pgrouting::Pgr_messages::get_log(), pgrouting::Pgr_messages::log, m_trucks, pgrouting::vrp::PD_problem::msg, pgassert, pgassertwm, un_used, and used.
{
 #if 0
     msg.log << "Available vehicles: " << un_used << "\n";
     msg.log << "NOT Available vehicles: " << used << "\n";
 #endif
     auto idx = un_used.front();
     for (const auto i : un_used) {
         if (m_trucks[i].feasable_orders().has(order)) {
             idx = i;
             msg.log << "getting idx" << idx << "\n";
             used += idx;
             if (un_used.size() > 1) un_used -= idx;
             return m_trucks[idx];
         }
     }
     /*
      * using phoney truck
      */
     pgassert(false);
     return m_trucks.back();
     for (auto truck : m_trucks) {
         if (truck.feasable_orders().has(order)) {
             idx = truck.idx();
             msg.log << "idx" << idx << "size" << m_trucks.size();
             pgassertwm(idx < m_trucks.size(), msg.get_log());
             used += idx;
             if (un_used.size() > 1) un_used -= idx;
             break;
         }
     }
     return m_trucks[idx];
 }
get_truck() [3/3]
Vehicle_pickDeliver pgrouting::vrp::Fleet::get_truck (const Order order)
Definition at line 117 of file fleet.cpp.
References pgrouting::Pgr_messages::get_log(), pgrouting::Identifier::idx(), pgrouting::Pgr_messages::log, m_trucks, pgrouting::vrp::PD_problem::msg, pgassertwm, Identifiers< T >::size(), un_used, and used.
{
     auto id = m_trucks.front().idx();
     for (auto truck : m_trucks) {
         if (truck.feasable_orders().has(order.idx())) {
             id = truck.idx();
             msg.log << "id" << id
                 << "size" << m_trucks.size();
             pgassertwm(id < m_trucks.size(), msg.get_log());
             used += id;
             if (un_used.size() > 1) un_used -= id;
             break;
         }
     }
     return m_trucks[id];
 }
is_fleet_ok()
bool pgrouting::vrp::Fleet::is_fleet_ok () const
Definition at line 320 of file fleet.cpp.
References ENTERING, pgrouting::Pgr_messages::error, EXITING, pgrouting::Pgr_messages::get_error(), pgrouting::Pgr_messages::log, m_trucks, pgrouting::vrp::PD_problem::msg, and pgassertwm.
Referenced by operator=(), and pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver().
{
     ENTERING();
     if (!msg.get_error().empty()) return false;
     for (auto truck : m_trucks) {
         if (!truck.is_ok()) {
             msg.error << "Illegal values found on vehicle";
             msg.log << "On vehicle " << truck.id()
                 << " a condition is not met, verify that:\n"
                 << "-  start_open <= start_close\n"
                 << "-  end_open <= end_close\n"
                 << "-  capacity > 0\n";
             return false;
         }
         if (!(truck.start_site().is_start()
                     && truck.end_site().is_end())) {
             pgassertwm(false, "should never pass through here");
             msg.error << "Illegal values found on vehicle";
             return false;
         }
         if (!truck.is_feasable()) {
             msg.error << "Truck is not feasible";
             return false;
         }
     }
     EXITING();
     return true;
 }
is_order_ok()
bool pgrouting::vrp::Fleet::is_order_ok (const Order & order) const
Given an order, Cycle trhugh all the trucks to verify if the order can be served by at least one truck.
Definition at line 355 of file fleet.cpp.
References pgrouting::vrp::Order::is_valid(), and m_trucks.
Referenced by operator=().
{
     for (const auto truck : m_trucks) {
         if (!order.is_valid(truck.speed())) continue;
         if (truck.is_order_feasable(order)) {
             return true;
         }
     }
     return false;
 }
operator=()
Fleet& pgrouting::vrp::Fleet::operator= (const Fleet & fleet) inline
Definition at line 65 of file fleet.h.
References get_truck(), is_fleet_ok(), is_order_ok(), m_trucks, release_truck(), set_compatibles(), un_used, and used.
{
          m_trucks = fleet.m_trucks;
          used = fleet.used;
          un_used = fleet.un_used;
          return *this;
      }
operator[]()
Vehicle_pickDeliver & pgrouting::vrp::Fleet::operator[] (size_t i)
Definition at line 366 of file fleet.cpp.
References m_trucks, and pgassert.
Referenced by size().
{
     pgassert(i < m_trucks.size());
     return m_trucks[i];
 }
release_truck()
void pgrouting::vrp::Fleet::release_truck (size_t id)
Definition at line 73 of file fleet.cpp.
References un_used, and used.
Referenced by pgrouting::vrp::Initial_solution::do_while_foo(), and operator=().
{
     used -= id;
     un_used += id;
 }
set_compatibles()
void pgrouting::vrp::Fleet::set_compatibles (const PD_Orders & orders)
Definition at line 372 of file fleet.cpp.
References m_trucks.
Referenced by operator=().
{
     for (auto &truck : m_trucks) {
         truck.set_compatibles(orders);
     }
 }
size()
size_t pgrouting::vrp::Fleet::size () const inline
Definition at line 85 of file fleet.h.
References operator[]().
 {return m_trucks.size();}
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const Fleet & v) friend
Definition at line 383 of file fleet.cpp.
Referenced by end().
{
     log << "fleet\n";
     for (const auto v : f.m_trucks) {
         log << v;
     }
     log << "end fleet\n";
     return log;
 }
Member Data Documentation
m_trucks
std::vector<Vehicle_pickDeliver> pgrouting::vrp::Fleet::m_trucks
Definition at line 50 of file fleet.h.
Referenced by add_vehicle(), build_fleet(), Fleet(), get_truck(), is_fleet_ok(), is_order_ok(), pgrouting::vrp::operator<<(), operator=(), operator[](), and set_compatibles().
msg
Pgr_messages pgrouting::vrp::PD_problem::msg static inherited
Definition at line 49 of file pd_problem.h.
Referenced by add_vehicle(), build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), pgrouting::vrp::Optimize::delete_empty_truck(), do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), pgrouting::vrp::Vehicle_pickDeliver::do_while_feasable(), pgrouting::vrp::Initial_solution::do_while_foo(), pgrouting::vrp::Pgr_pickDeliver::get_postgres_result(), pgrouting::vrp::Vehicle::get_postgres_result(), get_truck(), pgrouting::vrp::Optimize::inter_swap(), is_fleet_ok(), pgrouting::vrp::Pgr_pickDeliver::nodesOK(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), pgrouting::vrp::Optimize::Optimize(), pgrouting::vrp::Pgr_pickDeliver::optimize(), pgrouting::vrp::PD_problem::PD_problem(), pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Optimize::save_if_best(), pgrouting::vrp::Solution::Solution(), pgrouting::vrp::Pgr_pickDeliver::solve(), pgrouting::vrp::Optimize::swap_order(), and pgrouting::vrp::Vehicle::Vehicle().
problem
Pgr_pickDeliver * pgrouting::vrp::PD_problem::problem static protected inherited
Definition at line 52 of file pd_problem.h.
Referenced by pgrouting::vrp::PD_Orders::add_order(), add_vehicle(), build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), pgrouting::vrp::Dnode::distance(), pgrouting::vrp::Solution::get_kind(), pgrouting::vrp::Pgr_pickDeliver::get_kind(), pgrouting::vrp::operator<<(), pgrouting::vrp::Tw_node::operator==(), and pgrouting::vrp::Tw_node::travel_time_to().
un_used
Identifiers<size_t> pgrouting::vrp::Fleet::un_used private
Definition at line 96 of file fleet.h.
Referenced by build_fleet(), Fleet(), get_truck(), operator=(), and release_truck().
used
Identifiers<size_t> pgrouting::vrp::Fleet::used private
Definition at line 95 of file fleet.h.
Referenced by get_truck(), operator=(), and release_truck().
The documentation for this class was generated from the following files:
fleet.h
fleet.cpp