PGROUTING: pgrouting::vrp::Solution Class Reference
pgrouting::vrp::Solution Class Reference
#include "solution.h"
Public Member Functions
Solution ()
Solution (const Solution &sol)
Vehicle::Cost cost () const
std::string cost_str () const
int cvTot () const
double duration () const
size_t fleet_size () const
Initials_code get_kind () const
std::vector< General_vehicle_orders_t > get_postgres_result () const
bool is_feasable () const
bool operator< (const Solution &s_rhs) const
Solution & operator= (const Solution &sol)
void sort_by_id ()
std::string tau (const std::string &title="Tau") const
double total_service_time () const
double total_travel_time () const
int twvTot () const
double wait_time () const
Static Public Attributes
static Pgr_messages msg
Protected Attributes
double EPSILON
std::deque< Vehicle_pickDeliver > fleet
Fleet trucks
Static Protected Attributes
static Pgr_pickDeliver * problem
Friends
std::ostream & operator<< (std::ostream &log, const Solution &solution)
class Optimize
Detailed Description
Definition at line 45 of file solution.h.
Constructor & Destructor Documentation
Solution() [1/2]
pgrouting::vrp::Solution::Solution ()
Definition at line 239 of file solution.cpp.
References ENTERING, EXITING, pgrouting::Pgr_messages::log, pgrouting::vrp::PD_problem::msg, and trucks.
                    :
     EPSILON(0.0001),
     trucks(problem->trucks()) {
     ENTERING();
     for (const auto &t : trucks) {
         msg.log << t.tau() << "\n";
     }
     EXITING();
 }
Solution() [2/2]
pgrouting::vrp::Solution::Solution (const Solution & sol) inline
Definition at line 71 of file solution.h.
                                    :
          PD_problem(),
          EPSILON(0.0001),
          fleet(sol.fleet),
          trucks(sol.trucks)
     {};
Member Function Documentation
cost()
Vehicle::Cost pgrouting::vrp::Solution::cost () const
Definition at line 119 of file solution.cpp.
References fleet.
Referenced by cost_str(), fleet_size(), operator<(), and tau().
                      {
     double total_duration(0);
     double total_wait_time(0);
     int total_twv(0);
     int total_cv(0);
     for (const auto v : fleet) {
         total_duration += v.duration();
         total_wait_time += v.total_wait_time();
         total_twv += v.twvTot();
         total_cv += v.cvTot();
     }
     return std::make_tuple(
             total_twv, total_cv, fleet.size(),
             total_wait_time, total_duration);
 }
cost_str()
std::string pgrouting::vrp::Solution::cost_str () const
Definition at line 138 of file solution.cpp.
References cost().
Referenced by operator=(), pgrouting::vrp::Optimize::save_if_best(), and tau().
{
     Vehicle::Cost s_cost(cost());
     std::ostringstream log;
     log << "(twv, cv, fleet, wait, duration) = ("
         << std::get<0>(s_cost) << ", "
         << std::get<1>(s_cost) << ", "
         << std::get<2>(s_cost) << ", "
         << std::get<3>(s_cost) << ", "
         << std::get<4>(s_cost) << ")";
     return log.str();
 }
cvTot()
int pgrouting::vrp::Solution::cvTot () const
Definition at line 110 of file solution.cpp.
References fleet.
Referenced by operator=().
                       {
     int total(0);
     for (const auto v : fleet) {
         total += v.cvTot();
     }
     return total;
 }
duration()
double pgrouting::vrp::Solution::duration () const
Definition at line 65 of file solution.cpp.
References fleet.
Referenced by pgrouting::vrp::Optimize::move_reduce_cost(), operator=(), pgrouting::vrp::Optimize::save_if_best(), and pgrouting::vrp::Optimize::swap_worse().
{
     double total(0);
     for (const auto v : fleet) {
         total += v.duration();
     }
     return total;
 }
fleet_size()
size_t pgrouting::vrp::Solution::fleet_size () const inline
Definition at line 104 of file solution.h.
References cost().
 {return fleet.size();}
get_kind()
Initials_code pgrouting::vrp::Solution::get_kind () const
Definition at line 235 of file solution.cpp.
References pgrouting::vrp::Pgr_pickDeliver::get_kind(), and pgrouting::vrp::PD_problem::problem.
Referenced by pgrouting::vrp::Optimize::move_order(), pgrouting::vrp::Optimize::move_reduce_cost(), operator=(), pgrouting::vrp::Optimize::swap_order(), and pgrouting::vrp::Optimize::swap_worse().
{
     return problem->get_kind();
 }
get_postgres_result()
std::vector< General_vehicle_orders_t > pgrouting::vrp::Solution::get_postgres_result () const
Definition at line 39 of file solution.cpp.
References fleet.
{
     std::vector<General_vehicle_orders_t> result;
     /* postgres numbering starts with 1 */
     int i(1);
     for (const auto truck : fleet) {
         std::vector<General_vehicle_orders_t> data =
             truck.get_postgres_result(i);
         result.insert(result.end(), data.begin(), data.end());
         ++i;
     }
     return result;
 }
is_feasable()
bool pgrouting::vrp::Solution::is_feasable () const
Definition at line 56 of file solution.cpp.
References fleet.
Referenced by pgrouting::vrp::Optimize::decrease_truck(), pgrouting::vrp::Initial_solution::do_while_foo(), and operator=().
{
     for (const auto v : fleet) {
         if (v.is_feasable()) continue;
         return false;
     }
     return true;
 }
operator<()
bool pgrouting::vrp::Solution::operator< (const Solution & s_rhs) const
Definition at line 187 of file solution.cpp.
References cost().
Referenced by operator=().
{
     Vehicle::Cost lhs(cost());
     Vehicle::Cost rhs(s_rhs.cost());
     /*
      * capacity violations
      */
     if (std::get<0>(lhs) < std::get<0>(rhs))
         return true;
     if (std::get<0>(lhs) > std::get<0>(rhs))
         return false;
     /*
      * time window violations
      */
     if (std::get<1>(lhs) < std::get<1>(rhs))
         return true;
     if (std::get<1>(lhs) > std::get<1>(rhs))
         return false;
     /*
      * fleet size
      */
     if (std::get<2>(lhs) < std::get<2>(rhs))
         return true;
     if (std::get<2>(lhs) > std::get<2>(rhs))
         return false;
     /*
      * waiting time
      */
     if (std::get<3>(lhs) < std::get<3>(rhs))
         return true;
     if (std::get<3>(lhs) > std::get<3>(rhs))
         return false;
     /*
      * duration
      */
     if (std::get<4>(lhs) < std::get<4>(rhs))
         return true;
     if (std::get<4>(lhs) > std::get<4>(rhs))
         return false;
     return false;
 }
operator=()
Solution& pgrouting::vrp::Solution::operator= (const Solution & sol) inline
Definition at line 79 of file solution.h.
References cost_str(), cvTot(), duration(), fleet, get_kind(), is_feasable(), operator<(), operator<<, sort_by_id(), tau(), total_service_time(), total_travel_time(), trucks, twvTot(), and wait_time().
{
          EPSILON = 0.0001,
          fleet = sol.fleet;
          trucks = sol.trucks;
          return *this;
      };
sort_by_id()
void pgrouting::vrp::Solution::sort_by_id ()
Definition at line 166 of file solution.cpp.
References fleet, and pgrouting::Identifier::idx().
Referenced by operator=().
                      {
     std::sort(fleet.begin(), fleet.end(), []
             (const Vehicle_pickDeliver &lhs, const Vehicle_pickDeliver &rhs)
             -> bool {
             return lhs.idx() < rhs.idx();
             });
 }
tau()
std::string pgrouting::vrp::Solution::tau (const std::string & title = "Tau") const
Definition at line 153 of file solution.cpp.
References cost(), cost_str(), and fleet.
Referenced by pgrouting::vrp::Optimize::delete_empty_truck(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::operator<<(), operator=(), pgrouting::vrp::Optimize::Optimize(), pgrouting::vrp::Pgr_pickDeliver::optimize(), and pgrouting::vrp::Optimize::save_if_best().
{
     Vehicle::Cost s_cost(cost());
     std::ostringstream log;
     log << "\n" << title << ": " << std::endl;
     for (const auto v : fleet) {
         log << "\n" << v.tau();
     }
     log << "\n" << cost_str() << "\n";
     return log.str();
 }
total_service_time()
double pgrouting::vrp::Solution::total_service_time () const
Definition at line 101 of file solution.cpp.
References fleet.
Referenced by operator=().
{
     double total(0);
     for (const auto v : fleet) {
         total += v.total_service_time();
     }
     return total;
 }
total_travel_time()
double pgrouting::vrp::Solution::total_travel_time () const
Definition at line 92 of file solution.cpp.
References fleet.
Referenced by operator=().
{
     double total(0);
     for (const auto v : fleet) {
         total += v.total_travel_time();
     }
     return total;
 }
twvTot()
int pgrouting::vrp::Solution::twvTot () const
Definition at line 74 of file solution.cpp.
References fleet.
Referenced by operator=().
{
     int total(0);
     for (const auto v : fleet) {
         total += v.twvTot();
     }
     return total;
 }
wait_time()
double pgrouting::vrp::Solution::wait_time () const
Definition at line 83 of file solution.cpp.
References fleet.
Referenced by operator=().
{
     double total(0);
     for (const auto v : fleet) {
         total += v.total_wait_time();
     }
     return total;
 }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const Solution & solution) friend
Definition at line 175 of file solution.cpp.
Referenced by operator=().
{
     for (const auto vehicle : solution.fleet) {
         log << vehicle;
     }
     log << "\n SOLUTION:\n\n "
         << solution.tau();
     return log;
 }
Optimize
friend class Optimize friend
Definition at line 46 of file solution.h.
Member Data Documentation
EPSILON
double pgrouting::vrp::Solution::EPSILON protected
Definition at line 48 of file solution.h.
fleet
std::deque<Vehicle_pickDeliver> pgrouting::vrp::Solution::fleet protected
Definition at line 49 of file solution.h.
Referenced by cost(), cvTot(), pgrouting::vrp::Optimize::decrease_truck(), pgrouting::vrp::Optimize::delete_empty_truck(), pgrouting::vrp::Initial_solution::do_while_foo(), duration(), get_postgres_result(), pgrouting::vrp::Optimize::inter_swap(), is_feasable(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), pgrouting::vrp::operator<<(), operator=(), pgrouting::vrp::Optimize::Optimize(), pgrouting::vrp::Optimize::save_if_best(), pgrouting::vrp::Optimize::sort_by_duration(), pgrouting::vrp::Optimize::sort_by_id(), sort_by_id(), pgrouting::vrp::Optimize::sort_by_size(), pgrouting::vrp::Optimize::sort_for_move(), pgrouting::vrp::Optimize::swap_order(), tau(), total_service_time(), total_travel_time(), twvTot(), and wait_time().
msg
Pgr_messages pgrouting::vrp::PD_problem::msg static inherited
Definition at line 49 of file pd_problem.h.
Referenced by pgrouting::vrp::Fleet::add_vehicle(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), pgrouting::vrp::Optimize::delete_empty_truck(), do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), pgrouting::vrp::Vehicle_pickDeliver::do_while_feasable(), pgrouting::vrp::Initial_solution::do_while_foo(), pgrouting::vrp::Pgr_pickDeliver::get_postgres_result(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Fleet::is_fleet_ok(), pgrouting::vrp::Pgr_pickDeliver::nodesOK(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), pgrouting::vrp::Optimize::Optimize(), pgrouting::vrp::Pgr_pickDeliver::optimize(), pgrouting::vrp::PD_problem::PD_problem(), pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Optimize::save_if_best(), Solution(), pgrouting::vrp::Pgr_pickDeliver::solve(), pgrouting::vrp::Optimize::swap_order(), and pgrouting::vrp::Vehicle::Vehicle().
problem
Pgr_pickDeliver * pgrouting::vrp::PD_problem::problem static protected inherited
Definition at line 52 of file pd_problem.h.
Referenced by pgrouting::vrp::PD_Orders::add_order(), pgrouting::vrp::Fleet::add_vehicle(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), pgrouting::vrp::Dnode::distance(), get_kind(), pgrouting::vrp::Pgr_pickDeliver::get_kind(), pgrouting::vrp::operator<<(), pgrouting::vrp::Tw_node::operator==(), and pgrouting::vrp::Tw_node::travel_time_to().
trucks
Fleet pgrouting::vrp::Solution::trucks protected
Definition at line 52 of file solution.h.
Referenced by pgrouting::vrp::Initial_solution::do_while_foo(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), operator=(), and Solution().
The documentation for this class was generated from the following files:
solution.h
solution.cpp