PGROUTING: Pgr_kruskal< G > Class Template Reference
Pgr_kruskal< G > Class Template Reference
#include "pgr_kruskal.hpp"
Public Types
typedef G::E E
typedef G::V V
Public Member Functions
std::vector< pgr_kruskal_t > kruskal (G &graph)
Private Member Functions
std::vector< pgr_kruskal_t > generateKruskal (const G &graph)
Detailed Description
template<class G>
class Pgr_kruskal< G >
Definition at line 45 of file pgr_kruskal.hpp.
Member Typedef Documentation
template<class G> typedef G::E Pgr_kruskal< G >::E
Definition at line 56 of file pgr_kruskal.hpp.
template<class G> typedef G::V Pgr_kruskal< G >::V
Definition at line 55 of file pgr_kruskal.hpp.
Member Function Documentation
template<class G> std::vector< pgr_kruskal_t > Pgr_kruskal< G >::generateKruskal (const G & graph) inline private
Definition at line 64 of file pgr_kruskal.hpp.
References pgr_kruskal_t::component, pgr_kruskal_t::cost, pgr_kruskal_t::edge, and pgr_kruskal_t::tree_cost.
Referenced by Pgr_kruskal< G >::kruskal().
{
        typename std::vector < E >::iterator ei;
        std::vector < E > spanning_tree;
        boost::kruskal_minimum_spanning_tree(
                               graph.graph,
                               std::back_inserter(spanning_tree),
                               boost::weight_map(get(&G::G_T_E::cost, graph.graph))
                               );
        std::vector< pgr_kruskal_t > results;
        size_t totalNodes = num_vertices(graph.graph); // Total Node in graph
        /*Calculate connected components*/
        std::vector< int > components(totalNodes);
        size_t num_comps = boost::connected_components(graph.graph, &components[0]);
        std::vector< std::vector< int64_t > > component;
        component.resize(num_comps);
        for (size_t i = 0; i < totalNodes; i++)
            component[components[i]].push_back(graph[i].id);
        for (size_t i = 0; i < num_comps; i++) {
            std::sort(component[i].begin(), component[i].end());
        }
        sort(component.begin(), component.end());
        size_t size = component.size();
        for (size_t i = 0; i < size; i++){
          double totalcost = 0;
          for (ei = spanning_tree.begin(); ei != spanning_tree.end(); ++ei) {
             if(components[source(*ei, graph.graph)] == static_cast< int > (i)){
                pgr_kruskal_t tmp;
                tmp.component = component[i][0];;
                tmp.cost = graph[*ei].cost;  // cost
                auto start_node = graph.graph[source(*ei, graph.graph)].id;
                auto end_node = graph.graph[target(*ei, graph.graph)].id; // node
                auto v_sn(graph.get_V(start_node));
                auto v_en(graph.get_V(end_node));
                auto edge_id =
                     graph.get_edge_id(v_sn, v_en, tmp.cost);
            totalcost += tmp.cost;
                tmp.edge = edge_id;       // edge_id
                tmp.tree_cost = totalcost;    // tree_cost
                results.push_back(tmp);
             }
          }
        }
        return results;
      }
template<class G > std::vector< pgr_kruskal_t > Pgr_kruskal< G >::kruskal (G & graph)
Definition at line 126 of file pgr_kruskal.hpp.
References Pgr_kruskal< G >::generateKruskal().
Referenced by pgr_kruskal().
{
       return generateKruskal(
                              graph);
 }
The documentation for this class was generated from the following file:
/home/vicky/pgrouting/pgrouting/pgrouting/include/mst/pgr_kruskal.hpp