PGROUTING: pgrouting::tsp::Tour Class Reference
pgrouting::tsp::Tour Class Reference
#include "tour.h"
Public Member Functions
Tour (const Tour &)=default
Tour (const std::vector< size_t > &cities_order)
Tour (size_t n)
void reverse (size_t c1, size_t c2)
void rotate (size_t c1, size_t c2, size_t c3)
size_t size () const
void slide (size_t place, size_t first, size_t last)
void swap (size_t c1, size_t c2)
Public Attributes
std::vector< size_t > cities
Friends
double Dmatrix::tourCost (const Tour &tour) const
std::ostream & operator<< (std::ostream &log, const Tour &tour)
Detailed Description
Definition at line 42 of file tour.h.
Constructor & Destructor Documentation
Tour() [1/3]
pgrouting::tsp::Tour::Tour (const Tour &) default
Tour() [2/3]
pgrouting::tsp::Tour::Tour (const std::vector< size_t > & cities_order) inline explicit
Definition at line 46 of file tour.h.
                                                           :
          cities(cities_order) {
      }
Tour() [3/3]
pgrouting::tsp::Tour::Tour (size_t n) inline explicit
Definition at line 50 of file tour.h.
References cities.
{
          cities.resize(n);
          std::iota(std::begin(cities), std::end(cities), 0);
      }
Member Function Documentation
reverse()
void pgrouting::tsp::Tour::reverse (size_t c1, size_t c2)
Definition at line 47 of file tour.cpp.
References cities, and pgassert.
Referenced by pgrouting::tsp::TSP< MATRIX >::find_closest_city(), and size().
                    {
     pgassert(c1 < c2 && c2 < cities.size());
     std::reverse(
             cities.begin() + (c1 + 1),
             cities.begin() + (c2 + 1));
 }
rotate()
void pgrouting::tsp::Tour::rotate (size_t c1, size_t c2, size_t c3)
Definition at line 77 of file tour.cpp.
References cities, and pgassert.
Referenced by size().
                    {
     pgassert(c1 < c2 && c2 < c3 && c3 < cities.size());
     std::rotate(
             cities.begin() + (c1 + 1),
             cities.begin() + (c2 + 1),
             cities.begin() + (c3 + 1));
 }
size()
size_t pgrouting::tsp::Tour::size () const inline
Definition at line 55 of file tour.h.
References cities, operator<<, reverse(), rotate(), slide(), swap(), and pgrouting::tsp::Dmatrix::tourCost().
 {return cities.size();}
slide()
void pgrouting::tsp::Tour::slide (size_t place, size_t first, size_t last)
Definition at line 56 of file tour.cpp.
References cities, and pgassert.
Referenced by pgrouting::tsp::TSP< MATRIX >::find_closest_city(), pgrouting::tsp::TSP< MATRIX >::getDeltaSlide(), and size().
                      {
     pgassert(first < cities.size());
     pgassert(last  < cities.size());
     pgassert(place < cities.size());
     if (place < first) {
         std::rotate(
                 cities.begin() + (place + 1),
                 cities.begin() + (first + 1),
                 cities.begin() + (last + 1));
     } else {
         std::rotate(
                 cities.begin() + (first + 1),
                 cities.begin() + (last + 1),
                 cities.begin() + (place + 1));
     }
 }
swap()
void pgrouting::tsp::Tour::swap (size_t c1, size_t c2)
Definition at line 90 of file tour.cpp.
References cities, and pgassert.
Referenced by pgrouting::tsp::TSP< MATRIX >::find_closest_city(), and size().
                     {
     pgassert(c1 < c2);
     std::iter_swap(cities.begin() + c1, cities.begin() + c2);
 }
Friends And Related Function Documentation
Dmatrix::tourCost
double Dmatrix::tourCost (const Tour & tour) const friend
operator<<
std::ostream& operator<< (std::ostream & log, const Tour & tour) friend
Definition at line 36 of file tour.cpp.
Referenced by size().
{
     for (const auto &city : tour.cities) {
         log << city << ", ";
     }
     return log;
 }
Member Data Documentation
cities
std::vector<size_t> pgrouting::tsp::Tour::cities
Definition at line 154 of file tour.h.
Referenced by pgrouting::tsp::TSP< MATRIX >::find_closest_city(), pgrouting::tsp::TSP< MATRIX >::getDeltaSlide(), pgrouting::tsp::operator<<(), reverse(), rotate(), size(), slide(), swap(), Tour(), pgrouting::tsp::Dmatrix::tourCost(), and pgrouting::tsp::EuclideanDmatrix::tourCost().
The documentation for this class was generated from the following files:
tour.h
tour.cpp