PGROUTING: pgrouting::vrp::Vehicle Class Reference
pgrouting::vrp::Vehicle Class Reference
Vehicle with time windows.
#include "vehicle.h"
Public Types
typedef std::tuple< int, int, size_t, double, double > Cost
Public Member Functions
Vehicle (const Vehicle &)
Vehicle (size_t idx, int64_t kind, const Vehicle_node &starting_site, const Vehicle_node &ending_site, double p_capacity, double p_speed, double p_factor)
double deltaTime (const Vehicle_node &node, POS pos) const
std::pair< POS, POS > drop_position_limits (const Vehicle_node node) const
std::vector< General_vehicle_orders_t > get_postgres_result (int vid) const
int64_t id () const
size_t idx () const
POS insert_less_travel_time (const Vehicle_node &node, POS after_pos=0)
bool is_phony () const
std::pair< POS, POS > position_limits (const Vehicle_node node) const
void reset_id (int64_t)
double speed () const
void swap (POS i, POS j)
Swap two nodes in the path.
deque like functions
Returns
True if the operation was performed
Warning
Assertions are performed for out of range operations
no feasability nor time window or capacity violations checks are performed
Todo:
TODO more deque like functions here
void invariant () const
Invariant The path must:
void insert (POS pos, Vehicle_node node)
@ {
POS insert (std::pair< POS, POS > position_limits, const Vehicle_node &node)
Insert node in best position of the position_limits.
void push_back (const Vehicle_node &node)
Evaluated: push_back a node to the path.
void push_front (const Vehicle_node &node)
Evaluated: push_back a node to the path.
void pop_back ()
Evaluated: pop_back a node to the path.
void pop_front ()
Evaluated: pop_front a node to the path.
void erase (const Vehicle_node &node)
Erase node.id()
void erase (POS pos)
Erase node at pos from the path.
bool empty () const
return true when no nodes are in the truck
size_t size () const
return number of nodes in the truck
Cost cost () const
bool cost_compare (const Cost &, const Cost &) const
double duration () const
double total_wait_time () const
double total_travel_time () const
double total_service_time () const
double free_time () const
int twvTot () const
int cvTot () const
bool has_twv () const
bool has_cv () const
bool is_feasable () const
bool is_ok () const
Vehicle_node start_site () const
Vehicle_node end_site () const
double capacity () const
Evaluation
Path evaluation is done incrementally: from a given position to the end of the path, and intermediate values are cached on each node.
So, for example, changing the path at position 100: the evaluation function should be called as evaluate(100, maxcapacity) and from that position to the end of the path will be evaluated. None of the "unaffected" positions get reevaluated
void evaluate ()
@ {
void evaluate (POS from)
Evaluate: Evaluate a path from the given position.
accessors
std::deque< Vehicle_node > path () const
@ {
Static Public Attributes
static Pgr_messages msg
Protected Types
typedef size_t POS
Protected Attributes
std::deque< Vehicle_node > m_path
Static Protected Attributes
static Pgr_pickDeliver * problem
Private Member Functions
POS getDropPosLowLimit (const Vehicle_node &node) const
POS getPosHighLimit (const Vehicle_node &node) const
POS getPosLowLimit (const Vehicle_node &node) const
Private Attributes
double m_capacity
double m_factor
double m_speed
operators
std::string tau () const
std::ostream & operator<< (std::ostream &log, const Vehicle &v)
@ {
bool operator< (const Vehicle &lhs, const Vehicle &rhs)
Detailed Description
Vehicle with time windows.
General functionality for a vehicle in a VRP problem
Recommended use:
Class my_vehicle : public vechicle
Note
All members return true when the operation is successful
A vehicle is a sequence of Vehicle_node from starting site to ending site. has: capacity speed factor TODO(vicky)
See also
Vehicle_node
Definition at line 72 of file vehicle.h.
Member Typedef Documentation
Cost
typedef std::tuple< int, int, size_t, double, double > pgrouting::vrp::Vehicle::Cost
Definition at line 86 of file vehicle.h.
POS
typedef size_t pgrouting::vrp::Vehicle::POS protected
Definition at line 74 of file vehicle.h.
Constructor & Destructor Documentation
Vehicle() [1/2]
pgrouting::vrp::Vehicle::Vehicle (const Vehicle & v)
Definition at line 549 of file vehicle.cpp.
References ENTERING, EXITING, pgrouting::Pgr_messages::log, pgrouting::vrp::PD_problem::msg, and tau().
                                  :
     Identifier(v.idx(), v.id()),
     PD_problem(),
     m_path(v.m_path),
     m_capacity(v.m_capacity),
     m_factor(v.m_factor),
     m_speed(v.m_speed) {
 #if 0
         ENTERING();
         msg.log << v.tau() << "\n";
         msg.log << tau() << "\n";
         EXITING();
 #endif
 }
Vehicle() [2/2]
pgrouting::vrp::Vehicle::Vehicle (size_t idx, int64_t kind, const Vehicle_node & starting_site, const Vehicle_node & ending_site, double p_capacity, double p_speed, double p_factor)
Definition at line 514 of file vehicle.cpp.
References capacity(), pgrouting::vrp::Tw_node::closes(), ENTERING, evaluate(), EXITING, pgrouting::Identifier::id(), pgrouting::Identifier::idx(), invariant(), pgrouting::Pgr_messages::log, m_path, pgrouting::vrp::PD_problem::msg, pgrouting::vrp::Tw_node::opens(), pgassert, and tau().
                          :
     Identifier(p_idx, p_id),
     m_capacity(p_m_capacity),
     m_factor(p_factor),
     m_speed(p_speed) {
 #if 0
         ENTERING();
 #endif
         m_path.clear();
         pgassert(starting_site.opens() <= starting_site.closes());
         pgassert(ending_site.opens() <= ending_site.closes());
         pgassert(capacity() > 0);
 #if 0
         msg.log << "p_idx: " << p_idx << "\t idx(): " << idx() << "\n";
         msg.log << "p_id: " << p_id << "\tid(): " << id() << "\n";
 #endif
         m_path.push_back(starting_site);
         m_path.push_back(ending_site);
         evaluate(0);
         msg.log << tau() << "\n";
         invariant();
 #if 0
         EXITING();
 #endif
     }
Member Function Documentation
capacity()
double pgrouting::vrp::Vehicle::capacity () const inline
Definition at line 280 of file vehicle.h.
References deltaTime(), drop_position_limits(), evaluate(), getDropPosLowLimit(), getPosHighLimit(), getPosLowLimit(), insert_less_travel_time(), m_capacity, operator<, operator<<, path(), position_limits(), swap(), and tau().
Referenced by Vehicle().
 {return m_capacity;}
cost()
Vehicle::Cost pgrouting::vrp::Vehicle::cost () const
Definition at line 166 of file vehicle.cpp.
References cvTot(), duration(), m_path, total_wait_time(), and twvTot().
Referenced by insert(), and is_phony().
                     {
     return std::make_tuple(
             twvTot(), cvTot(), m_path.size(),
             total_wait_time(), duration());
 }
cost_compare()
bool pgrouting::vrp::Vehicle::cost_compare (const Cost & lhs, const Cost & rhs) const
Definition at line 88 of file vehicle.cpp.
Referenced by insert(), and is_phony().
{
     /*
      * capacity violations
      */
     if (std::get<1>(lhs) < std::get<1>(rhs))
         return true;
     if (std::get<1>(lhs) > std::get<1>(rhs))
         return false;
     /*
      * time window violations
      */
     if (std::get<0>(lhs) < std::get<0>(rhs))
         return true;
     if (std::get<0>(lhs) > std::get<0>(rhs))
         return false;
     /*
      * waiting time
      */
     if (std::get<3>(lhs) < std::get<3>(rhs))
         return true;
     if (std::get<3>(lhs) > std::get<3>(rhs))
         return false;
     /*
      * duration
      */
     if (std::get<4>(lhs) < std::get<4>(rhs))
         return true;
     if (std::get<4>(lhs) > std::get<4>(rhs))
         return false;
     /*
      * truck size
      */
     if (std::get<2>(lhs) < std::get<2>(rhs))
         return true;
     if (std::get<2>(lhs) > std::get<2>(rhs))
         return false;
     return false;
 }
cvTot()
int pgrouting::vrp::Vehicle::cvTot () const inline
Definition at line 255 of file vehicle.h.
Referenced by cost(), has_cv(), and tau().
{
          return m_path.back().cvTot();
      }
deltaTime()
double pgrouting::vrp::Vehicle::deltaTime (const Vehicle_node & node, POS pos) const
Definition at line 188 of file vehicle.cpp.
References pgrouting::vrp::Tw_node::closes(), pgrouting::vrp::Tw_node::is_early_arrival(), m_path, pgrouting::vrp::Tw_node::service_time(), speed(), and pgrouting::vrp::Tw_node::travel_time_to().
Referenced by capacity(), and insert_less_travel_time().
{
     /*
      * .... POS POS+1 ....
      * .... POS node POS+1 ....
      *
      */
     auto prev = m_path[pos-1];
     auto next = m_path[pos];
     auto original_time = next.travel_time();
     auto tt_p_n = prev.travel_time_to(node, speed());
     tt_p_n = node.is_early_arrival(prev.departure_time() + tt_p_n) ?
         node.closes() - prev.departure_time()
         : tt_p_n;
     auto tt_n_x = node.travel_time_to(next, speed());
     tt_p_n = next.is_early_arrival(
             prev.departure_time() + tt_p_n + node.service_time() + tt_n_x) ?
         next.closes() - (prev.departure_time() + tt_p_n + node.service_time())
         : tt_n_x;
     return (tt_p_n + tt_n_x) - original_time;
 }
drop_position_limits()
std::pair< size_t, size_t > pgrouting::vrp::Vehicle::drop_position_limits (const Vehicle_node node) const
Definition at line 401 of file vehicle.cpp.
References getDropPosLowLimit(), and getPosHighLimit().
Referenced by capacity(), and pgrouting::vrp::Vehicle_pickDeliver::semiLIFO().
{
     POS high = getPosHighLimit(node);
     POS low = getDropPosLowLimit(node);
     return std::make_pair(low, high);
 }
duration()
double pgrouting::vrp::Vehicle::duration () const inline
Definition at line 237 of file vehicle.h.
Referenced by cost(), free_time(), pgrouting::vrp::Vehicle_pickDeliver::get_worse_order(), pgrouting::vrp::Vehicle_pickDeliver::insert(), pgrouting::vrp::Optimize::sort_by_duration(), and tau().
{
          return m_path.back().departure_time();
      }
empty()
bool pgrouting::vrp::Vehicle::empty () const
return true when no nodes are in the truck
True: S E
False: S <nodes> E
Definition at line 354 of file vehicle.cpp.
References invariant(), and m_path.
Referenced by pgrouting::vrp::Vehicle_pickDeliver::get_first_order(), pgrouting::vrp::Vehicle_pickDeliver::get_worse_order(), is_phony(), pgrouting::vrp::Optimize::move_order(), pgrouting::vrp::Vehicle_pickDeliver::pop_back(), and pgrouting::vrp::Vehicle_pickDeliver::pop_front().
                      {
     invariant();
     return m_path.size() <= 2;
 }
end_site()
Vehicle_node pgrouting::vrp::Vehicle::end_site () const inline
Definition at line 274 of file vehicle.h.
References m_speed, and speed().
Referenced by is_ok().
{
          return m_path.back();
      }
erase() [1/2]
void pgrouting::vrp::Vehicle::erase (const Vehicle_node & node)
Erase node.id()
Note
start and ending nodes cannot be erased
Numbers are positions before: S .... node.id() .... E after: S .... .... E
Todo:
TODO evaluate with matrix also
Definition at line 238 of file vehicle.cpp.
References evaluate(), pgrouting::Identifier::idx(), invariant(), and m_path.
Referenced by pgrouting::vrp::Vehicle_pickDeliver::erase(), pgrouting::vrp::Vehicle_pickDeliver::insert(), is_phony(), pop_back(), pop_front(), and pgrouting::vrp::Vehicle_pickDeliver::semiLIFO().
{
     invariant();
     POS pos = 0;
     for ( ; pos < m_path.size() ; ++pos) {
         if (node.idx() == m_path[pos].idx())
             break;
     }
     erase(pos);
     evaluate(pos);
     invariant();
 }
erase() [2/2]
void pgrouting::vrp::Vehicle::erase (POS pos)
Erase node at pos from the path.
Note
start and ending nodes cannot be erased
Numbers are positions before: S 1 2 3 4 5 6 pos 8 9 E after: S 1 2 3 4 5 6 8 9 E
Parameters
[in] pos to be erased.
Definition at line 314 of file vehicle.cpp.
References evaluate(), invariant(), m_path, and pgassert.
                      {
     invariant();
     pgassert(m_path.size() > 2);
     pgassert(at < m_path.size());
     pgassert(!m_path[at].is_start());
     pgassert(!m_path[at].is_end());
     m_path.erase(m_path.begin() + at);
     evaluate(at);
     invariant();
 }
evaluate() [1/2]
void pgrouting::vrp::Vehicle::evaluate ()
@ {
Evaluate: Evaluate the whole path from the start.
Definition at line 345 of file vehicle.cpp.
References invariant().
Referenced by capacity(), erase(), insert(), pgrouting::vrp::Vehicle_pickDeliver::push_back(), pgrouting::vrp::Vehicle_pickDeliver::push_front(), swap(), and Vehicle().
                   {
     invariant();
     evaluate(0);
     invariant();
 }
evaluate() [2/2]
void pgrouting::vrp::Vehicle::evaluate (POS from)
Evaluate: Evaluate a path from the given position.
Parameters
[in] from The starting position in the path for evaluation to the end of the path.
Definition at line 366 of file vehicle.cpp.
References invariant(), m_capacity, m_path, pgassert, and speed().
{
     invariant();
     // preconditions
     pgassert(from < m_path.size());
     auto node = m_path.begin() + from;
     while (node != m_path.end()) {
         if (node == m_path.begin()) {
             node->evaluate(m_capacity);
         } else {
             node->evaluate(*(node - 1), m_capacity, speed());
         }
         ++node;
     }
     invariant();
 }
free_time()
double pgrouting::vrp::Vehicle::free_time () const inline
Definition at line 249 of file vehicle.h.
References duration(), and total_wait_time().
{
          return total_wait_time() + (m_path[0].closes() - duration());
      }
get_postgres_result()
std::vector< General_vehicle_orders_t > pgrouting::vrp::Vehicle::get_postgres_result (int vid) const
Definition at line 135 of file vehicle.cpp.
References pgrouting::Identifier::id(), pgrouting::Pgr_messages::log, m_path, pgrouting::vrp::PD_problem::msg, and tau().
{
     std::vector<General_vehicle_orders_t> result;
     /* postgres numbering starts with 1 */
     int stop_seq(1);
     msg.log << "getting solution: " << tau() << "\n";
     for (const auto p_stop : m_path) {
         General_vehicle_orders_t data = {
             vid,
             id(),
             stop_seq,
             /* order_id
              * The order_id is invalid for stops type 0 and 5
              */
             (p_stop.type() == 0 || p_stop.type() == 5)? -1 : p_stop.order(),
             p_stop.id(),
             p_stop.type(),
             p_stop.cargo(),
             p_stop.travel_time(),
             p_stop.arrival_time(),
             p_stop.wait_time(),
             p_stop.service_time(),
             p_stop.departure_time()};
         result.push_back(data);
         ++stop_seq;
     }
     return result;
 }
getDropPosLowLimit()
size_t pgrouting::vrp::Vehicle::getDropPosLowLimit (const Vehicle_node & node) const private
Definition at line 422 of file vehicle.cpp.
References invariant(), m_path, and speed().
Referenced by capacity(), and drop_position_limits().
{
     invariant();
     POS low = 0;
     POS high = m_path.size();
     POS low_limit = high;
     /* J == m_path[low_limit - 1] */
     while (low_limit > low
             && m_path[low_limit - 1].is_compatible_IJ(nodeI, speed())
             && !m_path[low_limit - 1].is_pickup()) {
         --low_limit;
     }
     invariant();
     return low_limit;
 }
getPosHighLimit()
size_t pgrouting::vrp::Vehicle::getPosHighLimit (const Vehicle_node & node) const private
Definition at line 487 of file vehicle.cpp.
References invariant(), pgrouting::vrp::Tw_node::is_compatible_IJ(), m_path, and speed().
Referenced by capacity(), drop_position_limits(), and position_limits().
{
     invariant();
     POS low = 0;
     POS high = m_path.size();
     POS high_limit = low;
     /* I == m_path[high_limit] */
     while (high_limit < high
             && nodeJ.is_compatible_IJ(m_path[high_limit], speed())) {
         ++high_limit;
     }
     invariant();
     return high_limit;
 }
getPosLowLimit()
size_t pgrouting::vrp::Vehicle::getPosLowLimit (const Vehicle_node & node) const private
Definition at line 455 of file vehicle.cpp.
References invariant(), m_path, and speed().
Referenced by capacity(), and position_limits().
{
     invariant();
     POS low = 0;
     POS high = m_path.size();
     POS low_limit = high;
     /* J == m_path[low_limit - 1] */
     while (low_limit > low
             && m_path[low_limit - 1].is_compatible_IJ(nodeI, speed())) {
         --low_limit;
     }
     invariant();
     return low_limit;
 }
has_cv()
bool pgrouting::vrp::Vehicle::has_cv () const inline
Definition at line 261 of file vehicle.h.
References cvTot().
Referenced by pgrouting::vrp::Vehicle_pickDeliver::insert(), is_feasable(), pgrouting::vrp::Vehicle_pickDeliver::push_back(), pgrouting::vrp::Vehicle_pickDeliver::push_front(), and pgrouting::vrp::Vehicle_pickDeliver::semiLIFO().
{
          return cvTot() != 0;
      }
has_twv()
bool pgrouting::vrp::Vehicle::has_twv () const inline
Definition at line 258 of file vehicle.h.
References twvTot().
Referenced by is_feasable(), and pgrouting::vrp::Vehicle_pickDeliver::semiLIFO().
{
          return twvTot() != 0;
      }
id()
int64_t pgrouting::Identifier::id () const inherited
Definition at line 42 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Dnode::distance(), get_postgres_result(), is_phony(), pgrouting::vrp::operator<<(), pgrouting::operator<<(), pgrouting::vrp::Base_node::operator==(), pgrouting::vrp::Node::operator==(), pgrouting::vrp::Node::print(), tau(), and Vehicle().
                      {
     return m_id;
 }
idx()
size_t pgrouting::Identifier::idx () const inherited
Definition at line 37 of file identifier.cpp.
References pgrouting::Identifier::m_idx.
Referenced by pgrouting::vrp::Vehicle_pickDeliver::erase(), erase(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Vehicle_pickDeliver::has_order(), insert(), pgrouting::vrp::Vehicle_pickDeliver::insert(), pgrouting::vrp::operator<<(), pgrouting::operator<<(), pgrouting::vrp::Base_node::operator==(), pgrouting::vrp::Node::operator==(), pgrouting::vrp::Tw_node::operator==(), pgrouting::vrp::Node::print(), pgrouting::vrp::Vehicle_pickDeliver::push_back(), pgrouting::vrp::Vehicle_pickDeliver::push_front(), pgrouting::vrp::Vehicle_pickDeliver::semiLIFO(), pgrouting::vrp::Order::set_compatibles(), pgrouting::vrp::Solution::sort_by_id(), tau(), pgrouting::vrp::Tw_node::travel_time_to(), and Vehicle().
                       {
     return m_idx;
 }
insert() [1/2]
void pgrouting::vrp::Vehicle::insert (POS pos, Vehicle_node node)
@ {
Insert node at pos position.
Parameters
[in] pos The position that the node should be inserted.
[in] node The node to insert.
Definition at line 174 of file vehicle.cpp.
References evaluate(), pgrouting::Identifier::idx(), invariant(), m_path, and pgassert.
Referenced by insert(), pgrouting::vrp::Vehicle_pickDeliver::insert(), insert_less_travel_time(), is_phony(), push_back(), push_front(), and pgrouting::vrp::Vehicle_pickDeliver::semiLIFO().
{
     invariant();
     pgassert(at <= m_path.size());
     m_path.insert(m_path.begin() + at, node);
     evaluate(at);
     pgassert(at < m_path.size());
     pgassert(m_path[at].idx() == node.idx());
     invariant();
 }
insert() [2/2]
size_t pgrouting::vrp::Vehicle::insert (std::pair< POS, POS > position_limits, const Vehicle_node & node)
Insert node in best position of the position_limits.
Parameters
[in] position_limits
[in] node The node to insert
Returns
position where it was inserted
Definition at line 54 of file vehicle.cpp.
References cost(), cost_compare(), pgrouting::Identifier::idx(), insert(), invariant(), m_path, pgassert, and swap().
{
     invariant();
     pgassert(position_limits.first <= m_path.size());
     pgassert(position_limits.second <= m_path.size());
     auto low = position_limits.first;
     auto high = position_limits.second;
     auto best = low;
     insert(low, node);
     Vehicle::Cost best_cost(cost());
     while (low < high) {
         swap(low, low + 1);
         ++low;
         if (cost_compare(best_cost, cost())) {
             best_cost = cost();
             best = low;
         }
     }
     return best;
     pgassert(best < m_path.size());
     pgassert(m_path[best].idx() == node.idx());
     invariant();
 }
insert_less_travel_time()
size_t pgrouting::vrp::Vehicle::insert_less_travel_time (const Vehicle_node & node, POS after_pos = 0)
Definition at line 215 of file vehicle.cpp.
References deltaTime(), insert(), invariant(), and m_path.
Referenced by capacity().
{
     invariant();
     double min_delta = (std::numeric_limits<double>::max)();
     POS min_pos = after_pos;
     for (POS pos = after_pos; pos < m_path.size(); ++pos) {
         if (!m_path[pos].is_start()) {
             auto tt = deltaTime(node, pos);
             if (tt < min_delta) {
                 min_delta = tt;
                 min_pos = pos;
             }
         }
     }
     insert(min_pos, node);
     invariant();
     return min_pos;
 }
invariant()
void pgrouting::vrp::Vehicle::invariant () const
Invariant The path must:
have at least 2 nodes
first node of the path must be Start node
last node of the path must be End node
path: S ..... E
Definition at line 47 of file vehicle.cpp.
References m_path, and pgassert.
Referenced by pgrouting::vrp::Vehicle_pickDeliver::do_while_feasable(), empty(), pgrouting::vrp::Vehicle_pickDeliver::erase(), erase(), evaluate(), pgrouting::vrp::Vehicle_pickDeliver::get_first_order(), pgrouting::vrp::Vehicle_pickDeliver::get_worse_order(), getDropPosLowLimit(), getPosHighLimit(), getPosLowLimit(), insert(), pgrouting::vrp::Vehicle_pickDeliver::insert(), insert_less_travel_time(), is_phony(), pgrouting::vrp::operator<(), pgrouting::vrp::operator<<(), path(), pop_back(), pgrouting::vrp::Vehicle_pickDeliver::pop_back(), pop_front(), pgrouting::vrp::Vehicle_pickDeliver::pop_front(), pgrouting::vrp::Vehicle_pickDeliver::push_back(), push_back(), pgrouting::vrp::Vehicle_pickDeliver::push_front(), push_front(), pgrouting::vrp::Vehicle_pickDeliver::semiLIFO(), size(), swap(), Vehicle(), and pgrouting::vrp::Vehicle_pickDeliver::Vehicle_pickDeliver().
{
     pgassert(m_path.size() >= 2);
     pgassert(m_path.front().is_start());
     pgassert(m_path.back().is_end());
 }
is_feasable()
bool pgrouting::vrp::Vehicle::is_feasable () const inline
Definition at line 265 of file vehicle.h.
References has_cv(), has_twv(), and is_ok().
Referenced by pgrouting::vrp::Vehicle_pickDeliver::do_while_feasable(), pgrouting::vrp::Vehicle_pickDeliver::insert(), pgrouting::vrp::Vehicle_pickDeliver::semiLIFO(), and pgrouting::vrp::Optimize::swap_order().
{
          return !(has_twv() ||  has_cv());
      }
is_ok()
bool pgrouting::vrp::Vehicle::is_ok () const
Definition at line 505 of file vehicle.cpp.
References pgrouting::vrp::Tw_node::closes(), end_site(), m_capacity, m_path, pgrouting::vrp::Tw_node::opens(), pgassert, and start_site().
Referenced by is_feasable().
                      {
     pgassert((m_path.front().opens() <= m_path.front().closes())
         && (m_path.back().opens() <= m_path.back().closes())
         && (m_capacity > 0));
     return (start_site().opens() <= start_site().closes())
         && (end_site().opens() <= end_site().closes())
         && (m_capacity > 0);
 }
is_phony()
bool pgrouting::vrp::Vehicle::is_phony () const inline
Definition at line 101 of file vehicle.h.
References cost(), cost_compare(), empty(), erase(), pgrouting::Identifier::id(), insert(), invariant(), pop_back(), pop_front(), position_limits(), push_back(), push_front(), size(), and speed().
Referenced by pgrouting::vrp::Optimize::move_order().
 {return id() < 0;}
path()
std::deque< Vehicle_node > pgrouting::vrp::Vehicle::path () const
@ {
Definition at line 387 of file vehicle.cpp.
References invariant(), and m_path.
Referenced by capacity(), and pgrouting::vrp::operator<<().
                     {
     invariant();
     return m_path;
 }
pop_back()
void pgrouting::vrp::Vehicle::pop_back ()
Evaluated: pop_back a node to the path.
before: S <nodes> n E
after: S <nodes> E
Definition at line 290 of file vehicle.cpp.
References erase(), invariant(), m_path, and pgassert.
Referenced by is_phony().
                   {
     invariant();
     pgassert(m_path.size() > 2);
     /* erase evaluates */
     erase(m_path.size() - 2);
     invariant();
 }
pop_front()
void pgrouting::vrp::Vehicle::pop_front ()
Evaluated: pop_front a node to the path.
before: S n <nodes> E
after: S <nodes> E
Definition at line 301 of file vehicle.cpp.
References erase(), invariant(), m_path, and pgassert.
Referenced by is_phony().
                    {
     invariant();
     pgassert(m_path.size() > 2);
     /* erase evaluates */
     erase(1);
     invariant();
 }
position_limits()
std::pair< size_t, size_t > pgrouting::vrp::Vehicle::position_limits (const Vehicle_node node) const
Definition at line 394 of file vehicle.cpp.
References getPosHighLimit(), and getPosLowLimit().
Referenced by capacity(), pgrouting::vrp::Vehicle_pickDeliver::insert(), and is_phony().
{
     POS high = getPosHighLimit(node);
     POS low = getPosLowLimit(node);
     return std::make_pair(low, high);
 }
push_back()
void pgrouting::vrp::Vehicle::push_back (const Vehicle_node & node)
Evaluated: push_back a node to the path.
before: S <nodes> E
after: S <nodes> n E
Parameters
[in] node to be push_back.
Definition at line 280 of file vehicle.cpp.
References insert(), invariant(), and m_path.
Referenced by is_phony().
{
     invariant();
     /* insert evaluates */
     insert(m_path.size() - 1, node);
     invariant();
 }
push_front()
void pgrouting::vrp::Vehicle::push_front (const Vehicle_node & node)
Evaluated: push_back a node to the path.
before: S <nodes> E
after: S n <nodes> E
Parameters
[in] node to be push_back.
Definition at line 263 of file vehicle.cpp.
References insert(), and invariant().
Referenced by is_phony().
{
     invariant();
     /* insert evaluates */
     insert(1, node);
     invariant();
 }
reset_id()
void pgrouting::Identifier::reset_id (int64_t _id) inherited
Definition at line 47 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Tw_node::Tw_node().
{
     m_id = _id;
 }
size()
size_t pgrouting::vrp::Vehicle::size () const
return number of nodes in the truck
True: S E
False: S <nodes> E
Definition at line 360 of file vehicle.cpp.
References invariant(), and m_path.
Referenced by is_phony(), and pgrouting::vrp::Optimize::move_order().
                     {
     invariant();
     return m_path.size() - 2;
 }
speed()
double pgrouting::vrp::Vehicle::speed () const
Definition at line 587 of file vehicle.cpp.
References m_factor, and m_speed.
Referenced by deltaTime(), end_site(), evaluate(), getDropPosLowLimit(), getPosHighLimit(), getPosLowLimit(), is_phony(), pgrouting::vrp::operator<<(), and pgrouting::vrp::Vehicle_pickDeliver::set_compatibles().
                      {
     return m_speed/m_factor;
 }
start_site()
Vehicle_node pgrouting::vrp::Vehicle::start_site () const inline
Definition at line 271 of file vehicle.h.
Referenced by is_ok().
{
          return m_path.front();
      }
swap()
void pgrouting::vrp::Vehicle::swap (POS i, POS j)
Swap two nodes in the path.
Before: S <nodesA> I <nodesB> J <nodesC> E
After: S <nodesA> J <nodesB> I <nodesC> E
Parameters
[in] i The position of the first node to swap.
[in] j The position of the second node to swap.
Definition at line 329 of file vehicle.cpp.
References evaluate(), invariant(), m_path, and pgassert.
Referenced by capacity(), and insert().
{
     invariant();
     pgassert(m_path.size() > 3);
     pgassert(!m_path[i].is_start());
     pgassert(!m_path[i].is_end());
     pgassert(!m_path[j].is_start());
     pgassert(!m_path[j].is_end());
     std::swap(m_path[i], m_path[j]);
     i < j ? evaluate(i) : evaluate(j);
     invariant();
 }
tau()
std::string pgrouting::vrp::Vehicle::tau () const
Definition at line 567 of file vehicle.cpp.
References cvTot(), duration(), pgrouting::Identifier::id(), pgrouting::Identifier::idx(), m_path, pgassert, total_wait_time(), and twvTot().
Referenced by capacity(), get_postgres_result(), pgrouting::vrp::Vehicle_pickDeliver::insert(), pgrouting::vrp::operator<<(), and Vehicle().
                    {
     pgassert(m_path.size() > 1);
     std::ostringstream log;
     log << "Truck " << id() << "(" << idx() << ")"
         << " (";
     for (const auto p_stop : m_path) {
         if (!(p_stop == m_path.front()))
             log << ", ";
         log << p_stop.id();
     }
     log << ")" << " \t(cv, twv, wait_time, duration) = ("
         << cvTot() << ", "
         << twvTot() << ", "
         << total_wait_time() << ", "
         << duration() << ")";
     return log.str();
 }
total_service_time()
double pgrouting::vrp::Vehicle::total_service_time () const inline
Definition at line 246 of file vehicle.h.
{
          return m_path.back().total_service_time();
      }
total_travel_time()
double pgrouting::vrp::Vehicle::total_travel_time () const inline
Definition at line 243 of file vehicle.h.
{
          return m_path.back().total_travel_time();
      }
total_wait_time()
double pgrouting::vrp::Vehicle::total_wait_time () const inline
Definition at line 240 of file vehicle.h.
Referenced by cost(), free_time(), pgrouting::vrp::Optimize::sort_for_move(), and tau().
{
          return m_path.back().total_wait_time();
      }
twvTot()
int pgrouting::vrp::Vehicle::twvTot () const inline
Definition at line 252 of file vehicle.h.
Referenced by cost(), has_twv(), and tau().
{
          return m_path.back().twvTot();
      }
Friends And Related Function Documentation
operator<
bool operator< (const Vehicle & lhs, const Vehicle & rhs) friend
Definition at line 612 of file vehicle.cpp.
Referenced by capacity().
{
     lhs.invariant();
     rhs.invariant();
     if (lhs.m_path.size() < rhs.m_path.size()) return true;
     /* here because sizes are equal */
     if (lhs.m_path.back().total_travel_time()
             < rhs.m_path.back().total_travel_time()) return true;
     return false;
 }
operator<<
std::ostream& operator<< (std::ostream & log, const Vehicle & v) friend
@ {
Definition at line 594 of file vehicle.cpp.
Referenced by capacity().
{
     v.invariant();
     int i(0);
     log << "\n\n****************** " << v.idx() << "th VEHICLE*************\n";
     log << "id = " << v.id()
         << "\tcapacity = " << v.m_capacity
         << "\tfactor = " << v.m_factor << "\n"
         << "\tspeed = " << v.m_speed << "\n"
         << "\tnew speed = " << v.speed() << "\n";
     for (const auto &path_stop : v.path()) {
         log << "Path_stop" << ++i << "\n";
         log << path_stop << "\n";
     }
     return log;
 }
Member Data Documentation
m_capacity
double pgrouting::vrp::Vehicle::m_capacity private
Definition at line 78 of file vehicle.h.
Referenced by capacity(), evaluate(), is_ok(), and pgrouting::vrp::operator<<().
m_factor
double pgrouting::vrp::Vehicle::m_factor private
Definition at line 79 of file vehicle.h.
Referenced by pgrouting::vrp::operator<<(), and speed().
m_path
std::deque< Vehicle_node > pgrouting::vrp::Vehicle::m_path protected
Definition at line 75 of file vehicle.h.
Referenced by cost(), deltaTime(), empty(), erase(), evaluate(), pgrouting::vrp::Vehicle_pickDeliver::get_first_order(), get_postgres_result(), getDropPosLowLimit(), getPosHighLimit(), getPosLowLimit(), insert(), pgrouting::vrp::Vehicle_pickDeliver::insert(), insert_less_travel_time(), invariant(), is_ok(), pgrouting::vrp::operator<(), path(), pop_back(), pgrouting::vrp::Vehicle_pickDeliver::pop_back(), pop_front(), pgrouting::vrp::Vehicle_pickDeliver::pop_front(), pgrouting::vrp::Vehicle_pickDeliver::push_back(), push_back(), pgrouting::vrp::Vehicle_pickDeliver::push_front(), pgrouting::vrp::Vehicle_pickDeliver::semiLIFO(), size(), swap(), tau(), and Vehicle().
m_speed
double pgrouting::vrp::Vehicle::m_speed private
Definition at line 80 of file vehicle.h.
Referenced by end_site(), pgrouting::vrp::operator<<(), and speed().
msg
Pgr_messages pgrouting::vrp::PD_problem::msg static inherited
Definition at line 49 of file pd_problem.h.
Referenced by pgrouting::vrp::Fleet::add_vehicle(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), pgrouting::vrp::Optimize::delete_empty_truck(), do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), pgrouting::vrp::Vehicle_pickDeliver::do_while_feasable(), pgrouting::vrp::Initial_solution::do_while_foo(), pgrouting::vrp::Pgr_pickDeliver::get_postgres_result(), get_postgres_result(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Fleet::is_fleet_ok(), pgrouting::vrp::Pgr_pickDeliver::nodesOK(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), pgrouting::vrp::Optimize::Optimize(), pgrouting::vrp::Pgr_pickDeliver::optimize(), pgrouting::vrp::PD_problem::PD_problem(), pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Optimize::save_if_best(), pgrouting::vrp::Solution::Solution(), pgrouting::vrp::Pgr_pickDeliver::solve(), pgrouting::vrp::Optimize::swap_order(), and Vehicle().
problem
Pgr_pickDeliver * pgrouting::vrp::PD_problem::problem static protected inherited
Definition at line 52 of file pd_problem.h.
Referenced by pgrouting::vrp::PD_Orders::add_order(), pgrouting::vrp::Fleet::add_vehicle(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), pgrouting::vrp::Dnode::distance(), pgrouting::vrp::Solution::get_kind(), pgrouting::vrp::Pgr_pickDeliver::get_kind(), pgrouting::vrp::operator<<(), pgrouting::vrp::Tw_node::operator==(), and pgrouting::vrp::Tw_node::travel_time_to().
The documentation for this class was generated from the following files:
vehicle.h
vehicle.cpp