PGROUTING: Pgr_randomSpanningTree< G > Class Template Reference
Pgr_randomSpanningTree< G > Class Template Reference
#include "pgr_randomSpanningTree.hpp"
Public Types
typedef G::E E
typedef G::V V
Public Member Functions
std::vector< pgr_randomSpanningTree_t > randomSpanningTree (G &graph, int64_t root_vertex)
Private Member Functions
std::vector< pgr_randomSpanningTree_t > undirectedGraph (const G &graph, int64_t root_vertex)
Private Attributes
std::vector< V > predecessors
Detailed Description
template<class G>
class Pgr_randomSpanningTree< G >
Definition at line 46 of file pgr_randomSpanningTree.hpp.
Member Typedef Documentation
E
template<class G> typedef G::E Pgr_randomSpanningTree< G >::E
Definition at line 56 of file pgr_randomSpanningTree.hpp.
V
template<class G> typedef G::V Pgr_randomSpanningTree< G >::V
Definition at line 55 of file pgr_randomSpanningTree.hpp.
Member Function Documentation
randomSpanningTree()
template<class G > std::vector< pgr_randomSpanningTree_t > Pgr_randomSpanningTree< G >::randomSpanningTree (G & graph, int64_t root_vertex)
Definition at line 132 of file pgr_randomSpanningTree.hpp.
References Pgr_randomSpanningTree< G >::predecessors, and Pgr_randomSpanningTree< G >::undirectedGraph().
Referenced by pgr_randomSpanningTree().
{
       predecessors.clear();
       // TODO(aps)
       // Currently only running for undirected graph
       return undirectedGraph(
               graph,
               root_vertex);
 }
undirectedGraph()
template<class G> std::vector< pgr_randomSpanningTree_t > Pgr_randomSpanningTree< G >::undirectedGraph (const G & graph, int64_t root_vertex) inline private
Definition at line 68 of file pgr_randomSpanningTree.hpp.
References pgr_randomSpanningTree_t::cost, pgr_randomSpanningTree_t::edge, pgr_randomSpanningTree_t::root_vertex, and pgr_randomSpanningTree_t::tree_cost.
Referenced by Pgr_randomSpanningTree< G >::randomSpanningTree().
{
          std::ostringstream log;
          auto v_root(graph.get_V(root_vertex));
          std::minstd_rand rng;
          // TODO(aps)
          // This function is running in infinite loop
          try {
              boost::random_spanning_tree(
                      graph.graph,
                      rng,
                      boost::root_vertex(v_root)
                      .predecessor_map(&predecessors[0])
                      .weight_map(get(&G::G_T_E::cost, graph.graph)));
          } catch (std::exception const &ex) {
              log << ex.what();
          } catch (...) {
              log << "Unknown exception caught";
          }
          std::vector< pgr_randomSpanningTree_t > resul;
          return resul;
          std::vector< pgr_randomSpanningTree_t > results;
          double totalcost = 0;
          pgr_randomSpanningTree_t tmp;
          tmp.root_vertex = root_vertex;
          tmp.edge = -1;
          tmp.cost = 0;
          tmp.tree_cost = totalcost;
          results.push_back(tmp);
          for (size_t j = 0; j < predecessors.size(); j++) {
            if (j != v_root) {
              pgr_randomSpanningTree_t tmp;
              auto start_node = graph.graph[predecessors[j]].id;
              auto end_node = graph.graph[j].id;  // node
              auto v_sn(graph.get_V(start_node));
              auto v_en(graph.get_V(end_node));
              auto cost = graph[boost::edge(
                      predecessors[j], j, graph.graph).first].cost;
              auto edge_id =
                  graph.get_edge_id(v_sn, v_en, cost);
          totalcost += cost;
              tmp.root_vertex = root_vertex;
              tmp.edge = edge_id;         // edge_id
              tmp.cost = cost;            // cost
              tmp.tree_cost = totalcost;      // tree_cost
              results.push_back(tmp);
            }
          }
          return results;
     }
Member Data Documentation
predecessors
template<class G> std::vector< V > Pgr_randomSpanningTree< G >::predecessors private
Definition at line 64 of file pgr_randomSpanningTree.hpp.
Referenced by Pgr_randomSpanningTree< G >::randomSpanningTree().
The documentation for this class was generated from the following file:
pgr_randomSpanningTree.hpp