PGROUTING: pgrouting::functions::Pgr_prim< G > Class Template Reference
pgrouting::functions::Pgr_prim< G > Class Template Reference
#include "pgr_prim.hpp"
Public Member Functions
std::vector< pgr_mst_rt > prim (G &graph)
std::vector< pgr_mst_rt > primBFS (G &graph, std::vector< int64_t > roots, int64_t max_depth)
std::vector< pgr_mst_rt > primDD (G &graph, std::vector< int64_t > roots, double distance)
std::vector< pgr_mst_rt > primDFS (G &graph, std::vector< int64_t > roots, int64_t max_depth)
Protected Types
typedef G::E_i E_i
Protected Member Functions
std::vector< pgr_mst_rt > bfs_order (const G &graph)
std::vector< pgr_mst_rt > dfs_order (const G &graph)
std::vector< pgr_mst_rt > mst (const G &graph)
std::vector< pgr_mst_rt > mstBFS (const G &graph, std::vector< int64_t > roots, int64_t max_depth)
std::vector< pgr_mst_rt > mstDD (const G &graph, std::vector< int64_t > roots, double distance)
std::vector< pgr_mst_rt > mstDFS (const G &graph, std::vector< int64_t > roots, int64_t max_depth)
std::vector< pgr_mst_rt > no_order (const G &graph)
Protected Attributes
std::vector< size_t > m_components
m_components[v]:
double m_distance
bool m_get_component
int64_t m_max_depth
std::vector< int64_t > m_roots
struct pgrouting::functions::Pgr_mst::InSpanning m_spanning_tree
std::string m_suffix
Stores which function is being executed.
std::vector< int64_t > m_tree_id
m_tree_id[v]:
Private Types
typedef G::B_G B_G
typedef G::E E
typedef G::V V
Private Member Functions
void clear ()
void generate_mst (const G &graph)
void primTree (const G &graph, int64_t root_vertex)
Private Attributes
std::vector< V > data
std::vector< double > distances
std::set< V > m_unassigned
std::vector< V > predecessors
Detailed Description
template<class G>
class pgrouting::functions::Pgr_prim< G >
Definition at line 42 of file pgr_prim.hpp.
Member Typedef Documentation
B_G
template<class G> typedef G::B_G pgrouting::functions::Pgr_prim< G >::B_G private
Definition at line 45 of file pgr_prim.hpp.
E
template<class G> typedef G::E pgrouting::functions::Pgr_prim< G >::E private
Definition at line 44 of file pgr_prim.hpp.
E_i
template<class G > typedef G::E_i pgrouting::functions::Pgr_mst< G >::E_i protected inherited
Definition at line 48 of file pgr_mst.hpp.
V
template<class G> typedef G::V pgrouting::functions::Pgr_prim< G >::V private
Definition at line 43 of file pgr_prim.hpp.
Member Function Documentation
bfs_order()
template<class G > std::vector<pgr_mst_rt> pgrouting::functions::Pgr_mst< G >::bfs_order (const G & graph) inline protected inherited
Definition at line 71 of file pgr_mst.hpp.
References pgrouting::functions::Pgr_mst< G >::bfs_ordering().
Referenced by pgrouting::functions::Pgr_mst< G >::mstBFS().
{
          return bfs_ordering(graph);
      }
clear()
template<class G> void pgrouting::functions::Pgr_prim< G >::clear () inline private
Definition at line 68 of file pgr_prim.hpp.
References pgrouting::functions::Pgr_prim< G >::data, pgrouting::functions::Pgr_prim< G >::distances, pgrouting::functions::Pgr_prim< G >::generate_mst(), pgrouting::functions::Pgr_prim< G >::predecessors, and pgrouting::functions::Pgr_prim< G >::primTree().
Referenced by pgrouting::functions::Pgr_prim< G >::generate_mst(), and pgrouting::functions::Pgr_prim< G >::primTree().
                   {
          data.clear();
          predecessors.clear();
          distances.clear();
      }
dfs_order()
template<class G > std::vector<pgr_mst_rt> pgrouting::functions::Pgr_mst< G >::dfs_order (const G & graph) inline protected inherited
Definition at line 66 of file pgr_mst.hpp.
References pgrouting::functions::Pgr_mst< G >::dfs_ordering().
Referenced by pgrouting::functions::Pgr_mst< G >::mstDD(), and pgrouting::functions::Pgr_mst< G >::mstDFS().
{
          return dfs_ordering(graph);
      }
generate_mst()
template<class G > void pgrouting::functions::Pgr_prim< G >::generate_mst (const G & graph) private virtual
Implements pgrouting::functions::Pgr_mst< G >.
Definition at line 135 of file pgr_prim.hpp.
References pgrouting::functions::Pgr_prim< G >::clear(), pgrouting::functions::Pgr_prim< G >::m_unassigned, and pgrouting::functions::Pgr_prim< G >::primTree().
Referenced by pgrouting::functions::Pgr_prim< G >::clear().
{
     this->clear();
     size_t totalNodes = num_vertices(graph.graph);
     m_unassigned.clear();
     for (V v = 0; v < totalNodes; ++v) {
             m_unassigned.insert(m_unassigned.end(), v);
     }
     while (!m_unassigned.empty()) {
         auto root = *m_unassigned.begin();
         m_unassigned.erase(m_unassigned.begin());
         primTree(
                 graph,
                 graph.graph[root].id);
     }
 }
mst()
template<class G > std::vector<pgr_mst_rt> pgrouting::functions::Pgr_mst< G >::mst (const G & graph) inline protected inherited
Definition at line 75 of file pgr_mst.hpp.
References pgrouting::functions::Pgr_mst< G >::generate_mst(), pgrouting::functions::Pgr_mst< G >::m_distance, pgrouting::functions::Pgr_mst< G >::m_get_component, pgrouting::functions::Pgr_mst< G >::m_max_depth, pgrouting::functions::Pgr_mst< G >::m_roots, pgrouting::functions::Pgr_mst< G >::m_suffix, pgrouting::functions::Pgr_mst< G >::no_neg_costs(), and pgrouting::functions::Pgr_mst< G >::no_order().
Referenced by pgrouting::functions::Pgr_mst< G >::bfs_ordering(), pgrouting::functions::Pgr_kruskal< G >::kruskal(), and pgrouting::functions::Pgr_prim< G >::prim().
{
          m_suffix = "";
          m_get_component = false;
          m_distance = -1;
          m_max_depth = -1;
          m_roots.clear();
          no_neg_costs(graph);
          this->generate_mst(graph);
          return no_order(graph);
      }
mstBFS()
template<class G > std::vector<pgr_mst_rt> pgrouting::functions::Pgr_mst< G >::mstBFS (const G & graph, std::vector< int64_t > roots, int64_t max_depth) inline protected inherited
Definition at line 88 of file pgr_mst.hpp.
References pgrouting::functions::Pgr_mst< G >::bfs_order(), pgrouting::details::clean_vids(), pgrouting::functions::Pgr_mst< G >::generate_mst(), pgrouting::functions::Pgr_mst< G >::m_distance, pgrouting::functions::Pgr_mst< G >::m_get_component, pgrouting::functions::Pgr_mst< G >::m_max_depth, pgrouting::functions::Pgr_mst< G >::m_roots, and pgrouting::functions::Pgr_mst< G >::m_suffix.
Referenced by pgrouting::functions::Pgr_kruskal< G >::kruskalBFS(), and pgrouting::functions::Pgr_prim< G >::primBFS().
{
          m_suffix = "BFS";
          m_get_component = true;
          m_distance = -1;
          m_max_depth = max_depth;
          m_roots = details::clean_vids(roots);
          this->generate_mst(graph);
          return bfs_order(graph);
      }
mstDD()
template<class G > std::vector<pgr_mst_rt> pgrouting::functions::Pgr_mst< G >::mstDD (const G & graph, std::vector< int64_t > roots, double distance) inline protected inherited
Definition at line 116 of file pgr_mst.hpp.
References pgrouting::details::clean_vids(), pgrouting::functions::Pgr_mst< G >::dfs_order(), pgrouting::functions::Pgr_mst< G >::generate_mst(), pgrouting::functions::Pgr_mst< G >::m_distance, pgrouting::functions::Pgr_mst< G >::m_get_component, pgrouting::functions::Pgr_mst< G >::m_max_depth, pgrouting::functions::Pgr_mst< G >::m_roots, and pgrouting::functions::Pgr_mst< G >::m_suffix.
Referenced by pgrouting::functions::Pgr_kruskal< G >::kruskalDD(), and pgrouting::functions::Pgr_prim< G >::primDD().
{
          m_suffix = "DD";
          m_get_component = false;
          m_distance = distance;
          m_max_depth = -1;
          m_roots = details::clean_vids(roots);
          this->generate_mst(graph);
          return dfs_order(graph);
      }
mstDFS()
template<class G > std::vector<pgr_mst_rt> pgrouting::functions::Pgr_mst< G >::mstDFS (const G & graph, std::vector< int64_t > roots, int64_t max_depth) inline protected inherited
Definition at line 102 of file pgr_mst.hpp.
References pgrouting::details::clean_vids(), pgrouting::functions::Pgr_mst< G >::dfs_order(), pgrouting::functions::Pgr_mst< G >::generate_mst(), pgrouting::functions::Pgr_mst< G >::m_distance, pgrouting::functions::Pgr_mst< G >::m_get_component, pgrouting::functions::Pgr_mst< G >::m_max_depth, pgrouting::functions::Pgr_mst< G >::m_roots, and pgrouting::functions::Pgr_mst< G >::m_suffix.
Referenced by pgrouting::functions::Pgr_kruskal< G >::kruskalDFS(), and pgrouting::functions::Pgr_prim< G >::primDFS().
{
          m_suffix = "DFS";
          m_get_component = false;
          m_distance = -1;
          m_max_depth = max_depth;
          m_roots = details::clean_vids(roots);
          this->generate_mst(graph);
          return dfs_order(graph);
      }
no_order()
template<class G > std::vector<pgr_mst_rt> pgrouting::functions::Pgr_mst< G >::no_order (const G & graph) inline protected inherited
Definition at line 61 of file pgr_mst.hpp.
References pgrouting::functions::Pgr_mst< G >::no_ordering().
Referenced by pgrouting::functions::Pgr_mst< G >::mst().
{
          return no_ordering(graph);
      }
prim()
template<class G > std::vector< pgr_mst_rt > pgrouting::functions::Pgr_prim< G >::prim (G & graph)
Definition at line 156 of file pgr_prim.hpp.
References pgrouting::functions::Pgr_mst< G >::mst().
Referenced by do_pgr_prim().
                   {
     return this->mst(graph);
 }
primBFS()
template<class G > std::vector< pgr_mst_rt > pgrouting::functions::Pgr_prim< G >::primBFS (G & graph, std::vector< int64_t > roots, int64_t max_depth)
Definition at line 163 of file pgr_prim.hpp.
References pgrouting::functions::Pgr_mst< G >::mstBFS().
Referenced by do_pgr_prim().
{
     return this->mstBFS(graph, roots, max_depth);
 }
primDD()
template<class G > std::vector< pgr_mst_rt > pgrouting::functions::Pgr_prim< G >::primDD (G & graph, std::vector< int64_t > roots, double distance)
Definition at line 181 of file pgr_prim.hpp.
References pgrouting::functions::Pgr_mst< G >::mstDD().
Referenced by do_pgr_prim().
{
     return this->mstDD(graph, roots, distance);
 }
primDFS()
template<class G > std::vector< pgr_mst_rt > pgrouting::functions::Pgr_prim< G >::primDFS (G & graph, std::vector< int64_t > roots, int64_t max_depth)
Definition at line 172 of file pgr_prim.hpp.
References pgrouting::functions::Pgr_mst< G >::mstDFS().
Referenced by do_pgr_prim().
{
     return this->mstDFS(graph, roots, max_depth);
 }
primTree()
template<class G > void pgrouting::functions::Pgr_prim< G >::primTree (const G & graph, int64_t root_vertex) private
Definition at line 91 of file pgr_prim.hpp.
References pgrouting::functions::Pgr_prim< G >::clear(), pgrouting::functions::Pgr_prim< G >::data, pgrouting::functions::Pgr_prim< G >::distances, pgrouting::functions::Pgr_mst< G >::InSpanning::edges, pgrouting::functions::Pgr_mst< G >::m_spanning_tree, pgrouting::functions::Pgr_prim< G >::m_unassigned, and pgrouting::functions::Pgr_prim< G >::predecessors.
Referenced by pgrouting::functions::Pgr_prim< G >::clear(), and pgrouting::functions::Pgr_prim< G >::generate_mst().
{
     clear();
     predecessors.resize(graph.num_vertices());
     distances.resize(graph.num_vertices());
     auto v_root(graph.get_V(root_vertex));
     using prim_visitor = visitors::Prim_dijkstra_visitor<V>;
     boost::prim_minimum_spanning_tree(
             graph.graph,
             &predecessors[0],
             boost::distance_map(&distances[0]).
             weight_map(get(&G::G_T_E::cost, graph.graph))
             .root_vertex(v_root)
             .visitor(prim_visitor(data)));
     for (const auto v : data) {
         /*
          * its not a tree, its a forest
          * - v is not on current tree
          */
         if (std::isinf(distances[v])) continue;
         m_unassigned.erase(v);
         auto u = predecessors[v];
         /*
          * Not a valid edge
          */
         if (u == v) continue;
         auto cost = distances[u] - distances[v];
         auto edge = graph.get_edge(u, v, cost);
         this->m_spanning_tree.edges.insert(edge);
     }
 }
Member Data Documentation
data
template<class G> std::vector<V> pgrouting::functions::Pgr_prim< G >::data private
Definition at line 84 of file pgr_prim.hpp.
Referenced by pgrouting::functions::Pgr_prim< G >::clear(), and pgrouting::functions::Pgr_prim< G >::primTree().
distances
template<class G> std::vector<double> pgrouting::functions::Pgr_prim< G >::distances private
Definition at line 83 of file pgr_prim.hpp.
Referenced by pgrouting::functions::Pgr_prim< G >::clear(), and pgrouting::functions::Pgr_prim< G >::primTree().
m_components
template<class G > std::vector<size_t> pgrouting::functions::Pgr_mst< G >::m_components protected inherited
m_components[v]:
is empty (when m_get_component = 0)
has the component number of vertex v (when m_get_component != 0)
Definition at line 147 of file pgr_mst.hpp.
Referenced by pgrouting::functions::Pgr_mst< G >::clear().
m_distance
template<class G > double pgrouting::functions::Pgr_mst< G >::m_distance protected inherited
Definition at line 134 of file pgr_mst.hpp.
Referenced by pgrouting::functions::Pgr_mst< G >::mst(), pgrouting::functions::Pgr_mst< G >::mstBFS(), pgrouting::functions::Pgr_mst< G >::mstDD(), and pgrouting::functions::Pgr_mst< G >::mstDFS().
m_get_component
template<class G > bool pgrouting::functions::Pgr_mst< G >::m_get_component protected inherited
Definition at line 132 of file pgr_mst.hpp.
Referenced by pgrouting::functions::Pgr_mst< G >::mst(), pgrouting::functions::Pgr_mst< G >::mstBFS(), pgrouting::functions::Pgr_mst< G >::mstDD(), and pgrouting::functions::Pgr_mst< G >::mstDFS().
m_max_depth
template<class G > int64_t pgrouting::functions::Pgr_mst< G >::m_max_depth protected inherited
Definition at line 133 of file pgr_mst.hpp.
Referenced by pgrouting::functions::Pgr_mst< G >::mst(), pgrouting::functions::Pgr_mst< G >::mstBFS(), pgrouting::functions::Pgr_mst< G >::mstDD(), and pgrouting::functions::Pgr_mst< G >::mstDFS().
m_roots
template<class G > std::vector<int64_t> pgrouting::functions::Pgr_mst< G >::m_roots protected inherited
Definition at line 131 of file pgr_mst.hpp.
Referenced by pgrouting::functions::Pgr_mst< G >::bfs_ordering(), pgrouting::functions::Pgr_mst< G >::mst(), pgrouting::functions::Pgr_mst< G >::mstBFS(), pgrouting::functions::Pgr_mst< G >::mstDD(), and pgrouting::functions::Pgr_mst< G >::mstDFS().
m_spanning_tree
template<class G > struct pgrouting::functions::Pgr_mst::InSpanning pgrouting::functions::Pgr_mst< G >::m_spanning_tree protected inherited
Referenced by pgrouting::functions::Pgr_mst< G >::bfs_ordering(), pgrouting::functions::Pgr_mst< G >::clear(), pgrouting::functions::Pgr_mst< G >::InSpanning::clear(), pgrouting::functions::Pgr_mst< G >::dfs_forest(), pgrouting::functions::Pgr_mst< G >::dfs_ordering(), pgrouting::functions::Pgr_mst< G >::no_ordering(), and pgrouting::functions::Pgr_prim< G >::primTree().
m_suffix
template<class G > std::string pgrouting::functions::Pgr_mst< G >::m_suffix protected inherited
Stores which function is being executed.
TODO change to enum
Definition at line 154 of file pgr_mst.hpp.
Referenced by pgrouting::functions::Pgr_mst< G >::mst(), pgrouting::functions::Pgr_mst< G >::mstBFS(), pgrouting::functions::Pgr_mst< G >::mstDD(), and pgrouting::functions::Pgr_mst< G >::mstDFS().
m_tree_id
template<class G > std::vector<int64_t> pgrouting::functions::Pgr_mst< G >::m_tree_id protected inherited
m_tree_id[v]:
is empty (when m_get_component = 0)
has the component number of vertex v (when m_get_component = 1)
has the min vertex id that belongs to the component (when m_get_component = 2)
Definition at line 161 of file pgr_mst.hpp.
Referenced by pgrouting::functions::Pgr_mst< G >::bfs_ordering(), and pgrouting::functions::Pgr_mst< G >::clear().
m_unassigned
template<class G> std::set<V> pgrouting::functions::Pgr_prim< G >::m_unassigned private
Definition at line 85 of file pgr_prim.hpp.
Referenced by pgrouting::functions::Pgr_prim< G >::generate_mst(), and pgrouting::functions::Pgr_prim< G >::primTree().
predecessors
template<class G> std::vector<V> pgrouting::functions::Pgr_prim< G >::predecessors private
Definition at line 82 of file pgr_prim.hpp.
Referenced by pgrouting::functions::Pgr_prim< G >::clear(), and pgrouting::functions::Pgr_prim< G >::primTree().
The documentation for this class was generated from the following file:
pgr_prim.hpp