PGROUTING: pgrouting::Pgr_messages Class Reference
pgrouting::Pgr_messages Class Reference
#include "pgr_messages.h"
Public Member Functions
Pgr_messages ()=default
Pgr_messages (const Pgr_messages &)
void clear ()
clear
std::string get_dbglog () const
get_error
std::string get_error () const
get_error
std::string get_log () const
get_log
std::string get_notice () const
get_notice
bool has_error () const
get_error
Pgr_messages & operator= (const Pgr_messages &)
Public Attributes
std::ostringstream dbg_log
std::ostringstream error
Stores the error information.
std::ostringstream log
Stores the hint information.
std::ostringstream notice
Stores the notice information.
Detailed Description
Definition at line 39 of file pgr_messages.h.
Constructor & Destructor Documentation
Pgr_messages() [1/2]
pgrouting::Pgr_messages::Pgr_messages () default
Pgr_messages() [2/2]
pgrouting::Pgr_messages::Pgr_messages (const Pgr_messages &) inline
Definition at line 42 of file pgr_messages.h.
 { }
Member Function Documentation
clear()
void pgrouting::Pgr_messages::clear ()
clear
Clears All the messages
Definition at line 66 of file pgr_messages.cpp.
References dbg_log, error, log, and notice.
Referenced by pgrouting::vrp::Fleet::build_fleet(), do_pgr_pickDeliver(), operator=(), and pgrouting::vrp::PD_problem::PD_problem().
                     {
     log.str("");
     log.clear();
     notice.str("");
     notice.clear();
     error.str("");
     error.clear();
 #ifndef NDEBUG
     dbg_log.str("");
     dbg_log.clear();
 #endif
 }
get_dbglog()
std::string pgrouting::Pgr_messages::get_dbglog () const
get_error
Returns
the current contents of the log and clears the log
Definition at line 60 of file pgr_messages.cpp.
References dbg_log.
Referenced by operator=().
{
     return dbg_log.str();
 }
get_error()
std::string pgrouting::Pgr_messages::get_error () const
get_error
Returns
the current contents of the log and clears the log
Definition at line 53 of file pgr_messages.cpp.
References error.
Referenced by pgrouting::vrp::Fleet::build_fleet(), do_pgr_many_withPointsDD(), do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), do_pgr_withPoints(), do_pgr_withPointsKsp(), pgrouting::vrp::Fleet::is_fleet_ok(), operator=(), and pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver().
{
     auto str = error.str();
     return str;
 }
get_log()
std::string pgrouting::Pgr_messages::get_log () const
get_log
Returns
the current contents of the log and clears the log
Definition at line 36 of file pgr_messages.cpp.
References log.
Referenced by do_pgr_many_withPointsDD(), do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), do_pgr_withPoints(), do_pgr_withPointsKsp(), pgrouting::vrp::Initial_solution::do_while_foo(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Pgr_pickDeliver::nodesOK(), operator=(), pgr_bellman_ford(), pgr_dijkstraTR(), and pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver().
{
     auto str = log.str();
     return str;
 }
get_notice()
std::string pgrouting::Pgr_messages::get_notice () const
get_notice
Returns
the current contents of the log and clears the log
Definition at line 42 of file pgr_messages.cpp.
References notice.
Referenced by operator=().
{
     auto str = notice.str();
     return str;
 }
has_error()
bool pgrouting::Pgr_messages::has_error () const
get_error
Returns
the current contents of the log and clears the log
Definition at line 48 of file pgr_messages.cpp.
References error.
Referenced by do_pgr_many_withPointsDD(), do_pgr_withPoints(), do_pgr_withPointsKsp(), and operator=().
{
     return  !error.str().empty();
 }
operator=()
Pgr_messages& pgrouting::Pgr_messages::operator= (const Pgr_messages &) inline
Definition at line 43 of file pgr_messages.h.
References clear(), get_dbglog(), get_error(), get_log(), get_notice(), has_error(), and log.
{
         return *this;
     }
Member Data Documentation
dbg_log
std::ostringstream pgrouting::Pgr_messages::dbg_log mutable
Definition at line 108 of file pgr_messages.h.
Referenced by clear(), get_dbglog(), and pgrouting::vrp::Optimize::save_if_best().
error
std::ostringstream pgrouting::Pgr_messages::error mutable
Stores the error information.
Definition at line 106 of file pgr_messages.h.
Referenced by pgrouting::vrp::Fleet::build_fleet(), pgrouting::Pg_points_graph::check_points(), clear(), pgrouting::Pg_points_graph::create_new_edges(), get_error(), has_error(), pgrouting::vrp::Fleet::is_fleet_ok(), and pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver().
log
std::ostringstream pgrouting::Pgr_messages::log mutable
Stores the hint information.
Definition at line 102 of file pgr_messages.h.
Referenced by pgrouting::vrp::Fleet::add_vehicle(), Pgr_bellman_ford< G >::bellman_ford(), Pgr_bellman_ford< G >::bellman_ford_1_to_1(), Pgr_bellman_ford< G >::bellman_ford_1_to_many(), pgrouting::alphashape::Pgr_alphaShape::build_best_alpha(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), pgrouting::Pg_points_graph::check_points(), clear(), pgrouting::Pg_points_graph::create_new_edges(), pgrouting::vrp::Optimize::delete_empty_truck(), pgrouting::vrp::Vehicle_pickDeliver::do_while_feasable(), pgrouting::vrp::Initial_solution::do_while_foo(), get_log(), Pgr_bellman_ford< G >::get_paths(), pgrouting::vrp::Pgr_pickDeliver::get_postgres_result(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Fleet::is_fleet_ok(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), operator=(), pgrouting::vrp::Optimize::Optimize(), pgrouting::vrp::Pgr_pickDeliver::optimize(), pgrouting::Pg_points_graph::Pg_points_graph(), pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Optimize::save_if_best(), pgrouting::vrp::Solution::Solution(), pgrouting::vrp::Pgr_pickDeliver::solve(), pgrouting::vrp::Optimize::swap_order(), and pgrouting::vrp::Vehicle::Vehicle().
notice
std::ostringstream pgrouting::Pgr_messages::notice mutable
Stores the notice information.
Definition at line 104 of file pgr_messages.h.
Referenced by clear(), and get_notice().
The documentation for this class was generated from the following files:
pgr_messages.h
pgr_messages.cpp