PGROUTING: pgrouting::tsp::TSP< MATRIX > Class Template Reference
pgrouting::tsp::TSP< MATRIX > Class Template Reference
#include "pgr_tsp.hpp"
Public Member Functions
TSP (const MATRIX &_costs)
void annealing (double initial_temperature, double final_temperature, double cooling_factor, int64_t tries_per_temperature, int64_t max_changes_per_temperature, int64_t max_consecutive_non_changes, bool randomize, double time_limit)
std::string get_log () const
std::string get_stats () const
Tour get_tour () const
void greedyInitial (size_t idx_start=0)
Private Member Functions
size_t find_closest_city (size_t current_city, const std::set< size_t > &inserted) const
double getDeltaReverse (size_t posA, size_t posC) const
double getDeltaSlide (size_t posP, size_t posF, size_t posL) const
double getDeltaSwap (size_t posA, size_t posC) const
void invariant () const
void swapClimb ()
void update_if_best ()
Private Attributes
Tour best_tour
double bestCost
double current_cost
Tour current_tour
double epsilon
size_t improve_count
std::ostringstream log
size_t n
size_t reverse_count
size_t slide_count
size_t swap_count
int updatecalls
Detailed Description
template<typename MATRIX>
class pgrouting::tsp::TSP< MATRIX >
Definition at line 77 of file pgr_tsp.hpp.
Constructor & Destructor Documentation
TSP()
template<typename MATRIX> pgrouting::tsp::TSP< MATRIX >::TSP (const MATRIX & _costs) inline explicit
Definition at line 86 of file pgr_tsp.hpp.
References pgrouting::tsp::TSP< MATRIX >::best_tour, pgrouting::tsp::TSP< MATRIX >::bestCost, pgrouting::tsp::TSP< MATRIX >::current_cost, pgrouting::tsp::TSP< MATRIX >::current_tour, pgrouting::tsp::TSP< MATRIX >::n, and pgassert.
          : MATRIX(_costs),
          current_tour(_costs.size()),
          best_tour(_costs.size()),
          epsilon(0.000001),
          n(_costs.size()),
          updatecalls(0),
          swap_count(0),
          slide_count(0),
          reverse_count(0),
          improve_count(0) {
              pgassert(n == MATRIX::size());
              bestCost = MATRIX::tourCost(best_tour);
              current_cost = MATRIX::tourCost(current_tour);
              pgassert(bestCost == current_cost);
          }
Member Function Documentation
annealing()
template<typename MATRIX > void pgrouting::tsp::TSP< MATRIX >::annealing (double initial_temperature, double final_temperature, double cooling_factor, int64_t tries_per_temperature, int64_t max_changes_per_temperature, int64_t max_consecutive_non_changes, bool randomize, double time_limit)
Definition at line 429 of file pgr_tsp.cpp.
References pgassert, rand(), and succ().
Referenced by do_pgr_euclideanTSP(), do_pgr_tsp(), pgrouting::tsp::TSP< MATRIX >::find_closest_city(), and pgrouting::tsp::TSP< MATRIX >::get_log().
{
     invariant();
     clock_t start_time(clock());
     if (randomize) {
         std::srand(static_cast<unsigned int>(time(NULL)));
     } else {
         std::srand(1);
     }
     /* annealing schedule */
     for (; final_temperature < temperature; temperature *= cooling_factor) {
         invariant();
         log << "\nCycle(" << temperature <<") ";
         /*
            how many times the tour changed in current temperature
            */
         int64_t pathchg = 0;
         size_t enchg = 0;
         int64_t non_change = 0;
         for (int64_t j = 0; j < tries_per_temperature; j++) {
             ++non_change;
             auto which = rand(2);
             // which = 1;
             switch (which) {
                 case 0: {
                             /* reverse */
                             pgassert(n > 2);
                             auto c1 = std::rand() % n;
                             auto c2 = std::rand() % n;
                             if (c1 == c2) c2 = succ(c2, n);
                             if (c1 == (c2 - 1)) c2 = succ(c2, n);
                             if (c1 > c2) std::swap(c1, c2);
                             pgassert(c1 != c2);
                             pgassert(c1 < n && c2 < n);
                             pgassert(c1 < c2);
                             auto energyChange = getDeltaReverse(c1, c2);
                             if ( (energyChange < 0
                                         && epsilon < std::fabs(energyChange))
                                     || (0 < energyChange
                                         &&  (
                                             static_cast<double>(std::rand()) /
                                             static_cast<double>(RAND_MAX))
                                         < exp(-energyChange / temperature))) {
                                 if (energyChange < 0) ++enchg;
                                 ++reverse_count;
                                 ++pathchg;
                                 non_change = 0;
                                 current_cost += energyChange;
                                 current_tour.reverse(c1, c2);
                                 update_if_best();
                             }
                         }
                         break;
                 case 1: {
                             /* slide */
                             if (n <= 3) {
                                 break;
                             }
                             pgassert(n > 3);
                             auto first = std::rand() % n;
                             auto last = std::rand() % n;
                             if (first == last) last = succ(last, n);
                             if (first > last) std::swap(first, last);
                             if (first == 0 && last == (n - 1)) {
                                 first = succ(first, n);
                             }
                             pgassert((n - (last - first) - 1) > 0);
                             auto place = std::rand() % (n - (last - first) - 1);
                             place = place < first?  place :
                                 last + (place - first) + 1;
                             pgassert((place < first
                                         || place > last)
                                     && (first < last));
                             auto energyChange = getDeltaSlide(
                                     place, first, last);
                             if ((energyChange < 0
                                         && epsilon < std::fabs(energyChange))
                                     || (0 < energyChange
                                         &&  (static_cast<double>(std::rand())
                                             / static_cast<double>(RAND_MAX))
                                         < exp(-energyChange / temperature))) {
                                 if (energyChange < 0) ++enchg;
                                 ++slide_count;
                                 ++pathchg;
                                 non_change = 0;
                                 current_cost += energyChange;
                                 current_tour.slide(place, first, last);
                                 update_if_best();
                             }
                         }
                         break;
             }  // switch
             if (max_changes_per_temperature < pathchg
                     && max_consecutive_non_changes < non_change ) {
                 break;
             }
         }  // for tries per temperature
         swapClimb();
         clock_t current_time(clock());
         double elapsed_time = static_cast<double>(
                 current_time - start_time) / CLOCKS_PER_SEC;
         if (time_limit < elapsed_time) {
             break;
         }
         log << "\ttotal changes =" << pathchg
             << "\t" << enchg << " were because  delta energy < 0";
         if (pathchg == 0) break;   /* if no change then quit */
     }  // for temperatures
 }
find_closest_city()
template<typename MATRIX > size_t pgrouting::tsp::TSP< MATRIX >::find_closest_city (size_t current_city, const std::set< size_t > & inserted) const private
Definition at line 202 of file pgr_tsp.hpp.
References pgrouting::tsp::TSP< MATRIX >::annealing(), pgrouting::tsp::TSP< MATRIX >::best_tour, pgrouting::tsp::Tour::cities, pgrouting::tsp::TSP< MATRIX >::current_cost, pgrouting::tsp::TSP< MATRIX >::current_tour, pgrouting::tsp::TSP< MATRIX >::epsilon, pgrouting::tsp::TSP< MATRIX >::getDeltaReverse(), pgrouting::tsp::TSP< MATRIX >::getDeltaSlide(), pgrouting::tsp::TSP< MATRIX >::getDeltaSwap(), pgrouting::tsp::TSP< MATRIX >::greedyInitial(), pgrouting::tsp::TSP< MATRIX >::invariant(), pgrouting::tsp::TSP< MATRIX >::log, pgrouting::tsp::TSP< MATRIX >::n, pgassert, pgassertwm, pred(), rand(), pgrouting::tsp::Tour::reverse(), pgrouting::tsp::TSP< MATRIX >::reverse_count, pgrouting::tsp::Tour::slide(), pgrouting::tsp::TSP< MATRIX >::slide_count, succ(), pgrouting::tsp::Tour::swap(), pgrouting::tsp::TSP< MATRIX >::swap_count, pgrouting::tsp::TSP< MATRIX >::swapClimb(), and pgrouting::tsp::TSP< MATRIX >::update_if_best().
Referenced by pgrouting::tsp::TSP< MATRIX >::update_if_best().
{
     invariant();
     auto distance_row(get_row(current_city));
     pgassert(distance_row.size() == n);
 #ifndef NDEBUG
     std::ostringstream err;
     for (const auto &d : distance_row) {
         err  << d << ", ";
     }
 #endif
     size_t best_city = 0;
     auto best_distance = (std::numeric_limits<double>::max)();
 #ifndef NDEBUG
     bool found(false);
 #endif
     for (size_t i = 0; i < distance_row.size(); ++i) {
         if (i == current_city) continue;
         if (inserted.find(i) != inserted.end()) continue;
         if (distance_row[i] <  best_distance) {
             best_city = i;
             best_distance = distance_row[i];
 #ifndef NDEBUG
             found = true;
 #endif
         }
     }
     pgassertwm(found, err.str());
     invariant();
     return best_city;
 }
get_log()
template<typename MATRIX> std::string pgrouting::tsp::TSP< MATRIX >::get_log () const inline
Definition at line 115 of file pgr_tsp.hpp.
References pgrouting::tsp::TSP< MATRIX >::annealing(), pgrouting::tsp::TSP< MATRIX >::greedyInitial(), and pgrouting::tsp::TSP< MATRIX >::log.
Referenced by do_pgr_euclideanTSP(), and do_pgr_tsp().
{
          return log.str();}
get_stats()
template<typename MATRIX> std::string pgrouting::tsp::TSP< MATRIX >::get_stats () const inline
Definition at line 106 of file pgr_tsp.hpp.
References pgrouting::tsp::TSP< MATRIX >::improve_count, pgrouting::tsp::TSP< MATRIX >::reverse_count, pgrouting::tsp::TSP< MATRIX >::slide_count, and pgrouting::tsp::TSP< MATRIX >::swap_count.
Referenced by do_pgr_euclideanTSP(), and do_pgr_tsp().
{
          std::ostringstream log1;
          log1
              << "\nTotal swaps: " << swap_count
              << "\nTotal slides: " << slide_count
              << "\nTotal reverses: " << reverse_count
              << "\nTimes best tour changed: " << improve_count;
          return log1.str();}
get_tour()
template<typename MATRIX> Tour pgrouting::tsp::TSP< MATRIX >::get_tour () const inline
Definition at line 104 of file pgr_tsp.hpp.
References pgrouting::tsp::TSP< MATRIX >::best_tour.
Referenced by do_pgr_euclideanTSP(), and do_pgr_tsp().
 {return best_tour;}
getDeltaReverse()
template<typename MATRIX > double pgrouting::tsp::TSP< MATRIX >::getDeltaReverse (size_t posA, size_t posC) const private
Definition at line 369 of file pgr_tsp.cpp.
References pgassertwm, and succ().
Referenced by pgrouting::tsp::TSP< MATRIX >::find_closest_city().
{
     invariant();
     if (posA == (posC - 1)) return 0;
     auto a = current_tour.cities[posA];
     auto b = current_tour.cities[succ(posA, n)];
     auto c = current_tour.cities[posC];
     auto d = current_tour.cities[succ(posC, n)];
 #ifndef NDEBUG
     auto delta =
         distance(a, c) + distance(b, d) - distance(a, b) - distance(c, d);
     auto new_tour(current_tour);
     new_tour.reverse(posA, posC);
     auto exactDelta = tourCost(new_tour) - tourCost(current_tour);
     std::ostringstream log;
     log << "exactDelta(" << exactDelta
         << ") - delta(" <<  delta
         << ") = "
         << exactDelta - delta
         << " = "
         << (exactDelta - delta)
         << " epsilon = " << epsilon;
     pgassertwm(std::fabs((exactDelta - delta)) < epsilon, log.str());
 #endif
     invariant();
     return  distance(a, c) + distance(b, d) - distance(a, b) - distance(c, d);
 }
getDeltaSlide()
template<typename MATRIX > double pgrouting::tsp::TSP< MATRIX >::getDeltaSlide (size_t posP, size_t posF, size_t posL) const private
Definition at line 224 of file pgr_tsp.cpp.
References pgrouting::tsp::Tour::cities, pgassertwm, pgrouting::tsp::Tour::slide(), and succ().
Referenced by pgrouting::tsp::TSP< MATRIX >::find_closest_city().
{
     invariant();
 #ifndef NDEBUG
     std::ostringstream err;
     err  << "\tplace" << place
         << "\tfirst" << first
         << "\tlast" << last
         << "\tn" << n;
 #endif
     pgassertwm(place < first || place > last, err.str());
     pgassertwm(first < last, err.str());
     pgassertwm(last < n, err.str());
     pgassertwm(place < n, err.str());
     pgassertwm(first < n, err.str());
     /*
      * Initial state
      * [...f] [f+1 ... l] [l+1 ...p] [p+1 ...]
      *
      * final state
      * [...f] [l+1 ... p] [f+1 ...l] [p+1 ...]
      *
      *
      * Initial state
      *   [f+1 ... l]
      *     :      :
      * [...f]   [l+1 ...p] [p+1 ...]
      *
      * final state
      *               [f+1 ... l]
      *                :       :
      * [...f] [l+1 ...p]   [p+1 ...]
      *
      */
     auto cityP = current_tour.cities[place];
     auto cityF = current_tour.cities[first];
     auto cityL = current_tour.cities[last];
     auto cityP1 = current_tour.cities[succ(place, n)];
     auto cityF1 = current_tour.cities[succ(first, n)];
     auto cityL1 = current_tour.cities[succ(last, n)];
     auto delta(
             distance(cityF, cityL1)
             + distance(cityP, cityF1)
             + distance(cityL, cityP1)
             - distance(cityF, cityF1)
             - distance(cityL, cityL1)
             - distance(cityP, cityP1));
 #ifndef NDEBUG
     Tour new_tour(current_tour);
     new_tour.slide(place, first, last);
     err << "\ncurrent_tour:";
     for (const auto id : current_tour.cities) {
         err << id << ", ";
     }
     err << "\nnew_tour:";
     for (const auto id : new_tour.cities) {
         err << id << ", ";
     }
     auto exactDelta = tourCost(new_tour) - tourCost(current_tour);
     err << "\n"
         << exactDelta
         << " - " <<  delta
         << " = "
         << exactDelta - delta
         << " = "
         << std::fabs(exactDelta - delta);
     pgassertwm(std::fabs((exactDelta - delta)) < epsilon, err.str());
 #endif
     invariant();
     return delta;
 }
getDeltaSwap()
template<typename MATRIX > double pgrouting::tsp::TSP< MATRIX >::getDeltaSwap (size_t posA, size_t posC) const private
Definition at line 316 of file pgr_tsp.cpp.
References pgassertwm, pred(), and succ().
Referenced by pgrouting::tsp::TSP< MATRIX >::find_closest_city().
{
     invariant();
     if (succ(posE, n ) == posA) std::swap(posA, posE);
     if (succ(posA, n) == posE) {
         auto b = current_tour.cities[pred(posA, n)];
         auto a = current_tour.cities[posA];
         auto e = current_tour.cities[posE];
         auto f = current_tour.cities[succ(posE, n)];
         return distance(b, e) + distance(e, a) + distance(a, f)
             - distance(b, a) - distance(a, e)  - distance(e, f);
     }
     auto b = current_tour.cities[pred(posA, n)];
     auto a = current_tour.cities[posA];
     auto c = current_tour.cities[succ(posA, n)];
     auto d = current_tour.cities[pred(posE, n)];
     auto e = current_tour.cities[posE];
     auto f = current_tour.cities[succ(posE, n)];
 #ifndef NDEBUG
     auto delta = distance(b, e)
         + distance(e, c) + distance(d, a) + distance(a, f)
         - distance(b, a) - distance(a, c)  - distance(d, e) - distance(e, f);
     auto new_tour(current_tour);
     new_tour.swap(posA, posE);
     auto exactDelta = tourCost(new_tour) - tourCost(current_tour);
     std::ostringstream log;
     log << exactDelta
         << " - " <<  delta
         << " = "
         << exactDelta - delta
         << " = "
         << std::fabs(exactDelta - delta);
     pgassertwm(std::fabs((exactDelta - delta)) < epsilon, log.str());
 #endif
     invariant();
     return  distance(b, e) + distance(e, c) + distance(d, a) + distance(a, f)
         - distance(b, a) - distance(a, c)  - distance(d, e) - distance(e, f);
 }
greedyInitial()
template<typename MATRIX > void pgrouting::tsp::TSP< MATRIX >::greedyInitial (size_t idx_start = 0)
Definition at line 143 of file pgr_tsp.cpp.
References pgassert, and pgassertwm.
Referenced by do_pgr_euclideanTSP(), do_pgr_tsp(), pgrouting::tsp::TSP< MATRIX >::find_closest_city(), and pgrouting::tsp::TSP< MATRIX >::get_log().
{
     invariant();
     std::set<size_t> pending(best_tour.cities.begin(), best_tour.cities.end());
     std::set<size_t> inserted;
     std::vector<size_t> tour_to_be;
     auto current_city = idx_start;
 #ifndef NDEBUG
     std::ostringstream err;
     auto ps(pending.size());
 #endif
     pending.erase(idx_start);
 #ifndef NDEBUG
     pgassert(pending.size() == (ps - 1));
 #endif
     tour_to_be.push_back(current_city);
     inserted.insert(current_city);
     while (!pending.empty()) {
         auto next_city = find_closest_city(current_city, inserted);
         tour_to_be.push_back(next_city);
         inserted.insert(next_city);
 #ifndef NDEBUG
         auto ps(pending.size());
         err << "before";
         for (const auto p : pending) {
             err << p << ",";
         }
 #endif
         pending.erase(next_city);
 #ifndef NDEBUG
         err << "\nafter deleting" << next_city << ":\t";
         for (const auto p : pending) {
             err << p << ",";
         }
         pgassertwm(pending.size() == (ps - 1), err.str());
 #endif
         current_city = next_city;
     }
     pgassert(tour_to_be.size() == n);
     current_tour = Tour(tour_to_be);
     current_cost = tourCost(current_tour);
     update_if_best();
     swapClimb();
     invariant();
     return;
 }
invariant()
template<typename MATRIX > void pgrouting::tsp::TSP< MATRIX >::invariant () const private
Definition at line 73 of file pgr_tsp.cpp.
References pgassert.
Referenced by pgrouting::tsp::TSP< MATRIX >::find_closest_city().
{
     /* the calculated value & the actual value are the same */
     pgassert(std::fabs(tourCost(current_tour) - current_cost) < epsilon);
     pgassert(std::fabs(tourCost(best_tour) - bestCost) < epsilon);
     pgassert(n == MATRIX::ids.size());
     pgassert(n == current_tour.size());
     pgassert(n == best_tour.size());
 }
swapClimb()
template<typename MATRIX > void pgrouting::tsp::TSP< MATRIX >::swapClimb () private
Definition at line 404 of file pgr_tsp.cpp.
References pgassert.
Referenced by pgrouting::tsp::TSP< MATRIX >::find_closest_city().
{
     invariant();
     pgassert(n > 2);
     //    auto first = std::rand() % n;
     //    for (size_t first = std::rand() % n; first < n; first++) {
     for (size_t first = 0; first < n; first++) {
         for (size_t last = first + 1; last < n; last++) {
             pgassert(first < last);
             auto energyChange = getDeltaSwap(first, last);
             if (energyChange < 0 && epsilon < std::fabs(energyChange)) {
                 ++swap_count;
                 current_cost += energyChange;
                 current_tour.swap(first, last);
                 update_if_best();
             }
         }
     }
     invariant();
 }
update_if_best()
template<typename MATRIX > void pgrouting::tsp::TSP< MATRIX >::update_if_best () private
Definition at line 84 of file pgr_tsp.cpp.
References pgrouting::tsp::TSP< MATRIX >::find_closest_city(), pgassert, and pgassertwm.
Referenced by pgrouting::tsp::TSP< MATRIX >::find_closest_city().
{
     invariant();
     ++updatecalls;
     if (current_cost < bestCost) {
         ++improve_count;
         best_tour = current_tour;
         bestCost = current_cost;
     }
     invariant();
 }
Member Data Documentation
best_tour
template<typename MATRIX> Tour pgrouting::tsp::TSP< MATRIX >::best_tour private
Definition at line 132 of file pgr_tsp.hpp.
Referenced by pgrouting::tsp::TSP< MATRIX >::find_closest_city(), pgrouting::tsp::TSP< MATRIX >::get_tour(), and pgrouting::tsp::TSP< MATRIX >::TSP().
bestCost
template<typename MATRIX> double pgrouting::tsp::TSP< MATRIX >::bestCost private
Definition at line 133 of file pgr_tsp.hpp.
Referenced by pgrouting::tsp::TSP< MATRIX >::TSP().
current_cost
template<typename MATRIX> double pgrouting::tsp::TSP< MATRIX >::current_cost private
Definition at line 134 of file pgr_tsp.hpp.
Referenced by pgrouting::tsp::TSP< MATRIX >::find_closest_city(), and pgrouting::tsp::TSP< MATRIX >::TSP().
current_tour
template<typename MATRIX> Tour pgrouting::tsp::TSP< MATRIX >::current_tour private
Definition at line 131 of file pgr_tsp.hpp.
Referenced by pgrouting::tsp::TSP< MATRIX >::find_closest_city(), and pgrouting::tsp::TSP< MATRIX >::TSP().
epsilon
template<typename MATRIX> double pgrouting::tsp::TSP< MATRIX >::epsilon private
Definition at line 135 of file pgr_tsp.hpp.
Referenced by pgrouting::tsp::TSP< MATRIX >::find_closest_city().
improve_count
template<typename MATRIX> size_t pgrouting::tsp::TSP< MATRIX >::improve_count private
Definition at line 144 of file pgr_tsp.hpp.
Referenced by pgrouting::tsp::TSP< MATRIX >::get_stats().
log
template<typename MATRIX> std::ostringstream pgrouting::tsp::TSP< MATRIX >::log private
Definition at line 140 of file pgr_tsp.hpp.
Referenced by pgrouting::tsp::TSP< MATRIX >::find_closest_city(), and pgrouting::tsp::TSP< MATRIX >::get_log().
n
template<typename MATRIX> size_t pgrouting::tsp::TSP< MATRIX >::n private
Definition at line 136 of file pgr_tsp.hpp.
Referenced by pgrouting::tsp::TSP< MATRIX >::find_closest_city(), and pgrouting::tsp::TSP< MATRIX >::TSP().
reverse_count
template<typename MATRIX> size_t pgrouting::tsp::TSP< MATRIX >::reverse_count private
Definition at line 143 of file pgr_tsp.hpp.
Referenced by pgrouting::tsp::TSP< MATRIX >::find_closest_city(), and pgrouting::tsp::TSP< MATRIX >::get_stats().
slide_count
template<typename MATRIX> size_t pgrouting::tsp::TSP< MATRIX >::slide_count private
Definition at line 142 of file pgr_tsp.hpp.
Referenced by pgrouting::tsp::TSP< MATRIX >::find_closest_city(), and pgrouting::tsp::TSP< MATRIX >::get_stats().
swap_count
template<typename MATRIX> size_t pgrouting::tsp::TSP< MATRIX >::swap_count private
Definition at line 141 of file pgr_tsp.hpp.
Referenced by pgrouting::tsp::TSP< MATRIX >::find_closest_city(), and pgrouting::tsp::TSP< MATRIX >::get_stats().
updatecalls
template<typename MATRIX> int pgrouting::tsp::TSP< MATRIX >::updatecalls private
Definition at line 138 of file pgr_tsp.hpp.
The documentation for this class was generated from the following files:
pgr_tsp.hpp
pgr_tsp.cpp