PGROUTING: pgrouting::trsp::EdgeInfo Class Reference
pgrouting::trsp::EdgeInfo Class Reference
#include "edgeInfo.h"
Public Member Functions
EdgeInfo ()=default
EdgeInfo (pgr_edge_t edgeIn, size_t edgeIndex)
void connect_endEdge (size_t edge_idx)
void connect_startEdge (size_t edge_idx)
double cost () const
int64_t edgeID () const
std::vector< size_t > endConnectedEdge () const
int64_t endNode () const
double get_cost (int64_t node) const
std::vector< size_t > get_idx (bool isStart) const
size_t idx () const
double r_cost () const
std::vector< size_t > startConnectedEdge () const
int64_t startNode () const
Private Attributes
pgr_edge_t m_edge
size_t m_edgeIndex
std::vector< size_t > m_endConnectedEdge
std::vector< size_t > m_startConnectedEdge
Detailed Description
Definition at line 39 of file edgeInfo.h.
Constructor & Destructor Documentation
EdgeInfo() [1/2]
pgrouting::trsp::EdgeInfo::EdgeInfo () default
EdgeInfo() [2/2]
pgrouting::trsp::EdgeInfo::EdgeInfo (pgr_edge_t edgeIn, size_t edgeIndex)
Definition at line 32 of file edgeInfo.cpp.
                               :
         m_edge(edgeIn),
         m_edgeIndex(edgeIndex),
         m_startConnectedEdge(),
         m_endConnectedEdge()
         {}
Member Function Documentation
connect_endEdge()
void pgrouting::trsp::EdgeInfo::connect_endEdge (size_t edge_idx) inline
Definition at line 67 of file edgeInfo.h.
References m_endConnectedEdge.
Referenced by pgrouting::trsp::Pgr_trspHandler::connectEndEdge(), and pgrouting::trsp::Pgr_trspHandler::connectStartEdge().
{
          m_endConnectedEdge.push_back(edge_idx);
      }
connect_startEdge()
void pgrouting::trsp::EdgeInfo::connect_startEdge (size_t edge_idx) inline
Definition at line 70 of file edgeInfo.h.
References m_startConnectedEdge.
Referenced by pgrouting::trsp::Pgr_trspHandler::connectEndEdge(), and pgrouting::trsp::Pgr_trspHandler::connectStartEdge().
{
          m_startConnectedEdge.push_back(edge_idx);
      }
cost()
double pgrouting::trsp::EdgeInfo::cost () const inline
Definition at line 58 of file edgeInfo.h.
References pgr_edge_t::cost, and m_edge.
Referenced by pgrouting::trsp::Pgr_trspHandler::connectEndEdge(), pgrouting::trsp::Pgr_trspHandler::connectStartEdge(), pgrouting::trsp::Pgr_trspHandler::dijkstra_exploration(), get_cost(), and pgrouting::trsp::Pgr_trspHandler::initialize_que().
 {return m_edge.cost;}
edgeID()
int64_t pgrouting::trsp::EdgeInfo::edgeID () const inline
Definition at line 57 of file edgeInfo.h.
References pgr_edge_t::id, and m_edge.
Referenced by pgrouting::trsp::Pgr_trspHandler::getRestrictionCost().
 {return m_edge.id;}
endConnectedEdge()
std::vector<size_t> pgrouting::trsp::EdgeInfo::endConnectedEdge () const inline
Definition at line 74 of file edgeInfo.h.
References m_endConnectedEdge.
Referenced by get_idx().
{
          return m_endConnectedEdge;
      }
endNode()
int64_t pgrouting::trsp::EdgeInfo::endNode () const inline
Definition at line 53 of file edgeInfo.h.
References m_edge, pgassert, and pgr_edge_t::target.
Referenced by pgrouting::trsp::Pgr_trspHandler::connectEndEdge(), pgrouting::trsp::Pgr_trspHandler::connectStartEdge(), pgrouting::trsp::Pgr_trspHandler::dijkstra_exploration(), get_cost(), and pgrouting::trsp::Pgr_trspHandler::initialize_que().
{
          pgassert(m_edge.target >= 0);
          return m_edge.target;}
get_cost()
double pgrouting::trsp::EdgeInfo::get_cost (int64_t node) const inline
Definition at line 60 of file edgeInfo.h.
References cost(), endNode(), pgassert, r_cost(), and startNode().
{
          pgassert(node == startNode() || node == endNode());
          return node == startNode() ?
              cost() :
              r_cost();
      }
get_idx()
std::vector<size_t> pgrouting::trsp::EdgeInfo::get_idx (bool isStart) const inline
Definition at line 82 of file edgeInfo.h.
References endConnectedEdge(), and startConnectedEdge().
Referenced by pgrouting::trsp::Pgr_trspHandler::explore().
{
          return isStart ?
              startConnectedEdge() :
              endConnectedEdge();
      }
idx()
size_t pgrouting::trsp::EdgeInfo::idx () const inline
Definition at line 47 of file edgeInfo.h.
References m_edgeIndex.
Referenced by pgrouting::trsp::Pgr_trspHandler::addEdge(), pgrouting::trsp::Pgr_trspHandler::explore(), and pgrouting::trsp::Pgr_trspHandler::initialize_que().
 {return m_edgeIndex;}
r_cost()
double pgrouting::trsp::EdgeInfo::r_cost () const inline
Definition at line 59 of file edgeInfo.h.
References m_edge, and pgr_edge_t::reverse_cost.
Referenced by pgrouting::trsp::Pgr_trspHandler::connectEndEdge(), pgrouting::trsp::Pgr_trspHandler::connectStartEdge(), pgrouting::trsp::Pgr_trspHandler::dijkstra_exploration(), get_cost(), and pgrouting::trsp::Pgr_trspHandler::initialize_que().
 {return m_edge.reverse_cost;}
startConnectedEdge()
std::vector<size_t> pgrouting::trsp::EdgeInfo::startConnectedEdge () const inline
Definition at line 78 of file edgeInfo.h.
References m_startConnectedEdge.
Referenced by get_idx().
{
          return m_startConnectedEdge;
      }
startNode()
int64_t pgrouting::trsp::EdgeInfo::startNode () const inline
Definition at line 49 of file edgeInfo.h.
References m_edge, pgassert, and pgr_edge_t::source.
Referenced by pgrouting::trsp::Pgr_trspHandler::connectEndEdge(), pgrouting::trsp::Pgr_trspHandler::connectStartEdge(), pgrouting::trsp::Pgr_trspHandler::dijkstra_exploration(), get_cost(), and pgrouting::trsp::Pgr_trspHandler::initialize_que().
{
          pgassert(m_edge.source >= 0);
          return m_edge.source;
      }
Member Data Documentation
m_edge
pgr_edge_t pgrouting::trsp::EdgeInfo::m_edge private
Definition at line 90 of file edgeInfo.h.
Referenced by cost(), edgeID(), endNode(), r_cost(), and startNode().
m_edgeIndex
size_t pgrouting::trsp::EdgeInfo::m_edgeIndex private
Definition at line 91 of file edgeInfo.h.
Referenced by idx().
m_endConnectedEdge
std::vector<size_t> pgrouting::trsp::EdgeInfo::m_endConnectedEdge private
Definition at line 93 of file edgeInfo.h.
Referenced by connect_endEdge(), and endConnectedEdge().
m_startConnectedEdge
std::vector<size_t> pgrouting::trsp::EdgeInfo::m_startConnectedEdge private
Definition at line 92 of file edgeInfo.h.
Referenced by connect_startEdge(), and startConnectedEdge().
The documentation for this class was generated from the following files:
edgeInfo.h
edgeInfo.cpp