PGROUTING: pgrouting::vrp::Node Class Reference
pgrouting::vrp::Node Class Reference
The Node class defines a point in 2D space with an id.
#include "node.h"
Public Member Functions
Node ()=default
Node (size_t id, int64_t original_id, double _x, double _y)
double distance (const Base_node *) const
Calculates distance between two Node.
int64_t id () const
size_t idx () const
void reset_id (int64_t)
to be or not to be
bool operator== (const Node &rhs) const
to be or not to be
virtual bool operator== (const Base_node &rhs) const
Private Member Functions
double distance (const Node &) const
void print (std::ostream &os) const
Private Attributes
Bpoint m_point
Friends
std::ostream & operator<< (std::ostream &log, const Node &node)
Detailed Description
The Node class defines a point in 2D space with an id.
A Node is a point that defines a location in 2D space. It maintains a user id and an internal nid along with its x, y location. This is the base object that things like depots, customer locations, etc. are built upon.
Definition at line 48 of file node.h.
Constructor & Destructor Documentation
Node() [1/2]
pgrouting::vrp::Node::Node () default
Node() [2/2]
pgrouting::vrp::Node::Node (size_t _idx, int64_t _id, double _x, double _y)
Parameters
[in] _idx index to a container
[in] _id original identifier
[in] _x coordinate value
[in] _y coordinate value
Definition at line 84 of file node.cpp.
     : Base_node(_idx, _id),
         m_point(_x, _y) {
     }
Member Function Documentation
distance() [1/2]
double pgrouting::vrp::Node::distance (const Base_node * n) const virtual
Calculates distance between two Node.
para[in] n bas node to be casted as Node
Implements pgrouting::vrp::Base_node.
Definition at line 74 of file node.cpp.
{
     return distance(*dynamic_cast<const Node*>(n));
 }
distance() [2/2]
double pgrouting::vrp::Node::distance (const Node & other) const private
Definition at line 64 of file node.cpp.
References m_point.
{
     auto dx = m_point.x() - other.m_point.x();
     auto dy = m_point.y() - other.m_point.y();
     return sqrt(dx * dx + dy * dy);
 }
id()
int64_t pgrouting::Identifier::id () const inherited
Definition at line 42 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Dnode::distance(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::vrp::Vehicle::is_phony(), pgrouting::vrp::operator<<(), pgrouting::operator<<(), operator==(), pgrouting::vrp::Base_node::operator==(), print(), pgrouting::vrp::Vehicle::tau(), and pgrouting::vrp::Vehicle::Vehicle().
                      {
     return m_id;
 }
idx()
size_t pgrouting::Identifier::idx () const inherited
Definition at line 37 of file identifier.cpp.
References pgrouting::Identifier::m_idx.
Referenced by pgrouting::vrp::Vehicle_pickDeliver::erase(), pgrouting::vrp::Vehicle::erase(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Vehicle_pickDeliver::has_order(), pgrouting::vrp::Vehicle::insert(), pgrouting::vrp::Vehicle_pickDeliver::insert(), pgrouting::vrp::operator<<(), pgrouting::operator<<(), pgrouting::vrp::Base_node::operator==(), operator==(), pgrouting::vrp::Tw_node::operator==(), print(), pgrouting::vrp::Vehicle_pickDeliver::push_back(), pgrouting::vrp::Vehicle_pickDeliver::push_front(), pgrouting::vrp::Vehicle_pickDeliver::semiLIFO(), pgrouting::vrp::Order::set_compatibles(), pgrouting::vrp::Solution::sort_by_id(), pgrouting::vrp::Vehicle::tau(), pgrouting::vrp::Tw_node::travel_time_to(), and pgrouting::vrp::Vehicle::Vehicle().
                       {
     return m_idx;
 }
operator==() [1/2]
bool pgrouting::vrp::Base_node::operator== (const Base_node & rhs) const virtual inherited
Definition at line 43 of file base_node.cpp.
References pgrouting::Identifier::id(), and pgrouting::Identifier::idx().
{
     if (&rhs == this) return true;
     return
         (idx() == rhs.idx())
          && (id() == rhs.id());
 }
operator==() [2/2]
bool pgrouting::vrp::Node::operator== (const Node & rhs) const
Definition at line 90 of file node.cpp.
References anonymous_namespace{node.cpp}::almost_equal(), pgrouting::Identifier::id(), pgrouting::Identifier::idx(), and m_point.
{
     if (&rhs == this) return true;
     return
         (idx() == rhs.idx())
          && (id() == rhs.id())
          && almost_equal(m_point.x(), rhs.m_point.x(), 2)
          && almost_equal(m_point.y(), rhs.m_point.y(), 2);
 }
print()
void pgrouting::vrp::Node::print (std::ostream & os) const private
Definition at line 55 of file node.cpp.
References pgrouting::Identifier::id(), pgrouting::Identifier::idx(), and m_point.
Referenced by pgrouting::vrp::operator<<().
{
     os << id()
 #ifndef NDEBUG
         << "(" << idx() << ")"
 #endif
        << " (x,y) = (" << m_point.x() << ", " << m_point.y() << ")";
 }
reset_id()
void pgrouting::Identifier::reset_id (int64_t _id) inherited
Definition at line 47 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Tw_node::Tw_node().
{
     m_id = _id;
 }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const Node & node) friend
Definition at line 49 of file node.cpp.
{
     node.print(log);
     return log;
 }
Member Data Documentation
m_point
Bpoint pgrouting::vrp::Node::m_point private
Definition at line 69 of file node.h.
Referenced by distance(), operator==(), and print().
The documentation for this class was generated from the following files:
node.h
node.cpp