PGROUTING: pgrouting::graph::PgrDirectedChPPGraph Class Reference
pgrouting::graph::PgrDirectedChPPGraph Class Reference
#include "pgr_directedChPP.hpp"
Public Member Functions
PgrDirectedChPPGraph (const pgr_edge_t *dataEdges, const size_t totalEdges)
double DirectedChPP ()
std::vector< General_path_element_t > GetPathEdges ()
Private Member Functions
void BuildResultGraph ()
void BuildResultPath ()
bool EulerCircuitDFS (int64_t p)
bool JudgeCoveredAllEdges ()
Private Attributes
std::map< std::pair< int64_t, int64_t >, size_t > edgeToId
std::vector< bool > edgeVisited
graph::PgrCostFlowGraph flowGraph
std::stack< int64_t > pathStack
std::vector< pgr_edge_t > resultEdges
std::vector< std::pair< int64_t, std::vector< size_t > > > resultGraph
std::vector< General_path_element_t > resultPath
int64_t startPoint
int64_t superSource
int64_t superTarget
double totalCost
int64_t totalDeg
std::map< int64_t, size_t > VToVecid
Detailed Description
Definition at line 46 of file pgr_directedChPP.hpp.
Constructor & Destructor Documentation
PgrDirectedChPPGraph()
pgrouting::graph::PgrDirectedChPPGraph::PgrDirectedChPPGraph (const pgr_edge_t * dataEdges, const size_t totalEdges)
Definition at line 88 of file pgr_directedChPP.hpp.
References pgr_costFlow_t::capacity, pgr_edge_t::cost, pgr_costFlow_t::cost, pgr_costFlow_t::edge_id, edgeToId, flowGraph, pgr_edge_t::id, resultEdges, pgr_costFlow_t::reverse_capacity, pgr_edge_t::reverse_cost, pgr_costFlow_t::reverse_cost, pgr_edge_t::source, pgr_costFlow_t::source, startPoint, superSource, superTarget, pgr_edge_t::target, pgr_costFlow_t::target, totalCost, and totalDeg.
{
     resultEdges.clear();
     for (size_t i = 0; i < totalEdges; i++) {
         pgr_edge_t edge;
         edge.id = dataEdges[i].id;
         edge.source = dataEdges[i].source;
         edge.target = dataEdges[i].target;
         edge.reverse_cost = -1.0;
         if (dataEdges[i].cost > 0) {
             startPoint = edge.source;
             edge.cost = dataEdges[i].cost;
             totalCost += edge.cost;
             resultEdges.push_back(edge);
         }
         if (dataEdges[i].reverse_cost > 0) {
             std::swap(edge.source, edge.target);
             edge.cost = dataEdges[i].reverse_cost;
             totalCost += edge.cost;
             resultEdges.push_back(edge);
         }
     }
     std::vector<pgr_costFlow_t> edges;
     std::set<int64_t> sources;
     std::set<int64_t> targets;
     // calcu deg & build part of edges
     std::map<int64_t, int> deg;
     for (size_t i = 0; i < resultEdges.size(); i++) {
         deg[resultEdges[i].source]++;
         deg[resultEdges[i].target]--;
         if (edgeToId.find(std::make_pair(resultEdges[i].source, resultEdges[i].target)) ==
                 edgeToId.end()) {
             edgeToId.insert(std::make_pair(std::make_pair(resultEdges[i].source, resultEdges[i].target), i));
         } else {
             if (resultEdges[edgeToId[
                     std::make_pair(resultEdges[i].source, resultEdges[i].target)]].cost >
                     resultEdges[i].cost) {
                 edgeToId[std::make_pair(resultEdges[i].source, resultEdges[i].target)] = i;
             }
         }
         pgr_costFlow_t edge;
         edge.edge_id = resultEdges[i].id;
         edge.reverse_capacity = -1;
         edge.reverse_cost = -1.0;
         edge.source = resultEdges[i].source;
         edge.target = resultEdges[i].target;
         edge.capacity = (std::numeric_limits<int32_t>::max)();
         edge.cost = resultEdges[i].cost;
         edges.push_back(edge);
     }
     // find superSource & superTarget
     superSource = superTarget = -1;
     int64_t iPointId = 1;
     while (superSource == -1 || superTarget == -1) {
         if (deg.find(iPointId) == deg.end()) {
             if (superSource == -1)
                 superSource = iPointId;
             else
                 superTarget = iPointId;
         }
         iPointId++;
     }
     sources.insert(superSource);
     targets.insert(superTarget);
     // build full edges
     std::map<int64_t, int>::iterator iter;
     totalDeg = 0;
     for (iter = deg.begin(); iter != deg.end(); ++iter) {
         int64_t p = iter->first;
         int d = iter->second;
         if (d == 0)
             continue;
         if (d > 0)
             totalDeg += d;
         pgr_costFlow_t edge;
         edge.reverse_capacity = -1;
         edge.reverse_cost = -1.0;
         edge.cost = 0.0;
         if (d > 0)
             edge.capacity = d;
         else
             edge.capacity = -d;
         edge.edge_id = 0;
         if (d > 0)
             edge.source = p, edge.target = superTarget;
         if (d < 0)
             edge.source = superSource, edge.target = p;
         edges.push_back(edge);
     }
     PgrCostFlowGraph graph(edges, sources, targets);
     flowGraph = graph;
 }
Member Function Documentation
BuildResultGraph()
void pgrouting::graph::PgrDirectedChPPGraph::BuildResultGraph () private
Definition at line 292 of file pgr_directedChPP.hpp.
References edgeVisited, resultEdges, resultGraph, pgr_edge_t::source, and VToVecid.
Referenced by DirectedChPP(), and GetPathEdges().
{
     resultGraph.clear();
     VToVecid.clear();
     edgeVisited.clear();
     for (size_t i = 0; i < resultEdges.size(); i++) {
         pgr_edge_t edge_t = resultEdges[i];
         edgeVisited.push_back(false);
         if (VToVecid.find(edge_t.source) == VToVecid.end()) {
             VToVecid.insert(
                     std::pair<int64_t, size_t>(
                         edge_t.source,
                         resultGraph.size()));
             resultGraph.resize(resultGraph.size() + 1);
         }
         size_t vid = VToVecid[edge_t.source];
         resultGraph[vid].second.push_back(i);
         resultGraph[vid].first = edge_t.source;
     }
 }
BuildResultPath()
void pgrouting::graph::PgrDirectedChPPGraph::BuildResultPath () private
Definition at line 234 of file pgr_directedChPP.hpp.
References General_path_element_t::agg_cost, pgr_edge_t::cost, General_path_element_t::cost, General_path_element_t::edge, edgeToId, pgr_edge_t::id, General_path_element_t::node, pathStack, resultEdges, resultPath, General_path_element_t::seq, and pgr_edge_t::source.
Referenced by DirectedChPP(), and GetPathEdges().
{
     if (pathStack.empty())
         return;
     int64_t preNode = pathStack.top();
     pathStack.pop();
     General_path_element_t newElement;
     while (!pathStack.empty()) {
         int64_t nowNode = pathStack.top();
         pathStack.pop();
         pgr_edge_t edge_t =
             resultEdges[edgeToId[std::make_pair(preNode, nowNode)]];
         newElement.node = edge_t.source;
         newElement.edge = edge_t.id;
         newElement.cost = edge_t.cost;
         if (resultPath.empty()) {
             newElement.seq = 1;
             newElement.agg_cost = 0.0;
         } else {
             newElement.seq = resultPath.back().seq + 1;
             newElement.agg_cost =
                 resultPath.back().agg_cost + resultPath.back().cost;
         }
         resultPath.push_back(newElement);
         preNode = nowNode;
     }
     newElement.node = preNode;
     newElement.edge = -1;
     newElement.cost = 0;
     if (resultPath.empty()) {
         newElement.seq = 1;
         newElement.agg_cost = 0.0;
     } else {
         newElement.seq = resultPath.back().seq + 1;
         newElement.agg_cost =
             resultPath.back().agg_cost + resultPath.back().cost;
     }
     resultPath.push_back(newElement);
 }
DirectedChPP()
double pgrouting::graph::PgrDirectedChPPGraph::DirectedChPP () inline
Definition at line 52 of file pgr_directedChPP.hpp.
References BuildResultGraph(), BuildResultPath(), EulerCircuitDFS(), flowGraph, pgrouting::graph::PgrCostFlowGraph::GetMaxFlow(), GetPathEdges(), JudgeCoveredAllEdges(), pgrouting::graph::PgrCostFlowGraph::MinCostMaxFlow(), totalCost, and totalDeg.
Referenced by do_pgr_directedChPP().
{
          double minAddedCost = flowGraph.MinCostMaxFlow();
          int64_t maxFlow = flowGraph.GetMaxFlow();
          if (maxFlow == totalDeg)
              return minAddedCost + totalCost;
          return -1.0;
      }
EulerCircuitDFS()
bool pgrouting::graph::PgrDirectedChPPGraph::EulerCircuitDFS (int64_t p) private
Definition at line 278 of file pgr_directedChPP.hpp.
References edgeVisited, pathStack, resultEdges, resultGraph, and VToVecid.
Referenced by DirectedChPP(), and GetPathEdges().
{
     for (auto iter = resultGraph[VToVecid[p]].second.begin();
          iter != resultGraph[VToVecid[p]].second.end();
          ++iter) {
         if (!edgeVisited[*iter]) {
             edgeVisited[*iter] = true;
             EulerCircuitDFS(resultEdges[*iter].target);
         }
     }
     pathStack.push(p);
     return true;
 }
GetPathEdges()
std::vector< General_path_element_t > pgrouting::graph::PgrDirectedChPPGraph::GetPathEdges ()
Definition at line 198 of file pgr_directedChPP.hpp.
References BuildResultGraph(), BuildResultPath(), pgr_edge_t::cost, edgeToId, EulerCircuitDFS(), flowGraph, pgrouting::graph::PgrCostFlowGraph::GetFlowEdges(), pgr_edge_t::id, JudgeCoveredAllEdges(), resultEdges, resultPath, pgr_edge_t::reverse_cost, pgr_edge_t::source, startPoint, superSource, superTarget, and pgr_edge_t::target.
Referenced by DirectedChPP(), and do_pgr_directedChPP().
{
     // catch new edges
     std::vector<pgr_flow_t> addedEdges = flowGraph.GetFlowEdges();
     for (auto &flow_t : addedEdges) {
         if (flow_t.source != superSource && flow_t.source != superTarget) {
             if (flow_t.target != superSource && flow_t.target != superTarget) {
                 pgr_edge_t newEdge;
                 newEdge.source = flow_t.source;
                 newEdge.target = flow_t.target;
                 newEdge.id =
                     resultEdges[edgeToId[std::make_pair(
                             newEdge.source,
                             newEdge.target)]].id;
                 newEdge.cost =
                     resultEdges[edgeToId[std::make_pair(
                             newEdge.source,
                             newEdge.target)]].cost;
                 newEdge.reverse_cost = -1.0;
                 while (flow_t.flow--)
                     resultEdges.push_back(newEdge);
             }
         }
     }
     BuildResultGraph();
     EulerCircuitDFS(startPoint);
     BuildResultPath();
     if (!JudgeCoveredAllEdges())
         resultPath.clear();
     return resultPath;
 }
JudgeCoveredAllEdges()
bool pgrouting::graph::PgrDirectedChPPGraph::JudgeCoveredAllEdges () private
Definition at line 190 of file pgr_directedChPP.hpp.
References edgeVisited.
Referenced by DirectedChPP(), and GetPathEdges().
{
     for (const auto b : edgeVisited)
         if (!b)
             return false;
     return true;
 }
Member Data Documentation
edgeToId
std::map<std::pair<int64_t, int64_t>, size_t> pgrouting::graph::PgrDirectedChPPGraph::edgeToId private
Definition at line 75 of file pgr_directedChPP.hpp.
Referenced by BuildResultPath(), GetPathEdges(), and PgrDirectedChPPGraph().
edgeVisited
std::vector<bool> pgrouting::graph::PgrDirectedChPPGraph::edgeVisited private
Definition at line 82 of file pgr_directedChPP.hpp.
Referenced by BuildResultGraph(), EulerCircuitDFS(), and JudgeCoveredAllEdges().
flowGraph
graph::PgrCostFlowGraph pgrouting::graph::PgrDirectedChPPGraph::flowGraph private
Definition at line 77 of file pgr_directedChPP.hpp.
Referenced by DirectedChPP(), GetPathEdges(), and PgrDirectedChPPGraph().
pathStack
std::stack<int64_t> pgrouting::graph::PgrDirectedChPPGraph::pathStack private
Definition at line 84 of file pgr_directedChPP.hpp.
Referenced by BuildResultPath(), and EulerCircuitDFS().
resultEdges
std::vector<pgr_edge_t> pgrouting::graph::PgrDirectedChPPGraph::resultEdges private
Definition at line 78 of file pgr_directedChPP.hpp.
Referenced by BuildResultGraph(), BuildResultPath(), EulerCircuitDFS(), GetPathEdges(), and PgrDirectedChPPGraph().
resultGraph
std::vector<std::pair<int64_t, std::vector<size_t> > > pgrouting::graph::PgrDirectedChPPGraph::resultGraph private
Definition at line 80 of file pgr_directedChPP.hpp.
Referenced by BuildResultGraph(), and EulerCircuitDFS().
resultPath
std::vector<General_path_element_t> pgrouting::graph::PgrDirectedChPPGraph::resultPath private
Definition at line 85 of file pgr_directedChPP.hpp.
Referenced by BuildResultPath(), and GetPathEdges().
startPoint
int64_t pgrouting::graph::PgrDirectedChPPGraph::startPoint private
Definition at line 72 of file pgr_directedChPP.hpp.
Referenced by GetPathEdges(), and PgrDirectedChPPGraph().
superSource
int64_t pgrouting::graph::PgrDirectedChPPGraph::superSource private
Definition at line 71 of file pgr_directedChPP.hpp.
Referenced by GetPathEdges(), and PgrDirectedChPPGraph().
superTarget
int64_t pgrouting::graph::PgrDirectedChPPGraph::superTarget private
Definition at line 71 of file pgr_directedChPP.hpp.
Referenced by GetPathEdges(), and PgrDirectedChPPGraph().
totalCost
double pgrouting::graph::PgrDirectedChPPGraph::totalCost private
Definition at line 70 of file pgr_directedChPP.hpp.
Referenced by DirectedChPP(), and PgrDirectedChPPGraph().
totalDeg
int64_t pgrouting::graph::PgrDirectedChPPGraph::totalDeg private
Definition at line 69 of file pgr_directedChPP.hpp.
Referenced by DirectedChPP(), and PgrDirectedChPPGraph().
VToVecid
std::map<int64_t, size_t> pgrouting::graph::PgrDirectedChPPGraph::VToVecid private
Definition at line 81 of file pgr_directedChPP.hpp.
Referenced by BuildResultGraph(), and EulerCircuitDFS().
The documentation for this class was generated from the following file:
pgr_directedChPP.hpp