PGROUTING: pgrouting::yen::Pgr_turnRestrictedPath< G > Class Template Reference
pgrouting::yen::Pgr_turnRestrictedPath< G > Class Template Reference
#include "pgr_turnRestrictedPath.hpp"
Classes
struct found_goals
class Myvisitor
Public Member Functions
Pgr_turnRestrictedPath ()=default
std::string get_dbglog () const
get_error
std::string get_error () const
get_error
std::string get_log () const
get_log
std::string get_notice () const
get_notice
bool has_error () const
get_error
std::deque< Path > turnRestrictedPath (G &graph, const std::vector< pgrouting::trsp::Rule > &restrictions, int64_t source, int64_t target, size_t k, bool heap_paths, bool stop_on_first, bool strict)
std::deque< Path > Yen (G &graph, int64_t start_vertex, int64_t end_vertex, size_t K, bool heap_paths)
std::deque< Path > Yen (G &graph, int64_t start_vertex, int64_t end_vertex, size_t K)
Public Attributes
std::ostringstream dbg_log
std::ostringstream error
Stores the error information.
std::ostringstream log
Stores the hint information.
std::ostringstream notice
Stores the notice information.
Protected Member Functions
void executeYen (G &graph)
the actual algorithm
Auxiliary function for yen's algorithm
Path getFirstSolution (G &graph)
Performs the first Dijkstra of the algorithm.
void doNextCycle (G &graph)
Performs the next cycle of the algorithm.
void removeVertices (G &graph, const Path &subpath)
stores in subPath the first i elements of path
std::deque< Path > get_results ()
Protected Attributes
members
V v_source
source descriptor
V v_target
target descriptor
int64_t m_start
source id
int64_t m_end
target id
size_t m_K
Path curr_result_path
storage for the current result
pSet m_ResultSet
ordered set of shortest paths
pSet m_Heap
the heap
Visitor * m_vis
Private Types
typedef std::set< Path, compPathsLess > pSet
Private Member Functions
void clear ()
containers cleanup
std::deque< Path > get_results (std::deque< Path > &paths)
std::deque< Path > inf_cost_on_restriction (std::deque< Path > &paths)
sets an inf value on agg_cost on the vertex/edge where the restriction begins
Private Attributes
bool m_heap_paths
std::vector< pgrouting::trsp::Rule > m_restrictions
pSet m_solutions
bool m_stop_on_first
bool m_strict
Detailed Description
template<typename G>
class pgrouting::yen::Pgr_turnRestrictedPath< G >
Definition at line 48 of file pgr_turnRestrictedPath.hpp.
Member Typedef Documentation
pSet
template<typename G> typedef std::set<Path, compPathsLess> pgrouting::yen::Pgr_turnRestrictedPath< G >::pSet private
Definition at line 49 of file pgr_turnRestrictedPath.hpp.
Constructor & Destructor Documentation
Pgr_turnRestrictedPath()
template<typename G> pgrouting::yen::Pgr_turnRestrictedPath< G >::Pgr_turnRestrictedPath () default
Member Function Documentation
clear()
template<typename G> void pgrouting::yen::Pgr_turnRestrictedPath< G >::clear () inline private
containers cleanup
empties containers
Definition at line 230 of file pgr_turnRestrictedPath.hpp.
References pgrouting::yen::Pgr_ksp< G >::clear(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::m_solutions.
Referenced by pgrouting::yen::Pgr_turnRestrictedPath< G >::Yen().
                   {
          Pgr_ksp<G>::clear();
          m_solutions.clear();
      }
doNextCycle()
template<class G> void pgrouting::yen::Pgr_ksp< G >::doNextCycle (G & graph) inline protected inherited
Performs the next cycle of the algorithm.
Definition at line 162 of file pgr_ksp.hpp.
References Path::appendPath(), pgrouting::yen::Pgr_ksp< G >::curr_result_path, pgrouting::Pgr_dijkstra< G >::dijkstra(), Path::getSubpath(), pgrouting::yen::Pgr_ksp< G >::m_end, pgrouting::yen::Pgr_ksp< G >::m_Heap, pgrouting::yen::Pgr_ksp< G >::m_ResultSet, pgrouting::yen::Pgr_ksp< G >::m_vis, pgrouting::yen::Pgr_ksp< G >::Visitor::on_insert_to_heap(), pgrouting::yen::Pgr_ksp< G >::removeVertices(), and Path::size().
Referenced by pgrouting::yen::Pgr_ksp< G >::executeYen().
{
          for (unsigned int i = 0; i < curr_result_path.size(); ++i) {
              int64_t spurNodeId = curr_result_path[i].node;
              auto rootPath = curr_result_path.getSubpath(i);
              for (const auto &path : m_ResultSet) {
                  if (path.isEqual(rootPath)) {
                      if (path.size() > i + 1) {
                          graph.disconnect_edge(path[i].node,     // from
                                  path[i + 1].node);  // to
                      }
                  }
              }
              removeVertices(graph, rootPath);
              Pgr_dijkstra< G > fn_dijkstra;
              auto spurPath = fn_dijkstra.dijkstra(graph, spurNodeId, m_end);
              if (spurPath.size() > 0) {
                  rootPath.appendPath(spurPath);
                  m_Heap.insert(rootPath);
                  m_vis->on_insert_to_heap(rootPath);
              }
              graph.restore_graph();
          }
      }
executeYen()
template<class G> void pgrouting::yen::Pgr_ksp< G >::executeYen (G & graph) inline protected inherited
the actual algorithm
Definition at line 127 of file pgr_ksp.hpp.
References pgrouting::yen::Pgr_ksp< G >::clear(), pgrouting::yen::Pgr_ksp< G >::curr_result_path, pgrouting::yen::Pgr_ksp< G >::doNextCycle(), pgrouting::yen::Pgr_ksp< G >::getFirstSolution(), pgrouting::yen::Pgr_ksp< G >::m_Heap, pgrouting::yen::Pgr_ksp< G >::m_K, pgrouting::yen::Pgr_ksp< G >::m_ResultSet, pgrouting::yen::Pgr_ksp< G >::m_vis, and pgrouting::yen::Pgr_ksp< G >::Visitor::on_insert_first_solution().
Referenced by pgrouting::yen::Pgr_ksp< G >::Yen(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::Yen().
{
          clear();
          curr_result_path = getFirstSolution(graph);
          m_vis->on_insert_first_solution(curr_result_path);
          if (m_ResultSet.size() == 0) return;  // no path found
          while (m_ResultSet.size() <  m_K) {
              doNextCycle(graph);
              if (m_Heap.empty()) break;
              curr_result_path = *m_Heap.begin();
              m_ResultSet.insert(curr_result_path);
              m_Heap.erase(m_Heap.begin());
          }
      }
get_dbglog()
std::string pgrouting::Pgr_messages::get_dbglog () const inherited
get_error
Returns
the current contents of the log and clears the log
Definition at line 60 of file pgr_messages.cpp.
References pgrouting::Pgr_messages::dbg_log.
Referenced by pgrouting::Pgr_messages::operator=().
{
     return dbg_log.str();
 }
get_error()
std::string pgrouting::Pgr_messages::get_error () const inherited
get_error
Returns
the current contents of the log and clears the log
Definition at line 53 of file pgr_messages.cpp.
References pgrouting::Pgr_messages::error.
Referenced by pgrouting::vrp::Fleet::build_fleet(), do_pgr_many_withPointsDD(), do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), do_pgr_withPoints(), do_pgr_withPointsKsp(), pgrouting::vrp::Fleet::is_fleet_ok(), pgrouting::Pgr_messages::operator=(), and pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver().
{
     auto str = error.str();
     return str;
 }
get_log()
std::string pgrouting::Pgr_messages::get_log () const inherited
get_log
Returns
the current contents of the log and clears the log
Definition at line 36 of file pgr_messages.cpp.
References pgrouting::Pgr_messages::log.
Referenced by do_pgr_many_withPointsDD(), do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), do_pgr_withPoints(), do_pgr_withPointsKsp(), pgrouting::vrp::Initial_solution::do_while_foo(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Pgr_pickDeliver::nodesOK(), pgrouting::Pgr_messages::operator=(), pgr_bellman_ford(), pgr_dijkstraTR(), and pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver().
{
     auto str = log.str();
     return str;
 }
get_notice()
std::string pgrouting::Pgr_messages::get_notice () const inherited
get_notice
Returns
the current contents of the log and clears the log
Definition at line 42 of file pgr_messages.cpp.
References pgrouting::Pgr_messages::notice.
Referenced by pgrouting::Pgr_messages::operator=().
{
     auto str = notice.str();
     return str;
 }
get_results() [1/2]
template<typename G> std::deque<Path> pgrouting::yen::Pgr_turnRestrictedPath< G >::get_results (std::deque< Path > & paths) inline private
Definition at line 197 of file pgr_turnRestrictedPath.hpp.
References Path::countInfinityCost(), pgrouting::yen::Pgr_turnRestrictedPath< G >::inf_cost_on_restriction(), pgrouting::yen::Pgr_turnRestrictedPath< G >::m_heap_paths, and pgrouting::yen::Pgr_turnRestrictedPath< G >::m_strict.
{
          if (paths.empty()) return paths;
          if (m_strict) return std::deque<Path>();
          paths = inf_cost_on_restriction(paths);
          std::stable_sort(paths.begin(), paths.end(),
                  [](const Path &left, const Path &right) -> bool {
                  return (left.countInfinityCost() < right.countInfinityCost());
                  });
          auto count = paths.begin()->countInfinityCost();
          if (m_heap_paths) return paths;
          paths.erase(
                  std::remove_if(
                      paths.begin(), paths.end(),
                      [&count](const Path &p){
                      return count != p.countInfinityCost();
                      }),
                  paths.end());
          return paths;
      }
get_results() [2/2]
template<class G> std::deque<Path> pgrouting::yen::Pgr_ksp< G >::get_results () inline protected inherited
Definition at line 199 of file pgr_ksp.hpp.
References pgrouting::yen::Pgr_ksp< G >::m_Heap, pgrouting::yen::Pgr_ksp< G >::m_heap_paths, pgrouting::yen::Pgr_ksp< G >::m_ResultSet, pgassert, and pgrouting::yen::Pgr_ksp< G >::v_source.
Referenced by pgrouting::yen::Pgr_ksp< G >::Yen(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::Yen().
{
          if (this->m_ResultSet.empty()) {
              return std::deque<Path>();
          }
          std::deque<Path> paths(m_ResultSet.begin(), m_ResultSet.end());
          if (m_heap_paths && !m_Heap.empty()) {
             paths.insert(paths.end(), m_Heap.begin(), m_Heap.end());
          }
          pgassert(!paths.empty());
          std::sort(paths.begin(), paths.end(), compPathsLess());
          return paths;
      }
getFirstSolution()
template<class G> Path pgrouting::yen::Pgr_ksp< G >::getFirstSolution (G & graph) inline protected inherited
Performs the first Dijkstra of the algorithm.
Definition at line 148 of file pgr_ksp.hpp.
References pgrouting::Pgr_dijkstra< G >::dijkstra(), Path::empty(), pgrouting::yen::Pgr_ksp< G >::m_end, pgrouting::yen::Pgr_ksp< G >::m_ResultSet, and pgrouting::yen::Pgr_ksp< G >::m_start.
Referenced by pgrouting::yen::Pgr_ksp< G >::executeYen().
{
          Path path;
          Pgr_dijkstra< G > fn_dijkstra;
          path = fn_dijkstra.dijkstra(graph, m_start, m_end);
          if (path.empty()) return path;
          m_ResultSet.insert(path);
          return path;
      }
has_error()
bool pgrouting::Pgr_messages::has_error () const inherited
get_error
Returns
the current contents of the log and clears the log
Definition at line 48 of file pgr_messages.cpp.
References pgrouting::Pgr_messages::error.
Referenced by do_pgr_many_withPointsDD(), do_pgr_withPoints(), do_pgr_withPointsKsp(), and pgrouting::Pgr_messages::operator=().
{
     return  !error.str().empty();
 }
inf_cost_on_restriction()
template<typename G> std::deque<Path> pgrouting::yen::Pgr_turnRestrictedPath< G >::inf_cost_on_restriction (std::deque< Path > & paths) inline private
sets an inf value on agg_cost on the vertex/edge where the restriction begins
Parameters
[in] paths that is being analized
Definition at line 241 of file pgr_turnRestrictedPath.hpp.
References pgrouting::yen::Pgr_turnRestrictedPath< G >::m_restrictions.
Referenced by pgrouting::yen::Pgr_turnRestrictedPath< G >::get_results().
{
          if (paths.empty()) return paths;
          for (auto &p : paths) {
              for (const auto r : m_restrictions) {
                  p = p.inf_cost_on_restriction(r);
              }
          }
          return paths;
      }
removeVertices()
template<class G> void pgrouting::yen::Pgr_ksp< G >::removeVertices (G & graph, const Path & subpath) inline protected inherited
stores in subPath the first i elements of path
Definition at line 194 of file pgr_ksp.hpp.
Referenced by pgrouting::yen::Pgr_ksp< G >::doNextCycle().
{
          for (const auto &e : subpath)
              graph.disconnect_vertex(e.node);
      }
turnRestrictedPath()
template<typename G> std::deque<Path> pgrouting::yen::Pgr_turnRestrictedPath< G >::turnRestrictedPath (G & graph, const std::vector< pgrouting::trsp::Rule > & restrictions, int64_t source, int64_t target, size_t k, bool heap_paths, bool stop_on_first, bool strict) inline
Definition at line 102 of file pgr_turnRestrictedPath.hpp.
References pgrouting::yen::Pgr_ksp< G >::m_Heap, pgrouting::yen::Pgr_turnRestrictedPath< G >::m_heap_paths, pgrouting::yen::Pgr_turnRestrictedPath< G >::m_restrictions, pgrouting::yen::Pgr_ksp< G >::m_ResultSet, pgrouting::yen::Pgr_turnRestrictedPath< G >::m_stop_on_first, pgrouting::yen::Pgr_turnRestrictedPath< G >::m_strict, pgassert, and pgrouting::yen::Pgr_turnRestrictedPath< G >::Yen().
Referenced by pgr_dijkstraTR().
{
         pgassert(m_restrictions.empty());
         pgassert(this->m_Heap.empty());
         pgassert(this->m_ResultSet.empty());
         m_stop_on_first = stop_on_first;
         m_strict = strict;
         m_restrictions = restrictions;
         m_heap_paths = heap_paths;
         return Yen(graph, source, target, k);
     }
Yen() [1/2]
template<class G> std::deque<Path> pgrouting::yen::Pgr_ksp< G >::Yen (G & graph, int64_t start_vertex, int64_t end_vertex, size_t K, bool heap_paths) inline inherited
Definition at line 61 of file pgr_ksp.hpp.
References pgrouting::yen::Pgr_ksp< G >::clear(), pgrouting::yen::Pgr_ksp< G >::executeYen(), pgrouting::yen::Pgr_ksp< G >::get_results(), pgrouting::yen::Pgr_ksp< G >::m_end, pgrouting::yen::Pgr_ksp< G >::m_heap_paths, pgrouting::yen::Pgr_ksp< G >::m_K, pgrouting::yen::Pgr_ksp< G >::m_start, pgrouting::yen::Pgr_ksp< G >::v_source, and pgrouting::yen::Pgr_ksp< G >::v_target.
Referenced by do_pgr_ksp(), and do_pgr_withPointsKsp().
{
          /*
           * No path: already in destination
           */
          if ((start_vertex == end_vertex) || (K == 0)) {
              return std::deque<Path>();
          }
          /*
           * no path: disconnected vertices
           */
          if (!graph.has_vertex(start_vertex)
                  || !graph.has_vertex(end_vertex)) {
              return std::deque<Path>();
          }
          /*
           * clean up containers
           */
          clear();
          v_source = graph.get_V(start_vertex);
          v_target = graph.get_V(end_vertex);
          m_start = start_vertex;
          m_end = end_vertex;
          m_K = K;
          m_heap_paths = heap_paths;
          executeYen(graph);
          auto paths = get_results();
          if (!m_heap_paths && paths.size() > m_K) paths.resize(m_K);
          return paths;
      }
Yen() [2/2]
template<typename G> std::deque<Path> pgrouting::yen::Pgr_turnRestrictedPath< G >::Yen (G & graph, int64_t start_vertex, int64_t end_vertex, size_t K) inline
Parameters
[in] graph
[in] start_vertex original id of vertex
[in] end_vertex original id of vertex
[in] K when k=0 stop at first path without turn restriction when k > 0 do K cycles and return best path without turn restriction
Definition at line 131 of file pgr_turnRestrictedPath.hpp.
References pgrouting::yen::Pgr_turnRestrictedPath< G >::clear(), pgrouting::yen::Pgr_ksp< G >::executeYen(), pgrouting::yen::Pgr_ksp< G >::get_results(), pgrouting::yen::Pgr_ksp< G >::m_end, pgrouting::yen::Pgr_ksp< G >::m_K, pgrouting::yen::Pgr_turnRestrictedPath< G >::m_restrictions, pgrouting::yen::Pgr_turnRestrictedPath< G >::m_solutions, pgrouting::yen::Pgr_ksp< G >::m_start, pgrouting::yen::Pgr_turnRestrictedPath< G >::m_stop_on_first, pgrouting::yen::Pgr_ksp< G >::m_vis, pgassert, pgrouting::yen::Pgr_ksp< G >::v_source, and pgrouting::yen::Pgr_ksp< G >::v_target.
Referenced by pgrouting::yen::Pgr_turnRestrictedPath< G >::turnRestrictedPath().
{
          /*
           * No path: already in destination
           */
          if ((start_vertex == end_vertex)) {
              return std::deque<Path>();
          }
          /*
           * no path: disconnected vertices
           */
          if (!graph.has_vertex(start_vertex)
                  || !graph.has_vertex(end_vertex)) {
              return std::deque<Path>();
          }
          /*
           * clean up containers
           */
          clear();
          this->v_source = graph.get_V(start_vertex);
          this->v_target = graph.get_V(end_vertex);
          this->m_start = start_vertex;
          this->m_end = end_vertex;
          this->m_K = K;
          Pgr_ksp<G>::m_heap_paths = true;
          delete this->m_vis;
          this->m_vis = new Myvisitor(
                  m_solutions,
                  m_restrictions,
                  m_stop_on_first);
          try {
               Pgr_ksp< G >::executeYen(graph);
          } catch(found_goals &) {
              pgassert(!m_solutions.empty());
              std::deque<Path> solutions(m_solutions.begin(), m_solutions.end());
              return solutions;
          } catch (boost::exception const& ex) {
              (void)ex;
              throw;
          } catch (std::exception &e) {
              (void)e;
              throw;
          } catch (...) {
              throw;
          }
          if (!m_solutions.empty()) {
              std::deque<Path> solutions(m_solutions.begin(), m_solutions.end());
              return solutions;
          }
          auto solutions = Pgr_ksp<G>::get_results();
          return get_results(solutions);
      }
Member Data Documentation
curr_result_path
template<class G> Path pgrouting::yen::Pgr_ksp< G >::curr_result_path protected inherited
storage for the current result
Definition at line 228 of file pgr_ksp.hpp.
Referenced by pgrouting::yen::Pgr_ksp< G >::doNextCycle(), and pgrouting::yen::Pgr_ksp< G >::executeYen().
dbg_log
std::ostringstream pgrouting::Pgr_messages::dbg_log mutable inherited
Definition at line 108 of file pgr_messages.h.
Referenced by pgrouting::Pgr_messages::clear(), pgrouting::Pgr_messages::get_dbglog(), and pgrouting::vrp::Optimize::save_if_best().
error
std::ostringstream pgrouting::Pgr_messages::error mutable inherited
Stores the error information.
Definition at line 106 of file pgr_messages.h.
Referenced by pgrouting::vrp::Fleet::build_fleet(), pgrouting::Pg_points_graph::check_points(), pgrouting::Pgr_messages::clear(), pgrouting::Pg_points_graph::create_new_edges(), pgrouting::Pgr_messages::get_error(), pgrouting::Pgr_messages::has_error(), pgrouting::vrp::Fleet::is_fleet_ok(), and pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver().
log
std::ostringstream pgrouting::Pgr_messages::log mutable inherited
Stores the hint information.
Definition at line 102 of file pgr_messages.h.
Referenced by pgrouting::vrp::Fleet::add_vehicle(), Pgr_bellman_ford< G >::bellman_ford(), Pgr_bellman_ford< G >::bellman_ford_1_to_1(), Pgr_bellman_ford< G >::bellman_ford_1_to_many(), pgrouting::alphashape::Pgr_alphaShape::build_best_alpha(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), pgrouting::Pg_points_graph::check_points(), pgrouting::Pgr_messages::clear(), pgrouting::Pg_points_graph::create_new_edges(), pgrouting::vrp::Optimize::delete_empty_truck(), pgrouting::vrp::Vehicle_pickDeliver::do_while_feasable(), pgrouting::vrp::Initial_solution::do_while_foo(), pgrouting::Pgr_messages::get_log(), Pgr_bellman_ford< G >::get_paths(), pgrouting::vrp::Pgr_pickDeliver::get_postgres_result(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Fleet::is_fleet_ok(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), pgrouting::Pgr_messages::operator=(), pgrouting::vrp::Optimize::Optimize(), pgrouting::vrp::Pgr_pickDeliver::optimize(), pgrouting::Pg_points_graph::Pg_points_graph(), pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Optimize::save_if_best(), pgrouting::vrp::Solution::Solution(), pgrouting::vrp::Pgr_pickDeliver::solve(), pgrouting::vrp::Optimize::swap_order(), and pgrouting::vrp::Vehicle::Vehicle().
m_end
template<class G> int64_t pgrouting::yen::Pgr_ksp< G >::m_end protected inherited
target id
Definition at line 224 of file pgr_ksp.hpp.
Referenced by pgrouting::yen::Pgr_ksp< G >::doNextCycle(), pgrouting::yen::Pgr_ksp< G >::getFirstSolution(), pgrouting::yen::Pgr_ksp< G >::Yen(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::Yen().
m_Heap
template<class G> pSet pgrouting::yen::Pgr_ksp< G >::m_Heap protected inherited
the heap
Definition at line 231 of file pgr_ksp.hpp.
Referenced by pgrouting::yen::Pgr_ksp< G >::clear(), pgrouting::yen::Pgr_ksp< G >::doNextCycle(), pgrouting::yen::Pgr_ksp< G >::executeYen(), pgrouting::yen::Pgr_ksp< G >::get_results(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::turnRestrictedPath().
m_heap_paths
template<typename G> bool pgrouting::yen::Pgr_turnRestrictedPath< G >::m_heap_paths private
Definition at line 257 of file pgr_turnRestrictedPath.hpp.
Referenced by pgrouting::yen::Pgr_turnRestrictedPath< G >::get_results(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::turnRestrictedPath().
m_K
template<class G> size_t pgrouting::yen::Pgr_ksp< G >::m_K protected inherited
Definition at line 225 of file pgr_ksp.hpp.
Referenced by pgrouting::yen::Pgr_ksp< G >::executeYen(), pgrouting::yen::Pgr_ksp< G >::Yen(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::Yen().
m_restrictions
template<typename G> std::vector<pgrouting::trsp::Rule> pgrouting::yen::Pgr_turnRestrictedPath< G >::m_restrictions private
Definition at line 253 of file pgr_turnRestrictedPath.hpp.
Referenced by pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::has_restriction(), pgrouting::yen::Pgr_turnRestrictedPath< G >::inf_cost_on_restriction(), pgrouting::yen::Pgr_turnRestrictedPath< G >::turnRestrictedPath(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::Yen().
m_ResultSet
template<class G> pSet pgrouting::yen::Pgr_ksp< G >::m_ResultSet protected inherited
ordered set of shortest paths
Definition at line 230 of file pgr_ksp.hpp.
Referenced by pgrouting::yen::Pgr_ksp< G >::clear(), pgrouting::yen::Pgr_ksp< G >::doNextCycle(), pgrouting::yen::Pgr_ksp< G >::executeYen(), pgrouting::yen::Pgr_ksp< G >::get_results(), pgrouting::yen::Pgr_ksp< G >::getFirstSolution(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::turnRestrictedPath().
m_solutions
template<typename G> pSet pgrouting::yen::Pgr_turnRestrictedPath< G >::m_solutions private
Definition at line 255 of file pgr_turnRestrictedPath.hpp.
Referenced by pgrouting::yen::Pgr_turnRestrictedPath< G >::clear(), pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::on_insert_first_solution(), pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::on_insert_to_heap(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::Yen().
m_start
template<class G> int64_t pgrouting::yen::Pgr_ksp< G >::m_start protected inherited
source id
Definition at line 223 of file pgr_ksp.hpp.
Referenced by pgrouting::yen::Pgr_ksp< G >::getFirstSolution(), pgrouting::yen::Pgr_ksp< G >::Yen(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::Yen().
m_stop_on_first
template<typename G> bool pgrouting::yen::Pgr_turnRestrictedPath< G >::m_stop_on_first private
Definition at line 256 of file pgr_turnRestrictedPath.hpp.
Referenced by pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::on_insert_first_solution(), pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::on_insert_to_heap(), pgrouting::yen::Pgr_turnRestrictedPath< G >::turnRestrictedPath(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::Yen().
m_strict
template<typename G> bool pgrouting::yen::Pgr_turnRestrictedPath< G >::m_strict private
Definition at line 254 of file pgr_turnRestrictedPath.hpp.
Referenced by pgrouting::yen::Pgr_turnRestrictedPath< G >::get_results(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::turnRestrictedPath().
m_vis
template<class G> Visitor* pgrouting::yen::Pgr_ksp< G >::m_vis protected inherited
Definition at line 233 of file pgr_ksp.hpp.
Referenced by pgrouting::yen::Pgr_ksp< G >::doNextCycle(), pgrouting::yen::Pgr_ksp< G >::executeYen(), pgrouting::yen::Pgr_ksp< G >::Pgr_ksp(), pgrouting::yen::Pgr_turnRestrictedPath< G >::Yen(), and pgrouting::yen::Pgr_ksp< G >::~Pgr_ksp().
notice
std::ostringstream pgrouting::Pgr_messages::notice mutable inherited
Stores the notice information.
Definition at line 104 of file pgr_messages.h.
Referenced by pgrouting::Pgr_messages::clear(), and pgrouting::Pgr_messages::get_notice().
v_source
template<class G> V pgrouting::yen::Pgr_ksp< G >::v_source protected inherited
source descriptor
Definition at line 221 of file pgr_ksp.hpp.
Referenced by pgrouting::yen::Pgr_ksp< G >::get_results(), pgrouting::yen::Pgr_ksp< G >::Yen(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::Yen().
v_target
template<class G> V pgrouting::yen::Pgr_ksp< G >::v_target protected inherited
target descriptor
Definition at line 222 of file pgr_ksp.hpp.
Referenced by pgrouting::yen::Pgr_ksp< G >::Yen(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::Yen().
The documentation for this class was generated from the following file:
pgr_turnRestrictedPath.hpp