PGROUTING: Path Class Reference
Path Class Reference
#include "basePath_SSEC.hpp"
Public Member Functions
Path ()
Path (int64_t s_id, int64_t e_id)
Path (const Path &)=default
template<typename G , typename V >
Path (G &graph, int64_t source, double distance, const std::vector< V > &predecessors, const std::vector< double > &distances)
template<typename G >
Path (const G &graph, const Path &original, bool only_cost)
template<typename G , typename V >
Path (G &graph, V v_source, double distance, const std::vector< V > &predecessors, const std::vector< double > &distances)
template<typename G , typename V >
Path (const G &graph, const V v_source, const V v_target, const std::vector< V > &predecessors, const std::vector< double > &distances, bool only_cost, bool normal=true)
void append (const Path &other)
Path: 2 -> 9 seq node edge cost agg_cost 0 2 4 1 0 1 5 8 1 1 2 6 9 1 2 3 9 -1 0 3 Path: 9 -> 3 seq node edge cost agg_cost 0 9 16 1 0 1 4 3 1 1 2 3 -1 0 2 Path: 2 -> 3 seq node edge cost agg_cost 0 2 4 1 0 1 5 8 1 1 2 6 9 1 2 3 9 16 1 3 4 4 3 1 4 5 3 -1 0 5.
void appendPath (const Path &o_path)
const Path_t & back () const
Path_t & back ()
pthIt begin ()
ConstpthIt begin () const
void clear ()
template<typename G , typename V >
void complete_path (const G &graph, const V v_source, const V v_target, const std::vector< V > &predecessors, const std::vector< double > &distances, bool normal)
constructs a path based on results
size_t countInfinityCost () const
bool empty () const
void empty_path (unsigned int d_vertex)
pthIt end ()
ConstpthIt end () const
int64_t end_id () const
void end_id (int64_t value)
void erase (pthIt pos)
ConstpthIt find_restriction (const pgrouting::trsp::Rule &rule) const
get the iterator of the path where the (restriction) rule starts
const Path_t & front () const
Path_t & front ()
void generate_postgres_data (General_path_element_t **postgres_data, size_t &sequence) const
void get_pg_dd_path (General_path_element_t **ret_path, size_t &sequence) const
void get_pg_ksp_path (General_path_element_t **ret_path, size_t &sequence, int routeId) const
void get_pg_turn_restricted_path (General_path_element_t **ret_path, size_t &sequence, int routeId) const
Path getSubpath (unsigned int j) const
bool has_restriction (const pgrouting::trsp::Rule &rule) const
Path inf_cost_on_restriction (const pgrouting::trsp::Rule &rule)
bool isEqual (const Path &subpath) const
const Path_t & operator[] (size_t i) const
Path_t & operator[] (size_t i)
void push_back (Path_t data)
void push_front (Path_t data)
void push_front (int64_t d_vertex, int64_t d_edge, double d_cost, double d_tot_cost)
void recalculate_agg_cost ()
Path & renumber_vertices (int64_t value)
void reverse ()
Path_t set_data (int64_t d_from, int64_t d_to, int64_t d_vertex, int64_t d_edge, double d_cost, double d_tot_cost)
size_t size () const
void sort_by_node_agg_cost ()
Sorts a path by node, aggcost ascending.
int64_t start_id () const
void start_id (int64_t value)
double tot_cost () const
Private Types
typedef std::deque< Path_t >::const_iterator ConstpthIt
typedef std::deque< Path_t >::iterator pthIt
Private Attributes
int64_t m_end_id
int64_t m_start_id
double m_tot_cost
std::deque< Path_t > path
Friends
size_t collapse_paths (General_path_element_t **ret_path, const std::deque< Path > &paths)
size_t count_tuples (const std::deque< Path > &paths)
counts the tuples to be returned
void equi_cost (std::deque< Path > &paths)
discards common vertices with greater agg_cost
std::ostream & operator<< (std::ostream &log, const Path &p)
Detailed Description
Definition at line 47 of file basePath_SSEC.hpp.
Member Typedef Documentation
ConstpthIt
typedef std::deque< Path_t >::const_iterator Path::ConstpthIt private
Definition at line 49 of file basePath_SSEC.hpp.
pthIt
typedef std::deque< Path_t >::iterator Path::pthIt private
Definition at line 48 of file basePath_SSEC.hpp.
Constructor & Destructor Documentation
Path() [1/7]
Path::Path () inline
Definition at line 58 of file basePath_SSEC.hpp.
Referenced by Path().
           : m_start_id(0), m_end_id(0), m_tot_cost(0)
     {}
Path() [2/7]
Path::Path (int64_t s_id, int64_t e_id) inline
Definition at line 60 of file basePath_SSEC.hpp.
References Path().
         : m_start_id(s_id), m_end_id(e_id), m_tot_cost(0)
     {}
Path() [3/7]
Path::Path (const Path &) default
Path() [4/7]
template<typename G , typename V > Path::Path (G & graph, int64_t source, double distance, const std::vector< V > & predecessors, const std::vector< double > & distances) inline
Definition at line 162 of file basePath_SSEC.hpp.
References push_back().
                                                 :
         m_start_id(source),
         m_end_id(source) {
             for (V i = 0; i < distances.size(); ++i) {
                 if (distances[i] <= distance) {
                     auto cost = distances[i] - distances[predecessors[i]];
                     auto edge_id = graph.get_edge_id(predecessors[i], i, cost);
                     push_back(
                             {graph[i].id,
                             edge_id, cost,
                             distances[i]});
                 }
             }
         }
Path() [5/7]
template<typename G > Path::Path (const G & graph, const Path & original, bool only_cost) inline
Definition at line 183 of file basePath_SSEC.hpp.
References m_end_id, m_tot_cost, path, push_back(), and recalculate_agg_cost().
                             :
         m_start_id(original.m_start_id),
         m_end_id(original.m_end_id),
         m_tot_cost(0) {
             if (original.path.empty()) return;
             typename G::EO_i ei, ei_end;
 //            auto last_node = m_start_id;
             for (const auto &p : original.path) {
                 boost::tie(ei, ei_end) = out_edges(
                         graph.get_V(p.node),
                         graph.graph);
                 if (p.edge == -1) {
                     path.push_back({m_end_id, -1, 0, 0});
                 } else {
                     for ( ; ei != ei_end; ++ei) {
                         if (graph[*ei].id == p.edge) {
                             auto cost = graph[*ei].cost;
                             push_back({p.node, p.edge, cost, 0});
                         }
                     }
                 }
 //                last_node = p.node;
             }
             recalculate_agg_cost();
             if (only_cost) {
                 path.clear();
                 path.push_back(
                         {m_end_id,
                         -1,
                         m_tot_cost,
                         m_tot_cost});
             }
         }
Path() [6/7]
template<typename G , typename V > Path::Path (G & graph, V v_source, double distance, const std::vector< V > & predecessors, const std::vector< double > & distances) inline
Definition at line 224 of file basePath_SSEC.hpp.
References push_back().
                                                 :
         m_start_id(graph.graph[v_source].id),
         m_end_id(graph.graph[v_source].id) {
         for (V i = 0; i < distances.size(); ++i) {
             if (distances[i] <= distance) {
                 auto cost = distances[i] - distances[predecessors[i]];
                 auto edge_id = graph.get_edge_id(predecessors[i], i, cost);
                 push_back(
                         {graph[i].id,
                         edge_id, cost,
                         distances[i]});
             }
         }
     }
Path() [7/7]
template<typename G , typename V > Path::Path (const G & graph, const V v_source, const V v_target, const std::vector< V > & predecessors, const std::vector< double > & distances, bool only_cost, bool normal = true) inline
Definition at line 246 of file basePath_SSEC.hpp.
References complete_path(), and push_front().
                                 :
         m_start_id(graph.graph[v_source].id),
         m_end_id(graph.graph[v_target].id) {
             if (!only_cost) {
                 complete_path(graph,
                         v_source,
                         v_target,
                         predecessors,
                         distances,
                         normal);
                 return;
             }
             /*
              * only_cost
              */
             if (v_target != predecessors[v_target]) {
                 push_front(
                         {graph.graph[v_target].id,
                         -1,
                         distances[v_target],
                         distances[v_target]});
             }
             return;
         }
Member Function Documentation
append()
void Path::append (const Path & other)
Path: 2 -> 9 seq node edge cost agg_cost 0 2 4 1 0 1 5 8 1 1 2 6 9 1 2 3 9 -1 0 3 Path: 9 -> 3 seq node edge cost agg_cost 0 9 16 1 0 1 4 3 1 1 2 3 -1 0 2 Path: 2 -> 3 seq node edge cost agg_cost 0 2 4 1 0 1 5 8 1 1 2 6 9 1 2 3 9 16 1 3 4 4 3 1 4 5 3 -1 0 5.
Definition at line 192 of file basePath_SSEC.cpp.
References m_end_id, m_start_id, path, pgassert, and push_back().
Referenced by pgrouting::bidirectional::Pgr_bidirectional< G >::bidirectional(), and front().
{
     pgassert(m_end_id == other.m_start_id);
     if (other.m_start_id == other.m_end_id) {
         pgassert(other.path.empty());
         return;
     }
     if (m_start_id == m_end_id) {
         pgassert(path.empty());
         *this = other;
         return;
     }
 #if 0
     pgassert(path.back().cost == 0);
 #endif
     pgassert(path.back().edge == -1);
     m_end_id = other.m_end_id;
     auto last = path.back();
     auto agg_cost = last.agg_cost;
     path.pop_back();
     for (auto item : other.path) {
         item.agg_cost += agg_cost;
         push_back(item);
     }
 }
appendPath()
void Path::appendPath (const Path & o_path)
Definition at line 164 of file basePath_SSEC.cpp.
References path, and recalculate_agg_cost().
Referenced by pgrouting::yen::Pgr_ksp< G >::doNextCycle(), and front().
{
     path.insert(path.end(), o_path.path.begin(), o_path.path.end());
     recalculate_agg_cost();
 }
back() [1/2]
const Path_t& Path::back () const inline
Definition at line 88 of file basePath_SSEC.hpp.
 {return path.back();}
back() [2/2]
Path_t& Path::back () inline
Definition at line 89 of file basePath_SSEC.hpp.
 {return path.back();}
begin() [1/2]
pthIt Path::begin () inline
Definition at line 81 of file basePath_SSEC.hpp.
Referenced by pgrouting::functions::Pgr_binaryBreadthFirstSearch< G >::getPath(), pgrouting::functions::Pgr_edwardMoore< G >::getPath(), and isEqual().
 {return path.begin();}
begin() [2/2]
ConstpthIt Path::begin () const inline
Definition at line 83 of file basePath_SSEC.hpp.
 {return path.begin();}
clear()
void Path::clear ()
Definition at line 87 of file basePath_SSEC.cpp.
References m_end_id, m_start_id, m_tot_cost, and path.
Referenced by pgrouting::trsp::Pgr_trspHandler::clear(), and front().
                  {
     path.clear();
     m_tot_cost = 0;
     m_start_id = 0;
     m_end_id = 0;
 }
complete_path()
template<typename G , typename V > void Path::complete_path (const G & graph, const V v_source, const V v_target, const std::vector< V > & predecessors, const std::vector< double > & distances, bool normal) inline
constructs a path based on results
Normal = false for reversed search path like in pgr_bdDijkstra
Definition at line 282 of file basePath_SSEC.hpp.
References push_front().
Referenced by Path().
{
         // no path was found
         if (v_target == predecessors[v_target]) {
             return;
         }
         /*
          * set the target
          */
         auto target = v_target;
         /*
          * the last stop is the target
          */
         push_front(
                 {graph.graph[target].id, -1,
                 0,  distances[target]});
         /*
          * get the path
          */
         while (target != v_source) {
             /*
              * done when the predecesor of the target is the target
              */
             if (target == predecessors[target]) break;
             /*
              * Inserting values in the path
              */
             auto cost = distances[target] - distances[predecessors[target]];
             auto vertex_id = graph.graph[predecessors[target]].id;
             auto edge_id = normal?
                 graph.get_edge_id(predecessors[target], target, cost)
                 : graph.get_edge_id(target, predecessors[target], cost);
             push_front({
                     vertex_id,
                     edge_id,
                     cost,
                     distances[target] - cost});
             target = predecessors[target];
         }
         return;
     }
countInfinityCost()
size_t Path::countInfinityCost () const
Definition at line 133 of file basePath_SSEC.cpp.
References path.
Referenced by empty(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::get_results().
{
     return std::count_if(path.begin(), path.end(),
             [](Path_t const&p) -> size_t {
             return std::isinf(p.agg_cost);
             });
 }
empty()
bool Path::empty () const inline
Definition at line 72 of file basePath_SSEC.hpp.
References countInfinityCost(), push_back(), and push_front().
Referenced by pgrouting::Pg_points_graph::adjust_pids(), pgrouting::Pg_points_graph::eliminate_details(), pgrouting::Pg_points_graph::eliminate_details_dd(), pgrouting::yen::Pgr_ksp< G >::getFirstSolution(), isEqual(), pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::on_insert_first_solution(), pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::on_insert_to_heap(), and pgRouting::pgr_dijkstraVia().
 {return path.empty();}
empty_path()
void Path::empty_path (unsigned int d_vertex)
Referenced by front().
end() [1/2]
pthIt Path::end () inline
Definition at line 82 of file basePath_SSEC.hpp.
Referenced by pgrouting::functions::Pgr_binaryBreadthFirstSearch< G >::getPath(), pgrouting::functions::Pgr_edwardMoore< G >::getPath(), and isEqual().
 {return path.end();}
end() [2/2]
ConstpthIt Path::end () const inline
Definition at line 84 of file basePath_SSEC.hpp.
 {return path.end();}
end_id() [1/2]
int64_t Path::end_id () const inline
Definition at line 67 of file basePath_SSEC.hpp.
References m_end_id.
Referenced by pgrouting::Pg_points_graph::adjust_pids(), pgrouting::algorithms::Pgr_astar< G >::astar(), Pgr_bellman_ford< G >::bellman_ford(), pgrouting::functions::Pgr_binaryBreadthFirstSearch< G >::binaryBreadthFirstSearch(), Pgr_dag< G >::dag(), pgrouting::Pgr_dijkstra< G >::dijkstra(), do_pgr_withPoints(), pgrouting::functions::Pgr_edwardMoore< G >::edwardMoore(), pgrouting::Pg_points_graph::eliminate_details(), pgrouting::Pg_points_graph::eliminate_details_dd(), generate_postgres_data(), get_pg_ksp_path(), get_pg_turn_restricted_path(), getSubpath(), operator<<(), pgrouting::trsp::Pgr_trspHandler::process(), and pgrouting::trsp::Pgr_trspHandler::process_trsp().
 {return m_end_id;}
end_id() [2/2]
void Path::end_id (int64_t value) inline
Definition at line 68 of file basePath_SSEC.hpp.
 {m_end_id = value;}
erase()
void Path::erase (pthIt pos) inline
Definition at line 87 of file basePath_SSEC.hpp.
 {path.erase(pos);}
find_restriction()
Path::ConstpthIt Path::find_restriction (const pgrouting::trsp::Rule & rule) const
get the iterator of the path where the (restriction) rule starts
Parameters
[in] rule A subpath of edges for turn restrictions
Returns
the iterator of the path
Definition at line 94 of file basePath_SSEC.cpp.
References pgrouting::trsp::Rule::begin(), Path_t::edge, pgrouting::trsp::Rule::end(), and path.
Referenced by front(), and has_restriction().
{
     return std::search(path.begin(),  path.end(), rule.begin(), rule.end(),
             [](Path_t p, int64_t e) {return p.edge == e;});
 }
front() [1/2]
const Path_t& Path::front () const inline
Definition at line 90 of file basePath_SSEC.hpp.
 {return path.front();}
front() [2/2]
Path_t& Path::front () inline
Definition at line 91 of file basePath_SSEC.hpp.
References append(), appendPath(), clear(), collapse_paths, count_tuples, empty_path(), equi_cost, find_restriction(), generate_postgres_data(), get_pg_dd_path(), get_pg_ksp_path(), get_pg_turn_restricted_path(), getSubpath(), has_restriction(), inf_cost_on_restriction(), isEqual(), operator<<, push_front(), recalculate_agg_cost(), reverse(), set_data(), and sort_by_node_agg_cost().
 {return path.front();}
generate_postgres_data()
void Path::generate_postgres_data (General_path_element_t ** postgres_data, size_t & sequence) const
Definition at line 221 of file basePath_SSEC.cpp.
References end_id(), path, and start_id().
Referenced by front().
{
     int i = 1;
     for (const auto e : path) {
         auto agg_cost = std::fabs(
                 e.agg_cost - (std::numeric_limits<double>::max)()) < 1?
             std::numeric_limits<double>::infinity() : e.agg_cost;
         auto cost = std::fabs(e.cost - (std::numeric_limits<double>::max)()) < 1?
             std::numeric_limits<double>::infinity() : e.cost;
         (*postgres_data)[sequence] = {i, start_id(), end_id(), e.node, e.edge, cost, agg_cost};
         ++i;
         ++sequence;
     }
 }
get_pg_dd_path()
void Path::get_pg_dd_path (General_path_element_t ** ret_path, size_t & sequence) const
Definition at line 239 of file basePath_SSEC.cpp.
References path, and start_id().
Referenced by front().
{
     for (unsigned int i = 0; i < path.size(); i++) {
         (*ret_path)[sequence].seq = i;
         (*ret_path)[sequence].start_id = start_id();
         (*ret_path)[sequence].end_id = start_id();
         (*ret_path)[sequence].node = path[i].node;
         (*ret_path)[sequence].edge = path[i].edge;
         (*ret_path)[sequence].cost = path[i].cost;
         (*ret_path)[sequence].agg_cost = path[i].agg_cost;
         sequence++;
     }
 }
get_pg_ksp_path()
void Path::get_pg_ksp_path (General_path_element_t ** ret_path, size_t & sequence, int routeId) const
Definition at line 255 of file basePath_SSEC.cpp.
References end_id(), and path.
Referenced by front().
{
     for (unsigned int i = 0; i < path.size(); i++) {
         (*ret_path)[sequence].seq = i + 1;
         (*ret_path)[sequence].start_id = routeId;
         (*ret_path)[sequence].end_id = end_id();
         (*ret_path)[sequence].node = path[i].node;
         (*ret_path)[sequence].edge = path[i].edge;
         (*ret_path)[sequence].cost = path[i].cost;
         (*ret_path)[sequence].agg_cost = (i == 0)?
             0 :
             (*ret_path)[sequence-1].agg_cost +  path[i-1].cost;
         sequence++;
     }
 }
get_pg_turn_restricted_path()
void Path::get_pg_turn_restricted_path (General_path_element_t ** ret_path, size_t & sequence, int routeId) const
Definition at line 273 of file basePath_SSEC.cpp.
References end_id(), and path.
Referenced by front().
{
     for (unsigned int i = 0; i < path.size(); i++) {
         (*ret_path)[sequence].seq = i + 1;
         (*ret_path)[sequence].start_id = routeId;
         (*ret_path)[sequence].end_id = end_id();
         (*ret_path)[sequence].node = path[i].node;
         (*ret_path)[sequence].edge = path[i].edge;
         (*ret_path)[sequence].cost = path[i].cost;
         (*ret_path)[sequence].agg_cost = path[i].agg_cost;
         sequence++;
     }
 }
getSubpath()
Path Path::getSubpath (unsigned int j) const
Definition at line 141 of file basePath_SSEC.cpp.
References end_id(), path, pgassert, push_back(), start_id(), and tot_cost().
Referenced by pgrouting::yen::Pgr_ksp< G >::doNextCycle(), and front().
{
     Path result(start_id(), end_id());
     if (j == 0)  return result;
     for (auto i = path.begin(); i != path.begin() + j; ++i) {
         result.push_back((*i));
     }
     pgassert(result.tot_cost() != 0);
     pgassert(this->tot_cost() != 0);
     return result;
 }
has_restriction()
bool Path::has_restriction (const pgrouting::trsp::Rule & rule) const
Definition at line 100 of file basePath_SSEC.cpp.
References find_restriction(), and path.
Referenced by front(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::has_restriction().
{
     return find_restriction(rule) != path.end();
 }
inf_cost_on_restriction()
Path Path::inf_cost_on_restriction (const pgrouting::trsp::Rule & rule)
Definition at line 105 of file basePath_SSEC.cpp.
References pgrouting::trsp::Rule::begin(), Path_t::edge, pgrouting::trsp::Rule::end(), and path.
Referenced by front().
{
     auto position = std::search(
             path.begin(),  path.end(), rule.begin(), rule.end(),
             [](Path_t p, int64_t e) { return p.edge == e;});
     if (position != path.end()) {
         position->agg_cost = std::numeric_limits<double>::infinity();
     }
     return *this;
 }
isEqual()
bool Path::isEqual (const Path & subpath) const
Definition at line 153 of file basePath_SSEC.cpp.
References begin(), empty(), end(), path, and size().
Referenced by front().
{
     if (subpath.empty()) return true;
     if (subpath.size() >= path.size()) return false;
     std::deque< Path_t >::const_iterator i, j;
     for (i = path.begin(),  j = subpath.begin();
             j != subpath.end();
             ++i, ++j)
         if ((*i).node != (*j).node) return false;
     return true;
 }
operator[]() [1/2]
const Path_t& Path::operator[] (size_t i) const inline
Definition at line 77 of file basePath_SSEC.hpp.
 {return path[i];}
operator[]() [2/2]
Path_t& Path::operator[] (size_t i) inline
Definition at line 78 of file basePath_SSEC.hpp.
References renumber_vertices().
 {return path[i];}
push_back()
void Path::push_back (Path_t data)
Definition at line 52 of file basePath_SSEC.cpp.
References Path_t::cost, m_tot_cost, and path.
Referenced by append(), pgrouting::trsp::Pgr_trspHandler::construct_path(), pgrouting::Pgr_dijkstra< G >::drivingDistance_no_equicost(), pgrouting::Pg_points_graph::eliminate_details(), empty(), pgrouting::functions::Pgr_binaryBreadthFirstSearch< G >::getPath(), pgrouting::functions::Pgr_edwardMoore< G >::getPath(), getSubpath(), Path(), and pgrouting::trsp::Pgr_trspHandler::process_trsp().
{
     path.push_back(data);
     m_tot_cost += data.cost;
 }
push_front() [1/2]
void Path::push_front (Path_t data)
Definition at line 47 of file basePath_SSEC.cpp.
References Path_t::cost, m_tot_cost, and path.
Referenced by complete_path(), empty(), front(), and Path().
{
     path.push_front(data);
     m_tot_cost += data.cost;
 }
push_front() [2/2]
void Path::push_front (int64_t d_vertex, int64_t d_edge, double d_cost, double d_tot_cost)
recalculate_agg_cost()
void Path::recalculate_agg_cost ()
Definition at line 77 of file basePath_SSEC.cpp.
References m_tot_cost, and path.
Referenced by appendPath(), front(), and Path().
{
     m_tot_cost = 0;
     for (auto &p : path) {
         p.agg_cost = m_tot_cost;
         m_tot_cost += p.cost;
     }
 }
renumber_vertices()
Path & Path::renumber_vertices (int64_t value)
Definition at line 38 of file basePath_SSEC.cpp.
References m_end_id, m_start_id, and path.
Referenced by operator[](), and pgrouting::trsp::Pgr_trspHandler::process_trsp().
{
     for (auto &r : path) {
         r.node += value;
     }
     m_start_id += value;
     m_end_id += value;
     return *this;
 }
reverse()
void Path::reverse ()
Definition at line 57 of file basePath_SSEC.cpp.
References m_end_id, m_start_id, and path.
Referenced by pgrouting::bidirectional::Pgr_bidirectional< G >::bidirectional(), front(), pgr_astar(), and pgr_dijkstra().
                    {
     std::swap(m_start_id, m_end_id);
     if (path.size() <= 1) return;
     std::deque< Path_t > newpath;
     for (size_t i = 0; i < path.size(); ++i) {
         newpath.push_front({
                 path[i].node,
                 (i == 0? -1 : path[i - 1].edge),
                 (i == 0? 0 : path[i - 1].cost),
                 0
                 });
     }
     for (size_t i = 0; i < newpath.size(); ++i) {
         newpath[i].agg_cost = (i == 0)?
             0 :
             newpath[i - 1].agg_cost +  newpath[i - 1].cost;
     }
     path = newpath;
 }
set_data()
Path_t Path::set_data (int64_t d_from, int64_t d_to, int64_t d_vertex, int64_t d_edge, double d_cost, double d_tot_cost)
Referenced by front().
size()
size_t Path::size () const inline
Definition at line 71 of file basePath_SSEC.hpp.
Referenced by pgrouting::yen::Pgr_ksp< G >::doNextCycle(), equi_cost(), isEqual(), pgrouting::compPathsLess::operator()(), and pgRouting::pgr_dijkstraVia().
 {return path.size();}
sort_by_node_agg_cost()
void Path::sort_by_node_agg_cost ()
Sorts a path by node, aggcost ascending.
nodes ASC agg_cost ASC
Definition at line 295 of file basePath_SSEC.cpp.
References Path_t::agg_cost, Path_t::node, and path.
Referenced by front().
{
     std::sort(path.begin(), path.end(),
             [](const Path_t &l, const  Path_t &r)
             {return l.node < r.node;});
     std::stable_sort(path.begin(), path.end(),
             [](const Path_t &l, const  Path_t &r)
             {return l.agg_cost < r.agg_cost;});
 }
start_id() [1/2]
int64_t Path::start_id () const inline
Definition at line 65 of file basePath_SSEC.hpp.
References m_start_id.
Referenced by pgrouting::Pg_points_graph::adjust_pids(), pgrouting::algorithms::Pgr_astar< G >::astar(), Pgr_bellman_ford< G >::bellman_ford(), pgrouting::functions::Pgr_binaryBreadthFirstSearch< G >::binaryBreadthFirstSearch(), pgrouting::trsp::Pgr_trspHandler::construct_path(), Pgr_dag< G >::dag(), pgrouting::Pgr_dijkstra< G >::dijkstra(), do_pgr_withPoints(), pgrouting::functions::Pgr_edwardMoore< G >::edwardMoore(), pgrouting::Pg_points_graph::eliminate_details(), pgrouting::Pg_points_graph::eliminate_details_dd(), equi_cost(), generate_postgres_data(), get_pg_dd_path(), getSubpath(), operator<<(), pgrouting::trsp::Pgr_trspHandler::process(), and pgrouting::trsp::Pgr_trspHandler::process_trsp().
 {return m_start_id;}
start_id() [2/2]
void Path::start_id (int64_t value) inline
Definition at line 66 of file basePath_SSEC.hpp.
 {m_start_id = value;}
tot_cost()
double Path::tot_cost () const inline
Definition at line 69 of file basePath_SSEC.hpp.
References m_tot_cost.
Referenced by getSubpath(), and pgrouting::compPathsLess::operator()().
 {return m_tot_cost;}
Friends And Related Function Documentation
collapse_paths
size_t collapse_paths (General_path_element_t ** ret_path, const std::deque< Path > & paths) friend
Definition at line 310 of file basePath_SSEC.cpp.
Referenced by front().
{
     size_t sequence = 0;
     for (const Path &path : paths) {
         if (path.path.size() > 0)
             path.generate_postgres_data(ret_path, sequence);
     }
     return sequence;
 }
count_tuples
size_t count_tuples (const std::deque< Path > & paths) friend
counts the tuples to be returned
Definition at line 387 of file basePath_SSEC.cpp.
Referenced by front().
{
     size_t count(0);
     for (const Path &e : paths) {
         count += e.path.size();
     }
     return count;
 }
equi_cost
void equi_cost (std::deque< Path > & paths) friend
discards common vertices with greater agg_cost
Definition at line 336 of file basePath_SSEC.cpp.
Referenced by front().
{
     /* sort paths by size: largest first */
     std::sort(paths.begin(), paths.end(),
             [](const Path &e1, const Path &e2)->bool {
             return e2.size() < e1.size();
             });
     /* sort each path by node: smaller id first */
     for (auto &p : paths) {
         if (p.size() < 2) continue;
         std::sort(p.begin(), p.end(),
                 [](const Path_t &e1, const Path_t &e2)->bool {
                 return e1.node < e2.node;
                 });
     }
     for (auto &p1 : paths) {
         for (const auto &p2 : paths) {
             if (p1.start_id() == p2.start_id()) continue;
             for (const auto &stop : p2.path) {
                 /* find the node of p2 in p1 */
                 auto pos = lower_bound(p1.begin(), p1.end(), stop,
                         [](const Path_t &l, const Path_t &r)->bool {
                         return l.node < r.node;
                         });
                 if (pos != p1.end()
                         && (stop.node == pos->node)
                         && (stop.agg_cost < pos->agg_cost)) {
                     /* both share the same node &
                      * the second path has the smallest
                      *  So erasing from the first path */
                     p1.erase(pos);
                 }
             }
         }
     }
     /* sort paths by start_id */
     std::sort(paths.begin(), paths.end(),
             [](const Path &e1, const Path &e2)->bool {
             return e1.start_id() < e2.start_id();
             });
     /* sort each path by agg_cost, node */
     for (auto &path : paths) {
         path.sort_by_node_agg_cost();
     }
 }
operator<<
std::ostream& operator<< (std::ostream & log, const Path & p) friend
Definition at line 118 of file basePath_SSEC.cpp.
Referenced by front().
{
     log << "Path: " << path.start_id() << " -> " << path.end_id() << "\n"
         << "seq\tnode\tedge\tcost\tagg_cost\n";
     int64_t i = 0;
     for (const auto &e : path) {
         log << i << "\t"
             << e.node << "\t"
             << e.edge << "\t"
             << e.cost << "\t"
             << e.agg_cost << "\n";
         ++i;
     }
     return log;
 }
Member Data Documentation
m_end_id
int64_t Path::m_end_id private
Definition at line 54 of file basePath_SSEC.hpp.
Referenced by append(), clear(), end_id(), Path(), renumber_vertices(), and reverse().
m_start_id
int64_t Path::m_start_id private
Definition at line 53 of file basePath_SSEC.hpp.
Referenced by append(), clear(), renumber_vertices(), reverse(), and start_id().
m_tot_cost
double Path::m_tot_cost private
Definition at line 55 of file basePath_SSEC.hpp.
Referenced by clear(), Path(), push_back(), push_front(), recalculate_agg_cost(), and tot_cost().
path
std::deque< Path_t > Path::path private
Definition at line 52 of file basePath_SSEC.hpp.
Referenced by append(), appendPath(), clear(), collapse_paths(), countInfinityCost(), equi_cost(), find_restriction(), generate_postgres_data(), get_pg_dd_path(), get_pg_ksp_path(), get_pg_turn_restricted_path(), getSubpath(), has_restriction(), inf_cost_on_restriction(), isEqual(), Path(), push_back(), push_front(), recalculate_agg_cost(), renumber_vertices(), reverse(), and sort_by_node_agg_cost().
The documentation for this class was generated from the following files:
basePath_SSEC.hpp
basePath_SSEC.cpp