PGROUTING: Pgr_prim< G > Class Template Reference
Pgr_prim< G > Class Template Reference
#include "pgr_prim.hpp"
Classes
class prim_visitor
Public Types
typedef G::B_G B_G
typedef G::V V
Public Member Functions
std::vector< pgr_prim_t > prim (G &graph, int64_t root_vertex, bool use_root)
Private Member Functions
double aggegrateCost (V root_vertex, V find_node)
void clear ()
std::vector< pgr_prim_t > disconnectedPrim (const G &graph)
std::vector< pgr_prim_t > generatePrim (const G &graph, int64_t root_vertex)
void resize (const G &graph)
Private Attributes
std::vector< V > data
std::vector< double > distances
std::vector< V > predecessors
Detailed Description
template<class G>
class Pgr_prim< G >
Definition at line 46 of file pgr_prim.hpp.
Member Typedef Documentation
template<class G> typedef G::B_G Pgr_prim< G >::B_G
Definition at line 57 of file pgr_prim.hpp.
template<class G> typedef G::V Pgr_prim< G >::V
Definition at line 56 of file pgr_prim.hpp.
Member Function Documentation
template<class G> double Pgr_prim< G >::aggegrateCost (V root_vertex, V find_node) inline private
Definition at line 138 of file pgr_prim.hpp.
Referenced by Pgr_prim< G >::generatePrim().
{
        double agg_cost = 0;
        for (V i = find_node; i!=root_vertex;){
           auto parent =  predecessors[i];
           auto cost = distances[i] - distances[root_vertex];
           agg_cost += cost;
           i = parent;
        }
        return agg_cost;
     }
template<class G> void Pgr_prim< G >::clear () inline private
Definition at line 72 of file pgr_prim.hpp.
Referenced by Pgr_prim< G >::disconnectedPrim(), and Pgr_prim< G >::prim().
                   {
          data.clear();
          predecessors.clear();
          distances.clear();
      }
template<class G> std::vector< pgr_prim_t > Pgr_prim< G >::disconnectedPrim (const G & graph) inline private
Definition at line 156 of file pgr_prim.hpp.
References Pgr_prim< G >::clear(), Pgr_prim< G >::generatePrim(), and Pgr_prim< G >::resize().
Referenced by Pgr_prim< G >::prim().
{
          size_t totalNodes = num_vertices(graph.graph); // Total Node in graph
          /*Calculate connected components*/
          std::vector< int > components(totalNodes);
          size_t num_comps = boost::connected_components(graph.graph, &components[0]);
          std::vector< std::vector< int64_t > > component;
          component.resize(num_comps);
          for (size_t i = 0; i < totalNodes; i++)
              component[components[i]].push_back(i);
          std::vector< pgr_prim_t > results, tmpresults;
          for (size_t i = 0; i < num_comps; i++) {
                /*Implementation */
                clear();
                resize(graph);
                tmpresults = generatePrim(
                              graph,
                              graph.graph[component[i][0]].id);
                size_t size = component[i].size();
                for (size_t j = 0; j < size; j++) {
                    results.push_back(tmpresults[j]);
                }
          }//for i
          return results;
     }
template<class G> std::vector< pgr_prim_t > Pgr_prim< G >::generatePrim (const G & graph, int64_t root_vertex) inline private
Definition at line 84 of file pgr_prim.hpp.
References pgr_prim_t::agg_cost, Pgr_prim< G >::aggegrateCost(), pgr_prim_t::cost, pgr_prim_t::edge, pgr_prim_t::node, pgr_prim_t::root_vertex, and pgr_prim_t::tree_cost.
Referenced by Pgr_prim< G >::disconnectedPrim(), and Pgr_prim< G >::prim().
{
          auto v_root(graph.get_V(root_vertex));
          boost::prim_minimum_spanning_tree(
                       graph.graph,
                       &predecessors[0],
                       boost::distance_map(&distances[0]).
                       weight_map(get(&G::G_T_E::cost, graph.graph))
                       .root_vertex(v_root)
                       .visitor(prim_visitor(data)));
          std::vector< pgr_prim_t > results;
          double totalcost = 0;
          size_t size = data.size();
          pgr_prim_t tmp;
          tmp.root_vertex = root_vertex;
          tmp.node = root_vertex;
          tmp.edge = -1;
          tmp.cost = 0;
          tmp.agg_cost = totalcost;
          tmp.tree_cost = totalcost;
          results.push_back(tmp);
           // for root node
          for (size_t j = 1; j < size; j++){
              pgr_prim_t tmp;
              tmp.root_vertex = root_vertex;  // root_vertex
              auto start_node = graph.graph[predecessors[data[j]]].id;
              tmp.node = graph.graph[data[j]].id; // node
              auto v_sn(graph.get_V(start_node));
              auto v_en(graph.get_V(tmp.node));
              auto cost = distances[v_sn] - distances[v_en];
              auto edge_id =
                  graph.get_edge_id(v_sn, v_en, cost);
          totalcost += cost;
              tmp.edge = edge_id;         // edge_id
              tmp.cost = cost;            // cost
              tmp.agg_cost = aggegrateCost(v_root, data[j]); // agg_cost
              tmp.tree_cost = totalcost;      // tree_cost
              results.push_back(tmp);
          }
          return results;
     }
template<class G > std::vector< pgr_prim_t > Pgr_prim< G >::prim (G & graph, int64_t root_vertex, bool use_root)
Definition at line 206 of file pgr_prim.hpp.
References Pgr_prim< G >::clear(), Pgr_prim< G >::disconnectedPrim(), Pgr_prim< G >::generatePrim(), and Pgr_prim< G >::resize().
Referenced by pgr_prim().
{
         clear();
         resize(graph);
         if(!use_root){
              return disconnectedPrim(
                           graph);
          }
          if (!graph.has_vertex(root_vertex)){
              std::vector< pgr_prim_t > results;
              return results;
          }
         return generatePrim(
                              graph,
                              root_vertex);
 }
template<class G> void Pgr_prim< G >::resize (const G & graph) inline private
Definition at line 77 of file pgr_prim.hpp.
Referenced by Pgr_prim< G >::disconnectedPrim(), and Pgr_prim< G >::prim().
{
           predecessors.resize(graph.num_vertices());
           distances.resize(graph.num_vertices());
      }
Member Data Documentation
template<class G> std::vector< V > Pgr_prim< G >::data private
Definition at line 69 of file pgr_prim.hpp.
template<class G> std::vector< double > Pgr_prim< G >::distances private
Definition at line 68 of file pgr_prim.hpp.
template<class G> std::vector< V > Pgr_prim< G >::predecessors private
Definition at line 67 of file pgr_prim.hpp.
The documentation for this class was generated from the following file:
/home/vicky/pgrouting/pgrouting/pgrouting/include/mst/pgr_prim.hpp