PGROUTING: pgrouting::vrp::Dnode Class Reference
pgrouting::vrp::Dnode Class Reference
The Dnode class defines a the basic operations when data is a matrix.
#include "dnode.h"
Public Member Functions
double distance (const Base_node *) const
int64_t id () const
size_t idx () const
void reset_id (int64_t)
constructors
Dnode ()=default
Dnode (size_t id, int64_t original_id, double, double)
data constructor
to be or not to be
virtual bool operator== (const Base_node &rhs) const
Static Public Attributes
static Pgr_messages msg
Static Protected Attributes
static Pgr_pickDeliver * problem
Friends
std::ostream & operator<< (std::ostream &log, const Dnode &node)
Detailed Description
The Dnode class defines a the basic operations when data is a matrix.
currently needs the PD_problem
Definition at line 45 of file dnode.h.
Constructor & Destructor Documentation
Dnode() [1/2]
pgrouting::vrp::Dnode::Dnode () default
Dnode() [2/2]
pgrouting::vrp::Dnode::Dnode (size_t id, int64_t original_id, double , double)
data constructor
Definition at line 49 of file dnode.cpp.
     : Base_node(id, original_id) {
     }
Member Function Documentation
distance()
double pgrouting::vrp::Dnode::distance (const Base_node * other) const virtual
Implements pgrouting::vrp::Base_node.
Definition at line 42 of file dnode.cpp.
References pgrouting::tsp::Dmatrix::distance(), pgrouting::tsp::Dmatrix::get_index(), pgrouting::Identifier::id(), pgrouting::vrp::Pgr_pickDeliver::m_cost_matrix, and pgrouting::vrp::PD_problem::problem.
{
     return problem->m_cost_matrix.distance(
             problem->m_cost_matrix.get_index(id()),
             problem->m_cost_matrix.get_index(other->id()));
 }
id()
int64_t pgrouting::Identifier::id () const inherited
Definition at line 42 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by distance(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::vrp::Vehicle::is_phony(), pgrouting::vrp::operator<<(), pgrouting::operator<<(), pgrouting::vrp::Base_node::operator==(), pgrouting::vrp::Node::operator==(), pgrouting::vrp::Node::print(), pgrouting::vrp::Vehicle::tau(), and pgrouting::vrp::Vehicle::Vehicle().
                      {
     return m_id;
 }
idx()
size_t pgrouting::Identifier::idx () const inherited
Definition at line 37 of file identifier.cpp.
References pgrouting::Identifier::m_idx.
Referenced by pgrouting::vrp::Vehicle_pickDeliver::erase(), pgrouting::vrp::Vehicle::erase(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Vehicle_pickDeliver::has_order(), pgrouting::vrp::Vehicle::insert(), pgrouting::vrp::Vehicle_pickDeliver::insert(), pgrouting::vrp::operator<<(), pgrouting::operator<<(), pgrouting::vrp::Base_node::operator==(), pgrouting::vrp::Node::operator==(), pgrouting::vrp::Tw_node::operator==(), pgrouting::vrp::Node::print(), pgrouting::vrp::Vehicle_pickDeliver::push_back(), pgrouting::vrp::Vehicle_pickDeliver::push_front(), pgrouting::vrp::Vehicle_pickDeliver::semiLIFO(), pgrouting::vrp::Order::set_compatibles(), pgrouting::vrp::Solution::sort_by_id(), pgrouting::vrp::Vehicle::tau(), pgrouting::vrp::Tw_node::travel_time_to(), and pgrouting::vrp::Vehicle::Vehicle().
                       {
     return m_idx;
 }
operator==()
bool pgrouting::vrp::Base_node::operator== (const Base_node & rhs) const virtual inherited
Definition at line 43 of file base_node.cpp.
References pgrouting::Identifier::id(), and pgrouting::Identifier::idx().
{
     if (&rhs == this) return true;
     return
         (idx() == rhs.idx())
          && (id() == rhs.id());
 }
reset_id()
void pgrouting::Identifier::reset_id (int64_t _id) inherited
Definition at line 47 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Tw_node::Tw_node().
{
     m_id = _id;
 }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const Dnode & node) friend
Definition at line 34 of file dnode.cpp.
{
     log << node.id()
         << "(" << node.idx() << ")";
     return log;
 }
Member Data Documentation
msg
Pgr_messages pgrouting::vrp::PD_problem::msg static inherited
Definition at line 49 of file pd_problem.h.
Referenced by pgrouting::vrp::Fleet::add_vehicle(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), pgrouting::vrp::Optimize::delete_empty_truck(), do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), pgrouting::vrp::Vehicle_pickDeliver::do_while_feasable(), pgrouting::vrp::Initial_solution::do_while_foo(), pgrouting::vrp::Pgr_pickDeliver::get_postgres_result(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Fleet::is_fleet_ok(), pgrouting::vrp::Pgr_pickDeliver::nodesOK(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), pgrouting::vrp::Optimize::Optimize(), pgrouting::vrp::Pgr_pickDeliver::optimize(), pgrouting::vrp::PD_problem::PD_problem(), pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Optimize::save_if_best(), pgrouting::vrp::Solution::Solution(), pgrouting::vrp::Pgr_pickDeliver::solve(), pgrouting::vrp::Optimize::swap_order(), and pgrouting::vrp::Vehicle::Vehicle().
problem
Pgr_pickDeliver * pgrouting::vrp::PD_problem::problem static protected inherited
Definition at line 52 of file pd_problem.h.
Referenced by pgrouting::vrp::PD_Orders::add_order(), pgrouting::vrp::Fleet::add_vehicle(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), distance(), pgrouting::vrp::Solution::get_kind(), pgrouting::vrp::Pgr_pickDeliver::get_kind(), pgrouting::vrp::operator<<(), pgrouting::vrp::Tw_node::operator==(), and pgrouting::vrp::Tw_node::travel_time_to().
The documentation for this class was generated from the following files:
dnode.h
dnode.cpp