PGROUTING: delauny_input.c File Reference
delauny_input.c File Reference
#include "c_common/delauny_input.h"
#include "c_types/delauny_t.h"
#include "c_common/debug_macro.h"
#include "c_common/get_check_data.h"
#include "c_common/time_msg.h"
Functions
static void pgr_fetch_row (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info[4], Delauny_t *delauny)
void pgr_get_delauny (char *sql, Delauny_t **delauny, size_t *total_delauny)
bigint tid, bigint pid, float x, float y,
Function Documentation
pgr_fetch_row()
static void pgr_fetch_row (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info[4], Delauny_t * delauny) static
Definition at line 36 of file delauny_input.c.
References pgr_SPI_getBigInt(), pgr_SPI_getFloat8(), Delauny_t::pid, Delauny_t::tid, Delauny_t::x, and Delauny_t::y.
Referenced by pgr_get_delauny().
{
     delauny->tid = pgr_SPI_getBigInt(tuple, tupdesc, info[0]);
     delauny->pid = pgr_SPI_getBigInt(tuple, tupdesc, info[1]);
     delauny->x = pgr_SPI_getFloat8(tuple, tupdesc, info[2]);
     delauny->y = pgr_SPI_getFloat8(tuple, tupdesc, info[3]);
 }
pgr_get_delauny()
void pgr_get_delauny (char * sql, Delauny_t ** delauny, size_t * total_delauny)
bigint tid, bigint pid, float x, float y,
Definition at line 53 of file delauny_input.c.
References ANY_INTEGER, ANY_NUMERICAL, Column_info_t::colNumber, Column_info_t::eType, Column_info_t::name, PGR_DBG, pgr_fetch_column_info(), pgr_fetch_row(), pgr_SPI_cursor_open(), pgr_SPI_prepare(), Column_info_t::strict, time_msg(), and Column_info_t::type.
{
     clock_t start_t = clock();
     const int tuple_limit = 1000000;
     size_t total_tuples = 0;
     Column_info_t info[4];
     int i;
     for (i = 0; i < 4; ++i) {
         info[i].colNumber = -1;
         info[i].type = 0;
         info[i].strict = true;
         info[i].eType = ANY_NUMERICAL;
     }
     info[0].name = "tid";
     info[1].name = "pid";
     info[2].name = "x";
     info[3].name = "y";
     info[0].eType = ANY_INTEGER;
     info[1].eType = ANY_INTEGER;
     void *SPIplan;
     SPIplan = pgr_SPI_prepare(sql);
     Portal SPIportal;
     SPIportal = pgr_SPI_cursor_open(SPIplan);
     bool moredata = true;
     (*total_delauny) = total_tuples;
     while (moredata == true) {
         SPI_cursor_fetch(SPIportal, true, tuple_limit);
         if (total_tuples == 0)
             pgr_fetch_column_info(info, 4);
         size_t ntuples = SPI_processed;
         total_tuples += ntuples;
         if (ntuples > 0) {
             if ((*delauny) == NULL)
                 (*delauny) = (Delauny_t *)
                     palloc0(total_tuples * sizeof(Delauny_t));
             else
                 (*delauny) = (Delauny_t *)
                     repalloc((*delauny),
                             total_tuples * sizeof(Delauny_t));
             if ((*delauny) == NULL) {
                 elog(ERROR, "Out of memory");
             }
             SPITupleTable *tuptable = SPI_tuptable;
             TupleDesc tupdesc = SPI_tuptable->tupdesc;
             size_t t;
             for (t = 0; t < ntuples; t++) {
                 HeapTuple tuple = tuptable->vals[t];
                 pgr_fetch_row(&tuple, &tupdesc, info,
                         &(*delauny)[total_tuples - ntuples + t]);
             }
             SPI_freetuptable(tuptable);
         } else {
             moredata = false;
         }
     }
     SPI_cursor_close(SPIportal);
     if (total_tuples == 0) {
         (*total_delauny) = 0;
         return;
     }
     (*total_delauny) = total_tuples;
     PGR_DBG("%ld", total_tuples);
     time_msg(" calculating Delauny triangles:", start_t, clock());
 }