PGROUTING: e_report.h File Reference
e_report.h File Reference
Functions
Postgres ereport
Send notice or error to postgreSQL (cleans the char *)
From the C++ err_msg, log_msg, notice_msg are returned as a (char *),
Before exiting the C code the pointers need to be freed:
This task can be done when there is no error,
Call to ERROR, gives the control back to postgreSQL
leaves a leak
on C++ side, the message to be returned;
std::ostringstream log;
log << "the message";
*log_msg = pgr_msg(log.str().c_str());
when there is ERROR then postgreSQL takes over control The char* messages are cleared automaticalyy with pfree.
Warning
When error: Free all data not created with palloc before calling
void pgr_global_report (char *log_msg, char *notice_msg, char *error_msg)
notice & error
void pgr_notice (char *notice_msg)
notice with no hint
void pgr_notice2 (char *log_msg, char *notice_msg)
notice with hint
void pgr_error (char *error_msg)
error with no hint
void pgr_error2 (char *log_msg, char *error_msg)
error with hint
Function Documentation
pgr_error()
void pgr_error (char * error_msg)
error with no hint
if (err_msg) {
    pfree(<data>);
}
pgr_error(&error_msg);
precondition: before calling ereport
    assert(!*error_msg);
Definition at line 61 of file e_report.c.
References pgr_cstring2char(), and PGR_DBG.
                      {
     PGR_DBG("Returned error message = %s", err);
 #if 0
     char *error = NULL;
     if (*err_msg) {
         error = pgr_cstring2char(*err_msg);
         free(*err_msg);
     }
 #endif
     if (err) {
         ereport(ERROR,
                 (errmsg_internal("Unexpected"),
                  errhint("%s", err)));
     }
 }
pgr_error2()
void pgr_error2 (char * log_msg, char * error_msg)
error with hint
if (err_msg) {
    pfree(<data>);
}
pgr_error(&log_msg, &error_msg);
precondition: before calling ereport
    assert(!*log_msg);
    assert(!*error_msg);
Definition at line 79 of file e_report.c.
References PGR_DBG.
                    {
     PGR_DBG("Returned log message = %s", log);
     PGR_DBG("Returned error message = %s", err);
     if (err) {
         ereport(ERROR,
                 (errmsg_internal("%s", err),
                  errhint("%s", log)));
     }
 }
pgr_global_report()
void pgr_global_report (char * log_msg, char * notice_msg, char * error_msg)
notice & error
pgr_notice(&log_msg, &notice_msg, &error_msg);
precondition: before calling ereport
    assert(!*log_msg);
    assert(!*notice_msg);
    assert(!*error_msg);
Definition at line 93 of file e_report.c.
Referenced by compute(), compute_trsp(), and process().
                    {
     if (!notice && log) {
         ereport(DEBUG1,
                 (errmsg_internal("%s", log)));
     }
     if (notice) {
         if (log) {
             ereport(NOTICE,
                     (errmsg_internal("%s", notice),
                      errhint("%s", log)));
         } else {
             ereport(NOTICE,
                     (errmsg_internal("%s", notice)));
         }
     }
     if (err) {
         if (log) {
             ereport(ERROR,
                     (errmsg_internal("%s", err),
                      errhint("%s", log)));
         } else {
             ereport(ERROR,
                     (errmsg_internal("%s", err)));
         }
     }
 }
pgr_notice()
void pgr_notice (char * notice_msg)
notice with no hint
pgr_notice(&log_msg, &notice_msg);
precondition: before calling ereport
    assert(!log_msg);
    assert(!notice_msg);
Definition at line 31 of file e_report.c.
References PGR_DBG.
Referenced by pgr_notice2().
                       {
     PGR_DBG("Returned notice message = %s", notice);
     if (notice) {
         ereport(NOTICE,
                 (errmsg("%s", notice)));
     }
 }
pgr_notice2()
void pgr_notice2 (char * log_msg, char * notice_msg)
notice with hint
pgr_notice(&log_msg, &notice_msg);
precondition: before calling ereport
    assert(!log_msg);
    assert(!notice_msg);
Definition at line 42 of file e_report.c.
References PGR_DBG, and pgr_notice().
                       {
     PGR_DBG("Returned log message = %s", log);
     PGR_DBG("Returned notice message = %s", notice);
     if (log) {
         pgr_notice(notice);
         return;
     }
     if (notice) {
         ereport(NOTICE,
                 (errmsg("%s", notice),
                  errhint("%s", log)));
     }
 }