PGROUTING: floydWarshall_driver.cpp File Reference
floydWarshall_driver.cpp File Reference
#include "drivers/allpairs/floydWarshall_driver.h"
#include <sstream>
#include <deque>
#include <vector>
#include "allpairs/pgr_allpairs.hpp"
#include "cpp_common/pgr_assert.h"
Functions
void do_pgr_floydWarshall (pgr_edge_t *data_edges, size_t total_tuples, bool directedFlag, Matrix_cell_t **return_tuples, size_t *return_count, char **log_msg, char **err_msg)
Function Documentation
do_pgr_floydWarshall()
void do_pgr_floydWarshall (pgr_edge_t * data_edges, size_t total_tuples, bool directedFlag, Matrix_cell_t ** return_tuples, size_t * return_count, char ** log_msg, char ** err_msg)
Definition at line 42 of file floydWarshall_driver.cpp.
References DIRECTED, pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::insert_edges(), pgassert, pgr_floydWarshall(), pgr_free(), pgr_msg(), UNDIRECTED, and AssertFailedException::what().
Referenced by process().
{
     std::ostringstream log;
     std::ostringstream err;
     try {
         pgassert(!(*log_msg));
         pgassert(!(*err_msg));
         pgassert(!(*return_tuples));
         pgassert(*return_count == 0);
         graphType gType = directedFlag? DIRECTED: UNDIRECTED;
         if (directedFlag) {
             log << "Processing Directed graph\n";
             pgrouting::DirectedGraph digraph(gType);
             digraph.insert_edges(data_edges, total_tuples);
             pgr_floydWarshall(digraph, *return_count, return_tuples);
         } else {
             log << "Processing Undirected graph\n";
             pgrouting::UndirectedGraph undigraph(gType);
             undigraph.insert_edges(data_edges, total_tuples);
             pgr_floydWarshall(undigraph, *return_count, return_tuples);
         }
         if (*return_count == 0) {
             err <<  "No result generated, report this error\n";
             *err_msg = pgr_msg(err.str().c_str());
             *return_tuples = NULL;
             *return_count = 0;
             return;
         }
         *log_msg = log.str().empty()?
             *log_msg :
             pgr_msg(log.str().c_str());
     } catch (AssertFailedException &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch (std::exception &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch(...) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << "Caught unknown exception!";
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     }
 }