PGROUTING: get_new_queries.h File Reference
get_new_queries.h File Reference
Functions
char estimate_drivingSide (char driving_side)
void get_new_queries (char *edges_sql, char *points_sql, char **edges_of_points_query, char **edges_no_points_query)
Function Documentation
estimate_drivingSide()
char estimate_drivingSide (char driving_side)
Definition at line 36 of file get_new_queries.cpp.
Referenced by process().
{
     char d_side = static_cast<char>(tolower(driving_side));
     if (!((d_side == 'r')
                 || (d_side == 'l'))) {
         d_side = 'b';
     }
     return d_side;
 }
get_new_queries()
void get_new_queries (char * edges_sql, char * points_sql, char ** edges_of_points_query, char ** edges_no_points_query)
Definition at line 46 of file get_new_queries.cpp.
References pgr_msg().
Referenced by process().
{
     std::ostringstream edges_of_points_sql;
     std::ostringstream edges_no_points_sql;
     edges_of_points_sql << "WITH "
         << " edges AS (" << edges_sql << "), "
         << " points AS (" << points_sql << ")"
         << " SELECT DISTINCT edges.* FROM edges JOIN points ON (id = edge_id)";
     *edges_of_points_query = pgr_msg(edges_of_points_sql.str().c_str());
     edges_no_points_sql << "WITH "
         << " edges AS (" << edges_sql << "), "
         << " points AS (" << points_sql << ")"
         << " SELECT edges.*"
         << " FROM edges"
         << " WHERE NOT EXISTS (SELECT edge_id FROM points WHERE id = edge_id)";
     *edges_no_points_query = pgr_msg(edges_no_points_sql.str().c_str());
 }