PGROUTING: get_check_data.c File Reference
get_check_data.c File Reference
#include <stdbool.h>
#include "c_common/postgres_connection.h"
#include "c_common/get_check_data.h"
#include "c_common/arrays_input.h"
#include "catalog/pg_type.h"
#include "c_common/debug_macro.h"
Functions
bool column_found (int colNumber)
Function will check whether the colNumber represent any specific column or NULL (SPI_ERROR_NOATTRIBUTE).
static bool fetch_column_info (Column_info_t *info)
void pgr_check_any_integer_type (Column_info_t info)
The function check whether column type is ANY-INTEGER or not.
void pgr_check_any_integerarray_type (Column_info_t info)
The function check whether column type is ANY-INTEGER-ARRAY or not.
void pgr_check_any_numerical_type (Column_info_t info)
The function check whether column type is ANY-NUMERICAL.
void pgr_check_char_type (Column_info_t info)
The function check whether column type is CHAR or not.
void pgr_check_text_type (Column_info_t info)
The function check whether column type is TEXT or not.
void pgr_fetch_column_info (Column_info_t info[], int info_size)
Function tells expected type of each column and then check the correspondence type of each column.
int64_t pgr_SPI_getBigInt (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info)
Function returns the value of specified column in integer type.
int64_t * pgr_SPI_getBigIntArr (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, uint64_t *the_size)
Function returns the values of specified columns in array.
char pgr_SPI_getChar (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, bool strict, char default_value)
Function return the value of specified column in char type.
double pgr_SPI_getFloat8 (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info)
Function returns the value of specified column in double type.
char * pgr_SPI_getText (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info)
under development
Function Documentation
column_found()
bool column_found (int colNumber)
Function will check whether the colNumber represent any specific column or NULL (SPI_ERROR_NOATTRIBUTE).
Parameters
[in] colNumber Column number (count starts at 1).
Returns
TRUE when colNumber exist. FALSE when colNumber was not found.
Definition at line 36 of file get_check_data.c.
Referenced by fetch_basic_edge(), fetch_column_info(), fetch_costFlow_edge(), fetch_edge(), fetch_edge_with_xy(), fetch_pd_orders(), fetch_point(), fetch_restriction(), fetch_vehicles(), and pgr_fetch_row().
{
     /*
      * [SPI_ERROR_NOATTRIBUTE](https://doxygen.postgresql.org/spi_8h.html#ac1512d8aaa23c2d57bb0d1eb8f453ee2)
      */
     return !(colNumber == SPI_ERROR_NOATTRIBUTE);
 }
fetch_column_info()
static bool fetch_column_info (Column_info_t * info) static
Definition at line 45 of file get_check_data.c.
References Column_info_t::colNumber, column_found(), Column_info_t::name, PGR_DBG, Column_info_t::strict, and Column_info_t::type.
Referenced by pgr_fetch_column_info().
{
 /* TODO(vicky) Remove unused code */
 #if 0
     PGR_DBG("Fetching column info of %s", info->name);
 #endif
     /*
      * [SPI_fnumber](https://www.postgresql.org/docs/8.2/static/spi-spi-fnumber.html)
      */
     info->colNumber =  SPI_fnumber(SPI_tuptable->tupdesc, info->name);
     if (info->strict && !column_found(info->colNumber)) {
         elog(ERROR, "Column '%s' not Found", info->name);
     }
     if (column_found(info->colNumber)) {
         /*
          * [SPI_gettypeid](https://www.postgresql.org/docs/9.1/static/spi-spi-gettypeid.html)
          */
         (info->type) = SPI_gettypeid(SPI_tuptable->tupdesc, (info->colNumber));
         PGR_DBG("%s %ld", info->name, info->type);
         if (SPI_result == SPI_ERROR_NOATTRIBUTE) {
             elog(ERROR, "Type of column '%s' not Found", info->name);
         }
 /* TODO(vicky) Remove unused code */
 #if 0
         PGR_DBG("Column %s found: %lu", info->name, info->type);
 #endif
         return true;
     }
     PGR_DBG("Column %s not found", info->name);
     return false;
 }
pgr_check_any_integer_type()
void pgr_check_any_integer_type (Column_info_t info)
The function check whether column type is ANY-INTEGER or not.
Where ANY-INTEGER is SQL type: SMALLINT, INTEGER, BIGINT
Parameters
[in] info contain column information.
Exceptions
ERROR Unexpected Column type. Expected column type is ANY-INTEGER.
Definition at line 128 of file get_check_data.c.
References Column_info_t::name, and Column_info_t::type.
Referenced by pgr_fetch_column_info().
{
     if (!(info.type == INT2OID
                 || info.type == INT4OID
                 || info.type == INT8OID)) {
         elog(ERROR,
                 "Unexpected Column '%s' type. Expected ANY-INTEGER",
                 info.name);
     }
 }
pgr_check_any_integerarray_type()
void pgr_check_any_integerarray_type (Column_info_t info)
The function check whether column type is ANY-INTEGER-ARRAY or not.
Where ANY-INTEGER-ARRAY is SQL type: SMALLINT[], INTEGER[], BIGINT[]
Parameters
[in] info contain column information.
Exceptions
ERROR Unexpected Column type. Expected column type is ANY-INTEGER-ARRAY.
Definition at line 139 of file get_check_data.c.
References Column_info_t::name, and Column_info_t::type.
Referenced by pgr_fetch_column_info().
{
     if (!(info.type == INT2ARRAYOID
                 || info.type == INT4ARRAYOID
                 || info.type == 1016)) {
         elog(ERROR,
                 "Unexpected Column '%s' type. Expected ANY-INTEGER-ARRAY",
                 info.name);
     }
 }
pgr_check_any_numerical_type()
void pgr_check_any_numerical_type (Column_info_t info)
The function check whether column type is ANY-NUMERICAL.
Where ANY-NUMERICAL is SQL type: SMALLINT, INTEGER, BIGINT, REAL, FLOAT
Parameters
[in] info contain column information.
Exceptions
ERROR Unexpected Column type. Expected column type is ANY-NUMERICAL.
Definition at line 149 of file get_check_data.c.
References Column_info_t::name, and Column_info_t::type.
Referenced by pgr_fetch_column_info().
{
     if (!(info.type == INT2OID
                 || info.type == INT4OID
                 || info.type == INT8OID
                 || info.type == FLOAT4OID
                 || info.type == FLOAT8OID
                 || info.type == NUMERICOID)) {
         elog(ERROR,
                 "Unexpected Column '%s' type. Expected ANY-NUMERICAL",
                 info.name);
     }
 }
pgr_check_char_type()
void pgr_check_char_type (Column_info_t info)
The function check whether column type is CHAR or not.
Where CHAR is SQL type: CHARACTER
Parameters
[in] info contain column information.
Exceptions
ERROR Unexpected Column type. Expected column type is CHAR.
Definition at line 114 of file get_check_data.c.
References Column_info_t::name, and Column_info_t::type.
Referenced by pgr_fetch_column_info().
{
     if (!(info.type == BPCHAROID)) {
         elog(ERROR, "Unexpected Column '%s' type. Expected CHAR", info.name);
     }
 }
pgr_check_text_type()
void pgr_check_text_type (Column_info_t info)
The function check whether column type is TEXT or not.
Where TEXT is SQL type: TEXT
Parameters
[in] info contain column information.
Exceptions
ERROR Unexpected Column type. Expected column type is TEXT.
Definition at line 121 of file get_check_data.c.
References Column_info_t::name, and Column_info_t::type.
Referenced by pgr_fetch_column_info().
{
     if (!(info.type == TEXTOID)) {
         elog(ERROR, "Unexpected Column '%s' type. Expected TEXT", info.name);
     }
 }
pgr_fetch_column_info()
void pgr_fetch_column_info (Column_info_t info[], int info_size)
Function tells expected type of each column and then check the correspondence type of each column.
Parameters
[in] info[] contain one or more column information.
[in] info_size number of columns.
Exceptions
ERROR Unknown type of column.
Returns
NULL is always returned.
Definition at line 79 of file get_check_data.c.
References ANY_INTEGER, ANY_INTEGER_ARRAY, ANY_NUMERICAL, CHAR1, fetch_column_info(), pgr_check_any_integer_type(), pgr_check_any_integerarray_type(), pgr_check_any_numerical_type(), pgr_check_char_type(), pgr_check_text_type(), and TEXT.
Referenced by get_edges_5_columns(), get_edges_9_columns(), get_edges_basic(), get_edges_costFlow(), get_edges_flow(), pgr_get_coordinates(), pgr_get_delauny(), pgr_get_matrixRows(), pgr_get_pd_orders_general(), pgr_get_points(), pgr_get_restrictions(), pgr_get_vehicles_general(), and pgr_point_input().
{
     int i;
     for (i = 0; i < info_size; ++i) {
         if (fetch_column_info(&info[i])) {
             switch (info[i].eType) {
                 case ANY_INTEGER:
                     pgr_check_any_integer_type(info[i]);
                     break;
                 case ANY_NUMERICAL:
                     pgr_check_any_numerical_type(info[i]);
                     break;
                 case TEXT:
                     pgr_check_text_type(info[i]);
                     break;
                 case CHAR1:
                     pgr_check_char_type(info[i]);
                     break;
                 case ANY_INTEGER_ARRAY:
                     pgr_check_any_integerarray_type(info[i]);
                     break;
                 default:
                     elog(ERROR, "Unknown type of column %s", info[i].name);
             }
         }
     }
 }
pgr_SPI_getBigInt()
int64_t pgr_SPI_getBigInt (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info)
Function returns the value of specified column in integer type.
Parameters
[in] tuple input row to be examined.
[in] tupdesc input row description.
[in] info contain column information.
Exceptions
ERROR Unexpected Column type. Expected column type is ANY-INTEGER.
ERROR When value of column is NULL.
Returns
Integer type of column value is returned.
Definition at line 217 of file get_check_data.c.
References Column_info_t::colNumber, Column_info_t::name, PGR_DBG, and Column_info_t::type.
Referenced by fetch_basic_edge(), fetch_costFlow_edge(), fetch_edge(), fetch_edge_with_xy(), fetch_pd_orders(), fetch_point(), fetch_restriction(), fetch_vehicles(), and pgr_fetch_row().
{
     Datum binval;
     bool isnull;
     int64_t value = 0;
     binval = SPI_getbinval(*tuple, *tupdesc, info.colNumber, &isnull);
     if (isnull)
         elog(ERROR, "Unexpected Null value in column %s", info.name);
     switch (info.type) {
         case INT2OID:
             value = (int64_t) DatumGetInt16(binval);
             break;
         case INT4OID:
             value = (int64_t) DatumGetInt32(binval);
             break;
         case INT8OID:
             value = DatumGetInt64(binval);
             break;
         default:
             elog(ERROR,
                     "Unexpected Column type of %s. Expected ANY-INTEGER",
                     info.name);
     }
 /* TODO(vicky) Remove unused code */
 #if 0
     PGR_DBG("Variable: %s Value: %ld", info.name, value);
 #endif
     return value;
 }
pgr_SPI_getBigIntArr()
int64_t* pgr_SPI_getBigIntArr (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, uint64_t * the_size)
Function returns the values of specified columns in array.
Parameters
[in] tuple input row to be examined.
[in] tupdesc input row description.
[in] info contain column information.
[out] the_size number of element in array.
Exceptions
ERROR No elements found in ARRAY.
ERROR Unexpected Column type. Expected column type is ANY-INTEGER-ARRAY.
ERROR NULL value found in Array.
Returns
Array of columns value is returned.
Definition at line 197 of file get_check_data.c.
References Column_info_t::colNumber, and pgr_get_bigIntArray().
Referenced by fetch_restriction().
{
     bool is_null = false;
     Datum raw_array = SPI_getbinval(*tuple, *tupdesc, info.colNumber, &is_null);
     /*
     * [DatumGetArrayTypeP](https://doxygen.postgresql.org/array_8h.html#aa1b8e77c103863862e06a7b7c07ec532)
     * [pgr_get_bigIntArray](http://docs.pgrouting.org/doxy/2.2/arrays__input_8c_source.html)
     */
     ArrayType *pg_array = DatumGetArrayTypeP(raw_array);
     return (int64_t*) pgr_get_bigIntArray(the_size, pg_array);
 }
pgr_SPI_getChar()
char pgr_SPI_getChar (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, bool strict, char default_value)
Function return the value of specified column in char type.
Parameters
[in] tuple input row to be examined.
[in] tupdesc input row description.
[in] info contain column information.
[in] strict boolean value of strict.
[in] default_value returned when column contain NULL value.
Exceptions
ERROR Unexpected Column type. Expected column type is CHAR.
ERROR When value of column is NULL.
Returns
Char type of column value is returned.
Definition at line 171 of file get_check_data.c.
References Column_info_t::colNumber, Column_info_t::name, and Column_info_t::type.
Referenced by fetch_point().
{
     Datum binval;
     bool isNull;
     char value = default_value;
     binval = SPI_getbinval(*tuple, *tupdesc, info.colNumber, &isNull);
     if (!(info.type == BPCHAROID)) {
         elog(ERROR, "Unexpected Column type of %s. Expected CHAR", info.name);
     }
     if (!isNull) {
         value =  ((char*)binval)[1];
     } else {
         if (strict) {
             elog(ERROR, "Unexpected Null value in column %s", info.name);
         }
         value = default_value;
     }
     return value;
 }
pgr_SPI_getFloat8()
double pgr_SPI_getFloat8 (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info)
Function returns the value of specified column in double type.
Parameters
[in] tuple input row to be examined.
[in] tupdesc input row description.
[in] info contain column information.
Exceptions
ERROR Unexpected Column type. Expected column type is ANY-NUMERICAL.
ERROR When value of column is NULL.
Returns
Double type of column value is returned.
Definition at line 247 of file get_check_data.c.
References Column_info_t::colNumber, Column_info_t::name, PGR_DBG, and Column_info_t::type.
Referenced by fetch_basic_edge(), fetch_costFlow_edge(), fetch_edge(), fetch_edge_with_xy(), fetch_pd_orders(), fetch_point(), fetch_restriction(), fetch_vehicles(), and pgr_fetch_row().
{
     Datum binval;
     bool isnull = false;
     double value = 0.0;
     binval = SPI_getbinval(*tuple, *tupdesc, info.colNumber, &isnull);
     if (isnull)
         elog(ERROR, "Unexpected Null value in column %s", info.name);
     switch (info.type) {
         case INT2OID:
             value = (double) DatumGetInt16(binval);
             break;
         case INT4OID:
             value = (double) DatumGetInt32(binval);
             break;
         case INT8OID:
             value = (double) DatumGetInt64(binval);
             break;
         case FLOAT4OID:
             value = (double) DatumGetFloat4(binval);
             break;
         case FLOAT8OID:
             value = DatumGetFloat8(binval);
             break;
         case NUMERICOID:
              /* Note: out-of-range values will be clamped to +-HUGE_VAL */
              value = (double) DatumGetFloat8(DirectFunctionCall1(numeric_float8_no_overflow, binval));
              break;
         default:
             elog(ERROR,
                     "Unexpected Column type of %s. Expected ANY-NUMERICAL",
                     info.name);
     }
 /* TODO(vicky) Remove unused code */
 #if 0
     PGR_DBG("Variable: %s Value: %.20f", info.name, value);
 #endif
     return value;
 }
pgr_SPI_getText()
char* pgr_SPI_getText (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info)
under development
Function returns the string representation of the value of specified column.
Definition at line 294 of file get_check_data.c.
References Column_info_t::colNumber.
{
     return DatumGetCString(SPI_getvalue(*tuple, *tupdesc, info.colNumber));
 }