PGROUTING: lineGraphFull.c File Reference
lineGraphFull.c File Reference
#include <stdbool.h>
#include "c_common/postgres_connection.h"
#include "c_common/debug_macro.h"
#include "c_common/e_report.h"
#include "c_common/time_msg.h"
#include "c_common/edges_input.h"
#include "drivers/lineGraph/lineGraphFull_driver.h"
Functions
PGDLLEXPORT Datum _pgr_linegraphfull (PG_FUNCTION_ARGS)
PG_FUNCTION_INFO_V1 (_pgr_linegraphfull)
static void process (char *edges_sql, Line_graph_full_rt **result_tuples, size_t *result_count)
Function Documentation
_pgr_linegraphfull()
PGDLLEXPORT Datum _pgr_linegraphfull (PG_FUNCTION_ARGS)
Definition at line 101 of file lineGraphFull.c.
References PGR_DBG, and process().
{
     FuncCallContext     *funcctx;
     TupleDesc           tuple_desc;
     Line_graph_full_rt  *result_tuples = NULL;
     size_t result_count = 0;
     if (SRF_IS_FIRSTCALL()) {
         MemoryContext   oldcontext;
         funcctx = SRF_FIRSTCALL_INIT();
         oldcontext = MemoryContextSwitchTo(funcctx->multi_call_memory_ctx);
         PGR_DBG("Calling process");
         process(text_to_cstring(PG_GETARG_TEXT_P(0)),
                 &result_tuples,
                 &result_count);
 #if PGSQL_VERSION > 95
         funcctx->max_calls = result_count;
 #else
         funcctx->max_calls = (uint32_t)result_count;
 #endif
         funcctx->user_fctx = result_tuples;
         if (get_call_result_type(fcinfo, NULL, &tuple_desc)
                 != TYPEFUNC_COMPOSITE) {
             ereport(ERROR,
                     (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
                      errmsg("function returning record called in context "
                          "that cannot accept type record")));
         }
         funcctx->tuple_desc = tuple_desc;
         MemoryContextSwitchTo(oldcontext);
     }
     funcctx = SRF_PERCALL_SETUP();
     tuple_desc = funcctx->tuple_desc;
     result_tuples = (Line_graph_full_rt*) funcctx->user_fctx;
     if (funcctx->call_cntr < funcctx->max_calls) {
         HeapTuple    tuple;
         Datum        result;
         Datum        *values;
         bool*        nulls;
         values = palloc(5 * sizeof(Datum));
         nulls = palloc(5 * sizeof(bool));
         size_t i;
         for (i = 0; i < 5; ++i) {
             nulls[i] = false;
         }
         size_t c_cntr = funcctx->call_cntr;
         values[0] = Int32GetDatum(c_cntr + 1);
         values[1] = Int64GetDatum(result_tuples[c_cntr].source);
         values[2] = Int64GetDatum(result_tuples[c_cntr].target);
         values[3] = Float8GetDatum(result_tuples[c_cntr].cost);
         values[4] = Int64GetDatum(result_tuples[c_cntr].edge);
         tuple = heap_form_tuple(tuple_desc, values, nulls);
         result = HeapTupleGetDatum(tuple);
         SRF_RETURN_NEXT(funcctx, result);
     } else {
         PGR_DBG("Clean up code");
         SRF_RETURN_DONE(funcctx);
     }
 }
PG_FUNCTION_INFO_V1()
PG_FUNCTION_INFO_V1 (_pgr_linegraphfull)
process()
static void process (char * edges_sql, Line_graph_full_rt ** result_tuples, size_t * result_count) static
Definition at line 44 of file lineGraphFull.c.
References do_pgr_lineGraphFull(), PGR_DBG, pgr_get_edges(), pgr_global_report(), pgr_SPI_connect(), pgr_SPI_finish(), and time_msg().
Referenced by _pgr_linegraphfull().
{
     PGR_DBG("\nSQL QUERY: %s\n", edges_sql);
     PGR_DBG("\nDirectedGraph\n");
     pgr_SPI_connect();
     (*result_tuples) = NULL;
     (*result_count) = 0;
     PGR_DBG("Load data");
     pgr_edge_t *edges = NULL;
     size_t total_edges = 0;
     pgr_get_edges(edges_sql, &edges, &total_edges);
     PGR_DBG("Total %ld edges in query:", total_edges);
     if (total_edges == 0) {
         PGR_DBG("No edges found");
         pgr_SPI_finish();
         return;
     }
     PGR_DBG("Starting processing");
     clock_t start_t = clock();
     char *log_msg = NULL;
     char *notice_msg = NULL;
     char *err_msg = NULL;
     do_pgr_lineGraphFull(
             edges,
             total_edges,
             result_tuples,
             result_count,
             &log_msg,
             &notice_msg,
             &err_msg);
     time_msg(" processing pgr_lineGraphFull", start_t, clock());
     PGR_DBG("Returning %ld tuples", *result_count);
     if (err_msg) {
         if (*result_tuples) pfree(*result_tuples);
     }
     pgr_global_report(log_msg, notice_msg, err_msg);
     if (edges) pfree(edges);
     if (log_msg) pfree(log_msg);
     if (notice_msg) pfree(notice_msg);
     if (err_msg) pfree(err_msg);
     pgr_SPI_finish();
 }