PGROUTING: pgrouting::vrp Namespace Reference
pgrouting::vrp Namespace Reference
Classes
class Base_node
The Base_node class defines the operations that can be performed in a 2D node.
class Dnode
The Dnode class defines a the basic operations when data is a matrix.
class Fleet
class Initial_solution
class Node
The Node class defines a point in 2D space with an id.
class Optimize
class Order
class PD_Orders
class PD_problem
class Pgr_pickDeliver
class Solution
class Swap_bk
class Swap_info
class Tw_node
Extends the Node class to create a Node with time window attributes.
class Vehicle
Vehicle with time windows.
class Vehicle_node
Extend Tw_node to evaluate the vehicle at node level.
class Vehicle_pickDeliver
Enumerations
enum Initials_code {
OneTruck, OnePerTruck, FrontTruck, BackTruck,
BestInsert, BestBack, BestFront, OneDepot
}
Different kinds to insert an order into the vehicle.
Functions
bool operator< (const Vehicle &lhs, const Vehicle &rhs)
std::ostream & operator<< (std::ostream &os, const Base_node &node)
std::ostream & operator<< (std::ostream &log, const Dnode &node)
std::ostream & operator<< (std::ostream &log, const Swap_info &d)
std::ostream & operator<< (std::ostream &log, const Node &node)
std::ostream & operator<< (std::ostream &log, const Order &order)
std::ostream & operator<< (std::ostream &log, const Swap_bk &data)
std::ostream & operator<< (std::ostream &log, const Vehicle_node &v)
std::ostream & operator<< (std::ostream &log, const Solution &solution)
std::ostream & operator<< (std::ostream &log, const Tw_node &n)
Print the contents of a Twnode object.
std::ostream & operator<< (std::ostream &log, const Fleet &f)
std::ostream & operator<< (std::ostream &log, const Vehicle &v)
Enumeration Type Documentation
Initials_code
enum pgrouting::vrp::Initials_code
Different kinds to insert an order into the vehicle.
Enumerator
OneTruck
OnePerTruck
All orders in one truck.
FrontTruck
One Order per truck.
BackTruck
Insetion at the front of the truck.
BestInsert
Insetion at the back of the truck.
BestBack
Best place to insert Order.
BestFront
Push back order that allows more orders to be inserted at the back.
OneDepot
Push front order that allows more orders to be inserted at the front.
Pick at front, drop at back, OneDepot for all vehicles
Definition at line 36 of file initials_code.h.
                    {
     OneTruck,
     OnePerTruck,
     FrontTruck,
     BackTruck,
     BestInsert,
     BestBack,
     BestFront,
     OneDepot
 };
Function Documentation
operator<()
bool pgrouting::vrp::operator< (const Vehicle & lhs, const Vehicle & rhs)
Definition at line 612 of file vehicle.cpp.
References pgrouting::vrp::Vehicle::invariant(), and pgrouting::vrp::Vehicle::m_path.
{
     lhs.invariant();
     rhs.invariant();
     if (lhs.m_path.size() < rhs.m_path.size()) return true;
     /* here because sizes are equal */
     if (lhs.m_path.back().total_travel_time()
             < rhs.m_path.back().total_travel_time()) return true;
     return false;
 }
operator<<() [1/11]
std::ostream& pgrouting::vrp::operator<< (std::ostream & os, const Base_node & node)
Definition at line 33 of file base_node.cpp.
References pgrouting::Identifier::id(), and pgrouting::Identifier::idx().
{
     return os << node.id()
         << "(" << node.idx() << ")";
 }
operator<<() [2/11]
std::ostream& pgrouting::vrp::operator<< (std::ostream & log, const Dnode & node)
Definition at line 34 of file dnode.cpp.
References pgrouting::Identifier::id(), and pgrouting::Identifier::idx().
{
     log << node.id()
         << "(" << node.idx() << ")";
     return log;
 }
operator<<() [3/11]
std::ostream& pgrouting::vrp::operator<< (std::ostream & log, const Swap_info & d)
Definition at line 47 of file book_keeping.cpp.
References pgrouting::vrp::Swap_info::estimated_delta, pgrouting::vrp::Swap_info::from_order, pgrouting::vrp::Swap_info::from_truck, pgrouting::vrp::Vehicle_pickDeliver::orders(), pgrouting::vrp::Vehicle::tau(), pgrouting::vrp::Swap_info::to_order, and pgrouting::vrp::Swap_info::to_truck.
{
     log << "\n" << d.from_truck.tau() << " --> "
         << d.from_order
         << "("
         << d.from_truck.orders()[d.from_order].pickup().id()
         << ")"
         << "\n" << d.to_truck.tau() << " --> "
         << d.to_order
         << "("
         << d.to_truck.orders()[d.to_order].pickup().id()
         << ")"
         << "\n" << "delta = " << d.estimated_delta;
     return log;
 }
operator<<() [4/11]
std::ostream& pgrouting::vrp::operator<< (std::ostream & log, const Node & node)
Definition at line 49 of file node.cpp.
References pgrouting::vrp::Node::print().
{
     node.print(log);
     return log;
 }
operator<<() [5/11]
std::ostream& pgrouting::vrp::operator<< (std::ostream & log, const Order & order)
Definition at line 55 of file order.cpp.
References pgrouting::vrp::Order::delivery(), pgrouting::Identifier::idx(), pgrouting::vrp::Order::m_compatibleI, pgrouting::vrp::Order::m_compatibleJ, pgrouting::vrp::Order::pickup(), Identifiers< T >::size(), and pgrouting::vrp::Tw_node::travel_time_to().
{
     log << "\n\nOrder "
         << static_cast<Identifier>(order) << ": \n"
         << "\tPickup: " << order.pickup() << "\n"
         << "\tDelivery: " << order.delivery() << "\n\n"
         << "\tTravel time: "
         << order.pickup().travel_time_to(order.delivery(), 1);
     log << "\nThere are | {I}| = "
         << order.m_compatibleI.size()
         << " -> order(" << order.idx()
         << ") -> | {J}| = " << order.m_compatibleJ.size()
         << "\n\n {";
     for (const auto o : order.m_compatibleI) {
         log << o << ", ";
     }
     log << "} -> " << order.idx() << " -> {";
     for (const auto o : order.m_compatibleJ) {
         log << o << ", ";
     }
     log << "}";
     return log;
 }
operator<<() [6/11]
std::ostream& pgrouting::vrp::operator<< (std::ostream & log, const Swap_bk & data)
Definition at line 63 of file book_keeping.cpp.
References pgrouting::vrp::Swap_bk::m_swaps.
{
     auto q = data.m_swaps;
     while (!q.empty()) {
         log << q.top() << " ";
         q.pop();
     }
     log << '\n';
     return log;
 }
operator<<() [7/11]
std::ostream& pgrouting::vrp::operator<< (std::ostream & log, const Vehicle_node & v)
Definition at line 101 of file vehicle_node.cpp.
References pgrouting::vrp::Vehicle_node::arrival_time(), pgrouting::vrp::Vehicle_node::cargo(), pgrouting::vrp::Vehicle_node::cvTot(), pgrouting::vrp::Vehicle_node::departure_time(), pgrouting::vrp::Vehicle_node::has_twv(), pgrouting::vrp::Tw_node::service_time(), pgrouting::vrp::Vehicle_node::travel_time(), pgrouting::vrp::Vehicle_node::twvTot(), and pgrouting::vrp::Vehicle_node::wait_time().
{
     log << static_cast<const Tw_node&>(v)
         << " twv = " << v.has_twv()
         << ", twvTot = " << v.twvTot()
         << ", cvTot = " << v.cvTot()
         << ", cargo = " << v.cargo()
         << ", travel_time = " << v.travel_time()
         << ", arrival_time = " << v.arrival_time()
         << ", wait_time = " << v.wait_time()
         << ", service_time = " << v.service_time()
         << ", departure_time = " << v.departure_time();
     return log;
 }
operator<<() [8/11]
std::ostream& pgrouting::vrp::operator<< (std::ostream & log, const Solution & solution)
Definition at line 175 of file solution.cpp.
References pgrouting::vrp::Solution::fleet, and pgrouting::vrp::Solution::tau().
{
     for (const auto vehicle : solution.fleet) {
         log << vehicle;
     }
     log << "\n SOLUTION:\n\n "
         << solution.tau();
     return log;
 }
operator<<() [9/11]
std::ostream& pgrouting::vrp::operator<< (std::ostream & log, const Tw_node & n)
Print the contents of a Twnode object.
Definition at line 272 of file tw_node.cpp.
References pgrouting::Identifier::idx(), pgrouting::vrp::Pgr_pickDeliver::m_base_nodes, pgrouting::vrp::Tw_node::m_closes, pgrouting::vrp::Tw_node::m_demand, pgrouting::vrp::Tw_node::m_opens, pgrouting::vrp::Tw_node::m_service_time, pgrouting::vrp::PD_problem::problem, and pgrouting::vrp::Tw_node::type_str().
{
     log << static_cast<const Node&>(
             *n.problem->m_base_nodes[n.idx()].get())
         << "[opens = " << n.m_opens
         << "\tcloses = " << n.m_closes
         << "\tservice = " << n.m_service_time
         << "\tdemand = " << n.m_demand
         << "\ttype = " << n.type_str()
         << "]"
         << "\n";
     return log;
 }
operator<<() [10/11]
std::ostream& pgrouting::vrp::operator<< (std::ostream & log, const Fleet & f)
Definition at line 383 of file fleet.cpp.
References pgrouting::vrp::Fleet::m_trucks.
{
     log << "fleet\n";
     for (const auto v : f.m_trucks) {
         log << v;
     }
     log << "end fleet\n";
     return log;
 }
operator<<() [11/11]
std::ostream& pgrouting::vrp::operator<< (std::ostream & log, const Vehicle & v)
Definition at line 594 of file vehicle.cpp.
References pgrouting::Identifier::id(), pgrouting::Identifier::idx(), pgrouting::vrp::Vehicle::invariant(), pgrouting::vrp::Vehicle::m_capacity, pgrouting::vrp::Vehicle::m_factor, pgrouting::vrp::Vehicle::m_speed, pgrouting::vrp::Vehicle::path(), and pgrouting::vrp::Vehicle::speed().
{
     v.invariant();
     int i(0);
     log << "\n\n****************** " << v.idx() << "th VEHICLE*************\n";
     log << "id = " << v.id()
         << "\tcapacity = " << v.m_capacity
         << "\tfactor = " << v.m_factor << "\n"
         << "\tspeed = " << v.m_speed << "\n"
         << "\tnew speed = " << v.speed() << "\n";
     for (const auto &path_stop : v.path()) {
         log << "Path_stop" << ++i << "\n";
         log << path_stop << "\n";
     }
     return log;
 }