PGROUTING: boost::detail Namespace Reference
boost::detail Namespace Reference
Classes
class MapReducedWeight
Functions
template<class Graph , class PredEdgeMap , class ResCapMap , class RevEdgeMap >
void augment (const Graph &g, typename graph_traits< Graph >::vertex_descriptor src, typename graph_traits< Graph >::vertex_descriptor sink, PredEdgeMap p, ResCapMap residual_capacity, RevEdgeMap reverse_edge)
template<class Graph , class Weight , class Distance , class Reversed >
MapReducedWeight< Graph, Weight, Distance, Reversed > make_mapReducedWeight (const Graph &g, Weight w, Distance d, Reversed r)
template<class Graph , class ResCapMap >
filtered_graph< const Graph, is_residual_edge< ResCapMap > > residual_graph (const Graph &g, ResCapMap residual_capacity)
template<class Graph , class P , class T , class R , class Capacity , class ResidualCapacity , class Weight , class Reversed , class Pred , class VertexIndex >
void successive_shortest_path_nonnegative_weights_dispatch1 (Graph &g, typename graph_traits< Graph >::vertex_descriptor s, typename graph_traits< Graph >::vertex_descriptor t, Capacity capacity, ResidualCapacity residual_capacity, Weight weight, Reversed rev, VertexIndex index, Pred pred, const bgl_named_params< P, T, R > &params)
template<class Graph , class P , class T , class R , class Capacity , class ResidualCapacity , class Weight , class Reversed , class VertexIndex >
void successive_shortest_path_nonnegative_weights_dispatch1 (Graph &g, typename graph_traits< Graph >::vertex_descriptor s, typename graph_traits< Graph >::vertex_descriptor t, Capacity capacity, ResidualCapacity residual_capacity, Weight weight, Reversed rev, VertexIndex index, param_not_found, const bgl_named_params< P, T, R > &params)
template<class Graph , class P , class T , class R , class Capacity , class ResidualCapacity , class Weight , class Reversed , class Pred , class Distance , class VertexIndex >
void successive_shortest_path_nonnegative_weights_dispatch2 (Graph &g, typename graph_traits< Graph >::vertex_descriptor s, typename graph_traits< Graph >::vertex_descriptor t, Capacity capacity, ResidualCapacity residual_capacity, Weight weight, Reversed rev, VertexIndex index, Pred pred, Distance dist, const bgl_named_params< P, T, R > &params)
template<class Graph , class P , class T , class R , class Capacity , class ResidualCapacity , class Weight , class Reversed , class Pred , class VertexIndex >
void successive_shortest_path_nonnegative_weights_dispatch2 (Graph &g, typename graph_traits< Graph >::vertex_descriptor s, typename graph_traits< Graph >::vertex_descriptor t, Capacity capacity, ResidualCapacity residual_capacity, Weight weight, Reversed rev, VertexIndex index, Pred pred, param_not_found, const bgl_named_params< P, T, R > &params)
template<class Graph , class Capacity , class ResidualCapacity , class Weight , class Reversed , class Pred , class Distance , class Distance2 , class VertexIndex >
void successive_shortest_path_nonnegative_weights_dispatch3 (const Graph &g, typename graph_traits< Graph >::vertex_descriptor s, typename graph_traits< Graph >::vertex_descriptor t, Capacity capacity, ResidualCapacity residual_capacity, Weight weight, Reversed rev, VertexIndex index, Pred pred, Distance dist, Distance2 dist_pred)
template<class Graph , class Capacity , class ResidualCapacity , class Weight , class Reversed , class Pred , class Distance , class VertexIndex >
void successive_shortest_path_nonnegative_weights_dispatch3 (Graph &g, typename graph_traits< Graph >::vertex_descriptor s, typename graph_traits< Graph >::vertex_descriptor t, Capacity capacity, ResidualCapacity residual_capacity, Weight weight, Reversed rev, VertexIndex index, Pred pred, Distance dist, param_not_found)
Function Documentation
template<class Graph , class PredEdgeMap , class ResCapMap , class RevEdgeMap > void boost::detail::augment (const Graph & g, typename graph_traits< Graph >::vertex_descriptor src, typename graph_traits< Graph >::vertex_descriptor sink, PredEdgeMap p, ResCapMap residual_capacity, RevEdgeMap reverse_edge) inline
Definition at line 28 of file detail_augment.hpp.
Referenced by boost::successive_shortest_path_nonnegative_weights().
 {
     typename graph_traits<Graph>::edge_descriptor e;
     typename graph_traits<Graph>::vertex_descriptor u;
     typedef typename property_traits<ResCapMap>::value_type FlowValue;
     // find minimum residual capacity along the augmenting path
     FlowValue delta = (std::numeric_limits<FlowValue>::max)();
     e = get(p, sink);
     do {
         BOOST_USING_STD_MIN();
         delta = min BOOST_PREVENT_MACRO_SUBSTITUTION(delta, get(residual_capacity, e));
         u = source(e, g);
         e = get(p, u);
     } while (u != src);
     // push delta units of flow along the augmenting path
     e = get(p, sink);
     do {
         put(residual_capacity, e, get(residual_capacity, e) - delta);
         put(residual_capacity, get(reverse_edge, e), get(residual_capacity, get(reverse_edge, e)) + delta);
         u = source(e, g);
         e = get(p, u);
     } while (u != src);
 }
template<class Graph , class Weight , class Distance , class Reversed > MapReducedWeight<Graph, Weight, Distance, Reversed> boost::detail::make_mapReducedWeight (const Graph & g, Weight w, Distance d, Reversed r)
Definition at line 57 of file successive_shortest_path_nonnegative_weights.hpp.
Referenced by boost::successive_shortest_path_nonnegative_weights().
{
     return MapReducedWeight<Graph, Weight, Distance, Reversed>(g, w, d, r);
 }
template<class Graph , class ResCapMap > filtered_graph<const Graph, is_residual_edge<ResCapMap> > boost::detail::residual_graph (const Graph & g, ResCapMap residual_capacity)
Definition at line 20 of file detail_augment.hpp.
Referenced by boost::successive_shortest_path_nonnegative_weights().
{
     return filtered_graph<const Graph, is_residual_edge<ResCapMap> >
         (g, is_residual_edge<ResCapMap>(residual_capacity));
 }
template<class Graph , class P , class T , class R , class Capacity , class ResidualCapacity , class Weight , class Reversed , class Pred , class VertexIndex > void boost::detail::successive_shortest_path_nonnegative_weights_dispatch1 (Graph & g, typename graph_traits< Graph >::vertex_descriptor s, typename graph_traits< Graph >::vertex_descriptor t, Capacity capacity, ResidualCapacity residual_capacity, Weight weight, Reversed rev, VertexIndex index, Pred pred, const bgl_named_params< P, T, R > & params)
Definition at line 192 of file successive_shortest_path_nonnegative_weights.hpp.
References successive_shortest_path_nonnegative_weights_dispatch2().
Referenced by boost::successive_shortest_path_nonnegative_weights().
{
     successive_shortest_path_nonnegative_weights_dispatch2(g, s, t, capacity, residual_capacity, weight,  rev, index, pred,
                                 get_param(params, vertex_distance), params);
 }
template<class Graph , class P , class T , class R , class Capacity , class ResidualCapacity , class Weight , class Reversed , class VertexIndex > void boost::detail::successive_shortest_path_nonnegative_weights_dispatch1 (Graph & g, typename graph_traits< Graph >::vertex_descriptor s, typename graph_traits< Graph >::vertex_descriptor t, Capacity capacity, ResidualCapacity residual_capacity, Weight weight, Reversed rev, VertexIndex index, param_not_found , const bgl_named_params< P, T, R > & params)
Definition at line 209 of file successive_shortest_path_nonnegative_weights.hpp.
References successive_shortest_path_nonnegative_weights_dispatch2().
{
     typedef typename graph_traits<Graph>::edge_descriptor edge_descriptor;
     std::vector<edge_descriptor> pred_vec(num_vertices(g));
     successive_shortest_path_nonnegative_weights_dispatch2(g, s, t, capacity, residual_capacity, weight, rev, index,
             make_iterator_property_map(pred_vec.begin(), index),
             get_param(params, vertex_distance), params);
 }
template<class Graph , class P , class T , class R , class Capacity , class ResidualCapacity , class Weight , class Reversed , class Pred , class Distance , class VertexIndex > void boost::detail::successive_shortest_path_nonnegative_weights_dispatch2 (Graph & g, typename graph_traits< Graph >::vertex_descriptor s, typename graph_traits< Graph >::vertex_descriptor t, Capacity capacity, ResidualCapacity residual_capacity, Weight weight, Reversed rev, VertexIndex index, Pred pred, Distance dist, const bgl_named_params< P, T, R > & params)
Definition at line 153 of file successive_shortest_path_nonnegative_weights.hpp.
References successive_shortest_path_nonnegative_weights_dispatch3().
Referenced by successive_shortest_path_nonnegative_weights_dispatch1().
{
     successive_shortest_path_nonnegative_weights_dispatch3(g, s, t, capacity, residual_capacity, weight, rev, index, pred, dist, get_param(params, vertex_distance2));
 }
template<class Graph , class P , class T , class R , class Capacity , class ResidualCapacity , class Weight , class Reversed , class Pred , class VertexIndex > void boost::detail::successive_shortest_path_nonnegative_weights_dispatch2 (Graph & g, typename graph_traits< Graph >::vertex_descriptor s, typename graph_traits< Graph >::vertex_descriptor t, Capacity capacity, ResidualCapacity residual_capacity, Weight weight, Reversed rev, VertexIndex index, Pred pred, param_not_found , const bgl_named_params< P, T, R > & params)
Definition at line 170 of file successive_shortest_path_nonnegative_weights.hpp.
References successive_shortest_path_nonnegative_weights_dispatch3().
{
     typedef typename property_traits<Weight>::value_type D;
     std::vector<D> d_map(num_vertices(g));
     successive_shortest_path_nonnegative_weights_dispatch3(g, s, t, capacity, residual_capacity, weight, rev, index, pred,
             make_iterator_property_map(d_map.begin(), index),
             get_param(params, vertex_distance2));
 }
template<class Graph , class Capacity , class ResidualCapacity , class Weight , class Reversed , class Pred , class Distance , class Distance2 , class VertexIndex > void boost::detail::successive_shortest_path_nonnegative_weights_dispatch3 (const Graph & g, typename graph_traits< Graph >::vertex_descriptor s, typename graph_traits< Graph >::vertex_descriptor t, Capacity capacity, ResidualCapacity residual_capacity, Weight weight, Reversed rev, VertexIndex index, Pred pred, Distance dist, Distance2 dist_pred)
Definition at line 115 of file successive_shortest_path_nonnegative_weights.hpp.
References boost::successive_shortest_path_nonnegative_weights().
Referenced by successive_shortest_path_nonnegative_weights_dispatch2().
{
     successive_shortest_path_nonnegative_weights(g, s, t, capacity, residual_capacity, weight, rev, index, pred, dist, dist_pred);
 }
template<class Graph , class Capacity , class ResidualCapacity , class Weight , class Reversed , class Pred , class Distance , class VertexIndex > void boost::detail::successive_shortest_path_nonnegative_weights_dispatch3 (Graph & g, typename graph_traits< Graph >::vertex_descriptor s, typename graph_traits< Graph >::vertex_descriptor t, Capacity capacity, ResidualCapacity residual_capacity, Weight weight, Reversed rev, VertexIndex index, Pred pred, Distance dist, param_not_found)
Definition at line 132 of file successive_shortest_path_nonnegative_weights.hpp.
References boost::successive_shortest_path_nonnegative_weights().
{
     typedef typename property_traits<Weight>::value_type D;
     std::vector<D> d_map(num_vertices(g));
     successive_shortest_path_nonnegative_weights(g, s, t, capacity, residual_capacity, weight, rev, index, pred, dist,
                              make_iterator_property_map(d_map.begin(), index));
 }