var namespacepgrouting =
[
    [ "algorithms", "namespacepgrouting_1_1algorithms.html", "namespacepgrouting_1_1algorithms" ],
    [ "alphashape", "namespacepgrouting_1_1alphashape.html", "namespacepgrouting_1_1alphashape" ],
    [ "bidirectional", "namespacepgrouting_1_1bidirectional.html", "namespacepgrouting_1_1bidirectional" ],
    [ "contraction", "namespacepgrouting_1_1contraction.html", "namespacepgrouting_1_1contraction" ],
    [ "flow", "namespacepgrouting_1_1flow.html", "namespacepgrouting_1_1flow" ],
    [ "functions", "namespacepgrouting_1_1functions.html", "namespacepgrouting_1_1functions" ],
    [ "graph", "namespacepgrouting_1_1graph.html", "namespacepgrouting_1_1graph" ],
    [ "trsp", "namespacepgrouting_1_1trsp.html", "namespacepgrouting_1_1trsp" ],
    [ "tsp", "namespacepgrouting_1_1tsp.html", "namespacepgrouting_1_1tsp" ],
    [ "visitors", "namespacepgrouting_1_1visitors.html", "namespacepgrouting_1_1visitors" ],
    [ "vrp", "namespacepgrouting_1_1vrp.html", "namespacepgrouting_1_1vrp" ],
    [ "yen", "namespacepgrouting_1_1yen.html", "namespacepgrouting_1_1yen" ],
    [ "Basic_edge", "classpgrouting_1_1Basic__edge.html", "classpgrouting_1_1Basic__edge" ],
    [ "Basic_vertex", "classpgrouting_1_1Basic__vertex.html", "classpgrouting_1_1Basic__vertex" ],
    [ "CH_edge", "classpgrouting_1_1CH__edge.html", "classpgrouting_1_1CH__edge" ],
    [ "CH_vertex", "classpgrouting_1_1CH__vertex.html", "classpgrouting_1_1CH__vertex" ],
    [ "compPathsLess", "classpgrouting_1_1compPathsLess.html", "classpgrouting_1_1compPathsLess" ],
    [ "found_goals", "structpgrouting_1_1found__goals.html", null ],
    [ "Identifier", "classpgrouting_1_1Identifier.html", "classpgrouting_1_1Identifier" ],
    [ "Line_vertex", "classpgrouting_1_1Line__vertex.html", "classpgrouting_1_1Line__vertex" ],
    [ "Pg_points_graph", "classpgrouting_1_1Pg__points__graph.html", "classpgrouting_1_1Pg__points__graph" ],
    [ "Pgr_dijkstra", "classpgrouting_1_1Pgr__dijkstra.html", "classpgrouting_1_1Pgr__dijkstra" ],
    [ "Pgr_messages", "classpgrouting_1_1Pgr__messages.html", "classpgrouting_1_1Pgr__messages" ],
    [ "XY_vertex", "classpgrouting_1_1XY__vertex.html", "classpgrouting_1_1XY__vertex" ]
];