PGROUTING: pgr_allpairs.hpp File Reference
pgr_allpairs.hpp File Reference
#include <boost/config.hpp>
#include <boost/graph/adjacency_list.hpp>
#include <boost/property_map/property_map.hpp>
#include <boost/graph/johnson_all_pairs_shortest.hpp>
#include <boost/graph/floyd_warshall_shortest.hpp>
#include <deque>
#include <vector>
#include <set>
#include <limits>
#include "cpp_common/basePath_SSEC.hpp"
#include "cpp_common/pgr_base_graph.hpp"
#include "cpp_common/pgr_alloc.hpp"
Classes
class Pgr_allpairs< G >
class Pgr_allpairs< G >
struct Pgr_allpairs< G >::inf_plus< T >
Functions
template<class G >
void pgr_floydWarshall (G &graph, std::vector< Matrix_cell_t > &rows)
template<class G >
void pgr_floydWarshall (G &graph, size_t &result_tuple_count, Matrix_cell_t **postgres_rows)
template<class G >
void pgr_johnson (G &graph, std::vector< Matrix_cell_t > &rows)
template<class G >
void pgr_johnson (G &graph, size_t &result_tuple_count, Matrix_cell_t **postgres_rows)
Function Documentation
pgr_floydWarshall() [1/2]
template<class G > void pgr_floydWarshall (G & graph, std::vector< Matrix_cell_t > & rows)
Definition at line 63 of file pgr_allpairs.hpp.
References Pgr_allpairs< G >::floydWarshall().
Referenced by do_pgr_floydWarshall().
{
     Pgr_allpairs< G > fn_floydWarshall;
     fn_floydWarshall.floydWarshall(graph, rows);
 }
pgr_floydWarshall() [2/2]
template<class G > void pgr_floydWarshall (G & graph, size_t & result_tuple_count, Matrix_cell_t ** postgres_rows)
Definition at line 82 of file pgr_allpairs.hpp.
References Pgr_allpairs< G >::floydWarshall().
{
     Pgr_allpairs< G > fn_floydWarshall;
     fn_floydWarshall.floydWarshall(graph, result_tuple_count, postgres_rows);
 }
pgr_johnson() [1/2]
template<class G > void pgr_johnson (G & graph, std::vector< Matrix_cell_t > & rows)
Definition at line 56 of file pgr_allpairs.hpp.
References Pgr_allpairs< G >::johnson().
Referenced by do_pgr_johnson().
{
     Pgr_allpairs< G > fn_johnson;
     fn_johnson.johnson(graph, rows);
 }
pgr_johnson() [2/2]
template<class G > void pgr_johnson (G & graph, size_t & result_tuple_count, Matrix_cell_t ** postgres_rows)
Definition at line 71 of file pgr_allpairs.hpp.
References Pgr_allpairs< G >::johnson().
{
     Pgr_allpairs< G > fn_johnson;
     fn_johnson.johnson(graph, result_tuple_count, postgres_rows);
 }