PGROUTING: pgr_tsp.hpp File Reference
pgr_tsp.hpp File Reference
#include <time.h>
#include <sstream>
#include <vector>
#include <set>
#include <string>
#include <utility>
#include <limits>
#include <cmath>
#include "cpp_common/pgr_assert.h"
#include "cpp_common/Dmatrix.h"
#include "tsp/euclideanDmatrix.h"
#include "tsp/tour.h"
Classes
class pgrouting::tsp::TSP< MATRIX >
Namespaces
pgrouting
Book keeping class for swapping orders between vehicles.
pgrouting::tsp
Functions
static size_t pred (size_t i, size_t n)
static size_t rand (size_t n)
static size_t succ (size_t i, size_t n)
Function Documentation
pred()
static size_t pred (size_t i, size_t n) static
Definition at line 68 of file pgr_tsp.hpp.
Referenced by pgrouting::tsp::TSP< MATRIX >::find_closest_city().
{
     return  i == 0? n - 1: i -1;
 }
rand()
static size_t rand (size_t n) static
Definition at line 53 of file pgr_tsp.hpp.
References pgassert.
Referenced by pgrouting::tsp::TSP< MATRIX >::find_closest_city().
                {
     pgassert(n > 0);
     return static_cast< size_t >(std::rand() % n);
 }
succ()
static size_t succ (size_t i, size_t n) static
Definition at line 61 of file pgr_tsp.hpp.
References pgassert.
Referenced by pgrouting::tsp::TSP< MATRIX >::find_closest_city().
{
     pgassert(n > 0);
     return static_cast<size_t>((i + 1) % n);
 }