PGROUTING: strongComponents_driver.cpp File Reference
strongComponents_driver.cpp File Reference
#include "drivers/components/strongComponents_driver.h"
#include <sstream>
#include <deque>
#include <vector>
#include "cpp_common/pgr_alloc.hpp"
#include "cpp_common/pgr_assert.h"
#include "cpp_common/pgr_base_graph.hpp"
#include "components/pgr_components.hpp"
Functions
void do_pgr_strongComponents (pgr_edge_t *data_edges, size_t total_edges, pgr_components_rt **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
Function Documentation
do_pgr_strongComponents()
void do_pgr_strongComponents (pgr_edge_t * data_edges, size_t total_edges, pgr_components_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 45 of file strongComponents_driver.cpp.
References DIRECTED, pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::insert_edges(), pgassert, pgr_alloc(), pgr_free(), pgr_msg(), pgrouting::algorithms::strongComponents(), and AssertFailedException::what().
Referenced by process().
{
     std::ostringstream log;
     std::ostringstream err;
     std::ostringstream notice;
     try {
         pgassert(!(*log_msg));
         pgassert(!(*notice_msg));
         pgassert(!(*err_msg));
         pgassert(!(*return_tuples));
         pgassert(*return_count == 0);
         pgassert(total_edges != 0);
         graphType gType = DIRECTED;
         pgrouting::DirectedGraph digraph(gType);
         digraph.insert_edges(data_edges, total_edges);
         auto results(pgrouting::algorithms::strongComponents(digraph));
         auto count = results.size();
         if (count == 0) {
             (*return_tuples) = NULL;
             (*return_count) = 0;
             notice <<
                 "No components found";
             return;
         }
         (*return_tuples) = pgr_alloc(count, (*return_tuples));
         for (size_t i = 0; i < count; i++) {
             *((*return_tuples) + i) = results[i];
         }
         (*return_count) = count;
         pgassert(*err_msg == NULL);
         *log_msg = log.str().empty()?
             *log_msg :
             pgr_msg(log.str().c_str());
         *notice_msg = notice.str().empty()?
             *notice_msg :
             pgr_msg(notice.str().c_str());
     } catch (AssertFailedException &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch (std::exception &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch(...) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << "Caught unknown exception!";
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     }
 }