PGROUTING: pgrouting::Pg_points_graph::pointCompare Struct Reference
pgrouting::Pg_points_graph::pointCompare Struct Reference
Public Member Functions
bool operator() (const Point_on_edge_t &lhs, const Point_on_edge_t &rhs) const
Detailed Description
Definition at line 41 of file pgr_withPoints.hpp.
Member Function Documentation
bool pgrouting::Pg_points_graph::pointCompare::operator() (const Point_on_edge_t & lhs, const Point_on_edge_t & rhs) const inline
Definition at line 42 of file pgr_withPoints.hpp.
References pgrouting::Pg_points_graph::edges_of_points(), Point_on_edge_t::fraction, pgrouting::Pg_points_graph::new_edges(), pgrouting::Pg_points_graph::Pg_points_graph(), Point_on_edge_t::pid, and pgrouting::Pg_points_graph::points().
         {return lhs.fraction < rhs.fraction? true : lhs.pid < rhs.pid;}
The documentation for this struct was generated from the following file:
/home/vicky/pgrouting/pgrouting/pgrouting/include/withPoints/pgr_withPoints.hpp