PGROUTING: topologicalSort_driver.cpp File Reference
topologicalSort_driver.cpp File Reference
#include "drivers/topologicalSort/topologicalSort_driver.h"
#include <sstream>
#include <deque>
#include <vector>
#include <algorithm>
#include <limits>
#include "topologicalSort/pgr_topologicalSort.hpp"
#include "cpp_common/pgr_alloc.hpp"
#include "cpp_common/pgr_assert.h"
Functions
void do_pgr_topologicalSort (pgr_edge_t *data_edges, size_t total_edges, pgr_topologicalSort_t **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
template<class G >
static std::vector< pgr_topologicalSort_t > pgr_topologicalSort (G &graph)
Function Documentation
do_pgr_topologicalSort()
void do_pgr_topologicalSort (pgr_edge_t * data_edges, size_t total_edges, pgr_topologicalSort_t ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 57 of file topologicalSort_driver.cpp.
References DIRECTED, pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::insert_edges(), pgassert, pgr_alloc(), pgr_free(), pgr_msg(), pgr_topologicalSort(), and AssertFailedException::what().
Referenced by process().
{
     std::ostringstream log;
     std::ostringstream err;
     std::ostringstream notice;
     try {
         pgassert(total_edges != 0);
         pgassert(!(*log_msg));
         pgassert(!(*notice_msg));
         pgassert(!(*err_msg));
         pgassert(!(*return_tuples));
         pgassert(*return_count == 0);
         graphType gType =  DIRECTED;
         std::vector<pgr_topologicalSort_t> results;
         log << "Working with Directed Graph\n";
         pgrouting::DirectedGraph digraph(gType);
         digraph.insert_edges(data_edges, total_edges);
         results = pgr_topologicalSort(
                 digraph);
         auto count = results.size();
         if (count == 0) {
             (*return_tuples) = NULL;
             (*return_count) = 0;
             notice <<
                 "No vertices";
             return;
         }
         (*return_tuples) = pgr_alloc(count, (*return_tuples));
         for (size_t i = 0; i < count; i++) {
             *((*return_tuples) + i) = results[i];
         }
         (*return_count) = count;
         pgassert(*err_msg == NULL);
         *log_msg = log.str().empty()?
             *log_msg :
             pgr_msg(log.str().c_str());
         *notice_msg = notice.str().empty()?
             *notice_msg :
             pgr_msg(notice.str().c_str());
     } catch (AssertFailedException &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch (std::exception &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch(...) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << "Caught unknown exception!";
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     }
 }
pgr_topologicalSort()
template<class G > static std::vector<pgr_topologicalSort_t> pgr_topologicalSort (G & graph) static
Definition at line 47 of file topologicalSort_driver.cpp.
References Pgr_topologicalSort< G >::topologicalSort().
Referenced by do_pgr_topologicalSort().
                   {
     Pgr_topologicalSort< G > fn_topologicalSort;
     return fn_topologicalSort.topologicalSort(graph);
 }