PGROUTING: trsp_driver.h File Reference
trsp_driver.h File Reference
#include <stddef.h>
#include "c_types/trsp_types.h"
#include "c_types/pgr_edge_t.h"
#include "c_types/restriction_t.h"
#include "c_types/general_path_element_t.h"
Functions
void do_trsp (pgr_edge_t *edges, size_t edge_count, Restriction_t *restrictions, size_t restrictions_size, int64_t *start_vidsArr, size_t size_start_vidsArr, int64_t *end_vidsArr, size_t size_end_vidsArr, bool directed, General_path_element_t **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
Function Documentation
do_trsp()
void do_trsp (pgr_edge_t * edges, size_t edge_count, Restriction_t * restrictions, size_t restrictions_size, int64_t * start_vidsArr, size_t size_start_vidsArr, int64_t * end_vidsArr, size_t size_end_vidsArr, bool directed, General_path_element_t ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 41 of file trsp_driver.cpp.
References collapse_paths(), count_tuples(), pgassert, pgr_alloc(), pgr_free(), pgr_msg(), pgrouting::trsp::Pgr_trspHandler::process(), and AssertFailedException::what().
Referenced by compute_trsp().
{
     std::ostringstream log;
     std::ostringstream err;
     std::ostringstream notice;
     try {
         pgassert(*return_tuples == NULL);
         pgassert(*return_count == 0);
         pgassert(*log_msg == NULL);
         pgassert(*notice_msg == NULL);
         pgassert(*err_msg == NULL);
         std::vector<pgrouting::trsp::Rule> ruleList;
         for (size_t i = 0; i < restrictions_size; ++i) {
             ruleList.push_back(pgrouting::trsp::Rule(*(restrictions + i)));
         }
         /*
          * Inserting vertices into a c++ vector structure
          */
         std::vector<int64_t>
             sources(start_vidsArr, start_vidsArr + size_start_vidsArr);
         std::vector< int64_t >
             targets(end_vidsArr, end_vidsArr + size_end_vidsArr);
         /*
          * ordering and removing duplicates
          */
         std::sort(sources.begin(), sources.end());
         sources.erase(
                 std::unique(sources.begin(), sources.end()),
                 sources.end());
         std::sort(targets.begin(), targets.end());
         targets.erase(
                 std::unique(targets.begin(), targets.end()),
                 targets.end());
         pgrouting::trsp::Pgr_trspHandler gdef(
                 edges,
                 total_edges,
                 directed,
                 ruleList);
         auto paths = gdef.process(
                 sources,
                 targets);
         size_t count(0);
         count = count_tuples(paths);
         if (count == 0) {
             (*return_tuples) = NULL;
             (*return_count) = 0;
             return;
         }
         (*return_tuples) = pgr_alloc(count, (*return_tuples));
         (*return_count) = collapse_paths(return_tuples, paths);
         *log_msg = log.str().empty()?
             *log_msg :
             pgr_msg(log.str().c_str());
         *notice_msg = notice.str().empty()?
             *notice_msg :
             pgr_msg(notice.str().c_str());
         return;
     } catch (AssertFailedException &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch (std::exception &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch(...) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << "Caught unknown exception!";
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     }
 }