 NOTICE:  Starting kshortest_path select source, target, cost,reverse_cost, id from network order by id

 NOTICE:  columns: id 5 source 1 target 2 cost 3.000000
 NOTICE:  Total 40 tuples in query
 NOTICE:  Calling doKpaths

 NOTICE:  total tuples found 2

 NOTICE:  Exist Status = 0

 NOTICE:  Returned message = OK

 NOTICE:  Total number of tuples to be returned 2 
0|0|4|15|2
1|0|5|-1|0
 NOTICE:  Starting kshortest_path select source, target, cost,reverse_cost, id from network order by id

 NOTICE:  columns: id 5 source 1 target 2 cost 3.000000
 NOTICE:  Total 40 tuples in query
 NOTICE:  Calling doKpaths

 NOTICE:  total tuples found 2

 NOTICE:  Exist Status = 0

 NOTICE:  Returned message = OK

 NOTICE:  Total number of tuples to be returned 2 
0|0|4|15|2
1|0|5|-1|0
 NOTICE:  Starting kshortest_path select source, target, cost,reverse_cost, id from network order by id

 NOTICE:  columns: id 5 source 1 target 2 cost 3.000000
 NOTICE:  Total 40 tuples in query
 NOTICE:  Calling doKpaths

 NOTICE:  total tuples found 2

 NOTICE:  Exist Status = 0

 NOTICE:  Returned message = OK

 NOTICE:  Total number of tuples to be returned 2 
0|0|4|15|2
1|0|5|-1|0
 NOTICE:  Starting kshortest_path select source, target, cost,reverse_cost, id from network order by id

 NOTICE:  columns: id 5 source 1 target 2 cost 3.000000
 NOTICE:  Total 40 tuples in query
 NOTICE:  Calling doKpaths

 NOTICE:  total tuples found 2

 NOTICE:  Exist Status = 0

 NOTICE:  Returned message = OK

 NOTICE:  Total number of tuples to be returned 2 
0|0|4|15|2
1|0|5|-1|0
 NOTICE:  Starting kshortest_path select source, target, cost,reverse_cost, id from network order by id

 NOTICE:  columns: id 5 source 1 target 2 cost 3.000000
 NOTICE:  columns: reverse_cost cost 4.000000
 NOTICE:  Total 40 tuples in query
 NOTICE:  Calling doKpaths

 NOTICE:  total tuples found 2

 NOTICE:  Exist Status = 0

 NOTICE:  Returned message = OK

 NOTICE:  Total number of tuples to be returned 2 
0|0|4|15|2
1|0|5|-1|0
 NOTICE:  Starting kshortest_path select source, target, cost,reverse_cost, id from network order by id

 NOTICE:  columns: id 5 source 1 target 2 cost 3.000000
 NOTICE:  columns: reverse_cost cost 4.000000
 NOTICE:  Total 40 tuples in query
 NOTICE:  Calling doKpaths

 NOTICE:  total tuples found 4

 NOTICE:  Exist Status = 0

 NOTICE:  Returned message = OK

 NOTICE:  Total number of tuples to be returned 4 
0|0|4|15|2
1|0|5|-1|0
2|1|4|17|10
3|1|5|-1|0
 NOTICE:  Starting kshortest_path select source, target, cost,reverse_cost, id from network order by id

 NOTICE:  columns: id 5 source 1 target 2 cost 3.000000
 NOTICE:  columns: reverse_cost cost 4.000000
 NOTICE:  Total 40 tuples in query
 NOTICE:  Calling doKpaths

 NOTICE:  total tuples found 4

 NOTICE:  Exist Status = 0

 NOTICE:  Returned message = OK

 NOTICE:  Total number of tuples to be returned 4 
0|0|4|15|2
1|0|5|-1|0
2|1|4|17|10
3|1|5|-1|0
 NOTICE:  Starting kshortest_path select source, target, cost,reverse_cost, id from network order by id

 NOTICE:  columns: id 5 source 1 target 2 cost 3.000000
 NOTICE:  columns: reverse_cost cost 4.000000
 NOTICE:  Total 40 tuples in query
 NOTICE:  Calling doKpaths

 NOTICE:  total tuples found 4

 NOTICE:  Exist Status = 0

 NOTICE:  Returned message = OK

 NOTICE:  Total number of tuples to be returned 4 
0|0|4|15|2
1|0|5|-1|0
2|1|4|17|10
3|1|5|-1|0
