pgRouting: astarManyToMany_driver.cpp File Reference
astarManyToMany_driver.cpp File Reference
#include <sstream>
#include <deque>
#include <algorithm>
#include <vector>
#include "./astarManyToMany_driver.h"
#include "./../../common/src/pgr_types.h"
#include "./pgr_astar.hpp"
#include "./../../common/src/pgr_assert.h"
#include "./../../common/src/pgr_alloc.hpp"
Functions
void do_pgr_astarManyToMany (Pgr_edge_xy_t *edges, size_t total_edges, int64_t *start_vidsArr, size_t size_start_vidsArr, int64_t *end_vidsArr, size_t size_end_vidsArr, bool directed, int heuristic, double factor, double epsilon, bool only_cost, General_path_element_t **return_tuples, size_t *return_count, char **log_msg, char **err_msg)
template<class G >
void pgr_astar (G &graph, std::deque< Path > &paths, std::vector< int64_t > sources, std::vector< int64_t > targets, int heuristic, double factor, double epsilon, bool only_cost=false)
Function Documentation
void do_pgr_astarManyToMany (Pgr_edge_xy_t * edges, size_t total_edges, int64_t * start_vidsArr, size_t size_start_vidsArr, int64_t * end_vidsArr, size_t size_end_vidsArr, bool directed, int heuristic, double factor, double epsilon, bool only_cost, General_path_element_t ** return_tuples, size_t * return_count, char ** log_msg, char ** err_msg)
Definition at line 73 of file astarManyToMany_driver.cpp.
References DIRECTED, pgrouting::extract_vertices(), pgrouting::graph::Pgr_base_graph< G, Vertex, Edge >::graph_insert_data(), pgassert, pgr_alloc(), pgr_astar(), UNDIRECTED, and AssertFailedException::what().
Referenced by process().
template<class G > void pgr_astar (G & graph, std::deque< Path > & paths, std::vector< int64_t > sources, std::vector< int64_t > targets, int heuristic, double factor, double epsilon, bool only_cost = false)
Definition at line 52 of file astarManyToMany_driver.cpp.
References Pgr_astar< G >::astar().
Referenced by do_pgr_astarManyToMany().