pgRouting: pgrouting::Pgr_deadEndContraction< G > Class Template Reference
pgrouting::Pgr_deadEndContraction< G > Class Template Reference
#include "pgr_deadEndContraction.hpp"
Public Types
typedef G::E E
typedef G::E_i E_i
typedef G::EI_i EI_i
typedef G::EO_i EO_i
typedef G::V V
typedef G::V_i V_i
Public Member Functions
void add_if_dead_end (G &graph, V v, std::ostringstream &debug)
void calculateVertices (G &graph, std::ostringstream &debug)
void doContraction (G &graph, std::ostringstream &debug)
bool is_dead_end (G &graph, V v, std::ostringstream &debug)
void setForbiddenVertices (G &graph, Identifiers< int64_t > forbidden_vertices, std::ostringstream &debug)
void setForbiddenVertices (G &graph, int64_t *forbidden_vertices, size_t size_forbidden_vertices, std::ostringstream &debug)
Private Attributes
Identifiers< V > deadendVertices
Identifiers< V > forbiddenVertices
Detailed Description
template<class G>
class pgrouting::Pgr_deadEndContraction< G >
Definition at line 44 of file pgr_deadEndContraction.hpp.
Member Typedef Documentation
template<class G> typedef G::E pgrouting::Pgr_deadEndContraction< G >::E
Definition at line 47 of file pgr_deadEndContraction.hpp.
template<class G> typedef G::E_i pgrouting::Pgr_deadEndContraction< G >::E_i
Definition at line 49 of file pgr_deadEndContraction.hpp.
template<class G> typedef G::EI_i pgrouting::Pgr_deadEndContraction< G >::EI_i
Definition at line 51 of file pgr_deadEndContraction.hpp.
template<class G> typedef G::EO_i pgrouting::Pgr_deadEndContraction< G >::EO_i
Definition at line 50 of file pgr_deadEndContraction.hpp.
template<class G> typedef G::V pgrouting::Pgr_deadEndContraction< G >::V
Definition at line 46 of file pgr_deadEndContraction.hpp.
template<class G> typedef G::V_i pgrouting::Pgr_deadEndContraction< G >::V_i
Definition at line 48 of file pgr_deadEndContraction.hpp.
Member Function Documentation
template<class G > void pgrouting::Pgr_deadEndContraction< G >::add_if_dead_end (G & graph, V v, std::ostringstream & debug)
Definition at line 165 of file pgr_deadEndContraction.hpp.
template<class G > void pgrouting::Pgr_deadEndContraction< G >::calculateVertices (G & graph, std::ostringstream & debug)
Definition at line 94 of file pgr_deadEndContraction.hpp.
Referenced by perform_deadEnd().
template<class G > void pgrouting::Pgr_deadEndContraction< G >::doContraction (G & graph, std::ostringstream & debug)
Definition at line 176 of file pgr_deadEndContraction.hpp.
Referenced by perform_deadEnd().
template<class G > bool pgrouting::Pgr_deadEndContraction< G >::is_dead_end (G & graph, V v, std::ostringstream & debug)
Definition at line 109 of file pgr_deadEndContraction.hpp.
References UNDIRECTED.
template<class G > void pgrouting::Pgr_deadEndContraction< G >::setForbiddenVertices (G & graph, Identifiers< int64_t > forbidden_vertices, std::ostringstream & debug)
Definition at line 73 of file pgr_deadEndContraction.hpp.
Referenced by perform_deadEnd().
template<class G > void pgrouting::Pgr_deadEndContraction< G >::setForbiddenVertices (G & graph, int64_t * forbidden_vertices, size_t size_forbidden_vertices, std::ostringstream & debug)
Definition at line 83 of file pgr_deadEndContraction.hpp.
Member Data Documentation
template<class G> Identifiers<V> pgrouting::Pgr_deadEndContraction< G >::deadendVertices private
Definition at line 68 of file pgr_deadEndContraction.hpp.
template<class G> Identifiers<V> pgrouting::Pgr_deadEndContraction< G >::forbiddenVertices private
Definition at line 69 of file pgr_deadEndContraction.hpp.
The documentation for this class was generated from the following file:
pgr_deadEndContraction.hpp