pgRouting: CMoveInfo Class Reference
CMoveInfo Class Reference
#include "VRP_Solver.h"
Public Member Functions
CMoveInfo ()
~CMoveInfo ()
void getInitialTour (CTourInfo &TourData)
void getInitialTour (CTourInfo &TourData1, CTourInfo &TourData2)
bool getModifiedTourAt (int index, CTourInfo &tourInfo)
double getModifiedTourCost () const
size_t getModifiedTourCount () const
bool isBetter (CMoveInfo *pVRPMove)
void reverseMove ()
void setInitialTour (CTourInfo pTourData)
void setInitialTour (CTourInfo pTourData1, CTourInfo pTourData2)
void setModifiedTour (CTourInfo pTourData)
void setModifiedTour (CTourInfo pTourData1, CTourInfo pTourData2)
Private Member Functions
void clearInitialTour ()
void clearModifiedTour ()
Private Attributes
std::vector< CTourInfo > m_vInitialTour
std::vector< CTourInfo > m_vModifiedTour
Friends
bool operator== (const CMoveInfo &cur, const CMoveInfo &that)
Detailed Description
Definition at line 290 of file VRP_Solver.h.
Constructor & Destructor Documentation
CMoveInfo::CMoveInfo ()
Definition at line 181 of file VRP_Solver.cpp.
CMoveInfo::~CMoveInfo ()
Definition at line 182 of file VRP_Solver.cpp.
Member Function Documentation
void CMoveInfo::clearInitialTour () private
void CMoveInfo::clearModifiedTour () private
void CMoveInfo::getInitialTour (CTourInfo & TourData)
Definition at line 206 of file VRP_Solver.cpp.
References m_vInitialTour.
Referenced by CVRPSolver::attemptVehicleExchange(), and CVRPSolver::insertUnservedOrders().
void CMoveInfo::getInitialTour (CTourInfo & TourData1, CTourInfo & TourData2)
Definition at line 210 of file VRP_Solver.cpp.
References m_vInitialTour.
bool CMoveInfo::getModifiedTourAt (int index, CTourInfo & tourInfo)
Definition at line 215 of file VRP_Solver.cpp.
References m_vModifiedTour.
Referenced by CVRPSolver::applyBestMoveInCurrentSolution(), and CVRPSolver::attemptVehicleExchange().
double CMoveInfo::getModifiedTourCost () const
size_t CMoveInfo::getModifiedTourCount () const inline
Definition at line 304 of file VRP_Solver.h.
References m_vModifiedTour.
Referenced by CVRPSolver::applyBestMoveInCurrentSolution().
bool CMoveInfo::isBetter (CMoveInfo * pVRPMove)
void CMoveInfo::reverseMove ()
Referenced by CVRPSolver::updateTabuCount().
void CMoveInfo::setInitialTour (CTourInfo pTourData)
Definition at line 184 of file VRP_Solver.cpp.
References m_vInitialTour.
Referenced by CVRPSolver::attemptVehicleExchange(), and CVRPSolver::insertUnservedOrders().
void CMoveInfo::setInitialTour (CTourInfo pTourData1, CTourInfo pTourData2)
Definition at line 189 of file VRP_Solver.cpp.
References m_vInitialTour.
void CMoveInfo::setModifiedTour (CTourInfo pTourData)
Definition at line 195 of file VRP_Solver.cpp.
References m_vModifiedTour.
Referenced by CVRPSolver::attemptVehicleExchange(), and CVRPSolver::insertUnservedOrders().
void CMoveInfo::setModifiedTour (CTourInfo pTourData1, CTourInfo pTourData2)
Definition at line 200 of file VRP_Solver.cpp.
References m_vModifiedTour.
Friends And Related Function Documentation
bool operator== (const CMoveInfo & cur, const CMoveInfo & that) friend
Definition at line 62 of file VRP_Solver.cpp.
Member Data Documentation
std::vector<CTourInfo> CMoveInfo::m_vInitialTour private
Definition at line 324 of file VRP_Solver.h.
Referenced by getInitialTour(), operator==(), and setInitialTour().
std::vector<CTourInfo> CMoveInfo::m_vModifiedTour private
Definition at line 325 of file VRP_Solver.h.
Referenced by getModifiedTourAt(), getModifiedTourCount(), operator==(), and setModifiedTour().
The documentation for this class was generated from the following files:
VRP_Solver.h
VRP_Solver.cpp