pgRouting: Identifiers< T > Class Template Reference
Identifiers< T > Class Template Reference
#include "identifiers.hpp"
Public Types
typedef std::set< T >
::const_iterator const_iterator
typedef std::set< T >::iterator iterator
Public Member Functions
Identifiers ()=default
Identifiers (T *container, size_t size)
iterator begin ()
const_iterator begin () const
void clear ()
bool empty () const
Returns true when the set is empty.
iterator end ()
const_iterator end () const
bool has (const T other) const
Returns a boolean value true or false.
const std::set< T > & ids () const
Returns a set of identifiers of type set<T>
void insert (const Identifiers< T > &other)
Inserts a set of identifiers of type Identifiers<T> to this set.
void insert (const T &other)
Inserts an identifier of type T to this set.
bool isDisjoint (const T other) const
Returns a boolean value true or false.
bool isDisjoint (const Identifiers< T > &other) const
Returns a boolean value true or false.
Identifiers< T > operator* (const T &other) const
Returns a set of identifiers of type Identifiers<T>
Identifiers< T > operator* (const Identifiers< T > &other) const
Returns a set of identifiers of type Identifiers<T>
Identifiers< T > & operator*= (const T &other)
Returns a set of identifiers of type Identifiers<T>&
Identifiers< T > & operator*= (const Identifiers< T > &other)
Returns a set of identifiers of type Identifiers<T>&
Identifiers< T > operator+ (const T &other) const
Returns a set of identifiers of type Identifiers<T>
Identifiers< T > operator+ (const Identifiers< T > &other) const
Returns a set of identifiers of type Identifiers<T>
Identifiers< T > & operator+= (const T &other)
Returns a set of identifiers of type Identifiers<T>&
Identifiers< T > & operator+= (const Identifiers< T > &other)
Returns a set of identifiers of type Identifiers<T>&
Identifiers< T > operator- (const T &other) const
Returns a set of identifiers of type Identifiers<T>
Identifiers< T > operator- (const Identifiers< T > &other) const
Returns a set of identifiers of type Identifiers<T>
Identifiers< T > & operator-= (const T &other)
Returns a set of identifiers of type Identifiers<T>&
Identifiers< T > & operator-= (const Identifiers< T > &other)
Returns a set of identifiers of type Identifiers<T>&
bool operator== (const Identifiers< T > &other) const
Returns a boolean value.
const T & operator[] (size_t index) const
Returns an identifier of type T at position index in the set.
size_t size () const
Private Attributes
std::set< T > m_ids
Friends
template<T >
std::ostream & operator<< (std::ostream &os, const Identifiers< T > &identifiers)
Prints the set of identifiers.
Detailed Description
template<typename T>
class Identifiers< T >
Definition at line 40 of file identifiers.hpp.
Member Typedef Documentation
template<typename T> typedef std::set<T>::const_iterator Identifiers< T >::const_iterator
Definition at line 51 of file identifiers.hpp.
template<typename T> typedef std::set<T>::iterator Identifiers< T >::iterator
Definition at line 50 of file identifiers.hpp.
Constructor & Destructor Documentation
template<typename T> Identifiers< T >::Identifiers () default
template<typename T> Identifiers< T >::Identifiers (T * container, size_t size) inline
Definition at line 43 of file identifiers.hpp.
Member Function Documentation
template<typename T> iterator Identifiers< T >::begin () inline
Definition at line 60 of file identifiers.hpp.
template<typename T> const_iterator Identifiers< T >::begin () const inline
Definition at line 61 of file identifiers.hpp.
template<typename T> void Identifiers< T >::clear () inline
Definition at line 54 of file identifiers.hpp.
Referenced by pgrouting::contraction::Vertex::clear_contracted_vertices(), and pgrouting::contraction::Edge::clear_contracted_vertices().
template<typename T> bool Identifiers< T >::empty (void) const inline
Returns true when the set is empty.
Definition at line 53 of file identifiers.hpp.
template<typename T> iterator Identifiers< T >::end () inline
Definition at line 62 of file identifiers.hpp.
template<typename T> const_iterator Identifiers< T >::end () const inline
Definition at line 63 of file identifiers.hpp.
template<typename T> bool Identifiers< T >::has (const T other) const
Returns a boolean value true or false.
Parameters
[in] other Identifier of type T Returns: true: If other is in this set false: Otherwise
Definition at line 104 of file identifiers.hpp.
Referenced by pgrouting::graph::Pgr_contractionGraph< G, T_V, T_E >::get_changed_vertices(), and pgrouting::graph::Pgr_contractionGraph< G, T_V, T_E >::get_remaining_vertices().
template<typename T > const std::set< T > & Identifiers< T >::ids () const
Returns a set of identifiers of type set<T>
Definition at line 92 of file identifiers.hpp.
Referenced by Identifiers< T >::insert(), Identifiers< T >::isDisjoint(), Identifiers< T >::operator*=(), Identifiers< T >::operator-=(), and Identifiers< T >::operator==().
template<typename T> void Identifiers< T >::insert (const Identifiers< T > & other)
Inserts a set of identifiers of type Identifiers<T> to this set.
Parameters
[in] other is a set of identifiers
Definition at line 142 of file identifiers.hpp.
References Identifiers< T >::ids().
Referenced by do_pgr_test_c_edges(), Identifiers< T >::operator*(), Identifiers< T >::operator+(), and Identifiers< T >::operator-().
template<typename T> void Identifiers< T >::insert (const T & other)
Inserts an identifier of type T to this set.
Parameters
[in] other is an identifier of type T
Definition at line 151 of file identifiers.hpp.
template<typename T> bool Identifiers< T >::isDisjoint (const T other) const
Returns a boolean value true or false.
Parameters
[in] other is an identifier of type T Returns: true: If other is not in this set false: Otherwise
Definition at line 116 of file identifiers.hpp.
template<typename T> bool Identifiers< T >::isDisjoint (const Identifiers< T > & other) const
Returns a boolean value true or false.
Parameters
[in] other is set of identifiers of type Identifiers<T> Returns: true: If other and this set are disjoint false: otherwise
Definition at line 128 of file identifiers.hpp.
References Identifiers< T >::ids().
template<typename T> Identifiers< T > Identifiers< T >::operator* (const T & other) const
Returns a set of identifiers of type Identifiers<T>
Parameters
[in] other is an identifier of type T Returns the set intersection of other with this set
Definition at line 187 of file identifiers.hpp.
References Identifiers< T >::insert().
template<typename T> Identifiers< T > Identifiers< T >::operator* (const Identifiers< T > & other) const
Returns a set of identifiers of type Identifiers<T>
Parameters
[in] other is a set of identifiers of type Identifiers<T> Returns the set intersection of other with this set
Definition at line 226 of file identifiers.hpp.
References Identifiers< T >::insert().
template<typename T> Identifiers< T > & Identifiers< T >::operator*= (const T & other)
Returns a set of identifiers of type Identifiers<T>&
Parameters
[in] other is an identifiers of type T Replaces this set with the set intersection of other with this set
Definition at line 264 of file identifiers.hpp.
template<typename T> Identifiers< T > & Identifiers< T >::operator*= (const Identifiers< T > & other)
Returns a set of identifiers of type Identifiers<T>&
Parameters
[in] other is a set of identifiers of type Identifiers<T> Replaces this set with the set intersection of other with this set
Definition at line 305 of file identifiers.hpp.
References Identifiers< T >::ids().
template<typename T> Identifiers< T > Identifiers< T >::operator+ (const T & other) const
Returns a set of identifiers of type Identifiers<T>
Parameters
[in] other is an identifier of type T Returns the set union of other with this set
Definition at line 174 of file identifiers.hpp.
References Identifiers< T >::insert().
template<typename T> Identifiers< T > Identifiers< T >::operator+ (const Identifiers< T > & other) const
Returns a set of identifiers of type Identifiers<T>
Parameters
[in] other is a set of identifiers of type Identifiers<T> Returns the set union of other with this set
Definition at line 213 of file identifiers.hpp.
References Identifiers< T >::insert().
template<typename T> Identifiers< T > & Identifiers< T >::operator+= (const T & other)
Returns a set of identifiers of type Identifiers<T>&
Parameters
[in] other is an identifiers of type T Replaces this set with the set union of other with this set
Definition at line 253 of file identifiers.hpp.
template<typename T> Identifiers< T > & Identifiers< T >::operator+= (const Identifiers< T > & other)
Returns a set of identifiers of type Identifiers<T>&
Parameters
[in] other is a set of identifiers of type Identifiers<T> Replaces this set with the set union of other with this set
Definition at line 294 of file identifiers.hpp.
template<typename T> Identifiers< T > Identifiers< T >::operator- (const T & other) const
Returns a set of identifiers of type Identifiers<T>
Parameters
[in] other is an identifier of type T Returns the set difference between this set and other
Definition at line 200 of file identifiers.hpp.
References Identifiers< T >::insert().
template<typename T> Identifiers< T > Identifiers< T >::operator- (const Identifiers< T > & other) const
Returns a set of identifiers of type Identifiers<T>
Parameters
[in] other is a set of identifiers of type Identifiers<T> Returns the set difference between this set and other
Definition at line 239 of file identifiers.hpp.
References Identifiers< T >::insert().
template<typename T> Identifiers< T > & Identifiers< T >::operator-= (const T & other)
Returns a set of identifiers of type Identifiers<T>&
Parameters
[in] other is a set of identifiers of type T Replaces this set with the set difference between this set and other
Definition at line 280 of file identifiers.hpp.
template<typename T> Identifiers< T > & Identifiers< T >::operator-= (const Identifiers< T > & other)
Returns a set of identifiers of type Identifiers<T>&
Parameters
[in] other is a set of identifiers of type Identifiers<T> Replaces this set with the set difference between this set and other
Definition at line 320 of file identifiers.hpp.
References Identifiers< T >::ids().
template<typename T> bool Identifiers< T >::operator== (const Identifiers< T > & other) const
Returns a boolean value.
Parameters
[in] other is a set of identifiers of type Identifiers<T> Returns: true: If other and this set are equivalent false: Otherwise
Definition at line 163 of file identifiers.hpp.
References Identifiers< T >::ids().
template<typename T > const T & Identifiers< T >::operator[] (size_t index) const
Returns an identifier of type T at position index in the set.
Parameters
[in] index is of type size_t
Definition at line 345 of file identifiers.hpp.
template<typename T> size_t Identifiers< T >::size () const inline
Definition at line 49 of file identifiers.hpp.
Referenced by do_pgr_contractGraph(), pgrouting::Pgr_linearContraction< G >::doContraction(), pgrouting::graph::Pgr_contractionGraph< G, T_V, T_E >::get_ids(), pgrouting::contraction::Vertex::has_contracted_vertices(), pgrouting::contraction::Edge::has_contracted_vertices(), Identifiers< V >::Identifiers(), and pgrouting::Pgr_linearContraction< G >::is_linear().
Friends And Related Function Documentation
template<typename T> template<T > std::ostream& operator<< (std::ostream & os, const Identifiers< T > & identifiers) friend
Prints the set of identifiers.
Definition at line 331 of file identifiers.hpp.
Member Data Documentation
template<typename T> std::set<T> Identifiers< T >::m_ids private
Definition at line 84 of file identifiers.hpp.
Referenced by Identifiers< V >::begin(), Identifiers< V >::clear(), Identifiers< V >::empty(), Identifiers< V >::end(), Identifiers< V >::Identifiers(), and Identifiers< V >::size().
The documentation for this class was generated from the following file:
identifiers.hpp