pgRouting: pgrouting::contraction Namespace Reference
pgrouting::contraction Namespace Reference
Classes
class Edge
class Vertex
Functions
size_t check_vertices (std::vector< Vertex > vertices)
std::vector< Vertex > extract_vertices (const std::vector< pgr_edge_t > &data_edges)
std::vector< Vertex > extract_vertices (const pgr_edge_t *data_edges, int64_t count)
std::ostream & operator<< (std::ostream &os, const Vertex &v)
std::ostream & operator<< (std::ostream &os, const Edge &e)
Function Documentation
size_t pgrouting::contraction::check_vertices (std::vector< Vertex > vertices)
Definition at line 68 of file ch_vertex.cpp.
References pgrouting::contraction::Vertex::id.
std::vector< Vertex > pgrouting::contraction::extract_vertices (const std::vector< pgr_edge_t > & data_edges)
Definition at line 84 of file ch_vertex.cpp.
References pgrouting::contraction::Vertex::id.
Referenced by do_pgr_contractGraph(), do_pgr_test_c_edges(), and extract_vertices().
std::vector< Vertex > pgrouting::contraction::extract_vertices (const pgr_edge_t * data_edges, int64_t count)
Definition at line 112 of file ch_vertex.cpp.
References extract_vertices().
std::ostream& pgrouting::contraction::operator<< (std::ostream & os, const Vertex & v)
Definition at line 57 of file ch_vertex.cpp.
References pgrouting::contraction::Vertex::contracted_vertices(), and pgrouting::contraction::Vertex::id.
std::ostream& pgrouting::contraction::operator<< (std::ostream & os, const Edge & e)
Definition at line 111 of file ch_edge.cpp.
References pgrouting::contraction::Edge::contracted_vertices(), pgrouting::contraction::Edge::cost, pgrouting::contraction::Edge::first, pgrouting::contraction::Edge::id, pgrouting::contraction::Edge::source, and pgrouting::contraction::Edge::target.