PGROUTING: /home/vicky/pgrouting/pgrouting/pgrouting/include/drivers/areaContraction/areaContraction_driver.h File Reference
areaContraction_driver.h File Reference
#include "c_types/pgr_edge_t.h"
#include "c_types/contracted_rt.h"
Functions
void do_pgr_areaContraction (pgr_edge_t *data_edges, size_t data_edges_size, int64_t *border_vertices, size_t border_vertices_size, bool directed, contracted_rt **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
Function Documentation
void do_pgr_areaContraction (pgr_edge_t * data_edges, size_t data_edges_size, int64_t * border_vertices, size_t border_vertices_size, bool directed, contracted_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 79 of file areaContraction_driver.cpp.
References DIRECTED, edges, Path::generate_postgres_data(), pgrouting::graph::Pgr_base_graph< G, Vertex, Edge >::insert_edges(), pgassert, pgr_alloc(), pgr_areaContraction(), pgr_free(), pgr_msg(), process_areaContraction(), Path::size(), UNDIRECTED, and AssertFailedException::what().
Referenced by process().
{
     std::ostringstream log;
     std::ostringstream err;
     std::ostringstream notice;
     try {
         pgassert(!(*log_msg));
         pgassert(!(*notice_msg));
         pgassert(!(*err_msg));
         pgassert(!(*return_tuples));
         pgassert(*return_count == 0);
         pgassert(data_edges_size != 0);
         graphType gType = directed? DIRECTED: UNDIRECTED;
         /*
         *Converting to C++ Structures
         */
         std::vector<pgr_edge_t> edges(data_edges, data_edges + data_edges_size);
         std::vector<int64_t> border(
                 borderVertices,
                 borderVertices + borderVertices_size);
         /*
         *Creating new containers
         */
         std::vector< pgrouting::CH_edge > shortcut_edges;
         pgassert(shortcut_edges.empty());
         /*
         *Working with directed and undirected graph
         */
         if (directed) {
           log << "Working with directed Graph\n";
           pgrouting::CHDirectedGraph digraph(gType);
           process_areaContraction(digraph, edges, border, shortcut_edges,
                   log, err);
         } else {
           log << "Working with Undirected Graph\n";
           pgrouting::CHUndirectedGraph undigraph(gType);
           process_areaContraction(undigraph, edges, border, shortcut_edges,
                   log, err);
         }
         pgassert(*err_msg == NULL);
         *log_msg = log.str().empty()?
             *log_msg :
             pgr_msg(log.str().c_str());
         *notice_msg = notice.str().empty()?
             *notice_msg :
             pgr_msg(notice.str().c_str());
     } catch (AssertFailedException &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch (std::exception &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch(...) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << "Caught unknown exception!";
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     }
 }