PGROUTING: pgrouting::vrp::pickdeliver::Vehicle_pickDeliver Class Reference
pgrouting::vrp::pickdeliver::Vehicle_pickDeliver Class Reference
#include "vehicle_pickDeliver.h"
Public Types
typedef std::tuple< int, int, size_t, double, double > Cost
Public Member Functions
Vehicle_pickDeliver (size_t idx, int64_t kind, const Vehicle_node &starting_site, const Vehicle_node &ending_site, double p_capacity, double p_speed)
Vehicle_pickDeliver (const Vehicle_pickDeliver &)=default
double deltaTime (const Vehicle_node &node, POS pos) const
void do_while_feasable (int kind, Identifiers< PD_Orders::OID > &unassigned, Identifiers< PD_Orders::OID > &assigned)
void erase (const Order &order)
Identifiers< size_t > feasable_orders () const
Order get_first_order () const
std::vector< General_vehicle_orders_t > get_postgres_result (int vid) const
Order get_worse_order (Identifiers< size_t > of_this_subset) const
bool has_order (const Order &order) const
int64_t id () const
size_t idx () const
void insert (const Order &order)
Inserts an order.
POS insert_less_travel_time (const Vehicle_node &node, POS after_pos=0)
bool is_order_feasable (const Order &order) const
bool is_phony ()
PD_Orders orders () const
Identifiers< size_t > orders_in_vehicle () const
size_t orders_size () const
size_t pop_back ()
The order that is picked last is removed.
size_t pop_front ()
std::pair< POS, POS > position_limits (const Vehicle_node node) const
void push_back (const Order &order)
puts an order at the end of the truck
void push_front (const Order &order)
Puts an order at the end front of the truck.
void reset_id (int64_t)
void set_compatibles (const PD_Orders &orders)
void swap (POS i, POS j)
Swap two nodes in the path.
deque like functions
Returns
True if the operation was performed
Warning
Assertions are performed for out of range operations
no feasability nor time window or capacity violations checks are performed
Todo:
TODO more deque like functions here
void invariant () const
Invariant The path must:
void insert (POS pos, Vehicle_node node)
@ {
POS insert (std::pair< POS, POS > position_limits, const Vehicle_node &node)
Insert node in best position of the position_limits.
void push_back (const Vehicle_node &node)
Evaluated: push_back a node to the path.
void push_front (const Vehicle_node &node)
Evaluated: push_back a node to the path.
void erase (const Vehicle_node &node)
Erase node.id()
void erase (POS pos)
Erase node at pos from the path.
bool empty () const
return true when no nodes are in the truck
Cost cost () const
bool cost_compare (const Cost &, const Cost &) const
double duration () const
double total_wait_time () const
double total_travel_time () const
double total_service_time () const
double free_time () const
int twvTot () const
int cvTot () const
bool has_twv () const
bool has_cv () const
bool is_feasable () const
Vehicle_node start_site () const
const Vehicle_node end_site () const
double speed () const
double capacity () const
Evaluation
Path evaluation is done incrementally: from a given position to the end of the path, and intermediate values are cached on each node.
So, for example, changing the path at position 100: the evaluation function should be called as evaluate(100, maxcapacity) and from that position to the end of the path will be evaluated. None of the "unaffected" positions get reevaluated
void evaluate ()
@ {
void evaluate (POS from)
Evaluate: Evaluate a path from the given position.
accessors
std::deque< Vehicle_node > path () const
@ {
operators
std::string tau () const
Static Public Attributes
static Pgr_messages msg
Protected Types
typedef size_t POS
Protected Attributes
double cost
double m_capacity
Identifiers< PD_Orders::OID > m_feasable_orders
orders that fit in the truck
PD_Orders m_orders
Identifiers< size_t > m_orders_in_vehicle
orders inserted in this vehicle
std::deque< Vehicle_node > m_path
double m_speed
Static Protected Attributes
static Pgr_pickDeliver * problem
Friends
class Initial_solution
std::ostream & operator<< (std::ostream &log, const Vehicle_pickDeliver &v)
class Optimize
Detailed Description
Definition at line 47 of file vehicle_pickDeliver.h.
Member Typedef Documentation
typedef std::tuple< int, int, size_t, double, double > pgrouting::vrp::pickdeliver::Vehicle::Cost inherited
Definition at line 84 of file vehicle.h.
typedef size_t pgrouting::vrp::pickdeliver::Vehicle::POS protected inherited
Definition at line 75 of file vehicle.h.
Constructor & Destructor Documentation
pgrouting::vrp::pickdeliver::Vehicle_pickDeliver::Vehicle_pickDeliver (size_t idx, int64_t kind, const Vehicle_node & starting_site, const Vehicle_node & ending_site, double p_capacity, double p_speed)
pgrouting::vrp::pickdeliver::Vehicle_pickDeliver::Vehicle_pickDeliver (const Vehicle_pickDeliver &) default
Member Function Documentation
double pgrouting::vrp::pickdeliver::Vehicle::capacity () const inline inherited
Definition at line 259 of file vehicle.h.
References pgrouting::vrp::pickdeliver::Vehicle::deltaTime(), pgrouting::vrp::pickdeliver::Vehicle::evaluate(), pgrouting::vrp::pickdeliver::Vehicle::getPosHighLimit(), pgrouting::vrp::pickdeliver::Vehicle::getPosLowLimit(), pgrouting::vrp::pickdeliver::Vehicle::insert_less_travel_time(), pgrouting::vrp::pickdeliver::Vehicle::m_capacity, pgrouting::vrp::pickdeliver::Vehicle::operator<, pgrouting::vrp::pickdeliver::Vehicle::operator<<, pgrouting::vrp::pickdeliver::Vehicle::path(), pgrouting::vrp::pickdeliver::Vehicle::position_limits(), pgrouting::vrp::pickdeliver::Vehicle::swap(), and pgrouting::vrp::pickdeliver::Vehicle::tau().
 {return m_capacity;}
Cost pgrouting::vrp::pickdeliver::Vehicle::cost () const inherited
Referenced by pgrouting::vrp::pickdeliver::Vehicle::is_phony().
bool pgrouting::vrp::pickdeliver::Vehicle::cost_compare (const Cost & , const Cost &) const inherited
Referenced by pgrouting::vrp::pickdeliver::Vehicle::is_phony().
int pgrouting::vrp::pickdeliver::Vehicle::cvTot () const inline inherited
Definition at line 242 of file vehicle.h.
Referenced by pgrouting::vrp::pickdeliver::Vehicle::has_cv().
{
          return m_path.back().cvTot();
      }
double pgrouting::vrp::pickdeliver::Vehicle::deltaTime (const Vehicle_node & node, POS pos) const inherited
Referenced by pgrouting::vrp::pickdeliver::Vehicle::capacity().
void pgrouting::vrp::pickdeliver::Vehicle_pickDeliver::do_while_feasable (int kind, Identifiers< PD_Orders::OID > & unassigned, Identifiers< PD_Orders::OID > & assigned)
Referenced by orders_in_vehicle().
double pgrouting::vrp::pickdeliver::Vehicle::duration () const inline inherited
Definition at line 224 of file vehicle.h.
Referenced by pgrouting::vrp::pickdeliver::Vehicle::free_time().
{
          return m_path.back().departure_time();
      }
bool pgrouting::vrp::pickdeliver::Vehicle::empty () const inherited
return true when no nodes are in the truck
True: S E
False: S <nodes> E
Referenced by pgrouting::vrp::pickdeliver::Vehicle::is_phony().
const Vehicle_node pgrouting::vrp::pickdeliver::Vehicle::end_site () const inline inherited
Definition at line 257 of file vehicle.h.
 {return m_path.back();}
void pgrouting::vrp::pickdeliver::Vehicle_pickDeliver::erase (const Order & order)
Referenced by orders_in_vehicle().
void pgrouting::vrp::pickdeliver::Vehicle::erase (const Vehicle_node & node) inherited
Erase node.id()
Note
start and ending nodes cannot be erased
Numbers are positions before: S .... node.id() .... E after: S .... .... E
Referenced by pgrouting::vrp::pickdeliver::Vehicle::is_phony().
void pgrouting::vrp::pickdeliver::Vehicle::erase (POS pos) inherited
Erase node at pos from the path.
Note
start and ending nodes cannot be erased
Numbers are positions before: S 1 2 3 4 5 6 pos 8 9 E after: S 1 2 3 4 5 6 8 9 E
Parameters
[in] pos to be erased.
void pgrouting::vrp::pickdeliver::Vehicle::evaluate () inherited
@ {
Evaluate: Evaluate the whole path from the start.
Referenced by pgrouting::vrp::pickdeliver::Vehicle::capacity().
void pgrouting::vrp::pickdeliver::Vehicle::evaluate (POS from) inherited
Evaluate: Evaluate a path from the given position.
Parameters
[in] from The starting position in the path for evaluation to the end of the path.
Identifiers<size_t> pgrouting::vrp::pickdeliver::Vehicle_pickDeliver::feasable_orders () const inline
Definition at line 74 of file vehicle_pickDeliver.h.
References m_feasable_orders.
 {return m_feasable_orders;}
double pgrouting::vrp::pickdeliver::Vehicle::free_time () const inline inherited
Definition at line 236 of file vehicle.h.
References pgrouting::vrp::pickdeliver::Vehicle::duration(), and pgrouting::vrp::pickdeliver::Vehicle::total_wait_time().
{
          return total_wait_time() + (m_path[0].closes() - duration());
      }
Order pgrouting::vrp::pickdeliver::Vehicle_pickDeliver::get_first_order () const
Referenced by orders_in_vehicle().
std::vector<General_vehicle_orders_t> pgrouting::vrp::pickdeliver::Vehicle::get_postgres_result (int vid) const inherited
Order pgrouting::vrp::pickdeliver::Vehicle_pickDeliver::get_worse_order (Identifiers< size_t > of_this_subset) const
Referenced by orders_in_vehicle().
bool pgrouting::vrp::pickdeliver::Vehicle::has_cv () const inline inherited
Definition at line 248 of file vehicle.h.
References pgrouting::vrp::pickdeliver::Vehicle::cvTot().
Referenced by pgrouting::vrp::pickdeliver::Vehicle::is_feasable().
{
          return cvTot() != 0;
      }
bool pgrouting::vrp::pickdeliver::Vehicle_pickDeliver::has_order (const Order & order) const
Referenced by orders_in_vehicle().
bool pgrouting::vrp::pickdeliver::Vehicle::has_twv () const inline inherited
Definition at line 245 of file vehicle.h.
References pgrouting::vrp::pickdeliver::Vehicle::twvTot().
Referenced by pgrouting::vrp::pickdeliver::Vehicle::is_feasable().
{
          return twvTot() != 0;
      }
int64_t pgrouting::Identifier::id () const inherited
Definition at line 42 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Dnode::distance(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::vrp::pickdeliver::Vehicle::is_phony(), pgrouting::vrp::Vehicle::is_phony(), pgrouting::vrp::Optimize::move_reduce_cost(), pgrouting::vrp::operator<<(), pgrouting::operator<<(), pgrouting::vrp::Base_node::operator==(), pgrouting::vrp::Node::operator==(), pgrouting::vrp::Node::print(), pgrouting::vrp::Base_node::print(), pgrouting::vrp::pickdeliver::Tw_node::set_Did(), and pgrouting::vrp::pickdeliver::Tw_node::set_Pid().
                      {
     return m_id;
 }
size_t pgrouting::Identifier::idx () const inherited
Definition at line 37 of file identifier.cpp.
References pgrouting::Identifier::m_idx.
Referenced by pgrouting::vrp::Vehicle_pickDeliver::erase(), pgrouting::vrp::Vehicle::erase(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Vehicle_pickDeliver::has_order(), pgrouting::vrp::Vehicle::insert(), pgrouting::vrp::Vehicle_pickDeliver::insert(), pgrouting::vrp::operator<<(), pgrouting::operator<<(), pgrouting::vrp::Base_node::operator==(), pgrouting::vrp::Node::operator==(), pgrouting::vrp::Tw_node::operator==(), pgrouting::vrp::Node::print(), pgrouting::vrp::Base_node::print(), pgrouting::vrp::Vehicle_pickDeliver::push_back(), pgrouting::vrp::Vehicle_pickDeliver::push_front(), pgrouting::vrp::Order::set_compatibles(), pgrouting::vrp::Solution::sort_by_id(), pgrouting::vrp::Optimize::swap_worse(), pgrouting::vrp::Vehicle::tau(), and pgrouting::vrp::Tw_node::travel_time_to().
                       {
     return m_idx;
 }
void pgrouting::vrp::pickdeliver::Vehicle::insert (POS pos, Vehicle_node node) inherited
@ {
Insert node at pos position.
Parameters
[in] pos The position that the node should be inserted.
[in] node The node to insert.
Referenced by pgrouting::vrp::pickdeliver::Vehicle::is_phony().
POS pgrouting::vrp::pickdeliver::Vehicle::insert (std::pair< POS, POS > position_limits, const Vehicle_node & node) inherited
Insert node in best position of the position_limits.
Parameters
[in] position_limits
[in] node The node to insert
Returns
position where it was inserted
void pgrouting::vrp::pickdeliver::Vehicle_pickDeliver::insert (const Order & order)
Inserts an order.
Precondition: !has_order(order)
Postcondition: has_order(order) !has_cv();
Before: S <nodes> E
  After: S ....P .... D .... E
push_back is performed when
pickup
Can generate time window violation No capacity violation
Referenced by orders_in_vehicle().
POS pgrouting::vrp::pickdeliver::Vehicle::insert_less_travel_time (const Vehicle_node & node, POS after_pos = 0) inherited
Referenced by pgrouting::vrp::pickdeliver::Vehicle::capacity().
void pgrouting::vrp::pickdeliver::Vehicle::invariant () const inherited
Invariant The path must:
have at least 2 nodes
first node of the path must be Start node
last node of the path must be End node
path: S ..... E
Referenced by pgrouting::vrp::pickdeliver::Vehicle::is_phony().
bool pgrouting::vrp::pickdeliver::Vehicle::is_feasable () const inline inherited
Definition at line 251 of file vehicle.h.
References pgrouting::vrp::pickdeliver::Vehicle::has_cv(), and pgrouting::vrp::pickdeliver::Vehicle::has_twv().
{
          return !(has_twv() ||  has_cv());
      }
bool pgrouting::vrp::pickdeliver::Vehicle_pickDeliver::is_order_feasable (const Order & order) const
bool pgrouting::vrp::pickdeliver::Vehicle::is_phony () inline inherited
Definition at line 97 of file vehicle.h.
References pgrouting::vrp::pickdeliver::Vehicle::cost(), pgrouting::vrp::pickdeliver::Vehicle::cost_compare(), pgrouting::vrp::pickdeliver::Vehicle::empty(), pgrouting::vrp::pickdeliver::Vehicle::erase(), pgrouting::Identifier::id(), pgrouting::vrp::pickdeliver::Vehicle::insert(), pgrouting::vrp::pickdeliver::Vehicle::invariant(), pgrouting::vrp::pickdeliver::Vehicle::pop_back(), pgrouting::vrp::pickdeliver::Vehicle::pop_front(), pgrouting::vrp::pickdeliver::Vehicle::position_limits(), pgrouting::vrp::pickdeliver::Vehicle::push_back(), and pgrouting::vrp::pickdeliver::Vehicle::push_front().
 {return id() < 0;}
PD_Orders pgrouting::vrp::pickdeliver::Vehicle_pickDeliver::orders () const inline
Definition at line 76 of file vehicle_pickDeliver.h.
References m_orders.
 {return m_orders;}
Identifiers<size_t> pgrouting::vrp::pickdeliver::Vehicle_pickDeliver::orders_in_vehicle () const inline
Definition at line 78 of file vehicle_pickDeliver.h.
References do_while_feasable(), erase(), get_first_order(), get_worse_order(), has_order(), insert(), m_orders_in_vehicle, operator<<, pop_back(), pop_front(), push_back(), and push_front().
 {return m_orders_in_vehicle;}
size_t pgrouting::vrp::pickdeliver::Vehicle_pickDeliver::orders_size () const inline
Definition at line 77 of file vehicle_pickDeliver.h.
References Identifiers< T >::size().
 {return m_orders_in_vehicle.size();}
std::deque< Vehicle_node > pgrouting::vrp::pickdeliver::Vehicle::path () const inherited
@ {
Referenced by pgrouting::vrp::pickdeliver::Vehicle::capacity().
size_t pgrouting::vrp::pickdeliver::Vehicle_pickDeliver::pop_back ()
The order that is picked last is removed.
Returns
id of the removed order
Referenced by orders_in_vehicle().
size_t pgrouting::vrp::pickdeliver::Vehicle_pickDeliver::pop_front ()
Referenced by orders_in_vehicle().
std::pair<POS, POS> pgrouting::vrp::pickdeliver::Vehicle::position_limits (const Vehicle_node node) const inherited
Referenced by pgrouting::vrp::pickdeliver::Vehicle::capacity(), and pgrouting::vrp::pickdeliver::Vehicle::is_phony().
void pgrouting::vrp::pickdeliver::Vehicle_pickDeliver::push_back (const Order & order)
puts an order at the end of the truck
Precondition: !has_order(order)
Postcondition: has_order(order) !has_cv();
Before: S <nodes> E
  After: S <nodes> P D E
Can generate time window violation No capacity violation
Referenced by orders_in_vehicle().
void pgrouting::vrp::pickdeliver::Vehicle::push_back (const Vehicle_node & node) inherited
Evaluated: push_back a node to the path.
before: S <nodes> E
after: S <nodes> n E
Parameters
[in] node to be push_back.
Referenced by pgrouting::vrp::pickdeliver::Vehicle::is_phony().
void pgrouting::vrp::pickdeliver::Vehicle_pickDeliver::push_front (const Order & order)
Puts an order at the end front of the truck.
Precondition: !has_order(order)
Postcondition: has_order(order) !has_cv();
Before: S <nodes> E
  After: S P D <nodes> E
Can generate time window violation No capacity violation
Referenced by orders_in_vehicle().
void pgrouting::vrp::pickdeliver::Vehicle::push_front (const Vehicle_node & node) inherited
Evaluated: push_back a node to the path.
before: S <nodes> E
after: S n <nodes> E
Parameters
[in] node to be push_back.
Referenced by pgrouting::vrp::pickdeliver::Vehicle::is_phony().
void pgrouting::Identifier::reset_id (int64_t _id) inherited
Definition at line 47 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Tw_node::Tw_node().
{
     m_id = _id;
 }
void pgrouting::vrp::pickdeliver::Vehicle_pickDeliver::set_compatibles (const PD_Orders & orders)
double pgrouting::vrp::pickdeliver::Vehicle::speed () const inline inherited
Definition at line 258 of file vehicle.h.
References pgrouting::vrp::pickdeliver::Vehicle::m_speed.
 {return m_speed;}
Vehicle_node pgrouting::vrp::pickdeliver::Vehicle::start_site () const inline inherited
Definition at line 254 of file vehicle.h.
{
          return m_path.front();
      }
void pgrouting::vrp::pickdeliver::Vehicle::swap (POS i, POS j) inherited
Swap two nodes in the path.
Before: S <nodesA> I <nodesB> J <nodesC> E
After: S <nodesA> J <nodesB> I <nodesC> E
Parameters
[in] i The position of the first node to swap.
[in] j The position of the second node to swap.
Referenced by pgrouting::vrp::pickdeliver::Vehicle::capacity().
std::string pgrouting::vrp::pickdeliver::Vehicle::tau () const inherited
Referenced by pgrouting::vrp::pickdeliver::Vehicle::capacity().
double pgrouting::vrp::pickdeliver::Vehicle::total_service_time () const inline inherited
Definition at line 233 of file vehicle.h.
{
          return m_path.back().total_service_time();
      }
double pgrouting::vrp::pickdeliver::Vehicle::total_travel_time () const inline inherited
Definition at line 230 of file vehicle.h.
{
          return m_path.back().total_travel_time();
      }
double pgrouting::vrp::pickdeliver::Vehicle::total_wait_time () const inline inherited
Definition at line 227 of file vehicle.h.
Referenced by pgrouting::vrp::pickdeliver::Vehicle::free_time().
{
          return m_path.back().total_wait_time();
      }
int pgrouting::vrp::pickdeliver::Vehicle::twvTot () const inline inherited
Definition at line 239 of file vehicle.h.
Referenced by pgrouting::vrp::pickdeliver::Vehicle::has_twv().
{
          return m_path.back().twvTot();
      }
Friends And Related Function Documentation
friend class Initial_solution friend
Definition at line 58 of file vehicle_pickDeliver.h.
std::ostream& operator<< (std::ostream & log, const Vehicle_pickDeliver & v) friend
Referenced by orders_in_vehicle().
friend class Optimize friend
Definition at line 59 of file vehicle_pickDeliver.h.
Member Data Documentation
double pgrouting::vrp::pickdeliver::Vehicle_pickDeliver::cost protected
Definition at line 49 of file vehicle_pickDeliver.h.
double pgrouting::vrp::pickdeliver::Vehicle::m_capacity protected inherited
Definition at line 77 of file vehicle.h.
Referenced by pgrouting::vrp::pickdeliver::Vehicle::capacity().
Identifiers<PD_Orders::OID> pgrouting::vrp::pickdeliver::Vehicle_pickDeliver::m_feasable_orders protected
orders that fit in the truck
Definition at line 54 of file vehicle_pickDeliver.h.
Referenced by feasable_orders().
PD_Orders pgrouting::vrp::pickdeliver::Vehicle_pickDeliver::m_orders protected
Definition at line 52 of file vehicle_pickDeliver.h.
Referenced by orders().
Identifiers<size_t> pgrouting::vrp::pickdeliver::Vehicle_pickDeliver::m_orders_in_vehicle protected
orders inserted in this vehicle
Definition at line 51 of file vehicle_pickDeliver.h.
Referenced by orders_in_vehicle().
std::deque< Vehicle_node > pgrouting::vrp::pickdeliver::Vehicle::m_path protected inherited
Definition at line 76 of file vehicle.h.
double pgrouting::vrp::pickdeliver::Vehicle::m_speed protected inherited
Definition at line 78 of file vehicle.h.
Referenced by pgrouting::vrp::pickdeliver::Vehicle::speed().
Pgr_messages pgrouting::vrp::pickdeliver::PD_problem::msg static inherited
Definition at line 49 of file pd_problem.h.
Pgr_pickDeliver* pgrouting::vrp::pickdeliver::PD_problem::problem static protected inherited
Definition at line 52 of file pd_problem.h.
The documentation for this class was generated from the following file:
/home/wang/mainrepo/include/pickDeliver/vehicle_pickDeliver.h