PGROUTING: COrderInfo Class Reference
COrderInfo Class Reference
#include "VRP_Solver.h"
Public Member Functions
COrderInfo ()
~COrderInfo ()
int getCloseTime ()
int getOpenTime ()
int getOrderId ()
Point getOrderLocation ()
int getOrderUnit ()
int getServiceTime ()
void setCloseTime (int closeTime)
void setOpenTime (int openTime)
void setOrderId (int orderId)
void setOrderLocation (Point location)
void setOrderUnit (int orderUnit)
void setServiceTime (int serviceTime)
Private Attributes
int m_iOrderCloseTime
int m_iOrderId
int m_iOrderOpenTime
int m_iOrderServiceTime
int m_iOrderUnitCount
Point m_ptOrderLocation
Detailed Description
Definition at line 95 of file VRP_Solver.h.
Constructor & Destructor Documentation
COrderInfo::COrderInfo ()
Definition at line 76 of file VRP_Solver.cpp.
 { }
COrderInfo::~COrderInfo ()
Definition at line 77 of file VRP_Solver.cpp.
 { }
Member Function Documentation
int COrderInfo::getCloseTime () inline
Definition at line 103 of file VRP_Solver.h.
References m_iOrderCloseTime.
Referenced by CVRPSolver::getPotentialInsert().
 {return m_iOrderCloseTime;}
int COrderInfo::getOpenTime () inline
Definition at line 100 of file VRP_Solver.h.
References m_iOrderOpenTime.
 {return m_iOrderOpenTime;}
int COrderInfo::getOrderId () inline
Definition at line 115 of file VRP_Solver.h.
References m_iOrderId.
Referenced by CVRPSolver::addOrder(), CVRPSolver::getCostForInsert(), and CVRPSolver::getPotentialInsert().
 {return m_iOrderId; }
Point COrderInfo::getOrderLocation () inline
Definition at line 112 of file VRP_Solver.h.
References m_ptOrderLocation.
 {return m_ptOrderLocation;}
int COrderInfo::getOrderUnit () inline
Definition at line 109 of file VRP_Solver.h.
References m_iOrderUnitCount.
Referenced by CVRPSolver::getPotentialInsert().
 {return m_iOrderUnitCount;}
int COrderInfo::getServiceTime () inline
Definition at line 106 of file VRP_Solver.h.
References m_iOrderServiceTime.
Referenced by CVRPSolver::getPotentialInsert().
 {return m_iOrderServiceTime;}
void COrderInfo::setCloseTime (int closeTime) inline
Definition at line 104 of file VRP_Solver.h.
References m_iOrderCloseTime.
Referenced by loadOrders().
 {m_iOrderCloseTime = closeTime;}
void COrderInfo::setOpenTime (int openTime) inline
Definition at line 101 of file VRP_Solver.h.
References m_iOrderOpenTime.
Referenced by loadOrders().
 {m_iOrderOpenTime = openTime;}
void COrderInfo::setOrderId (int orderId) inline
Definition at line 116 of file VRP_Solver.h.
References m_iOrderId.
Referenced by loadOrders().
 {m_iOrderId = orderId;}
void COrderInfo::setOrderLocation (Point location) inline
Definition at line 113 of file VRP_Solver.h.
References m_ptOrderLocation.
Referenced by loadOrders().
 {m_ptOrderLocation = location;}
void COrderInfo::setOrderUnit (int orderUnit) inline
Definition at line 110 of file VRP_Solver.h.
References m_iOrderUnitCount.
Referenced by loadOrders().
 {m_iOrderUnitCount = orderUnit;}
void COrderInfo::setServiceTime (int serviceTime) inline
Definition at line 107 of file VRP_Solver.h.
References m_iOrderServiceTime.
Referenced by loadOrders().
 {m_iOrderServiceTime = serviceTime;}
Member Data Documentation
int COrderInfo::m_iOrderCloseTime private
Definition at line 124 of file VRP_Solver.h.
Referenced by getCloseTime(), and setCloseTime().
int COrderInfo::m_iOrderId private
Definition at line 127 of file VRP_Solver.h.
Referenced by getOrderId(), and setOrderId().
int COrderInfo::m_iOrderOpenTime private
Definition at line 123 of file VRP_Solver.h.
Referenced by getOpenTime(), and setOpenTime().
int COrderInfo::m_iOrderServiceTime private
Definition at line 125 of file VRP_Solver.h.
Referenced by getServiceTime(), and setServiceTime().
int COrderInfo::m_iOrderUnitCount private
Definition at line 126 of file VRP_Solver.h.
Referenced by getOrderUnit(), and setOrderUnit().
Point COrderInfo::m_ptOrderLocation private
Definition at line 129 of file VRP_Solver.h.
Referenced by getOrderLocation(), and setOrderLocation().
The documentation for this class was generated from the following files:
/home/vicky/pgrouting/pgrouting/pgrouting/src/vrp_basic/src/VRP_Solver.h
/home/vicky/pgrouting/pgrouting/pgrouting/src/vrp_basic/src/VRP_Solver.cpp