PGROUTING: pgrouting::areacontraction::Pgr_contract< G > Class Template Reference
pgrouting::areacontraction::Pgr_contract< G > Class Template Reference
#include "pgr_areaContract.hpp"
Public Member Functions
Pgr_contract (G &graph, Identifiers< V > borderVertices, std::vector< pgrouting::CH_edge > &shortcut_edges, std::ostringstream &debug)
Private Types
typedef G::V V
Private Member Functions
void perform_areaContraction (G &graph, Identifiers< V > borderVertices, std::ostringstream &debug)
Detailed Description
template<class G>
class pgrouting::areacontraction::Pgr_contract< G >
Definition at line 44 of file pgr_areaContract.hpp.
Member Typedef Documentation
template<class G> typedef G::V pgrouting::areacontraction::Pgr_contract< G >::V private
Definition at line 45 of file pgr_areaContract.hpp.
Constructor & Destructor Documentation
template<class G> pgrouting::areacontraction::Pgr_contract< G >::Pgr_contract (G & graph, Identifiers< V > borderVertices, std::vector< pgrouting::CH_edge > & shortcut_edges, std::ostringstream & debug) inline
Definition at line 64 of file pgr_areaContract.hpp.
References pgrouting::areacontraction::Pgr_contract< G >::perform_areaContraction().
{
 #ifndef NDEBUG
     debug << "Graph before area contraction"
         << std::endl;
     graph.print_graph(debug);
     debug << "Performing area contraction"
         << std::endl;
 #endif
     perform_areaContraction(graph, borderVertices, debug);
 #ifndef NDEBUG
     debug << "Graph after area contraction"
         << std::endl;
     graph.print_graph(debug);
 #endif
     debug << "Printing shortcuts\n";
     for (auto shortcut : graph.shortcuts) {
         debug << shortcut;
     shortcut_edges.push_back(shortcut);
   }
 }
Member Function Documentation
template<class G> void pgrouting::areacontraction::Pgr_contract< G >::perform_areaContraction (G & graph, Identifiers< V > borderVertices, std::ostringstream & debug) inline private
Definition at line 48 of file pgr_areaContract.hpp.
References pgrouting::areacontraction::Pgr_areaContraction< G >::doContraction(), and pgrouting::areacontraction::Pgr_areaContraction< G >::setBorderVertices().
Referenced by pgrouting::areacontraction::Pgr_contract< G >::Pgr_contract().
{
         Pgr_areaContraction<G> areaContractor;
         debug << "Setting borderVertices";
         areaContractor.setBorderVertices(borderVertices);
         try {
             areaContractor.doContraction(graph);
         }
         catch ( ... ) {
             debug << "Caught unknown exception!\n";
         }
     }
The documentation for this class was generated from the following file:
/home/vicky/pgrouting/pgrouting/pgrouting/src/areaContraction/src/pgr_areaContract.hpp