PGROUTING: CSolutionInfo Class Reference
CSolutionInfo Class Reference
#include "VRP_Solver.h"
Public Member Functions
CSolutionInfo ()
~CSolutionInfo ()
bool addTour (CTourInfo &tour)
int getOrderServed ()
double getTotalCost ()
double getTotalDistance ()
double getTotalTravelTime ()
CTourInfo & getTour (int pos)
size_t getTourCount ()
std::vector< CTourInfo > getTourInfoVector ()
int getUnservedOrderAt (int pos)
size_t getUnservedOrderCount ()
int getUnusedVehicleAt (int pos)
size_t getUnusedVehicleCount ()
int getVehicleUsed ()
bool init (std::vector< int > vecOrder, int iTotalOrder, std::vector< int > vecVehicle)
void removeOrder (int pos)
void removeVehicle (int pos)
void replaceTour (CTourInfo curTour)
void replaceTourAt (int index, CTourInfo curTour)
Private Attributes
double m_dTotalCost
double m_dTotalDistance
double m_dTotalTravelTime
int m_iOrdersServed
int m_iTotalOrders
int m_iVehicleUsed
std::vector< CTourInfo > m_vtourAll
std::vector< int > m_vUnservedOrderId
std::vector< int > m_vUnusedVehicles
Detailed Description
Definition at line 240 of file VRP_Solver.h.
Constructor & Destructor Documentation
CSolutionInfo::CSolutionInfo ()
Definition at line 109 of file VRP_Solver.cpp.
 { }
CSolutionInfo::~CSolutionInfo ()
Definition at line 110 of file VRP_Solver.cpp.
 { }
Member Function Documentation
bool CSolutionInfo::addTour (CTourInfo & tour)
Definition at line 144 of file VRP_Solver.cpp.
References CTourInfo::getCost(), CTourInfo::getDistance(), CTourInfo::getOrderVector(), CTourInfo::getTravelTime(), CTourInfo::getVehicleId(), m_dTotalCost, m_dTotalDistance, m_dTotalTravelTime, m_iOrdersServed, m_iVehicleUsed, m_vtourAll, m_vUnservedOrderId, and m_vUnusedVehicles.
Referenced by CVRPSolver::generateInitialSolution().
{
     m_vtourAll.push_back(tour);
     int vid = tour.getVehicleId();
     std::vector<int>::iterator it;
     it = std::find(m_vUnusedVehicles.begin(), m_vUnusedVehicles.end(), vid);
     if (it != m_vUnusedVehicles.end()) {
         m_vUnusedVehicles.erase(it);
     }
     m_iVehicleUsed++;
     m_dTotalDistance += tour.getDistance();
     m_dTotalTravelTime += tour.getTravelTime();
     m_dTotalCost += tour.getCost();
     std::vector<int> vecOrders = tour.getOrderVector();
     m_iOrdersServed += static_cast<int>(vecOrders.size());
     for (const auto &order : vecOrders) {
         int oid = order;
         it = std::find(m_vUnservedOrderId.begin(), m_vUnservedOrderId.end(), oid);
         if (it != m_vUnservedOrderId.end()) {
             m_vUnservedOrderId.erase(it);
         }
     }
     return true;
 }
int CSolutionInfo::getOrderServed () inline
Definition at line 246 of file VRP_Solver.h.
References m_iOrdersServed.
Referenced by CVRPSolver::insertUnservedOrders(), and CVRPSolver::updateFinalSolution().
 {return m_iOrdersServed;}
double CSolutionInfo::getTotalCost () inline
Definition at line 262 of file VRP_Solver.h.
References m_dTotalCost.
Referenced by print_solution(), and CVRPSolver::updateFinalSolution().
 {return m_dTotalCost;}
double CSolutionInfo::getTotalDistance () inline
Definition at line 263 of file VRP_Solver.h.
References m_dTotalDistance.
Referenced by print_solution(), and CVRPSolver::updateFinalSolution().
 {return m_dTotalDistance;}
double CSolutionInfo::getTotalTravelTime () inline
Definition at line 264 of file VRP_Solver.h.
References m_dTotalTravelTime.
Referenced by print_solution(), and CVRPSolver::updateFinalSolution().
 {return m_dTotalTravelTime;}
CTourInfo& CSolutionInfo::getTour (int pos) inline
Definition at line 250 of file VRP_Solver.h.
References m_vtourAll.
Referenced by CVRPSolver::addOrderAtTour(), CVRPSolver::attemptVehicleExchange(), find_vrp_solution(), CVRPSolver::insertUnservedOrders(), and print_solution().
 {return m_vtourAll[pos];}
size_t CSolutionInfo::getTourCount () inline
Definition at line 252 of file VRP_Solver.h.
References m_vtourAll.
Referenced by CVRPSolver::attemptVehicleExchange().
 {return (m_vtourAll.size());}
std::vector<CTourInfo> CSolutionInfo::getTourInfoVector () inline
Definition at line 273 of file VRP_Solver.h.
References m_vtourAll.
Referenced by find_vrp_solution(), CVRPSolver::insertUnservedOrders(), and print_solution().
 {return m_vtourAll;}
int CSolutionInfo::getUnservedOrderAt (int pos) inline
Definition at line 265 of file VRP_Solver.h.
References m_vUnservedOrderId.
Referenced by CVRPSolver::generateInitialSolution(), and CVRPSolver::insertUnservedOrders().
 {return m_vUnservedOrderId[pos];}
size_t CSolutionInfo::getUnservedOrderCount () inline
Definition at line 254 of file VRP_Solver.h.
References m_vUnservedOrderId.
Referenced by CVRPSolver::generateInitialSolution().
 {return m_vUnservedOrderId.size();}
int CSolutionInfo::getUnusedVehicleAt (int pos) inline
Definition at line 257 of file VRP_Solver.h.
References m_vUnusedVehicles.
Referenced by CVRPSolver::generateInitialSolution().
 {return m_vUnusedVehicles[pos];}
size_t CSolutionInfo::getUnusedVehicleCount () inline
Definition at line 255 of file VRP_Solver.h.
References m_vUnusedVehicles.
Referenced by CVRPSolver::generateInitialSolution().
 {return m_vUnusedVehicles.size();}
int CSolutionInfo::getVehicleUsed () inline
Definition at line 245 of file VRP_Solver.h.
References m_iVehicleUsed.
 {return m_iVehicleUsed;}
bool CSolutionInfo::init (std::vector< int > vecOrder, int iTotalOrder, std::vector< int > vecVehicle)
Definition at line 129 of file VRP_Solver.cpp.
References m_dTotalCost, m_dTotalDistance, m_dTotalTravelTime, m_iOrdersServed, m_iTotalOrders, m_iVehicleUsed, m_vtourAll, m_vUnservedOrderId, and m_vUnusedVehicles.
Referenced by CVRPSolver::generateInitialSolution(), and CVRPSolver::solveVRP().
{
     m_vUnservedOrderId = vecOrder;
     m_iTotalOrders = iTotalOrder;
     m_vUnusedVehicles = vecVehicle;
     m_vtourAll.clear();
     m_iVehicleUsed = 0;
     m_iOrdersServed = 0;
     m_iTotalOrders = 0;
     m_dTotalCost = 0;
     m_dTotalDistance = 0;
     m_dTotalTravelTime = 0;
     return true;
 }
void CSolutionInfo::removeOrder (int pos) inline
Definition at line 260 of file VRP_Solver.h.
References m_vUnservedOrderId.
Referenced by CVRPSolver::generateInitialSolution().
 {m_vUnservedOrderId.erase(m_vUnservedOrderId.begin() + pos);}
void CSolutionInfo::removeVehicle (int pos) inline
Definition at line 259 of file VRP_Solver.h.
References m_vUnusedVehicles.
Referenced by CVRPSolver::generateInitialSolution().
 {m_vUnusedVehicles.erase(m_vUnusedVehicles.begin() + pos);}
void CSolutionInfo::replaceTour (CTourInfo curTour)
Definition at line 112 of file VRP_Solver.cpp.
References CTourInfo::getVehicleId(), and m_vtourAll.
Referenced by CVRPSolver::applyBestMoveInCurrentSolution().
{
     unsigned int i;
     for (i = 0; i < m_vtourAll.size(); i++) {
         if (m_vtourAll[i].getVehicleId() == curTour.getVehicleId()) {
             m_vtourAll[i] = curTour;
             return;
         }
     }
     return;
 }
void CSolutionInfo::replaceTourAt (int index, CTourInfo curTour)
Definition at line 123 of file VRP_Solver.cpp.
References m_vtourAll.
Referenced by CVRPSolver::attemptVehicleExchange().
{
     if (index < 0 ||  (unsigned int) index >= m_vtourAll.size())
         return;
     m_vtourAll[index] = curTour;
 }
Member Data Documentation
double CSolutionInfo::m_dTotalCost private
Definition at line 285 of file VRP_Solver.h.
Referenced by addTour(), getTotalCost(), and init().
double CSolutionInfo::m_dTotalDistance private
Definition at line 286 of file VRP_Solver.h.
Referenced by addTour(), getTotalDistance(), and init().
double CSolutionInfo::m_dTotalTravelTime private
Definition at line 287 of file VRP_Solver.h.
Referenced by addTour(), getTotalTravelTime(), and init().
int CSolutionInfo::m_iOrdersServed private
Definition at line 283 of file VRP_Solver.h.
Referenced by addTour(), getOrderServed(), and init().
int CSolutionInfo::m_iTotalOrders private
Definition at line 284 of file VRP_Solver.h.
Referenced by init().
int CSolutionInfo::m_iVehicleUsed private
Definition at line 282 of file VRP_Solver.h.
Referenced by addTour(), getVehicleUsed(), and init().
std::vector<CTourInfo> CSolutionInfo::m_vtourAll private
Definition at line 279 of file VRP_Solver.h.
Referenced by addTour(), getTour(), getTourCount(), getTourInfoVector(), init(), replaceTour(), and replaceTourAt().
std::vector<int> CSolutionInfo::m_vUnservedOrderId private
Definition at line 280 of file VRP_Solver.h.
Referenced by addTour(), getUnservedOrderAt(), getUnservedOrderCount(), init(), and removeOrder().
std::vector<int> CSolutionInfo::m_vUnusedVehicles private
Definition at line 281 of file VRP_Solver.h.
Referenced by addTour(), getUnusedVehicleAt(), getUnusedVehicleCount(), init(), and removeVehicle().
The documentation for this class was generated from the following files:
/home/vicky/pgrouting/pgrouting/pgrouting/src/vrp_basic/src/VRP_Solver.h
/home/vicky/pgrouting/pgrouting/pgrouting/src/vrp_basic/src/VRP_Solver.cpp