PGROUTING: pgrouting::vrp::pickdeliver::Vehicle Class Reference
pgrouting::vrp::pickdeliver::Vehicle Class Reference
Vehicle with time windows.
#include "vehicle.h"
Public Types
typedef std::tuple< int, int, size_t, double, double > Cost
Public Member Functions
Vehicle (size_t idx, int64_t kind, const Vehicle_node &starting_site, const Vehicle_node &ending_site, double m_capacity, double speed)
double deltaTime (const Vehicle_node &node, POS pos) const
std::vector< General_vehicle_orders_t > get_postgres_result (int vid) const
int64_t id () const
size_t idx () const
POS insert_less_travel_time (const Vehicle_node &node, POS after_pos=0)
bool is_phony ()
std::pair< POS, POS > position_limits (const Vehicle_node node) const
void reset_id (int64_t)
void swap (POS i, POS j)
Swap two nodes in the path.
deque like functions
Returns
True if the operation was performed
Warning
Assertions are performed for out of range operations
no feasability nor time window or capacity violations checks are performed
Todo:
TODO more deque like functions here
void invariant () const
Invariant The path must:
void insert (POS pos, Vehicle_node node)
@ {
POS insert (std::pair< POS, POS > position_limits, const Vehicle_node &node)
Insert node in best position of the position_limits.
void push_back (const Vehicle_node &node)
Evaluated: push_back a node to the path.
void push_front (const Vehicle_node &node)
Evaluated: push_back a node to the path.
void pop_back ()
Evaluated: pop_back a node to the path.
void pop_front ()
Evaluated: pop_front a node to the path.
void erase (const Vehicle_node &node)
Erase node.id()
void erase (POS pos)
Erase node at pos from the path.
bool empty () const
return true when no nodes are in the truck
Cost cost () const
bool cost_compare (const Cost &, const Cost &) const
double duration () const
double total_wait_time () const
double total_travel_time () const
double total_service_time () const
double free_time () const
int twvTot () const
int cvTot () const
bool has_twv () const
bool has_cv () const
bool is_feasable () const
Vehicle_node start_site () const
const Vehicle_node end_site () const
double speed () const
double capacity () const
Evaluation
Path evaluation is done incrementally: from a given position to the end of the path, and intermediate values are cached on each node.
So, for example, changing the path at position 100: the evaluation function should be called as evaluate(100, maxcapacity) and from that position to the end of the path will be evaluated. None of the "unaffected" positions get reevaluated
void evaluate ()
@ {
void evaluate (POS from)
Evaluate: Evaluate a path from the given position.
accessors
std::deque< Vehicle_node > path () const
@ {
Static Public Attributes
static Pgr_messages msg
Protected Types
typedef size_t POS
Protected Attributes
double m_capacity
std::deque< Vehicle_node > m_path
double m_speed
Static Protected Attributes
static Pgr_pickDeliver * problem
Private Member Functions
POS getPosHighLimit (const Vehicle_node &node) const
POS getPosLowLimit (const Vehicle_node &node) const
operators
std::string tau () const
std::ostream & operator<< (std::ostream &log, const Vehicle &v)
@ {
bool operator< (const Vehicle &lhs, const Vehicle &rhs)
Detailed Description
Vehicle with time windows.
General functionality for a vehicle in a PICKDELIVER problem
Recommended use:
Class my_vehicle : public vechicle
Note
All members return true when the operation is successful
A vehicle is a sequence of Vehicle_node from starting site to ending site. has: capacity speed factor TODO(vicky)
See also
Vehicle_node
Definition at line 73 of file vehicle.h.
Member Typedef Documentation
typedef std::tuple< int, int, size_t, double, double > pgrouting::vrp::pickdeliver::Vehicle::Cost
Definition at line 84 of file vehicle.h.
typedef size_t pgrouting::vrp::pickdeliver::Vehicle::POS protected
Definition at line 75 of file vehicle.h.
Constructor & Destructor Documentation
pgrouting::vrp::pickdeliver::Vehicle::Vehicle (size_t idx, int64_t kind, const Vehicle_node & starting_site, const Vehicle_node & ending_site, double m_capacity, double speed)
Member Function Documentation
double pgrouting::vrp::pickdeliver::Vehicle::capacity () const inline
Definition at line 259 of file vehicle.h.
References deltaTime(), evaluate(), getPosHighLimit(), getPosLowLimit(), insert_less_travel_time(), m_capacity, operator<, operator<<, path(), position_limits(), swap(), and tau().
 {return m_capacity;}
Cost pgrouting::vrp::pickdeliver::Vehicle::cost () const
Referenced by is_phony().
bool pgrouting::vrp::pickdeliver::Vehicle::cost_compare (const Cost & , const Cost &) const
Referenced by is_phony().
int pgrouting::vrp::pickdeliver::Vehicle::cvTot () const inline
Definition at line 242 of file vehicle.h.
Referenced by has_cv().
{
          return m_path.back().cvTot();
      }
double pgrouting::vrp::pickdeliver::Vehicle::deltaTime (const Vehicle_node & node, POS pos) const
Referenced by capacity().
double pgrouting::vrp::pickdeliver::Vehicle::duration () const inline
Definition at line 224 of file vehicle.h.
Referenced by free_time().
{
          return m_path.back().departure_time();
      }
bool pgrouting::vrp::pickdeliver::Vehicle::empty () const
return true when no nodes are in the truck
True: S E
False: S <nodes> E
Referenced by is_phony().
const Vehicle_node pgrouting::vrp::pickdeliver::Vehicle::end_site () const inline
Definition at line 257 of file vehicle.h.
 {return m_path.back();}
void pgrouting::vrp::pickdeliver::Vehicle::erase (const Vehicle_node & node)
Erase node.id()
Note
start and ending nodes cannot be erased
Numbers are positions before: S .... node.id() .... E after: S .... .... E
Referenced by is_phony().
void pgrouting::vrp::pickdeliver::Vehicle::erase (POS pos)
Erase node at pos from the path.
Note
start and ending nodes cannot be erased
Numbers are positions before: S 1 2 3 4 5 6 pos 8 9 E after: S 1 2 3 4 5 6 8 9 E
Parameters
[in] pos to be erased.
void pgrouting::vrp::pickdeliver::Vehicle::evaluate ()
@ {
Evaluate: Evaluate the whole path from the start.
Referenced by capacity().
void pgrouting::vrp::pickdeliver::Vehicle::evaluate (POS from)
Evaluate: Evaluate a path from the given position.
Parameters
[in] from The starting position in the path for evaluation to the end of the path.
double pgrouting::vrp::pickdeliver::Vehicle::free_time () const inline
Definition at line 236 of file vehicle.h.
References duration(), and total_wait_time().
{
          return total_wait_time() + (m_path[0].closes() - duration());
      }
std::vector<General_vehicle_orders_t> pgrouting::vrp::pickdeliver::Vehicle::get_postgres_result (int vid) const
POS pgrouting::vrp::pickdeliver::Vehicle::getPosHighLimit (const Vehicle_node & node) const private
Referenced by capacity().
POS pgrouting::vrp::pickdeliver::Vehicle::getPosLowLimit (const Vehicle_node & node) const private
Referenced by capacity().
bool pgrouting::vrp::pickdeliver::Vehicle::has_cv () const inline
Definition at line 248 of file vehicle.h.
References cvTot().
Referenced by is_feasable().
{
          return cvTot() != 0;
      }
bool pgrouting::vrp::pickdeliver::Vehicle::has_twv () const inline
Definition at line 245 of file vehicle.h.
References twvTot().
Referenced by is_feasable().
{
          return twvTot() != 0;
      }
int64_t pgrouting::Identifier::id () const inherited
Definition at line 42 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Dnode::distance(), pgrouting::vrp::Vehicle::get_postgres_result(), is_phony(), pgrouting::vrp::Vehicle::is_phony(), pgrouting::vrp::Optimize::move_reduce_cost(), pgrouting::vrp::operator<<(), pgrouting::operator<<(), pgrouting::vrp::Base_node::operator==(), pgrouting::vrp::Node::operator==(), pgrouting::vrp::Node::print(), pgrouting::vrp::Base_node::print(), pgrouting::vrp::pickdeliver::Tw_node::set_Did(), and pgrouting::vrp::pickdeliver::Tw_node::set_Pid().
                      {
     return m_id;
 }
size_t pgrouting::Identifier::idx () const inherited
Definition at line 37 of file identifier.cpp.
References pgrouting::Identifier::m_idx.
Referenced by pgrouting::vrp::Vehicle_pickDeliver::erase(), pgrouting::vrp::Vehicle::erase(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Vehicle_pickDeliver::has_order(), pgrouting::vrp::Vehicle::insert(), pgrouting::vrp::Vehicle_pickDeliver::insert(), pgrouting::vrp::operator<<(), pgrouting::operator<<(), pgrouting::vrp::Base_node::operator==(), pgrouting::vrp::Node::operator==(), pgrouting::vrp::Tw_node::operator==(), pgrouting::vrp::Node::print(), pgrouting::vrp::Base_node::print(), pgrouting::vrp::Vehicle_pickDeliver::push_back(), pgrouting::vrp::Vehicle_pickDeliver::push_front(), pgrouting::vrp::Order::set_compatibles(), pgrouting::vrp::Solution::sort_by_id(), pgrouting::vrp::Optimize::swap_worse(), pgrouting::vrp::Vehicle::tau(), and pgrouting::vrp::Tw_node::travel_time_to().
                       {
     return m_idx;
 }
void pgrouting::vrp::pickdeliver::Vehicle::insert (POS pos, Vehicle_node node)
@ {
Insert node at pos position.
Parameters
[in] pos The position that the node should be inserted.
[in] node The node to insert.
Referenced by is_phony().
POS pgrouting::vrp::pickdeliver::Vehicle::insert (std::pair< POS, POS > position_limits, const Vehicle_node & node)
Insert node in best position of the position_limits.
Parameters
[in] position_limits
[in] node The node to insert
Returns
position where it was inserted
POS pgrouting::vrp::pickdeliver::Vehicle::insert_less_travel_time (const Vehicle_node & node, POS after_pos = 0)
Referenced by capacity().
void pgrouting::vrp::pickdeliver::Vehicle::invariant () const
Invariant The path must:
have at least 2 nodes
first node of the path must be Start node
last node of the path must be End node
path: S ..... E
Referenced by is_phony().
bool pgrouting::vrp::pickdeliver::Vehicle::is_feasable () const inline
Definition at line 251 of file vehicle.h.
References has_cv(), and has_twv().
{
          return !(has_twv() ||  has_cv());
      }
bool pgrouting::vrp::pickdeliver::Vehicle::is_phony () inline
Definition at line 97 of file vehicle.h.
References cost(), cost_compare(), empty(), erase(), pgrouting::Identifier::id(), insert(), invariant(), pop_back(), pop_front(), position_limits(), push_back(), and push_front().
 {return id() < 0;}
std::deque< Vehicle_node > pgrouting::vrp::pickdeliver::Vehicle::path () const
@ {
Referenced by capacity().
void pgrouting::vrp::pickdeliver::Vehicle::pop_back ()
Evaluated: pop_back a node to the path.
before: S <nodes> n E
after: S <nodes> E
Referenced by is_phony().
void pgrouting::vrp::pickdeliver::Vehicle::pop_front ()
Evaluated: pop_front a node to the path.
before: S n <nodes> E
after: S <nodes> E
Referenced by is_phony().
std::pair<POS, POS> pgrouting::vrp::pickdeliver::Vehicle::position_limits (const Vehicle_node node) const
Referenced by capacity(), and is_phony().
void pgrouting::vrp::pickdeliver::Vehicle::push_back (const Vehicle_node & node)
Evaluated: push_back a node to the path.
before: S <nodes> E
after: S <nodes> n E
Parameters
[in] node to be push_back.
Referenced by is_phony().
void pgrouting::vrp::pickdeliver::Vehicle::push_front (const Vehicle_node & node)
Evaluated: push_back a node to the path.
before: S <nodes> E
after: S n <nodes> E
Parameters
[in] node to be push_back.
Referenced by is_phony().
void pgrouting::Identifier::reset_id (int64_t _id) inherited
Definition at line 47 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Tw_node::Tw_node().
{
     m_id = _id;
 }
double pgrouting::vrp::pickdeliver::Vehicle::speed () const inline
Definition at line 258 of file vehicle.h.
References m_speed.
 {return m_speed;}
Vehicle_node pgrouting::vrp::pickdeliver::Vehicle::start_site () const inline
Definition at line 254 of file vehicle.h.
{
          return m_path.front();
      }
void pgrouting::vrp::pickdeliver::Vehicle::swap (POS i, POS j)
Swap two nodes in the path.
Before: S <nodesA> I <nodesB> J <nodesC> E
After: S <nodesA> J <nodesB> I <nodesC> E
Parameters
[in] i The position of the first node to swap.
[in] j The position of the second node to swap.
Referenced by capacity().
std::string pgrouting::vrp::pickdeliver::Vehicle::tau () const
Referenced by capacity().
double pgrouting::vrp::pickdeliver::Vehicle::total_service_time () const inline
Definition at line 233 of file vehicle.h.
{
          return m_path.back().total_service_time();
      }
double pgrouting::vrp::pickdeliver::Vehicle::total_travel_time () const inline
Definition at line 230 of file vehicle.h.
{
          return m_path.back().total_travel_time();
      }
double pgrouting::vrp::pickdeliver::Vehicle::total_wait_time () const inline
Definition at line 227 of file vehicle.h.
Referenced by free_time().
{
          return m_path.back().total_wait_time();
      }
int pgrouting::vrp::pickdeliver::Vehicle::twvTot () const inline
Definition at line 239 of file vehicle.h.
Referenced by has_twv().
{
          return m_path.back().twvTot();
      }
Friends And Related Function Documentation
bool operator< (const Vehicle & lhs, const Vehicle & rhs) friend
Referenced by capacity().
std::ostream& operator<< (std::ostream & log, const Vehicle & v) friend
@ {
Referenced by capacity().
Member Data Documentation
double pgrouting::vrp::pickdeliver::Vehicle::m_capacity protected
Definition at line 77 of file vehicle.h.
Referenced by capacity().
std::deque< Vehicle_node > pgrouting::vrp::pickdeliver::Vehicle::m_path protected
Definition at line 76 of file vehicle.h.
double pgrouting::vrp::pickdeliver::Vehicle::m_speed protected
Definition at line 78 of file vehicle.h.
Referenced by speed().
Pgr_messages pgrouting::vrp::pickdeliver::PD_problem::msg static inherited
Definition at line 49 of file pd_problem.h.
Pgr_pickDeliver* pgrouting::vrp::pickdeliver::PD_problem::problem static protected inherited
Definition at line 52 of file pd_problem.h.
The documentation for this class was generated from the following file:
/home/wang/mainrepo/include/pickDeliver/vehicle.h