PGROUTING: StringTokenizer Class Reference
StringTokenizer Class Reference
#include "utils.h"
Public Member Functions
StringTokenizer ()
StringTokenizer ()
bool getToken (std::string &strToken, long iTokenIndex)
bool getToken (std::string &strToken, int64_t iTokenIndex)
size_t getTokenCount ()
size_t getTokenCount ()
bool getTokens (StringVector &vecTokensRef)
bool getTokens (StringVector &vecTokensRef)
bool parse (std::string strInput, std::string chDelim)
bool parse (std::string strInput, std::string chDelim)
void reset ()
void reset ()
Private Attributes
std::string strInput
StringVector vecTokens
Detailed Description
Definition at line 51 of file utils.h.
Constructor & Destructor Documentation
StringTokenizer::StringTokenizer () inline
Definition at line 53 of file utils.h.
References reset().
{
          reset();
      }
StringTokenizer::StringTokenizer () inline
Definition at line 72 of file Utils.h.
References reset().
{
          reset();
      }
Member Function Documentation
bool StringTokenizer::getToken (std::string & strToken, long iTokenIndex) inline
Definition at line 86 of file utils.h.
References vecTokens.
{
          long lTokenCount = vecTokens.size();
          if (iTokenIndex < 0 || iTokenIndex < lTokenCount) {
              strToken = vecTokens[iTokenIndex];
              return true;
          }
          return false;
      }
bool StringTokenizer::getToken (std::string & strToken, int64_t iTokenIndex) inline
Definition at line 93 of file Utils.h.
References vecTokens.
{
          int64_t lTokenCount = vecTokens.size();
          if (iTokenIndex < 0 ||  iTokenIndex < lTokenCount) {
              strToken = vecTokens[iTokenIndex];
              return true;
          }
          return false;
      }
size_t StringTokenizer::getTokenCount () inline
Definition at line 82 of file utils.h.
References vecTokens.
{
          return vecTokens.size();
      }
size_t StringTokenizer::getTokenCount () inline
Definition at line 89 of file Utils.h.
References vecTokens.
{
          return vecTokens.size();
      }
bool StringTokenizer::getTokens (StringVector & vecTokensRef) inline
Definition at line 95 of file utils.h.
References vecTokens.
Referenced by loadDistanceMatrix(), loadOrders(), and loadVehicles().
{
          vecTokensRef = vecTokens;
          return true;
      }
bool StringTokenizer::getTokens (StringVector & vecTokensRef) inline
Definition at line 102 of file Utils.h.
References vecTokens.
{
          vecTokensRef = vecTokens;
          return true;
      }
bool StringTokenizer::parse (std::string strInput, std::string chDelim) inline
Definition at line 60 of file utils.h.
References vecTokens.
Referenced by loadDistanceMatrix(), loadOrders(), and loadVehicles().
{
          size_t iStartPos = 0;
          while (true) {
              size_t iPos = strInput.find(chDelim[0], iStartPos);
              if (iPos != std::string::npos) {
                  std::string strToken;
                  strToken = strInput.substr(iStartPos, iPos - iStartPos);
                  vecTokens.push_back(strToken);
                  iStartPos = iPos + 1;
              } else if (iPos == std::string::npos && strInput.length() > 0) {
                  std::string strToken;
                  strToken = strInput.substr(iStartPos,
                      strInput.length() - iStartPos);
                  if (strToken.length() > 0)
                      vecTokens.push_back(strToken);
                  break;
              } else {
                  break;
              }
          }
          return true;
      }
bool StringTokenizer::parse (std::string strInput, std::string chDelim) inline
Definition at line 81 of file Utils.h.
References tokenizer::has_more_tokens(), tokenizer::next_token(), and vecTokens.
{
          tokenizer t(strInput, chDelim);
          while (t.has_more_tokens()) {
              vecTokens.push_back(t.next_token());
          }
          return true;
      }
void StringTokenizer::reset () inline
Definition at line 56 of file utils.h.
References strInput, and vecTokens.
Referenced by StringTokenizer().
                   {
          vecTokens.clear();
          strInput = "";
      }
void StringTokenizer::reset () inline
Definition at line 76 of file Utils.h.
References strInput, and vecTokens.
                   {
          vecTokens.clear();
          strInput = "";
      }
Member Data Documentation
std::string StringTokenizer::strInput private
Definition at line 101 of file utils.h.
Referenced by reset().
StringVector StringTokenizer::vecTokens private
Definition at line 102 of file utils.h.
Referenced by getToken(), getTokenCount(), getTokens(), parse(), and reset().
The documentation for this class was generated from the following file:
/home/vicky/pgrouting/pgrouting/pgrouting/src/trsp/src/utils.h