PGROUTING: CVRPSolver Class Reference
CVRPSolver Class Reference
#include "VRP_Solver.h"
Public Member Functions
CVRPSolver ()
~CVRPSolver ()
bool addDepot (CDepotInfo depotInfo)
bool addDepotToOrderCost (int depotId, int orderId, CostPack cost)
bool addOrder (COrderInfo orderInfo)
bool addOrderAtTour (CSolutionInfo &solutionInfo, int tourIndex, int insertIndex, int orderIndex)
bool addOrderToDepotCost (int depotId, int orderId, CostPack cost)
bool addOrderToOrderCost (int firstOrder, int secondOrder, CostPack cost)
bool addVehicle (CVehicleInfo vehicleInfo)
void applyBestMoveInCurrentSolution (CSolutionInfo &solutionInfo, CMoveInfo &bestMove)
void attemptVehicleExchange (CSolutionInfo &solutionInfo)
CSolutionInfo generateInitialSolution ()
CostPack getCostForInsert (CTourInfo &curTour, COrderInfo &curOrder, int pos)
CostPack getDepotToOrderCost (int depotId, int orderId)
CostPack getOrderToDepotCost (int depotId, int orderId)
CostPack getOrderToOrderCost (int firstOrder, int secondOrder)
std::pair< int, double > getPotentialInsert (CTourInfo &curTour, COrderInfo &curOrder)
int getServiceTime (int order_id)
bool getSolution (CSolutionInfo &solution, std::string &strError)
bool init ()
bool insertOrder (CTourInfo &tourInfo, int orderId, int pos)
void insertUnservedOrders (CSolutionInfo &solutionInfo)
bool isTabuMove (CMoveInfo &curMove)
void removeOrder (int orderIndex)
void removeVehicle (int vehicleIndex)
bool solveVRP (std::string &strError)
bool tabuSearch (CSolutionInfo &solutionInfo)
bool updateFinalSolution (CSolutionInfo &solutionInfo)
void updateTabuCount (CMoveInfo &bestMove)
bool updateTourCosts (CTourInfo &tourInfo)
Private Attributes
bool m_bFoundOptimal
bool m_bIsReadyToSolve
bool m_bIsSolutionReady
int m_iGeneratedSolutionCount
int m_iStepsSinceLastSolution
std::map< int, int > m_mapDepotIdToIndex
std::map< std::pair< int, int >, CostPack > m_mapDepotToOrderrCost
std::map< int, int > m_mapOrderIdToIndex
std::map< std::pair< int, int >, CostPack > m_mapOrderToDepotCost
std::map< std::pair< int, int >, CostPack > m_mapOrderToOrderCost
std::map< int, int > m_mapVehicleIdToIndex
CSolutionInfo m_solutionFinal
std::vector< CDepotInfo > m_vDepotInfos
std::vector< CMoveInfo > m_veMoves
std::vector< int > m_viUnservedOrderIndex
std::vector< int > m_viUnusedVehicleIndex
std::vector< COrderInfo > m_vOrderInfos
std::vector< CVehicleInfo > m_vVehicleInfos
Detailed Description
Definition at line 333 of file VRP_Solver.h.
Constructor & Destructor Documentation
CVRPSolver::CVRPSolver ()
Definition at line 215 of file VRP_Solver.cpp.
{
     // set a seed for the random number generator
     // so it will generate consistent results for the same input
     // otherwise we can not test it :(
     srand(1726354);
 }
CVRPSolver::~CVRPSolver ()
Definition at line 221 of file VRP_Solver.cpp.
 { }
Member Function Documentation
bool CVRPSolver::addDepot (CDepotInfo depotInfo)
Definition at line 490 of file VRP_Solver.cpp.
References CDepotInfo::getDepotId().
Referenced by loadOrders().
{
     int id = depotInfo.getDepotId();
     if (m_mapDepotIdToIndex.find(id) != m_mapDepotIdToIndex.end())
         return false;
     m_mapDepotIdToIndex.insert(std::make_pair(id, m_vDepotInfos.size()));
     m_vDepotInfos.push_back(depotInfo);
     return true;
 }
bool CVRPSolver::addDepotToOrderCost (int depotId, int orderId, CostPack cost)
Definition at line 524 of file VRP_Solver.cpp.
Referenced by loadDistanceMatrix().
{
     PII depo_order = std::make_pair(depotId, orderId);
     if (m_mapDepotToOrderrCost.find(depo_order) != m_mapDepotToOrderrCost.end()) {
         return false;
     }
     m_mapDepotToOrderrCost.insert(make_pair(depo_order, cost));
     return true;
 }
bool CVRPSolver::addOrder (COrderInfo orderInfo)
Definition at line 500 of file VRP_Solver.cpp.
References COrderInfo::getOrderId().
Referenced by loadOrders().
{
     int id = orderInfo.getOrderId();
     if (m_mapOrderIdToIndex.find(id) != m_mapOrderIdToIndex.end()) {
         return false;
     }
     int index = static_cast<int>(m_vOrderInfos.size());
     m_mapOrderIdToIndex.insert(std::make_pair(id, index));
     m_vOrderInfos.push_back(orderInfo);
     m_viUnservedOrderIndex.push_back(index);
     return true;
 }
bool CVRPSolver::addOrderAtTour (CSolutionInfo & solutionInfo, int tourIndex, int insertIndex, int orderIndex)
Definition at line 673 of file VRP_Solver.cpp.
References CSolutionInfo::getTour().
{
     return(insertOrder(solutionInfo.getTour(tourIndex), m_vOrderInfos[orderIndex].getOrderId(), insertIndex));
 }
bool CVRPSolver::addOrderToDepotCost (int depotId, int orderId, CostPack cost)
Definition at line 533 of file VRP_Solver.cpp.
Referenced by loadDistanceMatrix().
{
     PII depo_order = std::make_pair(orderId, depotId);
     if (m_mapOrderToDepotCost.find(depo_order) != m_mapOrderToDepotCost.end()) {
         return false;
     }
     m_mapOrderToDepotCost.insert(std::make_pair(depo_order, cost));
     return true;
 }
bool CVRPSolver::addOrderToOrderCost (int firstOrder, int secondOrder, CostPack cost)
Definition at line 542 of file VRP_Solver.cpp.
Referenced by loadDistanceMatrix().
{
     PII order_order = std::make_pair(firstOrder, secondOrder);
     if (m_mapOrderToOrderCost.find(order_order) != m_mapOrderToOrderCost.end()) {
         return false;
     }
     m_mapOrderToOrderCost.insert(std::make_pair(order_order, cost));
     return true;
 }
bool CVRPSolver::addVehicle (CVehicleInfo vehicleInfo)
Definition at line 512 of file VRP_Solver.cpp.
References CVehicleInfo::getId().
Referenced by loadVehicles().
{
     int id = vehicleInfo.getId();
     if (m_mapVehicleIdToIndex.find(id) != m_mapVehicleIdToIndex.end()) {
         return false;
     }
     int index = static_cast<int>(m_vVehicleInfos.size());
     m_mapVehicleIdToIndex.insert(std::make_pair(id, index));
     m_vVehicleInfos.push_back(vehicleInfo);
     m_viUnusedVehicleIndex.push_back(index);
     return true;
 }
void CVRPSolver::applyBestMoveInCurrentSolution (CSolutionInfo & solutionInfo, CMoveInfo & bestMove)
Definition at line 418 of file VRP_Solver.cpp.
References CMoveInfo::getModifiedTourAt(), CMoveInfo::getModifiedTourCount(), and CSolutionInfo::replaceTour().
{
     ++m_iGeneratedSolutionCount;
     ++m_iStepsSinceLastSolution;
     updateTabuCount(bestMove);
     int totalTour = static_cast<int>(bestMove.getModifiedTourCount());
     for (int i = 0; i < totalTour; ++i) {
         CTourInfo tourInfo;
         bool bIsValid = bestMove.getModifiedTourAt(i, tourInfo);
         if (bIsValid)
             curSolution.replaceTour(tourInfo);
     }
     updateFinalSolution(curSolution);
 }
void CVRPSolver::attemptVehicleExchange (CSolutionInfo & solutionInfo)
Definition at line 734 of file VRP_Solver.cpp.
References DOUBLE_MAX, CVehicleInfo::getCapacity(), CVehicleInfo::getCurrentLoad(), CMoveInfo::getInitialTour(), CMoveInfo::getModifiedTourAt(), CTourInfo::getOrderVector(), CTourInfo::getServedOrderCount(), CSolutionInfo::getTour(), CSolutionInfo::getTourCount(), CTourInfo::getVehicleId(), CTourInfo::getVehicleInfo(), CSolutionInfo::replaceTourAt(), CMoveInfo::setInitialTour(), CMoveInfo::setModifiedTour(), and CTourInfo::setVehicleInfo().
{
     ++m_iGeneratedSolutionCount;
     ++m_iStepsSinceLastSolution;
     CMoveInfo curMove;
     CMoveInfo bestMove;
     int bestFreeCapacity = 0;
     std::pair<int, int> bestSwapIndex;
     int totalTour = static_cast<int>(solutionInfo.getTourCount());
     for (int i = 0; i < totalTour; ++i) {
         CTourInfo firstTour = solutionInfo.getTour(i);
         int firstTourLoad = firstTour.getVehicleInfo().getCurrentLoad();
         int firstVehicleCapacity = firstTour.getVehicleInfo().getCapacity();
         for (int j = i + 1; j < totalTour; ++j) {
             CTourInfo secondTour = solutionInfo.getTour(j);
             curMove.setInitialTour(firstTour, secondTour);
             int FirstTourRemainingCapacity = firstVehicleCapacity - secondTour.getVehicleInfo().getCurrentLoad();
             int SecondTourRemainingCapacity = secondTour.getVehicleInfo().getCapacity() - firstTourLoad;
             // int prevFreeCapacity = max(secondTour.getRemainingCapacity(), firstTour.getRemainingCapacity() );
             int curFreeCapacity = (std::max)(FirstTourRemainingCapacity, SecondTourRemainingCapacity);
             if ((FirstTourRemainingCapacity > 0) &&  (SecondTourRemainingCapacity > 0) &&
                     // curFreeCapacity > curFreeCapacity autological compare evaluates to false (error on MAC)
                     (curFreeCapacity > bestFreeCapacity)) {
                 CVehicleInfo tempVehicle = m_vVehicleInfos[firstTour.getVehicleId()];
                 firstTour.setVehicleInfo(m_vVehicleInfos[secondTour.getVehicleId()]);
                 secondTour.setVehicleInfo(tempVehicle);
                 curMove.setModifiedTour(firstTour, secondTour);
                 if (!isTabuMove(curMove)) {
                     bestMove = curMove;
                     bestFreeCapacity = curFreeCapacity;
                     bestSwapIndex = std::make_pair(i, j);
                 }
                 curMove.getInitialTour(firstTour, secondTour);
             }
         }
     }
     if (bestFreeCapacity > 0) {
         CTourInfo tempTour;
         bestMove.getModifiedTourAt(0, tempTour);
         solutionInfo.replaceTourAt(bestSwapIndex.first, tempTour);
         bestMove.getModifiedTourAt(1, tempTour);
         solutionInfo.replaceTourAt(bestSwapIndex.second, tempTour);
         updateTabuCount(bestMove);
         updateFinalSolution(solutionInfo);
     }
 }
CSolutionInfo CVRPSolver::generateInitialSolution ()
Definition at line 262 of file VRP_Solver.cpp.
References CSolutionInfo::addTour(), DOUBLE_MAX, CVehicleInfo::getId(), CSolutionInfo::getUnservedOrderAt(), CSolutionInfo::getUnservedOrderCount(), CSolutionInfo::getUnusedVehicleAt(), CSolutionInfo::getUnusedVehicleCount(), CSolutionInfo::init(), PGR_LOG, rand(), CSolutionInfo::removeOrder(), CSolutionInfo::removeVehicle(), CTourInfo::setEndDepot(), CTourInfo::setStartDepot(), and CTourInfo::setVehicleInfo().
{
     CSolutionInfo initialSolution;
     PGR_LOG("Inside gen ini sol");
     std::vector<int> vecOrders, vecVehicles;
     for (unsigned int i = 0; i < m_vOrderInfos.size(); i++) {
         vecOrders.push_back(m_vOrderInfos[i].getOrderId());
     }
     for (unsigned int i = 0; i < m_vVehicleInfos.size(); i++) {
         vecVehicles.push_back(m_vVehicleInfos[i].getId());
     }
     initialSolution.init(vecOrders, static_cast<int>(vecOrders.size()), vecVehicles);
     int iUnusedVehicles = static_cast<int>(initialSolution.getUnusedVehicleCount());
     int iUnservedOrders = static_cast<int>(initialSolution.getUnservedOrderCount());  // m_viUnservedOrderIndex.size();
     PGR_LOG("before while");
     while (iUnusedVehicles &&  iUnservedOrders) {
         CTourInfo curTour;
         int vehicleIndex = rand() % iUnusedVehicles--;
         int vehicleInd = m_mapVehicleIdToIndex[initialSolution.getUnusedVehicleAt(vehicleIndex)];
         curTour.setVehicleInfo(m_vVehicleInfos[vehicleInd]);  // m_viUnusedVehicleIndex[vehicleIndex]
         initialSolution.removeVehicle(vehicleIndex);
         curTour.setStartDepot(m_vDepotInfos[0].getDepotId());
         curTour.setEndDepot(m_vDepotInfos[0].getDepotId());
         // use a random seed to start to tour. (we can use better approach in future)
         bool insertAvailable = true;
         while (insertAvailable) {
             insertAvailable = false;
             std::pair<int, int> PotentialInsert;  //  first = insert_index, second = removed_order_index;
             std::pair<int, double> bestInsert = std::make_pair(-1, DOUBLE_MAX);  // first = order_insert_index, second = cost;
             for (int i = 0; i < iUnservedOrders; ++i) {
                 int orderInd = m_mapOrderIdToIndex[initialSolution.getUnservedOrderAt(i)];
                 COrderInfo curOrder = m_vOrderInfos[orderInd];
                 std::pair<int, double> curInsert = getPotentialInsert(curTour, curOrder);
                 if (curInsert.second < bestInsert.second) {
                     insertAvailable = true;
                     bestInsert = curInsert;
                     PotentialInsert = std::make_pair(curInsert.first, i);
                 }
             }
             if (insertAvailable) {
                 if (insertOrder(curTour, initialSolution.getUnservedOrderAt(PotentialInsert.second), PotentialInsert.first)) {
                     iUnservedOrders--;
                     initialSolution.removeOrder(PotentialInsert.second);
                 }
             }
         }
         initialSolution.addTour(curTour);
     }
     return initialSolution;
 }
CostPack CVRPSolver::getCostForInsert (CTourInfo & curTour, COrderInfo & curOrder, int pos)
Definition at line 677 of file VRP_Solver.cpp.
References CostPack::cost, CostPack::distance, CTourInfo::getCost(), CTourInfo::getDistance(), CTourInfo::getEndDepot(), COrderInfo::getOrderId(), CTourInfo::getOrderVector(), CTourInfo::getStartDepot(), CTourInfo::getTravelTime(), INF, and CostPack::traveltime.
{
     std::vector<int> vecOrderId = curTour.getOrderVector();
     vecOrderId.insert(vecOrderId.begin() + pos, curOrder.getOrderId());
     double dCost, dDistance, dTravelTime;
     dCost = dDistance = dTravelTime = 0.0;
     CostPack costRet;
     costRet.cost = INF;
     costRet.distance = INF;
     costRet.traveltime = INF;
     CostPack cPack = getDepotToOrderCost(curTour.getStartDepot(), vecOrderId[0]);
     dCost += cPack.cost;
     dDistance += cPack.distance;
     int ind = m_mapOrderIdToIndex[vecOrderId[0]];
     if (dTravelTime + cPack.traveltime > m_vOrderInfos[ind].getCloseTime())
         return costRet;
     dTravelTime = (std::max)(dTravelTime + cPack.traveltime + m_vOrderInfos[ind].getServiceTime(),
             static_cast<double>(m_vOrderInfos[ind].getOpenTime() + m_vOrderInfos[ind].getServiceTime()));
     unsigned int i;
     for (i = 1; i < vecOrderId.size(); i++) {
         cPack = getOrderToOrderCost(vecOrderId[i - 1], vecOrderId[i]);
         dCost += cPack.cost;
         dDistance += cPack.distance;
         ind = m_mapOrderIdToIndex[vecOrderId[i]];
         if (dTravelTime + cPack.traveltime > m_vOrderInfos[ind].getCloseTime())
             return costRet;
         dTravelTime = (std::max)(dTravelTime + cPack.traveltime + m_vOrderInfos[ind].getServiceTime(),
                 static_cast<double>(m_vOrderInfos[ind].getOpenTime() + m_vOrderInfos[ind].getServiceTime()));
     }
     cPack = getOrderToDepotCost(vecOrderId[i - 1], curTour.getEndDepot());
     dCost += cPack.cost;
     dDistance += cPack.distance;
     dTravelTime += cPack.traveltime;
     ind = m_mapDepotIdToIndex[curTour.getEndDepot()];
     if (dTravelTime > m_vDepotInfos[ind].getCloseTime())
         return costRet;
     costRet.cost = dCost - curTour.getCost();
     costRet.distance = dDistance - curTour.getDistance();
     costRet.traveltime = dTravelTime - curTour.getTravelTime();
     return costRet;
 }
CostPack CVRPSolver::getDepotToOrderCost (int depotId, int orderId)
Definition at line 565 of file VRP_Solver.cpp.
References CostPack::cost, CostPack::distance, and CostPack::traveltime.
{
     PII depo_order = std::make_pair(depotId, orderId);
     if (m_mapDepotToOrderrCost.find(depo_order) != m_mapDepotToOrderrCost.end()) {
         return(m_mapDepotToOrderrCost[depo_order]);
     }
     CostPack ret;
     ret.cost = ret.distance = ret.traveltime = 1e15;
     return ret;
 }
CostPack CVRPSolver::getOrderToDepotCost (int depotId, int orderId)
Definition at line 588 of file VRP_Solver.cpp.
References CostPack::cost, CostPack::distance, and CostPack::traveltime.
{
     PII depo_order = std::make_pair(orderId, depotId);
     if (m_mapOrderToDepotCost.find(depo_order) != m_mapOrderToDepotCost.end()) {
         return(m_mapOrderToDepotCost[depo_order]);
     }
     CostPack ret;
     ret.cost = ret.distance = ret.traveltime = 1e15;
     return ret;
 }
CostPack CVRPSolver::getOrderToOrderCost (int firstOrder, int secondOrder)
Definition at line 576 of file VRP_Solver.cpp.
References CostPack::cost, CostPack::distance, and CostPack::traveltime.
{
     PII order_order = std::make_pair(orderId1, orderId2);
     if (m_mapOrderToOrderCost.find(order_order) != m_mapOrderToOrderCost.end()) {
         return(m_mapOrderToOrderCost[order_order]);
     }
     CostPack ret;
     ret.cost = ret.distance = ret.traveltime = 1e15;
     return ret;
 }
std::pair< int, double > CVRPSolver::getPotentialInsert (CTourInfo & curTour, COrderInfo & curOrder)
Definition at line 357 of file VRP_Solver.cpp.
References CostPack::cost, DOUBLE_MAX, COrderInfo::getCloseTime(), CTourInfo::getEndDepot(), COrderInfo::getOrderId(), COrderInfo::getOrderUnit(), CTourInfo::getOrderVector(), CTourInfo::getRemainingCapacity(), COrderInfo::getServiceTime(), CTourInfo::getStartDepot(), CTourInfo::getStartTime(), and CostPack::traveltime.
{
     std::pair<int, double> bestInsert = std::make_pair(-1, DOUBLE_MAX);
     if (curOrder.getOrderUnit() > curTour.getRemainingCapacity()) {
         return bestInsert;
     }
     // check if ith position insert is fisible.
     std::vector<int> vecOrderId = curTour.getOrderVector();
     for (unsigned int i = 0; i <= vecOrderId.size(); ++i) {
         CostPack costToOrder, costFromOrder;
         if (!i) {
             costToOrder = getDepotToOrderCost(curTour.getStartDepot(), curOrder.getOrderId());
         } else {
             costToOrder = getOrderToOrderCost(vecOrderId[i-1], curOrder.getOrderId());
         }
         double dArrivalTime = costToOrder.traveltime + curTour.getStartTime(i);
         if (dArrivalTime > curOrder.getCloseTime()) {
             continue;
         }
         if (i == vecOrderId.size()) {
             costFromOrder = getOrderToDepotCost(curOrder.getOrderId(), curTour.getEndDepot());
         } else {
             costFromOrder = getOrderToOrderCost(curOrder.getOrderId(), vecOrderId[i]);
         }
         dArrivalTime += curOrder.getServiceTime() + costFromOrder.traveltime;
         if (i < vecOrderId.size() &&  dArrivalTime > m_vOrderInfos[m_mapOrderIdToIndex[vecOrderId[i]]].getCloseTime()) {
             continue;
         }
         CostPack totalCost = getCostForInsert(curTour, curOrder, i);
         if (totalCost.cost < bestInsert.second) {
             bestInsert = std::make_pair(i, totalCost.cost);
         }
     }
     return bestInsert;
 }
int CVRPSolver::getServiceTime (int order_id) inline
Definition at line 366 of file VRP_Solver.h.
References getServiceTime().
Referenced by find_vrp_solution(), and getServiceTime().
 {return (m_vOrderInfos[m_mapOrderIdToIndex[order_id]].getServiceTime());}
bool CVRPSolver::getSolution (CSolutionInfo & solution, std::string & strError)
Definition at line 551 of file VRP_Solver.cpp.
Referenced by find_vrp_solution(), and print_solution().
{
     if (m_bIsSolutionReady == true) {
         solution = m_solutionFinal;
         return true;
     } else {
         bool ret = solveVRP(strError);
         if (ret == true) {
             solution = m_solutionFinal;
             return true;
         }
         return false;
     }
 }
bool CVRPSolver::init ()
bool CVRPSolver::insertOrder (CTourInfo & tourInfo, int orderId, int pos)
Definition at line 599 of file VRP_Solver.cpp.
References CTourInfo::getOrderVector(), CTourInfo::getVehicleInfo(), CTourInfo::insertOrder(), CVehicleInfo::loadUnit(), and CTourInfo::removeOrder().
{
     if (pos < 0 ||  (unsigned int) pos > tourInfo.getOrderVector().size())
         return false;
     int orderIndex = m_mapOrderIdToIndex[orderId];
     if (!tourInfo.getVehicleInfo().loadUnit(m_vOrderInfos[orderIndex].getOrderUnit()))
         return false;
     tourInfo.insertOrder(orderId, pos);
     if (!updateTourCosts(tourInfo)) {
         tourInfo.removeOrder(pos);
         return false;
     }
     return true;
 }
void CVRPSolver::insertUnservedOrders (CSolutionInfo & solutionInfo)
Definition at line 435 of file VRP_Solver.cpp.
References DOUBLE_MAX, CMoveInfo::getInitialTour(), CSolutionInfo::getOrderServed(), CSolutionInfo::getTour(), CSolutionInfo::getTourInfoVector(), CSolutionInfo::getUnservedOrderAt(), CMoveInfo::setInitialTour(), and CMoveInfo::setModifiedTour().
{
     ++m_iGeneratedSolutionCount;
     ++m_iStepsSinceLastSolution;
     bool insertAvailable = true;
     CMoveInfo curMove;
     int totalUnservedOrder = static_cast<int>(m_vOrderInfos.size() - curSolution.getOrderServed());
     while (insertAvailable &&  totalUnservedOrder > 0) {
         int insertTourId = -1;
         insertAvailable = false;
         int totalTour = static_cast<int>(curSolution.getTourInfoVector().size());
         std::pair<int, int> PotentialInsert;  //  first = insert_index, second = removed_customer_index;
         std::pair<int, double> bestInsert = std::make_pair(-1, DOUBLE_MAX);  // first = customer_insert_index, second = cost;
         for (int j = 0; j < totalTour; ++j) {
             CTourInfo curTour = curSolution.getTour(j);
             curMove.setInitialTour(curTour);
             for (int i = 0; i < totalUnservedOrder; ++i) {
                 int ordIndex = m_mapOrderIdToIndex[curSolution.getUnservedOrderAt(i)];
                 COrderInfo curOrder = m_vOrderInfos[ordIndex];
                 std::pair<int, double> curInsert = getPotentialInsert(curTour, curOrder);
                 insertOrder(curTour, i, curInsert.first);
                 curMove.setModifiedTour(curTour);
                 curMove.getInitialTour(curTour);
                 // check if current move is tabu.
                 if (isTabuMove(curMove)) {
                     continue;
                 }
                 if (curInsert.second < bestInsert.second) {
                     insertTourId = j;
                     insertAvailable = true;
                     bestInsert = curInsert;
                     PotentialInsert = std::make_pair(curInsert.first, i);
                 }
             }
         }
         if (insertAvailable) {
             totalUnservedOrder--;
             curMove.setInitialTour(curSolution.getTour(insertTourId));
             addOrderAtTour(curSolution, insertTourId,
                     PotentialInsert.first,
                     PotentialInsert.second);
             curMove.setModifiedTour(curSolution.getTour(insertTourId));
             this->updateTabuCount(curMove);
             this->updateFinalSolution(curSolution);  // this->evaluateCurrentSolution();
         }
     }
 }
bool CVRPSolver::isTabuMove (CMoveInfo & curMove)
Definition at line 880 of file VRP_Solver.cpp.
{
     size_t i, tot = m_veMoves.size();
     for (i = 0; i < tot; i++) {
         if (curMove == m_veMoves[i])
             return true;
     }
     return false;
 }
void CVRPSolver::removeOrder (int orderIndex) inline
Definition at line 355 of file VRP_Solver.h.
      {m_viUnservedOrderIndex.erase(m_viUnservedOrderIndex.begin() + orderIndex, m_viUnservedOrderIndex.begin() + orderIndex + 1);}
void CVRPSolver::removeVehicle (int vehicleIndex) inline
Definition at line 352 of file VRP_Solver.h.
      {m_viUnusedVehicleIndex.erase(m_viUnusedVehicleIndex.begin() + vehicleIndex, m_viUnusedVehicleIndex.begin() + vehicleIndex+1);}
bool CVRPSolver::solveVRP (std::string & strError)
Definition at line 223 of file VRP_Solver.cpp.
References MAXIMUM_TRY, and PGR_LOG.
Referenced by find_vrp_solution(), and main().
{
     // if (!m_bIsReadyToSolve)
     // {
     //      strError = "Scenario is not ready to solve. Configure all parameter";
     //      return false;
     // }
     PGR_LOG("Inside Solve VRP");
     std::vector<int> vecOrders, vecVehicles;
     for(auto &rule:m_vOrderInfos)
     {
       vecOrders.push_back(rule.getOrderId());
     }
     for (auto &rule:m_vVehicleInfos) {
         vecVehicles.push_back(rule.getId());
     }
     m_solutionFinal.init(vecOrders, static_cast<int>(vecOrders.size()), vecVehicles);
     PGR_LOG("After init solution");
     int iAttemptCount = 0;
     while (iAttemptCount < MAXIMUM_TRY) {
         bool bUpdateFound = false;
         CSolutionInfo initialSolution = generateInitialSolution();
         PGR_LOG("After Generate initial Solution");
         iAttemptCount++;
         bUpdateFound = updateFinalSolution(initialSolution);
         PGR_LOG("After update final Solution");
         bool bUpdateFound2 = tabuSearch(initialSolution);
         PGR_LOG("After Tabu Search");
         if ((bUpdateFound == true) ||  (bUpdateFound2 == true)) {
             iAttemptCount = 0;
         }
     }
     m_bIsSolutionReady = true;
     strError += " ";
     return true;
 }
bool CVRPSolver::tabuSearch (CSolutionInfo & solutionInfo)
Definition at line 400 of file VRP_Solver.cpp.
References TOTAL_NUMBER_OF_SEARCH.
{
     m_bFoundOptimal = false;
     updateFinalSolution(curSolution);
     int numberOfSearch = 0;
     m_iGeneratedSolutionCount = 0;
     m_iStepsSinceLastSolution = 0;
     while (numberOfSearch < TOTAL_NUMBER_OF_SEARCH) {
         // applyBestMoveInCurrentSolution(curSolution, identifyPotentialMove(curSolution) );
         insertUnservedOrders(curSolution);
         // attemptFeasibleNodeExchange(curSolution);
         attemptVehicleExchange(curSolution);
         ++numberOfSearch;
     }
     return false;
 }
bool CVRPSolver::updateFinalSolution (CSolutionInfo & solutionInfo)
Definition at line 324 of file VRP_Solver.cpp.
References CSolutionInfo::getOrderServed(), CSolutionInfo::getTotalCost(), CSolutionInfo::getTotalDistance(), and CSolutionInfo::getTotalTravelTime().
{
     bool callUpdate = false;
     if (curSolution.getOrderServed() > m_solutionFinal.getOrderServed()) {
         callUpdate = true;
     } else if (curSolution.getOrderServed() == m_solutionFinal.getOrderServed()) {
         if (curSolution.getTotalCost() < m_solutionFinal.getTotalCost()) {
             callUpdate = true;
         } else if (curSolution.getTotalCost() == m_solutionFinal.getTotalCost()) {
             if (curSolution.getTotalTravelTime() < m_solutionFinal.getTotalTravelTime()) {
                 callUpdate = true;
             } else if (curSolution.getTotalTravelTime() == m_solutionFinal.getTotalTravelTime()) {
                 if (curSolution.getTotalDistance() < m_solutionFinal.getTotalDistance()) {
                     callUpdate = true;
                 }
             }
         }
     }
     if (callUpdate) {
         // m_iStepsSinceLastSolution = 0;
         m_solutionFinal = curSolution;
         // clear map and delete objects
         // m_mpTabuCount.clear();
         // for (std::map< CVRPTWMove*, int >::iterator it = m_mpMoveFrequency.begin();it!= m_mpMoveFrequency.end();++it)
         // {
         //  delete (*it).first;
         // }
         // m_mpMoveFrequency.clear();
         return true;
     }
     return false;
 }
void CVRPSolver::updateTabuCount (CMoveInfo & bestMove)
Definition at line 846 of file VRP_Solver.cpp.
References MAXIMUM_MOVE_FREQUENCY, and CMoveInfo::reverseMove().
{
     m_veMoves.push_back(bestMove);
 #if 0
     bestMove.reverseMove();
     CMoveInfo curMove;
     std::map< CMoveInfo, int >::iterator mpIt = m_mapMoveFrequency.find(bestMove);
     if (mpIt == m_mapMoveFrequency.end()) {
         curMove = bestMove;
     } else {
         curMove = (*mpIt).first;
     }
     m_mapMoveFrequency[curMove]++;
     if (m_mapMoveFrequency[curMove] >= MAXIMUM_MOVE_FREQUENCY) {
         CMoveInfo tmpMove;
         std::set<CMoveInfo>::iterator sIt = m_sTabuList.find(curMove);
         CMoveInfo tmpMove2;
         if (sIt == m_sTabuList.end()) {
             tmpMove2 = curMove;
         } else {
             tmpMove2 = (*sIt);
         }
         m_sTabuList.insert(tmpMove2);
     }
     m_mapTabuCount[curMove] = std::make_pair(m_iGeneratedSolutionCount, m_iStepsSinceLastSolution);
     bestMove.reverseMove();
     */
 #endif
 }
bool CVRPSolver::updateTourCosts (CTourInfo & tourInfo)
Definition at line 616 of file VRP_Solver.cpp.
References CostPack::cost, CostPack::distance, CTourInfo::getEndDepot(), CTourInfo::getOrderVector(), CTourInfo::getStartDepot(), CTourInfo::setStartTime(), CostPack::traveltime, and CTourInfo::updateCost().
{
     std::vector<int> vecOrderId = tourInfo.getOrderVector();
     std::vector<int> vecStartTimes;
     double dCost, dDistance, dTravelTime;
     dCost = dDistance = dTravelTime = 0.0;
     CostPack cPack = getDepotToOrderCost(tourInfo.getStartDepot(), vecOrderId[0]);
     dCost += cPack.cost;
     dDistance += cPack.distance;
     int ind = m_mapOrderIdToIndex[vecOrderId[0]];
     vecStartTimes.push_back(0);
     if (dTravelTime + cPack.traveltime > m_vOrderInfos[ind].getCloseTime())
         return false;
     dTravelTime = (std::max)(dTravelTime + cPack.traveltime + m_vOrderInfos[ind].getServiceTime(),
             static_cast<double>(m_vOrderInfos[ind].getOpenTime() + m_vOrderInfos[ind].getServiceTime()));
     vecStartTimes.push_back(static_cast<int>(ceil(dTravelTime)));
     unsigned int i;
     for (i = 1; i < vecOrderId.size(); i++) {
         cPack = getOrderToOrderCost(vecOrderId[i - 1], vecOrderId[i]);
         dCost += cPack.cost;
         dDistance += cPack.distance;
         ind = m_mapOrderIdToIndex[vecOrderId[i]];
         if (dTravelTime + cPack.traveltime > m_vOrderInfos[ind].getCloseTime())
             return false;
         dTravelTime = (std::max)(dTravelTime + cPack.traveltime + m_vOrderInfos[ind].getServiceTime(),
                 static_cast<double>(m_vOrderInfos[ind].getOpenTime() + m_vOrderInfos[ind].getServiceTime()));
         vecStartTimes.push_back(static_cast<int>(ceil(dTravelTime)));
     }
     cPack = getOrderToDepotCost(vecOrderId[i - 1], tourInfo.getEndDepot());
     dCost += cPack.cost;
     dDistance += cPack.distance;
     dTravelTime += cPack.traveltime;
     vecStartTimes.push_back(static_cast<int>(ceil(dTravelTime)));
     ind = m_mapDepotIdToIndex[tourInfo.getEndDepot()];
     if (dTravelTime > m_vDepotInfos[ind].getCloseTime())
         return false;
     tourInfo.updateCost(dCost, dDistance, dTravelTime);
     tourInfo.setStartTime(vecStartTimes);
     return true;
 }
Member Data Documentation
bool CVRPSolver::m_bFoundOptimal private
Definition at line 411 of file VRP_Solver.h.
bool CVRPSolver::m_bIsReadyToSolve private
Definition at line 382 of file VRP_Solver.h.
bool CVRPSolver::m_bIsSolutionReady private
Definition at line 403 of file VRP_Solver.h.
int CVRPSolver::m_iGeneratedSolutionCount private
Definition at line 409 of file VRP_Solver.h.
int CVRPSolver::m_iStepsSinceLastSolution private
Definition at line 410 of file VRP_Solver.h.
std::map<int, int> CVRPSolver::m_mapDepotIdToIndex private
Definition at line 389 of file VRP_Solver.h.
std::map<std::pair<int, int>, CostPack> CVRPSolver::m_mapDepotToOrderrCost private
Definition at line 392 of file VRP_Solver.h.
std::map<int, int> CVRPSolver::m_mapOrderIdToIndex private
Definition at line 387 of file VRP_Solver.h.
std::map<std::pair<int, int>, CostPack> CVRPSolver::m_mapOrderToDepotCost private
Definition at line 393 of file VRP_Solver.h.
std::map<std::pair<int, int>, CostPack> CVRPSolver::m_mapOrderToOrderCost private
Definition at line 391 of file VRP_Solver.h.
std::map<int, int> CVRPSolver::m_mapVehicleIdToIndex private
Definition at line 388 of file VRP_Solver.h.
CSolutionInfo CVRPSolver::m_solutionFinal private
Definition at line 404 of file VRP_Solver.h.
std::vector<CDepotInfo> CVRPSolver::m_vDepotInfos private
Definition at line 385 of file VRP_Solver.h.
std::vector<CMoveInfo> CVRPSolver::m_veMoves private
Definition at line 401 of file VRP_Solver.h.
std::vector<int> CVRPSolver::m_viUnservedOrderIndex private
Definition at line 407 of file VRP_Solver.h.
std::vector<int> CVRPSolver::m_viUnusedVehicleIndex private
Definition at line 408 of file VRP_Solver.h.
std::vector<COrderInfo> CVRPSolver::m_vOrderInfos private
Definition at line 384 of file VRP_Solver.h.
std::vector<CVehicleInfo> CVRPSolver::m_vVehicleInfos private
Definition at line 383 of file VRP_Solver.h.
The documentation for this class was generated from the following files:
/home/wang/mainrepo/src/vrp_basic/src/VRP_Solver.h
/home/wang/mainrepo/src/vrp_basic/src/VRP_Solver.cpp