PGROUTING: CTourInfo Class Reference
CTourInfo Class Reference
#include "VRP_Solver.h"
Public Member Functions
CTourInfo ()
~CTourInfo ()
double getCost ()
double getDistance ()
int getEndDepot ()
std::vector< int > getOrderVector ()
int getRemainingCapacity ()
size_t getServedOrderCount ()
int getStartDepot ()
int getStartTime (int pos)
double getTravelTime ()
int getVehicleId ()
CVehicleInfo & getVehicleInfo ()
void init ()
bool insertOrder (int orderId, int pos)
bool removeOrder (int pos)
void setEndDepot (int depotId)
void setStartDepot (int depotId)
void setStartTime (std::vector< int > vStartTime)
void setVehicleInfo (CVehicleInfo vehicleInfo)
void updateCost (double cost, double distance, double travelTime)
Private Attributes
double m_dTotalCost
double m_dTotalDistance
double m_dTotalTraveltime
int m_iEndDepotId
int m_iOrdersServed
int m_iStartDepotId
CVehicleInfo m_vehicleInfo
std::vector< int > m_viOrderIds
std::vector< int > m_viStartTime
Friends
bool operator== (const CTourInfo &cur, const CTourInfo &that)
Detailed Description
Definition at line 166 of file VRP_Solver.h.
Constructor & Destructor Documentation
CTourInfo::CTourInfo ()
Definition at line 82 of file VRP_Solver.cpp.
References m_dTotalCost, m_dTotalDistance, and m_dTotalTraveltime.
                      {
     m_dTotalCost = 0.0;
     m_dTotalDistance = 0.0;
     m_dTotalTraveltime = 0.0;
 }
CTourInfo::~CTourInfo ()
Definition at line 87 of file VRP_Solver.cpp.
 { }
Member Function Documentation
double CTourInfo::getCost () inline
Definition at line 199 of file VRP_Solver.h.
References m_dTotalCost.
Referenced by CSolutionInfo::addTour(), and CVRPSolver::getCostForInsert().
 {return m_dTotalCost;}
double CTourInfo::getDistance () inline
Definition at line 197 of file VRP_Solver.h.
References m_dTotalDistance.
Referenced by CSolutionInfo::addTour(), and CVRPSolver::getCostForInsert().
 {return m_dTotalDistance;}
int CTourInfo::getEndDepot () inline
Definition at line 183 of file VRP_Solver.h.
References m_iEndDepotId.
Referenced by find_vrp_solution(), CVRPSolver::getCostForInsert(), CVRPSolver::getPotentialInsert(), print_solution(), and CVRPSolver::updateTourCosts().
 {return m_iEndDepotId;}
std::vector<int> CTourInfo::getOrderVector () inline
Definition at line 203 of file VRP_Solver.h.
References m_viOrderIds.
Referenced by CSolutionInfo::addTour(), find_vrp_solution(), CVRPSolver::getCostForInsert(), CVRPSolver::getPotentialInsert(), CVRPSolver::insertOrder(), print_solution(), and CVRPSolver::updateTourCosts().
 {return m_viOrderIds;}
int CTourInfo::getRemainingCapacity ()
Definition at line 94 of file VRP_Solver.cpp.
References CVehicleInfo::getRemainingCapacity(), and m_vehicleInfo.
Referenced by CVRPSolver::getPotentialInsert().
{
     return(m_vehicleInfo.getRemainingCapacity());
 }
size_t CTourInfo::getServedOrderCount () inline
Definition at line 186 of file VRP_Solver.h.
References m_viOrderIds.
Referenced by find_vrp_solution().
 {return m_viOrderIds.size();}
int CTourInfo::getStartDepot () inline
Definition at line 180 of file VRP_Solver.h.
References m_iStartDepotId.
Referenced by find_vrp_solution(), CVRPSolver::getCostForInsert(), CVRPSolver::getPotentialInsert(), print_solution(), and CVRPSolver::updateTourCosts().
 {return m_iStartDepotId;}
int CTourInfo::getStartTime (int pos) inline
Definition at line 205 of file VRP_Solver.h.
References m_viStartTime.
Referenced by find_vrp_solution(), and CVRPSolver::getPotentialInsert().
{
          if ((unsigned int) pos >= m_viStartTime.size())
              return 0;
          else
              return m_viStartTime[pos];
      }
double CTourInfo::getTravelTime () inline
Definition at line 201 of file VRP_Solver.h.
References m_dTotalTraveltime.
Referenced by CSolutionInfo::addTour(), and CVRPSolver::getCostForInsert().
 {return m_dTotalTraveltime;}
int CTourInfo::getVehicleId () inline
Definition at line 175 of file VRP_Solver.h.
References CVehicleInfo::getId(), and m_vehicleInfo.
Referenced by CSolutionInfo::addTour(), CVRPSolver::attemptVehicleExchange(), find_vrp_solution(), print_solution(), and CSolutionInfo::replaceTour().
 {return m_vehicleInfo.getId();}
CVehicleInfo& CTourInfo::getVehicleInfo () inline
Definition at line 177 of file VRP_Solver.h.
References m_vehicleInfo.
Referenced by CVRPSolver::attemptVehicleExchange(), and CVRPSolver::insertOrder().
 {return m_vehicleInfo;}
void CTourInfo::init ()
bool CTourInfo::insertOrder (int orderId, int pos)
Definition at line 89 of file VRP_Solver.cpp.
References m_viOrderIds.
Referenced by CVRPSolver::insertOrder().
{
     m_viOrderIds.insert(m_viOrderIds.begin() + pos, orderId);
     return true;
 }
bool CTourInfo::removeOrder (int pos)
Definition at line 98 of file VRP_Solver.cpp.
References m_viOrderIds.
Referenced by CVRPSolver::insertOrder().
{
     m_viOrderIds.erase(m_viOrderIds.begin() + pos);
     return true;
 }
void CTourInfo::setEndDepot (int depotId) inline
Definition at line 184 of file VRP_Solver.h.
References m_iEndDepotId.
Referenced by CVRPSolver::generateInitialSolution().
 {m_iEndDepotId = depotId;}
void CTourInfo::setStartDepot (int depotId) inline
Definition at line 181 of file VRP_Solver.h.
References m_iStartDepotId.
Referenced by CVRPSolver::generateInitialSolution().
 {m_iStartDepotId = depotId;}
void CTourInfo::setStartTime (std::vector< int > vStartTime) inline
Definition at line 190 of file VRP_Solver.h.
References m_viStartTime.
Referenced by CVRPSolver::updateTourCosts().
 {m_viStartTime = vStartTime;}
void CTourInfo::setVehicleInfo (CVehicleInfo vehicleInfo) inline
Definition at line 178 of file VRP_Solver.h.
References m_vehicleInfo.
Referenced by CVRPSolver::attemptVehicleExchange(), and CVRPSolver::generateInitialSolution().
 {m_vehicleInfo = vehicleInfo;}
void CTourInfo::updateCost (double cost, double distance, double travelTime)
Definition at line 103 of file VRP_Solver.cpp.
References m_dTotalCost, m_dTotalDistance, and m_dTotalTraveltime.
Referenced by CVRPSolver::updateTourCosts().
{
     m_dTotalCost = cost;
     m_dTotalDistance = distance;
     m_dTotalTraveltime = travelTime;
 }
Friends And Related Function Documentation
bool operator== (const CTourInfo & cur, const CTourInfo & that) friend
Definition at line 45 of file VRP_Solver.cpp.
{
     if (cur.m_vehicleInfo != that.m_vehicleInfo)
         return false;
     if (cur.m_viOrderIds.size() != that.m_viOrderIds.size())
         return false;
     return std::equal(cur.m_viOrderIds.begin(), cur.m_viOrderIds.end(), that.m_viOrderIds.begin());
 }
Member Data Documentation
double CTourInfo::m_dTotalCost private
Definition at line 231 of file VRP_Solver.h.
Referenced by CTourInfo(), getCost(), and updateCost().
double CTourInfo::m_dTotalDistance private
Definition at line 232 of file VRP_Solver.h.
Referenced by CTourInfo(), getDistance(), and updateCost().
double CTourInfo::m_dTotalTraveltime private
Definition at line 233 of file VRP_Solver.h.
Referenced by CTourInfo(), getTravelTime(), and updateCost().
int CTourInfo::m_iEndDepotId private
Definition at line 227 of file VRP_Solver.h.
Referenced by getEndDepot(), and setEndDepot().
int CTourInfo::m_iOrdersServed private
Definition at line 228 of file VRP_Solver.h.
int CTourInfo::m_iStartDepotId private
Definition at line 226 of file VRP_Solver.h.
Referenced by getStartDepot(), and setStartDepot().
CVehicleInfo CTourInfo::m_vehicleInfo private
Definition at line 225 of file VRP_Solver.h.
Referenced by getRemainingCapacity(), getVehicleId(), getVehicleInfo(), operator==(), and setVehicleInfo().
std::vector<int> CTourInfo::m_viOrderIds private
Definition at line 229 of file VRP_Solver.h.
Referenced by getOrderVector(), getServedOrderCount(), insertOrder(), operator==(), and removeOrder().
std::vector<int> CTourInfo::m_viStartTime private
Definition at line 230 of file VRP_Solver.h.
Referenced by getStartTime(), and setStartTime().
The documentation for this class was generated from the following files:
/home/vicky/pgrouting/pgrouting/pgrouting/src/vrp_basic/src/VRP_Solver.h
/home/vicky/pgrouting/pgrouting/pgrouting/src/vrp_basic/src/VRP_Solver.cpp