PGROUTING: pgrouting::vrp::pickdeliver::Initial_solution Class Reference
pgrouting::vrp::pickdeliver::Initial_solution Class Reference
#include "initial_solution.h"
Public Member Functions
Initial_solution (int kind, size_t)
Vehicle::Cost cost () const
std::string cost_str () const
int cvTot () const
double duration () const
size_t fleet_size () const
std::vector< General_vehicle_orders_t > get_postgres_result () const
void invariant () const
bool is_feasable () const
bool operator< (const Solution &s_rhs) const
void sort_by_id ()
std::string tau (const std::string &title="Tau") const
double total_service_time () const
double total_travel_time () const
int twvTot () const
double wait_time () const
Static Public Attributes
static Pgr_messages msg
Protected Attributes
double EPSILON
std::deque< Vehicle_pickDeliver > fleet
Fleet trucks
Static Protected Attributes
static Pgr_pickDeliver * problem
Private Member Functions
void do_while_foo (int kind)
void one_truck_all_orders ()
Private Attributes
Identifiers< size_t > all_orders
Identifiers< size_t > assigned
Identifiers< PD_Orders::OID > unassigned
Detailed Description
Definition at line 46 of file initial_solution.h.
Constructor & Destructor Documentation
pgrouting::vrp::pickdeliver::Initial_solution::Initial_solution (int kind, size_t)
Member Function Documentation
Vehicle::Cost pgrouting::vrp::pickdeliver::Solution::cost () const inherited
Referenced by pgrouting::vrp::pickdeliver::Solution::fleet_size().
std::string pgrouting::vrp::pickdeliver::Solution::cost_str () const inherited
Referenced by pgrouting::vrp::pickdeliver::Solution::operator=().
int pgrouting::vrp::pickdeliver::Solution::cvTot () const inherited
Referenced by pgrouting::vrp::pickdeliver::Solution::operator=().
void pgrouting::vrp::pickdeliver::Initial_solution::do_while_foo (int kind) private
double pgrouting::vrp::pickdeliver::Solution::duration () const inherited
Referenced by pgrouting::vrp::pickdeliver::Solution::operator=().
size_t pgrouting::vrp::pickdeliver::Solution::fleet_size () const inline inherited
Definition at line 104 of file solution.h.
References pgrouting::vrp::pickdeliver::Solution::cost().
 {return fleet.size();}
std::vector<General_vehicle_orders_t> pgrouting::vrp::pickdeliver::Solution::get_postgres_result () const inherited
void pgrouting::vrp::pickdeliver::Initial_solution::invariant () const
bool pgrouting::vrp::pickdeliver::Solution::is_feasable () const inherited
Referenced by pgrouting::vrp::pickdeliver::Solution::operator=().
void pgrouting::vrp::pickdeliver::Initial_solution::one_truck_all_orders () private
bool pgrouting::vrp::pickdeliver::Solution::operator< (const Solution & s_rhs) const inherited
Referenced by pgrouting::vrp::pickdeliver::Solution::operator=().
void pgrouting::vrp::pickdeliver::Solution::sort_by_id () inherited
Referenced by pgrouting::vrp::pickdeliver::Solution::operator=().
std::string pgrouting::vrp::pickdeliver::Solution::tau (const std::string & title = "Tau") const inherited
Referenced by pgrouting::vrp::pickdeliver::Solution::operator=().
double pgrouting::vrp::pickdeliver::Solution::total_service_time () const inherited
Referenced by pgrouting::vrp::pickdeliver::Solution::operator=().
double pgrouting::vrp::pickdeliver::Solution::total_travel_time () const inherited
Referenced by pgrouting::vrp::pickdeliver::Solution::operator=().
int pgrouting::vrp::pickdeliver::Solution::twvTot () const inherited
Referenced by pgrouting::vrp::pickdeliver::Solution::operator=().
double pgrouting::vrp::pickdeliver::Solution::wait_time () const inherited
Referenced by pgrouting::vrp::pickdeliver::Solution::operator=().
Member Data Documentation
Identifiers<size_t> pgrouting::vrp::pickdeliver::Initial_solution::all_orders private
Definition at line 64 of file initial_solution.h.
Identifiers<size_t> pgrouting::vrp::pickdeliver::Initial_solution::assigned private
Definition at line 66 of file initial_solution.h.
double pgrouting::vrp::pickdeliver::Solution::EPSILON protected inherited
Definition at line 50 of file solution.h.
std::deque<Vehicle_pickDeliver> pgrouting::vrp::pickdeliver::Solution::fleet protected inherited
Definition at line 51 of file solution.h.
Referenced by pgrouting::vrp::pickdeliver::Solution::operator=().
Pgr_messages pgrouting::vrp::pickdeliver::PD_problem::msg static inherited
Definition at line 49 of file pd_problem.h.
Pgr_pickDeliver* pgrouting::vrp::pickdeliver::PD_problem::problem static protected inherited
Definition at line 52 of file pd_problem.h.
Fleet pgrouting::vrp::pickdeliver::Solution::trucks protected inherited
Definition at line 54 of file solution.h.
Referenced by pgrouting::vrp::pickdeliver::Solution::operator=().
Identifiers<PD_Orders::OID> pgrouting::vrp::pickdeliver::Initial_solution::unassigned private
Definition at line 65 of file initial_solution.h.
The documentation for this class was generated from the following file:
/home/wang/mainrepo/include/pickDeliver/initial_solution.h