PGROUTING: pgrouting::vrp::pickdeliver::Tw_node Class Reference
pgrouting::vrp::pickdeliver::Tw_node Class Reference
Extends the Node class to create a Node with time window attributes.
#include "tw_node.h"
Public Types
enum NodeType {
kStart = 0, kPickup, kDelivery, kDump,
kLoad, kEnd
}
Public Member Functions
Tw_node ()
Tw_node (const Tw_node &)=default
Tw_node (size_t id, const PickDeliveryOrders_t data, NodeType type)
Tw_node (size_t id, Vehicle_t data, NodeType type)
size_t Did () const
double distance (const Base_node *) const
int64_t id () const
size_t idx () const
bool is_early_arrival (double arrival_time) const
True when arrivalTime is before it opens.
bool is_late_arrival (double arrival_time) const
True when arrivalTime is after it closes.
bool is_on_time (double arrival_time) const
True when arrivalTime in the time window.
bool operator== (const Tw_node &rhs) const
size_t Pid () const
void reset_id (int64_t)
void set_Did (size_t id)
void set_Pid (size_t id)
accessors
double opens () const
@ {
double closes () const
Returns the closing time.
double demand () const
Returns the demand associated with this node.
double service_time () const
Returns the service time for this node.
NodeType type () const
Returns the type of this node.
double window_length () const
Returns the length of time between the opening and closing.
double travel_time_to (const Dnode &other, double speed) const
time = distance / speed.
kind of node
A true value when;
0 < opens < closes
the type is the requested type
the demand are valid for the requested type
bool is_start () const
@ {
bool is_pickup () const
is_pickup
bool is_delivery () const
is_delivery
bool is_dump () const
is_dump
bool is_load () const
is_Load
bool is_end () const
is_end
std::string type_str () const
document functions
double arrival_j_opens_i (const Tw_node &I, double speed) const
@ {
double arrival_j_closes_i (const Tw_node &I, double speed) const
The actual arrival time at this node, given that: this node is visited directly after other node and that the actual arrival time at other node was closes(other)
bool is_compatible_IJ (const Tw_node &I, double speed) const
bool is_partially_compatible_IJ (const Tw_node &I, double speed) const
bool is_tight_compatible_IJ (const Tw_node &I, double speed) const
bool is_partially_waitTime_compatible_IJ (const Tw_node &I, double speed) const
bool is_waitTime_compatible_IJ (const Tw_node &I, double speed) const
to be or not to be
virtual bool operator== (const Base_node &rhs) const
Static Public Attributes
static Pgr_messages msg
Protected Member Functions
bool is_valid () const
Protected Attributes
double m_closes
closing time of the node
double m_demand
The demand for the Node.
double m_opens
opening time of the node
size_t m_otherid
the other's internal id
double m_service_time
NodeType m_type
The demand for the Node.
Static Protected Attributes
static Pgr_pickDeliver * problem
Friends
std::ostream & operator<< (std::ostream &log, const Tw_node &node)
Print the contents of a Twnode object.
Detailed Description
Extends the Node class to create a Node with time window attributes.
A Time Window node is a Node with addition attributes and methods to to support Time Windows and to model a more complex Node need in many vehicle routing problems.
Most application specific code will extend this class and define the specific values and requirements for type and streetid.
Definition at line 56 of file tw_node.h.
Member Enumeration Documentation
enum pgrouting::vrp::pickdeliver::Tw_node::NodeType
Enumerator
kStart
kPickup
kDelivery
kDump
kLoad
kEnd
ending site
Definition at line 58 of file tw_node.h.
                   {
          kStart = 0,  // /< starting site
          kPickup,  // /< pickup site
          kDelivery,  // /< delivery site
          kDump,  // /< dump site, empties truck
          kLoad,  // /< load site, fills the truck
          kEnd
      } NodeType;
Constructor & Destructor Documentation
pgrouting::vrp::pickdeliver::Tw_node::Tw_node () inline
Definition at line 273 of file tw_node.h.
References is_valid(), and type().
 : Dnode() {}
pgrouting::vrp::pickdeliver::Tw_node::Tw_node (const Tw_node &) default
pgrouting::vrp::pickdeliver::Tw_node::Tw_node (size_t id, const PickDeliveryOrders_t data, NodeType type)
pgrouting::vrp::pickdeliver::Tw_node::Tw_node (size_t id, Vehicle_t data, NodeType type)
Member Function Documentation
double pgrouting::vrp::pickdeliver::Tw_node::arrival_j_closes_i (const Tw_node & I, double speed) const
The actual arrival time at this node, given that: this node is visited directly after other node and that the actual arrival time at other node was closes(other)
Referenced by is_on_time().
double pgrouting::vrp::pickdeliver::Tw_node::arrival_j_opens_i (const Tw_node & I, double speed) const
@ {
The actual arrival time at This node, given that: this node is visited directly after other node and that the actual arrival time at other node was opens(other)
Referenced by is_on_time().
double pgrouting::vrp::pickdeliver::Tw_node::closes () const inline
Returns the closing time.
Definition at line 95 of file tw_node.h.
References m_closes.
 {return m_closes;}
double pgrouting::vrp::pickdeliver::Tw_node::demand () const inline
Returns the demand associated with this node.
Definition at line 98 of file tw_node.h.
References m_demand.
 {return m_demand;}
size_t pgrouting::vrp::pickdeliver::Tw_node::Did () const inline
Definition at line 76 of file tw_node.h.
References is_pickup(), m_otherid, and pgassert.
{
          pgassert(is_pickup());
          return m_otherid;
      }
double pgrouting::vrp::Dnode::distance (const Base_node * other) const virtual inherited
Implements pgrouting::vrp::Base_node.
Definition at line 42 of file dnode.cpp.
References pgrouting::tsp::Dmatrix::distance(), pgrouting::tsp::Dmatrix::get_index(), pgrouting::Identifier::id(), pgrouting::vrp::Pgr_pickDeliver::m_cost_matrix, and pgrouting::vrp::PD_problem::problem.
{
     return problem->m_cost_matrix.distance(
             problem->m_cost_matrix.get_index(id()),
             problem->m_cost_matrix.get_index(other->id()));
 }
int64_t pgrouting::Identifier::id () const inherited
Definition at line 42 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Dnode::distance(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::vrp::pickdeliver::Vehicle::is_phony(), pgrouting::vrp::Vehicle::is_phony(), pgrouting::vrp::Optimize::move_reduce_cost(), pgrouting::vrp::operator<<(), pgrouting::operator<<(), pgrouting::vrp::Base_node::operator==(), pgrouting::vrp::Node::operator==(), pgrouting::vrp::Node::print(), pgrouting::vrp::Base_node::print(), set_Did(), and set_Pid().
                      {
     return m_id;
 }
size_t pgrouting::Identifier::idx () const inherited
Definition at line 37 of file identifier.cpp.
References pgrouting::Identifier::m_idx.
Referenced by pgrouting::vrp::Vehicle_pickDeliver::erase(), pgrouting::vrp::Vehicle::erase(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Vehicle_pickDeliver::has_order(), pgrouting::vrp::Vehicle::insert(), pgrouting::vrp::Vehicle_pickDeliver::insert(), pgrouting::vrp::operator<<(), pgrouting::operator<<(), pgrouting::vrp::Base_node::operator==(), pgrouting::vrp::Node::operator==(), pgrouting::vrp::Tw_node::operator==(), pgrouting::vrp::Node::print(), pgrouting::vrp::Base_node::print(), pgrouting::vrp::Vehicle_pickDeliver::push_back(), pgrouting::vrp::Vehicle_pickDeliver::push_front(), pgrouting::vrp::Order::set_compatibles(), pgrouting::vrp::Solution::sort_by_id(), pgrouting::vrp::Optimize::swap_worse(), pgrouting::vrp::Vehicle::tau(), and pgrouting::vrp::Tw_node::travel_time_to().
                       {
     return m_idx;
 }
bool pgrouting::vrp::pickdeliver::Tw_node::is_compatible_IJ (const Tw_node & I, double speed) const
Referenced by is_on_time().
bool pgrouting::vrp::pickdeliver::Tw_node::is_delivery () const
is_delivery
To be a delivery node:
type is kDelivery
demand < 0
Referenced by Pid(), and window_length().
bool pgrouting::vrp::pickdeliver::Tw_node::is_dump () const
is_dump
To be a dump node:
type is kDump
demand <= 0
Referenced by window_length().
bool pgrouting::vrp::pickdeliver::Tw_node::is_early_arrival (double arrival_time) const inline
True when arrivalTime is before it opens.
Definition at line 200 of file tw_node.h.
References m_opens.
Referenced by is_on_time().
{
          return arrival_time < m_opens;
      }
bool pgrouting::vrp::pickdeliver::Tw_node::is_end () const
is_end
To be a End node:
type is kEnd
demand == 0
Referenced by pgrouting::vrp::pickdeliver::Vehicle_node::has_cv(), and window_length().
bool pgrouting::vrp::pickdeliver::Tw_node::is_late_arrival (double arrival_time) const inline
True when arrivalTime is after it closes.
Definition at line 205 of file tw_node.h.
References m_closes.
Referenced by pgrouting::vrp::pickdeliver::Vehicle_node::has_twv(), and is_on_time().
{
          return arrival_time > m_closes;
      }
bool pgrouting::vrp::pickdeliver::Tw_node::is_load () const
is_Load
To be a Load node:
type is kLoad
demand >= 0
Referenced by window_length().
bool pgrouting::vrp::pickdeliver::Tw_node::is_on_time (double arrival_time) const inline
True when arrivalTime in the time window.
Definition at line 209 of file tw_node.h.
References arrival_j_closes_i(), arrival_j_opens_i(), is_compatible_IJ(), is_early_arrival(), is_late_arrival(), is_partially_compatible_IJ(), is_partially_waitTime_compatible_IJ(), is_tight_compatible_IJ(), and is_waitTime_compatible_IJ().
{
          return !is_early_arrival(arrival_time)
              && !is_late_arrival(arrival_time);
      }
bool pgrouting::vrp::pickdeliver::Tw_node::is_partially_compatible_IJ (const Tw_node & I, double speed) const
Referenced by is_on_time().
bool pgrouting::vrp::pickdeliver::Tw_node::is_partially_waitTime_compatible_IJ (const Tw_node & I, double speed) const
Referenced by is_on_time().
bool pgrouting::vrp::pickdeliver::Tw_node::is_pickup () const
is_pickup
To be a pickup node:
type is kPickup
demand > 0
Referenced by Did(), and window_length().
bool pgrouting::vrp::pickdeliver::Tw_node::is_start () const
@ {
is_start
To be a start node:
type is kStart
demand == 0
Referenced by pgrouting::vrp::pickdeliver::Vehicle_node::has_cv(), and window_length().
bool pgrouting::vrp::pickdeliver::Tw_node::is_tight_compatible_IJ (const Tw_node & I, double speed) const
Referenced by is_on_time().
bool pgrouting::vrp::pickdeliver::Tw_node::is_valid () const protected
Referenced by Tw_node().
bool pgrouting::vrp::pickdeliver::Tw_node::is_waitTime_compatible_IJ (const Tw_node & I, double speed) const
Referenced by is_on_time().
double pgrouting::vrp::pickdeliver::Tw_node::opens () const inline
@ {
Returns the opening time.
Definition at line 92 of file tw_node.h.
References m_opens.
 {return m_opens;}
bool pgrouting::vrp::Base_node::operator== (const Base_node & rhs) const virtual inherited
Definition at line 48 of file base_node.cpp.
References pgrouting::Identifier::id(), and pgrouting::Identifier::idx().
{
     if (&rhs == this) return true;
     return
         (idx() == rhs.idx())
          && (id() == rhs.id());
 }
bool pgrouting::vrp::pickdeliver::Tw_node::operator== (const Tw_node & rhs) const
Referenced by window_length().
size_t pgrouting::vrp::pickdeliver::Tw_node::Pid () const inline
Definition at line 81 of file tw_node.h.
References is_delivery(), m_otherid, and pgassert.
{
          pgassert(is_delivery());
          return m_otherid;
      }
void pgrouting::Identifier::reset_id (int64_t _id) inherited
Definition at line 47 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Tw_node::Tw_node().
{
     m_id = _id;
 }
double pgrouting::vrp::pickdeliver::Tw_node::service_time () const inline
Returns the service time for this node.
Definition at line 101 of file tw_node.h.
References m_service_time.
 { return m_service_time;}
void pgrouting::vrp::pickdeliver::Tw_node::set_Did (size_t id) inline
Definition at line 72 of file tw_node.h.
References pgrouting::Identifier::id(), and m_otherid.
{
          m_otherid = id;
      }
void pgrouting::vrp::pickdeliver::Tw_node::set_Pid (size_t id) inline
Definition at line 68 of file tw_node.h.
References pgrouting::Identifier::id(), and m_otherid.
{
          m_otherid = id;
      }
double pgrouting::vrp::pickdeliver::Tw_node::travel_time_to (const Dnode & other, double speed) const
time = distance / speed.
Referenced by window_length().
NodeType pgrouting::vrp::pickdeliver::Tw_node::type () const inline
Returns the type of this node.
Definition at line 104 of file tw_node.h.
References m_type.
Referenced by Tw_node().
 { return m_type;}
std::string pgrouting::vrp::pickdeliver::Tw_node::type_str () const
Referenced by window_length().
double pgrouting::vrp::pickdeliver::Tw_node::window_length () const inline
Returns the length of time between the opening and closing.
Definition at line 107 of file tw_node.h.
References is_delivery(), is_dump(), is_end(), is_load(), is_pickup(), is_start(), m_closes, m_opens, operator<<, operator==(), travel_time_to(), and type_str().
 {return m_closes - m_opens;}
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & log, const Tw_node & node) friend
Print the contents of a Twnode object.
Referenced by window_length().
Member Data Documentation
double pgrouting::vrp::pickdeliver::Tw_node::m_closes protected
closing time of the node
Definition at line 288 of file tw_node.h.
Referenced by closes(), is_late_arrival(), and window_length().
double pgrouting::vrp::pickdeliver::Tw_node::m_demand protected
The demand for the Node.
Definition at line 290 of file tw_node.h.
Referenced by demand().
double pgrouting::vrp::pickdeliver::Tw_node::m_opens protected
opening time of the node
Definition at line 287 of file tw_node.h.
Referenced by is_early_arrival(), opens(), and window_length().
size_t pgrouting::vrp::pickdeliver::Tw_node::m_otherid protected
the other's internal id
Definition at line 291 of file tw_node.h.
Referenced by Did(), Pid(), set_Did(), and set_Pid().
double pgrouting::vrp::pickdeliver::Tw_node::m_service_time protected
Definition at line 289 of file tw_node.h.
Referenced by service_time().
NodeType pgrouting::vrp::pickdeliver::Tw_node::m_type protected
The demand for the Node.
Definition at line 292 of file tw_node.h.
Referenced by type().
Pgr_messages pgrouting::vrp::PD_problem::msg static inherited
Definition at line 48 of file pd_problem.h.
Referenced by pgrouting::vrp::Fleet::add_vehicle(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), pgrouting::vrp::Optimize::delete_empty_truck(), do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), pgrouting::vrp::Initial_solution::do_while_foo(), pgrouting::vrp::Pgr_pickDeliver::get_postgres_result(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Fleet::is_fleet_ok(), pgrouting::vrp::Optimize::move_reduce_cost(), pgrouting::vrp::Pgr_pickDeliver::nodesOK(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), pgrouting::vrp::Pgr_pickDeliver::optimize(), pgrouting::vrp::PD_problem::PD_problem(), pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Optimize::save_if_best(), pgrouting::vrp::Pgr_pickDeliver::solve(), pgrouting::vrp::Optimize::swap_order(), pgrouting::vrp::Optimize::swap_worse(), and pgrouting::vrp::Vehicle::Vehicle().
Pgr_pickDeliver * pgrouting::vrp::PD_problem::problem static protected inherited
Definition at line 51 of file pd_problem.h.
Referenced by pgrouting::vrp::PD_Orders::add_order(), pgrouting::vrp::Fleet::add_vehicle(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), pgrouting::vrp::Dnode::distance(), pgrouting::vrp::operator<<(), pgrouting::vrp::Tw_node::operator==(), and pgrouting::vrp::Tw_node::travel_time_to().
The documentation for this class was generated from the following file:
/home/wang/mainrepo/include/pickDeliver/tw_node.h