PGROUTING: pgrouting::vrp::pickdeliver::PD_Orders Class Reference
pgrouting::vrp::pickdeliver::PD_Orders Class Reference
#include "pd_orders.h"
Public Types
typedef Orders::const_iterator o_const_iterator
typedef Orders::iterator o_iterator
typedef size_t OID
typedef Identifiers< OID > setof_OID
Public Member Functions
void build_orders (const std::vector< PickDeliveryOrders_t > &pd_orders)
size_t find_best_I (Identifiers< size_t > &within_this_set) const
size_t find_best_J (Identifiers< size_t > &within_this_set) const
bool is_valid (double speed) const
void set_compatibles (double speed)
constructors
PD_Orders ()=default
PD_Orders (const PD_Orders &)=default
PD_Orders (const std::vector< PickDeliveryOrders_t > &pd_orders)
std container functions
functions with same "meaning" as an std container
Order & operator[] (OID o)
const Order & operator[] (OID o) const
size_t size () const
o_iterator begin ()
o_iterator end ()
o_const_iterator begin () const
o_const_iterator end () const
Static Public Attributes
static Pgr_messages msg
Protected Attributes
Orders m_orders
Static Protected Attributes
static Pgr_pickDeliver * problem
Private Types
typedef std::vector< Order > Orders
Friends
std::ostream & operator<< (std::ostream &log, const PD_Orders &)
Detailed Description
Definition at line 45 of file pd_orders.h.
Member Typedef Documentation
typedef Orders::const_iterator pgrouting::vrp::pickdeliver::PD_Orders::o_const_iterator
Definition at line 50 of file pd_orders.h.
typedef Orders::iterator pgrouting::vrp::pickdeliver::PD_Orders::o_iterator
Definition at line 49 of file pd_orders.h.
typedef size_t pgrouting::vrp::pickdeliver::PD_Orders::OID
Definition at line 51 of file pd_orders.h.
typedef std::vector<Order> pgrouting::vrp::pickdeliver::PD_Orders::Orders private
Definition at line 46 of file pd_orders.h.
typedef Identifiers<OID> pgrouting::vrp::pickdeliver::PD_Orders::setof_OID
Definition at line 52 of file pd_orders.h.
Constructor & Destructor Documentation
pgrouting::vrp::pickdeliver::PD_Orders::PD_Orders () default
pgrouting::vrp::pickdeliver::PD_Orders::PD_Orders (const PD_Orders &) default
pgrouting::vrp::pickdeliver::PD_Orders::PD_Orders (const std::vector< PickDeliveryOrders_t > & pd_orders) explicit
Member Function Documentation
o_iterator pgrouting::vrp::pickdeliver::PD_Orders::begin () inline
Definition at line 81 of file pd_orders.h.
 {return m_orders.begin();}
o_const_iterator pgrouting::vrp::pickdeliver::PD_Orders::begin () const inline
Definition at line 83 of file pd_orders.h.
 {return m_orders.begin();}
void pgrouting::vrp::pickdeliver::PD_Orders::build_orders (const std::vector< PickDeliveryOrders_t > & pd_orders)
Referenced by end().
o_iterator pgrouting::vrp::pickdeliver::PD_Orders::end () inline
Definition at line 82 of file pd_orders.h.
 {return m_orders.end();}
o_const_iterator pgrouting::vrp::pickdeliver::PD_Orders::end () const inline
Definition at line 84 of file pd_orders.h.
References build_orders(), and operator<<.
 {return m_orders.end();}
size_t pgrouting::vrp::pickdeliver::PD_Orders::find_best_I (Identifiers< size_t > & within_this_set) const
size_t pgrouting::vrp::pickdeliver::PD_Orders::find_best_J (Identifiers< size_t > & within_this_set) const
bool pgrouting::vrp::pickdeliver::PD_Orders::is_valid (double speed) const
Order& pgrouting::vrp::pickdeliver::PD_Orders::operator[] (OID o)
const Order& pgrouting::vrp::pickdeliver::PD_Orders::operator[] (OID o) const
void pgrouting::vrp::pickdeliver::PD_Orders::set_compatibles (double speed)
size_t pgrouting::vrp::pickdeliver::PD_Orders::size () const inline
Definition at line 80 of file pd_orders.h.
 {return m_orders.size();}
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & log, const PD_Orders &) friend
Referenced by end().
Member Data Documentation
Orders pgrouting::vrp::pickdeliver::PD_Orders::m_orders protected
Definition at line 55 of file pd_orders.h.
Pgr_messages pgrouting::vrp::pickdeliver::PD_problem::msg static inherited
Definition at line 49 of file pd_problem.h.
Pgr_pickDeliver* pgrouting::vrp::pickdeliver::PD_problem::problem static protected inherited
Definition at line 52 of file pd_problem.h.
The documentation for this class was generated from the following file:
/home/wang/mainrepo/include/pickDeliver/pd_orders.h