PGROUTING: pgrouting::Identifier Class Reference
pgrouting::Identifier Class Reference
#include "identifier.h"
Public Member Functions
Identifier ()=default
Identifier (const Identifier &v)=default
Identifier (const size_t _idx, const int64_t _id)
int64_t id () const
size_t idx () const
void reset_id (int64_t)
Private Attributes
int64_t m_id
size_t m_idx
Friends
std::ostream & operator<< (std::ostream &log, const Identifier &)
Detailed Description
Definition at line 39 of file identifier.h.
Constructor & Destructor Documentation
pgrouting::Identifier::Identifier () default
pgrouting::Identifier::Identifier (const Identifier & v) default
pgrouting::Identifier::Identifier (const size_t _idx, const int64_t _id)
Definition at line 30 of file identifier.cpp.
                            :
     m_idx(_idx),
     m_id(_id) {}
Member Function Documentation
int64_t pgrouting::Identifier::id () const
Definition at line 42 of file identifier.cpp.
References m_id.
Referenced by pgrouting::vrp::Dnode::distance(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::vrp::pickdeliver::Vehicle::is_phony(), pgrouting::vrp::Vehicle::is_phony(), pgrouting::vrp::Optimize::move_reduce_cost(), pgrouting::vrp::operator<<(), pgrouting::operator<<(), pgrouting::vrp::Base_node::operator==(), pgrouting::vrp::Node::operator==(), pgrouting::vrp::Node::print(), pgrouting::vrp::Base_node::print(), pgrouting::vrp::pickdeliver::Tw_node::set_Did(), and pgrouting::vrp::pickdeliver::Tw_node::set_Pid().
                      {
     return m_id;
 }
size_t pgrouting::Identifier::idx () const
Definition at line 37 of file identifier.cpp.
References m_idx.
Referenced by pgrouting::vrp::Vehicle_pickDeliver::erase(), pgrouting::vrp::Vehicle::erase(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Vehicle_pickDeliver::has_order(), pgrouting::vrp::Vehicle::insert(), pgrouting::vrp::Vehicle_pickDeliver::insert(), pgrouting::vrp::operator<<(), pgrouting::operator<<(), pgrouting::vrp::Base_node::operator==(), pgrouting::vrp::Node::operator==(), pgrouting::vrp::Tw_node::operator==(), pgrouting::vrp::Node::print(), pgrouting::vrp::Base_node::print(), pgrouting::vrp::Vehicle_pickDeliver::push_back(), pgrouting::vrp::Vehicle_pickDeliver::push_front(), pgrouting::vrp::Order::set_compatibles(), pgrouting::vrp::Solution::sort_by_id(), pgrouting::vrp::Optimize::swap_worse(), pgrouting::vrp::Vehicle::tau(), and pgrouting::vrp::Tw_node::travel_time_to().
                       {
     return m_idx;
 }
void pgrouting::Identifier::reset_id (int64_t _id)
Definition at line 47 of file identifier.cpp.
References m_id.
Referenced by pgrouting::vrp::Tw_node::Tw_node().
{
     m_id = _id;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & log, const Identifier & ident) friend
Definition at line 51 of file identifier.cpp.
{
     log << "id(idx) = " << ident.id() << "(" << ident.idx() << ")";
     return log;
 }
Member Data Documentation
int64_t pgrouting::Identifier::m_id private
Definition at line 53 of file identifier.h.
Referenced by id(), and reset_id().
size_t pgrouting::Identifier::m_idx private
Definition at line 52 of file identifier.h.
Referenced by idx().
The documentation for this class was generated from the following files:
/home/vicky/pgrouting/pgrouting/pgrouting/include/cpp_common/identifier.h
/home/vicky/pgrouting/pgrouting/pgrouting/src/common/src/identifier.cpp