PGROUTING: /home/vicky/pgrouting/pgrouting/pgrouting/src/common/src/coordinates_input.c File Reference
coordinates_input.c File Reference
#include "c_common/coordinates_input.h"
#include "c_types/column_info_t.h"
#include "c_common/debug_macro.h"
#include "c_common/get_check_data.h"
#include "c_common/time_msg.h"
Functions
static void pgr_fetch_row (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info[3], int64_t *default_id, Coordinate_t *distance)
void pgr_get_coordinates (char *sql, Coordinate_t **coordinates, size_t *total_coordinates)
bigint id, float x, float y,
Function Documentation
static void pgr_fetch_row (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info[3], int64_t * default_id, Coordinate_t * distance) static
Definition at line 36 of file coordinates_input.c.
References column_found(), Coordinate_t::id, pgr_SPI_getBigInt(), pgr_SPI_getFloat8(), Coordinate_t::x, and Coordinate_t::y.
Referenced by pgr_get_coordinates().
{
     if (column_found(info[0].colNumber)) {
         distance->id = pgr_SPI_getBigInt(tuple, tupdesc, info[0]);
     } else {
         distance->id = *default_id;
         ++(*default_id);
     }
     distance->x = pgr_SPI_getFloat8(tuple, tupdesc,  info[1]);
     distance->y = pgr_SPI_getFloat8(tuple, tupdesc, info[2]);
 }
void pgr_get_coordinates (char * sql, Coordinate_t ** coordinates, size_t * total_coordinates)
bigint id, float x, float y,
Definition at line 57 of file coordinates_input.c.
References ANY_INTEGER, ANY_NUMERICAL, Column_info_t::colNumber, Column_info_t::eType, Column_info_t::name, PGR_DBG, pgr_fetch_column_info(), pgr_fetch_row(), pgr_SPI_cursor_open(), pgr_SPI_prepare(), Column_info_t::strict, time_msg(), and Column_info_t::type.
Referenced by process().
{
     clock_t start_t = clock();
     const int tuple_limit = 1000000;
     size_t ntuples;
     size_t total_tuples = 0;
     Column_info_t info[3];
     int i;
     for (i = 0; i < 3; ++i) {
         info[i].colNumber = -1;
         info[i].type = 0;
         info[i].strict = true;
         info[i].eType = ANY_NUMERICAL;
     }
     info[0].name = strdup("id");
     info[1].name = strdup("x");
     info[2].name = strdup("y");
     info[0].eType = ANY_INTEGER;
     info[0].strict = false;
     void *SPIplan;
     SPIplan = pgr_SPI_prepare(sql);
     Portal SPIportal;
     SPIportal = pgr_SPI_cursor_open(SPIplan);
     bool moredata = TRUE;
     (*total_coordinates) = total_tuples;
     int64_t default_id = 1;
     while (moredata == TRUE) {
         SPI_cursor_fetch(SPIportal, TRUE, tuple_limit);
         if (total_tuples == 0)
             pgr_fetch_column_info(info, 3);
         ntuples = SPI_processed;
         total_tuples += ntuples;
         if (ntuples > 0) {
             if ((*coordinates) == NULL)
                 (*coordinates) = (Coordinate_t *)
                     palloc0(total_tuples * sizeof(Coordinate_t));
             else
                 (*coordinates) = (Coordinate_t *)
                     repalloc((*coordinates),
                             total_tuples * sizeof(Coordinate_t));
             if ((*coordinates) == NULL) {
                 elog(ERROR, "Out of memory");
             }
             SPITupleTable *tuptable = SPI_tuptable;
             TupleDesc tupdesc = SPI_tuptable->tupdesc;
             PGR_DBG("Processing %ld coordinates tupĺes", ntuples);
             size_t t;
             for (t = 0; t < ntuples; t++) {
                 HeapTuple tuple = tuptable->vals[t];
                 pgr_fetch_row(&tuple, &tupdesc, info,
                         &default_id,
                         &(*coordinates)[total_tuples - ntuples + t]);
             }
             SPI_freetuptable(tuptable);
         } else {
             moredata = FALSE;
         }
     }
     SPI_cursor_close(SPIportal);
     if (total_tuples == 0) {
         (*total_coordinates) = 0;
         PGR_DBG("NO coordinates");
         return;
     }
     (*total_coordinates) = total_tuples;
     time_msg(" reading coordinates:", start_t, clock());
 }