PGROUTING: /home/vicky/pgrouting/pgrouting/pgrouting/include/dijkstra/pgr_dijkstra.hpp File Reference
pgr_dijkstra.hpp File Reference
#include <boost/config.hpp>
#include <boost/graph/adjacency_list.hpp>
#include <boost/graph/dijkstra_shortest_paths.hpp>
#include <deque>
#include <set>
#include <vector>
#include <algorithm>
#include "cpp_common/basePath_SSEC.hpp"
#include "cpp_common/pgr_base_graph.hpp"
Classes
class Pgr_dijkstra< G >
class Pgr_dijkstra< G >
class Pgr_dijkstra< G >::dijkstra_distance_visitor
class for stopping when a distance/cost has being surpassed
class Pgr_dijkstra< G >::dijkstra_many_goal_visitor
class for stopping when all targets are found
class Pgr_dijkstra< G >::dijkstra_one_goal_visitor
class for stopping when 1 target is found
struct Pgr_dijkstra< G >::found_goals
exception for termination
Functions
template<class G >
Path pgr_dijkstra (G &graph, int64_t source, int64_t target, bool only_cost=false)
template<class G >
std::deque< Path > pgr_dijkstra (G &graph, int64_t source, std::vector< int64_t > targets, bool only_cost=false)
template<class G >
std::deque< Path > pgr_dijkstra (G &graph, std::vector< int64_t > sources, int64_t target, bool only_cost=false)
template<class G >
std::deque< Path > pgr_dijkstra (G &graph, std::vector< int64_t > sources, std::vector< int64_t > targets, bool only_cost=false)
template<class G >
std::deque< Path > pgr_drivingDistance (G &graph, std::vector< int64_t > start_vids, double distance, bool equicost)
template<class G >
Path pgr_drivingDistance (G &graph, int64_t source, double distance)
Function Documentation
template<class G > Path pgr_dijkstra (G & graph, int64_t source, int64_t target, bool only_cost = false)
Definition at line 77 of file pgr_dijkstra.hpp.
References Pgr_dijkstra< G >::dijkstra().
{
     Pgr_dijkstra< G > fn_dijkstra;
     return fn_dijkstra.dijkstra(graph, source, target, only_cost);
 }
template<class G > std::deque<Path> pgr_dijkstra (G & graph, int64_t source, std::vector< int64_t > targets, bool only_cost = false)
Definition at line 89 of file pgr_dijkstra.hpp.
References Pgr_dijkstra< G >::dijkstra().
{
     std::sort(targets.begin(), targets.end());
     targets.erase(
             std::unique(targets.begin(), targets.end()),
             targets.end());
     Pgr_dijkstra< G > fn_dijkstra;
     return fn_dijkstra.dijkstra(graph, source, targets, only_cost);
 }
template<class G > std::deque<Path> pgr_dijkstra (G & graph, std::vector< int64_t > sources, int64_t target, bool only_cost = false)
Definition at line 105 of file pgr_dijkstra.hpp.
References Pgr_dijkstra< G >::dijkstra().
{
     std::sort(sources.begin(), sources.end());
     sources.erase(
             std::unique(sources.begin(), sources.end()),
             sources.end());
     Pgr_dijkstra< G > fn_dijkstra;
     return fn_dijkstra.dijkstra(graph, sources, target, only_cost);
 }
template<class G > std::deque<Path> pgr_dijkstra (G & graph, std::vector< int64_t > sources, std::vector< int64_t > targets, bool only_cost = false)
Definition at line 122 of file pgr_dijkstra.hpp.
References Pgr_dijkstra< G >::dijkstra().
{
     std::sort(sources.begin(), sources.end());
     sources.erase(
             std::unique(sources.begin(), sources.end()),
             sources.end());
     std::sort(targets.begin(), targets.end());
     targets.erase(
             std::unique(targets.begin(), targets.end()),
             targets.end());
     Pgr_dijkstra< G > fn_dijkstra;
     return fn_dijkstra.dijkstra(graph, sources, targets, only_cost);
 }
template<class G > std::deque<Path> pgr_drivingDistance (G & graph, std::vector< int64_t > start_vids, double distance, bool equicost)
Definition at line 53 of file pgr_dijkstra.hpp.
References Pgr_dijkstra< G >::drivingDistance().
Referenced by do_pgr_driving_many_to_dist(), do_pgr_many_withPointsDD(), and process_drivingDistance().
{
     Pgr_dijkstra< G > fn_dijkstra;
     return fn_dijkstra.drivingDistance(graph, start_vids, distance, equicost);
 }
template<class G > Path pgr_drivingDistance (G & graph, int64_t source, double distance)
Definition at line 65 of file pgr_dijkstra.hpp.
References Pgr_dijkstra< G >::drivingDistance().
{
     Pgr_dijkstra< G > fn_dijkstra;
     return fn_dijkstra.drivingDistance(graph, source, distance);
 }