pgRouting: PgrFlowGraph< G > Class Template Reference
PgrFlowGraph< G > Class Template Reference
#include "pgr_maxflow.hpp"
Public Types
typedef boost::graph_traits< G >
::edge_descriptor E
typedef boost::graph_traits< G >
::edge_iterator E_it
typedef boost::graph_traits< G >
::vertex_descriptor V
typedef boost::graph_traits< G >
::vertex_iterator V_it
Public Member Functions
int64_t boykov_kolmogorov ()
void create_flow_graph (pgr_edge_t *data_edges, size_t total_tuples, const std::set< int64_t > &source_vertices, const std::set< int64_t > &sink_vertices, char *algorithm)
int64_t edmonds_karp ()
V get_boost_vertex (int64_t id)
int64_t get_edge_id (E e)
void get_flow_edges (std::vector< pgr_flow_t > &flow_edges)
int64_t get_vertex_id (V v)
int64_t push_relabel ()
Public Attributes
G boost_graph
boost::property_map< G,
boost::edge_capacity_t >::type capacity
std::map< E, int64_t > E_to_id
std::map< int64_t, V > id_to_V
boost::property_map< G,
boost::edge_residual_capacity_t >
::type residual_capacity
boost::property_map< G,
boost::edge_reverse_t >::type rev
V sink_vertex
V source_vertex
std::map< V, int64_t > V_to_id
Detailed Description
template<class G>
class PgrFlowGraph< G >
Definition at line 74 of file pgr_maxflow.hpp.
Member Typedef Documentation
template<class G> typedef boost::graph_traits<G>::edge_descriptor PgrFlowGraph< G >::E
Definition at line 79 of file pgr_maxflow.hpp.
template<class G> typedef boost::graph_traits<G>::edge_iterator PgrFlowGraph< G >::E_it
Definition at line 81 of file pgr_maxflow.hpp.
template<class G> typedef boost::graph_traits<G>::vertex_descriptor PgrFlowGraph< G >::V
Definition at line 78 of file pgr_maxflow.hpp.
template<class G> typedef boost::graph_traits<G>::vertex_iterator PgrFlowGraph< G >::V_it
Definition at line 80 of file pgr_maxflow.hpp.
Member Function Documentation
template<class G> int64_t PgrFlowGraph< G >::boykov_kolmogorov () inline
Definition at line 120 of file pgr_maxflow.hpp.
References PgrFlowGraph< G >::boost_graph, PgrFlowGraph< G >::sink_vertex, and PgrFlowGraph< G >::source_vertex.
Referenced by do_pgr_max_flow_many_to_many(), do_pgr_max_flow_many_to_one(), do_pgr_max_flow_one_to_many(), and do_pgr_max_flow_one_to_one().
template<class G> void PgrFlowGraph< G >::create_flow_graph (pgr_edge_t * data_edges, size_t total_tuples, const std::set< int64_t > & source_vertices, const std::set< int64_t > & sink_vertices, char * algorithm) inline
Definition at line 129 of file pgr_maxflow.hpp.
References PgrFlowGraph< G >::boost_graph, PgrFlowGraph< G >::capacity, pgr_edge_t::cost, PgrFlowGraph< G >::E_to_id, PgrFlowGraph< G >::get_boost_vertex(), PgrFlowGraph< G >::id_to_V, PgrFlowGraph< G >::residual_capacity, PgrFlowGraph< G >::rev, pgr_edge_t::reverse_cost, PgrFlowGraph< G >::sink_vertex, PgrFlowGraph< G >::source_vertex, and PgrFlowGraph< G >::V_to_id.
Referenced by do_pgr_max_flow_many_to_many(), do_pgr_max_flow_many_to_one(), do_pgr_max_flow_one_to_many(), and do_pgr_max_flow_one_to_one().
template<class G> int64_t PgrFlowGraph< G >::edmonds_karp () inline
Definition at line 114 of file pgr_maxflow.hpp.
References PgrFlowGraph< G >::boost_graph, PgrFlowGraph< G >::sink_vertex, and PgrFlowGraph< G >::source_vertex.
Referenced by do_pgr_max_flow_many_to_many(), do_pgr_max_flow_many_to_one(), do_pgr_max_flow_one_to_many(), and do_pgr_max_flow_one_to_one().
template<class G> V PgrFlowGraph< G >::get_boost_vertex (int64_t id) inline
Definition at line 96 of file pgr_maxflow.hpp.
References PgrFlowGraph< G >::id_to_V.
Referenced by PgrFlowGraph< G >::create_flow_graph().
template<class G> int64_t PgrFlowGraph< G >::get_edge_id (E e) inline
Definition at line 104 of file pgr_maxflow.hpp.
References PgrFlowGraph< G >::E_to_id.
Referenced by PgrFlowGraph< G >::get_flow_edges().
template<class G> void PgrFlowGraph< G >::get_flow_edges (std::vector< pgr_flow_t > & flow_edges) inline
Definition at line 244 of file pgr_maxflow.hpp.
References PgrFlowGraph< G >::boost_graph, PgrFlowGraph< G >::capacity, pgr_flow_t::edge, edges, pgr_flow_t::flow, PgrFlowGraph< G >::get_edge_id(), PgrFlowGraph< G >::get_vertex_id(), PgrFlowGraph< G >::residual_capacity, pgr_flow_t::residual_capacity, PgrFlowGraph< G >::sink_vertex, pgr_flow_t::source, PgrFlowGraph< G >::source_vertex, and pgr_flow_t::target.
Referenced by do_pgr_max_flow_many_to_many(), do_pgr_max_flow_many_to_one(), do_pgr_max_flow_one_to_many(), and do_pgr_max_flow_one_to_one().
template<class G> int64_t PgrFlowGraph< G >::get_vertex_id (V v) inline
Definition at line 100 of file pgr_maxflow.hpp.
References PgrFlowGraph< G >::V_to_id.
Referenced by PgrFlowGraph< G >::get_flow_edges().
template<class G> int64_t PgrFlowGraph< G >::push_relabel () inline
Definition at line 108 of file pgr_maxflow.hpp.
References PgrFlowGraph< G >::boost_graph, PgrFlowGraph< G >::sink_vertex, and PgrFlowGraph< G >::source_vertex.
Referenced by do_pgr_max_flow_many_to_many(), do_pgr_max_flow_many_to_one(), do_pgr_max_flow_one_to_many(), and do_pgr_max_flow_one_to_one().
Member Data Documentation
template<class G> G PgrFlowGraph< G >::boost_graph
Definition at line 76 of file pgr_maxflow.hpp.
Referenced by PgrFlowGraph< G >::boykov_kolmogorov(), PgrFlowGraph< G >::create_flow_graph(), PgrFlowGraph< G >::edmonds_karp(), PgrFlowGraph< G >::get_flow_edges(), and PgrFlowGraph< G >::push_relabel().
template<class G> boost::property_map<G, boost::edge_capacity_t>::type PgrFlowGraph< G >::capacity
Definition at line 83 of file pgr_maxflow.hpp.
Referenced by PgrFlowGraph< G >::create_flow_graph(), and PgrFlowGraph< G >::get_flow_edges().
template<class G> std::map<E, int64_t> PgrFlowGraph< G >::E_to_id
Definition at line 91 of file pgr_maxflow.hpp.
Referenced by PgrFlowGraph< G >::create_flow_graph(), and PgrFlowGraph< G >::get_edge_id().
template<class G> std::map<int64_t, V> PgrFlowGraph< G >::id_to_V
Definition at line 89 of file pgr_maxflow.hpp.
Referenced by PgrFlowGraph< G >::create_flow_graph(), and PgrFlowGraph< G >::get_boost_vertex().
template<class G> boost::property_map<G, boost::edge_residual_capacity_t>::type PgrFlowGraph< G >::residual_capacity
Definition at line 86 of file pgr_maxflow.hpp.
Referenced by PgrFlowGraph< G >::create_flow_graph(), and PgrFlowGraph< G >::get_flow_edges().
template<class G> boost::property_map<G, boost::edge_reverse_t>::type PgrFlowGraph< G >::rev
Definition at line 84 of file pgr_maxflow.hpp.
Referenced by PgrFlowGraph< G >::create_flow_graph().
template<class G> V PgrFlowGraph< G >::sink_vertex
Definition at line 94 of file pgr_maxflow.hpp.
Referenced by PgrFlowGraph< G >::boykov_kolmogorov(), PgrFlowGraph< G >::create_flow_graph(), PgrFlowGraph< G >::edmonds_karp(), PgrFlowGraph< G >::get_flow_edges(), and PgrFlowGraph< G >::push_relabel().
template<class G> V PgrFlowGraph< G >::source_vertex
Definition at line 93 of file pgr_maxflow.hpp.
Referenced by PgrFlowGraph< G >::boykov_kolmogorov(), PgrFlowGraph< G >::create_flow_graph(), PgrFlowGraph< G >::edmonds_karp(), PgrFlowGraph< G >::get_flow_edges(), and PgrFlowGraph< G >::push_relabel().
template<class G> std::map<V, int64_t> PgrFlowGraph< G >::V_to_id
Definition at line 90 of file pgr_maxflow.hpp.
Referenced by PgrFlowGraph< G >::create_flow_graph(), and PgrFlowGraph< G >::get_vertex_id().
The documentation for this class was generated from the following file:
pgr_maxflow.hpp