PGROUTING: pgrouting::flow::PgrEdgeDisjointPathsGraph< G > Class Template Reference
pgrouting::flow::PgrEdgeDisjointPathsGraph< G > Class Template Reference
#include "pgr_edgedisjointpaths.hpp"
Public Types
typedef boost::graph_traits< G >
::edge_descriptor E
typedef boost::graph_traits< G >
::edge_iterator E_it
typedef boost::graph_traits< G >
::out_edge_iterator Eout_it
typedef boost::graph_traits< G >
::vertex_descriptor V
typedef boost::graph_traits< G >
::vertex_iterator V_it
Public Member Functions
int64_t boykov_kolmogorov ()
void create_edge_disjoint_paths_graph (pgr_basic_edge_t *data_edges, size_t total_tuples, const std::set< int64_t > &source_vertices, const std::set< int64_t > &sink_vertices, bool directed)
void flow_dfs (V vertex, int64_t path_id, std::vector< std::vector< int64_t > > &paths)
V get_boost_vertex (int64_t id)
void get_edge_disjoint_paths (std::vector< General_path_element_t > &path_elements, int64_t flow)
int64_t get_edge_id (E e)
int64_t get_vertex_id (V v)
Public Attributes
G boost_graph
boost::property_map< G,
boost::edge_capacity_t >::type capacity
std::map< E, int64_t > E_to_id
std::map< int64_t, V > id_to_V
boost::property_map< G,
boost::edge_residual_capacity_t >
::type residual_capacity
boost::property_map< G,
boost::edge_reverse_t >::type rev
V sink_vertex
V source_vertex
std::map< V, int64_t > V_to_id
Detailed Description
template<class G>
class pgrouting::flow::PgrEdgeDisjointPathsGraph< G >
Definition at line 49 of file pgr_edgedisjointpaths.hpp.
Member Typedef Documentation
template<class G> typedef boost::graph_traits<G>::edge_descriptor pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::E
Definition at line 54 of file pgr_edgedisjointpaths.hpp.
template<class G> typedef boost::graph_traits<G>::edge_iterator pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::E_it
Definition at line 56 of file pgr_edgedisjointpaths.hpp.
template<class G> typedef boost::graph_traits<G>::out_edge_iterator pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::Eout_it
Definition at line 57 of file pgr_edgedisjointpaths.hpp.
template<class G> typedef boost::graph_traits<G>::vertex_descriptor pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::V
Definition at line 53 of file pgr_edgedisjointpaths.hpp.
template<class G> typedef boost::graph_traits<G>::vertex_iterator pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::V_it
Definition at line 55 of file pgr_edgedisjointpaths.hpp.
Member Function Documentation
template<class G> int64_t pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::boykov_kolmogorov () inline
Definition at line 83 of file pgr_edgedisjointpaths.hpp.
References pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::boost_graph, pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::sink_vertex, and pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::source_vertex.
Referenced by do_pgr_edge_disjoint_paths().
template<class G> void pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::create_edge_disjoint_paths_graph (pgr_basic_edge_t * data_edges, size_t total_tuples, const std::set< int64_t > & source_vertices, const std::set< int64_t > & sink_vertices, bool directed) inline
Definition at line 92 of file pgr_edgedisjointpaths.hpp.
References pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::boost_graph, pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::capacity, pgr_basic_edge_t::coming, pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::E_to_id, pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::get_boost_vertex(), pgr_basic_edge_t::going, pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::id_to_V, pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::residual_capacity, pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::rev, pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::sink_vertex, pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::source_vertex, and pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::V_to_id.
Referenced by do_pgr_edge_disjoint_paths().
template<class G> void pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::flow_dfs (V vertex, int64_t path_id, std::vector< std::vector< int64_t > > & paths) inline
Definition at line 187 of file pgr_edgedisjointpaths.hpp.
References pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::boost_graph, pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::capacity, pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::get_vertex_id(), pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::residual_capacity, and pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::sink_vertex.
Referenced by pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::get_edge_disjoint_paths().
template<class G> V pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::get_boost_vertex (int64_t id) inline
Definition at line 71 of file pgr_edgedisjointpaths.hpp.
References pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::id_to_V.
Referenced by pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::create_edge_disjoint_paths_graph(), and pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::get_edge_disjoint_paths().
template<class G> void pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::get_edge_disjoint_paths (std::vector< General_path_element_t > & path_elements, int64_t flow) inline
Definition at line 213 of file pgr_edgedisjointpaths.hpp.
References pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::boost_graph, pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::capacity, General_path_element_t::edge, General_path_element_t::end_id, pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::flow_dfs(), pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::get_boost_vertex(), pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::get_edge_id(), pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::get_vertex_id(), General_path_element_t::node, pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::residual_capacity, General_path_element_t::seq, pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::source_vertex, and General_path_element_t::start_id.
Referenced by do_pgr_edge_disjoint_paths().
template<class G> int64_t pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::get_edge_id (E e) inline
Definition at line 79 of file pgr_edgedisjointpaths.hpp.
References pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::E_to_id.
Referenced by pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::get_edge_disjoint_paths().
template<class G> int64_t pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::get_vertex_id (V v) inline
Definition at line 75 of file pgr_edgedisjointpaths.hpp.
References pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::V_to_id.
Referenced by pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::flow_dfs(), and pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::get_edge_disjoint_paths().
Member Data Documentation
template<class G> G pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::boost_graph
Definition at line 51 of file pgr_edgedisjointpaths.hpp.
Referenced by pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::boykov_kolmogorov(), pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::create_edge_disjoint_paths_graph(), pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::flow_dfs(), and pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::get_edge_disjoint_paths().
template<class G> boost::property_map<G, boost::edge_capacity_t>::type pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::capacity
Definition at line 59 of file pgr_edgedisjointpaths.hpp.
Referenced by pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::create_edge_disjoint_paths_graph(), pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::flow_dfs(), and pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::get_edge_disjoint_paths().
template<class G> std::map<E, int64_t> pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::E_to_id
Definition at line 66 of file pgr_edgedisjointpaths.hpp.
Referenced by pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::create_edge_disjoint_paths_graph(), and pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::get_edge_id().
template<class G> std::map<int64_t, V> pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::id_to_V
Definition at line 64 of file pgr_edgedisjointpaths.hpp.
Referenced by pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::create_edge_disjoint_paths_graph(), and pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::get_boost_vertex().
template<class G> boost::property_map<G, boost::edge_residual_capacity_t>::type pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::residual_capacity
Definition at line 62 of file pgr_edgedisjointpaths.hpp.
Referenced by pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::create_edge_disjoint_paths_graph(), pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::flow_dfs(), and pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::get_edge_disjoint_paths().
template<class G> boost::property_map<G, boost::edge_reverse_t>::type pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::rev
Definition at line 60 of file pgr_edgedisjointpaths.hpp.
Referenced by pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::create_edge_disjoint_paths_graph().
template<class G> V pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::sink_vertex
Definition at line 69 of file pgr_edgedisjointpaths.hpp.
Referenced by pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::boykov_kolmogorov(), pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::create_edge_disjoint_paths_graph(), and pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::flow_dfs().
template<class G> V pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::source_vertex
Definition at line 68 of file pgr_edgedisjointpaths.hpp.
Referenced by pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::boykov_kolmogorov(), pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::create_edge_disjoint_paths_graph(), and pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::get_edge_disjoint_paths().
template<class G> std::map<V, int64_t> pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::V_to_id
Definition at line 65 of file pgr_edgedisjointpaths.hpp.
Referenced by pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::create_edge_disjoint_paths_graph(), and pgrouting::flow::PgrEdgeDisjointPathsGraph< G >::get_vertex_id().
The documentation for this class was generated from the following file:
pgr_edgedisjointpaths.hpp