var files =
[
    [ "alpha.c", "alpha_8c.html", "alpha_8c" ],
    [ "alpha_driver.cpp", "alpha__driver_8cpp.html", "alpha__driver_8cpp" ],
    [ "alpha_driver.h", "alpha__driver_8h.html", "alpha__driver_8h" ],
    [ "arrays_input.c", "arrays__input_8c.html", "arrays__input_8c" ],
    [ "arrays_input.h", "arrays__input_8h.html", "arrays__input_8h" ],
    [ "astarManyToMany.c", "astarManyToMany_8c.html", "astarManyToMany_8c" ],
    [ "astarManyToMany_driver.cpp", "astarManyToMany__driver_8cpp.html", "astarManyToMany__driver_8cpp" ],
    [ "astarManyToMany_driver.h", "astarManyToMany__driver_8h.html", "astarManyToMany__driver_8h" ],
    [ "astarManyToOne.c", "astarManyToOne_8c.html", "astarManyToOne_8c" ],
    [ "astarOneToMany.c", "astarOneToMany_8c.html", "astarOneToMany_8c" ],
    [ "astarOneToMany_driver.cpp", "astarOneToMany__driver_8cpp.html", "astarOneToMany__driver_8cpp" ],
    [ "astarOneToMany_driver.h", "astarOneToMany__driver_8h.html", "astarOneToMany__driver_8h" ],
    [ "astarOneToOne.c", "astarOneToOne_8c.html", "astarOneToOne_8c" ],
    [ "astarOneToOne_driver.cpp", "astarOneToOne__driver_8cpp.html", "astarOneToOne__driver_8cpp" ],
    [ "astarOneToOne_driver.h", "astarOneToOne__driver_8h.html", "astarOneToOne__driver_8h" ],
    [ "basePath_SSEC.cpp", "basePath__SSEC_8cpp.html", "basePath__SSEC_8cpp" ],
    [ "basePath_SSEC.hpp", "basePath__SSEC_8hpp.html", [
      [ "Path", "classPath.html", "classPath" ]
    ] ],
    [ "basic_edge.cpp", "basic__edge_8cpp.html", null ],
    [ "basic_edge.h", "basic__edge_8h.html", [
      [ "Basic_edge", "classpgrouting_1_1Basic__edge.html", "classpgrouting_1_1Basic__edge" ]
    ] ],
    [ "basic_vertex.cpp", "basic__vertex_8cpp.html", "basic__vertex_8cpp" ],
    [ "basic_vertex.h", "basic__vertex_8h.html", "basic__vertex_8h" ],
    [ "bdastar.c", "bdastar_8c.html", "bdastar_8c" ],
    [ "bdastar_driver.cpp", "bdastar__driver_8cpp.html", "bdastar__driver_8cpp" ],
    [ "bdastar_driver.h", "bdastar__driver_8h.html", "bdastar__driver_8h" ],
    [ "BDATester.cpp", "BDATester_8cpp.html", "BDATester_8cpp" ],
    [ "bdsp.c", "bdsp_8c.html", "bdsp_8c" ],
    [ "bdsp_driver.cpp", "bdsp__driver_8cpp.html", "bdsp__driver_8cpp" ],
    [ "bdsp_driver.h", "bdsp__driver_8h.html", "bdsp__driver_8h" ],
    [ "src/BiDirAStar.cpp", "src_2BiDirAStar_8cpp.html", null ],
    [ "tester/BiDirAStar.cpp", "tester_2BiDirAStar_8cpp.html", null ],
    [ "src/BiDirAStar.h", "src_2BiDirAStar_8h.html", "src_2BiDirAStar_8h" ],
    [ "tester/BiDirAStar.h", "tester_2BiDirAStar_8h.html", "tester_2BiDirAStar_8h" ],
    [ "BiDirDijkstra.cpp", "BiDirDijkstra_8cpp.html", null ],
    [ "BiDirDijkstra.h", "BiDirDijkstra_8h.html", "BiDirDijkstra_8h" ],
    [ "boost_interface_drivedist.cpp", "boost__interface__drivedist_8cpp.html", "boost__interface__drivedist_8cpp" ],
    [ "boost_interface_drivedist.h", "boost__interface__drivedist_8h.html", "boost__interface__drivedist_8h" ],
    [ "boost_wrapper.cpp", "boost__wrapper_8cpp.html", "boost__wrapper_8cpp" ],
    [ "ch_edge.cpp", "ch__edge_8cpp.html", "ch__edge_8cpp" ],
    [ "ch_edge.h", "ch__edge_8h.html", [
      [ "Edge", "classpgrouting_1_1contraction_1_1Edge.html", "classpgrouting_1_1contraction_1_1Edge" ]
    ] ],
    [ "ch_vertex.cpp", "ch__vertex_8cpp.html", "ch__vertex_8cpp" ],
    [ "ch_vertex.h", "ch__vertex_8h.html", "ch__vertex_8h" ],
    [ "contractGraph.c", "contractGraph_8c.html", "contractGraph_8c" ],
    [ "contractGraph_driver.cpp", "contractGraph__driver_8cpp.html", "contractGraph__driver_8cpp" ],
    [ "contractGraph_driver.h", "contractGraph__driver_8h.html", "contractGraph__driver_8h" ],
    [ "coordinates_input.c", "coordinates__input_8c.html", "coordinates__input_8c" ],
    [ "coordinates_input.h", "coordinates__input_8h.html", "coordinates__input_8h" ],
    [ "customers_input.c", "customers__input_8c.html", "customers__input_8c" ],
    [ "customers_input.h", "customers__input_8h.html", "customers__input_8h" ],
    [ "debug_macro.h", "debug__macro_8h.html", "debug__macro_8h" ],
    [ "dijkstra.h", "dijkstra_8h.html", "dijkstra_8h" ],
    [ "dijkstra.hpp", "dijkstra_8hpp.html", "dijkstra_8hpp" ],
    [ "performance/dijkstra/dijkstra.hpp", "performance_2dijkstra_2dijkstra_8hpp.html", "performance_2dijkstra_2dijkstra_8hpp" ],
    [ "dijkstraVia.c", "dijkstraVia_8c.html", "dijkstraVia_8c" ],
    [ "dijkstraVia_driver.cpp", "dijkstraVia__driver_8cpp.html", "dijkstraVia__driver_8cpp" ],
    [ "dijkstraVia_driver.h", "dijkstraVia__driver_8h.html", "dijkstraVia__driver_8h" ],
    [ "Dmatrix.cpp", "Dmatrix_8cpp.html", "Dmatrix_8cpp" ],
    [ "Dmatrix.h", "Dmatrix_8h.html", [
      [ "Dmatrix", "classpgrouting_1_1tsp_1_1Dmatrix.html", "classpgrouting_1_1tsp_1_1Dmatrix" ]
    ] ],
    [ "drivedist.c", "drivedist_8c.html", "drivedist_8c" ],
    [ "driving.cpp", "driving_8cpp.html", "driving_8cpp" ],
    [ "edge_disjoint_paths_many_to_many.c", "edge__disjoint__paths__many__to__many_8c.html", "edge__disjoint__paths__many__to__many_8c" ],
    [ "edge_disjoint_paths_many_to_many_driver.cpp", "edge__disjoint__paths__many__to__many__driver_8cpp.html", "edge__disjoint__paths__many__to__many__driver_8cpp" ],
    [ "edge_disjoint_paths_many_to_many_driver.h", "edge__disjoint__paths__many__to__many__driver_8h.html", "edge__disjoint__paths__many__to__many__driver_8h" ],
    [ "edge_disjoint_paths_many_to_one.c", "edge__disjoint__paths__many__to__one_8c.html", "edge__disjoint__paths__many__to__one_8c" ],
    [ "edge_disjoint_paths_many_to_one_driver.cpp", "edge__disjoint__paths__many__to__one__driver_8cpp.html", "edge__disjoint__paths__many__to__one__driver_8cpp" ],
    [ "edge_disjoint_paths_many_to_one_driver.h", "edge__disjoint__paths__many__to__one__driver_8h.html", "edge__disjoint__paths__many__to__one__driver_8h" ],
    [ "edge_disjoint_paths_one_to_many.c", "edge__disjoint__paths__one__to__many_8c.html", "edge__disjoint__paths__one__to__many_8c" ],
    [ "edge_disjoint_paths_one_to_many_driver.cpp", "edge__disjoint__paths__one__to__many__driver_8cpp.html", "edge__disjoint__paths__one__to__many__driver_8cpp" ],
    [ "edge_disjoint_paths_one_to_many_driver.h", "edge__disjoint__paths__one__to__many__driver_8h.html", "edge__disjoint__paths__one__to__many__driver_8h" ],
    [ "edge_disjoint_paths_one_to_one.c", "edge__disjoint__paths__one__to__one_8c.html", "edge__disjoint__paths__one__to__one_8c" ],
    [ "edge_disjoint_paths_one_to_one_driver.cpp", "edge__disjoint__paths__one__to__one__driver_8cpp.html", "edge__disjoint__paths__one__to__one__driver_8cpp" ],
    [ "edge_disjoint_paths_one_to_one_driver.h", "edge__disjoint__paths__one__to__one__driver_8h.html", "edge__disjoint__paths__one__to__one__driver_8h" ],
    [ "edges_input.c", "edges__input_8c.html", "edges__input_8c" ],
    [ "edges_input.h", "edges__input_8h.html", "edges__input_8h" ],
    [ "eucledianDmatrix.cpp", "eucledianDmatrix_8cpp.html", "eucledianDmatrix_8cpp" ],
    [ "eucledianDmatrix.h", "eucledianDmatrix_8h.html", [
      [ "eucledianDmatrix", "classpgrouting_1_1tsp_1_1eucledianDmatrix.html", "classpgrouting_1_1tsp_1_1eucledianDmatrix" ]
    ] ],
    [ "eucledianTSP.c", "eucledianTSP_8c.html", "eucledianTSP_8c" ],
    [ "eucledianTSP_driver.cpp", "eucledianTSP__driver_8cpp.html", "eucledianTSP__driver_8cpp" ],
    [ "eucledianTSP_driver.h", "eucledianTSP__driver_8h.html", "eucledianTSP__driver_8h" ],
    [ "floydWarshall.c", "floydWarshall_8c.html", "floydWarshall_8c" ],
    [ "floydWarshall_driver.cpp", "floydWarshall__driver_8cpp.html", "floydWarshall__driver_8cpp" ],
    [ "floydWarshall_driver.h", "floydWarshall__driver_8h.html", "floydWarshall__driver_8h" ],
    [ "get_check_data.c", "get__check__data_8c.html", "get__check__data_8c" ],
    [ "get_check_data.h", "get__check__data_8h.html", "get__check__data_8h" ],
    [ "get_new_queries.cpp", "get__new__queries_8cpp.html", "get__new__queries_8cpp" ],
    [ "get_new_queries.h", "get__new__queries_8h.html", "get__new__queries_8h" ],
    [ "GraphDefinition.cpp", "GraphDefinition_8cpp.html", null ],
    [ "GraphDefinition.h", "GraphDefinition_8h.html", "GraphDefinition_8h" ],
    [ "identifiers.hpp", "identifiers_8hpp.html", "identifiers_8hpp" ],
    [ "initial_solution.cpp", "initial__solution_8cpp.html", null ],
    [ "initial_solution.h", "initial__solution_8h.html", [
      [ "Initial_solution", "classpgrouting_1_1vrp_1_1Initial__solution.html", "classpgrouting_1_1vrp_1_1Initial__solution" ]
    ] ],
    [ "issue191-bad-m1.h", "issue191-bad-m1_8h.html", "issue191-bad-m1_8h" ],
    [ "issue191-bad.h", "issue191-bad_8h.html", "issue191-bad_8h" ],
    [ "issue191-good.h", "issue191-good_8h.html", "issue191-good_8h" ],
    [ "johnson.c", "johnson_8c.html", "johnson_8c" ],
    [ "johnson_driver.cpp", "johnson__driver_8cpp.html", "johnson__driver_8cpp" ],
    [ "johnson_driver.h", "johnson__driver_8h.html", "johnson__driver_8h" ],
    [ "ksp.c", "ksp_8c.html", "ksp_8c" ],
    [ "ksp.cpp", "ksp_8cpp.html", "ksp_8cpp" ],
    [ "ksp_driver.cpp", "ksp__driver_8cpp.html", "ksp__driver_8cpp" ],
    [ "ksp_driver.h", "ksp__driver_8h.html", "ksp__driver_8h" ],
    [ "many_to_dist_driving_distance.c", "many__to__dist__driving__distance_8c.html", "many__to__dist__driving__distance_8c" ],
    [ "many_to_dist_withPointsDD.c", "many__to__dist__withPointsDD_8c.html", "many__to__dist__withPointsDD_8c" ],
    [ "many_to_many_dijkstra.c", "many__to__many__dijkstra_8c.html", "many__to__many__dijkstra_8c" ],
    [ "many_to_many_dijkstra_driver.cpp", "many__to__many__dijkstra__driver_8cpp.html", "many__to__many__dijkstra__driver_8cpp" ],
    [ "many_to_many_dijkstra_driver.h", "many__to__many__dijkstra__driver_8h.html", "many__to__many__dijkstra__driver_8h" ],
    [ "many_to_many_withPoints.c", "many__to__many__withPoints_8c.html", "many__to__many__withPoints_8c" ],
    [ "many_to_many_withPoints_driver.cpp", "many__to__many__withPoints__driver_8cpp.html", "many__to__many__withPoints__driver_8cpp" ],
    [ "many_to_many_withPoints_driver.h", "many__to__many__withPoints__driver_8h.html", "many__to__many__withPoints__driver_8h" ],
    [ "many_to_one_dijkstra.c", "many__to__one__dijkstra_8c.html", "many__to__one__dijkstra_8c" ],
    [ "many_to_one_dijkstra_driver.cpp", "many__to__one__dijkstra__driver_8cpp.html", "many__to__one__dijkstra__driver_8cpp" ],
    [ "many_to_one_dijkstra_driver.h", "many__to__one__dijkstra__driver_8h.html", "many__to__one__dijkstra__driver_8h" ],
    [ "many_to_one_withPoints.c", "many__to__one__withPoints_8c.html", "many__to__one__withPoints_8c" ],
    [ "many_to_one_withPoints_driver.cpp", "many__to__one__withPoints__driver_8cpp.html", "many__to__one__withPoints__driver_8cpp" ],
    [ "many_to_one_withPoints_driver.h", "many__to__one__withPoints__driver_8h.html", "many__to__one__withPoints__driver_8h" ],
    [ "matrixRows_input.c", "matrixRows__input_8c.html", "matrixRows__input_8c" ],
    [ "matrixRows_input.h", "matrixRows__input_8h.html", "matrixRows__input_8h" ],
    [ "max_flow_many_to_many.c", "max__flow__many__to__many_8c.html", "max__flow__many__to__many_8c" ],
    [ "max_flow_many_to_many_driver.cpp", "max__flow__many__to__many__driver_8cpp.html", "max__flow__many__to__many__driver_8cpp" ],
    [ "max_flow_many_to_many_driver.h", "max__flow__many__to__many__driver_8h.html", "max__flow__many__to__many__driver_8h" ],
    [ "max_flow_many_to_one.c", "max__flow__many__to__one_8c.html", "max__flow__many__to__one_8c" ],
    [ "max_flow_many_to_one_driver.cpp", "max__flow__many__to__one__driver_8cpp.html", "max__flow__many__to__one__driver_8cpp" ],
    [ "max_flow_many_to_one_driver.h", "max__flow__many__to__one__driver_8h.html", "max__flow__many__to__one__driver_8h" ],
    [ "max_flow_one_to_many.c", "max__flow__one__to__many_8c.html", "max__flow__one__to__many_8c" ],
    [ "max_flow_one_to_many_driver.cpp", "max__flow__one__to__many__driver_8cpp.html", "max__flow__one__to__many__driver_8cpp" ],
    [ "max_flow_one_to_many_driver.h", "max__flow__one__to__many__driver_8h.html", "max__flow__one__to__many__driver_8h" ],
    [ "max_flow_one_to_one.c", "max__flow__one__to__one_8c.html", "max__flow__one__to__one_8c" ],
    [ "max_flow_one_to_one_driver.cpp", "max__flow__one__to__one__driver_8cpp.html", "max__flow__one__to__one__driver_8cpp" ],
    [ "max_flow_one_to_one_driver.h", "max__flow__one__to__one__driver_8h.html", "max__flow__one__to__one__driver_8h" ],
    [ "maximum_cardinality_matching.c", "maximum__cardinality__matching_8c.html", "maximum__cardinality__matching_8c" ],
    [ "maximum_cardinality_matching_driver.cpp", "maximum__cardinality__matching__driver_8cpp.html", "maximum__cardinality__matching__driver_8cpp" ],
    [ "maximum_cardinality_matching_driver.h", "maximum__cardinality__matching__driver_8h.html", "maximum__cardinality__matching__driver_8h" ],
    [ "src/MinHeap.cpp", "src_2MinHeap_8cpp.html", null ],
    [ "tester/MinHeap.cpp", "tester_2MinHeap_8cpp.html", null ],
    [ "src/MinHeap.h", "src_2MinHeap_8h.html", "src_2MinHeap_8h" ],
    [ "tester/MinHeap.h", "tester_2MinHeap_8h.html", "tester_2MinHeap_8h" ],
    [ "msg_logger.hpp", "msg__logger_8hpp.html", "msg__logger_8hpp" ],
    [ "newTSP.c", "newTSP_8c.html", "newTSP_8c" ],
    [ "newTSP_driver.cpp", "newTSP__driver_8cpp.html", "newTSP__driver_8cpp" ],
    [ "newTSP_driver.h", "newTSP__driver_8h.html", "newTSP__driver_8h" ],
    [ "node.cpp", "node_8cpp.html", "node_8cpp" ],
    [ "node.h", "node_8h.html", [
      [ "Node", "classpgrouting_1_1vrp_1_1Node.html", "classpgrouting_1_1vrp_1_1Node" ]
    ] ],
    [ "one_to_many_dijkstra.c", "one__to__many__dijkstra_8c.html", "one__to__many__dijkstra_8c" ],
    [ "one_to_many_dijkstra_driver.cpp", "one__to__many__dijkstra__driver_8cpp.html", "one__to__many__dijkstra__driver_8cpp" ],
    [ "one_to_many_dijkstra_driver.h", "one__to__many__dijkstra__driver_8h.html", "one__to__many__dijkstra__driver_8h" ],
    [ "one_to_many_withPoints.c", "one__to__many__withPoints_8c.html", "one__to__many__withPoints_8c" ],
    [ "one_to_many_withPoints_driver.cpp", "one__to__many__withPoints__driver_8cpp.html", "one__to__many__withPoints__driver_8cpp" ],
    [ "one_to_many_withPoints_driver.h", "one__to__many__withPoints__driver_8h.html", "one__to__many__withPoints__driver_8h" ],
    [ "one_to_one_dijkstra.c", "one__to__one__dijkstra_8c.html", "one__to__one__dijkstra_8c" ],
    [ "one_to_one_dijkstra_driver.cpp", "one__to__one__dijkstra__driver_8cpp.html", "one__to__one__dijkstra__driver_8cpp" ],
    [ "one_to_one_dijkstra_driver.h", "one__to__one__dijkstra__driver_8h.html", "one__to__one__dijkstra__driver_8h" ],
    [ "one_to_one_withPoints.c", "one__to__one__withPoints_8c.html", "one__to__one__withPoints_8c" ],
    [ "one_to_one_withPoints_driver.cpp", "one__to__one__withPoints__driver_8cpp.html", "one__to__one__withPoints__driver_8cpp" ],
    [ "one_to_one_withPoints_driver.h", "one__to__one__withPoints__driver_8h.html", "one__to__one__withPoints__driver_8h" ],
    [ "optimize.cpp", "optimize_8cpp.html", null ],
    [ "optimize.h", "optimize_8h.html", [
      [ "Optimize", "classpgrouting_1_1vrp_1_1Optimize.html", "classpgrouting_1_1vrp_1_1Optimize" ]
    ] ],
    [ "order.cpp", "order_8cpp.html", "order_8cpp" ],
    [ "order.h", "order_8h.html", [
      [ "Order", "classpgrouting_1_1vrp_1_1Order.html", "classpgrouting_1_1vrp_1_1Order" ]
    ] ],
    [ "pgr_alloc.hpp", "pgr__alloc_8hpp.html", "pgr__alloc_8hpp" ],
    [ "pgr_allpairs.hpp", "pgr__allpairs_8hpp.html", "pgr__allpairs_8hpp" ],
    [ "pgr_assert.cpp", "pgr__assert_8cpp.html", "pgr__assert_8cpp" ],
    [ "pgr_assert.h", "pgr__assert_8h.html", "pgr__assert_8h" ],
    [ "pgr_astar.hpp", "pgr__astar_8hpp.html", [
      [ "Pgr_astar", "classPgr__astar.html", "classPgr__astar" ],
      [ "astar_many_goals_visitor", "classPgr__astar_1_1astar__many__goals__visitor.html", "classPgr__astar_1_1astar__many__goals__visitor" ],
      [ "astar_one_goal_visitor", "classPgr__astar_1_1astar__one__goal__visitor.html", "classPgr__astar_1_1astar__one__goal__visitor" ],
      [ "distance_heuristic", "classPgr__astar_1_1distance__heuristic.html", "classPgr__astar_1_1distance__heuristic" ],
      [ "found_goals", "structPgr__astar_1_1found__goals.html", null ]
    ] ],
    [ "pgr_base_graph.hpp", "pgr__base__graph_8hpp.html", "pgr__base__graph_8hpp" ],
    [ "pgr_contract.hpp", "pgr__contract_8hpp.html", "pgr__contract_8hpp" ],
    [ "pgr_contractionGraph.hpp", "pgr__contractionGraph_8hpp.html", "pgr__contractionGraph_8hpp" ],
    [ "pgr_deadEndContraction.hpp", "pgr__deadEndContraction_8hpp.html", [
      [ "Pgr_deadEndContraction", "classpgrouting_1_1Pgr__deadEndContraction.html", "classpgrouting_1_1Pgr__deadEndContraction" ]
    ] ],
    [ "pgr_dijkstra.hpp", "pgr__dijkstra_8hpp.html", "pgr__dijkstra_8hpp" ],
    [ "pgr_edgedisjointpaths.hpp", "pgr__edgedisjointpaths_8hpp.html", [
      [ "PgrEdgeDisjointPathsGraph", "classPgrEdgeDisjointPathsGraph.html", "classPgrEdgeDisjointPathsGraph" ]
    ] ],
    [ "pgr_ksp.cpp", "pgr__ksp_8cpp.html", null ],
    [ "pgr_ksp.hpp", "pgr__ksp_8hpp.html", [
      [ "Pgr_ksp", "classPgr__ksp.html", "classPgr__ksp" ],
      [ "compPaths", "classPgr__ksp_1_1compPaths.html", "classPgr__ksp_1_1compPaths" ]
    ] ],
    [ "pgr_linearContraction.hpp", "pgr__linearContraction_8hpp.html", [
      [ "Pgr_linearContraction", "classpgrouting_1_1Pgr__linearContraction.html", "classpgrouting_1_1Pgr__linearContraction" ]
    ] ],
    [ "pgr_logger.h", "pgr__logger_8h.html", "pgr__logger_8h" ],
    [ "pgr_maxflow.hpp", "pgr__maxflow_8hpp.html", "pgr__maxflow_8hpp" ],
    [ "pgr_maximumcardinalitymatching.hpp", "pgr__maximumcardinalitymatching_8hpp.html", "pgr__maximumcardinalitymatching_8hpp" ],
    [ "pgr_pickDeliver.cpp", "pgr__pickDeliver_8cpp.html", "pgr__pickDeliver_8cpp" ],
    [ "pgr_pickDeliver.h", "pgr__pickDeliver_8h.html", [
      [ "Pgr_pickDeliver", "classpgrouting_1_1vrp_1_1Pgr__pickDeliver.html", "classpgrouting_1_1vrp_1_1Pgr__pickDeliver" ]
    ] ],
    [ "pgr_tsp.cpp", "pgr__tsp_8cpp.html", "pgr__tsp_8cpp" ],
    [ "pgr_tsp.hpp", "pgr__tsp_8hpp.html", [
      [ "TSP", "classpgrouting_1_1tsp_1_1TSP.html", "classpgrouting_1_1tsp_1_1TSP" ]
    ] ],
    [ "pgr_types.h", "pgr__types_8h.html", "pgr__types_8h" ],
    [ "pgr_withPoints.cpp", "pgr__withPoints_8cpp.html", "pgr__withPoints_8cpp" ],
    [ "pgr_withPoints.hpp", "pgr__withPoints_8hpp.html", "pgr__withPoints_8hpp" ],
    [ "performance/dijkstra/pgRouting.cpp", "performance_2dijkstra_2pgRouting_8cpp.html", "performance_2dijkstra_2pgRouting_8cpp" ],
    [ "pgRouting.cpp", "pgRouting_8cpp.html", "pgRouting_8cpp" ],
    [ "pickDeliver.c", "pickDeliver_8c.html", "pickDeliver_8c" ],
    [ "pickDeliver_driver.cpp", "pickDeliver__driver_8cpp.html", "pickDeliver__driver_8cpp" ],
    [ "pickDeliver_driver.h", "pickDeliver__driver_8h.html", "pickDeliver__driver_8h" ],
    [ "points_input.c", "points__input_8c.html", "points__input_8c" ],
    [ "points_input.h", "points__input_8h.html", "points__input_8h" ],
    [ "postgres.h", "postgres_8h.html", "postgres_8h" ],
    [ "postgres_connection.c", "postgres__connection_8c.html", "postgres__connection_8c" ],
    [ "postgres_connection.h", "postgres__connection_8h.html", "postgres__connection_8h" ],
    [ "restrictions_input.c", "restrictions__input_8c.html", "restrictions__input_8c" ],
    [ "restrictions_input.h", "restrictions__input_8h.html", "restrictions__input_8h" ],
    [ "signalhandler.cpp", "signalhandler_8cpp.html", null ],
    [ "signalhandler.h", "signalhandler_8h.html", "signalhandler_8h" ],
    [ "solution.cpp", "solution_8cpp.html", "solution_8cpp" ],
    [ "solution.h", "solution_8h.html", [
      [ "Solution", "classpgrouting_1_1vrp_1_1Solution.html", "classpgrouting_1_1vrp_1_1Solution" ]
    ] ],
    [ "structs.h", "structs_8h.html", [
      [ "pgr_contracted_blob", "structpgr__contracted__blob.html", "structpgr__contracted__blob" ]
    ] ],
    [ "test1.c", "test1_8c.html", "test1_8c" ],
    [ "test2.cpp", "test2_8cpp.html", "test2_8cpp" ],
    [ "test_c_edges.c", "test__c__edges_8c.html", "test__c__edges_8c" ],
    [ "test_c_edges_driver.cpp", "test__c__edges__driver_8cpp.html", "test__c__edges__driver_8cpp" ],
    [ "test_c_edges_driver.h", "test__c__edges__driver_8h.html", "test__c__edges__driver_8h" ],
    [ "test_matrixRows.c", "test__matrixRows_8c.html", "test__matrixRows_8c" ],
    [ "test_matrixRows_driver.cpp", "test__matrixRows__driver_8cpp.html", "test__matrixRows__driver_8cpp" ],
    [ "test_matrixRows_driver.h", "test__matrixRows__driver_8h.html", "test__matrixRows__driver_8h" ],
    [ "Tester.cpp", "Tester_8cpp.html", "Tester_8cpp" ],
    [ "testit.c", "testit_8c.html", "testit_8c" ],
    [ "testit.cpp", "testit_8cpp.html", "testit_8cpp" ],
    [ "testXYedges.c", "testXYedges_8c.html", "testXYedges_8c" ],
    [ "testXYedges_driver.cpp", "testXYedges__driver_8cpp.html", "testXYedges__driver_8cpp" ],
    [ "testXYedges_driver.h", "testXYedges__driver_8h.html", "testXYedges__driver_8h" ],
    [ "time_msg.c", "time__msg_8c.html", "time__msg_8c" ],
    [ "time_msg.h", "time__msg_8h.html", "time__msg_8h" ],
    [ "tour.cpp", "tour_8cpp.html", "tour_8cpp" ],
    [ "tour.h", "tour_8h.html", [
      [ "Tour", "classpgrouting_1_1tsp_1_1Tour.html", "classpgrouting_1_1tsp_1_1Tour" ]
    ] ],
    [ "trsp.c", "trsp_8c.html", "trsp_8c" ],
    [ "trsp_driver.cpp", "trsp__driver_8cpp.html", "trsp__driver_8cpp" ],
    [ "trsp_driver.h", "trsp__driver_8h.html", "trsp__driver_8h" ],
    [ "tsp.h", "tsp_8h.html", "tsp_8h" ],
    [ "tsp2.c", "tsp2_8c.html", "tsp2_8c" ],
    [ "tsplib.c", "tsplib_8c.html", "tsplib_8c" ],
    [ "tw_node.cpp", "tw__node_8cpp.html", "tw__node_8cpp" ],
    [ "tw_node.h", "tw__node_8h.html", [
      [ "Tw_node", "classpgrouting_1_1vrp_1_1Tw__node.html", "classpgrouting_1_1vrp_1_1Tw__node" ]
    ] ],
    [ "Utils.h", "Utils_8h.html", "Utils_8h" ],
    [ "utils.h", "utils_8h.html", "utils_8h" ],
    [ "vehicle.cpp", "vehicle_8cpp.html", "vehicle_8cpp" ],
    [ "vehicle.h", "vehicle_8h.html", [
      [ "Vehicle", "classpgrouting_1_1vrp_1_1Vehicle.html", "classpgrouting_1_1vrp_1_1Vehicle" ]
    ] ],
    [ "vehicle_node.cpp", "vehicle__node_8cpp.html", "vehicle__node_8cpp" ],
    [ "vehicle_node.h", "vehicle__node_8h.html", [
      [ "Vehicle_node", "classpgrouting_1_1vrp_1_1Vehicle__node.html", "classpgrouting_1_1vrp_1_1Vehicle__node" ]
    ] ],
    [ "vehicle_pickDeliver.cpp", "vehicle__pickDeliver_8cpp.html", null ],
    [ "vehicle_pickDeliver.h", "vehicle__pickDeliver_8h.html", [
      [ "Vehicle_pickDeliver", "classpgrouting_1_1vrp_1_1Vehicle__pickDeliver.html", "classpgrouting_1_1vrp_1_1Vehicle__pickDeliver" ]
    ] ],
    [ "VRP.c", "VRP_8c.html", "VRP_8c" ],
    [ "VRP.h", "VRP_8h.html", "VRP_8h" ],
    [ "VRP_core.cpp", "VRP__core_8cpp.html", "VRP__core_8cpp" ],
    [ "VRP_Solver.cpp", "VRP__Solver_8cpp.html", "VRP__Solver_8cpp" ],
    [ "VRP_Solver.h", "VRP__Solver_8h.html", "VRP__Solver_8h" ],
    [ "warshall.hpp", "warshall_8hpp.html", "warshall_8hpp" ],
    [ "withPoints_dd.c", "withPoints__dd_8c.html", "withPoints__dd_8c" ],
    [ "withPoints_dd_driver.cpp", "withPoints__dd__driver_8cpp.html", "withPoints__dd__driver_8cpp" ],
    [ "withPoints_dd_driver.h", "withPoints__dd__driver_8h.html", "withPoints__dd__driver_8h" ],
    [ "withPoints_ksp.c", "withPoints__ksp_8c.html", "withPoints__ksp_8c" ],
    [ "withPoints_ksp_driver.cpp", "withPoints__ksp__driver_8cpp.html", "withPoints__ksp__driver_8cpp" ],
    [ "withPoints_ksp_driver.h", "withPoints__ksp__driver_8h.html", "withPoints__ksp__driver_8h" ],
    [ "xy_vertex.cpp", "xy__vertex_8cpp.html", "xy__vertex_8cpp" ],
    [ "xy_vertex.h", "xy__vertex_8h.html", "xy__vertex_8h" ]
];