pgRouting: alpha.h File Reference
alpha.h File Reference
#include "postgres.h"
#include "../../common/src/pgr_types.h"
Classes
struct vertex
Macros
#define _ALPHA_H
Typedefs
typedef struct vertex vertex_t
Functions
int alpha_shape (vertex_t *vertices, size_t count, double alpha, vertex_t **res, size_t *res_count, char **err_msg)
Macro Definition Documentation
#define _ALPHA_H
Definition at line 25 of file alpha.h.
Typedef Documentation
typedef struct vertex vertex_t
Function Documentation
int alpha_shape (vertex_t * vertices, size_t count, double alpha, vertex_t ** res, size_t * res_count, char ** err_msg)
Definition at line 190 of file alpha_drivedist.cpp.
References alpha_edges(), find_next_edge(), p, vertex::x, point::x, x, and y.
Referenced by compute_alpha_shape().