pgRouting: astarOneToOne_driver.cpp File Reference
astarOneToOne_driver.cpp File Reference
#include <sstream>
#include <deque>
#include <algorithm>
#include <vector>
#include "./astarOneToOne_driver.h"
#include "./../../common/src/pgr_types.h"
#include "./pgr_astar.hpp"
#include "./../../common/src/pgr_assert.h"
#include "./../../common/src/pgr_alloc.hpp"
Macros
#define DEBUG
Functions
void do_pgr_astarOneToOne (Pgr_edge_xy_t *data_edges, size_t total_edges, int64_t start_vid, int64_t end_vid, bool directed, int heuristic, double factor, double epsilon, bool only_cost, General_path_element_t **return_tuples, size_t *return_count, char **log_msg, char **err_msg)
template<class G >
void pgr_astar (G &graph, Path &path, int64_t source, int64_t target, int heuristic, double factor, double epsilon, bool only_cost=false)
Macro Definition Documentation
#define DEBUG
Definition at line 42 of file astarOneToOne_driver.cpp.
Function Documentation
void do_pgr_astarOneToOne (Pgr_edge_xy_t * data_edges, size_t total_edges, int64_t start_vid, int64_t end_vid, bool directed, int heuristic, double factor, double epsilon, bool only_cost, General_path_element_t ** return_tuples, size_t * return_count, char ** log_msg, char ** err_msg)
Definition at line 75 of file astarOneToOne_driver.cpp.
References DIRECTED, Path::generate_postgres_data(), pgRouting::graph::Pgr_base_graph< G, Vertex, Edge >::graph_insert_data(), path, pgassert, pgr_alloc(), pgr_astar(), Path::size(), UNDIRECTED, and AssertFailedException::what().
Referenced by process().
template<class G > void pgr_astar (G & graph, Path & path, int64_t source, int64_t target, int heuristic, double factor, double epsilon, bool only_cost = false)
Definition at line 55 of file astarOneToOne_driver.cpp.
References Pgr_astar< G >::astar().
Referenced by do_pgr_astarOneToOne().