pgRouting: bdastar.c File Reference
bdastar.c File Reference
#include "../../common/src/pgr_types.h"
#include "postgres.h"
#include "executor/spi.h"
#include "funcapi.h"
#include "catalog/pg_type.h"
#include <stdio.h>
#include <stdlib.h>
#include <search.h>
#include "../../common/src/postgres_connection.h"
#include "bdastar.h"
#include "../../common/src/debug_macro.h"
Classes
struct edge_astar_columns
Macros
#define TUPLIMIT 1000
Typedefs
typedef struct edge_astar_columns edge_astar_columns_t
Functions
Datum bidir_astar_shortest_path (PG_FUNCTION_ARGS)
static int compute_shortest_path_astar (char *sql, int source_vertex_id, int target_vertex_id, bool directed, bool has_reverse_cost, path_element_t **path, size_t *path_count)
static void fetch_edge_astar (HeapTuple *tuple, TupleDesc *tupdesc, edge_astar_columns_t *edge_columns, edge_astar_t *target_edge)
static int fetch_edge_astar_columns (SPITupleTable *tuptable, edge_astar_columns_t *edge_columns, bool has_reverse_cost)
PG_FUNCTION_INFO_V1 (bidir_astar_shortest_path)
Macro Definition Documentation
#define TUPLIMIT 1000
Definition at line 54 of file bdastar.c.
Referenced by compute_shortest_path_astar().
Typedef Documentation
typedef struct edge_astar_columns edge_astar_columns_t
Function Documentation
PGDLLEXPORT Datum bidir_astar_shortest_path (PG_FUNCTION_ARGS)
Definition at line 350 of file bdastar.c.
References compute_shortest_path_astar(), path, path_count, PGR_DBG, and pgr_text2char().
static int compute_shortest_path_astar (char * sql, int source_vertex_id, int target_vertex_id, bool directed, bool has_reverse_cost, path_element_t ** path, size_t * path_count) static
Definition at line 196 of file bdastar.c.
References bdastar_wrapper(), edges, err_msg, fetch_edge_astar(), fetch_edge_astar_columns(), edge_columns::id, edge_astar_columns::id, path_count, PGR_DBG, pgr_SPI_connect(), pgr_SPI_cursor_open(), pgr_SPI_finish(), pgr_SPI_prepare(), edge::source, edge::target, and TUPLIMIT.
Referenced by bidir_astar_shortest_path().
static void fetch_edge_astar (HeapTuple * tuple, TupleDesc * tupdesc, edge_astar_columns_t * edge_columns, edge_astar_t * target_edge) static
Definition at line 147 of file bdastar.c.
References edge_astar_columns::cost, edge::cost, edge_astar_columns::id, edge::id, edge_astar_columns::reverse_cost, edge::reverse_cost, edge_astar_columns::s_x, edge::s_x, edge_astar_columns::s_y, edge::s_y, edge_astar_columns::source, edge::source, edge_astar_columns::t_x, edge::t_x, edge_astar_columns::t_y, edge::t_y, edge_astar_columns::target, and edge::target.
Referenced by compute_shortest_path_astar().
static int fetch_edge_astar_columns (SPITupleTable * tuptable, edge_astar_columns_t * edge_columns, bool has_reverse_cost) static
Definition at line 71 of file bdastar.c.
References edge_astar_columns::cost, edge_astar_columns::id, PGR_DBG, edge_astar_columns::reverse_cost, edge_astar_columns::s_x, edge_astar_columns::s_y, edge_astar_columns::source, edge_astar_columns::t_x, edge_astar_columns::t_y, and edge_astar_columns::target.
Referenced by compute_shortest_path_astar().
PG_FUNCTION_INFO_V1 (bidir_astar_shortest_path)