pgRouting: bdsp.c File Reference
bdsp.c File Reference
#include "postgres.h"
#include "executor/spi.h"
#include "funcapi.h"
#include "catalog/pg_type.h"
#include "fmgr.h"
#include "bdsp_driver.h"
#include "../../common/src/debug_macro.h"
#include "../../common/src/pgr_types.h"
#include "../../common/src/postgres_connection.h"
Classes
struct edge_columns
Macros
#define TUPLIMIT 1000
Typedefs
typedef struct edge_columns edge_columns_t
Functions
PGDLLEXPORT Datum bidir_dijkstra_shortest_path (PG_FUNCTION_ARGS)
static int compute_bidirsp (char *sql, int64_t start_vertex, int64_t end_vertex, bool directed, bool has_reverse_cost, path_element_t **path, int *path_count)
static void fetch_edge (HeapTuple *tuple, TupleDesc *tupdesc, edge_columns_t *edge_columns, edge_t *target_edge)
static int fetch_edge_columns (SPITupleTable *tuptable, edge_columns_t *edge_columns, bool has_reverse_cost)
PG_FUNCTION_INFO_V1 (bidir_dijkstra_shortest_path)
Macro Definition Documentation
#define TUPLIMIT 1000
Definition at line 50 of file bdsp.c.
Referenced by compute_bidirsp().
Typedef Documentation
typedef struct edge_columns edge_columns_t
Function Documentation
PGDLLEXPORT Datum bidir_dijkstra_shortest_path (PG_FUNCTION_ARGS)
Definition at line 301 of file bdsp.c.
References compute_bidirsp(), path_element_t::cost, path, path_count, PGR_DBG, and pgr_text2char().
static int compute_bidirsp (char * sql, int64_t start_vertex, int64_t end_vertex, bool directed, bool has_reverse_cost, path_element_t ** path, int * path_count) static
Definition at line 153 of file bdsp.c.
References bidirsp_wrapper(), edges, err_msg, fetch_edge(), fetch_edge_columns(), edge_columns::id, path_count, PGR_DBG, pgr_SPI_connect(), pgr_SPI_cursor_open(), pgr_SPI_finish(), pgr_SPI_prepare(), pgr_edge_t::source, pgr_edge_t::target, and TUPLIMIT.
Referenced by bidir_dijkstra_shortest_path().
static void fetch_edge (HeapTuple * tuple, TupleDesc * tupdesc, edge_columns_t * edge_columns, edge_t * target_edge) static
Definition at line 124 of file bdsp.c.
References edge_columns::cost, pgr_edge_t::cost, edge_columns::id, pgr_edge_t::id, edge_columns::reverse_cost, pgr_edge_t::reverse_cost, edge_columns::source, pgr_edge_t::source, edge_columns::target, and pgr_edge_t::target.
Referenced by compute_bidirsp().
static int fetch_edge_columns (SPITupleTable * tuptable, edge_columns_t * edge_columns, bool has_reverse_cost) static
Definition at line 69 of file bdsp.c.
References edge_columns::cost, edge_columns::id, PGR_DBG, edge_columns::reverse_cost, edge_columns::source, and edge_columns::target.
Referenced by compute_bidirsp().
PG_FUNCTION_INFO_V1 (bidir_dijkstra_shortest_path)