pgRouting: boost_interface_drivedist.cpp File Reference
boost_interface_drivedist.cpp File Reference
#include "unistd.h"
#include <sstream>
#include <deque>
#include <vector>
#include "../../common/src/pgr_alloc.hpp"
#include "./../../dijkstra/src/pgr_dijkstra.hpp"
#include "./boost_interface_drivedist.h"
#include "./../../common/src/pgr_types.h"
Functions
void do_pgr_driving_distance (pgr_edge_t *data_edges, size_t total_edges, int64_t start_vertex, double distance, bool directedFlag, General_path_element_t **ret_path, size_t *path_count, char **err_msg)
void do_pgr_driving_many_to_dist (pgr_edge_t *data_edges, size_t total_tuples, int64_t *start_vertex, size_t s_len, double distance, bool directedFlag, bool equiCostFlag, General_path_element_t **ret_path, size_t *path_count, char **err_msg)
Function Documentation
void do_pgr_driving_distance (pgr_edge_t * data_edges, size_t total_edges, int64_t start_vertex, double distance, bool directedFlag, General_path_element_t ** ret_path, size_t * path_count, char ** err_msg)
Definition at line 108 of file boost_interface_drivedist.cpp.
References DIRECTED, Path::empty(), Path::get_pg_dd_path(), pgRouting::graph::Pgr_base_graph< G, Vertex, Edge >::graph_insert_data(), path, pgr_alloc(), pgr_drivingDistance(), Path::size(), and UNDIRECTED.
Referenced by compute_driving_distance().
void do_pgr_driving_many_to_dist (pgr_edge_t * data_edges, size_t total_tuples, int64_t * start_vertex, size_t s_len, double distance, bool directedFlag, bool equiCostFlag, General_path_element_t ** ret_path, size_t * path_count, char ** err_msg)
Definition at line 49 of file boost_interface_drivedist.cpp.
References DIRECTED, pgRouting::graph::Pgr_base_graph< G, Vertex, Edge >::graph_insert_data(), pgr_alloc(), pgr_drivingDistance(), and UNDIRECTED.
Referenced by driving_many_to_dist_driver().