pgRouting: CDepotInfo Class Reference
CDepotInfo Class Reference
#include "VRP_Solver.h"
Public Member Functions
CDepotInfo ()
~CDepotInfo ()
int getCloseTime ()
int getDepotId ()
Point getDepotLocation ()
int getOpenTime ()
void setCloseTime (int closeTime)
void setDepotId (int id)
void setDepotLocation (Point location)
void setOpenTime (int openTime)
Private Attributes
int m_iDepotCloseTime
int m_iDepotId
int m_iDepotOpenTime
Point m_ptDepotLocation
Detailed Description
Definition at line 145 of file VRP_Solver.h.
Constructor & Destructor Documentation
CDepotInfo::CDepotInfo ()
Definition at line 92 of file VRP_Solver.cpp.
CDepotInfo::~CDepotInfo ()
Definition at line 95 of file VRP_Solver.cpp.
Member Function Documentation
int CDepotInfo::getCloseTime () inline
Definition at line 154 of file VRP_Solver.h.
References m_iDepotCloseTime.
int CDepotInfo::getDepotId () inline
Definition at line 157 of file VRP_Solver.h.
References m_iDepotId.
Referenced by CVRPSolver::addDepot().
Point CDepotInfo::getDepotLocation () inline
Definition at line 160 of file VRP_Solver.h.
References m_ptDepotLocation.
int CDepotInfo::getOpenTime () inline
Definition at line 151 of file VRP_Solver.h.
References m_iDepotOpenTime.
void CDepotInfo::setCloseTime (int closeTime) inline
Definition at line 155 of file VRP_Solver.h.
References m_iDepotCloseTime.
Referenced by loadOrders().
void CDepotInfo::setDepotId (int id) inline
Definition at line 158 of file VRP_Solver.h.
References m_iDepotId.
Referenced by loadOrders().
void CDepotInfo::setDepotLocation (Point location) inline
Definition at line 161 of file VRP_Solver.h.
References m_ptDepotLocation.
Referenced by loadOrders().
void CDepotInfo::setOpenTime (int openTime) inline
Definition at line 152 of file VRP_Solver.h.
References m_iDepotOpenTime.
Referenced by loadOrders().
Member Data Documentation
int CDepotInfo::m_iDepotCloseTime private
Definition at line 168 of file VRP_Solver.h.
Referenced by getCloseTime(), and setCloseTime().
int CDepotInfo::m_iDepotId private
Definition at line 170 of file VRP_Solver.h.
Referenced by getDepotId(), and setDepotId().
int CDepotInfo::m_iDepotOpenTime private
Definition at line 167 of file VRP_Solver.h.
Referenced by getOpenTime(), and setOpenTime().
Point CDepotInfo::m_ptDepotLocation private
Definition at line 172 of file VRP_Solver.h.
Referenced by getDepotLocation(), and setDepotLocation().
The documentation for this class was generated from the following files:
VRP_Solver.h
VRP_Solver.cpp