pgRouting: PgrCardinalityGraph< G > Class Template Reference
PgrCardinalityGraph< G > Class Template Reference
#include "pgr_maximumcardinalitymatching.hpp"
Public Types
typedef boost::graph_traits< G >
::edge_descriptor E
typedef boost::graph_traits< G >
::edge_iterator E_it
typedef boost::graph_traits< G >
::vertex_descriptor V
typedef boost::graph_traits< G >
::vertex_iterator V_it
Public Member Functions
void create_max_cardinality_graph (pgr_basic_edge_t *data_edges, size_t total_tuples)
V get_boost_vertex (int64_t id)
int64_t get_edge_id (E e)
void get_matched_vertices (std::vector< pgr_basic_edge_t > &matched_vertices, const std::vector< int64_t > &mate_map)
int64_t get_vertex_id (V v)
void maximum_cardinality_matching (std::vector< int64_t > &mate_map)
Public Attributes
G boost_graph
std::map< E, int64_t > E_to_id
std::map< int64_t, V > id_to_V
std::map< V, int64_t > V_to_id
Detailed Description
template<class G>
class PgrCardinalityGraph< G >
Definition at line 61 of file pgr_maximumcardinalitymatching.hpp.
Member Typedef Documentation
template<class G> typedef boost::graph_traits<G>::edge_descriptor PgrCardinalityGraph< G >::E
Definition at line 66 of file pgr_maximumcardinalitymatching.hpp.
template<class G> typedef boost::graph_traits<G>::edge_iterator PgrCardinalityGraph< G >::E_it
Definition at line 68 of file pgr_maximumcardinalitymatching.hpp.
template<class G> typedef boost::graph_traits<G>::vertex_descriptor PgrCardinalityGraph< G >::V
Definition at line 65 of file pgr_maximumcardinalitymatching.hpp.
template<class G> typedef boost::graph_traits<G>::vertex_iterator PgrCardinalityGraph< G >::V_it
Definition at line 67 of file pgr_maximumcardinalitymatching.hpp.
Member Function Documentation
template<class G> void PgrCardinalityGraph< G >::create_max_cardinality_graph (pgr_basic_edge_t * data_edges, size_t total_tuples) inline
Definition at line 86 of file pgr_maximumcardinalitymatching.hpp.
References PgrCardinalityGraph< G >::boost_graph, PgrCardinalityGraph< G >::E_to_id, PgrCardinalityGraph< G >::get_boost_vertex(), PgrCardinalityGraph< G >::id_to_V, and PgrCardinalityGraph< G >::V_to_id.
Referenced by do_pgr_maximum_cardinality_matching().
template<class G> V PgrCardinalityGraph< G >::get_boost_vertex (int64_t id) inline
Definition at line 74 of file pgr_maximumcardinalitymatching.hpp.
References PgrCardinalityGraph< G >::id_to_V.
Referenced by PgrCardinalityGraph< G >::create_max_cardinality_graph().
template<class G> int64_t PgrCardinalityGraph< G >::get_edge_id (E e) inline
Definition at line 82 of file pgr_maximumcardinalitymatching.hpp.
References PgrCardinalityGraph< G >::E_to_id.
Referenced by PgrCardinalityGraph< G >::get_matched_vertices().
template<class G> void PgrCardinalityGraph< G >::get_matched_vertices (std::vector< pgr_basic_edge_t > & matched_vertices, const std::vector< int64_t > & mate_map) inline
Definition at line 116 of file pgr_maximumcardinalitymatching.hpp.
References PgrCardinalityGraph< G >::boost_graph, pgr_basic_edge_t::edge_id, PgrCardinalityGraph< G >::get_edge_id(), PgrCardinalityGraph< G >::get_vertex_id(), pgr_basic_edge_t::source, and pgr_basic_edge_t::target.
Referenced by do_pgr_maximum_cardinality_matching().
template<class G> int64_t PgrCardinalityGraph< G >::get_vertex_id (V v) inline
Definition at line 78 of file pgr_maximumcardinalitymatching.hpp.
References PgrCardinalityGraph< G >::V_to_id.
Referenced by PgrCardinalityGraph< G >::get_matched_vertices().
template<class G> void PgrCardinalityGraph< G >::maximum_cardinality_matching (std::vector< int64_t > & mate_map) inline
Definition at line 166 of file pgr_maximumcardinalitymatching.hpp.
References PgrCardinalityGraph< G >::boost_graph.
Referenced by do_pgr_maximum_cardinality_matching().
Member Data Documentation
template<class G> G PgrCardinalityGraph< G >::boost_graph
Definition at line 63 of file pgr_maximumcardinalitymatching.hpp.
Referenced by PgrCardinalityGraph< G >::create_max_cardinality_graph(), do_pgr_maximum_cardinality_matching(), PgrCardinalityGraph< G >::get_matched_vertices(), and PgrCardinalityGraph< G >::maximum_cardinality_matching().
template<class G> std::map<E, int64_t> PgrCardinalityGraph< G >::E_to_id
Definition at line 72 of file pgr_maximumcardinalitymatching.hpp.
Referenced by PgrCardinalityGraph< G >::create_max_cardinality_graph(), and PgrCardinalityGraph< G >::get_edge_id().
template<class G> std::map<int64_t, V> PgrCardinalityGraph< G >::id_to_V
Definition at line 70 of file pgr_maximumcardinalitymatching.hpp.
Referenced by PgrCardinalityGraph< G >::create_max_cardinality_graph(), and PgrCardinalityGraph< G >::get_boost_vertex().
template<class G> std::map<V, int64_t> PgrCardinalityGraph< G >::V_to_id
Definition at line 71 of file pgr_maximumcardinalitymatching.hpp.
Referenced by PgrCardinalityGraph< G >::create_max_cardinality_graph(), and PgrCardinalityGraph< G >::get_vertex_id().
The documentation for this class was generated from the following file:
pgr_maximumcardinalitymatching.hpp