pgRouting: pgrouting::contraction::Edge Class Reference
pgrouting::contraction::Edge Class Reference
#include "ch_edge.h"
Public Member Functions
Edge ()=default
Edge (int64_t eid, int64_t source, int64_t target, double cost)
Edge (int64_t eid, int64_t source, int64_t target, double cost, bool first)
void add_contracted_edge_vertices (Edge &e)
void add_contracted_vertex (Vertex &v, int64_t vid)
void clear_contracted_vertices ()
const Identifiers< int64_t > & contracted_vertices () const
void cp_members (const Edge &other, std::ostringstream &log)
void cp_members (const Edge &other)
void cp_members (const Basic_edge &other)
bool has_contracted_vertices () const
Public Attributes
double cost
bool first
int64_t id
int64_t source
int64_t target
Private Attributes
Identifiers< int64_t > m_contracted_vertices
Friends
std::ostream & operator<< (std::ostream &os, const Edge &e)
Detailed Description
Definition at line 41 of file ch_edge.h.
Constructor & Destructor Documentation
pgrouting::contraction::Edge::Edge () default
pgrouting::contraction::Edge::Edge (int64_t eid, int64_t source, int64_t target, double cost) inline
Definition at line 44 of file ch_edge.h.
pgrouting::contraction::Edge::Edge (int64_t eid, int64_t source, int64_t target, double cost, bool first) inline
Definition at line 47 of file ch_edge.h.
Member Function Documentation
void pgrouting::contraction::Edge::add_contracted_edge_vertices (Edge & e)
Definition at line 104 of file ch_edge.cpp.
References clear_contracted_vertices(), contracted_vertices(), and m_contracted_vertices.
Referenced by pgrouting::Pgr_linearContraction< G >::add_shortcut().
void pgrouting::contraction::Edge::add_contracted_vertex (Vertex & v, int64_t vid)
Definition at line 95 of file ch_edge.cpp.
References pgrouting::contraction::Vertex::clear_contracted_vertices(), pgrouting::contraction::Vertex::contracted_vertices(), and m_contracted_vertices.
Referenced by pgrouting::Pgr_linearContraction< G >::add_shortcut(), and do_pgr_test_c_edges().
void pgrouting::contraction::Edge::clear_contracted_vertices () inline
Definition at line 58 of file ch_edge.h.
References Identifiers< T >::clear(), and m_contracted_vertices.
Referenced by add_contracted_edge_vertices().
const Identifiers< int64_t > & pgrouting::contraction::Edge::contracted_vertices () const
Definition at line 90 of file ch_edge.cpp.
References m_contracted_vertices.
Referenced by add_contracted_edge_vertices(), cp_members(), and pgrouting::contraction::operator<<().
void pgrouting::contraction::Edge::cp_members (const Edge & other, std::ostringstream & log)
Definition at line 34 of file ch_edge.cpp.
References cost, first, m_contracted_vertices, source, and target.
void pgrouting::contraction::Edge::cp_members (const Edge & other)
Definition at line 69 of file ch_edge.cpp.
References contracted_vertices(), cost, first, id, m_contracted_vertices, source, and target.
void pgrouting::contraction::Edge::cp_members (const Basic_edge & other)
Definition at line 79 of file ch_edge.cpp.
References pgrouting::Basic_edge::cost, cost, pgrouting::Basic_edge::first, first, and pgrouting::Basic_edge::id.
bool pgrouting::contraction::Edge::has_contracted_vertices () const
Definition at line 84 of file ch_edge.cpp.
References m_contracted_vertices, and Identifiers< T >::size().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Edge & e) friend
Definition at line 111 of file ch_edge.cpp.
Member Data Documentation
double pgrouting::contraction::Edge::cost
Definition at line 66 of file ch_edge.h.
Referenced by cp_members(), and pgrouting::contraction::operator<<().
bool pgrouting::contraction::Edge::first
Definition at line 67 of file ch_edge.h.
Referenced by cp_members(), and pgrouting::contraction::operator<<().
int64_t pgrouting::contraction::Edge::id
Definition at line 63 of file ch_edge.h.
Referenced by cp_members(), do_pgr_test_c_edges(), and pgrouting::contraction::operator<<().
Identifiers<int64_t> pgrouting::contraction::Edge::m_contracted_vertices private
Definition at line 69 of file ch_edge.h.
Referenced by add_contracted_edge_vertices(), add_contracted_vertex(), clear_contracted_vertices(), contracted_vertices(), cp_members(), and has_contracted_vertices().
int64_t pgrouting::contraction::Edge::source
Definition at line 64 of file ch_edge.h.
Referenced by cp_members(), do_pgr_test_c_edges(), and pgrouting::contraction::operator<<().
int64_t pgrouting::contraction::Edge::target
Definition at line 65 of file ch_edge.h.
Referenced by cp_members(), do_pgr_test_c_edges(), and pgrouting::contraction::operator<<().
The documentation for this class was generated from the following files:
ch_edge.h
ch_edge.cpp