pgRouting: pgrouting::contraction::Vertex Class Reference
pgrouting::contraction::Vertex Class Reference
#include "ch_vertex.h"
Public Member Functions
Vertex ()=default
Vertex (const Vertex &)=default
Vertex (const pgr_edge_t &other, bool is_source)
void add_contracted_vertex (Vertex &v, int64_t vid)
void add_vertex_id (int64_t vid)
void clear_contracted_vertices ()
const Identifiers< int64_t > & contracted_vertices () const
void cp_members (const Vertex &other)
bool has_contracted_vertices () const
Public Attributes
int64_t id
Private Attributes
Identifiers< int64_t > m_contracted_vertices
Friends
std::ostream & operator<< (std::ostream &os, const Vertex &v)
Detailed Description
Definition at line 42 of file ch_vertex.h.
Constructor & Destructor Documentation
pgrouting::contraction::Vertex::Vertex () default
pgrouting::contraction::Vertex::Vertex (const Vertex &) default
pgrouting::contraction::Vertex::Vertex (const pgr_edge_t & other, bool is_source) inline
Definition at line 47 of file ch_vertex.h.
Member Function Documentation
void Vertex::add_contracted_vertex (Vertex & v, int64_t vid)
Definition at line 48 of file ch_vertex.cpp.
References clear_contracted_vertices(), contracted_vertices(), and m_contracted_vertices.
Referenced by do_pgr_test_c_edges().
void pgrouting::contraction::Vertex::add_vertex_id (int64_t vid) inline
Definition at line 54 of file ch_vertex.h.
References m_contracted_vertices.
void pgrouting::contraction::Vertex::clear_contracted_vertices () inline
Definition at line 57 of file ch_vertex.h.
References Identifiers< T >::clear(), and m_contracted_vertices.
Referenced by add_contracted_vertex(), and pgrouting::contraction::Edge::add_contracted_vertex().
const Identifiers< int64_t > & Vertex::contracted_vertices () const
Definition at line 37 of file ch_vertex.cpp.
References m_contracted_vertices.
Referenced by add_contracted_vertex(), pgrouting::contraction::Edge::add_contracted_vertex(), and pgrouting::contraction::operator<<().
void pgrouting::contraction::Vertex::cp_members (const Vertex & other) inline
Definition at line 50 of file ch_vertex.h.
References id.
bool Vertex::has_contracted_vertices () const
Definition at line 42 of file ch_vertex.cpp.
References m_contracted_vertices, and Identifiers< T >::size().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Vertex & v) friend
Definition at line 57 of file ch_vertex.cpp.
Member Data Documentation
int64_t pgrouting::contraction::Vertex::id
Definition at line 44 of file ch_vertex.h.
Referenced by pgrouting::contraction::check_vertices(), cp_members(), pgrouting::contraction::extract_vertices(), and pgrouting::contraction::operator<<().
Identifiers<int64_t> pgrouting::contraction::Vertex::m_contracted_vertices private
Definition at line 60 of file ch_vertex.h.
Referenced by add_contracted_vertex(), add_vertex_id(), clear_contracted_vertices(), contracted_vertices(), and has_contracted_vertices().
The documentation for this class was generated from the following files:
ch_vertex.h
ch_vertex.cpp