pgRouting: CVehicleInfo Class Reference
CVehicleInfo Class Reference
#include "VRP_Solver.h"
Public Member Functions
CVehicleInfo ()
~CVehicleInfo ()
int getCapacity ()
double getCostPerKM ()
int getCurrentLoad ()
int getId ()
int getRemainingCapacity ()
bool init ()
bool loadUnit (int lUnit)
void setCapacity (int capacity)
void setCostPerKM (double cost)
void setId (int id)
bool unloadUnit (int lUnit)
Private Attributes
double m_dCostPerKM
int m_iCapacity
int m_iCurrentLoad
int m_iVehicleId
Friends
bool operator!= (const CVehicleInfo &cur, const CVehicleInfo &that)
Detailed Description
Definition at line 58 of file VRP_Solver.h.
Constructor & Destructor Documentation
CVehicleInfo::CVehicleInfo ()
Definition at line 70 of file VRP_Solver.cpp.
References m_iCurrentLoad.
CVehicleInfo::~CVehicleInfo ()
Definition at line 74 of file VRP_Solver.cpp.
Member Function Documentation
int CVehicleInfo::getCapacity () inline
Definition at line 72 of file VRP_Solver.h.
References m_iCapacity.
Referenced by CVRPSolver::attempVehicleExchange().
double CVehicleInfo::getCostPerKM () inline
Definition at line 78 of file VRP_Solver.h.
References m_dCostPerKM.
int CVehicleInfo::getCurrentLoad () inline
Definition at line 70 of file VRP_Solver.h.
References m_iCurrentLoad.
Referenced by CVRPSolver::attempVehicleExchange().
int CVehicleInfo::getId () inline
Definition at line 75 of file VRP_Solver.h.
References m_iVehicleId.
Referenced by CVRPSolver::addVehicle(), and CTourInfo::getVehicleId().
int CVehicleInfo::getRemainingCapacity () inline
Definition at line 68 of file VRP_Solver.h.
References m_iCapacity, and m_iCurrentLoad.
Referenced by CTourInfo::getRemainingCapacity().
bool CVehicleInfo::init ()
bool CVehicleInfo::loadUnit (int lUnit)
Definition at line 78 of file VRP_Solver.cpp.
References m_iCapacity, and m_iCurrentLoad.
Referenced by CVRPSolver::insertOrder().
void CVehicleInfo::setCapacity (int capacity) inline
Definition at line 73 of file VRP_Solver.h.
References m_iCapacity.
Referenced by loadVehicles().
void CVehicleInfo::setCostPerKM (double cost) inline
Definition at line 79 of file VRP_Solver.h.
References m_dCostPerKM.
Referenced by loadVehicles().
void CVehicleInfo::setId (int id) inline
Definition at line 76 of file VRP_Solver.h.
References m_iVehicleId.
Referenced by loadVehicles().
bool CVehicleInfo::unloadUnit (int lUnit)
Friends And Related Function Documentation
bool operator!= (const CVehicleInfo & cur, const CVehicleInfo & that) friend
Definition at line 39 of file VRP_Solver.cpp.
Member Data Documentation
double CVehicleInfo::m_dCostPerKM private
Definition at line 91 of file VRP_Solver.h.
Referenced by getCostPerKM(), and setCostPerKM().
int CVehicleInfo::m_iCapacity private
Definition at line 88 of file VRP_Solver.h.
Referenced by getCapacity(), getRemainingCapacity(), loadUnit(), and setCapacity().
int CVehicleInfo::m_iCurrentLoad private
Definition at line 89 of file VRP_Solver.h.
Referenced by CVehicleInfo(), getCurrentLoad(), getRemainingCapacity(), and loadUnit().
int CVehicleInfo::m_iVehicleId private
Definition at line 90 of file VRP_Solver.h.
Referenced by getId(), operator!=(), and setId().
The documentation for this class was generated from the following files:
VRP_Solver.h
VRP_Solver.cpp