pgRouting: Route Class Reference
Route Class Reference
#include "Route.h"
Public Member Functions
Route (int _capacity, const Depot &_depot)
Route ()
void append (const Customers &c, const Pickup &order)
State append (customer *c, Pickup p, depot d, int CustomerLength, int PickupLength, State S)
double cost () const
double cost ()
bool has_twv (const Customers &customers)
bool has_violation (const Customers &customers)
int HillClimbing (customer *c, depot d, Pickup p)
bool insertOrder (const Customers &c, const Pickup &order)
int insertOrder (customer *c, depot d, Pickup p)
void remove (const State &S)
void remove (State S)
int RemoveOrder (const Customers &customers, const Pickup &p)
int RemoveOrder (Pickup p)
void update (const Customers &c)
void update (customer *c, depot d)
Public Attributes
double capacity
int cv
Depot depot
double dis
int dis
int order [1200]
std::vector< int64_t > path
int path [1200]
int path_length
int twv
Detailed Description
Definition at line 31 of file pickDeliver/src/Route.h.
Constructor & Destructor Documentation
Route::Route (int _capacity, const Depot & _depot) inline
Definition at line 40 of file pickDeliver/src/Route.h.
References path.
Route::Route () inline
Definition at line 47 of file vrppdtw/src/Route.h.
References cv, dis, order, path, path_length, and twv.
Member Function Documentation
void Route::append (const Customers & c, const Pickup & order)
Definition at line 90 of file pickDeliver/src/Route.h.
References Pickup::Did, path, Pickup::Pid, and update().
Referenced by Solver().
State Route::append (customer * c, Pickup p, depot d, int CustomerLength, int PickupLength, State S)
Definition at line 117 of file vrppdtw/src/Route.h.
References cv, State::cv, Pickup::Did, dis, State::dis, Pickup::id, order, path, State::path, path_length, Pickup::Pid, twv, and State::twv.
double Route::cost () const
Definition at line 148 of file pickDeliver/src/Route.h.
References cv, dis, and twv.
Referenced by HillClimbing(), and Solver().
double Route::cost ()
Definition at line 192 of file vrppdtw/src/Route.h.
References cv, dis, and twv.
bool Route::has_twv (const Customers & customers)
Definition at line 159 of file pickDeliver/src/Route.h.
References twv, and update().
Referenced by insertOrder().
bool Route::has_violation (const Customers & customers)
Definition at line 153 of file pickDeliver/src/Route.h.
References cv, twv, and update().
Referenced by insertOrder().
int Route::HillClimbing (customer * c, depot d, Pickup p)
Definition at line 248 of file vrppdtw/src/Route.h.
References cost(), cv, dis, Depot::Ltime, order, path, path_length, twv, and update().
Referenced by Solver().
bool Route::insertOrder (const Customers & c, const Pickup & order)
Definition at line 166 of file pickDeliver/src/Route.h.
References Pickup::Did, dis, has_twv(), has_violation(), path, Pickup::Pid, RemoveOrder(), and update().
int Route::insertOrder (customer * c, depot d, Pickup p)
Definition at line 196 of file vrppdtw/src/Route.h.
References cv, dis, Depot::Ltime, order, path, path_length, twv, and update().
void Route::remove (const State & S)
Definition at line 252 of file pickDeliver/src/Route.h.
References cv, State::cv, dis, State::dis, path, State::path, twv, and State::twv.
Referenced by Solver().
void Route::remove (State S)
Definition at line 340 of file vrppdtw/src/Route.h.
References cv, State::cv, dis, State::dis, order, path, State::path, path_length, twv, and State::twv.
int Route::RemoveOrder (const Customers & customers, const Pickup & p)
Definition at line 67 of file pickDeliver/src/Route.h.
References cv, Pickup::Did, dis, Depot::Ltime, path, Pickup::Pid, twv, and update().
Referenced by insertOrder().
int Route::RemoveOrder (Pickup p)
Definition at line 71 of file vrppdtw/src/Route.h.
References Pickup::Did, order, path, path_length, and Pickup::Pid.
void Route::update (const Customers & c)
Definition at line 99 of file pickDeliver/src/Route.h.
References CalculateDistance(), capacity, cv, dis, Depot::Ltime, path, and twv.
Referenced by append(), has_twv(), has_violation(), HillClimbing(), insertOrder(), and RemoveOrder().
void Route::update (customer * c, depot d)
Definition at line 139 of file vrppdtw/src/Route.h.
References cv, Customer::demand, dis, Customer::Etime, Depot::Ltime, path, path_length, Customer::Stime, twv, Depot::x, Customer::x, Depot::y, and Customer::y.
Member Data Documentation
double Route::capacity
Definition at line 37 of file pickDeliver/src/Route.h.
Referenced by update().
int Route::cv
Definition at line 34 of file pickDeliver/src/Route.h.
Referenced by append(), cost(), has_violation(), HillClimbing(), insertOrder(), remove(), RemoveOrder(), Route(), Solver(), and update().
Depot Route::depot
Definition at line 38 of file pickDeliver/src/Route.h.
double Route::dis
Definition at line 35 of file pickDeliver/src/Route.h.
Referenced by append(), cost(), HillClimbing(), insertOrder(), remove(), RemoveOrder(), Route(), Solver(), and update().
int Route::dis
Definition at line 43 of file vrppdtw/src/Route.h.
int Route::order[1200]
Definition at line 45 of file vrppdtw/src/Route.h.
Referenced by append(), HillClimbing(), insertOrder(), remove(), RemoveOrder(), and Route().
std::vector< int64_t > Route::path
Definition at line 36 of file pickDeliver/src/Route.h.
Referenced by append(), HillClimbing(), insertOrder(), remove(), RemoveOrder(), Route(), and update().
int Route::path[1200]
Definition at line 44 of file vrppdtw/src/Route.h.
int Route::path_length
Definition at line 46 of file vrppdtw/src/Route.h.
Referenced by append(), HillClimbing(), insertOrder(), remove(), RemoveOrder(), Route(), and update().
int Route::twv
Definition at line 33 of file pickDeliver/src/Route.h.
Referenced by append(), cost(), has_twv(), has_violation(), HillClimbing(), insertOrder(), remove(), RemoveOrder(), Route(), Solver(), and update().
The documentation for this class was generated from the following file:
pickDeliver/src/Route.h