pgRouting: Dmatrix Class Reference
Dmatrix Class Reference
#include "Dmatrix.hpp"
Public Types
typedef std::vector
< std::vector< double > > Costs
typedef std::vector< int64_t > Ids
Public Member Functions
Dmatrix ()=default
Dmatrix (const std::vector< Matrix_cell_t > &data_costs)
int64_t get_id (size_t id) const
size_t get_index (int64_t id) const
Dmatrix get_symetric () const
bool has_no_infinity () const
bool is_symetric () const
double max () const
bool obeys_triangle_inequality () const
std::vector< double > & operator[] (size_t i)
double pathCost (const Ids &path) const
void set_ids (const std::vector< matrix_cell > &data_costs)
size_t size () const
Public Attributes
Costs costs
Ids ids
Detailed Description
Definition at line 12 of file Dmatrix.hpp.
Member Typedef Documentation
typedef std::vector< std::vector < double > > Dmatrix::Costs
Definition at line 14 of file Dmatrix.hpp.
typedef std::vector< int64_t > Dmatrix::Ids
Definition at line 15 of file Dmatrix.hpp.
Constructor & Destructor Documentation
Dmatrix::Dmatrix () default
Dmatrix::Dmatrix (const std::vector< Matrix_cell_t > & data_costs)
Definition at line 71 of file Dmatrix.cpp.
References costs, get_index(), ids, max, and set_ids().
Member Function Documentation
int64_t Dmatrix::get_id (size_t id) const
Definition at line 64 of file Dmatrix.cpp.
References ids.
Referenced by do_pgr_tsp().
size_t Dmatrix::get_index (int64_t id) const
Definition at line 58 of file Dmatrix.cpp.
References ids.
Referenced by Dmatrix(), and do_pgr_tsp().
Dmatrix Dmatrix::get_symetric () const
Definition at line 131 of file Dmatrix.cpp.
References costs, ids, is_symetric(), and max.
Referenced by do_pgr_tsp().
bool Dmatrix::has_no_infinity () const
Definition at line 90 of file Dmatrix.cpp.
References costs, and max.
Referenced by do_pgr_tsp().
bool Dmatrix::is_symetric () const
Definition at line 120 of file Dmatrix.cpp.
References costs.
Referenced by get_symetric().
double Dmatrix::max () const
Definition at line 32 of file Dmatrix.cpp.
References costs.
Referenced by TSP::TSP().
bool Dmatrix::obeys_triangle_inequality () const
Definition at line 101 of file Dmatrix.cpp.
References costs.
Referenced by do_pgr_tsp().
std::vector< double >& Dmatrix::operator[] (size_t i) inline
Definition at line 34 of file Dmatrix.hpp.
References costs.
double Dmatrix::pathCost (const Ids & path) const
Definition at line 14 of file Dmatrix.cpp.
References costs, ids, len, and max.
Referenced by TSP::annealing(), TSP::TSP(), and TSP::update().
void Dmatrix::set_ids (const std::vector< matrix_cell > & data_costs)
Definition at line 42 of file Dmatrix.cpp.
References ids.
Referenced by Dmatrix().
size_t Dmatrix::size () const inline
Definition at line 31 of file Dmatrix.hpp.
References ids.
Member Data Documentation
Costs Dmatrix::costs
Definition at line 36 of file Dmatrix.hpp.
Referenced by Dmatrix(), get_symetric(), has_no_infinity(), is_symetric(), max(), obeys_triangle_inequality(), operator[](), and pathCost().
Ids Dmatrix::ids
Definition at line 37 of file Dmatrix.hpp.
Referenced by Dmatrix(), get_id(), get_index(), get_symetric(), pathCost(), set_ids(), and size().
The documentation for this class was generated from the following files:
Dmatrix.hpp
Dmatrix.cpp