pgRouting: customers_input.h File Reference
customers_input.h File Reference
#include "./pgr_types.h"
#include "./pdp.h"
Functions
void pgr_get_customers (char *sql, Customer **customers, size_t *total_customers)
int64_t id; double x; double y; double demand; double Etime; double Ltime; double Stime; int64_t Pindex; int64_t Dindex; double Ddist;
Function Documentation
void pgr_get_customers (char * sql, Customer ** customers, size_t * total_customers)
int64_t id; double x; double y; double demand; double Etime; double Ltime; double Stime; int64_t Pindex; int64_t Dindex; double Ddist;
int64_t id; double x; double y; double demand; double Etime; double Ltime; double Stime; int64_t Pindex; int64_t Dindex; double Ddist;
Definition at line 55 of file customers_input.c.
References ANY_INTEGER, ANY_NUMERICAL, Column_info_t::colNumber, Column_info_t::eType, Column_info_t::name, PGR_DBG, pgr_fetch_column_info(), pgr_fetch_customer(), pgr_SPI_cursor_open(), pgr_SPI_prepare(), Column_info_t::strict, total_tuples, and Column_info_t::type.
Referenced by compute_shortest_path().