pgRouting: dijkstraVia.c File Reference
dijkstraVia.c File Reference
#include "postgres.h"
#include "executor/spi.h"
#include "funcapi.h"
#include "utils/array.h"
#include "catalog/pg_type.h"
#include "fmgr.h"
#include "./../../common/src/debug_macro.h"
#include "./../../common/src/time_msg.h"
#include "./../../common/src/pgr_types.h"
#include "./../../common/src/postgres_connection.h"
#include "./../../common/src/edges_input.h"
#include "./../../common/src/arrays_input.h"
#include "./dijkstraVia_driver.h"
Functions
PGDLLEXPORT Datum dijkstraVia (PG_FUNCTION_ARGS)
PG_FUNCTION_INFO_V1 (dijkstraVia)
static void process (char *edges_sql, int64_t *via_vidsArr, size_t size_via_vidsArr, bool directed, bool strict, bool U_turn_on_edge, Routes_t **result_tuples, size_t *result_count)
Function Documentation
PGDLLEXPORT Datum dijkstraVia (PG_FUNCTION_ARGS)
Definition at line 115 of file dijkstraVia.c.
References PGR_DBG, pgr_get_bigIntArray(), pgr_text2char(), and process().
PG_FUNCTION_INFO_V1 (dijkstraVia)
static void process (char * edges_sql, int64_t * via_vidsArr, size_t size_via_vidsArr, bool directed, bool strict, bool U_turn_on_edge, Routes_t ** result_tuples, size_t * result_count) static
Definition at line 57 of file dijkstraVia.c.
References do_pgr_dijkstraViaVertex(), edges, err_msg, PGR_DBG, pgr_get_edges(), pgr_SPI_connect(), pgr_SPI_finish(), and time_msg().
Referenced by dijkstraVia().