pgRouting: distances_input.c File Reference
distances_input.c File Reference
#include "./debug_macro.h"
#include "./../../common/src/pgr_types.h"
#include "./../../common/src/postgres_connection.h"
#include "./../../common/src/get_check_data.h"
#include "./distances_input.h"
Functions
static void pgr_fetch_distance (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info[3], Matrix_cell_t *distance)
void pgr_get_distances (char *sql, Matrix_cell_t **distances, size_t *total_distances)
bigint start_vid, bigint end_vid, float agg_cost,
Function Documentation
static void pgr_fetch_distance (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info[3], Matrix_cell_t * distance) static
Definition at line 35 of file distances_input.c.
References matrix_cell::cost, matrix_cell::from_vid, pgr_SPI_getBigInt(), pgr_SPI_getFloat8(), and matrix_cell::to_vid.
Referenced by pgr_get_distances().
void pgr_get_distances (char * sql, Matrix_cell_t ** distances, size_t * total_distances)
bigint start_vid, bigint end_vid, float agg_cost,
Definition at line 51 of file distances_input.c.
References ANY_INTEGER, ANY_NUMERICAL, Column_info_t::colNumber, Column_info_t::eType, Column_info_t::name, PGR_DBG, pgr_fetch_column_info(), pgr_fetch_distance(), pgr_SPI_cursor_open(), pgr_SPI_prepare(), Column_info_t::strict, total_tuples, and Column_info_t::type.
Referenced by process().