pgRouting: drivedist.c File Reference
drivedist.c File Reference
#include "postgres.h"
#include "executor/spi.h"
#include "funcapi.h"
#include "catalog/pg_type.h"
#include "fmgr.h"
#include "./../../common/src/debug_macro.h"
#include "./../../common/src/time_msg.h"
#include "./../../common/src/pgr_types.h"
#include "./../../common/src/postgres_connection.h"
#include "./../../common/src/edges_input.h"
#include "./boost_interface_drivedist.h"
Functions
static void compute_driving_distance (char *sql, int64_t start_vertex, float8 distance, bool directed, General_path_element_t **path, size_t *path_count)
Datum driving_distance (PG_FUNCTION_ARGS)
PG_FUNCTION_INFO_V1 (driving_distance)
Function Documentation
static void compute_driving_distance (char * sql, int64_t start_vertex, float8 distance, bool directed, General_path_element_t ** path, size_t * path_count) static
Definition at line 52 of file drivedist.c.
References do_pgr_driving_distance(), edges, err_msg, PGR_DBG, pgr_get_edges(), pgr_SPI_connect(), pgr_SPI_finish(), and time_msg().
Referenced by driving_distance().
Datum driving_distance (PG_FUNCTION_ARGS)
Definition at line 100 of file drivedist.c.
References compute_driving_distance(), path_count, PGR_DBG, and pgr_text2char().
PG_FUNCTION_INFO_V1 (driving_distance)