pgRouting: edge_disjoint_paths_one_to_many.c File Reference
edge_disjoint_paths_one_to_many.c File Reference
#include "postgres.h"
#include "executor/spi.h"
#include "funcapi.h"
#include "utils/array.h"
#include "catalog/pg_type.h"
#include "fmgr.h"
#include "./../../common/src/debug_macro.h"
#include "./../../common/src/time_msg.h"
#include "./../../common/src/pgr_types.h"
#include "./../../common/src/postgres_connection.h"
#include "./../../common/src/edges_input.h"
#include "./../../common/src/arrays_input.h"
#include "./edge_disjoint_paths_one_to_many_driver.h"
Functions
PGDLLEXPORT Datum edge_disjoint_paths_one_to_many (PG_FUNCTION_ARGS)
PG_FUNCTION_INFO_V1 (edge_disjoint_paths_one_to_many)
static void process (char *edges_sql, int64_t source_vertex, int64_t *sink_vertices, size_t size_sink_verticesArr, bool directed, General_path_element_t **result_tuples, size_t *result_count)
Function Documentation
PGDLLEXPORT Datum edge_disjoint_paths_one_to_many (PG_FUNCTION_ARGS)
Definition at line 113 of file edge_disjoint_paths_one_to_many.c.
References PGR_DBG, pgr_get_bigIntArray(), pgr_text2char(), and process().
PG_FUNCTION_INFO_V1 (edge_disjoint_paths_one_to_many)
static void process (char * edges_sql, int64_t source_vertex, int64_t * sink_vertices, size_t size_sink_verticesArr, bool directed, General_path_element_t ** result_tuples, size_t * result_count) static
Definition at line 61 of file edge_disjoint_paths_one_to_many.c.
References do_pgr_edge_disjoint_paths_one_to_many(), edges, err_msg, PGR_DBG, pgr_get_basic_edges(), pgr_SPI_connect(), pgr_SPI_finish(), and time_msg().
Referenced by edge_disjoint_paths_one_to_many().