pgRouting: eucledianTSP_driver.h File Reference
eucledianTSP_driver.h File Reference
#include "../../common/src/pgr_types.h"
Functions
void do_pgr_eucledianTSP (Coordinate_t *coordinates, size_t total_coordinates, int64_t start_vid, int64_t end_vid, double initial_temperature, double final_temperature, double cooling_factor, int64_t tries_per_temperature, int64_t max_changes_per_temperature, int64_t max_consecutive_non_changes, bool randomize, double time_limit, General_path_element_t **results, size_t *total_results, char **log_msg, char **err_msg)
Function Documentation
void do_pgr_eucledianTSP (Coordinate_t * coordinates, size_t total_coordinates, int64_t start_vid, int64_t end_vid, double initial_temperature, double final_temperature, double cooling_factor, int64_t tries_per_temperature, int64_t max_changes_per_temperature, int64_t max_consecutive_non_changes, bool randomize, double time_limit, General_path_element_t ** results, size_t * total_results, char ** log_msg, char ** err_msg)
Definition at line 49 of file eucledianTSP_driver.cpp.
References General_path_element_t::agg_cost, pgrouting::tsp::TSP< MATRIX >::annealing(), General_path_element_t::cost, pgrouting::tsp::eucledianDmatrix::distance(), General_path_element_t::edge, pgrouting::tsp::eucledianDmatrix::get_id(), pgrouting::tsp::eucledianDmatrix::get_index(), pgrouting::tsp::TSP< MATRIX >::get_log(), pgrouting::tsp::TSP< MATRIX >::get_stats(), pgrouting::tsp::TSP< MATRIX >::get_tour(), pgrouting::tsp::TSP< MATRIX >::greedyInitial(), pgrouting::tsp::eucledianDmatrix::has_id(), General_path_element_t::node, pgassert, pgr_alloc(), reverse(), pgrouting::tsp::eucledianDmatrix::set(), pgrouting::tsp::eucledianDmatrix::size(), pgrouting::tsp::eucledianDmatrix::tourCost(), and AssertFailedException::what().
Referenced by process().