pgRouting: many_to_many_withPoints_driver.cpp File Reference
many_to_many_withPoints_driver.cpp File Reference
#include <sstream>
#include <deque>
#include <algorithm>
#include <set>
#include <vector>
#include <cassert>
#include "./pgr_dijkstra.hpp"
#include "./pgr_withPoints.hpp"
#include "./many_to_many_withPoints_driver.h"
#include "./../../common/src/pgr_types.h"
#include "./../../common/src/pgr_assert.h"
#include "./../../common/src/pgr_alloc.hpp"
Functions
int do_pgr_many_to_many_withPoints (pgr_edge_t *edges, size_t total_edges, Point_on_edge_t *points_p, size_t total_points, pgr_edge_t *edges_of_points, size_t total_edges_of_points, int64_t *start_pidsArr, size_t size_start_pidsArr, int64_t *end_pidsArr, size_t size_end_pidsArr, char driving_side, bool details, bool directed, bool only_cost, General_path_element_t **return_tuples, size_t *return_count, char **err_msg)
Function Documentation
int do_pgr_many_to_many_withPoints (pgr_edge_t * edges, size_t total_edges, Point_on_edge_t * points_p, size_t total_points, pgr_edge_t * edges_of_points, size_t total_edges_of_points, int64_t * start_pidsArr, size_t size_start_pidsArr, int64_t * end_pidsArr, size_t size_end_pidsArr, char driving_side, bool details, bool directed, bool only_cost, General_path_element_t ** return_tuples, size_t * return_count, char ** err_msg)
Definition at line 61 of file many_to_many_withPoints_driver.cpp.
References a, adjust_pids(), b, check_points(), create_new_edges(), DIRECTED, eliminate_details(), Path::end_id(), pgrouting::graph::Pgr_base_graph< G, Vertex, Edge >::graph_insert_data(), path, pgr_alloc(), pgr_dijkstra(), Path::start_id(), UNDIRECTED, and AssertFailedException::what().
Referenced by process().