pgRouting: many_to_many_dijkstra.c File Reference
many_to_many_dijkstra.c File Reference
#include "postgres.h"
#include "executor/spi.h"
#include "funcapi.h"
#include "utils/array.h"
#include "catalog/pg_type.h"
#include "fmgr.h"
#include "./../../common/src/debug_macro.h"
#include "./../../common/src/time_msg.h"
#include "./../../common/src/pgr_types.h"
#include "./../../common/src/postgres_connection.h"
#include "./../../common/src/edges_input.h"
#include "./../../common/src/arrays_input.h"
#include "./many_to_many_dijkstra_driver.h"
Functions
PGDLLEXPORT Datum many_to_many_dijkstra (PG_FUNCTION_ARGS)
PG_FUNCTION_INFO_V1 (many_to_many_dijkstra)
static void process (char *edges_sql, int64_t *start_vidsArr, size_t size_start_vidsArr, int64_t *end_vidsArr, size_t size_end_vidsArr, bool directed, bool only_cost, General_path_element_t **result_tuples, size_t *result_count)
Function Documentation
PGDLLEXPORT Datum many_to_many_dijkstra (PG_FUNCTION_ARGS)
Definition at line 115 of file many_to_many_dijkstra.c.
References PGR_DBG, pgr_get_bigIntArray(), pgr_text2char(), and process().
PG_FUNCTION_INFO_V1 (many_to_many_dijkstra)
static void process (char * edges_sql, int64_t * start_vidsArr, size_t size_start_vidsArr, int64_t * end_vidsArr, size_t size_end_vidsArr, bool directed, bool only_cost, General_path_element_t ** result_tuples, size_t * result_count) static
Definition at line 62 of file many_to_many_dijkstra.c.
References do_pgr_many_to_many_dijkstra(), edges, err_msg, PGR_DBG, pgr_get_edges(), pgr_SPI_connect(), pgr_SPI_finish(), and time_msg().
Referenced by many_to_many_dijkstra().