pgRouting: many_to_one_dijkstra_driver.h File Reference
many_to_one_dijkstra_driver.h File Reference
#include "./../../common/src/pgr_types.h"
Functions
void do_pgr_many_to_one_dijkstra (pgr_edge_t *data_edges, size_t total_tuples, int64_t *start_vidsArr, size_t size_start_vidsArr, int64_t end_vid, bool directed, bool only_cost, General_path_element_t **return_tuples, size_t *return_count, char **err_msg)
Function Documentation
void do_pgr_many_to_one_dijkstra (pgr_edge_t * data_edges, size_t total_tuples, int64_t * start_vidsArr, size_t size_start_vidsArr, int64_t end_vid, bool directed, bool only_cost, General_path_element_t ** return_tuples, size_t * return_count, char ** err_msg)
Definition at line 53 of file many_to_one_dijkstra_driver.cpp.
References DIRECTED, pgrouting::graph::Pgr_base_graph< G, Vertex, Edge >::graph_insert_data(), pgr_alloc(), pgr_dijkstra(), and UNDIRECTED.
Referenced by process().