pgRouting: matrixRows_input.c File Reference
matrixRows_input.c File Reference
#include "./debug_macro.h"
#include "./../../common/src/pgr_types.h"
#include "./../../common/src/postgres_connection.h"
#include "./../../common/src/get_check_data.h"
#include "./time_msg.h"
#include "./matrixRows_input.h"
Functions
static void pgr_fetch_row (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info[3], Matrix_cell_t *distance)
void pgr_get_matrixRows (char *sql, Matrix_cell_t **rows, size_t *total_rows)
bigint start_vid, bigint end_vid, float agg_cost,
Function Documentation
static void pgr_fetch_row (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info[3], Matrix_cell_t * distance) static
Definition at line 36 of file matrixRows_input.c.
References matrix_cell::cost, matrix_cell::from_vid, pgr_SPI_getBigInt(), pgr_SPI_getFloat8(), and matrix_cell::to_vid.
Referenced by pgr_get_matrixRows().
void pgr_get_matrixRows (char * sql, Matrix_cell_t ** rows, size_t * total_rows)
bigint start_vid, bigint end_vid, float agg_cost,
Definition at line 52 of file matrixRows_input.c.
References ANY_INTEGER, ANY_NUMERICAL, Column_info_t::colNumber, Column_info_t::eType, Column_info_t::name, PGR_DBG, pgr_fetch_column_info(), pgr_fetch_row(), pgr_SPI_cursor_open(), pgr_SPI_prepare(), Column_info_t::strict, time_msg(), and Column_info_t::type.
Referenced by process().