pgRouting: matrixRows_input.h File Reference
matrixRows_input.h File Reference
#include "./../../common/src/pgr_types.h"
Functions
void pgr_get_matrixRows (char *sql, Matrix_cell_t **distaces, size_t *total_distances)
bigint start_vid, bigint end_vid, float agg_cost,
Function Documentation
void pgr_get_matrixRows (char * sql, Matrix_cell_t ** distaces, size_t * total_distances)
bigint start_vid, bigint end_vid, float agg_cost,
Definition at line 52 of file matrixRows_input.c.
References ANY_INTEGER, ANY_NUMERICAL, Column_info_t::colNumber, Column_info_t::eType, Column_info_t::name, PGR_DBG, pgr_fetch_column_info(), pgr_fetch_row(), pgr_SPI_cursor_open(), pgr_SPI_prepare(), Column_info_t::strict, time_msg(), and Column_info_t::type.
Referenced by process().