pgRouting: boost Namespace Reference
boost Namespace Reference
Namespaces
detail
Classes
class astar_heuristic
struct AStarHeuristicConcept
struct closed_plus
struct on_discover_edge
struct on_finish_edge
struct on_initialize_edge
struct on_start_edge
class shooting_star_visitor
struct ShootingStarVisitorConcept
Typedefs
typedef shooting_star_visitor default_shooting_star_visitor
Functions
template<class Visitors >
shooting_star_visitor< Visitors > make_shooting_star_visitor (Visitors vis)
template<class Edge , class Graph , class WeightMap , class EdgeMap , class PredecessorMap , class DistanceMap , class CostMap , class BinaryFunction , class BinaryPredicate >
bool relax (Edge e, Edge pe, Edge s, const Graph &g, const WeightMap &w, const EdgeMap &em, PredecessorMap &p, DistanceMap &d, CostMap &c, const BinaryFunction &combine, const BinaryPredicate &compare, int e_max_id)
template<class Graph , class WeightMap , class EdgeMap , class PredecessorMap , class DistanceMap >
bool relax (typename graph_traits< Graph >::edge_descriptor e, const Graph &g, WeightMap w, EdgeMap em, PredecessorMap p, DistanceMap d)
template<class IncidenceGraph , class Buffer , class BFSVisitor , class ColorMap , class EdgeColorMap >
void shooting_star_edges_visit (const IncidenceGraph &g, typename graph_traits< IncidenceGraph >::edge_descriptor s, Buffer &Q, BFSVisitor vis, ColorMap color, EdgeColorMap edge_color, int e_max_id)
template<typename VertexAndEdgeListGraph , typename AStarHeuristic , typename ShootingStarVisitor , typename PredecessorMap , typename CostMap , typename DistanceMap , typename WeightMap , typename EdgeMap , typename IndexMap , typename ColorMap , typename EdgeColorMap , typename CompareFunction , typename CombineFunction , typename CostInf , typename CostZero >
void shooting_star_search (VertexAndEdgeListGraph &g, typename graph_traits< VertexAndEdgeListGraph >::edge_descriptor s, AStarHeuristic h, ShootingStarVisitor vis, PredecessorMap &predecessor, CostMap cost, DistanceMap distance, WeightMap weight, EdgeMap edge_map, IndexMap index_map, ColorMap color, EdgeColorMap edge_color, CompareFunction compare, CombineFunction combine, CostInf inf, CostZero zero, int e_max_id)
template<typename VertexAndEdgeListGraph , typename AStarHeuristic , typename P , typename T , typename R , typename IndexMap , typename DistanceMap , typename CostMap , typename PredecessorMap >
void shooting_star_search (VertexAndEdgeListGraph &g, typename graph_traits< VertexAndEdgeListGraph >::edge_descriptor s, AStarHeuristic h, const bgl_named_params< P, T, R > &params, IndexMap edge_index, DistanceMap distance, CostMap cost, PredecessorMap &pre_map, int e_max_id)
template<typename VertexAndEdgeListGraph , typename AStarHeuristic , typename ShootingStarVisitor , typename PredecessorMap , typename CostMap , typename DistanceMap , typename WeightMap , typename EdgeMap , typename ColorMap , typename EdgeColorMap , typename IndexMap , typename CompareFunction , typename CombineFunction , typename CostInf , typename CostZero >
void shooting_star_search_no_init (VertexAndEdgeListGraph &g, typename graph_traits< VertexAndEdgeListGraph >::edge_descriptor s, AStarHeuristic h, ShootingStarVisitor vis, PredecessorMap &predecessor, CostMap cost, DistanceMap distance, WeightMap weight, EdgeMap edge_map, ColorMap color, EdgeColorMap edge_color, IndexMap index_map, CompareFunction compare, CombineFunction combine, CostInf inf, CostZero zero, int e_max_id)
Typedef Documentation
typedef shooting_star_visitor boost::default_shooting_star_visitor
Definition at line 251 of file shooting_star_search.hpp.
Function Documentation
template<class Visitors > shooting_star_visitor<Visitors> boost::make_shooting_star_visitor (Visitors vis)
Definition at line 246 of file shooting_star_search.hpp.
Referenced by boost::detail::shooting_star_dispatch2().
template<class Edge , class Graph , class WeightMap , class EdgeMap , class PredecessorMap , class DistanceMap , class CostMap , class BinaryFunction , class BinaryPredicate > bool boost::relax (Edge e, Edge pe, Edge s, const Graph & g, const WeightMap & w, const EdgeMap & em, PredecessorMap & p, DistanceMap & d, CostMap & c, const BinaryFunction & combine, const BinaryPredicate & compare, int e_max_id)
Definition at line 86 of file shooting_star_relax.hpp.
References D, Edge::id, and U_TURN_COST.
Referenced by boost::detail::shooting_star_bfs_visitor< AStarHeuristic, UniformCostVisitor, UpdatableQueue, PredecessorMap, CostMap, DistanceMap, WeightMap, EdgeMap, ColorMap, EdgeColorMap, BinaryFunction, BinaryPredicate >::black_target(), boost::detail::shooting_star_bfs_visitor< AStarHeuristic, UniformCostVisitor, UpdatableQueue, PredecessorMap, CostMap, DistanceMap, WeightMap, EdgeMap, ColorMap, EdgeColorMap, BinaryFunction, BinaryPredicate >::gray_target(), relax(), and boost::detail::shooting_star_bfs_visitor< AStarHeuristic, UniformCostVisitor, UpdatableQueue, PredecessorMap, CostMap, DistanceMap, WeightMap, EdgeMap, ColorMap, EdgeColorMap, BinaryFunction, BinaryPredicate >::tree_edge().
template<class Graph , class WeightMap , class EdgeMap , class PredecessorMap , class DistanceMap > bool boost::relax (typename graph_traits< Graph >::edge_descriptor e, const Graph & g, WeightMap w, EdgeMap em, PredecessorMap p, DistanceMap d)
Definition at line 186 of file shooting_star_relax.hpp.
References D, and relax().
template<class IncidenceGraph , class Buffer , class BFSVisitor , class ColorMap , class EdgeColorMap > void boost::shooting_star_edges_visit (const IncidenceGraph & g, typename graph_traits< IncidenceGraph >::edge_descriptor s, Buffer & Q, BFSVisitor vis, ColorMap color, EdgeColorMap edge_color, int e_max_id)
Definition at line 137 of file shooting_star_search.hpp.
Referenced by shooting_star_search_no_init().
template<typename VertexAndEdgeListGraph , typename AStarHeuristic , typename ShootingStarVisitor , typename PredecessorMap , typename CostMap , typename DistanceMap , typename WeightMap , typename EdgeMap , typename IndexMap , typename ColorMap , typename EdgeColorMap , typename CompareFunction , typename CombineFunction , typename CostInf , typename CostZero > void boost::shooting_star_search (VertexAndEdgeListGraph & g, typename graph_traits< VertexAndEdgeListGraph >::edge_descriptor s, AStarHeuristic h, ShootingStarVisitor vis, PredecessorMap & predecessor, CostMap cost, DistanceMap distance, WeightMap weight, EdgeMap edge_map, IndexMap index_map, ColorMap color, EdgeColorMap edge_color, CompareFunction compare, CombineFunction combine, CostInf inf, CostZero zero, int e_max_id) inline
Definition at line 482 of file shooting_star_search.hpp.
References edges, and shooting_star_search_no_init().
Referenced by boost_shooting_star(), and boost::detail::shooting_star_dispatch2().
template<typename VertexAndEdgeListGraph , typename AStarHeuristic , typename P , typename T , typename R , typename IndexMap , typename DistanceMap , typename CostMap , typename PredecessorMap > void boost::shooting_star_search (VertexAndEdgeListGraph & g, typename graph_traits< VertexAndEdgeListGraph >::edge_descriptor s, AStarHeuristic h, const bgl_named_params< P, T, R > & params, IndexMap edge_index, DistanceMap distance, CostMap cost, PredecessorMap & pre_map, int e_max_id)
Definition at line 615 of file shooting_star_search.hpp.
References boost::detail::shooting_star_dispatch1().
template<typename VertexAndEdgeListGraph , typename AStarHeuristic , typename ShootingStarVisitor , typename PredecessorMap , typename CostMap , typename DistanceMap , typename WeightMap , typename EdgeMap , typename ColorMap , typename EdgeColorMap , typename IndexMap , typename CompareFunction , typename CombineFunction , typename CostInf , typename CostZero > void boost::shooting_star_search_no_init (VertexAndEdgeListGraph & g, typename graph_traits< VertexAndEdgeListGraph >::edge_descriptor s, AStarHeuristic h, ShootingStarVisitor vis, PredecessorMap & predecessor, CostMap cost, DistanceMap distance, WeightMap weight, EdgeMap edge_map, ColorMap color, EdgeColorMap edge_color, IndexMap index_map, CompareFunction compare, CombineFunction combine, CostInf inf, CostZero zero, int e_max_id) inline
Definition at line 435 of file shooting_star_search.hpp.
References shooting_star_edges_visit().
Referenced by shooting_star_search().