pgRouting: newTSP.c File Reference
newTSP.c File Reference
#include "postgres.h"
#include "executor/spi.h"
#include "funcapi.h"
#include "utils/array.h"
#include "catalog/pg_type.h"
#include "fmgr.h"
#include "./../../common/src/debug_macro.h"
#include "./../../common/src/time_msg.h"
#include "./../../common/src/pgr_types.h"
#include "./../../common/src/postgres_connection.h"
#include "./../../common/src/matrixRows_input.h"
#include "./newTSP_driver.h"
Macros
#define DEBUG
Functions
PGDLLEXPORT Datum newTSP (PG_FUNCTION_ARGS)
PG_FUNCTION_INFO_V1 (newTSP)
static void process (char *distances_sql, int64_t start_vid, int64_t end_vid, double time_limit, int64_t tries_per_temperature, int64_t max_changes_per_temperature, int64_t max_consecutive_non_changes, double initial_temperature, double final_temperature, double cooling_factor, bool randomize, General_path_element_t **result_tuples, size_t *result_count)
Macro Definition Documentation
#define DEBUG
Definition at line 40 of file newTSP.c.
Function Documentation
PGDLLEXPORT Datum newTSP (PG_FUNCTION_ARGS)
Definition at line 156 of file newTSP.c.
References pgr_text2char(), and process().
PG_FUNCTION_INFO_V1 (newTSP)
static void process (char * distances_sql, int64_t start_vid, int64_t end_vid, double time_limit, int64_t tries_per_temperature, int64_t max_changes_per_temperature, int64_t max_consecutive_non_changes, double initial_temperature, double final_temperature, double cooling_factor, bool randomize, General_path_element_t ** result_tuples, size_t * result_count) static
Definition at line 57 of file newTSP.c.
References do_pgr_tsp(), err_msg, PGR_DBG, pgr_get_matrixRows(), pgr_SPI_connect(), pgr_SPI_finish(), and time_msg().
Referenced by newTSP().