pgRouting: one_to_many_withPoints.c File Reference
one_to_many_withPoints.c File Reference
#include "postgres.h"
#include "executor/spi.h"
#include "funcapi.h"
#include "utils/array.h"
#include "catalog/pg_type.h"
#include "fmgr.h"
#include "./../../common/src/debug_macro.h"
#include "./../../common/src/time_msg.h"
#include "./../../common/src/pgr_types.h"
#include "./../../common/src/postgres_connection.h"
#include "./../../common/src/edges_input.h"
#include "./../../common/src/arrays_input.h"
#include "./../../common/src/points_input.h"
#include "./get_new_queries.h"
#include "./one_to_many_withPoints_driver.h"
Functions
PGDLLEXPORT Datum one_to_many_withPoints (PG_FUNCTION_ARGS)
PG_FUNCTION_INFO_V1 (one_to_many_withPoints)
static void process (char *edges_sql, char *points_sql, int64_t start_pid, int64_t *end_pidsArr, size_t size_end_pidsArr, bool directed, char *driving_side, bool details, bool only_cost, General_path_element_t **result_tuples, size_t *result_count)
Function Documentation
PGDLLEXPORT Datum one_to_many_withPoints (PG_FUNCTION_ARGS)
Definition at line 194 of file one_to_many_withPoints.c.
References PGR_DBG, pgr_get_bigIntArray(), pgr_text2char(), and process().
PG_FUNCTION_INFO_V1 (one_to_many_withPoints)
static void process (char * edges_sql, char * points_sql, int64_t start_pid, int64_t * end_pidsArr, size_t size_end_pidsArr, bool directed, char * driving_side, bool details, bool only_cost, General_path_element_t ** result_tuples, size_t * result_count) static
Definition at line 59 of file one_to_many_withPoints.c.
References do_pgr_one_to_many_withPoints(), edges, err_msg, get_new_queries(), PGR_DBG, pgr_get_edges(), pgr_get_points(), pgr_SPI_connect(), pgr_SPI_finish(), and time_msg().
Referenced by one_to_many_withPoints().