pgRouting: pdp.hpp File Reference
pdp.hpp File Reference
#include <math.h>
#include <vector>
Classes
struct Depot
struct Pickup
struct State
Typedefs
typedef std::vector< Customer > Customers
typedef std::vector< Pickup > Pickups
Functions
template<class T1 , class T2 >
double CalculateDistance (const T1 &from, const T2 &to)
Typedef Documentation
typedef std::vector< Customer > Customers
Definition at line 50 of file pdp.hpp.
typedef std::vector< Pickup > Pickups
Definition at line 51 of file pdp.hpp.
Function Documentation
template<class T1 , class T2 > double CalculateDistance (const T1 & from, const T2 & to)
Definition at line 66 of file pdp.hpp.
Referenced by get_result(), Solver(), and Route::update().