pgRouting: pgr_withPoints.hpp File Reference
pgr_withPoints.hpp File Reference
#include "./../../common/src/pgr_types.h"
#include "./../../common/src/basePath_SSEC.hpp"
Functions
void adjust_pids (const std::vector< Point_on_edge_t > &points, Path &path)
int check_points (std::vector< Point_on_edge_t > &points, std::ostringstream &log)
bool create_new_edges (std::vector< Point_on_edge_t > &points, const std::vector< pgr_edge_t > &edges, char driving_side, std::vector< pgr_edge_t > &new_edges)
bool create_new_edges (std::vector< Point_on_edge_t > &points, const std::vector< pgr_edge_t > &edges, char driving_side, std::vector< pgr_edge_t > &new_edges, std::ostringstream &log)
void eliminate_details (Path &path, const std::vector< pgr_edge_t > &point_edges)
void eliminate_details_dd (Path &path)
Function Documentation
void adjust_pids (const std::vector< Point_on_edge_t > & points, Path & path)
Definition at line 186 of file pgr_withPoints.cpp.
References adjust_pids(), Path::empty(), Path::end_id(), and Path::start_id().
int check_points (std::vector< Point_on_edge_t > & points, std::ostringstream & log)
Definition at line 56 of file pgr_withPoints.cpp.
References a, b, Point_on_edge_t::edge_id, Point_on_edge_t::fraction, PGR_LOG_POINTS(), Point_on_edge_t::pid, and Point_on_edge_t::side.
Referenced by do_pgr_many_to_many_withPoints(), do_pgr_many_to_one_withPoints(), do_pgr_many_withPointsDD(), do_pgr_one_to_many_withPoints(), do_pgr_withPoints(), do_pgr_withPointsDD(), and do_pgr_withPointsKsp().
bool create_new_edges (std::vector< Point_on_edge_t > & points, const std::vector< pgr_edge_t > & edges, char driving_side, std::vector< pgr_edge_t > & new_edges)
Definition at line 220 of file pgr_withPoints.cpp.
References create_new_edges().
Referenced by create_new_edges(), do_pgr_many_to_many_withPoints(), do_pgr_many_to_one_withPoints(), do_pgr_many_withPointsDD(), do_pgr_one_to_many_withPoints(), do_pgr_withPoints(), do_pgr_withPointsDD(), and do_pgr_withPointsKsp().
bool create_new_edges (std::vector< Point_on_edge_t > & points, const std::vector< pgr_edge_t > & edges, char driving_side, std::vector< pgr_edge_t > & new_edges, std::ostringstream & log)
Definition at line 232 of file pgr_withPoints.cpp.
References edge::cost, pgr_edge_t::cost, edge::id, pgr_edge_t::id, edge::reverse_cost, pgr_edge_t::reverse_cost, edge::source, pgr_edge_t::source, edge::target, and pgr_edge_t::target.
void eliminate_details (Path & path, const std::vector< pgr_edge_t > & point_edges)
Definition at line 121 of file pgr_withPoints.cpp.
References Path::empty(), Path::end_id(), edge::id, Path::push_back(), and Path::start_id().
Referenced by do_pgr_many_to_many_withPoints(), do_pgr_many_to_one_withPoints(), do_pgr_one_to_many_withPoints(), do_pgr_withPoints(), and do_pgr_withPointsKsp().
void eliminate_details_dd (Path & path)
Definition at line 100 of file pgr_withPoints.cpp.
References Path::empty(), Path::end_id(), Path::push_back(), and Path::start_id().
Referenced by do_pgr_many_withPointsDD(), and do_pgr_withPointsDD().