pgRouting: pgr_contract.hpp File Reference
pgr_contract.hpp File Reference
#include <stack>
#include <iostream>
#include <sstream>
#include <deque>
#include <queue>
#include <string>
#include <utility>
#include <functional>
#include <vector>
#include <map>
#include "./pgr_contractionGraph.hpp"
#include "./pgr_deadEndContraction.hpp"
#include "./pgr_linearContraction.hpp"
#include "../../common/src/pgr_assert.h"
Classes
class Pgr_contract< G >
class Pgr_contract< G >
Functions
bool is_valid_contraction_number (int number)
template<class G >
void perform_deadEnd (G &graph, Identifiers< int64_t > forbidden_vertices, std::ostringstream &debug)
template<class G >
void perform_linear (G &graph, Identifiers< int64_t > &forbidden_vertices, std::ostringstream &debug)
template<class G >
void pgr_contractGraph (G &graph, Identifiers< int64_t > forbidden_vertices, int64_t *contraction_order, size_t size_contraction_order, int64_t max_cycles, Identifiers< int64_t > &remaining_vertices, std::vector< pgrouting::contraction::Edge > &shortcut_edges, std::ostringstream &debug)
Function Documentation
bool is_valid_contraction_number (int number)
Definition at line 147 of file pgr_contract.hpp.
template<class G > void perform_deadEnd (G & graph, Identifiers< int64_t > forbidden_vertices, std::ostringstream & debug)
Definition at line 51 of file pgr_contract.hpp.
References pgrouting::Pgr_deadEndContraction< G >::calculateVertices(), pgrouting::Pgr_deadEndContraction< G >::doContraction(), and pgrouting::Pgr_deadEndContraction< G >::setForbiddenVertices().
Referenced by pgr_contractGraph().
template<class G > void perform_linear (G & graph, Identifiers< int64_t > & forbidden_vertices, std::ostringstream & debug)
Definition at line 71 of file pgr_contract.hpp.
References pgrouting::Pgr_linearContraction< G >::calculateVertices(), pgrouting::Pgr_linearContraction< G >::doContraction(), and pgrouting::Pgr_linearContraction< G >::setForbiddenVertices().
Referenced by pgr_contractGraph().
template<class G > void pgr_contractGraph (G & graph, Identifiers< int64_t > forbidden_vertices, int64_t * contraction_order, size_t size_contraction_order, int64_t max_cycles, Identifiers< int64_t > & remaining_vertices, std::vector< pgrouting::contraction::Edge > & shortcut_edges, std::ostringstream & debug)
Definition at line 91 of file pgr_contract.hpp.
References perform_deadEnd(), and perform_linear().
Referenced by do_pgr_contractGraph().