pgRouting: pgRouting.cpp File Reference
pgRouting.cpp File Reference
#include <boost/config.hpp>
#include <string>
#include <boost/program_options.hpp>
#include <boost/graph/adjacency_list.hpp>
#include <iostream>
#include <sstream>
#include <fstream>
#include <deque>
#include <unistd.h>
#include <libpq-fe.h>
#include "postgres.h"
#include "./../../common/src/pgr_types.h"
#include "./../../common/src/basePath_SSEC.hpp"
#include "./../../dijkstra/src/pgr_dijkstra.hpp"
#include "./../../warshall/src/pgr_warshall.hpp"
#include "./../../ksp/src/pgr_ksp.hpp"
#include "./driving.cpp"
#include "./dijkstra.hpp"
#include "./ksp.cpp"
#include "./warshall.hpp"
Functions
static void exit_nicely (PGconn *conn)
void get_options_description (po::options_description &od_desc)
void import_from_file (const std::string &input_file_name, pgr_edge_t *edges, unsigned int *count, int64_t start_vertex, int64_t end_vertex, bool &found)
int main (int ac, char *av[])
template<typename G >
void process (G graph, pgr_edge_t *data_edges, int row_count)
int process_command_line (po::variables_map &vm, po::options_description &od_desc)
Function Documentation
static void exit_nicely (PGconn * conn) static
Definition at line 162 of file pgRouting.cpp.
Referenced by main().
void get_options_description (po::options_description & od_desc)
Definition at line 93 of file pgRouting.cpp.
Referenced by main().
void import_from_file (const std::string & input_file_name, pgr_edge_t * edges, unsigned int * count, int64_t start_vertex, int64_t end_vertex, bool & found)
Definition at line 58 of file pgRouting.cpp.
References pgr_edge_t::cost, pgr_edge_t::id, pgr_edge_t::reverse_cost, pgr_edge_t::source, and pgr_edge_t::target.
int main (int ac, char * av[])
Definition at line 241 of file pgRouting.cpp.
References conn(), pgr_edge_t::cost, DIRECTED, exit_nicely(), get_options_description(), pgr_edge_t::id, process(), process_command_line(), pgr_edge_t::reverse_cost, pgr_edge_t::source, pgr_edge_t::target, and UNDIRECTED.
template<typename G > void process (G graph, pgr_edge_t * data_edges, int row_count)
Definition at line 171 of file pgRouting.cpp.
References process_dijkstra(), process_drivingDistance(), process_ksp(), and process_warshall().
Referenced by main().
int process_command_line (po::variables_map & vm, po::options_description & od_desc)
Definition at line 118 of file pgRouting.cpp.
Referenced by main().