pgRouting: pdp.c File Reference
pickDeliver/src/pdp.c File Reference
#include "postgres.h"
#include "executor/spi.h"
#include "funcapi.h"
#include "catalog/pg_type.h"
#include "fmgr.h"
#include "./pdp.h"
#include "../../common/src/debug_macro.h"
#include "../../common/src/postgres_connection.h"
#include "./customers_input.h"
Functions
static int compute_shortest_path (char *sql, int64_t vehicle_count, double capacity, path_element **results, size_t *length_results_struct)
PG_FUNCTION_INFO_V1 (vrppdtw)
Datum vrppdtw (PG_FUNCTION_ARGS)
Function Documentation
static int compute_shortest_path (char * sql, int64_t vehicle_count, double capacity, path_element ** results, size_t * length_results_struct) static
Definition at line 47 of file pickDeliver/src/pdp.c.
References err_msg, PGR_DBG, pgr_get_customers(), pgr_SPI_connect(), pgr_SPI_finish(), and Solver().
Referenced by vrppdtw().
PG_FUNCTION_INFO_V1 (vrppdtw)
Datum vrppdtw (PG_FUNCTION_ARGS)
Definition at line 86 of file pickDeliver/src/pdp.c.
References compute_shortest_path(), PGR_DBG, and pgr_text2char().