pgRouting: pdp.h File Reference
pickDeliver/src/pdp.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "postgres.h"
Classes
struct Customer
struct path_element
Functions
int64_t Solver (Customer *c, size_t total_tuples, int64_t vehicle_count, int64_t capacity, char **msg, path_element **results, size_t *length_results)
Function Documentation
int64_t Solver (Customer * c, size_t total_tuples, int64_t vehicle_count, int64_t capacity, char ** msg, path_element ** results, size_t * length_results)
Definition at line 80 of file pickDeliver/src/pdp_solver.cpp.
References c, CalculateDistance(), Customer::Ddist, Pickup::Ddist, Customer::demand, Customer::Dindex, Customer::Etime, get_result(), Customer::id, Customer::Ltime, Customer::Pindex, Solution::routes, S0, Customer::Stime, T, TabuSearch(), Customer::x, and Customer::y.
Referenced by compute_shortest_path().