pgRouting: restrictions_input.h File Reference
restrictions_input.h File Reference
#include "./pgr_types.h"
Functions
void pgr_get_restriction_data (char *restrictions_sql, Restrict_t **restructions, size_t *total_restrictions)
Function Documentation
void pgr_get_restriction_data (char * restrictions_sql, Restrict_t ** restructions, size_t * total_restrictions)
Definition at line 68 of file restrictions_input.c.
References ANY_INTEGER, ANY_NUMERICAL, Column_info_t::colNumber, Column_info_t::eType, fetch_restriction(), Column_info_t::name, PGR_DBG, pgr_fetch_column_info(), pgr_SPI_cursor_open(), pgr_SPI_prepare(), Column_info_t::strict, TEXT, time_msg(), total_tuples, and Column_info_t::type.
Referenced by compute_trsp().