pgRouting: shooting_star_boost_wrapper.cpp File Reference
shooting_star_boost_wrapper.cpp File Reference
#include "shooting_star.h"
#include <boost/config.hpp>
#include <boost/version.hpp>
#include <boost/graph/graph_traits.hpp>
#include <boost/graph/adjacency_list.hpp>
#include <boost/vector_property_map.hpp>
#include <shooting_star_search.hpp>
#include <cmath>
Classes
class distance_heuristic< Graph, CostType >
struct Edge
class found_goal< Edge >
class shooting_star_goal_visitor< Edge >
struct Vertex
Functions
int boost_shooting_star (edge_shooting_star_t *edges_array, unsigned int count, int source_edge_id, int target_edge_id, bool directed, bool has_reverse_cost, path_element_t **path, int *path_count, char **err_msg, int e_max_id)
template<class G , class E >
static void graph_add_edge (G &graph, int index, int id, int source, int target, float8 cost, float8 s_x, float8 s_y, float8 t_x, float8 t_y, std::map< int, vector< std::pair< float, vector< int > > >, std::less< int > > adjacent_edges)
Function Documentation
int boost_shooting_star (edge_shooting_star_t * edges_array, unsigned int count, int source_edge_id, int target_edge_id, bool directed, bool has_reverse_cost, path_element_t ** path, int * path_count, char ** err_msg, int e_max_id)
Definition at line 203 of file shooting_star_boost_wrapper.cpp.
References Edge::adjacent_edges, Edge::color, edge_shooting_star::cost, Edge::cost, Edge::distance, edges, found_goal< Edge >::get_target(), edge_shooting_star::id, Edge::index, MAX_NODES, MAX_RULE_LENGTH, Edge::rank, edge_shooting_star::reverse_cost, edge_shooting_star::s_x, edge_shooting_star::s_y, boost::shooting_star_search(), edge_shooting_star::source, edge_shooting_star::t_x, edge_shooting_star::t_y, and edge_shooting_star::target.
Referenced by compute_shortest_path_shooting_star().
template<class G , class E > static void graph_add_edge (G & graph, int index, int id, int source, int target, float8 cost, float8 s_x, float8 s_y, float8 t_x, float8 t_y, std::map< int, vector< std::pair< float, vector< int > > >, std::less< int > > adjacent_edges) static
Definition at line 157 of file shooting_star_boost_wrapper.cpp.
References MAX_COST.
Referenced by pgRouting::graph::Pgr_base_graph< G, Vertex, Edge >::restore_graph().