pgRouting: shooting_star.c File Reference
shooting_star.c File Reference
#include "postgres.h"
#include "executor/spi.h"
#include "funcapi.h"
#include "catalog/pg_type.h"
#include <stdio.h>
#include <stdlib.h>
#include <search.h>
#include <string.h>
#include <time.h>
#include "shooting_star.h"
Classes
struct edge_shooting_star_columns
Macros
#define DBG(format, arg...) do { ; } while (0)
#define TUPLIMIT 1000
Typedefs
typedef struct
edge_shooting_star_columns edge_shooting_star_columns_t
Functions
static int compute_shortest_path_shooting_star (char *sql, int source_edge_id, int target_edge_id, bool directed, bool has_reverse_cost, path_element_t **path, int *path_count)
static void fetch_edge_shooting_star (HeapTuple *tuple, TupleDesc *tupdesc, edge_shooting_star_columns_t *edge_columns, edge_shooting_star_t *target_edge)
static int fetch_edge_shooting_star_columns (SPITupleTable *tuptable, edge_shooting_star_columns_t *edge_columns, bool has_reverse_cost)
static int finish (int code, int ret)
PG_FUNCTION_INFO_V1 (shortest_path_shooting_star)
Datum shortest_path_shooting_star (PG_FUNCTION_ARGS)
static char * text2char (text *in)
Macro Definition Documentation
#define DBG (format, arg...) do { ; } while (0)
Definition at line 72 of file shooting_star.c.
Referenced by compute_shortest_path_shooting_star(), fetch_edge_shooting_star_columns(), and shortest_path_shooting_star().
#define TUPLIMIT 1000
Definition at line 76 of file shooting_star.c.
Referenced by compute_shortest_path_shooting_star().
Typedef Documentation
typedef struct edge_shooting_star_columns edge_shooting_star_columns_t
Function Documentation
static int compute_shortest_path_shooting_star (char * sql, int source_edge_id, int target_edge_id, bool directed, bool has_reverse_cost, path_element_t ** path, int * path_count) static
Definition at line 295 of file shooting_star.c.
References boost_shooting_star(), DBG, edges, err_msg, fetch_edge_shooting_star(), fetch_edge_shooting_star_columns(), finish(), edge_shooting_star::id, edge_shooting_star_columns::id, total_tuples, and TUPLIMIT.
Referenced by shortest_path_shooting_star().
static void fetch_edge_shooting_star (HeapTuple * tuple, TupleDesc * tupdesc, edge_shooting_star_columns_t * edge_columns, edge_shooting_star_t * target_edge) static
Definition at line 209 of file shooting_star.c.
References edge_shooting_star::cost, edge_shooting_star_columns::cost, edge_shooting_star::id, edge_shooting_star_columns::id, MAX_RULE_LENGTH, edge_shooting_star::reverse_cost, edge_shooting_star_columns::reverse_cost, edge_shooting_star::rule, edge_shooting_star_columns::rule, edge_shooting_star::s_x, edge_shooting_star_columns::s_x, edge_shooting_star::s_y, edge_shooting_star_columns::s_y, edge_shooting_star::source, edge_shooting_star_columns::source, edge_shooting_star::t_x, edge_shooting_star_columns::t_x, edge_shooting_star::t_y, edge_shooting_star_columns::t_y, edge_shooting_star::target, edge_shooting_star_columns::target, edge_shooting_star::to_cost, and edge_shooting_star_columns::to_cost.
Referenced by compute_shortest_path_shooting_star().
static int fetch_edge_shooting_star_columns (SPITupleTable * tuptable, edge_shooting_star_columns_t * edge_columns, bool has_reverse_cost) static
Definition at line 117 of file shooting_star.c.
References edge_shooting_star_columns::cost, DBG, edge_shooting_star_columns::id, edge_shooting_star_columns::reverse_cost, edge_shooting_star_columns::rule, edge_shooting_star_columns::s_x, edge_shooting_star_columns::s_y, edge_shooting_star_columns::source, edge_shooting_star_columns::t_x, edge_shooting_star_columns::t_y, edge_shooting_star_columns::target, and edge_shooting_star_columns::to_cost.
Referenced by compute_shortest_path_shooting_star().
static int finish (int code, int ret) static
Definition at line 89 of file shooting_star.c.
Referenced by compute_shortest_path_shooting_star().
PG_FUNCTION_INFO_V1 (shortest_path_shooting_star)
Datum shortest_path_shooting_star (PG_FUNCTION_ARGS)
Definition at line 472 of file shooting_star.c.
References compute_shortest_path_shooting_star(), DBG, path, path_count, and text2char().
static char* text2char (text * in) static
Definition at line 79 of file shooting_star.c.
Referenced by shortest_path_shooting_star().