pgRouting: tsp.h File Reference
tsp.h File Reference
#include "postgres.h"
#include "../../common/src/pgr_types.h"
Classes
struct point
Macros
#define _TSP_H
#define DTYPE double
Typedefs
typedef struct point point_t
Functions
int find_tsp_solution (int num, double *dist, int *p_ids, int source, int end, double *fit, char *err_msg)
Macro Definition Documentation
#define _TSP_H
Definition at line 29 of file tsp.h.
#define DTYPE double
Definition at line 32 of file tsp.h.
Referenced by annealing(), find_tsp_solution(), findEulerianPath(), get_pgarray(), getReverseCost(), getThreeWayCost(), pathLength(), solve_tsp(), and tsp_matrix().
Typedef Documentation
typedef struct point point_t
Function Documentation
int find_tsp_solution (int num, double * dist, int * p_ids, int source, int end, double * fit, char * err_msg)
Definition at line 496 of file tsplib.c.
References annealing(), tspstruct::bestlen, tspstruct::border, tspstruct::dist, DTYPE, findEulerianPath(), initRand(), tspstruct::iorder, tspstruct::jorder, MAX, tspstruct::maxd, tspstruct::n, pathLength(), PGR_DBG, and reverse().
Referenced by solve_tsp().