pgRouting: pdp.h File Reference
vrppdtw/src/pdp.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
Classes
struct Customer
struct Depot
struct PathElement
struct Pickup
struct statesave
struct Vehicle
Typedefs
typedef struct Customer customer
typedef struct Depot depot
typedef struct PathElement path_element
typedef struct Pickup pickup
typedef struct statesave State
typedef struct Vehicle VehicleInfo
Functions
double CalculateDistance (int x1, int y1, int x2, int y2)
int Solver (customer *c, int total_tuples, int vehicle_count, int capacity, char **msg, path_element **results, int *length_results)
Typedef Documentation
typedef struct Customer customer
typedef struct Depot depot
typedef struct PathElement path_element
typedef struct Pickup pickup
typedef struct statesave State
typedef struct Vehicle VehicleInfo
Function Documentation
double CalculateDistance (int x1, int y1, int x2, int y2)
Definition at line 82 of file vrppdtw/src/pdp.h.
int Solver (customer * c, int total_tuples, int vehicle_count, int capacity, char ** msg, path_element ** results, int * length_results)
Definition at line 92 of file vrppdtw/src/pdp_solver.cpp.
References Route::append(), CalculateDistance(), Vehicle::capacity, Pickup::checked, Route::cost(), Vehicle::cost, Solution::cost_total, CustomerLength, Route::cv, Solution::cv_total, Customer::D, Customer::Ddist, Pickup::Ddist, Depot::demand, Customer::demand, Pickup::Did, Depot::Dindex, Customer::Dindex, Route::dis, Solution::dis_total, Depot::Etime, Customer::Etime, Vehicle::given_vehicles, Route::HillClimbing(), Depot::id, Customer::id, Pickup::id, Depot::Ltime, Customer::Ltime, Customer::P, PickupLength, Pickup::Pid, Depot::Pindex, Customer::Pindex, Solution::r, Route::remove(), Solution::route_length, Vehicle::speed, Depot::Stime, Customer::Stime, TabuSearch(), Route::twv, Solution::twv_total, Vehicle::used_vehicles, Depot::x, Customer::x, Depot::y, and Customer::y.