pgRouting: pdp.c File Reference
vrppdtw/src/pdp.c File Reference
#include "./postgres.h"
#include "executor/spi.h"
#include "funcapi.h"
#include "catalog/pg_type.h"
#include "fmgr.h"
#include "./pdp.h"
#include "../../common/src/debug_macro.h"
Classes
struct Customer_type
Macros
#define TUPLIMIT 1000
Typedefs
typedef struct Customer_type customer_t
Functions
static int compute_shortest_path (char *sql, int vehicle_count, int capacity, path_element **results, int *length_results_struct)
static void fetch_customer (HeapTuple *tuple, TupleDesc *tupdesc, customer_t *c_all, customer *c_single)
static int fetch_customer_columns (SPITupleTable *tuptable, customer_t *c, int vehicle_count, int capacity)
static int finish (int code, int ret)
PG_FUNCTION_INFO_V1 (vrppdtw)
static char * text2char (text *in)
PGDLLEXPORT Datum vrppdtw (PG_FUNCTION_ARGS)
Variables
PG_MODULE_MAGIC
Macro Definition Documentation
#define TUPLIMIT 1000
Definition at line 43 of file vrppdtw/src/pdp.c.
Referenced by compute_shortest_path().
Typedef Documentation
typedef struct Customer_type customer_t
Function Documentation
static int compute_shortest_path (char * sql, int vehicle_count, int capacity, path_element ** results, int * length_results_struct) static
Definition at line 226 of file vrppdtw/src/pdp.c.
References err_msg, fetch_customer(), fetch_customer_columns(), finish(), Customer_type::id, PGR_DBG, Solver(), and TUPLIMIT.
Referenced by vrppdtw().
static void fetch_customer (HeapTuple * tuple, TupleDesc * tupdesc, customer_t * c_all, customer * c_single) static
Definition at line 166 of file vrppdtw/src/pdp.c.
References Customer::demand, Customer_type::demand, Customer::Dindex, Customer_type::Dindex, Customer::Etime, Customer_type::Etime, Customer::id, Customer_type::id, Customer::Ltime, Customer_type::Ltime, PGR_DBG, Customer::Pindex, Customer_type::Pindex, Customer::Stime, Customer_type::Stime, Customer::x, Customer_type::x, Customer::y, and Customer_type::y.
Referenced by compute_shortest_path().
static int fetch_customer_columns (SPITupleTable * tuptable, customer_t * c, int vehicle_count, int capacity) static
Definition at line 124 of file vrppdtw/src/pdp.c.
References Customer_type::demand, Customer_type::Dindex, Customer_type::Etime, Customer_type::id, Customer_type::Ltime, PGR_DBG, Customer_type::Pindex, Customer_type::Stime, Customer_type::x, and Customer_type::y.
Referenced by compute_shortest_path().
static int finish (int code, int ret) static
Definition at line 61 of file vrppdtw/src/pdp.c.
Referenced by compute_shortest_path().
PG_FUNCTION_INFO_V1 (vrppdtw)
static char* text2char (text * in) static
Definition at line 51 of file vrppdtw/src/pdp.c.
Referenced by vrppdtw().
PGDLLEXPORT Datum vrppdtw (PG_FUNCTION_ARGS)
Definition at line 355 of file vrppdtw/src/pdp.c.
References compute_shortest_path(), PGR_DBG, and text2char().
Variable Documentation
PG_MODULE_MAGIC
Definition at line 46 of file vrppdtw/src/pdp.c.