pgRouting: withPoints_dd.c File Reference
withPoints_dd.c File Reference
#include "postgres.h"
#include "executor/spi.h"
#include "funcapi.h"
#include "utils/array.h"
#include "catalog/pg_type.h"
#include "fmgr.h"
#include "./../../common/src/pgr_types.h"
#include "./../../common/src/time_msg.h"
#include "./../../common/src/postgres_connection.h"
#include "./../../common/src/edges_input.h"
#include "./../../common/src/points_input.h"
#include "./../../withPoints/src/get_new_queries.h"
#include "./withPoints_dd_driver.h"
#include "./../../common/src/debug_macro.h"
Functions
PG_FUNCTION_INFO_V1 (withPoints_dd)
static void process (char *edges_sql, char *points_sql, int64_t start_pid, double distance, bool directed, char *driving_side, bool details, General_path_element_t **result_tuples, size_t *result_count)
PGDLLEXPORT Datum withPoints_dd (PG_FUNCTION_ARGS)
Function Documentation
PG_FUNCTION_INFO_V1 (withPoints_dd)
static void process (char * edges_sql, char * points_sql, int64_t start_pid, double distance, bool directed, char * driving_side, bool details, General_path_element_t ** result_tuples, size_t * result_count) static
Definition at line 58 of file withPoints_dd.c.
References do_pgr_withPointsDD(), edges, err_msg, get_new_queries(), PGR_DBG, pgr_get_edges(), pgr_get_points(), pgr_send_error(), pgr_SPI_connect(), pgr_SPI_finish(), and time_msg().
Referenced by withPoints_dd().
PGDLLEXPORT Datum withPoints_dd (PG_FUNCTION_ARGS)
Definition at line 154 of file withPoints_dd.c.
References PGR_DBG, pgr_text2char(), and process().