pgRouting: xyd_tsp.c File Reference
xyd_tsp.c File Reference
#include "postgres.h"
#include "executor/spi.h"
#include "funcapi.h"
#include "utils/array.h"
#include "catalog/pg_type.h"
#include "fmgr.h"
#include "./../../common/src/debug_macro.h"
#include "./../../common/src/pgr_types.h"
#include "./../../common/src/postgres_connection.h"
#include "./distances_input.h"
#include "./tsp_driver.h"
Functions
PG_FUNCTION_INFO_V1 (xyd_tsp)
static void process (char *distances_sql, int64_t start_vid, int64_t end_vid, General_path_element_t **result_tuples, size_t *result_count)
Datum xyd_tsp (PG_FUNCTION_ARGS)
Function Documentation
PG_FUNCTION_INFO_V1 (xyd_tsp)
static void process (char * distances_sql, int64_t start_vid, int64_t end_vid, General_path_element_t ** result_tuples, size_t * result_count) static
Definition at line 63 of file xyd_tsp.c.
References do_pgr_tsp(), err_msg, PGR_DBG, pgr_get_distances(), pgr_SPI_connect(), and pgr_SPI_finish().
Referenced by xyd_tsp().
Datum xyd_tsp (PG_FUNCTION_ARGS)
Definition at line 110 of file xyd_tsp.c.
References PGR_DBG, pgr_text2char(), and process().