PGROUTING: alpha_driver.cpp File Reference
alpha_driver.cpp File Reference
#include "drivers/alpha_shape/alpha_driver.h"
#include <vector>
#include <list>
#include <cmath>
#include <utility>
#include <algorithm>
#include <set>
#include "cpp_common/pgr_assert.h"
#include "CGAL/Simple_cartesian.h"
#include "CGAL/Filtered_kernel.h"
#include "CGAL/algorithm.h"
#include "CGAL/Polygon_2.h"
#include "CGAL/Delaunay_triangulation_2.h"
#include "CGAL/Triangulation_2.h"
#include "CGAL/Triangulation_hierarchy_vertex_base_2.h"
#include "CGAL/Triangulation_hierarchy_2.h"
#include "CGAL/Triangulation_face_base_2.h"
#include "CGAL/Triangulation_euclidean_traits_2.h"
#include "CGAL/Alpha_shape_2.h"
#include "CGAL/Alpha_shape_face_base_2.h"
#include "CGAL/Alpha_shape_vertex_base_2.h"
#include "cpp_common/pgr_alloc.hpp"
Typedefs
typedef CGAL::Alpha_shape_face_base_2< K, Tf > Af
typedef Alpha_shape_2::Alpha_iterator Alpha_iterator
typedef CGAL::Alpha_shape_2< Ht > Alpha_shape_2
typedef Alpha_shape_2::Alpha_shape_edges_iterator Alpha_shape_edges_iterator
typedef CGAL::Triangulation_hierarchy_vertex_base_2< Avb > Av
typedef CGAL::Alpha_shape_vertex_base_2< K > Avb
typedef double coord_type
typedef CGAL::Delaunay_triangulation_2< K, Tds > Dt
typedef Alpha_shape_2::Face_circulator Face_circulator
typedef CGAL::Triangulation_hierarchy_2< Dt > Ht
typedef CGAL::Filtered_kernel< SC > K
typedef K::Point_2 Point
typedef CGAL::Polygon_2< K > Polygon_2
typedef CGAL::Simple_cartesian< coord_type > SC
typedef K::Segment_2 Segment
typedef CGAL::Triangulation_default_data_structure_2< K, Av, Af > Tds
typedef CGAL::Triangulation_face_base_2< K > Tf
typedef K::Vector_2 Vector
typedef Alpha_shape_2::Vertex_circulator Vertex_circulator
Functions
template<class OutputIterator >
void alpha_edges (const Alpha_shape_2 &A, OutputIterator out)
int alpha_shape (vertex_t *vertices, size_t count, double alpha, vertex_t **return_tuples, size_t *res_count, char **err_msg)
void find_next_edge (Segment s, std::vector< Segment > &segments, std::set< int > &unusedIndexes, std::vector< Polygon_2 > &rings)
double get_angle (Point p, Point q, Point r)
Variables
size_t prev_size = 0
Typedef Documentation
Af
typedef CGAL::Alpha_shape_face_base_2<K, Tf> Af
Definition at line 80 of file alpha_driver.cpp.
Alpha_iterator
typedef Alpha_shape_2::Alpha_iterator Alpha_iterator
Definition at line 90 of file alpha_driver.cpp.
Alpha_shape_2
typedef CGAL::Alpha_shape_2<Ht> Alpha_shape_2
Definition at line 85 of file alpha_driver.cpp.
Alpha_shape_edges_iterator
typedef Alpha_shape_2::Alpha_shape_edges_iterator Alpha_shape_edges_iterator
Definition at line 91 of file alpha_driver.cpp.
Av
typedef CGAL::Triangulation_hierarchy_vertex_base_2<Avb> Av
Definition at line 77 of file alpha_driver.cpp.
Avb
typedef CGAL::Alpha_shape_vertex_base_2<K> Avb
Definition at line 76 of file alpha_driver.cpp.
coord_type
typedef double coord_type
Definition at line 67 of file alpha_driver.cpp.
Dt
typedef CGAL::Delaunay_triangulation_2<K, Tds> Dt
Definition at line 83 of file alpha_driver.cpp.
Face_circulator
typedef Alpha_shape_2::Face_circulator Face_circulator
Definition at line 87 of file alpha_driver.cpp.
Ht
typedef CGAL::Triangulation_hierarchy_2<Dt> Ht
Definition at line 84 of file alpha_driver.cpp.
K
typedef CGAL::Filtered_kernel<SC> K
Definition at line 70 of file alpha_driver.cpp.
Point
typedef K::Point_2 Point
Definition at line 71 of file alpha_driver.cpp.
Polygon_2
typedef CGAL::Polygon_2<K> Polygon_2
Definition at line 74 of file alpha_driver.cpp.
SC
typedef CGAL::Simple_cartesian<coord_type> SC
Definition at line 69 of file alpha_driver.cpp.
Segment
typedef K::Segment_2 Segment
Definition at line 72 of file alpha_driver.cpp.
Tds
typedef CGAL::Triangulation_default_data_structure_2<K, Av, Af> Tds
Definition at line 82 of file alpha_driver.cpp.
Tf
typedef CGAL::Triangulation_face_base_2<K> Tf
Definition at line 79 of file alpha_driver.cpp.
Vector
typedef K::Vector_2 Vector
Definition at line 73 of file alpha_driver.cpp.
Vertex_circulator
typedef Alpha_shape_2::Vertex_circulator Vertex_circulator
Definition at line 88 of file alpha_driver.cpp.
Function Documentation
alpha_edges()
template<class OutputIterator > void alpha_edges (const Alpha_shape_2 & A, OutputIterator out)
Definition at line 164 of file alpha_driver.cpp.
Referenced by alpha_shape().
{
     for (Alpha_shape_edges_iterator it =  A.alpha_shape_edges_begin();
             it != A.alpha_shape_edges_end();
             ++it) {
         *out++ = A.segment(*it);
     }
 }
alpha_shape()
int alpha_shape (vertex_t * vertices, size_t count, double alpha, vertex_t ** return_tuples, size_t * res_count, char ** err_msg)
Definition at line 174 of file alpha_driver.cpp.
References alpha_edges(), find_next_edge(), pgr_alloc(), pgr_free(), pgr_msg(), and AssertFailedException::what().
Referenced by compute_alpha_shape().
{
     std::ostringstream err;
     try {
         std::list<Point> points;
         {
             std::vector<Point> pv;
             for (std::size_t j = 0; j < count; ++j) {
                 Point p(vertices[j].x, vertices[j].y);
                 pv.push_back(p);
             }
             std::sort(pv.begin(), pv.end(),
                     [](const Point &e1, const Point &e2)->bool {
                     return e2.y() < e1.y();
                     });
             std::stable_sort(pv.begin(), pv.end(),
                     [](const Point &e1, const Point &e2)->bool {
                     return e2.x() < e1.x();
                     });
             pv.erase(std::unique(pv.begin(), pv.end()), pv.end());
             if (pv.size() != count &&  pv.size() < 3) {
                 err << "After eliminating duplicated points,"
                    " less than 3 points remain!!."
                    " Alpha shape calculation needs at least 3 vertices.";
                 *err_msg = pgr_msg(err.str().c_str());
                 return -1;
             }
             points.insert(points.begin(), pv.begin(), pv.end());
         }
         Alpha_shape_2 A(points.begin(), points.end(),
                 coord_type(10000),
                 Alpha_shape_2::REGULARIZED);
         std::vector<Segment> segments;
         //  std::vector<Segment> result;
         //  Alpha_shape_2::Alpha_shape_vertices_iterator vit;
         //  Alpha_shape_2::Vertex_handle vertex;
         //  Alpha_shape_2::Alpha_shape_edges_iterator eit;
         //  Alpha_shape_2::Edge edge;
         //  Alpha_shape_2::Face_iterator fit;
         //  Alpha_shape_2::Face_handle face;
         if (alpha <= 0.0) {
             alpha = *A.find_optimal_alpha(1);
         }
         A.set_alpha(alpha);
         alpha_edges(A, std::back_inserter(segments));
         //  Segment s = segments.at(0);
         //  find_next_edge(s, segments, result);
         if (segments.empty()) {
             *return_tuples = NULL;
             *res_count = 0;
         } else {
             std::set<int> unusedIndexes;
             for (unsigned int i = 0; i < segments.size(); i++) {
                 unusedIndexes.insert(i);
             }
             std::vector<Polygon_2> rings;
             Polygon_2 ring;
             ring.push_back(segments.at(0).source());
             rings.push_back(ring);
             unusedIndexes.erase(0);
             find_next_edge(segments.at(0), segments, unusedIndexes, rings);
             size_t result_count = 0;
             for (unsigned int i = 0; i < rings.size(); i++) {
                 Polygon_2 ring = rings.at(i);
                 result_count += ring.size();
             }
             result_count += rings.size() - 1;
             *return_tuples = pgr_alloc(result_count, (*return_tuples));
             *res_count = result_count;
             int idx = 0;
             for (unsigned int i = 0; i < rings.size(); i++) {
                 if (i > 0) {
                     (*return_tuples)[idx].x = DBL_MAX;
                     (*return_tuples)[idx].y = DBL_MAX;
                     idx++;
                 }
                 Polygon_2 ring = rings.at(i);
                 for (unsigned int j = 0; j < ring.size(); j++) {
                     Point point = ring.vertex(j);
                     (*return_tuples)[idx].x = point.x();
                     (*return_tuples)[idx].y = point.y();
                     idx++;
                 }
             }
         }
         *err_msg = NULL;
         return EXIT_SUCCESS;
     } catch (AssertFailedException &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*res_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
     } catch (std::exception &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*res_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
     } catch(...) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*res_count) = 0;
         err << "Caught unknown exception!";
         *err_msg = pgr_msg(err.str().c_str());
     }
     return -1;
 }
find_next_edge()
void find_next_edge (Segment s, std::vector< Segment > & segments, std::set< int > & unusedIndexes, std::vector< Polygon_2 > & rings)
Definition at line 109 of file alpha_driver.cpp.
References get_angle(), and prev_size.
Referenced by alpha_shape().
{
     if (unusedIndexes.empty()
             || prev_size == unusedIndexes.size()) {
         return;
     }
     prev_size = unusedIndexes.size();
     Point start = s.source();
     Point end = s.target();
     rings.back().push_back(end);
     std::vector<int> nextIndexes;
     for (unsigned int i = 0; i < segments.size(); i++) {
         if (unusedIndexes.find(i) != unusedIndexes.end()) {
             Point source = segments.at(i).source();
             if (source == end) {
                 nextIndexes.push_back(i);
             }
         }
     }
     if (nextIndexes.size() == 1) {
         int i = nextIndexes.at(0);
         unusedIndexes.erase(i);
         find_next_edge(segments.at(i), segments, unusedIndexes, rings);
     } else if (nextIndexes.size() > 1) {
         std::vector< std::pair<double, int> > nextAngles;
         for (unsigned int i = 0; i < nextIndexes.size(); i++) {
             int j = nextIndexes.at(i);
             Point target = segments.at(j).target();
             double angle = get_angle(start, end, target);
             nextAngles.push_back(std::pair<double, int>(angle, j));
         }
         std::sort(nextAngles.begin(), nextAngles.end());
         int i = nextAngles.begin()->second;
         unusedIndexes.erase(i);
         find_next_edge(segments.at(i), segments, unusedIndexes, rings);
     }
     if (!unusedIndexes.empty()) {
         for (unsigned int i = 0; i < segments.size(); i++) {
             if (unusedIndexes.find(i) != unusedIndexes.end()) {
                 Polygon_2 ring;
                 ring.push_back(segments.at(i).source());
                 rings.push_back(ring);
                 unusedIndexes.erase(i);
                 find_next_edge(segments.at(i), segments, unusedIndexes, rings);
             }
         }
     }
 }
get_angle()
double get_angle (Point p, Point q, Point r)
Definition at line 95 of file alpha_driver.cpp.
Referenced by find_next_edge().
{
     double m_pi(3.14159265358979323846);
     Vector v1(q, p);
     Vector v2(q, r);
     double cross = v1.x() * v2.y() - v1.y() * v2.x();
     double dot = v1.x() * v2.x() + v1.y() * v2.y();
     double angle = atan2(cross, dot);
     if (angle < 0.0) {
         angle += 2 * m_pi;
     }
     return angle;
 }
Variable Documentation
prev_size
size_t prev_size = 0
Definition at line 108 of file alpha_driver.cpp.
Referenced by find_next_edge().