PGROUTING: alpha_driver.h File Reference
alpha_driver.h File Reference
#include <stddef.h>
Classes
struct vertex
Typedefs
typedef struct vertex vertex_t
Functions
int alpha_shape (vertex_t *vertices, size_t count, double alpha, vertex_t **res, size_t *res_count, char **err_msg)
Typedef Documentation
vertex_t
typedef struct vertex vertex_t
Function Documentation
alpha_shape()
int alpha_shape (vertex_t * vertices, size_t count, double alpha, vertex_t ** res, size_t * res_count, char ** err_msg)
Definition at line 174 of file alpha_driver.cpp.
References alpha_edges(), find_next_edge(), pgr_alloc(), pgr_free(), pgr_msg(), and AssertFailedException::what().
Referenced by compute_alpha_shape().
{
     std::ostringstream err;
     try {
         std::list<Point> points;
         {
             std::vector<Point> pv;
             for (std::size_t j = 0; j < count; ++j) {
                 Point p(vertices[j].x, vertices[j].y);
                 pv.push_back(p);
             }
             std::sort(pv.begin(), pv.end(),
                     [](const Point &e1, const Point &e2)->bool {
                     return e2.y() < e1.y();
                     });
             std::stable_sort(pv.begin(), pv.end(),
                     [](const Point &e1, const Point &e2)->bool {
                     return e2.x() < e1.x();
                     });
             pv.erase(std::unique(pv.begin(), pv.end()), pv.end());
             if (pv.size() != count &&  pv.size() < 3) {
                 err << "After eliminating duplicated points,"
                    " less than 3 points remain!!."
                    " Alpha shape calculation needs at least 3 vertices.";
                 *err_msg = pgr_msg(err.str().c_str());
                 return -1;
             }
             points.insert(points.begin(), pv.begin(), pv.end());
         }
         Alpha_shape_2 A(points.begin(), points.end(),
                 coord_type(10000),
                 Alpha_shape_2::REGULARIZED);
         std::vector<Segment> segments;
         //  std::vector<Segment> result;
         //  Alpha_shape_2::Alpha_shape_vertices_iterator vit;
         //  Alpha_shape_2::Vertex_handle vertex;
         //  Alpha_shape_2::Alpha_shape_edges_iterator eit;
         //  Alpha_shape_2::Edge edge;
         //  Alpha_shape_2::Face_iterator fit;
         //  Alpha_shape_2::Face_handle face;
         if (alpha <= 0.0) {
             alpha = *A.find_optimal_alpha(1);
         }
         A.set_alpha(alpha);
         alpha_edges(A, std::back_inserter(segments));
         //  Segment s = segments.at(0);
         //  find_next_edge(s, segments, result);
         if (segments.empty()) {
             *return_tuples = NULL;
             *res_count = 0;
         } else {
             std::set<int> unusedIndexes;
             for (unsigned int i = 0; i < segments.size(); i++) {
                 unusedIndexes.insert(i);
             }
             std::vector<Polygon_2> rings;
             Polygon_2 ring;
             ring.push_back(segments.at(0).source());
             rings.push_back(ring);
             unusedIndexes.erase(0);
             find_next_edge(segments.at(0), segments, unusedIndexes, rings);
             size_t result_count = 0;
             for (unsigned int i = 0; i < rings.size(); i++) {
                 Polygon_2 ring = rings.at(i);
                 result_count += ring.size();
             }
             result_count += rings.size() - 1;
             *return_tuples = pgr_alloc(result_count, (*return_tuples));
             *res_count = result_count;
             int idx = 0;
             for (unsigned int i = 0; i < rings.size(); i++) {
                 if (i > 0) {
                     (*return_tuples)[idx].x = DBL_MAX;
                     (*return_tuples)[idx].y = DBL_MAX;
                     idx++;
                 }
                 Polygon_2 ring = rings.at(i);
                 for (unsigned int j = 0; j < ring.size(); j++) {
                     Point point = ring.vertex(j);
                     (*return_tuples)[idx].x = point.x();
                     (*return_tuples)[idx].y = point.y();
                     idx++;
                 }
             }
         }
         *err_msg = NULL;
         return EXIT_SUCCESS;
     } catch (AssertFailedException &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*res_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
     } catch (std::exception &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*res_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
     } catch(...) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*res_count) = 0;
         err << "Caught unknown exception!";
         *err_msg = pgr_msg(err.str().c_str());
     }
     return -1;
 }