PGROUTING: pgrouting::contraction::Pgr_linear< G > Class Template Reference
pgrouting::contraction::Pgr_linear< G > Class Template Reference
#include "pgr_linearContraction.hpp"
Public Member Functions
Pgr_linear ()
void calculateVertices (G &graph)
void doContraction (G &graph)
void setForbiddenVertices (Identifiers< V > forbidden_vertices)
Private Types
typedef G::degree_size_type degree_size_type
typedef G::E E
typedef G::E_i E_i
typedef G::EI_i EI_i
typedef G::EO_i EO_i
typedef G::V V
typedef G::V_i V_i
Private Member Functions
void add_edge_pair (V vertex, int64_t &incoming_eid, int64_t &outgoing_eid)
void add_if_linear (G &graph, V v)
void add_shortcut (G &graph, V vertex, E incoming_edge, E outgoing_edge)
add edges(shortuct) to the graph during contraction
void add_shortcut (G &graph, pgrouting::CH_edge &shortcut)
int64_t get_next_id ()
bool is_linear (G &graph, V v)
Private Attributes
std::ostringstream debug
Identifiers< V > forbiddenVertices
int64_t last_edge_id
Identifiers< V > linearVertices
Detailed Description
template<class G>
class pgrouting::contraction::Pgr_linear< G >
Definition at line 46 of file pgr_linearContraction.hpp.
Member Typedef Documentation
degree_size_type
template<class G> typedef G::degree_size_type pgrouting::contraction::Pgr_linear< G >::degree_size_type private
Definition at line 54 of file pgr_linearContraction.hpp.
E
template<class G> typedef G::E pgrouting::contraction::Pgr_linear< G >::E private
Definition at line 49 of file pgr_linearContraction.hpp.
E_i
template<class G> typedef G::E_i pgrouting::contraction::Pgr_linear< G >::E_i private
Definition at line 51 of file pgr_linearContraction.hpp.
EI_i
template<class G> typedef G::EI_i pgrouting::contraction::Pgr_linear< G >::EI_i private
Definition at line 53 of file pgr_linearContraction.hpp.
EO_i
template<class G> typedef G::EO_i pgrouting::contraction::Pgr_linear< G >::EO_i private
Definition at line 52 of file pgr_linearContraction.hpp.
V
template<class G> typedef G::V pgrouting::contraction::Pgr_linear< G >::V private
Definition at line 48 of file pgr_linearContraction.hpp.
V_i
template<class G> typedef G::V_i pgrouting::contraction::Pgr_linear< G >::V_i private
Definition at line 50 of file pgr_linearContraction.hpp.
Constructor & Destructor Documentation
Pgr_linear()
template<class G> pgrouting::contraction::Pgr_linear< G >::Pgr_linear () inline
Definition at line 58 of file pgr_linearContraction.hpp.
References pgrouting::contraction::Pgr_linear< G >::calculateVertices(), pgrouting::contraction::Pgr_linear< G >::doContraction(), and pgrouting::contraction::Pgr_linear< G >::setForbiddenVertices().
 :last_edge_id(0) {}
Member Function Documentation
add_edge_pair()
template<class G> void pgrouting::contraction::Pgr_linear< G >::add_edge_pair (V vertex, int64_t & incoming_eid, int64_t & outgoing_eid) private
Referenced by pgrouting::contraction::Pgr_linear< G >::get_next_id().
add_if_linear()
template<class G> void pgrouting::contraction::Pgr_linear< G >::add_if_linear (G & graph, V v) private
Referenced by pgrouting::contraction::Pgr_linear< G >::get_next_id().
add_shortcut() [1/2]
template<class G > void pgrouting::contraction::Pgr_linear< G >::add_shortcut (G & graph, V vertex, E incoming_edge, E outgoing_edge) private
add edges(shortuct) to the graph during contraction
a –incomming–> b —outgoing–> c
a -> c
edge (a, c) is a new edge: shortcut e.contracted_vertices = b + b.contracted vertices b is "removed" disconnected from the graph
by removing all edges to/from b
Definition at line 227 of file pgr_linearContraction.hpp.
References pgrouting::CH_edge::add_contracted_edge_vertices(), pgrouting::CH_edge::add_contracted_vertex(), pgrouting::contraction::Pgr_linear< G >::debug, Identifiers< T >::front(), pgrouting::contraction::Pgr_linear< G >::get_next_id(), pgassert, and Identifiers< T >::pop_front().
Referenced by pgrouting::contraction::Pgr_linear< G >::doContraction(), and pgrouting::contraction::Pgr_linear< G >::get_next_id().
{
     pgassert(incoming_edge != outgoing_edge);
     auto a = graph.adjacent(vertex, incoming_edge);
     auto c = graph.adjacent(vertex, outgoing_edge);
     pgassert(a != vertex);
     pgassert(a != c);
     pgassert(vertex != c);
     if (graph.is_undirected()) {
         Identifiers<V> adjacent_vertices = graph.find_adjacent_vertices(vertex);
         V vertex_1 = adjacent_vertices.front();
         adjacent_vertices.pop_front();
         V vertex_2 = adjacent_vertices.front();
         adjacent_vertices.pop_front();
         E shortcut_E;
         CH_edge shortcut(get_next_id(), graph[vertex_1].id,
                 graph[vertex_2].id,
                 graph[incoming_edge].cost + graph[outgoing_edge].cost);
         shortcut.add_contracted_vertex(graph[vertex], vertex);
         shortcut.add_contracted_edge_vertices(graph[incoming_edge]);
         shortcut.add_contracted_edge_vertices(graph[outgoing_edge]);
         debug << "Adding shortcut\n";
         debug << shortcut;
         graph.add_shortcut(shortcut);
         debug << "Added shortcut\n";
     } else {
         CH_edge shortcut(
                 get_next_id(),
                 graph[a].id,
                 graph[c].id,
                 graph[incoming_edge].cost + graph[outgoing_edge].cost);
         shortcut.add_contracted_vertex(graph[vertex], vertex);
         shortcut.add_contracted_edge_vertices(graph[incoming_edge]);
         shortcut.add_contracted_edge_vertices(graph[outgoing_edge]);
         debug << "Adding shortcut\n";
         debug << shortcut;
         graph.add_shortcut(shortcut);
         debug << "Added shortcut\n";
     }
 }
add_shortcut() [2/2]
template<class G > void pgrouting::contraction::Pgr_linear< G >::add_shortcut (G & graph, pgrouting::CH_edge & shortcut) private
Definition at line 274 of file pgr_linearContraction.hpp.
{
     graph.add_shortcut(shortcut);
 }
calculateVertices()
template<class G > void pgrouting::contraction::Pgr_linear< G >::calculateVertices (G & graph)
Definition at line 115 of file pgr_linearContraction.hpp.
References pgrouting::contraction::Pgr_linear< G >::debug, pgrouting::contraction::Pgr_linear< G >::forbiddenVertices, pgrouting::contraction::Pgr_linear< G >::is_linear(), and pgrouting::contraction::Pgr_linear< G >::linearVertices.
Referenced by pgrouting::contraction::Pgr_contract< G >::perform_linear(), and pgrouting::contraction::Pgr_linear< G >::Pgr_linear().
{
     debug << "Calculating vertices\n";
     V_i vi;
     for (vi = vertices(graph.graph).first;
             vi != vertices(graph.graph).second;
             ++vi) {
         debug << "Checking vertex " << graph.graph[(*vi)].id << '\n';
         if (is_linear(graph, *vi)) {
             linearVertices += (*vi);
         }
     }
     linearVertices -= forbiddenVertices;
 }
doContraction()
template<class G > void pgrouting::contraction::Pgr_linear< G >::doContraction (G & graph)
Definition at line 132 of file pgr_linearContraction.hpp.
References pgrouting::contraction::Pgr_linear< G >::add_shortcut(), pgrouting::contraction::Pgr_linear< G >::debug, DIRECTED, pgrouting::contraction::Pgr_linear< G >::forbiddenVertices, Identifiers< T >::front(), Identifiers< T >::has(), pgrouting::contraction::Pgr_linear< G >::is_linear(), pgrouting::contraction::Pgr_linear< G >::linearVertices, pgassert, Identifiers< T >::pop_front(), Identifiers< T >::size(), and UNDIRECTED.
Referenced by pgrouting::contraction::Pgr_contract< G >::perform_linear(), and pgrouting::contraction::Pgr_linear< G >::Pgr_linear().
{
     std::ostringstream contraction_debug;
     contraction_debug << "Performing contraction\n";
     std::priority_queue<V, std::vector<V>, std::greater<V> > linearPriority;
     for (const auto linearVertex : linearVertices) {
         linearPriority.push(linearVertex);
     }
     contraction_debug << "Linear vertices" << std::endl;
     for (const auto v : linearVertices) {
         contraction_debug << graph[v].id << ", ";
     }
     contraction_debug << std::endl;
     while (!linearPriority.empty()) {
         V current_vertex = linearPriority.top();
         linearPriority.pop();
         if (!is_linear(graph, current_vertex)) {
             linearVertices -= current_vertex;
             continue;
         }
         Identifiers<V> adjacent_vertices =
             graph.find_adjacent_vertices(current_vertex);
         pgassert(adjacent_vertices.size() == 2);
         V vertex_1 = adjacent_vertices.front();
         adjacent_vertices.pop_front();
         V vertex_2 = adjacent_vertices.front();
         adjacent_vertices.pop_front();
         contraction_debug << "Adjacent vertices\n";
         contraction_debug << graph[vertex_1].id
             << ", " << graph[vertex_2].id
             << std::endl;
         if (graph.m_gType == DIRECTED) {
             if (graph.out_degree_to_vertex(vertex_1, current_vertex) > 0 &&
                     graph.in_degree_from_vertex(vertex_2, current_vertex) > 0) {
                 E e1 = graph.get_min_cost_edge(vertex_1,
                         current_vertex);
                 E e2 = graph.get_min_cost_edge(current_vertex,
                         vertex_2);
                 add_shortcut(graph, current_vertex, e1, e2);
             }
             if (graph.out_degree_to_vertex(vertex_2, current_vertex) > 0 &&
                     graph.in_degree_from_vertex(vertex_1, current_vertex) > 0) {
                 E e1 = graph.get_min_cost_edge(vertex_2,
                         current_vertex);
                 E e2 = graph.get_min_cost_edge(current_vertex,
                         vertex_1);
                 add_shortcut(graph, current_vertex, e1, e2);
             }
         } else if (graph.m_gType == UNDIRECTED) {
             if (graph.out_degree_to_vertex(vertex_1, current_vertex) > 0 &&
                     graph.in_degree_from_vertex(vertex_2, current_vertex) > 0) {
                 contraction_debug << "UNDIRECTED graph before contraction\n";
                 graph.print_graph(contraction_debug);
                 E e1 = graph.get_min_cost_edge(vertex_1,
                         current_vertex);
                 E e2 = graph.get_min_cost_edge(current_vertex,
                         vertex_2);
                 add_shortcut(graph, current_vertex, e1, e2);
             }
         }
         graph.disconnect_vertex(current_vertex);
         linearVertices -= current_vertex;
         if (is_linear(graph, vertex_1)
                 && !forbiddenVertices.has(vertex_1)) {
             linearPriority.push(vertex_1);
             linearVertices += vertex_1;
         }
         if (is_linear(graph, vertex_2)
                 && !forbiddenVertices.has(vertex_2)) {
             linearPriority.push(vertex_2);
             linearVertices += vertex_2;
         }
     }
     debug << contraction_debug.str().c_str() << "\n";
 }
get_next_id()
template<class G> int64_t pgrouting::contraction::Pgr_linear< G >::get_next_id () inline private
Definition at line 65 of file pgr_linearContraction.hpp.
References pgrouting::contraction::Pgr_linear< G >::add_edge_pair(), pgrouting::contraction::Pgr_linear< G >::add_if_linear(), pgrouting::contraction::Pgr_linear< G >::add_shortcut(), pgrouting::contraction::Pgr_linear< G >::is_linear(), and pgrouting::contraction::Pgr_linear< G >::last_edge_id.
Referenced by pgrouting::contraction::Pgr_linear< G >::add_shortcut().
{
          return --last_edge_id;
      }
is_linear()
template<class G > bool pgrouting::contraction::Pgr_linear< G >::is_linear (G & graph, V v) private
Definition at line 99 of file pgr_linearContraction.hpp.
References pgrouting::contraction::Pgr_linear< G >::debug, and Identifiers< T >::size().
Referenced by pgrouting::contraction::Pgr_linear< G >::calculateVertices(), pgrouting::contraction::Pgr_linear< G >::doContraction(), and pgrouting::contraction::Pgr_linear< G >::get_next_id().
{
     degree_size_type in_degree, out_degree;
     in_degree = graph.in_degree(v);
     out_degree = graph.out_degree(v);
     Identifiers<V> adjacent_vertices = graph.find_adjacent_vertices(v);
     if (adjacent_vertices.size() == 2) {
         if (in_degree > 0 && out_degree > 0) {
             debug << graph.graph[v].id << " is linear " << std::endl;
             return true;
         }
     }
     debug << graph.graph[v].id << " is not linear " << std::endl;
     return false;
 }
setForbiddenVertices()
template<class G > void pgrouting::contraction::Pgr_linear< G >::setForbiddenVertices (Identifiers< V > forbidden_vertices)
Definition at line 91 of file pgr_linearContraction.hpp.
References pgrouting::contraction::Pgr_linear< G >::debug, and pgrouting::contraction::Pgr_linear< G >::forbiddenVertices.
Referenced by pgrouting::contraction::Pgr_contract< G >::perform_linear(), and pgrouting::contraction::Pgr_linear< G >::Pgr_linear().
{
     debug << "Setting forbidden vertices\n";
     forbiddenVertices = forbidden_vertices;
 }
Member Data Documentation
debug
template<class G> std::ostringstream pgrouting::contraction::Pgr_linear< G >::debug private
Definition at line 84 of file pgr_linearContraction.hpp.
Referenced by pgrouting::contraction::Pgr_linear< G >::add_shortcut(), pgrouting::contraction::Pgr_linear< G >::calculateVertices(), pgrouting::contraction::Pgr_linear< G >::doContraction(), pgrouting::contraction::Pgr_linear< G >::is_linear(), and pgrouting::contraction::Pgr_linear< G >::setForbiddenVertices().
forbiddenVertices
template<class G> Identifiers<V> pgrouting::contraction::Pgr_linear< G >::forbiddenVertices private
Definition at line 81 of file pgr_linearContraction.hpp.
Referenced by pgrouting::contraction::Pgr_linear< G >::calculateVertices(), pgrouting::contraction::Pgr_linear< G >::doContraction(), and pgrouting::contraction::Pgr_linear< G >::setForbiddenVertices().
last_edge_id
template<class G> int64_t pgrouting::contraction::Pgr_linear< G >::last_edge_id private
Definition at line 83 of file pgr_linearContraction.hpp.
Referenced by pgrouting::contraction::Pgr_linear< G >::get_next_id().
linearVertices
template<class G> Identifiers<V> pgrouting::contraction::Pgr_linear< G >::linearVertices private
Definition at line 80 of file pgr_linearContraction.hpp.
Referenced by pgrouting::contraction::Pgr_linear< G >::calculateVertices(), and pgrouting::contraction::Pgr_linear< G >::doContraction().
The documentation for this class was generated from the following file:
pgr_linearContraction.hpp