PGROUTING: Pgr_ksp< G >::compPaths Class Reference
Pgr_ksp< G >::compPaths Class Reference
Public Member Functions
bool operator() (const Path &p1, const Path &p2) const
Detailed Description
template<class G>
class Pgr_ksp< G >::compPaths
Definition at line 52 of file pgr_ksp.hpp.
Member Function Documentation
operator()()
template<class G> bool Pgr_ksp< G >::compPaths::operator() (const Path & p1, const Path & p2) const inline
Definition at line 54 of file pgr_ksp.hpp.
References Pgr_ksp< G >::doNextCycle(), Pgr_ksp< G >::executeYen(), Pgr_ksp< G >::getFirstSolution(), pgassert, Pgr_ksp< G >::removeVertices(), Path::size(), and Path::tot_cost().
{
               /*
                * less cost is best
                */
               if (p1.tot_cost() > p2.tot_cost())
                   return  false;
               if (p1.tot_cost() < p2.tot_cost())
                 return  true;
               //pgassert(p1.tot_cost() == p2.tot_cost());
               // paths costs are equal now check by length
               if (p1.size() > p2.size())
                   return false;
               if (p1.size() < p2.size())
                   return true;
               pgassert(p1.tot_cost() == p2.tot_cost());
               pgassert(p1.size() == p2.size());
               // paths weights & lengths are equal now check by node ID
               unsigned int i;
               for (i = 0; i < p1.size(); i++) {
                   if (p1[i].node >  p2[i].node)
                       return false;
                   if (p1[i].node <  p2[i].node)
                       return true;
               }
               pgassert(p1.tot_cost() == p2.tot_cost());
               pgassert(p1.size() == p2.size());
 #ifdef NDEBUG
               for (i = 0; i < p1.size(); i++) {
                   pgassert(p1[i].node == p2[i].node);
               }
 #endif
               // we got here and everything is equal
               return false;
           }
The documentation for this class was generated from the following file:
pgr_ksp.hpp