PGROUTING: pgrouting::vrp::Tw_node Class Reference
pgrouting::vrp::Tw_node Class Reference
Extends the Node class to create a Node with time window attributes.
#include "tw_node.h"
Public Types
enum NodeType {
kStart = 0, kPickup, kDelivery, kDump,
kLoad, kEnd
}
Public Member Functions
Tw_node ()=default
Tw_node (const Tw_node &)=default
Tw_node (size_t id, PickDeliveryOrders_t data, NodeType type)
Tw_node (size_t id, Vehicle_t data, NodeType type)
int64_t id () const
size_t idx () const
void reset_id (int64_t)
accessors
int64_t order () const
@ {
double opens () const
Returns the opening time.
double closes () const
Returns the closing time.
double demand () const
Returns the demand associated with this node.
void demand (double value)
double service_time () const
Returns the service time for this node.
NodeType type () const
Returns the type of this node.
double window_length () const
Returns the length of time between the opening and closing.
double travel_time_to (const Tw_node &other, double speed) const
time = distance / speed.
kind of node
A true value when;
0 < opens < closes
the type is the requested type
the demand are valid for the requested type
bool is_start () const
@ {
bool is_pickup () const
is_pickup
bool is_delivery () const
is_delivery
bool is_dump () const
is_dump
bool is_load () const
is_Load
bool is_end () const
is_end
std::string type_str () const
to be or not to be
bool operator== (const Tw_node &rhs) const
bool is_early_arrival (double arrival_time) const
True when arrivalTime is before it opens.
bool is_late_arrival (double arrival_time) const
True when arrivalTime is after it closes.
bool is_on_time (double arrival_time) const
True when arrivalTime in the time window.
document functions
double arrival_j_opens_i (const Tw_node &I, double speed) const
@ {
double arrival_j_closes_i (const Tw_node &I, double speed) const
The actual arrival time at this node, given that: this node is visited directly after other node and that the actual arrival time at other node was closes(other)
bool is_compatible_IJ (const Tw_node &I, double speed) const
bool is_partially_compatible_IJ (const Tw_node &I, double speed) const
bool is_tight_compatible_IJ (const Tw_node &I, double speed) const
bool is_partially_waitTime_compatible_IJ (const Tw_node &I, double speed) const
bool is_waitTime_compatible_IJ (const Tw_node &I, double speed) const
Static Public Attributes
static Pgr_messages msg
Protected Member Functions
bool is_valid () const
Static Protected Attributes
static Pgr_pickDeliver * problem
Private Attributes
double m_closes
closing time of the node
double m_demand
The demand for the Node.
double m_opens
opening time of the node
int64_t m_order
order to which it belongs
double m_service_time
NodeType m_type
The demand for the Node.
Friends
std::ostream & operator<< (std::ostream &log, const Tw_node &node)
Print the contents of a Twnode object.
Detailed Description
Extends the Node class to create a Node with time window attributes.
A Time Window node is a Node with addition attributes and methods to to support Time Windows and to model a more complex Node need in many vehicle routing problems.
Most application specific code will extend this class and define the specific values and requirements for type and streetid.
Definition at line 57 of file tw_node.h.
Member Enumeration Documentation
NodeType
enum pgrouting::vrp::Tw_node::NodeType
Enumerator
kStart
starting site
kPickup
pickup site
kDelivery
delivery site
kDump
dump site, empties truck
kLoad
load site, fills the truck
kEnd
ending site
Definition at line 59 of file tw_node.h.
                   {
          kStart = 0,
          kPickup,
          kDelivery,
          kDump,
          kLoad,
          kEnd
      } NodeType;
Constructor & Destructor Documentation
Tw_node() [1/4]
pgrouting::vrp::Tw_node::Tw_node () default
Referenced by is_on_time().
Tw_node() [2/4]
pgrouting::vrp::Tw_node::Tw_node (const Tw_node &) default
Tw_node() [3/4]
pgrouting::vrp::Tw_node::Tw_node (size_t id, PickDeliveryOrders_t data, NodeType type)
Definition at line 232 of file tw_node.cpp.
References PickDeliveryOrders_t::deliver_close_t, PickDeliveryOrders_t::deliver_node_id, PickDeliveryOrders_t::deliver_open_t, PickDeliveryOrders_t::deliver_service_t, kDelivery, m_closes, m_demand, m_opens, m_service_time, m_type, and pgrouting::Identifier::reset_id().
                        :
     Identifier(id, data.pick_node_id),
     m_order(data.id),
     m_opens(data.pick_open_t),
     m_closes(data.pick_close_t),
     m_service_time(data.pick_service_t),
     m_demand(data.demand),
     m_type(type)  {
         if (m_type == kDelivery) {
             reset_id(data.deliver_node_id);
             m_opens = data.deliver_open_t;
             m_closes = data.deliver_close_t;
             m_service_time = data.deliver_service_t;
             m_demand *= -1;
         }
     }
Tw_node() [4/4]
pgrouting::vrp::Tw_node::Tw_node (size_t id, Vehicle_t data, NodeType type)
Definition at line 252 of file tw_node.cpp.
References Vehicle_t::end_close_t, Vehicle_t::end_node_id, Vehicle_t::end_open_t, Vehicle_t::end_service_t, kEnd, m_closes, m_opens, m_service_time, m_type, and pgrouting::Identifier::reset_id().
                        :
     Identifier(id, data.start_node_id),
     m_opens(data.start_open_t),
     m_closes(data.start_close_t),
     m_service_time(data.start_service_t),
     m_demand(0),
     m_type(type) {
         if (m_type == kEnd) {
             reset_id(data.end_node_id);
             m_opens = data.end_open_t;
             m_closes = data.end_close_t;
             m_service_time = data.end_service_t;
         }
     }
Member Function Documentation
arrival_j_closes_i()
double pgrouting::vrp::Tw_node::arrival_j_closes_i (const Tw_node & I, double speed) const
The actual arrival time at this node, given that: this node is visited directly after other node and that the actual arrival time at other node was closes(other)
Definition at line 64 of file tw_node.cpp.
References closes(), kStart, m_type, service_time(), and travel_time_to().
Referenced by is_on_time(), is_partially_compatible_IJ(), and is_tight_compatible_IJ().
{
     if (m_type == kStart) return  (std::numeric_limits<double>::max)();
     return I.closes() + I.service_time() + I.travel_time_to(*this, speed);
 }
arrival_j_opens_i()
double pgrouting::vrp::Tw_node::arrival_j_opens_i (const Tw_node & I, double speed) const
@ {
The actual arrival time at This node, given that: this node is visited directly after other node and that the actual arrival time at other node was opens(other)
Definition at line 58 of file tw_node.cpp.
References kStart, m_type, opens(), service_time(), and travel_time_to().
Referenced by is_compatible_IJ(), is_on_time(), is_partially_compatible_IJ(), is_partially_waitTime_compatible_IJ(), is_tight_compatible_IJ(), and is_waitTime_compatible_IJ().
{
     if (m_type == kStart) return (std::numeric_limits<double>::max)();
     return I.opens() + I.service_time() + I.travel_time_to(*this, speed);
 }
closes()
double pgrouting::vrp::Tw_node::closes () const inline
Returns the closing time.
Definition at line 79 of file tw_node.h.
References m_closes.
Referenced by pgrouting::vrp::Fleet::add_vehicle(), arrival_j_closes_i(), pgrouting::vrp::Vehicle::deltaTime(), is_delivery(), is_dump(), is_end(), is_load(), pgrouting::vrp::Vehicle::is_ok(), is_pickup(), is_start(), and pgrouting::vrp::Vehicle::Vehicle().
 {return m_closes;}
demand() [1/2]
double pgrouting::vrp::Tw_node::demand () const inline
Returns the demand associated with this node.
Definition at line 82 of file tw_node.h.
References m_demand.
Referenced by pgrouting::vrp::Vehicle_node::evaluate(), is_delivery(), is_dump(), is_end(), is_load(), is_pickup(), and is_start().
 {return m_demand;}
demand() [2/2]
void pgrouting::vrp::Tw_node::demand (double value) inline
Definition at line 83 of file tw_node.h.
References m_demand.
 {m_demand = value;}
id()
int64_t pgrouting::Identifier::id () const inherited
Definition at line 42 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Dnode::distance(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::vrp::Vehicle::is_phony(), pgrouting::vrp::Optimize::move_reduce_cost(), pgrouting::vrp::operator<<(), pgrouting::operator<<(), pgrouting::vrp::Base_node::operator==(), pgrouting::vrp::Node::operator==(), pgrouting::vrp::Node::print(), pgrouting::vrp::Base_node::print(), pgrouting::vrp::Vehicle::tau(), and pgrouting::vrp::Vehicle::Vehicle().
                      {
     return m_id;
 }
idx()
size_t pgrouting::Identifier::idx () const inherited
Definition at line 37 of file identifier.cpp.
References pgrouting::Identifier::m_idx.
Referenced by pgrouting::vrp::Vehicle_pickDeliver::erase(), pgrouting::vrp::Vehicle::erase(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Vehicle_pickDeliver::has_order(), pgrouting::vrp::Vehicle_pickDeliver::insert(), pgrouting::vrp::Vehicle::insert(), pgrouting::vrp::operator<<(), pgrouting::operator<<(), pgrouting::vrp::Base_node::operator==(), pgrouting::vrp::Node::operator==(), operator==(), pgrouting::vrp::Node::print(), pgrouting::vrp::Base_node::print(), pgrouting::vrp::Vehicle_pickDeliver::push_back(), pgrouting::vrp::Vehicle_pickDeliver::push_front(), pgrouting::vrp::Order::set_compatibles(), pgrouting::vrp::Solution::sort_by_id(), pgrouting::vrp::Optimize::swap_worse(), pgrouting::vrp::Vehicle::tau(), travel_time_to(), and pgrouting::vrp::Vehicle::Vehicle().
                       {
     return m_idx;
 }
is_compatible_IJ()
bool pgrouting::vrp::Tw_node::is_compatible_IJ (const Tw_node & I, double speed) const
Definition at line 73 of file tw_node.cpp.
References arrival_j_opens_i(), is_late_arrival(), kEnd, kStart, and m_type.
Referenced by pgrouting::vrp::Vehicle::getPosHighLimit(), is_on_time(), is_partially_compatible_IJ(), is_partially_waitTime_compatible_IJ(), is_tight_compatible_IJ(), pgrouting::vrp::Order::is_valid(), is_waitTime_compatible_IJ(), and pgrouting::vrp::Order::isCompatibleIJ().
{
     /*
      * I /->  kStart
      */
     if (m_type == kStart) return false;
     /*
      * kEnd /-> (*this)
      */
     if (I.m_type == kEnd) return false;
     return !is_late_arrival(arrival_j_opens_i(I, speed));
 }
is_delivery()
bool pgrouting::vrp::Tw_node::is_delivery () const
is_delivery
To be a delivery node:
type is kDelivery
demand < 0
Definition at line 150 of file tw_node.cpp.
References closes(), demand(), kDelivery, m_type, opens(), and service_time().
Referenced by pgrouting::vrp::Order::is_valid(), is_valid(), and window_length().
{
     return m_type == kDelivery
         && (opens() < closes())
         && (service_time() >= 0)
         && (demand() < 0);
 }
is_dump()
bool pgrouting::vrp::Tw_node::is_dump () const
is_dump
To be a dump node:
type is kDump
demand <= 0
Definition at line 159 of file tw_node.cpp.
References closes(), demand(), kDump, m_type, opens(), and service_time().
Referenced by pgrouting::vrp::Vehicle_node::evaluate(), is_valid(), and window_length().
{
     return m_type == kDump
         && (opens() < closes())
         && (service_time() >= 0)
         && (demand() <= 0);
 }
is_early_arrival()
bool pgrouting::vrp::Tw_node::is_early_arrival (double arrival_time) const inline
True when arrivalTime is before it opens.
Definition at line 187 of file tw_node.h.
References m_opens.
Referenced by pgrouting::vrp::Vehicle::deltaTime(), pgrouting::vrp::Vehicle_node::evaluate(), is_on_time(), is_partially_compatible_IJ(), is_partially_waitTime_compatible_IJ(), is_tight_compatible_IJ(), and is_waitTime_compatible_IJ().
{
          return arrival_time < m_opens;
      }
is_end()
bool pgrouting::vrp::Tw_node::is_end () const
is_end
To be a End node:
type is kEnd
demand == 0
Definition at line 177 of file tw_node.cpp.
References closes(), demand(), kEnd, m_type, opens(), and service_time().
Referenced by pgrouting::vrp::Fleet::add_vehicle(), pgrouting::vrp::Vehicle_node::has_cv(), is_valid(), and window_length().
                       {
     return m_type == kEnd
         && (opens() < closes())
         && (service_time() >= 0)
         && (demand() == 0);
 }
is_late_arrival()
bool pgrouting::vrp::Tw_node::is_late_arrival (double arrival_time) const inline
True when arrivalTime is after it closes.
Definition at line 192 of file tw_node.h.
References m_closes.
Referenced by pgrouting::vrp::Vehicle_node::deltaGeneratesTWV(), pgrouting::vrp::Vehicle_node::has_twv(), is_compatible_IJ(), is_on_time(), is_partially_compatible_IJ(), and is_tight_compatible_IJ().
{
          return arrival_time > m_closes;
      }
is_load()
bool pgrouting::vrp::Tw_node::is_load () const
is_Load
To be a Load node:
type is kLoad
demand >= 0
Definition at line 168 of file tw_node.cpp.
References closes(), demand(), kLoad, m_type, opens(), and service_time().
Referenced by is_valid(), and window_length().
{
     return m_type == kLoad
         && (opens() < closes())
         && (service_time() >= 0)
         && (demand() >= 0);
 }
is_on_time()
bool pgrouting::vrp::Tw_node::is_on_time (double arrival_time) const inline
True when arrivalTime in the time window.
Definition at line 196 of file tw_node.h.
References arrival_j_closes_i(), arrival_j_opens_i(), is_compatible_IJ(), is_early_arrival(), is_late_arrival(), is_partially_compatible_IJ(), is_partially_waitTime_compatible_IJ(), is_tight_compatible_IJ(), is_valid(), is_waitTime_compatible_IJ(), Tw_node(), and type().
{
          return !is_early_arrival(arrival_time)
              && !is_late_arrival(arrival_time);
      }
is_partially_compatible_IJ()
bool pgrouting::vrp::Tw_node::is_partially_compatible_IJ (const Tw_node & I, double speed) const
Definition at line 87 of file tw_node.cpp.
References arrival_j_closes_i(), arrival_j_opens_i(), is_compatible_IJ(), is_early_arrival(), and is_late_arrival().
Referenced by is_on_time().
{
     return
         is_compatible_IJ(I, speed)
         && !is_early_arrival(arrival_j_opens_i(I, speed))
         && is_late_arrival(arrival_j_closes_i(I, speed));
 }
is_partially_waitTime_compatible_IJ()
bool pgrouting::vrp::Tw_node::is_partially_waitTime_compatible_IJ (const Tw_node & I, double speed) const
Definition at line 103 of file tw_node.cpp.
References arrival_j_opens_i(), is_compatible_IJ(), and is_early_arrival().
Referenced by is_on_time().
{
     return
         is_compatible_IJ(I, speed)
         && is_early_arrival(arrival_j_opens_i(I, speed));
 }
is_pickup()
bool pgrouting::vrp::Tw_node::is_pickup () const
is_pickup
To be a pickup node:
type is kPickup
demand > 0
Definition at line 141 of file tw_node.cpp.
References closes(), demand(), kPickup, m_type, opens(), and service_time().
Referenced by pgrouting::vrp::Order::is_valid(), is_valid(), and window_length().
{
     return m_type == kPickup
         && (opens() < closes())
         && (service_time() >= 0)
         && (demand() > 0);
 }
is_start()
bool pgrouting::vrp::Tw_node::is_start () const
@ {
is_start
To be a start node:
type is kStart
demand == 0
Definition at line 132 of file tw_node.cpp.
References closes(), demand(), kStart, m_type, opens(), and service_time().
Referenced by pgrouting::vrp::Fleet::add_vehicle(), pgrouting::vrp::Vehicle_node::evaluate(), pgrouting::vrp::Vehicle_node::has_cv(), is_valid(), and window_length().
{
     return
         m_type == kStart
         && (opens() < closes())
         && (service_time() >= 0)
         && (demand() == 0);
 }
is_tight_compatible_IJ()
bool pgrouting::vrp::Tw_node::is_tight_compatible_IJ (const Tw_node & I, double speed) const
Definition at line 95 of file tw_node.cpp.
References arrival_j_closes_i(), arrival_j_opens_i(), is_compatible_IJ(), is_early_arrival(), and is_late_arrival().
Referenced by is_on_time().
{
     return
         is_compatible_IJ(I, speed)
         && !is_early_arrival(arrival_j_opens_i(I, speed))
         && !is_late_arrival(arrival_j_closes_i(I, speed));
 }
is_valid()
bool pgrouting::vrp::Tw_node::is_valid () const protected
Definition at line 197 of file tw_node.cpp.
References is_delivery(), is_dump(), is_end(), is_load(), is_pickup(), is_start(), kDelivery, kDump, kEnd, kLoad, kPickup, kStart, and type().
Referenced by is_on_time().
{
     switch (type()) {
         case kStart:
             return is_start();
             break;
         case kEnd:
             return is_end();
             break;
         case kDump:
             return is_dump();
             break;
         case kDelivery:
             return is_delivery();
             break;
         case kPickup:
             return is_pickup();
             break;
         case kLoad:
             return is_load();
             break;
         default:
             return false;
             break;
     }
     return false;
 }
is_waitTime_compatible_IJ()
bool pgrouting::vrp::Tw_node::is_waitTime_compatible_IJ (const Tw_node & I, double speed) const
Definition at line 112 of file tw_node.cpp.
References arrival_j_opens_i(), is_compatible_IJ(), and is_early_arrival().
Referenced by is_on_time().
{
     return
         is_compatible_IJ(I, speed)
         && is_early_arrival(arrival_j_opens_i(I, speed));
 }
opens()
double pgrouting::vrp::Tw_node::opens () const inline
Returns the opening time.
Definition at line 76 of file tw_node.h.
References m_opens.
Referenced by pgrouting::vrp::Fleet::add_vehicle(), arrival_j_opens_i(), pgrouting::vrp::Vehicle_node::evaluate(), is_delivery(), is_dump(), is_end(), is_load(), pgrouting::vrp::Vehicle::is_ok(), is_pickup(), is_start(), and pgrouting::vrp::Vehicle::Vehicle().
 {return m_opens;}
operator==()
bool pgrouting::vrp::Tw_node::operator== (const Tw_node & rhs) const
Definition at line 186 of file tw_node.cpp.
References pgrouting::Identifier::idx(), pgrouting::vrp::Pgr_pickDeliver::m_base_nodes, and pgrouting::vrp::PD_problem::problem.
Referenced by window_length().
{
     if (&other == this) return true;
     auto lhs = static_cast<const Node&>(
             *problem->m_base_nodes[idx()].get());
     auto rhs = static_cast<const Node&>(
             *problem->m_base_nodes[other.idx()].get());
     return lhs == rhs;
 }
order()
int64_t pgrouting::vrp::Tw_node::order () const inline
@ {
Returns the opening time.
Definition at line 73 of file tw_node.h.
References m_order.
 {return m_order;}
reset_id()
void pgrouting::Identifier::reset_id (int64_t _id) inherited
Definition at line 47 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by Tw_node().
{
     m_id = _id;
 }
service_time()
double pgrouting::vrp::Tw_node::service_time () const inline
Returns the service time for this node.
Definition at line 86 of file tw_node.h.
References m_service_time.
Referenced by pgrouting::vrp::Vehicle_node::arrival_i_arrives_j(), arrival_j_closes_i(), arrival_j_opens_i(), pgrouting::vrp::Vehicle::deltaTime(), pgrouting::vrp::Vehicle_node::evaluate(), is_delivery(), is_dump(), is_end(), is_load(), is_pickup(), is_start(), and pgrouting::vrp::operator<<().
 {return m_service_time;}
travel_time_to()
double pgrouting::vrp::Tw_node::travel_time_to (const Tw_node & other, double speed) const
time = distance / speed.
TODO(vicky) shall call Node or Dnode static cast won't work I think
Todo:
TODO evaluate with matrix also
Definition at line 40 of file tw_node.cpp.
References pgrouting::Identifier::idx(), pgrouting::vrp::Pgr_pickDeliver::m_base_nodes, pgassert, and pgrouting::vrp::PD_problem::problem.
Referenced by pgrouting::vrp::Vehicle_node::arrival_i_arrives_j(), arrival_j_closes_i(), arrival_j_opens_i(), pgrouting::vrp::Vehicle::deltaTime(), pgrouting::vrp::Vehicle_node::evaluate(), pgrouting::vrp::operator<<(), and window_length().
{
     auto from =  problem->m_base_nodes[idx()].get();
     auto destination = problem->m_base_nodes[to.idx()].get();
     pgassert(speed != 0);
     return from->distance(destination) / speed;
 }
type()
NodeType pgrouting::vrp::Tw_node::type () const inline
Returns the type of this node.
Definition at line 89 of file tw_node.h.
References m_type.
Referenced by is_on_time(), is_valid(), and type_str().
 {return m_type;}
type_str()
std::string pgrouting::vrp::Tw_node::type_str () const
Definition at line 119 of file tw_node.cpp.
References kDelivery, kDump, kEnd, kLoad, kPickup, kStart, and type().
Referenced by pgrouting::vrp::operator<<(), and window_length().
{
     switch (type()) {
         case kStart: return "START"; break;
         case kEnd: return "END"; break;
         case kDump: return "DUMP"; break;
         case kLoad: return "LOAD"; break;
         case kPickup: return "PICKUP"; break;
         case kDelivery: return "DELIVERY"; break;
         default: return "UNKNOWN";
     }
 }
window_length()
double pgrouting::vrp::Tw_node::window_length () const inline
Returns the length of time between the opening and closing.
Definition at line 92 of file tw_node.h.
References is_delivery(), is_dump(), is_end(), is_load(), is_pickup(), is_start(), m_closes, m_opens, operator<<, operator==(), travel_time_to(), and type_str().
 {return m_closes - m_opens;}
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const Tw_node & node) friend
Print the contents of a Twnode object.
Definition at line 272 of file tw_node.cpp.
Referenced by window_length().
{
     log << static_cast<const Node&>(
             *n.problem->m_base_nodes[n.idx()].get())
         << "[opens = " << n.m_opens
         << "\tcloses = " << n.m_closes
         << "\tservice = " << n.m_service_time
         << "\tdemand = " << n.m_demand
         << "\ttype = " << n.type_str()
         << "]"
         << "\n";
     return log;
 }
Member Data Documentation
m_closes
double pgrouting::vrp::Tw_node::m_closes private
closing time of the node
Definition at line 275 of file tw_node.h.
Referenced by closes(), is_late_arrival(), pgrouting::vrp::operator<<(), Tw_node(), and window_length().
m_demand
double pgrouting::vrp::Tw_node::m_demand private
The demand for the Node.
Definition at line 277 of file tw_node.h.
Referenced by demand(), pgrouting::vrp::operator<<(), and Tw_node().
m_opens
double pgrouting::vrp::Tw_node::m_opens private
opening time of the node
Definition at line 274 of file tw_node.h.
Referenced by is_early_arrival(), opens(), pgrouting::vrp::operator<<(), Tw_node(), and window_length().
m_order
int64_t pgrouting::vrp::Tw_node::m_order private
order to which it belongs
Definition at line 273 of file tw_node.h.
Referenced by order().
m_service_time
double pgrouting::vrp::Tw_node::m_service_time private
Definition at line 276 of file tw_node.h.
Referenced by pgrouting::vrp::operator<<(), service_time(), and Tw_node().
m_type
NodeType pgrouting::vrp::Tw_node::m_type private
The demand for the Node.
Definition at line 278 of file tw_node.h.
Referenced by arrival_j_closes_i(), arrival_j_opens_i(), is_compatible_IJ(), is_delivery(), is_dump(), is_end(), is_load(), is_pickup(), is_start(), Tw_node(), and type().
msg
Pgr_messages pgrouting::vrp::PD_problem::msg static inherited
Definition at line 48 of file pd_problem.h.
Referenced by pgrouting::vrp::Fleet::add_vehicle(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), pgrouting::vrp::Optimize::delete_empty_truck(), do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), pgrouting::vrp::Vehicle_pickDeliver::do_while_feasable(), pgrouting::vrp::Initial_solution::do_while_foo(), pgrouting::vrp::Pgr_pickDeliver::get_postgres_result(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Fleet::is_fleet_ok(), pgrouting::vrp::Optimize::move_reduce_cost(), pgrouting::vrp::Pgr_pickDeliver::nodesOK(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), pgrouting::vrp::Optimize::Optimize(), pgrouting::vrp::Pgr_pickDeliver::optimize(), pgrouting::vrp::PD_problem::PD_problem(), pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Optimize::save_if_best(), pgrouting::vrp::Solution::Solution(), pgrouting::vrp::Pgr_pickDeliver::solve(), pgrouting::vrp::Optimize::swap_order(), pgrouting::vrp::Optimize::swap_worse(), and pgrouting::vrp::Vehicle::Vehicle().
problem
Pgr_pickDeliver * pgrouting::vrp::PD_problem::problem static protected inherited
Definition at line 51 of file pd_problem.h.
Referenced by pgrouting::vrp::PD_Orders::add_order(), pgrouting::vrp::Fleet::add_vehicle(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), pgrouting::vrp::Dnode::distance(), pgrouting::vrp::operator<<(), operator==(), and travel_time_to().
The documentation for this class was generated from the following files:
tw_node.h
tw_node.cpp