PGROUTING: Pgr_ksp< G > Class Template Reference
Pgr_ksp< G > Class Template Reference
#include "pgr_ksp.hpp"
Classes
class compPaths
Public Member Functions
void clear ()
std::deque< Path > Yen (G &graph, int64_t source, int64_t target, int K, bool heap_paths)
Private Member Functions
void executeYen (G &graph, int top_k)
the actual algorithm
Auxiliary function for yen's algorithm
void getFirstSolution (G &graph)
Performs the first Dijkstra of the algorithm.
void doNextCycle (G &graph)
Performs the next cycle of the algorithm.
void removeVertices (G &graph, const Path &path)
stores in subPath the first i elements of path
members
typedef G::V V
typedef std::set< Path, compPaths > pSet
V v_source
source descriptor
V v_target
target descriptor
int64_t m_start
source id
int64_t m_end
target id
Path curr_result_path
storage for the current result
pSet m_ResultSet
ordered set of shortest paths
pSet m_Heap
the heap
std::ostringstream log
Detailed Description
template<class G>
class Pgr_ksp< G >
Definition at line 41 of file pgr_ksp.hpp.
Member Typedef Documentation
pSet
template<class G> typedef std::set<Path, compPaths> Pgr_ksp< G >::pSet private
Definition at line 121 of file pgr_ksp.hpp.
V
template<class G> typedef G::V Pgr_ksp< G >::V private
Definition at line 113 of file pgr_ksp.hpp.
Member Function Documentation
clear()
template<class G > void Pgr_ksp< G >::clear ()
Definition at line 130 of file pgr_ksp.hpp.
References Pgr_ksp< G >::m_Heap.
Referenced by Pgr_ksp< G >::executeYen().
{
         m_Heap.clear();
 }
doNextCycle()
template<class G > void Pgr_ksp< G >::doNextCycle (G & graph) private
Performs the next cycle of the algorithm.
Definition at line 207 of file pgr_ksp.hpp.
References Path::appendPath(), Pgr_ksp< G >::curr_result_path, Pgr_dijkstra< G >::dijkstra(), Path::getSubpath(), Pgr_ksp< G >::m_end, Pgr_ksp< G >::m_Heap, Pgr_ksp< G >::m_ResultSet, Pgr_ksp< G >::removeVertices(), and Path::size().
Referenced by Pgr_ksp< G >::executeYen(), and Pgr_ksp< G >::compPaths::operator()().
{
     int64_t spurNodeId;
     for (unsigned int i = 0; i < curr_result_path.size(); ++i) {
         spurNodeId = curr_result_path[i].node;
         auto rootPath = curr_result_path.getSubpath(i);
         for (const auto &path : m_ResultSet) {
             if (path.isEqual(rootPath)) {
                 if (path.size() > i + 1) {
                     graph.disconnect_edge(path[i].node,     // from
                             path[i + 1].node);  // to
                 }
             }
         }
         removeVertices(graph, rootPath);
         Pgr_dijkstra< G > fn_dijkstra;
         auto spurPath = fn_dijkstra.dijkstra(graph, spurNodeId, m_end);
         if (spurPath.size() > 0) {
             rootPath.appendPath(spurPath);
             m_Heap.insert(rootPath);
         }
         graph.restore_graph();
     }
 }
executeYen()
template<class G > void Pgr_ksp< G >::executeYen (G & graph, int top_k) private
the actual algorithm
Definition at line 240 of file pgr_ksp.hpp.
References Pgr_ksp< G >::clear(), Pgr_ksp< G >::curr_result_path, Pgr_ksp< G >::doNextCycle(), Pgr_ksp< G >::getFirstSolution(), Pgr_ksp< G >::log, Pgr_ksp< G >::m_Heap, and Pgr_ksp< G >::m_ResultSet.
Referenced by Pgr_ksp< G >::compPaths::operator()(), and Pgr_ksp< G >::Yen().
{
     clear();
     getFirstSolution(graph);
     if (m_ResultSet.size() == 0) return;  // no path found
     while (m_ResultSet.size() < (unsigned int) K) {
         doNextCycle(graph);
         if (m_Heap.empty()) break;
         curr_result_path = *m_Heap.begin();
         m_ResultSet.insert(curr_result_path);
         m_Heap.erase(m_Heap.begin());
         /*
          * without the next line withpointsKSP hungs with:
          *  c++ 4.6
          *  Debug mode
          */
 #ifndef NDEBUG
         log << "end of while heap size" << m_Heap.size();
 #endif
     }
 }
getFirstSolution()
template<class G > void Pgr_ksp< G >::getFirstSolution (G & graph) private
Performs the first Dijkstra of the algorithm.
Definition at line 135 of file pgr_ksp.hpp.
References Pgr_ksp< G >::curr_result_path, Pgr_dijkstra< G >::dijkstra(), Path::empty(), Pgr_ksp< G >::m_end, Pgr_ksp< G >::m_ResultSet, and Pgr_ksp< G >::m_start.
Referenced by Pgr_ksp< G >::executeYen(), and Pgr_ksp< G >::compPaths::operator()().
{
      Path path;
      Pgr_dijkstra< G > fn_dijkstra;
      path = fn_dijkstra.dijkstra(graph, m_start, m_end);
      if (path.empty()) return;
      curr_result_path = path;
      m_ResultSet.insert(curr_result_path);
 }
removeVertices()
template<class G > void Pgr_ksp< G >::removeVertices (G & graph, const Path & path) private
stores in subPath the first i elements of path
Definition at line 201 of file pgr_ksp.hpp.
Referenced by Pgr_ksp< G >::doNextCycle(), and Pgr_ksp< G >::compPaths::operator()().
{
     for (const auto &e : subpath)
         graph.disconnect_vertex(e.node);
 }
Yen()
template<class G > std::deque< Path > Pgr_ksp< G >::Yen (G & graph, int64_t source, int64_t target, int K, bool heap_paths)
Definition at line 148 of file pgr_ksp.hpp.
References Pgr_ksp< G >::executeYen(), Pgr_ksp< G >::m_end, Pgr_ksp< G >::m_Heap, Pgr_ksp< G >::m_ResultSet, Pgr_ksp< G >::m_start, Path::size(), Pgr_ksp< G >::v_source, and Pgr_ksp< G >::v_target.
Referenced by do_pgr_ksp(), and do_pgr_withPointsKsp().
{
     /*
      * No path: already in destination
      */
     if ((start_vertex == end_vertex) || (K == 0)) {
         return std::deque<Path>();
     }
     /*
      * no path: disconnected vertices
      */
     if (!graph.has_vertex(start_vertex)
                 || !graph.has_vertex(end_vertex)) {
         return std::deque<Path>();
     }
     m_ResultSet.clear();
     m_Heap.clear();
     v_source = graph.get_V(start_vertex);
     v_target = graph.get_V(end_vertex);
     m_start = start_vertex;
     m_end = end_vertex;
     executeYen(graph, K);
     while (!m_ResultSet.empty()) {
         m_Heap.insert(*m_ResultSet.begin());
         m_ResultSet.erase(m_ResultSet.begin());
     }
     std::deque<Path> l_ResultList(m_Heap.begin(), m_Heap.end());
     std::stable_sort(l_ResultList.begin(), l_ResultList.end(),
             [](const Path &left, const Path &right) -> bool {
             for (size_t i = 0;
                 i < (std::min)(left.size(), right.size());
                 ++i) {
             if (left[i].node < right[i].node) return true;
             if (left[i].node > right[i].node) return false;
             }
             return false;
             });
     std::stable_sort(l_ResultList.begin(), l_ResultList.end(),
             [](const Path &left, const Path &right) {
             return left.size() < right.size();});
     if (!heap_paths && l_ResultList.size() > (size_t) K)
         l_ResultList.resize(K);
     return l_ResultList;
 }
Member Data Documentation
curr_result_path
template<class G> Path Pgr_ksp< G >::curr_result_path private
storage for the current result
Definition at line 119 of file pgr_ksp.hpp.
Referenced by Pgr_ksp< G >::doNextCycle(), Pgr_ksp< G >::executeYen(), and Pgr_ksp< G >::getFirstSolution().
log
template<class G> std::ostringstream Pgr_ksp< G >::log private
Definition at line 125 of file pgr_ksp.hpp.
Referenced by Pgr_ksp< G >::executeYen().
m_end
template<class G> int64_t Pgr_ksp< G >::m_end private
target id
Definition at line 117 of file pgr_ksp.hpp.
Referenced by Pgr_ksp< G >::doNextCycle(), Pgr_ksp< G >::getFirstSolution(), and Pgr_ksp< G >::Yen().
m_Heap
template<class G> pSet Pgr_ksp< G >::m_Heap private
the heap
Definition at line 123 of file pgr_ksp.hpp.
Referenced by Pgr_ksp< G >::clear(), Pgr_ksp< G >::doNextCycle(), Pgr_ksp< G >::executeYen(), and Pgr_ksp< G >::Yen().
m_ResultSet
template<class G> pSet Pgr_ksp< G >::m_ResultSet private
ordered set of shortest paths
Definition at line 122 of file pgr_ksp.hpp.
Referenced by Pgr_ksp< G >::doNextCycle(), Pgr_ksp< G >::executeYen(), Pgr_ksp< G >::getFirstSolution(), and Pgr_ksp< G >::Yen().
m_start
template<class G> int64_t Pgr_ksp< G >::m_start private
source id
Definition at line 116 of file pgr_ksp.hpp.
Referenced by Pgr_ksp< G >::getFirstSolution(), and Pgr_ksp< G >::Yen().
v_source
template<class G> V Pgr_ksp< G >::v_source private
source descriptor
Definition at line 114 of file pgr_ksp.hpp.
Referenced by Pgr_ksp< G >::Yen().
v_target
template<class G> V Pgr_ksp< G >::v_target private
target descriptor
Definition at line 115 of file pgr_ksp.hpp.
Referenced by Pgr_ksp< G >::Yen().
The documentation for this class was generated from the following file:
pgr_ksp.hpp