PGROUTING: pgrouting::tsp::eucledianDmatrix Class Reference
pgrouting::tsp::eucledianDmatrix Class Reference
#include "eucledianDmatrix.h"
Public Member Functions
eucledianDmatrix ()=default
eucledianDmatrix (const std::vector< Coordinate_t > &data_coordinates)
double comparable_distance (size_t i, size_t j) const
double distance (size_t i, size_t j) const
int64_t get_id (size_t idx) const
idx -> original id
size_t get_index (int64_t id) const
original id -> idx
const std::vector< double > get_row (size_t idx) const
returns a row of distances
bool has_id (int64_t id) const
original id -> true
bool has_no_infinity () const
bool is_symmetric () const
bool obeys_triangle_inequality () const
void set (size_t i, size_t j, double dist)
sets a special value for the distance(i,j)
size_t size () const
|idx|
double tourCost (const Tour &tour) const
tour evaluation
Protected Member Functions
void set_ids ()
Protected Attributes
std::vector< int64_t > ids
Private Attributes
size_t column
std::vector< Coordinate_t > coordinates
size_t row
double special_distance
Friends
std::ostream & operator<< (std::ostream &log, const eucledianDmatrix &matrix)
Detailed Description
Definition at line 40 of file eucledianDmatrix.h.
Constructor & Destructor Documentation
eucledianDmatrix() [1/2]
pgrouting::tsp::eucledianDmatrix::eucledianDmatrix () default
eucledianDmatrix() [2/2]
pgrouting::tsp::eucledianDmatrix::eucledianDmatrix (const std::vector< Coordinate_t > & data_coordinates) explicit
Definition at line 115 of file eucledianDmatrix.cpp.
References coordinates, Coordinate_t::id, and set_ids().
     : coordinates(data_coordinates) {
         set_ids();
         std::sort(coordinates.begin(), coordinates.end(),
                 [](const Coordinate_t &lhs, const Coordinate_t &rhs)
                 {return lhs.id < rhs.id;});
     }
Member Function Documentation
comparable_distance()
double pgrouting::tsp::eucledianDmatrix::comparable_distance (size_t i, size_t j) const
Definition at line 55 of file eucledianDmatrix.cpp.
References column, coordinates, row, and special_distance.
Referenced by distance(), and size().
{
     if (special_distance >= 0 &&
             ((row == i && column == j)
              ||(row == j && column == i))) {
         return special_distance * special_distance;
     }
     auto dx = coordinates[i].x - coordinates[j].x;
     auto dy = coordinates[i].y - coordinates[j].y;
     return dx * dx + dy * dy;
 }
distance()
double pgrouting::tsp::eucledianDmatrix::distance (size_t i, size_t j) const
Definition at line 67 of file eucledianDmatrix.cpp.
References column, comparable_distance(), row, and special_distance.
Referenced by do_pgr_eucledianTSP(), get_row(), size(), and tourCost().
{
     if (special_distance >= 0 &&
             ((row == i && column == j)
              ||(row == j && column == i))) {
         return special_distance;
     }
     if (i == j) return 0;
     return std::sqrt(comparable_distance(i, j));
 }
get_id()
int64_t pgrouting::tsp::eucledianDmatrix::get_id (size_t idx) const
idx -> original id
Parameters
[in] idx - index (i-th coordinate)
Returns
the original id corresponding to idx
Definition at line 108 of file eucledianDmatrix.cpp.
References ids.
Referenced by do_pgr_eucledianTSP(), and set().
{
     return ids[id];
 }
get_index()
size_t pgrouting::tsp::eucledianDmatrix::get_index (int64_t id) const
original id -> idx
Parameters
[in] id - original id
Returns
idx index of the id in the distance table
Definition at line 102 of file eucledianDmatrix.cpp.
References ids.
Referenced by do_pgr_eucledianTSP(), and set().
{
     auto pos = std::lower_bound(ids.begin(), ids.end(), id);
     return pos - ids.begin();
 }
get_row()
const std::vector< double > pgrouting::tsp::eucledianDmatrix::get_row (size_t idx) const
returns a row of distances
Parameters
[in] idx row index
Returns
distances from idx to all other coordinates
Definition at line 42 of file eucledianDmatrix.cpp.
References distance(), ids, and pgassert.
Referenced by size().
{
     std::vector<double> result;
     for (size_t j = 0; j < ids.size(); ++j) {
         result.push_back(distance(i, j));
     }
     pgassert(result.size() == ids.size());
     return result;
 }
has_id()
bool pgrouting::tsp::eucledianDmatrix::has_id (int64_t id) const
original id -> true
Parameters
[in] id original id
Returns
true if id is in the distance table
Definition at line 96 of file eucledianDmatrix.cpp.
References ids.
Referenced by do_pgr_eucledianTSP(), and set().
{
     auto pos = std::lower_bound(ids.begin(), ids.end(), id);
     return *pos == id;
 }
has_no_infinity()
bool pgrouting::tsp::eucledianDmatrix::has_no_infinity () const
Definition at line 139 of file eucledianDmatrix.cpp.
{
     return true;
 }
is_symmetric()
bool pgrouting::tsp::eucledianDmatrix::is_symmetric () const
Definition at line 149 of file eucledianDmatrix.cpp.
{
     return true;
 }
obeys_triangle_inequality()
bool pgrouting::tsp::eucledianDmatrix::obeys_triangle_inequality () const
Definition at line 144 of file eucledianDmatrix.cpp.
{
     return true;
 }
set()
void pgrouting::tsp::eucledianDmatrix::set (size_t i, size_t j, double dist) inline
sets a special value for the distance(i,j)
Parameters
[in] i - index in matrix
[in] j - index in matrix
[in] dist - distance from i to j & from j to i
Definition at line 57 of file eucledianDmatrix.h.
References column, get_id(), get_index(), has_id(), row, and special_distance.
Referenced by do_pgr_eucledianTSP().
{
         row = i; column = j; special_distance = dist;}
set_ids()
void pgrouting::tsp::eucledianDmatrix::set_ids () protected
Definition at line 125 of file eucledianDmatrix.cpp.
References coordinates, ids, and pgassertwm.
Referenced by eucledianDmatrix(), and size().
{
     ids.reserve(coordinates.size());
     for (const auto &data : coordinates) {
         ids.push_back(data.id);
     }
     std::sort(ids.begin(), ids.end());
 #ifndef NDEBUG
     auto total = ids.size();
 #endif
     ids.erase(std::unique(ids.begin(), ids.end()), ids.end());
     pgassertwm(total == ids.size(), "Duplicated id found");
 }
size()
size_t pgrouting::tsp::eucledianDmatrix::size () const inline
|idx|
Returns
the total number of coordinates
Definition at line 86 of file eucledianDmatrix.h.
References comparable_distance(), distance(), get_row(), ids, operator<<, set_ids(), and tourCost().
Referenced by do_pgr_eucledianTSP().
 {return ids.size();}
tourCost()
double pgrouting::tsp::eucledianDmatrix::tourCost (const Tour & tour) const
tour evaluation
Parameters
[in] tour
Returns
total cost of traversing the tour
Definition at line 78 of file eucledianDmatrix.cpp.
References pgrouting::tsp::Tour::cities, and distance().
Referenced by do_pgr_eucledianTSP(), and size().
{
     double total_cost(0);
     if (tour.cities.empty()) return total_cost;
     auto prev_id = tour.cities.front();
     for (const auto &id : tour.cities) {
         if (id == tour.cities.front()) continue;
         total_cost += distance(prev_id, id);
         prev_id = id;
     }
     total_cost += distance(prev_id, tour.cities.front());
     return total_cost;
 }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const eucledianDmatrix & matrix) friend
Definition at line 153 of file eucledianDmatrix.cpp.
Referenced by size().
{
     for (const auto id : matrix.ids) {
         log << "\t" << id;
     }
     log << "\n";
     for (const auto row : matrix.coordinates) {
         log << row.id << "(" << row.x << "," << row.y << ")\n";
     }
     return log;
 }
Member Data Documentation
column
size_t pgrouting::tsp::eucledianDmatrix::column private
Definition at line 117 of file eucledianDmatrix.h.
Referenced by comparable_distance(), distance(), and set().
coordinates
std::vector< Coordinate_t > pgrouting::tsp::eucledianDmatrix::coordinates private
Definition at line 115 of file eucledianDmatrix.h.
Referenced by comparable_distance(), eucledianDmatrix(), pgrouting::tsp::operator<<(), and set_ids().
ids
std::vector<int64_t> pgrouting::tsp::eucledianDmatrix::ids protected
Definition at line 112 of file eucledianDmatrix.h.
Referenced by get_id(), get_index(), get_row(), has_id(), pgrouting::tsp::operator<<(), set_ids(), and size().
row
size_t pgrouting::tsp::eucledianDmatrix::row private
Definition at line 116 of file eucledianDmatrix.h.
Referenced by comparable_distance(), distance(), pgrouting::tsp::operator<<(), and set().
special_distance
double pgrouting::tsp::eucledianDmatrix::special_distance private
Definition at line 118 of file eucledianDmatrix.h.
Referenced by comparable_distance(), distance(), and set().
The documentation for this class was generated from the following files:
eucledianDmatrix.h
eucledianDmatrix.cpp