PGROUTING: pgrouting::vrp::Base_node Class Reference
pgrouting::vrp::Base_node Class Reference abstract
The Base_node class defines the operations that can be performed in a 2D node.
#include "base_node.h"
Public Member Functions
Base_node ()=default
Base_node (size_t, int64_t)
int64_t id () const
size_t idx () const
void reset_id (int64_t)
to be or not to be
virtual bool operator== (const Base_node &rhs) const
distance
virtual double distance (const Base_node *node) const =0
Private Member Functions
virtual void print (std::ostream &os) const
Friends
std::ostream & operator<< (std::ostream &log, const Base_node &node)
Detailed Description
The Base_node class defines the operations that can be performed in a 2D node.
A Base_node is an identifier of a Node or Dnode.
Definition at line 47 of file base_node.h.
Constructor & Destructor Documentation
Base_node() [1/2]
pgrouting::vrp::Base_node::Base_node () default
Base_node() [2/2]
pgrouting::vrp::Base_node::Base_node (size_t _idx, int64_t _id)
Definition at line 43 of file base_node.cpp.
     : Identifier(_idx, _id) {
     }
Member Function Documentation
distance()
virtual double pgrouting::vrp::Base_node::distance (const Base_node * node) const pure virtual
Implemented in pgrouting::vrp::Node, and pgrouting::vrp::Dnode.
id()
int64_t pgrouting::Identifier::id () const inherited
Definition at line 42 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Dnode::distance(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::vrp::Vehicle::is_phony(), pgrouting::vrp::Optimize::move_reduce_cost(), pgrouting::vrp::operator<<(), pgrouting::operator<<(), operator==(), pgrouting::vrp::Node::operator==(), pgrouting::vrp::Node::print(), print(), pgrouting::vrp::Vehicle::tau(), and pgrouting::vrp::Vehicle::Vehicle().
                      {
     return m_id;
 }
idx()
size_t pgrouting::Identifier::idx () const inherited
Definition at line 37 of file identifier.cpp.
References pgrouting::Identifier::m_idx.
Referenced by pgrouting::vrp::Vehicle_pickDeliver::erase(), pgrouting::vrp::Vehicle::erase(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Vehicle_pickDeliver::has_order(), pgrouting::vrp::Vehicle_pickDeliver::insert(), pgrouting::vrp::Vehicle::insert(), pgrouting::vrp::operator<<(), pgrouting::operator<<(), operator==(), pgrouting::vrp::Node::operator==(), pgrouting::vrp::Tw_node::operator==(), pgrouting::vrp::Node::print(), print(), pgrouting::vrp::Vehicle_pickDeliver::push_back(), pgrouting::vrp::Vehicle_pickDeliver::push_front(), pgrouting::vrp::Order::set_compatibles(), pgrouting::vrp::Solution::sort_by_id(), pgrouting::vrp::Optimize::swap_worse(), pgrouting::vrp::Vehicle::tau(), pgrouting::vrp::Tw_node::travel_time_to(), and pgrouting::vrp::Vehicle::Vehicle().
                       {
     return m_idx;
 }
operator==()
bool pgrouting::vrp::Base_node::operator== (const Base_node & rhs) const virtual
Definition at line 48 of file base_node.cpp.
References pgrouting::Identifier::id(), and pgrouting::Identifier::idx().
{
     if (&rhs == this) return true;
     return
         (idx() == rhs.idx())
          && (id() == rhs.id());
 }
print()
void pgrouting::vrp::Base_node::print (std::ostream & os) const private virtual
Reimplemented in pgrouting::vrp::Node.
Definition at line 38 of file base_node.cpp.
References pgrouting::Identifier::id(), and pgrouting::Identifier::idx().
Referenced by pgrouting::vrp::operator<<().
{
     os << id()
         << "(" << idx() << ")";
 }
reset_id()
void pgrouting::Identifier::reset_id (int64_t _id) inherited
Definition at line 47 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Tw_node::Tw_node().
{
     m_id = _id;
 }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const Base_node & node) friend
Definition at line 32 of file base_node.cpp.
{
     node.print(log);
     return log;
 }
The documentation for this class was generated from the following files:
base_node.h
base_node.cpp