PGROUTING: Pgr_allpairs< G > Class Template Reference
Pgr_allpairs< G > Class Template Reference
#include "pgr_allpairs.hpp"
Classes
struct inf_plus
Public Member Functions
void floydWarshall (G &graph, size_t &result_tuple_count, Matrix_cell_t **postgres_rows)
void floydWarshall (G &graph, std::vector< Matrix_cell_t > &rows)
void johnson (G &graph, size_t &result_tuple_count, Matrix_cell_t **postgres_rows)
void johnson (G &graph, std::vector< Matrix_cell_t > &rows)
Private Member Functions
size_t count_rows (const G &graph, const std::vector< std::vector< double > > &matrix) const
void make_matrix (size_t v_size, std::vector< std::vector< double >> &matrix) const
void make_result (const G &graph, const std::vector< std::vector< double > > &matrix, size_t &result_tuple_count, Matrix_cell_t **postgres_rows) const
void make_result (G &graph, std::vector< std::vector< double > > &matrix, std::vector< Matrix_cell_t > &rows)
Detailed Description
template<class G>
class Pgr_allpairs< G >
Definition at line 51 of file pgr_allpairs.hpp.
Member Function Documentation
count_rows()
template<class G> size_t Pgr_allpairs< G >::count_rows (const G & graph, const std::vector< std::vector< double > > & matrix) const inline private
Definition at line 200 of file pgr_allpairs.hpp.
Referenced by Pgr_allpairs< G >::make_result().
{
          size_t result_tuple_count = 0;
          for (size_t i = 0; i < graph.num_vertices(); i++) {
              for (size_t j = 0; j < graph.num_vertices(); j++) {
                  if (i == j) continue;
                  if (matrix[i][j] != (std::numeric_limits<double>::max)()) {
                      result_tuple_count++;
                  }  // if
              }  // for j
          }  // for i
          return result_tuple_count;
      }
floydWarshall() [1/2]
template<class G> void Pgr_allpairs< G >::floydWarshall (G & graph, size_t & result_tuple_count, Matrix_cell_t ** postgres_rows) inline
Definition at line 95 of file pgr_allpairs.hpp.
References pgrouting::Basic_edge::cost, Pgr_allpairs< G >::make_matrix(), and Pgr_allpairs< G >::make_result().
Referenced by pgr_floydWarshall().
{
          std::vector< std::vector<double>> matrix;
          make_matrix(graph.num_vertices(), matrix);
          inf_plus<double> combine;
          boost::floyd_warshall_all_pairs_shortest_paths(
                  graph.graph,
                  matrix,
                  weight_map(get(&pgrouting::Basic_edge::cost, graph.graph)).
                  distance_combine(combine).
                  distance_inf((std::numeric_limits<double>::max)()).
                  distance_zero(0));
          make_result(graph, matrix, result_tuple_count, postgres_rows);
      }
floydWarshall() [2/2]
template<class G> void Pgr_allpairs< G >::floydWarshall (G & graph, std::vector< Matrix_cell_t > & rows) inline
Definition at line 113 of file pgr_allpairs.hpp.
References pgrouting::Basic_edge::cost, Pgr_allpairs< G >::make_matrix(), and Pgr_allpairs< G >::make_result().
{
          std::vector< std::vector<double>> matrix;
          make_matrix(graph.num_vertices(), matrix);
          inf_plus<double> combine;
          boost::floyd_warshall_all_pairs_shortest_paths(
                  graph.graph,
                  matrix,
                  weight_map(get(&pgrouting::Basic_edge::cost, graph.graph)).
                  distance_combine(combine).
                  distance_inf((std::numeric_limits<double>::max)()).
                  distance_zero(0));
          make_result(graph, matrix, rows);
      }
johnson() [1/2]
template<class G> void Pgr_allpairs< G >::johnson (G & graph, size_t & result_tuple_count, Matrix_cell_t ** postgres_rows) inline
Definition at line 130 of file pgr_allpairs.hpp.
References pgrouting::Basic_edge::cost, Pgr_allpairs< G >::make_matrix(), and Pgr_allpairs< G >::make_result().
Referenced by pgr_johnson().
{
          std::vector< std::vector<double>> matrix;
          make_matrix(graph.num_vertices(), matrix);
          inf_plus<double> combine;
          boost::johnson_all_pairs_shortest_paths(
                  graph.graph,
                  matrix,
                  weight_map(get(&pgrouting::Basic_edge::cost, graph.graph)).
                  distance_combine(combine).
                  distance_inf((std::numeric_limits<double>::max)()).
                  distance_zero(0));
          make_result(graph, matrix, result_tuple_count, postgres_rows);
      }
johnson() [2/2]
template<class G> void Pgr_allpairs< G >::johnson (G & graph, std::vector< Matrix_cell_t > & rows) inline
Definition at line 149 of file pgr_allpairs.hpp.
References pgrouting::Basic_edge::cost, Pgr_allpairs< G >::make_matrix(), and Pgr_allpairs< G >::make_result().
{
          std::vector< std::vector<double>> matrix;
          make_matrix(graph.num_vertices(), matrix);
          inf_plus<double> combine;
          boost::johnson_all_pairs_shortest_paths(
                  graph.graph,
                  matrix,
                  weight_map(get(&pgrouting::Basic_edge::cost, graph.graph)).
                  distance_combine(combine).
                  distance_inf((std::numeric_limits<double>::max)()).
                  distance_zero(0));
          make_result(graph, matrix, rows);
      }
make_matrix()
template<class G> void Pgr_allpairs< G >::make_matrix (size_t v_size, std::vector< std::vector< double >> & matrix) const inline private
Definition at line 167 of file pgr_allpairs.hpp.
Referenced by Pgr_allpairs< G >::floydWarshall(), and Pgr_allpairs< G >::johnson().
{
          // TODO(vicky) in one step
          matrix.resize(v_size);
          for (size_t i=0; i < v_size; i++)
              matrix[i].resize(v_size);
      }
make_result() [1/2]
template<class G> void Pgr_allpairs< G >::make_result (const G & graph, const std::vector< std::vector< double > > & matrix, size_t & result_tuple_count, Matrix_cell_t ** postgres_rows) const inline private
Definition at line 176 of file pgr_allpairs.hpp.
References Pgr_allpairs< G >::count_rows(), and pgr_alloc().
Referenced by Pgr_allpairs< G >::floydWarshall(), and Pgr_allpairs< G >::johnson().
{
          result_tuple_count = count_rows(graph, matrix);
          *postgres_rows = pgr_alloc(result_tuple_count, (*postgres_rows));
          size_t seq = 0;
          for (typename G::V v_i = 0; v_i < graph.num_vertices(); v_i++) {
              for (typename G::V v_j = 0; v_j < graph.num_vertices(); v_j++) {
                  if (v_i == v_j) continue;
                  if (matrix[v_i][v_j] != (std::numeric_limits<double>::max)()) {
                      (*postgres_rows)[seq].from_vid = graph[v_i].id;
                      (*postgres_rows)[seq].to_vid = graph[v_j].id;
                      (*postgres_rows)[seq].cost =  matrix[v_i][v_j];
                      seq++;
                  }  // if
              }  // for j
          }  // for i
      }
make_result() [2/2]
template<class G> void Pgr_allpairs< G >::make_result (G & graph, std::vector< std::vector< double > > & matrix, std::vector< Matrix_cell_t > & rows) inline private
Definition at line 215 of file pgr_allpairs.hpp.
References Pgr_allpairs< G >::count_rows().
{
          size_t count = count_rows(graph, matrix);
          rows.resize(count);
          size_t seq = 0;
          for (typename G::V v_i = 0; v_i < graph.num_vertices(); v_i++) {
              for (typename G::V v_j = 0; v_j < graph.num_vertices(); v_j++) {
                  if (matrix[v_i][v_j] != (std::numeric_limits<double>::max)()) {
                      rows[seq] =
                      {graph[v_i].id, graph[v_j].id, matrix[v_i][v_j]};
                      seq++;
                  }  // if
              }  // for j
          }  // for i
      }
The documentation for this class was generated from the following file:
pgr_allpairs.hpp