PGROUTING: Pgr_dijkstraTRSP< G > Class Template Reference
Pgr_dijkstraTRSP< G > Class Template Reference
#include "pgr_dijkstraTRSP.hpp"
Public Member Functions
void clear ()
Path dijkstraTRSP (G &graph, const std::vector< Restriction > &restrictions, const std::vector< pgr_edge_t > &edges, int64_t source, int64_t target, bool only_cost, bool strict)
Public Attributes
std::ostringstream log
Private Types
typedef G::V V
Private Member Functions
void executeDijkstraTRSP (G &graph)
void getDijkstraSolution (G &graph)
bool has_a_restriction (int64_t edge, int64_t index)
bool has_restriction ()
Private Attributes
Path curr_result_path
std::vector< int64_t > m_edges_in_path
int64_t m_end
bool m_only_cost
std::vector< Restriction > m_restrictions
int64_t m_start
bool m_strict
V v_source
V v_target
Detailed Description
template<class G>
class Pgr_dijkstraTRSP< G >
Definition at line 44 of file pgr_dijkstraTRSP.hpp.
Member Typedef Documentation
V
template<class G> typedef G::V Pgr_dijkstraTRSP< G >::V private
Definition at line 63 of file pgr_dijkstraTRSP.hpp.
Member Function Documentation
clear()
template<class G > void Pgr_dijkstraTRSP< G >::clear ()
Definition at line 80 of file pgr_dijkstraTRSP.hpp.
Referenced by Pgr_dijkstraTRSP< G >::executeDijkstraTRSP().
{
 }
dijkstraTRSP()
template<class G > Path Pgr_dijkstraTRSP< G >::dijkstraTRSP (G & graph, const std::vector< Restriction > & restrictions, const std::vector< pgr_edge_t > & edges, int64_t source, int64_t target, bool only_cost, bool strict)
Definition at line 85 of file pgr_dijkstraTRSP.hpp.
References Pgr_dijkstraTRSP< G >::curr_result_path, DIRECTED, Pgr_dijkstraTRSP< G >::executeDijkstraTRSP(), Pgr_dijkstraTRSP< G >::log, Pgr_dijkstraTRSP< G >::m_end, Pgr_dijkstraTRSP< G >::m_only_cost, Pgr_dijkstraTRSP< G >::m_restrictions, Pgr_dijkstraTRSP< G >::m_start, Pgr_dijkstraTRSP< G >::m_strict, Path::size(), UNDIRECTED, Pgr_dijkstraTRSP< G >::v_source, and Pgr_dijkstraTRSP< G >::v_target.
Referenced by pgr_dijkstraTRSP().
                      {
     if (start_vertex == end_vertex)
         return Path();
     if (!graph.has_vertex(start_vertex) || !graph.has_vertex(end_vertex))
         return Path();
     m_only_cost = only_cost;
     v_source = graph.get_V(start_vertex);
     v_target = graph.get_V(end_vertex);
     m_start = start_vertex;
     m_end = end_vertex;
     m_restrictions = restrictions;
     m_strict = strict;
     executeDijkstraTRSP(graph);
     if (curr_result_path.size() || graph.m_gType == UNDIRECTED)
         return curr_result_path;
 #if 0
     pgrouting::LinearDirectedGraph line(DIRECTED);
     line.insert_vertices(edges);
     auto line_graph_edges = line.transform(graph);
     log << "\nGraph before removing restrictions\n" << line << "\n";
     auto remaining_restrictions = line.remove_restricted_edges(m_restrictions);
     log << "\n Graph after removing restrictions\n" << line << "\n";
     log << line.log.str().c_str() << "\n\n\n";
     line.create_virtual_vertices();
     log << line << "\n";
 #endif
     return curr_result_path;
 }
executeDijkstraTRSP()
template<class G > void Pgr_dijkstraTRSP< G >::executeDijkstraTRSP (G & graph) private
Definition at line 189 of file pgr_dijkstraTRSP.hpp.
References Pgr_dijkstraTRSP< G >::clear(), Pgr_dijkstraTRSP< G >::curr_result_path, Pgr_dijkstraTRSP< G >::getDijkstraSolution(), Pgr_dijkstraTRSP< G >::has_restriction(), Pgr_dijkstraTRSP< G >::log, and Pgr_dijkstraTRSP< G >::m_edges_in_path.
Referenced by Pgr_dijkstraTRSP< G >::dijkstraTRSP().
{
     clear();
     getDijkstraSolution(graph);
     log << curr_result_path;
     for (auto &path : curr_result_path) {
         m_edges_in_path.push_back(path.edge);
     }
     while (m_edges_in_path.size() && m_edges_in_path.back() == -1) {
         m_edges_in_path.pop_back();
     }
     log << "Edges in m_edges_in_path:-------------------\n";
     for (auto &it : m_edges_in_path) log << it << "\n";
     log << "---------------------------------------------\n";
     bool sol = has_restriction();
     log << "Result of valid solution: " << sol << "\n";
     if (sol) curr_result_path = Path();
 }
getDijkstraSolution()
template<class G > void Pgr_dijkstraTRSP< G >::getDijkstraSolution (G & graph) private
Definition at line 127 of file pgr_dijkstraTRSP.hpp.
References Pgr_dijkstraTRSP< G >::curr_result_path, Pgr_dijkstra< G >::dijkstra(), Path::empty(), Pgr_dijkstraTRSP< G >::m_end, and Pgr_dijkstraTRSP< G >::m_start.
Referenced by Pgr_dijkstraTRSP< G >::executeDijkstraTRSP().
{
      Path path;
      Pgr_dijkstra< G > fn_dijkstra;
      path = fn_dijkstra.dijkstra(graph, m_start, m_end);
      if (path.empty()) return;
      curr_result_path = path;
 }
has_a_restriction()
template<class G > bool Pgr_dijkstraTRSP< G >::has_a_restriction (int64_t edge, int64_t index) private
Definition at line 138 of file pgr_dijkstraTRSP.hpp.
References Pgr_dijkstraTRSP< G >::log, Pgr_dijkstraTRSP< G >::m_edges_in_path, Pgr_dijkstraTRSP< G >::m_restrictions, and Restriction::restrict_edges().
Referenced by Pgr_dijkstraTRSP< G >::has_restriction().
{
     auto lower_bound_cmp = [](const Restriction& r, const int64_t& target) {
         return r.restrict_edges()[0] < target;
     };
     auto edge_index = std::lower_bound(m_restrictions.begin(),
         m_restrictions.end(), edge, lower_bound_cmp) - m_restrictions.begin();
     log << "\nResult generated from lower_bound\n";
     while (edge_index < (int64_t)m_restrictions.size()) {
         auto r_edges = m_restrictions[edge_index].restrict_edges();
         if (r_edges[0] != edge) break;
         log << m_restrictions[edge_index] << "\n";
         bool okay = true;
         size_t temp_edge_index = index;
         for (auto &edge_id : r_edges) {
             if (temp_edge_index >= m_edges_in_path.size() ||
                 m_edges_in_path[temp_edge_index] != edge_id) {
                 okay = false;
                 break;
             }
             temp_edge_index++;
         }
         log << "\nokay value = " << okay <<"\n";
         if (okay) return true;
         edge_index++;
     }
     log << "Ends Here\n";
     return false;
 }
has_restriction()
template<class G > bool Pgr_dijkstraTRSP< G >::has_restriction () private
Definition at line 169 of file pgr_dijkstraTRSP.hpp.
References Pgr_dijkstraTRSP< G >::has_a_restriction(), Pgr_dijkstraTRSP< G >::log, Pgr_dijkstraTRSP< G >::m_edges_in_path, Pgr_dijkstraTRSP< G >::m_restrictions, and Restriction::restrict_edges().
Referenced by Pgr_dijkstraTRSP< G >::executeDijkstraTRSP().
{
     auto sort_cmp = [](const Restriction& left,
          const Restriction& right) -> bool {
            return left.restrict_edges()[0] <= right.restrict_edges()[0];
        };
     std::stable_sort(m_restrictions.begin(), m_restrictions.end(),
         sort_cmp);
     log << "\nRestriction array after sorting.\n";
     for (auto &it : m_restrictions) log << it << "\n";
     log << "\nEnd\n";
     size_t index = 0;
     for (auto &edge : m_edges_in_path) {
         if (has_a_restriction(edge, index))
             return true;
         index++;
     }
     return false;
 }
Member Data Documentation
curr_result_path
template<class G> Path Pgr_dijkstraTRSP< G >::curr_result_path private
Definition at line 73 of file pgr_dijkstraTRSP.hpp.
Referenced by Pgr_dijkstraTRSP< G >::dijkstraTRSP(), Pgr_dijkstraTRSP< G >::executeDijkstraTRSP(), and Pgr_dijkstraTRSP< G >::getDijkstraSolution().
log
template<class G> std::ostringstream Pgr_dijkstraTRSP< G >::log
Definition at line 76 of file pgr_dijkstraTRSP.hpp.
Referenced by Pgr_dijkstraTRSP< G >::dijkstraTRSP(), Pgr_dijkstraTRSP< G >::executeDijkstraTRSP(), Pgr_dijkstraTRSP< G >::has_a_restriction(), Pgr_dijkstraTRSP< G >::has_restriction(), and pgr_dijkstraTRSP().
m_edges_in_path
template<class G> std::vector< int64_t > Pgr_dijkstraTRSP< G >::m_edges_in_path private
Definition at line 69 of file pgr_dijkstraTRSP.hpp.
Referenced by Pgr_dijkstraTRSP< G >::executeDijkstraTRSP(), Pgr_dijkstraTRSP< G >::has_a_restriction(), and Pgr_dijkstraTRSP< G >::has_restriction().
m_end
template<class G> int64_t Pgr_dijkstraTRSP< G >::m_end private
Definition at line 67 of file pgr_dijkstraTRSP.hpp.
Referenced by Pgr_dijkstraTRSP< G >::dijkstraTRSP(), and Pgr_dijkstraTRSP< G >::getDijkstraSolution().
m_only_cost
template<class G> bool Pgr_dijkstraTRSP< G >::m_only_cost private
Definition at line 70 of file pgr_dijkstraTRSP.hpp.
Referenced by Pgr_dijkstraTRSP< G >::dijkstraTRSP().
m_restrictions
template<class G> std::vector< Restriction > Pgr_dijkstraTRSP< G >::m_restrictions private
Definition at line 68 of file pgr_dijkstraTRSP.hpp.
Referenced by Pgr_dijkstraTRSP< G >::dijkstraTRSP(), Pgr_dijkstraTRSP< G >::has_a_restriction(), and Pgr_dijkstraTRSP< G >::has_restriction().
m_start
template<class G> int64_t Pgr_dijkstraTRSP< G >::m_start private
Definition at line 66 of file pgr_dijkstraTRSP.hpp.
Referenced by Pgr_dijkstraTRSP< G >::dijkstraTRSP(), and Pgr_dijkstraTRSP< G >::getDijkstraSolution().
m_strict
template<class G> bool Pgr_dijkstraTRSP< G >::m_strict private
Definition at line 71 of file pgr_dijkstraTRSP.hpp.
Referenced by Pgr_dijkstraTRSP< G >::dijkstraTRSP().
v_source
template<class G> V Pgr_dijkstraTRSP< G >::v_source private
Definition at line 64 of file pgr_dijkstraTRSP.hpp.
Referenced by Pgr_dijkstraTRSP< G >::dijkstraTRSP().
v_target
template<class G> V Pgr_dijkstraTRSP< G >::v_target private
Definition at line 65 of file pgr_dijkstraTRSP.hpp.
Referenced by Pgr_dijkstraTRSP< G >::dijkstraTRSP().
The documentation for this class was generated from the following file:
pgr_dijkstraTRSP.hpp