PGROUTING: pgrouting::contraction::Pgr_contract< G > Class Template Reference
pgrouting::contraction::Pgr_contract< G > Class Template Reference
#include "pgr_contract.hpp"
Public Member Functions
Pgr_contract (G &graph, Identifiers< V > forbidden_vertices, std::vector< int64_t > contraction_order, int64_t max_cycles, Identifiers< int64_t > &remaining_vertices, std::vector< pgrouting::CH_edge > &shortcut_edges, std::ostringstream &debug)
Private Types
typedef G::V V
Private Member Functions
void perform_deadEnd (G &graph, Identifiers< V > forbidden_vertices, std::ostringstream &debug)
void perform_linear (G &graph, Identifiers< V > &forbidden_vertices, std::ostringstream &debug)
Detailed Description
template<class G>
class pgrouting::contraction::Pgr_contract< G >
Definition at line 47 of file pgr_contract.hpp.
Member Typedef Documentation
V
template<class G> typedef G::V pgrouting::contraction::Pgr_contract< G >::V private
Definition at line 48 of file pgr_contract.hpp.
Constructor & Destructor Documentation
Pgr_contract()
template<class G> pgrouting::contraction::Pgr_contract< G >::Pgr_contract (G & graph, Identifiers< V > forbidden_vertices, std::vector< int64_t > contraction_order, int64_t max_cycles, Identifiers< int64_t > & remaining_vertices, std::vector< pgrouting::CH_edge > & shortcut_edges, std::ostringstream & debug) inline
Definition at line 86 of file pgr_contract.hpp.
References pgrouting::contraction::Pgr_contract< G >::perform_deadEnd(), and pgrouting::contraction::Pgr_contract< G >::perform_linear().
{
         std::deque<int64_t> contract_order;
         //  push -1 to indicate the start of the queue
         contract_order.push_back(-1);
         contract_order.insert(
                 contract_order.end(),
                 contraction_order.begin(), contraction_order.end());
         for (int64_t i = 0; i < max_cycles; ++i) {
             int64_t front = contract_order.front();
             debug << "Starting cycle " << i+1 << "\n";
             contract_order.pop_front();
             contract_order.push_back(front);
             front = contract_order.front();
             while (front != -1) {
                 switch (front) {
                     case -1:
                         debug << "Finished cycle " << i+1 << std::endl;
                         break;
                     default:
                         debug << "contraction "<< front
                             << " asked" << std::endl;
                         if (front == 1) {
 #ifndef NDEBUG
                             debug << "Graph before dead end contraction"
                                 << std::endl;
                             graph.print_graph(debug);
                             debug << "Performing dead end contraction"
                                 << std::endl;
 #endif
                             perform_deadEnd(graph, forbidden_vertices, debug);
 #ifndef NDEBUG
                             debug << "Graph after dead end contraction"
                                 << std::endl;
                             graph.print_graph(debug);
 #endif
                         } else if (front == 2) {
 #ifndef NDEBUG
                             debug << "Graph before linear contraction"
                                 << std::endl;
                             graph.print_graph(debug);
                             debug << "Performing linear contraction"
                                 << std::endl;
 #endif
                             perform_linear(graph, forbidden_vertices, debug);
 #ifndef NDEBUG
                             debug << "Graph after linear contraction"
                                 << std::endl;
                             graph.print_graph(debug);
 #endif
                         }
                         contract_order.pop_front();
                         contract_order.push_back(front);
                         front = contract_order.front();
                 }
             }
         }
         remaining_vertices = graph.get_changed_vertices();
         debug << "Printing shortcuts\n";
         for (auto shortcut : graph.shortcuts) {
             debug << shortcut;
             shortcut_edges.push_back(shortcut);
         }
     }
Member Function Documentation
perform_deadEnd()
template<class G> void pgrouting::contraction::Pgr_contract< G >::perform_deadEnd (G & graph, Identifiers< V > forbidden_vertices, std::ostringstream & debug) inline private
Definition at line 51 of file pgr_contract.hpp.
References pgrouting::contraction::Pgr_deadend< G >::calculateVertices(), pgrouting::contraction::Pgr_deadend< G >::doContraction(), and pgrouting::contraction::Pgr_deadend< G >::setForbiddenVertices().
Referenced by pgrouting::contraction::Pgr_contract< G >::Pgr_contract().
{
         Pgr_deadend<G> deadendContractor;
         debug << "Setting forbidden_vertices";
         deadendContractor.setForbiddenVertices(forbidden_vertices);
         deadendContractor.calculateVertices(graph);
         try {
             deadendContractor.doContraction(graph);
         }
         catch ( ... ) {
             debug << "Caught unknown exception!\n";
         }
     }
perform_linear()
template<class G> void pgrouting::contraction::Pgr_contract< G >::perform_linear (G & graph, Identifiers< V > & forbidden_vertices, std::ostringstream & debug) inline private
Definition at line 68 of file pgr_contract.hpp.
References pgrouting::contraction::Pgr_linear< G >::calculateVertices(), pgrouting::contraction::Pgr_linear< G >::doContraction(), and pgrouting::contraction::Pgr_linear< G >::setForbiddenVertices().
Referenced by pgrouting::contraction::Pgr_contract< G >::Pgr_contract().
{
         std::ostringstream linear_debug;
         Pgr_linear<G> linearContractor;
         linearContractor.setForbiddenVertices(forbidden_vertices);
         linearContractor.calculateVertices(graph);
         try {
             linearContractor.doContraction(graph);
         }
         catch ( ... ) {
             linear_debug << "Caught unknown exception!\n";
         }
         debug << linear_debug.str().c_str() << "\n";
     }
The documentation for this class was generated from the following file:
pgr_contract.hpp