PGROUTING: Pgr_components< G > Class Template Reference
Pgr_components< G > Class Template Reference
#include "pgr_components.hpp"
Public Types
typedef G::E E
typedef G::E_i E_i
typedef G::V V
Public Member Functions
std::vector< pgr_components_rt > articulationPoints (G &graph)
Articulation Points.
std::vector< pgr_components_rt > biconnectedComponents (G &graph)
Biconnected Components.
std::vector< pgr_components_rt > bridges (G &graph)
Bridges.
std::vector< pgr_components_rt > connectedComponents (G &graph)
Connected Components Vertex Version.
std::vector< pgr_components_rt > strongComponents (G &graph)
Strongly Connected Components Vertex Version.
Private Member Functions
std::vector< pgr_components_rt > generate_results (std::vector< std::vector< int64_t > >)
Generate Results, Vertex Version.
Detailed Description
template<class G>
class Pgr_components< G >
Definition at line 44 of file pgr_components.hpp.
Member Typedef Documentation
E
template<class G> typedef G::E Pgr_components< G >::E
Definition at line 54 of file pgr_components.hpp.
E_i
template<class G> typedef G::E_i Pgr_components< G >::E_i
Definition at line 55 of file pgr_components.hpp.
V
template<class G> typedef G::V Pgr_components< G >::V
Definition at line 53 of file pgr_components.hpp.
Member Function Documentation
articulationPoints()
template<class G > std::vector< pgr_components_rt > Pgr_components< G >::articulationPoints (G & graph)
Articulation Points.
Definition at line 186 of file pgr_components.hpp.
References pgr_components_rt::identifier.
Referenced by pgr_articulationPoints().
                   {
     // perform the algorithm
     std::vector <size_t> art_points;
     boost::articulation_points(graph.graph, std::back_inserter(art_points));
     // get the results
     std::vector <pgr_components_rt> results;
     size_t totalArtp = art_points.size();
     results.resize(totalArtp);
     for (size_t i = 0; i < totalArtp; i++)
         results[i].identifier = graph[art_points[i]].id;
     // sort identifier
     std::sort(results.begin(), results.end(),
             [](const pgr_components_rt &left, const pgr_components_rt &right) {
             return left.identifier < right.identifier; });
     return results;
 }
biconnectedComponents()
template<class G > std::vector< pgr_components_rt > Pgr_components< G >::biconnectedComponents (G & graph)
Biconnected Components.
Definition at line 160 of file pgr_components.hpp.
References Pgr_components< G >::generate_results().
Referenced by pgr_biconnectedComponents().
                   {
     // perform the algorithm
     struct order_edges {
         bool operator() (const E &left, const E &right) const {
             return left.get_property() < right.get_property();
         }
     };
     typedef std::map< E, size_t > edge_map;
     edge_map bicmp_map;
     boost::associative_property_map< edge_map > bimap(bicmp_map);
     size_t num_comps = biconnected_components(graph.graph, bimap);
     // get the results
     E_i ei, ei_end;
     std::vector< std::vector< int64_t > > components(num_comps);
     for (boost::tie(ei, ei_end) = edges(graph.graph); ei != ei_end; ei++)
         components[bimap[*ei]].push_back(graph[*ei].id);
     return generate_results(components);
 }
bridges()
template<class G > std::vector< pgr_components_rt > Pgr_components< G >::bridges (G & graph)
Bridges.
Definition at line 210 of file pgr_components.hpp.
References pgr_components_rt::identifier.
Referenced by pgr_bridges().
                   {
     size_t totalNodes = num_vertices(graph.graph);
     std::vector< int > tmp_comp(totalNodes);
     std::vector <pgr_components_rt> results;
     int ini_comps = boost::connected_components(graph.graph, &tmp_comp[0]);
     // perform the algorithm
     E_i ei, ei_end;
     std::vector< std::pair<E, int64_t> > stored_edges;
     for (boost::tie(ei, ei_end) = edges(graph.graph); ei != ei_end; ++ei) {
         stored_edges.push_back(std::make_pair(*ei, graph[*ei].id));
     }
     for (const auto pair_edge : stored_edges) {
         E edge = pair_edge.first;
         boost::remove_edge(edge, graph.graph);
         int now_comps = boost::connected_components(graph.graph, &tmp_comp[0]);
         if (now_comps > ini_comps) {
             pgr_components_rt temp;
             temp.identifier = pair_edge.second;
             results.push_back(temp);
         }
         boost::add_edge(boost::source(edge, graph.graph),
                         boost::target(edge, graph.graph),
                         graph.graph);
     }
     // sort identifier
     std::sort(results.begin(), results.end(),
             [](const pgr_components_rt &left, const pgr_components_rt &right) {
             return left.identifier < right.identifier; });
     return results;
 }
connectedComponents()
template<class G > std::vector< pgr_components_rt > Pgr_components< G >::connectedComponents (G & graph)
Connected Components Vertex Version.
Definition at line 117 of file pgr_components.hpp.
References Pgr_components< G >::generate_results().
Referenced by pgr_connectedComponents().
                   {
     size_t totalNodes = num_vertices(graph.graph);
     // perform the algorithm
     std::vector< int > components(totalNodes);
     int num_comps = boost::connected_components(graph.graph, &components[0]);
     // get the results
     std::vector< std::vector< int64_t > > results;
     results.resize(num_comps);
     for (size_t i = 0; i < totalNodes; i++)
         results[components[i]].push_back(graph[i].id);
     return generate_results(results);
 }
generate_results()
template<class G > std::vector< pgr_components_rt > Pgr_components< G >::generate_results (std::vector< std::vector< int64_t > > components) private
Generate Results, Vertex Version.
Definition at line 89 of file pgr_components.hpp.
References pgr_components_rt::component, pgr_components_rt::identifier, and pgr_components_rt::n_seq.
Referenced by Pgr_components< G >::biconnectedComponents(), Pgr_components< G >::connectedComponents(), and Pgr_components< G >::strongComponents().
{
     // sort identifier
     size_t num_comps = components.size();
     for (size_t i = 0; i < num_comps; i++) {
         std::sort(components[i].begin(), components[i].end());
     }
     sort(components.begin(), components.end());
     // generate results
     std::vector< pgr_components_rt > results;
     for (size_t i = 0; i < num_comps; i++) {
         int64_t tempComp = components[i][0];
         size_t sizeCompi = components[i].size();
         for (size_t j = 0; j < sizeCompi; j++) {
             pgr_components_rt tmp;
             tmp.identifier = components[i][j];
             tmp.n_seq = static_cast< int > (j + 1);
             tmp.component = tempComp;
             results.push_back(tmp);
         }
     }
     return results;
 }
strongComponents()
template<class G > std::vector< pgr_components_rt > Pgr_components< G >::strongComponents (G & graph)
Strongly Connected Components Vertex Version.
Definition at line 137 of file pgr_components.hpp.
References Pgr_components< G >::generate_results().
Referenced by pgr_strongComponents().
                   {
     size_t totalNodes = num_vertices(graph.graph);
     // perform the algorithm
     std::vector< int > components(totalNodes);
     int num_comps = boost::strong_components(graph.graph,
             boost::make_iterator_property_map(components.begin(),
                                               get(boost::vertex_index,
                                                   graph.graph)));
     // get the results
     std::vector< std::vector< int64_t > > results;
     results.resize(num_comps);
     for (size_t i = 0; i < totalNodes; i++)
         results[components[i]].push_back(graph[i].id);
     return generate_results(results);
 }
The documentation for this class was generated from the following file:
pgr_components.hpp