PGROUTING: connectedComponents_driver.cpp File Reference
connectedComponents_driver.cpp File Reference
#include "drivers/components/connectedComponents_driver.h"
#include <sstream>
#include <deque>
#include <vector>
#include "components/pgr_components.hpp"
#include "cpp_common/pgr_alloc.hpp"
#include "cpp_common/pgr_assert.h"
Functions
void do_pgr_connectedComponents (pgr_edge_t *data_edges, size_t total_edges, pgr_components_rt **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
template<class G >
static std::vector< pgr_components_rt > pgr_connectedComponents (G &graph)
Function Documentation
do_pgr_connectedComponents()
void do_pgr_connectedComponents (pgr_edge_t * data_edges, size_t total_edges, pgr_components_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 63 of file connectedComponents_driver.cpp.
References pgrouting::graph::Pgr_componentsGraph< G, T_V, T_E >::insert_edges(), pgassert, pgr_alloc(), pgr_connectedComponents(), pgr_free(), pgr_msg(), UNDIRECTED, and AssertFailedException::what().
Referenced by process().
{
     std::ostringstream log;
     std::ostringstream err;
     std::ostringstream notice;
     try {
         pgassert(!(*log_msg));
         pgassert(!(*notice_msg));
         pgassert(!(*err_msg));
         pgassert(!(*return_tuples));
         pgassert(*return_count == 0);
         pgassert(total_edges != 0);
         graphType gType = UNDIRECTED;
         std::vector<pgr_components_rt> results;
         log << "Working with Undirected Graph\n";
         pgrouting::ComponentsUndiGraph undigraph(gType);
         undigraph.insert_edges(data_edges, total_edges);
         results = pgr_connectedComponents(
                 undigraph);
         auto count = results.size();
         if (count == 0) {
             (*return_tuples) = NULL;
             (*return_count) = 0;
             notice <<
                 "No paths found between start_vid and end_vid vertices";
             return;
         }
         (*return_tuples) = pgr_alloc(count, (*return_tuples));
         for (size_t i = 0; i < count; i++) {
             *((*return_tuples) + i) = results[i];
         }
         (*return_count) = count;
         pgassert(*err_msg == NULL);
         *log_msg = log.str().empty()?
             *log_msg :
             pgr_msg(log.str().c_str());
         *notice_msg = notice.str().empty()?
             *notice_msg :
             pgr_msg(notice.str().c_str());
     } catch (AssertFailedException &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch (std::exception &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch(...) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << "Caught unknown exception!";
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     }
 }
pgr_connectedComponents()
template<class G > static std::vector<pgr_components_rt> pgr_connectedComponents (G & graph) static
Definition at line 54 of file connectedComponents_driver.cpp.
References Pgr_components< G >::connectedComponents().
Referenced by do_pgr_connectedComponents().
                   {
     std::vector<pgr_components_rt> results;
     Pgr_components< G > fn_components;
     return fn_components.connectedComponents(graph);
 }