PGROUTING: contractGraph_driver.h File Reference
contractGraph_driver.h File Reference
#include "c_types/contracted_rt.h"
#include "c_types/pgr_edge_t.h"
Functions
void do_pgr_contractGraph (pgr_edge_t *data_edges, size_t total_tuples, int64_t *forbidden_vertices, size_t size_forbidden_vertices, int64_t *contraction_order, size_t size_contraction_order, int64_t max_cycles, bool directed, contracted_rt **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
Function Documentation
do_pgr_contractGraph()
void do_pgr_contractGraph (pgr_edge_t * data_edges, size_t total_tuples, int64_t * forbidden_vertices, size_t size_forbidden_vertices, int64_t * contraction_order, size_t size_contraction_order, int64_t max_cycles, bool directed, contracted_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 172 of file contractGraph_driver.cpp.
References edge::cost, DIRECTED, get_postgres_result(), edge::id, is_valid_contraction(), pgassert, pgr_free(), pgr_msg(), process_contraction(), edge::reverse_cost, Identifiers< T >::size(), edge::source, edge::target, UNDIRECTED, and AssertFailedException::what().
Referenced by process().
{
     std::ostringstream log;
     std::ostringstream notice;
     std::ostringstream err;
     try {
         pgassert(total_edges != 0);
         pgassert(size_contraction_order != 0);
         pgassert(max_cycles != 0);
         pgassert(!(*log_msg));
         pgassert(!(*notice_msg));
         pgassert(!(*err_msg));
         pgassert(!(*return_tuples));
         pgassert(*return_count == 0);
         std::ostringstream debug;
         /*
          * Converting to C++ structures
          */
         std::vector<pgr_edge_t> edges(data_edges, data_edges + total_edges);
         std::vector<int64_t> forbid(
                 forbidden_vertices,
                 forbidden_vertices + size_forbidden_vertices);
         std::vector<int64_t> ordering(
                 contraction_order,
                 contraction_order + size_contraction_order);
         for (const auto o : ordering) {
             if (!is_valid_contraction(o)) {
                 *err_msg = pgr_msg("Invalid Contraction Type found");
                 log << "Contraction type " << o << " not valid";
                 *log_msg = pgr_msg(log.str().c_str());
                 return;
             }
         }
         /*
          * Extracting vertices of the graph
          */
         Identifiers<int64_t> remaining_vertices;
         std::vector< pgrouting::CH_edge > shortcut_edges;
 #ifndef NDEBUG
         log << "Original Graph: \n" <<
             std::setprecision(32);
         for (const auto edge : edges) {
             log << "id = " << edge.id
                 << "\tsource = " << edge.source
                 << "\ttarget = " << edge.target
                 << "\tcost = " << edge.cost
                 << "\treverse_cost = " << edge.reverse_cost
                 << ")\n";
         }
         log << "size_contraction_order " << ordering.size() << "\n";
         log << "contraction_order: " <<"{ ";
         for (const auto o : ordering) {
             log << o << ", ";
         }
         log << " }\n";
         log << "size_forbidden_vertices " << forbid.size() << "\n";
         log << "forbidden_vertices" << "{ ";
         for (const auto vertex : forbid) {
             log << vertex << ", ";
         }
         log << " }\n";
         log << "max_cycles " << max_cycles << "\n";
         log << "directed " << directed << "\n";
 #endif
         graphType gType = directed? DIRECTED: UNDIRECTED;
         if (directed) {
             log << "Working with directed Graph\n";
             pgrouting::CHDirectedGraph digraph(gType);
             process_contraction(digraph, edges, forbid, ordering,
                     max_cycles,
                     remaining_vertices, shortcut_edges,
                     log, err);
             get_postgres_result(
                     digraph,
                     remaining_vertices,
                     shortcut_edges,
                     return_tuples);
         } else {
             log << "Working with Undirected Graph\n";
             pgrouting::CHUndirectedGraph undigraph(gType);
             process_contraction(undigraph, edges, forbid, ordering,
                     max_cycles,
                     remaining_vertices, shortcut_edges,
                     log, err);
             get_postgres_result(
                     undigraph,
                     remaining_vertices,
                     shortcut_edges,
                     return_tuples);
         }
         (*return_count) = remaining_vertices.size()+shortcut_edges.size();
         *log_msg = log.str().empty()?
             *log_msg :
             pgr_msg(log.str().c_str());
         *notice_msg = notice.str().empty()?
             *notice_msg :
             pgr_msg(notice.str().c_str());
     } catch (AssertFailedException &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch (std::exception &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch(...) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << "Caught unknown exception!";
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     }
 }