PGROUTING: dijkstraTRSP_driver.h File Reference
dijkstraTRSP_driver.h File Reference
#include "c_types/pgr_edge_t.h"
#include "c_types/general_path_element_t.h"
#include "c_types/restrict_t.h"
Functions
void do_pgr_dijkstraTRSP (pgr_edge_t *data_edges, size_t total_edges, Restrict_t *restrictions, size_t total_restrictions, int64_t start_vid, int64_t end_vid, bool directed, bool only_cost, bool strict, General_path_element_t **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
Function Documentation
do_pgr_dijkstraTRSP()
void do_pgr_dijkstraTRSP (pgr_edge_t * data_edges, size_t total_edges, Restrict_t * restrictions, size_t total_restrictions, int64_t start_vid, int64_t end_vid, bool directed, bool only_cost, bool strict, General_path_element_t ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 69 of file dijkstraTRSP_driver.cpp.
References DIRECTED, Path::generate_postgres_data(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::insert_edges(), pgassert, pgr_alloc(), pgr_dijkstraTRSP(), pgr_free(), pgr_msg(), Path::size(), UNDIRECTED, and AssertFailedException::what().
Referenced by process().
{
     std::ostringstream log;
     std::ostringstream err;
     std::ostringstream notice;
     try {
         pgassert(!(*log_msg));
         pgassert(!(*notice_msg));
         pgassert(!(*err_msg));
         pgassert(!(*return_tuples));
         pgassert(*return_count == 0);
         pgassert(total_edges != 0);
         log << "\n---------------------------------------\nRestrictions data\n";
         std::vector< Restriction > restrict_array;
         for (size_t i = 0; i < total_restrictions; i++) {
             restrict_array.push_back(Restriction(restrictions[i]));
         }
         log << "\n-----------------------------------------\nStart from here\n";
         for (const auto &it : restrict_array) {
             log << it << "\n";
         }
         log <<"------------------------------------------------------------\n";
         graphType gType = directed? DIRECTED: UNDIRECTED;
         std::vector < pgr_edge_t > edges(data_edges, data_edges + total_edges);
         Path path;
         std::string logstr;
         if (directed) {
             log << "Working with directed Graph\n";
             pgrouting::DirectedGraph digraph(gType);
             Pgr_dijkstraTRSP < pgrouting::DirectedGraph > fn_TRSP;
             digraph.insert_edges(edges);
             path = pgr_dijkstraTRSP(digraph,
                     restrict_array,
                     edges,
                     start_vid,
                     end_vid,
                     logstr,
                     only_cost,
                     strict);
         } else {
             log << "Working with Undirected Graph\n";
             pgrouting::UndirectedGraph undigraph(gType);
             Pgr_dijkstraTRSP < pgrouting::UndirectedGraph > fn_TRSP;
             undigraph.insert_edges(data_edges, total_edges);
         #if 0
             path = pgr_dijkstraTRSP(undigraph,
                     restrict_array,
                     edges,
                     start_vid,
                     end_vid,
                     logstr,
                     only_cost,
                     strict);
         #endif
         }
         log << logstr;
         auto count = path.size();
         log << "\nCount = " << count;
         if (count == 0) {
             (*return_tuples) = NULL;
             (*return_count) = 0;
             notice <<
                 "No paths found between start_vid and end_vid vertices";
         } else {
             (*return_tuples) = pgr_alloc(count, (*return_tuples));
             size_t sequence = 0;
             path.generate_postgres_data(return_tuples, sequence);
             (*return_count) = sequence;
         }
         pgassert(*err_msg == NULL);
         *log_msg = log.str().empty()?
             *log_msg :
             pgr_msg(log.str().c_str());
         #if 0
         *notice_msg = notice.str().empty()?
             *notice_msg :
             pgr_msg(notice.str().c_str());
         #endif
         pgassert(!log.str().empty());
     } catch (AssertFailedException &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch (std::exception &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch(...) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << "Caught unknown exception!";
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     }
 }