PGROUTING: /home/vicky/pgrouting/pgrouting/pgrouting/src/dijkstraTRSP/restriction.cpp File Reference
restriction.cpp File Reference
#include "dijkstraTRSP/restriction.h"
#include <vector>
#include <memory>
#include <utility>
#include <limits>
Functions
std::ostream & operator<< (std::ostream &log, const Restriction &r)
Function Documentation
std::ostream& operator<< (std::ostream & log, const Restriction & r)
Definition at line 43 of file restriction.cpp.
References Restriction::cost(), Restriction::id(), and Restriction::restrict_edges().
{
     log << "\n--------------------------------\nRestriction\n";
     log << "ID: " << r.id() << "\nRestricion edge sequence: ";
     for (const auto &v : r.restrict_edges()) {
         log << v <<" ";
     }
     log << "\n";
     log << "Cost: " << r.cost() << "\n";
     return log;
 }