PGROUTING: trsp_core.cpp File Reference
trsp_core.cpp File Reference
#include "trsp/GraphDefinition.h"
Functions
int trsp_edge_wrapper (edge_t *edges, size_t edge_count, restrict_t *restricts, size_t restrict_count, int64_t start_edge, double start_pos, int64_t end_edge, double end_pos, bool directed, bool has_reverse_cost, path_element_tt **path, size_t *path_count, char **err_msg)
int trsp_node_wrapper (edge_t *edges, size_t edge_count, restrict_t *restricts, size_t restrict_count, int64_t start_vertex, int64_t end_vertex, bool directed, bool has_reverse_cost, path_element_tt **path, size_t *path_count, char **err_msg)
Function Documentation
trsp_edge_wrapper()
int trsp_edge_wrapper (edge_t * edges, size_t edge_count, restrict_t * restricts, size_t restrict_count, int64_t start_edge, double start_pos, int64_t end_edge, double end_pos, bool directed, bool has_reverse_cost, path_element_tt ** path, size_t * path_count, char ** err_msg)
Definition at line 83 of file trsp_core.cpp.
References MAX_RULE_LENGTH, GraphDefinition::my_dijkstra(), and restrict_struct::via.
Referenced by compute_trsp().
       {
     try {
         std::vector<PDVI> ruleTable;
         size_t i, j;
         ruleTable.clear();
         for (i = 0; i < restrict_count; i++) {
             std::vector<long> seq;
             seq.clear();
             seq.push_back(restricts[i].target_id);
             for (j = 0; j < MAX_RULE_LENGTH && restricts[i].via[j] >- 1; j++) {
                 seq.push_back(restricts[i].via[j]);
             }
             ruleTable.push_back(make_pair(restricts[i].to_cost, seq));
         }
         GraphDefinition gdef;
         auto res = gdef.my_dijkstra(edges, edge_count, start_edge, start_pos,
             end_edge, end_pos, directed, has_reverse_cost, path, path_count,
             err_msg, ruleTable);
         if (res < 0)
             return res;
         else
             return EXIT_SUCCESS;
     }
     catch(std::exception& e) {
         *err_msg = (char *) e.what();
         return -1;
     }
     catch(...) {
         *err_msg = (char *) "Caught unknown exception!";
         return -1;
     }
 }
trsp_node_wrapper()
int trsp_node_wrapper (edge_t * edges, size_t edge_count, restrict_t * restricts, size_t restrict_count, int64_t start_vertex, int64_t end_vertex, bool directed, bool has_reverse_cost, path_element_tt ** path, size_t * path_count, char ** err_msg)
Definition at line 35 of file trsp_core.cpp.
References MAX_RULE_LENGTH, GraphDefinition::my_dijkstra(), and restrict_struct::via.
Referenced by compute_trsp().
       {
     try {
         std::vector<PDVI> ruleTable;
         size_t i, j;
         ruleTable.clear();
         for (i = 0; i < restrict_count; i++) {
             std::vector<long> seq;
             seq.clear();
             seq.push_back(restricts[i].target_id);
             for (j = 0; j < MAX_RULE_LENGTH && restricts[i].via[j] > -1; j++) {
                 seq.push_back(restricts[i].via[j]);
             }
             ruleTable.push_back(make_pair(restricts[i].to_cost, seq));
         }
         GraphDefinition gdef;
         int res = gdef.my_dijkstra(edges, edge_count, start_vertex, end_vertex,
             directed, has_reverse_cost, path, path_count, err_msg, ruleTable);
         if (res < 0)
             return res;
         else
             return EXIT_SUCCESS;
     }
     catch(std::exception& e) {
         *err_msg = (char *) e.what();
         return -1;
     }
     catch(...) {
         *err_msg = (char *) "Caught unknown exception!";
         return -1;
     }
 }