pgRouting: VRP_core.cpp File Reference
VRP_core.cpp File Reference
#include "VRP.h"
#include "VRP_Solver.h"
#include <vector>
#include <string>
#include <exception>
#include "../../common/src/pgr_logger.h"
Macros
#define PGR_LOGGER_FILE "/tmp/vrp-debug.log"
#define PGR_LOGGER_LOC
Functions
int find_vrp_solution (vrp_vehicles_t *vehicles, size_t vehicle_count, vrp_orders_t *orders, size_t order_count, vrp_cost_element_t *costmatrix, size_t cost_count, int depot_id, vrp_result_element_t **results, size_t *result_count, char **err_msg)
void loadDistanceMatrix (vrp_cost_element_t *costmatrix, int cost_count, int depotId)
void loadOrders (vrp_orders_t *orders, int order_count, int depotId)
void loadVehicles (vrp_vehicles_t *vehicles, int vehicle_count)
Variables
CVRPSolver solver
Macro Definition Documentation
#define PGR_LOGGER_FILE "/tmp/vrp-debug.log"
Definition at line 37 of file VRP_core.cpp.
#define PGR_LOGGER_LOC
Definition at line 36 of file VRP_core.cpp.
Function Documentation
int find_vrp_solution (vrp_vehicles_t * vehicles, size_t vehicle_count, vrp_orders_t * orders, size_t order_count, vrp_cost_element_t * costmatrix, size_t cost_count, int depot_id, vrp_result_element_t ** results, size_t * result_count, char ** err_msg)
Definition at line 137 of file VRP_core.cpp.
References CTourInfo::getEndDepot(), CTourInfo::getOrderVector(), CTourInfo::getServedOrderCount(), CVRPSolver::getServiceTime(), CVRPSolver::getSolution(), CTourInfo::getStartDepot(), CTourInfo::getStartTime(), CSolutionInfo::getTour(), CSolutionInfo::getTourInfoVector(), CTourInfo::getVehicleId(), loadDistanceMatrix(), loadOrders(), loadVehicles(), PGR_LOG, and CVRPSolver::solveVRP().
Referenced by solve_vrp().
void loadDistanceMatrix (vrp_cost_element_t * costmatrix, int cost_count, int depotId)
Definition at line 117 of file VRP_core.cpp.
References CVRPSolver::addDepotToOrderCost(), CVRPSolver::addOrderToDepotCost(), CVRPSolver::addOrderToOrderCost(), vrp_cost_element::cost, CostPack::cost, vrp_cost_element::dest_id, vrp_cost_element::distance, CostPack::distance, vrp_cost_element::src_id, CostPack::traveltime, and vrp_cost_element::traveltime.
Referenced by find_vrp_solution().
void loadOrders (vrp_orders_t * orders, int order_count, int depotId)
Definition at line 42 of file VRP_core.cpp.
References CVRPSolver::addDepot(), CVRPSolver::addOrder(), vrp_orders::close_time, vrp_orders::id, vrp_orders::open_time, vrp_orders::order_unit, PGR_LOG, PGR_LOGF, vrp_orders::service_time, COrderInfo::setCloseTime(), CDepotInfo::setCloseTime(), CDepotInfo::setDepotId(), CDepotInfo::setDepotLocation(), COrderInfo::setOpenTime(), CDepotInfo::setOpenTime(), COrderInfo::setOrderId(), COrderInfo::setOrderLocation(), COrderInfo::setOrderUnit(), COrderInfo::setServiceTime(), vrp_orders::x, Point::X, vrp_orders::y, and Point::Y.
Referenced by find_vrp_solution().
void loadVehicles (vrp_vehicles_t * vehicles, int vehicle_count)
Definition at line 100 of file VRP_core.cpp.
References CVRPSolver::addVehicle(), vrp_vehicles::capacity, vrp_vehicles::id, CVehicleInfo::setCapacity(), CVehicleInfo::setCostPerKM(), and CVehicleInfo::setId().
Referenced by find_vrp_solution().
Variable Documentation
CVRPSolver solver
Definition at line 40 of file VRP_core.cpp.