PGROUTING: /home/vicky/pgrouting/pgrouting/pgrouting/include/drivers/astar/astar_driver.h File Reference
astar_driver.h File Reference
#include "c_types/pgr_edge_xy_t.h"
#include "c_types/general_path_element_t.h"
Functions
void check_parameters (int heuristic, double factor, double epsilon)
void do_pgr_astarManyToMany (Pgr_edge_xy_t *data_edges, size_t total_edges, int64_t *start_vidsArr, size_t size_start_vidsArr, int64_t *end_vidsArr, size_t size_end_vidsArr, bool directed, int heuristic, double factor, double epsilon, bool only_cost, bool normal, General_path_element_t **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
Function Documentation
void check_parameters (int heuristic, double factor, double epsilon)
Definition at line 44 of file astar_driver.cpp.
Referenced by process().
{
     if (heuristic > 5 || heuristic < 0) {
         ereport(ERROR,
                 (errmsg("Unknown heuristic"),
                  errhint("Valid values: 0~5")));
     }
     if (factor <= 0) {
         ereport(ERROR,
                 (errmsg("Factor value out of range"),
                  errhint("Valid values: positive non zero")));
     }
     if (epsilon < 1) {
         ereport(ERROR,
                 (errmsg("Epsilon value out of range"),
                  errhint("Valid values: 1 or greater than 1")));
     }
 }
void do_pgr_astarManyToMany (Pgr_edge_xy_t * data_edges, size_t total_edges, int64_t * start_vidsArr, size_t size_start_vidsArr, int64_t * end_vidsArr, size_t size_end_vidsArr, bool directed, int heuristic, double factor, double epsilon, bool only_cost, bool normal, General_path_element_t ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 105 of file astar_driver.cpp.
References DIRECTED, pgrouting::extract_vertices(), pgrouting::graph::Pgr_base_graph< G, Vertex, Edge >::insert_edges(), pgassert, pgr_alloc(), pgr_astar(), pgr_free(), pgr_msg(), UNDIRECTED, and AssertFailedException::what().
Referenced by process().
{
     std::ostringstream log;
     std::ostringstream notice;
     std::ostringstream err;
     try {
         pgassert(!(*log_msg));
         pgassert(!(*err_msg));
         pgassert(!(*return_tuples));
         pgassert(*return_count == 0);
         pgassert(total_edges != 0);
         log << "Inserting target vertices into a c++ vector structure\n";
         std::vector< int64_t > end_vids(
                 end_vidsArr,
                 end_vidsArr + size_end_vidsArr);
         std::vector< int64_t > start_vids(
                 start_vidsArr,
                 start_vidsArr + size_start_vidsArr);
         graphType gType = directed? DIRECTED: UNDIRECTED;
         std::deque< Path >paths;
         if (directed) {
             log << "Working with directed Graph\n";
             pgrouting::xyDirectedGraph digraph(
                     pgrouting::extract_vertices(edges, total_edges),
                     gType);
             digraph.insert_edges(edges, total_edges);
             paths = pgr_astar(digraph, start_vids, end_vids,
                     heuristic, factor, epsilon, only_cost, normal);
         } else {
             log << "Working with Undirected Graph\n";
             pgrouting::xyUndirectedGraph undigraph(
                     pgrouting::extract_vertices(edges, total_edges),
                     gType);
             undigraph.insert_edges(edges, total_edges);
             paths = pgr_astar(undigraph, start_vids, end_vids,
                     heuristic, factor, epsilon, only_cost, normal);
         }
         size_t count(0);
         count = count_tuples(paths);
         if (count == 0) {
             (*return_tuples) = NULL;
             (*return_count) = 0;
             notice <<
                 "No paths found\n";
             *log_msg = pgr_msg(notice.str().c_str());
             return;
         }
         (*return_tuples) = pgr_alloc(count, (*return_tuples));
         log << "Converting a set of paths into the tuples\n";
         (*return_count) = (collapse_paths(return_tuples, paths));
         *log_msg = log.str().empty()?
             *log_msg :
             pgr_msg(log.str().c_str());
         *notice_msg = notice.str().empty()?
             *notice_msg :
             pgr_msg(notice.str().c_str());
     } catch (AssertFailedException &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch (std::exception &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch(...) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << "Caught unknown exception!";
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     }
 }