PGROUTING: Restriction Class Reference
Restriction Class Reference
#include "restriction.h"
Public Member Functions
Restriction ()=default
Restriction (const Restrict_t &r)
void clear ()
double cost () const
void cost (const double &value)
int64_t id () const
void id (const int64_t &value)
std::vector< int64_t > restrict_edges () const
void restrict_edges (const int64_t &value)
int64_t restriction_size () const
Private Attributes
double m_cost
int64_t m_id
std::vector< int64_t > m_restrict_edges
Friends
std::ostream & operator<< (std::ostream &log, const Restriction &r)
Detailed Description
Definition at line 38 of file restriction.h.
Constructor & Destructor Documentation
Restriction::Restriction () default
Restriction::Restriction (const Restrict_t & r)
Definition at line 33 of file restriction.cpp.
References restrict_edges(), and Restrict_t::restricted_edges.
                                             :
     m_id(r.id),
     m_cost(r.cost) {
         for(auto &it: r.restricted_edges) {
             if (it == -1) break;
             restrict_edges(it);
         }
     }
Member Function Documentation
void Restriction::clear () inline
Definition at line 56 of file restriction.h.
References m_restrict_edges.
                      {
             m_restrict_edges.clear();
         }
double Restriction::cost () const inline
Definition at line 51 of file restriction.h.
References m_cost.
Referenced by operator<<().
 {return m_cost;}
void Restriction::cost (const double & value) inline
Definition at line 52 of file restriction.h.
References m_cost.
 {m_cost = value;}
int64_t Restriction::id () const inline
Definition at line 48 of file restriction.h.
References m_id.
Referenced by operator<<().
 {return m_id;}
void Restriction::id (const int64_t & value) inline
Definition at line 49 of file restriction.h.
References m_id.
 {m_id = value;}
std::vector< int64_t > Restriction::restrict_edges () const inline
Definition at line 54 of file restriction.h.
References m_restrict_edges.
Referenced by Pgr_dijkstraTRSP< G >::has_a_restriction(), Pgr_dijkstraTRSP< G >::has_restriction(), operator<<(), and Restriction().
 {return m_restrict_edges;}
void Restriction::restrict_edges (const int64_t & value) inline
Definition at line 55 of file restriction.h.
References m_restrict_edges.
 {m_restrict_edges.push_back(value);}
int64_t Restriction::restriction_size () const inline
Definition at line 60 of file restriction.h.
References m_restrict_edges.
 {return m_restrict_edges.size();}
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & log, const Restriction & r) friend
Definition at line 43 of file restriction.cpp.
{
     log << "\n--------------------------------\nRestriction\n";
     log << "ID: " << r.id() << "\nRestricion edge sequence: ";
     for (const auto &v : r.restrict_edges()) {
         log << v <<" ";
     }
     log << "\n";
     log << "Cost: " << r.cost() << "\n";
     return log;
 }
Member Data Documentation
double Restriction::m_cost private
Definition at line 42 of file restriction.h.
Referenced by cost().
int64_t Restriction::m_id private
Definition at line 40 of file restriction.h.
Referenced by id().
std::vector< int64_t > Restriction::m_restrict_edges private
Definition at line 41 of file restriction.h.
Referenced by clear(), restrict_edges(), and restriction_size().
The documentation for this class was generated from the following files:
/home/vicky/pgrouting/pgrouting/pgrouting/include/dijkstraTRSP/restriction.h
/home/vicky/pgrouting/pgrouting/pgrouting/src/dijkstraTRSP/src/restriction.cpp