PGROUTING: pgrouting::graph::Pgr_lineGraph< G, T_V, T_E > Class Template Reference
pgrouting::graph::Pgr_lineGraph< G, T_V, T_E > Class Template Reference
#include "pgr_lineGraph.hpp"
Public Types
typedef boost::graph_traits< G >::edge_descriptor E
typedef boost::graph_traits< G >::in_edge_iterator EI_i
typedef boost::graph_traits< G >::out_edge_iterator EO_i
typedef boost::graph_traits< G >::vertex_descriptor V
typedef boost::graph_traits< G >::vertex_iterator V_i
Graph related types
Type boost meaning pgRouting meaning
G boost::adjacency_list Graph
V vertex_descriptor Think of it as local ID of a vertex
E edge_descriptor Think of it as local ID of an edge
V_i vertex_iterator To cycle the vertices of the Graph
E_i edge_iterator To cycle the edges of the Graph
EO_i out_edge_iterator To cycle the out going edges of a vertex
EI_i in_edge_iterator To cycle the in coming edges of a vertex (only in bidirectional graphs)
typedef G B_G
typedef T_E G_T_E
typedef T_V G_T_V
typedef boost::graph_traits< G >::edge_iterator E_i
typedef boost::graph_traits< G >::vertices_size_type vertices_size_type
typedef boost::graph_traits< G >::edges_size_type edges_size_type
typedef boost::graph_traits< G >::degree_size_type degree_size_type
Id handling related types
Type Meaning pgRouting Meaning
id_to_V maps id -> V given an id store the V
LI Left Iterator iterates over id_to_V
typedef std::map< int64_t, V > id_to_V
typedef id_to_V::const_iterator LI
Public Member Functions
Pgr_lineGraph (graphType gtype)
std::vector< Line_vertex > extract_vertices ()
int64_t get_edge_id (V from, V to, double &distance) const
std::vector< Line_graph_rt > get_postgres_results_directed ()
std::vector< Line_graph_rt > get_postgres_results_undirected ()
void graph_add_edge (const T_E &edge)
template<typename T >
void graph_add_edge (const T &edge)
template<typename T >
void graph_add_edge_no_create_vertex (const T &edge)
Use this function when the vertices are already inserted in the graph.
template<typename T >
void insert_vertices (const T *edges, int64_t count)
template<typename T >
void insert_vertices (const std::vector< T > &edges)
int64_t num_edges () const
size_t num_vertices () const
void transform (pgrouting::DirectedGraph &digraph)
Insert edges
template<typename T >
void insert_edges (const T *edges, int64_t count)
Inserts count edges of type T into the graph.
template<typename T >
void insert_edges (T *edges, int64_t count, bool)
template<typename T >
void insert_edges (const std::vector< T > &edges)
Inserts count edges of type pgr_edge_t into the graph.
boost wrappers with original id
degree_size_type out_degree (int64_t vertex_id) const
get the out-degree of a vertex
degree_size_type in_degree (int64_t vertex_id) const
V get_V (const T_V &vertex)
get the vertex descriptor of the vertex
V get_V (int64_t vid) const
get the vertex descriptor of the vid
bool has_vertex (int64_t vid) const
True when vid is in the graph.
boost wrappers with V
degree_size_type out_degree (V &v) const
out degree of a vertex
degree_size_type in_degree (V &v) const
in degree of a vertex
T_E & operator[] (E e_idx)
const T_E & operator[] (E e_idx) const
T_V & operator[] (V v_idx)
const T_V & operator[] (V v_idx) const
V source (E e_idx) const
V target (E e_idx) const
V adjacent (V v_idx, E e_idx) const
to be or not to be
bool is_directed () const
bool is_undirected () const
bool is_source (V v_idx, E e_idx) const
bool is_target (V v_idx, E e_idx) const
edge disconection/reconnection
void disconnect_edge (int64_t p_from, int64_t p_to)
Disconnects all edges from p_from to p_to.
void disconnect_out_going_edge (int64_t vertex_id, int64_t edge_id)
Disconnects the outgoing edges of a vertex.
void disconnect_vertex (int64_t p_vertex)
Disconnects all incoming and outgoing edges from the vertex.
void disconnect_vertex (V vertex)
void restore_graph ()
Reconnects all edges that were removed.
Public Attributes
std::ostringstream log
The Graph
G graph
The graph.
size_t m_num_vertices
local count.
graphType m_gType
type (DIRECTED or UNDIRECTED)
Graph Modification
std::deque< T_E > removed_edges
Used for storing the removed_edges.
Private Member Functions
void add_vertices (std::vector< T_V > vertices)
void create_edges (const pgrouting::DirectedGraph &digraph)
template<typename T >
void graph_add_edge (int64_t, const T &source, const T &target, int64_t, int64_t)
Private Attributes
std::map< int64_t, pgr_edge_t > m_edges
int64_t m_num_edges
std::map< std::pair< int64_t, int64_t >, int64_t > m_vertex_map
Friends
std::ostream & operator<< (std::ostream &log, const Pgr_lineGraph< G, T_V, T_E > &g)
Id mapping handling
typedef std::map< V, size_t > IndexMap
id_to_V vertices_map
id -> graph id
boost::property_map< G, boost::vertex_index_t >::type vertIndex
IndexMap mapIndex
boost::associative_property_map< IndexMap > propmapIndex
Detailed Description
template<class G, typename T_V, typename T_E>
class pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >
Definition at line 44 of file pgr_lineGraph.hpp.
Member Typedef Documentation
template<class G, typename T_V, typename T_E> typedef G pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::B_G inherited
Definition at line 273 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> typedef boost::graph_traits< G >::degree_size_type pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::degree_size_type inherited
Definition at line 288 of file pgr_base_graph.hpp.
template<class G , typename T_V , typename T_E > typedef boost::graph_traits< G >::edge_descriptor pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::E
Definition at line 87 of file pgr_lineGraph.hpp.
template<class G, typename T_V, typename T_E> typedef boost::graph_traits< G >::edge_iterator pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::E_i inherited
Definition at line 279 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> typedef boost::graph_traits< G >::edges_size_type pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::edges_size_type inherited
Definition at line 286 of file pgr_base_graph.hpp.
template<class G , typename T_V , typename T_E > typedef boost::graph_traits< G >::in_edge_iterator pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::EI_i
Definition at line 90 of file pgr_lineGraph.hpp.
template<class G , typename T_V , typename T_E > typedef boost::graph_traits< G >::out_edge_iterator pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::EO_i
Definition at line 89 of file pgr_lineGraph.hpp.
template<class G, typename T_V, typename T_E> typedef T_E pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::G_T_E inherited
Definition at line 274 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> typedef T_V pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::G_T_V inherited
Definition at line 275 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> typedef std::map< int64_t, V > pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::id_to_V inherited
Definition at line 300 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> typedef std::map<V, size_t> pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::IndexMap inherited
Definition at line 319 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> typedef id_to_V::const_iterator pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::LI inherited
Definition at line 301 of file pgr_base_graph.hpp.
template<class G , typename T_V , typename T_E > typedef boost::graph_traits< G >::vertex_descriptor pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::V
Definition at line 86 of file pgr_lineGraph.hpp.
template<class G , typename T_V , typename T_E > typedef boost::graph_traits< G >::vertex_iterator pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::V_i
Definition at line 88 of file pgr_lineGraph.hpp.
template<class G, typename T_V, typename T_E> typedef boost::graph_traits< G >::vertices_size_type pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::vertices_size_type inherited
Definition at line 284 of file pgr_base_graph.hpp.
Constructor & Destructor Documentation
template<class G , typename T_V , typename T_E > pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::Pgr_lineGraph (graphType gtype) inline explicit
Definition at line 94 of file pgr_lineGraph.hpp.
          : Pgr_base_graph< G, T_V, T_E >(gtype),
            m_num_edges(0) {
          }
Member Function Documentation
template<class G , typename T_V , typename T_E > void pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::add_vertices (std::vector< T_V > vertices) private
Definition at line 574 of file pgr_lineGraph.hpp.
References pgassert.
{
      for (const auto vertex : vertices) {
          pgassert(this->vertices_map.find(vertex.id) == this->vertices_map.end());
          auto v =  add_vertex(this->graph);
          this->vertices_map[vertex.id] = v;
          this->graph[v].cp_members(vertex);
          pgassert(boost::num_vertices(this->graph) == this->num_vertices());
      }
      return;
  }
template<class G, typename T_V, typename T_E> V pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::adjacent (V v_idx, E e_idx) const inline inherited
Definition at line 579 of file pgr_base_graph.hpp.
References pgassert.
{
          pgassert(is_source(v_idx, e_idx) || is_target(v_idx, e_idx));
          return is_source(v_idx, e_idx)?
              target(e_idx) :
              source(e_idx);
      }
template<class G , typename T_V , typename T_E > void pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::create_edges (const pgrouting::DirectedGraph & digraph) private
Definition at line 514 of file pgr_lineGraph.hpp.
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::graph, pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::source(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::target().
{
     V_i vertexIt, vertexEnd;
     EO_i e_outIt, e_outEnd;
     EI_i e_inIt, e_inEnd;
     /*
     for (each vertex v in original graph) {
        for( all incoming edges inn to vertex v) {
               for( all outgoing edges outt from vertex v) {
                      create an edge in the line graph(inn, outt);
              }
        }
    }
     */
     for(boost::tie(vertexIt, vertexEnd) = boost::vertices(digraph.graph);
             vertexIt != vertexEnd; vertexIt++) {
         V vertex = *vertexIt;
         for (boost::tie(e_outIt, e_outEnd) = boost::out_edges(vertex, digraph.graph);
                 e_outIt != e_outEnd; e_outIt++) {
             for (boost::tie(e_inIt, e_inEnd) = boost::in_edges(vertex, digraph.graph);
                     e_inIt != e_inEnd; e_inIt++) {
 #if 0
                 log << "\n";
                 log << digraph.graph[*inIt].id << " | " << digraph[digraph.source(*inIt)].id << " | " << digraph[digraph.target(*inIt)].id << " | " << digraph.graph[*inIt].cost << "\n";
                 log << digraph.graph[*outIt].id << " | " << digraph[digraph.source(*outIt)].id << " | " << digraph[digraph.target(*outIt)].id << " | " << digraph.graph[*outIt].cost << "\n\n";
 #endif
                 /*
                 Prevent self-edges from being created in the Line Graph
                 */
                 if (labs(digraph.graph[*e_inIt].id) == labs(digraph.graph[*e_outIt].id))
                     continue;
                 auto source_in_edge = digraph.source(*e_inIt);
 #if 0
                 log << "source = " << digraph[source_in_edge] << " | mid = " << digraph[vertex] << "\n\n\n";
 #endif
                 ++m_num_edges;
                 graph_add_edge(
                     m_num_edges,
                     (digraph.graph[*e_inIt]).id,
                     (digraph.graph[*e_outIt]).id,
                     digraph[source_in_edge].id,
                     digraph[vertex].id
                 );
             }
         }
     }
 }
template<class G , typename T_V , typename T_E > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::disconnect_edge (int64_t p_from, int64_t p_to) inherited
Disconnects all edges from p_from to p_to.
No edge is disconnected if the vertices id's do not exist in the graph
All removed edges are stored for future reinsertion
All parallel edges are disconnected (automatically by boost)
disconnect_edge(2,3) on an UNDIRECTED graph
disconnect_edge(2,3) on a DIRECTED graph
Parameters
[in] p_from original vertex id of the starting point of the edge
[in] p_to original vertex id of the ending point of the edge
Definition at line 748 of file pgr_base_graph.hpp.
Referenced by pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::get_postgres_results_directed().
{
     T_E d_edge;
     // nothing to do, the vertex doesn't exist
     if (!has_vertex(p_from) || !has_vertex(p_to)) return;
     EO_i out, out_end;
     V g_from(get_V(p_from));
     V g_to(get_V(p_to));
     // store the edges that are going to be removed
     for (boost::tie(out, out_end) = out_edges(g_from, graph);
             out != out_end; ++out) {
         if (target(*out) == g_to) {
             d_edge.id = graph[*out].id;
             d_edge.source = graph[source(*out)].id;
             d_edge.target = graph[target(*out)].id;
             d_edge.cost = graph[*out].cost;
             removed_edges.push_back(d_edge);
         }
     }
     // the actual removal
     boost::remove_edge(g_from, g_to, graph);
 }
template<class G , typename T_V , typename T_E > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::disconnect_out_going_edge (int64_t vertex_id, int64_t edge_id) inherited
Disconnects the outgoing edges of a vertex.
No edge is disconnected if it doesn't exist in the graph
Removed edges are stored for future reinsertion
all outgoing edges with the edge_id are removed if they exist
Parameters
[in] vertex_id original vertex
[in] edge_id original edge_id
Definition at line 777 of file pgr_base_graph.hpp.
{
     T_E d_edge;
     // nothing to do, the vertex doesn't exist
     if (!has_vertex(vertex_id)) return;
     auto v_from(get_V(vertex_id));
     EO_i out, out_end;
     bool change = true;
     // store the edge that are going to be removed
     while (change) {
         change = false;
         for (boost::tie(out, out_end) = out_edges(v_from, graph);
                 out != out_end; ++out) {
             if (graph[*out].id  == edge_id) {
                 d_edge.id = graph[*out].id;
                 d_edge.source = graph[source(*out)].id;
                 d_edge.target = graph[target(*out)].id;
                 d_edge.cost = graph[*out].cost;
                 removed_edges.push_back(d_edge);
                 boost::remove_edge((*out), graph);
                 change = true;
                 break;
             }
         }
     }
 }
template<class G , typename T_V , typename T_E > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::disconnect_vertex (int64_t p_vertex) inherited
Disconnects all incoming and outgoing edges from the vertex.
boost::graph doesn't recommend th to insert/remove vertices, so a vertex removal is simulated by disconnecting the vertex from the graph
No edge is disconnected if the vertices id's do not exist in the graph
All removed edges are stored for future reinsertion
All parallel edges are disconnected (automatically by boost)
disconnect_vertex(2) on an UNDIRECTED graph
disconnect_vertex(2) on a DIRECTED graph
Parameters
[in] p_vertex original vertex id of the starting point of the edge
Definition at line 809 of file pgr_base_graph.hpp.
{
     if (!has_vertex(vertex)) return;
     disconnect_vertex(get_V(vertex));
 }
template<class G , typename T_V , typename T_E > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::disconnect_vertex (V vertex) inherited
Definition at line 816 of file pgr_base_graph.hpp.
References DIRECTED.
{
     T_E d_edge;
     EO_i out, out_end;
     // store the edges that are going to be removed
     for (boost::tie(out, out_end) = out_edges(vertex, graph);
             out != out_end; ++out) {
         d_edge.id = graph[*out].id;
         d_edge.source = graph[source(*out)].id;
         d_edge.target = graph[target(*out)].id;
         d_edge.cost = graph[*out].cost;
         removed_edges.push_back(d_edge);
     }
     // special case
     if (m_gType == DIRECTED) {
         EI_i in, in_end;
         for (boost::tie(in, in_end) = in_edges(vertex, graph);
                 in != in_end; ++in) {
             d_edge.id = graph[*in].id;
             d_edge.source = graph[source(*in)].id;
             d_edge.target = graph[target(*in)].id;
             d_edge.cost = graph[*in].cost;
             removed_edges.push_back(d_edge);
         }
     }
     // delete incoming and outgoing edges from the vertex
     boost::clear_vertex(vertex, graph);
 }
template<class G , typename T_V , typename T_E > std::vector< Line_vertex > pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::extract_vertices ()
Definition at line 380 of file pgr_lineGraph.hpp.
References edge::cost, pgrouting::Line_vertex::cost, edge::id, pgrouting::Line_vertex::id, edge::reverse_cost, edge::source, pgrouting::Line_vertex::source, edge::target, pgrouting::Line_vertex::target, UNDIRECTED, and pgrouting::Line_vertex::vertex_id.
{
     /*
         m_vertex_map stores a unique id assigned to each vertex of Line Graph.
         In case of a directed edge, either 1 or 2 vertices are to be created in
         the Line Graph for each of the edges.
         Consider the following edge in directed graph:-
             ID = 1 | source = 2 | target = 3 | cost = 10 | reverse_cost = 20
         This creates 2 vertices in Line Graph:-
             1. ID = 1 | source = 2 | target = 3 | cost = 10
             2. ID = 1 | source = 3 | target = 2 | cost = 25
         So, the values stored in m_vertex_map would be:-
             1. {1, 2} = 1(Denoting the edge from 2 - > 3 of cost 10).
             2. {1, 3} = 2(Denoting the edge from 3 - > 2 of cost 25).
             where {key} = value in m_vertex_map.
         In case of undirected edge, either 2 or 4 vertices are to be created in
         the Line Graph for each of the edges.
         Consider the following edge in an undirected graph:-
             ID = 1 | source = 2 | target = 3 | cost = 10 | reverse_cost = 25
         This creates the following 4 vertices in Line Graph:-
             1. ID = 1 | source = 2 | target = 3 | cost = 10
             2. ID = 1 | source = 3 | target = 2 | cost = 10
             3. ID = 1 | source = 3 | target = 2 | cost = 25
             4. ID = 1 | source = 2 | target = 3 | cost = 25
         so, the values stored in m_vertex_map would be:-
             1. {1, 2} = 1(Denoting the edge from 2 - > 3 of cost 10).
             2. {-1, 3} = 2(Denoting the edge from 3 - > 2 of cost 10).
             3. {1, 3} = 3(Deonting the edge from 3 - > 2 of cost 25).
             4. {-1, 2} = 4(Denoting the edge from 2 - > 3 of cost 25).
             where {key} = value in m_vertex_map.
     */
     if (m_edges.empty()) return std::vector< Line_vertex >();
     std::vector< Line_vertex > vertices;
 #if 0
     log << "\nEdges of original graph\n";
 #endif
     for (const auto &it : m_edges) {
         auto edge = it.second;
         Line_vertex vertex(edge);
 #if 1
         log << "ID: " << edge.id;
         log << "| source: " << edge.source;
         log << "| target: " << edge.target;
         log << "| cost: " << edge.cost;
         log << "| reverse_cost: " << edge.reverse_cost << "\n\n";
 #endif
         if (edge.cost > 0) {
             vertex.id = (++(this->m_num_vertices));
             vertices.push_back(vertex);
             m_vertex_map[ std::pair<int64_t,int64_t>(edge.id, edge.source) ] = this->m_num_vertices;
             if (this->m_gType == UNDIRECTED) {
                 vertex.id = (++(this->m_num_vertices));
                 std::swap(vertex.source, vertex.target);
                 vertices.push_back(vertex);
                 m_vertex_map[std::pair<int64_t,int64_t>(-1*edge.id, edge.target)] = this->m_num_vertices;
                 std::swap(vertex.source, vertex.target);
             }
         }
         if (edge.reverse_cost > 0) {
             vertex.id = (++(this->m_num_vertices));
             vertex.cost = edge.reverse_cost;
             vertex.vertex_id *= -1;
             std::swap(vertex.source, vertex.target);
             vertices.push_back(vertex);
             m_vertex_map[ std::pair<int64_t,int64_t>(edge.id, edge.target) ] = this->m_num_vertices;
             if (this->m_gType == UNDIRECTED) {
                 vertex.id = (++(this->m_num_vertices));
                 std::swap(vertex.source, vertex.target);
                 vertices.push_back(vertex);
                 m_vertex_map[std::pair<int64_t,int64_t>(-1*edge.id, edge.source)] = this->m_num_vertices;
             }
         }
     }
 #if 0
     for (auto it: m_vertex_map) {
         log << it.first.first << " | " << it.first.second << " | " << it.second << "\n";
     }
 #endif
     return vertices;
 }
template<class G , typename T_V , typename T_E > int64_t pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::get_edge_id (V from, V to, double & distance) const inherited
Definition at line 859 of file pgr_base_graph.hpp.
{
     E e;
     EO_i out_i, out_end;
     V v_source, v_target;
     double minCost =  (std::numeric_limits<double>::max)();
     int64_t minEdge = -1;
     for (boost::tie(out_i, out_end) = boost::out_edges(from, graph);
             out_i != out_end; ++out_i) {
         e = *out_i;
         v_target = target(e);
         v_source = source(e);
         if ((from == v_source) && (to == v_target)
                 && (distance == graph[e].cost))
             return graph[e].id;
         if ((from == v_source) && (to == v_target)
                 && (minCost > graph[e].cost)) {
             minCost = graph[e].cost;
             minEdge = graph[e].id;
         }
     }
     distance = minEdge == -1? 0: minCost;
     return minEdge;
 }
template<class G , typename T_V , typename T_E > std::vector< Line_graph_rt > pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::get_postgres_results_directed ()
Definition at line 205 of file pgr_lineGraph.hpp.
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::disconnect_edge(), edges, and pgassert.
Referenced by do_pgr_lineGraph().
{
     std::vector< Line_graph_rt > results;
     typename boost::graph_traits < G >::edge_iterator edgeIt, edgeEnd;
     std::map < std::pair<int64_t,int64_t >, Line_graph_rt > unique;
     int64_t count = 0;
     log << "\nPostgres results\n";
     for (boost::tie(edgeIt, edgeEnd) = boost::edges(this->graph);
             edgeIt != edgeEnd; edgeIt++) {
         E e = *edgeIt;
         auto e_source = this->graph[this->source(e)].vertex_id;
         auto e_target = this->graph[this->target(e)].vertex_id;
         log << "e_source = " << e_source << " | e_target = " << e_target << "\n";
         if(unique.find( {e_target, e_source} ) != unique.end()) {
             unique[ std::pair<int64_t,int64_t>(e_target, e_source) ].reverse_cost = 1.0;
             continue;
         }
         e_source *= -1;
         e_target *= -1;
         if(unique.find( {e_target, e_source} ) != unique.end()) {
             unique[ std::pair<int64_t,int64_t>(e_target, e_source) ].reverse_cost = 1.0;
             continue;
         }
         e_source *= -1;
         e_target *= -1;
         Line_graph_rt edge = {
             ++count,
             e_source,
             e_target,
             1.0,
             -1.0
         };
         unique[ std::pair<int64_t,int64_t>(e_source, e_target)] = edge;
     }
     for (const auto &edge: unique) {
         results.push_back(edge.second);
     }
     return results;
 }
template<class G , typename T_V , typename T_E > std::vector< Line_graph_rt > pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::get_postgres_results_undirected ()
Definition at line 175 of file pgr_lineGraph.hpp.
References edges.
Referenced by do_pgr_lineGraph().
{
     std::vector< Line_graph_rt > results;
     typename boost::graph_traits < G >::edge_iterator edgeIt, edgeEnd;
     int64_t count = 0;
     log << "\nPostgres results\n";
     for (boost::tie(edgeIt, edgeEnd) = boost::edges(this->graph);
             edgeIt != edgeEnd; edgeIt++) {
         E e = *edgeIt;
         auto e_source = this->graph[this->source(e)].vertex_id;
         auto e_target = this->graph[this->target(e)].vertex_id;
         log << "e_source = " << e_source << " | e_target = " << e_target << "\n";
         Line_graph_rt edge = {
             ++count,
             e_source,
             e_target,
             1.0,
             -1.0
         };
         results.push_back(edge);
     }
     return results;
 }
template<class G, typename T_V, typename T_E> V pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::get_V (const T_V & vertex) inline inherited
get the vertex descriptor of the vertex
When the vertex does not exist
creates a new vetex
Returns
V: The vertex descriptor of the vertex
Definition at line 527 of file pgr_base_graph.hpp.
Referenced by do_pgr_test_c_edges(), and pgrouting::graph::Pgr_componentsGraph< G, T_V, T_E >::graph_add_edge().
{
          auto vm_s(vertices_map.find(vertex.id));
          if (vm_s == vertices_map.end()) {
              auto v =  add_vertex(graph);
              graph[v].cp_members(vertex);
              vertices_map[vertex.id] =  v;
              put(propmapIndex, v, m_num_vertices++);
              return v;
          }
          return vm_s->second;
      }
template<class G, typename T_V, typename T_E> V pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::get_V (int64_t vid) const inline inherited
get the vertex descriptor of the vid
Call has_vertex(vid) before calling this function
Returns
V: The vertex descriptor of the vertex
Definition at line 545 of file pgr_base_graph.hpp.
References pgassert.
{
          pgassert(has_vertex(vid));
          return vertices_map.find(vid)->second;
      }
template<class G , typename T_V , typename T_E > template<typename T > void pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::graph_add_edge (int64_t _id, const T & source, const T & target, int64_t source_in_edge, int64_t source_out_edge) private
Definition at line 473 of file pgr_lineGraph.hpp.
References pgassert.
{
     bool inserted;
     typename Pgr_base_graph< G, T_V, T_E >::E e;
     pgassert(m_vertex_map.find( {source, source_in_edge} ) !=
         m_vertex_map.end());
     pgassert(m_vertex_map.find( {target, source_out_edge} ) !=
             m_vertex_map.end());
     auto index_source_edge = m_vertex_map[ std::pair<int64_t,int64_t>(source, source_in_edge) ];
     auto index_target_edge = m_vertex_map[ std::pair<int64_t,int64_t>(target, source_out_edge) ];
 #if 0
     log << "\nsource_in_edge = " << source_in_edge << " | "
         << "source_out_edge = " << source_out_edge << " | "
         << "index_source_edge = " << index_source_edge << " | "
         << "index_target_edge = " << index_target_edge << " | "
         << "edge.source = " << source << " | "
         << "edge.target = " << target << "\n";
 #endif
     auto vm_s = this->get_V(index_source_edge);
     auto vm_t = this->get_V(index_target_edge);
     pgassert(this->vertices_map.find(index_source_edge) != this->vertices_map.end());
     pgassert(this->vertices_map.find(index_target_edge) != this->vertices_map.end());
     boost::tie(e, inserted) =
         boost::add_edge(vm_s, vm_t, this->graph);
     this->graph[e].id = _id;
 }
template<class G , typename T_V , typename T_E > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::graph_add_edge (const T_E & edge) inherited
Definition at line 889 of file pgr_base_graph.hpp.
{
     bool inserted;
     typename Pgr_base_graph< G, T_V, T_E >::LI vm_s, vm_t;
     typename Pgr_base_graph< G, T_V, T_E >::E e;
     vm_s = vertices_map.find(edge.source);
     if (vm_s == vertices_map.end()) {
         vertices_map[edge.source]=  m_num_vertices;
         vm_s = vertices_map.find(edge.source);
     }
     vm_t = vertices_map.find(edge.target);
     if (vm_t == vertices_map.end()) {
         vertices_map[edge.target]=  m_num_vertices;
         vm_t = vertices_map.find(edge.target);
     }
     if (edge.cost >= 0) {
         boost::tie(e, inserted) =
             boost::add_edge(vm_s->second, vm_t->second, graph);
         graph[e].cp_members(edge);
     }
 }
template<class G , typename T_V , typename T_E > template<typename T > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::graph_add_edge (const T & edge) inherited
Definition at line 917 of file pgr_base_graph.hpp.
References pgassert.
{
     bool inserted;
     typename Pgr_base_graph< G, T_V, T_E >::E e;
     if ((edge.cost < 0) && (edge.reverse_cost < 0))
         return;
     /*
      * true: for source
      * false: for target
      */
     auto vm_s = get_V(T_V(edge, true));
     auto vm_t = get_V(T_V(edge, false));
     pgassert(vertices_map.find(edge.source) != vertices_map.end());
     pgassert(vertices_map.find(edge.target) != vertices_map.end());
     if (edge.cost >= 0) {
         boost::tie(e, inserted) =
             boost::add_edge(vm_s, vm_t, graph);
         graph[e].cost = edge.cost;
         graph[e].id = edge.id;
     }
     if (edge.reverse_cost >= 0) {
         boost::tie(e, inserted) =
             boost::add_edge(vm_t, vm_s, graph);
         graph[e].cost = edge.reverse_cost;
         graph[e].id = edge.id;
     }
 }
template<class G, typename T_V, typename T_E> template<typename T > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::graph_add_edge_no_create_vertex (const T & edge) inline inherited
Use this function when the vertices are already inserted in the graph.
Definition at line 707 of file pgr_base_graph.hpp.
References pgassert, and pgassertwm.
{
          bool inserted;
          E e;
          if ((edge.cost < 0) && (edge.reverse_cost < 0))
              return;
 #if 0
          std::ostringstream log;
          for (auto iter = vertices_map.begin(); iter != vertices_map.end(); iter++) {
              log << "Key: " << iter->first <<"\tValue:" << iter->second << "\n";
          }
          pgassertwm(has_vertex(edge.source), log.str().c_str());
          pgassert(has_vertex(edge.target));
 #endif
          auto vm_s = get_V(edge.source);
          auto vm_t = get_V(edge.target);
          if (edge.cost >= 0) {
              boost::tie(e, inserted) =
                  boost::add_edge(vm_s, vm_t, graph);
              graph[e].cost = edge.cost;
              graph[e].id = edge.id;
          }
          if (edge.reverse_cost >= 0
                  && (is_directed() || (is_undirected() && edge.cost != edge.reverse_cost))) {
              boost::tie(e, inserted) =
                  boost::add_edge(vm_t, vm_s, graph);
              graph[e].cost = edge.reverse_cost;
              graph[e].id = edge.id;
          }
      }
template<class G, typename T_V, typename T_E> bool pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::has_vertex (int64_t vid) const inline inherited
True when vid is in the graph.
Definition at line 551 of file pgr_base_graph.hpp.
{
          return vertices_map.find(vid) != vertices_map.end();
      }
template<class G, typename T_V, typename T_E> degree_size_type pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::in_degree (int64_t vertex_id) const inline inherited
Definition at line 510 of file pgr_base_graph.hpp.
{
          if (!has_vertex(vertex_id)) {
              return 0;
          }
          return is_directed()?
              in_degree(get_V(vertex_id))
              :  out_degree(get_V(vertex_id));
      }
template<class G, typename T_V, typename T_E> degree_size_type pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::in_degree (V & v) const inline inherited
in degree of a vertex
when its undirected there is no "concept" of in degree
out degree is returned
on directed in degree of vertex is returned
Definition at line 593 of file pgr_base_graph.hpp.
{
          return is_directed()?
              boost::in_degree(v, graph) :
              boost::out_degree(v, graph);
      }
template<class G, typename T_V, typename T_E> template<typename T > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::insert_edges (const T * edges, int64_t count) inline inherited
Inserts count edges of type T into the graph.
Converts the edges to a std::vector<T> & calls the overloaded twin function.
Parameters
edges
count
Definition at line 398 of file pgr_base_graph.hpp.
Referenced by do_pgr_astarManyToMany(), do_pgr_bdAstar(), do_pgr_bdDijkstra(), do_pgr_dijkstraTRSP(), do_pgr_dijkstraVia(), do_pgr_driving_many_to_dist(), do_pgr_floydWarshall(), do_pgr_johnson(), do_pgr_ksp(), do_pgr_lineGraph(), do_pgr_many_to_many_dijkstra(), do_pgr_many_withPointsDD(), do_pgr_strongComponents(), do_pgr_test_c_edges(), do_pgr_testXYedges(), do_pgr_withPoints(), and do_pgr_withPointsKsp().
{
              insert_edges(std::vector < T >(edges, edges + count));
          }
template<class G, typename T_V, typename T_E> template<typename T > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::insert_edges (T * edges, int64_t count, bool) inline inherited
Definition at line 403 of file pgr_base_graph.hpp.
References pgassert.
{
              for (int64_t i = 0; i < count; ++i) {
                  pgassert(has_vertex(edges[i].source));
                  pgassert(has_vertex(edges[i].target));
                  graph_add_edge_no_create_vertex(edges[i]);
              }
          }
template<class G, typename T_V, typename T_E> template<typename T > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::insert_edges (const std::vector< T > & edges) inline inherited
Inserts count edges of type pgr_edge_t into the graph.
The set of edges should not have an illegal vertex defined
When the graph is empty calls:
extract_vertices and throws an exception if there are illegal vertices.
When developing:
if an illegal vertex is found an exception is thrown
That means that the set of vertices should be checked in the code that is being developed
No edge is inserted when there is an error on the vertices
Parameters
edges
Definition at line 431 of file pgr_base_graph.hpp.
References pgrouting::check_vertices(), pgrouting::extract_vertices(), and pgassert.
{
 #if 0
              // This code does not work with contraction
              if (num_vertices() == 0) {
                  auto vertices = pgrouting::extract_vertices(edges);
                  pgassert(pgrouting::check_vertices(vertices) == 0);
                  add_vertices(vertices);
              }
 #endif
              for (const auto edge : edges) {
                  graph_add_edge(edge);
              }
          }
template<class G , typename T_V , typename T_E > template<typename T > void pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::insert_vertices (const T * edges, int64_t count) inline
Definition at line 100 of file pgr_lineGraph.hpp.
Referenced by Pgr_dijkstraTRSP< G >::dijkstraTRSP(), and do_pgr_lineGraph().
{
             insert_vertices(std::vector < T >(edges, edges + count));
         }
template<class G , typename T_V , typename T_E > template<typename T > void pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::insert_vertices (const std::vector< T > & edges) inline
Definition at line 105 of file pgr_lineGraph.hpp.
References pgrouting::extract_vertices().
{
             for (auto &it: edges)
                 m_edges[it.id] = it;
             std::vector < Line_vertex > vertices = extract_vertices();
 #if 1
             log << "\nVertices of line graph: \n";
             for (auto vertex: vertices) {
                 log << vertex.id << "(" << vertex.source << " - > ";
                 log << vertex.target << ")" << vertex.cost << "\n";
             }
 #endif
             add_vertices(vertices);
         }
template<class G, typename T_V, typename T_E> bool pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::is_directed () const inline inherited
Definition at line 560 of file pgr_base_graph.hpp.
References DIRECTED.
 {return m_gType == DIRECTED;}
template<class G, typename T_V, typename T_E> bool pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::is_source (V v_idx, E e_idx) const inline inherited
Definition at line 562 of file pgr_base_graph.hpp.
 {return v_idx == source(e_idx);}
template<class G, typename T_V, typename T_E> bool pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::is_target (V v_idx, E e_idx) const inline inherited
Definition at line 563 of file pgr_base_graph.hpp.
 {return v_idx == target(e_idx);}
template<class G, typename T_V, typename T_E> bool pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::is_undirected () const inline inherited
Definition at line 561 of file pgr_base_graph.hpp.
References UNDIRECTED.
 {return m_gType == UNDIRECTED;}
template<class G , typename T_V , typename T_E > int64_t pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::num_edges () const inline
Definition at line 148 of file pgr_lineGraph.hpp.
 { return m_num_edges; }
template<class G, typename T_V, typename T_E> size_t pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::num_vertices () const inline inherited
Definition at line 696 of file pgr_base_graph.hpp.
 { return boost::num_vertices(graph);}
template<class G, typename T_V, typename T_E> T_E& pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::operator[] (E e_idx) inline inherited
Definition at line 571 of file pgr_base_graph.hpp.
 {return graph[e_idx];}
template<class G, typename T_V, typename T_E> const T_E& pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::operator[] (E e_idx) const inline inherited
Definition at line 572 of file pgr_base_graph.hpp.
 {return graph[e_idx];}
template<class G, typename T_V, typename T_E> T_V& pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::operator[] (V v_idx) inline inherited
Definition at line 574 of file pgr_base_graph.hpp.
 {return graph[v_idx];}
template<class G, typename T_V, typename T_E> const T_V& pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::operator[] (V v_idx) const inline inherited
Definition at line 575 of file pgr_base_graph.hpp.
 {return graph[v_idx];}
template<class G, typename T_V, typename T_E> degree_size_type pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::out_degree (int64_t vertex_id) const inline inherited
get the out-degree of a vertex
Returns
0: The out degree of a vertex that its not in the graph
Parameters
[in] vertex_id original vertex id
Definition at line 504 of file pgr_base_graph.hpp.
{
          if (!has_vertex(vertex_id)) {
              return 0;
          }
          return out_degree(get_V(vertex_id));
      }
template<class G, typename T_V, typename T_E> degree_size_type pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::out_degree (V & v) const inline inherited
out degree of a vertex
regardles of undirected or directed graph
out degree is returned
Definition at line 604 of file pgr_base_graph.hpp.
{
          return boost::out_degree(v, graph);
      }
template<class G , typename T_V , typename T_E > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::restore_graph () inherited
Reconnects all edges that were removed.
Definition at line 849 of file pgr_base_graph.hpp.
{
     while (removed_edges.size() != 0) {
         graph_add_edge(removed_edges[0]);
         removed_edges.pop_front();
     }
 }
template<class G, typename T_V, typename T_E> V pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::source (E e_idx) const inline inherited
Definition at line 577 of file pgr_base_graph.hpp.
Referenced by pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::create_edges().
 {return boost::source(e_idx, graph);}
template<class G, typename T_V, typename T_E> V pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::target (E e_idx) const inline inherited
Definition at line 578 of file pgr_base_graph.hpp.
Referenced by pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::create_edges().
 {return boost::target(e_idx, graph);}
template<class G , typename T_V , typename T_E > void pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::transform (pgrouting::DirectedGraph & digraph) inline
Definition at line 140 of file pgr_lineGraph.hpp.
Referenced by Pgr_dijkstraTRSP< G >::dijkstraTRSP(), and do_pgr_lineGraph().
{
         create_edges(digraph);
     }
Friends And Related Function Documentation
template<class G , typename T_V , typename T_E > std::ostream& operator<< (std::ostream & log, const Pgr_lineGraph< G, T_V, T_E > & g) friend
Definition at line 152 of file pgr_lineGraph.hpp.
{
         typename Pgr_base_graph< G, T_V, T_E >::EO_i out, out_end;
         for (auto vi = vertices(g.graph).first;
                 vi != vertices(g.graph).second; ++vi) {
             if ((*vi) >= g.m_num_vertices) break;
             log << (*vi) << ": " << " out_edges_of(" << g.graph[(*vi)] << "):";
             for (boost::tie(out, out_end) = out_edges(*vi, g.graph);
                     out != out_end; ++out) {
                 log << ' '
                     << g.graph[*out].id << "=("
                     << g[g.source(*out)].id << ", "
                     << g[g.target(*out)].id << ")\t";
             }
             log << std::endl;
         }
         return log;
     }
Member Data Documentation
template<class G, typename T_V, typename T_E> G pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::graph inherited
The graph.
Definition at line 307 of file pgr_base_graph.hpp.
Referenced by pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::create_edges().
template<class G , typename T_V , typename T_E > std::ostringstream pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::log
Definition at line 92 of file pgr_lineGraph.hpp.
Referenced by do_pgr_lineGraph().
template<class G , typename T_V , typename T_E > std::map< int64_t, pgr_edge_t > pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::m_edges private
Definition at line 59 of file pgr_lineGraph.hpp.
template<class G, typename T_V, typename T_E> graphType pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::m_gType inherited
type (DIRECTED or UNDIRECTED)
Definition at line 309 of file pgr_base_graph.hpp.
template<class G , typename T_V , typename T_E > int64_t pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::m_num_edges private
Definition at line 58 of file pgr_lineGraph.hpp.
template<class G, typename T_V, typename T_E> size_t pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::m_num_vertices inherited
local count.
Definition at line 308 of file pgr_base_graph.hpp.
Referenced by do_pgr_lineGraph().
template<class G , typename T_V , typename T_E > std::map< std::pair< int64_t, int64_t >, int64_t > pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::m_vertex_map private
Definition at line 60 of file pgr_lineGraph.hpp.
template<class G, typename T_V, typename T_E> IndexMap pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::mapIndex inherited
Definition at line 320 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> boost::associative_property_map<IndexMap> pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::propmapIndex inherited
Definition at line 321 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> std::deque< T_E > pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::removed_edges inherited
Used for storing the removed_edges.
Definition at line 329 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> id_to_V pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::vertices_map inherited
id -> graph id
Definition at line 315 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> boost::property_map<G, boost::vertex_index_t>::type pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::vertIndex inherited
Definition at line 317 of file pgr_base_graph.hpp.
The documentation for this class was generated from the following file:
/home/vicky/pgrouting/pgrouting/pgrouting/include/lineGraph/pgr_lineGraph.hpp