PGROUTING: pgrouting::vrp::pickdeliver::Base_node Class Reference
pgrouting::vrp::pickdeliver::Base_node Class Reference abstract
The Base_node class defines the operations that can be performed in a 2D node.
#include "base_node.h"
Public Member Functions
Base_node ()=default
Base_node (size_t, int64_t)
int64_t id () const
size_t idx () const
virtual void print (std::ostream &os) const
void reset_id (int64_t)
to be or not to be
virtual bool isSamePos (const Base_node &other) const
@ {
virtual bool operator== (const Base_node &rhs) const
distance
virtual double distance (const Base_node &node) const =0
virtual double comparable_distance (const Base_node &other) const
Friends
std::ostream & operator<< (std::ostream &log, const Base_node &node)
Detailed Description
The Base_node class defines the operations that can be performed in a 2D node.
A Base_node is an identifier of a Node or Dnode.
Definition at line 51 of file base_node.h.
Constructor & Destructor Documentation
pgrouting::vrp::pickdeliver::Base_node::Base_node () default
pgrouting::vrp::pickdeliver::Base_node::Base_node (size_t _idx, int64_t _id)
Definition at line 74 of file base_node.cpp.
     : Identifier(_idx, _id) {
     }
Member Function Documentation
double pgrouting::vrp::pickdeliver::Base_node::comparable_distance (const Base_node & other) const virtual
Definition at line 69 of file base_node.cpp.
{
     return 0;
 }
virtual double pgrouting::vrp::pickdeliver::Base_node::distance (const Base_node & node) const pure virtual
Implemented in pgrouting::vrp::pickdeliver::Node.
int64_t pgrouting::Identifier::id () const inherited
Definition at line 42 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::vrp::Vehicle::is_phony(), isSamePos(), pgrouting::vrp::Optimize::move_reduce_cost(), pgrouting::operator<<(), pgrouting::vrp::operator<<(), pgrouting::vrp::pickdeliver::Node::operator==(), operator==(), pgrouting::vrp::pickdeliver::Node::print(), and print().
                      {
     return m_id;
 }
size_t pgrouting::Identifier::idx () const inherited
Definition at line 37 of file identifier.cpp.
References pgrouting::Identifier::m_idx.
Referenced by pgrouting::vrp::Vehicle_pickDeliver::erase(), pgrouting::vrp::Vehicle::erase(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Vehicle_pickDeliver::has_order(), pgrouting::vrp::Vehicle::insert(), pgrouting::vrp::Vehicle_pickDeliver::insert(), pgrouting::vrp::Fleet::is_order_ok(), pgrouting::operator<<(), pgrouting::vrp::operator<<(), pgrouting::vrp::pickdeliver::Node::operator==(), operator==(), pgrouting::vrp::Tw_node::operator==(), pgrouting::vrp::Pgr_pickDeliver::order_of(), pgrouting::vrp::pickdeliver::Node::print(), print(), pgrouting::vrp::Vehicle_pickDeliver::push_back(), pgrouting::vrp::Vehicle_pickDeliver::push_front(), pgrouting::vrp::Order::set_compatibles(), pgrouting::vrp::Solution::sort_by_id(), pgrouting::vrp::Optimize::swap_worse(), pgrouting::vrp::Vehicle::tau(), and pgrouting::vrp::Tw_node::travel_time_to().
                       {
     return m_idx;
 }
bool pgrouting::vrp::pickdeliver::Base_node::isSamePos (const Base_node & other) const virtual
@ {
Definition at line 34 of file base_node.cpp.
References pgrouting::Identifier::id().
{
     return id() == rhs.id();
 }
bool pgrouting::vrp::pickdeliver::Base_node::operator== (const Base_node & rhs) const virtual
Definition at line 79 of file base_node.cpp.
References pgrouting::Identifier::id(), and pgrouting::Identifier::idx().
{
     if (&rhs == this) return true;
     return
         (idx() == rhs.idx())
          && (id() == rhs.id());
 }
void pgrouting::vrp::pickdeliver::Base_node::print (std::ostream & os) const virtual
Reimplemented in pgrouting::vrp::pickdeliver::Node.
Definition at line 56 of file base_node.cpp.
References pgrouting::Identifier::id(), and pgrouting::Identifier::idx().
Referenced by pgrouting::vrp::pickdeliver::operator<<().
{
     os << "USING BASE_NODE\n";
     os << id()
         << "(" << idx() << ")";
 }
void pgrouting::Identifier::reset_id (int64_t _id) inherited
Definition at line 47 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Tw_node::Tw_node().
{
     m_id = _id;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & log, const Base_node & node) friend
Definition at line 50 of file base_node.cpp.
{
     node.print(log);
     return log;
 }
The documentation for this class was generated from the following files:
/home/vicky/pgrouting/pgrouting/pgrouting/include/vrp/base_node.h
/home/vicky/pgrouting/pgrouting/pgrouting/src/pickDeliverE/src/base_node.cpp