PGROUTING: pgrouting::vrp::pickdeliver::Node Class Reference
pgrouting::vrp::pickdeliver::Node Class Reference
The Node class defines a point in 2D space with an id.
#include "node.h"
Public Member Functions
Node ()=default
Node (size_t id, int64_t original_id, double _x, double _y)
int64_t id () const
size_t idx () const
void reset_id (int64_t)
to be or not to be
virtual bool isSamePos (const Base_node &other) const
@ {
virtual bool operator== (const Base_node &rhs) const
distance
virtual double comparable_distance (const Base_node &other) const
Static Public Attributes
static Pgr_messages msg
Static Protected Attributes
static Pgr_pickDeliver * problem
state
pgrouting::Point m_point
bool isSamePos (const Node &other) const
@ {
bool operator== (const Node &rhs) const
double distance (const Node &) const
double distance (const Base_node *) const
double distance (const Base_node &) const
double comparable_distance (const Node &other) const
void print (std::ostream &os) const
std::ostream & operator<< (std::ostream &log, const Node &node)
Detailed Description
The Node class defines a point in 2D space with an id.
A Node is a point that defines a location in 2D space. It maintains a user id and an internal nid along with its x, y location. This is the base object that things like depots, customer locations, etc. are built upon.
Definition at line 51 of file node.h.
Constructor & Destructor Documentation
pgrouting::vrp::pickdeliver::Node::Node () default
pgrouting::vrp::pickdeliver::Node::Node (size_t id, int64_t original_id, double _x, double _y)
Definition at line 97 of file node.cpp.
     : Base_node(_idx, _id),
         m_point(_x, _y) {
     }
Member Function Documentation
double pgrouting::vrp::pickdeliver::Node::comparable_distance (const Node & other) const
Definition at line 90 of file node.cpp.
References m_point.
Referenced by isSamePos().
{
     auto dx = m_point.x() - other.m_point.x();
     auto dy = m_point.y() - other.m_point.y();
     return dx * dx + dy * dy;
 }
double pgrouting::vrp::pickdeliver::Base_node::comparable_distance (const Base_node & other) const virtual inherited
Definition at line 69 of file base_node.cpp.
{
     return 0;
 }
double pgrouting::vrp::pickdeliver::Node::distance (const Node & other) const
Definition at line 52 of file node.cpp.
References ENTERING, EXITING, pgrouting::Pgr_messages::log, m_point, and pgrouting::vrp::PD_problem::msg.
Referenced by pgrouting::vrp::PD_Orders::build_orders(), and distance().
{
     ENTERING();
     auto dx = m_point.x() - other.m_point.x();
     auto dy = m_point.y() - other.m_point.y();
     msg.log << *this << "\n";
     msg.log << other << "\n";
     msg.log << "dx: " << dx << "\n";
     msg.log << "dy: " << dx << "\n";
     msg.log << "d: " << sqrt(dx * dx + dy * dy) << "\n";
     EXITING();
     return sqrt(dx * dx + dy * dy);
 }
double pgrouting::vrp::pickdeliver::Node::distance (const Base_node * n) const
Definition at line 83 of file node.cpp.
References distance(), ENTERING, and EXITING.
{
     ENTERING();
     EXITING();
     return distance(*dynamic_cast<const Node*>(n));
 }
double pgrouting::vrp::pickdeliver::Node::distance (const Base_node & node) const virtual
Implements pgrouting::vrp::pickdeliver::Base_node.
Definition at line 66 of file node.cpp.
References ENTERING, EXITING, pgrouting::Pgr_messages::log, m_point, and pgrouting::vrp::PD_problem::msg.
{
     if (auto other = dynamic_cast<const Node*>(&node)) {
         ENTERING();
         auto dx = m_point.x() - other->m_point.x();
         auto dy = m_point.y() - other->m_point.y();
         msg.log << *this << "\n";
         msg.log << other << "\n";
         msg.log << "dx: " << dx << "\n";
         msg.log << "dy: " << dx << "\n";
         msg.log << "d: " << sqrt(dx * dx + dy * dy) << "\n";
         EXITING();
         return sqrt(dx * dx + dy * dy);
     }
     return 0;
 }
int64_t pgrouting::Identifier::id () const inherited
Definition at line 42 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::vrp::Vehicle::is_phony(), pgrouting::vrp::pickdeliver::Base_node::isSamePos(), pgrouting::vrp::Optimize::move_reduce_cost(), pgrouting::operator<<(), pgrouting::vrp::operator<<(), operator==(), pgrouting::vrp::pickdeliver::Base_node::operator==(), print(), and pgrouting::vrp::pickdeliver::Base_node::print().
                      {
     return m_id;
 }
size_t pgrouting::Identifier::idx () const inherited
Definition at line 37 of file identifier.cpp.
References pgrouting::Identifier::m_idx.
Referenced by pgrouting::vrp::Vehicle_pickDeliver::erase(), pgrouting::vrp::Vehicle::erase(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Vehicle_pickDeliver::has_order(), pgrouting::vrp::Vehicle::insert(), pgrouting::vrp::Vehicle_pickDeliver::insert(), pgrouting::vrp::Fleet::is_order_ok(), pgrouting::operator<<(), pgrouting::vrp::operator<<(), operator==(), pgrouting::vrp::pickdeliver::Base_node::operator==(), pgrouting::vrp::Tw_node::operator==(), pgrouting::vrp::Pgr_pickDeliver::order_of(), print(), pgrouting::vrp::pickdeliver::Base_node::print(), pgrouting::vrp::Vehicle_pickDeliver::push_back(), pgrouting::vrp::Vehicle_pickDeliver::push_front(), pgrouting::vrp::Order::set_compatibles(), pgrouting::vrp::Solution::sort_by_id(), pgrouting::vrp::Optimize::swap_worse(), pgrouting::vrp::Vehicle::tau(), and pgrouting::vrp::Tw_node::travel_time_to().
                       {
     return m_idx;
 }
bool pgrouting::vrp::pickdeliver::Node::isSamePos (const Node & other) const
@ {
Definition at line 34 of file node.cpp.
References comparable_distance().
{
     return comparable_distance(other) == 0;
 }
bool pgrouting::vrp::pickdeliver::Base_node::isSamePos (const Base_node & other) const virtual inherited
@ {
Definition at line 34 of file base_node.cpp.
References pgrouting::Identifier::id().
{
     return id() == rhs.id();
 }
bool pgrouting::vrp::pickdeliver::Node::operator== (const Node & rhs) const
Definition at line 103 of file node.cpp.
References pgrouting::Identifier::id(), pgrouting::Identifier::idx(), and m_point.
{
     if (&rhs == this) return true;
     return
         (idx() == rhs.idx())
          && (id() == rhs.id())
          && (m_point == rhs.m_point);
 }
bool pgrouting::vrp::pickdeliver::Base_node::operator== (const Base_node & rhs) const virtual inherited
Definition at line 79 of file base_node.cpp.
References pgrouting::Identifier::id(), and pgrouting::Identifier::idx().
{
     if (&rhs == this) return true;
     return
         (idx() == rhs.idx())
          && (id() == rhs.id());
 }
void pgrouting::vrp::pickdeliver::Node::print (std::ostream & os) const virtual
Reimplemented from pgrouting::vrp::pickdeliver::Base_node.
Definition at line 44 of file node.cpp.
References pgrouting::Identifier::id(), pgrouting::Identifier::idx(), and m_point.
Referenced by pgrouting::vrp::pickdeliver::operator<<().
{
     os << "USING NODE\n";
     os << id()
         << "(" << idx() << ")"
        << " (x,y) = (" << m_point.x() << ", " << m_point.y() << ")";
 }
void pgrouting::Identifier::reset_id (int64_t _id) inherited
Definition at line 47 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Tw_node::Tw_node().
{
     m_id = _id;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & log, const Node & node) friend
Definition at line 38 of file node.cpp.
{
     node.print(log);
     return log;
 }
Member Data Documentation
pgrouting::Point pgrouting::vrp::pickdeliver::Node::m_point protected
Definition at line 73 of file node.h.
Referenced by comparable_distance(), distance(), operator==(), and print().
Pgr_messages pgrouting::vrp::PD_problem::msg static inherited
Definition at line 48 of file pd_problem.h.
Referenced by pgrouting::vrp::Fleet::build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), distance(), do_pgr_pickDeliverEuclidean(), pgrouting::vrp::Initial_solution::do_while_foo(), pgrouting::vrp::Pgr_pickDeliver::get_postgres_result(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Fleet::is_fleet_ok(), pgrouting::vrp::Fleet::is_order_ok(), pgrouting::vrp::Optimize::move_reduce_cost(), pgrouting::vrp::Pgr_pickDeliver::node(), pgrouting::vrp::Pgr_pickDeliver::nodesOK(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), pgrouting::vrp::Pgr_pickDeliver::optimize(), pgrouting::vrp::PD_problem::PD_problem(), pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Optimize::save_if_best(), pgrouting::vrp::Pgr_pickDeliver::solve(), pgrouting::vrp::Optimize::swap_order(), and pgrouting::vrp::Optimize::swap_worse().
Pgr_pickDeliver * pgrouting::vrp::PD_problem::problem static protected inherited
Definition at line 51 of file pd_problem.h.
Referenced by pgrouting::vrp::Fleet::build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), pgrouting::vrp::Order::delivery(), pgrouting::vrp::operator<<(), pgrouting::vrp::Tw_node::operator==(), pgrouting::vrp::PD_problem::PD_problem(), pgrouting::vrp::Order::pickup(), and pgrouting::vrp::Tw_node::travel_time_to().
The documentation for this class was generated from the following files:
/home/vicky/pgrouting/pgrouting/pgrouting/include/vrp/node.h
/home/vicky/pgrouting/pgrouting/pgrouting/src/pickDeliverE/src/node.cpp