PGROUTING: pgrouting::vrp::Order Class Reference
pgrouting::vrp::Order Class Reference
#include "order.h"
Public Member Functions
int64_t id () const
size_t idx () const
void reset_id (int64_t)
Constructors
Order (size_t p_id, int64_t p_idx, const Vehicle_node &p_pickup, const Vehicle_node &p_deliver)
Order (const Order &)=default
Accessors
const Vehicle_node & delivery () const
The delivery node identifier.
const Vehicle_node & pickup () const
The delivery node identifier.
Identifiers< size_t > subsetJ (const Identifiers< size_t > &J) const
Get a subset of the orders that can be placed after this order.
Identifiers< size_t > subsetI (const Identifiers< size_t > &I) const
Modifiers
void set_compatibles (const Order order, double speed)
To be or not to be
bool is_valid (double speed) const
validate a pickup/delivery order
bool isCompatibleIJ (const Order &I, double speed) const
Can order I be placed before this order?
Static Public Attributes
static Pgr_messages msg
Static Protected Attributes
static Pgr_pickDeliver * problem
Private Attributes
size_t delivery_id
The delivery node identifier.
Identifiers< size_t > m_compatibleI
Stores all the orders that can be placed before this order.
Identifiers< size_t > m_compatibleJ
Stores all the orders that can be placed after this order.
size_t pickup_id
The pick up node identifier.
Friends
Friends
std::ostream & operator<< (std::ostream &, const Order &)
Detailed Description
Definition at line 43 of file order.h.
Constructor & Destructor Documentation
pgrouting::vrp::Order::Order (size_t p_id, int64_t p_idx, const Vehicle_node & p_pickup, const Vehicle_node & p_deliver)
Definition at line 48 of file order.cpp.
                                         :
     Identifier(p_idx, p_id),
     pickup_id(p_pickup.idx()),
     delivery_id(p_delivery.idx()) {
     }
pgrouting::vrp::Order::Order (const Order &) default
Member Function Documentation
const Vehicle_node & pgrouting::vrp::Order::delivery () const
The delivery node identifier.
It hold's the idx of the node
Definition at line 94 of file order.cpp.
References delivery_id, pgrouting::vrp::Pgr_pickDeliver::node(), and pgrouting::vrp::PD_problem::problem.
Referenced by pgrouting::vrp::Vehicle_pickDeliver::erase(), pgrouting::vrp::Vehicle_pickDeliver::insert(), is_valid(), isCompatibleIJ(), pgrouting::vrp::operator<<(), pgrouting::vrp::Vehicle_pickDeliver::push_back(), and pgrouting::vrp::Vehicle_pickDeliver::push_front().
                       {
     return problem->node(delivery_id);
 }
int64_t pgrouting::Identifier::id () const inherited
Definition at line 42 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::vrp::Vehicle::is_phony(), pgrouting::vrp::pickdeliver::Base_node::isSamePos(), pgrouting::vrp::Optimize::move_reduce_cost(), pgrouting::operator<<(), pgrouting::vrp::operator<<(), pgrouting::vrp::pickdeliver::Node::operator==(), pgrouting::vrp::pickdeliver::Base_node::operator==(), pgrouting::vrp::pickdeliver::Node::print(), and pgrouting::vrp::pickdeliver::Base_node::print().
                      {
     return m_id;
 }
size_t pgrouting::Identifier::idx () const inherited
Definition at line 37 of file identifier.cpp.
References pgrouting::Identifier::m_idx.
Referenced by pgrouting::vrp::Vehicle_pickDeliver::erase(), pgrouting::vrp::Vehicle::erase(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Vehicle_pickDeliver::has_order(), pgrouting::vrp::Vehicle::insert(), pgrouting::vrp::Vehicle_pickDeliver::insert(), pgrouting::vrp::Fleet::is_order_ok(), pgrouting::operator<<(), pgrouting::vrp::operator<<(), pgrouting::vrp::pickdeliver::Node::operator==(), pgrouting::vrp::pickdeliver::Base_node::operator==(), pgrouting::vrp::Tw_node::operator==(), pgrouting::vrp::Pgr_pickDeliver::order_of(), pgrouting::vrp::pickdeliver::Node::print(), pgrouting::vrp::pickdeliver::Base_node::print(), pgrouting::vrp::Vehicle_pickDeliver::push_back(), pgrouting::vrp::Vehicle_pickDeliver::push_front(), set_compatibles(), pgrouting::vrp::Solution::sort_by_id(), pgrouting::vrp::Optimize::swap_worse(), pgrouting::vrp::Vehicle::tau(), and pgrouting::vrp::Tw_node::travel_time_to().
                       {
     return m_idx;
 }
bool pgrouting::vrp::Order::is_valid (double speed) const
validate a pickup/delivery order
An order is valid when:
The pickup is well formed
The delivery is well formed
isCompatibleIJ to go to delivery after inmediatly visiting pickup
Definition at line 106 of file order.cpp.
References delivery(), pgrouting::vrp::Tw_node::is_compatible_IJ(), pgrouting::vrp::Tw_node::is_delivery(), pgrouting::vrp::Tw_node::is_pickup(), and pickup().
Referenced by pgrouting::vrp::Fleet::is_order_ok().
{
     return
         pickup().is_pickup()
         && delivery().is_delivery()
         /* IS P -> D */
         && delivery().is_compatible_IJ(pickup(), speed);
 }
bool pgrouting::vrp::Order::isCompatibleIJ (const Order & I, double speed) const
Can order I be placed before this order?
Parameters
[in] I order
[in] speed to be used for evaluating the order
Returns
true when order I can be placed before this order
Definition at line 147 of file order.cpp.
References delivery(), pgrouting::vrp::Tw_node::is_compatible_IJ(), and pickup().
Referenced by set_compatibles().
{
     /* this is true in all cases */
     auto all_cases(
             pickup().is_compatible_IJ(I.pickup(), speed)
             && delivery().is_compatible_IJ(I.pickup(), speed));
     /* case other(P) other(D) this(P) this(D) */
     auto case1(pickup().is_compatible_IJ(I.delivery(), speed)
             && delivery().is_compatible_IJ(I.delivery(), speed));
     /* case other(P) this(P) other(D) this(D) */
     auto case2(I.delivery().is_compatible_IJ(pickup(), speed)
             && delivery().is_compatible_IJ(I.delivery(), speed));
     /* case other(P) this(P) this(D) other(D) */
     auto case3(I.delivery().is_compatible_IJ(pickup(), speed)
             && I.delivery().is_compatible_IJ(delivery(), speed));
     return all_cases &&  (case1 ||  case2 ||  case3);
 }
const Vehicle_node & pgrouting::vrp::Order::pickup () const
The delivery node identifier.
It hold's the idx of the node
Definition at line 100 of file order.cpp.
References pgrouting::vrp::Pgr_pickDeliver::node(), pickup_id, and pgrouting::vrp::PD_problem::problem.
Referenced by pgrouting::vrp::Vehicle_pickDeliver::erase(), pgrouting::vrp::Vehicle_pickDeliver::insert(), is_valid(), isCompatibleIJ(), pgrouting::vrp::operator<<(), pgrouting::vrp::Vehicle_pickDeliver::push_back(), and pgrouting::vrp::Vehicle_pickDeliver::push_front().
                     {
     return problem->node(pickup_id);
 }
void pgrouting::Identifier::reset_id (int64_t _id) inherited
Definition at line 47 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Tw_node::Tw_node().
{
     m_id = _id;
 }
void pgrouting::vrp::Order::set_compatibles (const Order order, double speed)
Definition at line 123 of file order.cpp.
References pgrouting::Identifier::idx(), isCompatibleIJ(), m_compatibleI, and m_compatibleJ.
{
     if (J.idx() == idx()) return;
     if (J.isCompatibleIJ(*this, speed)) {
         /*
          * this -> {J}
          */
         m_compatibleJ += J.idx();
     }
     if (this->isCompatibleIJ(J, speed)) {
         /*
          * {J} -> this
          */
         m_compatibleI += J.idx();
     }
 }
Identifiers< size_t > pgrouting::vrp::Order::subsetI (const Identifiers< size_t > & I) const
Definition at line 38 of file order.cpp.
References m_compatibleI.
{
     return m_compatibleI * I;
 }
Identifiers< size_t > pgrouting::vrp::Order::subsetJ (const Identifiers< size_t > & J) const
Get a subset of the orders that can be placed after this order.
Parameters
[in] J set of orders
Returns
ithe set intersection of the J orders with the compatible_J orders of this order
Definition at line 43 of file order.cpp.
References m_compatibleJ.
{
     return m_compatibleJ * J;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & log, const Order & order) friend
Definition at line 58 of file order.cpp.
{
     log << "\n\nOrder " << order.idx() << ":\n"
         << "\tPickup: " << order.pickup() << "\n"
         << "\tDelivery: " << order.delivery() << "\n\n";
 #if 0
     if (order.delivery().is_partially_compatible_IJ(order.pickup(), speed)) {
         log << "\tis_partially_compatible_IJ: ";
     } else if (order.delivery().is_tight_compatible_IJ(order.pickup(), speed)) {
         log << "\tis_tight_compatible_IJ: ";
     } else if (order.delivery().is_waitTime_compatible_IJ(
                 order.pickup(), speed)) {
         log << "\tis_waitTime_compatible_IJ: ";
     } else {
         pgassert(false);
     }
 #endif
     log << "\nThere are | {I}| = "
         << order.m_compatibleI.size()
         << " -> order(" << order.idx()
         << ") -> | {J}| = " << order.m_compatibleJ.size()
         << "\n\n {";
     for (const auto o : order.m_compatibleI) {
         log << o << ", ";
     }
     log << "} -> " << order.idx() << " -> {";
     for (const auto o : order.m_compatibleJ) {
         log << o << ", ";
     }
     log << "}";
     return log;
 }
Member Data Documentation
size_t pgrouting::vrp::Order::delivery_id private
The delivery node identifier.
It hold's the idx of the node
Definition at line 152 of file order.h.
Referenced by delivery().
Identifiers<size_t> pgrouting::vrp::Order::m_compatibleI private
Stores all the orders that can be placed before this order.
Definition at line 183 of file order.h.
Referenced by pgrouting::vrp::operator<<(), set_compatibles(), and subsetI().
Identifiers<size_t> pgrouting::vrp::Order::m_compatibleJ private
Stores all the orders that can be placed after this order.
Todo:
TODO
compatibility changes based on the speed this is not taking that into account (here)
check where is it talking that into account
Definition at line 169 of file order.h.
Referenced by pgrouting::vrp::operator<<(), set_compatibles(), and subsetJ().
Pgr_messages pgrouting::vrp::PD_problem::msg static inherited
Definition at line 48 of file pd_problem.h.
Referenced by pgrouting::vrp::Fleet::build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), pgrouting::vrp::pickdeliver::Node::distance(), do_pgr_pickDeliverEuclidean(), pgrouting::vrp::Initial_solution::do_while_foo(), pgrouting::vrp::Pgr_pickDeliver::get_postgres_result(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Fleet::is_fleet_ok(), pgrouting::vrp::Fleet::is_order_ok(), pgrouting::vrp::Optimize::move_reduce_cost(), pgrouting::vrp::Pgr_pickDeliver::node(), pgrouting::vrp::Pgr_pickDeliver::nodesOK(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), pgrouting::vrp::Pgr_pickDeliver::optimize(), pgrouting::vrp::PD_problem::PD_problem(), pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Optimize::save_if_best(), pgrouting::vrp::Pgr_pickDeliver::solve(), pgrouting::vrp::Optimize::swap_order(), and pgrouting::vrp::Optimize::swap_worse().
size_t pgrouting::vrp::Order::pickup_id private
The pick up node identifier.
It hold's the idx of the node
Definition at line 146 of file order.h.
Referenced by pickup().
Pgr_pickDeliver * pgrouting::vrp::PD_problem::problem static protected inherited
Definition at line 51 of file pd_problem.h.
Referenced by pgrouting::vrp::Fleet::build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), delivery(), pgrouting::vrp::operator<<(), pgrouting::vrp::Tw_node::operator==(), pgrouting::vrp::PD_problem::PD_problem(), pickup(), and pgrouting::vrp::Tw_node::travel_time_to().
The documentation for this class was generated from the following files:
/home/vicky/pgrouting/pgrouting/pgrouting/include/vrp/order.h
/home/vicky/pgrouting/pgrouting/pgrouting/src/pickDeliverE/src/order.cpp