PGROUTING: pgrouting::graph::Pgr_componentsGraph< G, T_V, T_E > Class Template Reference
pgrouting::graph::Pgr_componentsGraph< G, T_V, T_E > Class Template Reference
#include "pgr_componentsGraph.hpp"
Public Types
Graph related types
Type boost meaning pgRouting meaning
G boost::adjacency_list Graph
V vertex_descriptor Think of it as local ID of a vertex
E edge_descriptor Think of it as local ID of an edge
V_i vertex_iterator To cycle the vertices of the Graph
E_i edge_iterator To cycle the edges of the Graph
EO_i out_edge_iterator To cycle the out going edges of a vertex
EI_i in_edge_iterator To cycle the in coming edges of a vertex (only in bidirectional graphs)
typedef G B_G
typedef T_E G_T_E
typedef T_V G_T_V
typedef boost::graph_traits< G >::vertex_descriptor V
typedef boost::graph_traits< G >::edge_descriptor E
typedef boost::graph_traits< G >::vertex_iterator V_i
typedef boost::graph_traits< G >::edge_iterator E_i
typedef boost::graph_traits< G >::out_edge_iterator EO_i
typedef boost::graph_traits< G >::in_edge_iterator EI_i
typedef boost::graph_traits< G >::vertices_size_type vertices_size_type
typedef boost::graph_traits< G >::edges_size_type edges_size_type
typedef boost::graph_traits< G >::degree_size_type degree_size_type
Id handling related types
Type Meaning pgRouting Meaning
id_to_V maps id -> V given an id store the V
LI Left Iterator iterates over id_to_V
typedef std::map< int64_t, V > id_to_V
typedef id_to_V::const_iterator LI
Public Member Functions
Pgr_componentsGraph (graphType gtype)
int64_t get_edge_id (V from, V to, double &distance) const
void graph_add_edge (const T_E &edge)
template<typename T >
void graph_add_edge_no_create_vertex (const T &edge)
Use this function when the vertices are already inserted in the graph.
template<typename T >
void insert_edges (const T *edges, int64_t count)
template<typename T >
void insert_edges (const std::vector< T > &edges)
size_t num_vertices () const
Insert edges
template<typename T >
void insert_edges (T *edges, int64_t count, bool)
boost wrappers with original id
degree_size_type out_degree (int64_t vertex_id) const
get the out-degree of a vertex
degree_size_type in_degree (int64_t vertex_id) const
V get_V (const T_V &vertex)
get the vertex descriptor of the vertex
V get_V (int64_t vid) const
get the vertex descriptor of the vid
bool has_vertex (int64_t vid) const
True when vid is in the graph.
boost wrappers with V
degree_size_type out_degree (V &v) const
out degree of a vertex
degree_size_type in_degree (V &v) const
in degree of a vertex
T_E & operator[] (E e_idx)
const T_E & operator[] (E e_idx) const
T_V & operator[] (V v_idx)
const T_V & operator[] (V v_idx) const
V source (E e_idx) const
V target (E e_idx) const
V adjacent (V v_idx, E e_idx) const
to be or not to be
bool is_directed () const
bool is_undirected () const
bool is_source (V v_idx, E e_idx) const
bool is_target (V v_idx, E e_idx) const
edge disconection/reconnection
void disconnect_edge (int64_t p_from, int64_t p_to)
Disconnects all edges from p_from to p_to.
void disconnect_out_going_edge (int64_t vertex_id, int64_t edge_id)
Disconnects the outgoing edges of a vertex.
void disconnect_vertex (int64_t p_vertex)
Disconnects all incoming and outgoing edges from the vertex.
void disconnect_vertex (V vertex)
void restore_graph ()
Reconnects all edges that were removed.
Public Attributes
G graph
The Graph
size_t m_num_vertices
local count.
graphType m_gType
type (DIRECTED or UNDIRECTED)
Graph Modification
std::deque< T_E > removed_edges
Used for storing the removed_edges.
Private Member Functions
template<typename T >
void graph_add_edge (const T &edge)
Id mapping handling
id_to_V vertices_map
id -> graph id
boost::property_map< G, boost::vertex_index_t >::type vertIndex
IndexMap mapIndex
boost::associative_property_map< IndexMap > propmapIndex
typedef std::map< V, size_t > IndexMap
Detailed Description
template<class G, typename T_V, typename T_E>
class pgrouting::graph::Pgr_componentsGraph< G, T_V, T_E >
Definition at line 45 of file pgr_componentsGraph.hpp.
Member Typedef Documentation
template<class G, typename T_V, typename T_E> typedef G pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::B_G inherited
Definition at line 273 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> typedef boost::graph_traits< G >::degree_size_type pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::degree_size_type inherited
Definition at line 288 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> typedef boost::graph_traits< G >::edge_descriptor pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::E inherited
Definition at line 277 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> typedef boost::graph_traits< G >::edge_iterator pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::E_i inherited
Definition at line 279 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> typedef boost::graph_traits< G >::edges_size_type pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::edges_size_type inherited
Definition at line 286 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> typedef boost::graph_traits< G >::in_edge_iterator pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::EI_i inherited
Definition at line 281 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> typedef boost::graph_traits< G >::out_edge_iterator pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::EO_i inherited
Definition at line 280 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> typedef T_E pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::G_T_E inherited
Definition at line 274 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> typedef T_V pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::G_T_V inherited
Definition at line 275 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> typedef std::map< int64_t, V > pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::id_to_V inherited
Definition at line 300 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> typedef std::map<V, size_t> pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::IndexMap inherited
Definition at line 319 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> typedef id_to_V::const_iterator pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::LI inherited
Definition at line 301 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> typedef boost::graph_traits< G >::vertex_descriptor pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::V inherited
Definition at line 276 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> typedef boost::graph_traits< G >::vertex_iterator pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::V_i inherited
Definition at line 278 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> typedef boost::graph_traits< G >::vertices_size_type pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::vertices_size_type inherited
Definition at line 284 of file pgr_base_graph.hpp.
Constructor & Destructor Documentation
template<class G , typename T_V , typename T_E > pgrouting::graph::Pgr_componentsGraph< G, T_V, T_E >::Pgr_componentsGraph (graphType gtype) inline explicit
Definition at line 62 of file pgr_componentsGraph.hpp.
          : Pgr_base_graph< G, T_V, T_E >(gtype) {
          }
Member Function Documentation
template<class G, typename T_V, typename T_E> V pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::adjacent (V v_idx, E e_idx) const inline inherited
Definition at line 579 of file pgr_base_graph.hpp.
References pgassert.
{
          pgassert(is_source(v_idx, e_idx) || is_target(v_idx, e_idx));
          return is_source(v_idx, e_idx)?
              target(e_idx) :
              source(e_idx);
      }
template<class G , typename T_V , typename T_E > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::disconnect_edge (int64_t p_from, int64_t p_to) inherited
Disconnects all edges from p_from to p_to.
No edge is disconnected if the vertices id's do not exist in the graph
All removed edges are stored for future reinsertion
All parallel edges are disconnected (automatically by boost)
disconnect_edge(2,3) on an UNDIRECTED graph
disconnect_edge(2,3) on a DIRECTED graph
Parameters
[in] p_from original vertex id of the starting point of the edge
[in] p_to original vertex id of the ending point of the edge
Definition at line 748 of file pgr_base_graph.hpp.
Referenced by pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::get_postgres_results_directed().
{
     T_E d_edge;
     // nothing to do, the vertex doesn't exist
     if (!has_vertex(p_from) || !has_vertex(p_to)) return;
     EO_i out, out_end;
     V g_from(get_V(p_from));
     V g_to(get_V(p_to));
     // store the edges that are going to be removed
     for (boost::tie(out, out_end) = out_edges(g_from, graph);
             out != out_end; ++out) {
         if (target(*out) == g_to) {
             d_edge.id = graph[*out].id;
             d_edge.source = graph[source(*out)].id;
             d_edge.target = graph[target(*out)].id;
             d_edge.cost = graph[*out].cost;
             removed_edges.push_back(d_edge);
         }
     }
     // the actual removal
     boost::remove_edge(g_from, g_to, graph);
 }
template<class G , typename T_V , typename T_E > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::disconnect_out_going_edge (int64_t vertex_id, int64_t edge_id) inherited
Disconnects the outgoing edges of a vertex.
No edge is disconnected if it doesn't exist in the graph
Removed edges are stored for future reinsertion
all outgoing edges with the edge_id are removed if they exist
Parameters
[in] vertex_id original vertex
[in] edge_id original edge_id
Definition at line 777 of file pgr_base_graph.hpp.
{
     T_E d_edge;
     // nothing to do, the vertex doesn't exist
     if (!has_vertex(vertex_id)) return;
     auto v_from(get_V(vertex_id));
     EO_i out, out_end;
     bool change = true;
     // store the edge that are going to be removed
     while (change) {
         change = false;
         for (boost::tie(out, out_end) = out_edges(v_from, graph);
                 out != out_end; ++out) {
             if (graph[*out].id  == edge_id) {
                 d_edge.id = graph[*out].id;
                 d_edge.source = graph[source(*out)].id;
                 d_edge.target = graph[target(*out)].id;
                 d_edge.cost = graph[*out].cost;
                 removed_edges.push_back(d_edge);
                 boost::remove_edge((*out), graph);
                 change = true;
                 break;
             }
         }
     }
 }
template<class G , typename T_V , typename T_E > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::disconnect_vertex (int64_t p_vertex) inherited
Disconnects all incoming and outgoing edges from the vertex.
boost::graph doesn't recommend th to insert/remove vertices, so a vertex removal is simulated by disconnecting the vertex from the graph
No edge is disconnected if the vertices id's do not exist in the graph
All removed edges are stored for future reinsertion
All parallel edges are disconnected (automatically by boost)
disconnect_vertex(2) on an UNDIRECTED graph
disconnect_vertex(2) on a DIRECTED graph
Parameters
[in] p_vertex original vertex id of the starting point of the edge
Definition at line 809 of file pgr_base_graph.hpp.
{
     if (!has_vertex(vertex)) return;
     disconnect_vertex(get_V(vertex));
 }
template<class G , typename T_V , typename T_E > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::disconnect_vertex (V vertex) inherited
Definition at line 816 of file pgr_base_graph.hpp.
References DIRECTED.
{
     T_E d_edge;
     EO_i out, out_end;
     // store the edges that are going to be removed
     for (boost::tie(out, out_end) = out_edges(vertex, graph);
             out != out_end; ++out) {
         d_edge.id = graph[*out].id;
         d_edge.source = graph[source(*out)].id;
         d_edge.target = graph[target(*out)].id;
         d_edge.cost = graph[*out].cost;
         removed_edges.push_back(d_edge);
     }
     // special case
     if (m_gType == DIRECTED) {
         EI_i in, in_end;
         for (boost::tie(in, in_end) = in_edges(vertex, graph);
                 in != in_end; ++in) {
             d_edge.id = graph[*in].id;
             d_edge.source = graph[source(*in)].id;
             d_edge.target = graph[target(*in)].id;
             d_edge.cost = graph[*in].cost;
             removed_edges.push_back(d_edge);
         }
     }
     // delete incoming and outgoing edges from the vertex
     boost::clear_vertex(vertex, graph);
 }
template<class G , typename T_V , typename T_E > int64_t pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::get_edge_id (V from, V to, double & distance) const inherited
Definition at line 859 of file pgr_base_graph.hpp.
{
     E e;
     EO_i out_i, out_end;
     V v_source, v_target;
     double minCost =  (std::numeric_limits<double>::max)();
     int64_t minEdge = -1;
     for (boost::tie(out_i, out_end) = boost::out_edges(from, graph);
             out_i != out_end; ++out_i) {
         e = *out_i;
         v_target = target(e);
         v_source = source(e);
         if ((from == v_source) && (to == v_target)
                 && (distance == graph[e].cost))
             return graph[e].id;
         if ((from == v_source) && (to == v_target)
                 && (minCost > graph[e].cost)) {
             minCost = graph[e].cost;
             minEdge = graph[e].id;
         }
     }
     distance = minEdge == -1? 0: minCost;
     return minEdge;
 }
template<class G, typename T_V, typename T_E> V pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::get_V (const T_V & vertex) inline inherited
get the vertex descriptor of the vertex
When the vertex does not exist
creates a new vetex
Returns
V: The vertex descriptor of the vertex
Definition at line 527 of file pgr_base_graph.hpp.
Referenced by do_pgr_test_c_edges(), and pgrouting::graph::Pgr_componentsGraph< G, T_V, T_E >::graph_add_edge().
{
          auto vm_s(vertices_map.find(vertex.id));
          if (vm_s == vertices_map.end()) {
              auto v =  add_vertex(graph);
              graph[v].cp_members(vertex);
              vertices_map[vertex.id] =  v;
              put(propmapIndex, v, m_num_vertices++);
              return v;
          }
          return vm_s->second;
      }
template<class G, typename T_V, typename T_E> V pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::get_V (int64_t vid) const inline inherited
get the vertex descriptor of the vid
Call has_vertex(vid) before calling this function
Returns
V: The vertex descriptor of the vertex
Definition at line 545 of file pgr_base_graph.hpp.
References pgassert.
{
          pgassert(has_vertex(vid));
          return vertices_map.find(vid)->second;
      }
template<class G , typename T_V , typename T_E > template<typename T > void pgrouting::graph::Pgr_componentsGraph< G, T_V, T_E >::graph_add_edge (const T & edge) inline private
Definition at line 81 of file pgr_componentsGraph.hpp.
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::get_V(), and pgassert.
{
         bool inserted;
         typename Pgr_base_graph< G, T_V, T_E >::E e;
         if ((edge.cost < 0) && (edge.reverse_cost < 0))
             return;
         /*
          * true: for source
          * false: for target
          */
         auto vm_s = Pgr_base_graph< G, T_V, T_E >::get_V(T_V(edge, true));
         auto vm_t = Pgr_base_graph< G, T_V, T_E >::get_V(T_V(edge, false));
         pgassert((Pgr_base_graph< G, T_V, T_E >::vertices_map).find(edge.source)
                  !=
                  (Pgr_base_graph< G, T_V, T_E >::vertices_map).end());
         pgassert((Pgr_base_graph< G, T_V, T_E >::vertices_map).find(edge.target)
                  !=
                  (Pgr_base_graph< G, T_V, T_E >::vertices_map).end());
         if (edge.cost >= 0) {
             boost::tie(e, inserted) =
                 boost::add_edge(vm_s, vm_t, graph);
             graph[e].cost = edge.cost;
             graph[e].id = edge.id;
         } else if (edge.reverse_cost >= 0) {
             boost::tie(e, inserted) =
                 boost::add_edge(vm_t, vm_s, graph);
             graph[e].cost = edge.reverse_cost;
             graph[e].id = edge.id;
         }
     }
template<class G , typename T_V , typename T_E > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::graph_add_edge (const T_E & edge) inherited
Definition at line 889 of file pgr_base_graph.hpp.
{
     bool inserted;
     typename Pgr_base_graph< G, T_V, T_E >::LI vm_s, vm_t;
     typename Pgr_base_graph< G, T_V, T_E >::E e;
     vm_s = vertices_map.find(edge.source);
     if (vm_s == vertices_map.end()) {
         vertices_map[edge.source]=  m_num_vertices;
         vm_s = vertices_map.find(edge.source);
     }
     vm_t = vertices_map.find(edge.target);
     if (vm_t == vertices_map.end()) {
         vertices_map[edge.target]=  m_num_vertices;
         vm_t = vertices_map.find(edge.target);
     }
     if (edge.cost >= 0) {
         boost::tie(e, inserted) =
             boost::add_edge(vm_s->second, vm_t->second, graph);
         graph[e].cp_members(edge);
     }
 }
template<class G, typename T_V, typename T_E> template<typename T > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::graph_add_edge_no_create_vertex (const T & edge) inline inherited
Use this function when the vertices are already inserted in the graph.
Definition at line 707 of file pgr_base_graph.hpp.
References pgassert, and pgassertwm.
{
          bool inserted;
          E e;
          if ((edge.cost < 0) && (edge.reverse_cost < 0))
              return;
 #if 0
          std::ostringstream log;
          for (auto iter = vertices_map.begin(); iter != vertices_map.end(); iter++) {
              log << "Key: " << iter->first <<"\tValue:" << iter->second << "\n";
          }
          pgassertwm(has_vertex(edge.source), log.str().c_str());
          pgassert(has_vertex(edge.target));
 #endif
          auto vm_s = get_V(edge.source);
          auto vm_t = get_V(edge.target);
          if (edge.cost >= 0) {
              boost::tie(e, inserted) =
                  boost::add_edge(vm_s, vm_t, graph);
              graph[e].cost = edge.cost;
              graph[e].id = edge.id;
          }
          if (edge.reverse_cost >= 0
                  && (is_directed() || (is_undirected() && edge.cost != edge.reverse_cost))) {
              boost::tie(e, inserted) =
                  boost::add_edge(vm_t, vm_s, graph);
              graph[e].cost = edge.reverse_cost;
              graph[e].id = edge.id;
          }
      }
template<class G, typename T_V, typename T_E> bool pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::has_vertex (int64_t vid) const inline inherited
True when vid is in the graph.
Definition at line 551 of file pgr_base_graph.hpp.
{
          return vertices_map.find(vid) != vertices_map.end();
      }
template<class G, typename T_V, typename T_E> degree_size_type pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::in_degree (int64_t vertex_id) const inline inherited
Definition at line 510 of file pgr_base_graph.hpp.
{
          if (!has_vertex(vertex_id)) {
              return 0;
          }
          return is_directed()?
              in_degree(get_V(vertex_id))
              :  out_degree(get_V(vertex_id));
      }
template<class G, typename T_V, typename T_E> degree_size_type pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::in_degree (V & v) const inline inherited
in degree of a vertex
when its undirected there is no "concept" of in degree
out degree is returned
on directed in degree of vertex is returned
Definition at line 593 of file pgr_base_graph.hpp.
{
          return is_directed()?
              boost::in_degree(v, graph) :
              boost::out_degree(v, graph);
      }
template<class G , typename T_V , typename T_E > template<typename T > void pgrouting::graph::Pgr_componentsGraph< G, T_V, T_E >::insert_edges (const T * edges, int64_t count) inline
Definition at line 67 of file pgr_componentsGraph.hpp.
Referenced by do_pgr_articulationPoints(), do_pgr_biconnectedComponents(), do_pgr_bridges(), and do_pgr_connectedComponents().
{
              insert_edges(std::vector < T >(edges, edges + count));
          }
template<class G , typename T_V , typename T_E > template<typename T > void pgrouting::graph::Pgr_componentsGraph< G, T_V, T_E >::insert_edges (const std::vector< T > & edges) inline
Definition at line 72 of file pgr_componentsGraph.hpp.
{
              for (const auto edge : edges) {
                  graph_add_edge(edge);
              }
          }
template<class G, typename T_V, typename T_E> template<typename T > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::insert_edges (T * edges, int64_t count, bool) inline inherited
Definition at line 403 of file pgr_base_graph.hpp.
References pgassert.
{
              for (int64_t i = 0; i < count; ++i) {
                  pgassert(has_vertex(edges[i].source));
                  pgassert(has_vertex(edges[i].target));
                  graph_add_edge_no_create_vertex(edges[i]);
              }
          }
template<class G, typename T_V, typename T_E> bool pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::is_directed () const inline inherited
Definition at line 560 of file pgr_base_graph.hpp.
References DIRECTED.
 {return m_gType == DIRECTED;}
template<class G, typename T_V, typename T_E> bool pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::is_source (V v_idx, E e_idx) const inline inherited
Definition at line 562 of file pgr_base_graph.hpp.
 {return v_idx == source(e_idx);}
template<class G, typename T_V, typename T_E> bool pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::is_target (V v_idx, E e_idx) const inline inherited
Definition at line 563 of file pgr_base_graph.hpp.
 {return v_idx == target(e_idx);}
template<class G, typename T_V, typename T_E> bool pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::is_undirected () const inline inherited
Definition at line 561 of file pgr_base_graph.hpp.
References UNDIRECTED.
 {return m_gType == UNDIRECTED;}
template<class G, typename T_V, typename T_E> size_t pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::num_vertices () const inline inherited
Definition at line 696 of file pgr_base_graph.hpp.
 { return boost::num_vertices(graph);}
template<class G, typename T_V, typename T_E> T_E& pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::operator[] (E e_idx) inline inherited
Definition at line 571 of file pgr_base_graph.hpp.
 {return graph[e_idx];}
template<class G, typename T_V, typename T_E> const T_E& pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::operator[] (E e_idx) const inline inherited
Definition at line 572 of file pgr_base_graph.hpp.
 {return graph[e_idx];}
template<class G, typename T_V, typename T_E> T_V& pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::operator[] (V v_idx) inline inherited
Definition at line 574 of file pgr_base_graph.hpp.
 {return graph[v_idx];}
template<class G, typename T_V, typename T_E> const T_V& pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::operator[] (V v_idx) const inline inherited
Definition at line 575 of file pgr_base_graph.hpp.
 {return graph[v_idx];}
template<class G, typename T_V, typename T_E> degree_size_type pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::out_degree (int64_t vertex_id) const inline inherited
get the out-degree of a vertex
Returns
0: The out degree of a vertex that its not in the graph
Parameters
[in] vertex_id original vertex id
Definition at line 504 of file pgr_base_graph.hpp.
{
          if (!has_vertex(vertex_id)) {
              return 0;
          }
          return out_degree(get_V(vertex_id));
      }
template<class G, typename T_V, typename T_E> degree_size_type pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::out_degree (V & v) const inline inherited
out degree of a vertex
regardles of undirected or directed graph
out degree is returned
Definition at line 604 of file pgr_base_graph.hpp.
{
          return boost::out_degree(v, graph);
      }
template<class G , typename T_V , typename T_E > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::restore_graph () inherited
Reconnects all edges that were removed.
Definition at line 849 of file pgr_base_graph.hpp.
{
     while (removed_edges.size() != 0) {
         graph_add_edge(removed_edges[0]);
         removed_edges.pop_front();
     }
 }
template<class G, typename T_V, typename T_E> V pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::source (E e_idx) const inline inherited
Definition at line 577 of file pgr_base_graph.hpp.
Referenced by pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::create_edges().
 {return boost::source(e_idx, graph);}
template<class G, typename T_V, typename T_E> V pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::target (E e_idx) const inline inherited
Definition at line 578 of file pgr_base_graph.hpp.
Referenced by pgrouting::graph::Pgr_lineGraph< G, T_V, T_E >::create_edges().
 {return boost::target(e_idx, graph);}
Member Data Documentation
template<class G , typename T_V , typename T_E > G pgrouting::graph::Pgr_componentsGraph< G, T_V, T_E >::graph
Definition at line 60 of file pgr_componentsGraph.hpp.
template<class G, typename T_V, typename T_E> graphType pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::m_gType inherited
type (DIRECTED or UNDIRECTED)
Definition at line 309 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> size_t pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::m_num_vertices inherited
local count.
Definition at line 308 of file pgr_base_graph.hpp.
Referenced by do_pgr_lineGraph().
template<class G, typename T_V, typename T_E> IndexMap pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::mapIndex inherited
Definition at line 320 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> boost::associative_property_map<IndexMap> pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::propmapIndex inherited
Definition at line 321 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> std::deque< T_E > pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::removed_edges inherited
Used for storing the removed_edges.
Definition at line 329 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> id_to_V pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::vertices_map inherited
id -> graph id
Definition at line 315 of file pgr_base_graph.hpp.
template<class G, typename T_V, typename T_E> boost::property_map<G, boost::vertex_index_t>::type pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::vertIndex inherited
Definition at line 317 of file pgr_base_graph.hpp.
The documentation for this class was generated from the following file:
/home/vicky/pgrouting/pgrouting/pgrouting/include/components/pgr_componentsGraph.hpp