PGROUTING: pgrouting::vrp::pickdeliver::Order Class Reference
pgrouting::vrp::pickdeliver::Order Class Reference
#include "order.h"
Public Member Functions
int64_t id () const
size_t idx () const
void reset_id (int64_t)
Constructors
Order (int64_t p_id, size_t p_idx, const Vehicle_node &p_pickup, const Vehicle_node &p_deliver)
Order (const Order &)=default
Accessors
const Vehicle_node & delivery () const
The delivery node.
const Vehicle_node & pickup () const
The delivery node identifier.
double distance () const
Identifiers< size_t > subsetJ (const Identifiers< size_t > &J) const
Get a subset of the orders identifiers that can be placed after this order.
Identifiers< size_t > subsetI (const Identifiers< size_t > &I) const
Modifiers
void set_compatibles (const Order order, double speed)
To be or not to be
bool is_valid (double speed) const
validate a pickup/delivery order
bool isCompatibleIJ (const Order &I, double speed) const
Can order I be placed before this order?
Static Public Attributes
static Pgr_messages msg
Static Protected Attributes
static Pgr_pickDeliver * problem
Private Attributes
size_t delivery_id
The delivery node identifier.
Identifiers< size_t > m_compatibleI
Stores all the orders that can be placed before this order.
Identifiers< size_t > m_compatibleJ
Stores all the orders that can be placed after this order.
size_t pickup_id
The pick up node identifier.
Friends
Friends
std::ostream & operator<< (std::ostream &, const Order &)
Detailed Description
Definition at line 44 of file order.h.
Constructor & Destructor Documentation
pgrouting::vrp::pickdeliver::Order::Order (int64_t p_id, size_t p_idx, const Vehicle_node & p_pickup, const Vehicle_node & p_deliver)
pgrouting::vrp::pickdeliver::Order::Order (const Order &) default
Member Function Documentation
const Vehicle_node& pgrouting::vrp::pickdeliver::Order::delivery () const
The delivery node.
Returns
the reference to the delivery node
double pgrouting::vrp::pickdeliver::Order::distance () const
int64_t pgrouting::Identifier::id () const inherited
Definition at line 42 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Dnode::distance(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::vrp::pickdeliver::Vehicle::is_phony(), pgrouting::vrp::Vehicle::is_phony(), pgrouting::vrp::Optimize::move_reduce_cost(), pgrouting::vrp::operator<<(), pgrouting::operator<<(), pgrouting::vrp::Base_node::operator==(), pgrouting::vrp::Node::operator==(), pgrouting::vrp::Node::print(), pgrouting::vrp::Base_node::print(), pgrouting::vrp::pickdeliver::Tw_node::set_Did(), and pgrouting::vrp::pickdeliver::Tw_node::set_Pid().
                      {
     return m_id;
 }
size_t pgrouting::Identifier::idx () const inherited
Definition at line 37 of file identifier.cpp.
References pgrouting::Identifier::m_idx.
Referenced by pgrouting::vrp::Vehicle_pickDeliver::erase(), pgrouting::vrp::Vehicle::erase(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Vehicle_pickDeliver::has_order(), pgrouting::vrp::Vehicle::insert(), pgrouting::vrp::Vehicle_pickDeliver::insert(), pgrouting::vrp::operator<<(), pgrouting::operator<<(), pgrouting::vrp::Base_node::operator==(), pgrouting::vrp::Node::operator==(), pgrouting::vrp::Tw_node::operator==(), pgrouting::vrp::Node::print(), pgrouting::vrp::Base_node::print(), pgrouting::vrp::Vehicle_pickDeliver::push_back(), pgrouting::vrp::Vehicle_pickDeliver::push_front(), pgrouting::vrp::Order::set_compatibles(), pgrouting::vrp::Solution::sort_by_id(), pgrouting::vrp::Optimize::swap_worse(), pgrouting::vrp::Vehicle::tau(), and pgrouting::vrp::Tw_node::travel_time_to().
                       {
     return m_idx;
 }
bool pgrouting::vrp::pickdeliver::Order::is_valid (double speed) const
validate a pickup/delivery order
An order is valid when:
The pickup is well formed
The delivery is well formed
isCompatibleIJ to go to delivery after inmediatly visiting pickup
bool pgrouting::vrp::pickdeliver::Order::isCompatibleIJ (const Order & I, double speed) const
Can order I be placed before this order?
Parameters
[in] I order
[in] speed to be used for evaluating the order
Returns
true when order I can be placed before this order
const Vehicle_node& pgrouting::vrp::pickdeliver::Order::pickup () const
The delivery node identifier.
Returns
the reference to the pickup node
void pgrouting::Identifier::reset_id (int64_t _id) inherited
Definition at line 47 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Tw_node::Tw_node().
{
     m_id = _id;
 }
void pgrouting::vrp::pickdeliver::Order::set_compatibles (const Order order, double speed)
Identifiers<size_t> pgrouting::vrp::pickdeliver::Order::subsetI (const Identifiers< size_t > & I) const
Identifiers<size_t> pgrouting::vrp::pickdeliver::Order::subsetJ (const Identifiers< size_t > & J) const
Get a subset of the orders identifiers that can be placed after this order.
Parameters
[in] J set of orders
Returns
ithe set intersection of the J orders with the compatible_J orders of this order
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & , const Order &) friend
Member Data Documentation
size_t pgrouting::vrp::pickdeliver::Order::delivery_id private
The delivery node identifier.
It hold's the idx of the node
Definition at line 188 of file order.h.
Identifiers<size_t> pgrouting::vrp::pickdeliver::Order::m_compatibleI private
Stores all the orders that can be placed before this order.
Definition at line 219 of file order.h.
Identifiers<size_t> pgrouting::vrp::pickdeliver::Order::m_compatibleJ private
Stores all the orders that can be placed after this order.
Todo:
TODO
compatibility changes based on the speed this is not taking that into account (here)
check where is it talking that into account
Definition at line 205 of file order.h.
Pgr_messages pgrouting::vrp::pickdeliver::PD_problem::msg static inherited
Definition at line 49 of file pd_problem.h.
size_t pgrouting::vrp::pickdeliver::Order::pickup_id private
The pick up node identifier.
It hold's the idx of the node
Definition at line 182 of file order.h.
Pgr_pickDeliver* pgrouting::vrp::pickdeliver::PD_problem::problem static protected inherited
Definition at line 52 of file pd_problem.h.
The documentation for this class was generated from the following file:
/home/vicky/pgrouting/pgrouting/pgrouting/include/pickDeliver/order.h