PGROUTING: /home/vicky/pgrouting/pgrouting/pgrouting/include/drivers/dijkstra/dijkstraVia_driver.h File Reference
dijkstraVia_driver.h File Reference
#include "c_types/routes_t.h"
#include "c_types/pgr_edge_t.h"
Functions
void do_pgr_dijkstraVia (pgr_edge_t *data_edges, size_t total_edges, int64_t *via_vidsArr, size_t size_via_vidsArr, bool directed, bool strict, bool U_turn_on_edge, Routes_t **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
Function Documentation
void do_pgr_dijkstraVia (pgr_edge_t * data_edges, size_t total_edges, int64_t * via_vidsArr, size_t size_via_vidsArr, bool directed, bool strict, bool U_turn_on_edge, Routes_t ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 165 of file dijkstraVia_driver.cpp.
References count_tuples(), DIRECTED, get_route(), pgrouting::graph::Pgr_base_graph< G, Vertex, Edge >::insert_edges(), pgassert, pgr_alloc(), pgr_dijkstraViaVertex(), pgr_free(), pgr_msg(), UNDIRECTED, and AssertFailedException::what().
Referenced by process().
{
     std::ostringstream log;
     std::ostringstream err;
     std::ostringstream notice;
     try {
         pgassert(total_edges != 0);
         pgassert(!(*log_msg));
         pgassert(!(*notice_msg));
         pgassert(!(*err_msg));
         pgassert(!(*return_tuples));
         pgassert(*return_count == 0);
         graphType gType = directed? DIRECTED: UNDIRECTED;
         std::deque< Path >paths;
         log << "\nInserting vertices into a c++ vector structure";
         std::vector< int64_t > via_vertices(
                 via_vidsArr, via_vidsArr + size_via_vidsArr);
         if (directed) {
             log << "\nWorking with directed Graph";
             pgrouting::DirectedGraph digraph(gType);
             digraph.insert_edges(data_edges, total_edges);
             pgr_dijkstraViaVertex(
                     digraph,
                     via_vertices,
                     paths,
                     strict,
                     U_turn_on_edge,
                     log);
         } else {
             log << "\nWorking with Undirected Graph";
             pgrouting::UndirectedGraph undigraph(gType);
             undigraph.insert_edges(data_edges, total_edges);
             pgr_dijkstraViaVertex(
                     undigraph,
                     via_vertices,
                     paths,
                     strict,
                     U_turn_on_edge,
                     log);
         }
         size_t count(count_tuples(paths));
         if (count == 0) {
             (*return_tuples) = NULL;
             (*return_count) = 0;
             notice <<
                 "No paths found";
             *log_msg = pgr_msg(notice.str().c_str());
             return;
         }
         // get the space required to store all the paths
         (*return_tuples) = pgr_alloc(count, (*return_tuples));
         log << "\nConverting a set of paths into the tuples";
         (*return_count) = (get_route(return_tuples, paths));
         (*return_tuples)[count - 1].edge = -2;
         *log_msg = log.str().empty()?
             *log_msg :
             pgr_msg(log.str().c_str());
         *notice_msg = notice.str().empty()?
             *notice_msg :
             pgr_msg(notice.str().c_str());
     } catch (AssertFailedException &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch (std::exception &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch(...) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << "Caught unknown exception!";
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     }
 }