PGROUTING: /home/vicky/pgrouting/pgrouting/pgrouting/src/allpairs/src/johnson.c File Reference
johnson.c File Reference
#include "c_common/postgres_connection.h"
#include "c_common/debug_macro.h"
#include "c_common/time_msg.h"
#include "c_common/edges_input.h"
#include "drivers/allpairs/johnson_driver.h"
Functions
PGDLLEXPORT Datum johnson (PG_FUNCTION_ARGS)
PG_FUNCTION_INFO_V1 (johnson)
static void process (char *edges_sql, bool directed, Matrix_cell_t **result_tuples, size_t *result_count)
Function Documentation
PGDLLEXPORT Datum johnson (PG_FUNCTION_ARGS)
Definition at line 87 of file johnson.c.
References matrix_cell::cost, matrix_cell::from_vid, PGR_DBG, process(), and matrix_cell::to_vid.
{
     FuncCallContext     *funcctx;
     TupleDesc            tuple_desc;
     /**************************************************************************/
     /*                          MODIFY AS NEEDED                              */
     /*                                                                        */
     Matrix_cell_t *result_tuples = NULL;
     size_t result_count = 0;
     /*                                                                        */
     /**************************************************************************/
     if (SRF_IS_FIRSTCALL()) {
         MemoryContext   oldcontext;
         funcctx = SRF_FIRSTCALL_INIT();
         oldcontext = MemoryContextSwitchTo(funcctx->multi_call_memory_ctx);
         /*********************************************************************/
         /*                          MODIFY AS NEEDED                         */
         // CREATE OR REPLACE FUNCTION pgr_johnson(
         // edges_sql TEXT,
         // directed BOOLEAN,
         PGR_DBG("Calling process");
         process(
                 text_to_cstring(PG_GETARG_TEXT_P(0)),
                 PG_GETARG_BOOL(1),
                 &result_tuples,
                 &result_count);
         /*                                                                   */
         /*********************************************************************/
 #if PGSQL_VERSION > 95
         funcctx->max_calls = result_count;
 #else
         funcctx->max_calls = (uint32_t)result_count;
 #endif
         funcctx->user_fctx = result_tuples;
         if (get_call_result_type(fcinfo, NULL, &tuple_desc)
                 != TYPEFUNC_COMPOSITE)
             ereport(ERROR,
                     (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
                      errmsg("function returning record called in context "
                          "that cannot accept type record")));
         funcctx->tuple_desc = tuple_desc;
         MemoryContextSwitchTo(oldcontext);
     }
     funcctx = SRF_PERCALL_SETUP();
     tuple_desc = funcctx->tuple_desc;
     result_tuples = (Matrix_cell_t*) funcctx->user_fctx;
     if (funcctx->call_cntr < funcctx->max_calls) {
         HeapTuple    tuple;
         Datum        result;
         Datum        *values;
         bool         *nulls;
         /*********************************************************************/
         /*                          MODIFY AS NEEDED                         */
         // OUT seq BIGINT,
         // OUT from_vid BIGINT,
         // OUT to_vid BIGINT,
         // OUT cost float)
         values = palloc(3 * sizeof(Datum));
         nulls = palloc(3 * sizeof(bool));
         // postgres starts counting from 1
         values[0] = Int64GetDatum(result_tuples[funcctx->call_cntr].from_vid);
         nulls[0] = false;
         values[1] = Int64GetDatum(result_tuples[funcctx->call_cntr].to_vid);
         nulls[1] = false;
         values[2] = Float8GetDatum(result_tuples[funcctx->call_cntr].cost);
         nulls[2] = false;
         /*********************************************************************/
         tuple = heap_form_tuple(tuple_desc, values, nulls);
         result = HeapTupleGetDatum(tuple);
         SRF_RETURN_NEXT(funcctx, result);
     } else {
         SRF_RETURN_DONE(funcctx);
     }
 }
PG_FUNCTION_INFO_V1 (johnson)
static void process (char * edges_sql, bool directed, Matrix_cell_t ** result_tuples, size_t * result_count) static
Definition at line 43 of file johnson.c.
References do_pgr_johnson(), edges, PGR_DBG, pgr_get_edges_no_id(), pgr_SPI_connect(), pgr_SPI_finish(), and time_msg().
Referenced by johnson().
{
     pgr_SPI_connect();
     PGR_DBG("Load data");
     pgr_edge_t *edges = NULL;
     size_t total_tuples = 0;
     pgr_get_edges_no_id(edges_sql, &edges, &total_tuples);
     if (total_tuples == 0) {
         PGR_DBG("No edges found");
         (*result_count) = 0;
         (*result_tuples) = NULL;
         pgr_SPI_finish();
         return;
     }
     PGR_DBG("Total %ld tuples in query:", total_tuples);
     PGR_DBG("Starting processing");
     char *err_msg = (char *)"";
     clock_t start_t = clock();
     do_pgr_johnson(
             edges,
             total_tuples,
             directed,
             result_tuples,
             result_count,
             &err_msg);
     time_msg(" processing Johnson", start_t, clock());
     PGR_DBG("Returning %ld tuples\n", *result_count);
     PGR_DBG("Returned message = %s\n", err_msg);
     free(err_msg);
     pfree(edges);
     pgr_SPI_finish();
 }