PGROUTING: /home/vicky/pgrouting/pgrouting/pgrouting/src/allpairs/src/johnson_driver.cpp File Reference
johnson_driver.cpp File Reference
#include "drivers/allpairs/johnson_driver.h"
#include <sstream>
#include <deque>
#include <vector>
#include "allpairs/pgr_allpairs.hpp"
Functions
void do_pgr_johnson (pgr_edge_t *data_edges, size_t total_tuples, bool directed, Matrix_cell_t **return_tuples, size_t *return_count, char **err_msg)
Function Documentation
void do_pgr_johnson (pgr_edge_t * data_edges, size_t total_tuples, bool directed, Matrix_cell_t ** return_tuples, size_t * return_count, char ** err_msg)
Definition at line 41 of file johnson_driver.cpp.
References DIRECTED, pgrouting::graph::Pgr_base_graph< G, Vertex, Edge >::insert_edges(), pgr_johnson(), and UNDIRECTED.
Referenced by process().
{
     std::ostringstream log;
     try {
         if (total_tuples == 1) {
             log << "Required: more than one tuple\n";
             (*return_tuples) = NULL;
             (*return_count) = 0;
             *err_msg = strdup(log.str().c_str());
             return;
         }
         graphType gType = directed? DIRECTED: UNDIRECTED;
         std::deque< Path >paths;
         if (directed) {
             log << "Working with directed Graph\n";
             pgrouting::DirectedGraph digraph(gType);
             digraph.insert_edges(data_edges, total_tuples);
             pgr_johnson(digraph, *return_count, return_tuples);
         } else {
             log << "Working with Undirected Graph\n";
             pgrouting::UndirectedGraph undigraph(gType);
             undigraph.insert_edges(data_edges, total_tuples);
             pgr_johnson(undigraph, *return_count, return_tuples);
         }
         if (*return_count == 0) {
             log <<  "NOTICE: No Vertices found??? wiered error\n";
             *err_msg = strdup(log.str().c_str());
             (*return_tuples) = NULL;
             (*return_count) = 0;
             return;
         }
 #ifndef DEBUG
         *err_msg = strdup("OK");
 #else
         *err_msg = strdup(log.str().c_str());
 #endif
     } catch ( ... ) {
         log << "Caught unknown exception!\n";
         *err_msg = strdup(log.str().c_str());
     }
 }