PGROUTING: /home/vicky/pgrouting/pgrouting/pgrouting/src/internalQueryTests/src/test_matrixRows.c File Reference
test_matrixRows.c File Reference
#include "c_common/postgres_connection.h"
#include "c_common/matrixRows_input.h"
#include "c_common/debug_macro.h"
#include "./test_matrixRows_driver.h"
Functions
PG_FUNCTION_INFO_V1 (test_matrixRows)
static void process (char *matrix_rows_sql, bool *result_bool)
PGDLLEXPORT Datum test_matrixRows (PG_FUNCTION_ARGS)
Function Documentation
PG_FUNCTION_INFO_V1 (test_matrixRows)
static void process (char * matrix_rows_sql, bool * result_bool) static
Definition at line 45 of file test_matrixRows.c.
References do_pgr_test_matrixRows(), PGR_DBG, pgr_get_matrixRows(), pgr_SPI_connect(), and pgr_SPI_finish().
Referenced by test_matrixRows().
{
     pgr_SPI_connect();
     PGR_DBG("Load data");
     Matrix_cell_t *matrix_rows = NULL;
     size_t total_rows = 0;
     pgr_get_matrixRows(matrix_rows_sql, &matrix_rows, &total_rows);
     if (total_rows == 0) {
         PGR_DBG("No rows found");
         (*result_bool) = true;
         pfree(matrix_rows);
         pgr_SPI_finish();
         return;
     }
     PGR_DBG("Total %ld rows in query:", total_rows);
     size_t i;
     for (i = 0; i < total_rows; ++i) {
         PGR_DBG("start_vid = %li \t end_vid = %li agg_cost = %lf",
                matrix_rows[i].from_vid, matrix_rows[i].to_vid, matrix_rows[i].cost);
     }
     PGR_DBG("Starting processing");
     char *err_msg = NULL;
     char *log_msg = NULL;
     (*result_bool) = do_pgr_test_matrixRows(
             matrix_rows,
             total_rows,
             &log_msg,
             &err_msg);
     pfree(matrix_rows);
     PGR_DBG("Returned log message = %s\n", log_msg);
     if (log_msg) {
         elog(DEBUG1, "%s", log_msg);
         free(log_msg);
     }
     PGR_DBG("Returned error message = %s\n", err_msg);
     if (err_msg) {
         pgr_SPI_finish();
         elog(ERROR, "%s", err_msg);
         free(err_msg);
     }
     pgr_SPI_finish();
 }
PGDLLEXPORT Datum test_matrixRows (PG_FUNCTION_ARGS)
Definition at line 99 of file test_matrixRows.c.
References process().
{
     bool  result_bool = false;
     process(
             text_to_cstring(PG_GETARG_TEXT_P(0)),
             &result_bool);
     PG_RETURN_BOOL(result_bool);
 }