PGROUTING: /home/vicky/pgrouting/pgrouting/pgrouting/src/internalQueryTests/src/testXYedges_driver.cpp File Reference
testXYedges_driver.cpp File Reference
#include "./testXYedges_driver.h"
#include <sstream>
#include <iomanip>
#include <vector>
#include "./../../common/src/pgr_base_graph.hpp"
#include "./../../dijkstra/src/pgr_dijkstra.hpp"
#include "./../../common/src/pgr_assert.h"
Functions
bool do_pgr_testXYedges (Pgr_edge_xy_t *data_edges, size_t total_edges, char **log_msg, char **err_msg)
Function Documentation
bool do_pgr_testXYedges (Pgr_edge_xy_t * data_edges, size_t total_edges, char ** log_msg, char ** err_msg)
Definition at line 45 of file testXYedges_driver.cpp.
References edge::cost, DIRECTED, edges, pgrouting::extract_vertices(), edge::id, pgrouting::graph::Pgr_base_graph< G, Vertex, Edge >::insert_edges(), pgassert, pgr_dijkstra(), edge::reverse_cost, edge::source, edge::target, UNDIRECTED, and AssertFailedException::what().
Referenced by process().
{
     std::ostringstream log;
     std::ostringstream err;
     try {
         pgassert(!(*log_msg));
         pgassert(!(*err_msg));
         std::vector< Pgr_edge_xy_t > edges(data_edges, data_edges + total_edges);
         auto vertices(pgrouting::extract_vertices(edges));
         log << "Original: \n" <<
             std::setprecision(32);
         for (const auto edge : edges) {
             log << "id = " << edge.id
                 << "\tsource = " << edge.source
                 << "\ttarget = " << edge.target
                 << "\tcost = " << edge.cost
                 << "\treverse_cost = " << edge.reverse_cost
                 << "\n\t(x1,y1) = (" << edge.x1 << "," << edge.y1 << ")"
                 << "\t(x2,y2) = (" << edge.x2 << "," << edge.y2 << ")\n";
         }
         {
             log << "Testing Directed ,  insertion using vector\n";
             pgrouting::xyDirectedGraph graph(DIRECTED);
             log << "  - Created graph:\n";
             log << graph;
             log << "  - Inserting Edges:\n";
             graph.insert_edges(edges);
             log << graph;
             log << "  - Can do a dijKstra:\n";
             pgr_dijkstra(graph, 2, 3, true);
         }
         {
             log << "Testing Directed ,  insertion using C array\n";
             pgrouting::xyDirectedGraph graph(DIRECTED);
             log << "  - Created graph:\n";
             log << graph;
             log << "  - Inserting Edges:\n";
             graph.insert_edges(data_edges, total_edges);
             log << graph;
             log << "  - Can do a dijKstra:\n";
             pgr_dijkstra(graph, 2, 3, true);
         }
         {
             log << "Testing Directed ,  creating with vertices, insertion using vector\n";
             pgrouting::xyDirectedGraph graph(vertices, DIRECTED);
             log << "  - Created graph:\n";
             log << graph;
             log << "  - Inserting Edges:\n";
             graph.insert_edges(edges);
             log << graph;
             log << "  - Can do a dijKstra:\n";
             pgr_dijkstra(graph, 2, 3, true);
         }
         {
             log << "Testing Directed ,  creating with vertices, insertion using C array\n";
             pgrouting::xyDirectedGraph graph(vertices, DIRECTED);
             log << "  - Created graph:\n";
             log << graph;
             log << "  - Inserting Edges:\n";
             graph.insert_edges(data_edges, total_edges);
             log << graph;
             log << "  - Can do a dijKstra:\n";
             pgr_dijkstra(graph, 2, 3, true);
         }
         {
             log << "Testing Undirected ,  insertion using vector\n";
             pgrouting::xyUndirectedGraph graph(UNDIRECTED);
             log << "  - Created graph:\n";
             log << graph;
             log << "  - Inserting Edges:\n";
             graph.insert_edges(edges);
             log << graph;
             log << "  - Can do a dijKstra:\n";
             pgr_dijkstra(graph, 2, 3, true);
         }
         {
             log << "Testing Directed ,  insertion using C array\n";
             pgrouting::xyUndirectedGraph graph(UNDIRECTED);
             log << "  - Created graph:\n";
             log << graph;
             log << "  - Inserting Edges:\n";
             graph.insert_edges(data_edges, total_edges);
             log << graph;
             log << "  - Can do a dijKstra:\n";
             pgr_dijkstra(graph, 2, 3, true);
         }
         {
             log << "Testing Undirected ,  insertion using C array\n";
             pgrouting::xyUndirectedGraph graph(UNDIRECTED);
             log << "  - Created graph:\n";
             log << graph;
             log << "  - Inserting Edges:\n";
             graph.insert_edges(data_edges, total_edges);
             log << graph;
             log << "  - Can do a dijKstra:\n";
             pgr_dijkstra(graph, 2, 3, true);
         }
         {
             log << "Testing Undirected ,  creating with vertices, insertion using vector\n";
             pgrouting::xyUndirectedGraph graph(vertices, UNDIRECTED);
             log << "  - Created graph:\n";
             log << graph;
             log << "  - Inserting Edges:\n";
             graph.insert_edges(edges);
             log << graph;
             log << "  - Can do a dijKstra:\n";
             pgr_dijkstra(graph, 2, 3, true);
         }
         *err_msg = NULL;
         *log_msg = strdup(log.str().c_str());
         return true;
     } catch (AssertFailedException &except) {
         log << except.what() << "\n";
         *err_msg = strdup(log.str().c_str());
         return false;
     } catch (std::exception& except) {
         log << except.what() << "\n";
         *err_msg = strdup(log.str().c_str());
         return false;
     } catch(...) {
         log << "Caught unknown exception!\n";
         *err_msg = strdup(log.str().c_str());
         return false;
     }
 }