PGROUTING: /home/vicky/pgrouting/pgrouting/pgrouting/src/internalQueryTests/src/testXYedges.c File Reference
testXYedges.c File Reference
#include "c_common/postgres_connection.h"
#include "./testXYedges_driver.h"
#include "c_common/edges_input.h"
#include "c_common/debug_macro.h"
Functions
PG_FUNCTION_INFO_V1 (testXYedges)
static void process (char *edges_sql, bool *result_bool)
PGDLLEXPORT Datum testXYedges (PG_FUNCTION_ARGS)
Function Documentation
PG_FUNCTION_INFO_V1()
PG_FUNCTION_INFO_V1 (testXYedges)
Referenced by process().
process()
static void process (char * edges_sql, bool * result_bool) static
Definition at line 42 of file testXYedges.c.
References do_pgr_testXYedges(), edges, PG_FUNCTION_INFO_V1(), PGR_DBG, pgr_get_edges_xy(), pgr_SPI_connect(), pgr_SPI_finish(), and testXYedges().
Referenced by testXYedges().
{
     pgr_SPI_connect();
     PGR_DBG("Load data");
     Pgr_edge_xy_t *edges = NULL;
     size_t total_edges = 0;
     pgr_get_edges_xy(edges_sql, &edges, &total_edges);
     if (total_edges == 0) {
         PGR_DBG("No edges found");
         (*result_bool) = true;
         pfree(edges);
         pgr_SPI_finish();
         return;
     }
     PGR_DBG("Total %ld tuples in query:", total_edges);
     size_t i;
     for (i = 0; i < total_edges; ++i) {
         PGR_DBG("id = %li \t source = %li \t target = %ld  cost = %lf reverse_cost = %lf",
                edges[i].id, edges[i].source, edges[i].target, edges[i].cost, edges[i].reverse_cost);
         PGR_DBG("    (x1,y1) = (%.32lf ,%.32lf) (x2,y2) = (%.32lf,.%.32lf)",
                edges[i].x1, edges[i].y1, edges[i].x2, edges[i].y2);
     }
     PGR_DBG("Starting processing");
     char *err_msg = NULL;
     char *log_msg = NULL;
     (*result_bool) = do_pgr_testXYedges(
             edges,
             total_edges,
             &log_msg,
             &err_msg);
     pfree(edges);
     PGR_DBG("Returned log message = %s\n", log_msg);
     if (log_msg) {
         elog(DEBUG1, "%s", log_msg);
         free(log_msg);
     }
     PGR_DBG("Returned error message = %s\n", err_msg);
     if (err_msg) {
         pgr_SPI_finish();
         elog(ERROR, "%s", err_msg);
         free(err_msg);
     }
     pgr_SPI_finish();
 }
testXYedges()
PGDLLEXPORT Datum testXYedges (PG_FUNCTION_ARGS)
Definition at line 96 of file testXYedges.c.
References process().
Referenced by process().
{
     bool  result_bool = false;
     process(
             text_to_cstring(PG_GETARG_TEXT_P(0)),
             &result_bool);
     PG_RETURN_BOOL(result_bool);
 }