PGROUTING: /home/vicky/pgrouting/pgrouting/pgrouting/include/c_common/vehicles_input.h File Reference
vehicles_input.h File Reference
#include "c_types/pickDeliver/vehicle_t.h"
Functions
void pgr_get_vehicles (char *vehicles_sql, Vehicle_t **vehicles, size_t *total_vehicles)
Reads the vehicles orders.
void pgr_get_vehicles_with_id (char *vehicles_sql, Vehicle_t **vehicles, size_t *total_vehicles)
Reads the vehicles orders.
Function Documentation
void pgr_get_vehicles (char * vehicles_sql, Vehicle_t ** vehicles, size_t * total_vehicles)
Reads the vehicles orders.
Parameters
[in] vehicles_sql
[out] vehicles
[out] total_vehicles
Definition at line 261 of file vehicles_input.c.
References pgr_get_vehicles_general().
Referenced by process().
{
     pgr_get_vehicles_general( vehicles_sql, vehicles, total_vehicles, false);
 }
void pgr_get_vehicles_with_id (char * vehicles_sql, Vehicle_t ** vehicles, size_t * total_vehicles)
Reads the vehicles orders.
Parameters
[in] vehicles_sql
[out] vehicles
[out] total_vehicles
Definition at line 269 of file vehicles_input.c.
References pgr_get_vehicles_general().
Referenced by process().
{
     pgr_get_vehicles_general(vehicles_sql, vehicles, total_vehicles, true);
 }