PGROUTING: /home/vicky/pgrouting/pgrouting/pgrouting/src/vrp_basic/src/VRP.h File Reference
VRP.h File Reference
#include <stddef.h>
Classes
struct vrp_cost_element
struct vrp_orders
struct vrp_result_element
struct vrp_vehicles
Typedefs
typedef struct vrp_cost_element vrp_cost_element_t
typedef struct vrp_orders vrp_orders_t
typedef struct vrp_result_element vrp_result_element_t
typedef struct vrp_vehicles vrp_vehicles_t
Functions
int find_vrp_solution (vrp_vehicles_t *vehicles, size_t vehicle_count, vrp_orders_t *orders, size_t order_count, vrp_cost_element_t *costmatrix, size_t cost_count, int depot_id, vrp_result_element_t **result, size_t *result_count, char **err_msg)
Typedef Documentation
typedef struct vrp_cost_element vrp_cost_element_t
typedef struct vrp_orders vrp_orders_t
typedef struct vrp_result_element vrp_result_element_t
typedef struct vrp_vehicles vrp_vehicles_t
Function Documentation
int find_vrp_solution (vrp_vehicles_t * vehicles, size_t vehicle_count, vrp_orders_t * orders, size_t order_count, vrp_cost_element_t * costmatrix, size_t cost_count, int depot_id, vrp_result_element_t ** result, size_t * result_count, char ** err_msg)
Definition at line 139 of file VRP_core.cpp.
References CTourInfo::getEndDepot(), CTourInfo::getOrderVector(), CTourInfo::getServedOrderCount(), CVRPSolver::getServiceTime(), CVRPSolver::getSolution(), CTourInfo::getStartDepot(), CTourInfo::getStartTime(), CSolutionInfo::getTour(), CSolutionInfo::getTourInfoVector(), CTourInfo::getVehicleId(), loadDistanceMatrix(), loadOrders(), loadVehicles(), pgr_alloc(), PGR_LOG, and CVRPSolver::solveVRP().
Referenced by solve_vrp().
{
     int res;
     std::string strError;
     try {
         PGR_LOG("Before load order");
         loadOrders(orders, static_cast<int>(order_count), depot_id);
         PGR_LOG("After load order");
         loadVehicles(vehicles, static_cast<int>(vehicle_count));
         PGR_LOG("After load vehicles");
         loadDistanceMatrix(costmatrix, static_cast<int>(cost_count), depot_id);
         PGR_LOG("After load distance matrix");
         res = solver.solveVRP(strError);
         PGR_LOG("After VRP Solve");
     }
     catch(std::exception& e) {
         *err_msg = (char *) e.what();
         return -1;
     }
     catch(...) {
         *err_msg = (char *) "Caught unknown exception!";
         return -1;
     }
     if (res < 0) {
         return res;
     } else {
         try {
         CSolutionInfo solution;
         CTourInfo ctour;
         // bool bOK =
                 solver.getSolution(solution, strError);
         auto totalRoute = solution.getTourInfoVector().size();
         size_t totRows = 0;
         for (size_t i = 0; i < totalRoute; i++) {
             totRows += (solution.getTour(static_cast<int>(i)).getServedOrderCount() + 2);
         }
         *results = pgr_alloc(totRows, *results);
         *result_count = totRows;
         int cnt = 0;
         for (size_t i = 0; i < totalRoute; i++) {
             ctour = solution.getTour(static_cast<int>(i));
             std::vector<int> vecOrder = ctour.getOrderVector();
             auto totalOrder = vecOrder.size();
             // For start depot
             (*results)[cnt].order_id = ctour.getStartDepot();
             (*results)[cnt].order_pos = 0;
             (*results)[cnt].vehicle_id = ctour.getVehicleId();
             (*results)[cnt].arrival_time = -1;
             (*results)[cnt].depart_time = ctour.getStartTime(0);
             cnt++;
             // For each order
             for (size_t j = 0; j < totalOrder; j++) {
                 (*results)[cnt].order_id = vecOrder[j];
                 (*results)[cnt].order_pos = static_cast<int>(j) + 1;
                 (*results)[cnt].vehicle_id = ctour.getVehicleId();
                 (*results)[cnt].depart_time = ctour.getStartTime(static_cast<int>(j) + 1);
                 (*results)[cnt].arrival_time = ctour.getStartTime(static_cast<int>(j) + 1) - solver.getServiceTime(vecOrder[j]);
                 cnt++;
             }
             // For return depot
             (*results)[cnt].order_id = ctour.getEndDepot();
             (*results)[cnt].order_pos = static_cast<int>(totalOrder) + 1;
             (*results)[cnt].vehicle_id = ctour.getVehicleId();
             (*results)[cnt].arrival_time = ctour.getStartTime(static_cast<int>(totalOrder) + 1);
             (*results)[cnt].depart_time = -1;
             cnt++;
         }
         }
         catch(std::exception& e) {
         *err_msg = (char *) e.what();
         return -1;
         }
         catch(...) {
         *err_msg = (char *) "Caught unknown exception!";
         return -1;
         }
     }
     return EXIT_SUCCESS;
 }