PGROUTING: /home/vicky/pgrouting/pgrouting/pgrouting/include/drivers/driving_distance/withPoints_dd_driver.h File Reference
withPoints_dd_driver.h File Reference
#include "c_types/point_on_edge_t.h"
#include "c_types/pgr_edge_t.h"
#include "c_types/general_path_element_t.h"
Functions
void do_pgr_many_withPointsDD (pgr_edge_t *edges, size_t total_edges, Point_on_edge_t *points_p, size_t total_points, pgr_edge_t *edges_of_points, size_t total_edges_of_points, int64_t *start_pids_arr, size_t s_len, double distance, bool directed, char driving_side, bool details, bool equiCost, General_path_element_t **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
Function Documentation
void do_pgr_many_withPointsDD (pgr_edge_t * edges, size_t total_edges, Point_on_edge_t * points_p, size_t total_points, pgr_edge_t * edges_of_points, size_t total_edges_of_points, int64_t * start_pids_arr, size_t s_len, double distance, bool directed, char driving_side, bool details, bool equiCost, General_path_element_t ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 59 of file withPoints_dd_driver.cpp.
References Path_t::agg_cost, check_points(), collapse_paths(), count_tuples(), create_new_edges(), DIRECTED, eliminate_details_dd(), pgrouting::graph::Pgr_base_graph< G, Vertex, Edge >::insert_edges(), Path_t::node, pgassert, pgr_alloc(), pgr_drivingDistance(), pgr_free(), pgr_msg(), UNDIRECTED, and AssertFailedException::what().
Referenced by process().
{
     std::ostringstream log;
     std::ostringstream notice;
     std::ostringstream err;
     try {
         pgassert(!(*log_msg));
         pgassert(!(*notice_msg));
         pgassert(!(*err_msg));
         pgassert(!(*return_tuples));
         pgassert((*return_count) == 0);
         pgassert(edges);
         pgassert(points_p);
         pgassert(edges_of_points);
         pgassert(start_pidsArr);
         /*
          * storing on C++ containers
          */
         std::vector<int64_t> start_vids(
                 start_pidsArr, start_pidsArr + s_len);
         std::vector<Point_on_edge_t>
             points(points_p, points_p + total_points);
         std::vector<pgr_edge_t> edges_to_modify(
                 edges_of_points, edges_of_points + total_edges_of_points);
         log << "start_vids :";
         for (const auto v : start_vids) log << v << ", ";
         /*
          * checking here is easier than on the C code
          */
         int errcode = check_points(points, log);
         if (errcode) {
             *log_msg = strdup(log.str().c_str());
             err << "Unexpected point(s) with same pid"
                 << " but different edge/fraction/side combination found.";
             *err_msg = pgr_msg(err.str().c_str());
             return;
         }
         std::vector< pgr_edge_t > new_edges;
         create_new_edges(
                 points,
                 edges_to_modify,
                 driving_side,
                 new_edges,
                 log);
         graphType gType = directed? DIRECTED: UNDIRECTED;
         std::deque< Path >paths;
         if (directed) {
             pgrouting::DirectedGraph digraph(gType);
             digraph.insert_edges(edges, total_edges);
             digraph.insert_edges(new_edges);
             paths = pgr_drivingDistance(
                     digraph, start_vids, distance, equiCost, log);
         } else {
             pgrouting::UndirectedGraph undigraph(gType);
             undigraph.insert_edges(edges, total_edges);
             undigraph.insert_edges(new_edges);
             paths = pgr_drivingDistance(
                     undigraph, start_vids, distance, equiCost, log);
         }
         for (auto &path : paths) {
             log << path;
             if (!details) {
                 eliminate_details_dd(path);
             }
             log << path;
             std::sort(path.begin(), path.end(),
                     [](const Path_t &l, const  Path_t &r)
                     {return l.node < r.node;});
             std::stable_sort(path.begin(), path.end(),
                     [](const Path_t &l, const  Path_t &r)
                     {return l.agg_cost < r.agg_cost;});
             log << path;
         }
         size_t count(count_tuples(paths));
         if (count == 0) {
             *notice_msg = pgr_msg("No return values was found");
             return;
         }
         *return_tuples = pgr_alloc(count, (*return_tuples));
         *return_count = collapse_paths(return_tuples, paths);
         *log_msg = log.str().empty()?
             *log_msg :
             pgr_msg(log.str().c_str());
         *notice_msg = notice.str().empty()?
             *notice_msg :
             pgr_msg(notice.str().c_str());
     } catch (AssertFailedException &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch (std::exception &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch(...) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << "Caught unknown exception!";
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     }
 }