PGROUTING: _version.c File Reference
_version.c File Reference
#include "c_common/postgres_connection.h"
#include "./_version.h"
Macros
#define UNUSED(x) (void)(x)
Functions
PGDLLEXPORT Datum _pgr_boost_version (PG_FUNCTION_ARGS)
PGDLLEXPORT Datum _pgr_build_type (PG_FUNCTION_ARGS)
PGDLLEXPORT Datum _pgr_compilation_date (PG_FUNCTION_ARGS)
PGDLLEXPORT Datum _pgr_compiler_version (PG_FUNCTION_ARGS)
PGDLLEXPORT Datum _pgr_git_hash (PG_FUNCTION_ARGS)
PGDLLEXPORT Datum _pgr_lib_version (PG_FUNCTION_ARGS)
PGDLLEXPORT Datum _pgr_operating_system (PG_FUNCTION_ARGS)
PGDLLEXPORT Datum _pgr_pgsql_version (PG_FUNCTION_ARGS)
PG_FUNCTION_INFO_V1 (_pgr_boost_version)
PG_FUNCTION_INFO_V1 (_pgr_build_type)
PG_FUNCTION_INFO_V1 (_pgr_compilation_date)
PG_FUNCTION_INFO_V1 (_pgr_compiler_version)
PG_FUNCTION_INFO_V1 (_pgr_git_hash)
PG_FUNCTION_INFO_V1 (_pgr_lib_version)
PG_FUNCTION_INFO_V1 (_pgr_operating_system)
PG_FUNCTION_INFO_V1 (_pgr_pgsql_version)
Macro Definition Documentation
UNUSED
#define UNUSED (x) (void)(x)
Definition at line 30 of file _version.c.
Referenced by _pgr_boost_version(), _pgr_build_type(), _pgr_compilation_date(), _pgr_compiler_version(), _pgr_git_hash(), _pgr_lib_version(), _pgr_operating_system(), and _pgr_pgsql_version().
Function Documentation
_pgr_boost_version()
PGDLLEXPORT Datum _pgr_boost_version (PG_FUNCTION_ARGS)
Definition at line 44 of file _version.c.
References _pgr_build_type(), BOOST_VERSION, PG_FUNCTION_INFO_V1(), and UNUSED.
{
     UNUSED(fcinfo);
     char *ver = BOOST_VERSION;
     text *result = cstring_to_text(ver);
     PG_RETURN_TEXT_P(result);
 }
_pgr_build_type()
PGDLLEXPORT Datum _pgr_build_type (PG_FUNCTION_ARGS)
Definition at line 52 of file _version.c.
References _pgr_compilation_date(), CMAKE_BUILD_TYPE, PG_FUNCTION_INFO_V1(), and UNUSED.
Referenced by _pgr_boost_version().
{
     UNUSED(fcinfo);
     char *ver = CMAKE_BUILD_TYPE;
     text *result = cstring_to_text(ver);
     PG_RETURN_TEXT_P(result);
 }
_pgr_compilation_date()
PGDLLEXPORT Datum _pgr_compilation_date (PG_FUNCTION_ARGS)
Definition at line 60 of file _version.c.
References _pgr_compiler_version(), COMPILATION_DATE, PG_FUNCTION_INFO_V1(), and UNUSED.
Referenced by _pgr_build_type().
{
     UNUSED(fcinfo);
     char *ver = COMPILATION_DATE;
     text *result = cstring_to_text(ver);
     PG_RETURN_TEXT_P(result);
 }
_pgr_compiler_version()
PGDLLEXPORT Datum _pgr_compiler_version (PG_FUNCTION_ARGS)
Definition at line 68 of file _version.c.
References _pgr_git_hash(), COMPILER_VERSION, PG_FUNCTION_INFO_V1(), and UNUSED.
Referenced by _pgr_compilation_date().
{
     UNUSED(fcinfo);
     char *ver = COMPILER_VERSION;
     text *result = cstring_to_text(ver);
     PG_RETURN_TEXT_P(result);
 }
_pgr_git_hash()
PGDLLEXPORT Datum _pgr_git_hash (PG_FUNCTION_ARGS)
Definition at line 76 of file _version.c.
References _pgr_lib_version(), PG_FUNCTION_INFO_V1(), PROJECT_GIT_HASH, and UNUSED.
Referenced by _pgr_compiler_version().
{
     UNUSED(fcinfo);
     char *ver = PROJECT_GIT_HASH;
     text *result = cstring_to_text(ver);
     PG_RETURN_TEXT_P(result);
 }
_pgr_lib_version()
PGDLLEXPORT Datum _pgr_lib_version (PG_FUNCTION_ARGS)
Definition at line 84 of file _version.c.
References _pgr_operating_system(), PG_FUNCTION_INFO_V1(), PROJECT_LIB_NAME, and UNUSED.
Referenced by _pgr_git_hash().
{
     UNUSED(fcinfo);
     char *ver = PROJECT_LIB_NAME;
     text *result = cstring_to_text(ver);
     PG_RETURN_TEXT_P(result);
 }
_pgr_operating_system()
PGDLLEXPORT Datum _pgr_operating_system (PG_FUNCTION_ARGS)
Definition at line 92 of file _version.c.
References _pgr_pgsql_version(), CMAKE_SYSTEM_NAME, PG_FUNCTION_INFO_V1(), and UNUSED.
Referenced by _pgr_lib_version().
{
     UNUSED(fcinfo);
     char *ver = CMAKE_SYSTEM_NAME;
     text *result = cstring_to_text(ver);
     PG_RETURN_TEXT_P(result);
 }
_pgr_pgsql_version()
PGDLLEXPORT Datum _pgr_pgsql_version (PG_FUNCTION_ARGS)
Definition at line 101 of file _version.c.
References POSTGRES_VERSION, and UNUSED.
Referenced by _pgr_operating_system().
{
     UNUSED(fcinfo);
     char *ver = POSTGRES_VERSION;
     text *result = cstring_to_text(ver);
     PG_RETURN_TEXT_P(result);
 }
PG_FUNCTION_INFO_V1() [1/8]
PG_FUNCTION_INFO_V1 (_pgr_boost_version)
Referenced by _pgr_boost_version(), _pgr_build_type(), _pgr_compilation_date(), _pgr_compiler_version(), _pgr_git_hash(), _pgr_lib_version(), and _pgr_operating_system().
PG_FUNCTION_INFO_V1() [2/8]
PG_FUNCTION_INFO_V1 (_pgr_build_type)
PG_FUNCTION_INFO_V1() [3/8]
PG_FUNCTION_INFO_V1 (_pgr_compilation_date)
PG_FUNCTION_INFO_V1() [4/8]
PG_FUNCTION_INFO_V1 (_pgr_compiler_version)
PG_FUNCTION_INFO_V1() [5/8]
PG_FUNCTION_INFO_V1 (_pgr_git_hash)
PG_FUNCTION_INFO_V1() [6/8]
PG_FUNCTION_INFO_V1 (_pgr_lib_version)
PG_FUNCTION_INFO_V1() [7/8]
PG_FUNCTION_INFO_V1 (_pgr_operating_system)
PG_FUNCTION_INFO_V1() [8/8]
PG_FUNCTION_INFO_V1 (_pgr_pgsql_version)