PGROUTING: alloc.hpp File Reference
alloc.hpp File Reference
#include <string>
#include <sstream>
Namespaces
namespace pgrouting
The main file which calls the respective boost function.
Functions
template<typename T >
T * pgrouting::pgr_alloc (std::size_t size, T *ptr)
allocates memory
template<typename T >
T * pgrouting::pgr_free (T *ptr)
void * SPI_palloc (size_t size)
void SPI_pfree (void *pointer)
void * SPI_repalloc (void *pointer, size_t size)
char * pgrouting::to_pg_msg (const std::ostringstream &msg)
char * pgrouting::to_pg_msg (const std::string &msg)
Function Documentation
SPI_palloc()
void * SPI_palloc (size_t size) extern
Referenced by pgrouting::pgr_alloc().
SPI_pfree()
void SPI_pfree (void * pointer) extern
Referenced by pgrouting::pgr_free().
SPI_repalloc()
void * SPI_repalloc (void * pointer, size_t size) extern
Referenced by pgrouting::pgr_alloc().