PGROUTING: allpairs_driver.hpp File Reference
allpairs_driver.hpp File Reference
#include <cstddef>
#include <string>
Typedefs
using IID_t_rt = IID_t_rt
Functions
void do_allpairs (std::string, bool, int, IID_t_rt **, size_t *, char **, char **)
Typedef Documentation
IID_t_rt
using IID_t_rt = IID_t_rt
Definition at line 42 of file allpairs_driver.hpp.
Function Documentation
do_allpairs()
void do_allpairs (std::string edges_sql, bool directed, int which, IID_t_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** err_msg)
Definition at line 43 of file allpairs_driver.cpp.
{
    using pgrouting::to_pg_msg;
    using pgrouting::pgr_free;
    std::ostringstream log;
    std::ostringstream err;
    std::string hint;
    try {
        pgassert(!(*log_msg));
        pgassert(!(*err_msg));
        pgassert(!(*return_tuples));
        pgassert(*return_count == 0);
        using pgrouting::johnson;
        using pgrouting::floydWarshall;
        using pgrouting::to_postgres::matrix_to_tuple;
        hint = edges_sql;
        auto edges = pgrouting::pgget::get_edges(std::string(edges_sql), true, true);
        if (edges.empty()) {
            throw std::string("No edges found");
        }
        hint = "";
        if (directed) {
            log << "Processing Directed graph\n";
            pgrouting::DirectedGraph digraph;
            digraph.insert_edges(edges);
            if (which == 0) {
                auto matrix = johnson(digraph);
                matrix_to_tuple(digraph, matrix, *return_count, return_tuples);
            } else {
                auto matrix = floydWarshall(digraph);
                matrix_to_tuple(digraph, matrix, *return_count, return_tuples);
            }
        } else {
            log << "Processing Undirected graph\n";
            pgrouting::UndirectedGraph undigraph;
            undigraph.insert_edges(edges);
            if (which == 0) {
                auto matrix = johnson(undigraph);
                matrix_to_tuple(undigraph, matrix, *return_count, return_tuples);
            } else {
                auto matrix = floydWarshall(undigraph);
                matrix_to_tuple(undigraph, matrix, *return_count, return_tuples);
            }
        }
        if (*return_count == 0) {
            err <<  "No result generated, report this error\n";
            *err_msg = to_pg_msg(err);
            *return_tuples = NULL;
            *return_count = 0;
            return;
        }
        *log_msg = to_pg_msg(log);
    } catch (AssertFailedException &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch (const std::string &ex) {
        *err_msg = to_pg_msg(ex);
        *log_msg = hint.empty()? to_pg_msg(hint) : to_pg_msg(log);
    } catch (std::exception &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch(...) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << "Caught unknown exception!";
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    }
}
References pgrouting::floydWarshall(), pgrouting::pgget::get_edges(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::insert_edges(), pgrouting::johnson(), pgrouting::to_postgres::matrix_to_tuple(), pgassert, pgrouting::pgr_free(), pgrouting::to_pg_msg(), and AssertFailedException::what().
Referenced by pgr_process_allpairs().