PGROUTING: allpairs_process.cpp File Reference
allpairs_process.cpp File Reference
#include "process/allpairs_process.h"
#include "c_common/postgres_connection.h"
#include "c_common/e_report.h"
#include "c_common/time_msg.h"
#include <string>
#include "c_types/iid_t_rt.h"
#include "cpp_common/assert.hpp"
#include "drivers/allpairs_driver.hpp"
Functions
void pgr_process_allpairs (const char *edges_sql, bool directed, int which, IID_t_rt **result_tuples, size_t *result_count)
which = 0 -> johnson which = 1 -> floydWarshall
Function Documentation
pgr_process_allpairs()
void pgr_process_allpairs (const char * edges_sql, bool directed, int which, IID_t_rt ** result_tuples, size_t * result_count)
which = 0 -> johnson which = 1 -> floydWarshall
This is c++ code, linked as C code, because pgr_process_allpairs is called from C code
Definition at line 55 of file allpairs_process.cpp.
{
    pgassert(edges_sql);
    pgassert(!(*result_tuples));
    pgassert(*result_count == 0);
    pgr_SPI_connect();
    char* log_msg = NULL;
    char* notice_msg = NULL;
    char* err_msg = NULL;
    clock_t start_t = clock();
    do_allpairs(
            edges_sql, directed,
            which,
            result_tuples, result_count,
            &log_msg, &err_msg);
    if (which == 0) {
        time_msg(std::string(" processing pgr_johnson").c_str(), start_t, clock());
    } else {
        time_msg(std::string(" processing pgr_floydWarshall").c_str(), start_t, clock());
    }
    if (err_msg && (*result_tuples)) {
        pfree(*result_tuples);
        (*result_tuples) = NULL;
        (*result_count) = 0;
    }
    pgr_global_report(&log_msg, &notice_msg, &err_msg);
    pgr_SPI_finish();
}
References do_allpairs(), pgassert, pgr_global_report(), pgr_SPI_connect(), pgr_SPI_finish(), and time_msg().
Referenced by _pgr_floydwarshall(), and _pgr_johnson().