PGROUTING: allpairs_process.h File Reference
allpairs_process.h File Reference
#include <stddef.h>
#include <stdbool.h>
Typedefs
typedef struct IID_t_rt IID_t_rt
Functions
void pgr_process_allpairs (const char *, bool, int, IID_t_rt **, size_t *)
which = 0 -> johnson which = 1 -> floydWarshall
Typedef Documentation
IID_t_rt
typedef struct IID_t_rt IID_t_rt
Definition at line 36 of file allpairs_process.h.
Function Documentation
pgr_process_allpairs()
void pgr_process_allpairs (const char * edges_sql, bool directed, int which, IID_t_rt ** result_tuples, size_t * result_count)
which = 0 -> johnson which = 1 -> floydWarshall
This is c++ code, linked as C code, because pgr_process_allpairs is called from C code
Definition at line 55 of file allpairs_process.cpp.
{
    pgassert(edges_sql);
    pgassert(!(*result_tuples));
    pgassert(*result_count == 0);
    pgr_SPI_connect();
    char* log_msg = NULL;
    char* notice_msg = NULL;
    char* err_msg = NULL;
    clock_t start_t = clock();
    do_allpairs(
            edges_sql, directed,
            which,
            result_tuples, result_count,
            &log_msg, &err_msg);
    if (which == 0) {
        time_msg(std::string(" processing pgr_johnson").c_str(), start_t, clock());
    } else {
        time_msg(std::string(" processing pgr_floydWarshall").c_str(), start_t, clock());
    }
    if (err_msg && (*result_tuples)) {
        pfree(*result_tuples);
        (*result_tuples) = NULL;
        (*result_count) = 0;
    }
    pgr_global_report(&log_msg, &notice_msg, &err_msg);
    pgr_SPI_finish();
}
References do_allpairs(), pgassert, pgr_global_report(), pgr_SPI_connect(), pgr_SPI_finish(), and time_msg().
Referenced by _pgr_floydwarshall(), and _pgr_johnson().