PGROUTING: betweennessCentrality_driver.h File Reference
betweennessCentrality_driver.h File Reference
#include <stddef.h>
#include <stdbool.h>
Typedefs
typedef struct IID_t_rt IID_t_rt
Functions
void pgr_do_betweennessCentrality (const char *, bool, IID_t_rt **, size_t *, char **, char **)
Typedef Documentation
IID_t_rt
typedef struct IID_t_rt IID_t_rt
Definition at line 41 of file betweennessCentrality_driver.h.
Function Documentation
pgr_do_betweennessCentrality()
void pgr_do_betweennessCentrality (const char * edges_sql, bool directed, IID_t_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** err_msg)
Definition at line 43 of file betweennessCentrality_driver.cpp.
{
    using pgrouting::to_pg_msg;
    using pgrouting::pgr_free;
    std::ostringstream log;
    std::ostringstream err;
    const char *hint = nullptr;
    try {
        pgassert(!(*log_msg));
        pgassert(!(*err_msg));
        pgassert(!(*return_tuples));
        pgassert(*return_count == 0);
        using pgrouting::metrics::betweennessCentrality;
        using pgrouting::to_postgres::vector_to_tuple;
        hint = edges_sql;
        auto edges = pgrouting::pgget::get_edges(std::string(edges_sql), true, true);
        if (edges.empty()) {
            throw std::string("No edges found");
        }
        hint = nullptr;
        if (directed) {
            log << "Processing Directed graph\n";
            pgrouting::DirectedGraph digraph;
            digraph.insert_edges(edges);
            vector_to_tuple(digraph, betweennessCentrality(digraph), *return_count, return_tuples);
        } else {
            log << "Processing Undirected graph\n";
            pgrouting::UndirectedGraph undigraph;
            undigraph.insert_edges(edges);
            vector_to_tuple(undigraph, betweennessCentrality(undigraph), *return_count, return_tuples);
        }
        if (*return_count == 0) {
            err <<  "No result generated, report this error\n";
            *err_msg = to_pg_msg(err);
            *return_tuples = NULL;
            *return_count = 0;
            return;
        }
        *log_msg = to_pg_msg(log);
    } catch (AssertFailedException &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch (const std::string &ex) {
        *err_msg = to_pg_msg(ex);
        *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
    } catch (std::exception &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch(...) {
       (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << "Caught unknown exception!";
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    }
}
References pgrouting::metrics::betweennessCentrality(), pgrouting::pgget::get_edges(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::insert_edges(), pgassert, pgrouting::pgr_free(), pgrouting::to_pg_msg(), pgrouting::to_postgres::vector_to_tuple(), and AssertFailedException::what().
Referenced by process().