PGROUTING: binaryBreadthFirstSearch_driver.h File Reference
binaryBreadthFirstSearch_driver.h File Reference
#include <postgres.h>
#include <utils/array.h>
#include "cpp_common/undefPostgresDefine.hpp"
#include <stddef.h>
#include <stdint.h>
Typedefs
typedef struct Path_rt Path_rt
Functions
void pgr_do_binaryBreadthFirstSearch (const char *, const char *, ArrayType *, ArrayType *, bool, Path_rt **, size_t *, char **, char **, char **)
Typedef Documentation
Path_rt
typedef struct Path_rt Path_rt
Definition at line 55 of file binaryBreadthFirstSearch_driver.h.
Function Documentation
pgr_do_binaryBreadthFirstSearch()
void pgr_do_binaryBreadthFirstSearch (const char * edges_sql, const char * combinations_sql, ArrayType * starts, ArrayType * ends, bool directed, Path_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 125 of file binaryBreadthFirstSearch_driver.cpp.
{
    using pgrouting::Path;
    using pgrouting::pgr_alloc;
    using pgrouting::to_pg_msg;
    using pgrouting::pgr_free;
    using pgrouting::utilities::get_combinations;
    using pgrouting::pgget::get_edges;
    std::ostringstream log;
    std::ostringstream err;
    std::ostringstream notice;
    const char *hint = nullptr;
    const char c_err_msg[] = "Graph Condition Failed: Graph should have at most two distinct non-negative edge costs! "
                             "If there are exactly two distinct edge costs, one of them must equal zero!";
    try {
        pgassert(!(*log_msg));
        pgassert(!(*notice_msg));
        pgassert(!(*err_msg));
        pgassert(!(*return_tuples));
        pgassert(*return_count == 0);
        hint = combinations_sql;
        auto combinations = get_combinations(combinations_sql, starts, ends, true);
        hint = nullptr;
        if (combinations.empty() && combinations_sql) {
            *notice_msg = to_pg_msg("No (source, target) pairs found");
            *log_msg = to_pg_msg(combinations_sql);
            return;
        }
        hint = edges_sql;
        auto edges = pgrouting::pgget::get_edges(std::string(edges_sql), true, false);
        if (edges.empty()) {
            *notice_msg = to_pg_msg("No edges found");
            *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
            return;
        }
        std::deque< Path >paths;
        if (directed) {
            pgrouting::DirectedGraph digraph;
            digraph.insert_edges(edges);
            if (!(costCheck(digraph))) {
                err << c_err_msg;
                *err_msg = to_pg_msg(err);
                return;
            }
            paths = binaryBreadthFirstSearch(digraph, combinations);
        } else {
            pgrouting::UndirectedGraph undigraph;
            undigraph.insert_edges(edges);
            if (!(costCheck(undigraph))) {
                err << c_err_msg;
                *err_msg = to_pg_msg(err);
                return;
            }
            paths = binaryBreadthFirstSearch(undigraph, combinations);
        }
        size_t count(0);
        count = count_tuples(paths);
        if (count == 0) {
            (*return_tuples) = NULL;
            (*return_count) = 0;
            notice <<
                "No paths found";
            *log_msg = to_pg_msg(notice);
            return;
        }
        (*return_tuples) = pgr_alloc(count, (*return_tuples));
        log << "\nConverting a set of paths into the tuples";
        (*return_count) = (collapse_paths(return_tuples, paths));
        *log_msg = to_pg_msg(log);
        *notice_msg = to_pg_msg(notice);
    } catch (AssertFailedException &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch (const std::string &ex) {
        *err_msg = to_pg_msg(ex);
        *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
    } catch (std::exception &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch(...) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << "Caught unknown exception!";
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    }
}
References anonymous_namespace{binaryBreadthFirstSearch_driver.cpp}::binaryBreadthFirstSearch(), anonymous_namespace{binaryBreadthFirstSearch_driver.cpp}::costCheck(), pgrouting::utilities::get_combinations(), pgrouting::pgget::get_edges(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::insert_edges(), pgassert, pgrouting::pgr_alloc(), pgrouting::pgr_free(), pgrouting::to_pg_msg(), and AssertFailedException::what().
Referenced by process().