PGROUTING: binaryBreadthFirstSearch_driver.cpp File Reference
binaryBreadthFirstSearch_driver.cpp File Reference
#include "drivers/breadthFirstSearch/binaryBreadthFirstSearch_driver.h"
#include <sstream>
#include <deque>
#include <vector>
#include <algorithm>
#include <string>
#include <set>
#include "breadthFirstSearch/pgr_binaryBreadthFirstSearch.hpp"
#include "cpp_common/pgr_alloc.hpp"
#include "cpp_common/pgr_assert.h"
Functions
template<class G >
bool costCheck (G &graph)
void do_pgr_binaryBreadthFirstSearch (pgr_edge_t *data_edges, size_t total_edges, int64_t *start_vidsArr, size_t size_start_vidsArr, int64_t *end_vidsArr, size_t size_end_vidsArr, bool directed, General_path_element_t **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
template<class G >
std::deque< Path > pgr_binaryBreadthFirstSearch (G &graph, std::vector< int64_t > sources, std::vector< int64_t > targets)
Variables
const char COST_ERR_MSG []
const size_t MAX_UNIQUE_EDGE_COSTS = 2
Function Documentation
costCheck()
template<class G > bool costCheck (G & graph)
Definition at line 74 of file binaryBreadthFirstSearch_driver.cpp.
                      {
     typedef typename G::E E;
     typedef typename G::E_i E_i;
     auto edges = boost::edges(graph.graph);
     E e;
     E_i out_i;
     E_i out_end;
     std::set<double> cost_set;
     for (boost::tie(out_i, out_end) = edges;
             out_i != out_end; ++out_i) {
         e = *out_i;
         cost_set.insert(graph[e].cost);
         if (cost_set.size() > MAX_UNIQUE_EDGE_COSTS) {
             return false;
         }
     }
     if (cost_set.size() == 2) {
         if (*cost_set.begin() != 0.0) {
             return false;
         }
     }
     return true;
 }
References MAX_UNIQUE_EDGE_COSTS.
Referenced by do_pgr_binaryBreadthFirstSearch().
do_pgr_binaryBreadthFirstSearch()
void do_pgr_binaryBreadthFirstSearch (pgr_edge_t * data_edges, size_t total_edges, int64_t * start_vidsArr, size_t size_start_vidsArr, int64_t * end_vidsArr, size_t size_end_vidsArr, bool directed, General_path_element_t ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 105 of file binaryBreadthFirstSearch_driver.cpp.
{
     std::ostringstream log;
     std::ostringstream err;
     std::ostringstream notice;
     try {
         pgassert(total_edges != 0);
         pgassert(!(*log_msg));
         pgassert(!(*notice_msg));
         pgassert(!(*err_msg));
         pgassert(!(*return_tuples));
         pgassert(*return_count == 0);
         graphType gType = directed? DIRECTED: UNDIRECTED;
         // log << "Inserting vertices into a c++ vector structure";
         std::vector<int64_t>
             start_vertices(start_vidsArr, start_vidsArr + size_start_vidsArr);
         std::vector< int64_t >
             end_vertices(end_vidsArr, end_vidsArr + size_end_vidsArr);
         std::deque< Path >paths;
         if (directed) {
             // log << "\nWorking with directed Graph";
             pgrouting::DirectedGraph digraph(gType);
             digraph.insert_edges(data_edges, total_edges);
             if (!(costCheck(digraph))) {
                 err << COST_ERR_MSG;
                 *err_msg = pgr_msg(err.str().c_str());
                 return;
             }
             paths = pgr_binaryBreadthFirstSearch(
                 digraph,
                 start_vertices,
                 end_vertices);
         } else {
             // log << "\nWorking with Undirected Graph";
             pgrouting::UndirectedGraph undigraph(gType);
             undigraph.insert_edges(data_edges, total_edges);
             if (!(costCheck(undigraph))) {
                 err << COST_ERR_MSG;
                 *err_msg = pgr_msg(err.str().c_str());
                 return;
             }
             paths = pgr_binaryBreadthFirstSearch(
                 undigraph,
                 start_vertices,
                 end_vertices);
         }
         size_t count(0);
         count = count_tuples(paths);
         if (count == 0) {
             (*return_tuples) = NULL;
             (*return_count) = 0;
             notice <<
                 "No paths found";
             *log_msg = pgr_msg(notice.str().c_str());
             return;
         }
         (*return_tuples) = pgr_alloc(count, (*return_tuples));
         log << "\nConverting a set of paths into the tuples";
         (*return_count) = (collapse_paths(return_tuples, paths));
         *log_msg = log.str().empty()?
             *log_msg :
             pgr_msg(log.str().c_str());
         *notice_msg = notice.str().empty()?
             *notice_msg :
             pgr_msg(notice.str().c_str());
     } catch (AssertFailedException &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch (std::exception &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch(...) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << "Caught unknown exception!";
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     }
 }
References collapse_paths(), COST_ERR_MSG, costCheck(), count_tuples(), DIRECTED, pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::insert_edges(), pgassert, pgr_alloc(), pgr_binaryBreadthFirstSearch(), pgr_free(), pgr_msg(), UNDIRECTED, and AssertFailedException::what().
Referenced by process().
pgr_binaryBreadthFirstSearch()
template<class G > std::deque< Path > pgr_binaryBreadthFirstSearch (G & graph, std::vector< int64_t > sources, std::vector< int64_t > targets)
Definition at line 47 of file binaryBreadthFirstSearch_driver.cpp.
{
     std::sort(sources.begin(), sources.end());
     sources.erase(
             std::unique(sources.begin(), sources.end()),
             sources.end());
     std::sort(targets.begin(), targets.end());
     targets.erase(
             std::unique(targets.begin(), targets.end()),
             targets.end());
     pgrouting::functions::Pgr_binaryBreadthFirstSearch< G > fn_binaryBreadthFirstSearch;
     auto paths = fn_binaryBreadthFirstSearch.binaryBreadthFirstSearch(
             graph,
             sources, targets);
     return paths;
 }
References pgrouting::functions::Pgr_binaryBreadthFirstSearch< G >::binaryBreadthFirstSearch().
Referenced by do_pgr_binaryBreadthFirstSearch().
Variable Documentation
COST_ERR_MSG
const char COST_ERR_MSG[]
Initial value:
=  "Graph Condition Failed: Graph should have atmost two distinct non-negative edge costs! "
                             "If there are exactly two distinct edge costs, one of them must equal zero!"
Definition at line 70 of file binaryBreadthFirstSearch_driver.cpp.
Referenced by do_pgr_binaryBreadthFirstSearch().
MAX_UNIQUE_EDGE_COSTS
const size_t MAX_UNIQUE_EDGE_COSTS = 2
Definition at line 69 of file binaryBreadthFirstSearch_driver.cpp.
Referenced by costCheck().