PGROUTING: breadthFirstSearch_driver.h File Reference
breadthFirstSearch_driver.h File Reference
#include <postgres.h>
#include <utils/array.h>
#include "cpp_common/undefPostgresDefine.hpp"
#include <stddef.h>
#include <stdint.h>
Typedefs
typedef struct MST_rt MST_rt
Functions
void pgr_do_breadthFirstSearch (const char *, ArrayType *, int64_t, bool, MST_rt **, size_t *, char **, char **, char **)
Typedef Documentation
MST_rt
typedef struct MST_rt MST_rt
Definition at line 54 of file breadthFirstSearch_driver.h.
Function Documentation
pgr_do_breadthFirstSearch()
void pgr_do_breadthFirstSearch (const char * edges_sql, ArrayType * starts, int64_t max_depth, bool directed, MST_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 58 of file breadthFirstSearch_driver.cpp.
{
    using pgrouting::pgr_alloc;
    using pgrouting::to_pg_msg;
    using pgrouting::pgr_free;
    using pgrouting::pgget::get_intSet;
    std::ostringstream log;
    std::ostringstream err;
    std::ostringstream notice;
    const char *hint = nullptr;
    try {
        // NOLINTBEGIN(clang-analyzer-cplusplus.NewDelete)
        pgassert(!(*log_msg));
        pgassert(!(*notice_msg));
        pgassert(!(*err_msg));
        pgassert(!(*return_tuples));
        pgassert(*return_count == 0);
        // NOLINTEND(clang-analyzer-cplusplus.NewDelete)
        hint = edges_sql;
        auto edges = pgrouting::pgget::get_edges(std::string(edges_sql), true, false);
        if (edges.empty()) {
            *notice_msg = to_pg_msg("No edges found");
            *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
            return;
        }
        hint = nullptr;
        auto roots = get_intSet(starts);
        std::vector<MST_rt> results;
        if (directed) {
            pgrouting::DirectedGraph digraph;
            digraph.insert_edges(edges);
            results = breadthFirstSearch(digraph, roots, max_depth);
        } else {
            pgrouting::UndirectedGraph undigraph;
            undigraph.insert_edges(edges);
            results = breadthFirstSearch(undigraph, roots, max_depth);
        }
        auto count = results.size();
        if (count == 0) {
            (*return_tuples) = NULL;
            (*return_count) = 0;
            notice << "No traversal found";
            *log_msg = to_pg_msg(notice);
            return;
        }
        (*return_tuples) = pgr_alloc(count, (*return_tuples));
        (*return_count) = count;
        for (size_t i = 0; i < count; i++) {
            *((*return_tuples) + i) = results[i];
        }
        *log_msg = to_pg_msg(log);
        *notice_msg = to_pg_msg(notice);
    } catch (AssertFailedException &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch (const std::string &ex) {
        *err_msg = to_pg_msg(ex);
        *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
    } catch (std::exception &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch(...) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << "Caught unknown exception!";
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    }
}
References anonymous_namespace{breadthFirstSearch_driver.cpp}::breadthFirstSearch(), pgrouting::pgget::get_edges(), pgrouting::pgget::get_intSet(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::insert_edges(), pgassert, pgrouting::pgr_alloc(), pgrouting::pgr_free(), pgrouting::to_pg_msg(), and AssertFailedException::what().
Referenced by process().