PGROUTING: chinesePostman_driver.cpp File Reference
chinesePostman_driver.cpp File Reference
#include "drivers/chinese/chinesePostman_driver.h"
#include <sstream>
#include <deque>
#include <vector>
#include <set>
#include <string>
#include "cpp_common/pgdata_getters.hpp"
#include "chinese/chinesePostman.hpp"
#include "cpp_common/alloc.hpp"
#include "cpp_common/assert.hpp"
Functions
void pgr_do_directedChPP (const char *edges_sql, bool only_cost, Path_rt **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
Function Documentation
pgr_do_directedChPP()
void pgr_do_directedChPP (const char * edges_sql, bool only_cost, Path_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 46 of file chinesePostman_driver.cpp.
{
    using pgrouting::pgr_alloc;
    using pgrouting::to_pg_msg;
    using pgrouting::pgr_free;
    std::ostringstream log;
    std::ostringstream err;
    std::ostringstream notice;
    const char *hint = nullptr;
    try {
        pgassert(!(*log_msg));
        pgassert(!(*notice_msg));
        pgassert(!(*err_msg));
        pgassert(!(*return_tuples));
        pgassert(*return_count == 0);
        hint = edges_sql;
        auto edges = pgrouting::pgget::get_edges(std::string(edges_sql), true, false);
        if (edges.empty()) {
            *notice_msg = to_pg_msg("No edges found");
            *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
            return;
        }
        hint = nullptr;
        pgrouting::graph::PgrDirectedChPPGraph digraph(edges);
        double minCost;
        minCost = digraph.DirectedChPP();
        std::vector<Path_rt> pathEdges;
        if (only_cost) {
            if (minCost >= 0.0) {
                Path_rt edge = {};
                edge.node = edge.edge = -1;
                edge.cost = edge.agg_cost = minCost;
                pathEdges.push_back(edge);
            }
        } else {
            pathEdges = digraph.GetPathEdges();
        }
        size_t count = pathEdges.size();
        if (count == 0) {
            (*return_tuples) = NULL;
            (*return_count) = 0;
            notice <<
                "No paths found";
            *log_msg = to_pg_msg(notice);
            return;
        }
        (*return_tuples) = pgr_alloc(count, (*return_tuples));
        for (size_t i = 0; i < count; i++) {
            (*return_tuples)[i] = pathEdges[i];
        }
        *return_count = count;
        *log_msg = to_pg_msg(log);
        *notice_msg = to_pg_msg(notice);
    } catch (AssertFailedException &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch (const std::string &ex) {
        *err_msg = to_pg_msg(ex);
        *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
    } catch (std::exception &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch(...) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << "Caught unknown exception!";
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    }
}
References Path_rt::agg_cost, Path_rt::cost, pgrouting::graph::PgrDirectedChPPGraph::DirectedChPP(), Path_rt::edge, pgrouting::pgget::get_edges(), pgrouting::graph::PgrDirectedChPPGraph::GetPathEdges(), Path_rt::node, pgassert, pgrouting::pgr_alloc(), pgrouting::pgr_free(), pgrouting::to_pg_msg(), and AssertFailedException::what().
Referenced by process().