PGROUTING: pgrouting::Identifiers< T > Class Template Reference
pgrouting::Identifiers< T > Class Template Reference
#include "identifiers.hpp"
Public Types
typedef std::set< T >::const_iterator const_iterator
typedef std::set< T >::iterator iterator
Public Member Functions
void set_ids (const std::set< T > &ids)
define ids
constructors
Identifiers ()=default
Identifiers (const std::set< T > &data)
Identifiers (const size_t number)
Friends
std::ostream & operator<< (std::ostream &os, const Identifiers< T > &identifiers)
Prints the set of identifiers.
set like operators
std::set< T > m_ids
size_t size () const
bool empty () const
T front () const
const_iterator begin () const
const_iterator end () const
void pop_front ()
void clear ()
iterator begin ()
iterator end ()
bool has (const T other) const
true ids() has element
bool operator== (const Identifiers< T > &rhs) const
true when both sets are equal
set UNION
Identifiers< T > & operator+= (const Identifiers< T > &other)
compound set UNION set
Identifiers< T > & operator+= (const T &element)
compound set UNION element
Identifiers< T > operator+ (const Identifiers< T > &lhs, const Identifiers< T > &rhs)
set UNION set
set INTERSECTION
Identifiers< T > & operator*= (const Identifiers< T > &other)
compound set INTERSECTION set
Identifiers< T > & operator*= (const T &element)
compound set INTERSECTION element
Identifiers< T > operator* (const Identifiers< T > &lhs, const Identifiers< T > &rhs)
set INTERSECTION
set DIFFERENCE
Identifiers< T > & operator-= (const Identifiers< T > &other)
compound set DIFFERENCE set
Identifiers< T > & operator-= (const T &element)
compound set DIFFERENCE element
Identifiers< T > operator- (const Identifiers< T > &lhs, const Identifiers< T > &rhs)
Detailed Description
template<typename T>
class pgrouting::Identifiers< T >
Definition at line 49 of file identifiers.hpp.
Member Typedef Documentation
const_iterator
template<typename T > typedef std::set<T>::const_iterator pgrouting::Identifiers< T >::const_iterator
Definition at line 52 of file identifiers.hpp.
iterator
template<typename T > typedef std::set<T>::iterator pgrouting::Identifiers< T >::iterator
Definition at line 51 of file identifiers.hpp.
Constructor & Destructor Documentation
Identifiers() [1/3]
template<typename T > pgrouting::Identifiers< T >::Identifiers () default
Identifiers() [2/3]
template<typename T > pgrouting::Identifiers< T >::Identifiers (const std::set< T > & data) inline explicit
Definition at line 64 of file identifiers.hpp.
                                                : m_ids(data) {
    }
Identifiers() [3/3]
template<typename T > pgrouting::Identifiers< T >::Identifiers (const size_t number) inline explicit
Definition at line 71 of file identifiers.hpp.
{
        size_t i(0);
        std::generate_n(std::inserter(m_ids, m_ids.begin()),
                number,
                [&i](){ return i++; });
    }
References pgrouting::Identifiers< T >::m_ids.
Member Function Documentation
begin() [1/2]
template<typename T > iterator pgrouting::Identifiers< T >::begin () inline
Definition at line 89 of file identifiers.hpp.
{return m_ids.begin();}
References pgrouting::Identifiers< T >::m_ids.
begin() [2/2]
template<typename T > const_iterator pgrouting::Identifiers< T >::begin () const inline
Definition at line 85 of file identifiers.hpp.
{return m_ids.begin();}
References pgrouting::Identifiers< T >::m_ids.
Referenced by pgrouting::vrp::Initial_solution::one_truck_all_orders().
clear()
template<typename T > void pgrouting::Identifiers< T >::clear () inline
Definition at line 88 of file identifiers.hpp.
{m_ids.clear();}
References pgrouting::Identifiers< T >::m_ids.
Referenced by pgrouting::contraction::Pgr_linear< G >::calculateVertices(), pgrouting::CH_edge::clear_contracted_vertices(), pgrouting::CH_vertex::clear_contracted_vertices(), pgrouting::contraction::Pgr_deadend< G >::doContraction(), and pgrouting::Identifiers< T >::operator*=().
empty()
template<typename T > bool pgrouting::Identifiers< T >::empty () const inline
Definition at line 83 of file identifiers.hpp.
{return m_ids.empty(); }
References pgrouting::Identifiers< T >::m_ids.
Referenced by pgrouting::vrp::Initial_solution::do_while_foo(), pgrouting::contraction::Pgr_deadend< G >::doContraction(), pgrouting::contraction::Pgr_linear< G >::doContraction(), pgrouting::vrp::PD_Orders::find_best_I(), pgrouting::vrp::PD_Orders::find_best_J(), pgrouting::CH_edge::has_contracted_vertices(), pgrouting::CH_vertex::has_contracted_vertices(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), and pgrouting::graph::PgrDirectedChPPGraph::setPathEdges().
end() [1/2]
template<typename T > iterator pgrouting::Identifiers< T >::end () inline
Definition at line 90 of file identifiers.hpp.
{return m_ids.end();}
References pgrouting::Identifiers< T >::m_ids.
end() [2/2]
template<typename T > const_iterator pgrouting::Identifiers< T >::end () const inline
Definition at line 86 of file identifiers.hpp.
{return m_ids.end();}
References pgrouting::Identifiers< T >::m_ids.
front()
template<typename T > T pgrouting::Identifiers< T >::front () const inline
Definition at line 84 of file identifiers.hpp.
{return *m_ids.begin();}
References pgrouting::Identifiers< T >::m_ids.
Referenced by pgrouting::vrp::Initial_solution::do_while_foo(), pgrouting::contraction::Pgr_deadend< G >::doContraction(), pgrouting::contraction::Pgr_linear< G >::doContraction(), pgrouting::vrp::PD_Orders::find_best_I(), pgrouting::vrp::PD_Orders::find_best_J(), pgrouting::vrp::Fleet::get_truck(), pgrouting::contraction::Pgr_linear< G >::one_cycle(), and pgrouting::vrp::Initial_solution::one_truck_all_orders().
has()
template<typename T > bool pgrouting::Identifiers< T >::has (const T other) const inline
true ids() has element
Parameters
[in] other Identifier of type T
Definition at line 102 of file identifiers.hpp.
{
        return (m_ids.find(other) != m_ids.end());
    }
References pgrouting::Identifiers< T >::m_ids.
Referenced by pgrouting::algorithms::bridges(), pgrouting::graph::PgrDirectedChPPGraph::EulerCircuitDFS(), pgrouting::vrp::Vehicle_pickDeliver::has_order(), pgrouting::graph::Pgr_contractionGraph< G, t_directed >::is_forbidden(), and pgrouting::Identifiers< T >::operator*=().
operator*=() [1/2]
template<typename T > Identifiers< T > & pgrouting::Identifiers< T >::operator*= (const Identifiers< T > & other) inline
compound set INTERSECTION set
Parameters
[in] other is a set of identifiers of type Identifiers<T>
Definition at line 178 of file identifiers.hpp.
{
        *this = *this * other;
        return *this;
    }
operator*=() [2/2]
template<typename T > Identifiers< T > & pgrouting::Identifiers< T >::operator*= (const T & element) inline
compound set INTERSECTION element
Parameters
[in] element is an identifiers of type T
Definition at line 188 of file identifiers.hpp.
{
        if (has(element)) {
            m_ids.clear();
            m_ids.insert(element);
        } else {
            m_ids.clear();
        }
        return *this;
    }
References pgrouting::Identifiers< T >::clear(), pgrouting::Identifiers< T >::has(), and pgrouting::Identifiers< T >::m_ids.
operator+=() [1/2]
template<typename T > Identifiers< T > & pgrouting::Identifiers< T >::operator+= (const Identifiers< T > & other) inline
compound set UNION set
Parameters
[in] other set of identifiers
Definition at line 135 of file identifiers.hpp.
{
        m_ids.insert(other.m_ids.begin(), other.m_ids.end());
        return *this;
    }
References pgrouting::Identifiers< T >::m_ids.
operator+=() [2/2]
template<typename T > Identifiers< T > & pgrouting::Identifiers< T >::operator+= (const T & element) inline
compound set UNION element
Parameters
[in] element of type T
Definition at line 144 of file identifiers.hpp.
{
        m_ids.insert(element);
        return *this;
    }
References pgrouting::Identifiers< T >::m_ids.
operator-=() [1/2]
template<typename T > Identifiers< T > & pgrouting::Identifiers< T >::operator-= (const Identifiers< T > & other) inline
compound set DIFFERENCE set
Parameters
[in] other is a set of identifiers of type Identifiers<T> Replaces this set with the set difference between this set and other
Definition at line 228 of file identifiers.hpp.
{
        *this = *this - other;
        return *this;
    }
operator-=() [2/2]
template<typename T > Identifiers< T > & pgrouting::Identifiers< T >::operator-= (const T & element) inline
compound set DIFFERENCE element
Parameters
[in] element to be removed
Definition at line 237 of file identifiers.hpp.
{
            m_ids.erase(element);
        return *this;
    }
References pgrouting::Identifiers< T >::m_ids.
operator==()
template<typename T > bool pgrouting::Identifiers< T >::operator== (const Identifiers< T > & rhs) const inline
true when both sets are equal
Parameters
[in] rhs set of identifiers to be compared
Definition at line 111 of file identifiers.hpp.
{
        return std::equal(m_ids.begin(), m_ids.end(), rhs.m_ids.begin());
    }
References pgrouting::Identifiers< T >::m_ids.
pop_front()
template<typename T > void pgrouting::Identifiers< T >::pop_front () inline
Definition at line 87 of file identifiers.hpp.
{m_ids.erase(m_ids.begin());}
References pgrouting::Identifiers< T >::m_ids.
Referenced by pgrouting::contraction::Pgr_linear< G >::one_cycle(), and pgrouting::vrp::Initial_solution::one_truck_all_orders().
set_ids()
template<typename T > void pgrouting::Identifiers< T >::set_ids (const std::set< T > & ids) inline
define ids
Definition at line 57 of file identifiers.hpp.
{
        m_ids = ids;
    }
References pgrouting::Identifiers< T >::m_ids.
Referenced by pgrouting::detail::compute_shortcuts().
size()
template<typename T > size_t pgrouting::Identifiers< T >::size () const inline
Definition at line 82 of file identifiers.hpp.
{return m_ids.size(); }
References pgrouting::Identifiers< T >::m_ids.
Referenced by pgrouting::vrp::Initial_solution::do_while_foo(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Fleet::get_truck(), pgrouting::graph::Pgr_contractionGraph< G, t_directed >::is_dead_end(), pgrouting::contraction::Pgr_linear< G >::one_cycle(), pgrouting::vrp::Vehicle_pickDeliver::orders_size(), pgr_do_pickDeliverEuclidean(), and pgrouting::detail::vertex_contraction().
Friends And Related Symbol Documentation
operator*
template<typename T > Identifiers< T > operator* (const Identifiers< T > & lhs, const Identifiers< T > & rhs) friend
set INTERSECTION
Parameters
[in] lhs Identifiers
[in] rhs Identifiers
Definition at line 163 of file identifiers.hpp.
{
            std::set<T> result;
            std::set_intersection(
                    lhs.m_ids.begin(), lhs.m_ids.end(),
                    rhs.m_ids.begin(), rhs.m_ids.end(),
                    std::inserter(result, result.begin()));
            return Identifiers<T>(result);
        }
operator+
template<typename T > Identifiers< T > operator+ (const Identifiers< T > & lhs, const Identifiers< T > & rhs) friend
set UNION set
Parameters
[in] lhs Identifiers
[in] rhs Identifiers
Definition at line 123 of file identifiers.hpp.
{
        Identifiers<T> union_ids(lhs);
        union_ids += rhs;
        return union_ids;
    }
operator-
template<typename T > Identifiers< T > operator- (const Identifiers< T > & lhs, const Identifiers< T > & rhs) friend
Definition at line 210 of file identifiers.hpp.
{
            std::set<T> result;
            std::set_difference(
                    lhs.m_ids.begin(), lhs.m_ids.end(),
                    rhs.m_ids.begin(), rhs.m_ids.end(),
                    std::inserter(result, result.begin()));
            return Identifiers<T>(result);
        }
operator<<
template<typename T > std::ostream & operator<< (std::ostream & os, const Identifiers< T > & identifiers) friend
Prints the set of identifiers.
Definition at line 246 of file identifiers.hpp.
{
            os << "{";
            for (auto identifier : identifiers.m_ids) {
                os << identifier << ", ";
            }
            os << "}";
            return os;
        }
Member Data Documentation
m_ids
template<typename T > std::set<T> pgrouting::Identifiers< T >::m_ids private
Definition at line 95 of file identifiers.hpp.
Referenced by pgrouting::Identifiers< T >::Identifiers(), pgrouting::Identifiers< T >::begin(), pgrouting::Identifiers< T >::begin(), pgrouting::Identifiers< T >::clear(), pgrouting::Identifiers< T >::empty(), pgrouting::Identifiers< T >::end(), pgrouting::Identifiers< T >::end(), pgrouting::Identifiers< T >::front(), pgrouting::Identifiers< T >::has(), pgrouting::Identifiers< T >::operator*=(), pgrouting::Identifiers< T >::operator+=(), pgrouting::Identifiers< T >::operator+=(), pgrouting::Identifiers< T >::operator-=(), pgrouting::Identifiers< T >::operator==(), pgrouting::Identifiers< T >::pop_front(), pgrouting::Identifiers< T >::set_ids(), and pgrouting::Identifiers< T >::size().
The documentation for this class was generated from the following file:
identifiers.hpp