PGROUTING: pgrouting::functions::Pgr_boyerMyrvold< G > Class Template Reference
pgrouting::functions::Pgr_boyerMyrvold< G > Class Template Reference
#include "pgr_boyerMyrvold.hpp"
Public Types
typedef G::E E
typedef G::E_i E_i
typedef G::V V
Public Member Functions
std::vector< pgr_boyer_t > boyerMyrvold (G &graph)
void clear ()
clear
std::string get_error () const
get_error
std::string get_log () const
get_log
std::string get_notice () const
get_notice
bool has_error () const
get_error
bool isPlanar (G &graph)
Public Attributes
std::ostringstream error
Stores the error information.
std::ostringstream log
Stores the hint information.
std::ostringstream notice
Stores the notice information.
Private Member Functions
std::vector< pgr_boyer_t > generateboyerMyrvold (const G &graph)
Detailed Description
template<class G>
class pgrouting::functions::Pgr_boyerMyrvold< G >
Definition at line 47 of file pgr_boyerMyrvold.hpp.
Member Typedef Documentation
E
template<class G > typedef G::E pgrouting::functions::Pgr_boyerMyrvold< G >::E
Definition at line 50 of file pgr_boyerMyrvold.hpp.
E_i
template<class G > typedef G::E_i pgrouting::functions::Pgr_boyerMyrvold< G >::E_i
Definition at line 51 of file pgr_boyerMyrvold.hpp.
V
template<class G > typedef G::V pgrouting::functions::Pgr_boyerMyrvold< G >::V
Definition at line 49 of file pgr_boyerMyrvold.hpp.
Member Function Documentation
boyerMyrvold()
template<class G > std::vector<pgr_boyer_t> pgrouting::functions::Pgr_boyerMyrvold< G >::boyerMyrvold (G & graph) inline
Definition at line 52 of file pgr_boyerMyrvold.hpp.
{
           return generateboyerMyrvold(graph);
      }
References pgrouting::functions::Pgr_boyerMyrvold< G >::generateboyerMyrvold().
Referenced by do_pgr_boyerMyrvold().
clear()
void pgrouting::Pgr_messages::clear () inherited
clear
Clears All the messages
Definition at line 59 of file pgr_messages.cpp.
                     {
     log.str("");
     log.clear();
     notice.str("");
     notice.clear();
     error.str("");
     error.clear();
 }
References pgrouting::Pgr_messages::error, pgrouting::Pgr_messages::log, and pgrouting::Pgr_messages::notice.
Referenced by do_pgr_pickDeliver().
generateboyerMyrvold()
template<class G > std::vector< pgr_boyer_t > pgrouting::functions::Pgr_boyerMyrvold< G >::generateboyerMyrvold (const G & graph) inline private
Definition at line 74 of file pgr_boyerMyrvold.hpp.
{
      std::vector< pgr_boyer_t > results;
      auto check = boost::boyer_myrvold_planarity_test(graph.graph);
      if (check) {
          E_i ei, ei_end;
      for (boost::tie(ei, ei_end) = edges(graph.graph); ei != ei_end; ++ei) {
          int64_t src = graph[graph.source(*ei)].id;
          int64_t tgt = graph[graph.target(*ei)].id;
          double cost = graph[*ei].cost;
          pgr_boyer_t tmp;
          tmp.source = src;
          tmp.target = tgt;
          tmp.cost = cost;
          results.push_back(tmp);
       }
     }
      return results;
     }
References pgr_boyer_t::cost, pgr_boyer_t::source, and pgr_boyer_t::target.
Referenced by pgrouting::functions::Pgr_boyerMyrvold< G >::boyerMyrvold().
get_error()
std::string pgrouting::Pgr_messages::get_error () const inherited
get_error
Returns
the current contents of the log and clears the log
Definition at line 53 of file pgr_messages.cpp.
{
     auto str = error.str();
     return str;
 }
References pgrouting::Pgr_messages::error.
Referenced by do_pgr_many_withPointsDD(), do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), do_pgr_withPoints(), do_pgr_withPointsKsp(), and pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver().
get_log()
std::string pgrouting::Pgr_messages::get_log () const inherited
get_log
Returns
the current contents of the log and clears the log
Definition at line 36 of file pgr_messages.cpp.
{
     auto str = log.str();
     return str;
 }
References pgrouting::Pgr_messages::log.
Referenced by do_pgr_bipartite(), do_pgr_boyerMyrvold(), do_pgr_LTDTree(), do_pgr_makeConnected(), do_pgr_many_withPointsDD(), do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), do_pgr_withPoints(), do_pgr_withPointsKsp(), pgr_bellman_ford(), pgr_dijkstraTR(), and pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver().
get_notice()
std::string pgrouting::Pgr_messages::get_notice () const inherited
get_notice
Returns
the current contents of the log and clears the log
Definition at line 42 of file pgr_messages.cpp.
{
     auto str = notice.str();
     return str;
 }
References pgrouting::Pgr_messages::notice.
has_error()
bool pgrouting::Pgr_messages::has_error () const inherited
get_error
Returns
the current contents of the log and clears the log
Definition at line 48 of file pgr_messages.cpp.
{
     return  !error.str().empty();
 }
References pgrouting::Pgr_messages::error.
Referenced by do_pgr_many_withPointsDD(), do_pgr_withPoints(), and do_pgr_withPointsKsp().
isPlanar()
template<class G > bool pgrouting::functions::Pgr_boyerMyrvold< G >::isPlanar (G & graph) inline
Definition at line 56 of file pgr_boyerMyrvold.hpp.
{
           /* abort in case of an interruption occurs (e.g. the query is being cancelled) */
           CHECK_FOR_INTERRUPTS();
           try {
              return (boost::boyer_myrvold_planarity_test(graph.graph));
           } catch (boost::exception const& ex) {
              (void)ex;
              throw;
           } catch (std::exception &e) {
              (void)e;
              throw;
           } catch (...) {
              throw;
           }
           return false;
      }
Referenced by do_pgr_isPlanar().
Member Data Documentation
error
std::ostringstream pgrouting::Pgr_messages::error mutable inherited
Stores the error information.
Definition at line 85 of file pgr_messages.h.
Referenced by pgrouting::vrp::Fleet::build_fleet(), pgrouting::Pg_points_graph::check_points(), pgrouting::Pgr_messages::clear(), pgrouting::Pg_points_graph::create_new_edges(), pgrouting::Pgr_messages::get_error(), pgrouting::Pgr_messages::has_error(), pgrouting::vrp::Fleet::is_fleet_ok(), and pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver().
log
std::ostringstream pgrouting::Pgr_messages::log mutable inherited
Stores the hint information.
Definition at line 81 of file pgr_messages.h.
Referenced by pgrouting::vrp::Fleet::add_vehicle(), Pgr_bellman_ford< G >::bellman_ford(), Pgr_bellman_ford< G >::bellman_ford_1_to_1(), Pgr_bellman_ford< G >::bellman_ford_1_to_many(), pgrouting::alphashape::Pgr_alphaShape::build_best_alpha(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::Pg_points_graph::check_points(), pgrouting::Pgr_messages::clear(), pgrouting::Pg_points_graph::create_new_edges(), pgrouting::vrp::Vehicle_pickDeliver::do_while_feasable(), pgrouting::vrp::Initial_solution::do_while_foo(), pgrouting::functions::Pgr_makeConnected< G >::generatemakeConnected(), pgrouting::Pgr_messages::get_log(), Pgr_bellman_ford< G >::get_paths(), pgrouting::vrp::Pgr_pickDeliver::get_postgres_result(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Fleet::is_fleet_ok(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), pgrouting::vrp::Optimize::Optimize(), pgrouting::Pg_points_graph::Pg_points_graph(), pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Optimize::save_if_best(), pgrouting::vrp::Solution::Solution(), pgrouting::vrp::Pgr_pickDeliver::solve(), and pgrouting::vrp::Vehicle::Vehicle().
notice
std::ostringstream pgrouting::Pgr_messages::notice mutable inherited
Stores the notice information.
Definition at line 83 of file pgr_messages.h.
Referenced by pgrouting::Pgr_messages::clear(), and pgrouting::Pgr_messages::get_notice().
The documentation for this class was generated from the following file:
pgr_boyerMyrvold.hpp