PGROUTING: pgrouting::functions::CuthillMckeeOrdering< G > Class Template Reference
pgrouting::functions::CuthillMckeeOrdering< G > Class Template Reference
#include "cuthillMckeeOrdering.hpp"
Public Types
typedef G::E E
typedef boost::adjacency_list< boost::vecS, boost::vecS, boost::undirectedS > Graph
typedef boost::graph_traits< Graph >::vertices_size_type size_type
typedef G::V V
typedef boost::graph_traits< Graph >::vertex_descriptor Vertex
Public Member Functions
void clear ()
clear
std::string get_error () const
get_error
std::string get_log () const
get_log
std::string get_notice () const
get_notice
bool has_error () const
get_error
Public Attributes
std::ostringstream error
Stores the error information.
std::ostringstream log
Stores the hint information.
std::ostringstream notice
Stores the notice information.
CuthillMckeeOrdering
std::vector< II_t_rt > cuthillMckeeOrdering (G &graph)
cuthillMckeeOrdering function
std::vector< II_t_rt > get_results (std::vector< size_type > &inv_perm, const G &graph)
to get the results
Detailed Description
template<class G>
class pgrouting::functions::CuthillMckeeOrdering< G >
Definition at line 64 of file cuthillMckeeOrdering.hpp.
Member Typedef Documentation
E
template<class G > typedef G::E pgrouting::functions::CuthillMckeeOrdering< G >::E
Definition at line 67 of file cuthillMckeeOrdering.hpp.
Graph
template<class G > typedef boost::adjacency_list<boost::vecS, boost::vecS, boost::undirectedS> pgrouting::functions::CuthillMckeeOrdering< G >::Graph
Definition at line 68 of file cuthillMckeeOrdering.hpp.
size_type
template<class G > typedef boost::graph_traits<Graph>::vertices_size_type pgrouting::functions::CuthillMckeeOrdering< G >::size_type
Definition at line 69 of file cuthillMckeeOrdering.hpp.
V
template<class G > typedef G::V pgrouting::functions::CuthillMckeeOrdering< G >::V
Definition at line 66 of file cuthillMckeeOrdering.hpp.
Vertex
template<class G > typedef boost::graph_traits<Graph>::vertex_descriptor pgrouting::functions::CuthillMckeeOrdering< G >::Vertex
Definition at line 70 of file cuthillMckeeOrdering.hpp.
Member Function Documentation
clear()
void pgrouting::Pgr_messages::clear () inherited
clear
Clears All the messages
Definition at line 58 of file messages.cpp.
                    {
    log.str("");
    log.clear();
    notice.str("");
    notice.clear();
    error.str("");
    error.clear();
}
References pgrouting::Pgr_messages::error, pgrouting::Pgr_messages::log, and pgrouting::Pgr_messages::notice.
Referenced by pgr_do_pickDeliver().
cuthillMckeeOrdering()
template<class G > std::vector< II_t_rt > pgrouting::functions::CuthillMckeeOrdering< G >::cuthillMckeeOrdering (G & graph) inline
cuthillMckeeOrdering function
It does all the processing and returns the results.
Parameters
graph the graph containing the edges
Returns
results, when results are found
See also
[boost::cuthill_mckee_ordering] (https://www.boost.org/libs/graph/doc/cuthill_mckee_ordering.html)
Definition at line 90 of file cuthillMckeeOrdering.hpp.
{
        std::vector<II_t_rt>results;
        // map which store the indices with their nodes.
        auto i_map = boost::get(boost::vertex_index, graph.graph);
        // vector which will store the order of the indices.
        std::vector<Vertex> inv_perm(boost::num_vertices(graph.graph));
        // vector which will store the color of all the vertices in the graph
        std::vector <boost::default_color_type> colors(boost::num_vertices(graph.graph));
        // An iterator property map which records the color of each vertex
        auto color_map = boost::make_iterator_property_map(&colors[0], i_map, colors[0]);
        // map which store the degree of each vertex.
        auto out_deg = boost::make_out_degree_map(graph.graph);
         /* abort in case of an interruption occurs (e.g. the query is being cancelled) */
         CHECK_FOR_INTERRUPTS();
         try {
             boost::cuthill_mckee_ordering(graph.graph, inv_perm.rbegin(), color_map, out_deg);
         } catch (boost::exception const& ex) {
             (void)ex;
             throw;
         } catch (std::exception &e) {
             (void)e;
             throw;
         } catch (...) {
             throw;
         }
         results = get_results(inv_perm, graph);
         return results;
     }
References CHECK_FOR_INTERRUPTS, and pgrouting::functions::CuthillMckeeOrdering< G >::get_results().
Referenced by anonymous_namespace{cuthillMckeeOrdering_driver.cpp}::cuthillMckeeOrdering().
get_error()
std::string pgrouting::Pgr_messages::get_error () const inherited
get_error
Returns
the current contents of the log and clears the log
Definition at line 52 of file messages.cpp.
{
    auto str = error.str();
    return str;
}
References pgrouting::Pgr_messages::error.
Referenced by pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), do_shortestPath(), pgr_do_pickDeliver(), pgr_do_pickDeliverEuclidean(), pgr_do_trsp_withPoints(), pgr_do_trspVia_withPoints(), pgr_do_withPoints(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), and pgr_do_withPointsVia().
get_log()
std::string pgrouting::Pgr_messages::get_log () const inherited
get_log
Returns
the current contents of the log and clears the log
Definition at line 35 of file messages.cpp.
{
    auto str = log.str();
    return str;
}
References pgrouting::Pgr_messages::log.
Referenced by pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), do_shortestPath(), pgr_do_bipartite(), pgr_do_boyerMyrvold(), pgr_do_LTDTree(), pgr_do_makeConnected(), pgr_do_pickDeliver(), pgr_do_pickDeliverEuclidean(), pgr_do_trsp_withPoints(), pgr_do_trspVia_withPoints(), pgr_do_withPoints(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), and pgr_do_withPointsVia().
get_notice()
std::string pgrouting::Pgr_messages::get_notice () const inherited
get_notice
Returns
the current contents of the log and clears the log
Definition at line 41 of file messages.cpp.
{
    auto str = notice.str();
    return str;
}
References pgrouting::Pgr_messages::notice.
get_results()
template<class G > std::vector< II_t_rt > pgrouting::functions::CuthillMckeeOrdering< G >::get_results (std::vector< size_type > & inv_perm, const G & graph) inline private
to get the results
Uses the inv_perm vector to get the results i.e. the ordering.
Parameters
inv_perm vector which contains the new ordering of indices.
graph the graph containing the edges
Returns
results vector
Definition at line 140 of file cuthillMckeeOrdering.hpp.
{
            std::vector <II_t_rt> results;
        for (std::vector<Vertex>::const_iterator i = inv_perm.begin();
             i != inv_perm.end(); ++i) {
            log << inv_perm[*i] << " ";
            auto seq = graph[*i].id;
            results.push_back({{seq}, {static_cast<int64_t>(graph.graph[*i].id)}});
            seq++;
            }
            return results;
        }
References pgrouting::Pgr_messages::log.
Referenced by pgrouting::functions::CuthillMckeeOrdering< G >::cuthillMckeeOrdering().
has_error()
bool pgrouting::Pgr_messages::has_error () const inherited
get_error
Returns
the current contents of the log and clears the log
Definition at line 47 of file messages.cpp.
{
    return  !error.str().empty();
}
References pgrouting::Pgr_messages::error.
Referenced by do_shortestPath(), pgr_do_trsp_withPoints(), pgr_do_trspVia_withPoints(), pgr_do_withPoints(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), and pgr_do_withPointsVia().
Member Data Documentation
error
std::ostringstream pgrouting::Pgr_messages::error mutable inherited
Stores the error information.
Definition at line 84 of file messages.hpp.
Referenced by pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::Pg_points_graph::check_points(), pgrouting::Pgr_messages::clear(), pgrouting::Pg_points_graph::create_new_edges(), pgrouting::Pgr_messages::get_error(), pgrouting::Pgr_messages::has_error(), and pgrouting::vrp::Fleet::is_fleet_ok().
log
std::ostringstream pgrouting::Pgr_messages::log mutable inherited
Stores the hint information.
Definition at line 80 of file messages.hpp.
Referenced by pgrouting::vrp::Optimize::Optimize(), pgrouting::Pg_points_graph::Pg_points_graph(), pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Solution::Solution(), pgrouting::vrp::Vehicle::Vehicle(), pgrouting::Pgr_bellman_ford< G >::bellman_ford_1_to_many(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::Pg_points_graph::check_points(), pgrouting::Pgr_messages::clear(), pgrouting::Pg_points_graph::create_new_edges(), pgrouting::functions::Pgr_makeConnected< G >::generatemakeConnected(), pgrouting::Pgr_messages::get_log(), pgrouting::vrp::Pgr_pickDeliver::get_postgres_result(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::functions::CuthillMckeeOrdering< G >::get_results(), pgrouting::functions::SloanOrdering< G >::get_results(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Fleet::is_fleet_ok(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), pgrouting::vrp::Optimize::save_if_best(), and pgrouting::vrp::Pgr_pickDeliver::solve().
notice
std::ostringstream pgrouting::Pgr_messages::notice mutable inherited
Stores the notice information.
Definition at line 82 of file messages.hpp.
Referenced by pgrouting::Pgr_messages::clear(), and pgrouting::Pgr_messages::get_notice().
The documentation for this class was generated from the following file:
cuthillMckeeOrdering.hpp