PGROUTING: pgrouting::vrp::Swap_bk Class Reference
pgrouting::vrp::Swap_bk Class Reference
#include "book_keeping.h"
Classes
class Compare
Public Types
typedef std::priority_queue< Swap_info, std::vector< Swap_info >, Compare > Swaps_queue
Public Member Functions
Swap_bk ()=default
Swap_bk (const Swap_bk &bk)=default
bool empty ()
void pop ()
Swaps_queue & possible_swaps ()
void push (const Swap_info &data)
Swap_info top ()
Public Attributes
Swaps_queue m_swaps
Friends
std::ostream & operator<< (std::ostream &log, const Swap_bk &data)
Detailed Description
Definition at line 91 of file book_keeping.h.
Member Typedef Documentation
Swaps_queue
typedef std::priority_queue< Swap_info, std::vector<Swap_info>, Compare > pgrouting::vrp::Swap_bk::Swaps_queue
Definition at line 104 of file book_keeping.h.
Constructor & Destructor Documentation
Swap_bk() [1/2]
pgrouting::vrp::Swap_bk::Swap_bk () default
Swap_bk() [2/2]
pgrouting::vrp::Swap_bk::Swap_bk (const Swap_bk & bk) default
Member Function Documentation
empty()
bool pgrouting::vrp::Swap_bk::empty () inline
Definition at line 128 of file book_keeping.h.
 {return m_swaps.empty();}
References m_swaps.
Referenced by pgrouting::vrp::Optimize::inter_swap(), and pgrouting::vrp::Optimize::swap_order().
pop()
void pgrouting::vrp::Swap_bk::pop () inline
Definition at line 127 of file book_keeping.h.
 {return m_swaps.pop();}
References m_swaps.
Referenced by pgrouting::vrp::Optimize::swap_order().
possible_swaps()
Swaps_queue& pgrouting::vrp::Swap_bk::possible_swaps () inline
Definition at line 124 of file book_keeping.h.
 {return m_swaps;}
References m_swaps.
push()
void pgrouting::vrp::Swap_bk::push (const Swap_info & data) inline
Definition at line 125 of file book_keeping.h.
 {m_swaps.push(data);}
References m_swaps.
top()
Swap_info pgrouting::vrp::Swap_bk::top () inline
Definition at line 126 of file book_keeping.h.
 {return m_swaps.top();}
References m_swaps.
Referenced by pgrouting::vrp::Optimize::swap_order().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const Swap_bk & data) friend
Definition at line 63 of file book_keeping.cpp.
{
     auto q = data.m_swaps;
     while (!q.empty()) {
         log << q.top() << " ";
         q.pop();
     }
     log << '\n';
     return log;
 }
Member Data Documentation
m_swaps
Swaps_queue pgrouting::vrp::Swap_bk::m_swaps
Definition at line 107 of file book_keeping.h.
Referenced by empty(), pgrouting::vrp::operator<<(), pop(), possible_swaps(), push(), and top().
The documentation for this class was generated from the following file:
book_keeping.h