PGROUTING: pgrouting::Pgr_bellman_ford< G > Class Template Reference
pgrouting::Pgr_bellman_ford< G > Class Template Reference
#include "bellman_ford.hpp"
Public Types
typedef G::E E
typedef G::V V
Public Member Functions
std::deque< Path > bellman_ford (G &graph, const std::map< int64_t, std::set< int64_t > > &combinations, bool only_cost=false)
BellmanFord combinations.
std::deque< Path > bellman_ford (G &graph, int64_t start_vertex, const std::set< int64_t > &end_vertex, bool only_cost=false)
bellman_ford one to a set of many
std::string get_error () const
get_error
std::string get_log () const
get_log
std::string get_notice () const
get_notice
bool has_error () const
get_error
Public Attributes
std::ostringstream error
Stores the error information.
std::ostringstream log
Stores the hint information.
std::ostringstream notice
Stores the notice information.
Private Member Functions
bool bellman_ford_1_to_many (G &graph, V source)
Call to BellmanFord 1 source to many targets.
void clear ()
std::deque< Path > get_paths (const G &graph, V source, std::vector< V > &targets, bool only_cost) const
Private Attributes
members
std::vector< V > predecessors
std::vector< double > distances
Detailed Description
template<class G>
class pgrouting::Pgr_bellman_ford< G >
Definition at line 55 of file bellman_ford.hpp.
Member Typedef Documentation
E
template<class G > typedef G::E pgrouting::Pgr_bellman_ford< G >::E
Definition at line 58 of file bellman_ford.hpp.
V
template<class G > typedef G::V pgrouting::Pgr_bellman_ford< G >::V
Definition at line 57 of file bellman_ford.hpp.
Member Function Documentation
bellman_ford() [1/2]
template<class G > std::deque< Path > pgrouting::Pgr_bellman_ford< G >::bellman_ford (G & graph, const std::map< int64_t, std::set< int64_t > > & combinations, bool only_cost = false) inline
BellmanFord combinations.
Definition at line 105 of file bellman_ford.hpp.
{
         std::deque<Path> paths;
         for (const auto &comb : combinations) {
             if (!graph.has_vertex(comb.first)) continue;
             auto tmp_paths = bellman_ford(graph, comb.first, comb.second, only_cost);
             paths.insert(paths.end(), tmp_paths.begin(), tmp_paths.end());
         }
         return paths;
     }
References pgrouting::Pgr_bellman_ford< G >::bellman_ford().
bellman_ford() [2/2]
template<class G > std::deque< Path > pgrouting::Pgr_bellman_ford< G >::bellman_ford (G & graph, int64_t start_vertex, const std::set< int64_t > & end_vertex, bool only_cost = false) inline
bellman_ford one to a set of many
Todo:
document this function
Definition at line 67 of file bellman_ford.hpp.
{
         // adjust predecessors and distances vectors
         clear();
         predecessors.resize(graph.num_vertices());
         distances.resize(graph.num_vertices());
         // get the graphs source and targets
         if (!graph.has_vertex(start_vertex)) return std::deque<Path>();
         auto v_source(graph.get_V(start_vertex));
         std::set<V> s_v_targets;
         for (const auto &vertex : end_vertex) {
             if (graph.has_vertex(vertex)) {
                 s_v_targets.insert(graph.get_V(vertex));
             }
         }
         std::vector<V> v_targets(s_v_targets.begin(), s_v_targets.end());
         // perform the algorithm
         bellman_ford_1_to_many(graph, v_source);
         // get the results // route id are the targets
         auto paths = get_paths(graph, v_source, v_targets, only_cost);
         std::stable_sort(paths.begin(), paths.end(),
                 [](const Path &e1, const Path &e2)->bool {
                 return e1.end_id() < e2.end_id();
                 });
         return paths;
     }
References pgrouting::Pgr_bellman_ford< G >::bellman_ford_1_to_many(), pgrouting::Pgr_bellman_ford< G >::clear(), pgrouting::Pgr_bellman_ford< G >::distances, pgrouting::Pgr_bellman_ford< G >::get_paths(), and pgrouting::Pgr_bellman_ford< G >::predecessors.
Referenced by pgrouting::Pgr_bellman_ford< G >::bellman_ford(), anonymous_namespace{bellman_ford_driver.cpp}::bellman_ford(), and anonymous_namespace{bellman_ford_neg_driver.cpp}::bellman_ford().
bellman_ford_1_to_many()
template<class G > bool pgrouting::Pgr_bellman_ford< G >::bellman_ford_1_to_many (G & graph, V source) inline private
Call to BellmanFord 1 source to many targets.
Definition at line 124 of file bellman_ford.hpp.
                       {
        log << std::string(__FUNCTION__) << "\n";
         /* abort in case of an interruption occurs (e.g. the query is being cancelled) */
         CHECK_FOR_INTERRUPTS();
         try {
             boost::bellman_ford_shortest_paths(
                     graph.graph,
                     static_cast<int>(graph.num_vertices()),
                     boost::predecessor_map(&predecessors[0])
                     .weight_map(get(&G::G_T_E::cost, graph.graph))
                     .distance_map(&distances[0])
                     .root_vertex(source));
         } catch (boost::exception const& ex) {
             (void)ex;
             throw;
         } catch (std::exception &e) {
             (void)e;
             throw;
         } catch (...) {
             throw;
         }
         return true;
     }
References CHECK_FOR_INTERRUPTS, pgrouting::Pgr_bellman_ford< G >::distances, pgrouting::Pgr_messages::log, and pgrouting::Pgr_bellman_ford< G >::predecessors.
Referenced by pgrouting::Pgr_bellman_ford< G >::bellman_ford().
clear()
template<class G > void pgrouting::Pgr_bellman_ford< G >::clear () inline private
Definition at line 152 of file bellman_ford.hpp.
                  {
         predecessors.clear();
         distances.clear();
     }
References pgrouting::Pgr_bellman_ford< G >::distances, and pgrouting::Pgr_bellman_ford< G >::predecessors.
Referenced by pgrouting::Pgr_bellman_ford< G >::bellman_ford().
get_error()
std::string pgrouting::Pgr_messages::get_error () const inherited
get_error
Returns
the current contents of the log and clears the log
Definition at line 52 of file messages.cpp.
{
    auto str = error.str();
    return str;
}
References pgrouting::Pgr_messages::error.
Referenced by pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), do_shortestPath(), pgr_do_pickDeliver(), pgr_do_pickDeliverEuclidean(), pgr_do_trsp_withPoints(), pgr_do_trspVia_withPoints(), pgr_do_withPoints(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), and pgr_do_withPointsVia().
get_log()
std::string pgrouting::Pgr_messages::get_log () const inherited
get_log
Returns
the current contents of the log and clears the log
Definition at line 35 of file messages.cpp.
{
    auto str = log.str();
    return str;
}
References pgrouting::Pgr_messages::log.
Referenced by pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), do_shortestPath(), pgr_do_bipartite(), pgr_do_boyerMyrvold(), pgr_do_LTDTree(), pgr_do_makeConnected(), pgr_do_pickDeliver(), pgr_do_pickDeliverEuclidean(), pgr_do_trsp_withPoints(), pgr_do_trspVia_withPoints(), pgr_do_withPoints(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), and pgr_do_withPointsVia().
get_notice()
std::string pgrouting::Pgr_messages::get_notice () const inherited
get_notice
Returns
the current contents of the log and clears the log
Definition at line 41 of file messages.cpp.
{
    auto str = notice.str();
    return str;
}
References pgrouting::Pgr_messages::notice.
get_paths()
template<class G > std::deque< Path > pgrouting::Pgr_bellman_ford< G >::get_paths (const G & graph, V source, std::vector< V > & targets, bool only_cost) const inline private
Definition at line 159 of file bellman_ford.hpp.
{
         std::deque<Path> paths;
         for (const auto target : targets) {
             paths.push_back(Path(
                         graph,
                         source, target,
                         predecessors, distances,
                         only_cost, true));
         }
         return paths;
     }
References pgrouting::Pgr_bellman_ford< G >::distances, and pgrouting::Pgr_bellman_ford< G >::predecessors.
Referenced by pgrouting::Pgr_bellman_ford< G >::bellman_ford().
has_error()
bool pgrouting::Pgr_messages::has_error () const inherited
get_error
Returns
the current contents of the log and clears the log
Definition at line 47 of file messages.cpp.
{
    return  !error.str().empty();
}
References pgrouting::Pgr_messages::error.
Referenced by do_shortestPath(), pgr_do_trsp_withPoints(), pgr_do_trspVia_withPoints(), pgr_do_withPoints(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), and pgr_do_withPointsVia().
Member Data Documentation
distances
template<class G > std::vector<double> pgrouting::Pgr_bellman_ford< G >::distances private
Definition at line 180 of file bellman_ford.hpp.
Referenced by pgrouting::Pgr_bellman_ford< G >::bellman_ford(), pgrouting::Pgr_bellman_ford< G >::bellman_ford_1_to_many(), pgrouting::Pgr_bellman_ford< G >::clear(), and pgrouting::Pgr_bellman_ford< G >::get_paths().
error
std::ostringstream pgrouting::Pgr_messages::error mutable inherited
Stores the error information.
Definition at line 84 of file messages.hpp.
Referenced by pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::Pg_points_graph::check_points(), pgrouting::Pgr_messages::clear(), pgrouting::Pg_points_graph::create_new_edges(), pgrouting::Pgr_messages::get_error(), pgrouting::Pgr_messages::has_error(), and pgrouting::vrp::Fleet::is_fleet_ok().
log
std::ostringstream pgrouting::Pgr_messages::log mutable inherited
Stores the hint information.
Definition at line 80 of file messages.hpp.
Referenced by pgrouting::vrp::Optimize::Optimize(), pgrouting::Pg_points_graph::Pg_points_graph(), pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Solution::Solution(), pgrouting::vrp::Vehicle::Vehicle(), pgrouting::Pgr_bellman_ford< G >::bellman_ford_1_to_many(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::Pg_points_graph::check_points(), pgrouting::Pgr_messages::clear(), pgrouting::Pg_points_graph::create_new_edges(), pgrouting::functions::Pgr_makeConnected< G >::generatemakeConnected(), pgrouting::Pgr_messages::get_log(), pgrouting::vrp::Pgr_pickDeliver::get_postgres_result(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::functions::CuthillMckeeOrdering< G >::get_results(), pgrouting::functions::SloanOrdering< G >::get_results(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Fleet::is_fleet_ok(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), pgrouting::vrp::Optimize::save_if_best(), and pgrouting::vrp::Pgr_pickDeliver::solve().
notice
std::ostringstream pgrouting::Pgr_messages::notice mutable inherited
Stores the notice information.
Definition at line 82 of file messages.hpp.
Referenced by pgrouting::Pgr_messages::clear(), and pgrouting::Pgr_messages::get_notice().
predecessors
template<class G > std::vector<V> pgrouting::Pgr_bellman_ford< G >::predecessors private
Definition at line 179 of file bellman_ford.hpp.
Referenced by pgrouting::Pgr_bellman_ford< G >::bellman_ford(), pgrouting::Pgr_bellman_ford< G >::bellman_ford_1_to_many(), pgrouting::Pgr_bellman_ford< G >::clear(), and pgrouting::Pgr_bellman_ford< G >::get_paths().
The documentation for this class was generated from the following file:
bellman_ford.hpp