PGROUTING: pgrouting::Pgr_dijkstra< G > Class Template Reference
pgrouting::Pgr_dijkstra< G > Class Template Reference
#include "pgr_dijkstra.hpp"
Classes
class dijkstra_distance_visitor
class for stopping when a distance/cost has being surpassed
class dijkstra_distance_visitor_no_init
class for stopping when a distance/cost has being surpassed
class dijkstra_many_goal_visitor
class for stopping when all targets are found
Public Types
typedef G::E E
typedef G::V V
Public Member Functions
drivingDistance
Path drivingDistance (G &graph, int64_t start_vertex, double distance)
1 to distance
std::deque< Path > drivingDistance (G &graph, const std::vector< int64_t > &start_vertex, double distance, bool equicost, std::ostringstream &the_log)
Dijkstra
Path dijkstra (G &graph, int64_t start_vertex, int64_t end_vertex, bool only_cost=false)
Dijkstra 1 to 1.
std::deque< Path > dijkstra (G &graph, int64_t start_vertex, const std::vector< int64_t > &end_vertex, bool only_cost, size_t n_goals=(std::numeric_limits< size_t >::max)())
Dijkstra 1 to many.
std::deque< Path > dijkstra (G &graph, const std::vector< int64_t > &start_vertex, int64_t end_vertex, bool only_cost)
std::deque< Path > dijkstra (G &graph, const std::vector< int64_t > &start_vertex, const std::vector< int64_t > &end_vertex, bool only_cost, size_t n_goals=(std::numeric_limits< size_t >::max)())
std::deque< Path > dijkstra (G &graph, const std::vector< pgr_combination_t > &combinations, bool only_cost, size_t n_goals=(std::numeric_limits< size_t >::max)())
Private Member Functions
void clear ()
bool dijkstra_1_to_1 (G &graph, V source, V target)
Call to Dijkstra 1 source to 1 target.
bool dijkstra_1_to_distance (G &graph, V source, double distance)
Call to Dijkstra 1 to distance.
bool dijkstra_1_to_distance_no_init (G &graph, V source, double distance)
Call to Dijkstra 1 to distance no init.
bool dijkstra_1_to_many (G &graph, V source, const std::vector< V > &targets, size_t n_goals=(std::numeric_limits< size_t >::max)())
Dijkstra 1 source to many targets.
std::deque< Path > drivingDistance_no_equicost (G &graph, const std::vector< int64_t > &start_vertex, double distance)
std::deque< Path > drivingDistance_with_equicost (G &graph, const std::vector< int64_t > &start_vertex, double distance)
bool execute_drivingDistance (G &graph, int64_t start_vertex, double distance)
to use with driving distance
bool execute_drivingDistance_no_init (G &graph, V start_vertex, double distance)
to use with driving distance
std::deque< Path > get_drivingDistance_with_equicost_paths (G &graph, const std::vector< int64_t > &start_vertex, std::deque< std::vector< V > > &pred, double distance)
gets results in form of a container of paths
std::deque< Path > get_paths (const G &graph, V source, std::vector< V > &targets, bool only_cost) const
Private Attributes
members
std::vector< V > predecessors
std::vector< double > distances
std::deque< V > nodesInDistance
std::ostringstream log
Detailed Description
template<class G>
class pgrouting::Pgr_dijkstra< G >
Definition at line 66 of file pgr_dijkstra.hpp.
Member Typedef Documentation
E
template<class G> typedef G::E pgrouting::Pgr_dijkstra< G >::E
Definition at line 109 of file pgr_dijkstra.hpp.
V
template<class G> typedef G::V pgrouting::Pgr_dijkstra< G >::V
Definition at line 108 of file pgr_dijkstra.hpp.
Member Function Documentation
clear()
template<class G> void pgrouting::Pgr_dijkstra< G >::clear () inline private
Definition at line 750 of file pgr_dijkstra.hpp.
References pgrouting::Pgr_dijkstra< G >::distances, pgrouting::Pgr_dijkstra< G >::nodesInDistance, and pgrouting::Pgr_dijkstra< G >::predecessors.
Referenced by pgrouting::Pgr_dijkstra< G >::dijkstra(), pgrouting::Pgr_dijkstra< G >::drivingDistance_with_equicost(), and pgrouting::Pgr_dijkstra< G >::execute_drivingDistance().
                   {
          predecessors.clear();
          distances.clear();
          nodesInDistance.clear();
      }
dijkstra() [1/5]
template<class G> Path pgrouting::Pgr_dijkstra< G >::dijkstra (G & graph, int64_t start_vertex, int64_t end_vertex, bool only_cost = false) inline
Dijkstra 1 to 1.
Definition at line 176 of file pgr_dijkstra.hpp.
References pgrouting::Pgr_dijkstra< G >::clear(), pgrouting::Pgr_dijkstra< G >::dijkstra_1_to_1(), pgrouting::Pgr_dijkstra< G >::distances, and pgrouting::Pgr_dijkstra< G >::predecessors.
Referenced by pgrouting::Pgr_dijkstra< G >::dijkstra(), pgrouting::yen::Pgr_ksp< G >::doNextCycle(), pgrouting::yen::Pgr_ksp< G >::getFirstSolution(), pgr_dijkstra(), pgrouting::pgr_dijkstra(), and detail::pgr_dijkstra().
{
          clear();
          // adjust predecessors and distances vectors
          predecessors.resize(graph.num_vertices());
          distances.resize(
                  graph.num_vertices(),
                  std::numeric_limits<double>::infinity());
          if (!graph.has_vertex(start_vertex)
                  || !graph.has_vertex(end_vertex)) {
              return Path(start_vertex, end_vertex);
          }
          // get the graphs source and target
          auto v_source(graph.get_V(start_vertex));
          auto v_target(graph.get_V(end_vertex));
          // perform the algorithm
          dijkstra_1_to_1(graph, v_source, v_target);
          // get the results
          return Path(
                  graph,
                  v_source, v_target,
                  predecessors, distances,
                  only_cost, true);
      }
dijkstra() [2/5]
template<class G> std::deque<Path> pgrouting::Pgr_dijkstra< G >::dijkstra (G & graph, int64_t start_vertex, const std::vector< int64_t > & end_vertex, bool only_cost, size_t n_goals = (std::numeric_limits<size_t>::max)()) inline
Dijkstra 1 to many.
Definition at line 216 of file pgr_dijkstra.hpp.
References pgrouting::Pgr_dijkstra< G >::clear(), pgrouting::Pgr_dijkstra< G >::dijkstra_1_to_many(), pgrouting::Pgr_dijkstra< G >::distances, Path::end_id(), pgrouting::Pgr_dijkstra< G >::get_paths(), and pgrouting::Pgr_dijkstra< G >::predecessors.
{
          // adjust predecessors and distances vectors
          clear();
          predecessors.resize(graph.num_vertices());
          distances.resize(
                  graph.num_vertices(),
                  std::numeric_limits<double>::infinity());
          // get the graphs source and target
          if (!graph.has_vertex(start_vertex))
              return std::deque<Path>();
          auto v_source(graph.get_V(start_vertex));
          std::set< V > s_v_targets;
          for (const auto &vertex : end_vertex) {
              if (graph.has_vertex(vertex)) {
                  s_v_targets.insert(graph.get_V(vertex));
              }
          }
          std::vector< V > v_targets(s_v_targets.begin(), s_v_targets.end());
          // perform the algorithm
          dijkstra_1_to_many(graph, v_source, v_targets, n_goals);
          std::deque< Path > paths;
          // get the results // route id are the targets
          paths = get_paths(graph, v_source, v_targets, only_cost);
          std::stable_sort(paths.begin(), paths.end(),
                  [](const Path &e1, const Path &e2)->bool {
                  return e1.end_id() < e2.end_id();
                  });
          return paths;
      }
dijkstra() [3/5]
template<class G> std::deque<Path> pgrouting::Pgr_dijkstra< G >::dijkstra (G & graph, const std::vector< int64_t > & start_vertex, int64_t end_vertex, bool only_cost) inline
Definition at line 260 of file pgr_dijkstra.hpp.
References pgrouting::Pgr_dijkstra< G >::dijkstra(), and Path::start_id().
{
          std::deque<Path> paths;
          for (const auto &start : start_vertex) {
              paths.push_back(
                      dijkstra(graph, start, end_vertex, only_cost));
          }
          std::stable_sort(paths.begin(), paths.end(),
                  [](const Path &e1, const Path &e2)->bool {
                  return e1.start_id() < e2.start_id();
                  });
          return paths;
      }
dijkstra() [4/5]
template<class G> std::deque<Path> pgrouting::Pgr_dijkstra< G >::dijkstra (G & graph, const std::vector< int64_t > & start_vertex, const std::vector< int64_t > & end_vertex, bool only_cost, size_t n_goals = (std::numeric_limits<size_t>::max)()) inline
Definition at line 281 of file pgr_dijkstra.hpp.
References pgrouting::Pgr_dijkstra< G >::dijkstra(), Path::end_id(), and Path::start_id().
{
          // a call to 1 to many is faster for each of the sources
          std::deque<Path> paths;
          for (const auto &start : start_vertex) {
              auto r_paths = dijkstra(
                      graph,
                      start, end_vertex,
                      only_cost, n_goals);
              paths.insert(paths.begin(), r_paths.begin(), r_paths.end());
          }
          std::sort(paths.begin(), paths.end(),
                  [](const Path &e1, const Path &e2)->bool {
                  return e1.end_id() < e2.end_id();
                  });
          std::stable_sort(paths.begin(), paths.end(),
                  [](const Path &e1, const Path &e2)->bool {
                  return e1.start_id() < e2.start_id();
                  });
          return paths;
      }
dijkstra() [5/5]
template<class G> std::deque<Path> pgrouting::Pgr_dijkstra< G >::dijkstra (G & graph, const std::vector< pgr_combination_t > & combinations, bool only_cost, size_t n_goals = (std::numeric_limits<size_t>::max)()) inline
Definition at line 310 of file pgr_dijkstra.hpp.
References pgrouting::Pgr_dijkstra< G >::dijkstra(), Path::end_id(), and Path::start_id().
{
         // a call to 1 to many is faster for each of the sources
         std::deque<Path> paths;
         // group targets per distinct source
         std::map<int64_t , std::vector<int64_t> > vertex_map;
         for (const pgr_combination_t &comb : combinations) {
             std::map< int64_t , std::vector<int64_t> >::iterator it = vertex_map.find(comb.source);
             if (it != vertex_map.end()) {
                 it->second.push_back(comb.target);
             } else {
                 std::vector<int64_t > targets{comb.target};
                 vertex_map[comb.source] = targets;
             }
         }
         for (const auto &start_ends : vertex_map) {
             auto r_paths = dijkstra(
                     graph,
                     start_ends.first, start_ends.second,
                     only_cost, n_goals);
             paths.insert(paths.begin(), r_paths.begin(), r_paths.end());
         }
         vertex_map.clear();
         std::sort(paths.begin(), paths.end(),
                 [](const Path &e1, const Path &e2)->bool {
                     return e1.end_id() < e2.end_id();
                 });
         std::stable_sort(paths.begin(), paths.end(),
                 [](const Path &e1, const Path &e2)->bool {
                     return e1.start_id() < e2.start_id();
                 });
         return paths;
     }
dijkstra_1_to_1()
template<class G> bool pgrouting::Pgr_dijkstra< G >::dijkstra_1_to_1 (G & graph, V source, V target) inline private
Call to Dijkstra 1 source to 1 target.
Definition at line 354 of file pgr_dijkstra.hpp.
References pgrouting::Pgr_dijkstra< G >::distances, and pgrouting::Pgr_dijkstra< G >::predecessors.
Referenced by pgrouting::Pgr_dijkstra< G >::dijkstra().
{
          /* abort in case of an interruption occurs (e.g. the query is being cancelled) */
          CHECK_FOR_INTERRUPTS();
          try {
              boost::dijkstra_shortest_paths(graph.graph, source,
                      boost::predecessor_map(&predecessors[0])
                      .weight_map(get(&G::G_T_E::cost, graph.graph))
                      .distance_map(&distances[0])
                      .visitor(visitors::dijkstra_one_goal_visitor<V>(target)));
          } catch(found_goals &) {
              return true;
          } catch (boost::exception const& ex) {
              (void)ex;
              throw;
          } catch (std::exception &e) {
              (void)e;
              throw;
          } catch (...) {
              throw;
          }
          return true;
      }
dijkstra_1_to_distance()
template<class G> bool pgrouting::Pgr_dijkstra< G >::dijkstra_1_to_distance (G & graph, V source, double distance) inline private
Call to Dijkstra 1 to distance.
Used on: 1 to distance many to distance On the first call of many to distance with equi_cost
Definition at line 387 of file pgr_dijkstra.hpp.
References pgrouting::Pgr_dijkstra< G >::distances, pgrouting::Pgr_dijkstra< G >::nodesInDistance, and pgrouting::Pgr_dijkstra< G >::predecessors.
Referenced by pgrouting::Pgr_dijkstra< G >::execute_drivingDistance().
{
          /* abort in case of an interruption occurs (e.g. the query is being cancelled) */
          CHECK_FOR_INTERRUPTS();
          try {
              boost::dijkstra_shortest_paths(graph.graph, source,
                      boost::predecessor_map(&predecessors[0])
                      .weight_map(get(&G::G_T_E::cost, graph.graph))
                      .distance_map(&distances[0])
                      .visitor(dijkstra_distance_visitor(
                              distance,
                              nodesInDistance,
                              distances)));
          } catch(found_goals &) {
              /*No op*/
          } catch (boost::exception const&) {
              throw;
          } catch (std::exception&) {
              throw;
          } catch (...) {
              throw;
          }
          return true;
      }
dijkstra_1_to_distance_no_init()
template<class G> bool pgrouting::Pgr_dijkstra< G >::dijkstra_1_to_distance_no_init (G & graph, V source, double distance) inline private
Call to Dijkstra 1 to distance no init.
Used on: On the subsequent calls of many to distance with equi_cost
Definition at line 419 of file pgr_dijkstra.hpp.
References pgrouting::Pgr_dijkstra< G >::distances, pgrouting::Pgr_dijkstra< G >::log, pgassert, pgassertwm, and pgrouting::Pgr_dijkstra< G >::predecessors.
Referenced by pgrouting::Pgr_dijkstra< G >::execute_drivingDistance_no_init().
{
          pgassert(predecessors.size() == graph.num_vertices());
          pgassert(distances.size() == graph.num_vertices());
          distances[source] = 0;
          std::vector<boost::default_color_type> color_map(graph.num_vertices());
          /* abort in case of an interruption occurs (e.g. the query is being cancelled) */
          CHECK_FOR_INTERRUPTS();
          try {
              boost::dijkstra_shortest_paths_no_init(graph.graph, source,
                      make_iterator_property_map(
                          predecessors.begin(),
                          graph.vertIndex),
                      make_iterator_property_map(
                          distances.begin(),
                          graph.vertIndex),
                      get(&G::G_T_E::cost, graph.graph),
                      graph.vertIndex,
                      std::less<double>(),
                      boost::closed_plus<double>(),
                      static_cast<double>(0),
                      dijkstra_distance_visitor_no_init(
                          log,
                          source,
                          distance,
                          predecessors,
                          distances,
                          color_map),
                      boost::make_iterator_property_map(
                          color_map.begin(),
                          graph.vertIndex,
                          color_map[0]));
          } catch(found_goals &) {
              return true;
          } catch (boost::exception const& ex) {
              (void)ex;
              throw;
          } catch (std::exception &e) {
              (void)e;
              throw;
          } catch (...) {
              throw;
          }
 #if 0
          /*
           * Expensive assertion
           */
          for (V v = 0 ; v < predecessors.size(); ++v) {
              log << "(" << predecessors[v] << "==" << v << "),";
              if (v != source) {
                  pgassertwm(predecessors[v] == v, log.str().c_str());
              }
          }
 #endif
          return true;
      }
dijkstra_1_to_many()
template<class G> bool pgrouting::Pgr_dijkstra< G >::dijkstra_1_to_many (G & graph, V source, const std::vector< V > & targets, size_t n_goals = (std::numeric_limits<size_t>::max)()) inline private
Dijkstra 1 source to many targets.
Definition at line 721 of file pgr_dijkstra.hpp.
References pgrouting::Pgr_dijkstra< G >::distances, and pgrouting::Pgr_dijkstra< G >::predecessors.
Referenced by pgrouting::Pgr_dijkstra< G >::dijkstra().
{
          /* abort in case of an interruption occurs (e.g. the query is being cancelled) */
          CHECK_FOR_INTERRUPTS();
          try {
              boost::dijkstra_shortest_paths(graph.graph, source,
                      boost::predecessor_map(&predecessors[0])
                      .weight_map(get(&G::G_T_E::cost, graph.graph))
                      .distance_map(&distances[0])
                      .distance_inf(std::numeric_limits<double>::infinity())
                      .visitor(dijkstra_many_goal_visitor(targets, n_goals)));
          } catch(found_goals &) {
              return true;
          } catch (boost::exception const& ex) {
              (void)ex;
              throw;
          } catch (std::exception &e) {
              (void)e;
              throw;
          } catch (...) {
              throw;
          }
          return true;
      }
drivingDistance() [1/2]
template<class G> Path pgrouting::Pgr_dijkstra< G >::drivingDistance (G & graph, int64_t start_vertex, double distance) inline
1 to distance
Definition at line 114 of file pgr_dijkstra.hpp.
Referenced by pgrouting::pgr_drivingDistance().
{
         if (execute_drivingDistance(
                 graph,
                 start_vertex,
                 distance)) {
             auto path = Path(graph,
                     start_vertex,
                     distance,
                     predecessors,
                     distances);
             std::sort(path.begin(), path.end(),
                     [](const Path_t &l, const  Path_t &r)
                     {return l.node < r.node;});
             std::stable_sort(path.begin(), path.end(),
                     [](const Path_t &l, const  Path_t &r)
                     {return l.agg_cost < r.agg_cost;});
             return path;
         }
         /* The result is empty */
         Path p(start_vertex, start_vertex);
         p.push_back({start_vertex, -1, 0, 0});
         return p;
      }
drivingDistance() [2/2]
template<class G> std::deque< Path > pgrouting::Pgr_dijkstra< G >::drivingDistance (G & graph, const std::vector< int64_t > & start_vertex, double distance, bool equicost, std::ostringstream & the_log) inline
Definition at line 144 of file pgr_dijkstra.hpp.
References pgrouting::Pgr_dijkstra< G >::drivingDistance_no_equicost(), pgrouting::Pgr_dijkstra< G >::drivingDistance_with_equicost(), and pgrouting::Pgr_dijkstra< G >::log.
{
          if (equicost) {
              auto paths = drivingDistance_with_equicost(
                      graph,
                      start_vertex,
                      distance);
              the_log << log.str();
              return paths;
          } else {
              return drivingDistance_no_equicost(
                      graph,
                      start_vertex,
                      distance);
          }
      }
drivingDistance_no_equicost()
template<class G> std::deque< Path > pgrouting::Pgr_dijkstra< G >::drivingDistance_no_equicost (G & graph, const std::vector< int64_t > & start_vertex, double distance) inline private
Definition at line 694 of file pgr_dijkstra.hpp.
References pgrouting::Pgr_dijkstra< G >::distances, pgrouting::Pgr_dijkstra< G >::execute_drivingDistance(), pgrouting::Pgr_dijkstra< G >::predecessors, and Path::push_back().
Referenced by pgrouting::Pgr_dijkstra< G >::drivingDistance().
{
          // perform the algorithm
          std::deque<Path> paths;
          for (const auto &vertex : start_vertex) {
              if (execute_drivingDistance(graph, vertex, distance)) {
                  auto path = Path(
                          graph,
                          vertex,
                          distance,
                          predecessors,
                          distances);
                  path.sort_by_node_agg_cost();
                  paths.push_back(path);
              } else {
                  Path p(vertex, vertex);
                  p.push_back({vertex, -1, 0, 0});
                  paths.push_back(p);
              }
          }
          return paths;
      }
drivingDistance_with_equicost()
template<class G> std::deque< Path > pgrouting::Pgr_dijkstra< G >::drivingDistance_with_equicost (G & graph, const std::vector< int64_t > & start_vertex, double distance) inline private
Definition at line 566 of file pgr_dijkstra.hpp.
References pgrouting::Pgr_dijkstra< G >::clear(), pgrouting::Pgr_dijkstra< G >::distances, pgrouting::Pgr_dijkstra< G >::execute_drivingDistance_no_init(), pgrouting::Pgr_dijkstra< G >::get_drivingDistance_with_equicost_paths(), pgrouting::Pgr_dijkstra< G >::log, pgrouting::Pgr_dijkstra< G >::nodesInDistance, pred(), and pgrouting::Pgr_dijkstra< G >::predecessors.
Referenced by pgrouting::Pgr_dijkstra< G >::drivingDistance().
{
          clear();
          log << "Number of edges:" << boost::num_edges(graph.graph) << "\n";
          predecessors.resize(graph.num_vertices());
          distances.resize(
                  graph.num_vertices(),
                  std::numeric_limits<double>::infinity());
          /*
           * Vector to store the different predessesors
           * each is of size = graph.num_vertices()
           *
           * TODO(vicky)
           * - figure out less storage if possible
           */
          std::deque< std::vector< V > > pred(start_vertex.size());
          // perform the algorithm
          size_t i = 0;
          for (const auto &vertex : start_vertex) {
              nodesInDistance.clear();
              /*
               * The vertex does not exist
               *   Nothing to do
               */
              if (graph.has_vertex(vertex)) {
                  if (execute_drivingDistance_no_init(
                              graph,
                              graph.get_V(vertex),
                              distance)) {
                      pred[i] = predecessors;
                  }
              }
              ++i;
          }
          /*
           * predecessors of vertices in the set are themselves
           */
          for (const auto &vertex : start_vertex) {
              for (auto &p : pred) {
                  if (!p.empty() && graph.has_vertex(vertex))
                      p[graph.get_V(vertex)] = graph.get_V(vertex);
              }
          }
         return get_drivingDistance_with_equicost_paths(
                 graph,
                 start_vertex,
                 pred,
                 distance);
      }
execute_drivingDistance()
template<class G> bool pgrouting::Pgr_dijkstra< G >::execute_drivingDistance (G & graph, int64_t start_vertex, double distance) inline private
to use with driving distance
Prepares the execution for a driving distance:
Parameters
graph
start_vertex
distance Results are kept on predecessor & distances
Returns
bool True when results are found
Definition at line 492 of file pgr_dijkstra.hpp.
References pgrouting::Pgr_dijkstra< G >::clear(), pgrouting::Pgr_dijkstra< G >::dijkstra_1_to_distance(), pgrouting::Pgr_dijkstra< G >::distances, and pgrouting::Pgr_dijkstra< G >::predecessors.
Referenced by pgrouting::Pgr_dijkstra< G >::drivingDistance_no_equicost().
{
          clear();
          predecessors.resize(graph.num_vertices());
          distances.resize(
                  graph.num_vertices(),
                  std::numeric_limits<double>::infinity());
          // get source;
          if (!graph.has_vertex(start_vertex)) {
              return false;
          }
          return dijkstra_1_to_distance(
                  graph,
                  graph.get_V(start_vertex),
                  distance);
      }
execute_drivingDistance_no_init()
template<class G> bool pgrouting::Pgr_dijkstra< G >::execute_drivingDistance_no_init (G & graph, V start_vertex, double distance) inline private
to use with driving distance
Prepares the execution for a driving distance:
Parameters
graph
start_vertex
distance Results are kept on predecessor & distances
Returns
bool True when results are found
Definition at line 527 of file pgr_dijkstra.hpp.
References pgrouting::Pgr_dijkstra< G >::dijkstra_1_to_distance_no_init(), pgrouting::Pgr_dijkstra< G >::distances, pgassert, and pgrouting::Pgr_dijkstra< G >::predecessors.
Referenced by pgrouting::Pgr_dijkstra< G >::drivingDistance_with_equicost().
{
          pgassert(predecessors.size() == graph.num_vertices());
          pgassert(distances.size() == graph.num_vertices());
          std::iota(predecessors.begin(), predecessors.end(), 0);
 #if 0
          /*
           * Expensive assertion
           */
          for (V i = 0 ; i < predecessors.size(); ++i) {
              pgassert(i == predecessors[i]);
          }
 #endif
          return dijkstra_1_to_distance_no_init(
                  graph,
                  start_vertex,
                  distance);
      }
get_drivingDistance_with_equicost_paths()
template<class G> std::deque< Path > pgrouting::Pgr_dijkstra< G >::get_drivingDistance_with_equicost_paths (G & graph, const std::vector< int64_t > & start_vertex, std::deque< std::vector< V > > & pred, double distance) inline private
gets results in form of a container of paths
Parameters
[in] graph The graph that is being worked
[in] start_vertex An array of vertices id
[in] pred an array of predecessors
[in] distance the max distance
Definition at line 632 of file pgr_dijkstra.hpp.
References pgrouting::Pgr_dijkstra< G >::distances, pgassert, and pred().
Referenced by pgrouting::Pgr_dijkstra< G >::drivingDistance_with_equicost().
{
          /*
           * precondition
           */
          pgassert(start_vertex.size() == pred.size());
          /*
           * Creating all the result "paths"
           */
          std::deque<Path> paths;
          for (const auto vertex : start_vertex) {
              paths.push_back(Path(vertex, vertex));
              paths.back().push_back({vertex, -1, 0, 0});
          }
          /*
           *  Ciclying the distances:
           *  To which vertex do they belong to?
           */
          for (V d = 0; d < distances.size(); ++d) {
              /*
               * Sikiping distances greater than the one asked for
               */
              if (!(distances[d] <= distance)) continue;
              for (auto i = start_vertex.size(); i > 0; --i) {
                  /*
                   * The vertex does not exist on the graph
                   */
                  if (pred[i - 1].empty()) break;
                  /*
                   * The predecessor = current then
                   *  its unreachable to this vertex
                   */
                  if (pred[i - 1][d] == d) continue;
                  auto cost = distances[d] - distances[pred[i - 1][d]];
                  auto edge_id = graph.get_edge_id(pred[i - 1][d], d, cost);
                  pgassert(edge_id != -1);
                  paths[i - 1].push_back(
                          {graph[d].id,
                          edge_id, cost,
                          distances[d]});
                  break;
              }
          }
          for (auto &path : paths) {
              path.sort_by_node_agg_cost();
          }
          return paths;
      }
get_paths()
template<class G> std::deque<Path> pgrouting::Pgr_dijkstra< G >::get_paths (const G & graph, V source, std::vector< V > & targets, bool only_cost) const inline private
Definition at line 760 of file pgr_dijkstra.hpp.
References pgrouting::Pgr_dijkstra< G >::distances, and pgrouting::Pgr_dijkstra< G >::predecessors.
Referenced by pgrouting::Pgr_dijkstra< G >::dijkstra().
{
          std::deque<Path> paths;
          for (const auto target : targets) {
              paths.push_back(Path(
                          graph,
                          source, target,
                          predecessors, distances,
                          only_cost, true));
          }
          return paths;
      }
Member Data Documentation
distances
template<class G> std::vector< double > pgrouting::Pgr_dijkstra< G >::distances private
Definition at line 784 of file pgr_dijkstra.hpp.
Referenced by pgrouting::Pgr_dijkstra< G >::clear(), pgrouting::Pgr_dijkstra< G >::dijkstra(), pgrouting::Pgr_dijkstra< G >::dijkstra_1_to_1(), pgrouting::Pgr_dijkstra< G >::dijkstra_1_to_distance(), pgrouting::Pgr_dijkstra< G >::dijkstra_1_to_distance_no_init(), pgrouting::Pgr_dijkstra< G >::dijkstra_1_to_many(), pgrouting::Pgr_dijkstra< G >::drivingDistance_no_equicost(), pgrouting::Pgr_dijkstra< G >::drivingDistance_with_equicost(), pgrouting::Pgr_dijkstra< G >::execute_drivingDistance(), pgrouting::Pgr_dijkstra< G >::execute_drivingDistance_no_init(), pgrouting::Pgr_dijkstra< G >::get_drivingDistance_with_equicost_paths(), and pgrouting::Pgr_dijkstra< G >::get_paths().
log
template<class G> std::ostringstream pgrouting::Pgr_dijkstra< G >::log private
Definition at line 786 of file pgr_dijkstra.hpp.
Referenced by pgrouting::Pgr_dijkstra< G >::dijkstra_1_to_distance_no_init(), pgrouting::Pgr_dijkstra< G >::drivingDistance(), and pgrouting::Pgr_dijkstra< G >::drivingDistance_with_equicost().
nodesInDistance
template<class G> std::deque< V > pgrouting::Pgr_dijkstra< G >::nodesInDistance private
Definition at line 785 of file pgr_dijkstra.hpp.
Referenced by pgrouting::Pgr_dijkstra< G >::clear(), pgrouting::Pgr_dijkstra< G >::dijkstra_1_to_distance(), and pgrouting::Pgr_dijkstra< G >::drivingDistance_with_equicost().
predecessors
template<class G> std::vector< V > pgrouting::Pgr_dijkstra< G >::predecessors private
Definition at line 783 of file pgr_dijkstra.hpp.
Referenced by pgrouting::Pgr_dijkstra< G >::clear(), pgrouting::Pgr_dijkstra< G >::dijkstra(), pgrouting::Pgr_dijkstra< G >::dijkstra_1_to_1(), pgrouting::Pgr_dijkstra< G >::dijkstra_1_to_distance(), pgrouting::Pgr_dijkstra< G >::dijkstra_1_to_distance_no_init(), pgrouting::Pgr_dijkstra< G >::dijkstra_1_to_many(), pgrouting::Pgr_dijkstra< G >::drivingDistance_no_equicost(), pgrouting::Pgr_dijkstra< G >::drivingDistance_with_equicost(), pgrouting::Pgr_dijkstra< G >::execute_drivingDistance(), pgrouting::Pgr_dijkstra< G >::execute_drivingDistance_no_init(), and pgrouting::Pgr_dijkstra< G >::get_paths().
The documentation for this class was generated from the following file:
pgr_dijkstra.hpp