PGROUTING: pgrouting::vrp::Vehicle_pickDeliver Class Reference
pgrouting::vrp::Vehicle_pickDeliver Class Reference
#include "vehicle_pickDeliver.h"
Public Types
typedef std::tuple< int, int, size_t, double, double > Cost
Public Member Functions
Vehicle_pickDeliver (size_t id, size_t kind, const Vehicle_node &starting_site, const Vehicle_node &ending_site, double p_capacity, double p_speed, double factor)
Vehicle_pickDeliver (const Vehicle_pickDeliver &)=default
double deltaTime (const Vehicle_node &node, POS pos) const
void do_while_feasable (Initials_code kind, Identifiers< size_t > &unassigned, Identifiers< size_t > &assigned)
std::pair< POS, POS > drop_position_limits (const Vehicle_node node) const
void erase (const Order &order)
Identifiers< size_t > feasable_orders () const
Order get_first_order () const
std::vector< General_vehicle_orders_t > get_postgres_result (int vid) const
Order get_worse_order (Identifiers< size_t > of_this_subset) const
bool has_order (const Order &order) const
int64_t id () const
size_t idx () const
bool insert (const Order &order)
Inserts an order.
POS insert_less_travel_time (const Vehicle_node &node, POS after_pos=0)
bool is_order_feasable (const Order &order) const
bool is_phony () const
const PD_Orders & orders () const
Identifiers< size_t > orders_in_vehicle () const
size_t orders_size () const
size_t pop_back ()
The order that is picked last is removed.
size_t pop_front ()
std::pair< POS, POS > position_limits (const Vehicle_node node) const
void push_back (const Order &order)
puts an order at the end of the truck
void push_front (const Order &order)
Puts an order at the end front of the truck.
void reset_id (int64_t)
bool semiLIFO (const Order &order)
Inserts an order In semi-Lifo order.
void set_compatibles (const PD_Orders &orders)
double speed () const
void swap (POS i, POS j)
Swap two nodes in the path.
deque like functions
Returns
True if the operation was performed
Warning
Assertions are performed for out of range operations
no feasability nor time window or capacity violations checks are performed
Todo:
TODO more deque like functions here
void invariant () const
Invariant The path must:
void insert (POS pos, Vehicle_node node)
@ {
POS insert (std::pair< POS, POS > position_limits, const Vehicle_node &node)
Insert node in best position of the position_limits.
void push_back (const Vehicle_node &node)
Evaluated: push_back a node to the path.
void push_front (const Vehicle_node &node)
Evaluated: push_back a node to the path.
void erase (const Vehicle_node &node)
Erase node.id()
void erase (POS pos)
Erase node at pos from the path.
bool empty () const
return true when no nodes are in the truck
size_t size () const
return number of nodes in the truck
Cost cost () const
bool cost_compare (const Cost &, const Cost &) const
double duration () const
double total_wait_time () const
double total_travel_time () const
double total_service_time () const
double free_time () const
int twvTot () const
int cvTot () const
bool has_twv () const
bool has_cv () const
bool is_feasable () const
bool is_ok () const
Vehicle_node start_site () const
Vehicle_node end_site () const
double capacity () const
Evaluation
Path evaluation is done incrementally: from a given position to the end of the path, and intermediate values are cached on each node.
So, for example, changing the path at position 100: the evaluation function should be called as evaluate(100, maxcapacity) and from that position to the end of the path will be evaluated. None of the "unaffected" positions get reevaluated
void evaluate ()
@ {
void evaluate (POS from)
Evaluate: Evaluate a path from the given position.
accessors
std::deque< Vehicle_node > path () const
@ {
operators
std::string tau () const
Static Public Attributes
static Pgr_messages msg
Protected Types
typedef size_t POS
Protected Attributes
double cost
Identifiers< size_t > m_feasable_orders
orders that fit in the truck
PD_Orders m_orders
Identifiers< size_t > m_orders_in_vehicle
orders inserted in this vehicle
std::deque< Vehicle_node > m_path
Static Protected Attributes
static Pgr_pickDeliver * problem
Friends
class Initial_solution
class Optimize
Detailed Description
Definition at line 47 of file vehicle_pickDeliver.h.
Member Typedef Documentation
Cost
typedef std::tuple< int, int, size_t, double, double > pgrouting::vrp::Vehicle::Cost inherited
Definition at line 86 of file vehicle.h.
POS
typedef size_t pgrouting::vrp::Vehicle::POS protected inherited
Definition at line 74 of file vehicle.h.
Constructor & Destructor Documentation
Vehicle_pickDeliver() [1/2]
pgrouting::vrp::Vehicle_pickDeliver::Vehicle_pickDeliver (size_t id, size_t kind, const Vehicle_node & starting_site, const Vehicle_node & ending_site, double p_capacity, double p_speed, double factor)
Definition at line 80 of file vehicle_pickDeliver.cpp.
References Identifiers< T >::clear(), ENTERING, EXITING, pgrouting::vrp::Vehicle::invariant(), and m_orders_in_vehicle.
                        :
     Vehicle(id, kind, starting_site, ending_site, p_capacity, p_speed, factor),
     cost((std::numeric_limits<double>::max)()) {
 #if 0
         ENTERING();
 #endif
         m_orders_in_vehicle.clear();
         invariant();
 #if 0
         EXITING();
 #endif
     }
Vehicle_pickDeliver() [2/2]
pgrouting::vrp::Vehicle_pickDeliver::Vehicle_pickDeliver (const Vehicle_pickDeliver &) default
Member Function Documentation
capacity()
double pgrouting::vrp::Vehicle::capacity () const inline inherited
Definition at line 280 of file vehicle.h.
References pgrouting::vrp::Vehicle::deltaTime(), pgrouting::vrp::Vehicle::drop_position_limits(), pgrouting::vrp::Vehicle::evaluate(), pgrouting::vrp::Vehicle::getDropPosLowLimit(), pgrouting::vrp::Vehicle::getPosHighLimit(), pgrouting::vrp::Vehicle::getPosLowLimit(), pgrouting::vrp::Vehicle::insert_less_travel_time(), pgrouting::vrp::Vehicle::m_capacity, pgrouting::vrp::Vehicle::operator<, pgrouting::vrp::Vehicle::operator<<, pgrouting::vrp::Vehicle::path(), pgrouting::vrp::Vehicle::position_limits(), pgrouting::vrp::Vehicle::swap(), and pgrouting::vrp::Vehicle::tau().
Referenced by pgrouting::vrp::Vehicle::Vehicle().
 {return m_capacity;}
cost()
Vehicle::Cost pgrouting::vrp::Vehicle::cost () const inherited
Definition at line 166 of file vehicle.cpp.
References pgrouting::vrp::Vehicle::cvTot(), pgrouting::vrp::Vehicle::duration(), pgrouting::vrp::Vehicle::m_path, pgrouting::vrp::Vehicle::total_wait_time(), and pgrouting::vrp::Vehicle::twvTot().
Referenced by pgrouting::vrp::Vehicle::insert(), and pgrouting::vrp::Vehicle::is_phony().
                     {
     return std::make_tuple(
             twvTot(), cvTot(), m_path.size(),
             total_wait_time(), duration());
 }
cost_compare()
bool pgrouting::vrp::Vehicle::cost_compare (const Cost & lhs, const Cost & rhs) const inherited
Definition at line 88 of file vehicle.cpp.
Referenced by pgrouting::vrp::Vehicle::insert(), and pgrouting::vrp::Vehicle::is_phony().
{
     /*
      * capacity violations
      */
     if (std::get<1>(lhs) < std::get<1>(rhs))
         return true;
     if (std::get<1>(lhs) > std::get<1>(rhs))
         return false;
     /*
      * time window violations
      */
     if (std::get<0>(lhs) < std::get<0>(rhs))
         return true;
     if (std::get<0>(lhs) > std::get<0>(rhs))
         return false;
     /*
      * waiting time
      */
     if (std::get<3>(lhs) < std::get<3>(rhs))
         return true;
     if (std::get<3>(lhs) > std::get<3>(rhs))
         return false;
     /*
      * duration
      */
     if (std::get<4>(lhs) < std::get<4>(rhs))
         return true;
     if (std::get<4>(lhs) > std::get<4>(rhs))
         return false;
     /*
      * truck size
      */
     if (std::get<2>(lhs) < std::get<2>(rhs))
         return true;
     if (std::get<2>(lhs) > std::get<2>(rhs))
         return false;
     return false;
 }
cvTot()
int pgrouting::vrp::Vehicle::cvTot () const inline inherited
Definition at line 255 of file vehicle.h.
Referenced by pgrouting::vrp::Vehicle::cost(), pgrouting::vrp::Vehicle::has_cv(), and pgrouting::vrp::Vehicle::tau().
{
          return m_path.back().cvTot();
      }
deltaTime()
double pgrouting::vrp::Vehicle::deltaTime (const Vehicle_node & node, POS pos) const inherited
Definition at line 188 of file vehicle.cpp.
References pgrouting::vrp::Tw_node::closes(), pgrouting::vrp::Tw_node::is_early_arrival(), pgrouting::vrp::Vehicle::m_path, pgrouting::vrp::Tw_node::service_time(), pgrouting::vrp::Vehicle::speed(), and pgrouting::vrp::Tw_node::travel_time_to().
Referenced by pgrouting::vrp::Vehicle::capacity(), and pgrouting::vrp::Vehicle::insert_less_travel_time().
{
     /*
      * .... POS POS+1 ....
      * .... POS node POS+1 ....
      *
      */
     auto prev = m_path[pos-1];
     auto next = m_path[pos];
     auto original_time = next.travel_time();
     auto tt_p_n = prev.travel_time_to(node, speed());
     tt_p_n = node.is_early_arrival(prev.departure_time() + tt_p_n) ?
         node.closes() - prev.departure_time()
         : tt_p_n;
     auto tt_n_x = node.travel_time_to(next, speed());
     tt_p_n = next.is_early_arrival(
             prev.departure_time() + tt_p_n + node.service_time() + tt_n_x) ?
         next.closes() - (prev.departure_time() + tt_p_n + node.service_time())
         : tt_n_x;
     return (tt_p_n + tt_n_x) - original_time;
 }
do_while_feasable()
void pgrouting::vrp::Vehicle_pickDeliver::do_while_feasable (Initials_code kind, Identifiers< size_t > & unassigned, Identifiers< size_t > & assigned)
Definition at line 263 of file vehicle_pickDeliver.cpp.
References pgrouting::vrp::BackTruck, pgrouting::vrp::BestBack, pgrouting::vrp::BestFront, pgrouting::vrp::BestInsert, erase(), pgrouting::vrp::PD_Orders::find_best_I(), pgrouting::vrp::PD_Orders::find_best_J(), pgrouting::vrp::FrontTruck, has_order(), insert(), pgrouting::vrp::Vehicle::invariant(), pgrouting::vrp::Vehicle::is_feasable(), pgrouting::Pgr_messages::log, m_feasable_orders, m_orders, pgrouting::vrp::PD_problem::msg, pgrouting::vrp::OneDepot, pgrouting::vrp::OnePerTruck, orders_size(), pgassert, push_back(), push_front(), and semiLIFO().
Referenced by orders_in_vehicle().
{
     pgassert(is_feasable());
 #if 0
     msg.log << "unasigned" << unassigned << "\n";
     msg.log << "m_feasable_orders" << m_feasable_orders << "\n";
 #endif
     auto current_feasable = m_feasable_orders * unassigned;
     while (!current_feasable.empty()) {
 #if 0
         msg.log << "current_feasable" << current_feasable << "\n";
 #endif
         auto order = m_orders[current_feasable.front()];
         switch (kind) {
             case OnePerTruck:
                 push_back(order);
                 pgassert(is_feasable());
                 assigned += order.idx();
                 unassigned -= order.idx();
                 invariant();
                 return;
                 break;
             case FrontTruck:
                 push_front(order);
                 break;
             case BackTruck:
                 push_back(order);
                 break;
             case BestInsert:
                 insert(order);
                 break;
             case BestBack:
                 order = m_orders[m_orders.find_best_J(current_feasable)];
                 insert(order);
                 break;
             case BestFront:
                 order = m_orders[m_orders.find_best_I(current_feasable)];
                 insert(order);
                 break;
             case OneDepot:
                 semiLIFO(order);
                 break;
             default: pgassert(false);
         }
         if (orders_size() == 1 && !is_feasable()) {
             pgassert(false);
         }
         if (!is_feasable()) {
             erase(order);
         } else if (has_order(order)) {
             assigned += order.idx();
             unassigned -= order.idx();
             if (kind == BestBack) {
                 current_feasable = m_orders[order.idx()].subsetJ(
                         current_feasable);
             }
             if (kind == BestFront) {
                 current_feasable = m_orders[order.idx()].subsetI(
                         current_feasable);
             }
         }
         current_feasable -= order.idx();
         invariant();
     }
     pgassert(is_feasable());
     invariant();
 }
drop_position_limits()
std::pair< size_t, size_t > pgrouting::vrp::Vehicle::drop_position_limits (const Vehicle_node node) const inherited
Definition at line 401 of file vehicle.cpp.
References pgrouting::vrp::Vehicle::getDropPosLowLimit(), and pgrouting::vrp::Vehicle::getPosHighLimit().
Referenced by pgrouting::vrp::Vehicle::capacity(), and semiLIFO().
{
     POS high = getPosHighLimit(node);
     POS low = getDropPosLowLimit(node);
     return std::make_pair(low, high);
 }
duration()
double pgrouting::vrp::Vehicle::duration () const inline inherited
Definition at line 237 of file vehicle.h.
Referenced by pgrouting::vrp::Vehicle::cost(), pgrouting::vrp::Vehicle::free_time(), get_worse_order(), insert(), pgrouting::vrp::Optimize::sort_by_duration(), and pgrouting::vrp::Vehicle::tau().
{
          return m_path.back().departure_time();
      }
empty()
bool pgrouting::vrp::Vehicle::empty () const inherited
return true when no nodes are in the truck
True: S E
False: S <nodes> E
Definition at line 354 of file vehicle.cpp.
References pgrouting::vrp::Vehicle::invariant(), and pgrouting::vrp::Vehicle::m_path.
Referenced by get_first_order(), get_worse_order(), pgrouting::vrp::Vehicle::is_phony(), pgrouting::vrp::Optimize::move_order(), pop_back(), and pop_front().
                      {
     invariant();
     return m_path.size() <= 2;
 }
end_site()
Vehicle_node pgrouting::vrp::Vehicle::end_site () const inline inherited
Definition at line 274 of file vehicle.h.
References pgrouting::vrp::Vehicle::m_speed, and pgrouting::vrp::Vehicle::speed().
Referenced by pgrouting::vrp::Vehicle::is_ok().
{
          return m_path.back();
      }
erase() [1/3]
void pgrouting::vrp::Vehicle_pickDeliver::erase (const Order & order)
Definition at line 341 of file vehicle_pickDeliver.cpp.
References pgrouting::vrp::Order::delivery(), pgrouting::vrp::Vehicle::erase(), has_order(), pgrouting::Identifier::idx(), pgrouting::vrp::Vehicle::invariant(), m_orders_in_vehicle, pgassert, and pgrouting::vrp::Order::pickup().
Referenced by do_while_feasable(), pgrouting::vrp::Optimize::move_order(), orders_in_vehicle(), pop_back(), pop_front(), and pgrouting::vrp::Optimize::swap_order().
{
     invariant();
     pgassert(has_order(order));
     Vehicle::erase(order.pickup());
     Vehicle::erase(order.delivery());
     m_orders_in_vehicle -= order.idx();
     invariant();
     pgassert(!has_order(order));
 }
erase() [2/3]
void pgrouting::vrp::Vehicle::erase (const Vehicle_node & node) inherited
Erase node.id()
Note
start and ending nodes cannot be erased
Numbers are positions before: S .... node.id() .... E after: S .... .... E
Todo:
TODO evaluate with matrix also
Definition at line 238 of file vehicle.cpp.
References pgrouting::vrp::Vehicle::evaluate(), pgrouting::Identifier::idx(), pgrouting::vrp::Vehicle::invariant(), and pgrouting::vrp::Vehicle::m_path.
Referenced by erase(), insert(), pgrouting::vrp::Vehicle::is_phony(), pgrouting::vrp::Vehicle::pop_back(), pgrouting::vrp::Vehicle::pop_front(), and semiLIFO().
{
     invariant();
     POS pos = 0;
     for ( ; pos < m_path.size() ; ++pos) {
         if (node.idx() == m_path[pos].idx())
             break;
     }
     erase(pos);
     evaluate(pos);
     invariant();
 }
erase() [3/3]
void pgrouting::vrp::Vehicle::erase (POS pos) inherited
Erase node at pos from the path.
Note
start and ending nodes cannot be erased
Numbers are positions before: S 1 2 3 4 5 6 pos 8 9 E after: S 1 2 3 4 5 6 8 9 E
Parameters
[in] pos to be erased.
Definition at line 314 of file vehicle.cpp.
References pgrouting::vrp::Vehicle::evaluate(), pgrouting::vrp::Vehicle::invariant(), pgrouting::vrp::Vehicle::m_path, and pgassert.
                      {
     invariant();
     pgassert(m_path.size() > 2);
     pgassert(at < m_path.size());
     pgassert(!m_path[at].is_start());
     pgassert(!m_path[at].is_end());
     m_path.erase(m_path.begin() + at);
     evaluate(at);
     invariant();
 }
evaluate() [1/2]
void pgrouting::vrp::Vehicle::evaluate () inherited
@ {
Evaluate: Evaluate the whole path from the start.
Definition at line 345 of file vehicle.cpp.
References pgrouting::vrp::Vehicle::invariant().
Referenced by pgrouting::vrp::Vehicle::capacity(), pgrouting::vrp::Vehicle::erase(), pgrouting::vrp::Vehicle::insert(), push_back(), push_front(), pgrouting::vrp::Vehicle::swap(), and pgrouting::vrp::Vehicle::Vehicle().
                   {
     invariant();
     evaluate(0);
     invariant();
 }
evaluate() [2/2]
void pgrouting::vrp::Vehicle::evaluate (POS from) inherited
Evaluate: Evaluate a path from the given position.
Parameters
[in] from The starting position in the path for evaluation to the end of the path.
Definition at line 366 of file vehicle.cpp.
References pgrouting::vrp::Vehicle::invariant(), pgrouting::vrp::Vehicle::m_capacity, pgrouting::vrp::Vehicle::m_path, pgassert, and pgrouting::vrp::Vehicle::speed().
{
     invariant();
     // preconditions
     pgassert(from < m_path.size());
     auto node = m_path.begin() + from;
     while (node != m_path.end()) {
         if (node == m_path.begin()) {
             node->evaluate(m_capacity);
         } else {
             node->evaluate(*(node - 1), m_capacity, speed());
         }
         ++node;
     }
     invariant();
 }
feasable_orders()
Identifiers<size_t> pgrouting::vrp::Vehicle_pickDeliver::feasable_orders () const inline
Definition at line 75 of file vehicle_pickDeliver.h.
References m_feasable_orders.
 {return m_feasable_orders;}
free_time()
double pgrouting::vrp::Vehicle::free_time () const inline inherited
Definition at line 249 of file vehicle.h.
References pgrouting::vrp::Vehicle::duration(), and pgrouting::vrp::Vehicle::total_wait_time().
{
          return total_wait_time() + (m_path[0].closes() - duration());
      }
get_first_order()
Order pgrouting::vrp::Vehicle_pickDeliver::get_first_order () const
Definition at line 73 of file vehicle_pickDeliver.cpp.
References pgrouting::vrp::Vehicle::empty(), pgrouting::vrp::Vehicle::invariant(), m_orders, pgrouting::vrp::Vehicle::m_path, and pgassert.
Referenced by orders_in_vehicle().
{
     invariant();
     pgassert(!empty());
     return m_orders[m_path[1].idx()];
 }
get_postgres_result()
std::vector< General_vehicle_orders_t > pgrouting::vrp::Vehicle::get_postgres_result (int vid) const inherited
Definition at line 135 of file vehicle.cpp.
References pgrouting::Identifier::id(), pgrouting::Pgr_messages::log, pgrouting::vrp::Vehicle::m_path, pgrouting::vrp::PD_problem::msg, and pgrouting::vrp::Vehicle::tau().
{
     std::vector<General_vehicle_orders_t> result;
     /* postgres numbering starts with 1 */
     int stop_seq(1);
     msg.log << "getting solution: " << tau() << "\n";
     for (const auto p_stop : m_path) {
         General_vehicle_orders_t data = {
             vid,
             id(),
             stop_seq,
             /* order_id
              * The order_id is invalid for stops type 0 and 5
              */
             (p_stop.type() == 0 || p_stop.type() == 5)? -1 : p_stop.order(),
             p_stop.id(),
             p_stop.type(),
             p_stop.cargo(),
             p_stop.travel_time(),
             p_stop.arrival_time(),
             p_stop.wait_time(),
             p_stop.service_time(),
             p_stop.departure_time()};
         result.push_back(data);
         ++stop_seq;
     }
     return result;
 }
get_worse_order()
Order pgrouting::vrp::Vehicle_pickDeliver::get_worse_order (Identifiers< size_t > of_this_subset) const
Definition at line 47 of file vehicle_pickDeliver.cpp.
References Identifiers< T >::begin(), pgrouting::vrp::Vehicle::duration(), Identifiers< T >::empty(), pgrouting::vrp::Vehicle::empty(), pgrouting::vrp::Vehicle::invariant(), m_orders, and pgassert.
Referenced by orders_in_vehicle().
{
     invariant();
     pgassert(!empty());
     // auto orders(of_this_subset);
     auto worse_order(m_orders[*orders.begin()]);
     auto delta_duration((std::numeric_limits<double>::max)());
     auto curr_duration(duration());
     while (!orders.empty()) {
         auto truck(*this);
         auto order = m_orders[*orders.begin()];
         pgassert(truck.has_order(order));
         orders -= order.idx();
         truck.erase(order);
         auto delta = truck.duration() - curr_duration;
         if (delta < delta_duration) {
             worse_order = order;
             delta_duration = delta;
         }
     }
     return worse_order;
 }
has_cv()
bool pgrouting::vrp::Vehicle::has_cv () const inline inherited
Definition at line 261 of file vehicle.h.
References pgrouting::vrp::Vehicle::cvTot().
Referenced by insert(), pgrouting::vrp::Vehicle::is_feasable(), push_back(), push_front(), and semiLIFO().
{
          return cvTot() != 0;
      }
has_order()
bool pgrouting::vrp::Vehicle_pickDeliver::has_order (const Order & order) const
Definition at line 103 of file vehicle_pickDeliver.cpp.
References Identifiers< T >::has(), pgrouting::Identifier::idx(), and m_orders_in_vehicle.
Referenced by do_while_feasable(), erase(), insert(), pgrouting::vrp::Optimize::move_order(), orders_in_vehicle(), push_back(), push_front(), semiLIFO(), pgrouting::vrp::Optimize::swap_order(), and pgrouting::vrp::Optimize::swap_worse().
{
     return m_orders_in_vehicle.has(order.idx());
 }
has_twv()
bool pgrouting::vrp::Vehicle::has_twv () const inline inherited
Definition at line 258 of file vehicle.h.
References pgrouting::vrp::Vehicle::twvTot().
Referenced by pgrouting::vrp::Vehicle::is_feasable(), and semiLIFO().
{
          return twvTot() != 0;
      }
id()
int64_t pgrouting::Identifier::id () const inherited
Definition at line 42 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Dnode::distance(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::vrp::Vehicle::is_phony(), pgrouting::vrp::operator<<(), pgrouting::operator<<(), pgrouting::vrp::Base_node::operator==(), pgrouting::vrp::Node::operator==(), pgrouting::vrp::Node::print(), pgrouting::vrp::Vehicle::tau(), and pgrouting::vrp::Vehicle::Vehicle().
                      {
     return m_id;
 }
idx()
size_t pgrouting::Identifier::idx () const inherited
Definition at line 37 of file identifier.cpp.
References pgrouting::Identifier::m_idx.
Referenced by erase(), pgrouting::vrp::Vehicle::erase(), pgrouting::vrp::Fleet::get_truck(), has_order(), pgrouting::vrp::Vehicle::insert(), insert(), pgrouting::vrp::operator<<(), pgrouting::operator<<(), pgrouting::vrp::Base_node::operator==(), pgrouting::vrp::Node::operator==(), pgrouting::vrp::Tw_node::operator==(), pgrouting::vrp::Node::print(), push_back(), push_front(), semiLIFO(), pgrouting::vrp::Order::set_compatibles(), pgrouting::vrp::Solution::sort_by_id(), pgrouting::vrp::Vehicle::tau(), pgrouting::vrp::Tw_node::travel_time_to(), and pgrouting::vrp::Vehicle::Vehicle().
                       {
     return m_idx;
 }
insert() [1/3]
void pgrouting::vrp::Vehicle::insert (POS pos, Vehicle_node node) inherited
@ {
Insert node at pos position.
Parameters
[in] pos The position that the node should be inserted.
[in] node The node to insert.
Definition at line 174 of file vehicle.cpp.
References pgrouting::vrp::Vehicle::evaluate(), pgrouting::Identifier::idx(), pgrouting::vrp::Vehicle::invariant(), pgrouting::vrp::Vehicle::m_path, and pgassert.
Referenced by pgrouting::vrp::Vehicle::insert(), insert(), pgrouting::vrp::Vehicle::insert_less_travel_time(), pgrouting::vrp::Vehicle::is_phony(), pgrouting::vrp::Vehicle::push_back(), pgrouting::vrp::Vehicle::push_front(), and semiLIFO().
{
     invariant();
     pgassert(at <= m_path.size());
     m_path.insert(m_path.begin() + at, node);
     evaluate(at);
     pgassert(at < m_path.size());
     pgassert(m_path[at].idx() == node.idx());
     invariant();
 }
insert() [2/3]
size_t pgrouting::vrp::Vehicle::insert (std::pair< POS, POS > position_limits, const Vehicle_node & node) inherited
Insert node in best position of the position_limits.
Parameters
[in] position_limits
[in] node The node to insert
Returns
position where it was inserted
Definition at line 54 of file vehicle.cpp.
References pgrouting::vrp::Vehicle::cost(), pgrouting::vrp::Vehicle::cost_compare(), pgrouting::Identifier::idx(), pgrouting::vrp::Vehicle::insert(), pgrouting::vrp::Vehicle::invariant(), pgrouting::vrp::Vehicle::m_path, pgassert, and pgrouting::vrp::Vehicle::swap().
{
     invariant();
     pgassert(position_limits.first <= m_path.size());
     pgassert(position_limits.second <= m_path.size());
     auto low = position_limits.first;
     auto high = position_limits.second;
     auto best = low;
     insert(low, node);
     Vehicle::Cost best_cost(cost());
     while (low < high) {
         swap(low, low + 1);
         ++low;
         if (cost_compare(best_cost, cost())) {
             best_cost = cost();
             best = low;
         }
     }
     return best;
     pgassert(best < m_path.size());
     pgassert(m_path[best].idx() == node.idx());
     invariant();
 }
insert() [3/3]
bool pgrouting::vrp::Vehicle_pickDeliver::insert (const Order & order)
Inserts an order.
Precondition: !has_order(order)
Postcondition: has_order(order) !has_cv();
Before: S <nodes> E
  After: S ....P .... D .... E
push_back is performed when
pickup
Can generate time window violation No capacity violation
Definition at line 109 of file vehicle_pickDeliver.cpp.
References pgrouting::vrp::Order::delivery(), pgrouting::vrp::Vehicle::duration(), pgrouting::vrp::Vehicle::erase(), pgrouting::vrp::Vehicle::has_cv(), has_order(), pgrouting::Identifier::idx(), pgrouting::vrp::Vehicle::insert(), pgrouting::vrp::Vehicle::invariant(), pgrouting::vrp::Vehicle::is_feasable(), m_orders_in_vehicle, pgrouting::vrp::Vehicle::m_path, pgassert, pgassertwm, pgrouting::vrp::Order::pickup(), pgrouting::vrp::Vehicle::position_limits(), and pgrouting::vrp::Vehicle::tau().
Referenced by do_while_feasable(), pgrouting::vrp::Optimize::move_order(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), orders_in_vehicle(), and pgrouting::vrp::Optimize::swap_order().
{
     invariant();
     pgassert(!has_order(order));
     auto pick_pos(position_limits(order.pickup()));
     auto deliver_pos(position_limits(order.delivery()));
 #ifndef NDEBUG
     std::ostringstream err_log;
     err_log << "\n\tpickup limits (low, high) = ("
         << pick_pos.first << ", "
         << pick_pos.second << ") "
         << "\n\tdeliver limits (low, high) = ("
         << deliver_pos.first << ", "
         << deliver_pos.second << ") "
         << "\noriginal" << tau();
 #endif
     if (pick_pos.second < pick_pos.first) {
         /*
          *  pickup generates twv evrywhere
          */
         return false;
     }
     if (deliver_pos.second < deliver_pos.first) {
         /*
          *  delivery generates twv evrywhere
          */
         return false;
     }
     /*
      * Because delivery positions were estimated without
      * the pickup:
      *   - increase the upper limit position estimation
      */
     ++deliver_pos.first;
     ++deliver_pos.second;
     auto d_pos_backup(deliver_pos);
     auto best_pick_pos = m_path.size();
     auto best_deliver_pos = m_path.size() + 1;
     auto current_duration(duration());
     auto min_delta_duration = (std::numeric_limits<double>::max)();
     auto found(false);
     pgassertwm(!has_order(order), err_log.str());
     while (pick_pos.first <= pick_pos.second) {
 #ifndef NDEBUG
         err_log << "\n\tpickup cycle limits (low, high) = ("
             << pick_pos.first << ", "
             << pick_pos.second << ") ";
 #endif
         Vehicle::insert(pick_pos.first, order.pickup());
 #ifndef NDEBUG
         err_log << "\npickup inserted: " << tau();
 #endif
         if (deliver_pos.first <= pick_pos.first) deliver_pos.first = pick_pos.first + 1;
         while (deliver_pos.first <= deliver_pos.second) {
             Vehicle::insert(deliver_pos.first, order.delivery());
             m_orders_in_vehicle += order.idx();
             pgassertwm(has_order(order), err_log.str());
 #ifndef NDEBUG
             err_log << "\ndelivery inserted: " << tau();
 #endif
             if (is_feasable()) {
                 pgassert(is_feasable());
                 auto delta_duration = duration() - current_duration;
                 if (delta_duration < min_delta_duration) {
 #ifndef NDEBUG
                     err_log << "\nsuccess" << tau();
 #endif
                     min_delta_duration = delta_duration;
                     best_pick_pos = pick_pos.first;
                     best_deliver_pos = deliver_pos.first;
                     found = true;
                 }
             }
             Vehicle::erase(deliver_pos.first);
 #ifndef NDEBUG
             err_log << "\ndelivery erased: " << tau();
 #endif
             ++deliver_pos.first;
         }
         Vehicle::erase(pick_pos.first);
 #ifndef NDEBUG
         err_log << "\npickup erased: " << tau();
 #endif
         m_orders_in_vehicle -= order.idx();
         pgassertwm(!has_order(order), err_log.str());
         deliver_pos = d_pos_backup;
 #ifndef NDEBUG
         err_log << "\n\trestoring deliver limits (low, high) = ("
             << deliver_pos.first << ", "
             << deliver_pos.second << ") ";
 #endif
         ++pick_pos.first;
     }
     pgassertwm(!has_order(order), err_log.str());
     if (!found) {
         /* order causes twv or cv */
         return false;
     }
     Vehicle::insert(best_pick_pos, order.pickup());
     Vehicle::insert(best_deliver_pos, order.delivery());
     m_orders_in_vehicle += order.idx();
     pgassertwm(is_feasable(), err_log.str());
     pgassertwm(has_order(order), err_log.str());
     pgassertwm(!has_cv(), err_log.str());
     invariant();
     return true;
 }
insert_less_travel_time()
size_t pgrouting::vrp::Vehicle::insert_less_travel_time (const Vehicle_node & node, POS after_pos = 0) inherited
Definition at line 215 of file vehicle.cpp.
References pgrouting::vrp::Vehicle::deltaTime(), pgrouting::vrp::Vehicle::insert(), pgrouting::vrp::Vehicle::invariant(), and pgrouting::vrp::Vehicle::m_path.
Referenced by pgrouting::vrp::Vehicle::capacity().
{
     invariant();
     double min_delta = (std::numeric_limits<double>::max)();
     POS min_pos = after_pos;
     for (POS pos = after_pos; pos < m_path.size(); ++pos) {
         if (!m_path[pos].is_start()) {
             auto tt = deltaTime(node, pos);
             if (tt < min_delta) {
                 min_delta = tt;
                 min_pos = pos;
             }
         }
     }
     insert(min_pos, node);
     invariant();
     return min_pos;
 }
invariant()
void pgrouting::vrp::Vehicle::invariant () const inherited
Invariant The path must:
have at least 2 nodes
first node of the path must be Start node
last node of the path must be End node
path: S ..... E
Definition at line 47 of file vehicle.cpp.
References pgrouting::vrp::Vehicle::m_path, and pgassert.
Referenced by do_while_feasable(), pgrouting::vrp::Vehicle::empty(), erase(), pgrouting::vrp::Vehicle::erase(), pgrouting::vrp::Vehicle::evaluate(), get_first_order(), get_worse_order(), pgrouting::vrp::Vehicle::getDropPosLowLimit(), pgrouting::vrp::Vehicle::getPosHighLimit(), pgrouting::vrp::Vehicle::getPosLowLimit(), pgrouting::vrp::Vehicle::insert(), insert(), pgrouting::vrp::Vehicle::insert_less_travel_time(), pgrouting::vrp::Vehicle::is_phony(), pgrouting::vrp::operator<(), pgrouting::vrp::operator<<(), pgrouting::vrp::Vehicle::path(), pgrouting::vrp::Vehicle::pop_back(), pop_back(), pgrouting::vrp::Vehicle::pop_front(), pop_front(), push_back(), pgrouting::vrp::Vehicle::push_back(), push_front(), pgrouting::vrp::Vehicle::push_front(), semiLIFO(), pgrouting::vrp::Vehicle::size(), pgrouting::vrp::Vehicle::swap(), pgrouting::vrp::Vehicle::Vehicle(), and Vehicle_pickDeliver().
{
     pgassert(m_path.size() >= 2);
     pgassert(m_path.front().is_start());
     pgassert(m_path.back().is_end());
 }
is_feasable()
bool pgrouting::vrp::Vehicle::is_feasable () const inline inherited
Definition at line 265 of file vehicle.h.
References pgrouting::vrp::Vehicle::has_cv(), pgrouting::vrp::Vehicle::has_twv(), and pgrouting::vrp::Vehicle::is_ok().
Referenced by do_while_feasable(), insert(), semiLIFO(), and pgrouting::vrp::Optimize::swap_order().
{
          return !(has_twv() ||  has_cv());
      }
is_ok()
bool pgrouting::vrp::Vehicle::is_ok () const inherited
Definition at line 505 of file vehicle.cpp.
References pgrouting::vrp::Tw_node::closes(), pgrouting::vrp::Vehicle::end_site(), pgrouting::vrp::Vehicle::m_capacity, pgrouting::vrp::Vehicle::m_path, pgrouting::vrp::Tw_node::opens(), pgassert, and pgrouting::vrp::Vehicle::start_site().
Referenced by pgrouting::vrp::Vehicle::is_feasable().
                      {
     pgassert((m_path.front().opens() <= m_path.front().closes())
         && (m_path.back().opens() <= m_path.back().closes())
         && (m_capacity > 0));
     return (start_site().opens() <= start_site().closes())
         && (end_site().opens() <= end_site().closes())
         && (m_capacity > 0);
 }
is_order_feasable()
bool pgrouting::vrp::Vehicle_pickDeliver::is_order_feasable (const Order & order) const
Definition at line 419 of file vehicle_pickDeliver.cpp.
Referenced by set_compatibles().
{
     auto test_truck =  *this;
     test_truck.push_back(order);
     return test_truck.is_feasable();
 }
is_phony()
bool pgrouting::vrp::Vehicle::is_phony () const inline inherited
Definition at line 101 of file vehicle.h.
References pgrouting::vrp::Vehicle::cost(), pgrouting::vrp::Vehicle::cost_compare(), pgrouting::vrp::Vehicle::empty(), pgrouting::vrp::Vehicle::erase(), pgrouting::Identifier::id(), pgrouting::vrp::Vehicle::insert(), pgrouting::vrp::Vehicle::invariant(), pgrouting::vrp::Vehicle::pop_back(), pgrouting::vrp::Vehicle::pop_front(), pgrouting::vrp::Vehicle::position_limits(), pgrouting::vrp::Vehicle::push_back(), pgrouting::vrp::Vehicle::push_front(), pgrouting::vrp::Vehicle::size(), and pgrouting::vrp::Vehicle::speed().
Referenced by pgrouting::vrp::Optimize::move_order().
 {return id() < 0;}
orders()
const PD_Orders& pgrouting::vrp::Vehicle_pickDeliver::orders () const inline
Definition at line 77 of file vehicle_pickDeliver.h.
References m_orders.
Referenced by pgrouting::vrp::operator<<(), set_compatibles(), and pgrouting::vrp::Optimize::swap_worse().
 {return m_orders;}
orders_in_vehicle()
Identifiers<size_t> pgrouting::vrp::Vehicle_pickDeliver::orders_in_vehicle () const inline
Definition at line 79 of file vehicle_pickDeliver.h.
References do_while_feasable(), erase(), get_first_order(), get_worse_order(), has_order(), insert(), m_orders_in_vehicle, pop_back(), pop_front(), push_back(), push_front(), and semiLIFO().
Referenced by pgrouting::vrp::Optimize::move_reduce_cost(), pgrouting::vrp::Optimize::sort_by_id(), pgrouting::vrp::Optimize::sort_by_size(), and pgrouting::vrp::Optimize::swap_worse().
 {return m_orders_in_vehicle;}
orders_size()
size_t pgrouting::vrp::Vehicle_pickDeliver::orders_size () const inline
Definition at line 78 of file vehicle_pickDeliver.h.
References Identifiers< T >::size().
Referenced by do_while_feasable(), and pgrouting::vrp::Optimize::sort_for_move().
 {return m_orders_in_vehicle.size();}
path()
std::deque< Vehicle_node > pgrouting::vrp::Vehicle::path () const inherited
@ {
Definition at line 387 of file vehicle.cpp.
References pgrouting::vrp::Vehicle::invariant(), and pgrouting::vrp::Vehicle::m_path.
Referenced by pgrouting::vrp::Vehicle::capacity(), and pgrouting::vrp::operator<<().
                     {
     invariant();
     return m_path;
 }
pop_back()
size_t pgrouting::vrp::Vehicle_pickDeliver::pop_back ()
The order that is picked last is removed.
Returns
id of the removed order
Definition at line 357 of file vehicle_pickDeliver.cpp.
References pgrouting::vrp::Vehicle::empty(), erase(), pgrouting::vrp::Vehicle::invariant(), m_orders, pgrouting::vrp::Vehicle::m_path, and pgassert.
Referenced by orders_in_vehicle().
{
     invariant();
     pgassert(!empty());
     auto pick_itr = m_path.rbegin();
     while (pick_itr != m_path.rend() &&  !pick_itr->is_pickup()) {
         ++pick_itr;
     }
     pgassert(pick_itr->is_pickup());
     auto deleted_pick_idx = pick_itr->idx();
     for (const auto o : m_orders) {
         if (o.pickup().idx() == deleted_pick_idx) {
             erase(o);
             invariant();
             return o.idx();
         }
     }
     pgassert(false);
     return 0;
 }
pop_front()
size_t pgrouting::vrp::Vehicle_pickDeliver::pop_front ()
Definition at line 384 of file vehicle_pickDeliver.cpp.
References pgrouting::vrp::Vehicle::empty(), erase(), pgrouting::vrp::Vehicle::invariant(), m_orders, pgrouting::vrp::Vehicle::m_path, and pgassert.
Referenced by orders_in_vehicle().
{
     invariant();
     pgassert(!empty());
     auto pick_itr = m_path.begin();
     while (pick_itr != m_path.end() &&  !pick_itr->is_pickup()) {
         ++pick_itr;
     }
     pgassert(pick_itr->is_pickup());
     auto deleted_pick_idx = pick_itr->idx();
     for (const auto o : m_orders) {
         if (o.pickup().idx() == deleted_pick_idx) {
             erase(o);
             invariant();
             return o.idx();
         }
     }
     pgassert(false);
     return 0;
 }
position_limits()
std::pair< size_t, size_t > pgrouting::vrp::Vehicle::position_limits (const Vehicle_node node) const inherited
Definition at line 394 of file vehicle.cpp.
References pgrouting::vrp::Vehicle::getPosHighLimit(), and pgrouting::vrp::Vehicle::getPosLowLimit().
Referenced by pgrouting::vrp::Vehicle::capacity(), insert(), and pgrouting::vrp::Vehicle::is_phony().
{
     POS high = getPosHighLimit(node);
     POS low = getPosLowLimit(node);
     return std::make_pair(low, high);
 }
push_back() [1/2]
void pgrouting::vrp::Vehicle_pickDeliver::push_back (const Order & order)
puts an order at the end of the truck
Precondition: !has_order(order)
Postcondition: has_order(order) !has_cv();
Before: S <nodes> E
  After: S <nodes> P D E
Can generate time window violation No capacity violation
Definition at line 227 of file vehicle_pickDeliver.cpp.
References pgrouting::vrp::Order::delivery(), pgrouting::vrp::Vehicle::evaluate(), pgrouting::vrp::Vehicle::has_cv(), has_order(), pgrouting::Identifier::idx(), pgrouting::vrp::Vehicle::invariant(), m_orders_in_vehicle, pgrouting::vrp::Vehicle::m_path, pgassert, and pgrouting::vrp::Order::pickup().
Referenced by do_while_feasable(), and orders_in_vehicle().
{
     invariant();
     pgassert(!has_order(order));
     m_orders_in_vehicle += order.idx();
     m_path.insert(m_path.end() - 1, order.pickup());
     m_path.insert(m_path.end() - 1, order.delivery());
     evaluate(m_path.size() - 3);
     pgassert(has_order(order));
 #if 0
     pgassert(!has_cv());
 #endif
     invariant();
 }
push_back() [2/2]
void pgrouting::vrp::Vehicle::push_back (const Vehicle_node & node) inherited
Evaluated: push_back a node to the path.
before: S <nodes> E
after: S <nodes> n E
Parameters
[in] node to be push_back.
Definition at line 280 of file vehicle.cpp.
References pgrouting::vrp::Vehicle::insert(), pgrouting::vrp::Vehicle::invariant(), and pgrouting::vrp::Vehicle::m_path.
Referenced by pgrouting::vrp::Vehicle::is_phony().
{
     invariant();
     /* insert evaluates */
     insert(m_path.size() - 1, node);
     invariant();
 }
push_front() [1/2]
void pgrouting::vrp::Vehicle_pickDeliver::push_front (const Order & order)
Puts an order at the end front of the truck.
Precondition: !has_order(order)
Postcondition: has_order(order) !has_cv();
Before: S <nodes> E
  After: S P D <nodes> E
Can generate time window violation No capacity violation
Definition at line 245 of file vehicle_pickDeliver.cpp.
References pgrouting::vrp::Order::delivery(), pgrouting::vrp::Vehicle::evaluate(), pgrouting::vrp::Vehicle::has_cv(), has_order(), pgrouting::Identifier::idx(), pgrouting::vrp::Vehicle::invariant(), m_orders_in_vehicle, pgrouting::vrp::Vehicle::m_path, pgassert, and pgrouting::vrp::Order::pickup().
Referenced by do_while_feasable(), and orders_in_vehicle().
{
     invariant();
     pgassert(!has_order(order));
     m_orders_in_vehicle += order.idx();
     m_path.insert(m_path.begin() + 1, order.delivery());
     m_path.insert(m_path.begin() + 1, order.pickup());
     evaluate(1);
     pgassert(has_order(order));
 #if 0
     pgassert(!has_cv());
 #endif
     invariant();
 }
push_front() [2/2]
void pgrouting::vrp::Vehicle::push_front (const Vehicle_node & node) inherited
Evaluated: push_back a node to the path.
before: S <nodes> E
after: S n <nodes> E
Parameters
[in] node to be push_back.
Definition at line 263 of file vehicle.cpp.
References pgrouting::vrp::Vehicle::insert(), and pgrouting::vrp::Vehicle::invariant().
Referenced by pgrouting::vrp::Vehicle::is_phony().
{
     invariant();
     /* insert evaluates */
     insert(1, node);
     invariant();
 }
reset_id()
void pgrouting::Identifier::reset_id (int64_t _id) inherited
Definition at line 47 of file identifier.cpp.
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Tw_node::Tw_node().
{
     m_id = _id;
 }
semiLIFO()
bool pgrouting::vrp::Vehicle_pickDeliver::semiLIFO (const Order & order)
Inserts an order In semi-Lifo order.
Precondition: !has_order(order)
Postcondition: has_order(order) !has_cv();
Before: S .... (P1 ....... P2) ... D2 .... D1 .... E
 After: S .... (P .. P1 .. P2) ... D2 .. D .. D1 .... E
push_back is performed when
drop generates a time window violation
Can generate time window violation No capacity violation
Definition at line 426 of file vehicle_pickDeliver.cpp.
References pgrouting::vrp::Order::delivery(), pgrouting::vrp::Vehicle::drop_position_limits(), pgrouting::vrp::Vehicle::erase(), pgrouting::vrp::Vehicle::has_cv(), has_order(), pgrouting::vrp::Vehicle::has_twv(), pgrouting::Identifier::idx(), pgrouting::vrp::Vehicle::insert(), pgrouting::vrp::Vehicle::invariant(), pgrouting::vrp::Vehicle::is_feasable(), m_orders_in_vehicle, pgrouting::vrp::Vehicle::m_path, pgassert, and pgrouting::vrp::Order::pickup().
Referenced by do_while_feasable(), pgrouting::vrp::Optimize::move_order(), orders_in_vehicle(), and pgrouting::vrp::Optimize::swap_order().
{
     invariant();
     pgassert(!has_order(order));
     /*
      * Insert pick up as first picked
      */
     Vehicle::insert(1, order.pickup());
     auto deliver_pos(drop_position_limits(order.delivery()));
     /*
      * delivery generates twv in all positions
      */
     if (deliver_pos.second < deliver_pos.first) {
         /*
          * Remove inserted pickup
          */
         Vehicle::erase(1);
         invariant();
         return false;
     }
     pgassert(!has_order(order));
     while (deliver_pos.first <= deliver_pos.second) {
         Vehicle::insert(deliver_pos.second, order.delivery());
         if (is_feasable() && !m_path[deliver_pos.second + 1].is_pickup()) {
             /*
              * Found a position to insert the delivery
              */
             m_orders_in_vehicle += order.idx();
             /*
              * There is one more order in the vehicle
              */
             pgassert(has_order(order));
             pgassert(is_feasable());
             pgassert(!has_cv());
             pgassert(!has_twv());
             pgassert(has_order(order));
             invariant();
             return true;
         }
         /*
          * This position in path is not suitable
          */
         Vehicle::erase(deliver_pos.second);
         /*
          * got to next position
          */
         --deliver_pos.second;
     }
     /*
      * Order could not be inserted
      */
     Vehicle::erase(1);
     pgassert(!has_order(order));
     invariant();
     return false;
 }
set_compatibles()
void pgrouting::vrp::Vehicle_pickDeliver::set_compatibles (const PD_Orders & orders)
Definition at line 410 of file vehicle_pickDeliver.cpp.
References is_order_feasable(), m_feasable_orders, m_orders, orders(), pgrouting::vrp::PD_Orders::set_compatibles(), and pgrouting::vrp::Vehicle::speed().
{
     m_orders = orders;
     for (const auto o : orders) {
         if (is_order_feasable(o)) m_feasable_orders += o.idx();
     }
     m_orders.set_compatibles(speed());
 }
size()
size_t pgrouting::vrp::Vehicle::size () const inherited
return number of nodes in the truck
True: S E
False: S <nodes> E
Definition at line 360 of file vehicle.cpp.
References pgrouting::vrp::Vehicle::invariant(), and pgrouting::vrp::Vehicle::m_path.
Referenced by pgrouting::vrp::Vehicle::is_phony(), and pgrouting::vrp::Optimize::move_order().
                     {
     invariant();
     return m_path.size() - 2;
 }
speed()
double pgrouting::vrp::Vehicle::speed () const inherited
Definition at line 587 of file vehicle.cpp.
References pgrouting::vrp::Vehicle::m_factor, and pgrouting::vrp::Vehicle::m_speed.
Referenced by pgrouting::vrp::Vehicle::deltaTime(), pgrouting::vrp::Vehicle::end_site(), pgrouting::vrp::Vehicle::evaluate(), pgrouting::vrp::Vehicle::getDropPosLowLimit(), pgrouting::vrp::Vehicle::getPosHighLimit(), pgrouting::vrp::Vehicle::getPosLowLimit(), pgrouting::vrp::Vehicle::is_phony(), pgrouting::vrp::operator<<(), and set_compatibles().
                      {
     return m_speed/m_factor;
 }
start_site()
Vehicle_node pgrouting::vrp::Vehicle::start_site () const inline inherited
Definition at line 271 of file vehicle.h.
Referenced by pgrouting::vrp::Vehicle::is_ok().
{
          return m_path.front();
      }
swap()
void pgrouting::vrp::Vehicle::swap (POS i, POS j) inherited
Swap two nodes in the path.
Before: S <nodesA> I <nodesB> J <nodesC> E
After: S <nodesA> J <nodesB> I <nodesC> E
Parameters
[in] i The position of the first node to swap.
[in] j The position of the second node to swap.
Definition at line 329 of file vehicle.cpp.
References pgrouting::vrp::Vehicle::evaluate(), pgrouting::vrp::Vehicle::invariant(), pgrouting::vrp::Vehicle::m_path, and pgassert.
Referenced by pgrouting::vrp::Vehicle::capacity(), and pgrouting::vrp::Vehicle::insert().
{
     invariant();
     pgassert(m_path.size() > 3);
     pgassert(!m_path[i].is_start());
     pgassert(!m_path[i].is_end());
     pgassert(!m_path[j].is_start());
     pgassert(!m_path[j].is_end());
     std::swap(m_path[i], m_path[j]);
     i < j ? evaluate(i) : evaluate(j);
     invariant();
 }
tau()
std::string pgrouting::vrp::Vehicle::tau () const inherited
Definition at line 567 of file vehicle.cpp.
References pgrouting::vrp::Vehicle::cvTot(), pgrouting::vrp::Vehicle::duration(), pgrouting::Identifier::id(), pgrouting::Identifier::idx(), pgrouting::vrp::Vehicle::m_path, pgassert, pgrouting::vrp::Vehicle::total_wait_time(), and pgrouting::vrp::Vehicle::twvTot().
Referenced by pgrouting::vrp::Vehicle::capacity(), pgrouting::vrp::Vehicle::get_postgres_result(), insert(), pgrouting::vrp::operator<<(), and pgrouting::vrp::Vehicle::Vehicle().
                    {
     pgassert(m_path.size() > 1);
     std::ostringstream log;
     log << "Truck " << id() << "(" << idx() << ")"
         << " (";
     for (const auto p_stop : m_path) {
         if (!(p_stop == m_path.front()))
             log << ", ";
         log << p_stop.id();
     }
     log << ")" << " \t(cv, twv, wait_time, duration) = ("
         << cvTot() << ", "
         << twvTot() << ", "
         << total_wait_time() << ", "
         << duration() << ")";
     return log.str();
 }
total_service_time()
double pgrouting::vrp::Vehicle::total_service_time () const inline inherited
Definition at line 246 of file vehicle.h.
{
          return m_path.back().total_service_time();
      }
total_travel_time()
double pgrouting::vrp::Vehicle::total_travel_time () const inline inherited
Definition at line 243 of file vehicle.h.
{
          return m_path.back().total_travel_time();
      }
total_wait_time()
double pgrouting::vrp::Vehicle::total_wait_time () const inline inherited
Definition at line 240 of file vehicle.h.
Referenced by pgrouting::vrp::Vehicle::cost(), pgrouting::vrp::Vehicle::free_time(), pgrouting::vrp::Optimize::sort_for_move(), and pgrouting::vrp::Vehicle::tau().
{
          return m_path.back().total_wait_time();
      }
twvTot()
int pgrouting::vrp::Vehicle::twvTot () const inline inherited
Definition at line 252 of file vehicle.h.
Referenced by pgrouting::vrp::Vehicle::cost(), pgrouting::vrp::Vehicle::has_twv(), and pgrouting::vrp::Vehicle::tau().
{
          return m_path.back().twvTot();
      }
Friends And Related Function Documentation
Initial_solution
friend class Initial_solution friend
Definition at line 58 of file vehicle_pickDeliver.h.
Optimize
friend class Optimize friend
Definition at line 59 of file vehicle_pickDeliver.h.
Member Data Documentation
cost
double pgrouting::vrp::Vehicle_pickDeliver::cost protected
Definition at line 49 of file vehicle_pickDeliver.h.
m_feasable_orders
Identifiers<size_t> pgrouting::vrp::Vehicle_pickDeliver::m_feasable_orders protected
orders that fit in the truck
Definition at line 54 of file vehicle_pickDeliver.h.
Referenced by do_while_feasable(), feasable_orders(), and set_compatibles().
m_orders
PD_Orders pgrouting::vrp::Vehicle_pickDeliver::m_orders protected
Definition at line 52 of file vehicle_pickDeliver.h.
Referenced by do_while_feasable(), get_first_order(), get_worse_order(), orders(), pop_back(), pop_front(), and set_compatibles().
m_orders_in_vehicle
Identifiers<size_t> pgrouting::vrp::Vehicle_pickDeliver::m_orders_in_vehicle protected
orders inserted in this vehicle
Definition at line 51 of file vehicle_pickDeliver.h.
Referenced by erase(), has_order(), insert(), orders_in_vehicle(), push_back(), push_front(), semiLIFO(), and Vehicle_pickDeliver().
m_path
std::deque< Vehicle_node > pgrouting::vrp::Vehicle::m_path protected inherited
Definition at line 75 of file vehicle.h.
Referenced by pgrouting::vrp::Vehicle::cost(), pgrouting::vrp::Vehicle::deltaTime(), pgrouting::vrp::Vehicle::empty(), pgrouting::vrp::Vehicle::erase(), pgrouting::vrp::Vehicle::evaluate(), get_first_order(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::vrp::Vehicle::getDropPosLowLimit(), pgrouting::vrp::Vehicle::getPosHighLimit(), pgrouting::vrp::Vehicle::getPosLowLimit(), pgrouting::vrp::Vehicle::insert(), insert(), pgrouting::vrp::Vehicle::insert_less_travel_time(), pgrouting::vrp::Vehicle::invariant(), pgrouting::vrp::Vehicle::is_ok(), pgrouting::vrp::operator<(), pgrouting::vrp::Vehicle::path(), pgrouting::vrp::Vehicle::pop_back(), pop_back(), pgrouting::vrp::Vehicle::pop_front(), pop_front(), push_back(), pgrouting::vrp::Vehicle::push_back(), push_front(), semiLIFO(), pgrouting::vrp::Vehicle::size(), pgrouting::vrp::Vehicle::swap(), pgrouting::vrp::Vehicle::tau(), and pgrouting::vrp::Vehicle::Vehicle().
msg
Pgr_messages pgrouting::vrp::PD_problem::msg static inherited
Definition at line 49 of file pd_problem.h.
Referenced by pgrouting::vrp::Fleet::add_vehicle(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), pgrouting::vrp::Optimize::delete_empty_truck(), do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), do_while_feasable(), pgrouting::vrp::Initial_solution::do_while_foo(), pgrouting::vrp::Pgr_pickDeliver::get_postgres_result(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Fleet::is_fleet_ok(), pgrouting::vrp::Pgr_pickDeliver::nodesOK(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), pgrouting::vrp::Optimize::Optimize(), pgrouting::vrp::Pgr_pickDeliver::optimize(), pgrouting::vrp::PD_problem::PD_problem(), pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Optimize::save_if_best(), pgrouting::vrp::Solution::Solution(), pgrouting::vrp::Pgr_pickDeliver::solve(), pgrouting::vrp::Optimize::swap_order(), and pgrouting::vrp::Vehicle::Vehicle().
problem
Pgr_pickDeliver * pgrouting::vrp::PD_problem::problem static protected inherited
Definition at line 52 of file pd_problem.h.
Referenced by pgrouting::vrp::PD_Orders::add_order(), pgrouting::vrp::Fleet::add_vehicle(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), pgrouting::vrp::Dnode::distance(), pgrouting::vrp::Solution::get_kind(), pgrouting::vrp::Pgr_pickDeliver::get_kind(), pgrouting::vrp::operator<<(), pgrouting::vrp::Tw_node::operator==(), and pgrouting::vrp::Tw_node::travel_time_to().
The documentation for this class was generated from the following files:
vehicle_pickDeliver.h
vehicle_pickDeliver.cpp