PGROUTING: Pgr_transitiveClosure< G > Class Template Reference
Pgr_transitiveClosure< G > Class Template Reference
#include "pgr_transitiveClosure.hpp"
Public Types
typedef G::V V
Public Member Functions
boost::adjacency_list< boost::vecS, boost::vecS, boost::directedS, boost::no_property, boost::no_property, boost::no_property, boost::listS > transitiveClosure (G &graph)
Private Member Functions
boost::adjacency_list< boost::vecS, boost::vecS, boost::directedS, boost::no_property, boost::no_property, boost::no_property, boost::listS > generatetransitiveClosure (G &graph)
Detailed Description
template<class G>
class Pgr_transitiveClosure< G >
Definition at line 43 of file pgr_transitiveClosure.hpp.
Member Typedef Documentation
V
template<class G> typedef G::V Pgr_transitiveClosure< G >::V
Definition at line 50 of file pgr_transitiveClosure.hpp.
Member Function Documentation
generatetransitiveClosure()
template<class G> boost::adjacency_list<boost::vecS, boost::vecS, boost::directedS, boost::no_property, boost::no_property, boost::no_property, boost::listS> Pgr_transitiveClosure< G >::generatetransitiveClosure (G & graph) inline private
Definition at line 56 of file pgr_transitiveClosure.hpp.
Referenced by Pgr_transitiveClosure< G >::transitiveClosure().
{
         boost::adjacency_list <boost::vecS, boost::vecS, boost::directedS, boost::no_property, boost::no_property,
       boost::no_property, boost::listS> TC;
         transitive_closure(graph.graph, TC);
         return TC;
     }
transitiveClosure()
template<class G > boost::adjacency_list< boost::vecS, boost::vecS, boost::directedS, boost::no_property, boost::no_property, boost::no_property, boost::listS > Pgr_transitiveClosure< G >::transitiveClosure (G & graph)
Definition at line 67 of file pgr_transitiveClosure.hpp.
References Pgr_transitiveClosure< G >::generatetransitiveClosure().
Referenced by pgr_transitiveClosure().
{
       return generatetransitiveClosure(
                              graph);
 }
The documentation for this class was generated from the following file:
pgr_transitiveClosure.hpp