PGROUTING: SignalHandler Class Reference
SignalHandler Class Reference
#include "signalhandler.h"
Public Member Functions
EventHandler * registerHandler (int signum, EventHandler *eh)
void removeHandler (int signum)
Static Public Member Functions
static SignalHandler * instance (void)
Private Member Functions
SignalHandler (void)
Static Private Member Functions
static void dispatcher (int signum)
Static Private Attributes
static SignalHandler * instance_ = NULL
static EventHandler * signalHandlers_ [NSIG]
Detailed Description
Definition at line 70 of file signalhandler.h.
Constructor & Destructor Documentation
SignalHandler()
SignalHandler::SignalHandler (void) inline private
Definition at line 87 of file signalhandler.h.
 {}
Referenced by instance().
Member Function Documentation
dispatcher()
void SignalHandler::dispatcher (int signum) static private
Definition at line 73 of file signalhandler.cpp.
{
   // Perform a sanity check...
   if (SignalHandler::signalHandlers_[signum] != 0)
     // Dispatch the handler's hook method.
     SignalHandler::signalHandlers_[signum]->handleSignal(signum);
 }
References EventHandler::handleSignal(), and signalHandlers_.
Referenced by registerHandler().
instance()
SignalHandler * SignalHandler::instance (void) static
Definition at line 38 of file signalhandler.cpp.
{
   if (!instance_) instance_ = new SignalHandler;
   // assert(instance_ != NULL);
   return instance_;
 }
References instance_, and SignalHandler().
registerHandler()
EventHandler * SignalHandler::registerHandler (int signum, EventHandler * eh)
Definition at line 47 of file signalhandler.cpp.
{
   // Copy the <old_eh> from the <signum> slot in
   // the <signalHandlers_> table.
   EventHandler *old_eh = signalHandlers_[signum];
   // Store <eh> into the <signum> slot in the
   // <signalHandlers_> table.
   SignalHandler::signalHandlers_[signum] = eh;
   // Register the <dispatcher> to handle this
   // <signum>.
   struct sigaction sa;
   sa.sa_handler = SignalHandler::dispatcher;
   sigemptyset(&sa.sa_mask);
   sa.sa_flags = 0;
   sigaction(signum, &sa, 0);
   return old_eh;
 }
References dispatcher(), and signalHandlers_.
removeHandler()
void SignalHandler::removeHandler (int signum)
Definition at line 67 of file signalhandler.cpp.
{
   // EventHandler *old_eh = signalHandlers_[signum];
   signalHandlers_[signum] = static_cast<EventHandler *>(0);
 }
References signalHandlers_.
Member Data Documentation
instance_
SignalHandler * SignalHandler::instance_ = NULL static private
Definition at line 90 of file signalhandler.h.
Referenced by instance().
signalHandlers_
EventHandler * SignalHandler::signalHandlers_ static private
Definition at line 100 of file signalhandler.h.
Referenced by dispatcher(), registerHandler(), and removeHandler().
The documentation for this class was generated from the following files:
signalhandler.h
signalhandler.cpp