PGROUTING: pgrouting::Pgr_dag< G > Class Template Reference
pgrouting::Pgr_dag< G > Class Template Reference
#include "dagShortestPath.hpp"
Classes
class dijkstra_many_goal_visitor
class for stopping when all targets are found
struct found_goals
exception for termination
Public Types
typedef G::E E
typedef G::V V
Public Member Functions
std::deque< Path > dag (G &graph, const std::map< int64_t, std::set< int64_t > > &combinations, bool only_cost)
combinations
std::deque< Path > dag (G &graph, int64_t start_vertex, const std::set< int64_t > &end_vertex, bool only_cost)
dag 1 to many
Private Member Functions
void clear ()
bool dag_1_to_many (G &graph, V source, const std::set< V > &targets, size_t n_goals=(std::numeric_limits< size_t >::max)())
DAG 1 source to many targets.
std::deque< Path > get_paths (const G &graph, V source, std::set< V > &targets, bool only_cost) const
Private Attributes
members
std::vector< V > predecessors
std::vector< double > distances
std::deque< V > nodesInDistance
std::ostringstream log
Detailed Description
template<class G>
class pgrouting::Pgr_dag< G >
Definition at line 56 of file dagShortestPath.hpp.
Member Typedef Documentation
E
template<class G > typedef G::E pgrouting::Pgr_dag< G >::E
Definition at line 59 of file dagShortestPath.hpp.
V
template<class G > typedef G::V pgrouting::Pgr_dag< G >::V
Definition at line 58 of file dagShortestPath.hpp.
Member Function Documentation
clear()
template<class G > void pgrouting::Pgr_dag< G >::clear () inline private
Definition at line 152 of file dagShortestPath.hpp.
                  {
         predecessors.clear();
         distances.clear();
         nodesInDistance.clear();
     }
References pgrouting::Pgr_dag< G >::distances, pgrouting::Pgr_dag< G >::nodesInDistance, and pgrouting::Pgr_dag< G >::predecessors.
Referenced by pgrouting::Pgr_dag< G >::dag().
dag() [1/2]
template<class G > std::deque< Path > pgrouting::Pgr_dag< G >::dag (G & graph, const std::map< int64_t, std::set< int64_t > > & combinations, bool only_cost) inline
combinations
Definition at line 103 of file dagShortestPath.hpp.
{
         std::deque<Path> paths;
         for (const auto &c : combinations) {
             auto result_paths = dag(graph, c.first, c.second, only_cost);
             paths.insert(
                     paths.end(),
                     std::make_move_iterator(result_paths.begin()),
                     std::make_move_iterator(result_paths.end()));
         }
         return paths;
     }
References pgrouting::Pgr_dag< G >::dag().
dag() [2/2]
template<class G > std::deque< Path > pgrouting::Pgr_dag< G >::dag (G & graph, int64_t start_vertex, const std::set< int64_t > & end_vertex, bool only_cost) inline
dag 1 to many
Definition at line 63 of file dagShortestPath.hpp.
{
         std::deque<Path> paths;
         /* precondition */
         if (!graph.has_vertex(start_vertex)) return paths;
         /* adjust predecessors and distances vectors */
         clear();
         size_t n_goals = (std::numeric_limits<size_t>::max)();
         predecessors.resize(graph.num_vertices());
         distances.resize(
                 graph.num_vertices(),
                 std::numeric_limits<double>::infinity());
         auto v_source(graph.get_V(start_vertex));
         std::set<V> v_targets;
         for (const auto &vertex : end_vertex) {
             if (graph.has_vertex(vertex)) v_targets.insert(graph.get_V(vertex));
         }
         if (v_targets.empty()) return paths;
         dag_1_to_many(graph, v_source, v_targets, n_goals);
         paths = get_paths(graph, v_source, v_targets, only_cost);
         std::stable_sort(paths.begin(), paths.end(),
                 [](const Path &e1, const Path &e2)->bool {
                 return e1.end_id() < e2.end_id();
                 });
         return paths;
     }
References pgrouting::Pgr_dag< G >::clear(), pgrouting::Pgr_dag< G >::dag_1_to_many(), pgrouting::Pgr_dag< G >::distances, pgrouting::Pgr_dag< G >::get_paths(), and pgrouting::Pgr_dag< G >::predecessors.
Referenced by pgrouting::Pgr_dag< G >::dag(), and anonymous_namespace{dagShortestPath_driver.cpp}::pgr_dagShortestPath().
dag_1_to_many()
template<class G > bool pgrouting::Pgr_dag< G >::dag_1_to_many (G & graph, V source, const std::set< V > & targets, size_t n_goals = (std::numeric_limits<size_t>::max)()) inline private
DAG 1 source to many targets.
Definition at line 124 of file dagShortestPath.hpp.
{
         CHECK_FOR_INTERRUPTS();
         try {
             boost::dag_shortest_paths(graph.graph, source,
                     boost::predecessor_map(&predecessors[0])
                     .weight_map(get(&G::G_T_E::cost, graph.graph))
                     .distance_map(&distances[0])
                     .distance_inf(std::numeric_limits<double>::infinity())
                     .visitor(dijkstra_many_goal_visitor(targets, n_goals)));
         } catch(found_goals &) {
             return true;
         } catch (boost::exception const& ex) {
             (void)ex;
             throw;
         } catch (std::exception &e) {
             (void)e;
             throw;
         } catch (...) {
             throw;
         }
         return true;
     }
References CHECK_FOR_INTERRUPTS, pgrouting::Pgr_dag< G >::distances, and pgrouting::Pgr_dag< G >::predecessors.
Referenced by pgrouting::Pgr_dag< G >::dag().
get_paths()
template<class G > std::deque< Path > pgrouting::Pgr_dag< G >::get_paths (const G & graph, V source, std::set< V > & targets, bool only_cost) const inline private
Definition at line 162 of file dagShortestPath.hpp.
{
         std::deque<Path> paths;
         for (const auto target : targets) {
             paths.push_back(Path(
                         graph,
                         source, target,
                         predecessors, distances,
                         only_cost, true));
         }
         return paths;
     }
References pgrouting::Pgr_dag< G >::distances, and pgrouting::Pgr_dag< G >::predecessors.
Referenced by pgrouting::Pgr_dag< G >::dag().
Member Data Documentation
distances
template<class G > std::vector< double > pgrouting::Pgr_dag< G >::distances private
Definition at line 184 of file dagShortestPath.hpp.
Referenced by pgrouting::Pgr_dag< G >::clear(), pgrouting::Pgr_dag< G >::dag(), pgrouting::Pgr_dag< G >::dag_1_to_many(), and pgrouting::Pgr_dag< G >::get_paths().
log
template<class G > std::ostringstream pgrouting::Pgr_dag< G >::log private
Definition at line 186 of file dagShortestPath.hpp.
nodesInDistance
template<class G > std::deque< V > pgrouting::Pgr_dag< G >::nodesInDistance private
Definition at line 185 of file dagShortestPath.hpp.
Referenced by pgrouting::Pgr_dag< G >::clear().
predecessors
template<class G > std::vector< V > pgrouting::Pgr_dag< G >::predecessors private
Definition at line 183 of file dagShortestPath.hpp.
Referenced by pgrouting::Pgr_dag< G >::clear(), pgrouting::Pgr_dag< G >::dag(), pgrouting::Pgr_dag< G >::dag_1_to_many(), and pgrouting::Pgr_dag< G >::get_paths().
The documentation for this class was generated from the following file:
dagShortestPath.hpp