PGROUTING: Pgr_dag< G > Class Template Reference
Pgr_dag< G > Class Template Reference
#include "pgr_dagShortestPath.hpp"
Classes
class dijkstra_many_goal_visitor
class for stopping when all targets are found
class dijkstra_one_goal_visitor
class for stopping when 1 target is found
struct found_goals
Public Types
typedef G::E E
typedef G::V V
Public Member Functions
std::deque< Path > dag (G &graph, const std::vector< int64_t > &start_vertex, const std::vector< int64_t > &end_vertex, bool only_cost)
std::deque< Path > dag (G &graph, const std::vector< int64_t > &start_vertex, int64_t end_vertex, bool only_cost)
std::deque< Path > dag (G &graph, int64_t start_vertex, const std::vector< int64_t > &end_vertex, bool only_cost)
Dijkstra 1 to many.
Path dag (G &graph, int64_t start_vertex, int64_t end_vertex, bool only_cost=false)
Dijkstra 1 to 1.
Private Member Functions
void clear ()
bool dag_1_to_1 (G &graph, V source, V target)
Call to Dijkstra 1 source to 1 target.
bool dag_1_to_many (G &graph, V source, const std::vector< V > &targets, size_t n_goals=(std::numeric_limits< size_t >::max)())
Dijkstra 1 source to many targets.
std::deque< Path > get_paths (const G &graph, V source, std::vector< V > &targets, bool only_cost) const
Private Attributes
members
std::vector< V > predecessors
std::vector< double > distances
std::deque< V > nodesInDistance
std::ostringstream log
Detailed Description
template<class G>
class Pgr_dag< G >
Definition at line 52 of file pgr_dagShortestPath.hpp.
Member Typedef Documentation
E
template<class G > typedef G::E Pgr_dag< G >::E
Definition at line 55 of file pgr_dagShortestPath.hpp.
V
template<class G > typedef G::V Pgr_dag< G >::V
Definition at line 54 of file pgr_dagShortestPath.hpp.
Member Function Documentation
clear()
template<class G > void Pgr_dag< G >::clear () inline private
Definition at line 246 of file pgr_dagShortestPath.hpp.
                   {
          predecessors.clear();
          distances.clear();
          nodesInDistance.clear();
      }
References Pgr_dag< G >::distances, Pgr_dag< G >::nodesInDistance, and Pgr_dag< G >::predecessors.
Referenced by Pgr_dag< G >::dag().
dag() [1/4]
template<class G > std::deque<Path> Pgr_dag< G >::dag (G & graph, const std::vector< int64_t > & start_vertex, const std::vector< int64_t > & end_vertex, bool only_cost) inline
Definition at line 159 of file pgr_dagShortestPath.hpp.
{
          // a call to 1 to many is faster for each of the sources
          std::deque<Path> paths;
          for (const auto &start : start_vertex) {
              auto r_paths = dag(
                      graph,
                      start, end_vertex,
                      only_cost);
              paths.insert(paths.begin(), r_paths.begin(), r_paths.end());
          }
          std::sort(paths.begin(), paths.end(),
                  [](const Path &e1, const Path &e2)->bool {
                  return e1.end_id() < e2.end_id();
                  });
          std::stable_sort(paths.begin(), paths.end(),
                  [](const Path &e1, const Path &e2)->bool {
                  return e1.start_id() < e2.start_id();
                  });
          return paths;
      }
References Pgr_dag< G >::dag().
dag() [2/4]
template<class G > std::deque<Path> Pgr_dag< G >::dag (G & graph, const std::vector< int64_t > & start_vertex, int64_t end_vertex, bool only_cost) inline
Definition at line 138 of file pgr_dagShortestPath.hpp.
{
          std::deque<Path> paths;
          for (const auto &start : start_vertex) {
              paths.push_back(
                      dag(graph, start, end_vertex, only_cost));
          }
          std::stable_sort(paths.begin(), paths.end(),
                  [](const Path &e1, const Path &e2)->bool {
                  return e1.start_id() < e2.start_id();
                  });
          return paths;
      }
References Pgr_dag< G >::dag().
dag() [3/4]
template<class G > std::deque<Path> Pgr_dag< G >::dag (G & graph, int64_t start_vertex, const std::vector< int64_t > & end_vertex, bool only_cost) inline
Dijkstra 1 to many.
Definition at line 95 of file pgr_dagShortestPath.hpp.
{
          // adjust predecessors and distances vectors
          clear();
          size_t n_goals = (std::numeric_limits<size_t>::max)();
          predecessors.resize(graph.num_vertices());
          distances.resize(
                  graph.num_vertices(),
                  std::numeric_limits<double>::infinity());
          // get the graphs source and target
          if (!graph.has_vertex(start_vertex))
              return std::deque<Path>();
          auto v_source(graph.get_V(start_vertex));
          std::set< V > s_v_targets;
          for (const auto &vertex : end_vertex) {
              if (graph.has_vertex(vertex)) {
                  s_v_targets.insert(graph.get_V(vertex));
              }
          }
          std::vector< V > v_targets(s_v_targets.begin(), s_v_targets.end());
          // perform the algorithm
          dag_1_to_many(graph, v_source, v_targets, n_goals);
          std::deque< Path > paths;
          // get the results // route id are the targets
          paths = get_paths(graph, v_source, v_targets, only_cost);
          std::stable_sort(paths.begin(), paths.end(),
                  [](const Path &e1, const Path &e2)->bool {
                  return e1.end_id() < e2.end_id();
                  });
          return paths;
      }
References Pgr_dag< G >::clear(), Pgr_dag< G >::dag_1_to_many(), Pgr_dag< G >::distances, Pgr_dag< G >::get_paths(), and Pgr_dag< G >::predecessors.
dag() [4/4]
template<class G > Path Pgr_dag< G >::dag (G & graph, int64_t start_vertex, int64_t end_vertex, bool only_cost = false) inline
Dijkstra 1 to 1.
Definition at line 59 of file pgr_dagShortestPath.hpp.
{
          clear();
          // adjust predecessors and distances vectors
          predecessors.resize(graph.num_vertices());
          distances.resize(
                  graph.num_vertices(),
                  std::numeric_limits<double>::infinity());
          if (!graph.has_vertex(start_vertex)
                  || !graph.has_vertex(end_vertex)) {
              return Path(start_vertex, end_vertex);
          }
          // get the graphs source and target
          auto v_source(graph.get_V(start_vertex));
          auto v_target(graph.get_V(end_vertex));
          // perform the algorithm
          dag_1_to_1(graph, v_source, v_target);
          // get the results
          return Path(
                  graph,
                  v_source, v_target,
                  predecessors, distances,
                  only_cost, true);
      }
References Pgr_dag< G >::clear(), Pgr_dag< G >::dag_1_to_1(), Pgr_dag< G >::distances, and Pgr_dag< G >::predecessors.
Referenced by Pgr_dag< G >::dag(), and pgr_dagShortestPath().
dag_1_to_1()
template<class G > bool Pgr_dag< G >::dag_1_to_1 (G & graph, V source, V target) inline private
Call to Dijkstra 1 source to 1 target.
Definition at line 190 of file pgr_dagShortestPath.hpp.
{
          /* abort in case of an interruption occurs (e.g. the query is being cancelled) */
          CHECK_FOR_INTERRUPTS();
          try {
              boost::dag_shortest_paths(graph.graph, source,
                      boost::predecessor_map(&predecessors[0])
                      .weight_map(get(&G::G_T_E::cost, graph.graph))
                      .distance_map(&distances[0])
                      .visitor(dijkstra_one_goal_visitor(target)));
          } catch(found_goals &) {
              return true;
          } catch (boost::exception const& ex) {
              (void)ex;
              throw;
          } catch (std::exception &e) {
              (void)e;
              throw;
          } catch (...) {
              throw;
          }
          return true;
      }
References Pgr_dag< G >::distances, and Pgr_dag< G >::predecessors.
Referenced by Pgr_dag< G >::dag().
dag_1_to_many()
template<class G > bool Pgr_dag< G >::dag_1_to_many (G & graph, V source, const std::vector< V > & targets, size_t n_goals = (std::numeric_limits<size_t>::max)()) inline private
Dijkstra 1 source to many targets.
Definition at line 217 of file pgr_dagShortestPath.hpp.
{
          /* abort in case of an interruption occurs (e.g. the query is being cancelled) */
          CHECK_FOR_INTERRUPTS();
          try {
              boost::dag_shortest_paths(graph.graph, source,
                      boost::predecessor_map(&predecessors[0])
                      .weight_map(get(&G::G_T_E::cost, graph.graph))
                      .distance_map(&distances[0])
                      .distance_inf(std::numeric_limits<double>::infinity())
                      .visitor(dijkstra_many_goal_visitor(targets, n_goals)));
          } catch(found_goals &) {
              return true;
          } catch (boost::exception const& ex) {
              (void)ex;
              throw;
          } catch (std::exception &e) {
              (void)e;
              throw;
          } catch (...) {
              throw;
          }
          return true;
      }
References Pgr_dag< G >::distances, and Pgr_dag< G >::predecessors.
Referenced by Pgr_dag< G >::dag().
get_paths()
template<class G > std::deque<Path> Pgr_dag< G >::get_paths (const G & graph, V source, std::vector< V > & targets, bool only_cost) const inline private
Definition at line 256 of file pgr_dagShortestPath.hpp.
{
          std::deque<Path> paths;
          for (const auto target : targets) {
              paths.push_back(Path(
                          graph,
                          source, target,
                          predecessors, distances,
                          only_cost, true));
          }
          return paths;
      }
References Pgr_dag< G >::distances, and Pgr_dag< G >::predecessors.
Referenced by Pgr_dag< G >::dag().
Member Data Documentation
distances
template<class G > std::vector< double > Pgr_dag< G >::distances private
Definition at line 278 of file pgr_dagShortestPath.hpp.
Referenced by Pgr_dag< G >::clear(), Pgr_dag< G >::dag(), Pgr_dag< G >::dag_1_to_1(), Pgr_dag< G >::dag_1_to_many(), and Pgr_dag< G >::get_paths().
log
template<class G > std::ostringstream Pgr_dag< G >::log private
Definition at line 280 of file pgr_dagShortestPath.hpp.
nodesInDistance
template<class G > std::deque< V > Pgr_dag< G >::nodesInDistance private
Definition at line 279 of file pgr_dagShortestPath.hpp.
Referenced by Pgr_dag< G >::clear().
predecessors
template<class G > std::vector< V > Pgr_dag< G >::predecessors private
Definition at line 277 of file pgr_dagShortestPath.hpp.
Referenced by Pgr_dag< G >::clear(), Pgr_dag< G >::dag(), Pgr_dag< G >::dag_1_to_1(), Pgr_dag< G >::dag_1_to_many(), and Pgr_dag< G >::get_paths().
The documentation for this class was generated from the following file:
pgr_dagShortestPath.hpp