PGROUTING: pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed > Class Template Reference
pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed > Class Template Reference
#include "lineGraphFull.hpp"
Public Types
typedef boost::graph_traits< G >::edge_descriptor E
typedef boost::graph_traits< G >::edge_iterator E_i
typedef boost::graph_traits< G >::in_edge_iterator EI_i
typedef boost::graph_traits< G >::out_edge_iterator EO_i
typedef boost::graph_traits< G >::vertex_descriptor V
typedef boost::graph_traits< G >::vertex_iterator V_i
Graph related types
Type boost meaning pgRouting meaning
G boost::adjacency_list Graph
V vertex_descriptor Think of it as local ID of a vertex
E edge_descriptor Think of it as local ID of an edge
V_i vertex_iterator To cycle the vertices of the Graph
E_i edge_iterator To cycle the edges of the Graph
EO_i out_edge_iterator To cycle the out going edges of a vertex
EI_i in_edge_iterator To cycle the in coming edges of a vertex (only in bidirectional graphs)
using B_G = G
using G_T_E = T_E
using G_T_V = T_V
using vertices_size_type = typename boost::graph_traits< G >::vertices_size_type
using edges_size_type = typename boost::graph_traits< G >::edges_size_type
using degree_size_type = typename boost::graph_traits< G >::degree_size_type
using vertex_index_t = typename boost::property_map< G, boost::vertex_index_t >::type
Other types
Type Meaning pgRouting Meaning
IndexMap maps V -> id given a V store the id
id_to_V maps id -> V given an id store the V
using IndexMap = std::map< V, size_t >
using id_to_V = typename std::map< int64_t, V >
Public Member Functions
Pgr_lineGraphFull ()
Pgr_lineGraphFull (const pgrouting::DirectedGraph &digraph)
std::vector< Line_graph_full_rt > get_postgres_results_directed ()
Edges inserters
template<typename T >
void insert_edges_neg (const std::vector< T > &edges)
template<typename T >
void insert_edges (const std::vector< T > &edges, bool normal=true)
Inserts count edges of type Edge_t into the graph The set of edges should not have an illegal vertex defined When the graph is empty calls:
template<typename T >
void insert_min_edges_no_parallel (const std::vector< T > &edges)
template<typename T >
void insert_negative_edges (const std::vector< T > &edges, bool normal=true)
in & out degree
degree_size_type out_degree (int64_t vertex_id) const
get the out-degree of a vertex
degree_size_type out_degree (V &v) const
out degree of a vertex
degree_size_type in_degree (int64_t vertex_id) const
degree_size_type in_degree (V &v) const
in degree of a vertex
Get vertex descriptor
V get_V (const T_V &vertex)
get the vertex descriptor of the vertex When the vertex does not exist
V get_V (int64_t vid) const
get the vertex descriptor of the vid Call has_vertex(vid) before calling this function
V source (E e) const
get source edge
V target (E e) const
get source edge
V adjacent (V v, E e) const
get source edge
to be or not to be
bool has_vertex (int64_t vid) const
does vertex exist in the graph?
bool is_directed () const
is the graph directed?
bool is_undirected () const
is the graph undirected?
bool is_source (V v, E e) const
is v a source in the edge?
bool is_target (V v, E e) const
is v a target in the edge?
get original edge/vertex data
T_E & operator[] (E e)
get the edge
const T_E & operator[] (E e) const
get the edge
T_V & operator[] (V v)
get the vertex
const T_V & operator[] (V v) const
get the vertex
int64_t get_edge_id (V from, V to, double &weight) const
get the edge id of from–to with the indicated distance
Get edge descriptor
E get_edge (V from, V to, double &distance) const
How big
size_t num_vertices () const
size_t num_edges () const
Public Attributes
std::ostringstream log
Private Member Functions
void apply_transformation (const pgrouting::DirectedGraph &digraph)
template<typename T >
void graph_add_edge (int64_t _id, const T &source, const T &target, int64_t source_in_edge, int64_t source_out_edge)
template<typename T >
void graph_add_min_edge_no_parallel (const T &edge)
template<typename T >
void graph_add_neg_edge (const T &edge, bool normal=true)
Add edges with negative cost(either cost or reverse_cost or both) Reading them into graph as positive cost (edge_cost = (-1)* edge_negative_cost) [L931 & L941] To Do: Read and apply edges with negative cost in function as it is.
void insert_vertex (int64_t original_vertex_id, int64_t original_edge_id)
void store_edge_costs (const pgrouting::DirectedGraph &digraph)
Private Attributes
std::map< int64_t, double > m_edge_costs
int64_t m_num_edges
std::map< int64_t, std::pair< int64_t, int64_t > > m_transformation_map
std::map< std::pair< int64_t, int64_t >, int64_t > m_vertex_map
Id mapping handling
vertex_index_t vertIndex
IndexMap mapIndex
boost::associative_property_map< IndexMap > propmapIndex
Graph Modification
std::deque< T_E > removed_edges
Used for storing the removed_edges.
Friends
std::ostream & operator<< (std::ostream &log, const Pgr_lineGraphFull< G, T_V, T_E, t_directed > &g)
The Graph
bool m_is_directed
type (DIRECTED or UNDIRECTED)
G graph
The graph.
id_to_V vertices_map
id -> graph id
edge disconnection/reconnection
void disconnect_edge (int64_t p_from, int64_t p_to)
Disconnects all edges from p_from to p_to.
void disconnect_out_going_edge (int64_t vid, int64_t eid)
Disconnects the outgoing edges of a vertex.
void disconnect_vertex (int64_t vid)
Disconnects all incoming and outgoing edges from vertex.
void disconnect_vertex (V v)
Disconnects all incoming and outgoing edges from the vertex.
void restore_graph ()
Reconnects all edges that were removed.
void restore_edge (const T_E &edge)
T_E get_edge_info (const E &e) const
Detailed Description
template<class G, typename T_V, typename T_E, bool t_directed>
class pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >
Definition at line 49 of file lineGraphFull.hpp.
Member Typedef Documentation
B_G
template<typename G , typename T_V , typename T_E , bool t_directed> using pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::B_G = G inherited
Definition at line 230 of file base_graph.hpp.
degree_size_type
template<typename G , typename T_V , typename T_E , bool t_directed> using pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::degree_size_type = typename boost::graph_traits<G>::degree_size_type inherited
Definition at line 242 of file base_graph.hpp.
E
template<class G , typename T_V , typename T_E , bool t_directed> typedef boost::graph_traits<G>::edge_descriptor pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::E
Definition at line 52 of file lineGraphFull.hpp.
E_i
template<class G , typename T_V , typename T_E , bool t_directed> typedef boost::graph_traits<G>::edge_iterator pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::E_i
Definition at line 54 of file lineGraphFull.hpp.
edges_size_type
template<typename G , typename T_V , typename T_E , bool t_directed> using pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::edges_size_type = typename boost::graph_traits<G>::edges_size_type inherited
Definition at line 241 of file base_graph.hpp.
EI_i
template<class G , typename T_V , typename T_E , bool t_directed> typedef boost::graph_traits<G>::in_edge_iterator pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::EI_i
Definition at line 56 of file lineGraphFull.hpp.
EO_i
template<class G , typename T_V , typename T_E , bool t_directed> typedef boost::graph_traits<G>::out_edge_iterator pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::EO_i
Definition at line 55 of file lineGraphFull.hpp.
G_T_E
template<typename G , typename T_V , typename T_E , bool t_directed> using pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::G_T_E = T_E inherited
Definition at line 231 of file base_graph.hpp.
G_T_V
template<typename G , typename T_V , typename T_E , bool t_directed> using pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::G_T_V = T_V inherited
Definition at line 232 of file base_graph.hpp.
id_to_V
template<typename G , typename T_V , typename T_E , bool t_directed> using pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::id_to_V = typename std::map<int64_t, V> inherited
Definition at line 256 of file base_graph.hpp.
IndexMap
template<typename G , typename T_V , typename T_E , bool t_directed> using pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::IndexMap = std::map<V, size_t> inherited
Definition at line 255 of file base_graph.hpp.
V
template<class G , typename T_V , typename T_E , bool t_directed> typedef boost::graph_traits<G>::vertex_descriptor pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::V
Definition at line 51 of file lineGraphFull.hpp.
V_i
template<class G , typename T_V , typename T_E , bool t_directed> typedef boost::graph_traits<G>::vertex_iterator pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::V_i
Definition at line 53 of file lineGraphFull.hpp.
vertex_index_t
template<typename G , typename T_V , typename T_E , bool t_directed> using pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::vertex_index_t = typename boost::property_map<G, boost::vertex_index_t>::type inherited
Definition at line 243 of file base_graph.hpp.
vertices_size_type
template<typename G , typename T_V , typename T_E , bool t_directed> using pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::vertices_size_type = typename boost::graph_traits<G>::vertices_size_type inherited
Definition at line 240 of file base_graph.hpp.
Constructor & Destructor Documentation
Pgr_lineGraphFull() [1/2]
template<class G , typename T_V , typename T_E , bool t_directed> pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::Pgr_lineGraphFull () inline explicit
Definition at line 59 of file lineGraphFull.hpp.
        : Pgr_base_graph<G, T_V, T_E, t_directed>(),
        m_num_edges(0) {
        }
Pgr_lineGraphFull() [2/2]
template<class G , typename T_V , typename T_E , bool t_directed> pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::Pgr_lineGraphFull (const pgrouting::DirectedGraph & digraph) inline explicit
Definition at line 64 of file lineGraphFull.hpp.
        : Pgr_base_graph<G, T_V, T_E, t_directed>() {
            apply_transformation(digraph);
            store_edge_costs(digraph);
        }
References pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::apply_transformation(), and pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::store_edge_costs().
Member Function Documentation
adjacent()
template<typename G , typename T_V , typename T_E , bool t_directed> V pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::adjacent (V v, E e) const inline inherited
get source edge
Parameters
[in] v vertex descriptor
[in] e edge descriptor
Returns
V vertex descriptor
Definition at line 442 of file base_graph.hpp.
{
         pgassert(is_source(v, e) || is_target(v, e));
         return is_source(v, e)? target(e) : source(e);
     }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::is_source(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::is_target(), pgassert, pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::source(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::target().
apply_transformation()
template<class G , typename T_V , typename T_E , bool t_directed> void pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::apply_transformation (const pgrouting::DirectedGraph & digraph) inline private
Definition at line 226 of file lineGraphFull.hpp.
{
        V_i vertexIt, vertexEnd;
        EO_i e_outIt, e_outEnd;
        EI_i e_inIt, e_inEnd;
        // For every vertex in the original graph, create a line graph
        // using the edges connected to that vertex
        for (boost::tie(vertexIt, vertexEnd) = boost::vertices(digraph.graph);
                vertexIt != vertexEnd; vertexIt++) {
            V vertex = *vertexIt;
            auto vertex_id = digraph[vertex].id;
            for (boost::tie(e_outIt, e_outEnd) =
                    boost::out_edges(vertex, digraph.graph);
                    e_outIt != e_outEnd; e_outIt++) {
                auto out_edge_id = digraph.graph[*e_outIt].id;
                insert_vertex(vertex_id, out_edge_id);
            }
            for (boost::tie(e_inIt, e_inEnd) =
                    boost::in_edges(vertex, digraph.graph);
                    e_inIt != e_inEnd; e_inIt++) {
                auto in_edge_id = digraph.graph[*e_inIt].id;
                insert_vertex(vertex_id, in_edge_id);
                for (boost::tie(e_outIt, e_outEnd) =
                        boost::out_edges(vertex, digraph.graph);
                        e_outIt != e_outEnd; e_outIt++) {
                    auto out_edge_id = digraph.graph[*e_outIt].id;
                    ++m_num_edges;
                    graph_add_edge(
                            m_num_edges,
                            vertex_id,
                            vertex_id,
                            in_edge_id,
                            out_edge_id);
                }
            }
        }
        // Connect all of the line graphs that were just created using the
        // edges from the original graph
        for (boost::tie(vertexIt, vertexEnd) =
                boost::vertices(digraph.graph);
                vertexIt != vertexEnd; vertexIt++) {
            V vertex = *vertexIt;
            auto vertex_id = digraph[vertex].id;
            for (boost::tie(e_inIt, e_inEnd) =
                    boost::in_edges(vertex, digraph.graph);
                    e_inIt != e_inEnd; e_inIt++) {
                auto source_vertex_id = digraph[digraph.source(*e_inIt)].id;
                auto in_edge_id = digraph.graph[*e_inIt].id;
                ++m_num_edges;
                graph_add_edge(
                        m_num_edges,
                        source_vertex_id,
                        vertex_id,
                        in_edge_id,
                        in_edge_id);
            }
        }
    }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph, pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::graph_add_edge(), pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::insert_vertex(), pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::m_num_edges, and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::source().
Referenced by pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::Pgr_lineGraphFull().
disconnect_edge()
template<typename G , typename T_V , typename T_E , bool t_directed> void pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::disconnect_edge (int64_t p_from, int64_t p_to) inline inherited
Disconnects all edges from p_from to p_to.
No edge is disconnected if the vertices id's do not exist in the graph
All removed edges are stored for future reinsertion
All parallel edges are disconnected (automatically by boost)
Parameters
[in] p_from vertex identifier of the starting point of the edge
[in] p_to vertex identifier of the ending point of the edge
Definition at line 614 of file base_graph.hpp.
{
         /* nothing to do, a vertex doesn't exist */
         if (!has_vertex(p_from) || !has_vertex(p_to)) return;
         EO_i out, out_end;
         auto u(get_V(p_from));
         auto v(get_V(p_to));
         for (boost::tie(out, out_end) = out_edges(u, graph); out != out_end; ++out) {
             if (target(*out) == v) {
                 removed_edges.push_back(get_edge_info(*out));
                 break;
             }
         }
         boost::remove_edge(u, v, graph);
     }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_edge_info(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_V(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph, pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::has_vertex(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::removed_edges, and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::target().
disconnect_out_going_edge()
template<typename G , typename T_V , typename T_E , bool t_directed> void pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::disconnect_out_going_edge (int64_t vid, int64_t eid) inline inherited
Disconnects the outgoing edges of a vertex.
No edge is disconnected if it doesn't exist in the graph
Removed edges are stored for future reinsertion
all outgoing edges with the edge_id are removed if they exist
Parameters
[in] vid original vertex
[in] eid original edge_id
Definition at line 639 of file base_graph.hpp.
{
         /* nothing to do, the vertex doesn't exist */
         if (!has_vertex(vid)) return;
         auto v(get_V(vid));
         EO_i out, out_end;
         bool change = true;
         while (change) {
             change = false;
             for (boost::tie(out, out_end) = out_edges(v, graph); out != out_end; ++out) {
                 if (graph[*out].id  == eid) {
                     removed_edges.push_back(get_edge_info(*out));
                     boost::remove_edge((*out), graph);
                     change = true;
                     break;
                 }
             }
         }
     }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_edge_info(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_V(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph, pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::has_vertex(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::removed_edges.
disconnect_vertex() [1/2]
template<typename G , typename T_V , typename T_E , bool t_directed> void pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::disconnect_vertex (int64_t vid) inline inherited
Disconnects all incoming and outgoing edges from vertex.
Parameters
[in] vid vertex identifier
Definition at line 662 of file base_graph.hpp.
{
         if (!has_vertex(vid)) return;
         disconnect_vertex(get_V(vid));
     }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::disconnect_vertex(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_V(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::has_vertex().
Referenced by pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::disconnect_vertex().
disconnect_vertex() [2/2]
template<typename G , typename T_V , typename T_E , bool t_directed> void pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::disconnect_vertex (V v) inline inherited
Disconnects all incoming and outgoing edges from the vertex.
boost::graph doesn't recommend th to insert/remove vertices, so a vertex removal is simulated by disconnecting the vertex from the graph
No edge is disconnected if the vertices id's do not exist in the graph
All removed edges are stored for future reinsertion
All parallel edges are disconnected (automatically by boost)
Parameters
[in] v vertex descriptor
Definition at line 678 of file base_graph.hpp.
{
         EO_i out, out_end;
         for (boost::tie(out, out_end) = out_edges(v, graph); out != out_end; ++out) {
                     removed_edges.push_back(get_edge_info(*out));
         }
         /* special case */
         if (m_is_directed) {
             EI_i in, in_end;
             for (boost::tie(in, in_end) = in_edges(v, graph); in != in_end; ++in) {
                     removed_edges.push_back(get_edge_info(*in));
             }
         }
         /* delete incoming and outgoing edges from the vertex */
         boost::clear_vertex(v, graph);
     }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_edge_info(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph, pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::m_is_directed, and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::removed_edges.
get_edge()
template<typename G , typename T_V , typename T_E , bool t_directed> E pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_edge (V from, V to, double & distance) const inline inherited
Definition at line 567 of file base_graph.hpp.
{
         E e;
         EO_i out_i, out_end;
         V v_source, v_target;
         double minCost =  (std::numeric_limits<double>::max)();
         E minEdge;
         bool valid = false;
         for (boost::tie(out_i, out_end) = boost::out_edges(from, graph);
                 out_i != out_end; ++out_i) {
             e = *out_i;
             if (!valid) {
                 minEdge = e;
                 valid = true;
             }
             v_target = target(e);
             v_source = source(e);
             if ((from == v_source) && (to == v_target)
                     && (distance == graph[e].cost)) {
                 return e;
             }
             if ((from == v_source) && (to == v_target)
                     && (minCost > graph[e].cost)) {
                 minCost = graph[e].cost;
                 minEdge = e;
             }
         }
         return minEdge;
     }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph, pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::source(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::target().
get_edge_id()
template<typename G , typename T_V , typename T_E , bool t_directed> int64_t pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_edge_id (V from, V to, double & weight) const inline inherited
get the edge id of from–to with the indicated distance
Parameters
[in] from vertex descriptor
[in] to vertex descriptor
[in] weight edge's weight to match when several options are found
Returns
The edge identifier of edge from–to with weight
OR the edge identifier of edge from–to with min weight
Definition at line 519 of file base_graph.hpp.
{
         EO_i out_i, out_end;
         double minCost =  (std::numeric_limits<double>::max)();
         int64_t minEdge = -1;
         for (boost::tie(out_i, out_end) = boost::out_edges(from, graph); out_i != out_end; ++out_i) {
             auto e = *out_i;
             auto v_target = target(e);
             auto v_source = source(e);
             if ((from == v_source) && (to == v_target) && (weight == graph[e].cost)) return graph[e].id;
             if ((from == v_source) && (to == v_target) && (minCost > graph[e].cost)) {
                 minCost = graph[e].cost;
                 minEdge = graph[e].id;
             }
         }
         weight = minEdge == -1? 0: minCost;
         return minEdge;
     }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph, pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::source(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::target().
get_edge_info()
template<typename G , typename T_V , typename T_E , bool t_directed> T_E pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_edge_info (const E & e) const inline private inherited
Definition at line 722 of file base_graph.hpp.
{
         T_E d_edge;
         d_edge.id = graph[e].id;
         d_edge.source = graph[source(e)].id;
         d_edge.target = graph[target(e)].id;
         d_edge.cost = graph[e].cost;
         return d_edge;
     }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph, pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::source(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::target().
Referenced by pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::disconnect_edge(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::disconnect_out_going_edge(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::disconnect_vertex().
get_postgres_results_directed()
template<class G , typename T_V , typename T_E , bool t_directed> std::vector< Line_graph_full_rt > pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::get_postgres_results_directed () inline
Definition at line 91 of file lineGraphFull.hpp.
{
            std::vector< Line_graph_full_rt > results;
            typename boost::graph_traits < G >::edge_iterator edgeIt, edgeEnd;
            std::map <
                std::pair<int64_t, int64_t >,
                Line_graph_full_rt > unique;
            auto count = 0;
            auto vertex_count = 0;
            std::map < int64_t, int64_t > vertex_id_map;
            std::map < int64_t, int64_t > vertex_id_reverse_map;
            log << "\nPostgres results\n";
            for (boost::tie(edgeIt, edgeEnd) = boost::edges(this->graph);
                    edgeIt != edgeEnd; edgeIt++) {
                E e = *edgeIt;
                auto e_source = this->graph[this->source(e)].vertex_id;
                auto e_target = this->graph[this->target(e)].vertex_id;
                auto target_vertex_edge_pair = m_transformation_map[e_target];
                auto target_vertex_id = target_vertex_edge_pair.first;
                auto target_edge_id = target_vertex_edge_pair.second;
                auto source_vertex_edge_pair = m_transformation_map[e_source];
                auto source_vertex_id = source_vertex_edge_pair.first;
                auto source_edge_id = source_vertex_edge_pair.second;
                int64_t edge_id = 0;
                auto e_cost = 0.0;
                if (source_edge_id == target_edge_id) {
                    e_cost = m_edge_costs[source_edge_id];
                    edge_id = source_edge_id;
                }
                if (vertex_id_map.find(e_source) == vertex_id_map.end()) {
                    if (vertex_id_reverse_map.find(source_vertex_id) ==
                      vertex_id_reverse_map.end()) {
                        vertex_id_map[e_source] = source_vertex_id;
                        vertex_id_reverse_map[source_vertex_id] = e_source;
                    } else {
                        --vertex_count;
                        vertex_id_map[e_source] = vertex_count;
                        vertex_id_reverse_map[vertex_count] = e_source;
                    }
                }
                if (vertex_id_map.find(e_target) == vertex_id_map.end()) {
                    if (vertex_id_reverse_map.find(target_vertex_id) ==
                      vertex_id_reverse_map.end()) {
                        vertex_id_map[e_target] = target_vertex_id;
                        vertex_id_reverse_map[target_vertex_id] = e_target;
                    } else {
                        --vertex_count;
                        vertex_id_map[e_target] = vertex_count;
                        vertex_id_reverse_map[vertex_count] = e_target;
                    }
                }
                Line_graph_full_rt edge = {
                    ++count,
                    vertex_id_map[e_source],
                    vertex_id_map[e_target],
                    e_cost,
                    edge_id
                };
                unique[ std::pair<int64_t, int64_t>(e_source, e_target) ] =
                    edge;
            }
            for (const auto &edge : unique) {
                results.push_back(edge.second);
            }
            return results;
        }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph, pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::log, pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::m_edge_costs, pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::m_transformation_map, pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::source(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::target().
Referenced by pgr_do_lineGraphFull().
get_V() [1/2]
template<typename G , typename T_V , typename T_E , bool t_directed> V pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_V (const T_V & vertex) inline inherited
get the vertex descriptor of the vertex When the vertex does not exist
creates a new vertex
Returns
V: The vertex descriptor of the vertex
Definition at line 403 of file base_graph.hpp.
{
         auto vm_s(vertices_map.find(vertex.id));
         if (vm_s == vertices_map.end()) {
             auto v =  add_vertex(graph);
             graph[v].cp_members(vertex);
             vertices_map[vertex.id] =  v;
             put(propmapIndex, v, num_vertices());
             return v;
         }
         return vm_s->second;
     }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph, pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::num_vertices(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::propmapIndex, and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::vertices_map.
Referenced by pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::disconnect_edge(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::disconnect_out_going_edge(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::disconnect_vertex(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph_add_edge(), pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::graph_add_edge(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph_add_min_edge_no_parallel(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph_add_neg_edge(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::in_degree(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::out_degree(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::restore_edge().
get_V() [2/2]
template<typename G , typename T_V , typename T_E , bool t_directed> V pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_V (int64_t vid) const inline inherited
get the vertex descriptor of the vid Call has_vertex(vid) before calling this function
Parameters
[in] vid vertex identifier
Returns
V: The vertex descriptor of the vertex
Definition at line 420 of file base_graph.hpp.
{
         if (!has_vertex(vid)) throw std::string("Call to ") + __PRETTY_FUNCTION__ + "without checking with has_vertex";
         return vertices_map.find(vid)->second;
     }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::has_vertex(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::vertices_map.
graph_add_edge()
template<class G , typename T_V , typename T_E , bool t_directed> template<typename T > void pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::graph_add_edge (int64_t _id, const T & source, const T & target, int64_t source_in_edge, int64_t source_out_edge) inline private
Definition at line 191 of file lineGraphFull.hpp.
{
            bool inserted;
            E e;
            pgassert(m_vertex_map.find({source, source_in_edge}) !=
                    m_vertex_map.end());
            pgassert(m_vertex_map.find({target, source_out_edge}) !=
                    m_vertex_map.end());
            auto index_source_edge =
                m_vertex_map[ std::pair<int64_t, int64_t>(source,
                                                          source_in_edge) ];
            auto index_target_edge =
                m_vertex_map[ std::pair<int64_t, int64_t>(target,
                                                          source_out_edge) ];
            auto vm_s = this->get_V(index_source_edge);
            auto vm_t = this->get_V(index_target_edge);
            pgassert(this->vertices_map.find(index_source_edge) !=
                    this->vertices_map.end());
            pgassert(this->vertices_map.find(index_target_edge) !=
                    this->vertices_map.end());
            boost::tie(e, inserted) =
                boost::add_edge(vm_s, vm_t, this->graph);
            this->graph[e].id = _id;
        }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_V(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph, pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::m_vertex_map, pgassert, pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::source(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::target(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::vertices_map.
Referenced by pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::apply_transformation().
graph_add_min_edge_no_parallel()
template<typename G , typename T_V , typename T_E , bool t_directed> template<typename T > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph_add_min_edge_no_parallel (const T & edge) inline private inherited
Definition at line 763 of file base_graph.hpp.
{
         bool inserted;
         E e;
         if ((edge.cost < 0) && (edge.reverse_cost < 0)) return;
         /*
          * true: for source
          * false: for target
          */
         auto vm_s = get_V(T_V(edge, true));
         auto vm_t = get_V(T_V(edge, false));
         pgassert(vertices_map.find(edge.source) != vertices_map.end());
         pgassert(vertices_map.find(edge.target) != vertices_map.end());
         if (edge.cost >= 0) {
             E e1;
             bool found;
             boost::tie(e1, found) = boost::edge(vm_s, vm_t, graph);
             if (found) {
                 if (edge.cost < graph[e1].cost) {
                     graph[e1].cost = edge.cost;
                     graph[e1].id = edge.id;
                 }
             } else {
                 boost::tie(e, inserted) = boost::add_edge(vm_s, vm_t, graph);
                 graph[e].cost = edge.cost;
                 graph[e].id = edge.id;
             }
         }
         if (edge.reverse_cost >= 0
                 && (m_is_directed || (!m_is_directed && edge.cost != edge.reverse_cost))) {
             E e1;
             bool found;
             boost::tie(e1, found) = boost::edge(vm_t, vm_s, graph);
             if (found) {
                 if (edge.reverse_cost < graph[e1].cost) {
                     graph[e1].cost = edge.reverse_cost;
                     graph[e1].id = edge.id;
                 }
             } else {
                 boost::tie(e, inserted) =
                     boost::add_edge(vm_t, vm_s, graph);
                 graph[e].cost = edge.reverse_cost;
                 graph[e].id = edge.id;
             }
         }
     }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_V(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph, pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::m_is_directed, pgassert, and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::vertices_map.
Referenced by pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::insert_min_edges_no_parallel().
graph_add_neg_edge()
template<typename G , typename T_V , typename T_E , bool t_directed> template<typename T > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph_add_neg_edge (const T & edge, bool normal = true) inline private inherited
Add edges with negative cost(either cost or reverse_cost or both) Reading them into graph as positive cost (edge_cost = (-1)* edge_negative_cost) [L931 & L941] To Do: Read and apply edges with negative cost in function as it is.
Definition at line 818 of file base_graph.hpp.
{
         bool inserted;
         E e;
         auto vm_s = get_V(T_V(edge, true));
         auto vm_t = get_V(T_V(edge, false));
         pgassert(vertices_map.find(edge.source) != vertices_map.end());
         pgassert(vertices_map.find(edge.target) != vertices_map.end());
         boost::tie(e, inserted) = boost::add_edge(vm_s, vm_t, graph);
         if (edge.cost < 0) {
             /* reading negative edges as positive */
             graph[e].cost = (-0.5)*edge.cost;
         } else {
             graph[e].cost = edge.cost;
         }
         graph[e].id = edge.id;
         if (m_is_directed
                 || (!m_is_directed && edge.cost > edge.reverse_cost)) {
             boost::tie(e, inserted) =
                 boost::add_edge(vm_t, vm_s, graph);
             if (edge.reverse_cost < 0) {
                 /* reading negative edges as positive */
                 graph[e].cost = (-0.5)*edge.reverse_cost;
             } else {
                 graph[e].cost = edge.reverse_cost;
             }
             graph[e].id = normal? edge.id : -edge.id;
         }
     }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_V(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph, pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::m_is_directed, pgassert, and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::vertices_map.
Referenced by pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::insert_negative_edges().
has_vertex()
template<typename G , typename T_V , typename T_E , bool t_directed> bool pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::has_vertex (int64_t vid) const inline inherited
does vertex exist in the graph?
Parameters
[in] vid vertex identifier
Returns
true: when vid is in the graph
false: when vid is not in the graph
Definition at line 456 of file base_graph.hpp.
{
         return vertices_map.find(vid) != vertices_map.end();
     }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::vertices_map.
Referenced by pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::disconnect_edge(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::disconnect_out_going_edge(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::disconnect_vertex(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_V(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::in_degree(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::out_degree().
in_degree() [1/2]
template<typename G , typename T_V , typename T_E , bool t_directed> degree_size_type pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::in_degree (int64_t vertex_id) const inline inherited
Definition at line 363 of file base_graph.hpp.
{
         if (!has_vertex(vertex_id)) {
             return 0;
         }
         return is_directed()?
             in_degree(get_V(vertex_id))
             :  out_degree(get_V(vertex_id));
     }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_V(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::has_vertex(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::in_degree(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::is_directed(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::out_degree().
Referenced by pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::in_degree().
in_degree() [2/2]
template<typename G , typename T_V , typename T_E , bool t_directed> degree_size_type pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::in_degree (V & v) const inline inherited
in degree of a vertex
when its undirected there is no "concept" of in degree
out degree is returned
on directed in degree of vertex is returned
Parameters
[in] v vertex descriptor
Definition at line 379 of file base_graph.hpp.
{
         return is_directed()?
             boost::in_degree(v, graph) :
             boost::out_degree(v, graph);
     }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph, and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::is_directed().
insert_edges()
template<typename G , typename T_V , typename T_E , bool t_directed> template<typename T > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::insert_edges (const std::vector< T > & edges, bool normal = true) inline inherited
Inserts count edges of type Edge_t into the graph The set of edges should not have an illegal vertex defined When the graph is empty calls:
extract_vertices and throws an exception if there are illegal vertices. When developing:
if an illegal vertex is found an exception is thrown
That means that the set of vertices should be checked in the code that is being developed No edge is inserted when there is an error on the vertices
Parameters
edges
normal
Definition at line 328 of file base_graph.hpp.
{
         for (const auto &edge : edges) {
             graph_add_edge(edge, normal);
         }
     }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph_add_edge().
Referenced by do_allpairs(), do_metrics(), do_shortestPath(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::insert_edges_neg(), pgr_do_articulationPoints(), pgr_do_astar(), pgr_do_bdAstar(), pgr_do_bdDijkstra(), pgr_do_bellman_ford(), pgr_do_bellman_ford_neg(), pgr_do_betweennessCentrality(), pgr_do_biconnectedComponents(), pgr_do_binaryBreadthFirstSearch(), pgr_do_bipartite(), pgr_do_boyerMyrvold(), pgr_do_breadthFirstSearch(), pgr_do_bridges(), pgr_do_connectedComponents(), pgr_do_cuthillMckeeOrdering(), pgr_do_dagShortestPath(), pgr_do_depthFirstSearch(), pgr_do_dijkstra(), pgr_do_dijkstraVia(), pgr_do_drivingDistance(), pgr_do_edwardMoore(), pgr_do_hawickCircuits(), pgr_do_isPlanar(), pgr_do_kruskal(), pgr_do_ksp(), pgr_do_lineGraph(), pgr_do_LTDTree(), pgr_do_makeConnected(), pgr_do_randomSpanningTree(), pgr_do_sequentialVertexColoring(), pgr_do_stoerWagner(), pgr_do_strongComponents(), pgr_do_topologicalSort(), pgr_do_transitiveClosure(), pgr_do_trsp(), pgr_do_trsp_withPoints(), pgr_do_trspVia(), pgr_do_trspVia_withPoints(), pgr_do_turnRestrictedPath(), pgr_do_withPoints(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), and pgr_do_withPointsVia().
insert_edges_neg()
template<typename G , typename T_V , typename T_E , bool t_directed> template<typename T > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::insert_edges_neg (const std::vector< T > & edges) inline inherited
Definition at line 309 of file base_graph.hpp.
{
         insert_edges(edges, false);
     }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::insert_edges().
Referenced by pgr_do_lineGraphFull().
insert_min_edges_no_parallel()
template<typename G , typename T_V , typename T_E , bool t_directed> template<typename T > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::insert_min_edges_no_parallel (const std::vector< T > & edges) inline inherited
Definition at line 335 of file base_graph.hpp.
{
         for (const auto edge : edges) {
             graph_add_min_edge_no_parallel(edge);
         }
     }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph_add_min_edge_no_parallel().
Referenced by pgr_do_prim().
insert_negative_edges()
template<typename G , typename T_V , typename T_E , bool t_directed> template<typename T > void pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::insert_negative_edges (const std::vector< T > & edges, bool normal = true) inline inherited
Definition at line 341 of file base_graph.hpp.
{
         for (const auto edge : edges) {
             graph_add_neg_edge(edge, normal);
         }
     }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph_add_neg_edge().
Referenced by pgr_do_bellman_ford_neg().
insert_vertex()
template<class G , typename T_V , typename T_E , bool t_directed> void pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::insert_vertex (int64_t original_vertex_id, int64_t original_edge_id) inline private
Definition at line 166 of file lineGraphFull.hpp.
{
        auto new_id = static_cast<int64_t>(this->num_vertices() + 1);
        m_transformation_map[new_id] =
            std::pair<int64_t, int64_t>(original_vertex_id, original_edge_id);
        m_vertex_map[std::pair<int64_t, int64_t>(original_vertex_id,
                                                 original_edge_id)] =
            new_id;
        auto v =  add_vertex(this->graph);
        this->graph[v].cp_members(original_vertex_id, original_edge_id);
        this->graph[v].vertex_id = new_id;
        this->vertices_map[new_id] = v;
    }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph, pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::m_transformation_map, pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::m_vertex_map, pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::num_vertices(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::vertices_map.
Referenced by pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::apply_transformation().
is_directed()
template<typename G , typename T_V , typename T_E , bool t_directed> bool pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::is_directed () const inline inherited
is the graph directed?
Returns
true: when the graph is directed
false: when the graph is not directed
Definition at line 463 of file base_graph.hpp.
{return m_is_directed;}
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::m_is_directed.
Referenced by pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::in_degree(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::in_degree().
is_source()
template<typename G , typename T_V , typename T_E , bool t_directed> bool pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::is_source (V v, E e) const inline inherited
is v a source in the edge?
Parameters
[in] v vertex descriptor
[in] e edge descriptor
Returns
true: when v is source on the edge
false: when v is not source on the edge
Definition at line 475 of file base_graph.hpp.
{return v == source(e);}
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::source().
Referenced by pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::adjacent().
is_target()
template<typename G , typename T_V , typename T_E , bool t_directed> bool pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::is_target (V v, E e) const inline inherited
is v a target in the edge?
Parameters
[in] v vertex descriptor
[in] e edge descriptor
Returns
true: when v is target on the edge
false: when v is not target on the edge
Definition at line 482 of file base_graph.hpp.
{return v == target(e);}
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::target().
Referenced by pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::adjacent().
is_undirected()
template<typename G , typename T_V , typename T_E , bool t_directed> bool pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::is_undirected () const inline inherited
is the graph undirected?
Returns
true: when the graph is undirected
false: when the graph is not undirected
Definition at line 468 of file base_graph.hpp.
{return !m_is_directed;}
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::m_is_directed.
num_edges()
template<typename G , typename T_V , typename T_E , bool t_directed> size_t pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::num_edges () const inline inherited
Definition at line 600 of file base_graph.hpp.
{ return boost::num_edges(graph);}
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph.
num_vertices()
template<typename G , typename T_V , typename T_E , bool t_directed> size_t pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::num_vertices () const inline inherited
Definition at line 599 of file base_graph.hpp.
{ return boost::num_vertices(graph);}
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph.
Referenced by pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_V(), and pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::insert_vertex().
operator[]() [1/4]
template<typename G , typename T_V , typename T_E , bool t_directed> T_E & pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::operator[] (E e) inline inherited
get the edge
Parameters
[in] e edge descriptor
Returns
The edge information (allows modification)
Definition at line 492 of file base_graph.hpp.
{return graph[e];}
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph.
operator[]() [2/4]
template<typename G , typename T_V , typename T_E , bool t_directed> const T_E & pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::operator[] (E e) const inline inherited
get the edge
Parameters
[in] e edge descriptor
Returns
The edge information (does not allow modification)
Definition at line 498 of file base_graph.hpp.
{return graph[e];}
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph.
operator[]() [3/4]
template<typename G , typename T_V , typename T_E , bool t_directed> T_V & pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::operator[] (V v) inline inherited
get the vertex
Parameters
[in] v vertex descriptor
Returns
The vertex information (allows modification)
Definition at line 504 of file base_graph.hpp.
{return graph[v];}
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph.
operator[]() [4/4]
template<typename G , typename T_V , typename T_E , bool t_directed> const T_V & pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::operator[] (V v) const inline inherited
get the vertex
Parameters
[in] v vertex descriptor
Returns
The vertex information (does not allow modification)
Definition at line 510 of file base_graph.hpp.
{return graph[v];}
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph.
out_degree() [1/2]
template<typename G , typename T_V , typename T_E , bool t_directed> degree_size_type pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::out_degree (int64_t vertex_id) const inline inherited
get the out-degree of a vertex
Returns
0: The out degree of a vertex that its not in the graph
Parameters
[in] vertex_id original vertex id
Definition at line 354 of file base_graph.hpp.
{
         if (!has_vertex(vertex_id)) {
             return 0;
         }
         auto v = get_V(vertex_id);
         auto d = out_degree(v);
         return d;
     }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_V(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::has_vertex(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::out_degree().
Referenced by pgrouting::algorithms::bridges(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::in_degree(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::out_degree().
out_degree() [2/2]
template<typename G , typename T_V , typename T_E , bool t_directed> degree_size_type pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::out_degree (V & v) const inline inherited
out degree of a vertex
regardless of undirected or directed graph
out degree is returned
Definition at line 390 of file base_graph.hpp.
{
         return boost::out_degree(v, graph);
     }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph.
restore_edge()
template<typename G , typename T_V , typename T_E , bool t_directed> void pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::restore_edge (const T_E & edge) inline private inherited
Definition at line 706 of file base_graph.hpp.
{
         E e;
         auto u = get_V(edge.source);
         auto v = get_V(edge.target);
         if (edge.cost >= 0) {
             bool inserted;
             boost::tie(e, inserted) = boost::add_edge(u, v, graph);
             graph[e].cp_members(edge);
         }
     }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_V(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph.
Referenced by pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::restore_graph().
restore_graph()
template<typename G , typename T_V , typename T_E , bool t_directed> void pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::restore_graph () inline inherited
Reconnects all edges that were removed.
Definition at line 698 of file base_graph.hpp.
{
             while (removed_edges.size() != 0) {
                 restore_edge(removed_edges[0]);
                 removed_edges.pop_front();
             }
         }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::removed_edges, and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::restore_edge().
source()
template<typename G , typename T_V , typename T_E , bool t_directed> V pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::source (E e) const inline inherited
get source edge
Parameters
[in] e edge descriptor
Returns
V vertex descriptor
Definition at line 429 of file base_graph.hpp.
{return boost::source(e, graph);}
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph.
Referenced by pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::adjacent(), pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::apply_transformation(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_edge(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_edge_id(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_edge_info(), pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::get_postgres_results_directed(), pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::graph_add_edge(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::is_source().
store_edge_costs()
template<class G , typename T_V , typename T_E , bool t_directed> void pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::store_edge_costs (const pgrouting::DirectedGraph & digraph) inline private
Definition at line 181 of file lineGraphFull.hpp.
{
        E_i e_It, e_End;
        for (boost::tie(e_It, e_End) = boost::edges(digraph.graph);
            e_It != e_End; e_It++) {
            m_edge_costs[digraph.graph[*e_It].id] = digraph.graph[*e_It].cost;
        }
    }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph, and pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::m_edge_costs.
Referenced by pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::Pgr_lineGraphFull().
target()
template<typename G , typename T_V , typename T_E , bool t_directed> V pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::target (E e) const inline inherited
get source edge
Parameters
[in] e edge descriptor
Returns
V vertex descriptor
Definition at line 435 of file base_graph.hpp.
{return boost::target(e, graph);}
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph.
Referenced by pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::adjacent(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::disconnect_edge(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_edge(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_edge_id(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_edge_info(), pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::get_postgres_results_directed(), pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::graph_add_edge(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::is_target().
Friends And Related Symbol Documentation
operator<<
template<class G , typename T_V , typename T_E , bool t_directed> std::ostream & operator<< (std::ostream & log, const Pgr_lineGraphFull< G, T_V, T_E, t_directed > & g) friend
Definition at line 70 of file lineGraphFull.hpp.
{
        typename Pgr_base_graph<G, T_V, T_E, t_directed>::EO_i out, out_end;
        for (auto vi = vertices(g.graph).first;
                vi != vertices(g.graph).second; ++vi) {
            if ((*vi) >= g.num_vertices()) break;
            log << (*vi) << ": " << " out_edges_of(" << g.graph[(*vi)] << "):";
            for (boost::tie(out, out_end) = out_edges(*vi, g.graph);
                    out != out_end; ++out) {
                log << ' '
                    << g.graph[*out].id << "=("
                    << g[g.source(*out)].id << ", "
                    << g[g.target(*out)].id << ")\t";
            }
            log << std::endl;
        }
        return log;
    }
Member Data Documentation
graph
template<typename G , typename T_V , typename T_E , bool t_directed> G pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph inherited
The graph.
Definition at line 855 of file base_graph.hpp.
Referenced by pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::Pgr_base_graph(), pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::apply_transformation(), pgrouting::algorithms::articulationPoints(), pgrouting::algorithms::biconnectedComponents(), pgrouting::algorithms::bridges(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::disconnect_edge(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::disconnect_out_going_edge(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::disconnect_vertex(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_edge(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_edge_id(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_edge_info(), pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::get_postgres_results_directed(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_V(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph_add_edge(), pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::graph_add_edge(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph_add_min_edge_no_parallel(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph_add_neg_edge(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::in_degree(), pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::insert_vertex(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::num_edges(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::num_vertices(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::operator[](), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::operator[](), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::operator[](), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::operator[](), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::out_degree(), pgrouting::algorithms::pgr_connectedComponents(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::restore_edge(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::source(), pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::store_edge_costs(), pgrouting::algorithms::strongComponents(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::target().
log
template<class G , typename T_V , typename T_E , bool t_directed> std::ostringstream pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::log
Definition at line 301 of file lineGraphFull.hpp.
Referenced by pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::get_postgres_results_directed(), and pgr_do_lineGraphFull().
m_edge_costs
template<class G , typename T_V , typename T_E , bool t_directed> std::map< int64_t, double > pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::m_edge_costs private
Definition at line 296 of file lineGraphFull.hpp.
Referenced by pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::get_postgres_results_directed(), and pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::store_edge_costs().
m_is_directed
template<typename G , typename T_V , typename T_E , bool t_directed> bool pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::m_is_directed private inherited
type (DIRECTED or UNDIRECTED)
Definition at line 859 of file base_graph.hpp.
Referenced by pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::disconnect_vertex(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph_add_edge(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph_add_min_edge_no_parallel(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph_add_neg_edge(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::is_directed(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::is_undirected().
m_num_edges
template<class G , typename T_V , typename T_E , bool t_directed> int64_t pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::m_num_edges private
Definition at line 295 of file lineGraphFull.hpp.
Referenced by pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::apply_transformation().
m_transformation_map
template<class G , typename T_V , typename T_E , bool t_directed> std::map< int64_t, std::pair< int64_t, int64_t > > pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::m_transformation_map private
Definition at line 297 of file lineGraphFull.hpp.
Referenced by pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::get_postgres_results_directed(), and pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::insert_vertex().
m_vertex_map
template<class G , typename T_V , typename T_E , bool t_directed> std::map< std::pair< int64_t, int64_t >, int64_t > pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::m_vertex_map private
Definition at line 298 of file lineGraphFull.hpp.
Referenced by pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::graph_add_edge(), and pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::insert_vertex().
mapIndex
template<typename G , typename T_V , typename T_E , bool t_directed> IndexMap pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::mapIndex private inherited
Definition at line 865 of file base_graph.hpp.
propmapIndex
template<typename G , typename T_V , typename T_E , bool t_directed> boost::associative_property_map<IndexMap> pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::propmapIndex private inherited
Definition at line 866 of file base_graph.hpp.
Referenced by pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_V().
removed_edges
template<typename G , typename T_V , typename T_E , bool t_directed> std::deque<T_E> pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::removed_edges private inherited
Used for storing the removed_edges.
Definition at line 872 of file base_graph.hpp.
Referenced by pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::disconnect_edge(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::disconnect_out_going_edge(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::disconnect_vertex(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::restore_graph().
vertices_map
template<typename G , typename T_V , typename T_E , bool t_directed> id_to_V pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::vertices_map inherited
id -> graph id
Definition at line 856 of file base_graph.hpp.
Referenced by pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::Pgr_base_graph(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_V(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::get_V(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph_add_edge(), pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::graph_add_edge(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph_add_min_edge_no_parallel(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph_add_neg_edge(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::has_vertex(), and pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::insert_vertex().
vertIndex
template<typename G , typename T_V , typename T_E , bool t_directed> vertex_index_t pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::vertIndex private inherited
Definition at line 864 of file base_graph.hpp.
Referenced by pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::Pgr_base_graph().
The documentation for this class was generated from the following file:
lineGraphFull.hpp