PGROUTING: pgrouting::graph::UndirectedHasCostBG Class Reference
pgrouting::graph::UndirectedHasCostBG Class Reference
#include "undirectedHasCostBG.hpp"
Public Types
using E = boost::graph_traits< TSP_Graph >::edge_descriptor
using E_it = boost::graph_traits< TSP_Graph >::edge_iterator
using Eout_it = boost::graph_traits< TSP_Graph >::out_edge_iterator
using TSP_Graph = boost::adjacency_list< boost::vecS, boost::vecS, boost::undirectedS, boost::property< boost::vertex_index_t, int >, boost::property< boost::edge_weight_t, double >, boost::no_property >
using V = boost::graph_traits< TSP_Graph >::vertex_descriptor
using V_it = boost::graph_traits< TSP_Graph >::vertex_iterator
Public Member Functions
UndirectedHasCostBG ()=delete
UndirectedHasCostBG (const std::vector< Coordinate_t > &)
The postgres user might inadvertently give duplicate points with the same id the approximation is quite right, for example 1, 3.5, 1 1, 3.499999999999 0.9999999 the approximation is quite wrong, for example 2 , 3.5 1 2 , 3.6 1 but when the remove_duplicates flag is on, keep only the first row that has the same id.
UndirectedHasCostBG (std::vector< IID_t_rt > &)
V get_boost_vertex (int64_t id) const
int64_t get_edge_id (E e) const
int64_t get_vertex_id (V v) const
TSP_Graph & graph ()
const TSP_Graph & graph () const
bool has_vertex (int64_t id) const
void insert_vertex (int64_t id)
Private Attributes
std::map< E, int64_t > m_E_to_id
TSP_Graph m_graph
std::map< int64_t, V > m_id_to_V
std::map< V, int64_t > m_V_to_id
Detailed Description
Definition at line 47 of file undirectedHasCostBG.hpp.
Member Typedef Documentation
E
using pgrouting::graph::UndirectedHasCostBG::E = boost::graph_traits<TSP_Graph>::edge_descriptor
Definition at line 56 of file undirectedHasCostBG.hpp.
E_it
using pgrouting::graph::UndirectedHasCostBG::E_it = boost::graph_traits<TSP_Graph>::edge_iterator
Definition at line 58 of file undirectedHasCostBG.hpp.
Eout_it
using pgrouting::graph::UndirectedHasCostBG::Eout_it = boost::graph_traits<TSP_Graph>::out_edge_iterator
Definition at line 59 of file undirectedHasCostBG.hpp.
TSP_Graph
using pgrouting::graph::UndirectedHasCostBG::TSP_Graph = boost::adjacency_list<boost::vecS, boost::vecS, boost::undirectedS, boost::property<boost::vertex_index_t, int>, boost::property<boost::edge_weight_t, double>, boost::no_property>
Definition at line 49 of file undirectedHasCostBG.hpp.
V
using pgrouting::graph::UndirectedHasCostBG::V = boost::graph_traits<TSP_Graph>::vertex_descriptor
Definition at line 55 of file undirectedHasCostBG.hpp.
V_it
using pgrouting::graph::UndirectedHasCostBG::V_it = boost::graph_traits<TSP_Graph>::vertex_iterator
Definition at line 57 of file undirectedHasCostBG.hpp.
Constructor & Destructor Documentation
UndirectedHasCostBG() [1/3]
pgrouting::graph::UndirectedHasCostBG::UndirectedHasCostBG (std::vector< IID_t_rt > & distances) explicit
Definition at line 45 of file undirectedHasCostBG.cpp.
{
    /*
     * Inserting vertices
     */
    Identifiers<int64_t> ids;
    for (auto &d : distances) {
        ids += d.from_vid;
        ids += d.to_vid;
        /*
         * Its undirected graph:
         * keeping from_vid < to_vid
         */
        if (d.to_vid > d.from_vid) {
            std::swap(d.to_vid, d.from_vid);
        }
    }
    for (const auto &id : ids) {
        insert_vertex(id);
    }
    /*
     * Inserting edges
     */
    for (const auto &edge : distances) {
        /*
         * skip loops
         */
        if (edge.from_vid == edge.to_vid) continue;
        /*
         * skip negative costs
         */
        if (edge.cost < 0) continue;
        auto v1 = get_boost_vertex(edge.from_vid);
        auto v2 = get_boost_vertex(edge.to_vid);
        auto e_exists = boost::edge(v1, v2, m_graph);
        if (e_exists.second) {
            auto weight = get(boost::edge_weight_t(), m_graph, e_exists.first);
            /*
             * skip duplicated edges with less cost
             */
            if (weight < edge.cost) continue;
            if (edge.cost < weight) {
                /*
                 * substitute edge with new lesser cost found
                 */
                boost::put(boost::edge_weight_t(), m_graph, e_exists.first, edge.cost);
            }
            continue;
        }
        auto add_result = boost::add_edge(v1, v2, edge.cost, m_graph);
        if (!add_result.second) {
            throw std::make_pair(
                    std::string("INTERNAL: something went wrong adding and edge\n"),
                    std::string(__PGR_PRETTY_FUNCTION__));
        }
    }
}
References __PGR_PRETTY_FUNCTION__, get_boost_vertex(), insert_vertex(), and m_graph.
UndirectedHasCostBG() [2/3]
pgrouting::graph::UndirectedHasCostBG::UndirectedHasCostBG (const std::vector< Coordinate_t > & coordinates) explicit
The postgres user might inadvertently give duplicate points with the same id the approximation is quite right, for example 1, 3.5, 1 1, 3.499999999999 0.9999999 the approximation is quite wrong, for example 2 , 3.5 1 2 , 3.6 1 but when the remove_duplicates flag is on, keep only the first row that has the same id.
Definition at line 118 of file undirectedHasCostBG.cpp.
{
    /*
     * Inserting edges
     */
    for (size_t i = 0; i < coordinates.size(); ++i) {
        insert_vertex(coordinates[i].id);
        auto u = get_boost_vertex(coordinates[i].id);
        auto ux = coordinates[i].x;
        auto uy = coordinates[i].y;
        /*
         *  undirected, so only need traverse higher coordinates for connections
         */
        for (size_t j = i + 1; j < coordinates.size(); ++j) {
            insert_vertex(coordinates[j].id);
            auto v = get_boost_vertex(coordinates[j].id);
            /*
             * ignoring duplicated coordinates
             */
            if (boost::edge(u, v, m_graph).second) continue;
            auto vx = coordinates[j].x;
            auto vy = coordinates[j].y;
            auto const dx = ux - vx;
            auto const dy = uy - vy;
            /*
             * weight is euclidean distance
             */
            auto add_result = boost::add_edge(u, v, sqrt(dx * dx + dy * dy), m_graph);
            if (!add_result.second) {
                throw std::make_pair(
                        std::string("INTERNAL: something went wrong adding and edge\n"),
                        std::string(__PGR_PRETTY_FUNCTION__));
            }
        }
    }
}
References __PGR_PRETTY_FUNCTION__, get_boost_vertex(), insert_vertex(), and m_graph.
UndirectedHasCostBG() [3/3]
pgrouting::graph::UndirectedHasCostBG::UndirectedHasCostBG () delete
Member Function Documentation
get_boost_vertex()
UndirectedHasCostBG::V pgrouting::graph::UndirectedHasCostBG::get_boost_vertex (int64_t id) const
Definition at line 180 of file undirectedHasCostBG.cpp.
{
    try {
        return m_id_to_V.at(id);
    } catch (...) {
        throw std::make_pair(
                std::string("INTERNAL: something went wrong when getting the vertex descriptor"),
                std::string(__PGR_PRETTY_FUNCTION__));
    }
}
References __PGR_PRETTY_FUNCTION__, and m_id_to_V.
Referenced by UndirectedHasCostBG(), UndirectedHasCostBG(), anonymous_namespace{tsp.cpp}::do_tsp(), anonymous_namespace{tsp.cpp}::eval_tour(), and anonymous_namespace{tsp.cpp}::tsp().
get_edge_id()
int64_t pgrouting::graph::UndirectedHasCostBG::get_edge_id (E e) const
Definition at line 202 of file undirectedHasCostBG.cpp.
{
    try {
        return m_E_to_id.at(e);
    } catch (...) {
        throw std::make_pair(
                std::string("INTERNAL: something went wrong when getting the edge id"),
                std::string(__PGR_PRETTY_FUNCTION__));
    }
}
References __PGR_PRETTY_FUNCTION__, and m_E_to_id.
get_vertex_id()
int64_t pgrouting::graph::UndirectedHasCostBG::get_vertex_id (V v) const
Definition at line 191 of file undirectedHasCostBG.cpp.
{
    try {
        return m_V_to_id.at(v);
    } catch (...) {
        throw std::make_pair(
                std::string("INTERNAL: something went wrong when getting the vertex id"),
                std::string(__PGR_PRETTY_FUNCTION__));
    }
}
References __PGR_PRETTY_FUNCTION__, and m_V_to_id.
Referenced by anonymous_namespace{tsp.cpp}::eval_tour().
graph() [1/2]
TSP_Graph & pgrouting::graph::UndirectedHasCostBG::graph () inline
Definition at line 69 of file undirectedHasCostBG.hpp.
{return m_graph;}
References m_graph.
graph() [2/2]
const TSP_Graph & pgrouting::graph::UndirectedHasCostBG::graph () const inline
Definition at line 68 of file undirectedHasCostBG.hpp.
{return m_graph;}
References m_graph.
Referenced by anonymous_namespace{tsp.cpp}::do_tsp(), anonymous_namespace{tsp.cpp}::eval_tour(), anonymous_namespace{tsp.cpp}::eval_tour(), anonymous_namespace{tsp.cpp}::get_min_cost(), anonymous_namespace{tsp.cpp}::tsp(), and anonymous_namespace{tsp.cpp}::tsp().
has_vertex()
bool pgrouting::graph::UndirectedHasCostBG::has_vertex (int64_t id) const
Definition at line 161 of file undirectedHasCostBG.cpp.
{
    return m_id_to_V.find(id) != m_id_to_V.end();
}
References m_id_to_V.
Referenced by anonymous_namespace{tsp.cpp}::do_tsp(), insert_vertex(), and anonymous_namespace{tsp.cpp}::tsp().
insert_vertex()
void pgrouting::graph::UndirectedHasCostBG::insert_vertex (int64_t id)
Definition at line 166 of file undirectedHasCostBG.cpp.
{
    try {
        if (has_vertex(id)) return;
        auto v = add_vertex(m_id_to_V.size(), m_graph);
        m_id_to_V.insert(std::make_pair(id, v));
        m_V_to_id.insert(std::make_pair(v, id));
    } catch (...) {
        throw std::make_pair(
                std::string("INTERNAL: something went wrong when inserting a vertex"),
                std::string(__PGR_PRETTY_FUNCTION__));
    }
}
References __PGR_PRETTY_FUNCTION__, has_vertex(), m_graph, m_id_to_V, and m_V_to_id.
Referenced by UndirectedHasCostBG(), UndirectedHasCostBG(), and anonymous_namespace{tsp.cpp}::do_tsp().
Member Data Documentation
m_E_to_id
std::map<E, int64_t> pgrouting::graph::UndirectedHasCostBG::m_E_to_id private
Definition at line 81 of file undirectedHasCostBG.hpp.
Referenced by get_edge_id().
m_graph
TSP_Graph pgrouting::graph::UndirectedHasCostBG::m_graph private
Definition at line 78 of file undirectedHasCostBG.hpp.
Referenced by UndirectedHasCostBG(), UndirectedHasCostBG(), graph(), graph(), and insert_vertex().
m_id_to_V
std::map<int64_t, V> pgrouting::graph::UndirectedHasCostBG::m_id_to_V private
Definition at line 79 of file undirectedHasCostBG.hpp.
Referenced by get_boost_vertex(), has_vertex(), and insert_vertex().
m_V_to_id
std::map<V, int64_t> pgrouting::graph::UndirectedHasCostBG::m_V_to_id private
Definition at line 80 of file undirectedHasCostBG.hpp.
Referenced by get_vertex_id(), and insert_vertex().
The documentation for this class was generated from the following files:
undirectedHasCostBG.hpp
undirectedHasCostBG.cpp