PGROUTING: pgrouting::vrp::Initial_solution Class Reference
pgrouting::vrp::Initial_solution Class Reference
#include "initial_solution.h"
Public Member Functions
Initial_solution (Initials_code kind, size_t)
Vehicle::Cost cost () const
std::string cost_str () const
int cvTot () const
double duration () const
size_t fleet_size () const
Initials_code get_kind () const
std::vector< General_vehicle_orders_t > get_postgres_result () const
void invariant () const
bool is_feasable () const
bool operator< (const Solution &s_rhs) const
void sort_by_id ()
std::string tau (const std::string &title="Tau") const
double total_service_time () const
double total_travel_time () const
int twvTot () const
double wait_time () const
Static Public Attributes
static Pgr_messages msg
Protected Attributes
double EPSILON
std::deque< Vehicle_pickDeliver > fleet
Fleet trucks
Static Protected Attributes
static Pgr_pickDeliver * problem
Private Member Functions
void do_while_foo (int kind)
void one_truck_all_orders ()
Private Attributes
Identifiers< size_t > all_orders
Identifiers< size_t > assigned
Identifiers< size_t > unassigned
Detailed Description
Definition at line 46 of file initial_solution.h.
Constructor & Destructor Documentation
Initial_solution()
pgrouting::vrp::Initial_solution::Initial_solution (Initials_code kind, size_t number_of_orders)
Definition at line 46 of file initial_solution.cpp.
                                  :
     Solution(),
     all_orders(number_of_orders),
     unassigned(number_of_orders),
     assigned() {
         invariant();
         pgassert(kind >= 0 && kind <= OneDepot);
         switch (kind) {
             case OneTruck:
                 one_truck_all_orders();
                 break;
             case OnePerTruck:
             case FrontTruck:
             case BackTruck:
             case BestInsert:
             case BestBack:
             case BestFront:
             case OneDepot:
                 do_while_foo(kind);
                 break;
             default: pgassert(false);
         }
     invariant();
 }
References pgrouting::vrp::BackTruck, pgrouting::vrp::BestBack, pgrouting::vrp::BestFront, pgrouting::vrp::BestInsert, do_while_foo(), pgrouting::vrp::FrontTruck, invariant(), one_truck_all_orders(), pgrouting::vrp::OneDepot, pgrouting::vrp::OnePerTruck, pgrouting::vrp::OneTruck, and pgassert.
Member Function Documentation
cost()
Vehicle::Cost pgrouting::vrp::Solution::cost () const inherited
Definition at line 119 of file solution.cpp.
                      {
     double total_duration(0);
     double total_wait_time(0);
     int total_twv(0);
     int total_cv(0);
     for (const auto &v : fleet) {
         total_duration += v.duration();
         total_wait_time += v.total_wait_time();
         total_twv += v.twvTot();
         total_cv += v.cvTot();
     }
     return std::make_tuple(
             total_twv, total_cv, fleet.size(),
             total_wait_time, total_duration);
 }
References pgrouting::vrp::Solution::fleet.
Referenced by pgrouting::vrp::Solution::cost_str(), and pgrouting::vrp::Solution::operator<().
cost_str()
std::string pgrouting::vrp::Solution::cost_str () const inherited
Definition at line 138 of file solution.cpp.
{
     Vehicle::Cost s_cost(cost());
     std::ostringstream log;
     log << "(twv, cv, fleet, wait, duration) = ("
         << std::get<0>(s_cost) << ", "
         << std::get<1>(s_cost) << ", "
         << std::get<2>(s_cost) << ", "
         << std::get<3>(s_cost) << ", "
         << std::get<4>(s_cost) << ")";
     return log.str();
 }
References pgrouting::vrp::Solution::cost().
Referenced by pgrouting::vrp::Optimize::save_if_best(), and pgrouting::vrp::Solution::tau().
cvTot()
int pgrouting::vrp::Solution::cvTot () const inherited
Definition at line 110 of file solution.cpp.
                       {
     int total(0);
     for (const auto &v : fleet) {
         total += v.cvTot();
     }
     return total;
 }
References pgrouting::vrp::Solution::fleet.
do_while_foo()
void pgrouting::vrp::Initial_solution::do_while_foo (int kind) private
Definition at line 78 of file initial_solution.cpp.
{
     invariant();
     pgassert(kind > 0 && kind <= OneDepot);
 #if 0
     msg.log << "\nInitial_solution::do_while_foo\n";
 #endif
     Identifiers<size_t> notused;
 #if 0
     bool out_of_trucks(true);
 #endif
     while (!unassigned.empty()) {
 #if 0
         msg.log << unassigned.size() << " unassigned: " << unassigned << "\n";
         msg.log << assigned.size() << " assigned:" << assigned << "\n";
 #endif
         auto current = unassigned.size();
 #if 0
         auto truck = out_of_trucks?
             trucks.get_truck(unassigned.front()) :
             trucks.get_truck();
 #else
         auto truck = trucks.get_truck(unassigned.front());
 #endif
 #if 0
         msg.log << "got truck:" << truck.tau() << "\n";
 #endif
         /*
          * kind 1 to 7 work with the same code structure
          */
         truck.do_while_feasable((Initials_code)kind, unassigned, assigned);
 #if 0
         msg.log << unassigned.size() << " unassigned: " << unassigned << "\n";
         msg.log << assigned.size() << " assigned:" << assigned << "\n";
         msg.log << "current" << current << " unassigned: " << unassigned.size();
 #endif
         pgassertwm(current > unassigned.size(), msg.get_log().c_str());
 #if 0
         if (truck.orders_in_vehicle().empty()) {
             out_of_trucks = notused.has(truck.idx());
             if (out_of_trucks) {
                 for (auto t : notused) {
                     trucks.release_truck(t);
                 }
             }
             notused += truck.idx();
             continue;
         }
 #endif
         fleet.push_back(truck);
         invariant();
     }
     pgassertwm(true, msg.get_log().c_str());
     pgassert(is_feasable());
     invariant();
 }
References assigned, Identifiers< T >::empty(), pgrouting::vrp::Solution::fleet, Identifiers< T >::front(), pgrouting::Pgr_messages::get_log(), pgrouting::vrp::Fleet::get_truck(), Identifiers< T >::has(), invariant(), pgrouting::vrp::Solution::is_feasable(), pgrouting::Pgr_messages::log, pgrouting::vrp::PD_problem::msg, pgrouting::vrp::OneDepot, pgassert, pgassertwm, pgrouting::vrp::Fleet::release_truck(), Identifiers< T >::size(), pgrouting::vrp::Solution::trucks, and unassigned.
Referenced by Initial_solution().
duration()
double pgrouting::vrp::Solution::duration () const inherited
Definition at line 65 of file solution.cpp.
{
     double total(0);
     for (const auto &v : fleet) {
         total += v.duration();
     }
     return total;
 }
References pgrouting::vrp::Solution::fleet.
Referenced by pgrouting::vrp::Optimize::move_reduce_cost(), pgrouting::vrp::Optimize::save_if_best(), and pgrouting::vrp::Optimize::swap_worse().
fleet_size()
size_t pgrouting::vrp::Solution::fleet_size () const inline inherited
Definition at line 104 of file solution.h.
 {return fleet.size();}
References pgrouting::vrp::Solution::fleet.
get_kind()
Initials_code pgrouting::vrp::Solution::get_kind () const inherited
Definition at line 234 of file solution.cpp.
{
     return problem->get_kind();
 }
References pgrouting::vrp::Pgr_pickDeliver::get_kind(), and pgrouting::vrp::PD_problem::problem.
Referenced by pgrouting::vrp::Optimize::move_order(), pgrouting::vrp::Optimize::move_reduce_cost(), pgrouting::vrp::Optimize::swap_order(), and pgrouting::vrp::Optimize::swap_worse().
get_postgres_result()
std::vector< General_vehicle_orders_t > pgrouting::vrp::Solution::get_postgres_result () const inherited
Definition at line 39 of file solution.cpp.
{
     std::vector<General_vehicle_orders_t> result;
     /* postgres numbering starts with 1 */
     int i(1);
     for (const auto& truck : fleet) {
         std::vector<General_vehicle_orders_t> data =
             truck.get_postgres_result(i);
         result.insert(result.end(), data.begin(), data.end());
         ++i;
     }
     return result;
 }
References pgrouting::vrp::Solution::fleet.
invariant()
void pgrouting::vrp::Initial_solution::invariant () const
Definition at line 39 of file initial_solution.cpp.
{
     /* this checks there is no order duplicated */
     pgassert(all_orders == (assigned + unassigned));
     pgassert((assigned * unassigned).empty());
 }
References all_orders, assigned, pgassert, and unassigned.
Referenced by do_while_foo(), Initial_solution(), and one_truck_all_orders().
is_feasable()
bool pgrouting::vrp::Solution::is_feasable () const inherited
Definition at line 56 of file solution.cpp.
{
     for (const auto& v : fleet) {
         if (v.is_feasable()) continue;
         return false;
     }
     return true;
 }
References pgrouting::vrp::Solution::fleet.
Referenced by pgrouting::vrp::Optimize::decrease_truck(), and do_while_foo().
one_truck_all_orders()
void pgrouting::vrp::Initial_solution::one_truck_all_orders () private
Definition at line 142 of file initial_solution.cpp.
{
     invariant();
     msg.log << "\nInitial_solution::one_truck_all_orders\n";
     auto truck = trucks.get_truck();
     while (!unassigned.empty()) {
         auto order(truck.orders()[*unassigned.begin()]);
         truck.insert(order);
         assigned += unassigned.front();
         unassigned.pop_front();
         invariant();
     }
     fleet.push_back(truck);
     invariant();
 }
References assigned, Identifiers< T >::begin(), Identifiers< T >::empty(), pgrouting::vrp::Solution::fleet, Identifiers< T >::front(), pgrouting::vrp::Fleet::get_truck(), invariant(), pgrouting::Pgr_messages::log, pgrouting::vrp::PD_problem::msg, Identifiers< T >::pop_front(), pgrouting::vrp::Solution::trucks, and unassigned.
Referenced by Initial_solution().
operator<()
bool pgrouting::vrp::Solution::operator< (const Solution & s_rhs) const inherited
Definition at line 186 of file solution.cpp.
{
     Vehicle::Cost lhs(cost());
     Vehicle::Cost rhs(s_rhs.cost());
     /*
      * capacity violations
      */
     if (std::get<0>(lhs) < std::get<0>(rhs))
         return true;
     if (std::get<0>(lhs) > std::get<0>(rhs))
         return false;
     /*
      * time window violations
      */
     if (std::get<1>(lhs) < std::get<1>(rhs))
         return true;
     if (std::get<1>(lhs) > std::get<1>(rhs))
         return false;
     /*
      * fleet size
      */
     if (std::get<2>(lhs) < std::get<2>(rhs))
         return true;
     if (std::get<2>(lhs) > std::get<2>(rhs))
         return false;
     /*
      * waiting time
      */
     if (std::get<3>(lhs) < std::get<3>(rhs))
         return true;
     if (std::get<3>(lhs) > std::get<3>(rhs))
         return false;
     /*
      * duration
      */
     if (std::get<4>(lhs) < std::get<4>(rhs))
         return true;
     if (std::get<4>(lhs) > std::get<4>(rhs))
         return false;
     return false;
 }
References pgrouting::vrp::Solution::cost().
sort_by_id()
void pgrouting::vrp::Solution::sort_by_id () inherited
Definition at line 165 of file solution.cpp.
                      {
     std::sort(fleet.begin(), fleet.end(), []
             (const Vehicle_pickDeliver &lhs, const Vehicle_pickDeliver &rhs)
             -> bool {
             return lhs.idx() < rhs.idx();
             });
 }
References pgrouting::vrp::Solution::fleet.
tau()
std::string pgrouting::vrp::Solution::tau (const std::string & title = "Tau") const inherited
Definition at line 153 of file solution.cpp.
{
     std::ostringstream log;
     log << "\n" << title << ": " << std::endl;
     for (const auto &v : fleet) {
         log << "\n" << v.tau();
     }
     log << "\n" << cost_str() << "\n";
     return log.str();
 }
References pgrouting::vrp::Solution::cost_str(), and pgrouting::vrp::Solution::fleet.
Referenced by pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::operator<<(), pgrouting::vrp::Optimize::Optimize(), pgrouting::vrp::Pgr_pickDeliver::optimize(), and pgrouting::vrp::Optimize::save_if_best().
total_service_time()
double pgrouting::vrp::Solution::total_service_time () const inherited
Definition at line 101 of file solution.cpp.
{
     double total(0);
     for (const auto &v : fleet) {
         total += v.total_service_time();
     }
     return total;
 }
References pgrouting::vrp::Solution::fleet.
total_travel_time()
double pgrouting::vrp::Solution::total_travel_time () const inherited
Definition at line 92 of file solution.cpp.
{
     double total(0);
     for (const auto &v : fleet) {
         total += v.total_travel_time();
     }
     return total;
 }
References pgrouting::vrp::Solution::fleet.
twvTot()
int pgrouting::vrp::Solution::twvTot () const inherited
Definition at line 74 of file solution.cpp.
{
     int total(0);
     for (const auto &v : fleet) {
         total += v.twvTot();
     }
     return total;
 }
References pgrouting::vrp::Solution::fleet.
wait_time()
double pgrouting::vrp::Solution::wait_time () const inherited
Definition at line 83 of file solution.cpp.
{
     double total(0);
     for (const auto &v : fleet) {
         total += v.total_wait_time();
     }
     return total;
 }
References pgrouting::vrp::Solution::fleet.
Member Data Documentation
all_orders
Identifiers<size_t> pgrouting::vrp::Initial_solution::all_orders private
Definition at line 64 of file initial_solution.h.
Referenced by invariant().
assigned
Identifiers<size_t> pgrouting::vrp::Initial_solution::assigned private
Definition at line 66 of file initial_solution.h.
Referenced by do_while_foo(), invariant(), and one_truck_all_orders().
EPSILON
double pgrouting::vrp::Solution::EPSILON protected inherited
Definition at line 48 of file solution.h.
Referenced by pgrouting::vrp::Solution::operator=().
fleet
std::deque<Vehicle_pickDeliver> pgrouting::vrp::Solution::fleet protected inherited
Definition at line 49 of file solution.h.
Referenced by pgrouting::vrp::Solution::cost(), pgrouting::vrp::Solution::cvTot(), pgrouting::vrp::Optimize::decrease_truck(), pgrouting::vrp::Optimize::delete_empty_truck(), do_while_foo(), pgrouting::vrp::Solution::duration(), pgrouting::vrp::Solution::fleet_size(), pgrouting::vrp::Solution::get_postgres_result(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Solution::is_feasable(), one_truck_all_orders(), pgrouting::vrp::operator<<(), pgrouting::vrp::Solution::operator=(), pgrouting::vrp::Optimize::Optimize(), pgrouting::vrp::Optimize::save_if_best(), pgrouting::vrp::Optimize::sort_by_duration(), pgrouting::vrp::Optimize::sort_by_id(), pgrouting::vrp::Solution::sort_by_id(), pgrouting::vrp::Optimize::sort_by_size(), pgrouting::vrp::Optimize::sort_for_move(), pgrouting::vrp::Optimize::swap_order(), pgrouting::vrp::Solution::tau(), pgrouting::vrp::Solution::total_service_time(), pgrouting::vrp::Solution::total_travel_time(), pgrouting::vrp::Solution::twvTot(), and pgrouting::vrp::Solution::wait_time().
msg
Pgr_messages pgrouting::vrp::PD_problem::msg static inherited
Definition at line 49 of file pd_problem.h.
Referenced by pgrouting::vrp::Fleet::add_vehicle(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), pgrouting::vrp::Vehicle_pickDeliver::do_while_feasable(), do_while_foo(), pgrouting::vrp::Pgr_pickDeliver::get_postgres_result(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Fleet::is_fleet_ok(), pgrouting::vrp::Dnode::msg(), pgrouting::vrp::Pgr_pickDeliver::nodesOK(), one_truck_all_orders(), pgrouting::vrp::Optimize::Optimize(), pgrouting::vrp::Pgr_pickDeliver::optimize(), pgrouting::vrp::PD_problem::PD_problem(), pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Optimize::save_if_best(), pgrouting::vrp::Solution::Solution(), pgrouting::vrp::Pgr_pickDeliver::solve(), pgrouting::vrp::Optimize::swap_order(), and pgrouting::vrp::Vehicle::Vehicle().
problem
Pgr_pickDeliver * pgrouting::vrp::PD_problem::problem static protected inherited
Definition at line 52 of file pd_problem.h.
Referenced by pgrouting::vrp::PD_Orders::add_order(), pgrouting::vrp::Fleet::add_vehicle(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), pgrouting::vrp::Dnode::distance(), pgrouting::vrp::Solution::get_kind(), pgrouting::vrp::Pgr_pickDeliver::get_kind(), pgrouting::vrp::Dnode::msg(), pgrouting::vrp::Tw_node::operator==(), pgrouting::vrp::PD_problem::PD_problem(), and pgrouting::vrp::Tw_node::travel_time_to().
trucks
Fleet pgrouting::vrp::Solution::trucks protected inherited
Definition at line 52 of file solution.h.
Referenced by do_while_foo(), one_truck_all_orders(), pgrouting::vrp::Solution::operator=(), and pgrouting::vrp::Solution::Solution().
unassigned
Identifiers<size_t> pgrouting::vrp::Initial_solution::unassigned private
Definition at line 65 of file initial_solution.h.
Referenced by do_while_foo(), invariant(), and one_truck_all_orders().
The documentation for this class was generated from the following files:
initial_solution.h
initial_solution.cpp