PGROUTING: pgrouting::yen::Pgr_ksp< G > Class Template Reference
pgrouting::yen::Pgr_ksp< G > Class Template Reference
#include "ksp.hpp"
Classes
class Visitor
Public Member Functions
Pgr_ksp ()
~Pgr_ksp ()
void clear ()
std::string get_error () const
get_error
std::string get_log () const
get_log
std::string get_notice () const
get_notice
bool has_error () const
get_error
std::deque< Path > Yen (G &graph, int64_t start_vertex, int64_t end_vertex, size_t K, bool heap_paths)
Public Attributes
std::ostringstream error
Stores the error information.
std::ostringstream log
Stores the hint information.
std::ostringstream notice
Stores the notice information.
Protected Member Functions
void executeYen (G &graph)
the actual algorithm
Auxiliary function for yen's algorithm
Path getFirstSolution (G &graph)
Performs the first Dijkstra of the algorithm.
void doNextCycle (G &graph)
Performs the next cycle of the algorithm.
void removeVertices (G &graph, const Path &subpath)
stores in subPath the first i elements of path
std::deque< Path > get_results ()
Protected Attributes
members
V v_source
source descriptor
V v_target
target descriptor
int64_t m_start
source id
int64_t m_end
target id
size_t m_K
bool m_heap_paths
Path curr_result_path
storage for the current result
pSet m_ResultSet
ordered set of shortest paths
pSet m_Heap
the heap
Visitor * m_vis
Private Types
typedef std::set< Path, compPathsLess > pSet
typedef G::V V
Detailed Description
template<class G>
class pgrouting::yen::Pgr_ksp< G >
Definition at line 56 of file ksp.hpp.
Member Typedef Documentation
pSet
template<class G > typedef std::set<Path, compPathsLess> pgrouting::yen::Pgr_ksp< G >::pSet private
Definition at line 58 of file ksp.hpp.
V
template<class G > typedef G::V pgrouting::yen::Pgr_ksp< G >::V private
Definition at line 57 of file ksp.hpp.
Constructor & Destructor Documentation
Pgr_ksp()
template<class G > pgrouting::yen::Pgr_ksp< G >::Pgr_ksp () inline
Definition at line 61 of file ksp.hpp.
               :
         m_start(0),
         m_end(0),
         m_K(0),
         m_heap_paths(false) {
             m_vis = new Visitor;
         }
References pgrouting::yen::Pgr_ksp< G >::m_vis.
~Pgr_ksp()
template<class G > pgrouting::yen::Pgr_ksp< G >::~Pgr_ksp () inline
Definition at line 68 of file ksp.hpp.
                {
         delete m_vis;
     }
References pgrouting::yen::Pgr_ksp< G >::m_vis.
Member Function Documentation
clear()
template<class G > void pgrouting::yen::Pgr_ksp< G >::clear () inline
Definition at line 115 of file ksp.hpp.
                  {
         m_Heap.clear();
         m_ResultSet.clear();
     }
References pgrouting::yen::Pgr_ksp< G >::m_Heap, and pgrouting::yen::Pgr_ksp< G >::m_ResultSet.
Referenced by pgrouting::yen::Pgr_turnRestrictedPath< G >::clear(), pgrouting::yen::Pgr_ksp< G >::executeYen(), pgrouting::algorithms::Yen(), and pgrouting::yen::Pgr_ksp< G >::Yen().
doNextCycle()
template<class G > void pgrouting::yen::Pgr_ksp< G >::doNextCycle (G & graph) inline protected
Performs the next cycle of the algorithm.
Definition at line 173 of file ksp.hpp.
{
         for (unsigned int i = 0; i < curr_result_path.size(); ++i) {
             int64_t spurNodeId = curr_result_path[i].node;
             auto rootPath = curr_result_path.getSubpath(i);
             for (const auto &path : m_ResultSet) {
                 if (path.isEqual(rootPath) && spurNodeId == path[i].node) {
                     if (path.size() > i + 1) {
                         graph.disconnect_edge(path[i].node,     // from
                                 path[i + 1].node);  // to
                     }
                 }
             }
             removeVertices(graph, rootPath);
             auto spurPath = algorithms::dijkstra(graph, spurNodeId, m_end);
             if (spurPath.size() > 0) {
                 rootPath.appendPath(spurPath);
                 m_Heap.insert(rootPath);
                 m_vis->on_insert_to_heap(rootPath);
             }
             graph.restore_graph();
         }
     }
References pgrouting::yen::Pgr_ksp< G >::curr_result_path, pgrouting::algorithms::dijkstra(), pgrouting::Path::getSubpath(), pgrouting::yen::Pgr_ksp< G >::m_end, pgrouting::yen::Pgr_ksp< G >::m_Heap, pgrouting::yen::Pgr_ksp< G >::m_ResultSet, pgrouting::yen::Pgr_ksp< G >::m_vis, pgrouting::yen::Pgr_ksp< G >::Visitor::on_insert_to_heap(), pgrouting::yen::Pgr_ksp< G >::removeVertices(), and pgrouting::Path::size().
Referenced by pgrouting::yen::Pgr_ksp< G >::executeYen().
executeYen()
template<class G > void pgrouting::yen::Pgr_ksp< G >::executeYen (G & graph) inline protected
the actual algorithm
Definition at line 137 of file ksp.hpp.
{
         clear();
         curr_result_path = getFirstSolution(graph);
         m_vis->on_insert_first_solution(curr_result_path);
         if (m_ResultSet.size() == 0) return;  // no path found
         while (m_ResultSet.size() <  m_K) {
             doNextCycle(graph);
             if (m_Heap.empty()) break;
             curr_result_path = *m_Heap.begin();
             curr_result_path.recalculate_agg_cost();
             m_ResultSet.insert(curr_result_path);
             m_Heap.erase(m_Heap.begin());
         }
     }
References pgrouting::Path::begin(), pgrouting::yen::Pgr_ksp< G >::clear(), pgrouting::yen::Pgr_ksp< G >::curr_result_path, pgrouting::yen::Pgr_ksp< G >::doNextCycle(), pgrouting::yen::Pgr_ksp< G >::getFirstSolution(), pgrouting::yen::Pgr_ksp< G >::m_Heap, pgrouting::yen::Pgr_ksp< G >::m_K, pgrouting::yen::Pgr_ksp< G >::m_ResultSet, pgrouting::yen::Pgr_ksp< G >::m_vis, pgrouting::yen::Pgr_ksp< G >::Visitor::on_insert_first_solution(), and pgrouting::Path::recalculate_agg_cost().
Referenced by pgrouting::yen::Pgr_turnRestrictedPath< G >::Yen(), and pgrouting::yen::Pgr_ksp< G >::Yen().
get_error()
std::string pgrouting::Pgr_messages::get_error () const inherited
get_error
Returns
the current contents of the log and clears the log
Definition at line 52 of file messages.cpp.
{
    auto str = error.str();
    return str;
}
References pgrouting::Pgr_messages::error.
Referenced by pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), do_shortestPath(), pgr_do_pickDeliver(), pgr_do_pickDeliverEuclidean(), pgr_do_trsp_withPoints(), pgr_do_trspVia_withPoints(), pgr_do_withPoints(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), and pgr_do_withPointsVia().
get_log()
std::string pgrouting::Pgr_messages::get_log () const inherited
get_log
Returns
the current contents of the log and clears the log
Definition at line 35 of file messages.cpp.
{
    auto str = log.str();
    return str;
}
References pgrouting::Pgr_messages::log.
Referenced by pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), do_shortestPath(), pgr_do_bipartite(), pgr_do_boyerMyrvold(), pgr_do_LTDTree(), pgr_do_makeConnected(), pgr_do_pickDeliver(), pgr_do_pickDeliverEuclidean(), pgr_do_trsp_withPoints(), pgr_do_trspVia_withPoints(), pgr_do_withPoints(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), and pgr_do_withPointsVia().
get_notice()
std::string pgrouting::Pgr_messages::get_notice () const inherited
get_notice
Returns
the current contents of the log and clears the log
Definition at line 41 of file messages.cpp.
{
    auto str = notice.str();
    return str;
}
References pgrouting::Pgr_messages::notice.
get_results()
template<class G > std::deque< Path > pgrouting::yen::Pgr_ksp< G >::get_results () inline protected
Definition at line 208 of file ksp.hpp.
{
         if (this->m_ResultSet.empty()) {
             return std::deque<Path>();
         }
         std::deque<Path> paths(m_ResultSet.begin(), m_ResultSet.end());
         if (m_heap_paths && !m_Heap.empty()) {
            paths.insert(paths.end(), m_Heap.begin(), m_Heap.end());
         }
         pgassert(!paths.empty());
         std::sort(paths.begin(), paths.end(), compPathsLess());
         return paths;
     }
References pgrouting::yen::Pgr_ksp< G >::m_Heap, pgrouting::yen::Pgr_ksp< G >::m_heap_paths, pgrouting::yen::Pgr_ksp< G >::m_ResultSet, and pgassert.
Referenced by pgrouting::yen::Pgr_turnRestrictedPath< G >::Yen(), and pgrouting::yen::Pgr_ksp< G >::Yen().
getFirstSolution()
template<class G > Path pgrouting::yen::Pgr_ksp< G >::getFirstSolution (G & graph) inline protected
Performs the first Dijkstra of the algorithm.
Definition at line 159 of file ksp.hpp.
{
         Path path;
         path = algorithms::dijkstra(graph, m_start, m_end);
         path.recalculate_agg_cost();
         if (path.empty()) return path;
         m_ResultSet.insert(path);
         return path;
     }
References pgrouting::algorithms::dijkstra(), pgrouting::Path::empty(), pgrouting::yen::Pgr_ksp< G >::m_end, pgrouting::yen::Pgr_ksp< G >::m_ResultSet, pgrouting::yen::Pgr_ksp< G >::m_start, and pgrouting::Path::recalculate_agg_cost().
Referenced by pgrouting::yen::Pgr_ksp< G >::executeYen().
has_error()
bool pgrouting::Pgr_messages::has_error () const inherited
get_error
Returns
the current contents of the log and clears the log
Definition at line 47 of file messages.cpp.
{
    return  !error.str().empty();
}
References pgrouting::Pgr_messages::error.
Referenced by do_shortestPath(), pgr_do_trsp_withPoints(), pgr_do_trspVia_withPoints(), pgr_do_withPoints(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), and pgr_do_withPointsVia().
removeVertices()
template<class G > void pgrouting::yen::Pgr_ksp< G >::removeVertices (G & graph, const Path & subpath) inline protected
stores in subPath the first i elements of path
Definition at line 204 of file ksp.hpp.
{
         for (const auto &e : subpath) graph.disconnect_vertex(e.node);
     }
Referenced by pgrouting::yen::Pgr_ksp< G >::doNextCycle().
Yen()
template<class G > std::deque< Path > pgrouting::yen::Pgr_ksp< G >::Yen (G & graph, int64_t start_vertex, int64_t end_vertex, size_t K, bool heap_paths) inline
Definition at line 72 of file ksp.hpp.
{
         /*
          * No path: already in destination
          */
         if ((start_vertex == end_vertex) || (K == 0)) {
             return std::deque<Path>();
         }
         /*
          * no path: disconnected vertices
          */
         if (!graph.has_vertex(start_vertex)
                 || !graph.has_vertex(end_vertex)) {
             return std::deque<Path>();
         }
         /*
          * clean up containers
          */
         clear();
         v_source = graph.get_V(start_vertex);
         v_target = graph.get_V(end_vertex);
         m_start = start_vertex;
         m_end = end_vertex;
         m_K = K;
         m_heap_paths = heap_paths;
         executeYen(graph);
         auto paths = get_results();
         if (!m_heap_paths && paths.size() > m_K) paths.resize(m_K);
         return paths;
     }
References pgrouting::yen::Pgr_ksp< G >::clear(), pgrouting::yen::Pgr_ksp< G >::executeYen(), pgrouting::yen::Pgr_ksp< G >::get_results(), pgrouting::yen::Pgr_ksp< G >::m_end, pgrouting::yen::Pgr_ksp< G >::m_heap_paths, pgrouting::yen::Pgr_ksp< G >::m_K, pgrouting::yen::Pgr_ksp< G >::m_start, pgrouting::yen::Pgr_ksp< G >::v_source, and pgrouting::yen::Pgr_ksp< G >::v_target.
Referenced by pgrouting::algorithms::Yen().
Member Data Documentation
curr_result_path
template<class G > Path pgrouting::yen::Pgr_ksp< G >::curr_result_path protected
storage for the current result
Definition at line 237 of file ksp.hpp.
Referenced by pgrouting::yen::Pgr_ksp< G >::doNextCycle(), and pgrouting::yen::Pgr_ksp< G >::executeYen().
error
std::ostringstream pgrouting::Pgr_messages::error mutable inherited
Stores the error information.
Definition at line 84 of file messages.hpp.
Referenced by pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::Pg_points_graph::check_points(), pgrouting::Pgr_messages::clear(), pgrouting::Pg_points_graph::create_new_edges(), pgrouting::Pgr_messages::get_error(), pgrouting::Pgr_messages::has_error(), and pgrouting::vrp::Fleet::is_fleet_ok().
log
std::ostringstream pgrouting::Pgr_messages::log mutable inherited
Stores the hint information.
Definition at line 80 of file messages.hpp.
Referenced by pgrouting::vrp::Optimize::Optimize(), pgrouting::Pg_points_graph::Pg_points_graph(), pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Solution::Solution(), pgrouting::vrp::Vehicle::Vehicle(), pgrouting::Pgr_bellman_ford< G >::bellman_ford_1_to_many(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::Pg_points_graph::check_points(), pgrouting::Pgr_messages::clear(), pgrouting::Pg_points_graph::create_new_edges(), pgrouting::functions::Pgr_makeConnected< G >::generatemakeConnected(), pgrouting::Pgr_messages::get_log(), pgrouting::vrp::Pgr_pickDeliver::get_postgres_result(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::functions::CuthillMckeeOrdering< G >::get_results(), pgrouting::functions::SloanOrdering< G >::get_results(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Fleet::is_fleet_ok(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), pgrouting::vrp::Optimize::save_if_best(), and pgrouting::vrp::Pgr_pickDeliver::solve().
m_end
template<class G > int64_t pgrouting::yen::Pgr_ksp< G >::m_end protected
target id
Definition at line 233 of file ksp.hpp.
Referenced by pgrouting::yen::Pgr_ksp< G >::doNextCycle(), pgrouting::yen::Pgr_ksp< G >::getFirstSolution(), pgrouting::yen::Pgr_turnRestrictedPath< G >::Yen(), and pgrouting::yen::Pgr_ksp< G >::Yen().
m_Heap
template<class G > pSet pgrouting::yen::Pgr_ksp< G >::m_Heap protected
the heap
Definition at line 240 of file ksp.hpp.
Referenced by pgrouting::yen::Pgr_ksp< G >::clear(), pgrouting::yen::Pgr_ksp< G >::doNextCycle(), pgrouting::yen::Pgr_ksp< G >::executeYen(), pgrouting::yen::Pgr_ksp< G >::get_results(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::turnRestrictedPath().
m_heap_paths
template<class G > bool pgrouting::yen::Pgr_ksp< G >::m_heap_paths protected
Definition at line 235 of file ksp.hpp.
Referenced by pgrouting::yen::Pgr_ksp< G >::get_results(), and pgrouting::yen::Pgr_ksp< G >::Yen().
m_K
template<class G > size_t pgrouting::yen::Pgr_ksp< G >::m_K protected
Definition at line 234 of file ksp.hpp.
Referenced by pgrouting::yen::Pgr_ksp< G >::executeYen(), pgrouting::yen::Pgr_turnRestrictedPath< G >::Yen(), and pgrouting::yen::Pgr_ksp< G >::Yen().
m_ResultSet
template<class G > pSet pgrouting::yen::Pgr_ksp< G >::m_ResultSet protected
ordered set of shortest paths
Definition at line 239 of file ksp.hpp.
Referenced by pgrouting::yen::Pgr_ksp< G >::clear(), pgrouting::yen::Pgr_ksp< G >::doNextCycle(), pgrouting::yen::Pgr_ksp< G >::executeYen(), pgrouting::yen::Pgr_ksp< G >::get_results(), pgrouting::yen::Pgr_ksp< G >::getFirstSolution(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::turnRestrictedPath().
m_start
template<class G > int64_t pgrouting::yen::Pgr_ksp< G >::m_start protected
source id
Definition at line 232 of file ksp.hpp.
Referenced by pgrouting::yen::Pgr_ksp< G >::getFirstSolution(), pgrouting::yen::Pgr_turnRestrictedPath< G >::Yen(), and pgrouting::yen::Pgr_ksp< G >::Yen().
m_vis
template<class G > Visitor* pgrouting::yen::Pgr_ksp< G >::m_vis protected
Definition at line 242 of file ksp.hpp.
Referenced by pgrouting::yen::Pgr_ksp< G >::Pgr_ksp(), pgrouting::yen::Pgr_ksp< G >::~Pgr_ksp(), pgrouting::yen::Pgr_ksp< G >::doNextCycle(), pgrouting::yen::Pgr_ksp< G >::executeYen(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::Yen().
notice
std::ostringstream pgrouting::Pgr_messages::notice mutable inherited
Stores the notice information.
Definition at line 82 of file messages.hpp.
Referenced by pgrouting::Pgr_messages::clear(), and pgrouting::Pgr_messages::get_notice().
v_source
template<class G > V pgrouting::yen::Pgr_ksp< G >::v_source protected
source descriptor
Definition at line 230 of file ksp.hpp.
Referenced by pgrouting::yen::Pgr_turnRestrictedPath< G >::Yen(), and pgrouting::yen::Pgr_ksp< G >::Yen().
v_target
template<class G > V pgrouting::yen::Pgr_ksp< G >::v_target protected
target descriptor
Definition at line 231 of file ksp.hpp.
Referenced by pgrouting::yen::Pgr_turnRestrictedPath< G >::Yen(), and pgrouting::yen::Pgr_ksp< G >::Yen().
The documentation for this class was generated from the following file:
ksp.hpp