PGROUTING: pgrouting::CH_edge Class Reference
pgrouting::CH_edge Class Reference
#include "ch_edge.hpp"
Public Member Functions
CH_edge ()=default
CH_edge (int64_t eid, int64_t source, int64_t target, double cost)
void add_contracted_edge_vertices (CH_edge &e)
void add_contracted_vertex (CH_vertex &v)
void add_contracted_vertices (Identifiers< int64_t > &)
void clear_contracted_vertices ()
Identifiers< int64_t > & contracted_vertices ()
const Identifiers< int64_t > & contracted_vertices () const
void cp_members (const CH_edge &other)
bool has_contracted_vertices () const
void set_contracted_vertices (Identifiers< int64_t > &)
Public Attributes
double cost
int64_t id
int64_t source
int64_t target
Private Attributes
Identifiers< int64_t > m_contracted_vertices
Friends
std::ostream & operator<< (std::ostream &os, const CH_edge &e)
Detailed Description
Definition at line 42 of file ch_edge.hpp.
Constructor & Destructor Documentation
CH_edge() [1/2]
pgrouting::CH_edge::CH_edge () default
CH_edge() [2/2]
pgrouting::CH_edge::CH_edge (int64_t eid, int64_t source, int64_t target, double cost) inline
Definition at line 46 of file ch_edge.hpp.
                                                                       :
         id(eid), source(source),
         target(target), cost(cost) {}
Member Function Documentation
add_contracted_edge_vertices()
void pgrouting::CH_edge::add_contracted_edge_vertices (CH_edge & e)
Definition at line 72 of file ch_edge.cpp.
{
    if (e.has_contracted_vertices()) {
        m_contracted_vertices += e.contracted_vertices();
    }
}
References contracted_vertices(), has_contracted_vertices(), and m_contracted_vertices.
Referenced by pgrouting::graph::Pgr_contractionGraph< G, t_directed >::process_ch_shortcut(), and pgrouting::graph::Pgr_contractionGraph< G, t_directed >::process_shortcut().
add_contracted_vertex()
void pgrouting::CH_edge::add_contracted_vertex (CH_vertex & v)
Definition at line 66 of file ch_edge.cpp.
{
    m_contracted_vertices += v.id;
    m_contracted_vertices += v.contracted_vertices();
}
References pgrouting::CH_vertex::contracted_vertices(), pgrouting::CH_vertex::id, and m_contracted_vertices.
Referenced by pgrouting::graph::Pgr_contractionGraph< G, t_directed >::process_ch_shortcut(), and pgrouting::graph::Pgr_contractionGraph< G, t_directed >::process_shortcut().
add_contracted_vertices()
void pgrouting::CH_edge::add_contracted_vertices (Identifiers< int64_t > & ids)
Definition at line 78 of file ch_edge.cpp.
{
    m_contracted_vertices += ids;
}
References m_contracted_vertices.
clear_contracted_vertices()
void pgrouting::CH_edge::clear_contracted_vertices () inline
Definition at line 60 of file ch_edge.hpp.
{m_contracted_vertices.clear();}
References pgrouting::Identifiers< T >::clear(), and m_contracted_vertices.
contracted_vertices() [1/2]
Identifiers< int64_t > & pgrouting::CH_edge::contracted_vertices ()
Definition at line 60 of file ch_edge.cpp.
{
    return m_contracted_vertices;
}
References m_contracted_vertices.
contracted_vertices() [2/2]
const Identifiers< int64_t > & pgrouting::CH_edge::contracted_vertices () const
Definition at line 55 of file ch_edge.cpp.
{
    return m_contracted_vertices;
}
References m_contracted_vertices.
Referenced by add_contracted_edge_vertices(), and cp_members().
cp_members()
void pgrouting::CH_edge::cp_members (const CH_edge & other)
Definition at line 40 of file ch_edge.cpp.
{
    this->cost = other.cost;
    this->id = other.id;
    this->source = other.source;
    this->target = other.target;
    this->m_contracted_vertices += other.contracted_vertices();
}
References contracted_vertices(), cost, id, m_contracted_vertices, source, and target.
has_contracted_vertices()
bool pgrouting::CH_edge::has_contracted_vertices () const
Definition at line 50 of file ch_edge.cpp.
{
    return !m_contracted_vertices.empty();
}
References pgrouting::Identifiers< T >::empty(), and m_contracted_vertices.
Referenced by add_contracted_edge_vertices().
set_contracted_vertices()
void pgrouting::CH_edge::set_contracted_vertices (Identifiers< int64_t > & contracted_vertices_ids)
Definition at line 34 of file ch_edge.cpp.
{
    m_contracted_vertices = contracted_vertices_ids;
}
References m_contracted_vertices.
Referenced by pgrouting::graph::Pgr_contractionGraph< G, t_directed >::get_min_cost_edge().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const CH_edge & e) friend
Definition at line 82 of file ch_edge.cpp.
{
    os << "{id: " << e.id << ",\t"
        << "source: " << e.source << ",\t"
        << "target: " << e.target << ",\t"
        << "cost: " << e.cost << ",\t"
        << "contracted vertices: "
        << e.contracted_vertices()
        << "}";
    return os;
}
Member Data Documentation
cost
double pgrouting::CH_edge::cost
Definition at line 69 of file ch_edge.hpp.
Referenced by pgrouting::graph::Pgr_contractionGraph< G, t_directed >::add_shortcut(), and cp_members().
id
int64_t pgrouting::CH_edge::id
Definition at line 66 of file ch_edge.hpp.
Referenced by cp_members().
m_contracted_vertices
Identifiers<int64_t> pgrouting::CH_edge::m_contracted_vertices private
Definition at line 72 of file ch_edge.hpp.
Referenced by add_contracted_edge_vertices(), add_contracted_vertex(), add_contracted_vertices(), clear_contracted_vertices(), contracted_vertices(), contracted_vertices(), cp_members(), has_contracted_vertices(), and set_contracted_vertices().
source
int64_t pgrouting::CH_edge::source
Definition at line 67 of file ch_edge.hpp.
Referenced by cp_members().
target
int64_t pgrouting::CH_edge::target
Definition at line 68 of file ch_edge.hpp.
Referenced by cp_members().
The documentation for this class was generated from the following files:
ch_edge.hpp
ch_edge.cpp