PGROUTING: pgrouting::vrp::Vehicle_node Class Reference
pgrouting::vrp::Vehicle_node Class Reference
Extend Tw_node to evaluate the vehicle at node level.
#include "vehicle_node.h"
Public Types
enum NodeType {
kStart = 0, kPickup, kDelivery, kDump,
kLoad, kEnd
}
Public Member Functions
Vehicle_node ()
Construct from parameters.
Vehicle_node (const Tw_node &node)
Creates a disconected vehicle node.
Vehicle_node (const Vehicle_node &)=default
bool deltaGeneratesTWV (double delta_time) const
True when arrival_time + delta_time generates TWV.
int64_t id () const
size_t idx () const
void reset_id (int64_t)
accessors
int64_t order () const
@ {
double opens () const
Returns the opening time.
double closes () const
Returns the closing time.
double demand () const
Returns the demand associated with this node.
void demand (double value)
double service_time () const
Returns the service time for this node.
NodeType type () const
Returns the type of this node.
double window_length () const
Returns the length of time between the opening and closing.
double travel_time_to (const Tw_node &other, double speed) const
time = distance / speed.
kind of node
A true value when;
0 < opens < closes
the type is the requested type
the demand are valid for the requested type
bool is_start () const
@ {
bool is_pickup () const
is_pickup
bool is_delivery () const
is_delivery
bool is_dump () const
is_dump
bool is_load () const
is_Load
bool is_end () const
is_end
std::string type_str () const
to be or not to be
bool operator== (const Tw_node &rhs) const
bool is_early_arrival (double arrival_time) const
True when arrivalTime is before it opens.
bool is_late_arrival (double arrival_time) const
True when arrivalTime is after it closes.
bool is_on_time (double arrival_time) const
True when arrivalTime in the time window.
document functions
double arrival_j_opens_i (const Tw_node &I, double speed) const
@ {
double arrival_j_closes_i (const Tw_node &I, double speed) const
The actual arrival time at this node, given that: this node is visited directly after other node and that the actual arrival time at other node was closes(other)
bool is_compatible_IJ (const Tw_node &I, double speed) const
bool is_partially_compatible_IJ (const Tw_node &I, double speed) const
bool is_tight_compatible_IJ (const Tw_node &I, double speed) const
bool is_partially_waitTime_compatible_IJ (const Tw_node &I, double speed) const
bool is_waitTime_compatible_IJ (const Tw_node &I, double speed) const
Node evaluation accessors
double travel_time () const
@ {
double arrival_time () const
Truck's arrival_time to this node.
double wait_time () const
Truck's wait_time at this node.
double departure_time () const
Truck's departure_time from this node.
double delta_time () const
delta_time = departure_time(this) - departure_time(previous)
Accumulated evaluation accessors
int twvTot () const
@ {
int cvTot () const
Truck's total times it has violated cargo limits.
double cargo () const
Truck's total cargo after the node was served.
double total_time () const
Truck's travel duration up to this node.
double total_travel_time () const
_time spent moving between nodes by the truck
double total_wait_time () const
_time spent by the truck waiting for nodes to open
double total_service_time () const
_time spent by the truck servicing the nodes
State
bool feasible () const
@ {
bool feasible (double cargoLimit) const
True doesn't have twc nor cv (including total counts)
bool has_twv () const
True when at this node does not violate time windows.
bool has_cv (double cargoLimit) const
True when not violation.
mutators
void evaluate (double cargoLimit)
@ {
void evaluate (const Vehicle_node &pred, double cargoLimit, double speed)
Document
double arrival_i_arrives_j (const Vehicle_node &other, double speed) const
@ {
accessors
int64_t order () const
@ {
double opens () const
Returns the opening time.
double closes () const
Returns the closing time.
double demand () const
Returns the demand associated with this node.
void demand (double value)
double service_time () const
Returns the service time for this node.
NodeType type () const
Returns the type of this node.
double window_length () const
Returns the length of time between the opening and closing.
double travel_time_to (const Tw_node &other, double speed) const
time = distance / speed.
kind of node
A true value when;
0 < opens < closes
the type is the requested type
the demand are valid for the requested type
bool is_start () const
@ {
bool is_pickup () const
is_pickup
bool is_delivery () const
is_delivery
bool is_dump () const
is_dump
bool is_load () const
is_Load
bool is_end () const
is_end
std::string type_str () const
to be or not to be
bool operator== (const Tw_node &rhs) const
bool is_early_arrival (double arrival_time) const
True when arrivalTime is before it opens.
bool is_late_arrival (double arrival_time) const
True when arrivalTime is after it closes.
bool is_on_time (double arrival_time) const
True when arrivalTime in the time window.
document functions
double arrival_j_opens_i (const Tw_node &I, double speed) const
@ {
double arrival_j_closes_i (const Tw_node &I, double speed) const
The actual arrival time at this node, given that: this node is visited directly after other node and that the actual arrival time at other node was closes(other)
bool is_compatible_IJ (const Tw_node &I, double speed) const
bool is_partially_compatible_IJ (const Tw_node &I, double speed) const
bool is_tight_compatible_IJ (const Tw_node &I, double speed) const
bool is_partially_waitTime_compatible_IJ (const Tw_node &I, double speed) const
bool is_waitTime_compatible_IJ (const Tw_node &I, double speed) const
Static Public Attributes
static Pgr_messages msg
Protected Member Functions
bool is_valid () const
Static Protected Attributes
static Pgr_pickDeliver * problem
Private Attributes
double m_closes
closing time of the node
double m_demand
The demand for the Node.
int64_t m_id
size_t m_idx
double m_opens
opening time of the node
int64_t m_order
order to which it belongs
double m_service_time
NodeType m_type
The demand for the Node.
Node evaluation members
double m_travel_time
@ {
double m_arrival_time
Arrival time at this node.
double m_wait_time
Wait time at this node when early arrival.
double m_departure_time
double m_delta_time
Departure time - last nodes departure time.
Accumulated evaluation members
double m_cargo
@ {
int m_twvTot
Total count of TWV.
int m_cvTot
Total count of CV.
double m_tot_wait_time
Accumulated wait time.
double m_tot_travel_time
Accumulated travel time.
double m_tot_service_time
Friends
log
std::ostream & operator<< (std::ostream &log, const Vehicle_node &node)
@ {
Detailed Description
Extend Tw_node to evaluate the vehicle at node level.
This class extends Twnode by adding attributes to store information about the node in a path and provides the tools evaluate the node and to set and get these attribute values.
Definition at line 48 of file vehicle_node.h.
Member Enumeration Documentation
NodeType
enum pgrouting::vrp::Tw_node::NodeType inherited
Enumerator
kStart
starting site
kPickup
pickup site
kDelivery
delivery site
kDump
dump site, empties truck
kLoad
load site, fills the truck
kEnd
ending site
Definition at line 59 of file tw_node.h.
                   {
          kStart = 0,
          kPickup,
          kDelivery,
          kDump,
          kLoad,
          kEnd
      } NodeType;
Constructor & Destructor Documentation
Vehicle_node() [1/3]
pgrouting::vrp::Vehicle_node::Vehicle_node () inline
Construct from parameters.
Definition at line 158 of file vehicle_node.h.
 : Tw_node() {}
Vehicle_node() [2/3]
pgrouting::vrp::Vehicle_node::Vehicle_node (const Vehicle_node &) default
Vehicle_node() [3/3]
pgrouting::vrp::Vehicle_node::Vehicle_node (const Tw_node & node) explicit
Creates a disconected vehicle node.
A node that is not served by any vehicle
Parameters
[in] node Time window node
Definition at line 122 of file vehicle_node.cpp.
     : Tw_node(node),
     m_travel_time(0),
     m_arrival_time(0),
     m_wait_time(0),
     m_departure_time(0),
     m_delta_time(0),
     m_cargo(0),
     m_twvTot(0),
     m_cvTot(0),
     m_tot_wait_time(0),
     m_tot_travel_time(0),
     m_tot_service_time(0) {
     }
Member Function Documentation
arrival_i_arrives_j()
double pgrouting::vrp::Vehicle_node::arrival_i_arrives_j (const Vehicle_node & other, double speed) const
@ {
The actual arrival time at This node, given that: this node is visited directly after other node and that the actual arrival time at other node was arrival(other)
returns the arrval time at this visited after other
Definition at line 151 of file vehicle_node.cpp.
{
     return other.arrival_time()
         + other.service_time()
         + other.travel_time_to(*this, speed);
 }
References arrival_time(), pgrouting::vrp::Tw_node::service_time(), and pgrouting::vrp::Tw_node::travel_time_to().
arrival_j_closes_i()
double pgrouting::vrp::Tw_node::arrival_j_closes_i (const Tw_node & I, double speed) const inherited
The actual arrival time at this node, given that: this node is visited directly after other node and that the actual arrival time at other node was closes(other)
Definition at line 64 of file tw_node.cpp.
{
     if (m_type == kStart) return  (std::numeric_limits<double>::max)();
     return I.closes() + I.service_time() + I.travel_time_to(*this, speed);
 }
References pgrouting::vrp::Tw_node::closes(), pgrouting::vrp::Tw_node::kStart, pgrouting::vrp::Tw_node::m_type, pgrouting::vrp::Tw_node::service_time(), and pgrouting::vrp::Tw_node::travel_time_to().
Referenced by pgrouting::vrp::Tw_node::is_partially_compatible_IJ(), and pgrouting::vrp::Tw_node::is_tight_compatible_IJ().
arrival_j_opens_i()
double pgrouting::vrp::Tw_node::arrival_j_opens_i (const Tw_node & I, double speed) const inherited
@ {
The actual arrival time at This node, given that: this node is visited directly after other node and that the actual arrival time at other node was opens(other)
Definition at line 58 of file tw_node.cpp.
{
     if (m_type == kStart) return (std::numeric_limits<double>::max)();
     return I.opens() + I.service_time() + I.travel_time_to(*this, speed);
 }
References pgrouting::vrp::Tw_node::kStart, pgrouting::vrp::Tw_node::m_type, pgrouting::vrp::Tw_node::opens(), pgrouting::vrp::Tw_node::service_time(), and pgrouting::vrp::Tw_node::travel_time_to().
Referenced by pgrouting::vrp::Tw_node::is_compatible_IJ(), pgrouting::vrp::Tw_node::is_partially_compatible_IJ(), pgrouting::vrp::Tw_node::is_partially_waitTime_compatible_IJ(), pgrouting::vrp::Tw_node::is_tight_compatible_IJ(), and pgrouting::vrp::Tw_node::is_waitTime_compatible_IJ().
arrival_time()
double pgrouting::vrp::Vehicle_node::arrival_time () const inline
Truck's arrival_time to this node.
Definition at line 65 of file vehicle_node.h.
 {return m_arrival_time;}
References m_arrival_time.
Referenced by arrival_i_arrives_j(), evaluate(), and pgrouting::vrp::operator<<().
cargo()
double pgrouting::vrp::Vehicle_node::cargo () const inline
Truck's total cargo after the node was served.
Definition at line 93 of file vehicle_node.h.
 {return m_cargo;}
References m_cargo.
Referenced by pgrouting::vrp::operator<<().
closes()
double pgrouting::vrp::Tw_node::closes () const inline inherited
Returns the closing time.
Definition at line 79 of file tw_node.h.
 {return m_closes;}
References pgrouting::vrp::Tw_node::m_closes.
Referenced by pgrouting::vrp::Fleet::add_vehicle(), pgrouting::vrp::Tw_node::arrival_j_closes_i(), pgrouting::vrp::Vehicle::deltaTime(), pgrouting::vrp::Tw_node::is_delivery(), pgrouting::vrp::Tw_node::is_dump(), pgrouting::vrp::Tw_node::is_end(), pgrouting::vrp::Tw_node::is_load(), pgrouting::vrp::Vehicle::is_ok(), pgrouting::vrp::Tw_node::is_pickup(), pgrouting::vrp::Tw_node::is_start(), and pgrouting::vrp::Vehicle::Vehicle().
cvTot()
int pgrouting::vrp::Vehicle_node::cvTot () const inline
Truck's total times it has violated cargo limits.
Definition at line 90 of file vehicle_node.h.
 {return m_cvTot;}
References m_cvTot.
Referenced by pgrouting::vrp::operator<<().
delta_time()
double pgrouting::vrp::Vehicle_node::delta_time () const inline
delta_time = departure_time(this) - departure_time(previous)
Definition at line 74 of file vehicle_node.h.
 {return m_delta_time;}
References m_delta_time.
Referenced by deltaGeneratesTWV().
deltaGeneratesTWV()
bool pgrouting::vrp::Vehicle_node::deltaGeneratesTWV (double delta_time) const
True when arrival_time + delta_time generates TWV.
Definition at line 140 of file vehicle_node.cpp.
{
     return is_late_arrival(m_arrival_time + delta_time);
 }
References delta_time(), pgrouting::vrp::Tw_node::is_late_arrival(), and m_arrival_time.
demand() [1/2]
double pgrouting::vrp::Tw_node::demand () const inline inherited
Returns the demand associated with this node.
Definition at line 82 of file tw_node.h.
 {return m_demand;}
References pgrouting::vrp::Tw_node::m_demand.
Referenced by evaluate(), pgrouting::vrp::Tw_node::is_delivery(), pgrouting::vrp::Tw_node::is_dump(), pgrouting::vrp::Tw_node::is_end(), pgrouting::vrp::Tw_node::is_load(), pgrouting::vrp::Tw_node::is_pickup(), and pgrouting::vrp::Tw_node::is_start().
demand() [2/2]
void pgrouting::vrp::Tw_node::demand (double value) inline inherited
Definition at line 83 of file tw_node.h.
 {m_demand = value;}
References pgrouting::vrp::Tw_node::m_demand.
departure_time()
double pgrouting::vrp::Vehicle_node::departure_time () const inline
Truck's departure_time from this node.
Definition at line 71 of file vehicle_node.h.
 {return m_departure_time;}
References m_departure_time.
Referenced by evaluate(), and pgrouting::vrp::operator<<().
evaluate() [1/2]
void pgrouting::vrp::Vehicle_node::evaluate (const Vehicle_node & pred, double cargoLimit, double speed)
Parameters
[in] pred The node preceding this node in the path.
[in] cargoLimit of the vehicle.
[in] speed of the vehicle.
Definition at line 68 of file vehicle_node.cpp.
                       {
     /* time */
     m_travel_time    = pred.travel_time_to(*this, speed);
     m_arrival_time   = pred.departure_time() + travel_time();
     m_wait_time      = is_early_arrival(arrival_time()) ?
         opens() - m_arrival_time :
         0;
     m_departure_time = arrival_time() + wait_time() + service_time();
     /* time aggregates */
     m_tot_travel_time = pred.total_travel_time() + travel_time();
     m_tot_wait_time    = pred.total_wait_time()    + wait_time();
     m_tot_service_time = pred.total_service_time() + service_time();
     /* cargo aggregates */
     if (is_dump() &&  pred.cargo() >= 0) {
         demand(-pred.cargo());
     }
     m_cargo = pred.cargo() + demand();
     /* violations aggregates */
     m_twvTot = has_twv() ? pred.twvTot() + 1 : pred.twvTot();
     m_cvTot = has_cv(cargoLimit) ? pred.cvTot() + 1 : pred.cvTot();
     m_delta_time = departure_time() - pred.departure_time();
 }
References arrival_time(), pgrouting::vrp::Tw_node::demand(), departure_time(), has_cv(), has_twv(), pgrouting::vrp::Tw_node::is_dump(), pgrouting::vrp::Tw_node::is_early_arrival(), m_arrival_time, m_cargo, m_cvTot, m_delta_time, m_departure_time, m_tot_service_time, m_tot_travel_time, m_tot_wait_time, m_travel_time, m_twvTot, m_wait_time, pgrouting::vrp::Tw_node::opens(), pred(), pgrouting::vrp::Tw_node::service_time(), travel_time(), and wait_time().
evaluate() [2/2]
void pgrouting::vrp::Vehicle_node::evaluate (double cargoLimit)
@ {
Todo:
TODO evaluate with matrix also
Parameters
[in] cargoLimit of the vehicle
Definition at line 38 of file vehicle_node.cpp.
{
     if (is_start()) {
         /* time */
         m_travel_time = 0;
         m_arrival_time = opens();
         m_wait_time = 0;
         m_departure_time = arrival_time() + service_time();
         /* time aggregates */
         m_tot_travel_time = 0;
         m_tot_wait_time = 0;
         m_tot_service_time = service_time();
         /* cargo aggregates */
         m_cargo = demand();
         /* violation aggregates */
         m_twvTot = m_cvTot = 0;
         m_cvTot = has_cv(cargoLimit) ? 1 : 0;
         m_delta_time = 0;
     }
 }
References arrival_time(), pgrouting::vrp::Tw_node::demand(), has_cv(), pgrouting::vrp::Tw_node::is_start(), m_arrival_time, m_cargo, m_cvTot, m_delta_time, m_departure_time, m_tot_service_time, m_tot_travel_time, m_tot_wait_time, m_travel_time, m_twvTot, m_wait_time, pgrouting::vrp::Tw_node::opens(), and pgrouting::vrp::Tw_node::service_time().
feasible() [1/2]
bool pgrouting::vrp::Vehicle_node::feasible () const inline
@ {
True when the total count for violations are 0
Definition at line 116 of file vehicle_node.h.
 {return m_twvTot == 0 &&  m_cvTot == 0;}
References m_cvTot, and m_twvTot.
Referenced by feasible().
feasible() [2/2]
bool pgrouting::vrp::Vehicle_node::feasible (double cargoLimit) const inline
True doesn't have twc nor cv (including total counts)
Definition at line 119 of file vehicle_node.h.
{
          return feasible() &&  !has_twv() &&  !has_cv(cargoLimit);
      }
References feasible(), has_cv(), and has_twv().
has_cv()
bool pgrouting::vrp::Vehicle_node::has_cv (double cargoLimit) const inline
True when not violation.
Ending's or start's cargo should be 0
Definition at line 132 of file vehicle_node.h.
{
          return is_end() ||  is_start() ? m_cargo != 0
              : m_cargo > cargoLimit ||  m_cargo < 0;
      }
References pgrouting::vrp::Tw_node::is_end(), pgrouting::vrp::Tw_node::is_start(), and m_cargo.
Referenced by evaluate(), and feasible().
has_twv()
bool pgrouting::vrp::Vehicle_node::has_twv () const inline
True when at this node does not violate time windows.
Definition at line 124 of file vehicle_node.h.
{
          return is_late_arrival(m_arrival_time);
      }
References pgrouting::vrp::Tw_node::is_late_arrival(), and m_arrival_time.
Referenced by evaluate(), feasible(), and pgrouting::vrp::operator<<().
id()
int64_t pgrouting::Identifier::id () const inherited
Definition at line 42 of file identifier.cpp.
                      {
     return m_id;
 }
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Dnode::distance(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::vrp::Vehicle::is_phony(), pgrouting::vrp::operator<<(), pgrouting::operator<<(), pgrouting::vrp::Node::operator==(), pgrouting::vrp::Base_node::operator==(), pgrouting::vrp::Node::print(), pgrouting::vrp::Vehicle::tau(), and pgrouting::vrp::Vehicle::Vehicle().
idx()
size_t pgrouting::Identifier::idx () const inherited
Definition at line 37 of file identifier.cpp.
                       {
     return m_idx;
 }
References pgrouting::Identifier::m_idx.
Referenced by pgrouting::vrp::Vehicle_pickDeliver::erase(), pgrouting::vrp::Vehicle::erase(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Vehicle_pickDeliver::has_order(), pgrouting::vrp::Vehicle::insert(), pgrouting::vrp::Vehicle_pickDeliver::insert(), pgrouting::vrp::operator<<(), pgrouting::operator<<(), pgrouting::vrp::Base_node::operator==(), pgrouting::vrp::Node::operator==(), pgrouting::vrp::Tw_node::operator==(), pgrouting::vrp::Node::print(), pgrouting::vrp::Vehicle_pickDeliver::push_back(), pgrouting::vrp::Vehicle_pickDeliver::push_front(), pgrouting::vrp::Vehicle_pickDeliver::semiLIFO(), pgrouting::vrp::Order::set_compatibles(), pgrouting::vrp::Vehicle::tau(), pgrouting::vrp::Tw_node::travel_time_to(), and pgrouting::vrp::Vehicle::Vehicle().
is_compatible_IJ()
bool pgrouting::vrp::Tw_node::is_compatible_IJ (const Tw_node & I, double speed) const inherited
Definition at line 73 of file tw_node.cpp.
{
     /*
      * I /->  kStart
      */
     if (m_type == kStart) return false;
     /*
      * kEnd /-> (*this)
      */
     if (I.m_type == kEnd) return false;
     return !is_late_arrival(arrival_j_opens_i(I, speed));
 }
References pgrouting::vrp::Tw_node::arrival_j_opens_i(), pgrouting::vrp::Tw_node::is_late_arrival(), pgrouting::vrp::Tw_node::kEnd, pgrouting::vrp::Tw_node::kStart, and pgrouting::vrp::Tw_node::m_type.
Referenced by pgrouting::vrp::Vehicle::getPosHighLimit(), pgrouting::vrp::Tw_node::is_partially_compatible_IJ(), pgrouting::vrp::Tw_node::is_partially_waitTime_compatible_IJ(), pgrouting::vrp::Tw_node::is_tight_compatible_IJ(), pgrouting::vrp::Order::is_valid(), pgrouting::vrp::Tw_node::is_waitTime_compatible_IJ(), and pgrouting::vrp::Order::isCompatibleIJ().
is_delivery()
bool pgrouting::vrp::Tw_node::is_delivery () const inherited
is_delivery
To be a delivery node:
type is kDelivery
demand < 0
Definition at line 150 of file tw_node.cpp.
{
     return m_type == kDelivery
         && (opens() < closes())
         && (service_time() >= 0)
         && (demand() < 0);
 }
References pgrouting::vrp::Tw_node::closes(), pgrouting::vrp::Tw_node::demand(), pgrouting::vrp::Tw_node::kDelivery, pgrouting::vrp::Tw_node::m_type, pgrouting::vrp::Tw_node::opens(), and pgrouting::vrp::Tw_node::service_time().
Referenced by pgrouting::vrp::Order::is_valid(), and pgrouting::vrp::Tw_node::is_valid().
is_dump()
bool pgrouting::vrp::Tw_node::is_dump () const inherited
is_dump
To be a dump node:
type is kDump
demand <= 0
Definition at line 159 of file tw_node.cpp.
{
     return m_type == kDump
         && (opens() < closes())
         && (service_time() >= 0)
         && (demand() <= 0);
 }
References pgrouting::vrp::Tw_node::closes(), pgrouting::vrp::Tw_node::demand(), pgrouting::vrp::Tw_node::kDump, pgrouting::vrp::Tw_node::m_type, pgrouting::vrp::Tw_node::opens(), and pgrouting::vrp::Tw_node::service_time().
Referenced by evaluate(), and pgrouting::vrp::Tw_node::is_valid().
is_early_arrival()
bool pgrouting::vrp::Tw_node::is_early_arrival (double arrival_time) const inline inherited
True when arrivalTime is before it opens.
Definition at line 187 of file tw_node.h.
{
          return arrival_time < m_opens;
      }
References pgrouting::vrp::Tw_node::m_opens.
Referenced by pgrouting::vrp::Vehicle::deltaTime(), evaluate(), pgrouting::vrp::Tw_node::is_on_time(), pgrouting::vrp::Tw_node::is_partially_compatible_IJ(), pgrouting::vrp::Tw_node::is_partially_waitTime_compatible_IJ(), pgrouting::vrp::Tw_node::is_tight_compatible_IJ(), and pgrouting::vrp::Tw_node::is_waitTime_compatible_IJ().
is_end()
bool pgrouting::vrp::Tw_node::is_end () const inherited
is_end
To be a End node:
type is kEnd
demand == 0
Definition at line 177 of file tw_node.cpp.
                       {
     return m_type == kEnd
         && (opens() < closes())
         && (service_time() >= 0)
         && (demand() == 0);
 }
References pgrouting::vrp::Tw_node::closes(), pgrouting::vrp::Tw_node::demand(), pgrouting::vrp::Tw_node::kEnd, pgrouting::vrp::Tw_node::m_type, pgrouting::vrp::Tw_node::opens(), and pgrouting::vrp::Tw_node::service_time().
Referenced by pgrouting::vrp::Fleet::add_vehicle(), has_cv(), and pgrouting::vrp::Tw_node::is_valid().
is_late_arrival()
bool pgrouting::vrp::Tw_node::is_late_arrival (double arrival_time) const inline inherited
True when arrivalTime is after it closes.
Definition at line 192 of file tw_node.h.
{
          return arrival_time > m_closes;
      }
References pgrouting::vrp::Tw_node::m_closes.
Referenced by deltaGeneratesTWV(), has_twv(), pgrouting::vrp::Tw_node::is_compatible_IJ(), pgrouting::vrp::Tw_node::is_on_time(), pgrouting::vrp::Tw_node::is_partially_compatible_IJ(), and pgrouting::vrp::Tw_node::is_tight_compatible_IJ().
is_load()
bool pgrouting::vrp::Tw_node::is_load () const inherited
is_Load
To be a Load node:
type is kLoad
demand >= 0
Definition at line 168 of file tw_node.cpp.
{
     return m_type == kLoad
         && (opens() < closes())
         && (service_time() >= 0)
         && (demand() >= 0);
 }
References pgrouting::vrp::Tw_node::closes(), pgrouting::vrp::Tw_node::demand(), pgrouting::vrp::Tw_node::kLoad, pgrouting::vrp::Tw_node::m_type, pgrouting::vrp::Tw_node::opens(), and pgrouting::vrp::Tw_node::service_time().
Referenced by pgrouting::vrp::Tw_node::is_valid().
is_on_time()
bool pgrouting::vrp::Tw_node::is_on_time (double arrival_time) const inline inherited
True when arrivalTime in the time window.
Definition at line 196 of file tw_node.h.
{
          return !is_early_arrival(arrival_time)
              && !is_late_arrival(arrival_time);
      }
References pgrouting::vrp::Tw_node::is_early_arrival(), and pgrouting::vrp::Tw_node::is_late_arrival().
is_partially_compatible_IJ()
bool pgrouting::vrp::Tw_node::is_partially_compatible_IJ (const Tw_node & I, double speed) const inherited
Definition at line 87 of file tw_node.cpp.
{
     return
         is_compatible_IJ(I, speed)
         && !is_early_arrival(arrival_j_opens_i(I, speed))
         && is_late_arrival(arrival_j_closes_i(I, speed));
 }
References pgrouting::vrp::Tw_node::arrival_j_closes_i(), pgrouting::vrp::Tw_node::arrival_j_opens_i(), pgrouting::vrp::Tw_node::is_compatible_IJ(), pgrouting::vrp::Tw_node::is_early_arrival(), and pgrouting::vrp::Tw_node::is_late_arrival().
is_partially_waitTime_compatible_IJ()
bool pgrouting::vrp::Tw_node::is_partially_waitTime_compatible_IJ (const Tw_node & I, double speed) const inherited
Definition at line 103 of file tw_node.cpp.
{
     return
         is_compatible_IJ(I, speed)
         && is_early_arrival(arrival_j_opens_i(I, speed));
 }
References pgrouting::vrp::Tw_node::arrival_j_opens_i(), pgrouting::vrp::Tw_node::is_compatible_IJ(), and pgrouting::vrp::Tw_node::is_early_arrival().
is_pickup()
bool pgrouting::vrp::Tw_node::is_pickup () const inherited
is_pickup
To be a pickup node:
type is kPickup
demand > 0
Definition at line 141 of file tw_node.cpp.
{
     return m_type == kPickup
         && (opens() < closes())
         && (service_time() >= 0)
         && (demand() > 0);
 }
References pgrouting::vrp::Tw_node::closes(), pgrouting::vrp::Tw_node::demand(), pgrouting::vrp::Tw_node::kPickup, pgrouting::vrp::Tw_node::m_type, pgrouting::vrp::Tw_node::opens(), and pgrouting::vrp::Tw_node::service_time().
Referenced by pgrouting::vrp::Order::is_valid(), and pgrouting::vrp::Tw_node::is_valid().
is_start()
bool pgrouting::vrp::Tw_node::is_start () const inherited
@ {
is_start
To be a start node:
type is kStart
demand == 0
Definition at line 132 of file tw_node.cpp.
{
     return
         m_type == kStart
         && (opens() < closes())
         && (service_time() >= 0)
         && (demand() == 0);
 }
References pgrouting::vrp::Tw_node::closes(), pgrouting::vrp::Tw_node::demand(), pgrouting::vrp::Tw_node::kStart, pgrouting::vrp::Tw_node::m_type, pgrouting::vrp::Tw_node::opens(), and pgrouting::vrp::Tw_node::service_time().
Referenced by pgrouting::vrp::Fleet::add_vehicle(), evaluate(), has_cv(), and pgrouting::vrp::Tw_node::is_valid().
is_tight_compatible_IJ()
bool pgrouting::vrp::Tw_node::is_tight_compatible_IJ (const Tw_node & I, double speed) const inherited
Definition at line 95 of file tw_node.cpp.
{
     return
         is_compatible_IJ(I, speed)
         && !is_early_arrival(arrival_j_opens_i(I, speed))
         && !is_late_arrival(arrival_j_closes_i(I, speed));
 }
References pgrouting::vrp::Tw_node::arrival_j_closes_i(), pgrouting::vrp::Tw_node::arrival_j_opens_i(), pgrouting::vrp::Tw_node::is_compatible_IJ(), pgrouting::vrp::Tw_node::is_early_arrival(), and pgrouting::vrp::Tw_node::is_late_arrival().
is_valid()
bool pgrouting::vrp::Tw_node::is_valid () const protected inherited
Definition at line 197 of file tw_node.cpp.
{
     switch (type()) {
         case kStart:
             return is_start();
             break;
         case kEnd:
             return is_end();
             break;
         case kDump:
             return is_dump();
             break;
         case kDelivery:
             return is_delivery();
             break;
         case kPickup:
             return is_pickup();
             break;
         case kLoad:
             return is_load();
             break;
         default:
             return false;
             break;
     }
     return false;
 }
References pgrouting::vrp::Tw_node::is_delivery(), pgrouting::vrp::Tw_node::is_dump(), pgrouting::vrp::Tw_node::is_end(), pgrouting::vrp::Tw_node::is_load(), pgrouting::vrp::Tw_node::is_pickup(), pgrouting::vrp::Tw_node::is_start(), pgrouting::vrp::Tw_node::kDelivery, pgrouting::vrp::Tw_node::kDump, pgrouting::vrp::Tw_node::kEnd, pgrouting::vrp::Tw_node::kLoad, pgrouting::vrp::Tw_node::kPickup, pgrouting::vrp::Tw_node::kStart, and pgrouting::vrp::Tw_node::type().
is_waitTime_compatible_IJ()
bool pgrouting::vrp::Tw_node::is_waitTime_compatible_IJ (const Tw_node & I, double speed) const inherited
Definition at line 112 of file tw_node.cpp.
{
     return
         is_compatible_IJ(I, speed)
         && is_early_arrival(arrival_j_opens_i(I, speed));
 }
References pgrouting::vrp::Tw_node::arrival_j_opens_i(), pgrouting::vrp::Tw_node::is_compatible_IJ(), and pgrouting::vrp::Tw_node::is_early_arrival().
opens()
double pgrouting::vrp::Tw_node::opens () const inline inherited
Returns the opening time.
Definition at line 76 of file tw_node.h.
 {return m_opens;}
References pgrouting::vrp::Tw_node::m_opens.
Referenced by pgrouting::vrp::Fleet::add_vehicle(), pgrouting::vrp::Tw_node::arrival_j_opens_i(), evaluate(), pgrouting::vrp::Tw_node::is_delivery(), pgrouting::vrp::Tw_node::is_dump(), pgrouting::vrp::Tw_node::is_end(), pgrouting::vrp::Tw_node::is_load(), pgrouting::vrp::Vehicle::is_ok(), pgrouting::vrp::Tw_node::is_pickup(), pgrouting::vrp::Tw_node::is_start(), and pgrouting::vrp::Vehicle::Vehicle().
operator==()
bool pgrouting::vrp::Tw_node::operator== (const Tw_node & rhs) const inherited
Definition at line 186 of file tw_node.cpp.
{
     if (&other == this) return true;
     auto lhs = static_cast<const Node&>(
             *problem->m_base_nodes[idx()].get());
     auto rhs = static_cast<const Node&>(
             *problem->m_base_nodes[other.idx()].get());
     return lhs == rhs;
 }
References pgrouting::Identifier::idx(), pgrouting::vrp::Pgr_pickDeliver::m_base_nodes, and pgrouting::vrp::PD_problem::problem.
order()
int64_t pgrouting::vrp::Tw_node::order () const inline inherited
@ {
Returns the opening time.
Definition at line 73 of file tw_node.h.
 {return m_order;}
References pgrouting::vrp::Tw_node::m_order.
reset_id()
void pgrouting::Identifier::reset_id (int64_t _id) inherited
Definition at line 47 of file identifier.cpp.
{
     m_id = _id;
 }
References pgrouting::Identifier::m_id.
Referenced by pgrouting::vrp::Tw_node::Tw_node().
service_time()
double pgrouting::vrp::Tw_node::service_time () const inline inherited
Returns the service time for this node.
Definition at line 86 of file tw_node.h.
 {return m_service_time;}
References pgrouting::vrp::Tw_node::m_service_time.
Referenced by arrival_i_arrives_j(), pgrouting::vrp::Tw_node::arrival_j_closes_i(), pgrouting::vrp::Tw_node::arrival_j_opens_i(), pgrouting::vrp::Vehicle::deltaTime(), evaluate(), pgrouting::vrp::Tw_node::is_delivery(), pgrouting::vrp::Tw_node::is_dump(), pgrouting::vrp::Tw_node::is_end(), pgrouting::vrp::Tw_node::is_load(), pgrouting::vrp::Tw_node::is_pickup(), pgrouting::vrp::Tw_node::is_start(), and pgrouting::vrp::operator<<().
total_service_time()
double pgrouting::vrp::Vehicle_node::total_service_time () const inline
_time spent by the truck servicing the nodes
Definition at line 105 of file vehicle_node.h.
 {return m_tot_service_time;}
References m_tot_service_time.
total_time()
double pgrouting::vrp::Vehicle_node::total_time () const inline
Truck's travel duration up to this node.
Definition at line 96 of file vehicle_node.h.
 {return m_departure_time;}
References m_departure_time.
total_travel_time()
double pgrouting::vrp::Vehicle_node::total_travel_time () const inline
_time spent moving between nodes by the truck
Definition at line 99 of file vehicle_node.h.
 {return m_tot_travel_time;}
References m_tot_travel_time.
total_wait_time()
double pgrouting::vrp::Vehicle_node::total_wait_time () const inline
_time spent by the truck waiting for nodes to open
Definition at line 102 of file vehicle_node.h.
 {return m_tot_wait_time;}
References m_tot_wait_time.
travel_time()
double pgrouting::vrp::Vehicle_node::travel_time () const inline
@ {
Truck's travel_time from previous node to this node.
Definition at line 62 of file vehicle_node.h.
 {return m_travel_time;}
References m_travel_time.
Referenced by evaluate(), and pgrouting::vrp::operator<<().
travel_time_to()
double pgrouting::vrp::Tw_node::travel_time_to (const Tw_node & other, double speed) const inherited
time = distance / speed.
TODO(vicky) shall call Node or Dnode static cast won't work I think
Todo:
TODO evaluate with matrix also
Definition at line 40 of file tw_node.cpp.
{
     auto from =  problem->m_base_nodes[idx()].get();
     auto destination = problem->m_base_nodes[to.idx()].get();
     pgassert(speed != 0);
     return from->distance(destination) / speed;
 }
References pgrouting::Identifier::idx(), pgrouting::vrp::Pgr_pickDeliver::m_base_nodes, pgassert, and pgrouting::vrp::PD_problem::problem.
Referenced by arrival_i_arrives_j(), pgrouting::vrp::Tw_node::arrival_j_closes_i(), pgrouting::vrp::Tw_node::arrival_j_opens_i(), pgrouting::vrp::Vehicle::deltaTime(), and pgrouting::vrp::operator<<().
twvTot()
int pgrouting::vrp::Vehicle_node::twvTot () const inline
@ {
Truck's total times it has violated time windows.
Definition at line 87 of file vehicle_node.h.
 {return m_twvTot;}
References m_twvTot.
Referenced by pgrouting::vrp::operator<<().
type()
NodeType pgrouting::vrp::Tw_node::type () const inline inherited
Returns the type of this node.
Definition at line 89 of file tw_node.h.
 {return m_type;}
References pgrouting::vrp::Tw_node::m_type.
Referenced by pgrouting::vrp::Tw_node::is_valid(), and pgrouting::vrp::Tw_node::type_str().
type_str()
std::string pgrouting::vrp::Tw_node::type_str () const inherited
Definition at line 119 of file tw_node.cpp.
{
     switch (type()) {
         case kStart: return "START"; break;
         case kEnd: return "END"; break;
         case kDump: return "DUMP"; break;
         case kLoad: return "LOAD"; break;
         case kPickup: return "PICKUP"; break;
         case kDelivery: return "DELIVERY"; break;
         default: return "UNKNOWN";
     }
 }
References pgrouting::vrp::Tw_node::kDelivery, pgrouting::vrp::Tw_node::kDump, pgrouting::vrp::Tw_node::kEnd, pgrouting::vrp::Tw_node::kLoad, pgrouting::vrp::Tw_node::kPickup, pgrouting::vrp::Tw_node::kStart, and pgrouting::vrp::Tw_node::type().
Referenced by pgrouting::vrp::operator<<().
wait_time()
double pgrouting::vrp::Vehicle_node::wait_time () const inline
Truck's wait_time at this node.
Definition at line 68 of file vehicle_node.h.
 {return m_wait_time;}
References m_wait_time.
Referenced by evaluate(), and pgrouting::vrp::operator<<().
window_length()
double pgrouting::vrp::Tw_node::window_length () const inline inherited
Returns the length of time between the opening and closing.
Definition at line 92 of file tw_node.h.
 {return m_closes - m_opens;}
References pgrouting::vrp::Tw_node::m_closes, and pgrouting::vrp::Tw_node::m_opens.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const Vehicle_node & node) friend
@ {
Definition at line 101 of file vehicle_node.cpp.
{
     log << static_cast<const Tw_node&>(v)
         << " twv = " << v.has_twv()
         << ", twvTot = " << v.twvTot()
         << ", cvTot = " << v.cvTot()
         << ", cargo = " << v.cargo()
         << ", travel_time = " << v.travel_time()
         << ", arrival_time = " << v.arrival_time()
         << ", wait_time = " << v.wait_time()
         << ", service_time = " << v.service_time()
         << ", departure_time = " << v.departure_time();
     return log;
 }
Member Data Documentation
m_arrival_time
double pgrouting::vrp::Vehicle_node::m_arrival_time private
Arrival time at this node.
Definition at line 167 of file vehicle_node.h.
Referenced by arrival_time(), deltaGeneratesTWV(), evaluate(), and has_twv().
m_cargo
double pgrouting::vrp::Vehicle_node::m_cargo private
@ {
Accumulated cargo
Definition at line 177 of file vehicle_node.h.
Referenced by cargo(), evaluate(), and has_cv().
m_closes
double pgrouting::vrp::Tw_node::m_closes private inherited
closing time of the node
Definition at line 275 of file tw_node.h.
Referenced by pgrouting::vrp::Tw_node::closes(), pgrouting::vrp::Tw_node::is_late_arrival(), pgrouting::vrp::operator<<(), pgrouting::vrp::Tw_node::Tw_node(), and pgrouting::vrp::Tw_node::window_length().
m_cvTot
int pgrouting::vrp::Vehicle_node::m_cvTot private
Total count of CV.
Definition at line 179 of file vehicle_node.h.
Referenced by cvTot(), evaluate(), and feasible().
m_delta_time
double pgrouting::vrp::Vehicle_node::m_delta_time private
Departure time - last nodes departure time.
Definition at line 170 of file vehicle_node.h.
Referenced by delta_time(), and evaluate().
m_demand
double pgrouting::vrp::Tw_node::m_demand private inherited
The demand for the Node.
Definition at line 277 of file tw_node.h.
Referenced by pgrouting::vrp::Tw_node::demand(), pgrouting::vrp::operator<<(), and pgrouting::vrp::Tw_node::Tw_node().
m_departure_time
double pgrouting::vrp::Vehicle_node::m_departure_time private
Definition at line 169 of file vehicle_node.h.
Referenced by departure_time(), evaluate(), and total_time().
m_id
int64_t pgrouting::Identifier::m_id private inherited
Definition at line 53 of file identifier.h.
Referenced by pgrouting::Identifier::id(), and pgrouting::Identifier::reset_id().
m_idx
size_t pgrouting::Identifier::m_idx private inherited
Definition at line 52 of file identifier.h.
Referenced by pgrouting::Identifier::idx().
m_opens
double pgrouting::vrp::Tw_node::m_opens private inherited
opening time of the node
Definition at line 274 of file tw_node.h.
Referenced by pgrouting::vrp::Tw_node::is_early_arrival(), pgrouting::vrp::Tw_node::opens(), pgrouting::vrp::operator<<(), pgrouting::vrp::Tw_node::Tw_node(), and pgrouting::vrp::Tw_node::window_length().
m_order
int64_t pgrouting::vrp::Tw_node::m_order private inherited
order to which it belongs
Definition at line 273 of file tw_node.h.
Referenced by pgrouting::vrp::Tw_node::order().
m_service_time
double pgrouting::vrp::Tw_node::m_service_time private inherited
Definition at line 276 of file tw_node.h.
Referenced by pgrouting::vrp::operator<<(), pgrouting::vrp::Tw_node::service_time(), and pgrouting::vrp::Tw_node::Tw_node().
m_tot_service_time
double pgrouting::vrp::Vehicle_node::m_tot_service_time private
Definition at line 182 of file vehicle_node.h.
Referenced by evaluate(), and total_service_time().
m_tot_travel_time
double pgrouting::vrp::Vehicle_node::m_tot_travel_time private
Accumulated travel time.
Definition at line 181 of file vehicle_node.h.
Referenced by evaluate(), and total_travel_time().
m_tot_wait_time
double pgrouting::vrp::Vehicle_node::m_tot_wait_time private
Accumulated wait time.
Definition at line 180 of file vehicle_node.h.
Referenced by evaluate(), and total_wait_time().
m_travel_time
double pgrouting::vrp::Vehicle_node::m_travel_time private
@ {
Travel time from last node
Definition at line 166 of file vehicle_node.h.
Referenced by evaluate(), and travel_time().
m_twvTot
int pgrouting::vrp::Vehicle_node::m_twvTot private
Total count of TWV.
Definition at line 178 of file vehicle_node.h.
Referenced by evaluate(), feasible(), and twvTot().
m_type
NodeType pgrouting::vrp::Tw_node::m_type private inherited
The demand for the Node.
Definition at line 278 of file tw_node.h.
Referenced by pgrouting::vrp::Tw_node::arrival_j_closes_i(), pgrouting::vrp::Tw_node::arrival_j_opens_i(), pgrouting::vrp::Tw_node::is_compatible_IJ(), pgrouting::vrp::Tw_node::is_delivery(), pgrouting::vrp::Tw_node::is_dump(), pgrouting::vrp::Tw_node::is_end(), pgrouting::vrp::Tw_node::is_load(), pgrouting::vrp::Tw_node::is_pickup(), pgrouting::vrp::Tw_node::is_start(), pgrouting::vrp::Tw_node::Tw_node(), and pgrouting::vrp::Tw_node::type().
m_wait_time
double pgrouting::vrp::Vehicle_node::m_wait_time private
Wait time at this node when early arrival.
Definition at line 168 of file vehicle_node.h.
Referenced by evaluate(), and wait_time().
msg
Pgr_messages pgrouting::vrp::PD_problem::msg static inherited
Definition at line 49 of file pd_problem.h.
Referenced by pgrouting::vrp::Fleet::add_vehicle(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), pgrouting::vrp::Vehicle_pickDeliver::do_while_feasable(), pgrouting::vrp::Initial_solution::do_while_foo(), pgrouting::vrp::Pgr_pickDeliver::get_postgres_result(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Fleet::is_fleet_ok(), pgrouting::vrp::Pgr_pickDeliver::nodesOK(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), pgrouting::vrp::Optimize::Optimize(), pgrouting::vrp::Pgr_pickDeliver::optimize(), pgrouting::vrp::PD_problem::PD_problem(), pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Optimize::save_if_best(), pgrouting::vrp::Solution::Solution(), pgrouting::vrp::Pgr_pickDeliver::solve(), pgrouting::vrp::Optimize::swap_order(), and pgrouting::vrp::Vehicle::Vehicle().
problem
Pgr_pickDeliver * pgrouting::vrp::PD_problem::problem static protected inherited
Definition at line 52 of file pd_problem.h.
Referenced by pgrouting::vrp::PD_Orders::add_order(), pgrouting::vrp::Fleet::add_vehicle(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), pgrouting::vrp::Dnode::distance(), pgrouting::vrp::Solution::get_kind(), pgrouting::vrp::Pgr_pickDeliver::get_kind(), pgrouting::vrp::operator<<(), pgrouting::vrp::Tw_node::operator==(), pgrouting::vrp::PD_problem::PD_problem(), and pgrouting::vrp::Tw_node::travel_time_to().
The documentation for this class was generated from the following files:
vehicle_node.h
vehicle_node.cpp