PGROUTING: pgrouting::Basic_vertex Class Reference
pgrouting::Basic_vertex Class Reference
#include "basic_vertex.h"
Public Member Functions
Basic_vertex ()
Basic_vertex (const Basic_vertex &v)
Basic_vertex (const int64_t _id)
Basic_vertex (const pgr_edge_t &other, bool is_source)
void cp_members (const Basic_vertex &other)
Basic_vertex & operator= (const Basic_vertex &)=default
Public Attributes
int64_t id
size_t vertex_index
Friends
std::ostream & operator<< (std::ostream &log, const Basic_vertex &v)
Detailed Description
Definition at line 40 of file basic_vertex.h.
Constructor & Destructor Documentation
Basic_vertex() [1/4]
pgrouting::Basic_vertex::Basic_vertex () inline
Definition at line 42 of file basic_vertex.h.
                     :
          id(0) {}
Basic_vertex() [2/4]
pgrouting::Basic_vertex::Basic_vertex (const Basic_vertex & v) inline
Definition at line 44 of file basic_vertex.h.
                                          :
          id(v.id) {}
Basic_vertex() [3/4]
pgrouting::Basic_vertex::Basic_vertex (const int64_t _id) inline explicit
Definition at line 47 of file basic_vertex.h.
References operator=().
                                               :
          id(_id) {}
Basic_vertex() [4/4]
pgrouting::Basic_vertex::Basic_vertex (const pgr_edge_t & other, bool is_source) inline
Definition at line 52 of file basic_vertex.h.
                                                            :
          id(is_source? other.source : other.target) {}
Member Function Documentation
cp_members()
void pgrouting::Basic_vertex::cp_members (const Basic_vertex & other) inline
Definition at line 55 of file basic_vertex.h.
References id, and operator<<.
{
          this->id = other.id;
      }
operator=()
Basic_vertex& pgrouting::Basic_vertex::operator= (const Basic_vertex &) default
Referenced by Basic_vertex().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & log, const Basic_vertex & v) friend
Definition at line 37 of file basic_vertex.cpp.
Referenced by cp_members().
{
         log << v.id;
         return log;
     }
Member Data Documentation
id
int64_t pgrouting::Basic_vertex::id
Definition at line 62 of file basic_vertex.h.
Referenced by pgrouting::check_vertices(), cp_members(), pgrouting::extract_vertices(), and pgrouting::operator<<().
vertex_index
size_t pgrouting::Basic_vertex::vertex_index
Definition at line 63 of file basic_vertex.h.
The documentation for this class was generated from the following file:
basic_vertex.h