PGROUTING: pgrouting::trsp::TrspHandler Class Reference
pgrouting::trsp::TrspHandler Class Reference
#include "trspHandler.hpp"
Classes
class CostHolder
class Predecessor
Public Member Functions
TrspHandler (std::vector< Edge_t > &edges, const bool directed, const std::vector< Rule > &ruleList)
TrspHandler (std::vector< Edge_t > &edges, const std::vector< Edge_t > &new_edges, const bool directed, const std::vector< Rule > &ruleList)
~TrspHandler (void)=default
void clear ()
std::string get_error () const
get_error
std::string get_log () const
get_log
std::string get_notice () const
get_notice
bool has_error () const
get_error
std::deque< Path > process (const std::map< int64_t, std::set< int64_t > > &)
process
Public Attributes
std::ostringstream error
Stores the error information.
std::ostringstream log
Stores the hint information.
std::ostringstream notice
Stores the notice information.
Private Types
typedef std::pair< double, std::pair< int64_t, bool > > PDP
Used in the priority queue.
enum Position { ILLEGAL = -1 , RC_EDGE = 0 , C_EDGE = 1 }
predecessor edge
Private Member Functions
void add_to_que (double, size_t, bool)
bool addEdge (Edge_t, bool)
void connectEndEdge (size_t, size_t)
void connectStartEdge (size_t, size_t)
void construct_graph (const std::vector< Edge_t > &, const std::vector< Edge_t > &, const bool)
double construct_path (int64_t, Position)
EdgeInfo dijkstra_exploration ()
void explore (int64_t, const EdgeInfo, bool)
double get_tot_cost (double, size_t, bool)
double getRestrictionCost (int64_t, const EdgeInfo &, bool)
void initialize_que ()
int initialize_restrictions (const std::vector< Rule > &)
Path process (const int64_t, const int64_t)
process
Path process_trsp (size_t edge_count)
void renumber_edges (std::vector< Edge_t > &)
void renumber_edges (std::vector< Edge_t > &, std::vector< Edge_t > &)
Private Attributes
std::map< int64_t, std::vector< size_t > > m_adjacency
m_adjacency[vertex] = {edges}
int64_t m_current_node
std::vector< CostHolder > m_dCost
std::vector< EdgeInfo > m_edges
int64_t m_end_vertex
std::map< int64_t, int64_t > m_id_to_idx
std::map< int64_t, int64_t > m_idx_to_id
std::map< int64_t, int64_t > m_mapEdgeId2Index
Used only to verify that there are no reppetitions inserted the way it works, repeating edges id is not allowed TODO when using points edges id are repeated.
std::vector< Predecessor > m_parent
Path m_path
std::priority_queue< PDP, std::vector< PDP >, std::greater< PDP > > m_que
std::map< int64_t, std::vector< Rule > > m_ruleTable
int64_t m_start_vertex
Detailed Description
Definition at line 54 of file trspHandler.hpp.
Member Typedef Documentation
PDP
typedef std::pair<double, std::pair<int64_t, bool> > pgrouting::trsp::TrspHandler::PDP private
Used in the priority queue.
Definition at line 58 of file trspHandler.hpp.
Member Enumeration Documentation
Position
enum pgrouting::trsp::TrspHandler::Position private
predecessor edge
because each row represents 2 edges, this enumeration is needed for the predecessors
C_EDGE: If the predecessor comes from the "cost" edge
RC_EDGE: If the predecessor comes from the "reverse_cost" edge
ILLEGAL: Its not a predecessor of anything
The "legal" values are indices to vectors
Enumerator
ILLEGAL
RC_EDGE
C_EDGE
Definition at line 70 of file trspHandler.hpp.
{ILLEGAL = -1, RC_EDGE = 0, C_EDGE = 1};
Constructor & Destructor Documentation
TrspHandler() [1/2]
pgrouting::trsp::TrspHandler::TrspHandler (std::vector< Edge_t > & edges, const std::vector< Edge_t > & new_edges, const bool directed, const std::vector< Rule > & ruleList)
Definition at line 60 of file trspHandler.cpp.
                                         :
    m_ruleTable() {
    initialize_restrictions(ruleList);
    auto point_edges = new_edges;
    renumber_edges(edges, point_edges);
    for (const auto& id :  m_id_to_idx) {
        m_idx_to_id[id.second] = id.first;
    }
    construct_graph(edges, point_edges, directed);
}
References construct_graph(), initialize_restrictions(), m_id_to_idx, m_idx_to_id, and renumber_edges().
TrspHandler() [2/2]
pgrouting::trsp::TrspHandler::TrspHandler (std::vector< Edge_t > & edges, const bool directed, const std::vector< Rule > & ruleList)
Definition at line 45 of file trspHandler.cpp.
                                         :
    m_ruleTable() {
    initialize_restrictions(ruleList);
    renumber_edges(edges);
    for (const auto& id :  m_id_to_idx) {
        m_idx_to_id[id.second] = id.first;
    }
    construct_graph(edges, std::vector<Edge_t>(), directed);
}
References construct_graph(), initialize_restrictions(), m_id_to_idx, m_idx_to_id, and renumber_edges().
~TrspHandler()
pgrouting::trsp::TrspHandler::~TrspHandler (void) default
Member Function Documentation
add_to_que()
void pgrouting::trsp::TrspHandler::add_to_que (double cost, size_t e_idx, bool isStart) private
Definition at line 355 of file trspHandler.cpp.
{
    m_que.push(std::make_pair(cost, std::make_pair(e_idx, isStart)));
}
References m_que.
Referenced by explore(), and initialize_que().
addEdge()
bool pgrouting::trsp::TrspHandler::addEdge (Edge_t edgeIn, bool directed) private
Definition at line 516 of file trspHandler.cpp.
{
    /*
     * making all "cost" > 0
     */
    if (edgeIn.cost < 0 && edgeIn.reverse_cost > 0) {
        std::swap(edgeIn.cost, edgeIn.reverse_cost);
        std::swap(edgeIn.source, edgeIn.target);
    }
    /* This gives a value to reverse_cost when:"
     * graph is undirected
     * reverse_cost is negative
     */
    if (!directed && edgeIn.reverse_cost < 0) {
        edgeIn.reverse_cost = edgeIn.cost;
    }
    /*
     * the index of this new edge in the edges container is
     *  m_edges.size()
     */
    EdgeInfo edge(edgeIn, m_edges.size());
    /*
     * Add to the set of edges
     */
    m_edges.push_back(edge);
    EdgeInfo &newEdge = m_edges[m_edges.size()-1];
    /*
     *  Searching the start node for connectivity
     */
    auto itNodeMap = m_adjacency.find(edgeIn.source);
    if (itNodeMap != m_adjacency.end()) {
        for (const auto &e_idx : itNodeMap->second) {
            connectStartEdge(edge.idx(), e_idx);
        }
    }
    /*
     *  Searching the end node for connectivity
     */
    itNodeMap = m_adjacency.find(edgeIn.target);
    if (itNodeMap != m_adjacency.end()) {
        for (const auto &e_idx : itNodeMap->second) {
            connectEndEdge(edge.idx(), e_idx);
        }
    }
    /*
     * Add the edges to the adjacency list
     */
    m_adjacency[edgeIn.source].push_back(newEdge.idx());
    m_adjacency[edgeIn.target].push_back(newEdge.idx());
    return true;
}
References connectEndEdge(), connectStartEdge(), Edge_t::cost, pgrouting::trsp::EdgeInfo::idx(), m_adjacency, m_edges, Edge_t::reverse_cost, Edge_t::source, and Edge_t::target.
Referenced by construct_graph().
clear()
void pgrouting::trsp::TrspHandler::clear ()
Definition at line 133 of file trspHandler.cpp.
{
    m_parent.clear();
    m_dCost.clear();
    m_path.clear();
}
References pgrouting::Path::clear(), m_dCost, m_parent, and m_path.
Referenced by process().
connectEndEdge()
void pgrouting::trsp::TrspHandler::connectEndEdge (size_t firstEdge_idx, size_t secondEdge_idx) private
Definition at line 493 of file trspHandler.cpp.
{
    EdgeInfo &firstEdge = m_edges[firstEdge_idx];
    EdgeInfo &secondEdge = m_edges[secondEdge_idx];
    if (firstEdge.cost() >= 0.0) {
        firstEdge.connect_endEdge(secondEdge_idx);
    }
    if (firstEdge.endNode() == secondEdge.startNode()
            && secondEdge.r_cost() >= 0.0) {
        secondEdge.connect_startEdge(firstEdge_idx);
    }
    if (firstEdge.endNode() == secondEdge.endNode()
            && secondEdge.cost() >= 0.0) {
        secondEdge.connect_endEdge(firstEdge_idx);
    }
}
References pgrouting::trsp::EdgeInfo::connect_endEdge(), pgrouting::trsp::EdgeInfo::connect_startEdge(), pgrouting::trsp::EdgeInfo::cost(), pgrouting::trsp::EdgeInfo::endNode(), m_edges, pgrouting::trsp::EdgeInfo::r_cost(), and pgrouting::trsp::EdgeInfo::startNode().
Referenced by addEdge().
connectStartEdge()
void pgrouting::trsp::TrspHandler::connectStartEdge (size_t firstEdge_idx, size_t secondEdge_idx) private
Definition at line 470 of file trspHandler.cpp.
{
    EdgeInfo &firstEdge = m_edges[firstEdge_idx];
    EdgeInfo &secondEdge = m_edges[secondEdge_idx];
    if (firstEdge.r_cost() >= 0.0) {
        firstEdge.connect_startEdge(secondEdge_idx);
    }
    if (firstEdge.startNode() == secondEdge.startNode()
            && secondEdge.r_cost() >= 0.0) {
            secondEdge.connect_startEdge(firstEdge_idx);
    }
    if (firstEdge.startNode() == secondEdge.endNode()
            &&secondEdge.cost() >= 0.0) {
        secondEdge.connect_endEdge(firstEdge_idx);
    }
}
References pgrouting::trsp::EdgeInfo::connect_endEdge(), pgrouting::trsp::EdgeInfo::connect_startEdge(), pgrouting::trsp::EdgeInfo::cost(), pgrouting::trsp::EdgeInfo::endNode(), m_edges, pgrouting::trsp::EdgeInfo::r_cost(), and pgrouting::trsp::EdgeInfo::startNode().
Referenced by addEdge().
construct_graph()
void pgrouting::trsp::TrspHandler::construct_graph (const std::vector< Edge_t > & edges, const std::vector< Edge_t > & new_edges, const bool directed) private
Definition at line 454 of file trspHandler.cpp.
{
    for (const auto &e : edges) {
        addEdge(e, directed);
    }
    for (const auto &e : new_edges) {
        addEdge(e, directed);
    }
    m_mapEdgeId2Index.clear();
}
References addEdge(), and m_mapEdgeId2Index.
Referenced by TrspHandler(), and TrspHandler().
construct_path()
double pgrouting::trsp::TrspHandler::construct_path (int64_t ed_id, Position pos) private
Definition at line 141 of file trspHandler.cpp.
{
    if (pos == ILLEGAL) return (std::numeric_limits<double>::max)();
    pgassert(pos != ILLEGAL);
    if (m_parent[static_cast<size_t>(ed_id)].isIllegal(pos)) {
        Path_t pelement = {};
        auto cur_edge = &m_edges[static_cast<size_t>(ed_id)];
        if (pos == RC_EDGE) {
            pelement.node = cur_edge->startNode();
            pelement.cost = cur_edge->cost();
        } else {
            pelement.node = cur_edge->endNode();
            pelement.cost = cur_edge->r_cost();
        }
        pelement.edge = cur_edge->edgeID();
        m_path.push_back(pelement);
        pgassert(m_path.start_id() == m_start_vertex);
        return pelement.cost;
    }
    double ret = construct_path(
        static_cast<int64_t>(m_parent[static_cast<size_t>(ed_id)].e_idx[static_cast<size_t>(pos)]),
        static_cast<Position>(m_parent[static_cast<size_t>(ed_id)].v_pos[static_cast<size_t>(pos)]));
    Path_t pelement = {};
    auto cur_edge = &m_edges[static_cast<size_t>(ed_id)];
    if (pos == RC_EDGE) {
        pelement.node = cur_edge->startNode();
        pelement.cost = m_dCost[static_cast<size_t>(ed_id)].endCost - ret;
        ret = m_dCost[static_cast<size_t>(ed_id)].endCost;
    } else {
        pelement.node = cur_edge->endNode();
        pelement.cost = m_dCost[static_cast<size_t>(ed_id)].startCost - ret;
        ret = m_dCost[static_cast<size_t>(ed_id)].startCost;
    }
    pelement.edge = cur_edge->edgeID();
    m_path.push_back(pelement);
    return ret;
}
References construct_path(), Path_t::cost, Path_t::edge, ILLEGAL, m_dCost, m_edges, m_parent, m_path, m_start_vertex, Path_t::node, pgassert, pgrouting::Path::push_back(), RC_EDGE, and pgrouting::Path::start_id().
Referenced by construct_path(), and process_trsp().
dijkstra_exploration()
EdgeInfo pgrouting::trsp::TrspHandler::dijkstra_exploration () private
Definition at line 380 of file trspHandler.cpp.
{
    EdgeInfo cur_edge;
    pgassert(m_current_node == m_start_vertex);
    while (!m_que.empty()) {
        auto cur_pos = m_que.top();
        m_que.pop();
        auto cure_idxex = cur_pos.second.first;
        cur_edge = m_edges[static_cast<size_t>(cure_idxex)];
        if (cur_pos.second.second) {
            /*
             * explore edges connected to end node
             */
            m_current_node = cur_edge.endNode();
            if (cur_edge.cost() < 0.0) continue;
            if (m_current_node == m_end_vertex) break;
            explore(m_current_node, cur_edge, false);
        } else {
            /*
             *  explore edges connected to start node
             */
            m_current_node = cur_edge.startNode();
            if (cur_edge.r_cost() < 0.0) continue;
            if (m_current_node == m_end_vertex) break;
            explore(m_current_node, cur_edge, true);
        }
    }
    return cur_edge;
}
References pgrouting::trsp::EdgeInfo::cost(), pgrouting::trsp::EdgeInfo::endNode(), explore(), m_current_node, m_edges, m_end_vertex, m_que, m_start_vertex, pgassert, pgrouting::trsp::EdgeInfo::r_cost(), and pgrouting::trsp::EdgeInfo::startNode().
Referenced by process_trsp().
explore()
void pgrouting::trsp::TrspHandler::explore (int64_t cur_node, const EdgeInfo cur_edge, bool isStart) private
Definition at line 231 of file trspHandler.cpp.
                      {
    double totalCost;
    auto vecIndex = cur_edge.get_idx(isStart);
    for (const auto &index : vecIndex) {
        auto edge = m_edges[index];
        auto extra_cost = getRestrictionCost(
                static_cast<int64_t>(cur_edge.idx()),
                edge, isStart);
        if ((edge.startNode() == cur_node) && (edge.cost() >= 0.0)) {
            totalCost = get_tot_cost(
                    edge.cost() + extra_cost,
                    cur_edge.idx(),
                    isStart);
            if (totalCost < m_dCost[index].endCost) {
                m_dCost[index].endCost = totalCost;
                m_parent[edge.idx()].v_pos[RC_EDGE] = isStart? C_EDGE : RC_EDGE;
                m_parent[edge.idx()].e_idx[RC_EDGE] =
                    cur_edge.idx();
                add_to_que(totalCost, edge.idx(), true);
            }
        }
       if ((edge.endNode() == cur_node) && (edge.r_cost() >= 0.0)) {
            totalCost = get_tot_cost(
                    edge.r_cost() + extra_cost,
                    cur_edge.idx(),
                    isStart);
            if (totalCost < m_dCost[index].startCost) {
                m_dCost[index].startCost = totalCost;
                m_parent[edge.idx()].v_pos[C_EDGE] = isStart? C_EDGE : RC_EDGE;
                m_parent[edge.idx()].e_idx[C_EDGE] = cur_edge.idx();
                add_to_que(totalCost, edge.idx(), false);
            }
        }
    }  // for
}
References add_to_que(), C_EDGE, pgrouting::trsp::EdgeInfo::get_idx(), get_tot_cost(), getRestrictionCost(), pgrouting::trsp::EdgeInfo::idx(), m_dCost, m_edges, m_parent, and RC_EDGE.
Referenced by dijkstra_exploration().
get_error()
std::string pgrouting::Pgr_messages::get_error () const inherited
get_error
Returns
the current contents of the log and clears the log
Definition at line 52 of file messages.cpp.
{
    auto str = error.str();
    return str;
}
References pgrouting::Pgr_messages::error.
Referenced by pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), do_shortestPath(), pgr_do_pickDeliver(), pgr_do_pickDeliverEuclidean(), pgr_do_trsp_withPoints(), pgr_do_trspVia_withPoints(), pgr_do_withPoints(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), and pgr_do_withPointsVia().
get_log()
std::string pgrouting::Pgr_messages::get_log () const inherited
get_log
Returns
the current contents of the log and clears the log
Definition at line 35 of file messages.cpp.
{
    auto str = log.str();
    return str;
}
References pgrouting::Pgr_messages::log.
Referenced by pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), do_shortestPath(), pgr_do_bipartite(), pgr_do_boyerMyrvold(), pgr_do_LTDTree(), pgr_do_makeConnected(), pgr_do_pickDeliver(), pgr_do_pickDeliverEuclidean(), pgr_do_trsp_withPoints(), pgr_do_trspVia_withPoints(), pgr_do_withPoints(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), and pgr_do_withPointsVia().
get_notice()
std::string pgrouting::Pgr_messages::get_notice () const inherited
get_notice
Returns
the current contents of the log and clears the log
Definition at line 41 of file messages.cpp.
{
    auto str = notice.str();
    return str;
}
References pgrouting::Pgr_messages::notice.
get_tot_cost()
double pgrouting::trsp::TrspHandler::get_tot_cost (double cost, size_t edge_idx, bool isStart) private
Definition at line 217 of file trspHandler.cpp.
                      {
    if (isStart) {
        return m_dCost[edge_idx].startCost +
            cost;
    }
    return m_dCost[edge_idx].endCost +
        cost;
}
References m_dCost.
Referenced by explore().
getRestrictionCost()
double pgrouting::trsp::TrspHandler::getRestrictionCost (int64_t edge_ind, const EdgeInfo & edge, bool isStart) private
Definition at line 185 of file trspHandler.cpp.
                      {
    double cost = 0.0;
    int64_t edge_id = edge.edgeID();
    if (m_ruleTable.find(edge_id) == m_ruleTable.end()) {
        return(0.0);
    }
    auto vecRules = m_ruleTable[edge_id];
    int64_t st_edge_ind = edge_ind;
    for (const auto &rule : vecRules) {
        bool flag = true;
        int64_t v_pos = (isStart? C_EDGE : RC_EDGE);
        edge_ind = st_edge_ind;
        pgassert(!(edge_ind == -1));
        for (auto const &precedence : rule.precedencelist()) {
            if (precedence != m_edges[static_cast<size_t>(edge_ind)].edgeID()) {
                flag = false;
                break;
            }
            auto m_parent_ind = m_parent[static_cast<size_t>(edge_ind)].e_idx[static_cast<size_t>(v_pos)];
            v_pos = m_parent[static_cast<size_t>(edge_ind)].v_pos[static_cast<size_t>(v_pos)];
            edge_ind = static_cast<int64_t>(m_parent_ind);
        }
        cost += flag? rule.cost() : 0;
    }
    return cost;
}
References C_EDGE, pgrouting::trsp::EdgeInfo::edgeID(), m_edges, m_parent, m_ruleTable, pgassert, and RC_EDGE.
Referenced by explore().
has_error()
bool pgrouting::Pgr_messages::has_error () const inherited
get_error
Returns
the current contents of the log and clears the log
Definition at line 47 of file messages.cpp.
{
    return  !error.str().empty();
}
References pgrouting::Pgr_messages::error.
Referenced by do_shortestPath(), pgr_do_trsp_withPoints(), pgr_do_trspVia_withPoints(), pgr_do_withPoints(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), and pgr_do_withPointsVia().
initialize_que()
void pgrouting::trsp::TrspHandler::initialize_que () private
Definition at line 359 of file trspHandler.cpp.
{
    /*
     * For each adjacent edge to the start_vertex
     */
    for (const auto source : m_adjacency[m_start_vertex]) {
        EdgeInfo &cur_edge = m_edges[source];
        if (cur_edge.startNode() == m_start_vertex && cur_edge.cost() >= 0.0) {
            m_dCost[cur_edge.idx()].endCost = cur_edge.cost();
            m_parent[cur_edge.idx()].v_pos[0] = ILLEGAL;
            add_to_que(cur_edge.cost(), cur_edge.idx(), true);
        }
        if (cur_edge.endNode() == m_start_vertex && cur_edge.r_cost() >= 0.0) {
            m_dCost[cur_edge.idx()].startCost = cur_edge.r_cost();
            m_parent[cur_edge.idx()].v_pos[1] = ILLEGAL;
            add_to_que(cur_edge.r_cost(), cur_edge.idx(), false);
        }
    }
}
References add_to_que(), pgrouting::trsp::EdgeInfo::cost(), pgrouting::trsp::EdgeInfo::endNode(), pgrouting::trsp::EdgeInfo::idx(), ILLEGAL, m_adjacency, m_dCost, m_edges, m_parent, m_start_vertex, pgrouting::trsp::EdgeInfo::r_cost(), and pgrouting::trsp::EdgeInfo::startNode().
Referenced by process_trsp().
initialize_restrictions()
int pgrouting::trsp::TrspHandler::initialize_restrictions (const std::vector< Rule > & ruleList) private
Definition at line 282 of file trspHandler.cpp.
{
    for (const auto &rule : ruleList) {
        auto dest_edge_id = rule.dest_id();
        if (m_ruleTable.find(dest_edge_id) != m_ruleTable.end()) {
            m_ruleTable[dest_edge_id].push_back(rule);
        } else {
            std::vector<Rule> r;
            r.push_back(rule);
            m_ruleTable.insert(std::make_pair(dest_edge_id, r));
        }
    }
    return true;
}
References m_ruleTable.
Referenced by TrspHandler(), and TrspHandler().
process() [1/2]
Path pgrouting::trsp::TrspHandler::process (const int64_t start_vertex, const int64_t end_vertex) private
process
does the processisng
Definition at line 304 of file trspHandler.cpp.
{
    if (m_id_to_idx.find(start_vertex) == m_id_to_idx.end()
        || m_id_to_idx.find(end_vertex) == m_id_to_idx.end()) {
        return Path();
    }
    clear();
    pgassert(m_id_to_idx.find(start_vertex) != m_id_to_idx.end());
    pgassert(m_id_to_idx.find(end_vertex) != m_id_to_idx.end());
    m_start_vertex = m_id_to_idx.at(start_vertex);
    m_end_vertex = m_id_to_idx.at(end_vertex);
    pgassert(m_idx_to_id.at(m_start_vertex) == start_vertex);
    pgassert(m_idx_to_id.at(m_end_vertex) == end_vertex);
    Path tmp(m_start_vertex, m_end_vertex);
    m_path = tmp;
    if (m_adjacency.find(m_start_vertex) == m_adjacency.end()) {
        return Path();
    }
    if (m_adjacency.find(m_end_vertex) == m_adjacency.end()) {
        return Path();
    }
    return process_trsp(m_edges.size());
}
References clear(), m_adjacency, m_edges, m_end_vertex, m_id_to_idx, m_idx_to_id, m_path, m_start_vertex, pgassert, and process_trsp().
process() [2/2]
std::deque< Path > pgrouting::trsp::TrspHandler::process (const std::map< int64_t, std::set< int64_t > > & combinations)
process
does the processisng
Definition at line 340 of file trspHandler.cpp.
          {
    std::deque<Path> paths;
    for (const auto &c : combinations) {
        for (const auto target : c.second) {
            paths.push_back(process(c.first, target));
        }
    }
    return paths;
}
References process().
Referenced by pgr_do_trsp(), pgr_do_trsp_withPoints(), pgr_do_trspVia(), pgr_do_trspVia_withPoints(), and process().
process_trsp()
Path pgrouting::trsp::TrspHandler::process_trsp (size_t edge_count) private
Definition at line 416 of file trspHandler.cpp.
{
    pgassert(m_path.start_id() == m_start_vertex);
    pgassert(m_path.end_id() == m_end_vertex);
    pgassert(m_parent.empty());
    m_parent.resize(edge_count + 1);
    m_dCost.resize(edge_count + 1);
    initialize_que();
    m_current_node = m_start_vertex;
    pgassert(m_path.start_id() == m_start_vertex);
    auto cur_edge = dijkstra_exploration();
    pgassert(m_path.start_id() == m_start_vertex);
    if (m_current_node != m_end_vertex) {
        Path result(m_start_vertex, m_end_vertex);
        return result.renumber_vertices(m_idx_to_id);;
    }
    pgassert(m_path.start_id() == m_start_vertex);
    construct_path(static_cast<int64_t>(cur_edge.idx()), m_current_node == cur_edge.startNode()? C_EDGE : RC_EDGE);
    Path_t pelement = {};
    pelement.node = m_end_vertex;
    pelement.edge = -1;
    pelement.cost = 0.0;
    m_path.push_back(pelement);
    m_path.Path::recalculate_agg_cost();
    return m_path.renumber_vertices(m_idx_to_id);
}
References C_EDGE, construct_path(), dijkstra_exploration(), pgrouting::Path::end_id(), initialize_que(), m_current_node, m_dCost, m_end_vertex, m_idx_to_id, m_parent, m_path, m_start_vertex, Path_t::node, pgassert, pgrouting::Path::push_back(), RC_EDGE, pgrouting::Path::renumber_vertices(), and pgrouting::Path::start_id().
Referenced by process().
renumber_edges() [1/2]
void pgrouting::trsp::TrspHandler::renumber_edges (std::vector< Edge_t > & edges) private
Definition at line 82 of file trspHandler.cpp.
{
    int64_t idx(0);
    for (auto &e : edges) {
        if (m_id_to_idx.find(e.source) == m_id_to_idx.end()) {
            m_id_to_idx[e.source] = idx;
            ++idx;
        }
        if (m_id_to_idx.find(e.target) == m_id_to_idx.end()) {
            m_id_to_idx[e.target] = idx;
            ++idx;
        }
        e.source = m_id_to_idx.at(e.source);
        e.target = m_id_to_idx.at(e.target);
    }
}
References m_id_to_idx.
Referenced by TrspHandler(), and TrspHandler().
renumber_edges() [2/2]
void pgrouting::trsp::TrspHandler::renumber_edges (std::vector< Edge_t > & edges, std::vector< Edge_t > & new_edges) private
Definition at line 100 of file trspHandler.cpp.
{
    int64_t idx(0);
    for (auto &e : edges) {
        if (m_id_to_idx.find(e.source) == m_id_to_idx.end()) {
            m_id_to_idx[e.source] = idx;
            ++idx;
        }
        if (m_id_to_idx.find(e.target) == m_id_to_idx.end()) {
            m_id_to_idx[e.target] = idx;
            ++idx;
        }
        e.source = m_id_to_idx.at(e.source);
        e.target = m_id_to_idx.at(e.target);
    }
    for (auto &e : new_edges) {
        if (m_id_to_idx.find(e.source) == m_id_to_idx.end()) {
            m_id_to_idx[e.source] = idx;
            ++idx;
        }
        if (m_id_to_idx.find(e.target) == m_id_to_idx.end()) {
            m_id_to_idx[e.target] = idx;
            ++idx;
        }
        e.source = m_id_to_idx.at(e.source);
        e.target = m_id_to_idx.at(e.target);
    }
}
References m_id_to_idx.
Member Data Documentation
error
std::ostringstream pgrouting::Pgr_messages::error mutable inherited
Stores the error information.
Definition at line 84 of file messages.hpp.
Referenced by pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::Pg_points_graph::check_points(), pgrouting::Pgr_messages::clear(), pgrouting::Pg_points_graph::create_new_edges(), pgrouting::Pgr_messages::get_error(), pgrouting::Pgr_messages::has_error(), and pgrouting::vrp::Fleet::is_fleet_ok().
log
std::ostringstream pgrouting::Pgr_messages::log mutable inherited
Stores the hint information.
Definition at line 80 of file messages.hpp.
Referenced by pgrouting::vrp::Optimize::Optimize(), pgrouting::Pg_points_graph::Pg_points_graph(), pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Solution::Solution(), pgrouting::vrp::Vehicle::Vehicle(), pgrouting::Pgr_bellman_ford< G >::bellman_ford_1_to_many(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::Pg_points_graph::check_points(), pgrouting::Pgr_messages::clear(), pgrouting::Pg_points_graph::create_new_edges(), pgrouting::functions::Pgr_makeConnected< G >::generatemakeConnected(), pgrouting::Pgr_messages::get_log(), pgrouting::vrp::Pgr_pickDeliver::get_postgres_result(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::functions::CuthillMckeeOrdering< G >::get_results(), pgrouting::functions::SloanOrdering< G >::get_results(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Fleet::is_fleet_ok(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), pgrouting::vrp::Optimize::save_if_best(), and pgrouting::vrp::Pgr_pickDeliver::solve().
m_adjacency
std::map<int64_t, std::vector<size_t> > pgrouting::trsp::TrspHandler::m_adjacency private
m_adjacency[vertex] = {edges}
Definition at line 167 of file trspHandler.hpp.
Referenced by addEdge(), initialize_que(), and process().
m_current_node
int64_t pgrouting::trsp::TrspHandler::m_current_node private
Definition at line 180 of file trspHandler.hpp.
Referenced by dijkstra_exploration(), and process_trsp().
m_dCost
std::vector<CostHolder> pgrouting::trsp::TrspHandler::m_dCost private
Definition at line 185 of file trspHandler.hpp.
Referenced by clear(), construct_path(), explore(), get_tot_cost(), initialize_que(), and process_trsp().
m_edges
std::vector<EdgeInfo> pgrouting::trsp::TrspHandler::m_edges private
Definition at line 155 of file trspHandler.hpp.
Referenced by addEdge(), connectEndEdge(), connectStartEdge(), construct_path(), dijkstra_exploration(), explore(), getRestrictionCost(), initialize_que(), and process().
m_end_vertex
int64_t pgrouting::trsp::TrspHandler::m_end_vertex private
Definition at line 175 of file trspHandler.hpp.
Referenced by dijkstra_exploration(), process(), and process_trsp().
m_id_to_idx
std::map<int64_t, int64_t> pgrouting::trsp::TrspHandler::m_id_to_idx private
Definition at line 170 of file trspHandler.hpp.
Referenced by TrspHandler(), TrspHandler(), process(), renumber_edges(), and renumber_edges().
m_idx_to_id
std::map<int64_t, int64_t> pgrouting::trsp::TrspHandler::m_idx_to_id private
Definition at line 172 of file trspHandler.hpp.
Referenced by TrspHandler(), TrspHandler(), process(), and process_trsp().
m_mapEdgeId2Index
std::map<int64_t, int64_t> pgrouting::trsp::TrspHandler::m_mapEdgeId2Index private
Used only to verify that there are no reppetitions inserted the way it works, repeating edges id is not allowed TODO when using points edges id are repeated.
Definition at line 162 of file trspHandler.hpp.
Referenced by construct_graph().
m_parent
std::vector<Predecessor> pgrouting::trsp::TrspHandler::m_parent private
Definition at line 184 of file trspHandler.hpp.
Referenced by clear(), construct_path(), explore(), getRestrictionCost(), initialize_que(), and process_trsp().
m_path
Path pgrouting::trsp::TrspHandler::m_path private
Definition at line 182 of file trspHandler.hpp.
Referenced by clear(), construct_path(), process(), and process_trsp().
m_que
std::priority_queue<PDP, std::vector<PDP>, std::greater<PDP> > pgrouting::trsp::TrspHandler::m_que private
Definition at line 192 of file trspHandler.hpp.
Referenced by add_to_que(), and dijkstra_exploration().
m_ruleTable
std::map<int64_t, std::vector<Rule> > pgrouting::trsp::TrspHandler::m_ruleTable private
Definition at line 187 of file trspHandler.hpp.
Referenced by getRestrictionCost(), and initialize_restrictions().
m_start_vertex
int64_t pgrouting::trsp::TrspHandler::m_start_vertex private
Definition at line 174 of file trspHandler.hpp.
Referenced by construct_path(), dijkstra_exploration(), initialize_que(), process(), and process_trsp().
notice
std::ostringstream pgrouting::Pgr_messages::notice mutable inherited
Stores the notice information.
Definition at line 82 of file messages.hpp.
Referenced by pgrouting::Pgr_messages::clear(), and pgrouting::Pgr_messages::get_notice().
The documentation for this class was generated from the following files:
trspHandler.hpp
trspHandler.cpp