PGROUTING: pgrouting::Path Class Reference
pgrouting::Path Class Reference
#include "path.hpp"
Public Member Functions
Path ()
template<typename G >
Path (const G &graph, const Path &original, bool only_cost)
template<typename G , typename V >
Path (const G &graph, const V v_source, const V v_target, const std::vector< V > &predecessors, const std::vector< double > &distances, bool only_cost, bool normal=true)
template<typename G , typename V >
Path (G &graph, int64_t source, double distance, const std::vector< V > &predecessors, const std::vector< double > &distances)
template<typename G , typename V >
Path (G &graph, V v_source, double distance, const std::vector< V > &predecessors, const std::vector< double > &distances)
Path (int64_t s_id, int64_t e_id)
void append (const Path &other)
Path: 2 -> 9 seq node edge cost agg_cost 0 2 4 1 0 1 5 8 1 1 2 6 9 1 2 3 9 -1 0 3 Path: 9 -> 3 seq node edge cost agg_cost 0 9 16 1 0 1 4 3 1 1 2 3 -1 0 2 Path: 2 -> 3 seq node edge cost agg_cost 0 2 4 1 0 1 5 8 1 1 2 6 9 1 2 3 9 16 1 3 4 4 3 1 4 5 3 -1 0 5.
void appendPath (const Path &o_path)
Path_t & back ()
const Path_t & back () const
pthIt begin ()
ConstpthIt begin () const
void clear ()
template<typename G , typename V >
void complete_path (const G &graph, const V v_source, const V v_target, const std::vector< V > &predecessors, const std::vector< double > &distances, bool normal)
constructs a path based on results
size_t countInfinityCost () const
bool empty () const
void empty_path (unsigned int d_vertex)
pthIt end ()
ConstpthIt end () const
int64_t end_id () const
void end_id (int64_t value)
void erase (const pthIt &pos)
ConstpthIt find_restriction (const pgrouting::trsp::Rule &rule) const
get the iterator of the path where the (restriction) rule starts
Path_t & front ()
const Path_t & front () const
void generate_postgres_data (Path_rt **postgres_data, size_t &sequence) const
void generate_tuples (MST_rt **, size_t &) const
void get_pg_nksp_path (Path_rt **, size_t &) const
void get_pg_turn_restricted_path (Path_rt **ret_path, size_t &sequence, int routeId) const
Path getSubpath (unsigned int j) const
bool has_restriction (const pgrouting::trsp::Rule &rule) const
Path inf_cost_on_restriction (const pgrouting::trsp::Rule &rule)
bool isEqual (const Path &subpath) const
Path_t & operator[] (size_t i)
const Path_t & operator[] (size_t i) const
void push_back (Path_t data)
void push_front (int64_t d_vertex, int64_t d_edge, double d_cost, double d_tot_cost)
void push_front (Path_t data)
void recalculate_agg_cost ()
Path & renumber_vertices (const std::map< int64_t, int64_t > &)
Path & renumber_vertices (int64_t value)
void reverse ()
Path_t set_data (int64_t d_from, int64_t d_to, int64_t d_vertex, int64_t d_edge, double d_cost, double d_tot_cost)
size_t size () const
void sort_by_node_agg_cost ()
Sorts a path by node, aggcost ascending.
int64_t start_id () const
void start_id (int64_t value)
double tot_cost () const
Private Types
typedef std::deque< Path_t >::const_iterator ConstpthIt
typedef std::deque< Path_t >::iterator pthIt
Private Attributes
int64_t m_end_id
int64_t m_start_id
double m_tot_cost
std::deque< Path_t > path
Friends
size_t collapse_paths (MST_rt **, const std::deque< Path > &)
size_t collapse_paths (Path_rt **ret_path, const std::deque< Path > &paths)
size_t count_tuples (const std::deque< Path > &paths)
counts the tuples to be returned
void equi_cost (std::deque< Path > &paths)
discards common vertices with greater agg_cost
std::ostream & operator<< (std::ostream &log, const Path &p)
Detailed Description
Definition at line 54 of file path.hpp.
Member Typedef Documentation
ConstpthIt
typedef std::deque<Path_t>::const_iterator pgrouting::Path::ConstpthIt private
Definition at line 56 of file path.hpp.
pthIt
typedef std::deque<Path_t>::iterator pgrouting::Path::pthIt private
Definition at line 55 of file path.hpp.
Constructor & Destructor Documentation
Path() [1/6]
pgrouting::Path::Path () inline
Definition at line 65 of file path.hpp.
          : m_start_id(0), m_end_id(0), m_tot_cost(0)
    {}
Path() [2/6]
pgrouting::Path::Path (int64_t s_id, int64_t e_id) inline
Definition at line 67 of file path.hpp.
        : m_start_id(s_id), m_end_id(e_id), m_tot_cost(0)
    {}
Path() [3/6]
template<typename G , typename V > pgrouting::Path::Path (G & graph, int64_t source, double distance, const std::vector< V > & predecessors, const std::vector< double > & distances) inline
Definition at line 166 of file path.hpp.
                                                :
        m_start_id(source),
        m_end_id(source) {
            for (V i = 0; i < distances.size(); ++i) {
                if (distances[i] <= distance) {
                    auto cost = distances[i] - distances[predecessors[i]];
                    auto edge_id = graph.get_edge_id(predecessors[i], i, cost);
                    push_back(
                            {graph[i].id,
                            edge_id, cost,
                            distances[i], graph[predecessors[i]].id});
                }
            }
        }
References push_back().
Path() [4/6]
template<typename G > pgrouting::Path::Path (const G & graph, const Path & original, bool only_cost) inline
Definition at line 187 of file path.hpp.
                            :
        m_start_id(original.m_start_id),
        m_end_id(original.m_end_id),
        m_tot_cost(0) {
            if (original.path.empty()) return;
            typename G::EO_i ei, ei_end;
//            auto last_node = m_start_id;
            for (const auto &p : original.path) {
                boost::tie(ei, ei_end) = out_edges(
                        graph.get_V(p.node),
                        graph.graph);
                if (p.edge == -1) {
                    /* TODO(v4) add correct predecessor node */
                    path.push_back({m_end_id, -1, 0, 0, 0});
                } else {
                    for ( ; ei != ei_end; ++ei) {
                        if (graph[*ei].id == p.edge) {
                            auto cost = graph[*ei].cost;
                            /* TODO(v4) add correct predecessor node */
                            push_back({p.node, p.edge, cost, 0, 0});
                        }
                    }
                }
                //                last_node = p.node;
            }
            recalculate_agg_cost();
            if (only_cost) {
                path.clear();
                /* TODO(v4) add correct predecessor node */
                path.push_back(
                        {m_end_id,
                        -1,
                        m_tot_cost,
                        m_tot_cost, 0});
            }
        }
References m_end_id, m_tot_cost, path, push_back(), and recalculate_agg_cost().
Path() [5/6]
template<typename G , typename V > pgrouting::Path::Path (G & graph, V v_source, double distance, const std::vector< V > & predecessors, const std::vector< double > & distances) inline
Definition at line 231 of file path.hpp.
                                                :
        m_start_id(graph.graph[v_source].id),
        m_end_id(graph.graph[v_source].id) {
        for (V i = 0; i < distances.size(); ++i) {
            if (distances[i] <= distance) {
                auto cost = distances[i] - distances[predecessors[i]];
                auto edge_id = graph.get_edge_id(predecessors[i], i, cost);
                push_back(
                        {graph[i].id,
                        edge_id, cost,
                        distances[i]});
            }
        }
    }
References push_back().
Path() [6/6]
template<typename G , typename V > pgrouting::Path::Path (const G & graph, const V v_source, const V v_target, const std::vector< V > & predecessors, const std::vector< double > & distances, bool only_cost, bool normal = true) inline
Definition at line 253 of file path.hpp.
                                :
        m_start_id(graph.graph[v_source].id),
        m_end_id(graph.graph[v_target].id) {
            if (!only_cost) {
                complete_path(graph,
                        v_source,
                        v_target,
                        predecessors,
                        distances,
                        normal);
                return;
            }
            /*
             * only_cost
             */
            if (v_target != predecessors[v_target]) {
                /* TODO(v4) add correct predecessor node */
                push_front(
                        {graph.graph[v_target].id,
                        -1,
                        distances[v_target],
                        distances[v_target],
                        0});
            }
            return;
        }
References complete_path(), and push_front().
Member Function Documentation
append()
void pgrouting::Path::append (const Path & other)
Path: 2 -> 9 seq node edge cost agg_cost 0 2 4 1 0 1 5 8 1 1 2 6 9 1 2 3 9 -1 0 3 Path: 9 -> 3 seq node edge cost agg_cost 0 9 16 1 0 1 4 3 1 1 2 3 -1 0 2 Path: 2 -> 3 seq node edge cost agg_cost 0 2 4 1 0 1 5 8 1 1 2 6 9 1 2 3 9 16 1 3 4 4 3 1 4 5 3 -1 0 5.
Definition at line 205 of file path.cpp.
{
    pgassert(m_end_id == other.m_start_id);
    if (other.m_start_id == other.m_end_id) {
        pgassert(other.path.empty());
        return;
    }
    if (m_start_id == m_end_id) {
        pgassert(path.empty());
        *this = other;
        return;
    }
    pgassert(path.back().edge == -1);
    m_end_id = other.m_end_id;
    auto last = path.back();
    auto agg_cost = last.agg_cost;
    path.pop_back();
    for (auto item : other.path) {
        item.agg_cost += agg_cost;
        push_back(item);
    }
}
References m_end_id, m_start_id, path, pgassert, and push_back().
Referenced by pgrouting::bidirectional::Pgr_bidirectional< G >::bidirectional().
appendPath()
void pgrouting::Path::appendPath (const Path & o_path)
Definition at line 177 of file path.cpp.
{
    path.insert(path.end(), o_path.path.begin(), o_path.path.end());
    recalculate_agg_cost();
}
References path, and recalculate_agg_cost().
back() [1/2]
Path_t & pgrouting::Path::back () inline
Definition at line 96 of file path.hpp.
{return path.back();}
References path.
back() [2/2]
const Path_t & pgrouting::Path::back () const inline
Definition at line 95 of file path.hpp.
{return path.back();}
References path.
begin() [1/2]
pthIt pgrouting::Path::begin () inline
Definition at line 88 of file path.hpp.
{return path.begin();}
References path.
Referenced by pgrouting::Pg_points_graph::eliminate_details_dd(), pgrouting::yen::Pgr_ksp< G >::executeYen(), pgrouting::functions::Pgr_binaryBreadthFirstSearch< G >::getPath(), pgrouting::functions::Pgr_edwardMoore< G >::getPath(), and isEqual().
begin() [2/2]
ConstpthIt pgrouting::Path::begin () const inline
Definition at line 90 of file path.hpp.
{return path.begin();}
References path.
clear()
void pgrouting::Path::clear ()
Definition at line 103 of file path.cpp.
                 {
    path.clear();
    m_tot_cost = 0;
    m_start_id = 0;
    m_end_id = 0;
}
References m_end_id, m_start_id, m_tot_cost, and path.
Referenced by pgrouting::trsp::TrspHandler::clear().
complete_path()
template<typename G , typename V > void pgrouting::Path::complete_path (const G & graph, const V v_source, const V v_target, const std::vector< V > & predecessors, const std::vector< double > & distances, bool normal) inline
constructs a path based on results
Normal = false for reversed search path like in pgr_bdDijkstra
Definition at line 291 of file path.hpp.
{
        // no path was found
        if (v_target == predecessors[v_target]) {
            return;
        }
        /*
         * set the target
         */
        auto target = v_target;
        /*
         * the last stop is the target
         */
        /* TODO(v4) add correct predecessor node */
        push_front(
                {graph.graph[target].id, -1,
                0,  distances[target], 0});
        /*
         * get the path
         */
        while (target != v_source) {
            /*
             * done when the predecessor of the target is the target
             */
            if (target == predecessors[target]) break;
            /*
             * Inserting values in the path
             */
            auto cost = distances[target] - distances[predecessors[target]];
            auto vertex_id = graph.graph[predecessors[target]].id;
            auto edge_id = normal?
                graph.get_edge_id(predecessors[target], target, cost)
                : graph.get_edge_id(target, predecessors[target], cost);
            /* TODO(v4) add correct predecessor node */
            push_front({
                    vertex_id,
                    edge_id,
                    cost,
                    distances[target] - cost, 0});
            target = predecessors[target];
        }
        return;
    }
References push_front().
Referenced by Path().
countInfinityCost()
size_t pgrouting::Path::countInfinityCost () const
Definition at line 149 of file path.cpp.
{
    return static_cast<size_t>(std::count_if(path.begin(), path.end(),
            [](Path_t const&p) -> size_t {
            return std::isinf(p.agg_cost);
            }));
}
References path.
empty()
bool pgrouting::Path::empty () const inline
Definition at line 78 of file path.hpp.
{return path.empty();}
References path.
Referenced by pgrouting::Pg_points_graph::adjust_pids(), pgrouting::Pg_points_graph::adjust_pids(), pgrouting::dijkstraVia(), pgrouting::Pg_points_graph::eliminate_details(), pgrouting::Pg_points_graph::eliminate_details_dd(), pgrouting::yen::Pgr_ksp< G >::getFirstSolution(), isEqual(), pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::on_insert_first_solution(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::on_insert_to_heap().
empty_path()
void pgrouting::Path::empty_path (unsigned int d_vertex)
end() [1/2]
pthIt pgrouting::Path::end () inline
Definition at line 89 of file path.hpp.
{return path.end();}
References path.
Referenced by pgrouting::Pg_points_graph::eliminate_details_dd(), pgrouting::functions::Pgr_binaryBreadthFirstSearch< G >::getPath(), pgrouting::functions::Pgr_edwardMoore< G >::getPath(), and isEqual().
end() [2/2]
ConstpthIt pgrouting::Path::end () const inline
Definition at line 91 of file path.hpp.
{return path.end();}
References path.
end_id() [1/2]
int64_t pgrouting::Path::end_id () const inline
Definition at line 73 of file path.hpp.
{return m_end_id;}
References m_end_id.
Referenced by pgrouting::Pg_points_graph::adjust_pids(), pgrouting::Pg_points_graph::adjust_pids(), pgrouting::Pg_points_graph::eliminate_details(), pgrouting::Pg_points_graph::eliminate_details_dd(), generate_postgres_data(), anonymous_namespace{to_postgres.cpp}::get_path(), get_pg_nksp_path(), get_pg_turn_restricted_path(), getSubpath(), and pgrouting::trsp::TrspHandler::process_trsp().
end_id() [2/2]
void pgrouting::Path::end_id (int64_t value) inline
Definition at line 74 of file path.hpp.
{m_end_id = value;}
References m_end_id.
erase()
void pgrouting::Path::erase (const pthIt & pos) inline
Definition at line 94 of file path.hpp.
{path.erase(pos);}
References path.
Referenced by anonymous_namespace{dijkstra_driver.cpp}::post_process(), anonymous_namespace{shortestPath_driver.cpp}::post_process(), anonymous_namespace{trsp_withPoints_driver.cpp}::post_process_trsp(), and anonymous_namespace{trsp_driver.cpp}::post_process_trsp().
find_restriction()
Path::ConstpthIt pgrouting::Path::find_restriction (const pgrouting::trsp::Rule & rule) const
get the iterator of the path where the (restriction) rule starts
Parameters
[in] rule A subpath of edges for turn restrictions
Returns
the iterator of the path
Definition at line 110 of file path.cpp.
{
    return std::search(path.begin(),  path.end(), rule.begin(), rule.end(),
            [](Path_t p, int64_t e) {return p.edge == e;});
}
References pgrouting::trsp::Rule::begin(), pgrouting::trsp::Rule::end(), and path.
Referenced by has_restriction().
front() [1/2]
Path_t & pgrouting::Path::front () inline
Definition at line 98 of file path.hpp.
{return path.front();}
References path.
front() [2/2]
const Path_t & pgrouting::Path::front () const inline
Definition at line 97 of file path.hpp.
{return path.front();}
References path.
generate_postgres_data()
void pgrouting::Path::generate_postgres_data (Path_rt ** postgres_data, size_t & sequence) const
Definition at line 231 of file path.cpp.
{
    for (const auto e : path) {
        auto agg_cost = std::fabs(
                e.agg_cost - (std::numeric_limits<double>::max)()) < 1?
            std::numeric_limits<double>::infinity() : e.agg_cost;
        auto cost = std::fabs(e.cost - (std::numeric_limits<double>::max)()) < 1?
            std::numeric_limits<double>::infinity() : e.cost;
        (*postgres_data)[sequence] = {start_id(), end_id(), e.node, e.edge, cost, agg_cost};
        ++sequence;
    }
}
References end_id(), path, and start_id().
generate_tuples()
void pgrouting::Path::generate_tuples (MST_rt ** tuples, size_t & sequence) const
Definition at line 246 of file path.cpp.
{
    for (const auto e : path) {
        auto agg_cost = std::fabs(
                e.agg_cost - (std::numeric_limits<double>::max)()) < 1?
            std::numeric_limits<double>::infinity() : e.agg_cost;
        auto cost = std::fabs(e.cost - (std::numeric_limits<double>::max)()) < 1?
            std::numeric_limits<double>::infinity() : e.cost;
        (*tuples)[sequence] = {start_id(), 0, e.pred, e.node, e.edge, cost, agg_cost};
        ++sequence;
    }
}
References path, and start_id().
get_pg_nksp_path()
void pgrouting::Path::get_pg_nksp_path (Path_rt ** ret_path, size_t & sequence) const
Definition at line 263 of file path.cpp.
{
    for (unsigned int i = 0; i < path.size(); i++) {
        (*ret_path)[sequence].start_id = start_id();
        (*ret_path)[sequence].end_id = end_id();
        (*ret_path)[sequence].node = path[i].node;
        (*ret_path)[sequence].edge = path[i].edge;
        (*ret_path)[sequence].cost = path[i].cost;
        (*ret_path)[sequence].agg_cost = (i == 0)?
            0 :
            (*ret_path)[sequence-1].agg_cost +  path[i-1].cost;
        sequence++;
    }
}
References end_id(), path, and start_id().
get_pg_turn_restricted_path()
void pgrouting::Path::get_pg_turn_restricted_path (Path_rt ** ret_path, size_t & sequence, int routeId) const
Definition at line 280 of file path.cpp.
{
    for (unsigned int i = 0; i < path.size(); i++) {
        (*ret_path)[sequence].start_id = routeId;
        (*ret_path)[sequence].end_id = end_id();
        (*ret_path)[sequence].node = path[i].node;
        (*ret_path)[sequence].edge = path[i].edge;
        (*ret_path)[sequence].cost = path[i].cost;
        (*ret_path)[sequence].agg_cost = path[i].agg_cost;
        sequence++;
    }
}
References end_id(), and path.
getSubpath()
Path pgrouting::Path::getSubpath (unsigned int j) const
Definition at line 157 of file path.cpp.
{
    Path result(start_id(), end_id());
    if (j == 0)  return result;
    for (auto i = path.begin(); i != path.begin() + j; ++i) {
        result.push_back((*i));
    }
    return result;
}
References end_id(), path, push_back(), and start_id().
Referenced by pgrouting::yen::Pgr_ksp< G >::doNextCycle().
has_restriction()
bool pgrouting::Path::has_restriction (const pgrouting::trsp::Rule & rule) const
Definition at line 116 of file path.cpp.
{
    return find_restriction(rule) != path.end();
}
References find_restriction(), and path.
Referenced by pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::has_restriction().
inf_cost_on_restriction()
Path pgrouting::Path::inf_cost_on_restriction (const pgrouting::trsp::Rule & rule)
Definition at line 121 of file path.cpp.
{
    auto position = std::search(
            path.begin(),  path.end(), rule.begin(), rule.end(),
            [](Path_t p, int64_t e) { return p.edge == e;});
    if (position != path.end()) {
        position->agg_cost = std::numeric_limits<double>::infinity();
    }
    return *this;
}
References pgrouting::trsp::Rule::begin(), pgrouting::trsp::Rule::end(), and path.
isEqual()
bool pgrouting::Path::isEqual (const Path & subpath) const
Definition at line 167 of file path.cpp.
{
    if (subpath.empty()) return true;
    if (subpath.size() >= path.size()) return false;
    std::deque< Path_t >::const_iterator i, j;
    for (i = path.begin(),  j = subpath.begin(); j != subpath.end(); ++i, ++j) {
        if ((*i).node != (*j).node) return false;
    }
    return true;
}
References begin(), empty(), end(), path, and size().
operator[]() [1/2]
Path_t & pgrouting::Path::operator[] (size_t i) inline
Definition at line 84 of file path.hpp.
{return path[i];}
References path.
operator[]() [2/2]
const Path_t & pgrouting::Path::operator[] (size_t i) const inline
Definition at line 83 of file path.hpp.
{return path[i];}
References path.
push_back()
void pgrouting::Path::push_back (Path_t data)
Definition at line 67 of file path.cpp.
{
    path.push_back(data);
    m_tot_cost += data.cost;
}
References Path_t::cost, m_tot_cost, and path.
Referenced by Path(), Path(), Path(), append(), pgrouting::trsp::TrspHandler::construct_path(), pgrouting::Pg_points_graph::eliminate_details(), pgrouting::Pg_points_graph::eliminate_details_dd(), pgrouting::functions::Pgr_binaryBreadthFirstSearch< G >::getPath(), pgrouting::functions::Pgr_edwardMoore< G >::getPath(), getSubpath(), and pgrouting::trsp::TrspHandler::process_trsp().
push_front() [1/2]
void pgrouting::Path::push_front (int64_t d_vertex, int64_t d_edge, double d_cost, double d_tot_cost)
push_front() [2/2]
void pgrouting::Path::push_front (Path_t data)
Definition at line 62 of file path.cpp.
{
    path.push_front(data);
    m_tot_cost += data.cost;
}
References Path_t::cost, m_tot_cost, path, and push_front().
Referenced by Path(), complete_path(), and push_front().
recalculate_agg_cost()
void pgrouting::Path::recalculate_agg_cost ()
Definition at line 93 of file path.cpp.
{
    m_tot_cost = 0;
    for (auto &p : path) {
        p.agg_cost = m_tot_cost;
        m_tot_cost += p.cost;
    }
}
References m_tot_cost, and path.
Referenced by Path(), appendPath(), pgrouting::Pg_points_graph::eliminate_details(), pgrouting::yen::Pgr_ksp< G >::executeYen(), pgrouting::yen::Pgr_ksp< G >::getFirstSolution(), anonymous_namespace{trspVia_driver.cpp}::post_process_trspvia(), and anonymous_namespace{trspVia_withPoints_driver.cpp}::post_process_trspvia().
renumber_vertices() [1/2]
Path & pgrouting::Path::renumber_vertices (const std::map< int64_t, int64_t > & idx_to_id)
Definition at line 44 of file path.cpp.
{
    for (auto &r : path) {
        r.node = idx_to_id.at(r.node);
    }
    m_start_id = idx_to_id.at(m_start_id);
    m_end_id = idx_to_id.at(m_end_id);
    return *this;
}
References m_end_id, m_start_id, and path.
renumber_vertices() [2/2]
Path & pgrouting::Path::renumber_vertices (int64_t value)
Definition at line 53 of file path.cpp.
{
    for (auto &r : path) {
        r.node += value;
    }
    m_start_id += value;
    m_end_id += value;
    return *this;
}
References m_end_id, m_start_id, and path.
Referenced by pgrouting::trsp::TrspHandler::process_trsp().
reverse()
void pgrouting::Path::reverse ()
Definition at line 72 of file path.cpp.
                   {
    std::swap(m_start_id, m_end_id);
    if (path.size() <= 1) return;
    std::deque< Path_t > newpath;
    for (size_t i = 0; i < path.size(); ++i) {
        /* TODO(v4) add correct predecessor node */
        newpath.push_front({
                path[i].node,
                (i == 0? -1 : path[i - 1].edge),
                (i == 0? 0 : path[i - 1].cost),
                0, 0
                });
    }
    for (size_t i = 0; i < newpath.size(); ++i) {
        newpath[i].agg_cost = (i == 0)?
            0 :
            newpath[i - 1].agg_cost +  newpath[i - 1].cost;
    }
    path = newpath;
}
References m_end_id, m_start_id, and path.
Referenced by pgrouting::bidirectional::Pgr_bidirectional< G >::bidirectional().
set_data()
Path_t pgrouting::Path::set_data (int64_t d_from, int64_t d_to, int64_t d_vertex, int64_t d_edge, double d_cost, double d_tot_cost)
size()
size_t pgrouting::Path::size () const inline
Definition at line 77 of file path.hpp.
{return path.size();}
References path.
Referenced by pgrouting::dijkstraVia(), pgrouting::yen::Pgr_ksp< G >::doNextCycle(), isEqual(), and pgrouting::compPathsLess::operator()().
sort_by_node_agg_cost()
void pgrouting::Path::sort_by_node_agg_cost ()
Sorts a path by node, aggcost ascending.
nodes ASC agg_cost ASC
Definition at line 301 of file path.cpp.
{
    std::sort(path.begin(), path.end(),
            [](const Path_t &l, const  Path_t &r)
            {return l.node < r.node;});
    std::stable_sort(path.begin(), path.end(),
            [](const Path_t &l, const  Path_t &r)
            {return l.agg_cost < r.agg_cost;});
}
References path.
start_id() [1/2]
int64_t pgrouting::Path::start_id () const inline
Definition at line 71 of file path.hpp.
{return m_start_id;}
References m_start_id.
Referenced by pgrouting::Pg_points_graph::adjust_pids(), pgrouting::Pg_points_graph::adjust_pids(), pgrouting::trsp::TrspHandler::construct_path(), pgrouting::Pg_points_graph::eliminate_details(), pgrouting::Pg_points_graph::eliminate_details_dd(), generate_postgres_data(), generate_tuples(), anonymous_namespace{to_postgres.cpp}::get_path(), get_pg_nksp_path(), getSubpath(), and pgrouting::trsp::TrspHandler::process_trsp().
start_id() [2/2]
void pgrouting::Path::start_id (int64_t value) inline
Definition at line 72 of file path.hpp.
{m_start_id = value;}
References m_start_id.
tot_cost()
double pgrouting::Path::tot_cost () const inline
Definition at line 75 of file path.hpp.
{return m_tot_cost;}
References m_tot_cost.
Referenced by pgrouting::compPathsLess::operator()().
Friends And Related Symbol Documentation
collapse_paths [1/2]
size_t collapse_paths (MST_rt ** tuples, const std::deque< Path > & paths) friend
Definition at line 329 of file path.cpp.
{
    size_t sequence = 0;
    for (const Path &path : paths) {
        if (path.path.size() > 0) path.generate_tuples(tuples, sequence);
    }
    return sequence;
}
collapse_paths [2/2]
size_t collapse_paths (Path_rt ** ret_path, const std::deque< Path > & paths) friend
Definition at line 316 of file path.cpp.
{
    size_t sequence = 0;
    for (const Path &path : paths) {
        if (path.path.size() > 0) {
            path.generate_postgres_data(ret_path, sequence);
        }
    }
    return sequence;
}
count_tuples
size_t count_tuples (const std::deque< Path > & paths) friend
counts the tuples to be returned
Definition at line 405 of file path.cpp.
{
    size_t count(0);
    for (const Path &e : paths) {
        count += e.path.size();
    }
    return count;
}
equi_cost
void equi_cost (std::deque< Path > & paths) friend
discards common vertices with greater agg_cost
Definition at line 354 of file path.cpp.
{
    /* sort paths by size: largest first */
    std::sort(paths.begin(), paths.end(),
            [](const Path &e1, const Path &e2)->bool {
            return e2.size() < e1.size();
            });
    /* sort each path by node: smaller id first */
    for (auto &p : paths) {
        if (p.size() < 2) continue;
        std::sort(p.begin(), p.end(),
                [](const Path_t &e1, const Path_t &e2)->bool {
                return e1.node < e2.node;
                });
    }
    for (auto &p1 : paths) {
        for (const auto &p2 : paths) {
            if (p1.start_id() == p2.start_id()) continue;
            for (const auto &stop : p2.path) {
                /* find the node of p2 in p1 */
                auto pos = lower_bound(p1.begin(), p1.end(), stop,
                        [](const Path_t &l, const Path_t &r)->bool {
                        return l.node < r.node;
                        });
                if (pos != p1.end()
                        && (stop.node == pos->node)
                        && (stop.agg_cost < pos->agg_cost)) {
                    /* both share the same node &
                     * the second path has the smallest
                     *  So erasing from the first path */
                    p1.erase(pos);
                }
            }
        }
    }
    /* sort paths by start_id */
    std::sort(paths.begin(), paths.end(),
            [](const Path &e1, const Path &e2)->bool {
            return e1.start_id() < e2.start_id();
            });
    /* sort each path by agg_cost, node */
    for (auto &path : paths) {
        path.sort_by_node_agg_cost();
    }
}
operator<<
std::ostream & operator<< (std::ostream & log, const Path & p) friend
Definition at line 134 of file path.cpp.
{
    log << "Path: " << path.start_id() << " -> " << path.end_id() << "\n"
        << "seq\tnode\tedge\tcost\tagg_cost\n";
    int64_t i = 0;
    for (const auto &e : path) {
        log << i << "\t"
            << e.node << "\t"
            << e.edge << "\t"
            << e.cost << "\t"
            << e.agg_cost << "\n";
        ++i;
    }
    return log;
}
Member Data Documentation
m_end_id
int64_t pgrouting::Path::m_end_id private
Definition at line 61 of file path.hpp.
Referenced by Path(), append(), clear(), end_id(), end_id(), renumber_vertices(), renumber_vertices(), and reverse().
m_start_id
int64_t pgrouting::Path::m_start_id private
Definition at line 60 of file path.hpp.
Referenced by append(), clear(), renumber_vertices(), renumber_vertices(), reverse(), start_id(), and start_id().
m_tot_cost
double pgrouting::Path::m_tot_cost private
Definition at line 62 of file path.hpp.
Referenced by Path(), clear(), push_back(), push_front(), recalculate_agg_cost(), and tot_cost().
path
std::deque< Path_t > pgrouting::Path::path private
Definition at line 59 of file path.hpp.
Referenced by Path(), append(), appendPath(), back(), back(), begin(), begin(), clear(), countInfinityCost(), empty(), end(), end(), erase(), find_restriction(), front(), front(), generate_postgres_data(), generate_tuples(), get_pg_nksp_path(), get_pg_turn_restricted_path(), getSubpath(), has_restriction(), inf_cost_on_restriction(), isEqual(), operator[](), operator[](), push_back(), push_front(), recalculate_agg_cost(), renumber_vertices(), renumber_vertices(), reverse(), size(), and sort_by_node_agg_cost().
The documentation for this class was generated from the following files:
path.hpp
path.cpp