PGROUTING: pgrouting::graph::Pgr_contractionGraph< G, t_directed > Class Template Reference
pgrouting::graph::Pgr_contractionGraph< G, t_directed > Class Template Reference
#include "contractionGraph.hpp"
Public Types
using E = typename boost::graph_traits< G >::edge_descriptor
using E_i = typename boost::graph_traits< G >::edge_iterator
using EI_i = typename boost::graph_traits< G >::in_edge_iterator
using EO_i = typename boost::graph_traits< G >::out_edge_iterator
using PQ = typename std::priority_queue< V_p, std::vector< V_p >, std::greater< V_p > >
using V = typename boost::graph_traits< G >::vertex_descriptor
using V_p = typename std::pair< double, V >
Graph related types
Type boost meaning pgRouting meaning
G boost::adjacency_list Graph
V vertex_descriptor Think of it as local ID of a vertex
E edge_descriptor Think of it as local ID of an edge
V_i vertex_iterator To cycle the vertices of the Graph
E_i edge_iterator To cycle the edges of the Graph
EO_i out_edge_iterator To cycle the out going edges of a vertex
EI_i in_edge_iterator To cycle the in coming edges of a vertex (only in bidirectional graphs)
using B_G = G
using G_T_E = CH_edge
using G_T_V = CH_vertex
using V_i = typename boost::graph_traits< G >::vertex_iterator
using vertices_size_type = typename boost::graph_traits< G >::vertices_size_type
using edges_size_type = typename boost::graph_traits< G >::edges_size_type
using degree_size_type = typename boost::graph_traits< G >::degree_size_type
using vertex_index_t = typename boost::property_map< G, boost::vertex_index_t >::type
Other types
Type Meaning pgRouting Meaning
IndexMap maps V -> id given a V store the id
id_to_V maps id -> V given an id store the V
using IndexMap = std::map< V, size_t >
using id_to_V = typename std::map< int64_t, V >
Public Member Functions
Pgr_contractionGraph ()
Prepares the graph to be of type directed
bool add_shortcut (const CH_edge &edge, V u, V v)
add_shortuct to the graph during contraction
int64_t compute_pmax (V u, V v, Identifiers< V > out_vertices)
computes p_max used in the contraction hierarchies method
void copy_shortcuts (std::vector< pgrouting::CH_edge > &shortcuts, std::ostringstream &log)
copies shortcuts and modified vertices from another graph
Identifiers< V > find_adjacent_in_vertices (V v) const
get the vertex descriptors of adjacent vertices of v
Identifiers< V > find_adjacent_out_vertices (V v) const
get the vertex descriptors of adjacent vertices of v
Identifiers< V > find_adjacent_vertices (V v) const
get the vertex descriptors of adjacent vertices of v
std::tuple< CH_edge, bool > get_min_cost_edge (V u, V v)
get the edge with minimum cost between two vertices
Identifiers< int64_t > get_modified_vertices ()
vertices with at least one contracted vertex
int64_t get_next_id ()
Accessor to the next negative vertex id (to be created)
std::vector< E > get_shortcuts ()
vertices with at least one contracted vertex
double get_vertex_metric (int64_t vertex_id)
for C calls: to get the metric of a node, directly from the graph
int64_t get_vertex_order (int64_t vertex_id)
for C calls: to get the order of a node, directly from the graph
bool has_u_v_w (V u, V v, V w) const
bool is_dead_end (V v)
Accessor of the vertices on which contraction is forbidden.
bool is_forbidden (V v)
Checks if a vertex is forbidden to the contraction process.
bool is_linear (V v)
bool is_shortcut_possible (V u, V v, V w)
Possibility of a shortcut from left vertex to right vertex v* should be a linear vertex u <-> v -> w: v not considered linear.
void process_ch_shortcut (V u, V v, V w, std::vector< E > &shortcuts, std::ostringstream &log)
CH_edge process_shortcut (V u, V v, V w)
builds the shortcut information and adds it during contraction or afterwards to copy them to the source graph
void set_forbidden_vertices (Identifiers< V > p_forbidden_vertices)
Accessor to the vertices on which contraction is forbidden.
void set_vertices_metric_and_hierarchy (PQ priority_queue, std::ostringstream &log)
defines the metric and hierarchy at the level of the nodes, from a given priority queue
Edges inserters
void insert_edges_neg (const std::vector< T > &edges)
void insert_edges (const std::vector< T > &edges, bool normal=true)
Inserts count edges of type Edge_t into the graph The set of edges should not have an illegal vertex defined When the graph is empty calls:
void insert_min_edges_no_parallel (const std::vector< T > &edges)
void insert_negative_edges (const std::vector< T > &edges, bool normal=true)
in & out degree
degree_size_type out_degree (int64_t vertex_id) const
get the out-degree of a vertex
degree_size_type out_degree (V &v) const
out degree of a vertex
degree_size_type in_degree (int64_t vertex_id) const
degree_size_type in_degree (V &v) const
in degree of a vertex
Get vertex descriptor
V get_V (const CH_vertex &vertex)
get the vertex descriptor of the vertex When the vertex does not exist
V get_V (int64_t vid) const
get the vertex descriptor of the vid Call has_vertex(vid) before calling this function
V source (E e) const
get source edge
V target (E e) const
get source edge
V adjacent (V v, E e) const
get source edge
to be or not to be
bool has_vertex (int64_t vid) const
does vertex exist in the graph?
bool is_directed () const
is the graph directed?
bool is_undirected () const
is the graph undirected?
bool is_source (V v, E e) const
is v a source in the edge?
bool is_target (V v, E e) const
is v a target in the edge?
get original edge/vertex data
CH_edge & operator[] (E e)
get the edge
const CH_edge & operator[] (E e) const
get the edge
CH_vertex & operator[] (V v)
get the vertex
const CH_vertex & operator[] (V v) const
get the vertex
int64_t get_edge_id (V from, V to, double &weight) const
get the edge id of from–to with the indicated distance
Get edge descriptor
E get_edge (V from, V to, double &distance) const
How big
size_t num_vertices () const
size_t num_edges () const
Private Member Functions
void graph_add_edge (const T &edge, bool normal)
void graph_add_min_edge_no_parallel (const T &edge)
void graph_add_neg_edge (const T &edge, bool normal=true)
Add edges with negative cost(either cost or reverse_cost or both) Reading them into graph as positive cost (edge_cost = (-1)* edge_negative_cost) [L931 & L941] To Do: Read and apply edges with negative cost in function as it is.
Private Attributes
Identifiers< V > forbiddenVertices
int64_t min_edge_id
Id mapping handling
vertex_index_t vertIndex
IndexMap mapIndex
boost::associative_property_map< IndexMap > propmapIndex
Graph Modification
std::deque< CH_edge > removed_edges
Used for storing the removed_edges.
Friends
std::ostream & operator<< (std::ostream &os, const Pgr_contractionGraph &g)
print the graph with contracted vertices of all vertices and edges
The Graph
bool m_is_directed
type (DIRECTED or UNDIRECTED)
G graph
The graph.
id_to_V vertices_map
id -> graph id
edge disconnection/reconnection
void disconnect_edge (int64_t p_from, int64_t p_to)
Disconnects all edges from p_from to p_to.
void disconnect_out_going_edge (int64_t vid, int64_t eid)
Disconnects the outgoing edges of a vertex.
void disconnect_vertex (int64_t vid)
Disconnects all incoming and outgoing edges from vertex.
void disconnect_vertex (V v)
Disconnects all incoming and outgoing edges from the vertex.
void restore_graph ()
Reconnects all edges that were removed.
void restore_edge (const CH_edge &edge)
CH_edge get_edge_info (const E &e) const
Detailed Description
template<class G, bool t_directed>
class pgrouting::graph::Pgr_contractionGraph< G, t_directed >
Definition at line 54 of file contractionGraph.hpp.
Member Typedef Documentation
B_G
using pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::B_G = G inherited
Definition at line 230 of file base_graph.hpp.
degree_size_type
using pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::degree_size_type = typename boost::graph_traits<G>::degree_size_type inherited
Definition at line 242 of file base_graph.hpp.
E
template<class G , bool t_directed> using pgrouting::graph::Pgr_contractionGraph< G, t_directed >::E = typename boost::graph_traits<G>::edge_descriptor
Definition at line 57 of file contractionGraph.hpp.
E_i
template<class G , bool t_directed> using pgrouting::graph::Pgr_contractionGraph< G, t_directed >::E_i = typename boost::graph_traits < G >::edge_iterator
Definition at line 60 of file contractionGraph.hpp.
edges_size_type
using pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::edges_size_type = typename boost::graph_traits<G>::edges_size_type inherited
Definition at line 241 of file base_graph.hpp.
EI_i
template<class G , bool t_directed> using pgrouting::graph::Pgr_contractionGraph< G, t_directed >::EI_i = typename boost::graph_traits<G>::in_edge_iterator
Definition at line 59 of file contractionGraph.hpp.
EO_i
template<class G , bool t_directed> using pgrouting::graph::Pgr_contractionGraph< G, t_directed >::EO_i = typename boost::graph_traits<G>::out_edge_iterator
Definition at line 58 of file contractionGraph.hpp.
G_T_E
using pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::G_T_E = CH_edge inherited
Definition at line 231 of file base_graph.hpp.
G_T_V
using pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::G_T_V = CH_vertex inherited
Definition at line 232 of file base_graph.hpp.
id_to_V
using pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::id_to_V = typename std::map<int64_t, V> inherited
Definition at line 256 of file base_graph.hpp.
IndexMap
using pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::IndexMap = std::map<V, size_t> inherited
Definition at line 255 of file base_graph.hpp.
PQ
template<class G , bool t_directed> using pgrouting::graph::Pgr_contractionGraph< G, t_directed >::PQ = typename std::priority_queue< V_p, std::vector<V_p>, std::greater<V_p> >
Definition at line 62 of file contractionGraph.hpp.
V
template<class G , bool t_directed> using pgrouting::graph::Pgr_contractionGraph< G, t_directed >::V = typename boost::graph_traits<G>::vertex_descriptor
Definition at line 56 of file contractionGraph.hpp.
V_i
using pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::V_i = typename boost::graph_traits<G>::vertex_iterator inherited
Definition at line 235 of file base_graph.hpp.
V_p
template<class G , bool t_directed> using pgrouting::graph::Pgr_contractionGraph< G, t_directed >::V_p = typename std::pair< double, V >
Definition at line 61 of file contractionGraph.hpp.
vertex_index_t
using pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::vertex_index_t = typename boost::property_map<G, boost::vertex_index_t>::type inherited
Definition at line 243 of file base_graph.hpp.
vertices_size_type
using pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::vertices_size_type = typename boost::graph_traits<G>::vertices_size_type inherited
Definition at line 240 of file base_graph.hpp.
Constructor & Destructor Documentation
Pgr_contractionGraph()
template<class G , bool t_directed> pgrouting::graph::Pgr_contractionGraph< G, t_directed >::Pgr_contractionGraph () inline explicit
Prepares the graph to be of type directed
Definition at line 68 of file contractionGraph.hpp.
         : Pgr_base_graph<G, CH_vertex, CH_edge, t_directed>(),
        min_edge_id(0) {
         }
Member Function Documentation
add_shortcut()
template<class G , bool t_directed> bool pgrouting::graph::Pgr_contractionGraph< G, t_directed >::add_shortcut (const CH_edge & edge, V u, V v) inline
add_shortuct to the graph during contraction
Parameters
[in] edge of type CH_edge is to be added
[in] u vertex
[in] v vertex
u -> w -> v
u -> v
edge (u, v) is a new edge e contracted_vertices = w + contracted vertices
Definition at line 184 of file contractionGraph.hpp.
{
         bool inserted;
         E e;
         if (edge.cost < 0) return false;
         boost::tie(e, inserted) = boost::add_edge(u, v, this->graph);
         this->graph[e]= edge;
         return inserted;
     }
References pgrouting::CH_edge::cost, and pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::graph.
Referenced by pgrouting::graph::Pgr_contractionGraph< G, t_directed >::copy_shortcuts(), and pgrouting::graph::Pgr_contractionGraph< G, t_directed >::process_shortcut().
adjacent()
V pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::adjacent (V v, E e) const inline inherited
get source edge
Parameters
[in] v vertex descriptor
[in] e edge descriptor
Returns
V vertex descriptor
Definition at line 442 of file base_graph.hpp.
{
         pgassert(is_source(v, e) || is_target(v, e));
         return is_source(v, e)? target(e) : source(e);
     }
compute_pmax()
template<class G , bool t_directed> int64_t pgrouting::graph::Pgr_contractionGraph< G, t_directed >::compute_pmax (V u, V v, Identifiers< V > out_vertices) inline
computes p_max used in the contraction hierarchies method
Definition at line 436 of file contractionGraph.hpp.
{
        int64_t p_max;
        E e, f;
        bool found_e;
        p_max = 0;
        boost::tie(e, found_e) = boost::edge(u, v, this->graph);
        if (found_e) {
            p_max = this->graph[e].cost;
            for (V w : out_vertices) {
                bool found_f;
                boost::tie(f, found_f) = boost::edge(v, w, this->graph);
                if ((found_f) && (u != w)) {
                    if ((this->graph[e].cost + this->graph[f].cost) > p_max) {
                        p_max = this->graph[e].cost + this->graph[f].cost;
                    }
                }
            }
        }
        return p_max;
    }
References pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::graph.
copy_shortcuts()
template<class G , bool t_directed> void pgrouting::graph::Pgr_contractionGraph< G, t_directed >::copy_shortcuts (std::vector< pgrouting::CH_edge > & shortcuts, std::ostringstream & log) inline
copies shortcuts and modified vertices from another graph
Definition at line 461 of file contractionGraph.hpp.
{
        for (auto it = shortcuts.begin(); it != shortcuts.end(); it++) {
            V u, v;
            u = this->vertices_map[it->source];
            v = this->vertices_map[it->target];
            log << "Shortcut " << it->id << "(" << it->source
                << ", " << it->target << ")" << std::endl;
            add_shortcut(*it, u, v);
        }
    }
References pgrouting::graph::Pgr_contractionGraph< G, t_directed >::add_shortcut(), and pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::vertices_map.
disconnect_edge()
void pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::disconnect_edge (int64_t p_from, int64_t p_to) inline inherited
Disconnects all edges from p_from to p_to.
No edge is disconnected if the vertices id's do not exist in the graph
All removed edges are stored for future reinsertion
All parallel edges are disconnected (automatically by boost)
Parameters
[in] p_from vertex identifier of the starting point of the edge
[in] p_to vertex identifier of the ending point of the edge
Definition at line 614 of file base_graph.hpp.
{
         /* nothing to do, a vertex doesn't exist */
         if (!has_vertex(p_from) || !has_vertex(p_to)) return;
         EO_i out, out_end;
         auto u(get_V(p_from));
         auto v(get_V(p_to));
         for (boost::tie(out, out_end) = out_edges(u, graph); out != out_end; ++out) {
             if (target(*out) == v) {
                 removed_edges.push_back(get_edge_info(*out));
                 break;
             }
         }
         boost::remove_edge(u, v, graph);
     }
disconnect_out_going_edge()
void pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::disconnect_out_going_edge (int64_t vid, int64_t eid) inline inherited
Disconnects the outgoing edges of a vertex.
No edge is disconnected if it doesn't exist in the graph
Removed edges are stored for future reinsertion
all outgoing edges with the edge_id are removed if they exist
Parameters
[in] vid original vertex
[in] eid original edge_id
Definition at line 639 of file base_graph.hpp.
{
         /* nothing to do, the vertex doesn't exist */
         if (!has_vertex(vid)) return;
         auto v(get_V(vid));
         EO_i out, out_end;
         bool change = true;
         while (change) {
             change = false;
             for (boost::tie(out, out_end) = out_edges(v, graph); out != out_end; ++out) {
                 if (graph[*out].id  == eid) {
                     removed_edges.push_back(get_edge_info(*out));
                     boost::remove_edge((*out), graph);
                     change = true;
                     break;
                 }
             }
         }
     }
disconnect_vertex() [1/2]
void pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::disconnect_vertex (int64_t vid) inline inherited
Disconnects all incoming and outgoing edges from vertex.
Parameters
[in] vid vertex identifier
Definition at line 662 of file base_graph.hpp.
{
         if (!has_vertex(vid)) return;
         disconnect_vertex(get_V(vid));
     }
disconnect_vertex() [2/2]
void pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::disconnect_vertex (V v) inline inherited
Disconnects all incoming and outgoing edges from the vertex.
boost::graph doesn't recommend th to insert/remove vertices, so a vertex removal is simulated by disconnecting the vertex from the graph
No edge is disconnected if the vertices id's do not exist in the graph
All removed edges are stored for future reinsertion
All parallel edges are disconnected (automatically by boost)
Parameters
[in] v vertex descriptor
Definition at line 678 of file base_graph.hpp.
{
         EO_i out, out_end;
         for (boost::tie(out, out_end) = out_edges(v, graph); out != out_end; ++out) {
                     removed_edges.push_back(get_edge_info(*out));
         }
         /* special case */
         if (m_is_directed) {
             EI_i in, in_end;
             for (boost::tie(in, in_end) = in_edges(v, graph); in != in_end; ++in) {
                     removed_edges.push_back(get_edge_info(*in));
             }
         }
         /* delete incoming and outgoing edges from the vertex */
         boost::clear_vertex(v, graph);
     }
find_adjacent_in_vertices()
template<class G , bool t_directed> Identifiers< V > pgrouting::graph::Pgr_contractionGraph< G, t_directed >::find_adjacent_in_vertices (V v) const inline
get the vertex descriptors of adjacent vertices of v
Parameters
[in] v vertex_descriptor
Returns
Identifiers<V>: The set of in vertex descriptors adjacent to the given vertex v
Definition at line 541 of file contractionGraph.hpp.
{
        Identifiers<V> adjacent_vertices;
        for (const auto &in : boost::make_iterator_range(in_edges(v, this->graph))) {
            adjacent_vertices += this->adjacent(v, in);
        }
        return adjacent_vertices;
    }
References pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::adjacent(), and pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::graph.
find_adjacent_out_vertices()
template<class G , bool t_directed> Identifiers< V > pgrouting::graph::Pgr_contractionGraph< G, t_directed >::find_adjacent_out_vertices (V v) const inline
get the vertex descriptors of adjacent vertices of v
Parameters
[in] v vertex_descriptor
Returns
Identifiers<V>: The set of out vertex descriptors adjacent to the given vertex v
Definition at line 526 of file contractionGraph.hpp.
{
        Identifiers<V> adjacent_vertices;
        for (const auto &out : boost::make_iterator_range(out_edges(v, this->graph))) {
            adjacent_vertices += this->adjacent(v, out);
        }
        return adjacent_vertices;
    }
References pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::adjacent(), and pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::graph.
find_adjacent_vertices()
template<class G , bool t_directed> Identifiers< V > pgrouting::graph::Pgr_contractionGraph< G, t_directed >::find_adjacent_vertices (V v) const inline
get the vertex descriptors of adjacent vertices of v
Parameters
[in] v vertex_descriptor
Returns
Identifiers<V>: The set of vertex descriptors adjacent to the given vertex v
Definition at line 77 of file contractionGraph.hpp.
{
         Identifiers<V> adjacent_vertices;
         for (const auto &e : boost::make_iterator_range(
                 out_edges(v, this->graph))) {
            adjacent_vertices += this->adjacent(v, e);
         }
         for (const auto &e : boost::make_iterator_range(
                 in_edges(v, this->graph))) {
            adjacent_vertices += this->adjacent(v, e);
         }
         return adjacent_vertices;
    }
References pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::adjacent(), and pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::graph.
Referenced by pgrouting::graph::Pgr_contractionGraph< G, t_directed >::is_dead_end(), and pgrouting::graph::Pgr_contractionGraph< G, t_directed >::is_linear().
get_edge()
E pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::get_edge (V from, V to, double & distance) const inline inherited
Definition at line 567 of file base_graph.hpp.
{
         E e;
         EO_i out_i, out_end;
         V v_source, v_target;
         double minCost =  (std::numeric_limits<double>::max)();
         E minEdge;
         bool valid = false;
         for (boost::tie(out_i, out_end) = boost::out_edges(from, graph);
                 out_i != out_end; ++out_i) {
             e = *out_i;
             if (!valid) {
                 minEdge = e;
                 valid = true;
             }
             v_target = target(e);
             v_source = source(e);
             if ((from == v_source) && (to == v_target)
                     && (distance == graph[e].cost)) {
                 return e;
             }
             if ((from == v_source) && (to == v_target)
                     && (minCost > graph[e].cost)) {
                 minCost = graph[e].cost;
                 minEdge = e;
             }
         }
         return minEdge;
     }
get_edge_id()
int64_t pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::get_edge_id (V from, V to, double & weight) const inline inherited
get the edge id of from–to with the indicated distance
Parameters
[in] from vertex descriptor
[in] to vertex descriptor
[in] weight edge's weight to match when several options are found
Returns
The edge identifier of edge from–to with weight
OR the edge identifier of edge from–to with min weight
Definition at line 519 of file base_graph.hpp.
{
         EO_i out_i, out_end;
         double minCost =  (std::numeric_limits<double>::max)();
         int64_t minEdge = -1;
         for (boost::tie(out_i, out_end) = boost::out_edges(from, graph); out_i != out_end; ++out_i) {
             auto e = *out_i;
             auto v_target = target(e);
             auto v_source = source(e);
             if ((from == v_source) && (to == v_target) && (weight == graph[e].cost)) return graph[e].id;
             if ((from == v_source) && (to == v_target) && (minCost > graph[e].cost)) {
                 minCost = graph[e].cost;
                 minEdge = graph[e].id;
             }
         }
         weight = minEdge == -1? 0: minCost;
         return minEdge;
     }
get_edge_info()
CH_edge pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::get_edge_info (const E & e) const inline private inherited
Definition at line 722 of file base_graph.hpp.
{
         T_E d_edge;
         d_edge.id = graph[e].id;
         d_edge.source = graph[source(e)].id;
         d_edge.target = graph[target(e)].id;
         d_edge.cost = graph[e].cost;
         return d_edge;
     }
get_min_cost_edge()
template<class G , bool t_directed> std::tuple< CH_edge, bool > pgrouting::graph::Pgr_contractionGraph< G, t_directed >::get_min_cost_edge (V u, V v) inline
get the edge with minimum cost between two vertices
Parameters
[in] u vertex_descriptor of source vertex
[in] v vertex_descriptor of target vertex
Returns
E: The edge descriptor of the edge with minimum cost
Definition at line 99 of file contractionGraph.hpp.
{
         Identifiers<int64_t> contracted_vertices;
         double min_cost = (std::numeric_limits<double>::max)();
         bool found = false;
         CH_edge edge;
         if (this->is_directed()) {
            for (const auto &e : boost::make_iterator_range(out_edges(u, this->graph))) {
                 if (target(e, this->graph) == v) {
                     contracted_vertices += this->graph[e].contracted_vertices();
                     if (this->graph[e].cost < min_cost) {
                         min_cost = this->graph[e].cost;
                         edge = this->graph[e];
                         found = true;
                     }
                 }
             }
            /*
             To follow the principles presented
             for linear contraction in "issue_1002.pg" test 3
            */
            edge.set_contracted_vertices(contracted_vertices);
            return std::make_tuple(edge, found);
        }
        pgassert(this->is_undirected());
        for (const auto &e : boost::make_iterator_range(out_edges(u, this->graph))) {
             if (this->adjacent(u, e) == v) {
                contracted_vertices += this->graph[e].contracted_vertices();
                if ((this->graph[e]).cost < min_cost) {
                    min_cost = (this->graph[e]).cost;
                    edge = this->graph[e];
                    found = true;
                }
            }
        }
        // To follow the principles presented
        // for linear contraction in "issue_1002.pg" test 3
        edge.set_contracted_vertices(contracted_vertices);
        return std::make_tuple(edge, found);
    }
References pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::adjacent(), pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::graph, pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::is_directed(), pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::is_undirected(), pgassert, pgrouting::CH_edge::set_contracted_vertices(), and pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::target().
Referenced by pgrouting::graph::Pgr_contractionGraph< G, t_directed >::process_ch_shortcut(), and pgrouting::graph::Pgr_contractionGraph< G, t_directed >::process_shortcut().
get_modified_vertices()
template<class G , bool t_directed> Identifiers< int64_t > pgrouting::graph::Pgr_contractionGraph< G, t_directed >::get_modified_vertices () inline
vertices with at least one contracted vertex
Returns
The vids Identifiers with at least one contracted vertex
Definition at line 339 of file contractionGraph.hpp.
{
        Identifiers<int64_t> vids;
        for (const auto &v :
                boost::make_iterator_range(boost::vertices(this->graph))) {
            if ((this->graph[v].vertex_order() > 0)
            || ((this->graph[v]).has_contracted_vertices())) {
                vids += (this->graph[v]).id;
            }
        }
        return vids;
    }
References pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::graph.
get_next_id()
template<class G , bool t_directed> int64_t pgrouting::graph::Pgr_contractionGraph< G, t_directed >::get_next_id () inline
Accessor to the next negative vertex id (to be created)
Returns
int64_t: id of the next vertex to be created
Definition at line 277 of file contractionGraph.hpp.
{
        return --min_edge_id;
    }
References pgrouting::graph::Pgr_contractionGraph< G, t_directed >::min_edge_id.
Referenced by pgrouting::graph::Pgr_contractionGraph< G, t_directed >::process_ch_shortcut(), and pgrouting::graph::Pgr_contractionGraph< G, t_directed >::process_shortcut().
get_shortcuts()
template<class G , bool t_directed> std::vector< E > pgrouting::graph::Pgr_contractionGraph< G, t_directed >::get_shortcuts () inline
vertices with at least one contracted vertex
Returns
The vids Identifiers with at least one contracted vertex
Definition at line 316 of file contractionGraph.hpp.
{
        std::vector<E> eids;
        for (const auto &e : boost::make_iterator_range(edges(this->graph))) {
            if (this->graph[e].id < 0) {
                eids.push_back(e);
                pgassert(!(this->graph[e]).contracted_vertices().empty());
            } else {
                pgassert((this->graph[e]).contracted_vertices().empty());
            }
        }
        std::sort(
            eids.begin(),
            eids.end(),
            [&](E lhs, E rhs) {
                return
                    -1*((this->graph)[lhs]).id < -1*((this->graph)[rhs]).id;
                });
        return eids;
    }
References pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::graph, and pgassert.
get_V() [1/2]
V pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::get_V (const CH_vertex & vertex) inline inherited
get the vertex descriptor of the vertex When the vertex does not exist
creates a new vertex
Returns
V: The vertex descriptor of the vertex
Definition at line 403 of file base_graph.hpp.
{
         auto vm_s(vertices_map.find(vertex.id));
         if (vm_s == vertices_map.end()) {
             auto v =  add_vertex(graph);
             graph[v].cp_members(vertex);
             vertices_map[vertex.id] =  v;
             put(propmapIndex, v, num_vertices());
             return v;
         }
         return vm_s->second;
     }
get_V() [2/2]
V pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::get_V (int64_t vid) const inline inherited
get the vertex descriptor of the vid Call has_vertex(vid) before calling this function
Parameters
[in] vid vertex identifier
Returns
V: The vertex descriptor of the vertex
Definition at line 420 of file base_graph.hpp.
{
         if (!has_vertex(vid)) throw std::string("Call to ") + __PRETTY_FUNCTION__ + "without checking with has_vertex";
         return vertices_map.find(vid)->second;
     }
get_vertex_metric()
template<class G , bool t_directed> double pgrouting::graph::Pgr_contractionGraph< G, t_directed >::get_vertex_metric (int64_t vertex_id) inline
for C calls: to get the metric of a node, directly from the graph
Parameters
[in] vertex_id vertex identifier
Returns
the value of the metric of vertex_id
Definition at line 479 of file contractionGraph.hpp.
{
        return (this->graph[this->vertices_map[vertex_id]]).metric();
    }
References pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::graph, and pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::vertices_map.
get_vertex_order()
template<class G , bool t_directed> int64_t pgrouting::graph::Pgr_contractionGraph< G, t_directed >::get_vertex_order (int64_t vertex_id) inline
for C calls: to get the order of a node, directly from the graph
Parameters
[in] vertex_id vertex identifier
Returns
the order of vertex_id
Definition at line 488 of file contractionGraph.hpp.
{
        return (this->graph[this->vertices_map[vertex_id]]).vertex_order();
    }
References pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::graph, and pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::vertices_map.
graph_add_edge()
void pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::graph_add_edge (const T & edge, bool normal) inline private inherited
Definition at line 732 of file base_graph.hpp.
{
         bool inserted;
         E e;
         if ((edge.cost < 0) && (edge.reverse_cost < 0)) return;
         /*
          * true: for source
          * false: for target
          */
         auto vm_s = get_V(T_V(edge, true));
         auto vm_t = get_V(T_V(edge, false));
         pgassert(vertices_map.find(edge.source) != vertices_map.end());
         pgassert(vertices_map.find(edge.target) != vertices_map.end());
         if (edge.cost >= 0) {
             boost::tie(e, inserted) =
                 boost::add_edge(vm_s, vm_t, graph);
             graph[e].cost = edge.cost;
             graph[e].id = edge.id;
         }
         if (edge.reverse_cost >= 0
                 && (m_is_directed || (!m_is_directed && edge.cost != edge.reverse_cost))) {
             boost::tie(e, inserted) =
                 boost::add_edge(vm_t, vm_s, graph);
             graph[e].cost = edge.reverse_cost;
             graph[e].id = normal? edge.id : -edge.id;
         }
     }
graph_add_min_edge_no_parallel()
void pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::graph_add_min_edge_no_parallel (const T & edge) inline private inherited
Definition at line 763 of file base_graph.hpp.
{
         bool inserted;
         E e;
         if ((edge.cost < 0) && (edge.reverse_cost < 0)) return;
         /*
          * true: for source
          * false: for target
          */
         auto vm_s = get_V(T_V(edge, true));
         auto vm_t = get_V(T_V(edge, false));
         pgassert(vertices_map.find(edge.source) != vertices_map.end());
         pgassert(vertices_map.find(edge.target) != vertices_map.end());
         if (edge.cost >= 0) {
             E e1;
             bool found;
             boost::tie(e1, found) = boost::edge(vm_s, vm_t, graph);
             if (found) {
                 if (edge.cost < graph[e1].cost) {
                     graph[e1].cost = edge.cost;
                     graph[e1].id = edge.id;
                 }
             } else {
                 boost::tie(e, inserted) = boost::add_edge(vm_s, vm_t, graph);
                 graph[e].cost = edge.cost;
                 graph[e].id = edge.id;
             }
         }
         if (edge.reverse_cost >= 0
                 && (m_is_directed || (!m_is_directed && edge.cost != edge.reverse_cost))) {
             E e1;
             bool found;
             boost::tie(e1, found) = boost::edge(vm_t, vm_s, graph);
             if (found) {
                 if (edge.reverse_cost < graph[e1].cost) {
                     graph[e1].cost = edge.reverse_cost;
                     graph[e1].id = edge.id;
                 }
             } else {
                 boost::tie(e, inserted) =
                     boost::add_edge(vm_t, vm_s, graph);
                 graph[e].cost = edge.reverse_cost;
                 graph[e].id = edge.id;
             }
         }
     }
graph_add_neg_edge()
void pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::graph_add_neg_edge (const T & edge, bool normal = true) inline private inherited
Add edges with negative cost(either cost or reverse_cost or both) Reading them into graph as positive cost (edge_cost = (-1)* edge_negative_cost) [L931 & L941] To Do: Read and apply edges with negative cost in function as it is.
Definition at line 818 of file base_graph.hpp.
{
         bool inserted;
         E e;
         auto vm_s = get_V(T_V(edge, true));
         auto vm_t = get_V(T_V(edge, false));
         pgassert(vertices_map.find(edge.source) != vertices_map.end());
         pgassert(vertices_map.find(edge.target) != vertices_map.end());
         boost::tie(e, inserted) = boost::add_edge(vm_s, vm_t, graph);
         if (edge.cost < 0) {
             /* reading negative edges as positive */
             graph[e].cost = (-0.5)*edge.cost;
         } else {
             graph[e].cost = edge.cost;
         }
         graph[e].id = edge.id;
         if (m_is_directed
                 || (!m_is_directed && edge.cost > edge.reverse_cost)) {
             boost::tie(e, inserted) =
                 boost::add_edge(vm_t, vm_s, graph);
             if (edge.reverse_cost < 0) {
                 /* reading negative edges as positive */
                 graph[e].cost = (-0.5)*edge.reverse_cost;
             } else {
                 graph[e].cost = edge.reverse_cost;
             }
             graph[e].id = normal? edge.id : -edge.id;
         }
     }
has_u_v_w()
template<class G , bool t_directed> bool pgrouting::graph::Pgr_contractionGraph< G, t_directed >::has_u_v_w (V u, V v, V w) const inline
Definition at line 195 of file contractionGraph.hpp.
{
         return boost::edge(u, v, this->graph).second &&  boost::edge(v, w, this->graph).second;
     }
References pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::graph.
Referenced by pgrouting::graph::Pgr_contractionGraph< G, t_directed >::is_shortcut_possible().
has_vertex()
bool pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::has_vertex (int64_t vid) const inline inherited
does vertex exist in the graph?
Parameters
[in] vid vertex identifier
Returns
true: when vid is in the graph
false: when vid is not in the graph
Definition at line 456 of file base_graph.hpp.
{
         return vertices_map.find(vid) != vertices_map.end();
     }
in_degree() [1/2]
degree_size_type pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::in_degree (int64_t vertex_id) const inline inherited
Definition at line 363 of file base_graph.hpp.
{
         if (!has_vertex(vertex_id)) {
             return 0;
         }
         return is_directed()?
             in_degree(get_V(vertex_id))
             :  out_degree(get_V(vertex_id));
     }
in_degree() [2/2]
degree_size_type pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::in_degree (V & v) const inline inherited
in degree of a vertex
when its undirected there is no "concept" of in degree
out degree is returned
on directed in degree of vertex is returned
Parameters
[in] v vertex descriptor
Definition at line 379 of file base_graph.hpp.
{
         return is_directed()?
             boost::in_degree(v, graph) :
             boost::out_degree(v, graph);
     }
insert_edges()
void pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::insert_edges (const std::vector< T > & edges, bool normal = true) inline inherited
Inserts count edges of type Edge_t into the graph The set of edges should not have an illegal vertex defined When the graph is empty calls:
extract_vertices and throws an exception if there are illegal vertices. When developing:
if an illegal vertex is found an exception is thrown
That means that the set of vertices should be checked in the code that is being developed No edge is inserted when there is an error on the vertices
Parameters
edges
normal
Definition at line 328 of file base_graph.hpp.
{
         for (const auto &edge : edges) {
             graph_add_edge(edge, normal);
         }
     }
insert_edges_neg()
void pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::insert_edges_neg (const std::vector< T > & edges) inline inherited
Definition at line 309 of file base_graph.hpp.
{
         insert_edges(edges, false);
     }
insert_min_edges_no_parallel()
void pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::insert_min_edges_no_parallel (const std::vector< T > & edges) inline inherited
Definition at line 335 of file base_graph.hpp.
{
         for (const auto edge : edges) {
             graph_add_min_edge_no_parallel(edge);
         }
     }
insert_negative_edges()
void pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::insert_negative_edges (const std::vector< T > & edges, bool normal = true) inline inherited
Definition at line 341 of file base_graph.hpp.
{
         for (const auto edge : edges) {
             graph_add_neg_edge(edge, normal);
         }
     }
is_dead_end()
template<class G , bool t_directed> bool pgrouting::graph::Pgr_contractionGraph< G, t_directed >::is_dead_end (V v) inline
Accessor of the vertices on which contraction is forbidden.
Returns
Identifiers<V>: The set of forbidden vertex descriptors
Definition at line 302 of file contractionGraph.hpp.
{
        if (this->is_undirected()) {
            return this->find_adjacent_vertices(v).size() == 1;
        }
        pgassert(this->is_directed());
        return this->find_adjacent_vertices(v).size() == 1
            || (this->in_degree(v) > 0 && this->out_degree(v) == 0);
    }
References pgrouting::graph::Pgr_contractionGraph< G, t_directed >::find_adjacent_vertices(), pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::in_degree(), pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::is_directed(), pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::is_undirected(), pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::out_degree(), pgassert, and pgrouting::Identifiers< T >::size().
is_directed()
bool pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::is_directed () const inline inherited
is the graph directed?
Returns
true: when the graph is directed
false: when the graph is not directed
Definition at line 463 of file base_graph.hpp.
{return m_is_directed;}
is_forbidden()
template<class G , bool t_directed> bool pgrouting::graph::Pgr_contractionGraph< G, t_directed >::is_forbidden (V v) inline
Checks if a vertex is forbidden to the contraction process.
Parameters
[in] v vertex to test
Returns
true if the vertex is forbidden to the contraction process, false else
Definition at line 294 of file contractionGraph.hpp.
{
        return forbiddenVertices.has(v);
    }
References pgrouting::graph::Pgr_contractionGraph< G, t_directed >::forbiddenVertices, and pgrouting::Identifiers< T >::has().
is_linear()
template<class G , bool t_directed> bool pgrouting::graph::Pgr_contractionGraph< G, t_directed >::is_linear (V v) inline
Definition at line 255 of file contractionGraph.hpp.
{
         // Checking adjacent vertices constraint
         auto adjacent_vertices = find_adjacent_vertices(v);
         if (adjacent_vertices.size() == 2) {
             // Checking u - v - w
             V u = adjacent_vertices.front();
             adjacent_vertices.pop_front();
             V w = adjacent_vertices.front();
             adjacent_vertices.pop_front();
             if (is_shortcut_possible(u, v, w)) {
                 return true;
             }
             return false;
         }
         return false;
     }
References pgrouting::graph::Pgr_contractionGraph< G, t_directed >::find_adjacent_vertices(), and pgrouting::graph::Pgr_contractionGraph< G, t_directed >::is_shortcut_possible().
is_shortcut_possible()
template<class G , bool t_directed> bool pgrouting::graph::Pgr_contractionGraph< G, t_directed >::is_shortcut_possible (V u, V v, V w) inline
Possibility of a shortcut from left vertex to right vertex v* should be a linear vertex u <-> v -> w: v not considered linear.
Definition at line 222 of file contractionGraph.hpp.
                  {
         if (u == v || v == w || u == w) return false;
         pgassert(u != v);
         pgassert(v != w);
         pgassert(u != w);
         if (this->is_undirected()) {
             /*
              * u - v - w
              */
             return has_u_v_w(u, v, w);
         }
         pgassert(this->is_directed());
         return
             /*
              * u <-> v <-> w
              */
             (has_u_v_w(u, v, w) && has_u_v_w(w, v, u))
             /*
              * u -> v -> w
              */
             ||
             (has_u_v_w(u, v, w) && !(boost::edge(v, u, this->graph).second || boost::edge(w, v, this->graph).second))
             /*
              * u <- v <- w
              */
             ||
             (has_u_v_w(w, v, u) && !(boost::edge(v, w, this->graph).second || boost::edge(u, v, this->graph).second));
     }
References pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::graph, pgrouting::graph::Pgr_contractionGraph< G, t_directed >::has_u_v_w(), pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::is_directed(), pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::is_undirected(), and pgassert.
Referenced by pgrouting::graph::Pgr_contractionGraph< G, t_directed >::is_linear(), and pgrouting::graph::Pgr_contractionGraph< G, t_directed >::process_ch_shortcut().
is_source()
bool pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::is_source (V v, E e) const inline inherited
is v a source in the edge?
Parameters
[in] v vertex descriptor
[in] e edge descriptor
Returns
true: when v is source on the edge
false: when v is not source on the edge
Definition at line 475 of file base_graph.hpp.
{return v == source(e);}
is_target()
bool pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::is_target (V v, E e) const inline inherited
is v a target in the edge?
Parameters
[in] v vertex descriptor
[in] e edge descriptor
Returns
true: when v is target on the edge
false: when v is not target on the edge
Definition at line 482 of file base_graph.hpp.
{return v == target(e);}
is_undirected()
bool pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::is_undirected () const inline inherited
is the graph undirected?
Returns
true: when the graph is undirected
false: when the graph is not undirected
Definition at line 468 of file base_graph.hpp.
{return !m_is_directed;}
num_edges()
size_t pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::num_edges () const inline inherited
Definition at line 600 of file base_graph.hpp.
{ return boost::num_edges(graph);}
num_vertices()
size_t pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::num_vertices () const inline inherited
Definition at line 599 of file base_graph.hpp.
{ return boost::num_vertices(graph);}
operator[]() [1/4]
CH_edge & pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::operator[] (E e) inline inherited
get the edge
Parameters
[in] e edge descriptor
Returns
The edge information (allows modification)
Definition at line 492 of file base_graph.hpp.
{return graph[e];}
operator[]() [2/4]
const CH_edge & pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::operator[] (E e) const inline inherited
get the edge
Parameters
[in] e edge descriptor
Returns
The edge information (does not allow modification)
Definition at line 498 of file base_graph.hpp.
{return graph[e];}
operator[]() [3/4]
CH_vertex & pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::operator[] (V v) inline inherited
get the vertex
Parameters
[in] v vertex descriptor
Returns
The vertex information (allows modification)
Definition at line 504 of file base_graph.hpp.
{return graph[v];}
operator[]() [4/4]
const CH_vertex & pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::operator[] (V v) const inline inherited
get the vertex
Parameters
[in] v vertex descriptor
Returns
The vertex information (does not allow modification)
Definition at line 510 of file base_graph.hpp.
{return graph[v];}
out_degree() [1/2]
degree_size_type pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::out_degree (int64_t vertex_id) const inline inherited
get the out-degree of a vertex
Returns
0: The out degree of a vertex that its not in the graph
Parameters
[in] vertex_id original vertex id
Definition at line 354 of file base_graph.hpp.
{
         if (!has_vertex(vertex_id)) {
             return 0;
         }
         auto v = get_V(vertex_id);
         auto d = out_degree(v);
         return d;
     }
out_degree() [2/2]
degree_size_type pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::out_degree (V & v) const inline inherited
out degree of a vertex
regardless of undirected or directed graph
out degree is returned
Definition at line 390 of file base_graph.hpp.
{
         return boost::out_degree(v, graph);
     }
process_ch_shortcut()
template<class G , bool t_directed> void pgrouting::graph::Pgr_contractionGraph< G, t_directed >::process_ch_shortcut (V u, V v, V w, std::vector< E > & shortcuts, std::ostringstream & log) inline
Definition at line 394 of file contractionGraph.hpp.
{
        bool found_e;
        E e;
        boost::tie(e, found_e) = boost::edge(u, w, this->graph);
        if ((is_shortcut_possible(u, v, w)) && (!found_e)) {
            log << "    Shortcut = ("
                << this->graph[u].id << ", " << this->graph[w].id
                << "), ";
            auto e1 = get_min_cost_edge(u, v);
            auto e2 = get_min_cost_edge(v, w);
            double cost = std::numeric_limits<double>::max();
            if (std::get<1>(e1) && std::get<1>(e2)) {
                cost = std::get<0>(e1).cost + std::get<0>(e2).cost;
            }
            log << "cost = " << cost << std::endl;
            // Create shortcut
            CH_edge shortcut(
                get_next_id(),
                (this->graph[u]).id,
                (this->graph[w]).id,
                cost);
            shortcut.add_contracted_vertex(this->graph[v]);
            shortcut.add_contracted_edge_vertices(std::get<0>(e1));
            shortcut.add_contracted_edge_vertices(std::get<0>(e2));
            // Add shortcut in the current graph (to go on the process)
            bool inserted;
            E s;
            boost::tie(s, inserted) = boost::add_edge(u, w, this->graph);
            this->graph[s]= shortcut;
            if (inserted) shortcuts.push_back(s);
        }
    }
References pgrouting::CH_edge::add_contracted_edge_vertices(), pgrouting::CH_edge::add_contracted_vertex(), pgrouting::graph::Pgr_contractionGraph< G, t_directed >::get_min_cost_edge(), pgrouting::graph::Pgr_contractionGraph< G, t_directed >::get_next_id(), pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::graph, and pgrouting::graph::Pgr_contractionGraph< G, t_directed >::is_shortcut_possible().
process_shortcut()
template<class G , bool t_directed> CH_edge pgrouting::graph::Pgr_contractionGraph< G, t_directed >::process_shortcut (V u, V v, V w) inline
builds the shortcut information and adds it during contraction or afterwards to copy them to the source graph
Parameters
[in] u origin node of the shortcut
[in] v shortcuted node
[in] w destination node of the shortcut
Returns
CH_edge: object containing the shortcut edge
u -—e1{v1}-—> v -—e2{v2}-—> w
e1: min cost edge from u to v e2: min cost edge from v to w
result: u —{v+v1+v2}—> w
Definition at line 369 of file contractionGraph.hpp.
{
        auto e1 = get_min_cost_edge(u, v);
        auto e2 = get_min_cost_edge(v, w);
        double cost = std::numeric_limits<double>::max();
        if (std::get<1>(e1) && std::get<1>(e2)) {
            cost = std::get<0>(e1).cost + std::get<0>(e2).cost;
        }
        // Create shortcut
        CH_edge shortcut(
            get_next_id(),
            (this->graph[u]).id,
            (this->graph[w]).id,
            cost);
        shortcut.add_contracted_vertex(this->graph[v]);
        shortcut.add_contracted_edge_vertices(std::get<0>(e1));
        shortcut.add_contracted_edge_vertices(std::get<0>(e2));
        // Add shortcut in the current graph (to go on the process)
        add_shortcut(shortcut, u, w);
        return shortcut;
    }
References pgrouting::CH_edge::add_contracted_edge_vertices(), pgrouting::CH_edge::add_contracted_vertex(), pgrouting::graph::Pgr_contractionGraph< G, t_directed >::add_shortcut(), pgrouting::graph::Pgr_contractionGraph< G, t_directed >::get_min_cost_edge(), pgrouting::graph::Pgr_contractionGraph< G, t_directed >::get_next_id(), and pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::graph.
restore_edge()
void pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::restore_edge (const CH_edge & edge) inline private inherited
Definition at line 706 of file base_graph.hpp.
{
         E e;
         auto u = get_V(edge.source);
         auto v = get_V(edge.target);
         if (edge.cost >= 0) {
             bool inserted;
             boost::tie(e, inserted) = boost::add_edge(u, v, graph);
             graph[e].cp_members(edge);
         }
     }
restore_graph()
void pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::restore_graph () inline inherited
Reconnects all edges that were removed.
Definition at line 698 of file base_graph.hpp.
{
             while (removed_edges.size() != 0) {
                 restore_edge(removed_edges[0]);
                 removed_edges.pop_front();
             }
         }
set_forbidden_vertices()
template<class G , bool t_directed> void pgrouting::graph::Pgr_contractionGraph< G, t_directed >::set_forbidden_vertices (Identifiers< V > p_forbidden_vertices) inline
Accessor to the vertices on which contraction is forbidden.
Parameters
[in] p_forbidden_vertices The set of forbidden vertex descriptors
Definition at line 285 of file contractionGraph.hpp.
{
        forbiddenVertices = p_forbidden_vertices;
    }
References pgrouting::graph::Pgr_contractionGraph< G, t_directed >::forbiddenVertices.
set_vertices_metric_and_hierarchy()
template<class G , bool t_directed> void pgrouting::graph::Pgr_contractionGraph< G, t_directed >::set_vertices_metric_and_hierarchy (PQ priority_queue, std::ostringstream & log) inline
defines the metric and hierarchy at the level of the nodes, from a given priority queue
Parameters
[in] priority_queue
[out] log used for debugging
Definition at line 497 of file contractionGraph.hpp.
      {
        int64_t i = 0;
        while (!priority_queue.empty()) {
            i++;
            std::pair< double, V > ordered_vertex = priority_queue.top();
            priority_queue.pop();
            (this->graph[ordered_vertex.second]).metric() = ordered_vertex.first;
            (this->graph[ordered_vertex.second]).vertex_order() = i;
            log << "(" << ordered_vertex.first << ", "
                << (this->graph[ordered_vertex.second]).id
                << ")" << std::endl;
            log << " metric = "
                << (this->graph[ordered_vertex.second]).metric()
                << " order = "
                << (this->graph[ordered_vertex.second]).vertex_order()
                << std::endl;
        }
    }
References pgrouting::graph::Pgr_base_graph< G, CH_vertex, CH_edge, t_directed >::graph.
source()
V pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::source (E e) const inline inherited
get source edge
Parameters
[in] e edge descriptor
Returns
V vertex descriptor
Definition at line 429 of file base_graph.hpp.
{return boost::source(e, graph);}
target()
V pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::target (E e) const inline inherited
get source edge
Parameters
[in] e edge descriptor
Returns
V vertex descriptor
Definition at line 435 of file base_graph.hpp.
{return boost::target(e, graph);}
Friends And Related Symbol Documentation
operator<<
template<class G , bool t_directed> std::ostream & operator<< (std::ostream & os, const Pgr_contractionGraph< G, t_directed > & g) friend
print the graph with contracted vertices of all vertices and edges
Definition at line 146 of file contractionGraph.hpp.
{
         EO_i out, out_end;
         for (auto vi = vertices(g.graph).first;
                 vi != vertices(g.graph).second;
                 ++vi) {
             if ((*vi) >= g.num_vertices()) break;
             os << g.graph[*vi].id << "(" << (*vi) << ")"
                 << g.graph[*vi].contracted_vertices() << std::endl;
             os << " out_edges_of(" << g.graph[*vi].id << "):";
             for (boost::tie(out, out_end) = out_edges(*vi, g.graph);
                     out != out_end; ++out) {
                 os << ' ' << g.graph[*out].id
                     << "=(" << g.graph[g.source(*out)].id
                     << ", " << g.graph[g.target(*out)].id << ") = "
                     <<  g.graph[*out].cost <<"\t";
             }
             os << std::endl;
         }
         return os;
     }
Member Data Documentation
forbiddenVertices
template<class G , bool t_directed> Identifiers<V> pgrouting::graph::Pgr_contractionGraph< G, t_directed >::forbiddenVertices private
Definition at line 553 of file contractionGraph.hpp.
Referenced by pgrouting::graph::Pgr_contractionGraph< G, t_directed >::is_forbidden(), and pgrouting::graph::Pgr_contractionGraph< G, t_directed >::set_forbidden_vertices().
graph
G pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::graph inherited
The graph.
Definition at line 855 of file base_graph.hpp.
m_is_directed
bool pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::m_is_directed private inherited
type (DIRECTED or UNDIRECTED)
Definition at line 859 of file base_graph.hpp.
mapIndex
IndexMap pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::mapIndex private inherited
Definition at line 865 of file base_graph.hpp.
min_edge_id
template<class G , bool t_directed> int64_t pgrouting::graph::Pgr_contractionGraph< G, t_directed >::min_edge_id private
Definition at line 552 of file contractionGraph.hpp.
Referenced by pgrouting::graph::Pgr_contractionGraph< G, t_directed >::get_next_id().
propmapIndex
boost::associative_property_map<IndexMap> pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::propmapIndex private inherited
Definition at line 866 of file base_graph.hpp.
removed_edges
std::deque<CH_edge > pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::removed_edges private inherited
Used for storing the removed_edges.
Definition at line 872 of file base_graph.hpp.
vertices_map
id_to_V pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::vertices_map inherited
id -> graph id
Definition at line 856 of file base_graph.hpp.
vertIndex
vertex_index_t pgrouting::graph::Pgr_base_graph< G, CH_vertex , CH_edge , t_directed >::vertIndex private inherited
Definition at line 864 of file base_graph.hpp.
The documentation for this class was generated from the following file:
contractionGraph.hpp