PGROUTING: pgrouting::functions::Pgr_edgeColoring Class Reference
pgrouting::functions::Pgr_edgeColoring Class Reference
#include "edgeColoring.hpp"
Public Types
using E = boost::graph_traits< EdgeColoring_Graph >::edge_descriptor
using E_it = boost::graph_traits< EdgeColoring_Graph >::edge_iterator
using EdgeColoring_Graph = boost::adjacency_list< boost::vecS, boost::vecS, boost::undirectedS, boost::no_property, int64_t, boost::no_property >
using V = boost::graph_traits< EdgeColoring_Graph >::vertex_descriptor
using V_it = boost::graph_traits< EdgeColoring_Graph >::vertex_iterator
Public Member Functions
Pgr_edgeColoring ()=delete
Pgr_edgeColoring (const std::vector< Edge_t > &)
void clear ()
clear
std::vector< II_t_rt > edgeColoring ()
std::string get_error () const
get_error
std::string get_log () const
get_log
std::string get_notice () const
get_notice
bool has_error () const
get_error
Public Attributes
std::ostringstream error
Stores the error information.
std::ostringstream log
Stores the hint information.
std::ostringstream notice
Stores the notice information.
Private Member Functions
V get_boost_vertex (int64_t id) const
int64_t get_edge_id (E e) const
int64_t get_vertex_id (V v) const
Private Attributes
std::map< E, int64_t > E_to_id
EdgeColoring_Graph graph
std::map< int64_t, V > id_to_V
std::map< V, int64_t > V_to_id
Detailed Description
Definition at line 47 of file edgeColoring.hpp.
Member Typedef Documentation
E
using pgrouting::functions::Pgr_edgeColoring::E = boost::graph_traits<EdgeColoring_Graph>::edge_descriptor
Definition at line 54 of file edgeColoring.hpp.
E_it
using pgrouting::functions::Pgr_edgeColoring::E_it = boost::graph_traits<EdgeColoring_Graph>::edge_iterator
Definition at line 56 of file edgeColoring.hpp.
EdgeColoring_Graph
using pgrouting::functions::Pgr_edgeColoring::EdgeColoring_Graph = boost::adjacency_list<boost::vecS, boost::vecS, boost::undirectedS, boost::no_property, int64_t, boost::no_property>
Definition at line 49 of file edgeColoring.hpp.
V
using pgrouting::functions::Pgr_edgeColoring::V = boost::graph_traits<EdgeColoring_Graph>::vertex_descriptor
Definition at line 53 of file edgeColoring.hpp.
V_it
using pgrouting::functions::Pgr_edgeColoring::V_it = boost::graph_traits<EdgeColoring_Graph>::vertex_iterator
Definition at line 55 of file edgeColoring.hpp.
Constructor & Destructor Documentation
Pgr_edgeColoring() [1/2]
pgrouting::functions::Pgr_edgeColoring::Pgr_edgeColoring (const std::vector< Edge_t > & edges) explicit
Definition at line 68 of file edgeColoring.cpp.
{
    /*
     * Inserting vertices
     */
    Identifiers<int64_t> ids;
    for (const auto &e : edges) {
        ids += e.source;
        ids += e.target;
    }
    for (const auto id : ids) {
        auto v = add_vertex(graph);
        id_to_V.insert(std::make_pair(id, v));
        V_to_id.insert(std::make_pair(v, id));
    }
    /*
     * Inserting edges
     */
    bool added;
    for (const auto &edge : edges) {
        auto v1 = get_boost_vertex(edge.source);
        auto v2 = get_boost_vertex(edge.target);
        auto e_exists = boost::edge(v1, v2, graph);
        // NOLINTNEXTLINE
        if (e_exists.second) continue;
        if (edge.source == edge.target) continue;
        if (edge.cost < 0 && edge.reverse_cost < 0) continue;
        E e;
        // NOLINTNEXTLINE
        boost::tie(e, added) = boost::add_edge(v1, v2, graph);
        E_to_id.insert(std::make_pair(e, edge.id));
    }
}
References E_to_id, get_boost_vertex(), graph, id_to_V, and V_to_id.
Pgr_edgeColoring() [2/2]
pgrouting::functions::Pgr_edgeColoring::Pgr_edgeColoring () delete
Member Function Documentation
clear()
void pgrouting::Pgr_messages::clear () inherited
clear
Clears All the messages
Definition at line 58 of file messages.cpp.
                    {
    log.str("");
    log.clear();
    notice.str("");
    notice.clear();
    error.str("");
    error.clear();
}
References pgrouting::Pgr_messages::error, pgrouting::Pgr_messages::log, and pgrouting::Pgr_messages::notice.
Referenced by pgr_do_pickDeliver().
edgeColoring()
std::vector< II_t_rt > pgrouting::functions::Pgr_edgeColoring::edgeColoring ()
Definition at line 47 of file edgeColoring.cpp.
{
    std::vector<II_t_rt> results;
    CHECK_FOR_INTERRUPTS();
    try {
        boost::edge_coloring(graph,  boost::get(boost::edge_bundle, graph));
    } catch (...) {
        throw std::make_pair(
            std::string("INTERNAL: something went wrong while calling boost::edge_coloring"),
            std::string(__PGR_PRETTY_FUNCTION__));
    }
    for (auto e_i : boost::make_iterator_range(boost::edges(graph))) {
        auto edge = get_edge_id(e_i);
        int64_t color = graph[e_i];
        results.push_back({{edge}, {(color + 1)}});
    }
    return results;
}
References __PGR_PRETTY_FUNCTION__, CHECK_FOR_INTERRUPTS, get_edge_id(), and graph.
Referenced by pgr_do_edgeColoring().
get_boost_vertex()
Pgr_edgeColoring::V pgrouting::functions::Pgr_edgeColoring::get_boost_vertex (int64_t id) const private
Definition at line 108 of file edgeColoring.cpp.
{
    try {
        return id_to_V.at(id);
    } catch (...) {
        throw std::make_pair(
            std::string("INTERNAL: something went wrong when getting the vertex descriptor"),
            std::string(__PGR_PRETTY_FUNCTION__));
    }
}
References __PGR_PRETTY_FUNCTION__, and id_to_V.
Referenced by Pgr_edgeColoring().
get_edge_id()
int64_t pgrouting::functions::Pgr_edgeColoring::get_edge_id (E e) const private
Definition at line 130 of file edgeColoring.cpp.
{
    try {
        return E_to_id.at(e);
    } catch (...) {
        throw std::make_pair(
            std::string("INTERNAL: something went wrong when getting the edge id"),
            std::string(__PGR_PRETTY_FUNCTION__));
    }
}
References __PGR_PRETTY_FUNCTION__, and E_to_id.
Referenced by edgeColoring().
get_error()
std::string pgrouting::Pgr_messages::get_error () const inherited
get_error
Returns
the current contents of the log and clears the log
Definition at line 52 of file messages.cpp.
{
    auto str = error.str();
    return str;
}
References pgrouting::Pgr_messages::error.
Referenced by pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), do_shortestPath(), pgr_do_pickDeliver(), pgr_do_pickDeliverEuclidean(), pgr_do_trsp_withPoints(), pgr_do_trspVia_withPoints(), pgr_do_withPoints(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), and pgr_do_withPointsVia().
get_log()
std::string pgrouting::Pgr_messages::get_log () const inherited
get_log
Returns
the current contents of the log and clears the log
Definition at line 35 of file messages.cpp.
{
    auto str = log.str();
    return str;
}
References pgrouting::Pgr_messages::log.
Referenced by pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), do_shortestPath(), pgr_do_bipartite(), pgr_do_boyerMyrvold(), pgr_do_LTDTree(), pgr_do_makeConnected(), pgr_do_pickDeliver(), pgr_do_pickDeliverEuclidean(), pgr_do_trsp_withPoints(), pgr_do_trspVia_withPoints(), pgr_do_withPoints(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), and pgr_do_withPointsVia().
get_notice()
std::string pgrouting::Pgr_messages::get_notice () const inherited
get_notice
Returns
the current contents of the log and clears the log
Definition at line 41 of file messages.cpp.
{
    auto str = notice.str();
    return str;
}
References pgrouting::Pgr_messages::notice.
get_vertex_id()
int64_t pgrouting::functions::Pgr_edgeColoring::get_vertex_id (V v) const private
Definition at line 119 of file edgeColoring.cpp.
{
    try {
        return V_to_id.at(v);
    } catch (...) {
        throw std::make_pair(
            std::string("INTERNAL: something went wrong when getting the vertex id"),
            std::string(__PGR_PRETTY_FUNCTION__));
    }
}
References __PGR_PRETTY_FUNCTION__, and V_to_id.
has_error()
bool pgrouting::Pgr_messages::has_error () const inherited
get_error
Returns
the current contents of the log and clears the log
Definition at line 47 of file messages.cpp.
{
    return  !error.str().empty();
}
References pgrouting::Pgr_messages::error.
Referenced by do_shortestPath(), pgr_do_trsp_withPoints(), pgr_do_trspVia_withPoints(), pgr_do_withPoints(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), and pgr_do_withPointsVia().
Member Data Documentation
E_to_id
std::map<E, int64_t> pgrouting::functions::Pgr_edgeColoring::E_to_id private
Definition at line 78 of file edgeColoring.hpp.
Referenced by Pgr_edgeColoring(), and get_edge_id().
error
std::ostringstream pgrouting::Pgr_messages::error mutable inherited
Stores the error information.
Definition at line 84 of file messages.hpp.
Referenced by pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::Pg_points_graph::check_points(), pgrouting::Pgr_messages::clear(), pgrouting::Pg_points_graph::create_new_edges(), pgrouting::Pgr_messages::get_error(), pgrouting::Pgr_messages::has_error(), and pgrouting::vrp::Fleet::is_fleet_ok().
graph
EdgeColoring_Graph pgrouting::functions::Pgr_edgeColoring::graph private
Definition at line 75 of file edgeColoring.hpp.
Referenced by Pgr_edgeColoring(), and edgeColoring().
id_to_V
std::map<int64_t, V> pgrouting::functions::Pgr_edgeColoring::id_to_V private
Definition at line 76 of file edgeColoring.hpp.
Referenced by Pgr_edgeColoring(), and get_boost_vertex().
log
std::ostringstream pgrouting::Pgr_messages::log mutable inherited
Stores the hint information.
Definition at line 80 of file messages.hpp.
Referenced by pgrouting::vrp::Optimize::Optimize(), pgrouting::Pg_points_graph::Pg_points_graph(), pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Solution::Solution(), pgrouting::vrp::Vehicle::Vehicle(), pgrouting::Pgr_bellman_ford< G >::bellman_ford_1_to_many(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::Pg_points_graph::check_points(), pgrouting::Pgr_messages::clear(), pgrouting::Pg_points_graph::create_new_edges(), pgrouting::functions::Pgr_makeConnected< G >::generatemakeConnected(), pgrouting::Pgr_messages::get_log(), pgrouting::vrp::Pgr_pickDeliver::get_postgres_result(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::functions::CuthillMckeeOrdering< G >::get_results(), pgrouting::functions::SloanOrdering< G >::get_results(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Fleet::is_fleet_ok(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), pgrouting::vrp::Optimize::save_if_best(), and pgrouting::vrp::Pgr_pickDeliver::solve().
notice
std::ostringstream pgrouting::Pgr_messages::notice mutable inherited
Stores the notice information.
Definition at line 82 of file messages.hpp.
Referenced by pgrouting::Pgr_messages::clear(), and pgrouting::Pgr_messages::get_notice().
V_to_id
std::map<V, int64_t> pgrouting::functions::Pgr_edgeColoring::V_to_id private
Definition at line 77 of file edgeColoring.hpp.
Referenced by Pgr_edgeColoring(), and get_vertex_id().
The documentation for this class was generated from the following files:
edgeColoring.hpp
edgeColoring.cpp