PGROUTING: Pgr_bellman_ford< G > Class Template Reference
Pgr_bellman_ford< G > Class Template Reference
#include "pgr_bellman_ford.hpp"
Public Types
typedef G::E E
typedef G::V V
Public Member Functions
std::string get_error () const
get_error
std::string get_log () const
get_log
std::string get_notice () const
get_notice
bool has_error () const
get_error
Public Attributes
std::ostringstream error
Stores the error information.
std::ostringstream log
Stores the hint information.
std::ostringstream notice
Stores the notice information.
Private Attributes
members
std::vector< V > predecessors
std::vector< double > distances
BellmanFord
Path bellman_ford (G &graph, int64_t start_vertex, int64_t end_vertex, bool only_cost=false)
BellmanFord 1 to 1.
std::deque< Path > bellman_ford (G &graph, int64_t start_vertex, const std::vector< int64_t > &end_vertex, bool only_cost=false)
BellmanFord 1 to many.
std::deque< Path > bellman_ford (G &graph, const std::vector< int64_t > &start_vertex, int64_t end_vertex, bool only_cost=false)
std::deque< Path > bellman_ford (G &graph, const std::vector< int64_t > &start_vertex, const std::vector< int64_t > &end_vertex, bool only_cost=false)
std::deque< Path > bellman_ford (G &graph, const std::vector< pgr_combination_t > &combinations, bool only_cost=false)
bool bellman_ford_1_to_1 (G &graph, V source)
Call to BellmanFord 1 source to 1 target.
bool bellman_ford_1_to_many (G &graph, V source)
Call to BellmanFord 1 source to many targets.
void clear ()
std::deque< Path > get_paths (const G &graph, V source, std::vector< V > &targets, bool only_cost) const
Detailed Description
template<class G>
class Pgr_bellman_ford< G >
Definition at line 53 of file pgr_bellman_ford.hpp.
Member Typedef Documentation
E
template<class G > typedef G::E Pgr_bellman_ford< G >::E
Definition at line 56 of file pgr_bellman_ford.hpp.
V
template<class G > typedef G::V Pgr_bellman_ford< G >::V
Definition at line 55 of file pgr_bellman_ford.hpp.
Member Function Documentation
bellman_ford() [1/5]
template<class G > std::deque<Path> Pgr_bellman_ford< G >::bellman_ford (G & graph, const std::vector< int64_t > & start_vertex, const std::vector< int64_t > & end_vertex, bool only_cost = false) inline
Definition at line 158 of file pgr_bellman_ford.hpp.
{
          // a call to 1 to many is faster for each of the sources
          std::deque<Path> paths;
          log << std::string(__FUNCTION__) << "\n";
          for (const auto &start : start_vertex) {
              auto r_paths = bellman_ford(graph, start, end_vertex, only_cost);
              paths.insert(paths.begin(), r_paths.begin(), r_paths.end());
          }
          std::sort(paths.begin(), paths.end(),
                  [](const Path &e1, const Path &e2)->bool {
                  return e1.end_id() < e2.end_id();
                  });
          std::stable_sort(paths.begin(), paths.end(),
                  [](const Path &e1, const Path &e2)->bool {
                  return e1.start_id() < e2.start_id();
                  });
          return paths;
      }
References Pgr_bellman_ford< G >::bellman_ford(), and pgrouting::Pgr_messages::log.
bellman_ford() [2/5]
template<class G > std::deque<Path> Pgr_bellman_ford< G >::bellman_ford (G & graph, const std::vector< int64_t > & start_vertex, int64_t end_vertex, bool only_cost = false) inline
Definition at line 137 of file pgr_bellman_ford.hpp.
{
          std::deque<Path> paths;
          log << std::string(__FUNCTION__) << "\n";
          for (const auto &start : start_vertex) {
              paths.push_back(
                      bellman_ford(graph, start, end_vertex, only_cost));
          }
          std::stable_sort(paths.begin(), paths.end(),
                  [](const Path &e1, const Path &e2)->bool {
                  return e1.start_id() < e2.start_id();
                  });
          return paths;
      }
References Pgr_bellman_ford< G >::bellman_ford(), and pgrouting::Pgr_messages::log.
bellman_ford() [3/5]
template<class G > std::deque<Path> Pgr_bellman_ford< G >::bellman_ford (G & graph, const std::vector< pgr_combination_t > & combinations, bool only_cost = false) inline
Definition at line 185 of file pgr_bellman_ford.hpp.
{
          // a call to 1 to many is faster for each of the sources
          std::deque<Path> paths;
          log << std::string(__FUNCTION__) << "\n";
          // group targets per distinct source
          std::map< int64_t, std::vector<int64_t> > vertex_map;
          for (const pgr_combination_t &comb : combinations) {
              std::map< int64_t, std::vector<int64_t> >::iterator it = vertex_map.find(comb.source);
              if (it != vertex_map.end()) {
                  it->second.push_back(comb.target);
              } else {
                  std::vector<int64_t > targets{comb.target};
                  vertex_map[comb.source] = targets;
              }
          }
          for (const auto &start_ends : vertex_map) {
              std::deque<Path> result_paths = bellman_ford(
                  graph,
                  start_ends.first,
                  start_ends.second,
                  only_cost);
              paths.insert(
                  paths.end(),
                  std::make_move_iterator(result_paths.begin()),
                  std::make_move_iterator(result_paths.end()));
          }
          return paths;
      }
References Pgr_bellman_ford< G >::bellman_ford(), and pgrouting::Pgr_messages::log.
bellman_ford() [4/5]
template<class G > std::deque<Path> Pgr_bellman_ford< G >::bellman_ford (G & graph, int64_t start_vertex, const std::vector< int64_t > & end_vertex, bool only_cost = false) inline
BellmanFord 1 to many.
Definition at line 97 of file pgr_bellman_ford.hpp.
{
          // adjust predecessors and distances vectors
          clear();
          log << std::string(__FUNCTION__) << "\n";
          predecessors.resize(graph.num_vertices());
          distances.resize(graph.num_vertices());
          // get the graphs source and target
          if (!graph.has_vertex(start_vertex))
              return std::deque<Path>();
          auto v_source(graph.get_V(start_vertex));
          std::set< V > s_v_targets;
          for (const auto &vertex : end_vertex) {
              if (graph.has_vertex(vertex)) {
                  s_v_targets.insert(graph.get_V(vertex));
              }
          }
          std::vector< V > v_targets(s_v_targets.begin(), s_v_targets.end());
          // perform the algorithm
          bellman_ford_1_to_many(graph, v_source);
          std::deque< Path > paths;
          // get the results // route id are the targets
          paths = get_paths(graph, v_source, v_targets, only_cost);
          std::stable_sort(paths.begin(), paths.end(),
                  [](const Path &e1, const Path &e2)->bool {
                  return e1.end_id() < e2.end_id();
                  });
          return paths;
      }
References Pgr_bellman_ford< G >::bellman_ford_1_to_many(), Pgr_bellman_ford< G >::clear(), Pgr_bellman_ford< G >::distances, Pgr_bellman_ford< G >::get_paths(), pgrouting::Pgr_messages::log, and Pgr_bellman_ford< G >::predecessors.
bellman_ford() [5/5]
template<class G > Path Pgr_bellman_ford< G >::bellman_ford (G & graph, int64_t start_vertex, int64_t end_vertex, bool only_cost = false) inline
BellmanFord 1 to 1.
Definition at line 62 of file pgr_bellman_ford.hpp.
{
          clear();
          log << std::string(__FUNCTION__) << "\n";
          // adjust predecessors and distances vectors
          predecessors.resize(graph.num_vertices());
          distances.resize(graph.num_vertices());
          if (!graph.has_vertex(start_vertex)
                  || !graph.has_vertex(end_vertex)) {
              return Path(start_vertex, end_vertex);
          }
          // get the graphs source and target
          auto v_source(graph.get_V(start_vertex));
          auto v_target(graph.get_V(end_vertex));
          // perform the algorithm
          bellman_ford_1_to_1(graph, v_source, v_target);
          // get the results
          return Path(
                  graph,
                  v_source, v_target,
                  predecessors, distances,
                  only_cost, true);
      }
Referenced by Pgr_bellman_ford< G >::bellman_ford(), and pgr_bellman_ford().
bellman_ford_1_to_1()
template<class G > bool Pgr_bellman_ford< G >::bellman_ford_1_to_1 (G & graph, V source) inline private
Call to BellmanFord 1 source to 1 target.
Definition at line 224 of file pgr_bellman_ford.hpp.
                    {
          log << std::string(__FUNCTION__) << "\n";
          /* abort in case of an interruption occurs (e.g. the query is being cancelled) */
          CHECK_FOR_INTERRUPTS();
          try {
              boost::bellman_ford_shortest_paths(
                      graph.graph,
                      static_cast<int>(graph.num_vertices()),
                      boost::predecessor_map(&predecessors[0])
                      .weight_map(get(&G::G_T_E::cost, graph.graph))
                      .distance_map(&distances[0])
                      .root_vertex(source));
          } catch (boost::exception const& ex) {
              (void)ex;
              throw;
          } catch (std::exception &e) {
              (void)e;
              throw;
          } catch (...) {
              throw;
          }
          return true;
      }
References Pgr_bellman_ford< G >::distances, pgrouting::Pgr_messages::log, and Pgr_bellman_ford< G >::predecessors.
bellman_ford_1_to_many()
template<class G > bool Pgr_bellman_ford< G >::bellman_ford_1_to_many (G & graph, V source) inline private
Call to BellmanFord 1 source to many targets.
Definition at line 251 of file pgr_bellman_ford.hpp.
{
         log << std::string(__FUNCTION__) << "\n";
          /* abort in case of an interruption occurs (e.g. the query is being cancelled) */
          CHECK_FOR_INTERRUPTS();
          try {
              boost::bellman_ford_shortest_paths(
                      graph.graph,
                      static_cast<int>(graph.num_vertices()),
                      boost::predecessor_map(&predecessors[0])
                      .weight_map(get(&G::G_T_E::cost, graph.graph))
                      .distance_map(&distances[0])
                      .root_vertex(source));
          } catch (boost::exception const& ex) {
              (void)ex;
              throw;
          } catch (std::exception &e) {
              (void)e;
              throw;
          } catch (...) {
              throw;
          }
          return true;
      }
References Pgr_bellman_ford< G >::distances, pgrouting::Pgr_messages::log, and Pgr_bellman_ford< G >::predecessors.
Referenced by Pgr_bellman_ford< G >::bellman_ford().
clear()
template<class G > void Pgr_bellman_ford< G >::clear () inline private
Definition at line 279 of file pgr_bellman_ford.hpp.
                   {
          predecessors.clear();
          distances.clear();
      }
References Pgr_bellman_ford< G >::distances, and Pgr_bellman_ford< G >::predecessors.
Referenced by Pgr_bellman_ford< G >::bellman_ford().
get_error()
std::string pgrouting::Pgr_messages::get_error () const inherited
get_error
Returns
the current contents of the log and clears the log
Definition at line 53 of file pgr_messages.cpp.
{
     auto str = error.str();
     return str;
 }
References pgrouting::Pgr_messages::error.
Referenced by do_pgr_many_withPointsDD(), do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), do_pgr_withPoints(), do_pgr_withPointsKsp(), and pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver().
get_log()
std::string pgrouting::Pgr_messages::get_log () const inherited
get_log
Returns
the current contents of the log and clears the log
Definition at line 36 of file pgr_messages.cpp.
{
     auto str = log.str();
     return str;
 }
References pgrouting::Pgr_messages::log.
Referenced by do_pgr_bipartite(), do_pgr_boyerMyrvold(), do_pgr_LTDTree(), do_pgr_makeConnected(), do_pgr_many_withPointsDD(), do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), do_pgr_withPoints(), do_pgr_withPointsKsp(), pgr_bellman_ford(), pgr_dijkstraTR(), and pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver().
get_notice()
std::string pgrouting::Pgr_messages::get_notice () const inherited
get_notice
Returns
the current contents of the log and clears the log
Definition at line 42 of file pgr_messages.cpp.
{
     auto str = notice.str();
     return str;
 }
References pgrouting::Pgr_messages::notice.
get_paths()
template<class G > std::deque<Path> Pgr_bellman_ford< G >::get_paths (const G & graph, V source, std::vector< V > & targets, bool only_cost) const inline private
Definition at line 286 of file pgr_bellman_ford.hpp.
{
         log << std::string(__FUNCTION__) << "\n";
          std::deque<Path> paths;
          for (const auto target : targets) {
              paths.push_back(Path(
                          graph,
                          source, target,
                          predecessors, distances,
                          only_cost, true));
          }
          return paths;
      }
References Pgr_bellman_ford< G >::distances, pgrouting::Pgr_messages::log, and Pgr_bellman_ford< G >::predecessors.
Referenced by Pgr_bellman_ford< G >::bellman_ford().
has_error()
bool pgrouting::Pgr_messages::has_error () const inherited
get_error
Returns
the current contents of the log and clears the log
Definition at line 48 of file pgr_messages.cpp.
{
     return  !error.str().empty();
 }
References pgrouting::Pgr_messages::error.
Referenced by do_pgr_many_withPointsDD(), do_pgr_withPoints(), and do_pgr_withPointsKsp().
Member Data Documentation
distances
template<class G > std::vector< double > Pgr_bellman_ford< G >::distances private
Definition at line 308 of file pgr_bellman_ford.hpp.
Referenced by Pgr_bellman_ford< G >::bellman_ford(), Pgr_bellman_ford< G >::bellman_ford_1_to_1(), Pgr_bellman_ford< G >::bellman_ford_1_to_many(), Pgr_bellman_ford< G >::clear(), and Pgr_bellman_ford< G >::get_paths().
error
std::ostringstream pgrouting::Pgr_messages::error mutable inherited
Stores the error information.
Definition at line 85 of file pgr_messages.h.
Referenced by pgrouting::vrp::Fleet::build_fleet(), pgrouting::Pg_points_graph::check_points(), pgrouting::Pgr_messages::clear(), pgrouting::Pg_points_graph::create_new_edges(), pgrouting::Pgr_messages::get_error(), pgrouting::Pgr_messages::has_error(), pgrouting::vrp::Fleet::is_fleet_ok(), and pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver().
log
std::ostringstream pgrouting::Pgr_messages::log mutable inherited
Stores the hint information.
Definition at line 81 of file pgr_messages.h.
Referenced by pgrouting::vrp::Fleet::add_vehicle(), Pgr_bellman_ford< G >::bellman_ford(), Pgr_bellman_ford< G >::bellman_ford_1_to_1(), Pgr_bellman_ford< G >::bellman_ford_1_to_many(), pgrouting::alphashape::Pgr_alphaShape::build_best_alpha(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::Pg_points_graph::check_points(), pgrouting::Pgr_messages::clear(), pgrouting::Pg_points_graph::create_new_edges(), pgrouting::vrp::Vehicle_pickDeliver::do_while_feasable(), pgrouting::vrp::Initial_solution::do_while_foo(), pgrouting::functions::Pgr_makeConnected< G >::generatemakeConnected(), pgrouting::Pgr_messages::get_log(), Pgr_bellman_ford< G >::get_paths(), pgrouting::vrp::Pgr_pickDeliver::get_postgres_result(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Fleet::is_fleet_ok(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), pgrouting::vrp::Optimize::Optimize(), pgrouting::Pg_points_graph::Pg_points_graph(), pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Optimize::save_if_best(), pgrouting::vrp::Solution::Solution(), pgrouting::vrp::Pgr_pickDeliver::solve(), and pgrouting::vrp::Vehicle::Vehicle().
notice
std::ostringstream pgrouting::Pgr_messages::notice mutable inherited
Stores the notice information.
Definition at line 83 of file pgr_messages.h.
Referenced by pgrouting::Pgr_messages::clear(), and pgrouting::Pgr_messages::get_notice().
predecessors
template<class G > std::vector< V > Pgr_bellman_ford< G >::predecessors private
Definition at line 307 of file pgr_bellman_ford.hpp.
Referenced by Pgr_bellman_ford< G >::bellman_ford(), Pgr_bellman_ford< G >::bellman_ford_1_to_1(), Pgr_bellman_ford< G >::bellman_ford_1_to_many(), Pgr_bellman_ford< G >::clear(), and Pgr_bellman_ford< G >::get_paths().
The documentation for this class was generated from the following file:
pgr_bellman_ford.hpp