PGROUTING: AssertFailedException Class Reference
AssertFailedException Class Reference
Extends std::exception and is the exception that we throw if an assert fails.
#include "assert.hpp"
Public Member Functions
AssertFailedException (std::string msg)
virtual ~AssertFailedException () throw ()
virtual const char * what () const throw ()
Private Attributes
const std::string str
Holds what() we got as message.
Detailed Description
Extends std::exception and is the exception that we throw if an assert fails.
Definition at line 141 of file assert.hpp.
Constructor & Destructor Documentation
AssertFailedException()
AssertFailedException::AssertFailedException (std::string msg) explicit
Definition at line 73 of file assert.cpp.
                                                          :
    str(msg) {}
~AssertFailedException()
virtual AssertFailedException::~AssertFailedException () throw () inline virtual
Definition at line 148 of file assert.hpp.
{}
Member Function Documentation
what()
const char * AssertFailedException::what () const throw () virtual
Definition at line 69 of file assert.cpp.
{
    return str.c_str();
}
References str.
Referenced by do_allpairs(), do_metrics(), do_ordering(), do_shortestPath(), pgr_contractionHierarchies(), pgr_do_articulationPoints(), pgr_do_astar(), pgr_do_bdAstar(), pgr_do_bdDijkstra(), pgr_do_bellman_ford(), pgr_do_bellman_ford_neg(), pgr_do_betweennessCentrality(), pgr_do_biconnectedComponents(), pgr_do_binaryBreadthFirstSearch(), pgr_do_bipartite(), pgr_do_boyerMyrvold(), pgr_do_breadthFirstSearch(), pgr_do_bridges(), pgr_do_connectedComponents(), pgr_do_contractGraph(), pgr_do_cuthillMckeeOrdering(), pgr_do_dagShortestPath(), pgr_do_depthFirstSearch(), pgr_do_dijkstra(), pgr_do_dijkstraVia(), pgr_do_directedChPP(), pgr_do_drivingDistance(), pgr_do_edge_disjoint_paths(), pgr_do_edgeColoring(), pgr_do_edwardMoore(), pgr_do_euclideanTSP(), pgr_do_hawickCircuits(), pgr_do_isPlanar(), pgr_do_kruskal(), pgr_do_ksp(), pgr_do_lineGraph(), pgr_do_lineGraphFull(), pgr_do_LTDTree(), pgr_do_makeConnected(), pgr_do_max_flow(), pgr_do_maximum_cardinality_matching(), pgr_do_minCostMaxFlow(), pgr_do_pickDeliver(), pgr_do_pickDeliverEuclidean(), pgr_do_prim(), pgr_do_randomSpanningTree(), pgr_do_sequentialVertexColoring(), pgr_do_stoerWagner(), pgr_do_strongComponents(), pgr_do_topologicalSort(), pgr_do_transitiveClosure(), pgr_do_trsp(), pgr_do_trsp_withPoints(), pgr_do_trspVia(), pgr_do_trspVia_withPoints(), pgr_do_tsp(), pgr_do_turnRestrictedPath(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), and pgr_do_withPointsVia().
Member Data Documentation
str
const std::string AssertFailedException::str private
Holds what() we got as message.
Definition at line 143 of file assert.hpp.
Referenced by what().
The documentation for this class was generated from the following files:
assert.hpp
assert.cpp