PGROUTING: pgrouting::vrp::Pgr_pickDeliver Class Reference
pgrouting::vrp::Pgr_pickDeliver Class Reference
#include "pgr_pickDeliver.h"
Public Member Functions
Pgr_pickDeliver (const std::vector< PickDeliveryOrders_t > &pd_orders, const std::vector< Vehicle_t > &vehicles, const pgrouting::tsp::Dmatrix &cost_matrix, double factor, size_t max_cycles, int initial)
Constructor for the matrix version.
void add_node (const Vehicle_node &node)
pgrouting::tsp::Dmatrix get_cost_matrix () const
Initials_code get_kind () const
std::vector< Vehicle_node > get_nodes () const
std::vector< General_vehicle_orders_t > get_postgres_result () const
size_t max_cycles () const
void solve ()
Fleet trucks () const
Public Attributes
Pgr_messages msg
message controller for all classes
Private Attributes
friend Dnode
friend Fleet
friend Initial_solution
pgrouting::tsp::Dmatrix m_cost_matrix
int m_initial_id
used define the initial solution algorithm to be used
size_t m_max_cycles
maximum cycles in the optimization
std::vector< Vehicle_node > m_nodes
PD_Orders m_orders
Fleet m_trucks
friend PD_Orders
friend Solution
std::vector< Solution > solutions
Detailed Description
Definition at line 57 of file pgr_pickDeliver.h.
Constructor & Destructor Documentation
Pgr_pickDeliver()
pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver (const std::vector< PickDeliveryOrders_t > & pd_orders, const std::vector< Vehicle_t > & vehicles, const pgrouting::tsp::Dmatrix & cost_matrix, double factor, size_t p_max_cycles, int initial)
Constructor for the matrix version.
Definition at line 135 of file pgr_pickDeliver.cpp.
                      :
     PD_problem(this),
     m_initial_id(initial),
     m_max_cycles(p_max_cycles),
     m_nodes(),
     m_cost_matrix(cost_matrix),
     m_orders(pd_orders),
     m_trucks(vehicles, factor) {
         ENTERING(msg);
         pgassert(!pd_orders.empty());
         pgassert(!vehicles.empty());
         pgassert(!m_cost_matrix.empty());
         if (!(m_initial_id > 0 && m_initial_id < OneDepot)) {
             msg.log << "\n m_initial_id " << m_initial_id;
         }
         pgassertwm(m_initial_id > 0 && m_initial_id <= OneDepot, msg.get_log().c_str());
         pgassert(!m_nodes.empty());
         if (!msg.get_error().empty()) {
             return;
         }
 #if 0
         pgassert(m_trucks.msg().get_error().empty());
         pgassert(msg().get_error().empty());
 #endif
         msg.log << "\n Checking fleet ...";
         if (!m_trucks.is_fleet_ok()) {
             pgassert(msg.get_error().empty());
 #if 0
             pgassert(!m_trucks.msg.get_error().empty());
             msg.error << m_trucks.msg.get_error();
 #endif
             return;
         }
         msg.log << "fleet OK \n";
 #if 0
         for (const auto t : m_trucks) {
             msg.log << t << "\n";
         }
         for (const auto &o : m_orders) {
             msg.log << o << "\n";
         }
 #endif
         /*
          * check the (S, P, D, E) order on all vehicles
          * stop when a feasible truck is found
          */
         msg.log << "\n Checking orders";
         for (const auto &o : m_orders) {
             if (!m_trucks.is_order_ok(o)) {
                 msg.error << "Order not feasible on any truck was found";
                 msg.log << "The order "
                     << o.id()
                     << " is not feasible on any truck";
                 msg.log << "\n" << o;
 #if 0
                 double old_speed(0);
                 for (auto t : m_trucks) {
                     if (old_speed == t.speed()) continue;
                     old_speed = t.speed();
                     msg.log << "****** With speed: " << t.speed() << "\n";
                     msg.log << t.start_site() << "\n";
                     msg.log << o.pickup() << "\n";
                     msg.log << "travel time to "
                         << t.start_site().travel_time_to(
                                 o.pickup(), t.speed()) << "\n";
                     msg.log << o.delivery() << "\n";
                     msg.log << t.end_site() << "\n";
                     msg.log << "travel time to "
                         << t.start_site().travel_time_to(
                                 o.delivery(), t.speed())
                         << "\n";
                     t.push_back(o);
                 }
 #endif
                 return;
             }
         }
         msg.log << "orders OK \n";
         m_trucks.set_compatibles(m_orders);
 #if 0
         msg.error << "foo";
         for (const auto t : m_trucks) {
             msg.log << t << "\n";
         }
 #endif
         EXITING(msg);
     }  //  constructor
References pgrouting::tsp::Dmatrix::empty(), ENTERING, pgrouting::Pgr_messages::error, EXITING, pgrouting::Pgr_messages::get_error(), pgrouting::Pgr_messages::get_log(), pgrouting::vrp::Fleet::is_fleet_ok(), pgrouting::vrp::Fleet::is_order_ok(), pgrouting::Pgr_messages::log, m_cost_matrix, m_initial_id, m_nodes, m_orders, m_trucks, msg, pgrouting::vrp::Fleet::msg(), pgrouting::vrp::OneDepot, pgassert, pgassertwm, and pgrouting::vrp::Fleet::set_compatibles().
Member Function Documentation
add_node()
void pgrouting::vrp::Pgr_pickDeliver::add_node (const Vehicle_node & node)
Definition at line 128 of file pgr_pickDeliver.cpp.
{
     m_nodes.push_back(node);
 }
References m_nodes.
Referenced by pgrouting::vrp::Fleet::build_fleet(), and pgrouting::vrp::PD_Orders::build_orders().
get_cost_matrix()
pgrouting::tsp::Dmatrix pgrouting::vrp::Pgr_pickDeliver::get_cost_matrix () const inline
Definition at line 92 of file pgr_pickDeliver.h.
{
         return m_cost_matrix;
     }
References m_cost_matrix.
Referenced by pgrouting::vrp::Fleet::build_fleet(), pgrouting::vrp::PD_Orders::build_orders(), and pgrouting::vrp::Dnode::distance().
get_kind()
Initials_code pgrouting::vrp::Pgr_pickDeliver::get_kind () const inline
Definition at line 84 of file pgr_pickDeliver.h.
{
         return (Initials_code) m_initial_id;
     }
References m_initial_id.
Referenced by pgrouting::vrp::Solution::get_kind().
get_nodes()
std::vector<Vehicle_node> pgrouting::vrp::Pgr_pickDeliver::get_nodes () const inline
Definition at line 88 of file pgr_pickDeliver.h.
{
         return m_nodes;
     }
References m_nodes.
Referenced by pgrouting::vrp::Fleet::build_fleet(), and pgrouting::vrp::PD_Orders::build_orders().
get_postgres_result()
std::vector< General_vehicle_orders_t > pgrouting::vrp::Pgr_pickDeliver::get_postgres_result () const
Definition at line 94 of file pgr_pickDeliver.cpp.
{
     auto result = solutions.back().get_postgres_result();
     General_vehicle_orders_t aggregates = {
             /*
              * Vehicle id = -2 indicates its an aggregate row
              *
              * (twv, cv, fleet, wait, duration)
              */
             -2,  // summary row on vehicle_number
             solutions.back().twvTot(),  // on vehicle_id
             solutions.back().cvTot(),   // on vehicle_seq
             -1,  // on order_id
             -1,  // on stop_id
             -2,  // on stop_type (gets increased later by one so it gets -1)
             -1,  // not accounting total loads
             solutions.back().total_travel_time(),
             -1,  // not accounting arrival_travel_time
             solutions.back().wait_time(),
             solutions.back().total_service_time(),
             solutions.back().duration(),
             };
     result.push_back(aggregates);
 #ifndef NDEBUG
     for (const auto &sol : solutions) {
         msg.log << sol.tau();
     }
 #endif
     return result;
 }
References pgrouting::Pgr_messages::log, msg, and solutions.
Referenced by do_pgr_pickDeliver(), and do_pgr_pickDeliverEuclidean().
max_cycles()
size_t pgrouting::vrp::Pgr_pickDeliver::max_cycles () const inline
Definition at line 80 of file pgr_pickDeliver.h.
 {return m_max_cycles;}
References m_max_cycles.
solve()
void pgrouting::vrp::Pgr_pickDeliver::solve ()
Definition at line 51 of file pgr_pickDeliver.cpp.
{
     auto initial_sols = solutions;
     if (m_initial_id == 0) {
         msg.log << "trying all \n";
         for (int i = 1; i < 7; ++i) {
             initial_sols.push_back(Initial_solution((Initials_code)i, m_orders.size()));
             msg.log << "solution " << i << "\n" << initial_sols.back().tau();
             // TODO(vicky) calculate the time it takes
             msg.log << "Initial solution " << i
                 << " duration: " << initial_sols.back().duration();
         }
     } else {
         msg.log << "only trying " << m_initial_id << "\n";
         initial_sols.push_back(Initial_solution((Initials_code)m_initial_id, m_orders.size()));
         // TODO(vicky) calculate the time it takes
         msg.log << "Initial solution " << m_initial_id
             << " duration: " << initial_sols[0].duration();
     }
     /*
      * Sorting solutions: the best is at the back
      */
     pgassert(!initial_sols.empty());
     std::sort(initial_sols.begin(), initial_sols.end(), []
             (const Solution &lhs, const Solution &rhs) -> bool {
             return rhs < lhs;
             });
 #if 1
     solutions.push_back(Optimize(initial_sols.back(), m_max_cycles));
 #else
     solutions.push_back(initial_sols.back());
 #endif
     pgassert(!solutions.empty());
     msg.log << "best solution duration = " << solutions.back().duration();
 }
References Initial_solution, pgrouting::Pgr_messages::log, m_initial_id, m_max_cycles, m_orders, msg, pgassert, pgrouting::vrp::PD_Orders::size(), and solutions.
Referenced by do_pgr_pickDeliver(), and do_pgr_pickDeliverEuclidean().
trucks()
Fleet pgrouting::vrp::Pgr_pickDeliver::trucks () const inline
Definition at line 96 of file pgr_pickDeliver.h.
 {return m_trucks;}
References m_trucks.
Member Data Documentation
Dnode
friend pgrouting::vrp::Pgr_pickDeliver::Dnode private
Definition at line 59 of file pgr_pickDeliver.h.
Fleet
friend pgrouting::vrp::Pgr_pickDeliver::Fleet private
Definition at line 58 of file pgr_pickDeliver.h.
Initial_solution
friend pgrouting::vrp::Pgr_pickDeliver::Initial_solution private
Definition at line 62 of file pgr_pickDeliver.h.
Referenced by solve().
m_cost_matrix
pgrouting::tsp::Dmatrix pgrouting::vrp::Pgr_pickDeliver::m_cost_matrix private
Definition at line 111 of file pgr_pickDeliver.h.
Referenced by get_cost_matrix(), and Pgr_pickDeliver().
m_initial_id
int pgrouting::vrp::Pgr_pickDeliver::m_initial_id private
used define the initial solution algorithm to be used
Definition at line 105 of file pgr_pickDeliver.h.
Referenced by get_kind(), Pgr_pickDeliver(), and solve().
m_max_cycles
size_t pgrouting::vrp::Pgr_pickDeliver::m_max_cycles private
maximum cycles in the optimization
Definition at line 108 of file pgr_pickDeliver.h.
Referenced by max_cycles(), and solve().
m_nodes
std::vector<Vehicle_node> pgrouting::vrp::Pgr_pickDeliver::m_nodes private
Definition at line 110 of file pgr_pickDeliver.h.
Referenced by add_node(), get_nodes(), and Pgr_pickDeliver().
m_orders
PD_Orders pgrouting::vrp::Pgr_pickDeliver::m_orders private
Definition at line 113 of file pgr_pickDeliver.h.
Referenced by Pgr_pickDeliver(), and solve().
m_trucks
Fleet pgrouting::vrp::Pgr_pickDeliver::m_trucks private
Definition at line 114 of file pgr_pickDeliver.h.
Referenced by Pgr_pickDeliver(), and trucks().
msg
Pgr_messages pgrouting::vrp::Pgr_pickDeliver::msg
message controller for all classes
Definition at line 99 of file pgr_pickDeliver.h.
Referenced by do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), get_postgres_result(), pgrouting::vrp::Fleet::msg(), pgrouting::vrp::Solution::msg(), pgrouting::vrp::Vehicle::msg(), Pgr_pickDeliver(), and solve().
PD_Orders
friend pgrouting::vrp::Pgr_pickDeliver::PD_Orders private
Definition at line 60 of file pgr_pickDeliver.h.
Solution
friend pgrouting::vrp::Pgr_pickDeliver::Solution private
Definition at line 61 of file pgr_pickDeliver.h.
solutions
std::vector<Solution> pgrouting::vrp::Pgr_pickDeliver::solutions private
Definition at line 115 of file pgr_pickDeliver.h.
Referenced by get_postgres_result(), and solve().
The documentation for this class was generated from the following files:
pgr_pickDeliver.h
pgr_pickDeliver.cpp