PGROUTING: pgrouting::vrp::PD_Orders Class Reference
pgrouting::vrp::PD_Orders Class Reference
#include "pd_orders.h"
Public Types
typedef Orders::const_iterator o_const_iterator
typedef Orders::iterator o_iterator
Public Member Functions
size_t find_best_I (Identifiers< size_t > &within_this_set) const
size_t find_best_J (Identifiers< size_t > &within_this_set) const
bool is_valid (double speed) const
void set_compatibles (double speed)
constructors
PD_Orders ()=default
PD_Orders (const PD_Orders &)=default
PD_Orders (const std::vector< PickDeliveryOrders_t > &)
std container functions
functions with same "meaning" as an std container
Order & operator[] (size_t o)
const Order & operator[] (size_t o) const
size_t size () const
o_iterator begin ()
o_iterator end ()
o_const_iterator begin () const
o_const_iterator end () const
Private Types
typedef std::vector< Order > Orders
Private Member Functions
void add_order (const PickDeliveryOrders_t &, const Vehicle_node &, const Vehicle_node &)
void build_orders (const std::vector< PickDeliveryOrders_t > &pd_orders)
Pgr_messages & msg () const
Access to the problem's message.
Private Attributes
Orders m_orders
Static Private Attributes
static Pgr_pickDeliver * problem
The problem.
Friends
class PD_problem
PD_rpblem needs access to set up the problem pointer.
Detailed Description
Definition at line 49 of file pd_orders.h.
Member Typedef Documentation
o_const_iterator
typedef Orders::const_iterator pgrouting::vrp::PD_Orders::o_const_iterator
Definition at line 57 of file pd_orders.h.
o_iterator
typedef Orders::iterator pgrouting::vrp::PD_Orders::o_iterator
Definition at line 56 of file pd_orders.h.
Orders
typedef std::vector<Order> pgrouting::vrp::PD_Orders::Orders private
Definition at line 53 of file pd_orders.h.
Constructor & Destructor Documentation
PD_Orders() [1/3]
pgrouting::vrp::PD_Orders::PD_Orders () default
PD_Orders() [2/3]
pgrouting::vrp::PD_Orders::PD_Orders (const PD_Orders &) default
PD_Orders() [3/3]
pgrouting::vrp::PD_Orders::PD_Orders (const std::vector< PickDeliveryOrders_t > & pd_orders) explicit
Definition at line 40 of file pd_orders.cpp.
References build_orders().
           {
     build_orders(pd_orders);
 }
Member Function Documentation
add_order()
void pgrouting::vrp::PD_Orders::add_order (const PickDeliveryOrders_t & order, const Vehicle_node & pick, const Vehicle_node & drop) private
Definition at line 48 of file pd_orders.cpp.
References pgrouting::vrp::Pgr_pickDeliver::add_node(), PickDeliveryOrders_t::id, m_orders, and problem.
Referenced by build_orders(), and end().
{
 #if 0
     problem->add_base_node(std::move(b_pick));
     problem->add_base_node(std::move(b_drop));
     problem->add_node(pick);
     problem->add_node(drop);
 #endif
     /*
      * add into an order
      */
     m_orders.push_back(
             Order(m_orders.size(), order.id,
                 pick,
                 drop));
 }
begin() [1/2]
o_iterator pgrouting::vrp::PD_Orders::begin () inline
Definition at line 82 of file pd_orders.h.
References m_orders.
 {return m_orders.begin();}
begin() [2/2]
o_const_iterator pgrouting::vrp::PD_Orders::begin () const inline
Definition at line 84 of file pd_orders.h.
References m_orders.
 {return m_orders.begin();}
build_orders()
void pgrouting::vrp::PD_Orders::build_orders (const std::vector< PickDeliveryOrders_t > & pd_orders) private
Definition at line 70 of file pd_orders.cpp.
References pgrouting::vrp::Pgr_pickDeliver::add_node(), add_order(), pgrouting::tsp::Dmatrix::empty(), ENTERING, EXITING, pgrouting::tsp::Dmatrix::has_id(), pgrouting::Pgr_messages::log, pgrouting::vrp::Pgr_pickDeliver::m_cost_matrix, pgrouting::vrp::Pgr_pickDeliver::m_nodes, msg(), pgassert, and problem.
Referenced by end(), and PD_Orders().
           {
 #if 0
     ENTERING();
 #endif
     for (const auto &order : pd_orders) {
         /*
          * SAMPLE CORRECT INFORMATION
          *
          * id | demand | pick_x | pick_y | pick_open_t | pick_close_t | pick_service_t | deliver_x | deliver_y | deliver_open_t | deliver_open_t | deliver_close_t | deliver_service_t
          * 1  | 10     |   35   |   69   |   448       |   505        |    90          |    45     |   68      |    912         |   967          |    90           |    35
          */
         if  (problem->m_cost_matrix.empty()) {
             pgassert(false);
 #if 0
             /*
              * Euclidean version
              */
             auto b_pick = create_b_pick<Node>(order, problem->node_id());
             Vehicle_node pickup(
                     {problem->node_id()++, order, Tw_node::NodeType::kPickup});
             auto b_drop = create_b_deliver<Node>(order, problem->node_id());
             Vehicle_node delivery({
                     problem->node_id()++,
                     order,
                     Tw_node::NodeType::kDelivery});
             add_order(order,
                     std::move(b_pick), pickup,
                     std::move(b_drop), delivery);
 #endif
         } else {
             /*
              * matrix version
              */
 #if 0
 #if 0
             msg.log << "pickup \n"
                 << "pick_node_id: " << order.pick_node_id
                 << "\n";
             msg.log << "pickup \n"
                 << "deliver_node_id: " << order.deliver_node_id
                 << "\n";
 #endif
             auto b_pick = create_b_pick<Dnode>(order, problem->node_id());
             Vehicle_node pickup(
                     {problem->node_id()++, order, Tw_node::NodeType::kPickup});
             auto b_drop = create_b_deliver<Dnode>(order, problem->node_id());
             Vehicle_node delivery({
                     problem->node_id()++,
                     order,
                     Tw_node::NodeType::kDelivery});
             add_order(order,
                     std::move(b_pick), pickup,
                     std::move(b_drop), delivery);
 #endif
             if (!problem->m_cost_matrix.has_id(order.pick_node_id)) {
                 throw std::make_pair(std::string("Unable to find node on matrix"), order.pick_node_id);
             }
             if (!problem->m_cost_matrix.has_id(order.deliver_node_id)) {
                 throw std::make_pair(std::string("Unable to find node on matrix"), order.deliver_node_id);
             }
             Vehicle_node pickup({problem->m_nodes.size(), order, Tw_node::NodeType::kPickup});
             problem->add_node(pickup);
             Vehicle_node delivery({problem->m_nodes.size(), order, Tw_node::NodeType::kDelivery});
             problem->add_node(delivery);
             add_order(order, pickup, delivery);
         }
     }  //  for (creating orders)
 #if 0
     EXITING();
 #endif
 }
end() [1/2]
o_iterator pgrouting::vrp::PD_Orders::end () inline
Definition at line 83 of file pd_orders.h.
References m_orders.
 {return m_orders.end();}
end() [2/2]
o_const_iterator pgrouting::vrp::PD_Orders::end () const inline
Definition at line 85 of file pd_orders.h.
References add_order(), build_orders(), and m_orders.
 {return m_orders.end();}
find_best_I()
size_t pgrouting::vrp::PD_Orders::find_best_I (Identifiers< size_t > & within_this_set) const
Definition at line 210 of file pd_orders.cpp.
References Identifiers< T >::empty(), Identifiers< T >::front(), m_orders, and pgassert.
Referenced by pgrouting::vrp::Vehicle_pickDeliver::do_while_feasable().
{
     pgassert(!within_this_set.empty());
     auto best_order = within_this_set.front();
     size_t max_size = 0;
     for (auto o : within_this_set) {
         auto size_I =  m_orders[o].subsetI(within_this_set).size();
         if (max_size < size_I) {
             max_size = size_I;
             best_order = o;
         }
     }
     return best_order;
 }
find_best_J()
size_t pgrouting::vrp::PD_Orders::find_best_J (Identifiers< size_t > & within_this_set) const
Definition at line 191 of file pd_orders.cpp.
References Identifiers< T >::empty(), Identifiers< T >::front(), m_orders, and pgassert.
Referenced by pgrouting::vrp::Vehicle_pickDeliver::do_while_feasable().
{
     pgassert(!within_this_set.empty());
     auto best_order = within_this_set.front();
     size_t max_size = 0;
     for (auto o : within_this_set) {
         auto size_J =  m_orders[o].subsetJ(within_this_set).size();
         if (max_size < size_J) {
             max_size = size_J;
             best_order = o;
         }
     }
     return best_order;
 }
is_valid()
bool pgrouting::vrp::PD_Orders::is_valid (double speed) const
Definition at line 156 of file pd_orders.cpp.
References m_orders, and pgassert.
{
     for (const auto &o : m_orders) {
         if (!o.is_valid(speed)) {
             return false;
         }
         pgassert(o.pickup().is_pickup());
         pgassert(o.delivery().is_delivery());
         /* P -> D */
         pgassert(o.delivery().is_compatible_IJ(o.pickup(), speed));
     }
     return true;
 }
msg()
Pgr_messages& pgrouting::vrp::PD_Orders::msg () const private
Access to the problem's message.
Referenced by build_orders().
operator[]() [1/2]
Order & pgrouting::vrp::PD_Orders::operator[] (size_t o)
Definition at line 170 of file pd_orders.cpp.
References m_orders, and pgassert.
{
     pgassert(i < m_orders.size());
     return m_orders[i];
 }
operator[]() [2/2]
const Order & pgrouting::vrp::PD_Orders::operator[] (size_t o) const
Definition at line 176 of file pd_orders.cpp.
References m_orders, and pgassert.
{
     pgassert(i < m_orders.size());
     return m_orders[i];
 }
set_compatibles()
void pgrouting::vrp::PD_Orders::set_compatibles (double speed)
Definition at line 182 of file pd_orders.cpp.
References m_orders.
Referenced by pgrouting::vrp::Vehicle_pickDeliver::set_compatibles().
{
     for (auto &I : m_orders) {
         for (const auto &J : m_orders) {
             I.set_compatibles(J, speed);
         }
     }
 }
size()
size_t pgrouting::vrp::PD_Orders::size () const inline
Definition at line 81 of file pd_orders.h.
References m_orders.
Referenced by pgrouting::vrp::Pgr_pickDeliver::solve().
 {return m_orders.size();}
Friends And Related Function Documentation
PD_problem
friend class PD_problem friend
PD_rpblem needs access to set up the problem pointer.
Definition at line 51 of file pd_orders.h.
Member Data Documentation
m_orders
Orders pgrouting::vrp::PD_Orders::m_orders private
Definition at line 99 of file pd_orders.h.
Referenced by add_order(), begin(), end(), find_best_I(), find_best_J(), is_valid(), operator[](), set_compatibles(), and size().
problem
Pgr_pickDeliver * pgrouting::vrp::PD_Orders::problem static private
The problem.
Definition at line 105 of file pd_orders.h.
Referenced by add_order(), build_orders(), and pgrouting::vrp::PD_problem::PD_problem().
The documentation for this class was generated from the following files:
pd_orders.h
pd_orders.cpp