PGROUTING: pgrouting::functions::Pgr_sequentialVertexColoring< G > Class Template Reference
pgrouting::functions::Pgr_sequentialVertexColoring< G > Class Template Reference
#include "pgr_sequentialVertexColoring.hpp"
Public Types
typedef G::E E
typedef boost::adjacency_list< boost::listS, boost::vecS, boost::undirectedS > Graph
typedef G::V V
typedef boost::graph_traits< Graph >::vertices_size_type vertices_size_type
SequentialVertexColoring
std::vector< pgr_vertex_color_rt > sequentialVertexColoring (G &graph)
sequentialVertexColoring function
std::vector< pgr_vertex_color_rt > get_results (std::vector< vertices_size_type > &colors, const G &graph)
to get the results
Detailed Description
template<class G>
class pgrouting::functions::Pgr_sequentialVertexColoring< G >
Definition at line 58 of file pgr_sequentialVertexColoring.hpp.
Member Typedef Documentation
E
template<class G > typedef G::E pgrouting::functions::Pgr_sequentialVertexColoring< G >::E
Definition at line 61 of file pgr_sequentialVertexColoring.hpp.
Graph
template<class G > typedef boost::adjacency_list< boost::listS, boost::vecS, boost::undirectedS > pgrouting::functions::Pgr_sequentialVertexColoring< G >::Graph
Definition at line 62 of file pgr_sequentialVertexColoring.hpp.
V
template<class G > typedef G::V pgrouting::functions::Pgr_sequentialVertexColoring< G >::V
Definition at line 60 of file pgr_sequentialVertexColoring.hpp.
vertices_size_type
template<class G > typedef boost::graph_traits< Graph >::vertices_size_type pgrouting::functions::Pgr_sequentialVertexColoring< G >::vertices_size_type
Definition at line 63 of file pgr_sequentialVertexColoring.hpp.
Member Function Documentation
get_results()
template<class G > std::vector< pgr_vertex_color_rt > pgrouting::functions::Pgr_sequentialVertexColoring< G >::get_results (std::vector< vertices_size_type > & colors, const G & graph) inline private
to get the results
Uses the colors vector to get the results i.e. the color of every vertex.
Parameters
colors vector which contains the color of every vertex
graph the graph containing the edges
Returns
results vector
Definition at line 124 of file pgr_sequentialVertexColoring.hpp.
{
          std::vector < pgr_vertex_color_rt > results;
          typename boost::graph_traits < Graph > ::vertex_iterator v, vend;
          for (boost::tie(v, vend) = vertices(graph.graph); v != vend; ++v) {
              int64_t node = graph[*v].id;
              auto color = colors[*v];
              results.push_back({ node, static_cast<int64_t>(color + 1) });
          }
          // ordering the results in an increasing order of the node id
          std::sort(results.begin(), results.end(),
              [](const pgr_vertex_color_rt row1, const pgr_vertex_color_rt row2) {
                  return row1.node < row2.node;
              });
          return results;
      }
Referenced by pgrouting::functions::Pgr_sequentialVertexColoring< G >::sequentialVertexColoring().
sequentialVertexColoring()
template<class G > std::vector< pgr_vertex_color_rt > pgrouting::functions::Pgr_sequentialVertexColoring< G >::sequentialVertexColoring (G & graph) inline
sequentialVertexColoring function
It does all the processing and returns the results.
Parameters
graph the graph containing the edges
Returns
results, when results are found
See also
boost::sequential_vertex_coloring
Definition at line 81 of file pgr_sequentialVertexColoring.hpp.
{
          std::vector < pgr_vertex_color_rt > results;
          auto i_map = boost::get(boost::vertex_index, graph.graph);
          // vector which will store the color of all the vertices in the graph
          std::vector < vertices_size_type > colors(boost::num_vertices(graph.graph));
          // An iterator property map which records the color of each vertex
          auto color_map = boost::make_iterator_property_map(colors.begin(), i_map);
          /* abort in case of an interruption occurs (e.g. the query is being cancelled) */
          CHECK_FOR_INTERRUPTS();
          try {
              boost::sequential_vertex_coloring(graph.graph, color_map);
          } catch (boost::exception const& ex) {
              (void)ex;
              throw;
          } catch (std::exception &e) {
              (void)e;
              throw;
          } catch (...) {
              throw;
          }
          results = get_results(colors, graph);
          return results;
      }
References pgrouting::functions::Pgr_sequentialVertexColoring< G >::get_results().
Referenced by pgr_sequentialVertexColoring().
The documentation for this class was generated from the following file:
pgr_sequentialVertexColoring.hpp