PGROUTING: pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor Class Reference
pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor Class Reference
#include "pgr_turnRestrictedPath.hpp"
Public Member Functions
Myvisitor (pSet &solutions, std::vector< trsp::Rule > &restrictions, bool stop_on_first)
void on_insert_first_solution (const Path path) const
void on_insert_to_heap (const Path path) const
Private Member Functions
bool has_restriction (const Path &path) const
Private Attributes
std::vector< trsp::Rule > & m_restrictions
pSet & m_solutions
bool m_stop_on_first
Detailed Description
template<typename G>
class pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor
Definition at line 58 of file pgr_turnRestrictedPath.hpp.
Constructor & Destructor Documentation
Myvisitor()
template<typename G > pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::Myvisitor (pSet & solutions, std::vector< trsp::Rule > & restrictions, bool stop_on_first) inline
Definition at line 60 of file pgr_turnRestrictedPath.hpp.
                                     :
              m_stop_on_first(stop_on_first),
              m_solutions(solutions),
              m_restrictions(restrictions) {
              }
Member Function Documentation
has_restriction()
template<typename G > bool pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::has_restriction (const Path & path) const inline private
Definition at line 90 of file pgr_turnRestrictedPath.hpp.
{
              for (const auto r :  m_restrictions) {
                  if (path.has_restriction(r)) {
                      return true;
                  }
              }
              return false;
          }
References Path::has_restriction(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::m_restrictions.
Referenced by pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::on_insert_first_solution(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::on_insert_to_heap().
on_insert_first_solution()
template<typename G > void pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::on_insert_first_solution (const Path path) const inline virtual
Reimplemented from pgrouting::yen::Pgr_ksp< G >::Visitor.
Definition at line 69 of file pgr_turnRestrictedPath.hpp.
{
              if (path.empty()) return;
              if (has_restriction(path)) return;
              m_solutions.insert(path);
              if (m_stop_on_first) throw found_goals();
          }
References Path::empty(), pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::has_restriction(), pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::m_solutions, and pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::m_stop_on_first.
on_insert_to_heap()
template<typename G > void pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::on_insert_to_heap (const Path path) const inline virtual
Reimplemented from pgrouting::yen::Pgr_ksp< G >::Visitor.
Definition at line 78 of file pgr_turnRestrictedPath.hpp.
{
              if (path.empty()) return;
              if (has_restriction(path)) return;
              m_solutions.insert(path);
              if (m_stop_on_first) {
                  throw found_goals();
              }
          }
References Path::empty(), pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::has_restriction(), pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::m_solutions, and pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::m_stop_on_first.
Member Data Documentation
m_restrictions
template<typename G > std::vector<trsp::Rule>& pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::m_restrictions private
Definition at line 102 of file pgr_turnRestrictedPath.hpp.
Referenced by pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::has_restriction().
m_solutions
template<typename G > pSet& pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::m_solutions private
Definition at line 101 of file pgr_turnRestrictedPath.hpp.
Referenced by pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::on_insert_first_solution(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::on_insert_to_heap().
m_stop_on_first
template<typename G > bool pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::m_stop_on_first private
Definition at line 100 of file pgr_turnRestrictedPath.hpp.
Referenced by pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::on_insert_first_solution(), and pgrouting::yen::Pgr_turnRestrictedPath< G >::Myvisitor::on_insert_to_heap().
The documentation for this class was generated from the following file:
pgr_turnRestrictedPath.hpp