PGROUTING: pgrouting::functions::Pgr_LTDTree< G > Class Template Reference
pgrouting::functions::Pgr_LTDTree< G > Class Template Reference
#include "lengauerTarjanDominatorTree_driver.hpp"
Public Types
typedef G::E_i E_i
typedef G::V_i V_i
typedef G::V Vertex
Public Member Functions
void clear ()
clear
std::string get_error () const
get_error
std::string get_log () const
get_log
std::string get_notice () const
get_notice
bool has_error () const
get_error
std::vector< II_t_rt > pgr_ltdtree (G &graph, int64_t root)
Public Attributes
std::ostringstream error
Stores the error information.
std::ostringstream log
Stores the hint information.
std::ostringstream notice
Stores the notice information.
Detailed Description
template<class G>
class pgrouting::functions::Pgr_LTDTree< G >
Definition at line 55 of file lengauerTarjanDominatorTree_driver.hpp.
Member Typedef Documentation
E_i
template<class G > typedef G::E_i pgrouting::functions::Pgr_LTDTree< G >::E_i
Definition at line 58 of file lengauerTarjanDominatorTree_driver.hpp.
V_i
template<class G > typedef G::V_i pgrouting::functions::Pgr_LTDTree< G >::V_i
Definition at line 59 of file lengauerTarjanDominatorTree_driver.hpp.
Vertex
template<class G > typedef G::V pgrouting::functions::Pgr_LTDTree< G >::Vertex
Definition at line 57 of file lengauerTarjanDominatorTree_driver.hpp.
Member Function Documentation
clear()
void pgrouting::Pgr_messages::clear () inherited
clear
Clears All the messages
Definition at line 58 of file messages.cpp.
                    {
    log.str("");
    log.clear();
    notice.str("");
    notice.clear();
    error.str("");
    error.clear();
}
References pgrouting::Pgr_messages::error, pgrouting::Pgr_messages::log, and pgrouting::Pgr_messages::notice.
Referenced by pgr_do_pickDeliver().
get_error()
std::string pgrouting::Pgr_messages::get_error () const inherited
get_error
Returns
the current contents of the log and clears the log
Definition at line 52 of file messages.cpp.
{
    auto str = error.str();
    return str;
}
References pgrouting::Pgr_messages::error.
Referenced by pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), do_shortestPath(), pgr_do_pickDeliver(), pgr_do_pickDeliverEuclidean(), pgr_do_trsp_withPoints(), pgr_do_trspVia_withPoints(), pgr_do_withPoints(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), and pgr_do_withPointsVia().
get_log()
std::string pgrouting::Pgr_messages::get_log () const inherited
get_log
Returns
the current contents of the log and clears the log
Definition at line 35 of file messages.cpp.
{
    auto str = log.str();
    return str;
}
References pgrouting::Pgr_messages::log.
Referenced by pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), do_shortestPath(), pgr_do_bipartite(), pgr_do_boyerMyrvold(), pgr_do_LTDTree(), pgr_do_makeConnected(), pgr_do_pickDeliver(), pgr_do_pickDeliverEuclidean(), pgr_do_trsp_withPoints(), pgr_do_trspVia_withPoints(), pgr_do_withPoints(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), and pgr_do_withPointsVia().
get_notice()
std::string pgrouting::Pgr_messages::get_notice () const inherited
get_notice
Returns
the current contents of the log and clears the log
Definition at line 41 of file messages.cpp.
{
    auto str = notice.str();
    return str;
}
References pgrouting::Pgr_messages::notice.
has_error()
bool pgrouting::Pgr_messages::has_error () const inherited
get_error
Returns
the current contents of the log and clears the log
Definition at line 47 of file messages.cpp.
{
    return  !error.str().empty();
}
References pgrouting::Pgr_messages::error.
Referenced by do_shortestPath(), pgr_do_trsp_withPoints(), pgr_do_trspVia_withPoints(), pgr_do_withPoints(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), and pgr_do_withPointsVia().
pgr_ltdtree()
template<class G > std::vector< II_t_rt > pgrouting::functions::Pgr_LTDTree< G >::pgr_ltdtree (G & graph, int64_t root) inline
Definition at line 60 of file lengauerTarjanDominatorTree_driver.hpp.
                     {
                std::vector<II_t_rt> results;
                if (!graph.has_vertex(root)) return results;
                std::vector<int64_t> idoms = std::vector<int64_t>(boost::num_vertices(graph.graph), -1);
                auto dominatorTree =
                make_iterator_property_map
                (idoms.begin(), boost::get(boost::vertex_index, graph.graph));
               /* abort in case of an interruption occurs (e.g. the query is being cancelled) */
                CHECK_FOR_INTERRUPTS();
                try {
             // calling the boost function
                boost::lengauer_tarjan_dominator_tree(graph.graph, graph.get_V(root), dominatorTree);
                     } catch (boost::exception const& ex) {
                          (void)ex;
                             throw;
                     } catch (std::exception &e) {
                         (void)e;
                         throw;
                      } catch (...) {
                          throw;
                      }
                V_i v, vend;
                for (boost::tie(v, vend) = vertices(graph.graph); v != vend; ++v) {
                    int64_t vid = graph[*v].id;
                    results.push_back({{vid}, {(idoms[*v] != -1 ? (idoms[*v]+1) : 0)}});
                }
                 return results;
            }
References CHECK_FOR_INTERRUPTS.
Referenced by pgr_do_LTDTree().
Member Data Documentation
error
std::ostringstream pgrouting::Pgr_messages::error mutable inherited
Stores the error information.
Definition at line 84 of file messages.hpp.
Referenced by pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::Pg_points_graph::check_points(), pgrouting::Pgr_messages::clear(), pgrouting::Pg_points_graph::create_new_edges(), pgrouting::Pgr_messages::get_error(), pgrouting::Pgr_messages::has_error(), and pgrouting::vrp::Fleet::is_fleet_ok().
log
std::ostringstream pgrouting::Pgr_messages::log mutable inherited
Stores the hint information.
Definition at line 80 of file messages.hpp.
Referenced by pgrouting::vrp::Optimize::Optimize(), pgrouting::Pg_points_graph::Pg_points_graph(), pgrouting::vrp::Pgr_pickDeliver::Pgr_pickDeliver(), pgrouting::vrp::Solution::Solution(), pgrouting::vrp::Vehicle::Vehicle(), pgrouting::Pgr_bellman_ford< G >::bellman_ford_1_to_many(), pgrouting::vrp::Fleet::build_fleet(), pgrouting::Pg_points_graph::check_points(), pgrouting::Pgr_messages::clear(), pgrouting::Pg_points_graph::create_new_edges(), pgrouting::functions::Pgr_makeConnected< G >::generatemakeConnected(), pgrouting::Pgr_messages::get_log(), pgrouting::vrp::Pgr_pickDeliver::get_postgres_result(), pgrouting::vrp::Vehicle::get_postgres_result(), pgrouting::functions::CuthillMckeeOrdering< G >::get_results(), pgrouting::functions::SloanOrdering< G >::get_results(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Fleet::get_truck(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Optimize::inter_swap(), pgrouting::vrp::Fleet::is_fleet_ok(), pgrouting::vrp::Initial_solution::one_truck_all_orders(), pgrouting::vrp::Optimize::save_if_best(), and pgrouting::vrp::Pgr_pickDeliver::solve().
notice
std::ostringstream pgrouting::Pgr_messages::notice mutable inherited
Stores the notice information.
Definition at line 82 of file messages.hpp.
Referenced by pgrouting::Pgr_messages::clear(), and pgrouting::Pgr_messages::get_notice().
The documentation for this class was generated from the following file:
lengauerTarjanDominatorTree_driver.hpp