PGROUTING: combinations_input.c File Reference
combinations_input.c File Reference
#include "c_common/combinations_input.h"
#include <math.h>
#include <float.h>
#include <limits.h>
#include <stddef.h>
#include "c_types/column_info_t.h"
#include "c_types/pgr_combination_t.h"
#include "c_common/debug_macro.h"
#include "c_common/get_check_data.h"
#include "c_common/time_msg.h"
Functions
static void fetch_combination (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info[2], pgr_combination_t *combination, size_t *valid_combinations)
static void get_combinations_2_columns (char *sql, pgr_combination_t **combinations, size_t *totalTuples)
void pgr_get_combinations (char *combinations_sql, pgr_combination_t **combinations, size_t *total_combinations)
combinations_sql
Function Documentation
fetch_combination()
static void fetch_combination (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info[2], pgr_combination_t * combination, size_t * valid_combinations) static
Definition at line 50 of file combinations_input.c.
{
     combination->source = pgr_SPI_getBigInt(tuple, tupdesc, info[0]);
     combination->target = pgr_SPI_getBigInt(tuple, tupdesc, info[1]);
     *valid_combinations = *valid_combinations + 1;
 }
References pgr_SPI_getBigInt(), pgr_combination_t::source, and pgr_combination_t::target.
Referenced by get_combinations_2_columns().
get_combinations_2_columns()
static void get_combinations_2_columns (char * sql, pgr_combination_t ** combinations, size_t * totalTuples) static
Definition at line 66 of file combinations_input.c.
{
     clock_t start_t = clock();
     const int tuple_limit = 1000000;
     size_t total_tuples;
     size_t valid_combinations;
     Column_info_t info[2];
     int i;
     for (i = 0; i < 2; ++i) {
         info[i].colNumber = -1;
         info[i].type = 0;
         info[i].strict = true;
         info[i].eType = ANY_INTEGER;
     }
     info[0].name = "source";
     info[1].name = "target";
     void *SPIplan;
     SPIplan = pgr_SPI_prepare(sql);
     Portal SPIportal;
     SPIportal = pgr_SPI_cursor_open(SPIplan);
     bool moredata = true;
     (*totalTuples) = total_tuples = valid_combinations = 0;
     while (moredata == true) {
         SPI_cursor_fetch(SPIportal, true, tuple_limit);
         if (total_tuples == 0)
             pgr_fetch_column_info(info, 2);
         size_t ntuples = SPI_processed;
         total_tuples += ntuples;
         if (ntuples > 0) {
             if ((*combinations) == NULL)
                 (*combinations) = (pgr_combination_t *)
                     palloc0(total_tuples * sizeof(pgr_combination_t));
             else
                 (*combinations) = (pgr_combination_t *)
                     repalloc((*combinations), total_tuples * sizeof(pgr_combination_t));
             if ((*combinations) == NULL) {
                 elog(ERROR, "Out of memory");
             }
             size_t t;
             SPITupleTable *tuptable = SPI_tuptable;
             TupleDesc tupdesc = SPI_tuptable->tupdesc;
             for (t = 0; t < ntuples; t++) {
                 HeapTuple tuple = tuptable->vals[t];
                 fetch_combination(&tuple, &tupdesc, info,
                                   &(*combinations)[total_tuples - ntuples + t],
                                   &valid_combinations);
             }
             SPI_freetuptable(tuptable);
         } else {
             moredata = false;
         }
     }
     SPI_cursor_close(SPIportal);
     if (total_tuples == 0 || valid_combinations == 0) {
         PGR_DBG("No combinations found");
     }
     (*totalTuples) = total_tuples;
     PGR_DBG("Reading %ld combinations", total_tuples);
     time_msg("reading combinations", start_t, clock());
 }
References ANY_INTEGER, Column_info_t::colNumber, Column_info_t::eType, fetch_combination(), Column_info_t::name, PGR_DBG, pgr_fetch_column_info(), pgr_SPI_cursor_open(), pgr_SPI_prepare(), Column_info_t::strict, time_msg(), and Column_info_t::type.
Referenced by pgr_get_combinations().
pgr_get_combinations()
void pgr_get_combinations (char * combinations_sql, pgr_combination_t ** combinations, size_t * total_combinations)
combinations_sql
SELECT source, target
FROM combinations_table;
Parameters
[in] combinations_sql
[out] combinations
[out] combinations_edges
Definition at line 147 of file combinations_input.c.
{
     get_combinations_2_columns(combinations_sql, combinations, total_combinations);
 }
References get_combinations_2_columns().
Referenced by process_combinations().