PGROUTING: depthFirstSearch_driver.cpp File Reference
depthFirstSearch_driver.cpp File Reference
Handles actual calling of function in the pgr_depthFirstSearch.hpp file.
#include "drivers/traversal/depthFirstSearch_driver.h"
#include <vector>
#include <algorithm>
#include <string>
#include "cpp_common/pgr_alloc.hpp"
#include "cpp_common/pgr_assert.h"
#include "traversal/pgr_depthFirstSearch.hpp"
Functions
void do_pgr_depthFirstSearch (pgr_edge_t *data_edges, size_t total_edges, int64_t *rootsArr, size_t size_rootsArr, bool directed, int64_t max_depth, pgr_mst_rt **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
Performs exception handling and converts the results to postgres.
template<class G >
std::vector< pgr_mst_rt > pgr_depthFirstSearch (G &graph, std::vector< int64_t > roots, bool directed, int64_t max_depth)
Calls the main function defined in the C++ Header file.
Detailed Description
Handles actual calling of function in the pgr_depthFirstSearch.hpp file.
Definition in file depthFirstSearch_driver.cpp.
Function Documentation
do_pgr_depthFirstSearch()
void do_pgr_depthFirstSearch (pgr_edge_t * data_edges, size_t total_edges, int64_t * rootsArr, size_t size_rootsArr, bool directed, int64_t max_depth, pgr_mst_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Performs exception handling and converts the results to postgres.
Precondition
log_msg is empty
notice_msg is empty
err_msg is empty
return_tuples is empty
return_count is 0
It builds the graph using the data_edges, depending on whether the graph is directed or undirected. It also converts the C types to the C++ types, such as the rootsArr to roots vector and passes these variables to the template function pgr_depthFirstSearch which calls the main function defined in the C++ Header file. It also does exception handling.
Parameters
data_edges the set of edges from the SQL query
total_edges the total number of edges in the SQL query
rootsArr the array containing the root vertices
size_rootsArr the size of the array containing the root vertices
directed whether the graph is directed or undirected
max_depth the maximum depth of traversal
return_tuples the rows in the result
return_count the count of rows in the result
log_msg stores the log message
notice_msg stores the notice message
err_msg stores the error message
Returns
void
Definition at line 118 of file depthFirstSearch_driver.cpp.
{
     std::ostringstream log;
     std::ostringstream err;
     std::ostringstream notice;
     try {
         pgassert(!(*log_msg));
         pgassert(!(*notice_msg));
         pgassert(!(*err_msg));
         pgassert(!(*return_tuples));
         pgassert(*return_count == 0);
         std::vector < int64_t > roots(rootsArr, rootsArr + size_rootsArr);
         std::vector < pgr_mst_rt > results;
         graphType gType = directed ? DIRECTED : UNDIRECTED;
         if (directed) {
             pgrouting::DirectedGraph digraph(gType);
             digraph.insert_edges(data_edges, total_edges);
             results = pgr_depthFirstSearch(
                     digraph,
                     roots,
                     directed,
                     max_depth);
         } else {
             pgrouting::UndirectedGraph undigraph(gType);
             undigraph.insert_edges(data_edges, total_edges);
             results = pgr_depthFirstSearch(
                     undigraph,
                     roots,
                     directed,
                     max_depth);
         }
         auto count = results.size();
         if (count == 0) {
             (*return_tuples) = NULL;
             (*return_count) = 0;
             notice << "No traversal found";
             *log_msg = pgr_msg(notice.str().c_str());
             return;
         }
         (*return_tuples) = pgr_alloc(count, (*return_tuples));
         for (size_t i = 0; i < count; i++) {
             *((*return_tuples) + i) = results[i];
         }
         (*return_count) = count;
         pgassert(*err_msg == NULL);
         *log_msg = log.str().empty()?
             *log_msg :
             pgr_msg(log.str().c_str());
         *notice_msg = notice.str().empty()?
             *notice_msg :
             pgr_msg(notice.str().c_str());
     } catch (AssertFailedException &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch (std::exception &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch(...) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << "Caught unknown exception!";
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     }
 }
References DIRECTED, pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::insert_edges(), pgassert, pgr_alloc(), pgr_depthFirstSearch(), pgr_free(), pgr_msg(), UNDIRECTED, and AssertFailedException::what().
Referenced by process().
pgr_depthFirstSearch()
template<class G > std::vector< pgr_mst_rt > pgr_depthFirstSearch (G & graph, std::vector< int64_t > roots, bool directed, int64_t max_depth)
Calls the main function defined in the C++ Header file.
Also sorts the root vertices in an increasing order, and removes the duplicated vertices. Then calls the function defined in the C++ Header file - pgr_depthFirstSearch.hpp
Parameters
graph the graph containing the edges
roots the root vertices
directed whether the graph is directed or undirected
max_depth the maximum depth of traversal
log stores the log message
Returns
results, when results are found
Definition at line 73 of file depthFirstSearch_driver.cpp.
{
     std::sort(roots.begin(), roots.end());
     roots.erase(
             std::unique(roots.begin(), roots.end()),
             roots.end());
     pgrouting::functions::Pgr_depthFirstSearch < G > fn_depthFirstSearch;
     auto results = fn_depthFirstSearch.depthFirstSearch(graph, roots, directed, max_depth);
     return results;
 }
References pgrouting::functions::Pgr_depthFirstSearch< G >::depthFirstSearch().
Referenced by do_pgr_depthFirstSearch().