PGROUTING: dijkstra_driver.cpp File Reference
dijkstra_driver.cpp File Reference
#include "drivers/dijkstra/dijkstra_driver.h"
#include <c_types/pgr_combination_t.h>
#include <sstream>
#include <deque>
#include <vector>
#include <algorithm>
#include <limits>
#include "dijkstra/pgr_dijkstra.hpp"
#include "cpp_common/pgr_alloc.hpp"
#include "cpp_common/pgr_assert.h"
Namespaces
detail
Functions
void do_pgr_combinations_dijkstra (pgr_edge_t *data_edges, size_t total_edges, pgr_combination_t *combinations, size_t total_combinations, bool directed, bool only_cost, bool normal, General_path_element_t **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
void do_pgr_many_to_many_dijkstra (pgr_edge_t *data_edges, size_t total_edges, int64_t *start_vidsArr, size_t size_start_vidsArr, int64_t *end_vidsArr, size_t size_end_vidsArr, bool directed, bool only_cost, bool normal, int64_t n_goals, General_path_element_t **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
template<class G >
std::deque< Path > detail::pgr_dijkstra (G &graph, std::vector< int64_t > sources, std::vector< int64_t > targets, bool only_cost, bool normal, size_t n_goals)
template<class G >
std::deque< Path > detail::pgr_dijkstra (G &graph, std::vector< pgr_combination_t > &combinations, bool only_cost, bool normal)
void detail::post_process (std::deque< Path > &paths, bool only_cost, bool normal, size_t n_goals)
Function Documentation
do_pgr_combinations_dijkstra()
void do_pgr_combinations_dijkstra (pgr_edge_t * data_edges, size_t total_edges, pgr_combination_t * combinations, size_t total_combinations, bool directed, bool only_cost, bool normal, General_path_element_t ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 260 of file dijkstra_driver.cpp.
{
     std::ostringstream log;
     std::ostringstream err;
     std::ostringstream notice;
     try {
         pgassert(total_edges != 0);
         pgassert(total_combinations != 0);
         pgassert(!(*log_msg));
         pgassert(!(*notice_msg));
         pgassert(!(*err_msg));
         pgassert(!(*return_tuples));
         pgassert(*return_count == 0);
         graphType gType = directed? DIRECTED: UNDIRECTED;
         log << "Inserting combinations into a c++ vector structure";
         std::vector<pgr_combination_t>
                 combinations_vector(combinations, combinations + total_combinations);
         std::deque< Path >paths;
         if (directed) {
             log << "\nWorking with directed Graph";
             pgrouting::DirectedGraph digraph(gType);
             digraph.insert_edges(data_edges, total_edges);
             paths = detail::pgr_dijkstra(
                     digraph,
                     combinations_vector,
                     only_cost, normal);
         } else {
             log << "\nWorking with Undirected Graph";
             pgrouting::UndirectedGraph undigraph(gType);
             undigraph.insert_edges(data_edges, total_edges);
             paths = detail::pgr_dijkstra(
                     undigraph,
                     combinations_vector,
                     only_cost, normal);
         }
         combinations_vector.clear();
         size_t count(0);
         count = count_tuples(paths);
         if (count == 0) {
             (*return_tuples) = NULL;
             (*return_count) = 0;
             notice <<
                    "No paths found";
             *log_msg = pgr_msg(notice.str().c_str());
             return;
         }
         (*return_tuples) = pgr_alloc(count, (*return_tuples));
         log << "\nConverting a set of paths into the tuples";
         (*return_count) = (collapse_paths(return_tuples, paths));
         *log_msg = log.str().empty()?
                    *log_msg :
                    pgr_msg(log.str().c_str());
         *notice_msg = notice.str().empty()?
                       *notice_msg :
                       pgr_msg(notice.str().c_str());
     } catch (AssertFailedException &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch (std::exception &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch(...) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << "Caught unknown exception!";
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     }
 }
References collapse_paths(), count_tuples(), DIRECTED, pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::insert_edges(), pgassert, pgr_alloc(), detail::pgr_dijkstra(), pgr_free(), pgr_msg(), UNDIRECTED, and AssertFailedException::what().
Referenced by process_combinations().
do_pgr_many_to_many_dijkstra()
void do_pgr_many_to_many_dijkstra (pgr_edge_t * data_edges, size_t total_edges, int64_t * start_vidsArr, size_t size_start_vidsArr, int64_t * end_vidsArr, size_t size_end_vidsArr, bool directed, bool only_cost, bool normal, int64_t n_goals, General_path_element_t ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 153 of file dijkstra_driver.cpp.
{
     std::ostringstream log;
     std::ostringstream err;
     std::ostringstream notice;
     try {
         pgassert(total_edges != 0);
         pgassert(!(*log_msg));
         pgassert(!(*notice_msg));
         pgassert(!(*err_msg));
         pgassert(!(*return_tuples));
         pgassert(*return_count == 0);
         graphType gType = directed? DIRECTED: UNDIRECTED;
         log << "Inserting vertices into a c++ vector structure";
         std::vector<int64_t>
             start_vertices(start_vidsArr, start_vidsArr + size_start_vidsArr);
         std::vector< int64_t >
             end_vertices(end_vidsArr, end_vidsArr + size_end_vidsArr);
         size_t n = n_goals <= 0? (std::numeric_limits<size_t>::max)() : static_cast<size_t>(n_goals);
         std::deque< Path >paths;
         if (directed) {
             log << "\nWorking with directed Graph";
             pgrouting::DirectedGraph digraph(gType);
             digraph.insert_edges(data_edges, total_edges);
             paths = detail::pgr_dijkstra(
                     digraph,
                     start_vertices, end_vertices,
                     only_cost, normal, n);
         } else {
             log << "\nWorking with Undirected Graph";
             pgrouting::UndirectedGraph undigraph(gType);
             undigraph.insert_edges(data_edges, total_edges);
             paths = detail::pgr_dijkstra(
                     undigraph,
                     start_vertices, end_vertices,
                     only_cost, normal, n);
         }
         size_t count(0);
         count = count_tuples(paths);
         if (count == 0) {
             (*return_tuples) = NULL;
             (*return_count) = 0;
             notice <<
                 "No paths found";
             *log_msg = pgr_msg(notice.str().c_str());
             return;
         }
         (*return_tuples) = pgr_alloc(count, (*return_tuples));
         log << "\nConverting a set of paths into the tuples";
         (*return_count) = (collapse_paths(return_tuples, paths));
         *log_msg = log.str().empty()?
             *log_msg :
             pgr_msg(log.str().c_str());
         *notice_msg = notice.str().empty()?
             *notice_msg :
             pgr_msg(notice.str().c_str());
     } catch (AssertFailedException &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch (std::exception &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch(...) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << "Caught unknown exception!";
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     }
 }
References collapse_paths(), count_tuples(), DIRECTED, pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::insert_edges(), pgassert, pgr_alloc(), detail::pgr_dijkstra(), pgr_free(), pgr_msg(), UNDIRECTED, and AssertFailedException::what().
Referenced by process().