PGROUTING: CMakeLists.txt File Reference
CMakeLists.txt File Reference
Functions
if (DOXYGEN_FOUND) configure_file($
option (BUILD_DOXY "Set ON|OFF (default=OFF) to build Developers Documentation" ON) if(BUILD_DOXY AND WITH_DOC) message(STATUS "Developers documentation.") find_package(Doxygen $
Function Documentation
if()
if (DOXYGEN_FOUND)
Definition at line 13 of file doxygen/CMakeLists.txt.
                         {CMAKE_CURRENT_SOURCE_DIR}/Doxyfile.in ${CMAKE_CURRENT_BINARY_DIR}/Doxyfile @ONLY)
Referenced by _pgr_alphashape(), _pgr_articulationpoints(), _pgr_astar(), _pgr_bdastar(), _pgr_bddijkstra(), _pgr_bellmanford(), _pgr_bellmanfordneg(), _pgr_biconnectedcomponents(), _pgr_binarybreadthfirstsearch(), _pgr_breadthfirstsearch(), _pgr_bridges(), _pgr_chinesepostman(), _pgr_connectedcomponents(), _pgr_contraction(), _pgr_dagshortestpath(), _pgr_dijkstra(), _pgr_dijkstravia(), _pgr_drivingdistance(), _pgr_edgedisjointpaths(), _pgr_edwardmoore(), _pgr_floydwarshall(), _pgr_johnson(), _pgr_kruskal(), _pgr_ksp(), _pgr_linegraph(), _pgr_linegraphfull(), _pgr_maxcardinalitymatch(), _pgr_maxflow(), _pgr_maxflowmincost(), _pgr_pickdeliver(), _pgr_pickdelivereuclidean(), _pgr_prim(), _pgr_stoerwagner(), _pgr_strongcomponents(), _pgr_topologicalsort(), _pgr_transitiveclosure(), _pgr_trsp(), _pgr_tsp(), _pgr_tspeuclidean(), _pgr_turnrestrictedpath(), _pgr_withpoints(), _pgr_withpointsdd(), _pgr_withpointsksp(), _trsp(), and randomSpanningTree().
option()
option (BUILD_DOXY "Set ON|OFF (default=OFF) to build Developers Documentation" ON)
Definition at line 6 of file doxygen/CMakeLists.txt.
                           {DOXYGEN_MINIMUM_VERSION})