PGROUTING: drivedist_driver.cpp File Reference
drivedist_driver.cpp File Reference
#include "drivers/driving_distance/drivedist_driver.h"
#include <sstream>
#include <deque>
#include <vector>
#include "dijkstra/pgr_dijkstra.hpp"
#include "cpp_common/pgr_alloc.hpp"
#include "cpp_common/pgr_assert.h"
Functions
void do_pgr_driving_many_to_dist (pgr_edge_t *data_edges, size_t total_edges, int64_t *start_vertex, size_t s_len, double distance, bool directedFlag, bool equiCostFlag, General_path_element_t **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
Function Documentation
do_pgr_driving_many_to_dist()
void do_pgr_driving_many_to_dist (pgr_edge_t * data_edges, size_t total_edges, int64_t * start_vertex, size_t s_len, double distance, bool directedFlag, bool equiCostFlag, General_path_element_t ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 82 of file drivedist_driver.cpp.
References collapse_paths(), count_tuples(), DIRECTED, pgrouting::extract_vertices(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::insert_edges(), pgassert, pgr_alloc(), pgrouting::pgr_drivingDistance(), pgr_free(), pgr_msg(), UNDIRECTED, and AssertFailedException::what().
Referenced by process().
{
     std::ostringstream log;
     std::ostringstream err;
     std::ostringstream notice;
     try {
         pgassert(total_edges != 0);
         pgassert(!(*log_msg));
         pgassert(!(*notice_msg));
         pgassert(!(*err_msg));
         pgassert(!(*return_tuples));
         pgassert(*return_count == 0);
         pgassert((*return_tuples) == NULL);
         graphType gType = directedFlag? DIRECTED: UNDIRECTED;
         std::deque<Path> paths;
         std::vector<int64_t> start_vertices(start_vertex, start_vertex + s_len);
         auto vertices(pgrouting::extract_vertices(data_edges, total_edges));
 #ifdef WITH_TIME
         clock_t begin;
         std::time_t start_t;
         std::chrono::steady_clock::time_point begin_elapsed;
 #endif
         if (directedFlag) {
 #ifdef WITH_TIME
             start_timing(start_t, begin_elapsed, begin);
             log << "*********Creating graph at time: " << std::ctime(&start_t)
                 << "\n";
 #endif
             pgrouting::DirectedGraph digraph(vertices, gType);
 #ifdef WITH_TIME
             end_timing(start_t, begin_elapsed, begin, log);
 #endif
 #ifdef WITH_TIME
             start_timing(start_t, begin_elapsed, begin);
             log << "********Inserting edges at time: " << std::ctime(&start_t)
                 << "\n";
 #endif
             digraph.insert_edges(data_edges, total_edges, true);
 #ifdef WITH_TIME
             end_timing(start_t, begin_elapsed, begin, log);
 #endif
 #ifdef WITH_TIME
             start_timing(start_t, begin_elapsed, begin);
             log << "*******Calling the C++ call to pgr_drivingDistance: "
                 << std::ctime(&start_t) << "\n";
 #endif
             paths = pgr_drivingDistance(
                     digraph, start_vertices, distance, equiCostFlag, log);
 #ifdef WITH_TIME
             end_timing(start_t, begin_elapsed, begin, log);
 #endif
         } else {
 #ifdef WITH_TIME
             start_timing(start_t, begin_elapsed, begin);
             log << "******Creating graph at time: " << std::ctime(&start_t)
                 << "\n";
 #endif
             pgrouting::UndirectedGraph undigraph(vertices, gType);
 #ifdef WITH_TIME
             end_timing(start_t, begin_elapsed, begin, log);
 #endif
 #ifdef WITH_TIME
             start_timing(start_t, begin_elapsed, begin);
             log << "*******Inserting edges at time: " << std::ctime(&start_t)
                 << "\n";
 #endif
             undigraph.insert_edges(data_edges, total_edges, true);
 #ifdef WITH_TIME
             end_timing(start_t, begin_elapsed, begin, log);
 #endif
 #ifdef WITH_TIME
             start_timing(start_t, begin_elapsed, begin);
             log << "*******Calling the C++ call to pgr_drivingDistance: "
                 << std::ctime(&start_t) << "\n";
 #endif
             paths = pgr_drivingDistance(
                     undigraph, start_vertices, distance, equiCostFlag, log);
 #ifdef WITH_TIME
             end_timing(start_t, begin_elapsed, begin, log);
 #endif
         }
         size_t count(count_tuples(paths));
         if (count == 0) {
             log << "\nNo return values were found";
             *notice_msg = pgr_msg(log.str().c_str());
             return;
         }
         *return_tuples = pgr_alloc(count, (*return_tuples));
         auto trueCount(collapse_paths(return_tuples, paths));
         *return_count = trueCount;
         *log_msg = log.str().empty()?
             *log_msg :
             pgr_msg(log.str().c_str());
         *notice_msg = notice.str().empty()?
             *notice_msg :
             pgr_msg(notice.str().c_str());
     } catch (AssertFailedException &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch (std::exception &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch( ... ) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << "Caught unknown exception!";
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     }
 }