PGROUTING: e_report.c File Reference
e_report.c File Reference
#include "c_common/postgres_connection.h"
#include "c_common/debug_macro.h"
#include "c_common/e_report.h"
Functions
void pgr_error (char *err)
error with no hint
void pgr_error2 (char *log, char *err)
error with hint
void pgr_global_report (char *log, char *notice, char *err)
notice & error
void pgr_notice (char *notice)
notice with no hint
void pgr_notice2 (char *log, char *notice)
notice with hint
Function Documentation
pgr_error()
void pgr_error (char * error_msg)
error with no hint
if (err_msg) {
    pfree(<data>);
}
pgr_error(&error_msg);
precondition: before calling ereport
    assert(!*error_msg);
Definition at line 61 of file e_report.c.
                      {
     PGR_DBG("Returned error message = %s", err);
 #if 0
     char *error = NULL;
     if (*err_msg) {
         error = pgr_cstring2char(*err_msg);
         free(*err_msg);
     }
 #endif
     if (err) {
         ereport(ERROR,
                 (errmsg_internal("Unexpected"),
                  errhint("%s", err)));
     }
 }
References pgr_cstring2char(), and PGR_DBG.
pgr_error2()
void pgr_error2 (char * log_msg, char * error_msg)
error with hint
if (err_msg) {
    pfree(<data>);
}
pgr_error(&log_msg, &error_msg);
precondition: before calling ereport
    assert(!*log_msg);
    assert(!*error_msg);
Definition at line 79 of file e_report.c.
                    {
     PGR_DBG("Returned log message = %s", log);
     PGR_DBG("Returned error message = %s", err);
     if (err) {
         ereport(ERROR,
                 (errmsg_internal("%s", err),
                  errhint("%s", log)));
     }
 }
References PGR_DBG.
pgr_global_report()
void pgr_global_report (char * log_msg, char * notice_msg, char * error_msg)
notice & error
pgr_notice(&log_msg, &notice_msg, &error_msg);
precondition: before calling ereport
    assert(!*log_msg);
    assert(!*notice_msg);
    assert(!*error_msg);
Definition at line 93 of file e_report.c.
                    {
     if (!notice && log) {
         ereport(DEBUG1,
                 (errmsg_internal("%s", log)));
     }
     if (notice) {
         if (log) {
             ereport(NOTICE,
                     (errmsg_internal("%s", notice),
                      errhint("%s", log)));
         } else {
             ereport(NOTICE,
                     (errmsg_internal("%s", notice)));
         }
     }
     if (err) {
         if (log) {
             ereport(ERROR,
                     (errmsg_internal("%s", err),
                      errhint("%s", log)));
         } else {
             ereport(ERROR,
                     (errmsg_internal("%s", err)));
         }
     }
 }
Referenced by compute(), compute_trsp(), process(), and process_combinations().
pgr_notice()
void pgr_notice (char * notice_msg)
notice with no hint
pgr_notice(&log_msg, &notice_msg);
precondition: before calling ereport
    assert(!log_msg);
    assert(!notice_msg);
Definition at line 31 of file e_report.c.
                       {
     PGR_DBG("Returned notice message = %s", notice);
     if (notice) {
         ereport(NOTICE,
                 (errmsg("%s", notice)));
     }
 }
References PGR_DBG.
Referenced by pgr_notice2().
pgr_notice2()
void pgr_notice2 (char * log_msg, char * notice_msg)
notice with hint
pgr_notice(&log_msg, &notice_msg);
precondition: before calling ereport
    assert(!log_msg);
    assert(!notice_msg);
Definition at line 42 of file e_report.c.
                       {
     PGR_DBG("Returned log message = %s", log);
     PGR_DBG("Returned notice message = %s", notice);
     if (log) {
         pgr_notice(notice);
         return;
     }
     if (notice) {
         ereport(NOTICE,
                 (errmsg("%s", notice),
                  errhint("%s", log)));
     }
 }
References PGR_DBG, and pgr_notice().