PGROUTING: edges_input.c File Reference
edges_input.c File Reference
#include "c_common/edges_input.h"
#include <math.h>
#include <float.h>
#include <limits.h>
#include <stddef.h>
#include "c_types/column_info_t.h"
#include "c_common/debug_macro.h"
#include "c_common/get_check_data.h"
#include "c_common/time_msg.h"
Functions
static void fetch_basic_edge (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info[5], int64_t *default_id, pgr_basic_edge_t *edge, size_t *valid_edges)
static void fetch_costFlow_edge (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info[7], int64_t *default_id, int64_t default_rcapacity, float8 default_rcost, pgr_costFlow_t *edge, size_t *valid_edges, bool normal)
static void fetch_edge (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info[5], int64_t *default_id, float8 default_rcost, pgr_edge_t *edge, size_t *valid_edges, bool normal)
static void fetch_edge_with_xy (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info[9], int64_t *default_id, float8 default_rcost, Pgr_edge_xy_t *edge, size_t *valid_edges, bool normal)
static void get_edges_5_columns (char *sql, pgr_edge_t **edges, size_t *totalTuples, bool ignore_id, bool normal)
static void get_edges_9_columns (char *sql, Pgr_edge_xy_t **edges, size_t *total_edges, bool normal)
static void get_edges_basic (char *sql, pgr_basic_edge_t **edges, size_t *totalTuples, bool ignore_id)
static void get_edges_costFlow (char *sql, pgr_costFlow_t **edges, size_t *totalTuples, bool ignore_id)
static void get_edges_flow (char *sql, pgr_edge_t **edges, size_t *totalTuples, bool ignore_id)
void pgr_get_basic_edges (char *sql, pgr_basic_edge_t **edges, size_t *total_edges)
read basic edges
void pgr_get_costFlow_edges (char *sql, pgr_costFlow_t **edges, size_t *total_edges)
read edges for cost flow
void pgr_get_edges (char *edges_sql, pgr_edge_t **edges, size_t *total_edges)
basic edge_sql
void pgr_get_edges_no_id (char *edges_sql, pgr_edge_t **edges, size_t *total_edges)
edges_sql without id parameter
void pgr_get_edges_reversed (char *edges_sql, pgr_edge_t **edges, size_t *total_edges)
void pgr_get_edges_xy (char *edges_sql, Pgr_edge_xy_t **edges, size_t *total_edges)
Edges with x, y vertices values.
void pgr_get_edges_xy_reversed (char *edges_sql, Pgr_edge_xy_t **edges, size_t *total_edges)
for many to 1 on aStar
void pgr_get_flow_edges (char *sql, pgr_edge_t **edges, size_t *total_edges)
read edges for flow
Function Documentation
fetch_basic_edge()
static void fetch_basic_edge (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info[5], int64_t * default_id, pgr_basic_edge_t * edge, size_t * valid_edges) static
Definition at line 44 of file edges_input.c.
{
     if (column_found(info[0].colNumber)) {
         edge->id = pgr_SPI_getBigInt(tuple, tupdesc, info[0]);
     } else {
         edge->id = *default_id;
         ++(*default_id);
     }
     edge->source = pgr_SPI_getBigInt(tuple, tupdesc, info[1]);
     edge->target = pgr_SPI_getBigInt(tuple, tupdesc, info[2]);
     edge->going = pgr_SPI_getFloat8(tuple, tupdesc, info[3]) > 0 ?
         true : false;
     edge->coming = (column_found(info[4].colNumber)
             && pgr_SPI_getFloat8(tuple, tupdesc, info[4]) > 0) ?
         true : false;
     (*valid_edges)++;
 }
References column_found(), edge::id, pgr_SPI_getBigInt(), pgr_SPI_getFloat8(), edge::source, and edge::target.
Referenced by get_edges_basic().
fetch_costFlow_edge()
static void fetch_costFlow_edge (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info[7], int64_t * default_id, int64_t default_rcapacity, float8 default_rcost, pgr_costFlow_t * edge, size_t * valid_edges, bool normal) static
Definition at line 113 of file edges_input.c.
                      {
     if (column_found(info[0].colNumber)) {
         edge->edge_id = pgr_SPI_getBigInt(tuple, tupdesc, info[0]);
     } else {
         edge->edge_id = *default_id;
         ++(*default_id);
     }
     if (normal) {
         edge->source = pgr_SPI_getBigInt(tuple, tupdesc,  info[1]);
         edge->target = pgr_SPI_getBigInt(tuple, tupdesc, info[2]);
     } else {
         edge->target = pgr_SPI_getBigInt(tuple, tupdesc,  info[1]);
         edge->source = pgr_SPI_getBigInt(tuple, tupdesc, info[2]);
     }
     edge->capacity = pgr_SPI_getBigInt(tuple, tupdesc, info[3]);
     if (column_found(info[4].colNumber)) {
         edge->reverse_capacity = pgr_SPI_getBigInt(tuple, tupdesc, info[4]);
     } else {
         edge->reverse_capacity = default_rcapacity;
     }
     edge->cost = pgr_SPI_getFloat8(tuple, tupdesc, info[5]);
     if (column_found(info[6].colNumber)) {
         edge->reverse_cost = pgr_SPI_getFloat8(tuple, tupdesc, info[6]);
     } else {
         edge->reverse_cost = default_rcost;
     }
     *valid_edges = edge->capacity < 0? *valid_edges: *valid_edges + 1;
     *valid_edges = edge->reverse_capacity < 0? *valid_edges: *valid_edges + 1;
 }
References column_found(), edge::cost, pgr_SPI_getBigInt(), pgr_SPI_getFloat8(), edge::reverse_cost, edge::source, and edge::target.
Referenced by get_edges_costFlow().
fetch_edge()
static void fetch_edge (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info[5], int64_t * default_id, float8 default_rcost, pgr_edge_t * edge, size_t * valid_edges, bool normal) static
Definition at line 70 of file edges_input.c.
                      {
     if (column_found(info[0].colNumber)) {
         edge->id = pgr_SPI_getBigInt(tuple, tupdesc, info[0]);
     } else {
         edge->id = *default_id;
         ++(*default_id);
     }
     if (normal) {
         edge->source = pgr_SPI_getBigInt(tuple, tupdesc,  info[1]);
         edge->target = pgr_SPI_getBigInt(tuple, tupdesc, info[2]);
     } else {
         edge->target = pgr_SPI_getBigInt(tuple, tupdesc,  info[1]);
         edge->source = pgr_SPI_getBigInt(tuple, tupdesc, info[2]);
     }
     edge->cost = pgr_SPI_getFloat8(tuple, tupdesc, info[3]);
     if (column_found(info[4].colNumber)) {
         edge->reverse_cost = pgr_SPI_getFloat8(tuple, tupdesc, info[4]);
     } else {
         edge->reverse_cost = default_rcost;
     }
     edge->cost = isinf(edge->cost)?
         DBL_MAX : edge->cost;
     edge->reverse_cost = isinf(edge->reverse_cost)?
         DBL_MAX : edge->reverse_cost;
     *valid_edges = edge->cost < 0? *valid_edges: *valid_edges + 1;
     *valid_edges = edge->reverse_cost < 0? *valid_edges: *valid_edges + 1;
 }
References column_found(), edge::cost, edge::id, pgr_SPI_getBigInt(), pgr_SPI_getFloat8(), edge::reverse_cost, edge::source, and edge::target.
Referenced by get_edges_5_columns(), and get_edges_flow().
fetch_edge_with_xy()
static void fetch_edge_with_xy (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info[9], int64_t * default_id, float8 default_rcost, Pgr_edge_xy_t * edge, size_t * valid_edges, bool normal) static
Definition at line 157 of file edges_input.c.
                      {
     if (column_found(info[0].colNumber)) {
         edge->id = pgr_SPI_getBigInt(tuple, tupdesc, info[0]);
     } else {
         edge->id = *default_id;
         ++(*default_id);
     }
     if (normal) {
         edge->source = pgr_SPI_getBigInt(tuple, tupdesc,  info[1]);
         edge->target = pgr_SPI_getBigInt(tuple, tupdesc, info[2]);
     } else {
         edge->target = pgr_SPI_getBigInt(tuple, tupdesc,  info[1]);
         edge->source = pgr_SPI_getBigInt(tuple, tupdesc, info[2]);
     }
     edge->cost = pgr_SPI_getFloat8(tuple, tupdesc, info[3]);
     if (column_found(info[4].colNumber)) {
         edge->reverse_cost = pgr_SPI_getFloat8(tuple, tupdesc, info[4]);
     } else {
         edge->reverse_cost = default_rcost;
     }
     edge->x1 = pgr_SPI_getFloat8(tuple, tupdesc, info[5]);
     edge->y1 = pgr_SPI_getFloat8(tuple, tupdesc, info[6]);
     edge->x2 = pgr_SPI_getFloat8(tuple, tupdesc, info[7]);
     edge->y2 = pgr_SPI_getFloat8(tuple, tupdesc, info[8]);
 #if 0
     PGR_DBG("%ld", edge->id);
     PGR_DBG("x1=%f y1=%.15lf", edge->x1, edge->y1);
     PGR_DBG("x2=%f y2=%.15lf", edge->x2, edge->y2);
 #endif
     *valid_edges = edge->cost < 0? *valid_edges: *valid_edges + 1;
     *valid_edges = edge->reverse_cost < 0? *valid_edges: *valid_edges + 1;
 }
References column_found(), edge::cost, edge::id, PGR_DBG, pgr_SPI_getBigInt(), pgr_SPI_getFloat8(), edge::reverse_cost, edge::source, and edge::target.
Referenced by get_edges_9_columns().
get_edges_5_columns()
static void get_edges_5_columns (char * sql, pgr_edge_t ** edges, size_t * totalTuples, bool ignore_id, bool normal) static
Definition at line 310 of file edges_input.c.
                      {
     clock_t start_t = clock();
     const int tuple_limit = 1000000;
     size_t total_tuples;
     size_t valid_edges;
     Column_info_t info[5];
     int i;
     for (i = 0; i < 5; ++i) {
         info[i].colNumber = -1;
         info[i].type = 0;
         info[i].strict = true;
         info[i].eType = ANY_INTEGER;
     }
     info[0].name = "id";
     info[1].name = "source";
     info[2].name = "target";
     info[3].name = "cost";
     info[4].name = "reverse_cost";
     info[0].strict = !ignore_id;
     info[4].strict = false;
     info[3].eType = ANY_NUMERICAL;
     info[4].eType = ANY_NUMERICAL;
     void *SPIplan;
     SPIplan = pgr_SPI_prepare(sql);
     Portal SPIportal;
     SPIportal = pgr_SPI_cursor_open(SPIplan);
     bool moredata = true;
     (*totalTuples) = total_tuples = valid_edges = 0;
     int64_t default_id = 0;
     while (moredata == true) {
         SPI_cursor_fetch(SPIportal, true, tuple_limit);
         if (total_tuples == 0)
             pgr_fetch_column_info(info, 5);
         size_t ntuples = SPI_processed;
         total_tuples += ntuples;
         if (ntuples > 0) {
             if ((*edges) == NULL)
                 (*edges) = (pgr_edge_t *)
                     palloc0(total_tuples * sizeof(pgr_edge_t));
             else
                 (*edges) = (pgr_edge_t *)
                     repalloc((*edges), total_tuples * sizeof(pgr_edge_t));
             if ((*edges) == NULL) {
                 elog(ERROR, "Out of memory");
             }
             size_t t;
             SPITupleTable *tuptable = SPI_tuptable;
             TupleDesc tupdesc = SPI_tuptable->tupdesc;
             for (t = 0; t < ntuples; t++) {
                 HeapTuple tuple = tuptable->vals[t];
                 fetch_edge(&tuple, &tupdesc, info,
                         &default_id, -1,
                         &(*edges)[total_tuples - ntuples + t],
                         &valid_edges,
                         normal);
             }
             SPI_freetuptable(tuptable);
         } else {
             moredata = false;
         }
     }
     SPI_cursor_close(SPIportal);
     if (total_tuples == 0 || valid_edges == 0) {
         PGR_DBG("No edges found");
     }
     (*totalTuples) = total_tuples;
     time_msg("reading edges", start_t, clock());
 }
References ANY_INTEGER, ANY_NUMERICAL, Column_info_t::colNumber, Column_info_t::eType, fetch_edge(), Column_info_t::name, PGR_DBG, pgr_fetch_column_info(), pgr_SPI_cursor_open(), pgr_SPI_prepare(), Column_info_t::strict, time_msg(), and Column_info_t::type.
Referenced by pgr_get_edges(), pgr_get_edges_no_id(), and pgr_get_edges_reversed().
get_edges_9_columns()
static void get_edges_9_columns (char * sql, Pgr_edge_xy_t ** edges, size_t * total_edges, bool normal) static
Definition at line 205 of file edges_input.c.
                      {
     clock_t start_t = clock();
     const int tuple_limit = 1000000;
     size_t total_tuples;
     size_t valid_edges;
     Column_info_t info[9];
     info[0].name = "id";
     info[1].name = "source";
     info[2].name = "target";
     info[3].name = "cost";
     info[4].name = "reverse_cost";
     info[5].name = "x1";
     info[6].name = "y1";
     info[7].name = "x2";
     info[8].name = "y2";
     int i;
     for (i = 0; i < 3; ++i) {
         info[i].colNumber = -1;
         info[i].type = 0;
         info[i].strict = true;
         info[i].eType = ANY_INTEGER;
     }
     for (i = 3; i < 9; ++i) {
         info[i].colNumber = -1;
         info[i].type = 0;
         info[i].strict = true;
         info[i].eType = ANY_NUMERICAL;
     }
     /*
      * reverse_cost is optional
      */
     info[4].strict = false;
     void *SPIplan;
     SPIplan = pgr_SPI_prepare(sql);
     Portal SPIportal;
     SPIportal = pgr_SPI_cursor_open(SPIplan);
     bool moredata = true;
     (*total_edges) = total_tuples = valid_edges = 0;
     int64_t default_id = 0;
     while (moredata == true) {
         SPI_cursor_fetch(SPIportal, true, tuple_limit);
         if (total_tuples == 0)
             pgr_fetch_column_info(info, 9);
         size_t ntuples = SPI_processed;
         total_tuples += ntuples;
         if (ntuples > 0) {
             if ((*edges) == NULL)
                 (*edges) = (Pgr_edge_xy_t *)
                     palloc0(total_tuples * sizeof(Pgr_edge_xy_t));
             else
                 (*edges) = (Pgr_edge_xy_t *)
                     repalloc((*edges), total_tuples * sizeof(Pgr_edge_xy_t));
             if ((*edges) == NULL) {
                 elog(ERROR, "Out of memory");
             }
             size_t t;
             SPITupleTable *tuptable = SPI_tuptable;
             TupleDesc tupdesc = SPI_tuptable->tupdesc;
             for (t = 0; t < ntuples; t++) {
                 HeapTuple tuple = tuptable->vals[t];
                 fetch_edge_with_xy(&tuple, &tupdesc, info,
                         &default_id, -1,
                         &(*edges)[total_tuples - ntuples + t],
                         &valid_edges, normal);
             }
             SPI_freetuptable(tuptable);
         } else {
             moredata = false;
         }
     }
     SPI_cursor_close(SPIportal);
     if (total_tuples == 0 || valid_edges == 0) {
         PGR_DBG("No edges found");
     }
     (*total_edges) = total_tuples;
     time_msg("reading edges", start_t, clock());
 }
References ANY_INTEGER, ANY_NUMERICAL, Column_info_t::colNumber, Column_info_t::eType, fetch_edge_with_xy(), Column_info_t::name, PGR_DBG, pgr_fetch_column_info(), pgr_SPI_cursor_open(), pgr_SPI_prepare(), Column_info_t::strict, time_msg(), and Column_info_t::type.
Referenced by pgr_get_edges_xy(), and pgr_get_edges_xy_reversed().
get_edges_basic()
static void get_edges_basic (char * sql, pgr_basic_edge_t ** edges, size_t * totalTuples, bool ignore_id) static
Definition at line 596 of file edges_input.c.
                     {
     clock_t start_t = clock();
     const int tuple_limit = 1000000;
     size_t total_tuples;
     size_t valid_edges;
     Column_info_t info[5];
     int i;
     for (i = 0; i < 5; ++i) {
         info[i].colNumber = -1;
         info[i].type = 0;
         info[i].strict = true;
         info[i].eType = ANY_INTEGER;
     }
     info[0].name = "id";
     info[1].name = "source";
     info[2].name = "target";
     info[3].name = "going";
     info[4].name = "coming";
     info[0].strict = !ignore_id;
     info[4].strict = false;
     info[3].eType = ANY_NUMERICAL;
     info[4].eType = ANY_NUMERICAL;
     void *SPIplan;
     SPIplan = pgr_SPI_prepare(sql);
     Portal SPIportal;
     SPIportal = pgr_SPI_cursor_open(SPIplan);
     bool moredata = true;
     (*totalTuples) = total_tuples = valid_edges = 0;
     int64_t default_id = 0;
     while (moredata == true) {
         SPI_cursor_fetch(SPIportal, true, tuple_limit);
         if (total_tuples == 0)
             pgr_fetch_column_info(info, 5);
         size_t ntuples = SPI_processed;
         total_tuples += ntuples;
         if (ntuples > 0) {
             if ((*edges) == NULL)
                 (*edges) = (pgr_basic_edge_t *)palloc0(
                         total_tuples * sizeof(pgr_basic_edge_t));
             else
                 (*edges) = (pgr_basic_edge_t *)repalloc(
                         (*edges), total_tuples * sizeof(pgr_basic_edge_t));
             if ((*edges) == NULL) {
                 elog(ERROR, "Out of memory");
             }
             size_t t;
             SPITupleTable *tuptable = SPI_tuptable;
             TupleDesc tupdesc = SPI_tuptable->tupdesc;
             for (t = 0; t < ntuples; t++) {
                 HeapTuple tuple = tuptable->vals[t];
                 fetch_basic_edge(&tuple, &tupdesc, info,
                            &default_id,
                            &(*edges)[total_tuples - ntuples + t],
                            &valid_edges);
             }
             SPI_freetuptable(tuptable);
         } else {
             moredata = false;
         }
     }
     SPI_cursor_close(SPIportal);
     if (total_tuples == 0 || valid_edges == 0) {
         PGR_DBG("No edges found");
     }
     (*totalTuples) = total_tuples;
     time_msg("reading edges", start_t, clock());
 }
References ANY_INTEGER, ANY_NUMERICAL, Column_info_t::colNumber, Column_info_t::eType, fetch_basic_edge(), Column_info_t::name, PGR_DBG, pgr_fetch_column_info(), pgr_SPI_cursor_open(), pgr_SPI_prepare(), Column_info_t::strict, time_msg(), and Column_info_t::type.
Referenced by pgr_get_basic_edges().
get_edges_costFlow()
static void get_edges_costFlow (char * sql, pgr_costFlow_t ** edges, size_t * totalTuples, bool ignore_id) static
Definition at line 498 of file edges_input.c.
                     {
     clock_t start_t = clock();
     const int tuple_limit = 1000000;
     size_t total_tuples;
     size_t valid_edges;
     Column_info_t info[7];
     int i;
     for (i = 0; i < 5; ++i) {
         info[i].colNumber = -1;
         info[i].type = 0;
         info[i].strict = true;
         info[i].eType = ANY_INTEGER;
     }
     info[0].name = "id";
     info[1].name = "source";
     info[2].name = "target";
     info[3].name = "capacity";
     info[4].name = "reverse_capacity";
     info[5].name = "cost";
     info[6].name = "reverse_cost";
     info[0].strict = !ignore_id;
     info[4].strict = false;
     info[6].strict = false;
     info[5].eType = ANY_NUMERICAL;
     info[6].eType = ANY_NUMERICAL;
     void *SPIplan;
     SPIplan = pgr_SPI_prepare(sql);
     Portal SPIportal;
     SPIportal = pgr_SPI_cursor_open(SPIplan);
     bool moredata = true;
     (*totalTuples) = total_tuples = valid_edges = 0;
     int64_t default_id = 0;
     while (moredata == true) {
         SPI_cursor_fetch(SPIportal, true, tuple_limit);
         if (total_tuples == 0)
             pgr_fetch_column_info(info, 7);
         size_t ntuples = SPI_processed;
         total_tuples += ntuples;
         if (ntuples > 0) {
             if ((*edges) == NULL)
                 (*edges) = (pgr_costFlow_t *)
                     palloc0(total_tuples * sizeof(pgr_costFlow_t));
             else
                 (*edges) = (pgr_costFlow_t *)
                     repalloc((*edges), total_tuples * sizeof(pgr_costFlow_t));
             if ((*edges) == NULL) {
                 elog(ERROR, "Out of memory");
             }
             size_t t;
             SPITupleTable *tuptable = SPI_tuptable;
             TupleDesc tupdesc = SPI_tuptable->tupdesc;
             for (t = 0; t < ntuples; t++) {
                 HeapTuple tuple = tuptable->vals[t];
                 fetch_costFlow_edge(&tuple, &tupdesc, info,
                                     &default_id, -1, 0,
                                     &(*edges)[total_tuples - ntuples + t],
                                     &valid_edges,
                                     true);
             }
             SPI_freetuptable(tuptable);
         } else {
             moredata = false;
         }
     }
     SPI_cursor_close(SPIportal);
     if (total_tuples == 0 || valid_edges == 0) {
         PGR_DBG("No edges found");
     }
     (*totalTuples) = total_tuples;
     time_msg("reading edges", start_t, clock());
 }
References ANY_INTEGER, ANY_NUMERICAL, Column_info_t::colNumber, Column_info_t::eType, fetch_costFlow_edge(), Column_info_t::name, PGR_DBG, pgr_fetch_column_info(), pgr_SPI_cursor_open(), pgr_SPI_prepare(), Column_info_t::strict, time_msg(), and Column_info_t::type.
Referenced by pgr_get_costFlow_edges().
get_edges_flow()
static void get_edges_flow (char * sql, pgr_edge_t ** edges, size_t * totalTuples, bool ignore_id) static
Definition at line 406 of file edges_input.c.
                     {
     clock_t start_t = clock();
     const int tuple_limit = 1000000;
     size_t total_tuples;
     size_t valid_edges;
     Column_info_t info[5];
     int i;
     for (i = 0; i < 5; ++i) {
         info[i].colNumber = -1;
         info[i].type = 0;
         info[i].strict = true;
         info[i].eType = ANY_INTEGER;
     }
     info[0].name = "id";
     info[1].name = "source";
     info[2].name = "target";
     info[3].name = "capacity";
     info[4].name = "reverse_capacity";
     info[0].strict = !ignore_id;
     info[4].strict = false;
     void *SPIplan;
     SPIplan = pgr_SPI_prepare(sql);
     Portal SPIportal;
     SPIportal = pgr_SPI_cursor_open(SPIplan);
     bool moredata = true;
     (*totalTuples) = total_tuples = valid_edges = 0;
     int64_t default_id = 0;
     while (moredata == true) {
         SPI_cursor_fetch(SPIportal, true, tuple_limit);
         if (total_tuples == 0)
             pgr_fetch_column_info(info, 5);
         size_t ntuples = SPI_processed;
         total_tuples += ntuples;
         if (ntuples > 0) {
             if ((*edges) == NULL)
                 (*edges) = (pgr_edge_t *)
                     palloc0(total_tuples * sizeof(pgr_flow_t));
             else
                 (*edges) = (pgr_edge_t *)
                     repalloc((*edges), total_tuples * sizeof(pgr_flow_t));
             if ((*edges) == NULL) {
                 elog(ERROR, "Out of memory");
             }
             size_t t;
             SPITupleTable *tuptable = SPI_tuptable;
             TupleDesc tupdesc = SPI_tuptable->tupdesc;
             for (t = 0; t < ntuples; t++) {
                 HeapTuple tuple = tuptable->vals[t];
                 fetch_edge(&tuple, &tupdesc, info,
                            &default_id, -1,
                            &(*edges)[total_tuples - ntuples + t],
                            &valid_edges,
                            true);
             }
             SPI_freetuptable(tuptable);
         } else {
             moredata = false;
         }
     }
     SPI_cursor_close(SPIportal);
     if (total_tuples == 0 || valid_edges == 0) {
         PGR_DBG("No edges found");
     }
     (*totalTuples) = total_tuples;
     time_msg("Reading edges", start_t, clock());
 }
References ANY_INTEGER, Column_info_t::colNumber, Column_info_t::eType, fetch_edge(), Column_info_t::name, PGR_DBG, pgr_fetch_column_info(), pgr_SPI_cursor_open(), pgr_SPI_prepare(), Column_info_t::strict, time_msg(), and Column_info_t::type.
Referenced by pgr_get_flow_edges().
pgr_get_basic_edges()
void pgr_get_basic_edges (char * sql, pgr_basic_edge_t ** edges, size_t * total_edges)
read basic edges
For queries of the type:
SELECT id, source, target, going, [coming]
FROM edge_table;
Parameters
[in] sql
[out] edges
[out] total_edges
Definition at line 766 of file edges_input.c.
{
     bool ignore_id = false;
     get_edges_basic(sql, edges, total_edges, ignore_id);
 }
References get_edges_basic().
Referenced by process().
pgr_get_costFlow_edges()
void pgr_get_costFlow_edges (char * sql, pgr_costFlow_t ** edges, size_t * total_edges)
read edges for cost flow
Edges:
bigint id, bigint source, bigint target, bigint capacity, bigint reverse_capacity float cost, float reverse_cost
Parameters
[in] sql
[out] edges
[out] total_edges
Definition at line 701 of file edges_input.c.
{
     bool ignore_id = false;
     get_edges_costFlow(sql, edges, total_edges, ignore_id);
 }
References get_edges_costFlow().
Referenced by process().
pgr_get_edges()
void pgr_get_edges (char * edges_sql, pgr_edge_t ** edges, size_t * total_edges)
basic edge_sql
For queries of the type:
SELECT id, source, target, cost, [reverse_cost]
FROM edge_table;
Parameters
[in] edges_sql
[out] edges
[out] total_edges
Definition at line 711 of file edges_input.c.
{
     bool ignore_id = false;
     bool normal = true;
     get_edges_5_columns(edges_sql, edges, total_edges, ignore_id, normal);
 }
References get_edges_5_columns().
Referenced by compute(), compute_trsp(), process(), and process_combinations().
pgr_get_edges_no_id()
void pgr_get_edges_no_id (char * edges_sql, pgr_edge_t ** edges, size_t * total_edges)
edges_sql without id parameter
SELECT source, target, cost, [reverse_cost]
FROM edge_table;
Currently used in: allpairs
Parameters
[in] edges_sql
[out] edges
[out] total_edges
Definition at line 733 of file edges_input.c.
{
     bool ignore_id = true;
     bool normal = true;
     get_edges_5_columns(edges_sql, edges, total_edges, ignore_id, normal);
 }
References get_edges_5_columns().
Referenced by process().
pgr_get_edges_reversed()
void pgr_get_edges_reversed (char * edges_sql, pgr_edge_t ** edges, size_t * total_edges)
Definition at line 722 of file edges_input.c.
{
     bool ignore_id = false;
     bool normal = false;
     get_edges_5_columns(edges_sql, edges, total_edges, ignore_id, normal);
 }
References get_edges_5_columns().
Referenced by process().
pgr_get_edges_xy()
void pgr_get_edges_xy (char * edges_sql, Pgr_edge_xy_t ** edges, size_t * total_edges)
Edges with x, y vertices values.
For queries of the type:
SELECT id, source, target, cost, [reverse_cost], x1, y1, x2, y2
FROM edge_table;
Parameters
[in] edges_sql
[out] edges
[out] total_edges
Definition at line 744 of file edges_input.c.
{
     get_edges_9_columns(edges_sql, edges, total_edges, true);
 }
References get_edges_9_columns().
Referenced by process().
pgr_get_edges_xy_reversed()
void pgr_get_edges_xy_reversed (char * edges_sql, Pgr_edge_xy_t ** edges, size_t * total_edges)
for many to 1 on aStar
Used internally
Transforms queries of the type:
SELECT id, source, target, cost, [reverse_cost], x1, y1, x2, y2
FROM edge_table;
to
SELECT id, target, source, cost, [reverse_cost], x1, y1, x2, y2
FROM edge_table;
Parameters
[in] edges_sql
[out] edges
[out] total_edges
Definition at line 757 of file edges_input.c.
{
     get_edges_9_columns(edges_sql, edges, total_edges, false);
 }
References get_edges_9_columns().
Referenced by process().
pgr_get_flow_edges()
void pgr_get_flow_edges (char * sql, pgr_edge_t ** edges, size_t * total_edges)
read edges for flow
Edges:
bigint id, bigint source, bigint target, bigint capacity, bigint reverse_capacity
Parameters
[in] sql
[out] edges
[out] total_edges
Definition at line 691 of file edges_input.c.
{
     bool ignore_id = false;
     get_edges_flow(sql, edges, total_edges, ignore_id);
 }
References get_edges_flow().
Referenced by process().