PGROUTING: edges_input.h File Reference
edges_input.h File Reference
#include <stddef.h>
#include "c_types/pgr_costFlow_t.h"
#include "c_types/pgr_flow_t.h"
#include "c_types/pgr_basic_edge_t.h"
#include "c_types/pgr_edge_t.h"
#include "c_types/pgr_edge_xy_t.h"
Functions
void pgr_get_basic_edges (char *sql, pgr_basic_edge_t **edges, size_t *total_edges)
read basic edges
void pgr_get_costFlow_edges (char *sql, pgr_costFlow_t **edges, size_t *total_edges)
read edges for cost flow
void pgr_get_edges (char *edges_sql, pgr_edge_t **edges, size_t *total_edges)
basic edge_sql
void pgr_get_edges_no_id (char *edges_sql, pgr_edge_t **edges, size_t *total_edges)
edges_sql without id parameter
void pgr_get_edges_reversed (char *edges_sql, pgr_edge_t **edges, size_t *total_edges)
void pgr_get_edges_xy (char *edges_sql, Pgr_edge_xy_t **edges, size_t *total_edges)
Edges with x, y vertices values.
void pgr_get_edges_xy_reversed (char *edges_sql, Pgr_edge_xy_t **edges, size_t *total_edges)
for many to 1 on aStar
void pgr_get_flow_edges (char *sql, pgr_edge_t **edges, size_t *total_edges)
read edges for flow
Function Documentation
pgr_get_basic_edges()
void pgr_get_basic_edges (char * sql, pgr_basic_edge_t ** edges, size_t * total_edges)
read basic edges
For queries of the type:
SELECT id, source, target, going, [coming]
FROM edge_table;
Parameters
[in] sql
[out] edges
[out] total_edges
Definition at line 771 of file edges_input.c.
{
     bool ignore_id = false;
     get_edges_basic(sql, edges, total_edges, ignore_id);
 }
References get_edges_basic().
Referenced by process().
pgr_get_costFlow_edges()
void pgr_get_costFlow_edges (char * sql, pgr_costFlow_t ** edges, size_t * total_edges)
read edges for cost flow
Edges:
bigint id, bigint source, bigint target, bigint capacity, bigint reverse_capacity float cost, float reverse_cost
Parameters
[in] sql
[out] edges
[out] total_edges
Definition at line 706 of file edges_input.c.
{
     bool ignore_id = false;
     get_edges_costFlow(sql, edges, total_edges, ignore_id);
 }
References get_edges_costFlow().
Referenced by process().
pgr_get_edges()
void pgr_get_edges (char * edges_sql, pgr_edge_t ** edges, size_t * total_edges)
basic edge_sql
For queries of the type:
SELECT id, source, target, cost, [reverse_cost]
FROM edge_table;
Parameters
[in] edges_sql
[out] edges
[out] total_edges
Definition at line 716 of file edges_input.c.
{
     bool ignore_id = false;
     bool normal = true;
     get_edges_5_columns(edges_sql, edges, total_edges, ignore_id, normal);
 }
References get_edges_5_columns().
Referenced by compute(), compute_trsp(), process(), and process_combinations().
pgr_get_edges_no_id()
void pgr_get_edges_no_id (char * edges_sql, pgr_edge_t ** edges, size_t * total_edges)
edges_sql without id parameter
SELECT source, target, cost, [reverse_cost]
FROM edge_table;
Currently used in: allpairs
Parameters
[in] edges_sql
[out] edges
[out] total_edges
Definition at line 738 of file edges_input.c.
{
     bool ignore_id = true;
     bool normal = true;
     get_edges_5_columns(edges_sql, edges, total_edges, ignore_id, normal);
 }
References get_edges_5_columns().
Referenced by process().
pgr_get_edges_reversed()
void pgr_get_edges_reversed (char * edges_sql, pgr_edge_t ** edges, size_t * total_edges)
Definition at line 727 of file edges_input.c.
{
     bool ignore_id = false;
     bool normal = false;
     get_edges_5_columns(edges_sql, edges, total_edges, ignore_id, normal);
 }
References get_edges_5_columns().
Referenced by process(), and process_combinations().
pgr_get_edges_xy()
void pgr_get_edges_xy (char * edges_sql, Pgr_edge_xy_t ** edges, size_t * total_edges)
Edges with x, y vertices values.
For queries of the type:
SELECT id, source, target, cost, [reverse_cost], x1, y1, x2, y2
FROM edge_table;
Parameters
[in] edges_sql
[out] edges
[out] total_edges
Definition at line 749 of file edges_input.c.
{
     get_edges_9_columns(edges_sql, edges, total_edges, true);
 }
References get_edges_9_columns().
Referenced by process().
pgr_get_edges_xy_reversed()
void pgr_get_edges_xy_reversed (char * edges_sql, Pgr_edge_xy_t ** edges, size_t * total_edges)
for many to 1 on aStar
Used internally
Transforms queries of the type:
SELECT id, source, target, cost, [reverse_cost], x1, y1, x2, y2
FROM edge_table;
to
SELECT id, target, source, cost, [reverse_cost], x1, y1, x2, y2
FROM edge_table;
Parameters
[in] edges_sql
[out] edges
[out] total_edges
Definition at line 762 of file edges_input.c.
{
     get_edges_9_columns(edges_sql, edges, total_edges, false);
 }
References get_edges_9_columns().
Referenced by process().
pgr_get_flow_edges()
void pgr_get_flow_edges (char * sql, pgr_edge_t ** edges, size_t * total_edges)
read edges for flow
Edges:
bigint id, bigint source, bigint target, bigint capacity, bigint reverse_capacity
Parameters
[in] sql
[out] edges
[out] total_edges
Definition at line 696 of file edges_input.c.
{
     bool ignore_id = false;
     get_edges_flow(sql, edges, total_edges, ignore_id);
 }
References get_edges_flow().
Referenced by process().