PGROUTING: euclideanTSP.c File Reference
euclideanTSP.c File Reference
#include "c_common/postgres_connection.h"
#include "c_types/path_rt.h"
#include "c_common/debug_macro.h"
#include "c_common/e_report.h"
#include "c_common/time_msg.h"
#include "c_types/tsp_tour_rt.h"
#include "drivers/tsp/euclideanTSP_driver.h"
Functions
PGDLLEXPORT Datum _pgr_tspeuclidean (PG_FUNCTION_ARGS)
PGDLLEXPORT Datum _pgr_tspeuclidean_v4 (PG_FUNCTION_ARGS)
PG_FUNCTION_INFO_V1 (_pgr_tspeuclidean)
PG_FUNCTION_INFO_V1 (_pgr_tspeuclidean_v4)
static void process (char *coordinates_sql, int64_t start_vid, int64_t end_vid, TSP_tour_rt **result_tuples, size_t *result_count)
Function Documentation
_pgr_tspeuclidean()
PGDLLEXPORT Datum _pgr_tspeuclidean (PG_FUNCTION_ARGS)
Definition at line 161 of file euclideanTSP.c.
{
    FuncCallContext     *funcctx;
    TupleDesc            tuple_desc;
    TSP_tour_rt  *result_tuples = NULL;
    size_t result_count = 0;
    if (SRF_IS_FIRSTCALL()) {
        MemoryContext   oldcontext;
        funcctx = SRF_FIRSTCALL_INIT();
        oldcontext = MemoryContextSwitchTo(funcctx->multi_call_memory_ctx);
#ifdef SHOWMSG
         ereport(NOTICE, (
                     errcode(ERRCODE_WARNING_DEPRECATED_FEATURE),
                     errmsg("A stored procedure is using deprecated C internal function '%s'", __func__),
                     errdetail("Library function '%s' was deprecated in pgRouting %s", __func__, "4.0.0"),
                     errhint("Consider upgrade pgRouting")));
#endif
        process(
                text_to_cstring(PG_GETARG_TEXT_P(0)),
                PG_GETARG_INT64(1),
                PG_GETARG_INT64(2),
                &result_tuples,
                &result_count);
        funcctx->max_calls = result_count;
        funcctx->user_fctx = result_tuples;
        if (get_call_result_type(fcinfo, NULL, &tuple_desc)
                != TYPEFUNC_COMPOSITE) {
            ereport(ERROR,
                    (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
                     errmsg("function returning record called in context "
                         "that cannot accept type record")));
        }
        funcctx->tuple_desc = tuple_desc;
        MemoryContextSwitchTo(oldcontext);
    }
    funcctx = SRF_PERCALL_SETUP();
    tuple_desc = funcctx->tuple_desc;
    result_tuples = (TSP_tour_rt*) funcctx->user_fctx;
    if (funcctx->call_cntr < funcctx->max_calls) {
        HeapTuple    tuple;
        Datum        result;
        Datum        *values;
        bool*        nulls;
        values = palloc(4 * sizeof(Datum));
        nulls = palloc(4 * sizeof(bool));
        size_t i;
        for (i = 0; i < 4; ++i) {
            nulls[i] = false;
        }
        values[0] = Int32GetDatum((int32_t)funcctx->call_cntr + 1);
        values[1] = Int64GetDatum(result_tuples[funcctx->call_cntr].node);
        values[2] = Float8GetDatum(result_tuples[funcctx->call_cntr].cost);
        values[3] = Float8GetDatum(result_tuples[funcctx->call_cntr].agg_cost);
        tuple = heap_form_tuple(tuple_desc, values, nulls);
        result = HeapTupleGetDatum(tuple);
        SRF_RETURN_NEXT(funcctx, result);
    } else {
        SRF_RETURN_DONE(funcctx);
    }
}
References TSP_tour_rt::agg_cost, TSP_tour_rt::cost, TSP_tour_rt::node, and process().
_pgr_tspeuclidean_v4()
PGDLLEXPORT Datum _pgr_tspeuclidean_v4 (PG_FUNCTION_ARGS)
Definition at line 84 of file euclideanTSP.c.
{
    FuncCallContext     *funcctx;
    TupleDesc            tuple_desc;
    TSP_tour_rt  *result_tuples = NULL;
    size_t result_count = 0;
    if (SRF_IS_FIRSTCALL()) {
        MemoryContext   oldcontext;
        funcctx = SRF_FIRSTCALL_INIT();
        oldcontext = MemoryContextSwitchTo(funcctx->multi_call_memory_ctx);
        process(
                text_to_cstring(PG_GETARG_TEXT_P(0)),
                PG_GETARG_INT64(1),
                PG_GETARG_INT64(2),
                &result_tuples,
                &result_count);
        funcctx->max_calls = result_count;
        funcctx->user_fctx = result_tuples;
        if (get_call_result_type(fcinfo, NULL, &tuple_desc)
                != TYPEFUNC_COMPOSITE) {
            ereport(ERROR,
                    (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
                     errmsg("function returning record called in context "
                         "that cannot accept type record")));
        }
        funcctx->tuple_desc = tuple_desc;
        MemoryContextSwitchTo(oldcontext);
    }
    funcctx = SRF_PERCALL_SETUP();
    tuple_desc = funcctx->tuple_desc;
    result_tuples = (TSP_tour_rt*) funcctx->user_fctx;
    if (funcctx->call_cntr < funcctx->max_calls) {
        HeapTuple    tuple;
        Datum        result;
        Datum        *values;
        bool*        nulls;
        values = palloc(4 * sizeof(Datum));
        nulls = palloc(4 * sizeof(bool));
        size_t i;
        for (i = 0; i < 4; ++i) {
            nulls[i] = false;
        }
        values[0] = Int32GetDatum((int32_t)funcctx->call_cntr + 1);
        values[1] = Int64GetDatum(result_tuples[funcctx->call_cntr].node);
        values[2] = Float8GetDatum(result_tuples[funcctx->call_cntr].cost);
        values[3] = Float8GetDatum(result_tuples[funcctx->call_cntr].agg_cost);
        tuple = heap_form_tuple(tuple_desc, values, nulls);
        result = HeapTupleGetDatum(tuple);
        SRF_RETURN_NEXT(funcctx, result);
    } else {
        SRF_RETURN_DONE(funcctx);
    }
}
References TSP_tour_rt::agg_cost, TSP_tour_rt::cost, TSP_tour_rt::node, and process().
PG_FUNCTION_INFO_V1() [1/2]
PG_FUNCTION_INFO_V1 (_pgr_tspeuclidean)
PG_FUNCTION_INFO_V1() [2/2]
PG_FUNCTION_INFO_V1 (_pgr_tspeuclidean_v4)
process()
static void process (char * coordinates_sql, int64_t start_vid, int64_t end_vid, TSP_tour_rt ** result_tuples, size_t * result_count) static
Definition at line 48 of file euclideanTSP.c.
{
    pgr_SPI_connect();
    char* log_msg = NULL;
    char* notice_msg = NULL;
    char* err_msg = NULL;
    clock_t start_t = clock();
    pgr_do_euclideanTSP(
            coordinates_sql,
            start_vid,
            end_vid,
            result_tuples,
            result_count,
            &log_msg,
            &notice_msg,
            &err_msg);
    time_msg("euclideanTSP", start_t, clock());
    if (err_msg && (*result_tuples)) {
        pfree(*result_tuples);
        (*result_tuples) = NULL;
        (*result_count) = 0;
    }
    pgr_global_report(&log_msg, &notice_msg, &err_msg);
    pgr_SPI_finish();
}
References pgr_do_euclideanTSP(), pgr_global_report(), pgr_SPI_connect(), pgr_SPI_finish(), and time_msg().
Referenced by _pgr_tspeuclidean(), and _pgr_tspeuclidean_v4().