PGROUTING: euclideanTSP_driver.h File Reference
euclideanTSP_driver.h File Reference
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
Typedefs
typedef struct TSP_tour_rt TSP_tour_rt
Functions
void pgr_do_euclideanTSP (const char *, int64_t, int64_t, TSP_tour_rt **, size_t *, char **, char **, char **)
Typedef Documentation
TSP_tour_rt
typedef struct TSP_tour_rt TSP_tour_rt
Definition at line 42 of file euclideanTSP_driver.h.
Function Documentation
pgr_do_euclideanTSP()
void pgr_do_euclideanTSP (const char * coordinates_sql, int64_t start_vid, int64_t end_vid, TSP_tour_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 46 of file euclideanTSP_driver.cpp.
{
    using pgrouting::pgr_alloc;
    using pgrouting::to_pg_msg;
    using pgrouting::pgr_free;
    using pgrouting::tsp;
    using pgrouting::pgget::get_coordinates;
    using TSP_graph = pgrouting::graph::UndirectedHasCostBG;
    std::ostringstream log;
    std::ostringstream notice;
    std::ostringstream err;
    const char *hint = nullptr;
    try {
        hint = coordinates_sql;
        auto coordinates = get_coordinates(std::string(coordinates_sql));
        if (coordinates.size() == 0) {
            *notice_msg = to_pg_msg("No coordinates found");
            *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
            return;
        }
        hint = nullptr;
        TSP_graph graph{coordinates};
        if (start_vid != 0 && !graph.has_vertex(start_vid)) {
            err << "Parameter 'start_id' do not exist on the data";
            *err_msg = to_pg_msg(err);
            return;
        }
        if (end_vid != 0 && !graph.has_vertex(end_vid)) {
            err << "Parameter 'end_id' do not exist on the data";
            *err_msg = to_pg_msg(err);
            return;
        }
        auto tsp_path = tsp(graph, start_vid, end_vid);
        if (!tsp_path.empty()) {
            *return_count = tsp_path.size();
            (*return_tuples) = pgr_alloc(tsp_path.size(), (*return_tuples));
            size_t seq{0};
            double total{0};
            for (const auto &e : tsp_path) {
                total += e.second;
                TSP_tour_rt data {e.first, e.second, total};
                (*return_tuples)[seq] = data;
                seq++;
            }
        }
        *log_msg = to_pg_msg(log);
        *notice_msg = to_pg_msg(notice);
    } catch (AssertFailedException &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch (const std::pair<std::string, std::string>& ex) {
        (*return_count) = 0;
        *err_msg = to_pg_msg(ex.first.c_str());
        *log_msg = to_pg_msg(ex.second.c_str());
    } catch (const std::string &ex) {
        *err_msg = to_pg_msg(ex);
        *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
    } catch (std::exception &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch(...) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << "Caught unknown exception!";
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    }
}
References pgrouting::pgget::get_coordinates(), pgrouting::pgr_alloc(), pgrouting::pgr_free(), pgrouting::to_pg_msg(), and AssertFailedException::what().
Referenced by process().