PGROUTING: get_new_queries.cpp File Reference
get_new_queries.cpp File Reference
#include "drivers/withPoints/get_new_queries.h"
#include <string>
#include <sstream>
#include "cpp_common/alloc.hpp"
Functions
char estimate_drivingSide (char driving_side)
void get_new_queries (char *edges_sql, char *points_sql, char **edges_of_points_query, char **edges_no_points_query)
Function Documentation
estimate_drivingSide()
char estimate_drivingSide (char driving_side)
Definition at line 36 of file get_new_queries.cpp.
{
    char d_side = static_cast<char>(tolower(driving_side));
    if (!((d_side == 'r') || (d_side == 'l') || (d_side == 'b'))) {
        d_side = ' ';
    }
    return d_side;
}
Referenced by process(), process(), process(), process(), and process().
get_new_queries()
void get_new_queries (char * edges_sql, char * points_sql, char ** edges_of_points_query, char ** edges_no_points_query)
Definition at line 45 of file get_new_queries.cpp.
{
    using pgrouting::to_pg_msg;
    std::ostringstream edges_of_points_sql;
    std::ostringstream edges_no_points_sql;
    edges_of_points_sql << "WITH "
        << " edges AS (" << edges_sql << "), "
        << " points AS (" << points_sql << ")"
        << " SELECT DISTINCT edges.* FROM edges JOIN points ON (id = edge_id)";
    *edges_of_points_query = to_pg_msg(edges_of_points_sql.str());
    edges_no_points_sql << "WITH "
        << " edges AS (" << edges_sql << "), "
        << " points AS (" << points_sql << ")"
        << " SELECT edges.*"
        << " FROM edges"
        << " WHERE NOT EXISTS (SELECT edge_id FROM points WHERE id = edge_id)";
    *edges_no_points_query = to_pg_msg(edges_no_points_sql.str());
}
References pgrouting::to_pg_msg().
Referenced by process(), process(), process(), process(), and process().