PGROUTING: isPlanar.c File Reference
isPlanar.c File Reference
#include <stdbool.h>
#include "c_common/postgres_connection.h"
#include "utils/array.h"
#include "c_common/debug_macro.h"
#include "c_common/e_report.h"
#include "c_common/time_msg.h"
#include "c_common/edges_input.h"
#include "drivers/planar/isPlanar_driver.h"
Functions
PGDLLEXPORT Datum _pgr_isplanar (PG_FUNCTION_ARGS)
PG_FUNCTION_INFO_V1 (_pgr_isplanar)
static bool process (char *edges_sql)
Function Documentation
_pgr_isplanar()
PGDLLEXPORT Datum _pgr_isplanar (PG_FUNCTION_ARGS)
Definition at line 94 of file isPlanar.c.
{
         /**********************************************************************/
         /*
         pgr_isPlanar(
             edge_sql TEXT)
         */
         /**********************************************************************/
         PG_RETURN_BOOL(process(text_to_cstring(PG_GETARG_TEXT_P(0))));
         /**********************************************************************/
 }
References process().
PG_FUNCTION_INFO_V1()
PG_FUNCTION_INFO_V1 (_pgr_isplanar)
process()
static bool process (char * edges_sql) static
Definition at line 46 of file isPlanar.c.
     {
     bool planarity = false;
     pgr_SPI_connect();
     pgr_edge_t *edges = NULL;
     size_t total_edges = 0;
     pgr_get_edges(edges_sql, &edges, &total_edges);
     if (total_edges == 0) {
         pgr_SPI_finish();
         return (false);
     }
     clock_t start_t = clock();
     char *log_msg = NULL;
     char *notice_msg = NULL;
     char *err_msg = NULL;
     planarity = do_pgr_isPlanar(
         edges,
         total_edges,
         &log_msg,
         &notice_msg,
         &err_msg);
     time_msg(" processing pgr_isPlanar", start_t, clock());
     pgr_global_report(log_msg, notice_msg, err_msg);
     if (edges)
         pfree(edges);
     if (log_msg)
         pfree(log_msg);
     if (notice_msg)
         pfree(notice_msg);
     if (err_msg)
         pfree(err_msg);
     pgr_SPI_finish();
     return planarity;
 }
References do_pgr_isPlanar(), pgr_get_edges(), pgr_global_report(), pgr_SPI_connect(), pgr_SPI_finish(), and time_msg().
Referenced by _pgr_isplanar().