PGROUTING: isPlanar_driver.cpp File Reference
isPlanar_driver.cpp File Reference
#include "drivers/planar/isPlanar_driver.h"
#include <vector>
#include <algorithm>
#include <string>
#include "cpp_common/alloc.hpp"
#include "cpp_common/assert.hpp"
#include "cpp_common/pgdata_getters.hpp"
#include "planar/boyerMyrvold.hpp"
#include "cpp_common/base_graph.hpp"
Functions
bool pgr_do_isPlanar (const char *edges_sql, char **log_msg, char **notice_msg, char **err_msg)
Function Documentation
pgr_do_isPlanar()
bool pgr_do_isPlanar (const char * edges_sql, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 46 of file isPlanar_driver.cpp.
{
    using pgrouting::pgr_alloc;
    using pgrouting::to_pg_msg;
    using pgrouting::pgr_free;
    using pgrouting::pgget::get_edges;
    std::ostringstream log;
    std::ostringstream err;
    std::ostringstream notice;
    const char *hint = nullptr;
    try {
        pgassert(!(*log_msg));
        pgassert(!(*notice_msg));
        pgassert(!(*err_msg));
        bool result = false;
        hint = edges_sql;
        auto edges = get_edges(std::string(edges_sql), true, true);
        if (edges.empty()) {
            return false;
        }
        hint = nullptr;
        pgrouting::UndirectedGraph undigraph;
        undigraph.insert_edges(edges);
        pgrouting::functions::Pgr_boyerMyrvold<pgrouting::UndirectedGraph> fn_isPlanar;
        result = fn_isPlanar.isPlanar(undigraph);
        pgassert(*err_msg == NULL);
        *log_msg = to_pg_msg(log);
        *notice_msg = to_pg_msg(notice);
        return result;
    } catch (AssertFailedException &except) {
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch (const std::string &ex) {
        *err_msg = to_pg_msg(ex);
        *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
    } catch (std::exception &except) {
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch(...) {
        err << "Caught unknown exception!";
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    }
    return false;
}
References pgrouting::pgget::get_edges(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::insert_edges(), pgrouting::functions::Pgr_boyerMyrvold< G >::isPlanar(), pgassert, pgrouting::pgr_alloc(), pgrouting::pgr_free(), pgrouting::to_pg_msg(), and AssertFailedException::what().
Referenced by process().