PGROUTING: kruskal_driver.cpp File Reference
kruskal_driver.cpp File Reference
#include "drivers/spanningTree/kruskal_driver.h"
#include <sstream>
#include <deque>
#include <vector>
#include <string>
#include "cpp_common/pgr_alloc.hpp"
#include "cpp_common/pgr_assert.h"
#include "spanningTree/pgr_kruskal.hpp"
#include "spanningTree/details.hpp"
Functions
void do_pgr_kruskal (pgr_edge_t *data_edges, size_t total_edges, int64_t *rootsArr, size_t size_rootsArr, char *fn_suffix, int64_t max_depth, double distance, pgr_mst_rt **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
Function Documentation
do_pgr_kruskal()
void do_pgr_kruskal (pgr_edge_t * data_edges, size_t total_edges, int64_t * rootsArr, size_t size_rootsArr, char * fn_suffix, int64_t max_depth, double distance, pgr_mst_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 44 of file kruskal_driver.cpp.
{
     std::ostringstream log;
     std::ostringstream err;
     std::ostringstream notice;
     try {
         pgassert(!(*log_msg));
         pgassert(!(*notice_msg));
         pgassert(!(*err_msg));
         pgassert(!(*return_tuples));
         pgassert(*return_count == 0);
         std::vector<int64_t> roots(rootsArr, rootsArr + size_rootsArr);
         std::string suffix(fn_suffix);
         std::vector<pgr_mst_rt> results;
         if (total_edges == 0) {
             results = pgrouting::details::get_no_edge_graph_result(roots);
         } else {
             pgrouting::UndirectedGraph undigraph(UNDIRECTED);
             undigraph.insert_edges(data_edges, total_edges);
             pgrouting::functions::Pgr_kruskal
                 <pgrouting::UndirectedGraph> kruskal;
             if (suffix == "") {
                 results = kruskal.kruskal(undigraph);
             } else if (suffix == "BFS") {
                 results = kruskal.kruskalBFS(undigraph, roots, max_depth);
             } else if (suffix == "DFS") {
                 results = kruskal.kruskalDFS(undigraph, roots, max_depth);
             } else if (suffix == "DD") {
                 results = kruskal.kruskalDD(undigraph, roots, distance);
             } else {
                 err << "Unknown Kruskal function";
                 *err_msg = pgr_msg(err.str().c_str());
                 return;
             }
         }
         auto count = results.size();
         if (count == 0) {
             (*return_tuples) = NULL;
             (*return_count) = 0;
             notice << "No spanning tree found";
             return;
         }
         (*return_tuples) = pgr_alloc(count, (*return_tuples));
         for (size_t i = 0; i < count; i++) {
             *((*return_tuples) + i) = results[i];
         }
         (*return_count) = count;
         pgassert(*err_msg == NULL);
         *log_msg = log.str().empty()?
             *log_msg :
             pgr_msg(log.str().c_str());
         *notice_msg = notice.str().empty()?
             *notice_msg :
             pgr_msg(notice.str().c_str());
     } catch (AssertFailedException &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch (std::exception &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch(...) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << "Caught unknown exception!";
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     }
 }
References pgrouting::details::get_no_edge_graph_result(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::insert_edges(), pgassert, pgr_alloc(), pgr_free(), pgr_msg(), UNDIRECTED, and AssertFailedException::what().
Referenced by process().