PGROUTING: kruskal_driver.h File Reference
kruskal_driver.h File Reference
#include <postgres.h>
#include <utils/array.h>
#include "cpp_common/undefPostgresDefine.hpp"
#include <stddef.h>
#include <stdint.h>
Typedefs
typedef struct MST_rt MST_rt
Functions
void pgr_do_kruskal (const char *, ArrayType *, const char *, int64_t, double, MST_rt **, size_t *, char **, char **, char **)
Typedef Documentation
MST_rt
typedef struct MST_rt MST_rt
Definition at line 54 of file kruskal_driver.h.
Function Documentation
pgr_do_kruskal()
void pgr_do_kruskal (const char * edges_sql, ArrayType * starts, const char * fn_suffix, int64_t max_depth, double distance, MST_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 45 of file kruskal_driver.cpp.
{
    using pgrouting::pgr_alloc;
    using pgrouting::to_pg_msg;
    using pgrouting::pgr_free;
    using pgrouting::pgget::get_intArray;
    std::ostringstream log;
    std::ostringstream err;
    std::ostringstream notice;
    const char *hint = nullptr;
    try {
        // NOLINTBEGIN(clang-analyzer-cplusplus.NewDelete)
        pgassert(!(*log_msg));
        pgassert(!(*notice_msg));
        pgassert(!(*err_msg));
        pgassert(!(*return_tuples));
        pgassert(*return_count == 0);
        // NOLINTEND(clang-analyzer-cplusplus.NewDelete)
        auto roots = get_intArray(starts, false);
        hint = edges_sql;
        auto edges = pgrouting::pgget::get_edges(std::string(edges_sql), true, false);
        hint = nullptr;
        std::string suffix(fn_suffix);
        std::vector<MST_rt> results;
        pgrouting::UndirectedGraph undigraph;
        undigraph.insert_edges(edges);
        pgrouting::functions::Pgr_kruskal<pgrouting::UndirectedGraph> kruskal;
        if (edges.empty()) {
            results = pgrouting::details::get_no_edge_graph_result(roots);
            *notice_msg = to_pg_msg("No edges found");
            *log_msg = to_pg_msg(edges_sql);
        } else {
            if (suffix == "") {
                results = kruskal.kruskal(undigraph);
            } else if (suffix == "BFS") {
                results = kruskal.kruskalBFS(undigraph, roots, max_depth);
            } else if (suffix == "DFS") {
                results = kruskal.kruskalDFS(undigraph, roots, max_depth);
            } else if (suffix == "DD") {
                results = kruskal.kruskalDD(undigraph, roots, distance);
            } else {
                err << "Unknown Kruskal function";
                *err_msg = to_pg_msg(err);
                return;
            }
        }
        auto count = results.size();
        (*return_tuples) = pgr_alloc(count, (*return_tuples));
        for (size_t i = 0; i < count; i++) {
            *((*return_tuples) + i) = results[i];
        }
        (*return_count) = count;
        pgassert(*err_msg == NULL);
        *log_msg = to_pg_msg(log);
        *notice_msg = to_pg_msg(notice);
    } catch (AssertFailedException &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch (const std::string &ex) {
        *err_msg = to_pg_msg(ex);
        *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
    } catch (std::exception &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch(...) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << "Caught unknown exception!";
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    }
}
References pgrouting::pgget::get_edges(), pgrouting::pgget::get_intArray(), pgrouting::details::get_no_edge_graph_result(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::insert_edges(), pgrouting::functions::Pgr_kruskal< G >::kruskal(), pgrouting::functions::Pgr_kruskal< G >::kruskalBFS(), pgrouting::functions::Pgr_kruskal< G >::kruskalDD(), pgrouting::functions::Pgr_kruskal< G >::kruskalDFS(), pgassert, pgrouting::pgr_alloc(), pgrouting::pgr_free(), pgrouting::to_pg_msg(), and AssertFailedException::what().
Referenced by process().