PGROUTING: kruskal.c File Reference
kruskal.c File Reference
#include <stdbool.h>
#include "c_common/postgres_connection.h"
#include "utils/array.h"
#include "c_common/debug_macro.h"
#include "c_common/e_report.h"
#include "c_common/time_msg.h"
#include "c_types/mst_rt.h"
#include "drivers/spanningTree/mst_common.h"
#include "drivers/spanningTree/kruskal_driver.h"
Functions
PGDLLEXPORT Datum _pgr_kruskal (PG_FUNCTION_ARGS)
PGDLLEXPORT Datum _pgr_kruskalv4 (PG_FUNCTION_ARGS)
PG_FUNCTION_INFO_V1 (_pgr_kruskal)
PG_FUNCTION_INFO_V1 (_pgr_kruskalv4)
static void process (char *edges_sql, ArrayType *roots, char *fn_suffix, int64_t max_depth, double distance, MST_rt **result_tuples, size_t *result_count)
Function Documentation
_pgr_kruskal()
PGDLLEXPORT Datum _pgr_kruskal (PG_FUNCTION_ARGS)
Definition at line 184 of file kruskal.c.
{
    FuncCallContext     *funcctx;
    TupleDesc           tuple_desc;
    MST_rt *result_tuples = NULL;
    size_t result_count = 0;
    if (SRF_IS_FIRSTCALL()) {
        MemoryContext   oldcontext;
        funcctx = SRF_FIRSTCALL_INIT();
        oldcontext = MemoryContextSwitchTo(funcctx->multi_call_memory_ctx);
#ifdef SHOWMSG
        ereport(NOTICE, (
                    errcode(ERRCODE_WARNING_DEPRECATED_FEATURE),
                    errmsg("A stored procedure is using deprecated C internal function '%s'", __func__),
                    errdetail("Library function '%s' was deprecated in pgRouting %s", __func__, "3.7.0"),
                    errhint("Consider upgrade pgRouting")));
#endif
        /* Edge sql, tree roots, fn_suffix, max_depth, distance */
        process(
                text_to_cstring(PG_GETARG_TEXT_P(0)),
                PG_GETARG_ARRAYTYPE_P(1),
                text_to_cstring(PG_GETARG_TEXT_P(2)),
                PG_GETARG_INT64(3),
                PG_GETARG_FLOAT8(4),
                &result_tuples,
                &result_count);
        funcctx->max_calls = result_count;
        funcctx->user_fctx = result_tuples;
        if (get_call_result_type(fcinfo, NULL, &tuple_desc)
                != TYPEFUNC_COMPOSITE) {
            ereport(ERROR,
                    (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
                     errmsg("function returning record called in context "
                         "that cannot accept type record")));
        }
        funcctx->tuple_desc = tuple_desc;
        MemoryContextSwitchTo(oldcontext);
    }
    funcctx = SRF_PERCALL_SETUP();
    tuple_desc = funcctx->tuple_desc;
    result_tuples = (MST_rt*) funcctx->user_fctx;
    if (funcctx->call_cntr < funcctx->max_calls) {
        HeapTuple    tuple;
        Datum        result;
        Datum        *values;
        bool*        nulls;
        size_t num  = 7;
        values = palloc(num * sizeof(Datum));
        nulls = palloc(num * sizeof(bool));
        size_t i;
        for (i = 0; i < num; ++i) {
            nulls[i] = false;
        }
        values[0] = Int64GetDatum((int64_t)funcctx->call_cntr + 1);
        values[1] = Int64GetDatum(result_tuples[funcctx->call_cntr].depth);
        values[2] = Int64GetDatum(result_tuples[funcctx->call_cntr].from_v);
        values[3] = Int64GetDatum(result_tuples[funcctx->call_cntr].node);
        values[4] = Int64GetDatum(result_tuples[funcctx->call_cntr].edge);
        values[5] = Float8GetDatum(result_tuples[funcctx->call_cntr].cost);
        values[6] = Float8GetDatum(result_tuples[funcctx->call_cntr].agg_cost);
        tuple = heap_form_tuple(tuple_desc, values, nulls);
        result = HeapTupleGetDatum(tuple);
        SRF_RETURN_NEXT(funcctx, result);
    } else {
        SRF_RETURN_DONE(funcctx);
    }
}
References MST_rt::agg_cost, MST_rt::cost, MST_rt::depth, MST_rt::edge, MST_rt::from_v, MST_rt::node, and process().
_pgr_kruskalv4()
PGDLLEXPORT Datum _pgr_kruskalv4 (PG_FUNCTION_ARGS)
Definition at line 101 of file kruskal.c.
{
    FuncCallContext     *funcctx;
    TupleDesc           tuple_desc;
    MST_rt *result_tuples = NULL;
    size_t result_count = 0;
    if (SRF_IS_FIRSTCALL()) {
        MemoryContext   oldcontext;
        funcctx = SRF_FIRSTCALL_INIT();
        oldcontext = MemoryContextSwitchTo(funcctx->multi_call_memory_ctx);
        process(
                text_to_cstring(PG_GETARG_TEXT_P(0)),
                PG_GETARG_ARRAYTYPE_P(1),
                text_to_cstring(PG_GETARG_TEXT_P(2)),
                PG_GETARG_INT64(3),
                PG_GETARG_FLOAT8(4),
                &result_tuples,
                &result_count);
        funcctx->max_calls = result_count;
        funcctx->user_fctx = result_tuples;
        if (get_call_result_type(fcinfo, NULL, &tuple_desc)
                != TYPEFUNC_COMPOSITE) {
            ereport(ERROR,
                    (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
                     errmsg("function returning record called in context "
                         "that cannot accept type record")));
        }
        funcctx->tuple_desc = tuple_desc;
        MemoryContextSwitchTo(oldcontext);
    }
    funcctx = SRF_PERCALL_SETUP();
    tuple_desc = funcctx->tuple_desc;
    result_tuples = (MST_rt*) funcctx->user_fctx;
    if (funcctx->call_cntr < funcctx->max_calls) {
        HeapTuple    tuple;
        Datum        result;
        Datum        *values;
        bool*        nulls;
        size_t num  = 8;
        values = palloc(num * sizeof(Datum));
        nulls = palloc(num * sizeof(bool));
        size_t i;
        for (i = 0; i < num; ++i) {
            nulls[i] = false;
        }
        values[0] = Int64GetDatum((int64_t)funcctx->call_cntr + 1);
        values[1] = Int64GetDatum(result_tuples[funcctx->call_cntr].depth);
        values[2] = Int64GetDatum(result_tuples[funcctx->call_cntr].from_v);
        values[3] = Int64GetDatum(result_tuples[funcctx->call_cntr].pred);
        values[4] = Int64GetDatum(result_tuples[funcctx->call_cntr].node);
        values[5] = Int64GetDatum(result_tuples[funcctx->call_cntr].edge);
        values[6] = Float8GetDatum(result_tuples[funcctx->call_cntr].cost);
        values[7] = Float8GetDatum(result_tuples[funcctx->call_cntr].agg_cost);
        tuple = heap_form_tuple(tuple_desc, values, nulls);
        result = HeapTupleGetDatum(tuple);
        SRF_RETURN_NEXT(funcctx, result);
    } else {
        SRF_RETURN_DONE(funcctx);
    }
}
References MST_rt::agg_cost, MST_rt::cost, MST_rt::depth, MST_rt::edge, MST_rt::from_v, MST_rt::node, MST_rt::pred, and process().
PG_FUNCTION_INFO_V1() [1/2]
PG_FUNCTION_INFO_V1 (_pgr_kruskal)
PG_FUNCTION_INFO_V1() [2/2]
PG_FUNCTION_INFO_V1 (_pgr_kruskalv4)
process()
static void process (char * edges_sql, ArrayType * roots, char * fn_suffix, int64_t max_depth, double distance, MST_rt ** result_tuples, size_t * result_count) static
Definition at line 48 of file kruskal.c.
{
    pgr_SPI_connect();
    char* log_msg = NULL;
    char* notice_msg = NULL;
    char* err_msg = NULL;
    (*result_tuples) = NULL;
    (*result_count) = 0;
    char * fn_name = get_name(0, fn_suffix, &err_msg);
    if (err_msg) {
        pgr_global_report(&log_msg, &notice_msg, &err_msg);
        return;
    }
    /* checks previously done on sql now done here */
    if (strcmp(fn_suffix, "DD") == 0 && distance < 0) {
        pgr_throw_error("Negative value found on 'distance'", "Must be positive");
    } else if ((strcmp(fn_suffix, "BFS") == 0 || strcmp(fn_suffix, "DFS") == 0) && max_depth < 0) {
        pgr_throw_error("Negative value found on 'max_depth'", "Must be positive");
    }
    clock_t start_t = clock();
    pgr_do_kruskal(
            edges_sql,
            roots,
            fn_suffix,
            max_depth,
            distance,
            result_tuples,
            result_count,
            &log_msg,
            &notice_msg,
            &err_msg);
    time_msg(fn_name, start_t, clock());
    if (err_msg) {
        if (*result_tuples) pfree(*result_tuples);
    }
    pgr_global_report(&log_msg, &notice_msg, &err_msg);
    pgr_SPI_finish();
}
References get_name(), pgr_do_kruskal(), pgr_global_report(), pgr_SPI_connect(), pgr_SPI_finish(), pgr_throw_error(), and time_msg().
Referenced by _pgr_kruskal(), and _pgr_kruskalv4().