PGROUTING: lengauerTarjanDominatorTree_driver.h File Reference
lengauerTarjanDominatorTree_driver.h File Reference
#include <stddef.h>
#include <c_types/pgr_ltdtree_rt.h>
#include "c_types/pgr_edge_t.h"
Functions
void do_pgr_LTDTree (pgr_edge_t *data_edges, size_t total_tuples, int64_t root_vertex, pgr_ltdtree_rt **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
Function Documentation
do_pgr_LTDTree()
void do_pgr_LTDTree (pgr_edge_t * data_edges, size_t total_tuples, int64_t root_vertex, pgr_ltdtree_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 51 of file lengauerTarjanDominatorTree_driver.cpp.
{
     std::ostringstream log;
     std::ostringstream notice;
     std::ostringstream err;
     try {
         pgassert(total_edges != 0);
         pgassert(!(*log_msg));
         pgassert(!(*notice_msg));
         pgassert(!(*err_msg));
         pgassert(!(*return_tuples));
         pgassert(*return_count == 0);
         std::string logstr;
 /***********************Working with graph**************************/
         graphType gType = DIRECTED;
         pgrouting::DirectedGraph digraph(gType);
         digraph.insert_edges(data_edges, total_edges);
         std::vector<pgr_ltdtree_rt> results;
         pgrouting::functions::Pgr_LTDTree<pgrouting::DirectedGraph> fn_LTDTree;
         results = fn_LTDTree.pgr_ltdtree(digraph, root_vertex);
         logstr += fn_LTDTree.get_log();
         log << logstr;
         auto count = results.size();
         if (count == 0) {
             (*return_tuples) = NULL;
             (*return_count) = 0;
             notice << "No result found";
             *log_msg = log.str().empty()?
                        *log_msg :
                        pgr_msg(log.str().c_str());
             *notice_msg = notice.str().empty()?
                           *notice_msg :
                           pgr_msg(notice.str().c_str());
             return;
         }
         (*return_tuples) = pgr_alloc(count, (*return_tuples));
         for (size_t i = 0; i < count; i++) {
             *((*return_tuples) + i) = results[i];
         }
         (*return_count) = count;
         pgassert(*err_msg == NULL);
         *log_msg = log.str().empty()?
                    *log_msg :
                    pgr_msg(log.str().c_str());
         *notice_msg = notice.str().empty()?
                       *notice_msg :
                       pgr_msg(notice.str().c_str());
     } catch (AssertFailedException &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch (std::exception &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch(...) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << "Caught unknown exception!";
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     }
 }
References DIRECTED, pgrouting::Pgr_messages::get_log(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::insert_edges(), pgassert, pgr_alloc(), pgr_free(), pgrouting::functions::Pgr_LTDTree< G >::pgr_ltdtree(), pgr_msg(), and AssertFailedException::what().
Referenced by process().