PGROUTING: lengauerTarjanDominatorTree.c File Reference
lengauerTarjanDominatorTree.c File Reference
#include <stdbool.h>
#include "c_common/postgres_connection.h"
#include "c_common/debug_macro.h"
#include "c_common/e_report.h"
#include "c_common/time_msg.h"
#include "c_types/ii_t_rt.h"
#include "drivers/dominator/lengauerTarjanDominatorTree_driver.h"
Functions
PGDLLEXPORT Datum _pgr_lengauertarjandominatortree (PG_FUNCTION_ARGS)
PG_FUNCTION_INFO_V1 (_pgr_lengauertarjandominatortree)
static void process (char *edges_sql, int64_t root_vertex, II_t_rt **result_tuples, size_t *result_count)
Function Documentation
_pgr_lengauertarjandominatortree()
PGDLLEXPORT Datum _pgr_lengauertarjandominatortree (PG_FUNCTION_ARGS)
Definition at line 81 of file lengauerTarjanDominatorTree.c.
{
    FuncCallContext     *funcctx;
    TupleDesc            tuple_desc;
    II_t_rt *result_tuples = NULL;
    size_t result_count = 0;
    if (SRF_IS_FIRSTCALL()) {
        MemoryContext   oldcontext;
        funcctx = SRF_FIRSTCALL_INIT();
        oldcontext = MemoryContextSwitchTo(funcctx->multi_call_memory_ctx);
        process(
                text_to_cstring(PG_GETARG_TEXT_P(0)),
                PG_GETARG_INT64(1),
                &result_tuples,
                &result_count);
        funcctx->max_calls = result_count;
        funcctx->user_fctx = result_tuples;
        if (get_call_result_type(fcinfo, NULL, &tuple_desc)
                != TYPEFUNC_COMPOSITE)
            ereport(ERROR,
                    (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
                     errmsg("function returning record called in context "
                         "that cannot accept type record")));
        funcctx->tuple_desc = tuple_desc;
        MemoryContextSwitchTo(oldcontext);
    }
    funcctx = SRF_PERCALL_SETUP();
    tuple_desc = funcctx->tuple_desc;
    result_tuples = (II_t_rt*) funcctx->user_fctx;
    if (funcctx->call_cntr < funcctx->max_calls) {
        HeapTuple   tuple;
        Datum       result;
        Datum       *values;
        bool        *nulls;
        size_t call_cntr = funcctx->call_cntr;
        size_t numb = 3;
        values =(Datum *)palloc(numb * sizeof(Datum));
        nulls = palloc(numb * sizeof(bool));
        size_t i;
        for (i = 0; i < numb; ++i) {
            nulls[i] = false;
        }
            values[0] = Int32GetDatum((int32_t)call_cntr + 1);
            values[1] = Int64GetDatum(result_tuples[call_cntr].d1.id);
            values[2] = Int64GetDatum(result_tuples[call_cntr].d2.value);
            tuple = heap_form_tuple(tuple_desc, values, nulls);
            result = HeapTupleGetDatum(tuple);
            SRF_RETURN_NEXT(funcctx, result);
        } else {
            SRF_RETURN_DONE(funcctx);
        }
}
References II_t_rt::id, process(), and II_t_rt::value.
PG_FUNCTION_INFO_V1()
PG_FUNCTION_INFO_V1 (_pgr_lengauertarjandominatortree)
process()
static void process (char * edges_sql, int64_t root_vertex, II_t_rt ** result_tuples, size_t * result_count) static
Definition at line 48 of file lengauerTarjanDominatorTree.c.
{
    pgr_SPI_connect();
    char* log_msg = NULL;
    char* notice_msg = NULL;
    char* err_msg = NULL;
    clock_t start_t = clock();
    pgr_do_LTDTree(
            edges_sql,
            root_vertex,
            result_tuples, result_count,
            &log_msg,
            &notice_msg,
            &err_msg);
    time_msg("processing pgr_LTDTree()", start_t, clock());
    if (err_msg && (*result_tuples)) {
        pfree(*result_tuples);
        (*result_tuples) = NULL;
        (*result_count) = 0;
    }
    pgr_global_report(&log_msg, &notice_msg, &err_msg);
    pgr_SPI_finish();
}
References pgr_do_LTDTree(), pgr_global_report(), pgr_SPI_connect(), pgr_SPI_finish(), and time_msg().
Referenced by _pgr_lengauertarjandominatortree().