PGROUTING: lineGraph_driver.h File Reference
lineGraph_driver.h File Reference
#include <stddef.h>
#include <stdbool.h>
Typedefs
typedef struct Edge_rt Edge_rt
Functions
void pgr_do_lineGraph (const char *, bool, Edge_rt **, size_t *, char **, char **, char **)
Typedef Documentation
Edge_rt
typedef struct Edge_rt Edge_rt
Definition at line 41 of file lineGraph_driver.h.
Function Documentation
pgr_do_lineGraph()
void pgr_do_lineGraph (const char * edges_sql, bool directed, Edge_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 58 of file lineGraph_driver.cpp.
{
    using pgrouting::to_pg_msg;
    using pgrouting::pgr_free;
    std::ostringstream log;
    std::ostringstream err;
    std::ostringstream notice;
    const char *hint = nullptr;
    try {
        pgassert(!(*log_msg));
        pgassert(!(*notice_msg));
        pgassert(!(*err_msg));
        pgassert(!(*return_tuples));
        pgassert(*return_count == 0);
        hint = edges_sql;
        auto edges = pgrouting::pgget::get_edges(std::string(edges_sql), true, false);
        if (edges.empty()) {
            *notice_msg = to_pg_msg("No edges found");
            *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
            return;
        }
        hint = nullptr;
        std::vector<Edge_t> line_graph_edges;
        if (directed) {
            pgrouting::DirectedGraph ograph;
            ograph.insert_edges(edges);
            line_graph_edges = line_graph(ograph, directed);
        } else {
            pgrouting::UndirectedGraph ograph;
            ograph.insert_edges(edges);
            line_graph_edges = line_graph(ograph, directed);
        }
        auto count = line_graph_edges.size();
        if (count == 0) {
            (*return_tuples) = NULL;
            (*return_count) = 0;
            *log_msg = to_pg_msg(log);
            return;
        }
        size_t sequence = 0;
        using pgrouting::pgr_alloc;
        (*return_tuples) = pgr_alloc(line_graph_edges.size(), (*return_tuples));
        for (const auto &e : line_graph_edges) {
            auto rev_c = directed? e.reverse_cost : -1;
            (*return_tuples)[sequence] = {e.id, e.source, e.target, e.cost, rev_c};
            sequence++;
        }
        (*return_count) = sequence;
        pgassert(*err_msg == NULL);
        *log_msg = to_pg_msg(log);
        *notice_msg = to_pg_msg(notice);
    } catch (AssertFailedException &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch (const std::string &ex) {
        *err_msg = to_pg_msg(ex);
        *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
    } catch (std::exception &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch(...) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << "Caught unknown exception!";
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    }
}
References pgrouting::pgget::get_edges(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::insert_edges(), anonymous_namespace{lineGraph_driver.cpp}::line_graph(), pgassert, pgrouting::pgr_alloc(), pgrouting::pgr_free(), pgrouting::to_pg_msg(), and AssertFailedException::what().
Referenced by process().