PGROUTING: lineGraphFull_driver.cpp File Reference
lineGraphFull_driver.cpp File Reference
#include "drivers/lineGraph/lineGraphFull_driver.h"
#include <sstream>
#include <deque>
#include <vector>
#include <string>
#include "c_types/line_graph_full_rt.h"
#include "cpp_common/pgdata_getters.hpp"
#include "cpp_common/alloc.hpp"
#include "cpp_common/assert.hpp"
#include "lineGraph/lineGraphFull.hpp"
#include "cpp_common/linear_directed_graph.hpp"
#include "dijkstra/dijkstra.hpp"
Namespaces
namespace anonymous_namespace{lineGraphFull_driver.cpp}
Functions
void anonymous_namespace{lineGraphFull_driver.cpp}::get_turn_penalty_postgres_result (std::vector< Line_graph_full_rt > edge_result, Line_graph_full_rt **return_tuples, size_t &sequence)
void pgr_do_lineGraphFull (const char *edges_sql, Line_graph_full_rt **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
Function Documentation
pgr_do_lineGraphFull()
void pgr_do_lineGraphFull (const char * edges_sql, Line_graph_full_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 70 of file lineGraphFull_driver.cpp.
{
    using pgrouting::to_pg_msg;
    using pgrouting::pgr_free;
    std::ostringstream log;
    std::ostringstream err;
    std::ostringstream notice;
    const char *hint = nullptr;
    try {
        pgassert(!(*log_msg));
        pgassert(!(*notice_msg));
        pgassert(!(*err_msg));
        pgassert(!(*return_tuples));
        pgassert(*return_count == 0);
        hint = edges_sql;
        auto edges = pgrouting::pgget::get_edges(std::string(edges_sql), true, false);
        if (edges.empty()) {
            *notice_msg = to_pg_msg("No edges found");
            *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
            return;
        }
        hint = nullptr;
        pgrouting::DirectedGraph digraph;
        digraph.insert_edges_neg(edges);
        pgrouting::graph::Pgr_lineGraphFull<
            pgrouting::LinearDirectedGraph,
            pgrouting::Line_vertex,
            pgrouting::Basic_edge, true> line(digraph);
        std::vector< Line_graph_full_rt > line_graph_edges;
        line_graph_edges = line.get_postgres_results_directed();
        auto count = line_graph_edges.size();
        if (count == 0) {
            (*return_tuples) = NULL;
            (*return_count) = 0;
            /* TODO change the notice message */
            notice <<
                "No paths found between start_vid and end_vid vertices";
        } else {
            size_t sequence = 0;
            get_turn_penalty_postgres_result(
                line_graph_edges,
                return_tuples,
                sequence);
            (*return_count) = sequence;
        }
#if 1
        log << line.log.str() << "\n\n\n";
        log << line << "\n";
#endif
        pgassert(*err_msg == NULL);
        *log_msg = to_pg_msg(log);
        *notice_msg = to_pg_msg(notice);
    } catch (AssertFailedException &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch (const std::string &ex) {
        *err_msg = to_pg_msg(ex);
        *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
    } catch (std::exception &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch(...) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << "Caught unknown exception!";
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    }
}
References pgrouting::pgget::get_edges(), pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::get_postgres_results_directed(), anonymous_namespace{lineGraphFull_driver.cpp}::get_turn_penalty_postgres_result(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::insert_edges_neg(), pgrouting::graph::Pgr_lineGraphFull< G, T_V, T_E, t_directed >::log, pgassert, pgrouting::pgr_free(), pgrouting::to_pg_msg(), and AssertFailedException::what().
Referenced by process().