PGROUTING: max_flow.c File Reference
max_flow.c File Reference
#include <stdbool.h>
#include "c_common/postgres_connection.h"
#include "c_common/debug_macro.h"
#include "c_common/e_report.h"
#include "c_common/time_msg.h"
#include "drivers/max_flow/max_flow_driver.h"
#include "c_types/flow_t.h"
Functions
PGDLLEXPORT Datum _pgr_maxflow (PG_FUNCTION_ARGS)
PG_FUNCTION_INFO_V1 (_pgr_maxflow)
static void process (char *edges_sql, char *combinations_sql, ArrayType *starts, ArrayType *ends, int algorithm, bool only_flow, Flow_t **result_tuples, size_t *result_count)
Function Documentation
_pgr_maxflow()
PGDLLEXPORT Datum _pgr_maxflow (PG_FUNCTION_ARGS)
Definition at line 103 of file max_flow.c.
{
    FuncCallContext *funcctx;
    TupleDesc tuple_desc;
    /**************************************************************************/
    Flow_t *result_tuples = 0;
    size_t result_count = 0;
    /**************************************************************************/
    if (SRF_IS_FIRSTCALL()) {
        MemoryContext oldcontext;
        funcctx = SRF_FIRSTCALL_INIT();
        oldcontext = MemoryContextSwitchTo(funcctx->multi_call_memory_ctx);
        /**********************************************************************/
        if (PG_NARGS() == 5) {
            /*
             * many to many
             */
            process(
                text_to_cstring(PG_GETARG_TEXT_P(0)),
                NULL,
                PG_GETARG_ARRAYTYPE_P(1),
                PG_GETARG_ARRAYTYPE_P(2),
                PG_GETARG_INT32(3),
                PG_GETARG_BOOL(4),
                &result_tuples,
                &result_count);
        } else if (PG_NARGS() == 4) {
            /*
             * combinations
             */
            process(
                text_to_cstring(PG_GETARG_TEXT_P(0)),
                text_to_cstring(PG_GETARG_TEXT_P(1)),
                NULL,
                NULL,
                PG_GETARG_INT32(2),
                PG_GETARG_BOOL(3),
                &result_tuples,
                &result_count);
        }
        /*                                                                    */
        /**********************************************************************/
        funcctx->max_calls = result_count;
        funcctx->user_fctx = result_tuples;
        if (get_call_result_type(fcinfo, NULL, &tuple_desc)
                != TYPEFUNC_COMPOSITE) {
            ereport(ERROR,
                    (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
                     errmsg("function returning record called in context "
                         "that cannot accept type record")));
        }
        funcctx->tuple_desc = tuple_desc;
        MemoryContextSwitchTo(oldcontext);
    }
    funcctx = SRF_PERCALL_SETUP();
    tuple_desc = funcctx->tuple_desc;
    result_tuples = (Flow_t *) funcctx->user_fctx;
    if (funcctx->call_cntr < funcctx->max_calls) {
        HeapTuple tuple;
        Datum result;
        Datum *values;
        bool *nulls;
        size_t call_cntr = funcctx->call_cntr;
        /**********************************************************************/
        /*                          MODIFY AS NEEDED                          */
        values = palloc(6 * sizeof(Datum));
        nulls = palloc(6 * sizeof(bool));
        size_t i;
        for (i = 0; i < 6; ++i) {
            nulls[i] = false;
        }
        values[0] = Int32GetDatum((int32_t)call_cntr + 1);
        values[1] = Int64GetDatum(result_tuples[call_cntr].edge);
        values[2] = Int64GetDatum(result_tuples[call_cntr].source);
        values[3] = Int64GetDatum(result_tuples[call_cntr].target);
        values[4] = Int64GetDatum(result_tuples[call_cntr].flow);
        values[5] = Int64GetDatum(result_tuples[call_cntr].residual_capacity);
        /**********************************************************************/
        tuple = heap_form_tuple(tuple_desc, values, nulls);
        result = HeapTupleGetDatum(tuple);
        SRF_RETURN_NEXT(funcctx, result);
    } else {
        SRF_RETURN_DONE(funcctx);
    }
}
References process().
PG_FUNCTION_INFO_V1()
PG_FUNCTION_INFO_V1 (_pgr_maxflow)
process()
static void process (char * edges_sql, char * combinations_sql, ArrayType * starts, ArrayType * ends, int algorithm, bool only_flow, Flow_t ** result_tuples, size_t * result_count) static
Definition at line 46 of file max_flow.c.
{
    if (algorithm < 1 || algorithm > 3) {
        elog(ERROR, "Unknown algorithm");
    }
    pgr_SPI_connect();
    char* log_msg = NULL;
    char* notice_msg = NULL;
    char* err_msg = NULL;
    clock_t start_t = clock();
    pgr_do_max_flow(
            edges_sql,
            combinations_sql,
            starts, ends,
            algorithm,
            only_flow,
            result_tuples, result_count,
            &log_msg,
            &notice_msg,
            &err_msg);
    if (only_flow) {
        time_msg("pgr_maxFlow(many to many)", start_t, clock());
    } else if (algorithm == 1) {
        time_msg("pgr_maxFlowPushRelabel(many to many)", start_t, clock());
    } else if (algorithm == 3) {
        time_msg("pgr_maxFlowEdmondsKarp(many to many)", start_t, clock());
    } else {
        time_msg("pgr_maxFlowBoykovKolmogorov(many to many)", start_t, clock());
    }
    if (err_msg && (*result_tuples)) {
        pfree(*result_tuples);
        (*result_tuples) = NULL;
        (*result_count) = 0;
    }
    pgr_global_report(&log_msg, &notice_msg, &err_msg);
    pgr_SPI_finish();
}
References pgr_do_max_flow(), pgr_global_report(), pgr_SPI_connect(), pgr_SPI_finish(), and time_msg().
Referenced by _pgr_maxflow().