PGROUTING: maximum_cardinality_matching.c File Reference
maximum_cardinality_matching.c File Reference
#include <stdbool.h>
#include "c_common/postgres_connection.h"
#include "c_common/debug_macro.h"
#include "c_common/e_report.h"
#include "c_common/time_msg.h"
#include "c_common/edges_input.h"
#include "drivers/max_flow/maximum_cardinality_matching_driver.h"
Functions
PGDLLEXPORT Datum _pgr_maxcardinalitymatch (PG_FUNCTION_ARGS)
PG_FUNCTION_INFO_V1 (_pgr_maxcardinalitymatch)
static void process (char *edges_sql, bool directed, pgr_basic_edge_t **result_tuples, size_t *result_count)
Function Documentation
_pgr_maxcardinalitymatch()
PGDLLEXPORT Datum _pgr_maxcardinalitymatch (PG_FUNCTION_ARGS)
Definition at line 102 of file maximum_cardinality_matching.c.
{
     FuncCallContext *funcctx;
     TupleDesc tuple_desc;
     /**************************************************************************/
     pgr_basic_edge_t *result_tuples = NULL;
     size_t result_count = 0;
     /**************************************************************************/
     if (SRF_IS_FIRSTCALL()) {
         MemoryContext oldcontext;
         funcctx = SRF_FIRSTCALL_INIT();
         oldcontext = MemoryContextSwitchTo(funcctx->multi_call_memory_ctx);
         /**********************************************************************/
         PGR_DBG("Calling process");
         process(
                 text_to_cstring(PG_GETARG_TEXT_P(0)),
                 PG_GETARG_BOOL(1),
                 &result_tuples,
                 &result_count);
         /**********************************************************************/
 #if PGSQL_VERSION > 95
         funcctx->max_calls = result_count;
 #else
         funcctx->max_calls = (uint32_t)result_count;
 #endif
         funcctx->user_fctx = result_tuples;
         if (get_call_result_type(fcinfo, NULL, &tuple_desc)
                 != TYPEFUNC_COMPOSITE) {
             ereport(ERROR,
                     (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
                      errmsg("function returning record called in context "
                          "that cannot accept type record")));
         }
         funcctx->tuple_desc = tuple_desc;
         MemoryContextSwitchTo(oldcontext);
     }
     funcctx = SRF_PERCALL_SETUP();
     tuple_desc = funcctx->tuple_desc;
     result_tuples = (pgr_basic_edge_t *) funcctx->user_fctx;
     if (funcctx->call_cntr < funcctx->max_calls) {
         HeapTuple tuple;
         Datum result;
         Datum *values;
         bool *nulls;
         /**********************************************************************/
         values = palloc(4 * sizeof(Datum));
         nulls = palloc(4 * sizeof(bool));
         size_t i;
         for (i = 0; i < 4; ++i) {
             nulls[i] = false;
         }
         values[0] = Int32GetDatum(funcctx->call_cntr + 1);
         values[1] = Int64GetDatum(result_tuples[funcctx->call_cntr].edge_id);
         values[2] = Int64GetDatum(result_tuples[funcctx->call_cntr].source);
         values[3] = Int64GetDatum(result_tuples[funcctx->call_cntr].target);
         /**********************************************************************/
         tuple = heap_form_tuple(tuple_desc, values, nulls);
         result = HeapTupleGetDatum(tuple);
         SRF_RETURN_NEXT(funcctx, result);
     } else {
         SRF_RETURN_DONE(funcctx);
     }
 }
References pgr_basic_edge_t::edge_id, if(), PGR_DBG, process(), pgr_basic_edge_t::source, and pgr_basic_edge_t::target.
PG_FUNCTION_INFO_V1()
PG_FUNCTION_INFO_V1 (_pgr_maxcardinalitymatch)
process()
static void process (char * edges_sql, bool directed, pgr_basic_edge_t ** result_tuples, size_t * result_count) static
Definition at line 48 of file maximum_cardinality_matching.c.
{
     pgr_SPI_connect();
     pgr_basic_edge_t *edges = NULL;
     size_t total_edges = 0;
     pgr_get_basic_edges(edges_sql, &edges, &total_edges);
     if (total_edges == 0) {
         pgr_SPI_finish();
         return;
     }
     PGR_DBG("Starting timer");
     clock_t start_t = clock();
     char* log_msg = NULL;
     char* notice_msg = NULL;
     char *err_msg = NULL;
     do_pgr_maximum_cardinality_matching(
             edges, total_edges,
             directed,
             result_tuples,
             result_count,
             &log_msg,
             &notice_msg,
             &err_msg);
     time_msg("pgr_maximumCardinalityMatching()", start_t, clock());
     if (edges) pfree(edges);
     if (err_msg && (*result_tuples)) {
         pfree(*result_tuples);
         (*result_tuples) = NULL;
         (*result_count) = 0;
     }
     pgr_global_report(log_msg, notice_msg, err_msg);
     if (log_msg) pfree(log_msg);
     if (notice_msg) pfree(notice_msg);
     if (err_msg) pfree(err_msg);
     pgr_SPI_finish();
 }
References do_pgr_maximum_cardinality_matching(), PGR_DBG, pgr_get_basic_edges(), pgr_global_report(), pgr_SPI_connect(), pgr_SPI_finish(), and time_msg().
Referenced by _pgr_maxcardinalitymatch().