PGROUTING: metrics_driver.cpp File Reference
metrics_driver.cpp File Reference
#include "drivers/metrics_driver.hpp"
#include <sstream>
#include <vector>
#include <string>
#include "metrics/bandwidth.hpp"
#include "cpp_common/pgdata_getters.hpp"
#include "cpp_common/assert.hpp"
#include "cpp_common/to_postgres.hpp"
#include "c_types/iid_t_rt.h"
Functions
void do_metrics (std::string edges_sql, int which, IID_t_rt **return_tuples, size_t *return_count, char **log_msg, char **err_msg)
Function Documentation
do_metrics()
void do_metrics (std::string edges_sql, int which, IID_t_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** err_msg)
Definition at line 43 of file metrics_driver.cpp.
                     {
    using pgrouting::to_pg_msg;
    using pgrouting::pgr_free;
    std::ostringstream log;
    std::ostringstream err;
    std::string hint;
    try {
        pgassert(!(*log_msg));
        pgassert(!(*err_msg));
        pgassert(!(*return_tuples));
        pgassert(*return_count == 0);
        hint = edges_sql;
        auto edges = pgrouting::pgget::get_edges(std::string(edges_sql), true, true);
        if (edges.empty()) {
            throw std::string("No edges found");
        }
        hint = "";
        auto vertices(pgrouting::extract_vertices(edges));
        pgrouting::UndirectedGraph undigraph(vertices);
        undigraph.insert_edges(edges);
        uint64_t result = 0;
        if (which == 0) {
            log << "call the function which calculates the bandwidth";
            result = pgrouting::metrics::bandwidth(undigraph);
        }
        log << "result = " << result;
        *return_tuples = new IID_t_rt[1];
        (*return_tuples)[0].from_vid = static_cast<int64_t>(result);
        *return_count = 1;
        *log_msg = to_pg_msg(log);
    } catch (AssertFailedException &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch (const std::string &ex) {
        *err_msg = to_pg_msg(ex);
        *log_msg = hint.empty()? to_pg_msg(hint) : to_pg_msg(log);
    } catch (std::exception &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch(...) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << "Caught unknown exception!";
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    }
}
References pgrouting::metrics::bandwidth(), pgrouting::extract_vertices(), IID_t_rt::from_vid, pgrouting::pgget::get_edges(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::insert_edges(), pgassert, pgrouting::pgr_free(), pgrouting::to_pg_msg(), and AssertFailedException::what().
Referenced by pgr_process_metrics().