PGROUTING: minCostMaxFlow_driver.cpp File Reference
minCostMaxFlow_driver.cpp File Reference
#include "drivers/max_flow/minCostMaxFlow_driver.h"
#include <sstream>
#include <deque>
#include <vector>
#include <set>
#include <string>
#include "cpp_common/costFlow_t.hpp"
#include "cpp_common/combinations.hpp"
#include "cpp_common/pgdata_getters.hpp"
#include "cpp_common/alloc.hpp"
#include "cpp_common/assert.hpp"
#include "max_flow/minCostMaxFlow.hpp"
Functions
void pgr_do_minCostMaxFlow (const char *edges_sql, const char *combinations_sql, ArrayType *starts, ArrayType *ends, bool only_cost, Flow_t **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
Function Documentation
pgr_do_minCostMaxFlow()
void pgr_do_minCostMaxFlow (const char * edges_sql, const char * combinations_sql, ArrayType * starts, ArrayType * ends, bool only_cost, Flow_t ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 49 of file minCostMaxFlow_driver.cpp.
{
    using pgrouting::pgr_alloc;
    using pgrouting::to_pg_msg;
    using pgrouting::pgr_free;
    using pgrouting::utilities::get_combinations;
    std::ostringstream log;
    std::ostringstream err;
    std::ostringstream notice;
    const char *hint = nullptr;
    try {
        pgassert(!(*log_msg));
        pgassert(!(*notice_msg));
        pgassert(!(*err_msg));
        pgassert(!(*return_tuples));
        pgassert(*return_count == 0);
        hint = combinations_sql;
        auto combinations = get_combinations(combinations_sql, starts, ends, true);
        hint = nullptr;
        if (combinations.empty() && combinations_sql) {
            *notice_msg = to_pg_msg("No (source, target) pairs found");
            *log_msg = to_pg_msg(combinations_sql);
            return;
        }
        std::set<int64_t> sources;
        std::set<int64_t> targets;
        for (const auto &c : combinations) {
            sources.insert(c.first);
            targets.insert(c.second.begin(), c.second.end());
        }
        std::set<int64_t> vertices(sources);
        vertices.insert(targets.begin(), targets.end());
        if (vertices.size() != (sources.size() + targets.size())) {
            *err_msg = to_pg_msg("A source found as sink");
            return;
        }
        hint = edges_sql;
        auto edges = pgrouting::pgget::get_costFlow_edges(std::string(edges_sql));
        if (edges.empty()) {
            *notice_msg = to_pg_msg("No edges found");
            *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
            return;
        }
        hint = nullptr;
        pgrouting::graph::PgrCostFlowGraph digraph(
                edges, sources, targets);
        double min_cost;
        min_cost = digraph.MinCostMaxFlow();
        std::vector<Flow_t> flow_edges;
        if (only_cost) {
            Flow_t edge;
            edge.edge = -1;
            edge.source = -1;
            edge.target = -1;
            edge.flow = -1;
            edge.residual_capacity = -1;
            edge.cost = min_cost;
            edge.agg_cost = min_cost;
            flow_edges.push_back(edge);
        } else {
            flow_edges = digraph.GetFlowEdges();
        }
        (*return_tuples) = pgr_alloc(flow_edges.size(), (*return_tuples));
        for (size_t i = 0; i < flow_edges.size(); i++) {
            (*return_tuples)[i] = flow_edges[i];
        }
        *return_count = flow_edges.size();
        pgassert(*err_msg == NULL);
        *log_msg = to_pg_msg(log);
        *notice_msg = to_pg_msg(notice);
    } catch (AssertFailedException &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch (const std::string &ex) {
        *err_msg = to_pg_msg(ex);
        *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
    } catch (std::exception &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch(...) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << "Caught unknown exception!";
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    }
}
References Flow_t::agg_cost, Flow_t::cost, Flow_t::edge, Flow_t::flow, pgrouting::utilities::get_combinations(), pgrouting::pgget::get_costFlow_edges(), pgrouting::graph::PgrCostFlowGraph::GetFlowEdges(), pgrouting::graph::PgrCostFlowGraph::MinCostMaxFlow(), pgassert, pgrouting::pgr_alloc(), pgrouting::pgr_free(), Flow_t::residual_capacity, Flow_t::source, Flow_t::target, pgrouting::to_pg_msg(), and AssertFailedException::what().
Referenced by process().