PGROUTING: mst_common.cpp File Reference
mst_common.cpp File Reference
#include "drivers/spanningTree/mst_common.h"
#include <string>
#include <sstream>
#include "cpp_common/assert.hpp"
#include "cpp_common/alloc.hpp"
Functions
char * get_name (int fn_id, char *fn_suffix, char **err_msg)
int get_order (char *fn_suffix, char **err_msg)
defines ordering
Function Documentation
get_name()
char * get_name (int fn_id, char * fn_suffix, char ** err_msg)
Definition at line 58 of file mst_common.cpp.
{
    using pgrouting::to_pg_msg;
    std::ostringstream err;
    try {
        pgassert(!(*err_msg));
        std::string name;
        switch (fn_id) {
            case 0: name = "pgr_kruskal";
                    break;
            case 1: name = "pgr_prim";
                    break;
            default : name = "unknown";
                      err << "Unknown function name";
                      *err_msg = to_pg_msg(err);
        }
        std::string suffix(fn_suffix);
        name += suffix;
        char * full_name = to_pg_msg(name.c_str());
        return full_name;
    } catch (std::exception &except) {
        err << except.what();
        *err_msg = to_pg_msg(err);
    }
    return nullptr;
}
References pgassert, and pgrouting::to_pg_msg().
Referenced by process(), and process().
get_order()
int get_order (char * fn_suffix, char ** err_msg)
defines ordering
Parameters
[in] fn_suffix
[in] err_msg
Returns
0 = no matter 1 = DFS 2 = BFS
Definition at line 37 of file mst_common.cpp.
{
    using pgrouting::to_pg_msg;
    std::ostringstream err;
    try {
        pgassert(!(*err_msg));
        std::string suffix(fn_suffix);
        if (suffix.empty()) return 0;
        if (suffix == "DFS") return 1;
        if (suffix == "BFS") return 2;
        if (suffix == "DD") return 1;
        err << "Unknown function suffix" << suffix;
        *err_msg = to_pg_msg(err);
    } catch (std::exception &except) {
        err << except.what();
        *err_msg = to_pg_msg(err);
    }
    return -1;
}
References pgassert, and pgrouting::to_pg_msg().