PGROUTING: detail Namespace Reference
detail Namespace Reference
Classes
class distance_heuristic
Functions
template<typename G , typename V >
bool astar_1_to_many (G &graph, std::vector< V > &predecessors, std::vector< double > &distances, V departure, const std::set< V > &destinations, int heuristic, double factor, double epsilon)
template<class G >
std::deque< pgrouting::Path > dijkstra (G &graph, int64_t start_vertex, const std::set< int64_t > &end_vertex, bool only_cost, size_t n_goals)
Dijkstra 1 to many.
template<typename B_G , typename V , typename T_E >
bool dijkstra_1_to_many (B_G &graph, std::vector< V > &predecessors, std::vector< double > &distances, V departure, const std::set< V > &destinations, size_t n_goals)
template<typename G >
std::deque< pgrouting::Path > drivingDistance_no_equicost (const G &graph, const std::set< int64_t > &roots, std::vector< std::map< int64_t, int64_t > > &depths, double distance, bool details)
gets results for many vertices and equi costs
template<typename G >
std::deque< pgrouting::Path > drivingDistance_with_equicost (G &graph, const std::set< int64_t > &roots, std::vector< std::map< int64_t, int64_t > > &depths, double distance, bool details)
template<typename G , typename V >
std::map< int64_t, int64_t > get_depth (const G &graph, V root, const std::vector< double > &distances, std::vector< V > &predecessors, double distance, bool details)
gets results in form of a container of paths with depth
template<typename G , typename V >
std::deque< pgrouting::Path > get_drivingDistance_with_equicost_paths (const G &graph, const std::set< int64_t > &roots, std::deque< std::vector< V > > &predecessors, std::vector< double > &distances, std::deque< std::vector< V > > &noDetailsPredecessors, double distance, bool details)
gets results for many vertices and equi costs
template<typename G , typename V >
std::deque< pgrouting::Path > get_paths (const G &graph, const std::vector< V > &predecessors, const std::vector< double > &distances, V source, const std::set< V > &targets, bool only_cost)
template<typename G , typename V >
std::deque< pgrouting::Path > get_paths (const G &graph, const std::vector< V > &predecessors, const std::vector< double > &distances, V source, std::set< V > &targets, bool only_cost)
template<typename G , typename V >
void remove_details (const G &graph, const std::vector< double > &distances, std::vector< V > &predecessors)
Function Documentation
astar_1_to_many()
template<typename G , typename V > bool detail::astar_1_to_many (G & graph, std::vector< V > & predecessors, std::vector< double > & distances, V departure, const std::set< V > & destinations, int heuristic, double factor, double epsilon)
Definition at line 115 of file astar.hpp.
{
    typedef typename G::B_G B_G;
    bool found = false;
    CHECK_FOR_INTERRUPTS();
    try {
        boost::astar_search(
                graph.graph, departure,
                distance_heuristic<B_G, V>(
                    graph.graph, destinations,
                    heuristic, factor * epsilon),
                boost::predecessor_map(&predecessors[0])
                .weight_map(get(&pgrouting::Basic_edge::cost, graph.graph))
                .distance_map(&distances[0])
                .visitor(pgrouting::visitors::astar_many_goals_visitor<V>(destinations)));
    }
    catch(pgrouting::found_goals &) {
        found = true;  // Target vertex found
    }
    return found;
}
References CHECK_FOR_INTERRUPTS, and pgrouting::Basic_edge::cost.
Referenced by pgrouting::algorithms::astar().
dijkstra()
template<class G > std::deque< pgrouting::Path > detail::dijkstra (G & graph, int64_t start_vertex, const std::set< int64_t > & end_vertex, bool only_cost, size_t n_goals)
Dijkstra 1 to many.
Definition at line 120 of file dijkstra.hpp.
{
    typedef typename G::V V;
    typedef typename G::G_T_E T_E;
    typedef typename G::B_G B_G;
    std::vector<V> predecessors(graph.num_vertices());
    std::vector<double> distances(graph.num_vertices(), std::numeric_limits<double>::infinity());
    if (!graph.has_vertex(start_vertex)) return std::deque<pgrouting::Path>();
    auto departure(graph.get_V(start_vertex));
    std::set<V> destinations;
    for (const auto &vertex : end_vertex) {
        if (graph.has_vertex(vertex)) destinations.insert(graph.get_V(vertex));
    }
    // perform the algorithm
    detail::dijkstra_1_to_many<B_G, V, T_E>(graph.graph, predecessors, distances, departure, destinations, n_goals);
    // get the results
    auto paths = get_paths(graph,  predecessors, distances, departure, destinations, only_cost);
    return paths;
}
References get_paths().
dijkstra_1_to_many()
template<typename B_G , typename V , typename T_E > bool detail::dijkstra_1_to_many (B_G & graph, std::vector< V > & predecessors, std::vector< double > & distances, V departure, const std::set< V > & destinations, size_t n_goals)
Definition at line 81 of file dijkstra.hpp.
{
    CHECK_FOR_INTERRUPTS();
    std::set<V> goals_found;
    try {
        boost::dijkstra_shortest_paths(graph, departure,
                boost::predecessor_map(&predecessors[0])
                .weight_map(get(&T_E::cost, graph))
                .distance_map(&distances[0])
                .distance_inf(std::numeric_limits<double>::infinity())
                .visitor(pgrouting::visitors::dijkstra_many_goal_visitor<V>(destinations, n_goals, goals_found)));
    } catch(pgrouting::found_goals &) {
        for (const auto &g : destinations) {
            if (goals_found.find(g) == goals_found.end()) {
                /* goal was not found */
                predecessors[g] = g;
            }
        }
        return true;
    } catch (boost::exception const& ex) {
        (void)ex;
        throw;
    } catch (std::exception &e) {
        (void)e;
        throw;
    } catch (...) {
             throw;
         }
         return true;
     }
References CHECK_FOR_INTERRUPTS.
drivingDistance_no_equicost()
template<typename G > std::deque< pgrouting::Path > detail::drivingDistance_no_equicost (const G & graph, const std::set< int64_t > & roots, std::vector< std::map< int64_t, int64_t > > & depths, double distance, bool details)
gets results for many vertices and equi costs
Parameters
[in] graph The graph that is being worked
[in] roots a set of roots
[in] depths a vector of map of depths
[in] distance maximum distance
[in] details flag to indicate to include points
Definition at line 432 of file drivingDist.hpp.
{
    using Path = pgrouting::Path;
    using B_G = typename G::B_G;
    using V = typename G::V;
    using T_E = typename G::G_T_E;
    std::deque<Path> paths;
    for (const auto &root : roots) {
        if (graph.has_vertex(root)) {
            std::vector<V> predecessors(graph.num_vertices());
            std::vector<double> distances(graph.num_vertices(), std::numeric_limits<double>::infinity());
            bg_detail::dijkstra_1_to_distance<B_G, V, T_E>(
                    graph.graph, graph.get_V(root), predecessors, distances, distance);
            auto path = Path(graph, root, distance, predecessors, distances);
            path.sort_by_node_agg_cost();
            depths.push_back(detail::get_depth(graph, graph.get_V(root), distances, predecessors, distance, details));
            /*
             * When details are not wanted update costs
             */
            if (!details) {
                for (auto &pathstop : path) {
                    auto node = graph.get_V(pathstop.node);
                    /* skip points */
                    if (graph[node].id < 0) continue;
                    pathstop.cost = distances[node] - distances[predecessors[node]];
                }
            }
            paths.push_back(path);
        } else {
            Path p(root, root);
            p.push_back({root, -1, 0, 0, root});
            paths.push_back(p);
            std::map<int64_t, int64_t> m;
            m[root] = 0;
            depths.push_back(m);
        }
    }
    return paths;
}
References get_depth().
Referenced by pgrouting::algorithm::drivingDistance().
drivingDistance_with_equicost()
template<typename G > std::deque< pgrouting::Path > detail::drivingDistance_with_equicost (G & graph, const std::set< int64_t > & roots, std::vector< std::map< int64_t, int64_t > > & depths, double distance, bool details)
Definition at line 367 of file drivingDist.hpp.
{
    using V = typename G::V;
    using E = typename G::E;
    using T_E = typename G::G_T_E;
    using B_G = typename G::B_G;
    depths.resize(roots.size());
    std::vector<V> predecessors(graph.num_vertices());
    std::vector<double> distances(graph.num_vertices(), std::numeric_limits<double>::infinity());
    std::deque<std::vector<V>> pred(roots.size());
    std::deque<std::vector<V>> noDetailsPredecessors(roots.size());
    size_t i = 0;
    for (const auto &root : roots) {
        /*
         * The vertex does not exist Nothing to do
         */
        if (!(graph.has_vertex(root))) continue;
        std::iota(predecessors.begin(), predecessors.end(), 0);
        bg_detail::dijkstra_1_to_distance_no_init<B_G, V, E, T_E>(graph.graph, graph.get_V(root), predecessors,
                distances, distance);
        pred[i] = predecessors;
        depths[i] = detail::get_depth(graph, graph.get_V(root), distances, predecessors, distance, details);
        if (!details) {
            noDetailsPredecessors[i] = predecessors;
        }
        ++i;
    }
    /*
     * predecessors of root vertices are themselves
     */
    for (const auto &root : roots) {
        for (auto &p : pred) {
            if (!p.empty() && graph.has_vertex(root)) {
                p[graph.get_V(root)] = graph.get_V(root);
            }
        }
    }
    return get_drivingDistance_with_equicost_paths(
            graph,
            roots,
            pred,
            distances,
            noDetailsPredecessors,
            distance, details);
}
References get_depth(), and get_drivingDistance_with_equicost_paths().
Referenced by pgrouting::algorithm::drivingDistance().
get_depth()
template<typename G , typename V > std::map< int64_t, int64_t > detail::get_depth (const G & graph, V root, const std::vector< double > & distances, std::vector< V > & predecessors, double distance, bool details)
gets results in form of a container of paths with depth
Parameters
[in] graph The graph that is being worked
[in] root The starting node
[in] distances An array of vertices id
[in] predecessors an array of predecessors
[in] distance the max distance
[in] details the max distance
Definition at line 220 of file drivingDist.hpp.
                      {
    std::map<int64_t, int64_t> depth;
    if (predecessors.empty()) return depth;
    if (predecessors.size() != distances.size()) return depth;
    depth[graph[root].id] = 0;
    std::set<V> vertices;
    vertices.insert(root);
    if (!details) {
        remove_details(graph, distances, predecessors);
    }
    /* cycle depth max depth can be number of nodes*/
    for (int64_t d = 1; static_cast<size_t>(d) < graph.num_vertices() ; ++d) {
        /*
         * there is no more to search for
         */
        if (vertices.empty()) break;
        /*
         * One next cycle these vertices have the next depth
         */
        std::set<V> vertices_next;
        std::set<V> point_vertices;
        for (const auto v : vertices) {
            /*
             * Cycle predecessors looking for vertices on the depth d
             * v -> p
             */
            for (V p = 0; p < graph.num_vertices() ; ++p) {
                /*
                 * Sikiping unassigned predecessors
                 * Sikiping distances greater than the one asked for
                 */
                if (predecessors[p] == p) continue;
                if (!(distances[p] <= distance)) continue;
                if (!(predecessors[p] == v)) continue;
                /* found */
                depth[graph[p].id] = d;
                vertices_next.insert(p);
            }
        }
        vertices = vertices_next;
    }
    return depth;
}
References remove_details().
Referenced by drivingDistance_no_equicost(), and drivingDistance_with_equicost().
get_drivingDistance_with_equicost_paths()
template<typename G , typename V > std::deque< pgrouting::Path > detail::get_drivingDistance_with_equicost_paths (const G & graph, const std::set< int64_t > & roots, std::deque< std::vector< V > > & predecessors, std::vector< double > & distances, std::deque< std::vector< V > > & noDetailsPredecessors, double distance, bool details)
gets results for many vertices and equi costs
Parameters
[in] graph The graph that is being worked
[in] roots a set of roots
[in] predecessors an array of predecessors
[in] noDetailsPredecessors veritces that do not have a predecessor
[in] distances a map of distances
[in] distance maximum distance
[in] details flag to indicate to include points
Precondition
one predecessor per root
Definition at line 291 of file drivingDist.hpp.
{
    using Path = pgrouting::Path;
    pgassert(roots.size() == predecessors.size());
    /*
     * Creating all the result "paths"
     */
    std::deque<Path> paths;
    for (const auto r : roots) {
        paths.push_back(Path(r, r));
        paths.back().push_back({r, -1, 0, 0, r});
    }
    /*
     *  Ciclying the vertices:
     *  To which vertex do they belong to?
     */
    for (V v = 0; v < distances.size(); ++v) {
        /*
         * Sikiping distances greater than the one asked for
         */
        if (!(distances[v] <= distance)) continue;
        for (auto i = roots.size(); i > 0; --i) {
            const auto &predecessor = predecessors[i - 1];
            /*
             * The vertex does not exist on the graph
             * The predecessor = current then its unreachable to this vertex
             */
            if (predecessor.empty()) break;
            if (predecessor[v] == v) continue;
            auto u =  details? predecessor[v] : noDetailsPredecessors[i - 1][v];
            /*
             * precalculating cost to find the edge
             */
            auto cost = distances[v] - distances[predecessor[v]];
            auto edge_id = graph.get_edge_id(predecessor[v], v, cost);
            pgassert(edge_id != -1);
            /*
             * real cost is with real predecessor
             */
            cost = details? cost : distances[v] - distances[u];
                 paths[i - 1].push_back({graph[v].id, edge_id, cost, distances[v], graph[u].id});
                 break;
             }
         }
    for (auto &path : paths) {
        path.sort_by_node_agg_cost();
    }
    return paths;
}
References pgassert.
Referenced by drivingDistance_with_equicost().
get_paths() [1/2]
template<typename G , typename V > std::deque< pgrouting::Path > detail::get_paths (const G & graph, const std::vector< V > & predecessors, const std::vector< double > & distances, V source, const std::set< V > & targets, bool only_cost)
Definition at line 145 of file astar.hpp.
{
    using Path = pgrouting::Path;
    std::deque<Path> paths;
    for (const auto &target : targets) {
        auto p = Path(graph,
                source, target,
                predecessors, distances,
                false);
        paths.push_back(Path(graph, p, only_cost));
    }
    return paths;
}
Referenced by pgrouting::algorithms::astar(), and dijkstra().
get_paths() [2/2]
template<typename G , typename V > std::deque< pgrouting::Path > detail::get_paths (const G & graph, const std::vector< V > & predecessors, const std::vector< double > & distances, V source, std::set< V > & targets, bool only_cost)
Definition at line 62 of file dijkstra.hpp.
{
    std::deque<pgrouting::Path> paths;
    for (const auto target : targets) {
        paths.push_back(pgrouting::Path(
                    graph,
                    source, target,
                    predecessors, distances,
                    only_cost, true));
    }
    return paths;
}
remove_details()
template<typename G , typename V > void detail::remove_details (const G & graph, const std::vector< double > & distances, std::vector< V > & predecessors)
Definition at line 164 of file drivingDist.hpp.
{
    /*
     * find all the points that are predecessors
     */
    std::set<V> node_with_predecessor_point;
    CHECK_FOR_INTERRUPTS();
    for (V v = 0; v < predecessors.size() ; ++v) {
        /*
         * skipping unreachable nodes and or initial node
         * skipping predecessors that are vertices
         */
        if (predecessors[v] == v) continue;
        if (graph[predecessors[v]].id >= 0) continue;
        node_with_predecessor_point.insert(v);
    }
    /*
     * Compact all nodes that have predecessor point
     */
    for (const auto node : node_with_predecessor_point) {
        /*
         * Cycle predecessors
         * u -> v  cost to arrive to v is distances[v]
         */
        auto v = node;
        auto u = predecessors[v];
        pgassert(graph[u].id < 0);
        /*
         * while u is a point and it's predecessor is not itself
         */
        CHECK_FOR_INTERRUPTS();
        while (graph[u].id < 0 && predecessors[u] != u) {
            pgassert(graph[u].id < 0);
            pgassert(distances[v] !=  std::numeric_limits<double>::infinity());
            v = u;
            u = predecessors[v];
        }
        /* the vertex (or initial point) that is a predecessor of p */
        predecessors[node] = u;
    }
}
References CHECK_FOR_INTERRUPTS, and pgassert.
Referenced by get_depth().