PGROUTING: anonymous_namespace{binaryBreadthFirstSearch_driver.cpp} Namespace Reference
anonymous_namespace{binaryBreadthFirstSearch_driver.cpp} Namespace Reference
Functions
template<class G >
std::deque< pgrouting::Path > binaryBreadthFirstSearch (G &graph, std::map< int64_t, std::set< int64_t > > &combinations)
template<class G >
bool costCheck (G &graph)
Function Documentation
binaryBreadthFirstSearch()
template<class G > std::deque< pgrouting::Path > anonymous_namespace{binaryBreadthFirstSearch_driver.cpp}::binaryBreadthFirstSearch (G & graph, std::map< int64_t, std::set< int64_t > > & combinations)
Definition at line 112 of file binaryBreadthFirstSearch_driver.cpp.
{
    pgrouting::functions::Pgr_binaryBreadthFirstSearch< G > fn_binaryBreadthFirstSearch;
    auto paths = fn_binaryBreadthFirstSearch.binaryBreadthFirstSearch(graph, combinations);
    return paths;
}
References pgrouting::functions::Pgr_binaryBreadthFirstSearch< G >::binaryBreadthFirstSearch().
Referenced by pgr_do_binaryBreadthFirstSearch().
costCheck()
template<class G > bool anonymous_namespace{binaryBreadthFirstSearch_driver.cpp}::costCheck (G & graph)
Definition at line 83 of file binaryBreadthFirstSearch_driver.cpp.
                     {
    typedef typename G::E E;
    typedef typename G::E_i E_i;
    const size_t max_unique_edge_costs = 2;
    auto edges = boost::edges(graph.graph);
    E e;
    E_i out_i;
    E_i out_end;
    std::set<double> cost_set;
    for (boost::tie(out_i, out_end) = edges;
            out_i != out_end; ++out_i) {
        e = *out_i;
        cost_set.insert(graph[e].cost);
        if (cost_set.size() > max_unique_edge_costs) {
            return false;
        }
    }
    if (cost_set.size() == 2) {
        if (*cost_set.begin() != 0.0) {
            return false;
        }
    }
    return true;
}
Referenced by pgr_do_binaryBreadthFirstSearch().