PGROUTING: anonymous_namespace{lineGraph_driver.cpp} Namespace Reference
anonymous_namespace{lineGraph_driver.cpp} Namespace Reference
Functions
template<typename G >
std::vector< Edge_t > line_graph (const G &original, bool add_self_loop)
Function Documentation
line_graph()
template<typename G > std::vector< Edge_t > anonymous_namespace{lineGraph_driver.cpp}::line_graph (const G & original, bool add_self_loop)
Definition at line 49 of file lineGraph_driver.cpp.
{
    auto lg_result = pgrouting::b_g::line_graph(original.graph);
    return pgrouting::b_g::graph_to_existing_edges(lg_result, add_self_loop);
}
References pgrouting::b_g::graph_to_existing_edges(), and pgrouting::b_g::line_graph().
Referenced by pgr_do_lineGraph().