PGROUTING: anonymous_namespace{transitiveClosure_driver.cpp} Namespace Reference
anonymous_namespace{transitiveClosure_driver.cpp} Namespace Reference
Functions
template<typename G >
void get_postgres_result (G &graph, TransitiveClosure_rt **return_tuples, size_t *count)
template<class G >
boost::adjacency_list pgr_transitiveClosure (G &graph)
Function Documentation
get_postgres_result()
template<typename G > void anonymous_namespace{transitiveClosure_driver.cpp}::get_postgres_result (G & graph, TransitiveClosure_rt ** return_tuples, size_t * count)
Definition at line 53 of file transitiveClosure_driver.cpp.
                       {
    using pgrouting::pgr_alloc;
    boost::adjacency_list <> TC;
    TC = pgr_transitiveClosure(graph);
    (*count) = boost::num_vertices(TC);
    (*return_tuples) = pgr_alloc((*count), (*return_tuples));
    size_t sequence = 0;
    boost::graph_traits < boost::adjacency_list <> >::vertex_iterator i, end;
    boost::graph_traits < boost::adjacency_list <> >::adjacency_iterator ai, a_end;
    int ii = 1;
    for (boost::tie(i, end) = boost::vertices(TC); i != end; ++i) {
            auto u = *i;
            int64_t* target_array = nullptr;
            auto uid = graph.graph[u].id;
            boost::tie(ai, a_end) = adjacent_vertices(u, TC);
            size_t adj_siz = static_cast<size_t>(a_end - ai);
            target_array = pgr_alloc(adj_siz , target_array);
            int number = 0;
            for (; ai != a_end; ++ai) {
                auto v = *ai;
                int64_t vid = graph.graph[v].id;
                target_array[number++] = vid;
            }
        (*return_tuples)[sequence] = {
            ii++,
            uid,
            target_array,
            number};
         ++sequence;
    }
}
References pgrouting::pgr_alloc(), and pgr_transitiveClosure().
Referenced by pgr_do_transitiveClosure().
pgr_transitiveClosure()
template<class G > boost::adjacency_list anonymous_namespace{transitiveClosure_driver.cpp}::pgr_transitiveClosure (G & graph)
Definition at line 45 of file transitiveClosure_driver.cpp.
                  {
    Pgr_transitiveClosure< G > fn_transitiveClosure;
    return fn_transitiveClosure.transitiveClosure(graph);
}
References Pgr_transitiveClosure< G >::transitiveClosure().
Referenced by get_postgres_result().