PGROUTING: pgrouting::algorithms::detail Namespace Reference
pgrouting::algorithms::detail Namespace Reference
Functions
std::vector< pgr_components_rt > componentsResult (std::vector< std::vector< int64_t > > &components)
std::vector< pgr_components_rt > componentsResult (std::vector< std::vector< int64_t >> &components)
Function Documentation
componentsResult() [1/2]
std::vector<pgr_components_rt> pgrouting::algorithms::detail::componentsResult (std::vector< std::vector< int64_t > > & components)
Definition at line 38 of file componentsResult.cpp.
{
     // sort identifier
     for (auto &component : components) {
         std::sort(component.begin(), component.end());
     }
     sort(components.begin(), components.end());
     // generate results
     std::vector< pgr_components_rt > results;
     for (const auto& component : components) {
         auto component_id = component[0];
         for (const auto element : component) {
             results.push_back({component_id, element});
         }
     }
     return results;
 }
Referenced by pgrouting::algorithms::biconnectedComponents(), pgrouting::algorithms::pgr_connectedComponents(), and pgrouting::algorithms::strongComponents().
componentsResult() [2/2]
std::vector<pgr_components_rt> pgrouting::algorithms::detail::componentsResult (std::vector< std::vector< int64_t >> & components)