PGROUTING: pgrouting::utilities Namespace Reference
pgrouting::utilities Namespace Reference
Functions
std::map< int64_t, std::set< int64_t > > get_combinations (const char *combinations_sql, ArrayType *startsArr, ArrayType *endsArr, bool normal)
gets all the departures and destinations
std::map< int64_t, std::set< int64_t > > get_combinations (const std::string &combinations_sql, ArrayType *startsArr, ArrayType *endsArr, bool normal, bool &is_matrix)
gets all the departures and destinations
std::map< int64_t, std::set< int64_t > > get_combinations (const std::vector< II_t_rt > &combinations)
std::map< int64_t, std::set< int64_t > > get_combinations (std::deque< Path > &paths, const std::vector< pgrouting::trsp::Rule > &ruleList)
Function Documentation
get_combinations() [1/4]
std::map< int64_t, std::set< int64_t > > pgrouting::utilities::get_combinations (const char * combinations_sql, ArrayType * startsArr, ArrayType * endsArr, bool normal)
gets all the departures and destinations
Parameters
[in] combinations_sql from the combinations signatures
[in] startsArr PostgreSQL array with the departures
[in] endsArr PostgreSQL array with the destinations
[in] normal the graph is reversed so reverse starts & ends
Returns
[out] map: for each departure a set of destinations
The resulting map can be empty
Definition at line 108 of file combinations.cpp.
{
    using pgrouting::pgget::get_intSet;
    std::map<int64_t, std::set<int64_t>> result;
    std::set<int64_t> starts;
    std::set<int64_t> ends;
    if (startsArr && endsArr) {
        starts = normal? get_intSet(startsArr) : get_intSet(endsArr);
        ends =   normal? get_intSet(endsArr) : get_intSet(startsArr);
    }
    /* TODO Read query storing like std::map<int64_t , std::set<int64_t>> */
    /* queries are stored in vectors */
    auto combinations = combinations_sql?
        pgrouting::pgget::get_combinations(std::string(combinations_sql)) : std::vector<II_t_rt>();
    /* data comes from a combinations */
    for (const auto &row : combinations) {
        result[row.d1.source].insert(row.d2.target);
    }
    /* data comes from many to many */
    for (const auto &s : starts) {
        result[s] = ends;
    }
    return result;
}
References pgrouting::pgget::get_combinations(), and pgrouting::pgget::get_intSet().
get_combinations() [2/4]
std::map< int64_t, std::set< int64_t > > pgrouting::utilities::get_combinations (const std::string & combinations_sql, ArrayType * startsArr, ArrayType * endsArr, bool normal, bool & is_matrix)
gets all the departures and destinations
Parameters
[in] combinations_sql from the combinations signatures
[in] startsArr PostgreSQL array with the departures
[in] endsArr PostgreSQL array with the destinations
[in] normal the graph is reversed so reverse starts & ends
[in] is_matrix set to true when data comes from costMatrix
Returns
[out] map: for each departure a set of destinations
When: combinations_sql comes from a combinations signature When: startsArr && endsArr comes from a Cost signature When: startsArr && !endsArr comes from a CostMatrix signature
The resulting std::map can be empty
Definition at line 154 of file combinations.cpp.
{
    using pgrouting::pgget::get_intSet;
    using pgrouting::pgget::get_combinations;
    std::map<int64_t, std::set<int64_t>> result;
    auto starts = normal? get_intSet(startsArr) : get_intSet(endsArr);
    auto ends = endsArr? (normal? get_intSet(endsArr) : get_intSet(startsArr)) : std::set<int64_t>();
    /* TODO Read query storing like std::map<int64_t , std::set<int64_t>> */
    /* queries are stored in vectors */
    auto combinations = !combinations_sql.empty()? get_combinations(combinations_sql) : std::vector<II_t_rt>();
    /* data comes from CostMatrix */
    if (combinations.empty() && !starts.empty() && ends.empty()) {
        is_matrix = true;
        ends = starts;
    }
    /* data comes from a combinations */
    for (const auto &row : combinations) {
        result[row.d1.source].insert(row.d2.target);
    }
    /* data comes from many to many */
    for (const auto &s : starts) {
        result[s] = ends;
    }
    return result;
}
References pgrouting::pgget::get_combinations(), get_combinations(), and pgrouting::pgget::get_intSet().
get_combinations() [3/4]
std::map< int64_t, std::set< int64_t > > pgrouting::utilities::get_combinations (const std::vector< II_t_rt > & combinations)
Definition at line 89 of file combinations.cpp.
{
    std::map<int64_t, std::set<int64_t>> result;
    for (const auto &row : combinations) {
        result[row.d1.source].insert(row.d2.target);
    }
    return result;
}
get_combinations() [4/4]
std::map< int64_t, std::set< int64_t > > pgrouting::utilities::get_combinations (std::deque< Path > & paths, const std::vector< pgrouting::trsp::Rule > & ruleList)
Definition at line 42 of file combinations.cpp.
{
    std::map<int64_t, std::set<int64_t>> new_combinations;
    for (auto &p : paths) {
        if (p.empty()) {
            new_combinations[p.start_id()].insert(p.end_id());
            continue;
        }
        std::deque<int64_t> edgesList(p.size());
        for (const auto &row : p) {
            edgesList.push_back(row.edge);
        }
        for (const auto &r : ruleList) {
            auto ptr = std::find(edgesList.begin(), edgesList.end(), r.precedences().front());
            if (ptr == edgesList.end()) continue;
            /*
             * And edge on the beginning of a rule list was found
             * Checking if the complete rule applies
             */
            /*
             * Suppose the rule is used
             */
            bool rule_breaker = true;
            for (const auto &e : r.precedences()) {
                if (*ptr != e) {
                    rule_breaker = false; break;
                }
                ++ptr;
            }
            if (rule_breaker) {
                new_combinations[p.start_id()].insert(p.end_id());
                p.clear();
            }
        }
    }
    paths.erase(std::remove_if(paths.begin(), paths.end(),
                [](const Path &p) {
                    return p.size() == 0;
                }),
                paths.end());
    return new_combinations;
}
Referenced by do_shortestPath(), get_combinations(), pgr_do_astar(), pgr_do_bdAstar(), pgr_do_bdDijkstra(), pgr_do_bellman_ford(), pgr_do_bellman_ford_neg(), pgr_do_binaryBreadthFirstSearch(), pgr_do_dagShortestPath(), pgr_do_dijkstra(), pgr_do_edge_disjoint_paths(), pgr_do_edwardMoore(), pgr_do_ksp(), pgr_do_max_flow(), pgr_do_minCostMaxFlow(), pgr_do_trsp(), pgr_do_trsp_withPoints(), pgr_do_trspVia(), pgr_do_trspVia_withPoints(), pgr_do_turnRestrictedPath(), pgr_do_withPoints(), pgr_do_withPointsDD(), and pgr_do_withPointsKsp().