PGROUTING: pgrouting Namespace Reference
pgrouting Namespace Reference
The main file which calls the respective boost function.
Namespaces
namespace algorithm
namespace algorithms
namespace b_g
namespace bidirectional
namespace contraction
namespace detail
namespace details
namespace flow
namespace functions
namespace graph
boost::graph simplified to pgRouting needs This class gives the handling basics of a boost::graph of kind G where G: can be an undirected graph or a directed graph.
namespace metrics
namespace pgget
namespace to_postgres
namespace trsp
namespace tsp
namespace utilities
namespace visitors
namespace vrp
namespace yen
Classes
class Basic_edge
class Basic_vertex
class CH_edge
class CH_vertex
struct Column_info_t
class compPathsLess
Compares 2 paths for <.
struct found_goals
exception for visitor termination
class Identifier
class Identifiers
class Line_vertex
class Path
class Pg_points_graph
class Pgr_bellman_ford
class Pgr_dag
class Pgr_messages
class XY_vertex
Typedefs
using Bline = bg::model::linestring< Bpoint >
using Blines = bg::model::multi_linestring< Bline >
using Bpoint = bg::model::d2::point_xy< double >
using Bpoints = bg::model::multi_point< Bpoint >
using Bpoly = bg::model::polygon< Bpoint >
using Bpolys = bg::model::multi_polygon< Bpoly >
typedef boost::property_map< CostFlowGraph, boost::edge_capacity_t >::type Capacity
using Column_info_t = Column_info_t
typedef boost::adjacency_list< boost::vecS, boost::vecS, boost::directedS, boost::no_property, boost::property< boost::edge_capacity_t, double, boost::property< boost::edge_residual_capacity_t, double, boost::property< boost::edge_reverse_t, Traits::edge_descriptor, boost::property< boost::edge_weight_t, double > > > > > CostFlowGraph
typedef boost::adjacency_list< boost::listS, boost::vecS, boost::directedS, boost::property< boost::vertex_index_t, int64_t, boost::property< boost::vertex_color_t, boost::default_color_type, boost::property< boost::vertex_distance_t, int64_t, boost::property< boost::vertex_predecessor_t, Traits::edge_descriptor > > > >, boost::property< boost::edge_capacity_t, int64_t, boost::property< boost::edge_residual_capacity_t, int64_t, boost::property< boost::edge_reverse_t, Traits::edge_descriptor > > > > FlowGraph
typedef boost::adjacency_list< boost::vecS, boost::vecS, boost::bidirectionalS, Line_vertex, Basic_edge > LinearDirectedGraph
Data type to handle graph -> lineGaph transformation.
typedef boost::property_map< CostFlowGraph, boost::edge_residual_capacity_t >::type ResidualCapacity
typedef boost::property_map< CostFlowGraph, boost::edge_reverse_t >::type Reversed
typedef boost::adjacency_list_traits< boost::vecS, boost::vecS, boost::directedS > Traits
typedef boost::property_map< CostFlowGraph, boost::edge_weight_t >::type Weight
Graph types
Type pgRouting
UndirectedGraph Basic undirected graph
DirectedGraph Basic directed graph
xyUndirectedGraph X & Y values stored on the vertex
xyDirectedGraph X & Y values stored on the vertex
typedef graph::Pgr_base_graph< boost::adjacency_list< boost::vecS, boost::vecS, boost::undirectedS, Basic_vertex, Basic_edge >, Basic_vertex, Basic_edge, false > UndirectedGraph
typedef graph::Pgr_base_graph< boost::adjacency_list< boost::vecS, boost::vecS, boost::bidirectionalS, Basic_vertex, Basic_edge >, Basic_vertex, Basic_edge, true > DirectedGraph
typedef graph::Pgr_base_graph< boost::adjacency_list< boost::listS, boost::vecS, boost::undirectedS, XY_vertex, Basic_edge >, XY_vertex, Basic_edge, false > xyUndirectedGraph
typedef graph::Pgr_base_graph< boost::adjacency_list< boost::listS, boost::vecS, boost::bidirectionalS, XY_vertex, Basic_edge >, XY_vertex, Basic_edge, true > xyDirectedGraph
Enumerations
enum expectType {
ANY_INTEGER , ANY_NUMERICAL , TEXT , CHAR1 ,
ANY_INTEGER_ARRAY
}
Functions
size_t check_vertices (std::vector< Basic_vertex > vertices)
size_t check_vertices (std::vector< CH_vertex > vertices)
size_t check_vertices (std::vector< XY_vertex > vertices)
size_t collapse_paths (MST_rt **tuples, const std::deque< Path > &paths)
size_t collapse_paths (Path_rt **ret_path, const std::deque< Path > &paths)
bool column_found (int)
Function will check whether the colNumber represent any specific column or NULL (SPI_ERROR_NOATTRIBUTE).
size_t count_tuples (const std::deque< Path > &paths)
template<class G >
void dijkstraVia (G &graph, const std::vector< int64_t > &via_vertices, std::deque< Path > &paths, bool strict, bool U_turn_on_edge, std::ostringstream &log)
void equi_cost (std::deque< Path > &paths)
std::vector< Basic_vertex > extract_vertices (const Edge_t *data_edges, size_t count)
std::vector< XY_vertex > extract_vertices (const Edge_xy_t *data_edges, size_t count)
std::vector< Basic_vertex > extract_vertices (const std::vector< Basic_vertex > &vertices, const Edge_t *data_edges, size_t count)
std::vector< Basic_vertex > extract_vertices (const std::vector< Edge_t > &data_edges)
std::vector< XY_vertex > extract_vertices (const std::vector< Edge_xy_t > &data_edges)
std::vector< Basic_vertex > extract_vertices (std::vector< Basic_vertex > vertices, const Edge_t *data_edges, size_t count)
std::vector< Basic_vertex > extract_vertices (std::vector< Basic_vertex > vertices, std::vector< Edge_t > data_edges)
void fetch_column_info (const TupleDesc &, std::vector< Column_info_t > &)
Function tells expected type of each column and then check the correspondence type of each column.
template<class G >
std::vector< std::vector< double > > floydWarshall (G &graph)
int64_t * get_array (ArrayType *v, size_t *arrlen, bool allow_empty)
get the array contents from postgres
template<typename Data_type , typename Func >
void get_data (char *sql, Data_type **pgtuples, size_t *total_pgtuples, bool flag, std::vector< Column_info_t > info, Func func)
Retrieves the tuples.
std::vector< int64_t > get_pgarray (ArrayType *v, bool allow_empty)
get the array contents from postgres
std::set< int64_t > get_pgset (ArrayType *v)
get the array contents from postgres
int64_t getBigInt (const HeapTuple, const TupleDesc &, const Column_info_t &)
Function returns the value of specified column in integer type.
int64_t * getBigIntArr (const HeapTuple tuple, const TupleDesc &tupdesc, const Column_info_t &info, size_t *the_size)
DatumGetArrayTypeP pgrouting::get_bigIntArray
char getChar (const HeapTuple tuple, const TupleDesc &tupdesc, const pgrouting::Column_info_t &info, bool strict, char default_value)
http://doxygen.postgresql.org/include_2catalog_2pg__type_8h.html; SPI_getbinval Datum DatumGetInt16
double getFloat8 (const HeapTuple, const TupleDesc &, const Column_info_t &)
Function returns the value of specified column in double type.
char * getText (const HeapTuple tuple, const TupleDesc &tupdesc, const pgrouting::Column_info_t &info)
[SPI_getvalue](https://doxygen.postgresql.org/spi_8c.html#ae53c12ff90592f67e4e40ad0af24205b which calls OidOutputFunctionCall, which calls OutputFunctionCall - https://doxygen.postgresql.org/fmgr_8c.html#ae19cff34818e4a6c90523e8bb02c3420 which returns pointer to CString)
template<class G >
std::vector< std::vector< double > > johnson (G &graph)
template<class G >
std::vector< int64_t > kingOrdering (G &graph)
std::ostream & operator<< (std::ostream &log, const Basic_vertex &v)
std::ostream & operator<< (std::ostream &log, const Identifier &ident)
std::ostream & operator<< (std::ostream &log, const Path &path)
std::ostream & operator<< (std::ostream &log, const XY_vertex &v)
std::ostream & operator<< (std::ostream &os, const CH_edge &e)
std::ostream & operator<< (std::ostream &os, const CH_vertex &v)
std::ostream & operator<< (std::ostream &os, const Pg_points_graph &g)
template<typename T >
T * pgr_alloc (std::size_t size, T *ptr)
allocates memory
template<typename T >
T * pgr_free (T *ptr)
char * to_pg_msg (const std::ostringstream &msg)
char * to_pg_msg (const std::string &msg)
std::deque< std::pair< int64_t, double > > tsp (graph::UndirectedHasCostBG &, int64_t, int64_t)
std::deque< std::pair< int64_t, double > > tsp (TSP_graph &graph, int64_t sid, int64_t eid)
Detailed Description
The main file which calls the respective boost function.
Contains actual implementation of the function and the calling of the respective boost function.
Typedef Documentation
Bline
using pgrouting::Bline = typedef bg::model::linestring<Bpoint>
Definition at line 47 of file bline.hpp.
Blines
using pgrouting::Blines = typedef bg::model::multi_linestring<Bline>
Definition at line 48 of file bline.hpp.
Bpoint
typedef bg::model::d2::point_xy< double > pgrouting::Bpoint
Definition at line 44 of file bline.hpp.
Bpoints
using pgrouting::Bpoints = typedef bg::model::multi_point<Bpoint>
Definition at line 45 of file bline.hpp.
Bpoly
using pgrouting::Bpoly = typedef bg::model::polygon<Bpoint>
Definition at line 50 of file bline.hpp.
Bpolys
using pgrouting::Bpolys = typedef bg::model::multi_polygon<Bpoly>
Definition at line 51 of file bline.hpp.
Capacity
typedef boost::property_map<CostFlowGraph,boost::edge_capacity_t>::type pgrouting::Capacity
Definition at line 51 of file costFlowGraph.hpp.
Column_info_t
using pgrouting::Column_info_t = typedef Column_info_t
Definition at line 49 of file get_check_data.hpp.
CostFlowGraph
typedef boost::adjacency_list< boost::vecS, boost::vecS, boost::directedS, boost::no_property, boost::property < boost::edge_capacity_t, double, boost::property < boost::edge_residual_capacity_t, double, boost::property < boost::edge_reverse_t, Traits::edge_descriptor, boost::property < boost::edge_weight_t, double> > > > > pgrouting::CostFlowGraph
Definition at line 49 of file costFlowGraph.hpp.
DirectedGraph
typedef graph::Pgr_base_graph<boost::adjacency_list < boost::vecS, boost::vecS, boost::bidirectionalS, Basic_vertex, Basic_edge >, Basic_vertex, Basic_edge , true> pgrouting::DirectedGraph
Definition at line 196 of file base_graph.hpp.
FlowGraph
typedef boost::adjacency_list<boost::listS, boost::vecS, boost::directedS, boost::property<boost::vertex_index_t, int64_t, boost::property<boost::vertex_color_t, boost::default_color_type, boost::property<boost::vertex_distance_t, int64_t, boost::property<boost::vertex_predecessor_t, Traits::edge_descriptor> > > >, boost::property<boost::edge_capacity_t, int64_t, boost::property<boost::edge_residual_capacity_t, int64_t, boost::property<boost::edge_reverse_t, Traits::edge_descriptor> > > > pgrouting::FlowGraph
Definition at line 53 of file flowgraph.hpp.
LinearDirectedGraph
typedef boost::adjacency_list< boost::vecS, boost::vecS, boost::bidirectionalS, Line_vertex, Basic_edge > pgrouting::LinearDirectedGraph
Data type to handle graph -> lineGaph transformation.
Usage:
pgrouting::graph::Pgr_lineGraphFull<
     pgrouting::LinearDirectedGraph,  // using here
     pgrouting::Line_vertex,
     pgrouting::Basic_edge > line(graphType::DIRECTED);
pgrouting::graph::Pgr_lineGraph<
     pgrouting::LinearDirectedGraph,  // using here
     pgrouting::Line_vertex,
     pgrouting::Basic_edge > line(graphType::DIRECTED);
Definition at line 55 of file linear_directed_graph.hpp.
ResidualCapacity
typedef boost::property_map<CostFlowGraph,boost::edge_residual_capacity_t>::type pgrouting::ResidualCapacity
Definition at line 53 of file costFlowGraph.hpp.
Reversed
typedef boost::property_map<CostFlowGraph,boost::edge_reverse_t>::type pgrouting::Reversed
Definition at line 57 of file costFlowGraph.hpp.
Traits
typedef boost::adjacency_list_traits< boost::vecS, boost::vecS, boost::directedS > pgrouting::Traits
Definition at line 39 of file costFlowGraph.hpp.
UndirectedGraph
typedef graph::Pgr_base_graph<boost::adjacency_list < boost::vecS, boost::vecS, boost::undirectedS, Basic_vertex, Basic_edge >, Basic_vertex, Basic_edge, false > pgrouting::UndirectedGraph
Definition at line 190 of file base_graph.hpp.
Weight
typedef boost::property_map<CostFlowGraph,boost::edge_weight_t>::type pgrouting::Weight
Definition at line 55 of file costFlowGraph.hpp.
xyDirectedGraph
typedef graph::Pgr_base_graph<boost::adjacency_list < boost::listS, boost::vecS, boost::bidirectionalS, XY_vertex, Basic_edge >, XY_vertex, Basic_edge , true> pgrouting::xyDirectedGraph
Definition at line 208 of file base_graph.hpp.
xyUndirectedGraph
typedef graph::Pgr_base_graph<boost::adjacency_list < boost::listS, boost::vecS, boost::undirectedS, XY_vertex, Basic_edge >, XY_vertex, Basic_edge , false> pgrouting::xyUndirectedGraph
Definition at line 202 of file base_graph.hpp.
Enumeration Type Documentation
expectType
enum pgrouting::expectType
Enumerator
ANY_INTEGER
ANY_NUMERICAL
TEXT
CHAR1
ANY_INTEGER_ARRAY
Definition at line 38 of file info_t.hpp.
                {
    ANY_INTEGER,
    ANY_NUMERICAL,
    TEXT,
    CHAR1,
    ANY_INTEGER_ARRAY
};
Function Documentation
check_vertices() [1/3]
size_t pgrouting::check_vertices (std::vector< Basic_vertex > vertices)
Definition at line 45 of file basic_vertex.cpp.
{
        auto count(vertices.size());
        std::stable_sort(
                vertices.begin(), vertices.end(),
                [](const Basic_vertex &lhs, const Basic_vertex &rhs)
                {return lhs.id < rhs.id;});
        vertices.erase(
                std::unique(
                    vertices.begin(), vertices.end(),
                    [](const Basic_vertex &lhs, const Basic_vertex &rhs)
                    {return lhs.id == rhs.id;}), vertices.end());
        return vertices.size() - count;
    }
check_vertices() [2/3]
size_t pgrouting::check_vertices (std::vector< CH_vertex > vertices)
check_vertices() [3/3]
size_t pgrouting::check_vertices (std::vector< XY_vertex > vertices)
Definition at line 68 of file xy_vertex.cpp.
{
    auto count(vertices.size());
    std::stable_sort(
        vertices.begin(), vertices.end(),
        [](const XY_vertex &lhs, const XY_vertex &rhs)
        {return lhs.id < rhs.id;});
    vertices.erase(
        std::unique(
            vertices.begin(), vertices.end(),
            [](const XY_vertex &lhs, const XY_vertex &rhs)
            {return lhs.id == rhs.id;}), vertices.end());
    return count - vertices.size();
}
collapse_paths() [1/2]
size_t pgrouting::collapse_paths (MST_rt ** tuples, const std::deque< Path > & paths)
Definition at line 329 of file path.cpp.
{
    size_t sequence = 0;
    for (const Path &path : paths) {
        if (path.path.size() > 0) path.generate_tuples(tuples, sequence);
    }
    return sequence;
}
collapse_paths() [2/2]
size_t pgrouting::collapse_paths (Path_rt ** ret_path, const std::deque< Path > & paths)
Definition at line 316 of file path.cpp.
{
    size_t sequence = 0;
    for (const Path &path : paths) {
        if (path.path.size() > 0) {
            path.generate_postgres_data(ret_path, sequence);
        }
    }
    return sequence;
}
column_found()
bool pgrouting::column_found (int colNumber)
Function will check whether the colNumber represent any specific column or NULL (SPI_ERROR_NOATTRIBUTE).
Parameters
[in] colNumber Column number (count starts at 1).
Returns
TRUE when colNumber exist. FALSE when colNumber was not found.
SPI_ERROR_NOATTRIBUTE
Definition at line 170 of file get_check_data.cpp.
{
    return !(colNumber == SPI_ERROR_NOATTRIBUTE);
}
Referenced by pgrouting::pgget::fetch_basic_edge(), pgrouting::pgget::fetch_coordinate(), pgrouting::pgget::fetch_costFlow_edge(), pgrouting::pgget::fetch_edge(), pgrouting::pgget::fetch_edge_xy(), pgrouting::pgget::fetch_orders(), pgrouting::pgget::fetch_point(), and pgrouting::pgget::fetch_vehicle().
count_tuples()
size_t pgrouting::count_tuples (const std::deque< Path > & paths)
Definition at line 405 of file path.cpp.
{
    size_t count(0);
    for (const Path &e : paths) {
        count += e.path.size();
    }
    return count;
}
Referenced by pgrouting::to_postgres::get_viaRoute().
dijkstraVia()
template<class G > void pgrouting::dijkstraVia (G & graph, const std::vector< int64_t > & via_vertices, std::deque< Path > & paths, bool strict, bool U_turn_on_edge, std::ostringstream & log)
Definition at line 47 of file dijkstraVia.hpp.
{
    if (via_vertices.size() == 0) {
        return;
    }
    paths.clear();
    int64_t prev_vertex = via_vertices[0];
    Path path;
    int64_t i = 0;
    for (const auto &vertex : via_vertices) {
        if (i == 0) {
            prev_vertex = vertex; ++i;
            continue;
        }
        // Delete U Turn edges only valid for paths that are not the first path
        if (!U_turn_on_edge && i > 1) {
            /*
             * Can only delete if there was a path,
             * that is at least one edge size
             */
            if (path.size() > 1) {
                /*
                 * Delete from the graph the last edge if its outgoing also
                 * edge to be removed = second to last edge path[i].edge;
                 */
                int64_t edge_to_be_removed = path[path.size() - 2].edge;
                int64_t last_vertex_of_path = prev_vertex;
                // and the current vertex is not a dead end
                if (graph.out_degree(last_vertex_of_path) > 1) {
                    log << "\ndeparting from " << last_vertex_of_path
                        << " deleting edge " << edge_to_be_removed << "\n";
                    graph.disconnect_out_going_edge(
                            last_vertex_of_path,
                            edge_to_be_removed);
                }
            }
        }
        log << "\nfrom " << prev_vertex << " to " << vertex;
        path = algorithms::dijkstra(graph, prev_vertex, vertex);
        if (!U_turn_on_edge && i > 1) {
            graph.restore_graph();
            if (path.empty()) {
                /*
                 *  no path was found with the deleted edge
                 *  try with the edge back in the graph
                 */
                log << "\nEmpty so again from "
                    << prev_vertex << " to " << vertex;
                path = algorithms::dijkstra(graph, prev_vertex, vertex);
            }
        }
        if (strict && path.empty()) {
            paths.clear();
            return;
        }
        paths.push_back(path);
        /*
         * got to the next
         */
        prev_vertex = vertex; ++i;
    }
}
References pgrouting::algorithms::dijkstra(), pgrouting::Path::empty(), and pgrouting::Path::size().
Referenced by pgr_do_dijkstraVia(), pgr_do_trspVia(), pgr_do_trspVia_withPoints(), and pgr_do_withPointsVia().
equi_cost()
void pgrouting::equi_cost (std::deque< Path > & paths)
Definition at line 354 of file path.cpp.
{
    /* sort paths by size: largest first */
    std::sort(paths.begin(), paths.end(),
            [](const Path &e1, const Path &e2)->bool {
            return e2.size() < e1.size();
            });
    /* sort each path by node: smaller id first */
    for (auto &p : paths) {
        if (p.size() < 2) continue;
        std::sort(p.begin(), p.end(),
                [](const Path_t &e1, const Path_t &e2)->bool {
                return e1.node < e2.node;
                });
    }
    for (auto &p1 : paths) {
        for (const auto &p2 : paths) {
            if (p1.start_id() == p2.start_id()) continue;
            for (const auto &stop : p2.path) {
                /* find the node of p2 in p1 */
                auto pos = lower_bound(p1.begin(), p1.end(), stop,
                        [](const Path_t &l, const Path_t &r)->bool {
                        return l.node < r.node;
                        });
                if (pos != p1.end()
                        && (stop.node == pos->node)
                        && (stop.agg_cost < pos->agg_cost)) {
                    /* both share the same node &
                     * the second path has the smallest
                     *  So erasing from the first path */
                    p1.erase(pos);
                }
            }
        }
    }
    /* sort paths by start_id */
    std::sort(paths.begin(), paths.end(),
            [](const Path &e1, const Path &e2)->bool {
            return e1.start_id() < e2.start_id();
            });
    /* sort each path by agg_cost, node */
    for (auto &path : paths) {
        path.sort_by_node_agg_cost();
    }
}
extract_vertices() [1/7]
std::vector< Basic_vertex > pgrouting::extract_vertices (const Edge_t * data_edges, size_t count)
Definition at line 127 of file basic_vertex.cpp.
{
        return extract_vertices(
                std::vector < Edge_t >(
                    data_edges, data_edges + count));
    }
References extract_vertices().
extract_vertices() [2/7]
std::vector< XY_vertex > pgrouting::extract_vertices (const Edge_xy_t * data_edges, size_t count)
Definition at line 117 of file xy_vertex.cpp.
{
    return extract_vertices(
        std::vector <Edge_xy_t >(data_edges, data_edges + count));
}
References extract_vertices().
extract_vertices() [3/7]
std::vector< Basic_vertex > pgrouting::extract_vertices (const std::vector< Basic_vertex > & vertices, const Edge_t * data_edges, size_t count)
Definition at line 134 of file basic_vertex.cpp.
{
        return extract_vertices(
                vertices, std::vector < Edge_t >(
                    data_edges, data_edges + count));
    }
References extract_vertices().
extract_vertices() [4/7]
std::vector< Basic_vertex > pgrouting::extract_vertices (const std::vector< Edge_t > & data_edges)
Definition at line 95 of file basic_vertex.cpp.
{
        std::vector< Basic_vertex > vertices;
        if (data_edges.empty()) return vertices;
        vertices.reserve(data_edges.size() * 2);
        for (const auto edge : data_edges) {
            Basic_vertex vertex;
            vertex.id = edge.source;
            vertices.push_back(vertex);
            vertex.id = edge.target;
            vertices.push_back(vertex);
        }
        /*
         * sort and delete duplicates
         */
        std::stable_sort(vertices.begin(), vertices.end(),
                [](const Basic_vertex &lhs, const Basic_vertex &rhs)
                {return lhs.id < rhs.id;});
        vertices.erase(
                std::unique(vertices.begin(), vertices.end(),
                    [](const Basic_vertex &lhs, const Basic_vertex &rhs)
                    {return lhs.id == rhs.id;}), vertices.end());
        return vertices;
    }
References pgrouting::Basic_vertex::id.
extract_vertices() [5/7]
std::vector< XY_vertex > pgrouting::extract_vertices (const std::vector< Edge_xy_t > & data_edges)
Definition at line 85 of file xy_vertex.cpp.
{
    std::vector< XY_vertex > vertices;
    if (data_edges.empty()) return vertices;
    vertices.reserve(data_edges.size() * 2);
    for (const auto &edge : data_edges) {
        XY_vertex v_source(edge, true);
        vertices.push_back(v_source);
        XY_vertex v_target(edge, false);
        vertices.push_back(v_target);
    }
    /*
     * sort and delete duplicates
     */
    std::stable_sort(
        vertices.begin(), vertices.end(),
        [](const XY_vertex &lhs, const XY_vertex &rhs)
        {return lhs.id < rhs.id;});
    vertices.erase(
        std::unique(
            vertices.begin(), vertices.end(),
            [](const XY_vertex &lhs, const XY_vertex &rhs)
            {return lhs.id == rhs.id;}), vertices.end());
    return vertices;
}
extract_vertices() [6/7]
std::vector< Basic_vertex > pgrouting::extract_vertices (std::vector< Basic_vertex > vertices, const Edge_t * data_edges, size_t count)
extract_vertices() [7/7]
std::vector< Basic_vertex > pgrouting::extract_vertices (std::vector< Basic_vertex > vertices, std::vector< Edge_t > data_edges)
Definition at line 62 of file basic_vertex.cpp.
{
        if (data_edges.empty()) return vertices;
        vertices.reserve(vertices.size() + data_edges.size() * 2);
        for (const auto edge : data_edges) {
            Basic_vertex vertex;
            vertex.id = edge.source;
            vertices.push_back(vertex);
            vertex.id = edge.target;
            vertices.push_back(vertex);
        }
        /*
         * sort and delete duplicates
         */
        std::stable_sort(vertices.begin(), vertices.end(),
                [](const Basic_vertex &lhs, const Basic_vertex &rhs)
                {return lhs.id < rhs.id;});
        vertices.erase(
                std::unique(vertices.begin(), vertices.end(),
                    [](const Basic_vertex &lhs, const Basic_vertex &rhs)
                    {return lhs.id == rhs.id;}), vertices.end());
        return vertices;
    }
References pgrouting::Basic_vertex::id.
Referenced by do_metrics(), do_ordering(), extract_vertices(), extract_vertices(), extract_vertices(), pgr_do_trsp_withPoints(), and pgr_do_withPoints().
fetch_column_info()
void pgrouting::fetch_column_info (const TupleDesc & tupdesc, std::vector< pgrouting::Column_info_t > & info)
Function tells expected type of each column and then check the correspondence type of each column.
Parameters
[in] tupdesc tuple descriptor
[in] info contain one or more column information.
Exceptions
ERROR Unknown type of column.
Definition at line 181 of file get_check_data.cpp.
{
    for (auto &coldata : info) {
        if (get_column_info(tupdesc, coldata)) {
            switch (coldata.eType) {
                case ANY_INTEGER:
                    check_any_integer_type(coldata);
                    break;
                case ANY_NUMERICAL:
                    check_any_numerical_type(coldata);
                    break;
                case TEXT:
                    check_text_type(coldata);
                    break;
                case CHAR1:
                    check_char_type(coldata);
                    break;
                case ANY_INTEGER_ARRAY:
                    check_any_integer_array_type(coldata);
                    break;
                default:
                    throw std::string("Unexpected type of column ") + coldata.name;
            }
        }
    }
}
References ANY_INTEGER, ANY_INTEGER_ARRAY, ANY_NUMERICAL, CHAR1, and TEXT.
Referenced by get_data(), and pgrouting::pgget::get_data().
floydWarshall()
template<class G > std::vector< std::vector< double > > pgrouting::floydWarshall (G & graph)
Definition at line 62 of file allpairs.hpp.
{
    std::vector<std::vector<double>> matrix(graph.num_vertices(), std::vector<double>(graph.num_vertices(), 0));
    detail::inf_plus<double> combine;
    CHECK_FOR_INTERRUPTS();
    boost::floyd_warshall_all_pairs_shortest_paths(
            graph.graph,
            matrix,
            weight_map(get(&pgrouting::Basic_edge::cost, graph.graph)).
            distance_combine(combine).
            distance_inf((std::numeric_limits<double>::max)()).
            distance_zero(0));
    return matrix;
}
References CHECK_FOR_INTERRUPTS, and pgrouting::Basic_edge::cost.
Referenced by do_allpairs().
get_array()
int64_t * pgrouting::get_array (ArrayType * v, size_t * arrlen, bool allow_empty)
get the array contents from postgres
Enforces the input array to be NOT empty.
This function generates the array inputs according to their type received through ArrayType *v parameter and store them in c_array. It can be empty also if received allow_empty true. The cases of failure are:-
When ndim is not equal to one dimension.
When no element is found i.e. nitems is zero or negative.
If the element type doesn't lie in switch cases, give the error of expected array of any integer type
When size of c_array is out of range or memory.
When null value is found in the array.
All these failures are represented as error through elog.
Parameters
[in] v Pointer to the postgres C array
[out] arrlen size of the C array
[in] allow_empty flag to allow empty arrays
Precondition
the array has to be one dimension
Must have elements (when allow_empty is false)
Returns
The resultant array
Definition at line 445 of file get_check_data.cpp.
{
    int64_t *c_array = nullptr;
    auto    element_type = ARR_ELEMTYPE(v);
    auto    dim = ARR_DIMS(v);
    auto    ndim = ARR_NDIM(v);
    auto    nitems = ArrayGetNItems(ndim, dim);
    Datum  *elements = nullptr;
    bool   *nulls = nullptr;
    int16   typlen;
    bool    typbyval;
    char    typalign;
    if (allow_empty && (ndim == 0 || nitems <= 0)) {
        return nullptr;
    }
    if (ndim != 1) {
        throw std::string("One dimension expected");
    }
    if (nitems <= 0) {
        throw std::string("No elements found");
    }
    get_typlenbyvalalign(element_type, &typlen, &typbyval, &typalign);
    /* validate input data type */
    switch (element_type) {
        case INT2OID:
        case INT4OID:
        case INT8OID:
            break;
        default:
            throw std::string("Expected array of ANY-INTEGER");
            return nullptr;
    }
    deconstruct_array(v, element_type, typlen, typbyval,
            typalign, &elements, &nulls,
            &nitems);
    c_array = pgr_alloc(static_cast<size_t>(nitems), (c_array));
    if (!c_array) {
        throw std::string("Out of memory!");
    }
    for (int i = 0; i < nitems; i++) {
        if (nulls[i]) {
            pfree(c_array);
            throw std::string("NULL value found in Array!");
            return nullptr;
        } else {
            switch (element_type) {
                case INT2OID:
                    c_array[i] = static_cast<int64_t>(DatumGetInt16(elements[i]));
                    break;
                case INT4OID:
                    c_array[i] = static_cast<int64_t>(DatumGetInt32(elements[i]));
                    break;
                case INT8OID:
                    c_array[i] = DatumGetInt64(elements[i]);
                    break;
            }
        }
    }
    (*arrlen) = static_cast<size_t>(nitems);
    pfree(elements);
    pfree(nulls);
    return c_array;
}
References pgr_alloc().
Referenced by getBigIntArr().
get_data()
template<typename Data_type , typename Func > void pgrouting::get_data (char * sql, Data_type ** pgtuples, size_t * total_pgtuples, bool flag, std::vector< Column_info_t > info, Func func)
Retrieves the tuples.
Template Parameters
Data_type Scructure of data
Func fetcher function
Parameters
[in] sql Query to be processed
[out] pgtuples C array of data
[out] total_pgtuples C array size
[in] flag useful flag depending on data
[in] info information about the data
[in] func fetcher function to be used
Definition at line 55 of file get_data.hpp.
                   {
    const int tuple_limit = 1000000;
    size_t total_tuples;
    size_t valid_pgtuples;
    auto SPIplan = pgr_SPI_prepare(sql);
    auto SPIportal = pgr_SPI_cursor_open(SPIplan);
    bool moredata = true;
    (*total_pgtuples) = total_tuples = valid_pgtuples = 0;
    int64_t default_id = 0;
    while (moredata == true) {
        SPI_cursor_fetch(SPIportal, true, tuple_limit);
        auto tuptable = SPI_tuptable;
        auto tupdesc = SPI_tuptable->tupdesc;
        if (total_tuples == 0) fetch_column_info(tupdesc, info);
        size_t ntuples = SPI_processed;
        total_tuples += ntuples;
        if (ntuples > 0) {
            (*pgtuples) = pgr_alloc(total_tuples, *pgtuples);
            if ((*pgtuples) == NULL) {
                throw std::string("Out of memory!");
            }
            for (size_t t = 0; t < ntuples; t++) {
                func(tuptable->vals[t], tupdesc, info,
                        &default_id,
                        &(*pgtuples)[total_tuples - ntuples + t],
                        &valid_pgtuples, flag);
            }
            SPI_freetuptable(tuptable);
        } else {
            moredata = false;
        }
    }
    SPI_cursor_close(SPIportal);
    (*total_pgtuples) = total_tuples;
}
References fetch_column_info(), pgr_alloc(), pgr_SPI_cursor_open(), and pgr_SPI_prepare().
get_pgarray()
std::vector< int64_t > pgrouting::get_pgarray (ArrayType * v, bool allow_empty)
get the array contents from postgres
get postgres array into c++ vector container
This function generates the array inputs according to their type received through ArrayType *v parameter and store them in c_array. It can be empty also if received allow_empty true. The cases of failure are:-
When ndim is not equal to one dimension.
When no element is found i.e. nitems is zero or negative.
If the element type doesn't lie in switch cases, give the error of expected array of any integer type
When size of c_array is out of range or memory.
When null value is found in the array.
All these failures are represented as error through elog.
Parameters
[in] v Pointer to the postgres C array
[in] allow_empty flag to allow empty arrays
Precondition
the array has to be one dimension
Must have elements (when allow_empty is false)
Returns
Vector of elements of the PostgreSQL array
Definition at line 352 of file get_check_data.cpp.
{
    std::vector<int64_t> results;
    if (!v) return results;
    auto    element_type = ARR_ELEMTYPE(v);
    auto    dim = ARR_DIMS(v);
    auto    ndim = ARR_NDIM(v);
    auto    nitems = ArrayGetNItems(ndim, dim);
    Datum  *elements = nullptr;
    bool   *nulls = nullptr;
    int16   typlen;
    bool    typbyval;
    char    typalign;
    if (allow_empty && (ndim == 0 || nitems <= 0)) {
        return results;
    }
    if (ndim != 1) {
        throw std::string("One dimension expected");
    }
    if (nitems <= 0) {
        throw std::string("No elements found");
    }
    get_typlenbyvalalign(element_type, &typlen, &typbyval, &typalign);
    /* validate input data type */
    switch (element_type) {
        case INT2OID:
        case INT4OID:
        case INT8OID:
            break;
        default:
            throw std::string("Expected array of ANY-INTEGER");
    }
    deconstruct_array(v, element_type, typlen, typbyval,
            typalign, &elements, &nulls,
            &nitems);
    int64_t data(0);
    results.reserve(static_cast<size_t>(nitems));
    for (int i = 0; i < nitems; i++) {
        if (nulls[i]) {
            throw std::string("NULL value found in Array!");
        } else {
            switch (element_type) {
                case INT2OID:
                    data = static_cast<int64_t>(DatumGetInt16(elements[i]));
                    break;
                case INT4OID:
                    data = static_cast<int64_t>(DatumGetInt32(elements[i]));
                    break;
                case INT8OID:
                    data = DatumGetInt64(elements[i]);
                    break;
            }
        }
        results.push_back(data);
    }
    pfree(elements);
    pfree(nulls);
    return results;
}
Referenced by pgrouting::pgget::get_intArray().
get_pgset()
std::set< int64_t > pgrouting::get_pgset (ArrayType * v)
get the array contents from postgres
get postgres array into c++ set container
This function generates the array inputs according to their type received through ArrayType *v parameter and store them in c_array. It can be empty also if received allow_empty true. The cases of failure are:-
When ndim is not equal to one dimension.
When no element is found i.e. nitems is zero or negative.
If the element type doesn't lie in switch cases, give the error of expected array of any integer type
When size of c_array is out of range or memory.
When null value is found in the array.
All these failures are represented as error through elog.
Parameters
[in] v Pointer to the postgres C array
Precondition
the array has to be one dimension
Must have elements (when allow_empty is false)
Returns
set of elements on the PostgreSQL array
Definition at line 266 of file get_check_data.cpp.
{
    std::set<int64_t> results;
    if (!v) return results;
    auto    element_type = ARR_ELEMTYPE(v);
    auto    dim = ARR_DIMS(v);
    auto    ndim = ARR_NDIM(v);
    auto    nitems = ArrayGetNItems(ndim, dim);
    Datum  *elements = nullptr;
    bool   *nulls = nullptr;
    int16   typlen;
    bool    typbyval;
    char    typalign;
    if (ndim == 0 || nitems <= 0) {
        return results;
    }
    if (ndim != 1) {
        throw std::string("One dimension expected");
    }
    get_typlenbyvalalign(element_type, &typlen, &typbyval, &typalign);
    switch (element_type) {
        case INT2OID:
        case INT4OID:
        case INT8OID:
            break;
        default:
            throw std::string("Expected array of ANY-INTEGER");
    }
    deconstruct_array(v, element_type, typlen, typbyval,
            typalign, &elements, &nulls,
            &nitems);
    int64_t data(0);
    for (int i = 0; i < nitems; i++) {
        if (nulls[i]) {
            throw std::string("NULL value found in Array!");
        } else {
            switch (element_type) {
                case INT2OID:
                    data = static_cast<int64_t>(DatumGetInt16(elements[i]));
                    break;
                case INT4OID:
                    data = static_cast<int64_t>(DatumGetInt32(elements[i]));
                    break;
                case INT8OID:
                    data = DatumGetInt64(elements[i]);
                    break;
            }
        }
        results.insert(data);
    }
    pfree(elements);
    pfree(nulls);
    return results;
}
Referenced by pgrouting::pgget::get_intSet().
getBigInt()
int64_t pgrouting::getBigInt (const HeapTuple tuple, const TupleDesc & tupdesc, const pgrouting::Column_info_t & info)
Function returns the value of specified column in integer type.
Parameters
[in] tuple input row to be examined.
[in] tupdesc tuple descriptor
[in] info contain column information.
Exceptions
ERROR Unexpected Column type. Expected column type is ANY-INTEGER.
ERROR When value of column is NULL.
Returns
Integer type of column value is returned.
Definition at line 557 of file get_check_data.cpp.
{
    Datum binval;
    bool isnull;
    int64_t value = 0;
    binval = SPI_getbinval(tuple, tupdesc, info.colNumber, &isnull);
    if (isnull) {
        throw std::string("Unexpected Null value in column ") + info.name;
    }
    switch (info.type) {
        case INT2OID:
            value = static_cast<int64_t>(DatumGetInt16(binval));
            break;
        case INT4OID:
            value = static_cast<int64_t>(DatumGetInt32(binval));
            break;
        case INT8OID:
            value = DatumGetInt64(binval);
            break;
        default:
            throw std::string("Unexpected Column type of ") + info.name + ". Expected ANY-INTEGER";
    }
    return value;
}
References pgrouting::Column_info_t::colNumber, pgrouting::Column_info_t::name, and pgrouting::Column_info_t::type.
Referenced by pgrouting::pgget::fetch_basic_edge(), pgrouting::pgget::fetch_combination(), pgrouting::pgget::fetch_coordinate(), pgrouting::pgget::fetch_costFlow_edge(), pgrouting::pgget::fetch_delauny(), pgrouting::pgget::fetch_edge(), pgrouting::pgget::fetch_edge_xy(), pgrouting::pgget::fetch_orders(), pgrouting::pgget::fetch_point(), pgrouting::pgget::fetch_vehicle(), and pgrouting::pgget::pgr_fetch_row().
getBigIntArr()
int64_t * pgrouting::getBigIntArr (const HeapTuple tuple, const TupleDesc & tupdesc, const Column_info_t & info, size_t * the_size)
DatumGetArrayTypeP pgrouting::get_bigIntArray
Function returns the values of specified columns in array.
Parameters
[in] tuple input row to be examined.
[in] tupdesc input row description.
[in] info contain column information.
[out] the_size number of element in array.
Exceptions
ERROR No elements found in ARRAY.
ERROR Unexpected Column type. Expected column type is ANY-INTEGER-ARRAY.
ERROR NULL value found in Array.
Returns
Array of columns value is returned.
Definition at line 533 of file get_check_data.cpp.
{
    bool is_null = false;
    Datum raw_array = SPI_getbinval(tuple, tupdesc, info.colNumber, &is_null);
    *the_size = 0;
    if (is_null) return nullptr;
    ArrayType *pg_array = DatumGetArrayTypeP(raw_array);
    return get_array(pg_array, the_size, true);
}
References pgrouting::Column_info_t::colNumber, and get_array().
Referenced by pgrouting::pgget::fetch_restriction().
getChar()
char pgrouting::getChar (const HeapTuple tuple, const TupleDesc & tupdesc, const pgrouting::Column_info_t & info, bool strict, char default_value)
http://doxygen.postgresql.org/include_2catalog_2pg__type_8h.html; SPI_getbinval Datum DatumGetInt16
Function return the value of specified column in char type.
Parameters
[in] tuple input row to be examined.
[in] tupdesc tuple descriptor
[in] info contain column information.
[in] strict boolean value of strict.
[in] default_value returned when column contain NULL value.
Exceptions
ERROR Unexpected Column type. Expected column type is CHAR.
ERROR When value of column is NULL.
Returns
Char type of column value is returned.
Definition at line 224 of file get_check_data.cpp.
{
    Datum binval;
    bool isNull;
    char value = default_value;
    binval = SPI_getbinval(tuple, tupdesc, info.colNumber, &isNull);
    if (!(info.type == BPCHAROID)) {
        throw std::string("Unexpected Column type of ") + info.name + ". Expected CHAR";
    }
    if (!isNull) {
        value =  reinterpret_cast<char*>(binval)[1];
    } else {
        if (strict) {
            throw std::string("Unexpected Null value in column ") + info.name;
        }
        value = default_value;
    }
    return value;
}
References pgrouting::Column_info_t::colNumber, pgrouting::Column_info_t::name, and pgrouting::Column_info_t::type.
Referenced by pgrouting::pgget::fetch_point().
getFloat8()
double pgrouting::getFloat8 (const HeapTuple tuple, const TupleDesc & tupdesc, const pgrouting::Column_info_t & info)
Function returns the value of specified column in double type.
Parameters
[in] tuple input row to be examined.
[in] tupdesc tuple descriptor
[in] info contain column information.
Exceptions
ERROR Unexpected Column type. Expected column type is ANY-NUMERICAL.
ERROR When value of column is NULL.
Returns
Double type of column value is returned.
Definition at line 590 of file get_check_data.cpp.
{
    Datum binval;
    bool isnull = false;
    binval = SPI_getbinval(tuple, tupdesc, info.colNumber, &isnull);
    if (isnull) {
        throw std::string("Unexpected Null value in column ") + info.name;
    }
    switch (info.type) {
        case INT2OID:
            return static_cast<double>(DatumGetInt16(binval));
            break;
        case INT4OID:
            return static_cast<double>(DatumGetInt32(binval));
            break;
        case INT8OID:
            return static_cast<double>(DatumGetInt64(binval));
            break;
        case FLOAT4OID:
            return static_cast<double>(DatumGetFloat4(binval));
            break;
        case FLOAT8OID:
            return static_cast<double>(DatumGetFloat8(binval));
            break;
        case NUMERICOID:
            /* Note: out-of-range values will be clamped to +-HUGE_VAL */
            return static_cast<double>(DatumGetFloat8(DirectFunctionCall1(numeric_float8_no_overflow, binval)));
            break;
        default:
            throw std::string("Unexpected Column type of ") + info.name + ". Expected ANY-NUMERICAL";
    }
    return 0.0;
}
References pgrouting::Column_info_t::colNumber, pgrouting::Column_info_t::name, and pgrouting::Column_info_t::type.
Referenced by pgrouting::pgget::fetch_basic_edge(), pgrouting::pgget::fetch_coordinate(), pgrouting::pgget::fetch_costFlow_edge(), pgrouting::pgget::fetch_delauny(), pgrouting::pgget::fetch_edge(), pgrouting::pgget::fetch_edge_xy(), pgrouting::pgget::fetch_orders(), pgrouting::pgget::fetch_point(), pgrouting::pgget::fetch_restriction(), pgrouting::pgget::fetch_vehicle(), and pgrouting::pgget::pgr_fetch_row().
getText()
char * pgrouting::getText (const HeapTuple tuple, const TupleDesc & tupdesc, const pgrouting::Column_info_t & info)
[SPI_getvalue](https://doxygen.postgresql.org/spi_8c.html#ae53c12ff90592f67e4e40ad0af24205b which calls OidOutputFunctionCall, which calls OutputFunctionCall - https://doxygen.postgresql.org/fmgr_8c.html#ae19cff34818e4a6c90523e8bb02c3420 which returns pointer to CString)
Function returns the string representation of the value of specified column.
Note
under development Not used, not tested
Parameters
[in] tuple input row to be examined.
[in] tupdesc tuple descriptor
[in] info contain column information.
Returns
Pointer of string is returned.
Definition at line 638 of file get_check_data.cpp.
{
    return SPI_getvalue(tuple, tupdesc, info.colNumber);
}
References pgrouting::Column_info_t::colNumber.
johnson()
template<class G > std::vector< std::vector< double > > pgrouting::johnson (G & graph)
Definition at line 82 of file allpairs.hpp.
                  {
    std::vector<std::vector<double>> matrix(graph.num_vertices(), std::vector<double>(graph.num_vertices(), 0));
    detail::inf_plus<double> combine;
    CHECK_FOR_INTERRUPTS();
    boost::johnson_all_pairs_shortest_paths(
            graph.graph,
            matrix,
            weight_map(get(&pgrouting::Basic_edge::cost, graph.graph)).
            distance_combine(combine).
            distance_inf((std::numeric_limits<double>::max)()).
            distance_zero(0));
    return matrix;
}
References CHECK_FOR_INTERRUPTS, and pgrouting::Basic_edge::cost.
Referenced by do_allpairs().
kingOrdering()
template<class G > std::vector< int64_t > pgrouting::kingOrdering (G & graph)
Definition at line 54 of file kingOrdering.hpp.
                       {
    using V = typename G::V;
    size_t n = boost::num_vertices(graph.graph);
    std::vector<int64_t> results(n);
    auto index_map = boost::get(boost::vertex_index, graph.graph);
    std::vector<V> colors(n);
    auto color_map = boost::make_iterator_property_map(colors.begin(), index_map);
    auto degree_map = boost::make_degree_map(graph.graph);
    std::vector<V> inv_permutation(n);
    CHECK_FOR_INTERRUPTS();
    boost::king_ordering(
        graph.graph,
        inv_permutation.rbegin(),
        color_map,
        degree_map,
        index_map);
    size_t j = 0;
    for (auto i = inv_permutation.begin(); i != inv_permutation.end(); ++i, ++j) {
        results[j] = static_cast<int64_t>(graph.graph[index_map[*i]].id);
    }
    return results;
}
References CHECK_FOR_INTERRUPTS.
Referenced by do_ordering().
operator<<() [1/7]
std::ostream & pgrouting::operator<< (std::ostream & log, const Basic_vertex & v)
Definition at line 40 of file basic_vertex.cpp.
{
        log << v.id;
        return log;
    }
operator<<() [2/7]
std::ostream & pgrouting::operator<< (std::ostream & log, const Identifier & ident)
Definition at line 55 of file identifier.cpp.
{
    log << "id(idx) = " << ident.id() << "(" << ident.idx() << ")";
    return log;
}
operator<<() [3/7]
std::ostream & pgrouting::operator<< (std::ostream & log, const Path & path)
Definition at line 134 of file path.cpp.
{
    log << "Path: " << path.start_id() << " -> " << path.end_id() << "\n"
        << "seq\tnode\tedge\tcost\tagg_cost\n";
    int64_t i = 0;
    for (const auto &e : path) {
        log << i << "\t"
            << e.node << "\t"
            << e.edge << "\t"
            << e.cost << "\t"
            << e.agg_cost << "\n";
        ++i;
    }
    return log;
}
operator<<() [4/7]
std::ostream & pgrouting::operator<< (std::ostream & log, const XY_vertex & v)
Definition at line 54 of file xy_vertex.cpp.
{
    log << v.id << "-" << bg::wkt(v.point);
    return log;
}
operator<<() [5/7]
std::ostream & pgrouting::operator<< (std::ostream & os, const CH_edge & e)
Definition at line 82 of file ch_edge.cpp.
{
    os << "{id: " << e.id << ",\t"
        << "source: " << e.source << ",\t"
        << "target: " << e.target << ",\t"
        << "cost: " << e.cost << ",\t"
        << "contracted vertices: "
        << e.contracted_vertices()
        << "}";
    return os;
}
operator<<() [6/7]
std::ostream & pgrouting::operator<< (std::ostream & os, const CH_vertex & v)
Definition at line 75 of file ch_vertex.cpp.
{
    os << "{id: " << v.id << ",\t"
     << "contracted vertices: "
     << v.contracted_vertices()
     << "}";
    return os;
}
operator<<() [7/7]
std::ostream & pgrouting::operator<< (std::ostream & os, const Pg_points_graph & g)
Definition at line 46 of file withPoints.cpp.
{
    for (const auto p : g.m_points) {
        os << p.pid << "\t"
            << p.edge_id << "\t"
            << p.fraction << "\t"
            << p.side << "\n";
    }
    return os;
}
pgr_alloc()
template<typename T > pgrouting::pgr_alloc (std::size_t size, T * ptr)
allocates memory
Does a malloc or realloc depending on the ptr value
To be used only on C++ code
To be used when returning results to postgres
free must occur in the C code
Parameters
[in] size
[in] ptr
Returns
pointer to the first byte of allocated space
Definition at line 72 of file alloc.hpp.
{
    if (!ptr) {
        ptr = static_cast<T*>(SPI_palloc(size * sizeof(T)));
    } else {
        ptr = static_cast<T*>(SPI_repalloc(ptr, size * sizeof(T)));
    }
    return ptr;
}
References SPI_palloc(), and SPI_repalloc().
Referenced by do_ordering(), do_shortestPath(), get_array(), get_data(), anonymous_namespace{contractGraph_driver.cpp}::get_postgres_result(), anonymous_namespace{transitiveClosure_driver.cpp}::get_postgres_result(), anonymous_namespace{lineGraphFull_driver.cpp}::get_turn_penalty_postgres_result(), pgrouting::to_postgres::get_viaRoute(), pgrouting::to_postgres::graph_to_tuple(), pgrouting::to_postgres::matrix_to_tuple(), pgr_contractionHierarchies(), pgr_do_articulationPoints(), pgr_do_astar(), pgr_do_bdAstar(), pgr_do_bdDijkstra(), pgr_do_bellman_ford(), pgr_do_bellman_ford_neg(), pgr_do_biconnectedComponents(), pgr_do_binaryBreadthFirstSearch(), pgr_do_bipartite(), pgr_do_boyerMyrvold(), pgr_do_breadthFirstSearch(), pgr_do_bridges(), pgr_do_connectedComponents(), pgr_do_contractGraph(), pgr_do_cuthillMckeeOrdering(), pgr_do_dagShortestPath(), pgr_do_depthFirstSearch(), pgr_do_dijkstra(), pgr_do_dijkstraVia(), pgr_do_directedChPP(), pgr_do_drivingDistance(), pgr_do_edge_disjoint_paths(), pgr_do_edgeColoring(), pgr_do_edwardMoore(), pgr_do_euclideanTSP(), pgr_do_hawickCircuits(), pgr_do_isPlanar(), pgr_do_kruskal(), pgr_do_ksp(), pgr_do_lineGraph(), pgr_do_LTDTree(), pgr_do_makeConnected(), pgr_do_max_flow(), pgr_do_maximum_cardinality_matching(), pgr_do_minCostMaxFlow(), pgr_do_pickDeliver(), pgr_do_pickDeliverEuclidean(), pgr_do_prim(), pgr_do_randomSpanningTree(), pgr_do_sequentialVertexColoring(), pgr_do_stoerWagner(), pgr_do_strongComponents(), pgr_do_topologicalSort(), pgr_do_trsp(), pgr_do_trsp_withPoints(), pgr_do_trspVia(), pgr_do_trspVia_withPoints(), pgr_do_tsp(), pgr_do_turnRestrictedPath(), pgr_do_withPoints(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), pgr_do_withPointsVia(), to_pg_msg(), and pgrouting::to_postgres::vector_to_tuple().
pgr_free()
template<typename T > T * pgrouting::pgr_free (T * ptr)
Definition at line 83 of file alloc.hpp.
                 {
    if (ptr) {
        SPI_pfree(ptr);
    }
    return nullptr;
}
References SPI_pfree().
Referenced by do_allpairs(), do_metrics(), do_ordering(), do_shortestPath(), pgr_contractionHierarchies(), pgr_do_articulationPoints(), pgr_do_astar(), pgr_do_bdAstar(), pgr_do_bdDijkstra(), pgr_do_bellman_ford(), pgr_do_bellman_ford_neg(), pgr_do_betweennessCentrality(), pgr_do_biconnectedComponents(), pgr_do_binaryBreadthFirstSearch(), pgr_do_bipartite(), pgr_do_boyerMyrvold(), pgr_do_breadthFirstSearch(), pgr_do_bridges(), pgr_do_connectedComponents(), pgr_do_contractGraph(), pgr_do_cuthillMckeeOrdering(), pgr_do_dagShortestPath(), pgr_do_depthFirstSearch(), pgr_do_dijkstra(), pgr_do_dijkstraVia(), pgr_do_directedChPP(), pgr_do_drivingDistance(), pgr_do_edge_disjoint_paths(), pgr_do_edgeColoring(), pgr_do_edwardMoore(), pgr_do_euclideanTSP(), pgr_do_hawickCircuits(), pgr_do_isPlanar(), pgr_do_kruskal(), pgr_do_ksp(), pgr_do_lineGraph(), pgr_do_lineGraphFull(), pgr_do_LTDTree(), pgr_do_makeConnected(), pgr_do_max_flow(), pgr_do_maximum_cardinality_matching(), pgr_do_minCostMaxFlow(), pgr_do_pickDeliver(), pgr_do_pickDeliverEuclidean(), pgr_do_prim(), pgr_do_randomSpanningTree(), pgr_do_sequentialVertexColoring(), pgr_do_stoerWagner(), pgr_do_strongComponents(), pgr_do_topologicalSort(), pgr_do_transitiveClosure(), pgr_do_trsp(), pgr_do_trsp_withPoints(), pgr_do_trspVia(), pgr_do_trspVia_withPoints(), pgr_do_tsp(), pgr_do_turnRestrictedPath(), pgr_do_withPoints(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), and pgr_do_withPointsVia().
to_pg_msg() [1/2]
char * pgrouting::to_pg_msg (const std::ostringstream & msg)
Definition at line 45 of file alloc.cpp.
{
    return to_pg_msg(msg.str());
}
References to_pg_msg().
to_pg_msg() [2/2]
char * pgrouting::to_pg_msg (const std::string & msg)
Definition at line 35 of file alloc.cpp.
{
    if (msg.empty()) return nullptr;
    char* duplicate = nullptr;
    duplicate = pgr_alloc(msg.size() + 1, duplicate);
    memcpy(duplicate, msg.c_str(), msg.size());
    duplicate[msg.size()] = '\0';
    return duplicate;
}
References pgr_alloc().
Referenced by do_allpairs(), do_metrics(), do_ordering(), do_shortestPath(), get_name(), get_new_queries(), get_order(), pgr_contractionHierarchies(), pgr_do_articulationPoints(), pgr_do_astar(), pgr_do_bdAstar(), pgr_do_bdDijkstra(), pgr_do_bellman_ford(), pgr_do_bellman_ford_neg(), pgr_do_betweennessCentrality(), pgr_do_biconnectedComponents(), pgr_do_binaryBreadthFirstSearch(), pgr_do_bipartite(), pgr_do_boyerMyrvold(), pgr_do_breadthFirstSearch(), pgr_do_bridges(), pgr_do_connectedComponents(), pgr_do_contractGraph(), pgr_do_cuthillMckeeOrdering(), pgr_do_dagShortestPath(), pgr_do_depthFirstSearch(), pgr_do_dijkstra(), pgr_do_dijkstraVia(), pgr_do_directedChPP(), pgr_do_drivingDistance(), pgr_do_edge_disjoint_paths(), pgr_do_edgeColoring(), pgr_do_edwardMoore(), pgr_do_euclideanTSP(), pgr_do_hawickCircuits(), pgr_do_isPlanar(), pgr_do_kruskal(), pgr_do_ksp(), pgr_do_lineGraph(), pgr_do_lineGraphFull(), pgr_do_LTDTree(), pgr_do_makeConnected(), pgr_do_max_flow(), pgr_do_maximum_cardinality_matching(), pgr_do_minCostMaxFlow(), pgr_do_pickDeliver(), pgr_do_pickDeliverEuclidean(), pgr_do_prim(), pgr_do_randomSpanningTree(), pgr_do_sequentialVertexColoring(), pgr_do_stoerWagner(), pgr_do_strongComponents(), pgr_do_topologicalSort(), pgr_do_transitiveClosure(), pgr_do_trsp(), pgr_do_trsp_withPoints(), pgr_do_trspVia(), pgr_do_trspVia_withPoints(), pgr_do_tsp(), pgr_do_turnRestrictedPath(), pgr_do_withPoints(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), pgr_do_withPointsVia(), and to_pg_msg().
tsp() [1/2]
std::deque< std::pair< int64_t, double > > pgrouting::tsp (graph::UndirectedHasCostBG & , int64_t , int64_t)
tsp() [2/2]
std::deque< std::pair< int64_t, double > > pgrouting::tsp (TSP_graph & graph, int64_t sid, int64_t eid)
Definition at line 303 of file tsp.cpp.
{
    return do_tsp(graph, sid, eid);
}