PGROUTING: pgrouting::to_postgres Namespace Reference
pgrouting::to_postgres Namespace Reference
Namespaces
namespace detail
Functions
size_t get_viaRoute (std::deque< pgrouting::Path > &paths, Routes_t **tuples)
template<class G >
void graph_to_tuple (G &graph, contractionHierarchies_rt **return_tuples, size_t *count)
returns results to the SQL function
template<class G >
void matrix_to_tuple (const G &graph, const std::vector< std::vector< double > > &matrix, size_t &result_tuple_count, IID_t_rt **postgres_rows)
Stored results on a vector are saved on a C array.
template<class G >
void vector_to_tuple (const G &graph, const std::vector< double > results, size_t &result_count, IID_t_rt **result_tuples)
Stored results on a vector are saved on a C array.
Function Documentation
get_viaRoute()
size_t pgrouting::to_postgres::get_viaRoute (std::deque< pgrouting::Path > & paths, Routes_t ** tuples)
Parameters
[in] paths The set of Paths
[out] tuples The C array of Route_t
Returns
number of tuples on the C array
Currently works for
pgr_dijkstraVia
pgr_trspVia
pgr_trspVia_withPoints
pgr_withPointsVia
Definition at line 82 of file to_postgres.cpp.
{
    pgassert(!(*tuples));
    auto count = count_tuples(paths);
    if (count == 0) return 0;
    (*tuples) = pgr_alloc(count, (*tuples));
    size_t sequence = 0;
    int path_id = 1;
    int route_id = 1;
    double route_agg_cost = 0;
    for (auto &p : paths) {
        p.recalculate_agg_cost();
    }
    for (const auto &path : paths) {
        if (path.size() > 0) {
            ::get_path(route_id, path_id, path, tuples, route_agg_cost, sequence);
        }
        ++path_id;
    }
    (*tuples)[count - 1].edge = -2;
    pgassert(count == sequence);
    return sequence;
}
References pgrouting::count_tuples(), pgassert, and pgrouting::pgr_alloc().
Referenced by pgr_do_dijkstraVia(), pgr_do_trspVia(), pgr_do_trspVia_withPoints(), and pgr_do_withPointsVia().
graph_to_tuple()
template<class G > void pgrouting::to_postgres::graph_to_tuple (G & graph, contractionHierarchies_rt ** return_tuples, size_t * count)
returns results to the SQL function
Parameters
[in] graph created graph
[out] return_tuples tuples containing the results to pass to the SQL function
[out] count string stream containing log information
Currently works for pgr_contractionHierarchies
Definition at line 150 of file to_postgres.hpp.
                       {
    using pgrouting::pgr_alloc;
    auto modified_vertices(graph.get_modified_vertices());
    auto shortcut_edges(graph.get_shortcuts());
    (*count) = modified_vertices.size() + shortcut_edges.size();
    (*return_tuples) = pgr_alloc((*count), (*return_tuples));
    size_t sequence = 0;
    for (const auto id : modified_vertices) {
        auto v = graph.get_V(id);
        int64_t* contracted_vertices = NULL;
        auto vids = graph[v].contracted_vertices();
        int64_t o = graph.get_vertex_order(id);
        int64_t m = graph.get_vertex_metric(id);
        contracted_vertices = pgr_alloc(vids.size(), contracted_vertices);
        int count = 0;
        for (const auto id : vids) {
            contracted_vertices[count++] = id;
        }
        (*return_tuples)[sequence] = {
            id,
            const_cast<char*>("v"),
            -1, -1, -1.00,
            contracted_vertices,
            count,
            o, m};
        ++sequence;
    }
    int64_t eid = 0;
    for (auto e : shortcut_edges) {
        auto edge = graph[e];
        int64_t* contracted_vertices = NULL;
        const auto vids(edge.contracted_vertices());
        pgassert(!vids.empty());
        contracted_vertices = pgr_alloc(vids.size(), contracted_vertices);
        int count = 0;
        for (const auto vid : vids) {
            contracted_vertices[count++] = vid;
        }
        (*return_tuples)[sequence] = {
            --eid,
            const_cast<char*>("e"),
            edge.source, edge.target, edge.cost,
            contracted_vertices, count, -1, -1};
        ++sequence;
    }
}
References pgassert, and pgrouting::pgr_alloc().
Referenced by pgr_contractionHierarchies().
matrix_to_tuple()
template<class G > void pgrouting::to_postgres::matrix_to_tuple (const G & graph, const std::vector< std::vector< double > > & matrix, size_t & result_tuple_count, IID_t_rt ** postgres_rows)
Stored results on a vector are saved on a C array.
Parameters
[in] graph Created graph with the base Graph
[in] matrix matrix[i,j] -> the i,j element contains the results
[out] result_tuple_count the size of the C array
[out] postgres_rows The C array of <bigint, bigint, float>
<bigint, bigint, float> = <i , j, results[i,j]>
Currently works for
pgr_johnson
pgr_floydWarshall
Definition at line 120 of file to_postgres.hpp.
{
    result_tuple_count = detail::count_rows(graph, matrix);
    *postgres_rows = pgr_alloc(result_tuple_count, (*postgres_rows));
    size_t seq = 0;
    for (typename G::V v_i = 0; v_i < graph.num_vertices(); v_i++) {
        for (typename G::V v_j = 0; v_j < graph.num_vertices(); v_j++) {
            if (v_i == v_j) continue;
            if (matrix[v_i][v_j] != (std::numeric_limits<double>::max)()) {
                (*postgres_rows)[seq].from_vid = graph[v_i].id;
                (*postgres_rows)[seq].to_vid = graph[v_j].id;
                (*postgres_rows)[seq].cost =  matrix[v_i][v_j];
                seq++;
            }
        }
    }
}
References pgrouting::to_postgres::detail::count_rows(), and pgrouting::pgr_alloc().
Referenced by do_allpairs().
vector_to_tuple()
template<class G > void pgrouting::to_postgres::vector_to_tuple (const G & graph, const std::vector< double > results, size_t & result_count, IID_t_rt ** result_tuples)
Stored results on a vector are saved on a C array.
Parameters
[in] graph Created graph with the base Graph
[in] results results[i] -> the ith element of the vector contains the results
[out] result_count The size of the vector
[out] result_tuples The C array of <bigint, bigint, float>
<bigint, bigint, float> = < i , 0, results[i] >
Currently works for pgr_betweennessCentrality
Definition at line 86 of file to_postgres.hpp.
{
    result_count = results.size();
    *result_tuples = pgrouting::pgr_alloc(result_count, (*result_tuples));
    size_t seq = 0;
    for (typename G::V v_i = 0; v_i < graph.num_vertices(); ++v_i) {
        (*result_tuples)[seq].from_vid = graph[v_i].id;
        /*
         * These 2 lines are specifically for pgr_betweennessCentrality
         */
        (*result_tuples)[seq].to_vid = 0;
        (*result_tuples)[seq].cost = graph.is_directed()? results[v_i] / 2.0 : results[v_i];
        seq++;
    }
}
References pgrouting::pgr_alloc().
Referenced by pgr_do_betweennessCentrality().