PGROUTING: anonymous_namespace{shortestPath_driver.cpp} Namespace Reference
anonymous_namespace{shortestPath_driver.cpp} Namespace Reference
Functions
char estimate_drivingSide (char driving_side, int32_t which)
void get_new_queries (const std::string &edges_sql, const std::string &points_sql, std::string &edges_of_points_query, std::string &edges_no_points_query)
void post_process (std::deque< pgrouting::Path > &paths, bool only_cost, bool normal, size_t n_goals, bool global)
Function Documentation
estimate_drivingSide()
char anonymous_namespace{shortestPath_driver.cpp}::estimate_drivingSide (char driving_side, int32_t which)
Definition at line 59 of file shortestPath_driver.cpp.
{
    char d_side = static_cast<char>(tolower(driving_side));
    if (!((d_side == 'r') || (d_side == 'l') || (d_side == 'b'))) {
        d_side = ' ';
    }
    if (which == 0) {
        return ' ';
    } else if (which == 1) {
        if (d_side == ' ') {
            throw std::make_pair(std::string("Invalid value of 'driving side'"),
                    std::string("Valid value are 'r', 'l', 'b'"));
        }
    } else {
        /* For the moment its old signature of pgr_withPoints */
        if (!((d_side == 'r') || (d_side == 'l'))) d_side = 'b';
    }
    return d_side;
}
Referenced by do_shortestPath().
get_new_queries()
void anonymous_namespace{shortestPath_driver.cpp}::get_new_queries (const std::string & edges_sql, const std::string & points_sql, std::string & edges_of_points_query, std::string & edges_no_points_query)
Definition at line 79 of file shortestPath_driver.cpp.
{
    edges_of_points_query = std::string("WITH ")
        + " edges AS (" + edges_sql + "), "
        + " points AS (" + points_sql + ")"
        + " SELECT DISTINCT edges.* FROM edges JOIN points ON (id = edge_id)";
    edges_no_points_query  = std::string("WITH ")
        + " edges AS (" + edges_sql + "), "
        + " points AS (" + points_sql + ")"
        + " SELECT edges.*"
        + " FROM edges"
        + " WHERE NOT EXISTS (SELECT edge_id FROM points WHERE id = edge_id)";
}
Referenced by do_shortestPath().
post_process()
void anonymous_namespace{shortestPath_driver.cpp}::post_process (std::deque< pgrouting::Path > & paths, bool only_cost, bool normal, size_t n_goals, bool global)
Definition at line 98 of file shortestPath_driver.cpp.
{
    using pgrouting::Path;
    paths.erase(std::remove_if(paths.begin(), paths.end(),
                [](const Path &p) {
                    return p.size() == 0;
                }),
                paths.end());
    using difference_type = std::deque<double>::difference_type;
    if (!normal) {
        for (auto &path : paths) path.reverse();
    }
    if (!only_cost) {
        for (auto &p : paths) {
            p.recalculate_agg_cost();
        }
    }
    if (n_goals != (std::numeric_limits<size_t>::max)()) {
        std::sort(paths.begin(), paths.end(),
                [](const Path &e1, const Path &e2)->bool {
                    return e1.end_id() < e2.end_id();
                });
        std::stable_sort(paths.begin(), paths.end(),
                [](const Path &e1, const Path &e2)->bool {
                    return e1.start_id() < e2.start_id();
                });
        std::stable_sort(paths.begin(), paths.end(),
                [](const Path &e1, const Path &e2)->bool {
                    return e1.tot_cost() < e2.tot_cost();
                });
        if (global && n_goals < paths.size()) {
            paths.erase(paths.begin() + static_cast<difference_type>(n_goals), paths.end());
        }
    } else {
        std::sort(paths.begin(), paths.end(),
                [](const Path &e1, const Path &e2)->bool {
                    return e1.end_id() < e2.end_id();
                });
        std::stable_sort(paths.begin(), paths.end(),
                [](const Path &e1, const Path &e2)->bool {
                    return e1.start_id() < e2.start_id();
                });
    }
}
References pgrouting::Path::erase().
Referenced by do_shortestPath().