PGROUTING: pgrouting::details Namespace Reference
pgrouting::details Namespace Reference
Functions
std::vector< int64_t > clean_vids (std::vector< int64_t > vids)
std::vector< MST_rt > get_no_edge_graph_result (const std::vector< int64_t > &vids)
Function Documentation
clean_vids()
std::vector< int64_t > pgrouting::details::clean_vids (std::vector< int64_t > vids)
Definition at line 36 of file details.cpp.
{
    std::sort(vids.begin(), vids.end());
    vids.erase(
            std::unique(vids.begin(), vids.end()),
            vids.end());
    vids.erase(
            std::remove(vids.begin(), vids.end(), 0),
            vids.end());
    return vids;
}
Referenced by get_no_edge_graph_result(), pgrouting::functions::Pgr_mst< G >::mstBFS(), pgrouting::functions::Pgr_mst< G >::mstDD(), and pgrouting::functions::Pgr_mst< G >::mstDFS().
get_no_edge_graph_result()
std::vector< MST_rt > pgrouting::details::get_no_edge_graph_result (const std::vector< int64_t > & vids)
Definition at line 48 of file details.cpp.
{
    std::vector<MST_rt> results;
    if (vids.empty()) return results;
    for (auto const root : clean_vids(vids)) {
        results.push_back({root, 0, root, root, -1, 0.0, 0.0});
    }
    return results;
}
References clean_vids().
Referenced by pgr_do_depthFirstSearch(), pgr_do_kruskal(), and pgr_do_prim().