PGROUTING: anonymous_namespace{tsp.cpp} Namespace Reference
anonymous_namespace{tsp.cpp} Namespace Reference
Typedefs
using TSP_graph = pgrouting::graph::UndirectedHasCostBG
using V = TSP_graph::V
Functions
std::deque< std::pair< int64_t, double > > crossover_optimize (TSP_graph &graph, std::deque< std::pair< int64_t, double > > result, size_t limit)
std::deque< std::pair< int64_t, double > > do_tsp (TSP_graph &graph, int64_t start_vid, int64_t end_vid)
std::deque< std::pair< int64_t, double > > eval_tour (TSP_graph &graph, const std::vector< V > &tsp_tour)
double eval_tour (TSP_graph &graph, std::deque< std::pair< int64_t, double > > &tsp_tour)
double get_min_cost (V u, V v, TSP_graph &graph)
std::deque< std::pair< int64_t, double > > start_vid_end_vid_are_fixed (std::deque< std::pair< int64_t, double > > tsp_path, int64_t start_vid, int64_t end_vid)
std::deque< std::pair< int64_t, double > > tsp (TSP_graph &graph)
std::deque< std::pair< int64_t, double > > tsp (TSP_graph &graph, int64_t start_vid)
Typedef Documentation
TSP_graph
using anonymous_namespace{tsp.cpp}::TSP_graph = typedef pgrouting::graph::UndirectedHasCostBG
Definition at line 53 of file tsp.cpp.
V
using anonymous_namespace{tsp.cpp}::V = typedef TSP_graph::V
Definition at line 54 of file tsp.cpp.
Function Documentation
crossover_optimize()
std::deque< std::pair< int64_t, double > > anonymous_namespace{tsp.cpp}::crossover_optimize (TSP_graph & graph, std::deque< std::pair< int64_t, double > > result, size_t limit)
Definition at line 216 of file tsp.cpp.
{
    auto best_cost = eval_tour(graph, result);
    for (size_t i = 1; i < result.size() - limit; ++i) {
        for (size_t j = result.size() - limit; j >= i + 1; --j) {
            auto tmp = result;
            std::reverse(tmp.begin() + static_cast<ptrdiff_t>(i),  tmp.begin() + static_cast<ptrdiff_t>(j));
            auto new_cost = eval_tour(graph, tmp);
            if (new_cost < best_cost) {
                result = tmp;
                best_cost = new_cost;
            }
        }
    }
    return result;
}
References eval_tour().
Referenced by do_tsp().
do_tsp()
std::deque< std::pair< int64_t, double > > anonymous_namespace{tsp.cpp}::do_tsp (TSP_graph & graph, int64_t start_vid, int64_t end_vid)
Parameters
[in] graph The graph
[in] start_vid user's start vertex identifier, 0 when not set
[in] end_vid user's end vertex identifier, 0 when not set
Definition at line 239 of file tsp.cpp.
{
    /*
     * check that the start_vid, and end_vid exist on the data
     */
    if (start_vid == 0) std::swap(start_vid, end_vid);
    if (start_vid != 0 && !graph.has_vertex(start_vid)) {
        throw std::make_pair(
                std::string("INTERNAL: start_id not found on data"),
                std::string(__PGR_PRETTY_FUNCTION__));
    }
    if (end_vid !=0 && !graph.has_vertex(end_vid)) {
        throw std::make_pair(
                std::string("INTERNAL: end_id not found on data"),
                std::string(__PGR_PRETTY_FUNCTION__));
    }
    std::deque<std::pair<int64_t, double>> result;
    /*
     * just get a tsp result
     */
    if (start_vid == 0) {
        return crossover_optimize(graph, tsp(graph), 1);
    }
    /*
     * the has a start value same as end_vid ignore end_vid
     */
    if ((end_vid == 0) || (start_vid == end_vid)) {
        return crossover_optimize(graph, tsp(graph, start_vid), 1);
    }
    /*
     * have start and end, a dummy node is needed
     */
    auto u = graph.get_boost_vertex(start_vid);
    auto v = graph.get_boost_vertex(end_vid);
    graph.insert_vertex(0);
    auto dummy_node = graph.get_boost_vertex(0);
    boost::add_edge(u, dummy_node, 0, graph.graph());
    boost::add_edge(v, dummy_node, 0, graph.graph());
    for (auto v1 : boost::make_iterator_range(boost::vertices(graph.graph()))) {
        if (v1 == u || v1 == v) continue;
        boost::add_edge(v1, dummy_node, std::numeric_limits<double>::infinity(), graph.graph());
    }
    result = tsp(graph, start_vid);
    result = start_vid_end_vid_are_fixed(result, start_vid, end_vid);
    return crossover_optimize(graph, result, 2);
}
References __PGR_PRETTY_FUNCTION__, crossover_optimize(), pgrouting::graph::UndirectedHasCostBG::get_boost_vertex(), pgrouting::graph::UndirectedHasCostBG::graph(), pgrouting::graph::UndirectedHasCostBG::has_vertex(), pgrouting::graph::UndirectedHasCostBG::insert_vertex(), start_vid_end_vid_are_fixed(), and tsp().
eval_tour() [1/2]
std::deque< std::pair< int64_t, double > > anonymous_namespace{tsp.cpp}::eval_tour (TSP_graph & graph, const std::vector< V > & tsp_tour)
Definition at line 132 of file tsp.cpp.
{
    std::deque<std::pair<int64_t, double>> results;
    auto u = graph.graph().null_vertex();
    for (auto v : tsp_tour) {
        auto cost = (u == graph.graph().null_vertex()) ?
            0 :
            get_min_cost(u, v, graph);
        u = v;
        results.push_back(std::make_pair(graph.get_vertex_id(v), cost));
    }
    return results;
}
References get_min_cost(), pgrouting::graph::UndirectedHasCostBG::get_vertex_id(), and pgrouting::graph::UndirectedHasCostBG::graph().
Referenced by crossover_optimize(), tsp(), and tsp().
eval_tour() [2/2]
double anonymous_namespace{tsp.cpp}::eval_tour (TSP_graph & graph, std::deque< std::pair< int64_t, double > > & tsp_tour)
Definition at line 146 of file tsp.cpp.
{
    std::deque<std::pair<int64_t, double>> results;
    auto u = graph.graph().null_vertex();
    double agg_cost(0);
    for (auto &node : tsp_tour) {
        auto v = graph.get_boost_vertex(node.first);
        auto cost = (u == graph.graph().null_vertex()) ?
            0 :
            get_min_cost(u, v, graph);
        u = v;
        node.second = cost;
        agg_cost += cost;
    }
    return agg_cost;
}
References pgrouting::graph::UndirectedHasCostBG::get_boost_vertex(), get_min_cost(), and pgrouting::graph::UndirectedHasCostBG::graph().
get_min_cost()
double anonymous_namespace{tsp.cpp}::get_min_cost (V u, V v, TSP_graph & graph)
Definition at line 92 of file tsp.cpp.
{
    auto the_edge = boost::edge(u, v, graph.graph());
    /*
     * The edge exists, then return the weight it has
     */
    if (the_edge.second) {
        return get(boost::edge_weight, graph.graph())[the_edge.first];
    }
    std::vector<V> predecessors(num_vertices(graph.graph()));
    std::vector<double> distances(num_vertices(graph.graph()), std::numeric_limits<double>::infinity());
    bool found = false;
    CHECK_FOR_INTERRUPTS();
    try {
        boost::dijkstra_shortest_paths(
                graph.graph(), u,
                boost::predecessor_map(&predecessors[0])
                .distance_map(&distances[0])
                .visitor(pgrouting::visitors::dijkstra_one_goal_visitor<V>(v)));
    } catch(pgrouting::found_goals &) {
        found = true;
    }
    if (!found) {
        pgassert(false);
        throw std::make_pair(std::string("INTERNAL: graph is incomplete 1"), std::string("Check graph before calling"));
    }
    double agg_cost(0);
    while (v != u) {
        agg_cost += distances[predecessors[v]];
        v = predecessors[v];
    }
    return agg_cost;
}
References CHECK_FOR_INTERRUPTS, pgrouting::graph::UndirectedHasCostBG::graph(), and pgassert.
Referenced by eval_tour(), and eval_tour().
start_vid_end_vid_are_fixed()
std::deque< std::pair< int64_t, double > > anonymous_namespace{tsp.cpp}::start_vid_end_vid_are_fixed (std::deque< std::pair< int64_t, double > > tsp_path, int64_t start_vid, int64_t end_vid)
Definition at line 57 of file tsp.cpp.
{
    pgassert(tsp_path[0].first == start_vid);
    /*
     * Where is 0?
     */
    auto where = std::find_if(tsp_path.begin(), tsp_path.end(),
            [&](std::pair<int64_t, double>& row){return row.first == 0;});
    /*
     * Move the 0 to be the second value
     * 5,2,1,8,7,10,11,16,6,9,12,17,15,13,14,0,3,4,5
     * to
     * 5 0 3 4 2 1 8 7 10 11 16 6 9 12 17 15 13 14 5
     */
    std::rotate(tsp_path.begin() + 1, where, tsp_path.end() - 1);
    /*
     * delete the 0
     * to
     * 5 3 4 2 1 8 7 10 11 16 6 9 12 17 15 13 14 5
     */
    tsp_path.erase(tsp_path.begin() + 1);
    /*
     * when the second value is not the end_vid, reverse the path
     * - it is the second to last, like the 14 above
     */
    if (tsp_path[0].first != end_vid) std::reverse(tsp_path.begin(), tsp_path.end());
    return tsp_path;
}
References pgassert.
Referenced by do_tsp().
tsp() [1/2]
std::deque< std::pair< int64_t, double > > anonymous_namespace{tsp.cpp}::tsp (TSP_graph & graph)
Definition at line 164 of file tsp.cpp.
                      {
    std::vector<V> tsp_path;
    CHECK_FOR_INTERRUPTS();
    try {
        boost::metric_tsp_approx_tour(
                graph.graph(),
                back_inserter(tsp_path));
    } catch (...) {
        throw std::make_pair(
                std::string("INTERNAL: something went wrong while calling boost::metric_tsp_approx_tour"),
                std::string(__PGR_PRETTY_FUNCTION__));
    }
    return eval_tour(graph, tsp_path);
}
References __PGR_PRETTY_FUNCTION__, CHECK_FOR_INTERRUPTS, eval_tour(), and pgrouting::graph::UndirectedHasCostBG::graph().
Referenced by do_tsp().
tsp() [2/2]
std::deque< std::pair< int64_t, double > > anonymous_namespace{tsp.cpp}::tsp (TSP_graph & graph, int64_t start_vid)
Definition at line 182 of file tsp.cpp.
{
    std::vector<V> tsp_path;
    /*
     * check that the start_vid
     */
    if (!graph.has_vertex(start_vid)) {
        throw std::make_pair(
                std::string("INTERNAL: Verify start_vid before calling"),
                std::string(__PGR_PRETTY_FUNCTION__));
    }
    auto v = graph.get_boost_vertex(start_vid);
    CHECK_FOR_INTERRUPTS();
    try {
    boost::metric_tsp_approx_tour_from_vertex(
            graph.graph(),
            v,
            back_inserter(tsp_path));
    }  catch (...)  {
        throw std::make_pair(
                std::string("INTERNAL: something went wrong while calling boost::metric_tsp_approx_tour_from_vertex"),
                std::string(__PGR_PRETTY_FUNCTION__));
    }
    return eval_tour(graph, tsp_path);
}
References __PGR_PRETTY_FUNCTION__, CHECK_FOR_INTERRUPTS, eval_tour(), pgrouting::graph::UndirectedHasCostBG::get_boost_vertex(), pgrouting::graph::UndirectedHasCostBG::graph(), and pgrouting::graph::UndirectedHasCostBG::has_vertex().