PGROUTING: pgrouting::algorithms Namespace Reference
pgrouting::algorithms Namespace Reference
Namespaces
namespace detail
Functions
Identifiers< int64_t > articulationPoints (pgrouting::UndirectedGraph &graph)
Articulation Points.
template<class G >
std::deque< Path > astar (G &graph, const std::map< int64_t, std::set< int64_t > > &combinations, int heuristic, double factor, double epsilon, bool only_cost)
template<class G >
std::deque< Path > bdastar (G &graph, const std::map< int64_t, std::set< int64_t > > &combinations, int heuristic, double factor, double epsilon, bool only_cost)
std::vector< II_t_rt > biconnectedComponents (pgrouting::UndirectedGraph &graph)
Biconnected Components.
Identifiers< int64_t > bridges (pgrouting::UndirectedGraph &graph)
Bridges Bridges are closely related to the concept of articulation vertices, vertices that belong to every path between some pair of other vertices.
template<class G >
std::deque< Path > dijkstra (G &graph, const std::map< int64_t, std::set< int64_t > > &combinations, bool only_cost, size_t n_goals=(std::numeric_limits< size_t >::max)())
template<class G >
Path dijkstra (G &graph, int64_t start_vertex, int64_t end_vertex, bool only_cost=false)
std::vector< II_t_rt > pgr_connectedComponents (pgrouting::UndirectedGraph &graph)
works for undirected graph
std::vector< II_t_rt > strongComponents (pgrouting::DirectedGraph &graph)
Strongly Connected Components Vertex Version.
template<class G >
std::deque< Path > Yen (G &graph, const std::map< int64_t, std::set< int64_t > > &combinations, size_t k, bool heap_paths)
Function Documentation
articulationPoints()
Identifiers< int64_t > pgrouting::algorithms::articulationPoints (pgrouting::UndirectedGraph & graph)
Articulation Points.
Definition at line 128 of file components.cpp.
{
    using G = pgrouting::UndirectedGraph;
    using V =  G::V;
    /* abort in case of an interruption occurs (e.g. the query is being cancelled) */
    CHECK_FOR_INTERRUPTS();
    // perform the algorithm
    std::vector<V> art_points;
    try {
        boost::articulation_points(graph.graph, std::back_inserter(art_points));
    } catch (...) {
        throw;
    }
    // get the results
    Identifiers<int64_t> results;
    for (const auto v : art_points) {
        results += graph[v].id;
    }
    return results;
}
References CHECK_FOR_INTERRUPTS, and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph.
Referenced by pgr_do_articulationPoints().
astar()
template<class G > std::deque< Path > pgrouting::algorithms::astar (G & graph, const std::map< int64_t, std::set< int64_t > > & combinations, int heuristic, double factor, double epsilon, bool only_cost) private
Definition at line 170 of file astar.hpp.
{
    typedef typename G::V V;
    std::deque<Path> paths;
    for (const auto &c : combinations) {
        if (!graph.has_vertex(c.first)) continue;
        std::vector<V> predecessors(graph.num_vertices());
        std::vector<double> distances(graph.num_vertices());
        auto departure(graph.get_V(c.first));
        std::set<V> destinations;
        for (const auto &vertex : c.second) {
            if (graph.has_vertex(vertex)) {
                destinations.insert(graph.get_V(vertex));
            }
        }
        detail::astar_1_to_many(graph, predecessors, distances, departure, destinations, heuristic, factor, epsilon);
        auto r_paths = detail::get_paths(graph, predecessors, distances, departure, destinations, only_cost);
        std::stable_sort(r_paths.begin(), r_paths.end(),
                [](const Path &e1, const Path &e2)->bool {
                return e1.end_id() < e2.end_id();
                });
        paths.insert(paths.end(), r_paths.begin(), r_paths.end());
    }
    return paths;
}
References detail::astar_1_to_many(), and detail::get_paths().
Referenced by pgr_do_astar().
bdastar()
template<class G > std::deque< Path > pgrouting::algorithms::bdastar (G & graph, const std::map< int64_t, std::set< int64_t > > & combinations, int heuristic, double factor, double epsilon, bool only_cost) private
Definition at line 197 of file bdAstar.hpp.
{
    std::deque<Path> paths;
    pgrouting::bidirectional::Pgr_bdAstar<G> fn_bdAstar(graph);
    for (const auto &c : combinations) {
        if (!graph.has_vertex(c.first)) continue;
        for (const auto &destination : c.second) {
            if (!graph.has_vertex(destination)) continue;
            fn_bdAstar.clear();
            paths.push_back(fn_bdAstar.pgr_bdAstar(
                        graph.get_V(c.first), graph.get_V(destination),
                        heuristic, factor, epsilon, only_cost));
        }
    }
    return paths;
}
References pgrouting::bidirectional::Pgr_bidirectional< G >::clear(), and pgrouting::bidirectional::Pgr_bdAstar< G >::pgr_bdAstar().
Referenced by pgr_do_bdAstar().
biconnectedComponents()
std::vector< II_t_rt > pgrouting::algorithms::biconnectedComponents (pgrouting::UndirectedGraph & graph)
Biconnected Components.
Biconnected Components (for undirected)
Definition at line 102 of file components.cpp.
{
    using G = pgrouting::UndirectedGraph;
    using E = G::E;
    using Edge_map = std::map< E, size_t >;
    // perform the algorithm
    Edge_map bicmp_map;
    boost::associative_property_map<Edge_map> bimap(bicmp_map);
    size_t num_comps;
    try {
        // NOLINTNEXTLINE(clang-analyzer-cplusplus.NewDelete)
        num_comps = biconnected_components(graph.graph, bimap);
    } catch (...) {
        throw;
    }
    std::vector< std::vector< int64_t > > results(num_comps);
    for (auto ed : boost::make_iterator_range(edges(graph.graph))) {
        results[bimap[ed]].push_back(graph[ed].id);
    }
    return detail::componentsResult(results);
}
References pgrouting::algorithms::detail::componentsResult(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph.
Referenced by pgr_do_biconnectedComponents().
bridges()
Identifiers< int64_t > pgrouting::algorithms::bridges (pgrouting::UndirectedGraph & graph)
Bridges Bridges are closely related to the concept of articulation vertices, vertices that belong to every path between some pair of other vertices.
Bridges.
The two endpoints of a bridge are articulation vertices unless they have a degree of 1, although it may also be possible for a non-bridge edge to have two articulation vertices as endpoints.
Analogously to bridgeless graphs being 2-edge-connected, graphs without articulation vertices are 2-vertex-connected.
Definition at line 164 of file components.cpp.
{
    using G = pgrouting::UndirectedGraph;
    using V = G::V;
    using EO_i = G::EO_i;
    Identifiers<int64_t> bridge_edges;
    Identifiers<int64_t> processed_edges;
    std::vector<V> components(num_vertices(graph.graph));
    size_t ini_comps;
    /* abort in case of an interruption occurs (e.g. the query is being cancelled) */
    CHECK_FOR_INTERRUPTS();
    try {
        ini_comps = boost::connected_components(graph.graph, &components[0]);
    } catch (...) {
        throw;
    }
    /* abort in case of an interruption occurs (e.g. the query is being cancelled) */
    CHECK_FOR_INTERRUPTS();
    std::vector<V> art_points;
    try {
        boost::articulation_points(graph.graph, std::back_inserter(art_points));
    } catch (...) {
        throw;
    }
    for (auto v : boost::make_iterator_range(vertices(graph.graph))) {
        if (graph.out_degree(v) == 1) {
            art_points.push_back(v);
        }
    }
    for (const auto u : art_points) {
        for (const auto v : art_points) {
            /*
             * skip when the vertices are the same and do half the work
             */
            if (u < v) continue;
            auto p = boost::edge(u, v, graph.graph);
            /*
             * skip when there is no edge (u, v) on the graph
             */
            if (!p.second) continue;
            auto edge = p.first;
            auto id = graph[edge].id;
            /*
             * Skip when the edge has already being processed
             */
            if (processed_edges.has(id)) continue;
            /*
             * Processing edge
             */
            processed_edges += id;
            /*
             * At least one edge between articulation points u & v
             */
            int parallel_count = 0;
            EO_i ei, ei_end;
            boost::tie(ei, ei_end) = out_edges(u, graph.graph);
            for ( ; ei != ei_end; ++ei) {
                if (target(*ei, graph.graph) == v) ++parallel_count;
            }
            if (parallel_count == 1) {
                // TODO(vicky) filter graph instead of removing edges
                size_t now_comps;
                try {
                    boost::remove_edge(edge, graph.graph);
                    now_comps = boost::connected_components(graph.graph, &components[0]);
                    boost::add_edge(boost::source(edge, graph.graph),
                            boost::target(edge, graph.graph),
                            graph.graph);
                } catch (...) {
                    throw;
                }
                if (now_comps > ini_comps) {
                    bridge_edges += id;
                }
            }
        }
    }
    return bridge_edges;
}
References CHECK_FOR_INTERRUPTS, pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph, pgrouting::Identifiers< T >::has(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::out_degree().
Referenced by pgr_do_bridges().
dijkstra() [1/2]
template<class G > std::deque< Path > pgrouting::algorithms::dijkstra (G & graph, const std::map< int64_t, std::set< int64_t > > & combinations, bool only_cost, size_t n_goals = (std::numeric_limits<size_t>::max)())
Definition at line 157 of file dijkstra.hpp.
{
    std::deque<Path> paths;
    for (const auto &c : combinations) {
        auto r_paths = detail::dijkstra<G>(graph, c.first, c.second, only_cost, n_goals);
        paths.insert(paths.begin(), r_paths.begin(), r_paths.end());
    }
    return paths;
}
Referenced by dijkstra(), pgrouting::dijkstraVia(), do_shortestPath(), pgrouting::yen::Pgr_ksp< G >::doNextCycle(), pgrouting::yen::Pgr_ksp< G >::getFirstSolution(), anonymous_namespace{withPoints_driver.cpp}::pgr_dijkstra(), anonymous_namespace{trsp_driver.cpp}::pgr_dijkstra(), pgr_do_dijkstra(), and pgr_do_trsp_withPoints().
dijkstra() [2/2]
template<class G > Path pgrouting::algorithms::dijkstra (G & graph, int64_t start_vertex, int64_t end_vertex, bool only_cost = false)
Definition at line 174 of file dijkstra.hpp.
{
    typedef typename G::V V;
    std::vector<V> predecessors(graph.num_vertices());
    std::vector<double> distances(graph.num_vertices(), std::numeric_limits<double>::infinity());
    std::map<int64_t, std::set<int64_t>> combinations;
    combinations[start_vertex].insert(end_vertex);
    auto paths = dijkstra(graph, combinations, only_cost);
    return paths.front();
}
References dijkstra().
pgr_connectedComponents()
std::vector< II_t_rt > pgrouting::algorithms::pgr_connectedComponents (pgrouting::UndirectedGraph & graph)
works for undirected graph
Definition at line 48 of file components.cpp.
{
    typedef pgrouting::UndirectedGraph::V V;
    // perform the algorithm
    std::vector<V> components(num_vertices(graph.graph));
    size_t num_comps;
    /* abort in case of an interruption occurs (e.g. the query is being cancelled) */
    CHECK_FOR_INTERRUPTS();
    try {
        num_comps = boost::connected_components(graph.graph, &components[0]);
    } catch (...) {
        throw;
    }
    // get the results
    std::vector< std::vector< int64_t > > results(num_comps);
    for (auto vd : boost::make_iterator_range(vertices(graph.graph))) {
        results[components[vd]].push_back(graph[vd].id);
    }
    return detail::componentsResult(results);
}
References CHECK_FOR_INTERRUPTS, pgrouting::algorithms::detail::componentsResult(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph.
Referenced by pgr_do_connectedComponents().
strongComponents()
std::vector< II_t_rt > pgrouting::algorithms::strongComponents (pgrouting::DirectedGraph & graph)
Strongly Connected Components Vertex Version.
Definition at line 72 of file components.cpp.
{
    typedef pgrouting::UndirectedGraph::V V;
    // perform the algorithm
    std::vector<V> components(num_vertices(graph.graph));
    size_t num_comps;
    /* abort in case of an interruption occurs (e.g. the query is being cancelled) */
    CHECK_FOR_INTERRUPTS();
    try {
        num_comps = boost::strong_components(
                graph.graph,
                boost::make_iterator_property_map(components.begin(),
                    get(boost::vertex_index, graph.graph)));
    } catch (...) {
        throw;
    }
    // get the results
    std::vector< std::vector< int64_t > > results(num_comps);
    for (auto vd : boost::make_iterator_range(vertices(graph.graph))) {
        results[components[vd]].push_back(graph[vd].id);
    }
    return detail::componentsResult(results);
}
References CHECK_FOR_INTERRUPTS, pgrouting::algorithms::detail::componentsResult(), and pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::graph.
Referenced by pgr_do_strongComponents().
Yen()
template<class G > std::deque< Path > pgrouting::algorithms::Yen (G & graph, const std::map< int64_t, std::set< int64_t > > & combinations, size_t k, bool heap_paths)
Definition at line 251 of file ksp.hpp.
{
        std::deque<Path> paths;
        pgrouting::yen::Pgr_ksp<G> fn_yen;
        for (const auto &c : combinations) {
            if (!graph.has_vertex(c.first)) continue;
            for (const auto &destination : c.second) {
                if (!graph.has_vertex(destination)) continue;
                fn_yen.clear();
                auto result_path = fn_yen.Yen(graph, c.first, destination, k, heap_paths);
                paths.insert(paths.end(), result_path.begin(), result_path.end());
            }
        }
        return paths;
    }
References pgrouting::yen::Pgr_ksp< G >::clear(), and pgrouting::yen::Pgr_ksp< G >::Yen().
Referenced by pgr_do_ksp(), and pgr_do_withPointsKsp().