PGROUTING: pgrouting::pgget Namespace Reference
pgrouting::pgget Namespace Reference
Functions
Edge_bool_t fetch_basic_edge (const HeapTuple tuple, const TupleDesc &tupdesc, const std::vector< Column_info_t > &info, int64_t *default_id, size_t *valid_edges, bool)
II_t_rt fetch_combination (const HeapTuple tuple, const TupleDesc &tupdesc, const std::vector< Column_info_t > &info, int64_t *, size_t *, bool)
Coordinate_t fetch_coordinate (const HeapTuple tuple, const TupleDesc &tupdesc, const std::vector< Column_info_t > &info, int64_t *default_id, size_t *, bool)
CostFlow_t fetch_costFlow_edge (const HeapTuple tuple, const TupleDesc &tupdesc, const std::vector< Column_info_t > &info, int64_t *default_id, size_t *valid_edges, bool normal)
Delauny_t fetch_delauny (const HeapTuple tuple, const TupleDesc &tupdesc, const std::vector< Column_info_t > &info, int64_t *, size_t *, bool)
Edge_t fetch_edge (const HeapTuple tuple, const TupleDesc &tupdesc, const std::vector< Column_info_t > &info, int64_t *default_id, size_t *valid_edges, bool normal)
Edge_xy_t fetch_edge_xy (const HeapTuple tuple, const TupleDesc &tupdesc, const std::vector< Column_info_t > &info, int64_t *default_id, size_t *valid_edges, bool normal)
Orders_t fetch_orders (const HeapTuple tuple, const TupleDesc &tupdesc, const std::vector< Column_info_t > &info, int64_t *, size_t *, bool with_id)
Point_on_edge_t fetch_point (const HeapTuple tuple, const TupleDesc &tupdesc, const std::vector< Column_info_t > &info, int64_t *default_pid, size_t *, bool)
Restriction_t fetch_restriction (const HeapTuple tuple, const TupleDesc &tupdesc, const std::vector< Column_info_t > &info, int64_t *, size_t *, bool)
Vehicle_t fetch_vehicle (const HeapTuple tuple, const TupleDesc &tupdesc, const std::vector< Column_info_t > &info, int64_t *, size_t *, bool with_id)
std::vector< Edge_bool_t > get_basic_edges (const std::string &sql)
For queries of the type:
std::vector< II_t_rt > get_combinations (const std::string &sql)
For queries of the type:
std::vector< Coordinate_t > get_coordinates (const std::string &)
Read rows of matrix.
std::vector< CostFlow_t > get_costFlow_edges (const std::string &sql)
For queries of the type:
template<typename Data_type , typename Func >
std::vector< Data_type > get_data (const std::string &sql, bool flag, std::vector< Column_info_t > info, Func func)
Retrieves the tuples.
std::vector< Delauny_t > get_delauny (const std::string &)
Read rows of delauny triangles.
std::vector< Edge_t > get_edges (const std::string &sql, bool normal, bool ignore_id)
For queries of the type:
std::vector< Edge_xy_t > get_edges_xy (const std::string &sql, bool normal)
For queries of the type:
std::vector< Edge_t > get_flow_edges (const std::string &sql)
For queries of the type:
std::vector< int64_t > get_intArray (ArrayType *, bool)
Enforces the input array to be NOT empty.
std::set< int64_t > get_intSet (ArrayType *)
Reads a postgres array saving it as set.
std::vector< IID_t_rt > get_matrixRows (const std::string &sql)
For queries of the type:
std::vector< Orders_t > get_orders (const std::string &sql, bool with_id)
For queries of the type:
std::vector< Point_on_edge_t > get_points (const std::string &sql)
For queries of the type:
std::vector< Restriction_t > get_restrictions (const std::string &sql)
For queries of the type:
std::vector< Vehicle_t > get_vehicles (const std::string &sql, bool with_id)
For queries of the type:
IID_t_rt pgr_fetch_row (const HeapTuple tuple, const TupleDesc &tupdesc, const std::vector< Column_info_t > &info, int64_t *, size_t *, bool)
Function Documentation
fetch_basic_edge()
Edge_bool_t pgrouting::pgget::fetch_basic_edge (const HeapTuple tuple, const TupleDesc & tupdesc, const std::vector< Column_info_t > & info, int64_t * default_id, size_t * valid_edges, bool)
Definition at line 113 of file pgdata_fetchers.cpp.
              {
    Edge_bool_t edge;
    if (column_found(info[0].colNumber)) {
        edge.id = getBigInt(tuple, tupdesc, info[0]);
    } else {
        edge.id = *default_id;
        ++(*default_id);
    }
    bool new_columns = column_found(info[5].colNumber);
    edge.source = getBigInt(tuple, tupdesc, info[1]);
    edge.target = getBigInt(tuple, tupdesc, info[2]);
    if (new_columns) {
        edge.going = getFloat8(tuple, tupdesc, info[5]) > 0
            || (column_found(info[6].colNumber)
                    && getFloat8(tuple, tupdesc, info[6]) > 0);
    } else {
        edge.going = getFloat8(tuple, tupdesc, info[3]) > 0
            || (column_found(info[4].colNumber)
                    && getFloat8(tuple, tupdesc, info[4]) > 0);
    }
    (*valid_edges)++;
    return edge;
}
References pgrouting::column_found(), pgrouting::getBigInt(), pgrouting::getFloat8(), Edge_bool_t::going, Edge_bool_t::id, Edge_bool_t::source, and Edge_bool_t::target.
Referenced by get_basic_edges().
fetch_combination()
II_t_rt pgrouting::pgget::fetch_combination (const HeapTuple tuple, const TupleDesc & tupdesc, const std::vector< Column_info_t > & info, int64_t * , size_t * , bool)
Definition at line 64 of file pgdata_fetchers.cpp.
              {
    II_t_rt combination;
    combination.d1.source = getBigInt(tuple, tupdesc, info[0]);
    combination.d2.target = getBigInt(tuple, tupdesc, info[1]);
    return combination;
}
References II_t_rt::d1, II_t_rt::d2, pgrouting::getBigInt(), II_t_rt::source, and II_t_rt::target.
Referenced by get_combinations().
fetch_coordinate()
Coordinate_t pgrouting::pgget::fetch_coordinate (const HeapTuple tuple, const TupleDesc & tupdesc, const std::vector< Column_info_t > & info, int64_t * default_id, size_t * , bool)
Definition at line 77 of file pgdata_fetchers.cpp.
              {
    Coordinate_t coordinate;
    if (column_found(info[0].colNumber)) {
        coordinate.id = getBigInt(tuple, tupdesc, info[0]);
    } else {
        coordinate.id = *default_id;
        ++(*default_id);
    }
    coordinate.x = getFloat8(tuple, tupdesc, info[1]);
    coordinate.y = getFloat8(tuple, tupdesc, info[2]);
    return coordinate;
}
References pgrouting::column_found(), pgrouting::getBigInt(), pgrouting::getFloat8(), Coordinate_t::id, Coordinate_t::x, and Coordinate_t::y.
Referenced by get_coordinates().
fetch_costFlow_edge()
CostFlow_t pgrouting::pgget::fetch_costFlow_edge (const HeapTuple tuple, const TupleDesc & tupdesc, const std::vector< Column_info_t > & info, int64_t * default_id, size_t * valid_edges, bool normal)
Definition at line 190 of file pgdata_fetchers.cpp.
                     {
    CostFlow_t edge;
    if (column_found(info[0].colNumber)) {
        edge.edge_id = getBigInt(tuple, tupdesc, info[0]);
    } else {
        edge.edge_id = *default_id;
        ++(*default_id);
    }
    if (normal) {
        edge.source = getBigInt(tuple, tupdesc,  info[1]);
        edge.target = getBigInt(tuple, tupdesc, info[2]);
    } else {
        edge.target = getBigInt(tuple, tupdesc,  info[1]);
        edge.source = getBigInt(tuple, tupdesc, info[2]);
    }
    edge.capacity = getBigInt(tuple, tupdesc, info[3]);
    if (column_found(info[4].colNumber)) {
        edge.reverse_capacity = getBigInt(tuple, tupdesc, info[4]);
    } else {
        edge.reverse_capacity = -1;
    }
    edge.cost = getFloat8(tuple, tupdesc, info[5]);
    if (column_found(info[6].colNumber)) {
        edge.reverse_cost = getFloat8(tuple, tupdesc, info[6]);
    } else {
        edge.reverse_cost = 0;
    }
    *valid_edges = edge.capacity < 0? *valid_edges: *valid_edges + 1;
    *valid_edges = edge.reverse_capacity < 0? *valid_edges: *valid_edges + 1;
    return edge;
}
References CostFlow_t::capacity, pgrouting::column_found(), CostFlow_t::cost, CostFlow_t::edge_id, pgrouting::getBigInt(), pgrouting::getFloat8(), CostFlow_t::reverse_capacity, CostFlow_t::reverse_cost, CostFlow_t::source, and CostFlow_t::target.
Referenced by get_costFlow_edges().
fetch_delauny()
Delauny_t pgrouting::pgget::fetch_delauny (const HeapTuple tuple, const TupleDesc & tupdesc, const std::vector< Column_info_t > & info, int64_t * , size_t * , bool)
Definition at line 96 of file pgdata_fetchers.cpp.
              {
    Delauny_t delauny;
    delauny.tid = getBigInt(tuple, tupdesc, info[0]);
    delauny.pid = getBigInt(tuple, tupdesc, info[1]);
    delauny.x = getFloat8(tuple, tupdesc, info[2]);
    delauny.y = getFloat8(tuple, tupdesc, info[3]);
    return delauny;
}
References pgrouting::getBigInt(), pgrouting::getFloat8(), Delauny_t::pid, Delauny_t::tid, Delauny_t::x, and Delauny_t::y.
Referenced by get_delauny().
fetch_edge()
Edge_t pgrouting::pgget::fetch_edge (const HeapTuple tuple, const TupleDesc & tupdesc, const std::vector< Column_info_t > & info, int64_t * default_id, size_t * valid_edges, bool normal)
Definition at line 146 of file pgdata_fetchers.cpp.
                     {
    Edge_t edge;
    if (column_found(info[0].colNumber)) {
        edge.id = getBigInt(tuple, tupdesc, info[0]);
    } else {
        edge.id = *default_id;
        ++(*default_id);
    }
    if (normal) {
        edge.source = getBigInt(tuple, tupdesc,  info[1]);
        edge.target = getBigInt(tuple, tupdesc, info[2]);
    } else {
        edge.target = getBigInt(tuple, tupdesc,  info[1]);
        edge.source = getBigInt(tuple, tupdesc, info[2]);
    }
    edge.cost = getFloat8(tuple, tupdesc, info[3]);
    if (column_found(info[4].colNumber)) {
        edge.reverse_cost = getFloat8(tuple, tupdesc, info[4]);
    } else {
        edge.reverse_cost = -1;
    }
    edge.cost = std::isinf(edge.cost)?
        std::numeric_limits<double>::max() : edge.cost;
    edge.reverse_cost = std::isinf(edge.reverse_cost)?
        std::numeric_limits<double>::max() : edge.reverse_cost;
    *valid_edges = edge.cost < 0? *valid_edges: *valid_edges + 1;
    *valid_edges = edge.reverse_cost < 0? *valid_edges: *valid_edges + 1;
    return edge;
}
References pgrouting::column_found(), Edge_t::cost, pgrouting::getBigInt(), pgrouting::getFloat8(), Edge_t::id, Edge_t::reverse_cost, Edge_t::source, and Edge_t::target.
Referenced by get_edges(), and get_flow_edges().
fetch_edge_xy()
Edge_xy_t pgrouting::pgget::fetch_edge_xy (const HeapTuple tuple, const TupleDesc & tupdesc, const std::vector< Column_info_t > & info, int64_t * default_id, size_t * valid_edges, bool normal)
Definition at line 232 of file pgdata_fetchers.cpp.
                     {
    Edge_xy_t edge;
    if (column_found(info[0].colNumber)) {
        edge.id = getBigInt(tuple, tupdesc, info[0]);
    } else {
        edge.id = *default_id;
        ++(*default_id);
    }
    if (normal) {
        edge.source = getBigInt(tuple, tupdesc,  info[1]);
        edge.target = getBigInt(tuple, tupdesc, info[2]);
    } else {
        edge.target = getBigInt(tuple, tupdesc,  info[1]);
        edge.source = getBigInt(tuple, tupdesc, info[2]);
    }
    edge.cost = getFloat8(tuple, tupdesc, info[3]);
    if (column_found(info[4].colNumber)) {
        edge.reverse_cost = getFloat8(tuple, tupdesc, info[4]);
    } else {
        edge.reverse_cost = -1;
    }
    edge.x1 = getFloat8(tuple, tupdesc, info[5]);
    edge.y1 = getFloat8(tuple, tupdesc, info[6]);
    edge.x2 = getFloat8(tuple, tupdesc, info[7]);
    edge.y2 = getFloat8(tuple, tupdesc, info[8]);
    *valid_edges = edge.cost < 0? *valid_edges: *valid_edges + 1;
    *valid_edges = edge.reverse_cost < 0? *valid_edges: *valid_edges + 1;
    return edge;
}
References pgrouting::column_found(), Edge_xy_t::cost, pgrouting::getBigInt(), pgrouting::getFloat8(), Edge_xy_t::id, Edge_xy_t::reverse_cost, Edge_xy_t::source, Edge_xy_t::target, Edge_xy_t::x1, Edge_xy_t::x2, Edge_xy_t::y1, and Edge_xy_t::y2.
Referenced by get_edges_xy().
fetch_orders()
Orders_t pgrouting::pgget::fetch_orders (const HeapTuple tuple, const TupleDesc & tupdesc, const std::vector< Column_info_t > & info, int64_t * , size_t * , bool with_id)
Definition at line 287 of file pgdata_fetchers.cpp.
                      {
    Orders_t pd_order;
    pd_order.id = getBigInt(tuple, tupdesc, info[0]);
    pd_order.demand = getFloat8(tuple, tupdesc, info[1]);
    /*
     * the pickups
     */
    pd_order.pick_x = with_id ?
        0 : getFloat8(tuple, tupdesc, info[2]);
    pd_order.pick_y =  with_id ?
        0 : getFloat8(tuple, tupdesc, info[3]);
    pd_order.pick_open_t = getFloat8(tuple, tupdesc, info[4]);
    pd_order.pick_close_t = getFloat8(tuple, tupdesc, info[5]);
    pd_order.pick_service_t = column_found(info[6].colNumber) ?
        getFloat8(tuple, tupdesc, info[6]) : 0;
    /*
     * the deliveries
     */
    pd_order.deliver_x =  with_id ?
        0 : getFloat8(tuple, tupdesc, info[7]);
    pd_order.deliver_y =  with_id ?
        0 : getFloat8(tuple, tupdesc, info[8]);
    pd_order.deliver_open_t = getFloat8(tuple, tupdesc, info[9]);
    pd_order.deliver_close_t = getFloat8(tuple, tupdesc, info[10]);
    pd_order.deliver_service_t = column_found(info[11].colNumber) ?
        getFloat8(tuple, tupdesc, info[11]) : 0;
    pd_order.pick_node_id = with_id ?
        getBigInt(tuple, tupdesc, info[12]) : 0;
    pd_order.deliver_node_id = with_id ?
        getBigInt(tuple, tupdesc, info[13]) : 0;
    return pd_order;
}
References pgrouting::column_found(), Orders_t::deliver_close_t, Orders_t::deliver_node_id, Orders_t::deliver_open_t, Orders_t::deliver_service_t, Orders_t::deliver_x, Orders_t::deliver_y, Orders_t::demand, pgrouting::getBigInt(), pgrouting::getFloat8(), Orders_t::id, Orders_t::pick_close_t, Orders_t::pick_node_id, Orders_t::pick_open_t, Orders_t::pick_service_t, Orders_t::pick_x, and Orders_t::pick_y.
Referenced by get_orders().
fetch_point()
Point_on_edge_t pgrouting::pgget::fetch_point (const HeapTuple tuple, const TupleDesc & tupdesc, const std::vector< Column_info_t > & info, int64_t * default_pid, size_t * , bool)
Definition at line 347 of file pgdata_fetchers.cpp.
              {
    Point_on_edge_t point = {};
    if (column_found(info[0].colNumber)) {
        point.pid = getBigInt(tuple, tupdesc, info[0]);
    } else {
        ++(*default_pid);
        point.pid = *default_pid;
    }
    point.edge_id = getBigInt(tuple, tupdesc, info[1]);
    point.fraction = getFloat8(tuple, tupdesc, info[2]);
    if (column_found(info[3].colNumber)) {
        point.side = getChar(tuple, tupdesc, info[3], false, 'b');
    } else {
        point.side = 'b';
    }
    return point;
}
References pgrouting::column_found(), Point_on_edge_t::edge_id, Point_on_edge_t::fraction, pgrouting::getBigInt(), pgrouting::getChar(), pgrouting::getFloat8(), Point_on_edge_t::pid, and Point_on_edge_t::side.
Referenced by get_points().
fetch_restriction()
Restriction_t pgrouting::pgget::fetch_restriction (const HeapTuple tuple, const TupleDesc & tupdesc, const std::vector< Column_info_t > & info, int64_t * , size_t * , bool)
Definition at line 330 of file pgdata_fetchers.cpp.
              {
    Restriction_t restriction;
    restriction.cost = getFloat8(tuple, tupdesc, info[0]);
    restriction.via = NULL;
    restriction.via_size = 0;
    restriction.via = getBigIntArr(tuple, tupdesc, info[1], &restriction.via_size);
    return restriction;
}
References Restriction_t::cost, pgrouting::getBigIntArr(), pgrouting::getFloat8(), Restriction_t::via, and Restriction_t::via_size.
Referenced by get_restrictions().
fetch_vehicle()
Vehicle_t pgrouting::pgget::fetch_vehicle (const HeapTuple tuple, const TupleDesc & tupdesc, const std::vector< Column_info_t > & info, int64_t * , size_t * , bool with_id)
Definition at line 373 of file pgdata_fetchers.cpp.
                      {
    Vehicle_t vehicle;
    vehicle.id = getBigInt(tuple, tupdesc, info[0]);
    vehicle.capacity = getFloat8(tuple, tupdesc, info[1]);
    vehicle.start_x = with_id ?
        0 :
        getFloat8(tuple, tupdesc, info[2]);
    vehicle.start_y = with_id ?
        0 :
        getFloat8(tuple, tupdesc, info[3]);
    vehicle.speed = column_found(info[13].colNumber) ?
        getFloat8(tuple, tupdesc, info[13]) :
        1;
    vehicle.cant_v =  column_found(info[4].colNumber) ?
        getBigInt(tuple, tupdesc, info[4]) :
        1;
    vehicle.start_open_t = column_found(info[5].colNumber) ?
        getFloat8(tuple, tupdesc, info[5]) :
        0;
    vehicle.start_close_t = column_found(info[6].colNumber) ?
        getFloat8(tuple, tupdesc, info[6]) :
        std::numeric_limits<double>::max();
    vehicle.start_service_t = column_found(info[7].colNumber) ?
        getFloat8(tuple, tupdesc, info[7]) :
        0;
    if (!(column_found(info[8].colNumber))
            && column_found(info[9].colNumber)) {
        ereport(ERROR,
                (errmsg("Column \'%s\' not Found", info[8].name.c_str()),
                 errhint("%s was found, also column is expected %s ",
                     info[9].name.c_str(), info[8].name.c_str())));
    }
    if (column_found(info[8].colNumber)
            && !(column_found(info[9].colNumber))) {
        ereport(ERROR,
                (errmsg("Column \'%s\' not Found", info[9].name.c_str()),
                 errhint("%s was found, also column is expected %s ",
                     info[8].name.c_str(), info[9].name.c_str())));
    }
    vehicle.end_x = column_found(info[8].colNumber) ?
        getFloat8(tuple, tupdesc, info[8]) :
        vehicle.start_x;
    vehicle.end_y = column_found(info[9].colNumber) ?
        getFloat8(tuple, tupdesc, info[9]) :
        vehicle.start_y;
    if (!(column_found(info[10].colNumber))
            && column_found(info[11].colNumber)) {
        ereport(ERROR,
                (errmsg("Column \'%s\' not Found", info[10].name.c_str()),
                 errhint("%s was found, also column is expected %s ",
                     info[10].name.c_str(), info[11].name.c_str())));
    }
    if (column_found(info[10].colNumber)
            && !(column_found(info[11].colNumber))) {
        ereport(ERROR,
                (errmsg("Column \'%s\' not Found", info[11].name.c_str()),
                 errhint("%s was found, also column is expected %s ",
                     info[11].name.c_str(), info[10].name.c_str())));
    }
    vehicle.end_open_t = column_found(info[10].colNumber) ?
        getFloat8(tuple, tupdesc, info[10]) :
        vehicle.start_open_t;
    vehicle.end_close_t = column_found(info[11].colNumber) ?
        getFloat8(tuple, tupdesc, info[11]) :
        vehicle.start_close_t;
    vehicle.end_service_t = column_found(info[12].colNumber) ?
        getFloat8(tuple, tupdesc, info[12]) :
        vehicle.start_service_t;
    vehicle.speed = column_found(info[13].colNumber) ?
        getFloat8(tuple, tupdesc, info[13]) :
        1;
    vehicle.start_node_id = with_id ?
        getBigInt(tuple, tupdesc, info[14]) :
        0;
    vehicle.end_node_id = with_id ?
        (column_found(info[12].colNumber) ?
         getBigInt(tuple, tupdesc, info[15]) :
         vehicle.start_node_id) :
        0;
    return vehicle;
}
References Vehicle_t::cant_v, Vehicle_t::capacity, pgrouting::column_found(), Vehicle_t::end_close_t, Vehicle_t::end_node_id, Vehicle_t::end_open_t, Vehicle_t::end_service_t, Vehicle_t::end_x, Vehicle_t::end_y, pgrouting::getBigInt(), pgrouting::getFloat8(), Vehicle_t::id, Vehicle_t::speed, Vehicle_t::start_close_t, Vehicle_t::start_node_id, Vehicle_t::start_open_t, Vehicle_t::start_service_t, Vehicle_t::start_x, and Vehicle_t::start_y.
Referenced by get_vehicles().
get_basic_edges()
std::vector< Edge_bool_t > pgrouting::pgget::get_basic_edges (const std::string & sql)
For queries of the type:
Read basic edges.
SELECT id, source, target, cost, [reverse_cost] FROM edge_table;
For backward compatibility it also accepts:
SELECT id, source, target, going, [coming] FROM edge_table;
Todo:
This option will be removed on V4
Parameters
[in] sql The query
Returns
vector of Edge_bool_t
Definition at line 227 of file pgdata_getters.cpp.
{
    using pgrouting::Column_info_t;
    std::vector<Column_info_t> info{
    {-1, 0, true, "id", ANY_INTEGER},
    {-1, 0, true, "source", ANY_INTEGER},
    {-1, 0, true, "target", ANY_INTEGER},
    {-1, 0, false, "going", ANY_NUMERICAL},
    {-1, 0, false, "coming", ANY_NUMERICAL},
    {-1, 0, false, "cost", ANY_NUMERICAL},
    {-1, 0, false, "reverse_cost", ANY_NUMERICAL}};
    return get_data<Edge_bool_t>(sql, true, info, &fetch_basic_edge);
}
References pgrouting::ANY_INTEGER, pgrouting::ANY_NUMERICAL, and fetch_basic_edge().
Referenced by pgr_do_maximum_cardinality_matching().
get_combinations()
std::vector< II_t_rt > pgrouting::pgget::get_combinations (const std::string & sql)
For queries of the type:
Read rows of combinations.
SELECT source, target FROM combinations;
Parameters
[in] sql The combinations query
Returns
vector of II_t_rt combinations
Definition at line 110 of file pgdata_getters.cpp.
{
    using pgrouting::Column_info_t;
    std::vector<Column_info_t> info{
    {-1, 0, true, "source", ANY_INTEGER},
    {-1, 0, true, "target", ANY_INTEGER}};
    return get_data<II_t_rt>(sql, true, info, &fetch_combination);
}
References pgrouting::ANY_INTEGER, and fetch_combination().
Referenced by pgrouting::utilities::get_combinations(), and pgrouting::utilities::get_combinations().
get_coordinates()
std::vector< Coordinate_t > pgrouting::pgget::get_coordinates (const std::string & sql)
Read rows of matrix.
For queries of the type:
SELECT id, x, y FROM coordinates;
Parameters
[in] sql The coordinates query
Returns
vector of Coordinate_t
Definition at line 129 of file pgdata_getters.cpp.
{
    using pgrouting::Column_info_t;
    std::vector<Column_info_t> info{
    {-1, 0, true, "id", ANY_INTEGER},
    {-1, 0, true, "x", ANY_NUMERICAL},
    {-1, 0, true, "y", ANY_NUMERICAL}};
    return get_data<Coordinate_t>(sql, true, info, &fetch_coordinate);
}
References pgrouting::ANY_INTEGER, pgrouting::ANY_NUMERICAL, and fetch_coordinate().
Referenced by pgr_do_euclideanTSP().
get_costFlow_edges()
std::vector< CostFlow_t > pgrouting::pgget::get_costFlow_edges (const std::string & sql)
For queries of the type:
Read edges for cost.
SELECT id, source, target, capacity, [reverse_capacity], cost, [reverse_cost]
FROM edge_table;
Parameters
[in] sql The query
Returns
vector of CostFlow_t edges
Definition at line 196 of file pgdata_getters.cpp.
{
    using pgrouting::Column_info_t;
    std::vector<Column_info_t> info{
    {-1, 0, true, "id", ANY_INTEGER},
    {-1, 0, true, "source", ANY_INTEGER},
    {-1, 0, true, "target", ANY_INTEGER},
    {-1, 0, true, "capacity", ANY_INTEGER},
    {-1, 0, false, "reverse_capacity", ANY_INTEGER},
    {-1, 0, true, "cost", ANY_NUMERICAL},
    {-1, 0, false, "reverse_cost", ANY_NUMERICAL}};
    return get_data<CostFlow_t>(sql, true, info, &fetch_costFlow_edge);
}
References pgrouting::ANY_INTEGER, pgrouting::ANY_NUMERICAL, and fetch_costFlow_edge().
Referenced by pgr_do_minCostMaxFlow().
get_data()
template<typename Data_type , typename Func > std::vector< Data_type > pgrouting::pgget::get_data (const std::string & sql, bool flag, std::vector< Column_info_t > info, Func func)
Retrieves the tuples.
Template Parameters
Data_type Scructure of data
Func fetcher function
Parameters
[in] sql Query to be processed
[in] flag useful flag depending on data
[in] info information about the data
[in] func fetcher function to be used
Definition at line 116 of file get_data.hpp.
                   {
    const int tuple_limit = 1000000;
    size_t total_tuples;
    size_t valid_pgtuples;
    auto SPIplan = pgr_SPI_prepare(sql.c_str());
    auto SPIportal = pgr_SPI_cursor_open(SPIplan);
    bool moredata = true;
    total_tuples = valid_pgtuples = 0;
    int64_t default_id = 0;
    std::vector<Data_type> tuples;
    while (moredata == true) {
        SPI_cursor_fetch(SPIportal, true, tuple_limit);
        auto tuptable = SPI_tuptable;
        auto tupdesc = SPI_tuptable->tupdesc;
        if (total_tuples == 0) fetch_column_info(tupdesc, info);
        size_t ntuples = SPI_processed;
        total_tuples += ntuples;
        if (ntuples > 0) {
            tuples.reserve(total_tuples);
            for (size_t t = 0; t < ntuples; t++) {
                tuples.push_back(func(tuptable->vals[t], tupdesc, info,
                        &default_id,
                        &valid_pgtuples, flag));
            }
            SPI_freetuptable(tuptable);
        } else {
            moredata = false;
        }
    }
    SPI_cursor_close(SPIportal);
    return tuples;
}
References pgrouting::fetch_column_info(), pgr_SPI_cursor_open(), and pgr_SPI_prepare().
get_delauny()
std::vector< Delauny_t > pgrouting::pgget::get_delauny (const std::string & sql)
Read rows of delauny triangles.
For queries of the type:
SELECT tid, pid, x, y FROM delauny;
SELECT pid, pid, x, y FROM delauny;
Parameters
[in] sql The delauny triangles query
Returns
vector of Delauny_t
Definition at line 151 of file pgdata_getters.cpp.
{
    using pgrouting::Column_info_t;
    std::vector<Column_info_t> info{
    {-1, 0, true, "tid", ANY_INTEGER},
    {-1, 0, true, "pid", ANY_INTEGER},
    {-1, 0, true, "x", ANY_NUMERICAL},
    {-1, 0, true, "y", ANY_NUMERICAL}};
    return get_data<Delauny_t>(sql, true, info, &fetch_delauny);
}
References pgrouting::ANY_INTEGER, pgrouting::ANY_NUMERICAL, and fetch_delauny().
get_edges()
std::vector< Edge_t > pgrouting::pgget::get_edges (const std::string & sql, bool normal, bool ignore_id)
For queries of the type:
Read edges.
SELECT id, source, target, cost, [reverse_cost] FROM edge_table;
Parameters
[in] sql The query
[in] normal when false then the graph is reversed
[in] ignore_id when true id value of edge is ignored
Returns
vector of Edge_t
Definition at line 280 of file pgdata_getters.cpp.
{
    using pgrouting::Column_info_t;
    std::vector<Column_info_t> info{
    {-1, 0, !ignore_id, "id", ANY_INTEGER},
    {-1, 0, true, "source", ANY_INTEGER},
    {-1, 0, true, "target", ANY_INTEGER},
    {-1, 0, true, "cost", ANY_NUMERICAL},
    {-1, 0, false, "reverse_cost", ANY_NUMERICAL}};
    return get_data<Edge_t>(sql, normal, info, &fetch_edge);
}
References pgrouting::ANY_INTEGER, pgrouting::ANY_NUMERICAL, and fetch_edge().
Referenced by do_allpairs(), do_metrics(), do_ordering(), do_shortestPath(), pgr_contractionHierarchies(), pgr_do_articulationPoints(), pgr_do_bdDijkstra(), pgr_do_bellman_ford(), pgr_do_bellman_ford_neg(), pgr_do_betweennessCentrality(), pgr_do_biconnectedComponents(), pgr_do_binaryBreadthFirstSearch(), pgr_do_bipartite(), pgr_do_boyerMyrvold(), pgr_do_breadthFirstSearch(), pgr_do_bridges(), pgr_do_connectedComponents(), pgr_do_contractGraph(), pgr_do_cuthillMckeeOrdering(), pgr_do_dagShortestPath(), pgr_do_depthFirstSearch(), pgr_do_dijkstra(), pgr_do_dijkstraVia(), pgr_do_directedChPP(), pgr_do_drivingDistance(), pgr_do_edge_disjoint_paths(), pgr_do_edgeColoring(), pgr_do_edwardMoore(), pgr_do_hawickCircuits(), pgr_do_isPlanar(), pgr_do_kruskal(), pgr_do_ksp(), pgr_do_lineGraph(), pgr_do_lineGraphFull(), pgr_do_LTDTree(), pgr_do_makeConnected(), pgr_do_prim(), pgr_do_randomSpanningTree(), pgr_do_sequentialVertexColoring(), pgr_do_stoerWagner(), pgr_do_strongComponents(), pgr_do_topologicalSort(), pgr_do_transitiveClosure(), pgr_do_trsp(), pgr_do_trsp_withPoints(), pgr_do_trspVia(), pgr_do_trspVia_withPoints(), pgr_do_turnRestrictedPath(), pgr_do_withPoints(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), and pgr_do_withPointsVia().
get_edges_xy()
std::vector< Edge_xy_t > pgrouting::pgget::get_edges_xy (const std::string & sql, bool normal)
For queries of the type:
Read edges with x, y endpoints.
SELECT id, source, target, cost, [reverse_cost], x1, y1, x2, y2 FROM edge_table;
Parameters
[in] sql The edges query
[in] normal when false then the graph is reversed
Returns
vector of Edge_xy_t
Definition at line 252 of file pgdata_getters.cpp.
{
    using pgrouting::Column_info_t;
    std::vector<Column_info_t> info{
    {-1, 0, true, "id", ANY_INTEGER},
    {-1, 0, true, "source", ANY_INTEGER},
    {-1, 0, true, "target", ANY_INTEGER},
    {-1, 0, true, "cost", ANY_NUMERICAL},
    {-1, 0, false, "reverse_cost", ANY_NUMERICAL},
    {-1, 0, true, "x1", ANY_NUMERICAL},
    {-1, 0, true, "y1", ANY_NUMERICAL},
    {-1, 0, true, "x2", ANY_NUMERICAL},
    {-1, 0, true, "y2", ANY_NUMERICAL}};
    return get_data<Edge_xy_t>(sql, normal, info, &fetch_edge_xy);
}
References pgrouting::ANY_INTEGER, pgrouting::ANY_NUMERICAL, and fetch_edge_xy().
Referenced by pgr_do_astar(), and pgr_do_bdAstar().
get_flow_edges()
std::vector< Edge_t > pgrouting::pgget::get_flow_edges (const std::string & sql)
For queries of the type:
Read edges for flow.
SELECT id, source, target, capacity, [reverse_capacity] FROM edge_table;
Parameters
[in] sql The flow edges query
Returns
vector of Edge_t
Definition at line 173 of file pgdata_getters.cpp.
{
    using pgrouting::Column_info_t;
    std::vector<Column_info_t> info{
    {-1, 0, true, "id", ANY_INTEGER},
    {-1, 0, true, "source", ANY_INTEGER},
    {-1, 0, true, "target", ANY_INTEGER},
    {-1, 0, true, "capacity", ANY_INTEGER},
    {-1, 0, false, "reverse_capacity", ANY_INTEGER}};
    return get_data<Edge_t>(sql, true, info, &fetch_edge);
}
References pgrouting::ANY_INTEGER, and fetch_edge().
Referenced by pgr_do_max_flow().
get_intArray()
std::vector< int64_t > pgrouting::pgget::get_intArray (ArrayType * input, bool allow_empty)
Enforces the input array to be NOT empty.
Parameters
[in] input the postgres array
[in] allow_empty when true, empty arrays are accepted.
Returns
Returns a vector of int64_t
Definition at line 85 of file pgdata_getters.cpp.
{
    return pgrouting::get_pgarray(input, allow_empty);
}
References pgrouting::get_pgarray().
Referenced by pgr_contractionHierarchies(), pgr_do_contractGraph(), pgr_do_depthFirstSearch(), pgr_do_dijkstraVia(), pgr_do_kruskal(), pgr_do_prim(), pgr_do_trspVia(), pgr_do_trspVia_withPoints(), and pgr_do_withPointsVia().
get_intSet()
std::set< int64_t > pgrouting::pgget::get_intSet (ArrayType * arr)
Reads a postgres array saving it as set.
Parameters
[in] arr 1 dimension postgres array
Returns
Returns a set of int64_t
Can be empty set.
Definition at line 95 of file pgdata_getters.cpp.
{
    return pgrouting::get_pgset(arr);
}
References pgrouting::get_pgset().
Referenced by pgrouting::utilities::get_combinations(), pgrouting::utilities::get_combinations(), pgr_do_breadthFirstSearch(), pgr_do_drivingDistance(), and pgr_do_withPointsDD().
get_matrixRows()
std::vector< IID_t_rt > pgrouting::pgget::get_matrixRows (const std::string & sql)
For queries of the type:
Read rows of matrix.
SELECT start_vid, end_vid, agg_cost FROM matrix_data;
Parameters
[in] sql The matrix
Returns
vector of IID_t_rt
Definition at line 303 of file pgdata_getters.cpp.
{
    using pgrouting::Column_info_t;
    std::vector<Column_info_t> info{
    {-1, 0, true, "start_vid", ANY_INTEGER},
    {-1, 0, true, "end_vid", ANY_INTEGER},
    {-1, 0, true, "agg_cost", ANY_NUMERICAL}};
    return get_data<IID_t_rt>(sql, true, info, &pgr_fetch_row);
}
References pgrouting::ANY_INTEGER, pgrouting::ANY_NUMERICAL, and pgr_fetch_row().
Referenced by pgr_do_pickDeliver(), and pgr_do_tsp().
get_orders()
std::vector< Orders_t > pgrouting::pgget::get_orders (const std::string & sql, bool with_id)
For queries of the type:
Reads the pick-Deliver orders.
SELECT id, demand
[p_node_id | p_x, p_y], p_open, p_close, p_service,
[d_node_id | d_x, d_y], d_open, d_close, d_service,
FROM orders;
Parameters
[in] sql The orders query
[in] with_id flag that indicates if id is to be used
Returns
vector of Orders_t
Definition at line 327 of file pgdata_getters.cpp.
          {
    using pgrouting::Column_info_t;
    std::vector<Column_info_t> info{
    {-1, 0, true, "id", ANY_INTEGER},
    {-1, 0, true, "demand", ANY_NUMERICAL},
    {-1, 0, true, "p_x", ANY_NUMERICAL},
    {-1, 0, true, "p_y", ANY_NUMERICAL},
    {-1, 0, true, "p_open", ANY_NUMERICAL},
    {-1, 0, true, "p_close", ANY_NUMERICAL},
    {-1, 0, false, "p_service", ANY_NUMERICAL},
    {-1, 0, true, "d_x", ANY_NUMERICAL},
    {-1, 0, true, "d_y", ANY_NUMERICAL},
    {-1, 0, true, "d_open", ANY_NUMERICAL},
    {-1, 0, true, "d_close", ANY_NUMERICAL},
    {-1, 0, false, "d_service", ANY_NUMERICAL},
    /* nodes are going to be ignored*/
    {-1, 0, false, "p_node_id", ANY_INTEGER},
    {-1, 0, false, "d_node_id", ANY_INTEGER}};
    if (with_id) {
        /* (x,y) values are ignored*/
        info[2].strict = false;
        info[3].strict = false;
        info[7].strict = false;
        info[8].strict = false;
        /* nodes are compulsory*/
        info[12].strict = true;
        info[13].strict = true;
    }
    return get_data<Orders_t>(sql, with_id, info, &fetch_orders);
}
References pgrouting::ANY_INTEGER, pgrouting::ANY_NUMERICAL, fetch_orders(), and pgrouting::Column_info_t::strict.
Referenced by pgr_do_pickDeliver(), and pgr_do_pickDeliverEuclidean().
get_points()
std::vector< Point_on_edge_t > pgrouting::pgget::get_points (const std::string & sql)
For queries of the type:
Read rows of points.
SELECT pid, edge_id, fraction side FROM points;
Parameters
[in] sql The points query
Returns
vector of Point_on_edge_t
Definition at line 373 of file pgdata_getters.cpp.
{
    using pgrouting::Column_info_t;
    std::vector<Column_info_t> info{
    {-1, 0, false, "pid", ANY_INTEGER},
    {-1, 0, true, "edge_id", ANY_INTEGER},
    {-1, 0, true, "fraction", ANY_NUMERICAL},
    {-1, 0, false, "side", pgrouting::CHAR1}};
    return get_data<Point_on_edge_t>(sql, true, info, &fetch_point);
}
References pgrouting::ANY_INTEGER, pgrouting::ANY_NUMERICAL, pgrouting::CHAR1, and fetch_point().
Referenced by do_shortestPath(), pgr_do_trsp_withPoints(), pgr_do_trspVia_withPoints(), pgr_do_withPoints(), pgr_do_withPointsDD(), pgr_do_withPointsKsp(), and pgr_do_withPointsVia().
get_restrictions()
std::vector< Restriction_t > pgrouting::pgget::get_restrictions (const std::string & sql)
For queries of the type:
Read rows of matrix.
SELECT cost, path FROM restrictions;
Parameters
[in] sql The restrictions query
Returns
vector of Restriction_t
Definition at line 395 of file pgdata_getters.cpp.
{
    using pgrouting::Column_info_t;
    std::vector<Column_info_t> info{
    {-1, 0, true, "cost", ANY_NUMERICAL},
    {-1, 0, true, "path", ANY_INTEGER_ARRAY}};
    return get_data<Restriction_t>(sql, true, info, &fetch_restriction);
}
References pgrouting::ANY_INTEGER_ARRAY, pgrouting::ANY_NUMERICAL, and fetch_restriction().
Referenced by pgr_do_trsp(), pgr_do_trsp_withPoints(), pgr_do_trspVia(), pgr_do_trspVia_withPoints(), and pgr_do_turnRestrictedPath().
get_vehicles()
std::vector< Vehicle_t > pgrouting::pgget::get_vehicles (const std::string & sql, bool with_id)
For queries of the type:
Reads the vehicles.
SELECT id, capacity, speed, number
[start_node_id | start_x, start_y], start_open, start_close, start_service,
[end_node_id | end_x, end_y], end_open, end_close, end_service,
FROM orders;
Parameters
[in] sql The vehicles query
[in] with_id flag that indicates if id is to be used
Returns
vector of Vehicle_t
Definition at line 419 of file pgdata_getters.cpp.
{
    using pgrouting::Column_info_t;
    std::vector<Column_info_t> info{
    {-1, 0, true, "id", ANY_INTEGER},
    {-1, 0, true, "capacity", ANY_NUMERICAL},
    {-1, 0, true, "start_x", ANY_NUMERICAL},
    {-1, 0, true, "start_y", ANY_NUMERICAL},
    {-1, 0, false, "number", ANY_INTEGER},
    {-1, 0, false, "start_open", ANY_NUMERICAL},
    {-1, 0, false, "start_close", ANY_NUMERICAL},
    {-1, 0, false, "start_service", ANY_NUMERICAL},
    {-1, 0, false, "end_x", ANY_NUMERICAL},
    {-1, 0, false, "end_y", ANY_NUMERICAL},
    {-1, 0, false, "end_open", ANY_NUMERICAL},
    {-1, 0, false, "end_close", ANY_NUMERICAL},
    {-1, 0, false, "end_service", ANY_NUMERICAL},
    {-1, 0, false, "speed", ANY_NUMERICAL},
    /* nodes are going to be ignored*/
    {-1, 0, false, "start_node_id", ANY_INTEGER},
    {-1, 0, false, "end_node_id", ANY_INTEGER}};
    if (with_id) {
        /* (x,y) values are ignored*/
        info[2].strict = false;
        info[3].strict = false;
        /* start nodes are compulsory*/
        info[14].strict = false;
    }
    return get_data<Vehicle_t>(sql, with_id, info, &fetch_vehicle);
}
References pgrouting::ANY_INTEGER, pgrouting::ANY_NUMERICAL, fetch_vehicle(), and pgrouting::Column_info_t::strict.
Referenced by pgr_do_pickDeliver(), and pgr_do_pickDeliverEuclidean().
pgr_fetch_row()
IID_t_rt pgrouting::pgget::pgr_fetch_row (const HeapTuple tuple, const TupleDesc & tupdesc, const std::vector< Column_info_t > & info, int64_t * , size_t * , bool)
Definition at line 272 of file pgdata_fetchers.cpp.
              {
    IID_t_rt distance;
    distance.from_vid = getBigInt(tuple, tupdesc,  info[0]);
    distance.to_vid = getBigInt(tuple, tupdesc,  info[1]);
    distance.cost = getFloat8(tuple, tupdesc, info[2]);
    return distance;
}
References IID_t_rt::cost, IID_t_rt::from_vid, pgrouting::getBigInt(), pgrouting::getFloat8(), and IID_t_rt::to_vid.
Referenced by get_matrixRows().