PGROUTING: pgrouting::algorithm Namespace Reference
pgrouting::algorithm Namespace Reference
Functions
template<typename G >
std::deque< Path > drivingDistance (const G &graph, const std::set< int64_t > &roots, double distance, bool equicost, std::vector< std::map< int64_t, int64_t > > &depths, bool details)
Function Documentation
drivingDistance()
template<typename G > std::deque< Path > pgrouting::algorithm::drivingDistance (const G & graph, const std::set< int64_t > & roots, double distance, bool equicost, std::vector< std::map< int64_t, int64_t > > & depths, bool details)
Definition at line 491 of file drivingDist.hpp.
                      {
    if (equicost) {
        return detail::drivingDistance_with_equicost(
                graph,
                roots,
                depths,
                distance, details);
    } else {
        return detail::drivingDistance_no_equicost(
                graph,
                roots,
                depths,
                distance, details);
    }
}
References detail::drivingDistance_no_equicost(), and detail::drivingDistance_with_equicost().
Referenced by pgr_do_drivingDistance(), and pgr_do_withPointsDD().