PGROUTING: anonymous_namespace{bdDijkstra_driver.cpp} Namespace Reference
anonymous_namespace{bdDijkstra_driver.cpp} Namespace Reference
Functions
template<class G >
std::deque< pgrouting::Path > pgr_bdDijkstra (G &graph, const std::map< int64_t, std::set< int64_t > > &combinations, bool only_cost)
Function Documentation
pgr_bdDijkstra()
template<class G > std::deque< pgrouting::Path > anonymous_namespace{bdDijkstra_driver.cpp}::pgr_bdDijkstra (G & graph, const std::map< int64_t, std::set< int64_t > > & combinations, bool only_cost)
Definition at line 56 of file bdDijkstra_driver.cpp.
{
    using pgrouting::Path;
    pgrouting::bidirectional::Pgr_bdDijkstra<G> fn_bdDijkstra(graph);
    std::deque<Path> paths;
    for (const auto &comb : combinations) {
        auto source = comb.first;
        if (!graph.has_vertex(source)) continue;
        for (const auto &target : comb.second) {
            if (!graph.has_vertex(target)) continue;
            fn_bdDijkstra.clear();
            paths.push_back(fn_bdDijkstra.pgr_bdDijkstra(graph.get_V(source), graph.get_V(target), only_cost));
        }
    }
    return paths;
}
References pgrouting::bidirectional::Pgr_bidirectional< G >::clear(), and pgrouting::bidirectional::Pgr_bdDijkstra< G >::pgr_bdDijkstra().
Referenced by pgr_do_bdDijkstra().