PGROUTING: ordering_process.cpp File Reference
ordering_process.cpp File Reference
#include "process/ordering_process.h"
#include "c_common/postgres_connection.h"
#include "c_common/e_report.h"
#include "c_common/time_msg.h"
#include <string>
#include "cpp_common/assert.hpp"
#include "drivers/ordering_driver.hpp"
Functions
void pgr_process_ordering (const char *edges_sql, int which, int64_t **result_tuples, size_t *result_count)
which = 0 -> sloan which = 1 -> cuthillmckee which = 2 -> king
Function Documentation
pgr_process_ordering()
void pgr_process_ordering (const char * edges_sql, int which, int64_t ** result_tuples, size_t * result_count)
which = 0 -> sloan which = 1 -> cuthillmckee which = 2 -> king
This is c++ code, linked as C code, because pgr_process_foo is called from C code
Definition at line 50 of file ordering_process.cpp.
{
    pgassert(edges_sql);
    pgassert(!(*result_tuples));
    pgassert(*result_count == 0);
    pgr_SPI_connect();
    char* log_msg = NULL;
    char* notice_msg = NULL;
    char* err_msg = NULL;
    clock_t start_t = clock();
    do_ordering(
            std::string(edges_sql),
            which,
            result_tuples, result_count,
            &log_msg , &notice_msg, &err_msg);
    if (which == 0) {
        time_msg(std::string(" processing pgr_sloanOrdering").c_str(), start_t, clock());
    } else if (which == 1) {
        time_msg(std::string("processing pgr_cuthillMckeeOrdering").c_str(), start_t, clock());
    } else if (which == 2) {
        time_msg(std::string("processing pgr_kingOrdering").c_str(), start_t, clock());
    }
    if (err_msg && (*result_tuples)) {
        pfree(*result_tuples);
        (*result_tuples) = NULL;
        (*result_count) = 0;
    }
    pgr_global_report(&log_msg, &notice_msg, &err_msg);
    pgr_SPI_finish();
}
References do_ordering(), pgassert, pgr_global_report(), pgr_SPI_connect(), pgr_SPI_finish(), and time_msg().
Referenced by _pgr_kingordering(), and _pgr_sloanordering().