PGROUTING: orders_input.h File Reference
orders_input.h File Reference
#include <stddef.h>
#include "c_types/pickDeliver/pickDeliveryOrders_t.h"
Functions
void pgr_get_pd_orders (char *pd_orders_sql, PickDeliveryOrders_t **pd_orders, size_t *total_pd_orders)
Reads the pick-Deliver orders.
void pgr_get_pd_orders_with_id (char *pd_orders_sql, PickDeliveryOrders_t **pd_orders, size_t *total_pd_orders)
Reads the pick-Deliver orders.
Function Documentation
pgr_get_pd_orders()
void pgr_get_pd_orders (char * pd_orders_sql, PickDeliveryOrders_t ** pd_orders, size_t * total_pd_orders)
Reads the pick-Deliver orders.
Parameters
[in] pd_orders_sql
[out] pd_orders
[out] total_pd_orders
Definition at line 205 of file orders_input.c.
References pgr_get_pd_orders_general().
Referenced by process().
{
     pgr_get_pd_orders_general(pd_orders_sql, pd_orders, total_pd_orders, false);
 }
pgr_get_pd_orders_with_id()
void pgr_get_pd_orders_with_id (char * pd_orders_sql, PickDeliveryOrders_t ** pd_orders, size_t * total_pd_orders)
Reads the pick-Deliver orders.
Parameters
[in] pd_orders_sql
[out] pd_orders
[out] total_pd_orders
Definition at line 213 of file orders_input.c.
References pgr_get_pd_orders_general().
Referenced by process().
{
     pgr_get_pd_orders_general(pd_orders_sql, pd_orders, total_pd_orders, true);
 }