PGROUTING: pgr_tsp.cpp File Reference
pgr_tsp.cpp File Reference
#include "tsp/pgr_tsp.hpp"
#include <time.h>
#include <utility>
#include <iomanip>
#include <limits>
#include <vector>
#include <set>
#include <algorithm>
#include <cmath>
#include "cpp_common/pgr_assert.h"
Namespaces
pgrouting
Book keeping class for swapping orders between vehicles.
pgrouting::tsp
Functions
static size_t pred (size_t i, size_t n)
static size_t rand (size_t n)
static size_t succ (size_t i, size_t n)
Function Documentation
pred()
static size_t pred (size_t i, size_t n) static
Definition at line 64 of file pgr_tsp.cpp.
{
     return  i == 0? n - 1: i -1;
 }
Referenced by pgrouting::Pgr_dijkstra< G >::drivingDistance_with_equicost(), pgrouting::vrp::Vehicle_node::evaluate(), pgrouting::Pgr_dijkstra< G >::get_drivingDistance_with_equicost_paths(), and pgrouting::tsp::TSP< MATRIX >::getDeltaSwap().
rand()
static size_t rand (size_t n) static
Definition at line 49 of file pgr_tsp.cpp.
                {
     pgassert(n > 0);
     return static_cast< size_t >(std::rand() % n);
 }
References pgassert.
Referenced by pgrouting::tsp::TSP< MATRIX >::annealing().
succ()
static size_t succ (size_t i, size_t n) static
Definition at line 57 of file pgr_tsp.cpp.
{
     pgassert(n > 0);
     return static_cast<size_t>((i + 1) % n);
 }
References pgassert.
Referenced by pgrouting::tsp::TSP< MATRIX >::annealing(), pgrouting::tsp::TSP< MATRIX >::getDeltaReverse(), pgrouting::tsp::TSP< MATRIX >::getDeltaSlide(), and pgrouting::tsp::TSP< MATRIX >::getDeltaSwap().