PGROUTING: pgr_alloc.cpp File Reference
pgr_alloc.cpp File Reference
#include "cpp_common/pgr_alloc.hpp"
#include <cstring>
#include <string>
Functions
char * pgr_msg (const std::string &msg)
Function Documentation
pgr_msg()
char* pgr_msg (const std::string & msg)
Definition at line 30 of file pgr_alloc.cpp.
{
     char* duplicate = NULL;
     duplicate = pgr_alloc(msg.size() + 1, duplicate);
     memcpy(duplicate, msg.c_str(), msg.size());
     duplicate[msg.size()] = '\0';
     return duplicate;
 }
References pgr_alloc().
Referenced by do_alphaShape(), do_pgr_articulationPoints(), do_pgr_astarManyToMany(), do_pgr_bdAstar(), do_pgr_bdDijkstra(), do_pgr_bellman_ford(), do_pgr_bellman_ford_neg(), do_pgr_biconnectedComponents(), do_pgr_binaryBreadthFirstSearch(), do_pgr_breadthFirstSearch(), do_pgr_bridges(), do_pgr_combinations_dijkstra(), do_pgr_connectedComponents(), do_pgr_contractGraph(), do_pgr_dagShortestPath(), do_pgr_dijkstraVia(), do_pgr_directedChPP(), do_pgr_driving_many_to_dist(), do_pgr_edge_disjoint_paths(), do_pgr_edwardMoore(), do_pgr_euclideanTSP(), do_pgr_floydWarshall(), do_pgr_johnson(), do_pgr_kruskal(), do_pgr_ksp(), do_pgr_lineGraph(), do_pgr_lineGraphFull(), do_pgr_many_to_many_dijkstra(), do_pgr_many_withPointsDD(), do_pgr_max_flow(), do_pgr_maximum_cardinality_matching(), do_pgr_minCostMaxFlow(), do_pgr_pickDeliver(), do_pgr_pickDeliverEuclidean(), do_pgr_prim(), do_pgr_randomSpanningTree(), do_pgr_stoerWagner(), do_pgr_strongComponents(), do_pgr_topologicalSort(), do_pgr_transitiveClosure(), do_pgr_tsp(), do_pgr_turnRestrictedPath(), do_pgr_withPoints(), do_pgr_withPointsKsp(), do_trsp(), get_name(), get_new_queries(), and get_order().