PGROUTING: points_input.c File Reference
points_input.c File Reference
#include "c_common/points_input.h"
#include <stdbool.h>
#include <stddef.h>
#include "c_types/column_info_t.h"
#include "c_common/debug_macro.h"
#include "c_common/get_check_data.h"
Functions
static void fetch_point (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info[4], int64_t *default_pid, char default_side, Point_on_edge_t *point)
void pgr_get_points (char *points_sql, Point_on_edge_t **points, size_t *total_points)
pgr_get_points
Function Documentation
fetch_point()
static void fetch_point (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info[4], int64_t * default_pid, char default_side, Point_on_edge_t * point) static
Definition at line 41 of file points_input.c.
{
     if (column_found(info[0].colNumber)) {
         point->pid = pgr_SPI_getBigInt(tuple, tupdesc, info[0]);
     } else {
         point->pid = *default_pid;
         ++(*default_pid);
     }
     point->edge_id = pgr_SPI_getBigInt(tuple, tupdesc, info[1]);
     point->fraction = pgr_SPI_getFloat8(tuple, tupdesc, info[2]);
     if (column_found(info[3].colNumber)) {
         point->side =
             (char)pgr_SPI_getChar(tuple, tupdesc, info[3], false, default_side);
     } else {
         point->side = default_side;
     }
 }
References column_found(), Point_on_edge_t::edge_id, Point_on_edge_t::fraction, pgr_SPI_getBigInt(), pgr_SPI_getChar(), pgr_SPI_getFloat8(), Point_on_edge_t::pid, and Point_on_edge_t::side.
Referenced by pgr_get_points().
pgr_get_points()
void pgr_get_points (char * points_sql, Point_on_edge_t ** points, size_t * total_points)
pgr_get_points
For queries of the type:
SELECT pid, edge_id, fraction, [side]
FROM edge_table;
Parameters
[in] points_sql
[out] points
[out] total_points
Definition at line 69 of file points_input.c.
{
     const int tuple_limit = 1000;
     size_t total_tuples;
     Column_info_t info[4];
     int i;
     for (i = 0; i < 4; ++i) {
         info[i].colNumber = -1;
         info[i].type = 0;
         info[i].strict = true;
         info[i].eType = ANY_INTEGER;
     }
     info[0].name = "pid";
     info[1].name = "edge_id";
     info[2].name = "fraction";
     info[3].name = "side";
     info[0].strict = false;
     info[3].strict = false;
     info[2].eType = ANY_NUMERICAL;
     info[3].eType = CHAR1;
     void *SPIplan;
     SPIplan = pgr_SPI_prepare(points_sql);
     Portal SPIportal;
     SPIportal = pgr_SPI_cursor_open(SPIplan);
     bool moredata = true;
     (*total_points) = total_tuples = 0;
     int64_t default_pid = 1;
     char default_side = 'b';
     while (moredata == true) {
         SPI_cursor_fetch(SPIportal, true, tuple_limit);
         if (total_tuples == 0) {
             /* on the first tuple get the column information */
             pgr_fetch_column_info(info, 4);
         }
         size_t ntuples = SPI_processed;
         total_tuples += ntuples;
         if (ntuples > 0) {
             if ((*points) == NULL)
                 (*points) = (Point_on_edge_t *)
                     palloc0(total_tuples * sizeof(Point_on_edge_t));
             else
                 (*points) = (Point_on_edge_t *)
                     repalloc((*points), total_tuples * sizeof(Point_on_edge_t));
             if ((*points) == NULL) {
                 elog(ERROR, "Out of memory");
             }
             SPITupleTable *tuptable = SPI_tuptable;
             TupleDesc tupdesc = SPI_tuptable->tupdesc;
             size_t t;
             PGR_DBG("processing %ld points tuples", ntuples);
             for (t = 0; t < ntuples; t++) {
                 HeapTuple tuple = tuptable->vals[t];
                 fetch_point(&tuple, &tupdesc, info,
                         &default_pid, default_side,
                         &(*points)[total_tuples - ntuples + t]);
             }
             SPI_freetuptable(tuptable);
         } else {
             moredata = false;
         }
     }
     SPI_cursor_close(SPIportal);
     if (total_tuples == 0) {
         (*total_points) = 0;
         PGR_DBG("NO points");
         return;
     }
     (*total_points) = total_tuples;
     PGR_DBG("Finish reading %ld points, %ld", total_tuples, (*total_points));
 }
References ANY_INTEGER, ANY_NUMERICAL, CHAR1, Column_info_t::colNumber, Column_info_t::eType, fetch_point(), Column_info_t::name, PGR_DBG, pgr_fetch_column_info(), pgr_SPI_cursor_open(), pgr_SPI_prepare(), Column_info_t::strict, and Column_info_t::type.
Referenced by process().