PGROUTING: postgres_connection.h File Reference
postgres_connection.h File Reference
#include <postgres.h>
#include <executor/spi.h>
#include <funcapi.h>
#include <utils/builtins.h>
#include <access/htup_details.h>
#include <fmgr.h>
#include <utils/array.h>
#include <catalog/pg_type.h>
#include "cpp_common/undefPostgresDefine.hpp"
Functions
void pgr_send_error (int errcode)
void pgr_SPI_connect (void)
Portal pgr_SPI_cursor_open (SPIPlanPtr SPIplan)
void pgr_SPI_finish (void)
SPIPlanPtr pgr_SPI_prepare (const char *sql)
Function Documentation
pgr_send_error()
void pgr_send_error (int errcode)
Definition at line 39 of file postgres_connection.c.
{
    switch (errcode) {
        case 1:
            elog(ERROR, "Unexpected point(s) with same pid but different"
                   " edge/fraction/side combination found.");
            break;
        case 2:
            elog(ERROR, "Internal: Unexpected mismatch "
                   "count and sequence number on results");
            break;
        default:
            elog(ERROR, "Unknown exception");
    }
}
pgr_SPI_connect()
void pgr_SPI_connect (void)
Definition at line 66 of file postgres_connection.c.
                      {
    int SPIcode;
    SPIcode = SPI_connect();
    if (SPIcode  != SPI_OK_CONNECT) {
        elog(ERROR, "Couldn't open a connection to SPI");
    }
}
Referenced by pgr_process_allpairs(), pgr_process_metrics(), pgr_process_ordering(), pgr_process_shortestPath(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), and process().
pgr_SPI_cursor_open()
Portal pgr_SPI_cursor_open (SPIPlanPtr SPIplan)
Definition at line 85 of file postgres_connection.c.
{
    Portal SPIportal;
    SPIportal = SPI_cursor_open(NULL, SPIplan, NULL, NULL, true);
    if (SPIportal == NULL) {
        elog(ERROR, "SPI_cursor_open returns NULL");
    }
    return SPIportal;
}
Referenced by pgrouting::get_data(), and pgrouting::pgget::get_data().
pgr_SPI_finish()
void pgr_SPI_finish (void)
Definition at line 58 of file postgres_connection.c.
                     {
    int code = SPI_finish();
    if (code != SPI_OK_FINISH) {  // SPI_ERROR_UNCONNECTED
        elog(ERROR, "There was no connection to SPI");
    }
}
Referenced by pgr_process_allpairs(), pgr_process_metrics(), pgr_process_ordering(), pgr_process_shortestPath(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), and process().
pgr_SPI_prepare()
SPIPlanPtr pgr_SPI_prepare (const char * sql)
Definition at line 75 of file postgres_connection.c.
{
    SPIPlanPtr SPIplan;
    SPIplan = SPI_prepare(sql, 0, NULL);
    if (SPIplan  == NULL) {
        elog(ERROR, "Couldn't create query plan via SPI: %s", sql);
    }
    return SPIplan;
}
Referenced by pgrouting::get_data(), and pgrouting::pgget::get_data().