PGROUTING: prim_driver.cpp File Reference
prim_driver.cpp File Reference
#include "drivers/spanningTree/prim_driver.h"
#include <sstream>
#include <deque>
#include <vector>
#include <string>
#include "cpp_common/pgdata_getters.hpp"
#include "cpp_common/alloc.hpp"
#include "cpp_common/assert.hpp"
#include "c_types/mst_rt.h"
#include "spanningTree/prim.hpp"
#include "spanningTree/details.hpp"
Functions
void pgr_do_prim (const char *edges_sql, ArrayType *starts, const char *fn_suffix, int64_t max_depth, double distance, MST_rt **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
Function Documentation
pgr_do_prim()
void pgr_do_prim (const char * edges_sql, ArrayType * starts, const char * fn_suffix, int64_t max_depth, double distance, MST_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 47 of file prim_driver.cpp.
{
    using pgrouting::pgr_alloc;
    using pgrouting::to_pg_msg;
    using pgrouting::pgr_free;
    using pgrouting::pgget::get_intArray;
    std::ostringstream log;
    std::ostringstream err;
    std::ostringstream notice;
    const char *hint = nullptr;
    try {
        // NOLINTBEGIN(clang-analyzer-cplusplus.NewDelete)
        pgassert(!(*log_msg));
        pgassert(!(*notice_msg));
        pgassert(!(*err_msg));
        pgassert(!(*return_tuples));
        pgassert(*return_count == 0);
        // NOLINTEND(clang-analyzer-cplusplus.NewDelete)
        auto roots = get_intArray(starts, false);
        hint = edges_sql;
        auto edges = pgrouting::pgget::get_edges(std::string(edges_sql), true, false);
        hint = nullptr;
        std::string suffix(fn_suffix);
        std::vector<MST_rt> results;
        pgrouting::UndirectedGraph undigraph;
        undigraph.insert_min_edges_no_parallel(edges);
        pgrouting::functions::Pgr_prim<pgrouting::UndirectedGraph> prim;
        if (edges.empty()) {
            results = pgrouting::details::get_no_edge_graph_result(roots);
            *notice_msg = to_pg_msg("No edges found");
            *log_msg = to_pg_msg(edges_sql);
        } else {
            if (suffix == "") {
                results = prim.prim(undigraph);
            } else if (suffix == "BFS") {
                results = prim.primBFS(undigraph, roots, max_depth);
            } else if (suffix == "DFS") {
                results = prim.primDFS(undigraph, roots, max_depth);
            } else if (suffix == "DD") {
                results = prim.primDD(undigraph, roots, distance);
            } else {
                err << "Unknown Prim function";
                *err_msg = to_pg_msg(err);
                return;
            }
        }
        auto count = results.size();
        (*return_tuples) = pgr_alloc(count, (*return_tuples));
        for (size_t i = 0; i < count; i++) {
            *((*return_tuples) + i) = results[i];
        }
        (*return_count) = count;
        pgassert(*err_msg == NULL);
        *log_msg = to_pg_msg(log);
        *notice_msg = to_pg_msg(notice);
    } catch (AssertFailedException &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch (const std::string &ex) {
        *err_msg = to_pg_msg(ex);
        *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
    } catch (std::exception &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch(...) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << "Caught unknown exception!";
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    }
}
References pgrouting::pgget::get_edges(), pgrouting::pgget::get_intArray(), pgrouting::details::get_no_edge_graph_result(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::insert_min_edges_no_parallel(), pgassert, pgrouting::pgr_alloc(), pgrouting::pgr_free(), pgrouting::functions::Pgr_prim< G >::prim(), pgrouting::functions::Pgr_prim< G >::primBFS(), pgrouting::functions::Pgr_prim< G >::primDD(), pgrouting::functions::Pgr_prim< G >::primDFS(), pgrouting::to_pg_msg(), and AssertFailedException::what().
Referenced by process().