PGROUTING: randomSpanningTree_driver.cpp File Reference
randomSpanningTree_driver.cpp File Reference
#include "drivers/spanningTree/randomSpanningTree_driver.h"
#include <sstream>
#include <deque>
#include <vector>
#include <string>
#include "cpp_common/pgdata_getters.hpp"
#include "cpp_common/alloc.hpp"
#include "cpp_common/assert.hpp"
#include "spanningTree/randomSpanningTree.hpp"
Functions
void pgr_do_randomSpanningTree (const char *edges_sql, int64_t root_vertex, bool directed, SpanTree_rt **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
template<class G >
static std::vector< SpanTree_rt > pgr_randomSpanningTree (G &graph, int64_t root_vertex)
Function Documentation
pgr_do_randomSpanningTree()
void pgr_do_randomSpanningTree (const char * edges_sql, int64_t root_vertex, bool directed, SpanTree_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 54 of file randomSpanningTree_driver.cpp.
{
    using pgrouting::pgr_alloc;
    using pgrouting::to_pg_msg;
    using pgrouting::pgr_free;
    std::ostringstream log;
    std::ostringstream err;
    std::ostringstream notice;
    const char *hint = nullptr;
    try {
        pgassert(!(*log_msg));
        pgassert(!(*notice_msg));
        pgassert(!(*err_msg));
        pgassert(!(*return_tuples));
        pgassert(*return_count == 0);
        pgassert(total_edges != 0);
        hint = edges_sql;
        auto edges = pgrouting::pgget::get_edges(std::string(edges_sql), true, false);
        if (edges.empty()) {
            *notice_msg = to_pg_msg("No edges found");
            *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
            return;
        }
        hint = nullptr;
        std::vector<SpanTree_rt> results;
        if (directed) {
            log << "Working with directed Graph\n";
            pgrouting::DirectedGraph digraph(directed);
            digraph.insert_edges(data_edges, total_edges);
            results = pgr_randomSpanningTree(
                    digraph,
                    root_vertex);
        } else {
            log << "Working with Undirected Graph\n";
            pgrouting::UndirectedGraph undigraph(directed);
            undigraph.insert_edges(data_edges, total_edges);
            results = pgr_randomSpanningTree(
                    undigraph,
                    root_vertex);
        }
        auto count = results.size();
        if (count == 0) {
            (*return_tuples) = NULL;
            (*return_count) = 0;
            notice << "No paths found";
            return;
        }
        (*return_tuples) = pgr_alloc(count, (*return_tuples));
        for (size_t i = 0; i < count; i++) {
            *((*return_tuples) + i) = results[i];
        }
        (*return_count) = count;
        pgassert(*err_msg == NULL);
        *log_msg = to_pg_msg(log);
        *notice_msg = to_pg_msg(notice);
    } catch (AssertFailedException &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch (const std::string &ex) {
        *err_msg = to_pg_msg(ex);
        *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
    } catch (std::exception &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch(...) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << "Caught unknown exception!";
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    }
}
References pgrouting::pgget::get_edges(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::insert_edges(), pgassert, pgrouting::pgr_alloc(), pgrouting::pgr_free(), pgr_randomSpanningTree(), pgrouting::to_pg_msg(), and AssertFailedException::what().
Referenced by process().
pgr_randomSpanningTree()
template<class G > static std::vector< SpanTree_rt > pgr_randomSpanningTree (G & graph, int64_t root_vertex) static
Definition at line 45 of file randomSpanningTree_driver.cpp.
{
    Pgr_randomSpanningTree< G > fn_randomSpanningTree;
    return fn_randomSpanningTree.randomSpanningTree(graph, root_vertex);
}
Referenced by pgr_do_randomSpanningTree().