PGROUTING: randomSpanningTree.c File Reference
randomSpanningTree.c File Reference
#include <stdbool.h>
#include "c_common/postgres_connection.h"
#include "c_types/spanTree_rt.h"
#include "c_common/debug_macro.h"
#include "c_common/e_report.h"
#include "c_common/time_msg.h"
#include "drivers/spanningTree/randomSpanningTree_driver.h"
Functions
PG_FUNCTION_INFO_V1 (randomSpanningTree)
static void process (char *edges_sql, int64_t root_vertex, bool directed, SpanTree_rt **result_tuples, size_t *result_count)
PGDLLEXPORT Datum randomSpanningTree (PG_FUNCTION_ARGS)
Function Documentation
PG_FUNCTION_INFO_V1()
PG_FUNCTION_INFO_V1 (randomSpanningTree)
process()
static void process (char * edges_sql, int64_t root_vertex, bool directed, SpanTree_rt ** result_tuples, size_t * result_count) static
Definition at line 44 of file randomSpanningTree.c.
{
    pgr_SPI_connect();
    char* log_msg = NULL;
    char* notice_msg = NULL;
    char* err_msg = NULL;
    (*result_tuples) = NULL;
    (*result_count) = 0;
    clock_t start_t = clock();
    pgr_do_randomSpanningTree(
            edges,
            total_edges,
            root_vertex,
            directed,
            result_tuples,
            result_count,
            &log_msg,
            &notice_msg,
            &err_msg);
    time_msg(" processing pgr_randomSpanningTree", start_t, clock());
    PGR_DBG("Returning %ld tuples", *result_count);
    if (err_msg) {
        if (*result_tuples) pfree(*result_tuples);
    }
    pgr_global_report(&log_msg, &notice_msg, &err_msg);
    pgr_SPI_finish();
}
References PGR_DBG, pgr_do_randomSpanningTree(), pgr_global_report(), pgr_SPI_connect(), pgr_SPI_finish(), and time_msg().
Referenced by randomSpanningTree().
randomSpanningTree()
PGDLLEXPORT Datum randomSpanningTree (PG_FUNCTION_ARGS)
Definition at line 82 of file randomSpanningTree.c.
{
    FuncCallContext     *funcctx;
    TupleDesc           tuple_desc;
    SpanTree_rt *result_tuples = NULL;
    size_t result_count = 0;
    if (SRF_IS_FIRSTCALL()) {
        MemoryContext   oldcontext;
        funcctx = SRF_FIRSTCALL_INIT();
        oldcontext = MemoryContextSwitchTo(funcctx->multi_call_memory_ctx);
        PGR_DBG("Calling process");
        process(
                text_to_cstring(PG_GETARG_TEXT_P(0)),
                PG_GETARG_INT64(1),
                PG_GETARG_BOOL(2),
                &result_tuples,
                &result_count);
        funcctx->max_calls = result_count;
        funcctx->user_fctx = result_tuples;
        if (get_call_result_type(fcinfo, NULL, &tuple_desc)
                != TYPEFUNC_COMPOSITE) {
            ereport(ERROR,
                    (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
                     errmsg("function returning record called in context "
                         "that cannot accept type record")));
        }
        funcctx->tuple_desc = tuple_desc;
        MemoryContextSwitchTo(oldcontext);
    }
    funcctx = SRF_PERCALL_SETUP();
    tuple_desc = funcctx->tuple_desc;
    result_tuples = (SpanTree_rt*) funcctx->user_fctx;
    if (funcctx->call_cntr < funcctx->max_calls) {
        HeapTuple    tuple;
        Datum        result;
        Datum        *values;
        bool*        nulls;
        values = palloc(5 * sizeof(Datum));
        nulls = palloc(5 * sizeof(bool));
        size_t i;
        for (i = 0; i < 5; ++i) {
            nulls[i] = false;
        }
        values[0] = Int64GetDatum((int64_t)funcctx->call_cntr + 1);
        values[1] =
            Int64GetDatum(result_tuples[funcctx->call_cntr].root_vertex);
        values[2] = Int64GetDatum(result_tuples[funcctx->call_cntr].edge);
        values[3] = Float8GetDatum(result_tuples[funcctx->call_cntr].cost);
        values[4] = Float8GetDatum(result_tuples[funcctx->call_cntr].tree_cost);
        tuple = heap_form_tuple(tuple_desc, values, nulls);
        result = HeapTupleGetDatum(tuple);
        SRF_RETURN_NEXT(funcctx, result);
    } else {
        PGR_DBG("Clean up code");
        SRF_RETURN_DONE(funcctx);
    }
}
References PGR_DBG, and process().