PGROUTING: sequentialVertexColoring_driver.cpp File Reference
sequentialVertexColoring_driver.cpp File Reference
#include "drivers/coloring/sequentialVertexColoring_driver.h"
#include <sstream>
#include <vector>
#include <algorithm>
#include <string>
#include "cpp_common/pgdata_getters.hpp"
#include "cpp_common/alloc.hpp"
#include "cpp_common/assert.hpp"
#include "coloring/sequentialVertexColoring.hpp"
Namespaces
namespace anonymous_namespace{sequentialVertexColoring_driver.cpp}
Functions
void pgr_do_sequentialVertexColoring (const char *edges_sql, II_t_rt **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
template<class G >
std::vector< II_t_rt > anonymous_namespace{sequentialVertexColoring_driver.cpp}::pgr_sequentialVertexColoring (G &graph)
Function Documentation
pgr_do_sequentialVertexColoring()
void pgr_do_sequentialVertexColoring (const char * edges_sql, II_t_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 58 of file sequentialVertexColoring_driver.cpp.
{
    using pgrouting::pgr_alloc;
    using pgrouting::to_pg_msg;
    using pgrouting::pgr_free;
    std::ostringstream log;
    std::ostringstream err;
    std::ostringstream notice;
    const char *hint = nullptr;
    try {
        pgassert(!(*log_msg));
        pgassert(!(*notice_msg));
        pgassert(!(*err_msg));
        pgassert(!(*return_tuples));
        pgassert(*return_count == 0);
        hint = edges_sql;
        auto edges = pgrouting::pgget::get_edges(std::string(edges_sql), true, false);
        if (edges.empty()) {
            *notice_msg = to_pg_msg("No edges found");
            *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
            return;
        }
        hint = nullptr;
        std::vector <II_t_rt> results;
        pgrouting::UndirectedGraph undigraph;
        undigraph.insert_edges(edges);
        results = pgr_sequentialVertexColoring(undigraph);
        auto count = results.size();
        if (count == 0) {
            (*return_tuples) = NULL;
            (*return_count) = 0;
            notice << "No traversal found";
            *log_msg = to_pg_msg(notice);
            return;
        }
        (*return_tuples) = pgr_alloc(count, (*return_tuples));
        for (size_t i = 0; i < count; i++) {
            *((*return_tuples) + i) = results[i];
        }
        (*return_count) = count;
        pgassert(*err_msg == NULL);
        *log_msg = to_pg_msg(log);
        *notice_msg = to_pg_msg(notice);
    } catch (AssertFailedException &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch (const std::string &ex) {
        *err_msg = to_pg_msg(ex);
        *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
    } catch (std::exception &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch(...) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << "Caught unknown exception!";
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    }
}
References pgrouting::pgget::get_edges(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::insert_edges(), pgassert, pgrouting::pgr_alloc(), pgrouting::pgr_free(), anonymous_namespace{sequentialVertexColoring_driver.cpp}::pgr_sequentialVertexColoring(), pgrouting::to_pg_msg(), and AssertFailedException::what().
Referenced by process().