PGROUTING: sequentialVertexColoring_driver.h File Reference
sequentialVertexColoring_driver.h File Reference
#include <stddef.h>
#include "c_types/pgr_edge_t.h"
#include "c_types/pgr_vertex_color_rt.h"
Functions
void do_pgr_sequentialVertexColoring (pgr_edge_t *data_edges, size_t total_edges, pgr_vertex_color_rt **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
Performs exception handling and converts the results to postgres.
Function Documentation
do_pgr_sequentialVertexColoring()
void do_pgr_sequentialVertexColoring (pgr_edge_t * data_edges, size_t total_edges, pgr_vertex_color_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Performs exception handling and converts the results to postgres.
Precondition
log_msg is empty
notice_msg is empty
err_msg is empty
return_tuples is empty
return_count is 0
It builds the undirected graph using the data_edges variable. Then, it passes the required variables to the template function pgr_sequentialVertexColoring which calls the main function defined in the C++ Header file. It also does exception handling.
Parameters
data_edges the set of edges from the SQL query
total_edges the total number of edges in the SQL query
return_tuples the rows in the result
return_count the count of rows in the result
log_msg stores the log message
notice_msg stores the notice message
err_msg stores the error message
Returns
void
Definition at line 93 of file sequentialVertexColoring_driver.cpp.
{
     std::ostringstream log;
     std::ostringstream err;
     std::ostringstream notice;
     try {
         pgassert(!(*log_msg));
         pgassert(!(*notice_msg));
         pgassert(!(*err_msg));
         pgassert(!(*return_tuples));
         pgassert(*return_count == 0);
         std::vector < pgr_vertex_color_rt > results;
         graphType gType = UNDIRECTED;
         pgrouting::UndirectedGraph undigraph(gType);
         undigraph.insert_edges(data_edges, total_edges);
         results = pgr_sequentialVertexColoring(undigraph);
         auto count = results.size();
         if (count == 0) {
             (*return_tuples) = NULL;
             (*return_count) = 0;
             notice << "No traversal found";
             *log_msg = pgr_msg(notice.str().c_str());
             return;
         }
         (*return_tuples) = pgr_alloc(count, (*return_tuples));
         for (size_t i = 0; i < count; i++) {
             *((*return_tuples) + i) = results[i];
         }
         (*return_count) = count;
         pgassert(*err_msg == NULL);
         *log_msg = log.str().empty()?
             *log_msg :
             pgr_msg(log.str().c_str());
         *notice_msg = notice.str().empty()?
             *notice_msg :
             pgr_msg(notice.str().c_str());
     } catch (AssertFailedException &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch (std::exception &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch(...) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << "Caught unknown exception!";
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     }
 }
References pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::insert_edges(), pgassert, pgr_alloc(), pgr_free(), pgr_msg(), pgr_sequentialVertexColoring(), UNDIRECTED, and AssertFailedException::what().
Referenced by process().