PGROUTING: shortestPath_process.cpp File Reference
shortestPath_process.cpp File Reference
#include "process/shortestPath_process.h"
#include "c_common/postgres_connection.h"
#include "c_common/e_report.h"
#include "c_common/time_msg.h"
#include <string>
#include "c_types/path_rt.h"
#include "cpp_common/assert.hpp"
#include "drivers/shortestPath_driver.hpp"
Namespaces
namespace anonymous_namespace{shortestPath_process.cpp}
Functions
std::string anonymous_namespace{shortestPath_process.cpp}::get_name (int32_t which, bool is_only_cost, bool is_near, bool is_withPoints, bool is_matrix)
void pgr_process_shortestPath (const char *edges_sql, const char *points_sql, const char *combinations_sql, ArrayType *starts, ArrayType *ends, bool directed, bool only_cost, bool normal, int64_t n_goals, bool global, char *driving_side, bool details, int32_t which, Path_rt **result_tuples, size_t *result_count)
which
Function Documentation
pgr_process_shortestPath()
void pgr_process_shortestPath (const char * edges_sql, const char * points_sql, const char * combinations_sql, ArrayType * starts, ArrayType * ends, bool directed, bool only_cost, bool normal, int64_t n_goals, bool global, char * driving_side, bool details, int32_t which, Path_rt ** result_tuples, size_t * result_count)
which
0 = dijkstra 1 = withPoints 101 = old withPoints
This is c++ code, linked as C code, because pgr_process_shortestPath is called from C code
Definition at line 74 of file shortestPath_process.cpp.
{
    pgassert(edges_sql);
    pgassert(!(*result_tuples));
    pgassert(*result_count == 0);
    pgr_SPI_connect();
    char* log_msg = NULL;
    char* notice_msg = NULL;
    char* err_msg = NULL;
    bool is_matrix = false;
    clock_t start_t = clock();
    do_shortestPath(
            edges_sql? edges_sql : "",
            points_sql? points_sql : "",
            combinations_sql? combinations_sql : "",
            starts, ends,
            directed, only_cost, normal,
            n_goals, global,
            driving_side[0], details,
            which,
            result_tuples, result_count,
            &is_matrix, &log_msg, &notice_msg, &err_msg);
    auto fn_name = get_name(which,  only_cost, n_goals > 0, points_sql != nullptr, is_matrix);
    time_msg(fn_name.c_str(), start_t, clock());
    if (err_msg && (*result_tuples)) {
        pfree(*result_tuples);
        (*result_tuples) = NULL;
        (*result_count) = 0;
    }
    pgr_global_report(&log_msg, &notice_msg, &err_msg);
    pgr_SPI_finish();
}
References do_shortestPath(), anonymous_namespace{shortestPath_process.cpp}::get_name(), pgassert, pgr_global_report(), pgr_SPI_connect(), pgr_SPI_finish(), and time_msg().
Referenced by _pgr_dijkstra(), _pgr_dijkstra_v4(), _pgr_withpoints(), and _pgr_withpoints_v4().