PGROUTING: stoerWagner.c File Reference
stoerWagner.c File Reference
#include <stdbool.h>
#include "c_common/postgres_connection.h"
#include "c_common/debug_macro.h"
#include "c_common/e_report.h"
#include "c_common/time_msg.h"
#include "c_types/stoerWagner_t.h"
#include "drivers/mincut/stoerWagner_driver.h"
Functions
PGDLLEXPORT Datum _pgr_stoerwagner (PG_FUNCTION_ARGS)
PG_FUNCTION_INFO_V1 (_pgr_stoerwagner)
static void process (char *edges_sql, StoerWagner_t **result_tuples, size_t *result_count)
Function Documentation
_pgr_stoerwagner()
PGDLLEXPORT Datum _pgr_stoerwagner (PG_FUNCTION_ARGS)
Definition at line 79 of file stoerWagner.c.
{
    FuncCallContext     *funcctx;
    TupleDesc           tuple_desc;
    StoerWagner_t *result_tuples = NULL;
    size_t result_count = 0;
    if (SRF_IS_FIRSTCALL()) {
        MemoryContext   oldcontext;
        funcctx = SRF_FIRSTCALL_INIT();
        oldcontext = MemoryContextSwitchTo(funcctx->multi_call_memory_ctx);
        PGR_DBG("Calling process");
        process(
                text_to_cstring(PG_GETARG_TEXT_P(0)),
                &result_tuples,
                &result_count);
        funcctx->max_calls = result_count;
        funcctx->user_fctx = result_tuples;
        if (get_call_result_type(fcinfo, NULL, &tuple_desc)
                != TYPEFUNC_COMPOSITE) {
            ereport(ERROR,
                    (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
                     errmsg("function returning record called in context "
                         "that cannot accept type record")));
        }
        funcctx->tuple_desc = tuple_desc;
        MemoryContextSwitchTo(oldcontext);
    }
    funcctx = SRF_PERCALL_SETUP();
    tuple_desc = funcctx->tuple_desc;
    result_tuples = (StoerWagner_t*) funcctx->user_fctx;
    if (funcctx->call_cntr < funcctx->max_calls) {
        HeapTuple    tuple;
        Datum        result;
        Datum        *values;
        bool*        nulls;
        values = palloc(4 * sizeof(Datum));
        nulls = palloc(4 * sizeof(bool));
        size_t i;
        for (i = 0; i < 4; ++i) {
            nulls[i] = false;
        }
        values[0] = Int32GetDatum((int32_t)funcctx->call_cntr + 1);
        values[1] = Int64GetDatum(result_tuples[funcctx->call_cntr].edge);
        values[2] = Float8GetDatum(result_tuples[funcctx->call_cntr].cost);
        values[3] = Float8GetDatum(result_tuples[funcctx->call_cntr].mincut);
        tuple = heap_form_tuple(tuple_desc, values, nulls);
        result = HeapTupleGetDatum(tuple);
        SRF_RETURN_NEXT(funcctx, result);
    } else {
        SRF_RETURN_DONE(funcctx);
    }
}
References StoerWagner_t::cost, StoerWagner_t::edge, StoerWagner_t::mincut, PGR_DBG, and process().
PG_FUNCTION_INFO_V1()
PG_FUNCTION_INFO_V1 (_pgr_stoerwagner)
process()
static void process (char * edges_sql, StoerWagner_t ** result_tuples, size_t * result_count) static
Definition at line 48 of file stoerWagner.c.
{
    pgr_SPI_connect();
    char* log_msg = NULL;
    char* notice_msg = NULL;
    char* err_msg = NULL;
    (*result_tuples) = NULL;
    (*result_count) = 0;
    clock_t start_t = clock();
    pgr_do_stoerWagner(
            edges_sql,
            result_tuples,
            result_count,
            &log_msg,
            &notice_msg,
            &err_msg);
    time_msg(" processing pgr_stoerWagner", start_t, clock());
    if (err_msg) {
        if (*result_tuples) pfree(*result_tuples);
    }
    pgr_global_report(&log_msg, &notice_msg, &err_msg);
    pgr_SPI_finish();
}
References pgr_do_stoerWagner(), pgr_global_report(), pgr_SPI_connect(), pgr_SPI_finish(), and time_msg().
Referenced by _pgr_stoerwagner().