PGROUTING: time_msg.c File Reference
time_msg.c File Reference
#include <time.h>
#include "c_common/postgres_connection.h"
#include "c_common/time_msg.h"
Functions
void time_msg (const char *msg, clock_t start_t, clock_t end_t)
Function Documentation
time_msg()
void time_msg (const char * msg, clock_t start_t, clock_t end_t)
Definition at line 31 of file time_msg.c.
{
    double elapsed_t = (double)(end_t - start_t) / CLOCKS_PER_SEC;
    elog(DEBUG2,
            "Elapsed time for %s: %lf sec = (%lf - %f) / CLOCKS_PER_SEC ",
            msg,
            elapsed_t,
            (double) end_t,
            (double) start_t);
}
Referenced by pgr_process_allpairs(), pgr_process_metrics(), pgr_process_ordering(), pgr_process_shortestPath(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), process(), and process().