PGROUTING: transitiveClosure_driver.cpp File Reference
transitiveClosure_driver.cpp File Reference
#include "drivers/transitiveClosure/transitiveClosure_driver.h"
#include <string>
#include <sstream>
#include <deque>
#include <vector>
#include <algorithm>
#include "transitiveClosure/transitiveClosure.hpp"
#include "cpp_common/pgdata_getters.hpp"
#include "cpp_common/identifiers.hpp"
#include "cpp_common/alloc.hpp"
#include "cpp_common/path.hpp"
#include "cpp_common/base_graph.hpp"
#include "c_types/transitiveClosure_rt.h"
Namespaces
namespace anonymous_namespace{transitiveClosure_driver.cpp}
Functions
template<typename G >
void anonymous_namespace{transitiveClosure_driver.cpp}::get_postgres_result (G &graph, TransitiveClosure_rt **return_tuples, size_t *count)
void pgr_do_transitiveClosure (const char *edges_sql, TransitiveClosure_rt **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
template<class G >
boost::adjacency_list anonymous_namespace{transitiveClosure_driver.cpp}::pgr_transitiveClosure (G &graph)
Function Documentation
pgr_do_transitiveClosure()
void pgr_do_transitiveClosure (const char * edges_sql, TransitiveClosure_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 97 of file transitiveClosure_driver.cpp.
{
    using pgrouting::to_pg_msg;
    using pgrouting::pgr_free;
    std::ostringstream log;
    std::ostringstream notice;
    std::ostringstream err;
    const char *hint = nullptr;
    try {
        pgassert(!(*log_msg));
        pgassert(!(*notice_msg));
        pgassert(!(*err_msg));
        pgassert(!(*return_tuples));
        pgassert(*return_count == 0);
        hint = edges_sql;
        auto edges = pgrouting::pgget::get_edges(std::string(edges_sql), true, false);
        if (edges.empty()) {
            *notice_msg = to_pg_msg("No edges found");
            *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
            return;
        }
        hint = nullptr;
        pgrouting::DirectedGraph digraph;
        digraph.insert_edges(edges);
        get_postgres_result(
                digraph,
                return_tuples,
                return_count);
        *log_msg = to_pg_msg(log);
        *notice_msg = to_pg_msg(notice);
    } catch (AssertFailedException &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch (const std::string &ex) {
        *err_msg = to_pg_msg(ex);
        *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
    } catch (std::exception &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch(...) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << "Caught unknown exception!";
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    }
}
References pgrouting::pgget::get_edges(), anonymous_namespace{transitiveClosure_driver.cpp}::get_postgres_result(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::insert_edges(), pgassert, pgrouting::pgr_free(), pgrouting::to_pg_msg(), and AssertFailedException::what().
Referenced by process().