PGROUTING: trsp_withPoints.c File Reference
trsp_withPoints.c File Reference
#include <stdbool.h>
#include "c_common/postgres_connection.h"
#include "c_types/path_rt.h"
#include "c_common/debug_macro.h"
#include "c_common/e_report.h"
#include "c_common/time_msg.h"
#include "drivers/withPoints/get_new_queries.h"
#include "drivers/trsp/trsp_withPoints_driver.h"
Functions
PGDLLEXPORT Datum _pgr_trsp_withpoints (PG_FUNCTION_ARGS)
PGDLLEXPORT Datum _pgr_trsp_withpoints_v4 (PG_FUNCTION_ARGS)
PG_FUNCTION_INFO_V1 (_pgr_trsp_withpoints)
PG_FUNCTION_INFO_V1 (_pgr_trsp_withpoints_v4)
static void process (char *edges_sql, char *restrictions_sql, char *points_sql, char *combinations_sql, ArrayType *starts, ArrayType *ends, bool directed, char *driving_side, bool details, Path_rt **result_tuples, size_t *result_count)
Function Documentation
_pgr_trsp_withpoints()
PGDLLEXPORT Datum _pgr_trsp_withpoints (PG_FUNCTION_ARGS)
Definition at line 233 of file trsp_withPoints.c.
{
    FuncCallContext     *funcctx;
    TupleDesc            tuple_desc;
    Path_rt *result_tuples = 0;
    size_t result_count = 0;
    if (SRF_IS_FIRSTCALL()) {
        MemoryContext   oldcontext;
        funcctx = SRF_FIRSTCALL_INIT();
        oldcontext = MemoryContextSwitchTo(funcctx->multi_call_memory_ctx);
#ifdef SHOWMSG
        ereport(NOTICE, (
                    errcode(ERRCODE_WARNING_DEPRECATED_FEATURE),
                    errmsg("A stored procedure is using deprecated C internal function '%s'", __func__),
                    errdetail("Library function '%s' was deprecated in pgRouting %s", __func__, "4.0.0"),
                    errhint("Consider upgrade pgRouting")));
#endif
        if (PG_NARGS() == 8) {
            /*
             * many to many
             */
            process(
                text_to_cstring(PG_GETARG_TEXT_P(0)),
                text_to_cstring(PG_GETARG_TEXT_P(1)),
                text_to_cstring(PG_GETARG_TEXT_P(2)),
                NULL,  // combinations
                PG_GETARG_ARRAYTYPE_P(3),
                PG_GETARG_ARRAYTYPE_P(4),
                PG_GETARG_BOOL(5),
                text_to_cstring(PG_GETARG_TEXT_P(6)),
                PG_GETARG_BOOL(7),
                &result_tuples,
                &result_count);
        } else if (PG_NARGS() == 7) {
            /*
             * Combinations
             */
            process(
                text_to_cstring(PG_GETARG_TEXT_P(0)),
                text_to_cstring(PG_GETARG_TEXT_P(1)),
                text_to_cstring(PG_GETARG_TEXT_P(2)),
                text_to_cstring(PG_GETARG_TEXT_P(3)),
                NULL, NULL,  // starts & ends
                PG_GETARG_BOOL(5),
                text_to_cstring(PG_GETARG_TEXT_P(5)),
                PG_GETARG_BOOL(6),
                &result_tuples,
                &result_count);
        }
        funcctx->max_calls = result_count;
        funcctx->user_fctx = result_tuples;
        if (get_call_result_type(fcinfo, NULL, &tuple_desc)
                != TYPEFUNC_COMPOSITE) {
            ereport(ERROR,
                    (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
                     errmsg("function returning record called in context "
                         "that cannot accept type record")));
        }
        funcctx->tuple_desc = tuple_desc;
        MemoryContextSwitchTo(oldcontext);
    }
    funcctx = SRF_PERCALL_SETUP();
    tuple_desc = funcctx->tuple_desc;
    result_tuples = (Path_rt*) funcctx->user_fctx;
    if (funcctx->call_cntr < funcctx->max_calls) {
        HeapTuple    tuple;
        Datum        result;
        Datum        *values;
        bool*        nulls;
        size_t call_cntr = funcctx->call_cntr;
        size_t numb = 8;
        values = palloc(numb * sizeof(Datum));
        nulls = palloc(numb * sizeof(bool));
        size_t i;
        for (i = 0; i < numb; ++i) {
            nulls[i] = false;
        }
        int64_t seq = call_cntr == 0? 1 : result_tuples[call_cntr - 1].start_id;
        values[0] = Int32GetDatum((int32_t)call_cntr + 1);
        values[1] = Int32GetDatum((int32_t)seq);
        values[2] = Int64GetDatum(result_tuples[call_cntr].start_id);
        values[3] = Int64GetDatum(result_tuples[call_cntr].end_id);
        values[4] = Int64GetDatum(result_tuples[call_cntr].node);
        values[5] = Int64GetDatum(result_tuples[call_cntr].edge);
        values[6] = Float8GetDatum(result_tuples[call_cntr].cost);
        values[7] = Float8GetDatum(result_tuples[call_cntr].agg_cost);
        result_tuples[call_cntr].start_id = result_tuples[call_cntr].edge < 0? 1 : seq + 1;
        tuple = heap_form_tuple(tuple_desc, values, nulls);
        result = HeapTupleGetDatum(tuple);
        SRF_RETURN_NEXT(funcctx, result);
    } else {
        SRF_RETURN_DONE(funcctx);
    }
}
References Path_rt::edge, process(), and Path_rt::start_id.
_pgr_trsp_withpoints_v4()
PGDLLEXPORT Datum _pgr_trsp_withpoints_v4 (PG_FUNCTION_ARGS)
Definition at line 122 of file trsp_withPoints.c.
{
    FuncCallContext     *funcctx;
    TupleDesc            tuple_desc;
    Path_rt *result_tuples = 0;
    size_t result_count = 0;
    if (SRF_IS_FIRSTCALL()) {
        MemoryContext   oldcontext;
        funcctx = SRF_FIRSTCALL_INIT();
        oldcontext = MemoryContextSwitchTo(funcctx->multi_call_memory_ctx);
        if (PG_NARGS() == 8) {
            /*
             * many to many
             */
            process(
                text_to_cstring(PG_GETARG_TEXT_P(0)),
                text_to_cstring(PG_GETARG_TEXT_P(1)),
                text_to_cstring(PG_GETARG_TEXT_P(2)),
                NULL,  // combinations
                PG_GETARG_ARRAYTYPE_P(3),
                PG_GETARG_ARRAYTYPE_P(4),
                PG_GETARG_BOOL(5),
                text_to_cstring(PG_GETARG_TEXT_P(6)),
                PG_GETARG_BOOL(7),
                &result_tuples,
                &result_count);
        } else if (PG_NARGS() == 7) {
            /*
             * Combinations
             */
            process(
                text_to_cstring(PG_GETARG_TEXT_P(0)),
                text_to_cstring(PG_GETARG_TEXT_P(1)),
                text_to_cstring(PG_GETARG_TEXT_P(2)),
                text_to_cstring(PG_GETARG_TEXT_P(3)),
                NULL, NULL,  // starts & ends
                PG_GETARG_BOOL(4),
                text_to_cstring(PG_GETARG_TEXT_P(5)),
                PG_GETARG_BOOL(6),
                &result_tuples,
                &result_count);
        }
        funcctx->max_calls = result_count;
        funcctx->user_fctx = result_tuples;
        if (get_call_result_type(fcinfo, NULL, &tuple_desc) != TYPEFUNC_COMPOSITE) {
            ereport(ERROR, (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
                        errmsg("function returning record called in context "
                            "that cannot accept type record")));
        }
        funcctx->tuple_desc = tuple_desc;
        MemoryContextSwitchTo(oldcontext);
    }
    funcctx = SRF_PERCALL_SETUP();
    tuple_desc = funcctx->tuple_desc;
    result_tuples = (Path_rt*) funcctx->user_fctx;
    if (funcctx->call_cntr < funcctx->max_calls) {
        HeapTuple    tuple;
        Datum        result;
        Datum        *values;
        bool*        nulls;
        size_t call_cntr = funcctx->call_cntr;
        size_t numb = 8;
        values = palloc(numb * sizeof(Datum));
        nulls = palloc(numb * sizeof(bool));
        size_t i;
        for (i = 0; i < numb; ++i) {
            nulls[i] = false;
        }
        int64_t seq = call_cntr == 0? 1 : result_tuples[call_cntr - 1].start_id;
        values[0] = Int32GetDatum((int32_t)call_cntr + 1);
        values[1] = Int32GetDatum((int32_t)seq);
        values[2] = Int64GetDatum(result_tuples[call_cntr].start_id);
        values[3] = Int64GetDatum(result_tuples[call_cntr].end_id);
        values[4] = Int64GetDatum(result_tuples[call_cntr].node);
        values[5] = Int64GetDatum(result_tuples[call_cntr].edge);
        values[6] = Float8GetDatum(result_tuples[call_cntr].cost);
        values[7] = Float8GetDatum(result_tuples[call_cntr].agg_cost);
        result_tuples[call_cntr].start_id = result_tuples[call_cntr].edge < 0? 1 : seq + 1;
        tuple = heap_form_tuple(tuple_desc, values, nulls);
        result = HeapTupleGetDatum(tuple);
        SRF_RETURN_NEXT(funcctx, result);
    } else {
        SRF_RETURN_DONE(funcctx);
    }
}
References Path_rt::edge, process(), and Path_rt::start_id.
PG_FUNCTION_INFO_V1() [1/2]
PG_FUNCTION_INFO_V1 (_pgr_trsp_withpoints)
PG_FUNCTION_INFO_V1() [2/2]
PG_FUNCTION_INFO_V1 (_pgr_trsp_withpoints_v4)
process()
static void process (char * edges_sql, char * restrictions_sql, char * points_sql, char * combinations_sql, ArrayType * starts, ArrayType * ends, bool directed, char * driving_side, bool details, Path_rt ** result_tuples, size_t * result_count) static
Definition at line 46 of file trsp_withPoints.c.
{
    char d_side = estimate_drivingSide(driving_side[0]);
    if (d_side == ' ') {
        pgr_throw_error("Invalid value of 'driving side'", "Valid value are 'r', 'l', 'b'");
        return;
    }
    pgr_SPI_connect();
    char* log_msg = NULL;
    char* notice_msg = NULL;
    char* err_msg = NULL;
    char *edges_of_points_query = NULL;
    char *edges_no_points_query = NULL;
    get_new_queries(
            edges_sql, points_sql,
            &edges_of_points_query,
            &edges_no_points_query);
    clock_t start_t = clock();
    pgr_do_trsp_withPoints(
            edges_no_points_query,
            restrictions_sql,
            points_sql,
            edges_of_points_query,
            combinations_sql,
            starts, ends,
            directed,
            d_side,
            details,
            result_tuples, result_count,
            &log_msg,
            &notice_msg,
            &err_msg);
    time_msg("processing pgr_trsp_withPoints", start_t, clock());
    if (err_msg && (*result_tuples)) {
        pfree(*result_tuples);
        (*result_tuples) = NULL;
        (*result_count) = 0;
    }
    pgr_global_report(&log_msg, &notice_msg, &err_msg);
    if (edges_of_points_query) {
        pfree(edges_of_points_query); edges_of_points_query = NULL;
    }
    if (edges_no_points_query) {
        pfree(edges_no_points_query); edges_no_points_query = NULL;
    }
    pgr_SPI_finish();
}
References estimate_drivingSide(), get_new_queries(), pgr_do_trsp_withPoints(), pgr_global_report(), pgr_SPI_connect(), pgr_SPI_finish(), pgr_throw_error(), and time_msg().
Referenced by _pgr_trsp_withpoints(), and _pgr_trsp_withpoints_v4().