PGROUTING: trsp_withPoints_driver.cpp File Reference
trsp_withPoints_driver.cpp File Reference
#include "drivers/trsp/trsp_withPoints_driver.h"
#include <utility>
#include <vector>
#include <cstdint>
#include <sstream>
#include <deque>
#include <algorithm>
#include <limits>
#include <set>
#include <map>
#include <string>
#include "cpp_common/pgdata_getters.hpp"
#include "cpp_common/alloc.hpp"
#include "cpp_common/assert.hpp"
#include "cpp_common/rule.hpp"
#include "cpp_common/combinations.hpp"
#include "withPoints/withPoints.hpp"
#include "trsp/trspHandler.hpp"
#include "dijkstra/dijkstra.hpp"
Namespaces
namespace anonymous_namespace{trsp_withPoints_driver.cpp}
Functions
void pgr_do_trsp_withPoints (const char *edges_sql, const char *restrictions_sql, const char *points_sql, const char *edges_of_points_sql, const char *combinations_sql, ArrayType *starts, ArrayType *ends, bool directed, char driving_side, bool details, Path_rt **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
void anonymous_namespace{trsp_withPoints_driver.cpp}::post_process_trsp (std::deque< pgrouting::Path > &paths)
Function Documentation
pgr_do_trsp_withPoints()
void pgr_do_trsp_withPoints (const char * edges_sql, const char * restrictions_sql, const char * points_sql, const char * edges_of_points_sql, const char * combinations_sql, ArrayType * starts, ArrayType * ends, bool directed, char driving_side, bool details, Path_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 79 of file trsp_withPoints_driver.cpp.
{
    using pgrouting::Path;
    using pgrouting::pgr_alloc;
    using pgrouting::to_pg_msg;
    using pgrouting::pgr_free;
    using pgrouting::utilities::get_combinations;
    std::ostringstream log;
    std::ostringstream notice;
    std::ostringstream err;
    const char *hint = nullptr;
    try {
        pgassert(!(*log_msg));
        pgassert(!(*notice_msg));
        pgassert(!(*err_msg));
        pgassert(!(*return_tuples));
        pgassert(*return_count == 0);
        hint = combinations_sql;
        auto combinations = get_combinations(combinations_sql, starts, ends, true);
        hint = nullptr;
        if (combinations.empty() && combinations_sql) {
            *notice_msg = to_pg_msg("No (source, target) pairs found");
            *log_msg = to_pg_msg(combinations_sql);
            return;
        }
        hint = points_sql;
        auto points = pgrouting::pgget::get_points(std::string(points_sql));
        hint = edges_of_points_sql;
        auto edges_of_points = pgrouting::pgget::get_edges(std::string(edges_of_points_sql), true, false);
        hint = edges_sql;
        auto edges = pgrouting::pgget::get_edges(std::string(edges_sql), true, false);
        if (edges.size() + edges_of_points.size() == 0) {
            *notice_msg = to_pg_msg("No edges found");
            *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
            return;
        }
        hint = restrictions_sql;
        auto restrictions = restrictions_sql?
            pgrouting::pgget::get_restrictions(std::string(restrictions_sql)) : std::vector<Restriction_t>();
        /* Dealing with points */
        pgrouting::Pg_points_graph pg_graph(
                points, edges_of_points,
                true,
                driving_side,
                directed);
        log << pg_graph.get_log();
        if (pg_graph.has_error()) {
            log << pg_graph.get_log();
            err << pg_graph.get_error();
            *log_msg = to_pg_msg(log);
            *err_msg = to_pg_msg(err);
            return;
        }
        auto vertices(pgrouting::extract_vertices(edges));
        vertices = pgrouting::extract_vertices(vertices, pg_graph.new_edges());
        std::deque<Path> paths;
        if (directed) {
            pgrouting::DirectedGraph digraph;
            digraph.insert_edges(edges);
            digraph.insert_edges(pg_graph.new_edges());
            paths = pgrouting::algorithms::dijkstra(
                    digraph,
                    combinations,
                    false, (std::numeric_limits<size_t>::max)());
        } else {
            pgrouting::UndirectedGraph undigraph;
            undigraph.insert_edges(edges);
            undigraph.insert_edges(pg_graph.new_edges());
            paths = pgrouting::algorithms::dijkstra(
                    undigraph,
                    combinations,
                    false, (std::numeric_limits<size_t>::max)());
        }
        post_process_trsp(paths);
        if (!details) {
            for (auto &path : paths) path = pg_graph.eliminate_details(path);
        }
        size_t count(count_tuples(paths));
        if (count == 0) {
            notice << "No paths found";
            *log_msg = to_pg_msg(notice);
            return;
        }
        if (!restrictions_sql || restrictions.empty()) {
            if (!details) {
                for (auto &path : paths) {
                    path = pg_graph.eliminate_details(path);
                }
            }
            count = count_tuples(paths);
            if (count == 0) {
                (*return_tuples) = NULL;
                (*return_count) = 0;
                return;
            }
            (*return_tuples) = pgr_alloc(count, (*return_tuples));
            (*return_count) = (collapse_paths(return_tuples, paths));
            return;
        }
        /*
         * When there are turn restrictions
         */
        std::vector<pgrouting::trsp::Rule> ruleList;
        for (const auto &r : restrictions) {
            if (r.via) ruleList.push_back(pgrouting::trsp::Rule(r));
        }
        hint = nullptr;
        auto new_combinations = pgrouting::utilities::get_combinations(paths, ruleList);
        if (!new_combinations.empty()) {
            pgrouting::trsp::TrspHandler gdef(
                    edges,
                    pg_graph.new_edges(),
                    directed,
                    ruleList);
            auto new_paths = gdef.process(new_combinations);
            paths.insert(paths.end(), new_paths.begin(), new_paths.end());
        }
        post_process_trsp(paths);
        if (!details) {
            for (auto &path : paths) path = pg_graph.eliminate_details(path);
        }
        count = count_tuples(paths);
        if (count == 0) {
            (*return_tuples) = NULL;
            (*return_count) = 0;
            return;
        }
        (*return_tuples) = pgr_alloc(count, (*return_tuples));
        (*return_count) = collapse_paths(return_tuples, paths);
        *log_msg = to_pg_msg(log);
        *notice_msg = to_pg_msg(notice);
    } catch (AssertFailedException &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch (std::exception &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch (const std::string &ex) {
        *err_msg = to_pg_msg(ex);
        *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
    } catch(...) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << "Caught unknown exception!";
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    }
}
References pgrouting::algorithms::dijkstra(), pgrouting::Pg_points_graph::eliminate_details(), pgrouting::extract_vertices(), pgrouting::utilities::get_combinations(), pgrouting::pgget::get_edges(), pgrouting::Pgr_messages::get_error(), pgrouting::Pgr_messages::get_log(), pgrouting::pgget::get_points(), pgrouting::pgget::get_restrictions(), pgrouting::Pgr_messages::has_error(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::insert_edges(), pgrouting::Pg_points_graph::new_edges(), pgassert, pgrouting::pgr_alloc(), pgrouting::pgr_free(), anonymous_namespace{trsp_withPoints_driver.cpp}::post_process_trsp(), pgrouting::trsp::TrspHandler::process(), pgrouting::to_pg_msg(), and AssertFailedException::what().
Referenced by process().