PGROUTING: trsp_driver.cpp File Reference
trsp_driver.cpp File Reference
#include "drivers/trsp/trsp_driver.h"
#include <utility>
#include <vector>
#include <cstdint>
#include <sstream>
#include <deque>
#include <algorithm>
#include <limits>
#include <set>
#include <map>
#include <cassert>
#include <string>
#include "trsp/trspHandler.hpp"
#include "cpp_common/pgdata_getters.hpp"
#include "cpp_common/rule.hpp"
#include "cpp_common/assert.hpp"
#include "cpp_common/alloc.hpp"
#include "cpp_common/combinations.hpp"
#include "cpp_common/restriction_t.hpp"
#include "c_types/ii_t_rt.h"
#include "withPoints/withPoints.hpp"
#include "dijkstra/dijkstra.hpp"
Namespaces
namespace anonymous_namespace{trsp_driver.cpp}
Functions
template<class G >
std::deque< pgrouting::Path > anonymous_namespace{trsp_driver.cpp}::pgr_dijkstra (G &graph, std::map< int64_t, std::set< int64_t > > &combinations)
void pgr_do_trsp (const char *edges_sql, const char *restrictions_sql, const char *combinations_sql, ArrayType *starts, ArrayType *ends, bool directed, Path_rt **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
void anonymous_namespace{trsp_driver.cpp}::post_process_trsp (std::deque< pgrouting::Path > &paths, bool sort)
Function Documentation
pgr_do_trsp()
void pgr_do_trsp (const char * edges_sql, const char * restrictions_sql, const char * combinations_sql, ArrayType * starts, ArrayType * ends, bool directed, Path_rt ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 98 of file trsp_driver.cpp.
{
    using pgrouting::Path;
    using pgrouting::pgr_alloc;
    using pgrouting::to_pg_msg;
    using pgrouting::pgr_free;
    using pgrouting::utilities::get_combinations;
    std::ostringstream log;
    std::ostringstream notice;
    std::ostringstream err;
    const char *hint = nullptr;
    try {
        pgassert(!(*log_msg));
        pgassert(!(*notice_msg));
        pgassert(!(*err_msg));
        pgassert(!(*return_tuples));
        pgassert(*return_count == 0);
        hint = combinations_sql;
        auto combinations = get_combinations(combinations_sql, starts, ends, true);
        hint = nullptr;
        if (combinations.empty() && combinations_sql) {
            *notice_msg = to_pg_msg("No (source, target) pairs found");
            *log_msg = to_pg_msg(combinations_sql);
            return;
        }
        hint = edges_sql;
        auto edges = pgrouting::pgget::get_edges(std::string(edges_sql), true, false);
        hint = nullptr;
        if (edges.empty()) {
            *notice_msg = to_pg_msg("No edges found");
            *log_msg = to_pg_msg(edges_sql);
            return;
        }
        std::deque<Path> paths;
        if (directed) {
            pgrouting::DirectedGraph digraph;
            digraph.insert_edges(edges);
            paths = pgr_dijkstra(
                    digraph,
                    combinations);
        } else {
            pgrouting::UndirectedGraph undigraph;
            undigraph.insert_edges(edges);
            paths = pgr_dijkstra(
                    undigraph,
                    combinations);
        }
        post_process_trsp(paths, false);
        size_t count(0);
        count = count_tuples(paths);
        if (count == 0) {
            notice << "No paths found";
            *log_msg = to_pg_msg(notice);
            return;
        }
        if (!restrictions_sql) {
            (*return_tuples) = pgr_alloc(count, (*return_tuples));
            (*return_count) = (collapse_paths(return_tuples, paths));
            return;
        }
        /*
         * When there are turn restrictions
         */
        hint = restrictions_sql;
        auto restrictions = pgrouting::pgget::get_restrictions(std::string(restrictions_sql));
        if (restrictions.empty()) {
            (*return_tuples) = pgr_alloc(count, (*return_tuples));
            (*return_count) = (collapse_paths(return_tuples, paths));
            return;
        }
        std::vector<pgrouting::trsp::Rule> ruleList;
        for (const auto &r : restrictions) {
            if (r.via) ruleList.push_back(pgrouting::trsp::Rule(r));
        }
        hint = nullptr;
        auto new_combinations = pgrouting::utilities::get_combinations(paths, ruleList);
        if (!new_combinations.empty()) {
            pgrouting::trsp::TrspHandler gdef(
                    edges,
                    directed,
                    ruleList);
            auto new_paths = gdef.process(new_combinations);
            paths.insert(paths.end(), new_paths.begin(), new_paths.end());
        }
        post_process_trsp(paths, true);
        count = count_tuples(paths);
        if (count == 0) {
            (*return_tuples) = NULL;
            (*return_count) = 0;
            return;
        }
        (*return_tuples) = pgr_alloc(count, (*return_tuples));
        (*return_count) = collapse_paths(return_tuples, paths);
        *log_msg = to_pg_msg(log);
        *notice_msg = to_pg_msg(notice);
    } catch (AssertFailedException &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch (std::exception &except) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << except.what();
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    } catch (const std::string &ex) {
        *err_msg = to_pg_msg(ex);
        *log_msg = hint? to_pg_msg(hint) : to_pg_msg(log);
    } catch(...) {
        (*return_tuples) = pgr_free(*return_tuples);
        (*return_count) = 0;
        err << "Caught unknown exception!";
        *err_msg = to_pg_msg(err);
        *log_msg = to_pg_msg(log);
    }
}
References pgrouting::utilities::get_combinations(), pgrouting::pgget::get_edges(), pgrouting::pgget::get_restrictions(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E, t_directed >::insert_edges(), pgassert, pgrouting::pgr_alloc(), anonymous_namespace{trsp_driver.cpp}::pgr_dijkstra(), pgrouting::pgr_free(), anonymous_namespace{trsp_driver.cpp}::post_process_trsp(), pgrouting::trsp::TrspHandler::process(), pgrouting::to_pg_msg(), and AssertFailedException::what().
Referenced by process().