PGROUTING: withPoints_ksp.c File Reference
withPoints_ksp.c File Reference
#include <stdbool.h>
#include "c_common/postgres_connection.h"
#include "c_types/path_rt.h"
#include "c_common/time_msg.h"
#include "c_common/e_report.h"
#include "drivers/withPoints/get_new_queries.h"
#include "drivers/yen/withPoints_ksp_driver.h"
Functions
PGDLLEXPORT Datum _pgr_withpointsksp (PG_FUNCTION_ARGS)
PGDLLEXPORT Datum _pgr_withpointsksp_v4 (PG_FUNCTION_ARGS)
PG_FUNCTION_INFO_V1 (_pgr_withpointsksp)
PG_FUNCTION_INFO_V1 (_pgr_withpointsksp_v4)
static void process (char *edges_sql, char *points_sql, char *combinations_sql, ArrayType *starts, ArrayType *ends, int64_t *start_vid, int64_t *end_vid, int p_k, char *driving_side, bool directed, bool heap_paths, bool details, Path_rt **result_tuples, size_t *result_count)
Function Documentation
_pgr_withpointsksp()
PGDLLEXPORT Datum _pgr_withpointsksp (PG_FUNCTION_ARGS)
Definition at line 245 of file withPoints_ksp.c.
{
    FuncCallContext     *funcctx;
    TupleDesc            tuple_desc;
    Path_rt  *result_tuples = 0;
    size_t result_count = 0;
    if (SRF_IS_FIRSTCALL()) {
        MemoryContext   oldcontext;
        funcctx = SRF_FIRSTCALL_INIT();
        oldcontext = MemoryContextSwitchTo(funcctx->multi_call_memory_ctx);
#ifdef SHOWMSG
        ereport(NOTICE, (
                    errcode(ERRCODE_WARNING_DEPRECATED_FEATURE),
                    errmsg("A stored procedure is using deprecated C internal function '%s'", __func__),
                    errdetail("Library function '%s' was deprecated in pgRouting %s", __func__, "4.0.0"),
                    errhint("Consider upgrade pgRouting")));
#endif
        if (PG_NARGS() == 10) {
            process(
                text_to_cstring(PG_GETARG_TEXT_P(0)),
                text_to_cstring(PG_GETARG_TEXT_P(1)),
                NULL,
                PG_GETARG_ARRAYTYPE_P(2),
                PG_GETARG_ARRAYTYPE_P(3),
                NULL, NULL,
                PG_GETARG_INT32(4),
                text_to_cstring(PG_GETARG_TEXT_P(5)),
                PG_GETARG_BOOL(6),
                PG_GETARG_BOOL(7),
                PG_GETARG_BOOL(8),
                &result_tuples,
                &result_count);
        } else if (PG_NARGS() == 8) {
            process(
                text_to_cstring(PG_GETARG_TEXT_P(0)),
                text_to_cstring(PG_GETARG_TEXT_P(1)),
                text_to_cstring(PG_GETARG_TEXT_P(2)),
                NULL, NULL,
                NULL, NULL,
                PG_GETARG_INT32(3),
                text_to_cstring(PG_GETARG_TEXT_P(4)),
                PG_GETARG_BOOL(5),
                PG_GETARG_BOOL(6),
                PG_GETARG_BOOL(7),
                &result_tuples,
                &result_count);
        } else if (PG_NARGS() == 9) {
            /* this is for the old signature */
            int64_t departure = PG_GETARG_INT64(2);
            int64_t destination = PG_GETARG_INT64(3);
            process(
                    text_to_cstring(PG_GETARG_TEXT_P(0)),
                    text_to_cstring(PG_GETARG_TEXT_P(1)),
                    NULL,
                    NULL, NULL,
                    &departure,
                    &destination,
                    PG_GETARG_INT32(4),
                    text_to_cstring(PG_GETARG_TEXT_P(7)),
                    PG_GETARG_BOOL(5),
                    PG_GETARG_BOOL(6),
                    PG_GETARG_BOOL(8),
                    &result_tuples,
                    &result_count);
        }
        funcctx->max_calls = result_count;
        funcctx->user_fctx = result_tuples;
        if (get_call_result_type(fcinfo, NULL, &tuple_desc) != TYPEFUNC_COMPOSITE) {
            ereport(ERROR,
                    (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
                     errmsg("function returning record called in context "
                         "that cannot accept type record")));
        }
        funcctx->tuple_desc = tuple_desc;
        MemoryContextSwitchTo(oldcontext);
    }
    funcctx = SRF_PERCALL_SETUP();
    tuple_desc = funcctx->tuple_desc;
    result_tuples = (Path_rt*) funcctx->user_fctx;
    if (funcctx->call_cntr < funcctx->max_calls) {
        HeapTuple    tuple;
        Datum        result;
        Datum        *values;
        bool*        nulls;
        size_t n = (PG_NARGS() == 9)? 7 : 9;
        values = palloc(n * sizeof(Datum));
        nulls = palloc(n * sizeof(bool));
        size_t i;
        for (i = 0; i < n; ++i) {
            nulls[i] = false;
        }
        int64_t path_id = 1;
        if (funcctx->call_cntr != 0) {
            if (result_tuples[funcctx->call_cntr - 1].edge == -1) {
                path_id = result_tuples[funcctx->call_cntr - 1].start_id + 1;
            } else {
                path_id = result_tuples[funcctx->call_cntr - 1].start_id;
            }
        }
        int64_t seq = funcctx->call_cntr == 0?  1 : result_tuples[funcctx->call_cntr - 1].end_id;
        values[0] = Int32GetDatum((int32_t)funcctx->call_cntr + 1);
        values[1] = Int32GetDatum((int32_t)path_id);
        values[2] = Int32GetDatum((int32_t)seq);
        if (PG_NARGS() != 9) {
            values[3] = Int64GetDatum(result_tuples[funcctx->call_cntr].start_id);
            values[4] = Int64GetDatum(result_tuples[funcctx->call_cntr].end_id);
        }
        values[n - 4] = Int64GetDatum(result_tuples[funcctx->call_cntr].node);
        values[n - 3] = Int64GetDatum(result_tuples[funcctx->call_cntr].edge);
        values[n - 2] = Float8GetDatum(result_tuples[funcctx->call_cntr].cost);
        values[n - 1] = Float8GetDatum(result_tuples[funcctx->call_cntr].agg_cost);
        result_tuples[funcctx->call_cntr].start_id = path_id;
        result_tuples[funcctx->call_cntr].end_id = result_tuples[funcctx->call_cntr].edge < 0? 1 : seq + 1;
        tuple = heap_form_tuple(tuple_desc, values, nulls);
        result = HeapTupleGetDatum(tuple);
        SRF_RETURN_NEXT(funcctx, result);
    } else {
        SRF_RETURN_DONE(funcctx);
    }
}
References Path_rt::agg_cost, Path_rt::cost, Path_rt::edge, Path_rt::end_id, Path_rt::node, process(), and Path_rt::start_id.
_pgr_withpointsksp_v4()
PGDLLEXPORT Datum _pgr_withpointsksp_v4 (PG_FUNCTION_ARGS)
Definition at line 128 of file withPoints_ksp.c.
{
    FuncCallContext     *funcctx;
    TupleDesc            tuple_desc;
    Path_rt  *result_tuples = 0;
    size_t result_count = 0;
    if (SRF_IS_FIRSTCALL()) {
        MemoryContext   oldcontext;
        funcctx = SRF_FIRSTCALL_INIT();
        oldcontext = MemoryContextSwitchTo(funcctx->multi_call_memory_ctx);
        if (PG_NARGS() == 9) {
            process(
                text_to_cstring(PG_GETARG_TEXT_P(0)),
                text_to_cstring(PG_GETARG_TEXT_P(1)),
                NULL,
                PG_GETARG_ARRAYTYPE_P(2),
                PG_GETARG_ARRAYTYPE_P(3),
                NULL, NULL,
                PG_GETARG_INT32(4),
                text_to_cstring(PG_GETARG_TEXT_P(5)),
                PG_GETARG_BOOL(6),
                PG_GETARG_BOOL(7),
                PG_GETARG_BOOL(8),
                &result_tuples,
                &result_count);
        } else if (PG_NARGS() == 8) {
            process(
                text_to_cstring(PG_GETARG_TEXT_P(0)),
                text_to_cstring(PG_GETARG_TEXT_P(1)),
                text_to_cstring(PG_GETARG_TEXT_P(2)),
                NULL, NULL,
                NULL, NULL,
                PG_GETARG_INT32(3),
                text_to_cstring(PG_GETARG_TEXT_P(4)),
                PG_GETARG_BOOL(5),
                PG_GETARG_BOOL(6),
                PG_GETARG_BOOL(7),
                &result_tuples,
                &result_count);
        }
        funcctx->max_calls = result_count;
        funcctx->user_fctx = result_tuples;
        if (get_call_result_type(fcinfo, NULL, &tuple_desc) != TYPEFUNC_COMPOSITE) {
            ereport(ERROR,
                    (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
                     errmsg("function returning record called in context that cannot accept type record")));
        }
        funcctx->tuple_desc = tuple_desc;
        MemoryContextSwitchTo(oldcontext);
    }
    funcctx = SRF_PERCALL_SETUP();
    tuple_desc = funcctx->tuple_desc;
    result_tuples = (Path_rt*) funcctx->user_fctx;
    if (funcctx->call_cntr < funcctx->max_calls) {
        HeapTuple    tuple;
        Datum        result;
        Datum        *values;
        bool*        nulls;
        size_t n = 9;
        values = palloc(n * sizeof(Datum));
        nulls = palloc(n * sizeof(bool));
        size_t i;
        for (i = 0; i < n; ++i) {
            nulls[i] = false;
        }
        int64_t path_id = 1;
        if (funcctx->call_cntr != 0) {
            if (result_tuples[funcctx->call_cntr - 1].edge == -1) {
                path_id = result_tuples[funcctx->call_cntr - 1].start_id + 1;
            } else {
                path_id = result_tuples[funcctx->call_cntr - 1].start_id;
            }
        }
        int64_t seq = funcctx->call_cntr == 0?  1 : result_tuples[funcctx->call_cntr - 1].end_id;
        values[0] = Int32GetDatum((int32_t)funcctx->call_cntr + 1);
        values[1] = Int32GetDatum((int32_t)path_id);
        values[2] = Int32GetDatum((int32_t)seq);
        values[3] = Int64GetDatum(result_tuples[funcctx->call_cntr].start_id);
        values[4] = Int64GetDatum(result_tuples[funcctx->call_cntr].end_id);
        values[5] = Int64GetDatum(result_tuples[funcctx->call_cntr].node);
        values[6] = Int64GetDatum(result_tuples[funcctx->call_cntr].edge);
        values[7] = Float8GetDatum(result_tuples[funcctx->call_cntr].cost);
        values[8] = Float8GetDatum(result_tuples[funcctx->call_cntr].agg_cost);
        result_tuples[funcctx->call_cntr].start_id = path_id;
        result_tuples[funcctx->call_cntr].end_id = result_tuples[funcctx->call_cntr].edge < 0? 1 : seq + 1;
        tuple = heap_form_tuple(tuple_desc, values, nulls);
        result = HeapTupleGetDatum(tuple);
        SRF_RETURN_NEXT(funcctx, result);
    } else {
        SRF_RETURN_DONE(funcctx);
    }
}
References Path_rt::agg_cost, Path_rt::cost, Path_rt::edge, Path_rt::end_id, Path_rt::node, process(), and Path_rt::start_id.
PG_FUNCTION_INFO_V1() [1/2]
PG_FUNCTION_INFO_V1 (_pgr_withpointsksp)
PG_FUNCTION_INFO_V1() [2/2]
PG_FUNCTION_INFO_V1 (_pgr_withpointsksp_v4)
process()
static void process (char * edges_sql, char * points_sql, char * combinations_sql, ArrayType * starts, ArrayType * ends, int64_t * start_vid, int64_t * end_vid, int p_k, char * driving_side, bool directed, bool heap_paths, bool details, Path_rt ** result_tuples, size_t * result_count) static
Definition at line 47 of file withPoints_ksp.c.
{
    char d_side = estimate_drivingSide(driving_side[0]);
    if (d_side == ' ') {
        pgr_throw_error("Invalid value of 'driving side'", "Valid value are 'r', 'l', 'b'");
        return;
    }
    if (p_k < 0) {
        pgr_throw_error("Invalid value of 'K'", "Valid value are greater than 0");
    }
    size_t k = (size_t)p_k;
    pgr_SPI_connect();
    char* log_msg = NULL;
    char* notice_msg = NULL;
    char* err_msg = NULL;
    char *edges_of_points_query = NULL;
    char *edges_no_points_query = NULL;
    get_new_queries(
            edges_sql, points_sql,
            &edges_of_points_query,
            &edges_no_points_query);
    clock_t start_t = clock();
    pgr_do_withPointsKsp(
            edges_no_points_query,
            points_sql,
            edges_of_points_query,
            combinations_sql,
            starts, ends,
            start_vid, end_vid,
            k,
            directed,
            heap_paths,
            d_side,
            details,
            result_tuples,
            result_count,
            &log_msg,
            &notice_msg,
            &err_msg);
    time_msg(" processing withPointsKSP", start_t, clock());
    if (err_msg && (*result_tuples)) {
        pfree(*result_tuples);
        (*result_tuples) = NULL;
        (*result_count) = 0;
    }
    pgr_global_report(&log_msg, &notice_msg, &err_msg);
    pgr_SPI_finish();
}
References estimate_drivingSide(), get_new_queries(), pgr_do_withPointsKsp(), pgr_global_report(), pgr_SPI_connect(), pgr_SPI_finish(), pgr_throw_error(), and time_msg().
Referenced by _pgr_withpointsksp(), and _pgr_withpointsksp_v4().