PGROUTING: withPoints_driver.cpp File Reference
withPoints_driver.cpp File Reference
#include "drivers/withPoints/withPoints_driver.h"
#include <algorithm>
#include <sstream>
#include <deque>
#include <vector>
#include <cassert>
#include <limits>
#include "dijkstra/pgr_dijkstra.hpp"
#include "withPoints/pgr_withPoints.hpp"
#include "cpp_common/pgr_alloc.hpp"
#include "cpp_common/pgr_assert.h"
Functions
void do_pgr_withPoints (pgr_edge_t *edges, size_t total_edges, Point_on_edge_t *points_p, size_t total_points, pgr_edge_t *edges_of_points, size_t total_edges_of_points, pgr_combination_t *combinations, size_t total_combinations, int64_t *start_pidsArr, size_t size_start_pidsArr, int64_t *end_pidsArr, size_t size_end_pidsArr, char driving_side, bool details, bool directed, bool only_cost, bool normal, General_path_element_t **return_tuples, size_t *return_count, char **log_msg, char **notice_msg, char **err_msg)
template<class G >
std::deque< Path > pgr_dijkstra (G &graph, std::vector< pgr_combination_t > &combinations, std::vector< int64_t > sources, std::vector< int64_t > targets, bool only_cost, bool normal)
Function Documentation
do_pgr_withPoints()
void do_pgr_withPoints (pgr_edge_t * edges, size_t total_edges, Point_on_edge_t * points_p, size_t total_points, pgr_edge_t * edges_of_points, size_t total_edges_of_points, pgr_combination_t * combinations, size_t total_combinations, int64_t * start_pidsArr, size_t size_start_pidsArr, int64_t * end_pidsArr, size_t size_end_pidsArr, char driving_side, bool details, bool directed, bool only_cost, bool normal, General_path_element_t ** return_tuples, size_t * return_count, char ** log_msg, char ** notice_msg, char ** err_msg)
Definition at line 93 of file withPoints_driver.cpp.
{
     std::ostringstream log;
     std::ostringstream notice;
     std::ostringstream err;
     try {
         pgassert(!(*log_msg));
         pgassert(!(*notice_msg));
         pgassert(!(*err_msg));
         pgassert(!(*return_tuples));
         pgassert((*return_count) == 0);
         pgassert(edges || edges_of_points);
         pgrouting::Pg_points_graph pg_graph(
                 std::vector<Point_on_edge_t>(
                     points_p,
                     points_p + total_points),
                 std::vector< pgr_edge_t >(
                     edges_of_points,
                     edges_of_points + total_edges_of_points),
                 normal,
                 driving_side,
                 directed);
         if (pg_graph.has_error()) {
             log << pg_graph.get_log();
             err << pg_graph.get_error();
             *log_msg = pgr_msg(log.str().c_str());
             *err_msg = pgr_msg(err.str().c_str());
             return;
         }
         std::vector<pgr_combination_t>
                 combinations_vector(combinations, combinations + total_combinations);
         std::vector<int64_t>
             start_vertices(start_pidsArr, start_pidsArr + size_start_pidsArr);
         std::vector< int64_t >
             end_vertices(end_pidsArr, end_pidsArr + size_end_pidsArr);
         auto vertices(pgrouting::extract_vertices(edges, total_edges));
         vertices = pgrouting::extract_vertices(vertices, pg_graph.new_edges());
         graphType gType = directed? DIRECTED: UNDIRECTED;
         std::deque< Path > paths;
         if (directed) {
             log << "Working with directed Graph\n";
             pgrouting::DirectedGraph digraph(vertices, gType);
             digraph.insert_edges(edges, total_edges);
             digraph.insert_edges(pg_graph.new_edges());
             paths = pgr_dijkstra(
                     digraph,
                     combinations_vector,
                     start_vertices, end_vertices,
                     only_cost, normal);
         } else {
             log << "Working with Undirected Graph\n";
             pgrouting::UndirectedGraph undigraph(vertices, gType);
             undigraph.insert_edges(edges, total_edges);
             undigraph.insert_edges(pg_graph.new_edges());
             paths = pgr_dijkstra(
                     undigraph,
                     combinations_vector,
                     start_vertices, end_vertices,
                     only_cost, normal);
         }
         if (!details) {
             for (auto &path : paths) {
                 path = pg_graph.eliminate_details(path);
             }
         }
         /*
          * order paths based on the start_pid, end_pid
          */
         std::sort(paths.begin(), paths.end(),
                 [](const Path &a, const Path &b)
                 -> bool {
                 if (b.start_id() != a.start_id()) {
                 return a.start_id() < b.start_id();
                 }
                 return a.end_id() < b.end_id();
                 });
         size_t count(0);
         count = count_tuples(paths);
         if (count == 0) {
             (*return_tuples) = NULL;
             (*return_count) = 0;
             return;
         }
         (*return_tuples) = pgr_alloc(count, (*return_tuples));
         log << "Converting a set of paths into the tuples\n";
         (*return_count) = (collapse_paths(return_tuples, paths));
         log << "************************************************";
         log << pg_graph.get_log();
         log << "************************************************";
         *log_msg = log.str().empty()?
             *log_msg :
             pgr_msg(log.str().c_str());
         *notice_msg = notice.str().empty()?
             *notice_msg :
             pgr_msg(notice.str().c_str());
     } catch (AssertFailedException &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch (std::exception &except) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << except.what();
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     } catch(...) {
         (*return_tuples) = pgr_free(*return_tuples);
         (*return_count) = 0;
         err << "Caught unknown exception!";
         *err_msg = pgr_msg(err.str().c_str());
         *log_msg = pgr_msg(log.str().c_str());
     }
 }
References collapse_paths(), count_tuples(), DIRECTED, pgrouting::Pg_points_graph::eliminate_details(), Path::end_id(), pgrouting::extract_vertices(), pgrouting::Pgr_messages::get_error(), pgrouting::Pgr_messages::get_log(), pgrouting::Pgr_messages::has_error(), pgrouting::graph::Pgr_base_graph< G, T_V, T_E >::insert_edges(), pgrouting::Pg_points_graph::new_edges(), pgassert, pgr_alloc(), pgr_dijkstra(), pgr_msg(), and UNDIRECTED.
Referenced by process().
pgr_dijkstra()
template<class G > std::deque< Path > pgr_dijkstra (G & graph, std::vector< pgr_combination_t > & combinations, std::vector< int64_t > sources, std::vector< int64_t > targets, bool only_cost, bool normal)
Definition at line 48 of file withPoints_driver.cpp.
                      {
     std::sort(sources.begin(), sources.end());
     sources.erase(
             std::unique(sources.begin(), sources.end()),
             sources.end());
     std::sort(targets.begin(), targets.end());
     targets.erase(
             std::unique(targets.begin(), targets.end()),
             targets.end());
     pgrouting::Pgr_dijkstra< G > fn_dijkstra;
     size_t n_goals = (std::numeric_limits<size_t>::max)();
     auto paths = combinations.empty()?
         fn_dijkstra.dijkstra(graph, sources, targets, only_cost)
         : fn_dijkstra.dijkstra(graph, combinations, only_cost, n_goals);
     if (!normal) {
         for (auto &path : paths) {
             path.reverse();
         }
     }
     if (!only_cost) {
         for (auto &p : paths) {
             p.recalculate_agg_cost();
         }
     }
     return paths;
 }
References pgrouting::Pgr_dijkstra< G >::dijkstra(), and Path::reverse().
Referenced by do_pgr_withPoints(), and pgRouting::pgr_dijkstraVia().