PGROUTING: vehicles_input.c File Reference
vehicles_input.c File Reference
#include "./postgres_connection.h"
#include <limits.h>
#include "./debug_macro.h"
#include "./pgr_types.h"
#include "./get_check_data.h"
#include "./vehicles_input.h"
Functions
static void fetch_vehicles (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info[14], Vehicle_t *vehicle)
void pgr_get_vehicles (char *vehicles_sql, Vehicle_t **vehicles, size_t *total_vehicles)
Reads the vehicles orders.
Function Documentation
static void fetch_vehicles (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info[14], Vehicle_t * vehicle) static
Definition at line 36 of file vehicles_input.c.
References Vehicle_t::cant_v, Vehicle_t::capacity, column_found(), Vehicle_t::end_close_t, Vehicle_t::end_open_t, Vehicle_t::end_service_t, Vehicle_t::end_x, Vehicle_t::end_y, Vehicle_t::id, pgr_SPI_getBigInt(), pgr_SPI_getFloat8(), Vehicle_t::speed, Vehicle_t::start_close_t, Vehicle_t::start_open_t, Vehicle_t::start_service_t, Vehicle_t::start_x, and Vehicle_t::start_y.
Referenced by pgr_get_vehicles().
void pgr_get_vehicles (char * vehicles_sql, Vehicle_t ** vehicles, size_t * total_vehicles)
Reads the vehicles orders.
Parameters
[in] vehicles_sql
[in] default_capacity
[in] default_open_t
[in] default_close_t
[out] vehicles
[out] total_vehicles
Definition at line 83 of file vehicles_input.c.
References ANY_INTEGER, ANY_NUMERICAL, Column_info_t::colNumber, Column_info_t::eType, fetch_vehicles(), Column_info_t::name, PGR_DBG, pgr_fetch_column_info(), pgr_SPI_cursor_open(), pgr_SPI_prepare(), Column_info_t::strict, and Column_info_t::type.
Referenced by process().